linting, `setup-util` multiple clis and fallbacks
- `trunk.yaml`: this fixes whatever the formatting as that trunk complained about, so the `shfmt` disable exceptions are now removed
- `*`: adopt `__print_help` is more locations and fix linting issues
- `down`, `setup-util`: make use of a new `--archive-extract` option for when we want to denote the intention to unzip without any other unzip options
- `echo-json.ts` and `ts.ts`: lint and types fix
- `setup-python`: fix prior commit `PIPX_INSTALL` deprecation
- `setup-util`:
    - support multiple `--cli` and relevant download technique options, to support `setup-util-uv`
    - improve styling of messaging
    - improve performance of brew checks
    - remove `tea` as it is defunct
    - fix fallbacks not working, this regression may go back months if not longer
    - improve apt error messaging
    - consistent check conventions
- `setup-util-*`: rewrote conditional checks to not crash if a conditional source fails, but to just continue without that failed source
- `setup-util-csvlens`: fix changed and renamed source assets
- `setup-util-lux`: add more sources
- `setup-util-resilio`: use `https`
- `setup-uutil-uv`: support `uv` and `uvx` clis
- `unziptar`: better support and check `<archive-file>` option permutations
- `bash.bash`: add `__sort`, still needs tests
- `styles.bash`:
    - introduce `--help=` which calls `__print_help`, such that once can do help styling in arguments
    - add `* ` list conversion in addition to existing `- `

diff --git a/commands.beta/echo-if-directory b/commands.beta/echo-if-directory
--- a/commands.beta/echo-if-directory
+++ b/commands.beta/echo-if-directory
@@ -55,15 +55,16 @@ function echo_if_directory_test() (
 function echo_if_directory() (
 	source "$DOROTHY/sources/stdinargs.bash"
 
+	# trunk-ignore(shellcheck/SC2120)
 	function help {
-		cat <<-EOF >&2
+		__print_help "$@" <<-EOF || return
 			ABOUT:
 			Output <input>s that are a directory, or an unbroken symlink to a directory.
-			Companion to [is-directory].
+			Companion to \`is-directory\`.
 
 			USAGE:
-			echo-if-directory [...options] [--] ...<input>
-			echo-lines ...<input> | echo-if-directory [...options]
+			\`echo-if-directory [...options] [--] ...<input>\`
+			\`echo-lines ...<input> | echo-if-directory [...options]\`
 
 			OPTIONS:
 			--elevated=<elevated>
@@ -71,13 +72,13 @@ function echo_if_directory() (
 			--user=<user>
 			--group=<group>
 			--reason=<reason>
-			    Forwarded to [eval-helper].
+			    Forwarded to \`eval-helper\`
 
 			$(__stdinargs__help_options --)
 
 			EXAMPLES:
 
-			echo-if-directory -- "$HOME"
+			\`echo-if-directory -- "$HOME"
 
 			    $HOME
 			    # exit status: 0
@@ -85,11 +86,8 @@ function echo_if_directory() (
 			echo-lines -- "$HOME" | echo-if-directory --stdin
 
 			    $HOME
-			    # exit status: 0
+			    # exit status: 0\`
 		EOF
-		if [[ $# -ne 0 ]]; then
-			__print_error "$@"
-		fi
 		return 22 # EINVAL 22 Invalid argument
 	}
 
@@ -99,6 +97,7 @@ function echo_if_directory() (
 		item="$1"
 		shift
 		case "$item" in
+		# trunk-ignore(shellcheck/SC2119)
 		'--help' | '-h') help ;;
 		# <elevate>
 		'--elevated='*) option_elevated="${item#*=}" ;;
diff --git a/commands/echo-if-file b/commands/echo-if-file
--- a/commands/echo-if-file
+++ b/commands/echo-if-file
@@ -55,15 +55,16 @@ function echo_if_file_test() (
 function echo_if_file() (
 	source "$DOROTHY/sources/stdinargs.bash"
 
+	# trunk-ignore(shellcheck/SC2120)
 	function help {
-		cat <<-EOF >&2
+		__print_help "$@" <<-EOF || return
 			ABOUT:
 			Output <input>s that are a file, or an unbroken symlink to a file.
-			Companion to [is-file].
+			Companion to \`is-file\`.
 
 			USAGE:
-			echo-if-file [...options] [--] ...<input>
-			echo-lines ...<input> | echo-if-file [...options]
+			\`echo-if-file [...options] [--] ...<input>\`
+			\`echo-lines ...<input> | echo-if-file [...options]\`
 
 			OPTIONS:
 			--elevated=<elevated>
@@ -71,13 +72,13 @@ function echo_if_file() (
 			--user=<user>
 			--group=<group>
 			--reason=<reason>
-			    Forwarded to [is-file].
+			    Forwarded to \`is-file\`
 
 			$(__stdinargs__help_options --)
 
 			EXAMPLES:
 
-			echo-if-file -- "$DOROTHY/README.md"
+			\`echo-if-file -- "$DOROTHY/README.md"
 
 			    $DOROTHY/README.md
 			    # exit status: 0
@@ -85,7 +86,7 @@ function echo_if_file() (
 			echo-lines -- "$DOROTHY/README.md" | echo-if-file --stdin
 
 			    $DOROTHY/README.md
-			    # exit status: 0
+			    # exit status: 0\`
 		EOF
 		if [[ $# -ne 0 ]]; then
 			__print_error "$@"
@@ -99,6 +100,7 @@ function echo_if_file() (
 		item="$1"
 		shift
 		case "$item" in
+		# trunk-ignore(shellcheck/SC2119)
 		'--help' | '-h') help ;;
 		# <elevate>
 		'--elevated='*) option_elevated="${item#*=}" ;;
diff --git a/commands/echo-if-present b/commands/echo-if-present
--- a/commands/echo-if-present
+++ b/commands/echo-if-present
@@ -55,15 +55,16 @@ function echo_if_present_test() (
 function echo_if_present() (
 	source "$DOROTHY/sources/stdinargs.bash"
 
+	# trunk-ignore(shellcheck/SC2120)
 	function help {
-		cat <<-EOF >&2
+		__print_help "$@" <<-EOF || return
 			ABOUT:
 			Output <input>s that are paths that are present (including that of symlinks, broken or otherwise).
-			Companion to [is-missing], [is-present].
+			Companion to \`is-missing\`, \`is-present\`.
 
 			USAGE:
-			echo-if-present [...options] [--] ...<input>
-			echo-lines ...<input> | echo-if-present [...options]
+			\`echo-if-present [...options] [--] ...<input>\`
+			\`echo-lines ...<input> | echo-if-present [...options]\`
 
 			OPTIONS:
 			--elevated=<elevated>
@@ -71,13 +72,13 @@ function echo_if_present() (
 			--user=<user>
 			--group=<group>
 			--reason=<reason>
-			    Forwarded to [is-present].
+			    Forwarded to \`is-present\`
 
 			$(__stdinargs__help_options --)
 
 			EXAMPLES:
 
-			echo-if-present -- "$HOME"
+			\`echo-if-present -- "$HOME"
 
 			    $HOME
 			    # exit status: 0
@@ -85,11 +86,8 @@ function echo_if_present() (
 			echo-lines -- "$HOME" | echo-if-present --stdin
 
 			    $HOME
-			    # exit status: 0
+			    # exit status: 0\`
 		EOF
-		if [[ $# -ne 0 ]]; then
-			__print_error "$@"
-		fi
 		return 22 # EINVAL 22 Invalid argument
 	}
 
@@ -99,6 +97,7 @@ function echo_if_present() (
 		item="$1"
 		shift
 		case "$item" in
+		# trunk-ignore(shellcheck/SC2119)
 		'--help' | '-h') help ;;
 		# <elevate>
 		'--elevated='*) option_elevated="${item#*=}" ;;
diff --git a/commands/setup-mac-brew b/commands/setup-mac-brew
--- a/commands/setup-mac-brew
+++ b/commands/setup-mac-brew
@@ -396,10 +396,10 @@ function setup_mac_brew() (
 				for pkg in "$@"; do
 					if brew-installed --quiet -- "$pkg"; then
 						eval_helper --quiet --wrap \
-						--pending="$(__print_style --bold='Uninstalling: ' --code="$pkg")" \
-						--success="$(__print_style --success='Uninstalled: ' --code="$pkg")" \
-						--failure="$(__print_style --error='Failed to uninstall: ' --code="$pkg")" \
-						-- brew uninstall --quiet --ignore-dependencies "$pkg" || :
+							--pending="$(__print_style --bold='Uninstalling: ' --code="$pkg")" \
+							--success="$(__print_style --success='Uninstalled: ' --code="$pkg")" \
+							--failure="$(__print_style --error='Failed to uninstall: ' --code="$pkg")" \
+							-- brew uninstall --quiet --ignore-dependencies "$pkg" || :
 					fi
 				done
 				# cleanup, used to fix any breaks after the removals, this is only here are is purges upgrade caches, which is undesirable on unreliable internet connections as it means re-runs always has to download everything again
@@ -511,7 +511,7 @@ function setup_mac_brew() (
 	brew_tap "${HOMEBREW_TAPS[@]}"
 
 	# repositories
-	if [[ "${#HOMEBREW_TAPS[@]}" -ne 0 ]]; then
+	if [[ ${#HOMEBREW_TAPS[@]} -ne 0 ]]; then
 		local first_tap="${HOMEBREW_TAPS[0]}" first_tap_repo_path casks_repo_path repo_paths=()
 		first_tap_repo_path="$(brew --repo "$first_tap")"
 		casks_repo_path="$(fs-path --parents -- "$first_tap_repo_path")"
diff --git a/commands/setup-shell b/commands/setup-shell
--- a/commands/setup-shell
+++ b/commands/setup-shell
@@ -81,8 +81,8 @@ function setup_shell() (
 		'bash') command "$path" -c "printf '%s\n' \"\$BASH_VERSION\"" || return ;; # eval
 		'zsh') command "$path" -c "printf '%s\n' \"\$ZSH_VERSION\"" || return ;;   # eval
 		'fish') command "$path" -c "printf '%s\n' \"\$FISH_VERSION\"" || return ;; # eval
-		'nu') command "$path" -c "printf '%s\n' \$env.NU_VERSION"  || return ;;     # eval
-		'elvish') command "$path" --version  || return ;;                           # eval
+		'nu') command "$path" -c "printf '%s\n' \$env.NU_VERSION" || return ;;     # eval
+		'elvish') command "$path" --version || return ;;                           # eval
 		*) : ;;
 		# go on the safe side, any don't do versions for anything we can't guarantee handling of
 		#'dash' | 'ksh') : ;;  # these don't support [<shell> --version]
@@ -147,10 +147,10 @@ function setup_shell() (
 			# type -Pa "$basename_or_path" || : # suppress failure status if no results
 			local paths=() path
 			__split --target={paths} --no-zero-length --invoke=try \
-			-- 	type -Pa "$shell" || return
+				-- type -Pa "$shell" || return
 			if [[ ${#paths[@]} -ne 0 ]]; then
 				__split --target={paths} --no-zero-length --invoke \
-			-- 		__get_unique_and_permitted_shells "${paths[@]}" || return
+					-- __get_unique_and_permitted_shells "${paths[@]}" || return
 				all+=("${paths[@]}")
 			fi
 		done
@@ -301,7 +301,7 @@ function setup_shell() (
 					__print_error 'Updating the login shell failed because ' --code='chpass' ' was aborted with exit status ' --status="$__chpass_status" || return
 					return 125 # ECANCELED 125 Operation cancelled
 				else
-					__print_error 'Updating the login shell failed because ' --code='chpass' ' failed with exit status '  --status="$__chpass_status" || return
+					__print_error 'Updating the login shell failed because ' --code='chpass' ' failed with exit status ' --status="$__chpass_status" || return
 					return "$__chpass_status"
 				fi
 			done
@@ -663,7 +663,7 @@ function setup_shell() (
 			-- __get_unique_and_permitted_installed_shells "${all_installable_basenames_of_shells[@]}" || return
 		if [[ ${#option_shells[@]} -ne 0 ]]; then
 			__split --target={user_shells} --no-zero-length --invoke \
-			-- 	__get_unique_and_permitted_basenames_of_shells "${option_shells[@]}" || return
+				-- __get_unique_and_permitted_basenames_of_shells "${option_shells[@]}" || return
 		fi
 		if [[ ${#user_shells[@]} -ne 0 && ${#installed_shells[@]} -ne 0 ]]; then
 			defaults=("${user_shells[@]}" "${installed_shells[@]}")
@@ -751,10 +751,10 @@ function setup_shell() (
 		# handle defaults
 		local configured_shells=() user_shells=() defaults=() defaults_string=''
 		__split --target={configured_shells} --no-zero-length --invoke \
-			-- 	__get_unique_and_permitted_configured_basenames_of_shells "${all_configurable_basenames_of_shells[@]}" || return
+			-- __get_unique_and_permitted_configured_basenames_of_shells "${all_configurable_basenames_of_shells[@]}" || return
 		if [[ ${#option_shells[@]} -ne 0 ]]; then
 			__split --target={user_shells} --no-zero-length --invoke \
-			-- 	__get_unique_and_permitted_basenames_of_shells "${option_shells[@]}" || return
+				-- __get_unique_and_permitted_basenames_of_shells "${option_shells[@]}" || return
 		fi
 		if [[ ${#user_shells[@]} -ne 0 && ${#configured_shells[@]} -ne 0 ]]; then
 			defaults=("${user_shells[@]}" "${configured_shells[@]}")
@@ -791,7 +791,7 @@ function setup_shell() (
 		if [[ $option_clean == 'yes' ]]; then
 			# note that for WSL, they include useful configurations that Dorothy does reimplement
 			fs-remove --confirm --no-confirm-if-empty --reason='Once you have migrated all your configuration to Dorothy, these files can usually be safely removed.' \
-			-- 	"$HOME/.profile" "$HOME/.bash_profile" "$HOME/.bashrc" "$XDG_CONFIG_HOME/fish/config.fish" "$ZDOTDIR/.zshrc" "$ZDOTDIR/.zprofile" || return
+				-- "$HOME/.profile" "$HOME/.bash_profile" "$HOME/.bashrc" "$XDG_CONFIG_HOME/fish/config.fish" "$ZDOTDIR/.zshrc" "$ZDOTDIR/.zprofile" || return
 		fi
 
 		# configure or deconfigure
@@ -820,7 +820,7 @@ function setup_shell() (
 		local allowed_shells=() user_shells=() configured_shells=() installed_shells=() # apply choices, defaults, and details to caller
 		if [[ ${#option_shells[@]} -ne 0 ]]; then
 			__split --target={user_shells} --no-zero-length --invoke \
-			-- 	__get_unique_and_permitted_paths_of_shells "${option_shells[@]}" || return
+				-- __get_unique_and_permitted_paths_of_shells "${option_shells[@]}" || return
 			choices+=("${user_shells[@]}")
 		fi
 		__split --target={allowed_shells} --no-zero-length --invoke \
@@ -833,7 +833,7 @@ function setup_shell() (
 			-- __get_unique_and_permitted_installed_shells "${all_allowable_basenames_of_shells[@]}" || return
 		if [[ ${#installed_shells[@]} -ne 0 ]]; then
 			__split --target={installed_shells} --no-zero-length --invoke \
-			-- 	__get_unique_and_permitted_paths_of_shells "${installed_shells[@]}" || return
+				-- __get_unique_and_permitted_paths_of_shells "${installed_shells[@]}" || return
 			choices+=("${installed_shells[@]}")
 		fi
 		if [[ ${#user_shells[@]} -ne 0 && ${#allowed_shells[@]} -ne 0 ]]; then
@@ -874,7 +874,7 @@ function setup_shell() (
 			if [[ $option_disallow == 'yes' || $option_allow == 'yes' ]]; then
 				local arg_shells=() shell
 				__split --target={arg_shells} --no-zero-length --invoke \
-			-- 		__get_unique_and_permitted_paths_of_shells "${option_shells[@]}" || return
+					-- __get_unique_and_permitted_paths_of_shells "${option_shells[@]}" || return
 				for shell in "${arg_shells[@]}"; do
 					if [[ $option_disallow == 'yes' ]]; then
 						__disallow_login_shell_path "$shell" || return
@@ -892,7 +892,7 @@ function setup_shell() (
 		question='Which shells to allow as system login shells?'
 		details='Shells that are enabled to run as system login shells can be used by your system upon login to configure your environment, as well as by your terminal emulator as your default shell.'
 		details+=$'\nYour selection will be allowed as a system login shell. Unselected shells will be disallowed as system login shells. Your password may be required to apply the changes.'
-		__get_login_choices_defaults_details  || return # apply choices, defaults, defaults_string, and details
+		__get_login_choices_defaults_details || return # apply choices, defaults, defaults_string, and details
 
 		# select which shells to allow and consequently which to also disallow
 		local choices_with_labels=() selected_shells=() result=''
