`__tool`, `__require_command`, `__print_style`
- continue performance improvements
- simplify some common patterns
- add `__affirm_function_is_defined`
- leftover `echo-style` now `__print_style`
- more `|| return` usage
- convert `is-fs.bash` and its callers to safety functions for eventual bash 4.3 compat

diff --git a/commands.beta/eject-all b/commands.beta/eject-all
--- a/commands.beta/eject-all
+++ b/commands.beta/eject-all
@@ -6,8 +6,8 @@ function eject_all() (
 	# =====================================
 	# Arguments
 
-	function help {
-		cat <<-EOF >&2
+	function __help {
+		cat <<-EOF >&2 || return
 			ABOUT:
 			Eject all the ejectable drives attached to the system.
 
@@ -15,7 +15,7 @@ function eject_all() (
 			eject-all
 		EOF
 		if [[ $# -ne 0 ]]; then
-			__print_error "$@"
+			__print_error "$@" || return
 		fi
 		return 22 # EINVAL 22 Invalid argument
 	}
@@ -26,32 +26,32 @@ function eject_all() (
 		item="$1"
 		shift
 		case "$item" in
-		'--help' | '-h') help ;;
-		'--'*) help "An unrecognised flag was provided: $item" ;;
-		*) help "An unrecognised argument was provided: $item" ;;
+		'--help' | '-h') __help || return ;;
+		'--'*) __help "An unrecognised flag was provided: $item" || return ;;
+		*) __help "An unrecognised argument was provided: $item" || return ;;
 		esac
 	done
 
 	# =====================================
 	# Action
 
-	echo-style --h1='eject-all'
+	__print_style --h1='eject-all' || return
 
-	echo-style --h2='before'
-	fs-structure -- /Volumes
-	echo-style --g2='before'
+	__print_style --h2='before' || return
+	fs-structure -- /Volumes || return
+	__print_style --g2='before' || return
 
 	eval-helper --quiet --no-wrap \
-		--pending="$(echo-style --bold='Ejecting...')" \
-		--success="$(echo-style --success='Ejected.')" \
-		--failure="$(echo-style --error='Failed to eject.')" -- \
-		osascript -e 'tell application "Finder" to eject (every disk whose ejectable is true)'
+		--pending="$(__print_style --bold='Ejecting...')" \
+		--success="$(__print_style --success='Ejected.')" \
+		--failure="$(__print_style --error='Failed to eject.')" -- \
+		osascript -e 'tell application "Finder" to eject (every disk whose ejectable is true)' || return
 
-	echo-style --h2='after'
-	fs-structure -- /Volumes
-	echo-style --g2='after'
+	__print_style --h2='after' || return
+	fs-structure -- /Volumes || return
+	__print_style --g2='after' || return
 
-	echo-style --h1='eject-all'
+	__print_style --h1='eject-all' || return
 )
 
 # fire if invoked standalone
diff --git a/commands.beta/twitter-helper b/commands.beta/twitter-helper
--- a/commands.beta/twitter-helper
+++ b/commands.beta/twitter-helper
@@ -69,7 +69,7 @@ function twitter_helper() (
 	# =====================================
 	# Dependencies
 
-	setup-util-jq --quiet
+	__command_required -- 'jq' || return
 	setup-util --quiet --cli=twurl GEM='twurl'
 
 	if ruby --version | grep --quiet --extended-regexp --regexp='^ruby 3'; then
@@ -123,9 +123,9 @@ function twitter_helper() (
 			# https://developer.twitter.com/en/docs/labs/tweets-and-users/api-reference
 			local tweet_id="$1"
 			eval_collapse \
-				--pending="$(echo-style --bold="Deleting tweet $tweet_id...")" \
-				--success="$(echo-style --success="Deleted tweet $tweet_id")" \
-				--failure="$(echo-style --error="Failed to delete tweet $tweet_id")" -- \
+				--pending="$(__print_style --bold="Deleting tweet $tweet_id...")" \
+				--success="$(__print_style --success="Deleted tweet $tweet_id")" \
+				--failure="$(__print_style --error="Failed to delete tweet $tweet_id")" -- \
 				twurl -X POST "/1.1/statuses/destroy/$tweet_id.json"
 		}
 		stdinargs "$@"
@@ -136,9 +136,9 @@ function twitter_helper() (
 			# https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/mute-block-report-users/api-reference/post-blocks-create
 			local user_id="$1"
 			eval_collapse \
-				--pending="$(echo-style --bold="Blocking user $user_id...")" \
-				--success="$(echo-style --success="Blocked user $user_id")" \
-				--failure="$(echo-style --error="Failed to block user $user_id")" -- \
+				--pending="$(__print_style --bold="Blocking user $user_id...")" \
+				--success="$(__print_style --success="Blocked user $user_id")" \
+				--failure="$(__print_style --error="Failed to block user $user_id")" -- \
 				twurl -d "screen_name=$1" '/1.1/blocks/create.json'
 		}
 		stdinargs "$@"
@@ -148,9 +148,9 @@ function twitter_helper() (
 		function on_piece {
 			local user_id="$1"
 			eval_collapse \
-				--pending="$(echo-style --bold="Muting user $user_id...")" \
-				--success="$(echo-style --success="Muted user $user_id")" \
-				--failure="$(echo-style --error="Failed to mute user $user_id")" -- \
+				--pending="$(__print_style --bold="Muting user $user_id...")" \
+				--success="$(__print_style --success="Muted user $user_id")" \
+				--failure="$(__print_style --error="Failed to mute user $user_id")" -- \
 				twurl -d "screen_name=$user_id" '/1.1/mutes/users/create.json'
 		}
 		stdinargs "$@"
diff --git a/commands/get-installer b/commands/get-installer
--- a/commands/get-installer
+++ b/commands/get-installer
@@ -75,13 +75,13 @@ function get_installer() (
 	# Configuration
 
 	# dependencies
-	setup-util-jq --quiet
+	__command_required -- 'jq' || return
 
 	# load aliases
 	local database="$DOROTHY/config/installers.json" aliases=() installers=() alias installer
 	while IFS=$'\t' read -r alias installer; do
 		if [[ -z $alias || -z $installer ]]; then
-			echo-style --stderr --code="$alias" ' => ' --code="$installer" ' ❌ ' --error='invalid database entry'
+			__print_style --stderr --code="$alias" ' => ' --code="$installer" ' ❌ ' --error='invalid database entry'
 			continue
 		fi
 		aliases+=("$alias")
@@ -94,7 +94,7 @@ function get_installer() (
 	# testing
 	if [[ $option_verify == 'yes' ]]; then
 		# test that the installers for the aliases actually exist
-		# queue the log entries into echo-style to output all at once, as it turns it from like a minute into a second
+		# queue the log entries to output all at once, as it turns it from like a minute into a second
 		local index result=0 logs=()
 		for index in "${!aliases[@]}"; do
 			alias="${aliases[index]}"
@@ -110,7 +110,7 @@ function get_installer() (
 			fi
 		done
 		if [[ ${#logs[@]} -ne 0 ]]; then
-			echo-style --no-trail --stderr "${logs[@]}"
+			__print_style --no-trail --stderr "${logs[@]}"
 		fi
 
 		# sort all keys in the installers.json configuration file
@@ -146,31 +146,29 @@ function get_installer() (
 			# -[^ ]+ matches a dash followed by one or more non-space characters
 			# so this is what converts the `--classic` flag into ``
 			# then we trim whitespace at the start and end
-			util="$(echo-regexp -g '(^| )-[^ ]+' '' -- "$util" | echo-trim-each-line --stdin)"
+			util="$(echo-regexp -g '(^| )-[^ ]+' '' -- "$util" | echo-trim-each-line --stdin)" || return
 		fi
 		# done
-		__print_lines "$util"
-		return
+		__print_lines "$util" || return
 	}
 
 	function __get_installer {
 		local alias="$1" index
 		for index in "${!aliases[@]}"; do
 			if [[ $alias == "${aliases[index]}" ]]; then
-				__print_lines "${installers[index]}"
-				return
+				__print_lines "${installers[index]}" || return
+				return 0
 			fi
 		done
 		# alias not found, check if it exists normally
-		echo-if-command-exists -- "setup-util-$alias"
-		return
+		echo-if-command-exists -- "setup-util-$alias" || return
 	}
 
 	# handle each utility
 	local util alias installer any_failure='no'
 	for util in "${option_utils[@]}"; do
 		# get the alias
-		alias="$(__get_alias "$util")"
+		alias="$(__get_alias "$util")" || return
 		if [[ -z $alias ]]; then
 			continue
 		fi
@@ -180,13 +178,13 @@ function get_installer() (
 		if [[ -z $installer ]]; then
 			any_failure='yes'
 			if [[ $option_quiet != 'yes' ]]; then
-				echo-style --stderr --notice1='No installer found for: ' --code-notice1="$util"
+				__print_style --stderr --notice1='No installer found for: ' --code-notice1="$util" || return
 			fi
 			if [[ $option_first_failure == 'yes' ]]; then
 				return 1
 			fi
 		elif [[ $option_invoke == 'no' ]]; then
-			__print_lines "$installer"
+			__print_lines "$installer" || return
 			if [[ $option_first_success == 'yes' ]]; then
 				return 0
 			fi
