huge WIP commit
- new `__do` and `__try`, instead of `eval_capture`
    - better coverage and tests, see `dorothy-internals`
    - more powerful API
- new `is-fs` helpers
- new `echo-wait` (maybe should rename to `echo-write`)
    - no longer needs sponge
    - more powerful API
    - moreutils as such is no longer a dorothy recommended dep
- auto-sudo escalation on nearly everything
    - new sudo/elevate/elevated args
- use FDs instead of device files where sensible to avoid linux divergence from macos
- ... todo

diff --git a/commands.beta/ensure-trailing-slash b/commands.beta/ensure-trailing-slash
--- a/commands.beta/ensure-trailing-slash
+++ b/commands.beta/ensure-trailing-slash
@@ -7,7 +7,7 @@ function ensure_trailing_slash() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Ensure directories have a trailing newline.
 			Ensure files do not have a trailing newline.
@@ -62,7 +62,7 @@ function ensure_trailing_slash() (
 				__print_lines "$path"
 			fi
 		else
-			echo-style --error1='Not a file nor directory: ' --code-error1="$path" >/dev/stderr
+			echo-style --stderr --error1='Not a file nor directory: ' --code-error1="$path"
 			return 1
 		fi
 	done
diff --git a/commands/command-working b/commands/command-working
--- a/commands/command-working
+++ b/commands/command-working
@@ -4,10 +4,10 @@ function command_working_test() (
 	source "$DOROTHY/sources/bash.bash"
 	echo-style --h1="TEST: $0"
 
-	eval-tester --status=3 --stderr="< 'this-is-a-non-existent-command' />[3] not working because it is missing" \
+	eval-tester --status=3 --stderr="< this-is-a-non-existent-command />[3] not working because it is missing" \
 		-- env COLOR=no command-working -- this-is-a-non-existent-command
 
-	eval-tester --status=3 --stderr="< 'this-is-a-non-existent-command' />[3] not working because it is missing" \
+	eval-tester --status=3 --stderr="< this-is-a-non-existent-command />[3] not working because it is missing" \
 		-- env COLOR=no command-working -- this-is-a-non-existent-command command-missing
 
 	eval-tester \
@@ -26,7 +26,7 @@ function command_working() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Check if <command>s are available and working.
 			Working check is done via [<command> --help] and [<command> --version] checks.
@@ -97,26 +97,28 @@ function command_working() (
 		trash
 		trunk
 	)
-	function check_status {
+	function __check_status {
 		local cmd=() cmd_string cmd_exit_status cmd_output
 		# ensure sbin commands work
 		if [[ $* == *sbin* || $option_sudo == 'yes' ]]; then
 			cmd+=(
-				'sudo-helper'
-				'--reason=Your sudo/root/login password is required to verify this command is available and working:'
-				'--'
+				sudo-helper
+				--reason='Your password is required to momentarily grant privileges to validate that this command is available and working:'
+				--
 			)
 		fi
 		# continue with the command
 		cmd+=("$@")
 		# run the command hiding the output
-		eval_capture --statusvar=cmd_exit_status --outputvar=cmd_output -- "${cmd[@]}"
+		__do --redirect-status={cmd_exit_status} --redirect-output={cmd_output} -- command "${cmd[@]}" # eval
+		__return $? || return
 		# check for correct failure codes
 		if [[ $cmd_exit_status -eq 22 || $cmd_exit_status -eq 200 ]]; then
 			return 0
 		else
 			# otherwise return success or failure code
 			cmd_string="$(echo-escape-command -- "${cmd[@]}")"
+			__return $? || return
 			if [[ -n $cmd_output ]]; then
 				cmd_output+=$'\n'
 			fi
@@ -126,17 +128,18 @@ function command_working() (
 			return "$cmd_exit_status"
 		fi
 	}
-	function check_working {
+	function __check_working {
 		# reset debug
 		failures=()
 
 		# check it exists first
 		local cmd cmd_string
 		cmd_string="$(echo-escape-command -- "$1")"
+		__return $? || return
 		cmd="$(type -P "$1" 2>/dev/null || :)"
 		if [[ -z $cmd ]]; then
 			# we must at least find it
-			echo-style --element/+red="$cmd_string" --status=3 ' ' --error='not working because it is missing' >/dev/stderr
+			echo-style --stderr --element/+red="$cmd_string" --status=3 ' ' --error='not working because it is missing' || return
 			return 3 # ESRCH 3 No such process
 		fi
 
@@ -149,30 +152,25 @@ function command_working() (
 		done
 
 		# it does exist, now check its return code
-		check_status "$cmd" --version ||
-			check_status "$cmd" version ||
-			check_status "$cmd" --help ||
-			check_status "$cmd" -h || {
+		__check_status "$cmd" --version ||
+			__check_status "$cmd" version ||
+			__check_status "$cmd" --help ||
+			__check_status "$cmd" -h ||
 			{
-				echo-style --element+red="$cmd_string"
-				__print_lines "${failures[@]}"
-				echo-style --/element+red="$cmd_string" --status=1 ' ' --error='not working because it is failing'
-			} >/dev/stderr
-			return 1 # command not working
-		}
+				echo-style --stderr \
+					--element+red="$cmd_string" --newline \
+					--="$(__print_lines "${failures[@]}")" --newline \
+					--/element+red="$cmd_string" --status=1 ' ' --error='not working because it is failing' || return
+				return 1 # command not working
+			}
 	}
 
 	# =====================================
 	# Action
 
-	local command action_exit_status
+	local command
 	for command in "${option_commands[@]}"; do
-		eval_capture --statusvar=action_exit_status -- check_working "$command"
-		if [[ $action_exit_status -eq 0 ]]; then
-			continue
-		else
-			return "$action_exit_status"
-		fi
+		__check_working "$command" || return
 	done
 	return 0 # all commands are working
 )
diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -25,7 +25,7 @@ function dorothy_() (
 	# sanity check that we are running in bash
 	# sanity check, as [function .. () (], [elif], [&>], [local] are all bashisms, so other shells should have failed by now
 	if [[ -z ${BASH_VERSION-} ]]; then
-		printf '%s\n' "Dorothy requires bash to run. Refer to the installation instructions: $dorothy_install" >/dev/stderr
+		printf '%s\n' "Dorothy requires bash to run. Refer to the installation instructions: $dorothy_install" >&2
 		exit 6 # ENXIO 6 Device not configured
 	fi
 
@@ -80,7 +80,7 @@ function dorothy_() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Helpers for interacting with the Dorothy dotfile ecosystem.
 
@@ -199,7 +199,7 @@ function dorothy_() (
 		EOF
 		if [[ $# -ne 0 ]]; then
 			# use printf, as __print_line not loaded yet
-			printf '%s' "ERROR: $*" >/dev/stderr
+			printf '%s' "ERROR: $*" >&2
 		fi
 		return 22 # EINVAL 22 Invalid argument
 	}
@@ -429,7 +429,7 @@ function dorothy_() (
 				fish -c 'builtin realpath "$argv[1]"' -- "$path"
 				return
 			else
-				__print_lines "Dorothy requires GNU readlink or realpath to be installed. $dorothy_install" >/dev/stderr
+				__print_lines "Dorothy requires GNU readlink or realpath to be installed. $dorothy_install" >&2
 				return 6 # ENXIO 6 Device not configured
 			fi
 		done
@@ -557,42 +557,41 @@ function dorothy_() (
 			if __command_exists -- apt-get; then
 				# for ubuntu/debian/kali
 				# E: Unable to locate package ncurses
-				__try_sudo apt-get install -y bash curl git coreutils moreutils gawk
+				__try_sudo apt-get install -y bash curl git coreutils gawk
 			elif __command_exists -- zypper; then
 				# for opensuse
-				__try_sudo zypper --non-interactive install bash curl git-core coreutils moreutils gawk
+				__try_sudo zypper --non-interactive install bash curl git-core coreutils gawk
 			elif __command_exists -- apk; then
 				# for alpine
-				__try_sudo apk add bash curl grep git coreutils moreutils gawk
+				__try_sudo apk add bash curl grep git coreutils gawk
 			elif __command_exists -- pamac; then
 				# for manjaro that has pamac installed
-				__try_sudo pamac install --no-confirm bash curl git coreutils moreutils gawk
+				__try_sudo pamac install --no-confirm bash curl git coreutils gawk
 			elif __command_exists -- pacman; then
 				# for manjaro and arch
-				__try_sudo pacman --noconfirm --refresh --sync --needed bash curl git coreutils moreutils gawk
+				__try_sudo pacman --noconfirm --refresh --sync --needed bash curl git coreutils gawk
 			elif __command_exists -- urpmi; then
 				# for mageia, prefer over fedora as mageia contains dnf
-				# No package named moreutils
 				__try_sudo urpmi --auto bash curl git gawk
 			elif __command_exists -- dnf; then
 				# for fedora
-				__try_sudo dnf install --assumeyes --refresh --best --allowerasing bash curl git coreutils moreutils gawk
+				__try_sudo dnf install --assumeyes --refresh --best --allowerasing bash curl git coreutils gawk
 			elif [[ -n ${HOMEBREW_PREFIX-} && -x "$HOMEBREW_PREFIX/bin/brew" ]]; then
 				# this is here for consistency only, as it is unnecessary, all the commands already exist on macos without any need for homebrew
-				"$HOMEBREW_PREFIX/bin/brew" install bash curl git coreutils moreutils gawk
+				"$HOMEBREW_PREFIX/bin/brew" install bash curl git coreutils gawk
 			elif __command_exists -- xbps-install; then
 				# for void
-				__try_sudo xbps-install --sync --yes bash curl git coreutils moreutils gawk
+				__try_sudo xbps-install --sync --yes bash curl git coreutils gawk
 			elif __command_exists -- nix-env; then
 				# for nix
-				__try_sudo nix-env --install --attr nixpkgs.bash nixpkgs.curl nixpkgs.git nixpkgs.coreutils nixpkgs.moreutils nixpkgs.gawk
+				__try_sudo nix-env --install --attr nixpkgs.bash nixpkgs.curl nixpkgs.git nixpkgs.coreutils nixpkgs.gawk
 			elif __command_exists -- emerge; then
 				# for gentoo
-				__try_sudo emerge app-shells/bash net-misc/curl dev-vcs/git sys-apps/coreutils sys-apps/moreutils sys-apps/gawk
+				__try_sudo emerge app-shells/bash net-misc/curl dev-vcs/git sys-apps/coreutils sys-apps/gawk
 			else
 				# for everything else
 				# @todo style with var_dump or something
-				cat <<-EOF >/dev/stderr
+				cat <<-EOF >&2
 					One of these installation dependencies are missing:
 					bash:  $(bash --version | head -1 || :)
 					curl:  $(curl --version | head -1 || :)
@@ -627,7 +626,7 @@ function dorothy_() (
 		if __is_mac; then
 			setup-util-apple-rosetta --quiet
 			setup-util-apple-cli-tools --quiet
-			source "$DOROTHY/sources/environment.sh"
+			# environment invalidation and reloading now happens automatically via signals
 		fi
 
 		# upgrade bash if necessary
@@ -680,6 +679,8 @@ function dorothy_() (
 			return 2 # ENOENT 2 No such file or directory
 		fi
 		# no need to source bash.bash here, as we did it earlier via source and curl
+
+		# prepare environment for invalidations
 		source "$DOROTHY/sources/environment.sh"
 
 		# ensure state exists
@@ -1267,7 +1268,7 @@ function dorothy_() (
 	}
 
 	function adjust_user_configuration {
-		local file who name url header content
+		local file who name url header
 
 		# create essential directories
 		__mkdirp \
@@ -1297,10 +1298,11 @@ function dorothy_() (
 				EOF
 			)"
 			if [[ ! -f $file ]]; then
+				# file doesn't exist, so just add the header to the file
 				__print_lines "$header" >"$file"
 			else
-				content="$(cat -- "$file")"
-				printf '%s\n\n%s' "$header" "$content" >"$file"
+				# add the header to the start of the file
+				printf '%s\n\n%s' "$header" "$(<"$file")" >"$file"
 			fi
 		fi
 
@@ -1492,11 +1494,11 @@ function dorothy_() (
 			ensure_dorothy_configured
 			assert_dorothy_configured
 			ensure_minimal_dependencies
-		} >/dev/stderr # don't conflate stdout, don't use /dev/tty as tty doesn't exist on CI
+		} >&2 # don't pollute stdout, don't use /dev/tty as tty doesn't exist on CI
 
 		# now that our environment is setup, run the command
 		export DOROTHY_RUN=yes
-		command "${args[@]}" # eval builtins and commands, but not functions
+		command "${args[@]}" # eval
 		return
 	}
 
@@ -1742,15 +1744,21 @@ function dorothy_() (
 			fi
 		fi
 
-		# check for unsafe function calls, by checking for __ convention
+		# check for unsafe function calls, by checking for missing __* safety convention
 		# ((if|[&][&]|[|][|]|[!])\s)[a-z]+_[a-z_]+
 		# \s[a-z]+_[a-z_]+( ([&][&]|[|][|]))
 		# @todo improve upon this by checking if the function also calls function, as any calling of a function must also be safe
+		# Unfortunately, it seems [^=] does not work in ((if|[&][&]|[|][|]|[!])\s)[a-z]+_[a-z_]+[^=]
+		# To avoid matching: OR a_var=$?
+		# So for now, just modify the var names even though it is unnecessary.
 		local unsafe_regexp='((if|[&][&]|[|][|]|[!])\s)[a-z]+_[a-z_]+|\s[a-z]+_[a-z_]+( ([&][&]|[|][|]))' unsafe_contents='' unsafe_bundle='' unsafe_count=0
 		mapfile -t commands < <(rg --files-with-matches --sortr modified --regexp="$unsafe_regexp" "${scan_paths[@]}")
 		if [[ ${#commands[@]} -ne 0 ]]; then
 			for filepath in "${commands[@]}"; do
-				unsafe_contents="$(rg --regexp="$unsafe_regexp" "$filepath" | grep --invert-match --fixed-strings --regexp='for ' || :)"
+				if [[ $filepath == "$DOROTHY/commands/dorothy-internals" ]]; then
+					continue
+				fi
+				unsafe_contents="$(rg --color always --regexp="$unsafe_regexp" "$filepath" | grep --invert-match --fixed-strings --regexp='for ' || :)"
 				if [[ -z $unsafe_contents ]]; then
 					continue
 				fi
@@ -1846,14 +1854,20 @@ function dorothy_() (
 		source "$DOROTHY/sources/ripgrep.bash"
 
 		# before we begin, trim the bash.bash:eval_capture cache, and our own cache
-		export DEBUG=yes DEBUG_TTY="$XDG_CACHE_HOME/dorothy/debug-tty"
+		export DEBUG=yes DEBUG_TARGET="$XDG_CACHE_HOME/dorothy-debug.log"
 		__mkdirp "$XDG_CACHE_HOME/dorothy"
-		rm -rf -- "$XDG_CACHE_HOME/dorothy/eval-capture" "$XDG_CACHE_HOME/dorothy/debug-tty"
+		rm -rf -- "$XDG_CACHE_HOME/dorothy-try" "$DEBUG_TARGET"
 
 		# on CI set the modification times to reflect those from the git repository, rather than from clone
 		if is-ci; then
 			git-helper --path="$DOROTHY" umt
 		fi
+
+		# can't figure out how to sort array values
+		# # sort all array values in the cspell.json configuration file
+		# if __command_exists -- jq; then
+		# 	# jq --sort-keys . "$DOROTHY/cspell.json" | echo-wait --atomic -- "$DOROTHY/cspell.json"
+		# fi
 
 		# run relevant debugs
 		# __print_lines '' 'debug-terminal-stdin:'
@@ -1944,13 +1958,13 @@ function dorothy_() (
 		fi
 
 		# check for eval-capture failed cleaning
-		if ! is-empty-directory -- "$XDG_CACHE_HOME/dorothy/eval-capture"; then
-			failures+=($'bash.bash:eval_capture had leftovers: \n'"$(fs-structure -- "$XDG_CACHE_HOME/dorothy/eval-capture")")
+		if is-nonempty-directory -- "$XDG_CACHE_HOME/dorothy-try"; then
+			failures+=($'bash.bash:__try had leftovers: \n'"$(fs-structure -- "$XDG_CACHE_HOME/dorothy-try")")
 		fi
 
 		# check for debug lines
-		if [[ -n ${DEBUG_TTY-} && -f $DEBUG_TTY ]]; then
-			failures+=($'bash.bash:__debug_lines had output: \n'"$(echo-file -- "$DEBUG_TTY")")
+		if [[ -n ${DEBUG_TARGET-} && -f $DEBUG_TARGET ]]; then
+			failures+=($'bash.bash:__debug_lines had output: \n'"$(echo-file -- "$DEBUG_TARGET")")
 		fi
 
 		# check for warnings
@@ -2082,12 +2096,12 @@ function dorothy_() (
 	# Act
 
 	# ensure the prerequisites are installed in case the user skipped them
-	ensure_prereq_dependencies >/dev/stderr # don't conflate stdout, don't use /dev/tty as tty doesn't exist on CI
+	ensure_prereq_dependencies >&2 # don't pollute stdout, don't use /dev/tty as tty doesn't exist on CI
 
 	# all helpers are defined, and argument overrides are handled
 	# so prepare the local environment context with what is necessary for dorothy
 	# such that the following [choose] will be found
-	prepare_dorothy >/dev/stderr # don't conflate stdout, don't use /dev/tty as tty doesn't exist on CI
+	prepare_dorothy >&2 # don't pollute stdout, don't use /dev/tty as tty doesn't exist on CI
 
 	if [[ "$(type -t "act_$action")" == 'function' ]]; then
 		if [[ ${#option_args[@]} -eq 0 ]]; then # bash v3 compat
diff --git a/commands/echo-style b/commands/echo-style
--- a/commands/echo-style
+++ b/commands/echo-style
@@ -11,7 +11,7 @@ function echo_style() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			USAGE:
 
 			echo-style [...options] [--!style] [--!style+!style] value [--!style=value] [--!style+!style=value]
@@ -126,7 +126,7 @@ function echo_style() (
 	# act
 	local item flag style generic \
 		i current_char_index last_char_index \
-		item_target buffer_target='/dev/stdout' terminal_device_file \
+		item_target buffer_target='/dev/stdout' \
 		MISSING_STYLES=() \
 		ITEM_COLOR buffer_color="$option_color" \
 		ITEM_BEGIN \
@@ -261,7 +261,7 @@ function echo_style() (
 				black | red | green | yellow | blue | magenta | cyan | white | purple | gray | grey) style="foreground_$style" ;;
 				'intense_'*) style="foreground_intense_${style:8}" ;;
 				/*) style="slash_${style:1}" ;;
-				*/) style="$(__substr "$style" 0 -1)_slash" ;;
+				*/) style="$(__get_substring "$style" 0 -1)_slash" ;;
 				status)
 					if [[ $item_content -eq 0 ]]; then
 						style='good3'
@@ -287,10 +287,7 @@ function echo_style() (
 					continue
 					;;
 				tty)
-					if [[ -z ${terminal_device_file-} ]]; then
-						terminal_device_file="$(get-terminal-device-file)"
-					fi
-					item_target="$terminal_device_file"
+					item_target='/dev/tty'
 					continue
 					;;
 				null)
@@ -315,7 +312,7 @@ function echo_style() (
 		if [[ $generic == 'yes' ]]; then
 			# flush buffer if necessary
 			if [[ $item_target != "$buffer_target" ]]; then
-				__print_string "${buffer_left}" >"$buffer_target"
+				__do --redirect-stdout="$buffer_target" -- __print_string "${buffer_left}"
 				buffer_left=''
 				buffer_target="$item_target"
 			fi
@@ -328,9 +325,9 @@ function echo_style() (
 		else
 			# flush buffer if necessary
 			if [[ $item_target != "$buffer_target" ]]; then
-				__print_string "${buffer_left}" >"$buffer_target"
+				__do --redirect-stdout="$buffer_target" -- __print_string "${buffer_left}"
 				buffer_left=''
-				__print_string "${ITEM_BEGIN}${item_content}${ITEM_END}" >"$item_target"
+				__do --redirect-stdout="$item_target" -- __print_string "${ITEM_BEGIN}${item_content}${ITEM_END}"
 			else
 				buffer_left+="${ITEM_BEGIN}${item_content}${ITEM_END}"
 			fi
@@ -341,9 +338,9 @@ function echo_style() (
 	if [[ $option_trail == 'yes' ]]; then
 		buffer_right+=$'\n'
 	fi
-	__print_string "${buffer_left}${buffer_disable}${buffer_right}" >"$buffer_target"
+	__do --redirect-stdout="$buffer_target" -- __print_string "${buffer_left}${buffer_disable}${buffer_right}"
 	if [[ $option_debug == 'yes' || ${#MISSING_STYLES[@]} -ne 0 ]]; then
-		__print_lines 'ERROR: MISSING STYLES:' "${MISSING_STYLES[@]}" >/dev/stderr
+		__print_lines 'ERROR: MISSING STYLES:' "${MISSING_STYLES[@]}" >&2
 		return 22 # EINVAL 22 Invalid argument
 	fi
 )
diff --git a/commands/get-devices b/commands/get-devices
--- a/commands/get-devices
+++ b/commands/get-devices
@@ -30,7 +30,7 @@ function get_devices() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Get devices and their information.
 
@@ -238,10 +238,6 @@ function get_devices() (
 	# =====================================
 	# Action
 
-	# terminal
-	local terminal_device_file
-	terminal_device_file="$(get-terminal-device-file)"
-
 	# dependencies
 	setup-util-devices --quiet
 
@@ -328,7 +324,7 @@ function get_devices() (
 				# trail
 				__print_line
 			fi
-		} >/dev/stderr
+		} >&2
 	fi
 
 	# action
@@ -339,7 +335,7 @@ function get_devices() (
 			# if you attach a btrfs cluster to a new machine
 			# it may not be completely discovered until the btrfs agent scans for the devices
 			# and btrfs supports mounting partial filesystems, which cause innumerable errors
-			eval-helper --quiet -- btrfs-helper discover >"$terminal_device_file"
+			__do --redirect-stdout=tty -- eval-helper --quiet -- btrfs-helper discover
 			MOUNT_HAYSTACK="$(mount)"
 		fi
 		if is-mac; then
@@ -354,7 +350,7 @@ function get_devices() (
 		local exclude_status temp node="$1" size="${2-}" model="${3-}" label='' uuid='' block='' filesystem='' mount='' count='' count_available='' count_info='' serial='' vendor='' product='' revision=''
 
 		# check node quickly
-		eval_capture --statusvar=exclude_status -- check_exclude 'node' "$node"
+		__do --redirect-status={exclude_status} -- check_exclude 'node' "$node"
 		if [[ $exclude_status -eq 0 ]]; then
 			return 0
 		fi
@@ -455,7 +451,7 @@ function get_devices() (
 		# check filters
 		local filter
 		for filter in "${filters[@]}"; do
-			eval_capture --statusvar=exclude_status -- check_exclude "$filter" "${!filter}"
+			__do --redirect-status={exclude_status} -- check_exclude "$filter" "${!filter}"
 			if [[ $exclude_status -eq 0 ]]; then
 				return 0
 			fi
@@ -465,11 +461,15 @@ function get_devices() (
 		local result_status=0
 		if [[ -n $count ]]; then
 			if [[ $count != "$count_available" ]] || echo-regexp -qi --regexp='(warning|error|missing)' -- "$count_info"; then
-				echo-style --error="$node: $count_available/$count devices found" $'\n' "$(echo-lines --indent=$'\t' --stdin <<<"$count_info")" >/dev/stderr
+				echo-style --stderr \
+					--error="$node: $count_available/$count devices found" --newline \
+					--"$(echo-lines --indent=$'\t' --stdin <<<"$count_info")"
 				result_status=5 # EIO 5 Input/output error
 			fi
 			if [[ -n $option_count && $option_label == "$label" && $option_count != "$count" ]]; then
-				echo-style --error="$node: $count_available/$count devices found, however we expected $option_count devices" $'\n' "$(echo-lines --indent=$'\t' --stdin <<<"$count_info")" >/dev/stderr
+				echo-style --stderr \
+					--error="$node: $count_available/$count devices found, however we expected $option_count devices" --newline \
+					--"$(echo-lines --indent=$'\t' --stdin <<<"$count_info")"
 				result_status=5 # EIO 5 Input/output error
 			fi
 		fi
@@ -503,13 +503,13 @@ function get_devices() (
 
 	# fetch all
 	local status result
-	echo-style --bold='Getting devices...' >"$terminal_device_file"
-	eval_capture --statusvar=status --stdoutvar=result -- get_all
+	echo-style --tty --bold='Getting devices...'
+	__do --redirect-status={status} --copy-stdout={result} --redirect-stdout=tty -- get_all
 	if [[ $status -ne 0 ]]; then
 		return "$status"
 	fi
 	# erase [Getting devices...] message
-	echo-style --no-trail --delete-line >"$terminal_device_file"
+	echo-style --no-trail --tty --delete-line
 
 	# iterate through all
 	local message items=() node size model results=() result_status=0
@@ -532,9 +532,9 @@ function get_devices() (
 		if [[ -n $model ]]; then
 			model="$(echo-trim-each-line -- "$model")"
 		fi
-		printf "$message\n" "$node" "$size" "$model" >"$terminal_device_file"
+		__do --redirect-stdout=tty -- printf "$message\n" "$node" "$size" "$model"
 		# process
-		eval_capture --statusvar=status --stdoutvar=result -- get_one "$node" "$size" "$model"
+		__do --redirect-status={status} --copy-stdout={result} --redirect-stdout=tty -- get_one "$node" "$size" "$model"
 		# handle
 		if [[ -n $result ]]; then
 			results+=("$result")
@@ -543,7 +543,7 @@ function get_devices() (
 			result_status="$status"
 		else
 			# erase [Getting device:] message
-			echo-style --no-trail --delete-line >"$terminal_device_file"
+			echo-style --no-trail --tty --delete-line
 		fi
 	done
 
@@ -558,7 +558,7 @@ function get_devices() (
 	# check for missing failure
 	if [[ ${#results[@]} -eq 0 ]]; then
 		if [[ $option_quiet != 'yes' ]]; then
-			echo-style --error="$option_missing" >/dev/stderr
+			echo-style --stderr --error="$option_missing"
 		fi
 		return 6 # ENXIO 6 Device not configured
 	fi
diff --git a/commands/is-root b/commands/is-root
--- a/commands/is-root
+++ b/commands/is-root
@@ -3,7 +3,7 @@
 # @todo rename to is-root-user or is-user-root
 
 function is_root_test() (
-	source "$DOROTHY/sources/tests.bash"
+	source "$DOROTHY/sources/is-fs-tests.bash"
 	echo-style --h1="TEST: $0"
 
 	eval-helper --wrap --verbose -- whoami || :
@@ -32,7 +32,7 @@ function is_root() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Check if the currently logged in user, or the specified <user>s are root.
 
@@ -89,11 +89,11 @@ function is_root() (
 		# if [[ "$(id -u "$user")" -ne 0 ]]; then
 		if [[ $user != 'root' ]]; then
 			if [[ -z $option_quiet || $option_quiet == 'no' ]]; then
-				echo-style --error1='User ' --code-error1="$user" --error1=' is not root.' >/dev/stderr
+				echo-style --stderr --error1='User ' --code-error1="$user" --error1=' is not root.'
 			fi
 			return 1
 		elif [[ $option_quiet == 'no' ]]; then
-			echo-style --info1='User ' --code-info1="$user" --info1=' is root.' >/dev/stderr
+			echo-style --stderr --info1='User ' --code-info1="$user" --info1=' is root.'
 		fi
 	done
 	return 0
diff --git a/commands/service-helper b/commands/service-helper
--- a/commands/service-helper
+++ b/commands/service-helper
@@ -21,7 +21,7 @@ function service_helper() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Cross-platform service management.
 
@@ -133,10 +133,10 @@ function service_helper() (
 		# quirks about macos/launchctl
 		# - service identifiers can have a `system/`, `user/`, `pid/`, and `session/` prefix, such as `system/com.apple.smbd`
 		# - service identifiers can also have extensions it seems, such as `system/com.apple.smb.preferences`
-		function do_unmask {
+		function __do_unmask {
 			return 0 # not needed
 		}
-		function do_load {
+		function __do_load {
 			# Usage: launchctl load <service-path, service-path2, ...>
 			# -w      If the service is disabled, it will be enabled. In previous
 			# 		versions of launchd, being disabled meant that a service was
@@ -144,64 +144,66 @@ function service_helper() (
 			# 		disabled, launchd does not advertise its service endpoints
 			# 		(sockets, Mach ports, etc.).
 			local plist
-			plist="$(do_find "$1")"
-			sudo-helper --reason="Loading the service $1 requires your sudo/root/login password." \
+			plist="$(__do_find "$1")"
+			__return $? || return
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Loading the service: $1" \
 				-- launchctl load -w "$plist"
 		}
-		function do_unload {
+		function __do_unload {
 			# Usage: launchctl unload <service-path, service-path2, ...>
 			# -w      Additionally disables the service such that future load
 			# 		operations will result in a service which launchd tracks but
 			# 		cannot be launched or discovered in any way.
 			# ...
 			local plist
-			plist="$(do_find "$1")"
-			sudo-helper --reason="Unloading the service $1 requires your sudo/root/login password." \
+			plist="$(__do_find "$1")"
+			__return $? || return
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Unloading the service: $1" \
 				-- launchctl unload -w "$plist"
 		}
-		function do_start {
+		function __do_start {
 			local id="$1"
 			id="${id#*system/}" # trim system/
-			sudo-helper --reason="Starting the service $1 requires your sudo/root/login password." \
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Starting the service: $1" \
 				-- launchctl start "$id"
 		}
-		function do_stop {
+		function __do_stop {
 			local id="$1"
 			id="${id#*system/}" # trim system/
-			sudo-helper --reason="Stopping the service $1 requires your sudo/root/login password." \
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Stopping the service: $1" \
 				-- launchctl stop "$id"
 		}
-		function do_restart {
-			eval_capture -- do_stop "$1"
-			do_load "$1"
-			do_start "$1"
+		function __do_restart {
+			__do_stop "$1" || : # ignore
+			__do_load "$1" || return
+			__do_start "$1" || return
 		}
-		function do_enable {
-			sudo-helper --reason="Enabling the service $1 requires your sudo/root/login password." \
+		function __do_enable {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Enabling the service: $1" \
 				-- launchctl enable "$1"
 		}
-		function do_enable_now {
-			do_enable "$1"
-			do_start "$1"
+		function __do_enable_now {
+			__do_enable "$1" || return
+			__do_start "$1" || return
 		}
-		function do_disable {
-			sudo-helper --reason="Disabling the service $1 requires your sudo/root/login password." \
+		function __do_disable {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Disabling the service: $1" \
 				-- launchctl disable "$1"
 		}
-		function do_disable_now {
-			do_disable "$1"
-			do_stop "$1"
+		function __do_disable_now {
+			__do_disable "$1" || return
+			__do_stop "$1" || return
 		}
-		function do_reenable {
-			do_disable "$1"
-			do_enable "$1"
+		function __do_reenable {
+			__do_disable "$1" || return
+			__do_enable "$1" || return
 		}
-		function do_status {
+		function __do_status {
 			# return code based on service existence, so ignore, save for running and exists
-			sudo-helper --reason="Checking the status of the service $1 requires your sudo/root/login password." \
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Checking the status of the service: $1" \
 				-- launchctl print "$1" || :
 		}
-		function do_logs {
+		function __do_logs {
 			# @todo
 			# https://stackoverflow.com/a/29926482/130638
 			# https://stackoverflow.com/a/6887421/130638
@@ -209,29 +211,30 @@ function service_helper() (
 			# https://apple.stackexchange.com/a/435504/15131
 			return 78 # ENOSYS 78 Function not implemented
 		}
-		function do_running {
+		function __do_running {
 			# return code based on service pid existing / running, hide output
-			sudo-helper --reason="Checking the run status of the service $1 requires your sudo/root/login password." \
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Checking the run status of the service: $1" \
 				-- launchctl list | grep --regexp="$1" | grep --quiet --regexp='^[^-]'
 		}
-		function do_remove {
+		function __do_remove {
 			return 78 # ENOSYS 78 Function not implemented
 		}
 		function __do_exists {
 			# return code based on service existence
-			sudo-helper --reason="Checking the existence of the service $1 requires your sudo/root/login password." \
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Checking the existence of the service: $1" \
 				-- launchctl print "$1" &>/dev/null
 		}
-		function do_edit {
+		function __do_edit {
 			local plist
-			plist="$(do_find "$1")"
-			edit --wait --sudo -- "$plist"
+			plist="$(__do_find "$1")"
+			__return $? || return
+			edit --wait --sudo -- "$plist" || return
 		}
-		function do_find {
+		function __do_find {
 			local id="$1"
 			id="${id#*system/}" # trim system/
 			if [[ -f $id ]]; then
-				__print_lines "$id"
+				__print_lines "$id" || return
 				return 0
 			fi
 			local paths=(
@@ -243,72 +246,72 @@ function service_helper() (
 				/System/Library/LaunchAgents/*"$id"*
 			)
 			if [[ ${#paths[@]} -eq 0 ]]; then
-				echo-style -stderr --error1='Service does not exist: ' --code-error1="$id"
+				echo-style -stderr --error1='Service does not exist: ' --code-error1="$id" || return
 				return 2 # ENOENT 2 No such file or directory
 			else
-				__print_lines "${paths[@]}"
+				__print_lines "${paths[@]}" || return
 			fi
 		}
 	elif __command_exists -- systemctl; then
-		function do_unmask {
-			sudo-helper --reason="Unmasking the service $1 requires your sudo/root/login password." \
+		function __do_unmask {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to unmask the service: $1" \
 				-- systemctl unmask "$1"
 		}
-		function do_load {
-			sudo-helper --reason="Loading the service $1 requires your sudo/root/login password." \
+		function __do_load {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to load the service: $1" \
 				-- systemctl daemon-reload
 		}
-		function do_unload {
-			sudo-helper --reason="Unloading the service $1 requires your sudo/root/login password." \
+		function __do_unload {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to unload the service: $1" \
 				-- systemctl daemon-reload
 		}
-		function do_start {
-			sudo-helper --reason="Starting the service $1 requires your sudo/root/login password." \
+		function __do_start {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to start the service: $1" \
 				-- systemctl start "$1"
 		}
-		function do_stop {
-			sudo-helper --reason="Stopping the service $1 requires your sudo/root/login password." \
+		function __do_stop {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to stop the service: $1" \
 				-- systemctl stop "$1"
 		}
-		function do_restart {
-			sudo-helper --reason="Restarting the service $1 requires your sudo/root/login password." \
+		function __do_restart {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to restart the service: $1" \
 				-- systemctl restart "$1"
 		}
-		function do_enable {
-			sudo-helper --reason="Enabling the service $1 requires your sudo/root/login password." \
+		function __do_enable {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to enable the service: $1" \
 				-- systemctl enable "$1"
 		}
-		function do_enable_now {
-			sudo-helper --reason="Enabling the service $1 requires your sudo/root/login password." \
+		function __do_enable_now {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to instantly enable the service: $1" \
 				-- systemctl enable --now "$1"
 		}
-		function do_disable {
-			sudo-helper --reason="Disabling service $1 requires your sudo/root/login password." \
+		function __do_disable {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to disable service $1" \
 				-- systemctl disable "$1"
 		}
-		function do_disable_now {
-			sudo-helper --reason="Disabling service $1 requires your sudo/root/login password." \
+		function __do_disable_now {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to instantly disable service $1" \
 				-- systemctl disable --now "$1"
 		}
-		function do_reenable {
-			sudo-helper --reason="Reenabling service $1 requires your sudo/root/login password." \
+		function __do_reenable {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Reenabling service $1" \
 				-- systemctl reenable "$1"
 		}
-		function do_status {
+		function __do_status {
 			# return code based on service running, so ignore, save for running and exists
-			sudo-helper --reason="Checking the status of the service $1 requires your sudo/root/login password." \
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Checking the status of the service: $1" \
 				-- systemctl status "$1" --no-pager || :
 		}
-		function do_logs {
-			sudo-helper --reason="Checking the logs of the service $1 requires your sudo/root/login password." \
+		function __do_logs {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Checking the logs of the service: $1" \
 				-- sudo journalctl -u "$1" --no-pager || :
 		}
-		function do_running {
+		function __do_running {
 			# return code based on service running, hide output
-			sudo-helper --reason="Checking the run status of the service $1 requires your sudo/root/login password." \
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Checking the run status of the service: $1" \
 				-- systemctl status "$1" --no-pager &>/dev/null
 		}
-		function do_remove {
+		function __do_remove {
 			local id="$1" paths
 			if [[ $id == *'@'* ]]; then
 				id="${id%@*}@" # `syncthing@user` => `syncthing@`
@@ -320,7 +323,7 @@ function service_helper() (
 				/usr/lib/systemd/system/*"$id"*
 			)
 			if [[ ${#paths[@]} -ne 0 ]]; then
-				fs-rm --confirm --sudo -- "${paths[@]}"
+				fs-rm --confirm --sudo -- "${paths[@]}" || return
 			fi
 		}
 		function __do_exists {
@@ -341,75 +344,75 @@ function service_helper() (
 			[[ ${#paths[@]} -ne 0 ]]
 			return # explicit return with [[ required for bash v3
 		}
-		function do_edit {
+		function __do_edit {
 			local id="$1"
 			# --inherit to maintain editor preferences
-			sudo-helper --inherit -- systemctl edit "$id"
+			sudo-helper --inherit -- systemctl edit "$id" || return
 			# apply the changes, otherwise they will be reverted
-			sudo-helper -- systemctl daemon-reload
+			sudo-helper -- systemctl daemon-reload || return
 			# if you aren't seeing your changes saved, make sure you save them between the comment sections where it tells you to, and not just say at the very top of the file
 		}
 	elif __command_exists -- rc-service; then
-		function do_unmask {
+		function __do_unmask {
 			return 0 # not needed
 		}
-		function do_load {
+		function __do_load {
 			return 0 # not needed
 		}
-		function do_unload {
+		function __do_unload {
 			return 0 # not needed
 		}
-		function do_start {
-			sudo-helper --reason="Starting the service $1 requires your sudo/root/login password." \
+		function __do_start {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Starting the service: $1" \
 				-- rc-service "$1" start
 		}
-		function do_stop {
-			sudo-helper --reason="Stopping the service $1 requires your sudo/root/login password." \
+		function __do_stop {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Stopping the service: $1" \
 				-- rc-service "$1" stop
 		}
-		function do_restart {
-			sudo-helper --reason="Restarting the service $1 requires your sudo/root/login password." \
+		function __do_restart {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Restarting the service: $1" \
 				-- rc-service "$1" restart
 		}
-		function do_enable {
-			sudo-helper --reason="Enabling the service $1 requires your sudo/root/login password." \
+		function __do_enable {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Enabling the service: $1" \
 				-- rc-update add "$1"
 		}
-		function do_enable_now {
-			sudo-helper --reason="Adding the service $1 requires your sudo/root/login password." \
+		function __do_enable_now {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Adding the service: $1" \
 				-- rc-update add "$1"
-			sudo-helper --reason="Starting the service $1 requires your sudo/root/login password." \
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Starting the service: $1" \
 				-- rc-service "$1" start
 		}
-		function do_disable {
-			sudo-helper --reason="Disabling the service $1 requires your sudo/root/login password." \
+		function __do_disable {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Disabling the service: $1" \
 				-- rc-update del "$1"
 		}
-		function do_disable_now {
-			sudo-helper --reason="Stopping the service $1 requires your sudo/root/login password." \
+		function __do_disable_now {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Stopping the service: $1" \
 				-- rc-service "$1" stop
-			sudo-helper --reason="Removing the service $1 requires your sudo/root/login password." \
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Removing the service: $1" \
 				-- rc-update del "$1"
 		}
-		function do_reenable {
-			sudo-helper --reason="Reenabling the service $1 requires your sudo/root/login password." \
+		function __do_reenable {
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Reenabling the service: $1" \
 				-- rc-update add "$1"
 		}
-		function do_status {
+		function __do_status {
 			# return code based on service running, so ignore, save for running and exists
-			sudo-helper --reason="Checking the status of the service $1 requires your sudo/root/login password." \
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Checking the status of the service: $1" \
 				-- rc-service "$1" status || :
 		}
-		function do_logs {
+		function __do_logs {
 			# @todo
 			return 78 # ENOSYS 78 Function not implemented
 		}
-		function do_running {
+		function __do_running {
 			# return code based on service running, hide output
-			sudo-helper --reason="Checking the run status of the service $1 requires your sudo/root/login password." \
+			sudo-helper --reason="Your password is required to momentarily grant privileges to Checking the run status of the service: $1" \
 				-- rc-service "$1" status &>/dev/null
 		}
-		function do_remove {
+		function __do_remove {
 			return 78 # ENOSYS 78 Function not implemented
 		}
 		function __do_exists {
@@ -476,30 +479,30 @@ function service_helper() (
 					__do_exists "$this_service"
 				fi
 				;;
-			'edit') do_edit "$this_service" ;;
-			'remove') do_remove "$this_service" ;;
-			'status') do_status "$this_service" ;;
+			'edit') __do_edit "$this_service" ;;
+			'remove') __do_remove "$this_service" ;;
+			'status') __do_status "$this_service" ;;
 			# unmask before load
-			'unmask') do_unmask "$this_service" ;;
+			'unmask') __do_unmask "$this_service" ;;
 			# load before stops
-			'load') do_load "$this_service" ;;
+			'load') __do_load "$this_service" ;;
 			# do stop, starts, before unload
-			'stop') do_stop "$this_service" ;;
-			'reenable') do_reenable "$this_service" ;;
-			'enable') do_enable "$this_service" ;;
-			'disable') do_disable "$this_service" ;;
+			'stop') __do_stop "$this_service" ;;
+			'reenable') __do_reenable "$this_service" ;;
+			'enable') __do_enable "$this_service" ;;
+			'disable') __do_disable "$this_service" ;;
 			# do enable/disable starts stops
-			'enable-now') do_enable_now "$this_service" ;;
-			'disable-now') do_disable_now "$this_service" ;;
+			'enable-now') __do_enable_now "$this_service" ;;
+			'disable-now') __do_disable_now "$this_service" ;;
 			# do starts
-			'start') do_start "$this_service" ;;
+			'start') __do_start "$this_service" ;;
 			# if any of reenable/disable/enable, then restart should be changed to stop and start
-			'restart') do_restart "$this_service" ;;
+			'restart') __do_restart "$this_service" ;;
 			# do unload
-			'unload') do_unload "$this_service" ;;
-			'logs') do_logs "$this_service" ;;
+			'unload') __do_unload "$this_service" ;;
+			'logs') __do_logs "$this_service" ;;
 			# do running
-			'running') do_running "$this_service" ;;
+			'running') __do_running "$this_service" ;;
 			*) help "An unrecognised action was provided: $this_action" ;;
 			esac
 		done
diff --git a/commands/setup-shell b/commands/setup-shell
--- a/commands/setup-shell
+++ b/commands/setup-shell
@@ -36,7 +36,7 @@ function setup_shell() (
 		'xonsh') __print_lines 'Xonsh' ;;
 		'elvish') __print_lines 'Elvish' ;;
 		'dash') __print_lines 'Dash' ;;
-		'ksh') __print_lines 'KSH' ;;
+		'ksh') __print_lines 'KSH' ;; # http://kornshell.com/doc/faq.html KornShell is the language, KSH-93 is the most recent version of the language, ksh is the program, so do KSH as a middle-ground
 		*) __print_lines "$shell" ;;
 		esac
 	}
@@ -261,17 +261,17 @@ function setup_shell() (
 				chpass -s "$login_shell_path" -u "$USER" || __chpass_status=$?
 				if [[ $__chpass_status -eq 0 ]]; then
 					# successfully updated
-					echo-style --dim='You can ignore [chpass: no changes made] warnings.' >"$terminal_device_file" || return
+					echo-style --tty --dim='You can ignore [chpass: no changes made] warnings.' || return
 					break
 				elif [[ $__chpass_status -eq 1 ]]; then
 					# incorrect password
 					continue # try again
 				elif [[ $__chpass_status -eq 130 ]]; then
 					# 130 = SIGINT = ctrl+c = abort
-					echo-style --error="Updating the login shell failed because [chpass] was aborted with exit status [$__chpass_status]." >/dev/stderr || return
+					echo-style --stderr --error="Updating the login shell failed because [chpass] was aborted with exit status [$__chpass_status]." || return
 					return 125 # ECANCELED 125 Operation cancelled
 				else
-					echo-style --error="Updating the login shell failed because [chpass] failed with exit status [$__chpass_status]." >/dev/stderr || return
+					echo-style --stderr --error="Updating the login shell failed because [chpass] failed with exit status [$__chpass_status]." || return
 					return "$__chpass_status"
 				fi
 			done
@@ -489,7 +489,7 @@ function setup_shell() (
 	# ^ if config provided, it does not reconfigure, unless --configure is provided
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Setup your desired shells. Installs/uninstalls them. Configures/deconfigures them for Dorothy. allows and applies your login shell.
 
@@ -603,9 +603,6 @@ function setup_shell() (
 		option_shells=("${USER_SHELLS[@]}")
 	fi
 
-	local terminal_device_file
-	terminal_device_file="$(get-terminal-device-file)"
-
 	# =====================================
 	# Helpers
 
@@ -662,11 +659,11 @@ function setup_shell() (
 		# select which shells to install and consequently which to also uninstall
 		local choices=() selected_shells=() result status
 		mapfile -t choices < <(get_unique_and_permitted_basenames_of_shells_with_labels "${all_installable_basenames_of_shells[@]}")
-		__print_line >"$terminal_device_file"
-		eval_capture --statusvar=status --stdoutvar=result -- \
+		__do --redirect-stdout=tty -- __print_line
+		__do --redirect-status={status} --redirect-stdout={result} -- \
 			choose --linger --multi "$question" "$details" --defaults="$defaults_string" --label -- "${choices[@]}"
 		if [[ $status -eq 130 ]]; then
-			echo-style --notice='No changes to installed shells were desired.' >"$terminal_device_file"
+			echo-style --tty --notice='No changes to installed shells were desired.'
 			return 0
 		elif [[ $status -ne 0 ]]; then
 			return "$status"
@@ -749,11 +746,11 @@ function setup_shell() (
 		# select which shells to configure and consequently which to also deconfigure
 		local choices=() selected_shells=() result status
 		mapfile -t choices < <(get_unique_and_permitted_basenames_of_shells_with_labels "${all_configurable_basenames_of_shells[@]}")
-		__print_line >"$terminal_device_file"
-		eval_capture --statusvar=status --stdoutvar=result -- \
+		__do --redirect-stdout=tty -- __print_line
+		__do --redirect-status={status} --redirect-stdout={result} -- \
 			choose --linger --multi "$question" "$details" --defaults="$defaults_string" --label -- "${choices[@]}"
 		if [[ $status -eq 130 ]]; then
-			echo-style --notice='No changes to configured shells were desired.' >"$terminal_device_file"
+			echo-style --tty --notice='No changes to configured shells were desired.'
 			return 0
 		elif [[ $status -ne 0 ]]; then
 			return "$status"
@@ -872,11 +869,11 @@ function setup_shell() (
 		# select which shells to allow and consequently which to also disallow
 		local choices_with_labels=() selected_shells=() result status
 		mapfile -t choices_with_labels < <(get_unique_and_permitted_paths_of_shells_with_labels "${choices[@]}")
-		__print_line >"$terminal_device_file"
-		eval_capture --statusvar=status --stdoutvar=result -- \
+		__do --redirect-stdout=tty -- __print_line
+		__do --redirect-status={status} --redirect-stdout={result} -- \
 			choose --linger --required --multi "$question" "$details" --defaults="$defaults_string" --label -- "${choices_with_labels[@]}"
 		if [[ $status -eq 130 ]]; then
-			echo-style --notice='No changes to system login shells were desired.' >"$terminal_device_file"
+			echo-style --tty --notice='No changes to system login shells were desired.'
 			return 0
 		elif [[ $status -ne 0 ]]; then
 			return "$status"
@@ -889,7 +886,7 @@ function setup_shell() (
 		if [[ ${#selected_shells[@]} -eq 0 ]]; then
 			# disallow everything
 			if [[ $option_disallow != 'no' ]]; then
-				echo-style --notice='Skipping disallowing all shells form being used as a login shell, as that is a mistake.' >"$terminal_device_file"
+				echo-style --tty --notice='Skipping disallowing all shells form being used as a login shell, as that is a mistake.'
 				return 0
 			fi
 		else
@@ -914,7 +911,7 @@ function setup_shell() (
 
 		# check
 		if [[ $can_apply_login_shell == 'no' ]]; then
-			echo-style --notice="Dorothy doesn't know how to set the login shell on this Operating System." >"$terminal_device_file"
+			echo-style --tty --notice="Dorothy doesn't know how to set the login shell on this Operating System."
 			return 0
 			# return 19 # ENODEV 19 Operation not configurable by device
 		fi
@@ -940,12 +937,12 @@ function setup_shell() (
 		get_login_choices_defaults_details # apply choices, defaults, defaults_string, and details
 
 		# select which shell to use as login shell
-		__print_line >"$terminal_device_file"
+		__do --redirect-stdout=tty -- __print_line
 		login_shell_path="$(
 			choose --linger --no-multi "$question" "$details" --defaults="$defaults_string" --label -- "${choices[@]}" || :
 		)"
 		if [[ -z $login_shell_path ]]; then
-			echo-style --notice='No changes to the default login shell were desired.' >"$terminal_device_file"
+			echo-style --tty --notice='No changes to the default login shell were desired.'
 			return 0
 		fi
 
diff --git a/commands/ssh-helper b/commands/ssh-helper
--- a/commands/ssh-helper
+++ b/commands/ssh-helper
@@ -8,7 +8,7 @@ function ssh_helper() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Helpers for interacting with SSH.
 
@@ -182,10 +182,11 @@ function ssh_helper() (
 			fi
 		elif [[ -n $SSH_IDENTITY_AGENT ]]; then
 			if [[ $SSH_IDENTITY_AGENT == 'op' && -z $op_sock ]]; then
-				echo-style --warning='1Password SSH Agent is not available.' $'\n' \
-					'If you wish to use it, you must enable it first:' $'\n' \
-					--code='https://developer.op.com/docs/ssh/get-started#step-3-turn-on-the-op-ssh-agent' $'\n' \
-					--notice='Disabling for now...' >/dev/stderr
+				echo-style --stderr \
+					--warning='1Password SSH Agent is not available.' --newline \
+					'If you wish to use it, you must enable it first:' --newline \
+					--code='https://developer.op.com/docs/ssh/get-started#step-3-turn-on-the-op-ssh-agent' --newline \
+					--notice='Disabling for now...'
 				SSH_IDENTITY_AGENT=''
 			fi
 		fi
@@ -205,8 +206,9 @@ function ssh_helper() (
 
 		# confirm the ssh agent is a working socket
 		if [[ -n $SSH_IDENTITY_AGENT ]] && ! __sock_exists "$SSH_IDENTITY_AGENT"; then
-			echo-style --warning="$0: The SSH_IDENTITY_AGENT of [$SSH_IDENTITY_AGENT] does not exist as a valid socket." $'\n' \
-				--notice='Disabling for now...' >/dev/stderr
+			echo-style --stderr \
+				--warning="$0: The SSH_IDENTITY_AGENT of [$SSH_IDENTITY_AGENT] does not exist as a valid socket." --newline \
+				--notice='Disabling for now...'
 			SSH_IDENTITY_AGENT=''
 		fi
 
@@ -320,7 +322,7 @@ function ssh_helper() (
 		cat <<-EOF
 			Public key that you can share is outputted below
 			------------------------------------------------
-			$(cat -- "${path}.pub")
+			$(<"${path}.pub")
 		EOF
 	}
 
@@ -438,7 +440,7 @@ function ssh_helper() (
 		if [[ $__test_status -le 1 ]]; then
 			return 0
 		else
-			cat -- "$logs" >/dev/stderr
+			cat -- "$logs" >&2
 			return 1
 		fi
 	}
@@ -485,9 +487,9 @@ function ssh_helper() (
 		# 0 = success
 		# 130 = success then closed eventually
 		local connect_status
-		eval_capture --statusvar=connect_status -- ssh "$@"
+		__try {connect_status} -- ssh "$@"
 		if [[ $connect_status -ne 0 ]] && ! is-abort -- "$connect_status"; then
-			echo-style --warning="Failed with exit code [$connect_status], will try again in 10 seconds..." >/dev/stderr
+			echo-style --stderr --warning="Failed with exit code [$connect_status], will try again in 10 seconds..."
 			sleep 10
 			ssh_connect "$@"
 		fi
diff --git a/commands/unziptar b/commands/unziptar
--- a/commands/unziptar
+++ b/commands/unziptar
@@ -10,7 +10,7 @@ function unziptar_() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Extract the files from a zip/tar/dmg/etc file.
 
@@ -166,7 +166,8 @@ function unziptar_() (
 		trap dmg_unmount EXIT
 		# install what is necessary for identifying the DMG volume
 		# attach the DMG to a volume
-		dmg_device="$(hdiutil attach -readonly -nobrowse -mountroot "$archive_directory" "$archive" | echo-wait | echo-regexp -fo --regexp='(/dev/.+?)\s' --replace='$1')"
+		# this had a [echo-wait --buffer | echo-regexp] however that is not necessary with [echo-regexp -f] (as it reads all of stdin) but was necessary when [rg --max-count=1] was used instead (as it reads chunk by chunk)
+		dmg_device="$(hdiutil attach -readonly -nobrowse -mountroot "$archive_directory" "$archive" | echo-regexp -fo --regexp='(/dev/.+?)\s' --replace='$1')"
 		function relocate {
 			cp -Rfv -- "$@"
 		}
@@ -178,13 +179,11 @@ function unziptar_() (
 		__unzip "$archive" 2>/dev/null || {
 			setup-util-unziptar --quiet
 			__unzip "$archive" || {
-				{
-					echo-error 'Failed to extract the archive:'
-					get-file -- "$archive"
-					unzip --help
-				} >/dev/stderr
+				echo-error 'Failed to extract the archive:'
+				get-file -- "$archive"
+				unzip --help
 				return 1
-			}
+			} >&2
 		}
 	elif [[ $format == 'tar' ]]; then
 		# be cautious with unziptar dependency, as is challenging on fresh macos
@@ -196,13 +195,11 @@ function unziptar_() (
 		__tar "$archive" 2>/dev/null || {
 			setup-util-unziptar --quiet
 			__tar "$archive" || {
-				{
-					echo-error 'Failed to extract the archive:'
-					get-file -- "$archive"
-					tar --help
-				} >/dev/stderr
+				echo-error 'Failed to extract the archive:'
+				get-file -- "$archive"
+				tar --help
 				return 1
-			}
+			} >&2
 		}
 	else
 		help "Unrecognised format: $format"
@@ -216,19 +213,18 @@ function unziptar_() (
 
 	# relocate extracted files
 	function log_extraction_failure {
-		{
-			# @todo style with var_dump or something
-			echo-error "$1" --newline \
-				--bold='Archive:' ' ' "$(get-file -- "$archive")" --newline \
-				--bold='Glob:' ' ' "$glob" --newline \
-				--bold='File:' ' ' "$file" --newline \
-				--bold='Expansion:' ' ' "$archive_directory/$glob" --newline \
-				--bold='-- matched paths --' --newline \
-				--="$(echo-verbose -- "${glob_paths[@]}")" --newline \
-				--bold='-- available paths --'
-			setup-util-tree --quiet
-			tree "$archive_directory"
-		} >/dev/stderr
+		# @todo style with var_dump or something
+		echo-error --stderr \
+			"$1" --newline \
+			--bold='Archive:' ' ' "$(get-file -- "$archive")" --newline \
+			--bold='Glob:' ' ' "$glob" --newline \
+			--bold='File:' ' ' "$file" --newline \
+			--bold='Expansion:' ' ' "$archive_directory/$glob" --newline \
+			--bold='-- matched paths --' --newline \
+			--="$(echo-verbose -- "${glob_paths[@]}")" --newline \
+			--bold='-- available paths --'
+		setup-util-tree --quiet >&2
+		tree "$archive_directory" >&2
 	}
 	if [[ ${#glob_paths[@]} -eq 0 ]]; then
 		log_extraction_failure 'No extracted files matched the glob:'
