get-codec: tests: if deps fail, ignore
/ref openeuuler arm

diff --git a/commands.beta/get-codec b/commands.beta/get-codec
--- a/commands.beta/get-codec
+++ b/commands.beta/get-codec
@@ -3,10 +3,18 @@
 function get_codec_test() (
 	source "$DOROTHY/sources/bash.bash"
 
+	# ignore failures on unsupported platforms
+	if ! setup-util-mediainfo; then
+		__print_error 'Cannot run tests for get-codec as mediainfo is not supported on this platform.' || return $?
+		return 0
+	fi
+
+	# download the media file
 	local ogg_media_url='https://upload.wikimedia.org/wikipedia/commons/c/c8/Example.ogg' ogg_media_file
 	ogg_media_file="$(fs-temp --directory='dorothy' --directory='get-codec' --directory='tests' --file --extension='ogg')"
 	down --url="$ogg_media_url" --filepath="$ogg_media_file"
 
+	# test the media file
 	local expected
 	expected="$(
 		# minify
