more linting and fixes re regexp, deno, unziptar
/ref https://github.com/bevry/dorothy/actions/runs/10868220016/job/30157899424

diff --git a/commands.beta/get-codec b/commands.beta/get-codec
--- a/commands.beta/get-codec
+++ b/commands.beta/get-codec
@@ -8,8 +8,13 @@ function get_codec_test() (
 	ogg_media_file="$(fs-temp --directory='get-codec' --file --extension='ogg')"
 	down --url="$ogg_media_url" --filepath="$ogg_media_file"
 
-	eval-tester --name='ogg vorbis file is ogg vorbis' --stdout='vorbis' \
-		-- get-codec --path="$ogg_media_file"
+	if command-exists -- ffprobe; then
+		eval-tester --name='ogg vorbis file is ogg vorbis' --stdout='vorbis' \
+			-- get-codec --path="$ogg_media_file"
+	else
+		eval-tester --name='ogg vorbis file is ogg vorbis' --status=6 \
+			-- get-codec --path="$ogg_media_file"
+	fi
 
 	echo-style --g1="TEST: $0"
 	return 0
@@ -63,6 +68,11 @@ function get_codec() (
 
 	# =====================================
 	# Action
+
+	if ! command-exists -- ffprobe; then
+		echo-error 'ffprobe is required for this command.'
+		return 6 # ENXIO 6 No such device or address
+	fi
 
 	if test "$option_verbose" = 'no'; then
 		# trunk-ignore(shellcheck/SC2016)
diff --git a/commands/unziptar b/commands/unziptar
--- a/commands/unziptar
+++ b/commands/unziptar
@@ -145,6 +145,18 @@ function unziptar_() (
 			dmg_device=''
 		fi
 	}
+	if is-alpine; then
+		function __unzip {
+			unzip "$@"
+		}
+	else
+		function __unzip {
+			unzip -u "$@"
+		}
+	fi
+	function __tar {
+		tar -xvf "$@"
+	}
 	if test "$format" = 'dmg'; then
 		if test "$0" != "${BASH_SOURCE[0]}"; then
 			help 'Must be run as a command, not a function, such that DMG cleanup always occurs, even on failures.'
@@ -152,6 +164,7 @@ function unziptar_() (
 		trap dmg_unmount EXIT
 		# install what is necessary for identifying the DMG volume
 		# attach the DMG to a volume
+		# trunk-ignore(shellcheck/SC2016)
 		dmg_device="$(hdiutil attach -readonly -nobrowse -mountroot "$archive_directory" "$archive" | echo-wait | echo-regexp -fo --regexp='(/dev/.+?)\s' --replace='$1')"
 		function relocate {
 			cp -Rfv "$@"
@@ -161,10 +174,14 @@ function unziptar_() (
 		if command-missing -- unzip; then
 			setup-util-unziptar --quiet
 		fi
-		unzip -u "$archive" 2>/dev/null || {
+		__unzip "$archive" 2>/dev/null || {
 			setup-util-unziptar --quiet
-			unzip -u "$archive" || {
-				echo-error 'Failed to extract the archive:' $'\n' "$(get-file -- "$archive")" $'\n' "$(unzip --help)"
+			__unzip "$archive" || {
+				{
+					echo-error 'Failed to extract the archive:'
+					get-file -- "$archive"
+					unzip --help
+				} >/dev/stderr
 				return 1
 			}
 		}
@@ -175,10 +192,14 @@ function unziptar_() (
 		fi
 		# don't use -z flag, as that enforces gzip (tar.xy) which is not valid for (.tar.xz)
 		# without -z, auto-detection is used
-		tar -xvf "$archive" 2>/dev/null || {
+		__tar "$archive" 2>/dev/null || {
 			setup-util-unziptar --quiet
-			tar -xvf "$archive" || {
-				echo-error 'Failed to extract the archive:' $'\n' "$(get-file -- "$archive")" $'\n' "$(tar --help)"
+			__tar "$archive" || {
+				{
+					echo-error 'Failed to extract the archive:'
+					get-file -- "$archive"
+					tar --help
+				} >/dev/stderr
 				return 1
 			}
 		}
