echo-trim-special: fix tests
- `bash.bash`, `eval-tester`, `echo-trim-special`, `versions.md`
    - work around two different bash bugs regarding file descriptors, one affecting all versions, one affecting v4.2
    - add new `__cat*` helpers
- `bash.bash`, `echo-trim-special`, `read-key`, `is-shapeshifter`:
    - add new `ANSI` section and helpers, such that trimming ansi sequences doesn't leave leftovers
    - `__to` now supports inputs
- `is-shapeshifter`:
    - tests now include new code for assisted detection of shapeshifting
- `echo-revolving-door`:
    - work around `__slice` now erroring on out of bound index/lengths
- `echo-write`:
    - rename its `__read_whole` to `__escape_stdin` for what it actually does
    - fix tests for when `bat` is not installed
- `expand-path`:
    - change a bash version check for a feature flag test

/amend WIP commit of ce8658711fe48467a1c9abe8c1bfc24eb382dade to fix tests and oversights

diff --git a/commands.beta/is-shapeshifter b/commands.beta/is-shapeshifter
--- a/commands.beta/is-shapeshifter
+++ b/commands.beta/is-shapeshifter
@@ -4,158 +4,46 @@ function is_shapeshifter_test() (
 	source "$DOROTHY/sources/bash.bash"
 	echo-style --h1="TEST: $0"
 
-	local item inputs outputs output
+	local inputs=() inputs_no_shapeshifters=() outputs=() output item
 
-	# non-shapeshift inputs
-	inputs=()
-	outputs=()
-	for item in "${inputs[@]}"; do
-		outputs+=("$(printf '%s %q\n' 'no:' "$item")")
+	# prep
+	local -i ansi_index
+	local key pattern name tags escaped_key shapeshifter
+	for ((ansi_index = 0; ansi_index < ANSI_SIZE; ansi_index += 4)); do
+		# <KEY/EXAMPLE-KEY> <PATTERN> <NAME> <CONSUMERS>
+		# printf '%s' $'\e#8\e[H' # make everything E characters so that we can see if things that delete forward do so, and go to top
+		key="${ANSI[ansi_index]}"
+		pattern="${ANSI[ansi_index + 1]}"
+		name="${ANSI[ansi_index + 2]}"
+		tags="${ANSI[ansi_index + 3]}"
+		if [[ $key =~ $pattern ]]; then
+			printf '%s %q %s\n' "$name example key" "$key" 'matched its pattern' >&2
+		else
+			printf '%s %q %s\n' "$name example key" "$key" 'FAILED to match the pattern' >&2
+			exit 1
+		fi
+		escaped_key="$(printf '%q' "$key")"
+		if [[ $tags == *'[shapeshifter]'* ]]; then
+			# shapeshifter='SHAPESHIFTER '
+			inputs+=("$key")
+			outputs+=("yes $escaped_key")
+		else
+			# shapeshifter='
+			inputs_no_shapeshifters+=("$key")
+			inputs+=("$key")
+			outputs+=("no $escaped_key")
+		fi
+		# __print_lines "$name $escaped_key $shapeshifter" "[12${key}34]" "$name $escaped_key $shapeshifter"
+		# read -s
 	done
+
+	# test
 	__join --source={outputs} --delimiter=$'\n' --target={output}
-	eval-tester --name='testing non-shapeshift inputs' --stderr="$output" --status=1 -- \
-		is-shapeshifter --verbose -- "${inputs[@]}"
-
-	# shapeshift inputs
-	inputs=(
-		# read-key
-		$'\e[A'    # up
-		$'\eM'     # up
-		$'\e[B'    # down
-		$'\e[C'    # right <-- can still move cursor to a different line
-		$'\e[D'    # left <-- can still move cursor to a different line
-		$'\e[H'    # home
-		$'\e[1~'   # home
-		$'\e[1;2D' # home
-		$'\r'      # carriage-return
-		$'\e[F'    # end
-		$'\e[4~'   # end
-		$'\e[1;2C' # end
-		$'\e[2~'   # insert
-		$'\e[3~'   # delete
-		$'\e[5~'   # page-up
-		$'\e[1;5D' # page-up
-		$'\eb'     # page-up
-		$'\e[6~'   # page-down
-		$'\e[1;5C' # page-down
-		$'\ef'     # page-down
-		$'\177'    # backspace
-		$'\b'      # backspace
-		# $'\n' # enter <-- ignore as this is an everyday normal character
-		# $'\t' # tab <-- ignore as this is an everyday normal character
-		$'\e[Z' # backtab
-
-		# styles.bash
-		$'\e[?1049h' # Default Screen Buffer
-		$'\e[?1049l' # Alternative Screen Buffer
-
-		# ansi escape codes
-		# https://terminals-wiki.org/wiki/index.php/CodeChart:ANSI/ESC/CSI
-		$'\e[A'    # Cursor Up
-		$'\e[0A'   # Cursor Up
-		$'\e[B'    # Cursor Down
-		$'\e[0B'   # Cursor Down
-		$'\e[C'    # Cursor Forward
-		$'\e[0C'   # Cursor Forward
-		$'\e[D'    # Cursor Back
-		$'\e[0D'   # Cursor Back
-		$'\e[E'    # Cursor Next Line
-		$'\e[0E'   # Cursor Next Line
-		$'\e[F'    # Cursor Previous Line
-		$'\e[0F'   # Cursor Previous Line
-		$'\e[G'    # Cursor Horizontal Absolute
-		$'\e[0G'   # Cursor Horizontal Absolute
-		$'\e[H'    # Cursor Position
-		$'\e[0H'   # Cursor Position
-		$'\e[0;H'  # Cursor Position
-		$'\e[0;0H' # Cursor Position
-		$'\e[I'    # Cursor Horizontal Tab
-		$'\e[0I'   # Cursor Horizontal Tab
-		$'\e[J'    # Erase Display
-		$'\e[0J'   # Erase Display
-		$'\e[K'    # Erase Line
-		$'\e[0K'   # Erase Line
-		$'\e[L'    # Insert Line
-		$'\e[0L'   # Insert Line
-		$'\e[M'    # Delete Line
-		$'\e[0M'   # Delete Line
-		$'\e[N'    # Erase Field
-		$'\e[0N'   # Erase Field
-		$'\e[O'    # Erase Area
-		$'\e[0O'   # Erase Area
-		$'\e[P'    # Delete Character
-		$'\e[0P'   # Delete Character
-		$'\e[Q'    # Select Editing Extent
-		$'\e[0Q'   # Select Editing Extent
-		$'\e[S'    # Scroll Up
-		$'\e[0S'   # Scroll Up
-		$'\e[T'    # Scroll Down
-		$'\e[0T'   # Scroll Down
-		$'\e[U'    # Next Page
-		$'\e[0U'   # Next Page
-		$'\e[V'    # Previous Page
-		$'\e[0V'   # Previous Page
-		$'\e[W'    # Cursor Tabulation Control
-		$'\e[0W'   # Cursor Tabulation Control
-		$'\e[X'    # Erase Character
-		$'\e[0X'   # Erase Character
-		$'\e[Y'    # Cursor Vertical Tab
-		$'\e[0Y'   # Cursor Vertical Tab
-		$'\e[Z'    # Cursor Backward Tab
-		$'\e[0Z'   # Cursor Backward Tab
-		$'\e[`'    # Horizontal Position Absolute
-		$'\e[0`'   # Horizontal Position Absolute
-		$'\e[a'    # Horizontal Position Right
-		$'\e[0a'   # Horizontal Position Right
-		$'\e[b'    # Repeat
-		$'\e[0b'   # Repeat
-		$'\e[c'    # Device Attributes
-		$'\e[0c'   # Device Attributes
-		$'\e[d'    # Vertical Position Absolute
-		$'\e[0d'   # Vertical Position Absolute
-		$'\e[e'    # Vertical Position Right
-		$'\e[0e'   # Vertical Position Right
-		$'\e[f'    # Horizontal Vertical Position
-		$'\e[0f'   # Horizontal Vertical Position
-		$'\e[g'    # Tabulation Clear
-		$'\e[0g'   # Tabulation Clear
-		$'\e[h'    # Set Mode
-		$'\e[0h'   # Set Mode
-		$'\e[i'    # Media Copy
-		$'\e[0i'   # Media Copy
-		$'\e[j'    # Horizontal Position Backward
-		$'\e[0j'   # Horizontal Position Backward
-		$'\e[k'    # Vertical Position Backward
-		$'\e[0k'   # Vertical Position Backward
-		$'\e[l'    # Reset Mode
-		$'\e[0l'   # Reset Mode
-		#$'\e[m' # Select Graphic Rendition <-- don't do this, as it is just colors
-		#$'\e[0m' # Select Graphic Rendition <-- don't do this, as it is just colors
-		$'\e[n'  # Device Status Report
-		$'\e[0n' # Device Status Report
-		$'\e[o'  # Define Area Qualifications
-		$'\e[0o' # Define Area Qualifications
-		# $'\e['    # Start Reversed String <-- don't do this, as it cannot be isolated
-		$'\e[0['  # Start Reversed String
-		$'\e\\'   # Parallel Texts
-		$'\e[0\\' # Parallel Texts
-		$'\e]'    # Start Directed String
-		$'\e[0]'  # Start Directed String
-		$'\e^'    # Select Implicit Movement Direction
-		$'\e[0^'  # Select Implicit Movement Direction
-
-		# https://www.gnu.org/software/screen/manual/html_node/Control-Sequences.html
-		$'\e7'  # Save Cursor
-		$'\e[s' # Save Cursor
-		$'\e8'  # Restore Cursor
-		$'\e[u' # Restore Cursor
-	)
-	outputs=()
-	for item in "${inputs[@]}"; do
-		outputs+=("$(printf '%s %q\n' 'yes:' "$item")")
-	done
-	__join --source={outputs} --delimiter=$'\n' --target={output}
-	eval-tester --name='testing shapeshift inputs' --stdout="$output" -- \
+	eval-tester --name='testing non-shapeshift inputs' --status=1 -- \
+		is-shapeshifter -- "${inputs_no_shapeshifters[@]}"
+	eval-tester --name='testing all inputs' -- \
+		is-shapeshifter -- "${inputs[@]}"
+	eval-tester --name='testing all inputs' --stdout="$output" -- \
 		is-shapeshifter --verbose -- "${inputs[@]}"
 
 	echo-style --g1="TEST: $0"
@@ -225,9 +113,9 @@ function is_shapeshifter() (
 			local input="$1"
 			if __is_shapeshifter -- "$input"; then
 				found='yes'
-				printf '%s %q\n' 'yes:' "$input"
+				printf '%s %q\n' 'yes' "$input"
 			else
-				printf '%s %q\n' 'no:' "$input"
+				printf '%s %q\n' 'no' "$input"
 			fi
 		}
 	fi
