huge WIP commit
- new `__do` and `__try`, instead of `eval_capture`
    - better coverage and tests, see `dorothy-internals`
    - more powerful API
- new `is-fs` helpers
- new `echo-wait` (maybe should rename to `echo-write`)
    - no longer needs sponge
    - more powerful API
    - moreutils as such is no longer a dorothy recommended dep
- auto-sudo escalation on nearly everything
    - new sudo/elevate/elevated args
- use FDs instead of device files where sensible to avoid linux divergence from macos
- ... todo

diff --git a/commands.beta/mail-sync b/commands.beta/mail-sync
--- a/commands.beta/mail-sync
+++ b/commands.beta/mail-sync
@@ -23,7 +23,7 @@ function mail_sync() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Uses imapsync to sync two mailboxes.
 
@@ -202,11 +202,11 @@ function mail_sync() (
 			echo-style --success='Success!'
 			break
 		elif [[ $__imapsync_status -eq 143 ]]; then
-			echo-style --error="Manually terminated [$__imapsync_status]..." >/dev/stderr
+			echo-style --stderr --error="Manually terminated [$__imapsync_status]..."
 			break
 			return "$__imapsync_status"
 		else
-			echo-style --warning="Failure with exit code [$__imapsync_status] restarting..." >/dev/stderr
+			echo-style --stderr --warning="Failure with exit code [$__imapsync_status] restarting..."
 		fi
 	done
 )
diff --git a/commands/alias-helper b/commands/alias-helper
--- a/commands/alias-helper
+++ b/commands/alias-helper
@@ -7,7 +7,7 @@ function alias_helper() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Wrappers around macOS aliases to make things easier.
 
@@ -89,33 +89,33 @@ function alias_helper() (
 	function do_verify {
 		local path="$1" alias
 		if [[ -L $path ]]; then
-			echo-style --bold+red="$path" ' ' --error='<- origin is a symlink not an alias' >/dev/stderr
+			echo-style --stderr --bold+red="$path" ' ' --error='<- origin is a symlink not an alias'
 			return 22 # EINVAL 22 Invalid argument
 		elif [[ -e $path ]]; then
-			eval_capture --stdoutvar=alias -- get_alias_origin "$path"
+			__do --redirect-stdout={alias} -- get_alias_origin "$path"
 			if [[ -n $alias ]]; then
 				# don't output anything, we are just verifying
 				return 0
 			else
-				echo-style --bold+red="$path" ' ' --error='<- origin is not an alias' >/dev/stderr
+				echo-style --stderr --bold+red="$path" ' ' --error='<- origin is not an alias'
 				return 22 # EINVAL 22 Invalid argument
 			fi
 		else
-			echo-style --bold+red="$path" ' ' --error='<- origin does not exist' >/dev/stderr
+			echo-style --stderr --bold+red="$path" ' ' --error='<- origin does not exist'
 			return 22 # EINVAL 22 Invalid argument
 		fi
 	}
 
 	function do_target {
 		local path="$1" target verify_status
-		eval_capture --statusvar=verify_status -- do_verify "$path"
+		__do --redirect-status={verify_status} -- do_verify "$path"
 		if [[ $verify_status -eq 0 ]]; then
-			eval_capture --stdoutvar=target -- get_alias_target "$path"
+			__do --redirect-stdout={target} -- get_alias_target "$path"
 			if [[ -n $target ]]; then
 				__print_lines "$target" # output the target from the origin
 				return 0
 			else
-				echo-style --bold+red="$path" ' ' --error='<- alias target is broken' >/dev/stderr
+				echo-style --stderr --bold+red="$path" ' ' --error='<- alias target is broken'
 				return 22 # EINVAL 22 Invalid argument
 			fi
 		fi
@@ -125,29 +125,29 @@ function alias_helper() (
 		local path="$1" origin target
 
 		# verify
-		eval_capture --stdoutvar=origin -- get_alias_origin "$path"
+		__do --redirect-stdout={origin} -- get_alias_origin "$path"
 		if [[ -z $origin ]]; then
-			echo-style \
+			echo-style --stderr \
 				--bold+red="$path" \
 				$'\t' \
-				$'\t' --error='← not an alias' >/dev/stderr
+				$'\t' --error='← not an alias'
 			return 22 # EINVAL 22 Invalid argument
 		fi
 
 		# target
-		eval_capture --stdoutvar=target -- get_alias_target "$path"
+		__do --redirect-stdout={target} -- get_alias_target "$path"
 		if [[ -z $target ]]; then
-			echo-style \
+			echo-style --stderr \
 				--bold="$origin" \
 				$'\t' \
-				$'\t' --error='← target broken' >/dev/stderr
+				$'\t' --error='← target broken'
 			return 9 # EBADF 9 Bad file descriptor
 		fi
 		if [[ ! -e $target ]]; then
-			echo-style \
+			echo-style --stderr \
 				--bold="$origin" \
 				--nocolor=$'\t' --color+dim=$'\t→\t' --bold+red="$target" \
-				$'\t' --error='← target missing' >/dev/stderr
+				$'\t' --error='← target missing'
 			return 2 # ENOENT 2 No such file or directory
 		fi
 
@@ -192,20 +192,20 @@ function alias_helper() (
 		local path="$1" origin target
 
 		# verify alias
-		eval_capture --stdoutvar=origin -- get_alias_origin "$path"
+		__do --redirect-stdout={origin} -- get_alias_origin "$path"
 		if [[ -z $origin ]]; then
-			echo-style --bold+red="$path" ' ' --error='<- not an alias' >/dev/stderr
+			echo-style --stderr --bold+red="$path" ' ' --error='<- not an alias'
 			return 22 # EINVAL 22 Invalid argument
 		fi
 
 		# verify target
-		eval_capture --stdoutvar=target -- get_alias_target "$path"
+		__do --redirect-stdout={target} -- get_alias_target "$path"
 		if [[ -z $target ]]; then
-			echo-style --bold="$origin" --dim=' → ' --bold+red="$target" ' ' --error='← target broken' >/dev/stderr
+			echo-style --stderr --bold="$origin" --dim=' → ' --bold+red="$target" ' ' --error='← target broken'
 			return 9 # EBADF 9 Bad file descriptor
 		fi
 		if [[ ! -e $target ]]; then
-			echo-style --bold="$origin" --dim=' → ' --bold+red="$target" ' ' --error='← target missing' >/dev/stderr
+			echo-style --stderr --bold="$origin" --dim=' → ' --bold+red="$target" ' ' --error='← target missing'
 			return 2 # ENOENT 2 No such file or directory
 		fi
 
diff --git a/commands/btrfs-helper b/commands/btrfs-helper
--- a/commands/btrfs-helper
+++ b/commands/btrfs-helper
@@ -7,7 +7,7 @@ function btrfs_helper() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Wrappers around btrfs to make things easier.
 
@@ -240,11 +240,11 @@ function btrfs_helper() (
 
 		# validate
 		if [[ $existing_node == "$extra_node" ]]; then
-			echo-style --error='You cannot add the same device to itself.' >/dev/stderr
+			echo-style --stderr --error='You cannot add the same device to itself.'
 			return 22 # EINVAL 22 Invalid argument
 		fi
 		if [[ $existing_uuid == "$extra_uuid" ]]; then
-			echo-style --error='The device is already part of the intended filesystem.' >/dev/stderr
+			echo-style --stderr --error='The device is already part of the intended filesystem.'
 			return 22 # EINVAL 22 Invalid argument
 		fi
 
diff --git a/commands/choose b/commands/choose
--- a/commands/choose
+++ b/commands/choose
@@ -628,7 +628,7 @@ function choose_() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Prompt the user to select an item from the menu, in a clean and robust way.
 
@@ -876,7 +876,7 @@ function choose_() (
 					"${style__error}The amount of <label>s must match the amount of <value>s. See [$0 --help] for usage.${style__end__error}" \
 					"${style__notice}Provide an even amount of items to ensure there is a <label> for each <value>:${style__end__notice}"
 				echo-verbose -- "${inputs[@]}"
-			} >/dev/stderr
+			} >&2
 			return 22 # EINVAL 22 Invalid argument
 		fi
 	fi
@@ -893,7 +893,7 @@ function choose_() (
 			VALUE="${inputs[index]}"
 			LABEL="$VALUE"
 			if [[ -z $VALUE ]]; then
-				__print_lines "${style__error}The $INDEX item at index $index was empty, all items must be non-empty.${style__end__error}" >/dev/stderr
+				__print_lines "${style__error}The $INDEX item at index $index was empty, all items must be non-empty.${style__end__error}" >&2
 				return 22 # EINVAL 22 Invalid argument
 			fi
 		else
@@ -904,11 +904,11 @@ function choose_() (
 				VALUE="${inputs[index + 1]}"
 				LABEL="${inputs[index]}"
 			else
-				__print_lines "${style__error}Invalid label option [$option_label], it must be no, yes, or first.${style__end__error}" >/dev/stderr
+				__print_lines "${style__error}Invalid label option [$option_label], it must be no, yes, or first.${style__end__error}" >&2
 				return 22 # EINVAL 22 Invalid argument
 			fi
 			if [[ -z $LABEL || -z $VALUE ]]; then
-				__print_lines "${style__error}Invalid label=[$LABEL] value=[$VALUE] combination, both must be non-empty.${style__end__error}" >/dev/stderr
+				__print_lines "${style__error}Invalid label=[$LABEL] value=[$VALUE] combination, both must be non-empty.${style__end__error}" >&2
 				return 22 # EINVAL 22 Invalid argument
 			fi
 		fi
@@ -920,7 +920,7 @@ function choose_() (
 			VISUAL="$LABEL"
 		fi
 		if [[ -z $VISUAL ]]; then
-			__print_lines "${style__error}Invalid visual=[$VISUAL] for label=[$LABEL] value=[$VALUE], all must be non-empty.${style__end__error}" >/dev/stderr
+			__print_lines "${style__error}Invalid visual=[$VISUAL] for label=[$LABEL] value=[$VALUE], all must be non-empty.${style__end__error}" >&2
 			return 22 # EINVAL 22 Invalid argument
 		fi
 		items+=("$VISUAL")
@@ -930,7 +930,7 @@ function choose_() (
 			RETURN="$VALUE"
 		fi
 		if [[ -z $RETURN ]]; then
-			__print_lines "${style__error}Invalid return=[$RETURN] for label=[$LABEL] value=[$VALUE] visual=[$VISUAL], all must be non-empty.${style__end__error}" >/dev/stderr
+			__print_lines "${style__error}Invalid return=[$RETURN] for label=[$LABEL] value=[$VALUE] visual=[$VISUAL], all must be non-empty.${style__end__error}" >&2
 			return 22 # EINVAL 22 Invalid argument
 		fi
 		returns+=("$RETURN")
@@ -942,7 +942,7 @@ function choose_() (
 			for MATCH in "${option_matches[@]}"; do
 				eval "MATCH=\"$MATCH\""
 				if [[ -z $MATCH ]]; then
-					__print_lines "${style__error}Invalid match=[$MATCH] for label=[$LABEL] value=[$VALUE] visual=[$VISUAL] return=[$RETURN], all must be non-empty.${style__end__error}" >/dev/stderr
+					__print_lines "${style__error}Invalid match=[$MATCH] for label=[$LABEL] value=[$VALUE] visual=[$VISUAL] return=[$RETURN], all must be non-empty.${style__end__error}" >&2
 					return 22 # EINVAL 22 Invalid argument
 				fi
 
@@ -1042,7 +1042,6 @@ function choose_() (
 		text__pick_confirm \
 		terminal_columns_prior=-1 \
 		terminal_columns \
-		terminal_device_file \
 		terminal_margin=0 \
 		terminal_lines_prior=-1 \
 		terminal_lines \
@@ -1069,13 +1068,12 @@ function choose_() (
 	fi
 
 	# prepare paging
-	terminal_device_file="$(get-terminal-device-file)"
 	if ! get-terminal-size-support --quiet; then
 		# fix [tput: No value for $TERM and no -T specified] errors when fetching columns and rows on CI
 		paging_supported='no'
 	fi
 	if ! get-terminal-title-support --quiet; then
-		# [ssh -T ...] passes [! -t 0] ["$terminal_device_file" = '/dev/stderr'] [__command_exists tput]
+		# [ssh -T ...] passes [! -t 0] ["$TERMINAL_DEVICE_FILE" = '/dev/stderr'] [__command_exists tput]
 		title_supported='no'
 	fi
 
@@ -1272,7 +1270,7 @@ function choose_() (
 		}
 	else
 		function reset_terminal_modifications_now {
-			__print_string "$style__show_cursor$style__default_screen_buffer" >"$terminal_device_file"
+			__do --redirect-stdout=tty -- __print_string "$style__show_cursor$style__default_screen_buffer"
 			trap - EXIT
 		}
 		function reset_terminal_modifications_on_exit {
@@ -1650,7 +1648,7 @@ function choose_() (
 			then
 				menu_skip_render='yes'
 				menu_mode='choose'
-				__print_string "$style__bell" >"$terminal_device_file"
+				__do --redirect-stdout=tty -- __print_string "$style__bell"
 				return 0
 			fi
 		fi
@@ -2119,13 +2117,13 @@ function choose_() (
 		else
 			terminal_title+="${style__terminal_title}👉 ${verb} ${verb_total} of ${items_count} items 👈${style__end__terminal_title}"
 		fi
-		printf '%s' "${style__clear_screen}${style__hide_cursor}${terminal_title}${menu_title}${menu_body}${bar_top_content}${bar_middle_content}${items_bundled}${bar_bottom_content}${menu_legend_content}" >"$terminal_device_file"
+		__do --redirect-stdout=tty -- printf '%s' "${style__clear_screen}${style__hide_cursor}${terminal_title}${menu_title}${menu_body}${bar_top_content}${bar_middle_content}${items_bundled}${bar_bottom_content}${menu_legend_content}"
 		if [[ -n $menu_resized_lines ]]; then
 			refresh_terminal_size
 			if [[ $terminal_too_short == 'yes' ]]; then
 				terminal_title="${style__terminal_title}‼️ TERMINAL TOO SHORT ‼️${style__end__terminal_title}"
 				local additional_rows="$((menu_resized_lines - terminal_lines))"
-				printf '%s' "${style__clear_screen}${style__hide_cursor}${terminal_title}${style__error}You have been prompted to make a menu selection, however the terminal does not have enough vertical height to make that selection.${style__end__error}"$'\n'"${style__notice}Increase the terminal height or reduce font size to proceed, then press any key.${style__end__notice}"$'\n'"Terminal rows = ${terminal_lines}, Needed rows = ${menu_resized_lines}, Additional rows = ${additional_rows}"$'\n' >"$terminal_device_file"
+				__do --redirect-stdout=tty -- printf '%s' "${style__clear_screen}${style__hide_cursor}${terminal_title}${style__error}You have been prompted to make a menu selection, however the terminal does not have enough vertical height to make that selection.${style__end__error}"$'\n'"${style__notice}Increase the terminal height or reduce font size to proceed, then press any key.${style__end__notice}"$'\n'"Terminal rows = ${terminal_lines}, Needed rows = ${menu_resized_lines}, Additional rows = ${additional_rows}"$'\n'
 			fi
 		fi
 	}
@@ -2154,10 +2152,10 @@ function choose_() (
 					done
 				fi
 				# inform
-				__print_string "$render" >"$terminal_device_file"
+				__do --redirect-stdout=tty -- __print_string "$render"
 			elif [[ -n $commentary ]]; then
 				# inform to stderr, consistent with ask, choose, confirm
-				__print_string "$render" >/dev/stderr
+				__print_string "$render" >&2
 			fi
 			# stdout
 			for index in "${selected_indexes[@]}"; do
@@ -2169,9 +2167,9 @@ function choose_() (
 			# inform
 			if [[ -n $commentary ]]; then
 				if [[ $option_linger == 'yes' ]]; then
-					__print_string "$render" >"$terminal_device_file"
+					__do --redirect-stdout=tty -- __print_string "$render"
 				else
-					__print_string "$render" >/dev/stderr
+					__print_string "$render" >&2
 				fi
 			fi
 			return "$menu_status"
@@ -2184,15 +2182,15 @@ function choose_() (
 			printf '' >debug.txt
 		fi
 		message="$(printf '%q ' "$@" "c=${debug_counter}")"
-		printf '%s' "${style__terminal_title}${message}${style__end__terminal_title}" >"$terminal_device_file"
+		__do --redirect-stdout=tty -- printf '%s' "${style__terminal_title}${message}${style__end__terminal_title}"
 		printf '%s\n' "$message" >>debug.txt
 		debug_counter="$((debug_counter + 1))"
 	}
 	function handle_menu {
-		local input read_status keys skips
+		local read_status input keys skips
 		# action
 		reset_terminal_modifications_on_exit
-		__print_string "$style__alternative_screen_buffer" >"$terminal_device_file"
+		__do --redirect-stdout=tty -- __print_string "$style__alternative_screen_buffer"
 		while :; do
 			# (re-)render the menu?
 			if [[ $menu_skip_render == 'no' ]]; then
@@ -2201,7 +2199,8 @@ function choose_() (
 			menu_skip_render='no'
 
 			# handle the response
-			eval_capture --statusvar=read_status --stdoutvar=input -- read-key --timeout="$option_timeout"
+			__do --redirect-status={read_status} --redirect-stdout={input} -- \
+				read-key --timeout="$option_timeout"
 			if [[ $read_status -eq 60 ]]; then
 				if [[ $selected_count -ne 0 ]]; then
 					# default
@@ -2225,7 +2224,7 @@ function choose_() (
 			elif [[ $read_status -eq 94 ]]; then
 				# unknown character, send bell and continue
 				menu_skip_render='yes'
-				__print_string "$style__bell" >"$terminal_device_file"
+				__do --redirect-stdout=tty -- __print_string "$style__bell"
 				continue
 			elif [[ $read_status -ne 0 ]]; then
 				# failure
@@ -2356,7 +2355,7 @@ function choose_() (
 			if [[ ${#skips[@]} -eq ${#keys[@]} ]]; then
 				# all were unknown characters, send bell and continue
 				menu_skip_render='yes'
-				__print_string "$style__bell" >"$terminal_device_file"
+				__do --redirect-stdout=tty -- __print_string "$style__bell"
 				continue
 			fi
 
diff --git a/commands/fs-structure b/commands/fs-structure
--- a/commands/fs-structure
+++ b/commands/fs-structure
@@ -34,7 +34,7 @@ function fs_structure() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Output the structure of a directory path.
 
@@ -203,7 +203,7 @@ function fs_structure() (
 
 		# just -e is faulty, as -e fails on broken symlinks
 		if is-missing --sudo="$option_sudo" --user="$option_user" --group="$option_group" -- "$input"; then
-			echo-style --error1='The path is missing: ' --code-error1="$input" >/dev/stderr
+			echo-style --stderr --error1='The path is missing: ' --code-error1="$input"
 			return 2 # ENOENT 2 No such file or directory
 		fi
 
diff --git a/commands/setup-ruby b/commands/setup-ruby
--- a/commands/setup-ruby
+++ b/commands/setup-ruby
@@ -35,7 +35,7 @@ function setup_ruby() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			Setup the Ruby ecosystem.
 
 			USAGE:
@@ -135,7 +135,7 @@ function setup_ruby() (
 	echo-style --h2='Reload paths'
 	source "$DOROTHY/sources/environment.sh"
 	if __command_missing -- gem; then
-		echo-style --error2='Unable to find [gem] executable, so cannot proceed... ❌' >/dev/stderr
+		echo-style --stderr --error2='Unable to find [gem] executable, so cannot proceed... ❌'
 		return 1
 	fi
 	# @todo style with var_dump or something
diff --git a/commands/sudo-helper b/commands/sudo-helper
--- a/commands/sudo-helper
+++ b/commands/sudo-helper
@@ -2,33 +2,71 @@
 
 function sudo_helper() (
 	source "$DOROTHY/sources/bash.bash"
-	source "$(type -P eval-helper)" # enable eval_helper
 
 	# =====================================
 	# Arguments
 
+	# NOTE:
+
+	# [sudo] and [doas] asks for your own password, not the target users password
+	# [su] asks for the target user password
+	# [sudo] and [doas] can be configured via their configuration files to target other users, not just [root]
+
+	# EXAMPLE:
+
+	# with this sudoers configuration file
+	# developer ALL=(root,webuser) /a-special-echo arg1 arg2
+
+	# and with /a-special-echo only being executable to [root] and [webuser]:
+	# sudo chown root:webuser /a-special-echo
+	# sudo chmod 750 /a-special-echo
+
+	# if you are [webuser], you can run this without escalation (not because of sudoers, but because of the file-system permissions):
+	# /a-special-echo arg1 arg2
+
+	# if you are [someuser], you will be denied ability to run this (not because of sudoers, but because of the file-system permissions):
+	# /a-special-echo arg1 arg2
+	# and if that was the only configuration in sudoers, you would also be denied escalation to [root] or [webuser]
+
+	# if you are [developer], you will be denied ability to run this (not because of sudoers, but because of the file-system permissions):
+	# /a-special-echo arg1 arg2
+	# however, sudoers will allow [developer] to escalate to [root] or [webuser]:
+	# sudo /a-special-echo arg1 arg2
+	# sudo -u webuser /a-special-echo arg1 arg2
+
+	# TERMINOLOGY
+
+	# "privilege escalation" is a bad thing: https://en.wikipedia.org/wiki/Privilege_escalation
+	# use elevation/grant/authorise when it is good thing: https://en.wikipedia.org/wiki/Privilege_elevation
+
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
-			Run the command with escalation to root, be it via sudo or doas, or neither if not needed.
+			Run the command with privilege elevation, be it via sudo or doas, or neither if not needed.
 
 			USAGE:
 			sudo-helper [...options] -- <command> [...args]
 			sudo-helper --local
 
 			OPTIONS:
-			--reason=<reason>
-			    If a prompt is required for your sudo/root/login password, this reason will be used to explain why escalation was required.
-
-			--sudo=<YES|no|''|failure|<exit-status>>
-			    If specified as yes, the default, then the command will be escalated to root.
-			    If specified as no or empty string, then the command will be run without escalation.
-			    If specified as failure, then the command will be run without escalation, and if it fails, it will be run with escalation.
-			    If specified as an integer, then the command will be run without escalation, and if it fails with that exit status, it will be run with escalation.
+			--elevated=<file|device-file|fd>
+			    If specified, append [yes] to this target if the command required elevation.
+			--elevate=<YES|no|''|failure|<exit-status>> | --sudo=<...>
+			    If specified as yes, then the command will be elevated.
+			    If <user> or <group> is specified, the remaining alternatives are discarded:
+			    If specified as no, then the command will be run without elevation.
+			    If specified as failure, then the command will be run without elevation, and if it fails, it will be run with elevation.
+			    If specified as an integer, then the command will be run without elevation, and if it fails with that exit status, it will be run with elevation.
+			    This can be specified multiple times, in which a [yes] or [no] value will reset prior values.
+			    It can be [\n\t ,|] separated.
+			    If this is not specified at all, it will default to [yes].
+			    If this is specified as an empty string, it will default to [no].
 			--user=<user>
 			    Specify a user to run the command as. Forces --sudo=yes
 			--group=<group>
 			    Specify a group to run the command as. Forces --sudo=yes
+			--reason=<reason>
+			    If a prompt is required to momentarily grant privileges, this reason will be used to explain why elevation was required.
 
 			--inherit
 			    If enabled, inherit environment variables include PATH.
@@ -52,7 +90,16 @@ function sudo_helper() (
 
 	# process
 	# option_quiet='no' is an important default to ensure our call to eval-helper can still be interpolated
-	local item option_cmd=() option_quiet='no' option_reason='' option_user='' option_group='' option_sudo='yes' option_confirm='no' option_wrap='no' option_inherit='no' option_local=''
+	local item option_cmd=() option_quiet='no' option_elevated='' option_elevate=() option_user='' option_group='' option_reason='' option_confirm='no' option_wrap='no' option_inherit='no' option_local=''
+	function parse_sudo_arg_value {
+		local sudo_arg="$1" sudo_args=()
+		if [[ -z $sudo_arg ]]; then
+			option_elevate+=('')
+		else
+			mapfile -t sudo_args < <(echo-split --characters=$'\n\t ,|' -- "$sudo_arg")
+			option_elevate+=("${sudo_args[@]}")
+		fi
+	}
 	while [[ $# -ne 0 ]]; do
 		item="$1"
 		shift
@@ -64,12 +111,11 @@ function sudo_helper() (
 		'--no-quiet'* | '--quiet'*)
 			option_quiet="$(get-flag-value --affirmative --fallback="$option_quiet" -- "$item")"
 			;;
-		'--reason='*) option_reason="${item#*=}" ;;
-		'--no-sudo'* | '--sudo'*)
-			option_sudo="$(get-flag-value --affirmative --fallback="$option_sudo" -- "$item")"
-			;;
+		'--elevated='*) option_elevated="${item#*=}" ;;
+		'--no-elevate'* | '--elevate'* | '--no-sudo'* | '--sudo'*) parse_sudo_arg_value "$(get-flag-value --affirmative -- "$item")" ;;
 		'--user='*) option_user="${item#*=}" ;;
 		'--group='*) option_group="${item#*=}" ;;
+		'--reason='*) option_reason="${item#*=}" ;;
 		'--no-inherit'* | '--inherit'*)
 			option_inherit="$(get-flag-value --affirmative --fallback="$option_inherit" -- "$item")"
 			;;
@@ -132,10 +178,51 @@ function sudo_helper() (
 	fi
 
 	# ensure sudo is a valid value
-	if [[ -n $option_user || -n $option_user ]]; then
-		option_sudo='yes'
-	elif [[ -z $option_sudo ]]; then
-		option_sudo='no'
+	local elevate='' elevate_on_statuses=()
+	if [[ -n $option_user || -n $option_group ]]; then
+		# validate user and group, user is important, as otherwise we will be creating directories for users that don't exist
+		if [[ -n $option_user ]] && ! is-user -- "$option_user"; then
+			echo-style --stderr --error1='Cannot elevate privileges to a non-existent user: ' --code-error1="$option_user"
+			return 2 # ENOENT 2 No such file or directory
+		fi
+		if [[ -n $option_group ]] && ! is-group -- "$option_group"; then
+			echo-style --stderr --error1='Cannot elevate privileges to a non-existent group: ' --code-error1="$option_group"
+			return 2 # ENOENT 2 No such file or directory
+		fi
+		elevate='yes'
+	elif [[ ${#option_elevate[@]} -eq 0 ]]; then
+		elevate='yes'
+	elif [[ -z ${option_elevate[*]} ]]; then
+		elevate='no'
+	else
+		elevate='no'
+		for item in "${option_elevate[@]}"; do
+			case "$item" in
+			'') : ;; # discard, it's already served its purpose in now defaulting to disabled
+			'yes')
+				elevate='yes'
+				elevate_on_statuses=()
+				;;
+			'no')
+				elevate='no'
+				elevate_on_statuses=()
+				;;
+			'failure')
+				elevate='failure'
+				elevate_on_statuses=()
+				;;
+			[0-9]*)
+				if ! is-integer -- "$item"; then
+					help "An unrecognised value was provided for --sudo: $item"
+				fi
+				elevate='status'
+				elevate_on_statuses+=("$item")
+				;;
+			*)
+				help "An unrecognised value was provided for --sudo: $item"
+				;;
+			esac
+		done
 	fi
 
 	# =====================================
@@ -175,19 +262,30 @@ function sudo_helper() (
 	fi
 
 	# try without sudo
-	if [[ $option_sudo == 'no' || $technique == 'none' ]]; then
+	if [[ $elevate == 'no' || $technique == 'none' ]]; then
 		__wrap "${option_cmd[@]}"
 		return
-	elif [[ $option_sudo == 'failure' ]]; then
+	elif [[ $elevate == 'failure' ]]; then
 		if __wrap "${option_cmd[@]}"; then
 			return 0
 		fi
-	elif is-integer -- "$option_sudo"; then
+	elif [[ $elevate == 'status' ]]; then
 		local status=0
 		__wrap "${option_cmd[@]}" || status=$?
-		if [[ $status -eq 0 || $status -ne $option_sudo ]]; then
+		for item in "${elevate_on_statuses[@]}"; do
+			if [[ $status -eq $item ]]; then
+				elevate='yes'
+				break
+			fi
+		done
+		if [[ $elevate != 'yes' ]]; then
 			return "$status"
 		fi
+	fi
+
+	# if desired, note that it needed elevation
+	if [[ -n $option_elevated ]]; then
+		__do --redirect-stdout="$option_elevated" -- __print_lines 'yes'
 	fi
 
 	# prep sudo execution
@@ -195,6 +293,16 @@ function sudo_helper() (
 	local sudo_cmd=() home=''
 	if [[ $technique == 'sudo' ]]; then
 		sudo_cmd+=('sudo')
+
+		# if no-tty, then use the builtin sudo workaround which is the same as Dorothy's
+		# if ! __has_tty_support; then
+		# 	sudo_cmd+=('--stdin') # note tha this outputs what they are typing unconcealed to terminal
+		# 	# alternative is this insecure option: export SUDO_ASKPASS=...; sudo_cmd+=('--askpass')
+		# 	# as this is an edge case in what is meant to be non-interactive environments, this is fine
+		# fi
+		# ^ don't enable this yet, until someone requests it, I don't know the implications
+
+		# add the things specific to attestation, while prepping home
 		# don't use is-directory, is-missing, __sudo_mkdirp, as they will cause infinite recursion
 		if [[ -n $option_user ]]; then
 			sudo_cmd+=("--user=$option_user")
@@ -209,30 +317,13 @@ function sudo_helper() (
 		elif [[ -n $HOME ]]; then
 			home="$HOME"
 		fi
-
 		if [[ -n $option_group ]]; then
 			sudo_cmd+=("--group=$option_group")
 		fi
 
-		if [[ -n $home ]]; then
-			if [[ ! -e $home && ! -L $home ]]; then
-				sudo mkdir -p -- "$home"
-				fs-own --quiet --user="$option_user" --group="$option_group" --no-recursive -- "$home"
-			fi
-			sudo_cmd+=('--set-home')
-		fi
-
-		if [[ $option_inherit == 'yes' ]]; then
-			sudo_cmd+=(
-				'--preserve-env'
-				'env'
-				"PATH=$PATH"
-			)
-		fi
-
 		# check if password is required
 		# [sudo --validate] doesn't work on multipass, so just use [true] as a no-op
-		if ! sudo --non-interactive true &>/dev/null; then
+		if ! "${sudo_cmd[@]}" --non-interactive -- true &>/dev/null; then
 			# password is required, let the user know what they are being prompted for
 			# [--code=*] better than [echo-style --element/="$(echo-escape-command -- "${sudo_cmd[@]}" | echo-join ' ' --stdin)"] as that is too verbose
 			# use [--tty] to ensure the prompt is not hidden when otherwise hiding sudo output, such as in [command-working]
@@ -240,9 +331,36 @@ function sudo_helper() (
 			if [[ -n $option_reason ]]; then
 				echo-style --tty --notice="$option_reason"
 			else
-				echo-style --tty --notice='Your sudo/root/login password is required to execute the command:'
+				echo-style --tty --notice='Your password is required to momentarily grant privileges to execute the command:'
 			fi
 			option_wrap='yes'
+		fi
+
+		# add the things specific to the command
+		if [[ -n $home ]]; then
+			if [[ ! -e $home && ! -L $home ]]; then
+				sudo mkdir -p -- "$home" # don't use __sudo_mkdirp as that calls __try_sudo which calls this
+				fs-own --quiet --user="$option_user" --group="$option_group" --no-recursive -- "$home"
+			fi
+			sudo_cmd+=('--set-home')
+		fi
+
+		# sudo supports passing environment variables
+		if [[ $option_inherit == 'yes' ]]; then
+			sudo_cmd+=(
+				'--preserve-env'
+				"PATH=$PATH"
+				--
+			)
+			# if it is linux, [sudo PATH=$PATH] doesn't seem to work, but [env PATH=$PATH] does, so just duplicate it
+			if is-linux; then
+				sudo_cmd+=(
+					'env'
+					"PATH=$PATH"
+				)
+			fi
+		else
+			sudo_cmd+=(--)
 		fi
 	elif [[ $technique == 'doas' ]]; then
 		# https://man.archlinux.org/man/doas.1.en
@@ -256,6 +374,7 @@ function sudo_helper() (
 		if [[ -n $option_group ]]; then
 			help 'doas does not support --group'
 		fi
+		# doas doesn't support ENVVAR=value, nor --
 		if [[ $option_inherit == 'yes' ]]; then
 			sudo_cmd+=(
 				'env'
diff --git a/commands/symlink-helper b/commands/symlink-helper
--- a/commands/symlink-helper
+++ b/commands/symlink-helper
@@ -71,10 +71,11 @@ function symlink_helper() (
 
 	# check
 	function help_missing {
-		echo-style --error='FAILURE:' --newline \
+		echo-style --stderr \
+			--error='FAILURE:' --newline \
 			'The path to be symlinked ' --code="$option_target" " doesn't actually exist." --newline \
 			'As such, we cannot create a symlink at ' --code="$option_symlink" ' pointing to it.' --newline \
-			'Create the path at ' --code="$option_target" ' first, then try again.' >/dev/stderr
+			'Create the path at ' --code="$option_target" ' first, then try again.'
 		return 2 # ENOENT 2 No such file or directory
 	}
 	if [[ -z $option_target ]]; then
@@ -121,7 +122,7 @@ function symlink_helper() (
 			original="$option_target"
 			option_target="$(fs-realpath -- "$option_target")"
 			if [[ -z $option_quiet || $option_quiet == 'no' ]]; then
-				echo-style --bold='💁‍♀️ Target ' --code="$original" --bold=' redirects to ' --code="$option_target" --bold=' 👉 using the redirection...' >/dev/stderr
+				echo-style --stderr --bold='💁‍♀️ Target ' --code="$original" --bold=' redirects to ' --code="$option_target" --bold=' 👉 using the redirection...'
 			fi
 			continue
 		fi
@@ -140,22 +141,22 @@ function symlink_helper() (
 		if [[ -L $option_symlink ]]; then
 			if [[ "$(fs-realpath -- "$option_symlink")" == "$option_target" ]]; then
 				if [[ $option_quiet == 'no' ]]; then
-					echo-style --bold='👍 Symlink already created at ' --code="$option_symlink" --bold=' targetting ' --code="$option_target" >/dev/stderr
+					echo-style --stderr --bold='👍 Symlink already created at ' --code="$option_symlink" --bold=' targetting ' --code="$option_target"
 				fi
 				return 0
 			fi
 			if [[ -z $option_quiet || $option_quiet == 'no' ]]; then
-				echo-style --bold='💁‍♀️ Symlink already exists at ' --code="$option_symlink" --bold=' 👉 recreating...' >/dev/stderr
+				echo-style --stderr --bold='💁‍♀️ Symlink already exists at ' --code="$option_symlink" --bold=' 👉 recreating...'
 			fi
 			# is a symlink but a different target, drop it and recreate
-			rm -f -- "$option_symlink" >/dev/stderr
+			rm -f -- "$option_symlink" >&2
 		else
 			# not a symlink, confirm with the user what to do
-			fs-rm --quiet="$option_quiet" --confirm -- "$option_symlink" >/dev/stderr
+			fs-rm --quiet="$option_quiet" --confirm -- "$option_symlink" >&2
 		fi
 	elif [[ -L $option_symlink ]]; then
 		# is a broken symlink, drop it and recreate
-		rm -f -- "$option_symlink" >/dev/stderr
+		rm -f -- "$option_symlink" >&2
 	fi
 
 	# create the symlink
@@ -165,14 +166,14 @@ function symlink_helper() (
 	if is-alpine; then
 		# alpine doesn't support -F, however the above removals should make it unnecessary
 		# https://github.com/bevry/dorothy/actions/runs/11323459946/job/31486170602#step:4:11
-		ln -sf -- "$option_target" "$option_symlink" >/dev/stderr
+		ln -sf -- "$option_target" "$option_symlink" >&2
 	else
-		ln -sfF -- "$option_target" "$option_symlink" >/dev/stderr
+		ln -sfF -- "$option_target" "$option_symlink" >&2
 	fi
 
 	# log result to stderr
 	if [[ -z $option_quiet || $option_quiet == 'no' ]]; then
-		echo-style --success='👍 Symlink created at ' --code="$option_symlink" --bold=' targetting ' --code="$option_target" >/dev/stderr
+		echo-style --stderr --success='👍 Symlink created at ' --code="$option_symlink" --bold=' targetting ' --code="$option_target"
 	fi
 )
 
