conventions: ec => status

diff --git a/commands.beta/mail-sync b/commands.beta/mail-sync
--- a/commands.beta/mail-sync
+++ b/commands.beta/mail-sync
@@ -189,24 +189,24 @@ function mail_sync() (
 	# act and continue until success
 	# --usecache
 	# --useuid
-	local ec
+	local imapsync_status
 	while true; do
-		ec=0 && imapsync \
+		imapsync_status=0 && imapsync \
 			--automap \
 			--skipcrossduplicates \
 			--addheader --useheader 'Message-Id' \
 			--syncinternaldates \
 			--nofoldersizes --nofoldersizesatend --no-modulesversion --nolog \
-			"${args[@]}" || ec="$?"
-		if test "$ec" -eq 0; then
+			"${args[@]}" || imapsync_status="$?"
+		if test "$imapsync_status" -eq 0; then
 			echo-style --success='Success!'
 			break
-		elif test "$ec" -eq 143; then
-			echo-style --error="Manually terminated [$ec]..."
+		elif test "$imapsync_status" -eq 143; then
+			echo-style --error="Manually terminated [$imapsync_status]..."
 			break
-			return "$ec"
+			return "$imapsync_status"
 		else
-			echo-style --warning="Failure with exit code [$ec] restarting..."
+			echo-style --warning="Failure with exit code [$imapsync_status] restarting..."
 		fi
 	done
 )
diff --git a/commands/ask b/commands/ask
--- a/commands/ask
+++ b/commands/ask
@@ -158,15 +158,15 @@ function ask() (
 		fi
 	}
 	function do_ask { # has sideffects: RESULT, ASKED
-		local ec
+		local read_status
 		tty_auto
 		ASKED='yes' # not lcoal
 		if test -n "${1-}"; then
 			print_line "$1" >/dev/tty
 		fi
 		while true; do
-			ec=0 && read -r -t 300 -r -p '> ' RESULT || ec=$?
-			if test "$ec" -eq 142; then
+			read_status=0 && read -r -t 300 -r -p '> ' RESULT || read_status=$?
+			if test "$read_status" -eq 142; then
 				return 60 # ETIMEDOUT 60 Operation timed out
 			fi
 			if is-value "$RESULT"; then
@@ -179,7 +179,7 @@ function ask() (
 		do_validate
 	}
 	function do_validate {
-		local ec choice choices=()
+		local choose_status ask_status choice choices=()
 		if is-value "$RESULT"; then
 			# we have a value, so go for it
 			if test "$option_confirm" != 'yes'; then
@@ -217,21 +217,21 @@ function ask() (
 		fi
 
 		# ask
-		eval_capture --statusvar=ec --stdoutvar=choice -- \
+		eval_capture --statusvar=choose_status --stdoutvar=choice -- \
 			choose-option \
 			--timeout="$option_timeout" \
 			--question="$option_question" \
 			--label -- "${choices[@]}"
 
 		# check
-		if test "$ec" -eq 60; then
-			echo-style --error="Choose timed out: $ec" >/dev/stderr
+		if test "$choose_status" -eq 60; then
+			echo-style --error="Choose timed out: $choose_status" >/dev/stderr
 			on_timeout
 			return
-		elif test "$ec" -ne 0; then
-			echo-style --error="Choose failed: $ec" >/dev/stderr
+		elif test "$choose_status" -ne 0; then
+			echo-style --error="Choose failed: $choose_status" >/dev/stderr
 			sleep 5
-			return "$ec"
+			return "$choose_status"
 		fi
 
 		# handle
@@ -241,10 +241,10 @@ function ask() (
 			return 0
 		elif test "$choice" = 'custom'; then
 			# ask
-			eval_capture --statusvar=ec -- do_ask "$option_question"
+			eval_capture --statusvar=ask_status -- do_ask "$option_question"
 
 			# check for failure
-			if test "$ec" -ne 0; then
+			if test "$ask_status" -ne 0; then
 				# timeout probably
 				on_timeout
 				return
diff --git a/commands/read-key b/commands/read-key
--- a/commands/read-key
+++ b/commands/read-key
@@ -78,16 +78,16 @@ function read_key() (
 		print_line "${k0}${k1}${k2}"
 	}
 	function read_key_bash_compat {
-		local ec=0
+		local status=0
 		if test "$BASH_VERSION_MAJOR" -ge '4'; then
-			read_key_bash_v4 || ec=$? # 👍 /docs/bash/errors: robust exit status
+			read_key_bash_v4 || status=$? # 👍 /docs/bash/errors: robust exit status
 		else
-			read_key_bash_v3 || ec=$? # 👍 /docs/bash/errors: robust exit status
+			read_key_bash_v3 || status=$? # 👍 /docs/bash/errors: robust exit status
 		fi
-		if test "$ec" -eq 142; then
+		if test "$status" -eq 142; then
 			return 60 # ETIMEDOUT 60 Operation timed out
-		elif test "$ec" -ne 0; then
-			return "$ec" # some other issue, let the caller figure it out
+		elif test "$status" -ne 0; then
+			return "$status" # some other issue, let the caller figure it out
 		fi
 	}
 
diff --git a/commands/ssh-helper b/commands/ssh-helper
--- a/commands/ssh-helper
+++ b/commands/ssh-helper
@@ -364,16 +364,16 @@ function ssh_helper() (
 	}
 
 	function ssh_test {
-		local uri="${1:-"git@github.com"}" logs ec
+		local uri="${1:-"git@github.com"}" logs test_status
 		logs="$(mktemp)"
 
 		# test and fetch exit code
-		ec=0 && ssh -qT "$uri" &>"$logs" || ec=$?
+		test_status=0 && ssh -qT "$uri" &>"$logs" || test_status=$?
 
 		# 0 no error
 		# 1 success but error - this is what github does, as is not a real ssh terminal
 		# 255 configuration error - this is what we are after
-		if test "$ec" -le 1; then
+		if test "$test_status" -le 1; then
 			return 0
 		else
 			cat "$logs" >/dev/stderr
@@ -422,10 +422,10 @@ function ssh_helper() (
 	function ssh_connect {
 		# 0 = success
 		# 130 = success then closed eventually
-		local ec
-		eval_capture --statusvar=ec -- ssh "$@"
-		if test "$ec" -ne 0 -a "$ec" -ne 130; then
-			echo-style --warning="Failed with exit code [$ec], will try again in 10 seconds..." >/dev/stderr
+		local connect_status
+		eval_capture --statusvar=connect_status -- ssh "$@"
+		if test "$connect_status" -ne 0 -a "$connect_status" -ne 130; then
+			echo-style --warning="Failed with exit code [$connect_status], will try again in 10 seconds..." >/dev/stderr
 			sleep 5
 			ssh_connect "$@"
 		fi
