eval_capture: subshell and bash v3 compatibility
- eval_capture now supports invoking subshells, now has bash v3 compatibility, doesn't need to alter set/shopt options, and will delete the trap when no longer required
- don't wrap things in redirection blocks that don't require redirections
- only use subshells when necessary
- fixed xonsh, which broke with 86d029ea79484b4ab50a16c5f33ca7ba7791c0f9
- use new __ prefix to indicate safety for if, and, or, not invocations (see docs/bash/errors for details)
- `dorothy test` will now check for `__` prefix conformance for unsafe function invocations
- `dorothy run` uses `command` builtin to execute the eval
- config-helper can now source eval-tester thanks to the new eval_capture
- alias __print* helpers to print* to work around __ convention tests
- `dorothy` => `doorthy_` to conform to function convention, worker also updated
- added `eval-capture` command which only invokes tests for `eval_capture`
- echo-wait: don't install sponge on tests on fresh macos

/close #203
/ref 482075979000c6447e45aabe77a2b17169a8786d

diff --git a/commands.beta/mail-sync b/commands.beta/mail-sync
--- a/commands.beta/mail-sync
+++ b/commands.beta/mail-sync
@@ -189,24 +189,24 @@ function mail_sync() (
 	# act and continue until success
 	# --usecache
 	# --useuid
-	local imapsync_status
+	local __imapsync_status
 	while true; do
-		imapsync_status=0 && imapsync \
+		__imapsync_status=0 && imapsync \
 			--automap \
 			--skipcrossduplicates \
 			--addheader --useheader 'Message-Id' \
 			--syncinternaldates \
 			--nofoldersizes --nofoldersizesatend --no-modulesversion --nolog \
-			"${args[@]}" || imapsync_status=$?
-		if test "$imapsync_status" -eq 0; then
+			"${args[@]}" || __imapsync_status=$?
+		if test "$__imapsync_status" -eq 0; then
 			echo-style --success='Success!'
 			break
-		elif test "$imapsync_status" -eq 143; then
-			echo-style --error="Manually terminated [$imapsync_status]..." >/dev/stderr
+		elif test "$__imapsync_status" -eq 143; then
+			echo-style --error="Manually terminated [$__imapsync_status]..." >/dev/stderr
 			break
-			return "$imapsync_status"
+			return "$__imapsync_status"
 		else
-			echo-style --warning="Failure with exit code [$imapsync_status] restarting..." >/dev/stderr
+			echo-style --warning="Failure with exit code [$__imapsync_status] restarting..." >/dev/stderr
 		fi
 	done
 )
diff --git a/commands/setup-dns b/commands/setup-dns
--- a/commands/setup-dns
+++ b/commands/setup-dns
@@ -16,8 +16,8 @@ function setup_dns() (
 	# Detection
 
 	# helper
-	function die_unknown_os {
-		echo-style --error='Unknown Operating System' >/dev/stderr
+	function __die_unknown_os {
+		echo-style --error='Unknown Operating System' >/dev/stderr || return
 		return 19 # ENODEV 19 Operation not supported by device
 	}
 
@@ -35,7 +35,7 @@ function setup_dns() (
 	elif is-linux; then
 		SERVICE_DIR='/etc/systemd/system'
 	else
-		die_unknown_os
+		__die_unknown_os
 	fi
 
 	# prepare the installers
@@ -70,7 +70,7 @@ function setup_dns() (
 			dnscrypt_installer='dnscrypt-proxy-linux_i386' # ...
 		fi
 	else
-		die_unknown_os
+		__die_unknown_os
 	fi
 
 	# determine available services
@@ -739,24 +739,24 @@ function setup_dns() (
 	# =====================================
 	# DNS Service: System: macOS
 
-	function system_exists { # 👍 /docs/bash/errors: robust exit status
+	function __system_exists {
 		if is-mac; then
 			command-exists networksetup || return
 		elif is-linux; then
 			command-exists systemctl resolvectl || return
 		else
-			die_unknown_os || return
+			__die_unknown_os || return
 		fi
 	}
-	function system_install { # 👍 /docs/bash/errors: robust exit status
-		if ! system_exists; then
-			eval_capture -- die_unknown_os # use this message, but keep the custom return code
-			return 29                      # Illegal seek
+	function system_install {
+		if ! __system_exists; then
+			eval_capture -- __die_unknown_os # use this message, but keep the custom return code
+			return 29                        # Illegal seek
 		fi
 	}
-	function system_uninstall {     # 👍 /docs/bash/errors: robust exit status
-		eval_capture -- die_unknown_os # use this message, but keep the custom return code
-		return 29                      # Illegal seek
+	function system_uninstall {
+		eval_capture -- __die_unknown_os # use this message, but keep the custom return code
+		return 29                        # Illegal seek
 	}
 	function system_configure {
 		# determine servers and action
@@ -909,7 +909,7 @@ function setup_dns() (
 			local default_route
 			for interface in "${interfaces[@]}"; do
 				# skip vpn interfaces
-				if is_vpn_interface "$interface"; then
+				if __is_vpn_interface "$interface"; then
 					echo-style --dim="Skipping VPN interface: $interface"
 					continue
 				fi
@@ -971,7 +971,7 @@ function setup_dns() (
 			echo-segment --g1="Configure and $action_title $systemd_title"
 		fi
 	}
-	function is_vpn_interface {
+	function __is_vpn_interface {
 		local interface="$1"
 		if [[ $interface =~ nordlynx ]] || [[ $interface == *vpn* ]] || [[ $interface == *tun* ]] || [[ $interface == *tap* ]]; then
 			return 0
@@ -1005,13 +1005,13 @@ function setup_dns() (
 		'--pidfile' "$aghome_state_pid_file"
 		'--logfile' "$aghome_state_log_file"
 	)
-	function aghome_exists { # 👍 /docs/bash/errors: robust exit status
+	function __aghome_exists {
 		test -x "$aghome_bin_file"
 	}
 	function aghome_install {
 		local action action_title temp_bin_file
 		action='install'
-		if aghome_exists; then
+		if __aghome_exists; then
 			action='upgrade'
 		fi
 		action_title="$(uppercase_first_letter "$action")"
@@ -1063,7 +1063,7 @@ function setup_dns() (
 	}
 	function aghome_uninstall {
 		# check
-		if ! aghome_exists; then
+		if ! __aghome_exists; then
 			return 0
 		fi
 
@@ -1089,7 +1089,7 @@ function setup_dns() (
 		action_title="$(uppercase_first_letter "$action")"
 
 		# check
-		if ! aghome_exists; then
+		if ! __aghome_exists; then
 			return 0
 		fi
 
@@ -1169,13 +1169,13 @@ function setup_dns() (
 		dnscrypt_service_id="$dnscrypt_id"
 		dnscrypt_service_file="$SERVICE_DIR/$dnscrypt_service_id.service"
 	fi
-	function dnscrypt_exists { # 👍 /docs/bash/errors: robust exit status
+	function __dnscrypt_exists {
 		test -x "$dnscrypt_bin_file"
 	}
 	function dnscrypt_install {
 		local action action_title temp_bin_file
 		action='install'
-		if dnscrypt_exists; then
+		if __dnscrypt_exists; then
 			action='upgrade'
 		fi
 		action_title="$(uppercase_first_letter "$action")"
@@ -1246,7 +1246,7 @@ function setup_dns() (
 	}
 	function dnscrypt_uninstall {
 		# check
-		if ! dnscrypt_exists; then
+		if ! __dnscrypt_exists; then
 			return 0
 		fi
 
@@ -1272,7 +1272,7 @@ function setup_dns() (
 		action_title="$(uppercase_first_letter "$action")"
 
 		# check
-		if ! dnscrypt_exists; then
+		if ! __dnscrypt_exists; then
 			return 0
 		fi
 
@@ -1358,13 +1358,13 @@ function setup_dns() (
 		cloudflared_proxy_service_file="$SERVICE_DIR/$cloudflared_proxy_service_id.service"
 	fi
 
-	function cloudflared_exists { # 👍 /docs/bash/errors: robust exit status
+	function __cloudflared_exists {
 		test -x "$cloudflared_bin_file"
 	}
 	function cloudflared_install {
 		local action action_title temp_bin_file
 		action='install' # install/upgrade
-		if cloudflared_exists; then
+		if __cloudflared_exists; then
 			action='upgrade'
 		fi
 		action_title="$(uppercase_first_letter "$action")"
@@ -1415,7 +1415,7 @@ function setup_dns() (
 	}
 	function cloudflared_uninstall {
 		# check
-		if ! cloudflared_exists; then
+		if ! __cloudflared_exists; then
 			return 0
 		fi
 
@@ -1446,7 +1446,7 @@ function setup_dns() (
 		upstream_args=''
 
 		# check
-		if ! cloudflared_exists; then
+		if ! __cloudflared_exists; then
 			return 0
 		fi
 
@@ -1561,7 +1561,7 @@ EOF
 
 	function tunnel_install {
 		# ensure cloudflared is installed
-		if ! cloudflared_exists; then
+		if ! __cloudflared_exists; then
 			cloudflared_install
 		fi
 
@@ -1591,7 +1591,7 @@ EOF
 		ingress=''
 
 		# check
-		if ! cloudflared_exists; then
+		if ! __cloudflared_exists; then
 			return 0
 		fi
 
@@ -1766,7 +1766,7 @@ EOF
 		args=()
 
 		# check
-		if ! cloudflared_exists; then
+		if ! __cloudflared_exists; then
 			return 0
 		fi
 
@@ -1857,26 +1857,26 @@ EOF
 	# Detect installed custom services
 	local installed_custom_services
 	installed_custom_services=()
-	if aghome_exists; then
+	if __aghome_exists; then
 		installed_custom_services+=(aghome)
 	fi
-	if cloudflared_exists; then
+	if __cloudflared_exists; then
 		installed_custom_services+=(cloudflared)
 	fi
-	if dnscrypt_exists; then
+	if __dnscrypt_exists; then
 		installed_custom_services+=(dnscrypt)
 	fi
 
 	# Disable all custom services, reconfigure the system (system on linux must be temporarily enabled to be configured), and then enable the chosen service
 	local installed_custom_service
 	for installed_custom_service in "${installed_custom_services[@]}"; do
-		("$installed_custom_service"_configure disable)
+		"$installed_custom_service"_configure disable # eval
 	done
 	if test "$service" = 'system'; then
 		system_configure enable
 	else
 		system_configure disable
-		("$service"_configure enable)
+		"$service"_configure enable # eval
 	fi
 
 	# -------------------------------------
diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -630,7 +630,7 @@ function setup_util() (
 	# apk / Alpine Linux
 	# https://wiki.alpinelinux.org/wiki/Package_management
 	# https://pkgs.alpinelinux.org/packages
-	function are_any_of_these_apk_packages_installed { # 👍 /docs/bash/errors: robust exit status
+	function __are_any_of_these_apk_packages_installed {
 		local package packages=("$@")
 		# returns 1 if any are missin
 		for package in "${packages[@]}"; do
@@ -656,7 +656,7 @@ function setup_util() (
 
 		# args
 		if test "$action" = 'uninstall'; then
-			if ! are_any_of_these_apk_packages_installed "${packages[@]}"; then
+			if ! __are_any_of_these_apk_packages_installed "${packages[@]}"; then
 				return 200 # ECUSTOM 200 Not applicable to this uninstallation
 			fi
 			args+=(
@@ -779,7 +779,7 @@ function setup_util() (
 	}
 
 	# pacman / Arch Linux / Manjaro
-	function are_any_of_these_pacman_packages_installed {
+	function __are_any_of_these_pacman_packages_installed {
 		local package packages=("$@")
 		# returns 1 if any are missing
 		for package in "${packages[@]}"; do
@@ -836,7 +836,7 @@ function setup_util() (
 
 		# args
 		if test "$action" = 'uninstall'; then
-			if ! are_any_of_these_pacman_packages_installed "${packages[@]}"; then
+			if ! __are_any_of_these_pacman_packages_installed "${packages[@]}"; then
 				return 200 # ECUSTOM 200 Not applicable to this uninstallation
 			fi
 			args+=(
@@ -1196,7 +1196,7 @@ function setup_util() (
 			return 200 # ECUSTOM 200 Not applicable for this package system
 		fi
 
-		# if APT_REPO or APT_KEY are used, then determine APT_ID automatically, and fail if it couldn't be determined
+		# when APT_REPO or APT_KEY are used, then determine APT_ID automatically, and fail if it couldn't be determined
 		if test -n "$repo" -o -n "$key"; then
 			# ensure apt is setup
 			setup-util-apt --quiet
@@ -1220,7 +1220,7 @@ function setup_util() (
 		if test -n "$key"; then
 			if test -z "$repo"; then
 				cat <<-EOF >/dev/stderr
-					$(echo-style --error="If APT_KEY is set, APT_REPO must also be set.")
+					$(echo-style --error="When APT_KEY is set, APT_REPO must also be set.")
 
 					APT: ${packages[*]}
 				EOF
@@ -1228,7 +1228,7 @@ function setup_util() (
 			fi
 			if [[ $repo != *'signed-by'* ]]; then
 				cat <<-EOF >/dev/stderr
-					$(echo-style --error="If APT_KEY is set, APT_REPO must contain:")
+					$(echo-style --error="When APT_KEY is set, APT_REPO must contain:")
 					$(echo-style --code="deb [signed-by={KEY}] https://...")
 
 					APT: ${packages[*]}
@@ -1242,7 +1242,7 @@ function setup_util() (
 		if test -n "$repo" && [[ $repo == 'deb '* ]]; then
 			if [[ $repo != *'arch={ARCH}'* ]]; then
 				cat <<-EOF >/dev/stderr
-					$(echo-style --error="If APT_REPO is set, arch must be set to {ARCH}")
+					$(echo-style --error="When APT_REPO is set, arch must be set to {ARCH}")
 					$(echo-style --code="deb [arch={ARCH}] https://...")
 
 					APT: ${packages[*]}
@@ -1252,7 +1252,7 @@ function setup_util() (
 			fi
 			if test -n "$key" && [[ $repo != *'signed-by={KEY}'* ]]; then
 				cat <<-EOF >/dev/stderr
-					$(echo-style --error="If APT_REPO and APT_KEY is set, signed-by must be set to {KEY}")
+					$(echo-style --error="When APT_REPO and APT_KEY is set, signed-by must be set to {KEY}")
 					$(echo-style --code="deb [signed-by={KEY}] https://...")
 
 					APT: ${packages[*]}
@@ -1700,7 +1700,7 @@ function setup_util() (
 	# MacOS
 
 	# brew / Homebrew / macOS
-	function are_all_of_these_brew_packages_installed { # 👍 /docs/bash/errors: robust exit status
+	function __are_all_of_these_brew_packages_installed {
 		local packages=("$@")
 		brew-installed --formula -- "${packages[@]}" &>/dev/null
 	}
@@ -1739,7 +1739,7 @@ function setup_util() (
 
 		# args
 		if test "$action" = 'uninstall'; then
-			if ! are_all_of_these_brew_packages_installed "${packages[@]}"; then
+			if ! __are_all_of_these_brew_packages_installed "${packages[@]}"; then
 				return 200 # ECUSTOM 200 Not applicable for this package system
 			fi
 			args+=(
@@ -1775,7 +1775,7 @@ function setup_util() (
 	# brew / Homebrew Casks / macOS
 	# some packages are available as both brew, and cask
 	# ... so provide both independently as they are alternatives
-	function are_all_of_these_cask_packages_installed { # 👍 /docs/bash/errors: robust exit status
+	function __are_all_of_these_cask_packages_installed {
 		local packages=("$@")
 		brew-installed --cask -- "${packages[@]}" &>/dev/null
 	}
@@ -1814,7 +1814,7 @@ function setup_util() (
 
 		# args
 		if test "$action" = 'uninstall'; then
-			if ! are_all_of_these_cask_packages_installed "${packages[@]}"; then
+			if ! __are_all_of_these_cask_packages_installed "${packages[@]}"; then
 				return 200 # ECUSTOM 200 Not applicable for this package system
 			fi
 			args+=(
@@ -1920,7 +1920,7 @@ function setup_util() (
 
 		# signin, signout, no longer supported
 		# local signed_in='maybe'
-		# function mas_signin {
+		# function __mas_signin {
 		# 	local email
 		# 	if test "$signed_in" = 'yes'; then
 		# 		return 0
@@ -1941,11 +1941,11 @@ function setup_util() (
 		# 		return 1
 		# 	fi
 		# }
-		# function mas_action {
+		# function __mas_action {
 		# 	"${args[@]}" "${packages[@]}"
 		# }
-		# mas_action || {
-		# 	mas_signin && mas_action
+		# __mas_action || {
+		# 	__mas_signin && __mas_action
 		# }
 
 		# packages
@@ -2067,7 +2067,7 @@ function setup_util() (
 	# Node.js
 
 	# npm / Node.js
-	function are_any_of_these_npm_packages_installed { # 👍 /docs/bash/errors: robust exit status
+	function __are_any_of_these_npm_packages_installed {
 		local packages=("$@")
 		# returns 1 only if all are missing, returns 0 if any are installed
 		nvm-env -- npm list --global --depth 0 "${packages[@]}" &>/dev/null
@@ -2093,7 +2093,7 @@ function setup_util() (
 
 		# args
 		if test "$action" = 'uninstall'; then
-			if ! are_any_of_these_npm_packages_installed "${packages[@]}"; then
+			if ! __are_any_of_these_npm_packages_installed "${packages[@]}"; then
 				return 200 # ECUSTOM 200 Not applicable to this uninstallation
 			fi
 			args+=(
@@ -2128,7 +2128,7 @@ function setup_util() (
 
 	# pip / Python
 	# https://man.archlinux.org/man/extra/python-pip/pip.1.en
-	function pip_helper { # 👍 /docs/bash/errors: robust exit status
+	function __pip_helper {
 		# Use the correct [pip] executable for the user's environment, as there may be many or multiple installed, such as one for Python v2 and one for Python v3.
 		if command-exists pip; then
 			pip "$@" || return
@@ -2143,18 +2143,18 @@ function setup_util() (
 		elif python2 -m pip --version &>/dev/null; then
 			python -m pip "$@" || return
 		elif command-exists /usr/local/bin/pip; then
-			/usr/local/bin/pip "$@"
+			/usr/local/bin/pip "$@" || return
 		elif test -n "${HOMEBREW_PREFIX-}" -a -x "${HOMEBREW_PREFIX-}/bin/pip"; then
 			"${HOMEBREW_PREFIX}/bin/pip" "$@" || return
 		else
-			echo-style --error="[pip] nor its variations were found" >/dev/stderr
+			echo-style --error="[pip] nor its variations were found" >/dev/stderr || return
 			return 1
 		fi
 	}
-	function are_any_of_these_pip_packages_installed { # 👍 /docs/bash/errors: robust exit status
+	function __are_any_of_these_pip_packages_installed {
 		local packages=("$@")
 		# returns 1 only if all are missing, returns 0 if any are installed
-		pip_helper show -q "${packages[@]}" &>/dev/null
+		__pip_helper show -q "${packages[@]}" &>/dev/null
 	}
 	function do_pip {
 		local args=() packages=() pip_status
@@ -2168,7 +2168,7 @@ function setup_util() (
 		if test "${#packages[@]}" -eq 0; then
 			return 200 # ECUSTOM 200 Not applicable to this utility
 		fi
-		eval_capture --statusvar=pip_status --no-output -- pip_helper --version
+		eval_capture --statusvar=pip_status --no-output -- __pip_helper --version
 		if test "$pip_status" -ne 0; then
 			fallbacks+=('pip')
 			return 200 # ECUSTOM 200 Not applicable yet but provided fallback
@@ -2176,17 +2176,17 @@ function setup_util() (
 
 		# args
 		if test "$action" = 'uninstall'; then
-			if ! are_any_of_these_pip_packages_installed "${packages[@]}"; then
+			if ! __are_any_of_these_pip_packages_installed "${packages[@]}"; then
 				return 200 # ECUSTOM 200 Not applicable to this uninstallation
 			fi
 			args+=(
-				'pip_helper'
+				'__pip_helper'
 				'uninstall'
 				'--yes'
 			)
 		else
 			args+=(
-				'pip_helper'
+				'__pip_helper'
 				'install'
 				'--user'
 				'--no-warn-script-location'
@@ -2213,7 +2213,7 @@ function setup_util() (
 	# https://www.mankier.com/1/pipx#COMMAND_'pipx_upgrade'
 	# https://www.mankier.com/1/pipx#COMMAND_'pipx_uninstall'
 	# https://www.mankier.com/1/pipx#COMMAND_'pipx_reinstall'
-	function are_any_of_these_pipx_packages_installed {
+	function __are_any_of_these_pipx_packages_installed {
 		local package packages=("$@")
 		for package in "${packages[@]}"; do
 			# only supports one package at a time
@@ -2242,7 +2242,7 @@ function setup_util() (
 
 		# args
 		if test "$action" = 'uninstall'; then
-			if ! are_any_of_these_pipx_packages_installed "${packages[@]}"; then
+			if ! __are_any_of_these_pipx_packages_installed "${packages[@]}"; then
 				return 200 # ECUSTOM 200 Not applicable to this uninstallation
 			fi
 			args+=(
@@ -2273,7 +2273,7 @@ function setup_util() (
 		"${args[@]}" "${packages[@]}"
 	}
 	function do_pipx_fallback {
-		if ! pip_helper --version &>/dev/null; then
+		if ! __pip_helper --version &>/dev/null; then
 			setup-python
 		fi
 		setup-util-pipx --quiet="$quiet"
@@ -2627,7 +2627,7 @@ function setup_util() (
 	# gem / Ruby
 	# we use --user-install because of:
 	# https://github.com/ffi/ffi/issues/631
-	function are_any_of_these_gem_packages_installed { # 👍 /docs/bash/errors: robust exit status
+	function __are_any_of_these_gem_packages_installed {
 		local packages=("$@")
 		for package in "${packages[@]}"; do
 			# only supports one package at a time
@@ -2656,7 +2656,7 @@ function setup_util() (
 
 		# args
 		if test "$action" = 'uninstall'; then
-			if ! are_any_of_these_gem_packages_installed "${packages[@]}"; then
+			if ! __are_any_of_these_gem_packages_installed "${packages[@]}"; then
 				return 200 # ECUSTOM 200 Not applicable to this uninstallation
 			fi
 			for package in "${packages[@]}"; do
@@ -2692,7 +2692,7 @@ function setup_util() (
 	# cargo / Crates.io / Rust
 	# https://manpages.debian.org/testing/cargo/cargo-install.1.en.html
 	# https://manpages.debian.org/testing/cargo/cargo-uninstall.1.en.html
-	function are_any_of_these_cargo_packages_installed { # 👍 /docs/bash/errors: robust exit status
+	function __are_any_of_these_cargo_packages_installed {
 		local package packages=("$@")
 		for package in "${packages[@]}"; do
 			# only supports one package at a time
@@ -2721,7 +2721,7 @@ function setup_util() (
 
 		# args
 		if test "$action" = 'uninstall'; then
-			if ! are_any_of_these_cargo_packages_installed "${packages[@]}"; then
+			if ! __are_any_of_these_cargo_packages_installed "${packages[@]}"; then
 				return 200 # ECUSTOM 200 Not applicable to this uninstallation
 			fi
 			args+=(
@@ -2770,7 +2770,7 @@ function setup_util() (
 
 	# snap / Snap Craft / Ubuntu
 	# needs sudo, otherwise: error: access denied (try with sudo)
-	function are_any_of_these_snap_packages_installed { # 👍 /docs/bash/errors: robust exit status
+	function __are_any_of_these_snap_packages_installed {
 		local packages=("$@")
 		# returns 1 only if all are missing, returns 0 if any are installed
 		snap list "${packages[@]}" &>/dev/null
@@ -2792,7 +2792,7 @@ function setup_util() (
 
 		# action args
 		if test "$action" = 'uninstall'; then
-			if ! are_any_of_these_snap_packages_installed "${packages[@]}"; then
+			if ! __are_any_of_these_snap_packages_installed "${packages[@]}"; then
 				return 200 # ECUSTOM 200 Not applicable to this uninstallation
 			fi
 			args+=(
@@ -3071,15 +3071,15 @@ function setup_util() (
 	# https://scoop.sh/
 	# https://github.com/ScoopInstaller/Scoop/wiki/Commands
 	# https://github.com/ScoopInstaller/Scoop/wiki/Example-Setup-Scripts
-	function is_this_scoop_package_installed {
+	function __is_this_scoop_package_installed {
 		# check for the header of the table of results
 		scoop list "$package" | echo-wait | grep --quiet --fixed-strings --regexp='----'
 	}
-	function are_any_of_these_scoop_packages_installed { # 👍 /docs/bash/errors: robust exit status
+	function __are_any_of_these_scoop_packages_installed {
 		local package packages=("$@")
 		for package in "${packages[@]}"; do
 			# only supports one package at a time
-			if is_this_scoop_package_installed "$package"; then
+			if __is_this_scoop_package_installed "$package"; then
 				return 0
 			fi
 		done
@@ -3098,7 +3098,7 @@ function setup_util() (
 		if command-missing scoop; then
 			return 200 # ECUSTOM 200 Not applicable for this package system
 		fi
-		if test "$action" = 'uninstall' && ! are_any_of_these_scoop_packages_installed "${packages[@]}"; then
+		if test "$action" = 'uninstall' && ! __are_any_of_these_scoop_packages_installed "${packages[@]}"; then
 			return 200 # ECUSTOM 200 Not applicable to this uninstallation
 		fi
 
@@ -3135,14 +3135,14 @@ function setup_util() (
 	# installs applications (via ids) to various locations
 	# https://docs.microsoft.com/en-us/windows/package-manager/winget/
 	# https://docs.microsoft.com/en-us/windows/package-manager/winget/install
-	function is_this_winget_package_installed {
+	function __is_this_winget_package_installed {
 		winget.exe list --disable-interactivity --id="$package" &>/dev/null
 	}
-	function are_any_of_these_winget_packages_installed { # 👍 /docs/bash/errors: robust exit status
+	function __are_any_of_these_winget_packages_installed {
 		local package packages=("$@")
 		for package in "${packages[@]}"; do
 			# only supports one package at a time
-			if is_this_winget_package_installed "$package"; then
+			if __is_this_winget_package_installed "$package"; then
 				return 0
 			fi
 		done
@@ -3161,7 +3161,7 @@ function setup_util() (
 		if command-missing 'winget.exe'; then
 			return 200 # ECUSTOM 200 Not applicable for this package system
 		fi
-		if test "$action" = 'uninstall' && ! are_any_of_these_winget_packages_installed "${packages[@]}"; then
+		if test "$action" = 'uninstall' && ! __are_any_of_these_winget_packages_installed "${packages[@]}"; then
 			return 200 # ECUSTOM 200 Not applicable to this uninstallation
 		fi
 
@@ -3171,7 +3171,7 @@ function setup_util() (
 			args=()
 			if test "$action" = 'uninstall'; then
 				# fails if already uninstalled, so check beforehand
-				if ! is_this_winget_package_installed "${packages[@]}"; then
+				if ! __is_this_winget_package_installed "${packages[@]}"; then
 					continue
 				fi
 				args+=(
@@ -3184,7 +3184,7 @@ function setup_util() (
 					'upgrade'
 				)
 			else
-				if is_this_winget_package_installed "${packages[@]}"; then
+				if __is_this_winget_package_installed "${packages[@]}"; then
 					continue
 				fi
 				args+=(
@@ -3338,18 +3338,17 @@ function setup_util() (
 
 		# build
 		if test -n "$build_eval"; then
-			(
-				local build_status
-				cd "$download_directory"
-				echo-style --bold="Building $name..."
-				eval_capture --statusvar=build_status -- "$build_eval"
-				if test "$build_status" -eq 0; then
-					echo-style --success="Built $name."
-				else
-					echo-style --error="Failed to build $name." >/dev/stderr
-					return "$build_status"
-				fi
-			)
+			local build_status
+			echo-style --bold="Building $name..."
+			pushd "$download_directory" &>/dev/null
+			eval_capture --statusvar=build_status -- "$build_eval"
+			popd &>/dev/null
+			if test "$build_status" -eq 0; then
+				echo-style --success="Built $name."
+			else
+				echo-style --error="Failed to build $name." >/dev/stderr
+				return "$build_status"
+			fi
 			if test -n "$build_filter"; then
 				# match extracted paths against filter
 				local filtered_paths=() filtered_path
