another huge WIP commit:
- new `--elevated`, `--elevate`, `--user`, `--group`, `--reason` elevation args
- merging of `until-success` and `sudo-helper` into `eval-helper`
- change source code convention of having a newline follow `--`
- merged `fs-bytes`, `fs-kilobytes`, `fs-megabytes` into new `fs-size`
- merged various dirname/basename/filename commands into new `fs-path`
- renamed `echo-wait` to `echo-write`
- renamed `get-file` to `fs-type`
- add `is-exit`

todos:

- finish merged `eval-helper`
- finish new elevation args on `fs-*` commands
- finish new `fs-mkdir`

diff --git a/commands.beta/pdf-decrypt b/commands.beta/pdf-decrypt
--- a/commands.beta/pdf-decrypt
+++ b/commands.beta/pdf-decrypt
@@ -49,33 +49,27 @@ function pdf_decrypt() (
 	# =====================================
 	# Act
 
-	local index filepath filename
-
-	local filenames=()
-	for index in "${!option_inputs[@]}"; do
-		filepath="${option_inputs[index]}"
-		filename="$(fs-filename -- "$filepath")"
-		filenames[index]="$filename"
-	done
-
-	local password
+	local password path file outpath
 	password="$(
 		ask --required --password \
 			--question='Enter the decryption password for the PDFs' \
-			--question="$(echo-lines --columns -- "${filenames[@]}")" \
+			--question="$(echo-lines --columns -- "${option_inputs[@]}")" \
 			--default="$option_password"
 	)"
-
-	local outpath
-	for index in "${!option_inputs[@]}"; do
-		filepath="${option_inputs[index]}"
-		filename="${filenames[index]}"
-		outpath="$item [decrypted].pdf"
-		eval-helper --quiet \
-			--pending="$(echo-style --bold='Decrypting ' --code="$filepath" --bold=' to ' --code="$outpath")" \
-			--success="$(echo-style --bold+green='Decrypted ' --code="$filepath" --bold=' to ' --code="$outpath")" \
-			--failure="$(echo-style --bold+red='Failed to decrypt ' --code="$filepath" --bold=' to ' --code="$outpath")" \
-			-- qpdf -password="$password" -decrypt "$filepath" "$outpath" || :
+	for path in "${option_inputs[@]}"; do
+		file="$(fs-path --no-parents --no-extensions -- "$path")"
+		outpath="$file [decrypted].pdf"
+		eval-helper --quiet --no-wrap \
+			--pending="$(
+				echo-style --bold='Decrypting ' --code="$path" --bold=' to ' --code="$outpath"
+			)" \
+			--success="$(
+				echo-style --bold+green='Decrypted ' --code="$path" --bold=' to ' --code="$outpath"
+			)" \
+			--failure="$(
+				echo-style --bold+red='Failed to decrypt ' --code="$path" --bold=' to ' --code="$outpath"
+			)" -- \
+			qpdf -password="$password" -decrypt "$path" "$outpath" || :
 	done
 
 )
diff --git a/commands/btrfs-helper b/commands/btrfs-helper
--- a/commands/btrfs-helper
+++ b/commands/btrfs-helper
@@ -82,7 +82,7 @@ function btrfs_helper() (
 
 	function act_discover {
 		# ensure btrfs devices are discovered, this is necessary
-		sudo-helper -- btrfs --verbose device scan --all-devices
+		eval-helper --elevate -- btrfs --verbose device scan --all-devices
 	}
 	function act_devices {
 		get-devices --filesystem=btrfs "$@"
@@ -102,39 +102,39 @@ function btrfs_helper() (
 
 		# Show the structure of a filesystem
 		# usage: btrfs filesystem show [options] [<path>|<uuid>|<device>|label]
-		sudo-helper --wrap \
-			-- btrfs filesystem show "$path"
+		eval-helper --elevate --wrap -- \
+			btrfs filesystem show "$path"
 
 		if [[ -n $existing_mount ]]; then
 			# Show detailed information about internal allocations in devices.
 			# usage: btrfs device usage [options] <path> [<path>..]
-			sudo-helper --wrap \
-				-- btrfs device usage "$existing_mount"
+			eval-helper --elevate --wrap -- \
+				btrfs device usage "$existing_mount"
 
 			# Show detailed information about internal filesystem usage .
 			# usage: btrfs filesystem usage [options] <path> [<path>..]
-			sudo-helper --wrap \
-				-- btrfs filesystem usage "$existing_mount"
+			eval-helper --elevate --wrap -- \
+				btrfs filesystem usage "$existing_mount"
 
 			# Show space usage information for a mount point
 			# usage: btrfs filesystem df [options] <path>
-			sudo-helper --wrap \
-				-- btrfs filesystem df "$existing_mount"
+			eval-helper --elevate --wrap -- \
+				btrfs filesystem df "$existing_mount"
 
 			# Show space usage via system
 			# -a, --all             include pseudo, duplicate, inaccessible file systems
 			# -h, --human-readable  print sizes in powers of 1024 (e.g., 1023M)
-			sudo-helper --wrap \
-				-- df -ah "$existing_mount"
+			eval-helper --elevate --wrap -- \
+				df -ah "$existing_mount"
 		fi
 
 		# Show status
-		sudo-helper --wrap \
-			-- btrfs balance status "$path" || : # if still running, exit code 1
-		sudo-helper --wrap \
-			-- btrfs scrub status "$path" || : # if still running, exit code 1
-		sudo-helper --wrap \
-			-- btrfs device stats "$path"
+		eval-helper --elevate --wrap -- \
+			btrfs balance status "$path" || : # if still running, exit code 1
+		eval-helper --elevate --wrap -- \
+			btrfs scrub status "$path" || : # if still running, exit code 1
+		eval-helper --elevate --wrap -- \
+			btrfs device stats "$path"
 
 		# Get all devices of the mount
 		if [[ -n $existing_uuid && $existing_count -gt 1 ]]; then
@@ -142,32 +142,32 @@ function btrfs_helper() (
 		fi
 
 		# Summarize disk usage of every nested file inside the directory
-		# sudo-helper --wrap \
+		# eval-helper --elevate --wrap \
 		#	-- btrfs filesystem du --summarize --human-readable "$path"
 
 		# Rename
-		# sudo-helper --wrap \
+		# eval-helper --elevate --wrap \
 		#	-- btrfs filesystem label "$path" "$name"
 
 		# Change unallocated to free
-		# sudo-helper --wrap \
+		# eval-helper --elevate --wrap \
 		#	-- btrfs filesystem resize max "$path"
 
 		# Defragment (balance also defrags)
-		# sudo-helper --wrap \
+		# eval-helper --elevate --wrap \
 		#	-- btrfs filesystem defragment "$path"
 
 		# Balance as raid1
-		# sudo-helper --wrap \
+		# eval-helper --elevate --wrap \
 		#	-- btrfs balance start --background -dconvert=raid1 -mconvert=raid1 "$path"
 
 		# Scrub (check filesystem for errors and auto-heal)
-		# sudo-helper --wrap \
+		# eval-helper --elevate --wrap \
 		#	-- btrfs scrub start "$path"
 
 		# Check devices for errors
 		# WARNING: the repair mode is considered dangerous and should not be used without prior analysis of problems found on the filesystem.
-		# sudo-helper --wrap \
+		# eval-helper --elevate --wrap \
 		#	-- btrfs check --repair --progress /dev/...
 
 		# Logs
@@ -187,8 +187,8 @@ function btrfs_helper() (
 		)"
 
 		# format
-		sudo-helper --wrap --confirm \
-			-- mkfs.btrfs -f -L "$label" "$node"
+		eval-helper --elevate --wrap --confirm -- \
+			mkfs.btrfs -f -L "$label" "$node"
 	}
 	function act_mount {
 		# Mount a btrfs device
@@ -253,8 +253,8 @@ function btrfs_helper() (
 		# -K|--nodiscard            do not perform whole device TRIM on devices that report such capability
 		# -f|--force                force overwrite existing filesystem on the disk
 		# --enqueue                 wait if there's another exclusive operation running, otherwise continue
-		sudo-helper --wrap --confirm \
-			-- btrfs device add --force --enqueue "$extra_node" "$existing_mount"
+		eval-helper --elevate --wrap --confirm -- \
+			btrfs device add --force --enqueue "$extra_node" "$existing_mount"
 
 		# run a balance
 		echo-style --notice='Once you a done with adding devices, you should run a balance now on the mount.'
@@ -288,16 +288,16 @@ function btrfs_helper() (
 		fi
 
 		# wait until balance completes
-		while ! sudo-helper --wrap \
-			-- btrfs balance status --verbose "$existing_mount"; do
+		while ! eval-helper --elevate --wrap -- \
+			btrfs balance status --verbose "$existing_mount"; do
 			waiter 5
 		done
 
 		# usage: btrfs device remove <device>|<devid> [<device>|<devid>...] <path>
 		# Remove a device from a filesystem, specified by a path to the device or as a device id in the filesystem. The btrfs signature is removed from the device.
 		# --enqueue                 wait if there's another exclusive operation running, otherwise continue
-		sudo-helper --wrap --confirm \
-			-- btrfs device remove --enqueue "$extra_node" "$existing_mount"
+		eval-helper --elevate --wrap --confirm -- \
+			btrfs device remove --enqueue "$extra_node" "$existing_mount"
 
 		# run a balance
 		echo-style --notice='Once you a done with removing devices, you should run a balance now on the mount.'
@@ -323,21 +323,21 @@ function btrfs_helper() (
 		# usage: btrfs balance status [-v] <path>
 		# Show status of running or paused balance
 		# -v|--verbose              increase output verbosity
-		if ! sudo-helper --wrap \
-			-- btrfs balance status --verbose "$existing_mount"; then
+		if ! eval-helper --elevate --wrap -- \
+			btrfs balance status --verbose "$existing_mount"; then
 
 			# balance is running, ask what to do
 			if [[ "$(choose --linger --required --label --question="Do you wish to?" -- 'resume' "Resume the existing balance, and abort a new $strategy balance." 'start' "Cancel the existing balance and resume, and start a new $strategy balance.")" == 'resume' ]]; then
 				# usage: btrfs balance resume <path>
 				# Resume interrupted balance
-				sudo-helper --wrap --confirm \
-					-- btrfs balance resume "$existing_mount"
+				eval-helper --elevate --wrap --confirm -- \
+					btrfs balance resume "$existing_mount"
 				return
 			else
 				# usage: btrfs balance cancel <path>
 				# Cancel running or paused balance
-				sudo-helper --wrap --confirm \
-					-- btrfs balance cancel "$existing_mount"
+				eval-helper --elevate --wrap --confirm -- \
+					btrfs balance cancel "$existing_mount"
 			fi
 		fi
 
@@ -352,8 +352,8 @@ function btrfs_helper() (
 		if [[ $strategy == 'single' ]]; then
 			args+=('--force')
 		fi
-		sudo-helper --wrap --confirm \
-			-- btrfs balance start --verbose --background --enqueue "${args[@]}" -dconvert="$strategy" -mconvert="$strategy" "$existing_mount"
+		eval-helper --elevate --wrap --confirm -- \
+			btrfs balance start --verbose --background --enqueue "${args[@]}" -dconvert="$strategy" -mconvert="$strategy" "$existing_mount"
 	}
 
 	# act
diff --git a/commands/config-edit b/commands/config-edit
--- a/commands/config-edit
+++ b/commands/config-edit
@@ -19,6 +19,7 @@ function config_edit() (
 			config-edit --cron-system --line=<line>
 			config-edit --cron-user --line=<line>
 			config-edit --file --line=<line>
+			config-edit --local
 
 			OPTIONS:
 			--name=<name>
@@ -48,6 +49,8 @@ function config_edit() (
 			--applier=<apply-command>
 			    A command that is called that will automatically replace the found lines (first argument) with the desired <line> (second argument) and save changes, inserting the desired <line> if no lines were found.
 
+			--[no-]local
+			    Update sudo and cron configuration to enable or disable access to /usr/local paths
 			--fuse | --fstab | --sudoers | --hosts | --cron-system | --cron-user | --file=<file>
 			    Each of these set appropriate defaults for those configurations.
 		EOF
@@ -64,7 +67,7 @@ function config_edit() (
 	}
 
 	# process
-	local item option_name='' option_file='' option_action='' option_line='' option_needle='' option_searcher='' option_comparer='default_comparer' option_editor='' option_applier=''
+	local item option_name='' option_file='' option_action='' option_line='' option_needle='' option_searcher='' option_comparer='default_comparer' option_editor='' option_applier='' option_local=''
 	while [[ $# -ne 0 ]]; do
 		item="$1"
 		shift
@@ -121,12 +124,12 @@ function config_edit() (
 				rg --fixed-strings --regexp="$1" --line-regexp '/etc/fuse.conf'
 			}
 			function default_fuse_editor {
-				edit --wait --sudo -- '/etc/fuse.conf'
+				edit --wait --elevate -- '/etc/fuse.conf'
 			}
 			function default_fuse_applier {
 				local needle="${1:-"$2"}" replace="$2"
-				sudo-helper --inherit \
-					-- config-helper --file='/etc/fuse.conf' -- \
+				eval-helper --elevate --inherit -- \
+					config-helper --file='/etc/fuse.conf' -- \
 					--string-find="$needle" --string-replace="$replace"
 			}
 			;;
@@ -139,18 +142,18 @@ function config_edit() (
 				rg --fixed-strings --regexp="$1" '/etc/fstab'
 			}
 			function default_fstab_editor {
-				edit --wait --sudo -- '/etc/fstab'
+				edit --wait --elevate -- '/etc/fstab'
 				if is-linux; then
-					sudo-helper -- systemctl daemon-reload
+					eval-helper --elevate -- systemctl daemon-reload
 				fi
 			}
 			function default_fstab_applier {
 				local needle="${1:-"$2"}" replace="$2"
-				sudo-helper --inherit \
-					-- config-helper --file='/etc/fstab' -- \
+				eval-helper --elevate --inherit -- \
+					config-helper --file='/etc/fstab' -- \
 					--string-find="$needle" --string-replace="$replace"
 				if is-linux; then
-					sudo-helper -- systemctl daemon-reload
+					eval-helper --elevate -- systemctl daemon-reload
 				fi
 			}
 			;;
@@ -159,28 +162,28 @@ function config_edit() (
 			option_searcher='default_sudoers_searcher'
 			option_editor='default_sudoers_editor'
 			function default_sudoers_searcher {
-				sudo-helper -- cat /etc/sudoers | rg --fixed-strings --regexp="$1"
+				echo-file --raw -- /etc/sudoers | rg --fixed-strings --regexp="$1"
 			}
 			function default_sudoers_editor {
 				# --inherit to maintain editor preferences
-				sudo-helper --inherit -- visudo
+				eval-helper --elevate --inherit -- visudo
 			}
 			;;
 		'--hosts')
-			option_name='fuse'
+			option_name='hosts'
 			option_searcher='default_hosts_searcher'
 			option_editor='default_hosts_editor'
 			option_applier='default_hosts_applier'
 			function default_hosts_searcher {
-				rg --fixed-strings --regexp="$1" --line-regexp '/etc/hosts.conf'
+				rg --fixed-strings --regexp="$1" --line-regexp '/etc/hosts'
 			}
 			function default_hosts_editor {
-				edit --wait --sudo -- '/etc/hosts'
+				edit --wait --elevate -- '/etc/hosts'
 			}
 			function default_hosts_applier {
 				local needle="${1:-"$2"}" replace="$2"
-				sudo-helper --inherit \
-					-- config-helper --file='/etc/hosts.conf' -- \
+				eval-helper --elevate --inherit -- \
+					config-helper --file='/etc/hosts' -- \
 					--string-find="$needle" --string-replace="$replace"
 			}
 			;;
@@ -194,13 +197,13 @@ function config_edit() (
 				return # explicit return with [[ required for bash v3
 			}
 			function default_cron_system_searcher {
-				# did testing on macos, and windows WSL2 ubuntu, [echo-wait] seemed unnecessary, no documentation why it was there, works with sudo and without sudo prompt
-				# @todo test on raspberry pi if [echo-wait] and [--buffer] are even needed
-				sudo-helper -- crontab -l | echo-wait --buffer | rg --fixed-strings --regexp="$1"
+				# did testing on macos, and windows WSL2 ubuntu, [echo-write] seemed unnecessary, no documentation why it was there, works with sudo and without sudo prompt
+				# @todo test on raspberry pi if [echo-write] and [--buffer] are even needed
+				eval-helper --elevate -- crontab -l | echo-write --buffer | rg --fixed-strings --regexp="$1"
 			}
 			function default_cron_system_editor {
 				# --inherit to maintain editor preferences
-				sudo-helper --inherit -- crontab -e || :
+				eval-helper --elevate --inherit -- crontab -e || :
 				if is-mac; then
 					service-helper --restart -- system/com.vix.cron
 				else
@@ -218,9 +221,9 @@ function config_edit() (
 				return # explicit return with [[ required for bash v3
 			}
 			function default_cron_user_searcher {
-				# did testing on macos, and windows WSL2 ubuntu, [echo-wait] seemed unnecessary, no documentation why it was there, works with sudo and without sudo prompt
-				# @todo test on raspberry pi if [echo-wait] and [--buffer] are even needed
-				crontab -l | echo-wait --buffer | rg --fixed-strings --regexp="$1"
+				# did testing on macos, and windows WSL2 ubuntu, [echo-write] seemed unnecessary, no documentation why it was there, works with sudo and without sudo prompt
+				# @todo test on raspberry pi if [echo-write] and [--buffer] are even needed
+				crontab -l | echo-write --buffer | rg --fixed-strings --regexp="$1"
 			}
 			function default_cron_user_editor {
 				# user crontab already inherits editor preferences
@@ -232,10 +235,47 @@ function config_edit() (
 				fi
 			}
 			;;
+		'--no-local'* | '--local'*)
+			option_local="$(get-flag-value --affirmative --fallback="$option_local" -- "$item")"
+			;;
 		'--'*) help "An unrecognised flag was provided: $item" ;;
 		*) help "An unrecognised argument was provided: $item" ;;
 		esac
 	done
+
+	# local
+	if [[ -n $option_local ]]; then
+		# trim problematic paths
+		local system_paths sudoers_line cron_system_line cron_user_line ignore_args=(
+			# these are not needed for [dorothy run] to bootstrap itself
+			--regexp="$HOME"
+			--regexp='/Applications/'
+		)
+		if [[ -n ${HOMEBREW_PREFIX-} ]]; then
+			# these are not needed for [dorothy run] to bootstrap itself
+			# and they confuse cron as it thinks they have minutes due to version numbers
+			ignore_args+=(
+				--regexp="$HOMEBREW_PREFIX/Cellar"
+				--regexp="$HOMEBREW_PREFIX/lib"
+				--regexp="$HOMEBREW_PREFIX/opt"
+			)
+		fi
+		system_paths="$(echo-split ':' --stdin <<<"$PATH" | grep --invert-match --fixed-strings "${ignore_args[@]}" | echo-join ':' --stdin)"
+
+		sudoers_line="Defaults	secure_path=\"$system_paths\"" # $HOME paths do not make sense for root operation
+		cron_system_line="PATH=\"$system_paths\""             # $HOME paths do not make sense for root operation
+		cron_user_line="PATH=\"$system_paths\""               # $HOME paths fails to apply
+
+		# sudoers
+		config-edit --sudoers --line="$sudoers_line" --needle='secure_path' --add="$option_local"
+
+		# cron
+		config-edit --cron-system --line="$cron_system_line" --needle='PATH=' --add="$option_local"
+		config-edit --cron-user --line="$cron_user_line" --needle='PATH=' --add="$option_local"
+
+		# done
+		return 0
+	fi
 
 	if is-vscode; then
 		# https://github.com/Microsoft/vscode/issues/29523
diff --git a/commands/setup-mac-brew b/commands/setup-mac-brew
--- a/commands/setup-mac-brew
+++ b/commands/setup-mac-brew
@@ -217,12 +217,12 @@ function setup_mac_brew() (
 				fi
 			fi
 			if [[ -d "$HOME/Library/Caches/go-build" ]]; then
-				fs-own --sudo --ugx -- "$HOME/Library/Caches/go-build"
+				fs-own --elevate --ugx -- "$HOME/Library/Caches/go-build"
 				# fix: go: unlinkat /Users/balupton/Library/Caches/go-build/01/0128314b8deff070ae65a398c7404f3988fc31b20cd934f950eee92284d36875-d: permission denied
 			fi
 			# cleanup
-			eval_helper --quiet \
-				-- brew cleanup --quiet -s --prune=all
+			eval_helper --quiet --wrap -- \
+				brew cleanup --quiet -s --prune=all
 			# cleanup further
 			fs-rm --quiet --no-confirm -- "$(brew --cache)"
 		fi
@@ -232,7 +232,7 @@ function setup_mac_brew() (
 	# update brew
 	function update_brew {
 		local __brew_upgrade_status=0
-		brew upgrade --quiet || __brew_upgrade_status=$?
+		brew upgrade || __brew_upgrade_status=$? # don't use `--quiet` such that progress bars are visible, which is important on slow or unreliable internet connections that otherwise may think the operation has stalled
 		if [[ $__brew_upgrade_status -ne 0 ]]; then
 			if ! confirm --positive --ppid=$$ --linger -- 'Would you like to proceed?' "The homebrew upgrade reported a failure exit status of $__brew_upgrade_status, however unless there is actually an error above that requires attention then you can proceed safely, as homebrew reports failure exit statuses when there are merely recommendations, and such recommendations are typically already handled by Dorothy."; then
 				return "$__brew_upgrade_status"
@@ -299,8 +299,8 @@ function setup_mac_brew() (
 			mapfile -t ffmpeg_opts < <(echo-split ' ' -- "$ffmpeg_opts")
 
 			# install with the build options
-			eval_helper --shapeshifter \
-				-- brew install homebrew-ffmpeg/ffmpeg/ffmpeg "${ffmpeg_opts[@]}"
+			eval_helper --quiet --wrap --shapeshifter -- \
+				brew install homebrew-ffmpeg/ffmpeg/ffmpeg "${ffmpeg_opts[@]}"
 
 			# log
 			echo-style --g2='Install ffmpeg with options'
@@ -338,13 +338,13 @@ function setup_mac_brew() (
 				brew_pkgs_bulk+=("$pkg")
 			else
 				# it has arguments, install it right now with the arguments
-				eval_helper --quiet \
-					-- brew install "${brew_opts[@]}" "${brew_pkg_args[@]}"
+				eval_helper --quiet --wrap -- \
+					brew install "${brew_opts[@]}" "${brew_pkg_args[@]}"
 			fi
 		done
 		if [[ ${#brew_pkgs_bulk[@]} -ne 0 ]]; then
-			eval_helper --quiet \
-				-- brew install "${brew_opts[@]}" "${brew_pkgs_bulk[@]}"
+			eval_helper --quiet --wrap -- \
+				brew install "${brew_opts[@]}" "${brew_pkgs_bulk[@]}"
 		fi
 	}
 
@@ -390,8 +390,8 @@ function setup_mac_brew() (
 		elif [[ $# -gt 1 ]]; then
 			fodder="$(
 				choose --multi \
-					--question='Which casks would you like to brew install?' \
-					-- "$@"
+					--question='Which casks would you like to brew install?' -- \
+					"$@"
 			)"
 			mapfile -t cask_selection <<<"$fodder" # <( destroys stdin
 		fi
@@ -405,15 +405,22 @@ function setup_mac_brew() (
 	# uninstall packages with brew
 	function brew_uninstall {
 		local pkg
-		echo-style --h2="Uninstall $# formulas"
+		echo-style --h2="Uninstall $# packages"
 		if [[ $# -ne 0 ]]; then
-			echo-style --dim='You can ignore "No available ..." errors.'
-			echo-style --dim='You can ignore "No such keg: ..." errors.'
-			for pkg in "$@"; do
-				brew uninstall --quiet --ignore-dependencies "$pkg" || :
-			done
+			if brew-installed -- "$@" &>/dev/null; then
+				echo-style --dim='You can ignore "No available ..." errors.'
+				echo-style --dim='You can ignore "No such keg: ..." errors.'
+				for pkg in "$@"; do
+					brew uninstall --quiet --ignore-dependencies "$pkg" || :
+				done
+				# cleanup, used to fix any breaks after the removals, this is only here are is purges upgrade caches, which is undesirable on unreliable internet connections as it means re-runs always has to download everything again
+				source "$DOROTHY/sources/environment.sh"
+				clean_brew
+			else
+				echo-style --dim='Already uninstalled.'
+			fi
 		fi
-		echo-style --g2="Uninstall $# formulas"
+		echo-style --g2="Uninstall $# packages"
 	}
 
 	# untap repositories with brew
@@ -434,10 +441,10 @@ function setup_mac_brew() (
 		local tap
 		echo-style --h2="Tap $# repositories"
 		for tap in "$@"; do
-			eval_helper --quiet --no-wrap \
+			eval_helper --quiet --wrap \
 				--pending="Tap: $tap" \
-				--success="Tapped: $tap" \
-				-- brew tap --quiet "$tap"
+				--success="Tapped: $tap" -- \
+				brew tap --quiet "$tap"
 		done
 		echo-style --g2="Tap $# repositories"
 	}
@@ -465,10 +472,10 @@ function setup_mac_brew() (
 		local repo
 		echo-style --h2="Update $# repositories"
 		for repo in "$@"; do
-			eval_helper --quiet --no-wrap \
+			eval_helper --quiet --wrap \
 				--pending="Updating: $repo" \
-				--success="Updated: $repo" \
-				-- brew_update_repo "$repo"
+				--success="Updated: $repo" -- \
+				brew_update_repo "$repo"
 		done
 		echo-style --g2="Update $# repositories"
 	}
@@ -519,11 +526,6 @@ function setup_mac_brew() (
 	# uninstall packages
 	brew_uninstall "${HOMEBREW_UNINSTALL[@]}"
 
-	# cleanup
-	# used to fix any breaks after the removals
-	source "$DOROTHY/sources/environment.sh"
-	clean_brew
-
 	# uninstall encoding tools
 	# this is necessary before updates, as it could update to a broken update
 	# as such, uninstall before updates, so we can reinstall with our workarounds after
@@ -536,8 +538,8 @@ function setup_mac_brew() (
 
 	# dependencies
 	echo-style --h2='Install build dependencies'
-	eval_helper --quiet \
-		-- setup-util-devel
+	eval_helper --quiet --wrap -- \
+		setup-util-devel
 	echo-style --g2='Install build dependencies'
 
 	# install encoding tools
@@ -592,10 +594,10 @@ function setup_mac_brew() (
 				fi
 				continue
 			fi
-			if is-needle --needle="$item" -- "${HOMEBREW_SLOW_FORMULAS[@]}"; then
+			if __is_within "$item" 'HOMEBREW_SLOW_FORMULAS'; then
 				continue
 			fi
-			if is-needle --needle="$item" -- "${HOMEBREW_ENCODING_FORMULAS[@]}"; then
+			if __is_within "$item" 'HOMEBREW_ENCODING_FORMULAS'; then
 				continue
 			fi
 			if [[ $item == *'ffmpeg'* ]]; then
diff --git a/commands/setup-system b/commands/setup-system
--- a/commands/setup-system
+++ b/commands/setup-system
@@ -121,22 +121,22 @@ function setup_system() (
 			# "$XDG_CACHE_HOME/gems"
 			# "$XDG_CACHE_HOME/pip/http"
 		)
-		fs-rm --quiet --no-confirm --sudo -- "${caches[@]}" || :
+		fs-rm --quiet --no-confirm --elevate -- "${caches[@]}" || :
 		__mkdirp "${recreate[@]}"
 	}
-	eval_helper --shapeshifter --no-wrap \
+	eval_helper --quiet --wrap --shapeshifter \
 		--pending="$(echo-style --bold="Cleaning directory caches...")" \
 		--success="$(echo-style --success="Cleaned directory caches.")" \
-		--failure="$(echo-style --error="Failed to clean directory caches.")" \
-		-- clean_dirs
+		--failure="$(echo-style --error="Failed to clean directory caches.")" -- \
+		clean_dirs
 
 	# npm
 	if __command_exists -- npm; then
-		eval_helper --shapeshifter --no-wrap \
+		eval_helper --quiet --wrap --shapeshifter \
 			--pending="$(echo-style --bold="Cleaning npm...")" \
 			--success="$(echo-style --success="Cleaned npm.")" \
-			--failure="$(echo-style --error="Failed to clean npm.")" \
-			-- nvm-env -- npm cache clean --force || :
+			--failure="$(echo-style --error="Failed to clean npm.")" -- \
+			nvm-env -- npm cache clean --force || :
 	fi
 
 	# operating system
