`__tool`, `__require_command`, `__print_style`
- continue performance improvements
- simplify some common patterns
- add `__affirm_function_is_defined`
- leftover `echo-style` now `__print_style`
- more `|| return` usage
- convert `is-fs.bash` and its callers to safety functions for eventual bash 4.3 compat

diff --git a/commands.beta/setup-server b/commands.beta/setup-server
--- a/commands.beta/setup-server
+++ b/commands.beta/setup-server
@@ -21,9 +21,9 @@ function setup_server() (
 	local DRIVE_MOUNT=() VAULT_MOUNT=() SAMBA_MOUNT=()
 	local PLEX_HOME='' SYNCTHING_HOME='' TRANSMISSION_HOME=''
 	local NORDVPN_TOKEN='' NORDVPN_DNS='' # 1.1.1.1 or 192.168.5.20 or whatever
-	echo-style --h2='server configuration'
+	__print_style --h2='server configuration' || return
 	load_dorothy_config 'server.bash'
-	echo-style --g2='server configuration'
+	__print_style --g2='server configuration' || return
 
 	# -------------------------------------
 	# Adjustments
@@ -184,7 +184,7 @@ function setup_server() (
 				fi
 				# skip if user already inside the group
 				if is-user-in-group --user="$user" --group="$group"; then
-					echo-style --dim="user [$user] is already inside group [$group]"
+					__print_style --dim="user [$user] is already inside group [$group]" || return
 					continue
 				fi
 				# add the user to the group
@@ -198,7 +198,7 @@ function setup_server() (
 
 		# check if reload is necessary
 		if [[ $option_reload == 'yes' ]]; then
-			echo-style \
+			__print_style \
 				--success="The current user [$me] has been added to new groups." --newline \
 				--notice='You must logout or reboot for the change to apply.'
 		fi
@@ -235,7 +235,7 @@ function setup_server() (
 			if is-missing --user="$SHARE_USER" --group="$SHARE_GROUP" -- "$PLEX_HOME"; then
 				eval-helper --elevate -- mv -v -- "$temp" "$PLEX_HOME"
 			else
-				echo-style --warning="Both [$temp] and [$PLEX_HOME] exist"
+				__print_style --warning="Both [$temp] and [$PLEX_HOME] exist" || return
 			fi
 		fi
 		if is-present --user="$SHARE_USER" --group="$SHARE_GROUP" -- "$temp"; then
@@ -252,7 +252,7 @@ function setup_server() (
 			if is-missing --user="$SHARE_USER" --group="$SHARE_GROUP" -- "$SYNCTHING_HOME"; then
 				eval-helper --elevate -- mv -v -- "$temp" "$SYNCTHING_HOME"
 			else
-				echo-style --warning="Both [$temp] and [$SYNCTHING_HOME] exist"
+				__print_style --warning="Both [$temp] and [$SYNCTHING_HOME] exist" || return
 			fi
 		fi
 		if is-present --user="$SHARE_USER" --group="$SHARE_GROUP" -- "$temp"; then
@@ -272,7 +272,7 @@ function setup_server() (
 			if is-missing --user="$SHARE_USER" --group="$SHARE_GROUP" -- "$TRANSMISSION_HOME"; then
 				eval-helper --elevate -- mv -v -- "$temp" "$TRANSMISSION_HOME"
 			else
-				echo-style --warning="Both [$temp] and [$TRANSMISSION_HOME] exist"
+				__print_style --warning="Both [$temp] and [$TRANSMISSION_HOME] exist" || return
 			fi
 		fi
 		if is-present --user="$SHARE_USER" --group="$SHARE_GROUP" -- "$temp"; then
@@ -291,7 +291,7 @@ function setup_server() (
 			eval-helper --verbose --wrap -- \
 				fs-own --optional --permissions="$perms" --user="$SHARE_USER" --group="$SHARE_GROUP" --recursive -- "${paths[@]}"
 		else
-			echo-style --notice='No service configurations found yet.'
+			__print_style --notice='No service configurations found yet.' || return
 		fi
 	}
 
@@ -395,7 +395,7 @@ function setup_server() (
 		nordvpn set firewall on || : # or to prevent already enabled errors
 		waiter 5                     # this can take a while for changes to be reflected
 		if ! nordvpn settings | echo-write --buffer | grep --quiet --fixed-strings --regexp='Firewall: enabled'; then
-			echo-style --error='Firewall failed to enable. Reboot your machine.'
+			__print_style --error='Firewall failed to enable. Reboot your machine.' || return
 			return 2
 		fi
 
@@ -403,7 +403,7 @@ function setup_server() (
 		nordvpn set killswitch on || : # or to prevent already enabled errors
 		waiter 5                       # this can take a while for changes to be reflected
 		if ! nordvpn settings | echo-write --buffer | grep --quiet --fixed-strings --regexp='Kill Switch: enabled'; then
-			echo-style --error='Killswitch failed to enable. Reboot your machine.'
+			__print_style --error='Killswitch failed to enable. Reboot your machine.' || return
 			return 2
 		fi
 	}
@@ -419,9 +419,9 @@ function setup_server() (
 			clear_address="$(what-is-my-ip remote)"
 			clear_prefix="$(__print_lines "$clear_address" | echo-regexp -o --regexp='^[0-9]+[.][0-9]+[.][0-9]+[.]')"
 			if [[ $vpn_prefix == "$clear_prefix" ]]; then
-				echo-style --success="Successfully connected [$clear_address] to NordVPN [$vpn_address]."
+				__print_style --success="Successfully connected [$clear_address] to NordVPN [$vpn_address]." || return
 			else
-				echo-style --error="Not connected [$clear_address] to NordVPN [$vpn_address]."
+				__print_style --error="Not connected [$clear_address] to NordVPN [$vpn_address]." || return
 				return 1
 			fi
 		else
@@ -572,7 +572,7 @@ function setup_server() (
 			# attempt nordvpn connect
 			nordvpn set autoconnect on P2P
 			nordvpn connect P2P || {
-				echo-style --warning='NordVPN failed to connect, here are the logs:'
+				__print_style --warning='NordVPN failed to connect, here are the logs:' || return
 				service-helper --logs -- nordvpnd
 				nordvpn connect P2P || __return $? -- __print_error 'NordVPN failed to connect, try rebooting manually.' || return
 			}
@@ -603,29 +603,29 @@ function setup_server() (
 		if [[ $check_status -eq 2 ]]; then
 			# killswitch failed, we must reboot
 			act_stop
-			echo-style --warning='Failed to activate killswitch. Stopped all services. Ready for reboot:'
-			echo-style --code='sudo reboot'
+			__print_style --warning='Failed to activate killswitch. Stopped all services. Ready for reboot:' || return
+			__print_style --code='sudo reboot' || return
 			return 1
 		elif [[ $check_status -ne 0 ]]; then
 			# failed to connect, try again
 			service-helper --stop --ignore -- "${services_vpn_dependent[@]}"
 			__try {check_status} -- act_connect
 			if [[ $check_status -eq 0 ]]; then
-				echo-style --success='Reconnected to NordVPN.'
+				__print_style --success='Reconnected to NordVPN.' || return
 
-				echo-style --notice='Resuming dependent services:'
+				__print_style --notice='Resuming dependent services:' || return
 				# the [|| :] is to that we resume, rather than start, as the service may be dependent on another service such as samba or a mount, this functionality is more just for temporary vpn disconnections/reconnections
 				service-helper --start --ignore -- "${services_vpn_dependent[@]}" || :
-				echo-style --success='Resumed dependent services.'
+				__print_style --success='Resumed dependent services.' || return
 			else
-				echo-style --error='Failed to connect to NordVPN.'
-				echo-style --notice='As dependent services have already stopped, disabling NordVPN.'
+				__print_style --error='Failed to connect to NordVPN.' || return
+				__print_style --notice='As dependent services have already stopped, disabling NordVPN.' || return
 				act_disconnect
-				echo-style --warning='You will have to figure out why NordVPN failed.'
+				__print_style --warning='You will have to figure out why NordVPN failed.' || return
 				return 1
 			fi
 		else
-			echo-style --success='Connection OK.'
+			__print_style --success='Connection OK.' || return
 		fi
 	}
 
@@ -823,12 +823,9 @@ function setup_server() (
 	# act
 	if [[ -z $action ]]; then
 		help 'No <action> provided.'
-	elif [[ "$(type -t "act_$action")" == 'function' ]]; then
-		"act_$action" "${option_args[@]}"
-	else
-		__print_error "$0: Action not yet implemented: $action"
-		return 78 # ENOSYS 78 Function not implemented
 	fi
+	__affirm_function_is_defined "act_$action"
+	"act_$action" "${option_args[@]}" # eval
 )
 
 # fire if invoked standalone
