`alias-*`: redo with modern dorothy conventions

diff --git a/commands/alias-make b/commands/alias-make
--- a/commands/alias-make
+++ b/commands/alias-make
@@ -1,39 +1,37 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# continue
-sourcePath="$(fs-absolute "$1")"
-targetPath="$(fs-absolute "$2")"
-targetDirectory="$(dirname "$targetPath")"
-targetFilename="$(basename "$targetPath")"
+# inputs
+path="$(ask --question="Enter path where you want the macOS alias file to exist." --default="${1-}" --required)"
+target="$(ask --question="Enter path where you want the macOS alias file to target." --default="${2-}" --required)"
 
-if is-dir "$1"; then
+# prepare
+targetAbsolute="$(fs-absolute "$target")"
+pathAbsolute="$(fs-absolute "$path")"
+pathDirectory="$(dirname "$pathAbsolute")"
+pathFilename="$(basename "$pathAbsolute")"
+
+# act
+if test -d "$targetAbsolute"; then
 	type="folder"
+elif test -f "$targetAbsolute"; then
+	type="file"
 else
-	if is-file "$1"; then
-		type="file"
-	else
-		echo "Invalid path or unsupported type"
-		exit 22 # Invalid argument
-	fi
+	stderr echo "Invalid path or unsupported type"
+	exit 22 # Invalid argument
 fi
 
-ok rm -rfi "$2"
+if test -f "$pathAbsolute"; then
+	rm -rfi "$pathAbsolute"
+fi
 
-osascript <<EOF
-tell application "Finder"
-	make new alias to $type (posix file "$sourcePath") at (posix file "$targetDirectory")
-	set name of result to "$targetFilename"
-end tell
+osascript <<-EOF
+	tell application "Finder"
+		make new alias to $type (posix file "$targetAbsolute") at (posix file "$pathDirectory")
+		set name of result to "$pathFilename"
+	end tell
 EOF
 
-chmod "$(stat -f '%p' "$sourcePath")" "$targetPath"
-
-#chmod --reference="$sourcePath" "$targetPath"
-
-# make new alias to $type (posix file "$from") at (posix file "$todir")
-# set name of result to "$toname"
-
-# osascript -e 'tell application "Finder"' -e "make new alias to $type (posix file \"$sourcePath\") at (posix file \"$targetDirectory\")" -e "set name of result to \"$targetFilename\"" -e 'end tell'
-
-# make new alias to $type (posix file "$1") at desktop
+# make the alias's permissions the same as the target's
+chmod "$(stat -f '%p' "$targetAbsolute")" "$pathAbsolute"
+#chmod --reference="$targetPath" "$pathAbsolute"
