major rewrite of many commands, some still WIP

diff --git a/commands/alias-helper b/commands/alias-helper
--- a/commands/alias-helper
+++ b/commands/alias-helper
@@ -1,254 +1,217 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# =====================================
-# Arguments
+function alias-helper() (
+	# =====================================
+	# Arguments
 
-# prepare
-actions=(
-	new
-	symlink
-	verify
-	target
-	info
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Wrappers around macOS aliases to make things easier.
+
+			USAGE:
+			alias-helper <action>
+
+			ACTIONS:
+			new -- <alias-file-path> <target-file-path>
+			    Makes a new macOS alias file at the <alias-file-path> pointing to the <target-file-path>.
+
+			symlink -- <alias-file-path>
+			    Converts the macOS alias file with its UNIX symlink equivalent.
+
+			verify -- <alias-file-path>
+			    Verify the path is a macOS alias file.
+
+			target -- <alias-file-path>
+			    Output the target if the path is a macOS alias file.
+
+			info -- <alias-file-path>
+			    Human friendly details about the macOS alias file.
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item action='' args=()
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--')
+			args+=("$@")
+			shift $#
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*)
+			if test -z "$action"; then
+				action="$item"
+			else
+				help "An unrecognised argument was provided: $item"
+			fi
+			;;
+		esac
+	done
+
+	# =====================================
+	# Actions
+
+	function alias_verify {
+		local path="$1"
+		silent-stderr osascript <<-EOF
+			tell application "Finder"
+				set theItem to (POSIX file "$path") as alias
+				if the kind of theItem is "alias" then
+					get the posix path of ((theItem) as text)
+				end if
+			end tell
+		EOF
+	}
+
+	function alias_target {
+		local path="$1"
+		silent-stderr osascript <<-EOF
+			tell application "Finder"
+				set theItem to (POSIX file "$path") as alias
+				if the kind of theItem is "alias" then
+					get the POSIX path of ((original item of theItem) as text)
+				end if
+			end tell
+		EOF
+	}
+
+	function alias_info {
+		local path="$1" src target
+
+		# verify
+		src="$(alias_verify "$path" || :)"
+		if test -z "$src"; then
+			{
+				echo-style \
+					--bold+red="$path" \
+					$'\t' \
+					$'\t' --error='← not an alias'
+				return 22 # EINVAL Invalid argument
+			} >/dev/stderr
+		fi
+
+		# target
+		target="$(aliastarget "$path" || :)"
+		if test -z "$target"; then
+			{
+				stderr echo-style \
+					--bold="$src" \
+					$'\t' \
+					$'\t' --error='← target broken'
+				return 9 # EBADF Bad file descriptor
+			} >/dev/stderr
+		fi
+		if test ! -e "$target"; then
+			{
+				stderr echo-style \
+					--bold="$src" \
+					--nocolor=$'\t' --color+dim=$'\t→\t' --bold+red="$target" \
+					$'\t' --error='← target missing'
+				return 2 # ENOENT No such file or directory
+			} >/dev/stderr
+		fi
+
+		# success
+		echo-style \
+			--bold="$src" \
+			--nocolor=$'\t' --color+dim=$'\t→\t' --bold+green="$target"
+	}
+
+	function alias_new {
+		local path="$1" target="$2" type target_absolute path_absolute path_directory path_filename
+		target_absolute="$(fs-absolute "$target")"
+		path_absolute="$(fs-absolute "$path")"
+		path_directory="$(dirname "$path_absolute")"
+		path_filename="$(basename "$path_absolute")"
+
+		# act
+		if test -d "$target_absolute"; then
+			type="folder"
+		elif test -f "$target_absolute"; then
+			type="file"
+		else
+			{
+				echo-style --error='Invalid path or unsupported type:' ' ' --code="$path"
+				return 22 # EINVAL Invalid argument
+			} >/dev/stderr
+		fi
+
+		if test -f "$path_absolute"; then
+			fs-rm "$path_absolute"
+		fi
+
+		osascript <<-EOF
+			tell application "Finder"
+				make new alias to ${type} (posix file "$target_absolute") at (posix file "$path_directory")
+				set name of result to "$path_filename"
+			end tell
+		EOF
+
+		# make the alias's permissions the same as the target's
+		chmod "$(stat -f '%p' "$target_absolute")" "$path_absolute"
+		#chmod --reference="$targetPath" "$path_absolute"
+	}
+
+	function alias_symlink {
+		local path="$1" src target
+
+		# verify alias
+		src="$(alias_verify "$path" || :)"
+		if test -z "$src"; then
+			{
+				echo-style --bold+red="$path" ' ' --error='<- not an alias'
+				return 22 # EINVAL Invalid argument
+			} >/dev/stderr
+		fi
+
+		# verify target
+		target="$(alias_target "$path" || :)"
+		if test -z "$target"; then
+			{
+				echo-style --bold="$src" --dim=' → ' --bold+red="$target" ' ' --error='← target broken'
+				return 9 # EBADF Bad file descriptor
+			} >/dev/stderr
+		fi
+		if test ! -e "$target"; then
+			{
+				echo-style --bold="$src" --dim=' → ' --bold+red="$target" ' ' --error='← target missing'
+				return 2 # ENOENT No such file or directory
+			} >/dev/stderr
+		fi
+
+		# convert
+		if test -f "$target"; then
+			ln -nfs "$target" "$src"
+			echo "converted $path -> $target"
+		elif test -d "$target"; then
+			ln -nfs "$target" "$src"
+			echo "converted $path -> $target"
+		fi
+	}
+
+	# =====================================
+	# Act
+
+	if test "$(type -t "alias_$action")" = 'function'; then
+		"alias_$action" "${args[@]}"
+		return "$?"
+	else
+		echo-style --error="Action [$action] not yet implemented." >/dev/stderr
+		return 78 # Function not implemented
+	fi
 )
 
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Wrappers around macOS aliases to make things easier.
-
-		USAGE:
-		alias-helper <action>
-
-		ACTIONS:
-		new -- <alias-file-path> <target-file-path>
-		    Creates a macOS alias file at <alias-file-path> pointing to <target-file-path>.
-
-		symlink -- <alias-file-path>
-		    Replaces the macOS alias file with its UNIX symlink equivalent.
-
-		verify -- <alias-file-path>
-		    Verify that the path is actually a macOS alias file.
-
-		target -- <alias-file-path>
-		    If the path is a macOS alias file, output its target.
-
-		info -- <alias-file-path>
-		    Human friendly details about the macOS alias file.
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
-	fi
-	return 22 # Invalid argument
-}
-
-# process
-action=''
-action_args=()
-option_path=''
-option_target=''
-while test "$#" -ne 0; do
-	item="${1-"$option_path"}"
-	shift
-	case "$item" in
-	'help' | '--help' | '-h') help ;;
-	'--action='*) action="${item:9}" ;;
-	'--path='*) option_path="${item:7}" ;;
-	'--target='*) option_target="${item:9}" ;;
-	'--')
-		action_args+=("$@")
-		shift $#
-		break
-		;;
-	'--'*) help "An unrecognised flag was provided: $item" ;;
-	*)
-		if test -z "$action"; then
-			action="$item"
-		elif test -z "$option_path"; then
-			option_path="$item"
-		elif test -z "$option_target" -a "$action" = 'new'; then
-			option_target="$item"
-		else
-			help "An unrecognised argument was provided: $item"
-		fi
-		;;
-	esac
-done
-
-# ensure valid action
-action="$(
-	choose-option --required \
-		--question='What action to perform?' \
-		--filter="$action" -- "${actions[@]}"
-)"
-
-# ensure valid paths
-option_path="$(
-	ask --required \
-		--question="Enter the path of the macOS alias file" \
-		--default="$option_path"
-)"
-if test "$action" = 'new'; then
-	option_target="$(
-		ask --required \
-			--question="Enter the path of the target file" \
-			--default="$option_target"
-	)"
-fi
-
-# =====================================
-# Actions
-
-function alias_verify {
-	local path="${1-"$option_path"}"
-	silent-stderr osascript <<-EOF
-		tell application "Finder"
-			set theItem to (POSIX file "$path") as alias
-			if the kind of theItem is "alias" then
-				get the posix path of ((theItem) as text)
-			end if
-		end tell
-	EOF
-}
-
-function alias_target {
-	local path="${1-"$option_path"}"
-	silent-stderr osascript <<-EOF
-		tell application "Finder"
-			set theItem to (POSIX file "$path") as alias
-			if the kind of theItem is "alias" then
-				get the POSIX path of ((original item of theItem) as text)
-			end if
-		end tell
-	EOF
-}
-
-function alias_info {
-	local path="${1-"$option_path"}" src target
-
-	# verify
-	src="$(alias_verify "$path" || :)"
-	if test -z "$src"; then
-		{
-			echo-style \
-				--bold+red="$path" \
-				$'\t' \
-				$'\t' --error='← not an alias'
-			exit 22 # EINVAL Invalid argument
-		} >/dev/stderr
-	fi
-
-	# target
-	target="$(alias_target "$path" || :)"
-	if test -z "$target"; then
-		{
-			stderr echo-style \
-				--bold="$src" \
-				$'\t' \
-				$'\t' --error='← target broken'
-			exit 9 # EBADF Bad file descriptor
-		} >/dev/stderr
-	fi
-	if test ! -e "$target"; then
-		{
-			stderr echo-style \
-				--bold="$src" \
-				--nocolor=$'\t' --color+dim=$'\t→\t' --bold+red="$target" \
-				$'\t' --error='← target missing'
-			exit 2 # ENOENT No such file or directory
-		} >/dev/stderr
-	fi
-
-	# success
-	echo-style \
-		--bold="$src" \
-		--nocolor=$'\t' --color+dim=$'\t→\t' --bold+green="$target"
-}
-
-function alias_new {
-	local path="${1-"$option_path"}" target="${2-"$option_target"}" type
-
-	# prepare
-	targetAbsolute="$(fs-absolute "$target")"
-	pathAbsolute="$(fs-absolute "$path")"
-	pathDirectory="$(dirname "$pathAbsolute")"
-	pathFilename="$(basename "$pathAbsolute")"
-
-	# act
-	if test -d "$targetAbsolute"; then
-		type="folder"
-	elif test -f "$targetAbsolute"; then
-		type="file"
-	else
-		{
-			echo-style --error='Invalid path or unsupported type:' ' ' --code="$path"
-			exit 22 # EINVAL Invalid argument
-		} >/dev/stderr
-	fi
-
-	if test -f "$pathAbsolute"; then
-		fs-rm "$pathAbsolute"
-	fi
-
-	osascript <<-EOF
-		tell application "Finder"
-			make new alias to $type (posix file "$targetAbsolute") at (posix file "$pathDirectory")
-			set name of result to "$pathFilename"
-		end tell
-	EOF
-
-	# make the alias's permissions the same as the target's
-	chmod "$(stat -f '%p' "$targetAbsolute")" "$pathAbsolute"
-	#chmod --reference="$targetPath" "$pathAbsolute"
-}
-
-function alias_symlink {
-	local path="${1-"$option_path"}" src
-
-	# verify alias
-	src="$(alias_verify "$path" || :)"
-	if test -z "$src"; then
-		{
-			echo-style --bold+red="$path" ' ' --error='<- not an alias'
-			exit 22 # EINVAL Invalid argument
-		} >/dev/stderr
-	fi
-
-	# verify target
-	target="$(alias_target "$path" || :)"
-	if test -z "$target"; then
-		{
-			echo-style --bold="$src" --dim=' → ' --bold+red="$target" ' ' --error='← target broken'
-			exit 9 # EBADF Bad file descriptor
-		} >/dev/stderr
-	fi
-	if test ! -e "$target"; then
-		{
-			echo-style --bold="$src" --dim=' → ' --bold+red="$target" ' ' --error='← target missing'
-			exit 2 # ENOENT No such file or directory
-		} >/dev/stderr
-	fi
-
-	# convert
-	if test -f "$target"; then
-		ln -nfs "$target" "$src"
-		echo "converted $path -> $target"
-	elif test -d "$target"; then
-		ln -nfs "$target" "$src"
-		echo "converted $path -> $target"
-	fi
-
-}
-
-# =====================================
-# Act
-
-if test "$(type -t "alias_$action")" = 'function'; then
-	"alias_$action" "${action_args[@]}"
-	exit "$?"
-else
-	echo-style --error="Action [$action] not yet implemented." >/dev/stderr
-	exit 78 # Function not implemented
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	alias-helper "$@"
 fi
diff --git a/commands/confirm b/commands/confirm
--- a/commands/confirm
+++ b/commands/confirm
@@ -3,237 +3,262 @@
 # ^ [echo -en] doesn't work with escape codes on bash v3, [printf ...] does
 source "$DOROTHY/sources/strict.bash"
 
-# =====================================
-# Arguments
+function confirm() (
+	# =====================================
+	# Arguments
 
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		USAGE:
-		confirm --ppid=\$\$ [<...flags>] -- [<question> [<...details>]]
+	function help {
+		cat <<-EOF >/dev/stderr
+			USAGE:
+			confirm --ppid=\$\$ [...options] -- <question> ...[detail]
 
-		FLAGS:
-		[--mode=<bool, positive, negative, confirm>]
-		[--timeout=<timeout in seconds>]
-		[--yes=<on positive confirmations, what value to display>]
-		[--no=<on negative confirmations, what value to display>]
-		[--abort=<on aborted confirmations, what value to display>]
-		[--ppid=<on aborted confirmations, terminate this process id>]
+			OPTIONS:
+			--mode=<bool|positive|negative|confirm>
+			    [bool] mode forces a positive or negative confirmation, with no default.
+			    [positive] mode defaults to a positive confirmation.
+			    [negative] mode defaults to a negative confirmation.
+			    [confirm] mode forces a confirmation, with no default.
 
-		QUIRKS:
-		Why is --ppid=\$\$ necessary?
-		As negative confirmations return a failure exit code, and abortions a different failure exit code, you probably need to use [--ppid=\$\$] so that confirmation abortions actually continue the abortion, and are not just considered a negative confirmation.
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
+			--timeout=<timeout>
+			    Specify the timeout in seconds.
+			    Under <negative> mode, defaults to 60 seconds (one minute) before defaulting to a negative confirmation.
+			    Under <positive> mode, defaults to 60 seconds (one minute) before defaulting to a positive confirmation.
+			    Under other modes, defaults to 3600 seconds (one hour) before abortion occurs.
+
+			--yes=<OK>
+			    What to display to the user for positive confirmations, defaults to "OK".
+
+			--no=<CANCEL>
+			    What to display to the user for negative confirmations, defaults to "CANCEL".
+
+			--abort=<ABORT>
+			    What to display to the user for aborted confirmations, defaults to "ABORT".
+
+			--ppid=<ppid>
+			    Specifies the parent process ID to also terminate upon abortion.
+			    In bourne shells this is specified like so [--ppid=\$\$]
+			    This is necessary because the typical usage of [if confirm ...; then ...; else ...; fi]
+			    will only catch positive and negative confirmations, but not abortion cases,
+			    as such abortions would otherwise be registered as negative cases.
+			    Providing the parent process ID allows the abortion to propagate to the parent,
+			    allowing the intended abortion behaviour to propagate.
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# prepare
+	local item question_parts=() mode='confirm' timeout='3600' yes='OK' no='CANCEL' abort='ABORT' ppid=''
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--mode='*)
+			mode="${item:7}" # bool/positive/negative/confirm
+			if test "$mode" = 'positive' -o "$mode" = 'negative'; then
+				timeout='60' # one minute
+				yes='YES'
+				no='NO'
+			elif test "$mode" = 'bool'; then
+				yes='YES'
+				no='NO'
+			fi
+			;;
+		'--timeout='*) timeout="${item:10}" ;;
+		'--yes='*) yes="${item:6}" ;;
+		'--no='*) no="${item:5}" ;;
+		'--abort='*) abort="${item:8}" ;;
+		'--ppid='*) ppid="${item:7}" ;; # alias for term
+		'--')
+			question_parts+=("$@")
+			shift $#
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) help "An unrecognised argument was provided: $item" ;;
+		esac
+	done
+
+	# requirements
+	if test -z "$ppid"; then
+		help '--ppid=$$ is necessary'
 	fi
-	return 22 # Invalid argument
-}
 
-# prepare
-question_parts=()
+	# =====================================
+	# Helpers
 
-# process
-option_mode='confirm'
-option_timeout='3600' # one hour
-option_yes='OK'
-option_no='CANCEL'
-option_abort='ABORT'
-option_ppid=''
-while test "$#" -ne 0; do
-	item="$1"
-	shift
-	case "$item" in
-	'help' | '--help' | '-h') help ;;
-	'--mode='*)
-		option_mode="${item:7}" # bool/positive/negative/confirm
-		if test "$option_mode" = 'positive' -o "$option_mode" = 'negative'; then
-			option_timeout='60' # one minute
-			option_yes='YES'
-			option_no='NO'
-		elif test "$option_mode" = 'bool'; then
-			option_yes='YES'
-			option_no='NO'
-		fi
-		;;
-	'--timeout='*) option_timeout="${item:10}" ;;
-	'--yes='*) option_yes="${item:6}" ;;
-	'--no='*) option_no="${item:5}" ;;
-	'--abort='*) option_abort="${item:8}" ;;
-	'--ppid='*) option_ppid="${item:7}" ;; # alias for term
-	'--')
-		question_parts+=("$@")
-		shift $#
-		break
-		;;
-	'--'*) help "An unrecognised flag was provided: $item" ;;
-	*) help "An unrecognised argument was provided: $item" ;;
-	esac
-done
+	# used to process the input
+	function confirmer {
+		local ec answer
 
-# requirements
-if test -z "$option_ppid"; then
-	help '--ppid=$$ is necessary'
-fi
+		# ask and timeout
+		ec=0 && answer="$(read-key --timeout="$timeout")" || ec="$?"
 
-# =====================================
-# Helpers
+		# process
+		if test "$mode" = 'positive'; then
+			# positive
+			if test "$ec" -eq 62; then
+				return 0 # timeout
+			elif test "$ec" -ne 0; then
+				return "$ec" # failure
+			fi
+			ec=0 && is-affirmative "$answer" || ec="$?"
+			if test "$ec" -lt 2; then
+				return "$ec"
+			elif test "$answer" = 'enter' -o "$answer" = 'space'; then
+				return 0
+			elif test "$answer" = 'escape' -o "$answer" = 'q'; then
+				return 125 # Operation canceled
+			fi
 
-# used to process the input
-function confirmer() {
-	local ec answer
+		elif test "$mode" = 'negative'; then
+			# negative
+			if test "$ec" -eq 62; then
+				return 1 # timeout
+			elif test "$ec" -ne 0; then
+				return "$ec" # failure
+			fi
+			ec=0 && is-affirmative "$answer" || ec="$?"
+			if test "$ec" -lt 2; then
+				return "$ec"
+			elif test "$answer" = 'enter' -o "$answer" = 'space'; then
+				return 1
+			elif test "$answer" = 'escape' -o "$answer" = 'q'; then
+				return 125 # Operation canceled
+			fi
 
-	# ask and timeout
-	ec=0 && answer="$(read-arrow --timeout "$option_timeout")" || ec="$?"
+		elif test "$mode" = 'bool'; then
+			# bool
+			if test "$ec" -ne 0; then
+				return "$ec" # timeout and failure
+			fi
+			ec=0 && is-affirmative "$answer" || ec="$?"
+			if test "$ec" -lt 2; then
+				return "$ec"
+			elif test "$answer" = 'escape' -o "$answer" = 'q'; then
+				return 125 # Operation canceled
+			fi
 
-	# process
-	if test "$option_mode" = 'positive'; then
-		# positive
-		if test "$ec" -eq 62; then
-			return 0 # timeout
-		elif test "$ec" -ne 0; then
-			return "$ec" # failure
-		fi
-		ec=0 && is-affirmative "$answer" || ec="$?"
-		if test "$ec" -lt 2; then
-			return "$ec"
-		elif test "$answer" = 'enter' -o "$answer" = 'space'; then
-			return 0
-		elif test "$answer" = 'escape' -o "$answer" = 'q'; then
-			return 125 # Operation canceled
-		fi
+		elif test "$mode" = 'confirm'; then
+			# confirm
+			if test "$ec" -ne 0; then
+				return "$ec" # timeout and failure
+			fi
+			ec=0 && is-affirmative "$answer" || ec="$?"
+			if test "$ec" -lt 2; then
+				return "$ec"
+			elif test "$answer" = 'enter' -o "$answer" = 'space'; then
+				return 0
+			elif test "$answer" = 'escape' -o "$answer" = 'q'; then
+				return 125 # Operation canceled
+			fi
 
-	elif test "$option_mode" = 'negative'; then
-		# negative
-		if test "$ec" -eq 62; then
-			return 1 # timeout
-		elif test "$ec" -ne 0; then
-			return "$ec" # failure
-		fi
-		ec=0 && is-affirmative "$answer" || ec="$?"
-		if test "$ec" -lt 2; then
-			return "$ec"
-		elif test "$answer" = 'enter' -o "$answer" = 'space'; then
-			return 1
-		elif test "$answer" = 'escape' -o "$answer" = 'q'; then
-			return 125 # Operation canceled
-		fi
-
-	elif test "$option_mode" = 'bool'; then
-		# bool
-		if test "$ec" -ne 0; then
-			return "$ec" # timeout and failure
-		fi
-		ec=0 && is-affirmative "$answer" || ec="$?"
-		if test "$ec" -lt 2; then
-			return "$ec"
-		elif test "$answer" = 'escape' -o "$answer" = 'q'; then
-			return 125 # Operation canceled
-		fi
-
-	else
-		# confirm
-		if test "$ec" -ne 0; then
-			return "$ec" # timeout and failure
-		fi
-		if test "$answer" = 'escape'; then
-			return 125 # Operation canceled
 		else
-			# @todo what happens here if scrolling on ssh
-			return 0
+			# unknown
+			help "An invalid <mode> was provided: $mode"
 		fi
-	fi
 
-	# try again, and erase any leaked characters
-	printf "\e[${hx}G\e[K"
-	confirmer "$@"
-	return "$?" # return with the above on success and failure
-}
+		# try again, and erase any leaked characters
+		printf "\e[${hx}G\e[K"
+		confirmer "$@"
+		return "$?" # return with the above on success and failure
+	}
 
-# =====================================
-# Question
+	# =====================================
+	# Question
 
-# prepare
-question_first_part="${question_parts[0]} " # this is stored for the finale
-question_parts_total="${#question_parts[@]}"
-question_parts_last="$((question_parts_total - 1))"
-header="$(mktemp)"
-lines=0
-ec=0
+	local question_first_part="${question_parts[0]} " # this is stored for the finale
+	local question_parts_total="${#question_parts[@]}"
+	local question_parts_last="$((question_parts_total - 1))"
+	local index header lines=0 result=0 _hx=''
+	header="$(mktemp)"
 
-# update the first question part
-if test "$option_mode" = 'positive'; then
-	question_parts[0]+=" $(echo-style --blink='(' --blink+green+bold='Y' --blink='/n)')"
-elif test "$option_mode" = 'negative'; then
-	question_parts[0]+=" $(echo-style --blink='(y/' --blink+red+bold='N' --blink=')')"
-elif test "$option_mode" = 'bool'; then
-	question_parts[0]+=" $(echo-style --blink='(y/n)')"
-fi
-
-# output the question parts
-# saving the cursor position of the first line
-# and outputting a newline beteen all lines, except the last, which should not have a trailing line
-for ((i = 0; i < "$question_parts_total"; i++)); do
-	echo -n "${question_parts[i]} " | tee -a "$header"
-	if test "$i" -eq 0; then
-		# read cursor x y, discard y, set hx to y
-		IFS='[;' read -srd R -p $'\e[6n' _ _ hx
-	fi
-	if test "$i" -ne "$question_parts_last"; then
-		echo | tee -a "$header"
-	fi
-done
-
-# move the cursor
-if test "$question_parts_total" -ne 0; then
-	# reposition the cursor, to after the options in the first part
-	lines="$(echo-count-lines --no-inline <"$header")"
-	# move these lines up
-	if test "$lines" -ne 0; then
-		printf "\e[${lines}F"
-	fi
-	# move to the hx column
-	printf "\e[${hx}G"
-fi
-
-# handle terminations
-function failure() {
-	ec="$?"
-}
-function finish() {
-	# in case we were called naturally, erase the listen
-	trap - EXIT
-	# make sure to erase question, as ctrl+c buggers everything
-	echo -n $'\e[G\e[J'
-	# output the finale
-	if test "$ec" -eq 0; then
-		echo-style "$question_first_part" --green+bold="$option_yes"
-	elif test "$ec" -eq 1; then
-		echo-style "$question_first_part" --red+bold="$option_no"
+	# update the first question part
+	if test "$mode" = 'positive'; then
+		question_parts[0]+=" $(echo-style --blink='(' --blink+green+bold='Y' --blink='/n)')"
+	elif test "$mode" = 'negative'; then
+		question_parts[0]+=" $(echo-style --blink='(y/' --blink+red+bold='N' --blink=')')"
+	elif test "$mode" = 'bool'; then
+		question_parts[0]+=" $(echo-style --blink='(y/n)')"
+	elif test "$mode" = 'confirm'; then
+		question_parts[0]+=" $(echo-style --blink='(CONFIRM)')"
 	else
-		echo-style "$question_first_part" --red+bold="$option_abort"
-		if test -n "$option_ppid"; then
-			# kill "-$ec" ...
-			# ^ fails because 130 isn't supported
-			# kill -n ... ...
-			# kill "-$(kill -l "$ec")" ...
-			# ^ works but isn't serious enough to cause the termination
-			# "$(ps -p $$ -o ppid=)"
-			# ^ doesn't work, as is different pid than manual
-			kill "$option_ppid"
-		fi
+		help "An invalid <mode> was provided: $mode"
 	fi
-}
-trap failure SIGINT SIGTERM
-trap finish EXIT
 
-# read and handle answer
-confirmer || ec="$?"
-finish
-exit "$ec" # exit with the result
+	# output the question parts
+	# saving the cursor position of the first line
+	# and outputting a newline beteen all lines, except the last, which should not have a trailing line
+	for ((index = 0; index < "$question_parts_total"; index++)); do
+		echo -n "${question_parts[index]} " | tee -a "$header"
+		if test "$index" -eq 0; then
+			# read cursor x y, discard y, set hx to y
+			IFS='[;' read -srd R -p $'\e[6n' _ _ hx
+		fi
+		if test "$index" -ne "$question_parts_last"; then
+			echo | tee -a "$header"
+		fi
+	done
 
-# @todo
-# an alternative implementation could be a new line like this at the end, with ENTER and ESCAPE and SPACE as the correct outputs
-# echo-style --blink='Press: ' --blink+green+bold='y ' --blink='for ' --blink+green='YES' --blink=', ' --blink+red+bold='n ' --blink='for ' --blink+red='NO' --blink=', ' --blink+bold='ENTER '  --blink='for ' --blink+red='NO'
+	# move the cursor
+	if test "$question_parts_total" -ne 0; then
+		# reposition the cursor, to after the options in the first part
+		lines="$(echo-count-lines --no-inline <"$header")"
+		# move these lines up
+		if test "$lines" -ne 0; then
+			printf "\e[${lines}F"
+		fi
+		# move to the hx column
+		printf "\e[${hx}G"
+	fi
 
-# using \e[s (save) and \e[u (restore) for ctrl+c handling did not work
+	# handle terminations
+	function failure {
+		result="$?"
+	}
+	function finish {
+		# in case we were called naturally, erase the listen
+		trap - EXIT
+		# make sure to erase question, as ctrl+c buggers everything
+		printf '\e[G\e[J'
+		# output the finale
+		if test "$result" -eq 0; then
+			echo-style "$question_first_part" --green+bold="$yes"
+		elif test "$result" -eq 1; then
+			echo-style "$question_first_part" --red+bold="$no"
+		else
+			echo-style "$question_first_part" --red+bold="$abort"
+			if test -n "$ppid"; then
+				# kill "-$ppid" ...
+				# ^ fails because 130 isn't supported
+				# kill -n ... ...
+				# kill "-$(kill -l "$ppid")" ...
+				# ^ works but isn't serious enough to cause the termination
+				# "$(ps -p $$ -o ppid=)"
+				# ^ doesn't work, as is different pid than manual
+				kill "$ppid"
+			fi
+		fi
+	}
+	trap failure SIGINT SIGTERM
+	trap finish EXIT
+
+	# read and handle answer
+	confirmer || result="$?"
+	finish
+	exit "$result" # exit with the result
+
+	# @todo
+	# an alternative implementation could be a new line like this at the end, with ENTER and ESCAPE and SPACE as the correct outputs
+	# echo-style --blink='Press: ' --blink+green+bold='y ' --blink='for ' --blink+green='YES' --blink=', ' --blink+red+bold='n ' --blink='for ' --blink+red='NO' --blink=', ' --blink+bold='ENTER '  --blink='for ' --blink+red='NO'
+
+	# using \e[s (save) and \e[u (restore) for ctrl+c handling did not work
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	confirm "$@"
+fi
diff --git a/commands/contains-line b/commands/contains-line
--- a/commands/contains-line
+++ b/commands/contains-line
@@ -1,55 +1,64 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# @todo: what is the different between contains-string, contains-word, contains-line?
+function contains-line() (
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Returns [0] if a STDIN line matched <line>, otherwise returns [1].
 
-function help() {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Checks whether the <line> is contained in stdin.
+			USAGE:
+			contains-line <line>
+			echo-lines <...input> | contains-line <line>
 
-		USAGE:
-		printf 'one\ntwo\nthree'   | contains-line 'two'      # success
-		printf 'one\ntwo\nthree'   | contains-line 'three'    # success
-		printf 'one\n\nthree\n'    | contains-line ''         # success
-		printf 'one\ntwo\nthree\n' | contains-line ''         # failure
+			USAGE:
+			echo-lines 'one' 'two' 'three'  | contains-line 'two'    # success
+			echo-lines 'one' 'two' 'three'  | contains-line 'three'  # success
+			echo-lines 'one' 'two' 'three'  | contains-line 'w'      # failure
+			echo-lines 'one' 'two' 'three'  | contains-line ''       # failure
 
-		RETURNS:
-		[0] if the line is contained in stdin.
-		[1] if the line is not contained in stdin.
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
-	fi
-	return 22 # Invalid argument
-}
+			RETURNS:
+			[0] if the line is contained in stdin.
+			[1] if the line is not contained in stdin.
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
 
-option_line=''
-function arg {
-	if test -z "$option_line"; then
-		option_line="$1"
-	else
-		help "An unrecognised argument was provided: $1"
-	fi
-}
-function line {
-	if test "$1" = "$option_line"; then
-		# it was found, success case, exit immediately
-		exit 0
-	fi
-	# not found, continue reading
-}
-function finish {
-	# it was not found, failure case
-	return 1
-}
+	local expected=''
+	function on_arg {
+		if test -z "$expected"; then
+			expected="$1"
+		else
+			help "An unrecognised argument was provided: $1"
+		fi
+	}
+	function on_line {
+		if test "$1" = "$expected"; then
+			# it was found, success case, exit immediately
+			exit 0
+		fi
+		# not found, continue reading
+	}
+	function on_finish {
+		# it was not found, failure case
+		return 1
+	}
+	function on_no_args {
+		help "Missing <line> argument."
+	}
+	function on_no_stdin {
+		help "Missing STDIN to check the <line> against." || :
+		return 96 # ENODATA 96 No message available on STREAM
+	}
 
-export require_stdin='yes'
-function no_args {
-	help "Missing <line> argument."
-}
-function no_stdin {
-	help "Missing STDIN to check the <line> against." || :
-	return 96 # ENODATA 96 No message available on STREAM
-}
-source "$DOROTHY/sources/stdinargs.bash"
+	local REQUIRE_STDIN='yes'
+	source "$DOROTHY/sources/stdinargs.bash"
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	contains-line "$@"
+fi
diff --git a/commands/down b/commands/down
--- a/commands/down
+++ b/commands/down
@@ -1,66 +1,228 @@
 #!/usr/bin/env bash
-# shellcheck disable=SC2164,SC1091
 source "$DOROTHY/sources/strict.bash"
 
-# download a file
-# do not use the continue flags as they will prefer the local file over the remote file if the local exists
+function down() (
+	# supported downloaders
+	local available=() downloaders=(
+		aria2c
+		wget
+		curl
+		http
+	)
 
-# help
-if is-help "$@"; then
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		??????
-	EOF
-	return 22 # Invalid argument
-fi
+	# determine which downloaders are available
+	local downloader
+	for downloader in "${downloaders[@]}"; do
+		if command-exists "$downloader"; then
+			available+=("$downloader")
+		fi
+	done
 
-# options
-url="$(
-	ask --required \
-		--question="Enter the URL of the file to download" \
-		--default="${1-}"
-)"
-destination="$(get-flag-value destination -- "$@")" # custom destination
-if test -n "$destination"; then
-	dir="$(dirname "$destination")"
-	file="$(basename "$destination")"
-fi
+	# if no downloaders are available, install aria2
+	if test "${#available[@]}" -eq 0; then
+		env QUIET=yes setup-util-aria2
+		available+=(aria2c)
+	fi
 
-# https://github.com/aria2/aria2/issues/1137
-if command-exists aria2c; then
-	if test -n "$destination"; then
-		aria2c --allow-overwrite=true --auto-file-renaming=false --dir="$dir" --out="$file" "$url"
-	else
-		aria2c --allow-overwrite=true --auto-file-renaming=false "$url"
+	# =====================================
+	# Arguments
+
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Download a file, using the best available tool, and with the best available options.
+
+			USAGE:
+			down [...options] <url>
+
+			OPTIONS:
+			--downloader=<downloader>
+			    Enforce the usage of <downloader>.
+			    If omitted, the first available preferred downloader will be used.
+
+			--unzip-format=<format>
+			    Treat the download as a zip file, and enforce <format> as the extraction format.
+			    This option is handled by the [unziptar] command.
+
+			--unzip-filter=<filter>
+			    Treat the download as a zip fie, and only extract files that match the glob pattern <filter>.
+			    This option is handled by the [unziptar] command.
+
+			--directory=<path>
+			    Place downloaded file(s) inside <path>.
+			    If ommitted, the current working directory will be used.
+
+			--file=<filename>
+			    If only a single file was downloaded, rename it to <filename>.
+			    If multiple files were downloaded, then fail.
+
+			--path=<path>/<filename>
+			    Set the <path> and <filename> from this value.
+
+			DOWNLOADERS:
+			The following downloaders, sorted by order of preference, were determined to be available on your system:
+
+			    ${available[*]}
+
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item
+	local option_url=''
+	local option_downloader=''
+	local option_unzip_format=''
+	local option_unzip_filter=''
+	local option_directory=''
+	local option_file=''
+	local option_path=''
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--downloader='*) option_downloader="${item:13}" ;;
+		'--unzip-format='*) option_unzip_format="${item:15}" ;;
+		'--unzip-filter='*) option_unzip_filter="${item:15}" ;;
+		'--directory='*) option_directory="${item:12}" ;;
+		'--filename='*) option_file="${item:11}" ;;
+		'--path='*) option_path="${item:7}" ;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*)
+			if test -z "$option_url"; then
+				option_url="$item"
+			else
+				help "An unrecognised argument was provided: $item"
+			fi
+			;;
+		esac
+	done
+
+	# destination shorthand
+	if test -n "$option_destination"; then
+		option_inside="$(dirname "$option_destination")"
+		option_file="$(basename "$option_destination")"
 	fi
-elif command-exists wget; then
-	#   -O,  --output-document=FILE      write documents to FILE
-	#   -o,  --output-file=FILE          log messages to FILE
-	#   -N,  --timestamping              don't re-retrieve files unless newer than local
-	#   -c,  --continue                  resume getting a partially-downloaded file
-	#   -q,  --quiet                     quiet (no output)
-	#   -v,  --verbose                   be verbose (this is the default)
-	#   -nv, --no-verbose                turn off verboseness, without being quiet
-	#        --show-progress             display the progress bar in any verbosity mode
-	# WARNING: timestamping does nothing in combination with -O. See the manual for details.
-	if test -n "$destination"; then
-		wget --output-document="$destination" "$url"
-	else
-		wget --timestamping "$url"
+
+	# ensure downloader
+	if test -z "$option_downloader"; then
+		option_downloader="${available[0]}"
+	elif ! is-needle "$option_downloader" "${available[@]}"; then
+		help "The specified downloader is not available: $option_downloader"
 	fi
-elif command-exists curl; then
-	if test -n "$destination"; then
-		curl -L "$url" -o "$destination"
+
+	# ensure inside
+	if test -z "$option_inside"; then
+		option_inside="$(pwd)"
 	else
-		curl -OL "$url"
+		# ensure the custom download directory exists
+		mkdir -p "$option_inside"
 	fi
-elif command-exists http; then
-	if test -n "$destination"; then
-		http --output "$destination" -d "$url"
+
+	# assert url
+	if test -z "$option_url"; then
+		help "No URL was provided."
+	fi
+
+	# =====================================
+	# Action
+
+	# if zip, then download to a temporary directory first
+	if test -n "$option_unzip_format" -o -n "$option_unzip_filter"; then
+		download_directory="$(fs-temp --directory='down' --directory)"
+		download_filename="$(fs-temp --root="$download_directory" --file --prefix='archive-file--')"
 	else
-		http -d "$url"
+		download_directory="$option_inside"
+		download_filename="$option_file" # can be empty
 	fi
-else
-	env QUIET=yes setup-util-aria2
-	down --url="$option_url" --destination="$option_destination"
+
+	# downloader helpers
+	function down_aria2c {
+		local args=(
+			--allow-overwrite=true
+			--auto-file-renaming=false
+			--dir="$download_directory"
+		)
+		if test -n "$download_filename"; then
+			args+=(
+				--out="$download_filename"
+			)
+		fi
+		aria2c "${args[@]}" "$option_url"
+	}
+	function down_wget {
+		#   -O,  --output-document=FILE      write documents to FILE
+		#   -o,  --output-file=FILE          log messages to FILE
+		#   -N,  --timestamping              don't re-retrieve files unless newer than local
+		#   -c,  --continue                  resume getting a partially-downloaded file
+		#   -q,  --quiet                     quiet (no output)
+		#   -v,  --verbose                   be verbose (this is the default)
+		#   -nv, --no-verbose                turn off verboseness, without being quiet
+		#        --show-progress             display the progress bar in any verbosity mode
+		# WARNING: timestamping does nothing in combination with -O. See the manual for details.
+		pushd "$download_directory" >/dev/null
+		if test -n "$download_filename"; then
+			wget --output-document="$download_filename" "$option_url"
+		else
+			wget --timestamping "$option_url"
+		fi
+		popd >/dev/null
+	}
+	function down_curl {
+		pushd "$download_directory" >/dev/null
+		if test -n "$download_filename"; then
+			curl -L "$option_url" -o "$download_filename"
+		else
+			curl -OL "$option_url"
+		fi
+		popd >/dev/null
+	}
+	function down_http {
+		pushd "$download_directory" >/dev/null
+		if test -n "$download_filename"; then
+			http --output "$download_filename" -d "$option_url"
+		else
+			http -d "$option_url"
+		fi
+		popd >/dev/null
+	}
+
+	# invoke the downlaoder
+	case "$option_downloader" in
+	'aria2c' | 'wget' | 'curl' | 'http') down_"$option_downloader" ;;
+	*) help "Invalid downloader." ;;
+	esac
+
+	# if desired, perform extraction of the temporary file
+	if test -n "$option_unzip_format" -o -n "$option_unzip_filter"; then
+		unziptar "$download_directory/$download_filename" \
+			--inside="$option_inside" \
+			--format="$option_unzip_format" \
+			--filter="$option_unzip_filter"
+	fi
+
+	# filename handling
+	if test -n "$option_file"; then
+		# assert it was created
+		if test ! -e "$option_inside/$option_file"; then
+			echo-style --error="Failed to download" ' ' --code="$option_url" ' to ' --code="$option_inside/$option_file" >/dev/stderr
+			exit 1
+		fi
+	fi
+
+	# add a nice output if not in verbose mode
+	# eval_collapse \
+	# 		--pending="$(echo-style --bold="Downloading $url")" \
+	# 		--success="$(echo-style --success="Downloaded $url")" \
+	# 		--failure="$(echo-style --error="Failed to download $url")" \
+	# 		--
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	down "$@"
 fi
diff --git a/commands/echo-exit-affirmative b/commands/echo-exit-affirmative
--- a/commands/echo-exit-affirmative
+++ b/commands/echo-exit-affirmative
@@ -1,59 +1,58 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# =====================================
-# Arguments
+function echo-exit-affirmative() (
+	# =====================================
+	# Arguments
 
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Given a command as arguments, execute it, and:
-		if [0] was the exit code, output [yes]
-		if [1] was the exit code, output [no]
-		if anything else was the exit code, propagate that exit code
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Given a command as arguments, execute it, and:
+			if [0] was the exit code, output [yes]
+			if [1] was the exit code, output [no]
+			if anything else was the exit code, propagate that exit code
 
-		USAGE:
-		echo-exit-affirmative [--] <command...>
+			USAGE:
+			echo-exit-affirmative [--] ...<command>
 
-		EXAMPLES:
-		echo-exit-affirmative -- exit 0    # outputs: yes    exit code: 0
-		echo-exit-affirmative -- exit 1    # outputs: no     exit code: 0
-		echo-exit-affirmative -- exit 2    # exit code: 2
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
+			EXAMPLES:
+			echo-exit-affirmative -- exit 0    # outputs: yes    exit code: 0
+			echo-exit-affirmative -- exit 1    # outputs: no     exit code: 0
+			echo-exit-affirmative -- exit 2    # exit code: 2
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item cmd=()
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--')
+			cmd+=("$@")
+			shift "$#"
+			break
+			;;
+		*) cmd+=("$item") ;;
+		esac
+	done
+
+	# check
+	if test "${#cmd[@]}" -eq 0; then
+		help "No <command> was provided."
 	fi
-	return 22 # Invalid argument
-}
 
-# process
-option_cmd=()
-while test "$#" -ne 0; do
-	item="$1"
-	shift
-	case "$item" in
-	'help' | '--help' | '-h') help ;;
-	'--')
-		option_cmd+=("$@")
-		shift "$#"
-		break
-		;;
-	*) option_cmd+=("$item") ;;
-	esac
-done
+	# =====================================
+	# Action
 
-# check
-if test "${#option_cmd[@]}" -eq 0; then
-	help "No command was provided."
-fi
-
-# =====================================
-# Action
-
-function echo_exit_affirmative {
 	local ec
-	ec=0 && ("$@") || ec="$?"
+	ec=0 && ("${cmd[@]}") || ec="$?"
 	if test "$ec" -eq 0; then
 		echo 'yes'
 	elif test "$ec" -eq 1; then
@@ -61,9 +60,9 @@ function echo_exit_affirmative {
 	else
 		return "$ec"
 	fi
-}
+)
 
 # fire if invoked standalone
 if test "$0" = "${BASH_SOURCE[0]}"; then
-	echo_exit_affirmative "${option_cmd[@]}"
+	echo-exit-affirmative "$@"
 fi
diff --git a/commands/echo-exit-code b/commands/echo-exit-code
--- a/commands/echo-exit-code
+++ b/commands/echo-exit-code
@@ -1,60 +1,59 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# =====================================
-# Arguments
+function echo-exit-code() (
+	# =====================================
+	# Arguments
 
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Given a command as arguments, execute it, output the exit code.
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Given a command as arguments, execute it, output the exit code.
 
-		USAGE:
-		echo-exit-affirmative [--] <command...>
+			USAGE:
+			echo-exit-affirmative [--] ...<command>
 
-		EXAMPLES:
-		echo-exit-affirmative -- exit 0    # outputs: 0    exit code: 0
-		echo-exit-affirmative -- exit 1    # outputs: 1    exit code: 0
-		echo-exit-affirmative -- exit 2    # outputs: 2    exit code: 0
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
+			EXAMPLES:
+			echo-exit-affirmative -- exit 0    # outputs: 0    exit code: 0
+			echo-exit-affirmative -- exit 1    # outputs: 1    exit code: 0
+			echo-exit-affirmative -- exit 2    # outputs: 2    exit code: 0
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item cmd=()
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--')
+			cmd+=("$@")
+			shift "$#"
+			break
+			;;
+		*) cmd+=("$item") ;;
+		esac
+	done
+
+	# check
+	if test "${#cmd[@]}" -eq 0; then
+		help "No <command> was provided."
 	fi
-	return 22 # Invalid argument
-}
 
-# process
-option_cmd=()
-while test "$#" -ne 0; do
-	item="$1"
-	shift
-	case "$item" in
-	'help' | '--help' | '-h') help ;;
-	'--')
-		option_cmd+=("$@")
-		shift "$#"
-		break
-		;;
-	*) option_cmd+=("$item") ;;
-	esac
-done
+	# =====================================
+	# Action
 
-# check
-if test "${#option_cmd[@]}" -eq 0; then
-	help "No command was provided."
-fi
-
-# =====================================
-# Action
-
-function echo_exit_code {
 	local ec
-	ec=0 && ("$@") || ec="$?"
+	ec=0 && ("${cmd[@]}") || ec="$?"
 	echo "$ec"
-}
+)
 
 # fire if invoked standalone
 if test "$0" = "${BASH_SOURCE[0]}"; then
-	echo_exit_code "${option_cmd[@]}"
+	echo-exit-code "$@"
 fi
diff --git a/commands/echo-file b/commands/echo-file
--- a/commands/echo-file
+++ b/commands/echo-file
@@ -1,99 +1,100 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# =====================================
-# Arguments
+function echo-file() (
+	# =====================================
+	# Arguments
 
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Output the contents of the passed file paths.
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Output the contents of the passed file paths.
 
-		USAGE:
-		echo-file [--] <...path>
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
-	fi
-	return 22 # Invalid argument
-}
-
-# process
-option_paths=()
-while test "$#" -ne 0; do
-	item="$1"
-	shift
-	case "$item" in
-	'help' | '--help' | '-h') help ;;
-	'--')
-		option_paths+=("$@")
-		shift "$#"
-		break
-		;;
-	'--'*) help "An unrecognised flag was provided: $item" ;;
-	*) option_paths+=("$item") ;;
-	esac
-done
-
-# check
-if test "${#option_paths[@]}" -eq 0; then
-	help "No paths were provided"
-fi
-
-# =====================================
-# Arguments
-
-function echo_file_bat {
-	local file="$1" os_theme
-	if command-exists bat; then
-		if test -n "${BAT_THEME-}"; then
-			# manual theme
-			bat --paging=never "$file"
-		else
-			# get the operating system theme, so that we can ensure bat output is visible
-			os_theme="$(get-os-theme 2>/dev/null || :)" # ignore and silent errors
-			if test "$os_theme" = 'light'; then
-				bat --theme=ansi --paging=never "$file"
-			elif test "$os_theme" = 'dark'; then
-				bat --theme=1337 --paging=never "$file"
-			else
-				# bat is installed, but without knowing the operating system theme, we cannot be sure that the bat theme is readable
-				return 1
-			fi
-		fi
-	else
-		# bat not installed, fail
-		return 1
-	fi
-}
-
-function echo_file {
-	local file ec=0
-	while test "$#" -ne 0; do
-		file="$1"
-		shift
-		if test -f "$file"; then
-			if ! echo_file_bat "$file"; then
-				echo-element --open="$file"
-				echo-style --dim "$(echo-trim <"$file")"
-				echo-element --close="$file"
-			fi
-		else
-			echo-element --open="$file"
-			echo-style --error="The file does not exist."
-			echo-element --openclose="$file" --status=2
-			ec=2 # ENOENT No such file or directory
-			# ^ dont like this, so that all files are noted before crash
-		fi
+			USAGE:
+			echo-file [--] ...<paths>
+		EOF
 		if test "$#" -ne 0; then
-			echo
+			echo-error "$@"
 		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item paths=()
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--')
+			paths+=("$@")
+			shift "$#"
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) paths+=("$item") ;;
+		esac
 	done
-	return "$ec"
-}
+
+	# check
+	if test "${#paths[@]}" -eq 0; then
+		help "No <paths> were provided"
+	fi
+
+	# =====================================
+	# Act
+
+	function echo_file_bat {
+		local file="$1" os_theme
+		if command-exists bat; then
+			if test -n "${BAT_THEME-}"; then
+				# manual theme
+				bat --paging=never "$file"
+			else
+				# get the operating system theme, so that we can ensure bat output is visible
+				os_theme="$(get-os-theme 2>/dev/null || :)" # ignore and silent errors
+				if test "$os_theme" = 'light'; then
+					bat --theme=ansi --paging=never "$file"
+				elif test "$os_theme" = 'dark'; then
+					bat --theme=1337 --paging=never "$file"
+				else
+					# bat is installed, but without knowing the operating system theme, we cannot be sure that the bat theme is readable
+					return 1
+				fi
+			fi
+		else
+			# bat not installed, fail
+			return 1
+		fi
+	}
+	function echo_file {
+		local file ec=0
+		while test "$#" -ne 0; do
+			file="$1"
+			shift
+			if test -f "$file"; then
+				if ! echo_file_bat "$file"; then
+					echo-element --open="$file"
+					echo-style --code="$(echo-trim <"$file")"
+					echo-element --close="$file"
+				fi
+			else
+				echo-element --open="$file"
+				echo-style --error="The file does not exist."
+				echo-element --close="$file" --status=2
+				ec=2 # ENOENT No such file or directory
+				# ^ dont like this, so that all files are noted before crash
+			fi
+			if test "$#" -ne 0; then
+				echo
+			fi
+		done
+		return "$ec"
+	}
+	echo_file "${paths[@]}"
+)
 
 # fire if invoked standalone
 if test "$0" = "${BASH_SOURCE[0]}"; then
-	echo_file "${option_paths[@]}"
+	echo-file "$@"
 fi
diff --git a/commands/eval-tester b/commands/eval-tester
--- a/commands/eval-tester
+++ b/commands/eval-tester
@@ -2,115 +2,119 @@
 # shellcheck disable=SC2164,SC1091
 source "$DOROTHY/sources/strict.bash"
 
-# =====================================
-# Arguments
+function eval-tester() (
+	# =====================================
+	# Arguments
 
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		USAGE:
-		eval-tester <...flags> -- <command> [<...args>]
+	function help {
+		cat <<-EOF >/dev/stderr
+			USAGE:
+			eval-tester <...flags> -- <command> [<...args>]
 
-		FLAGS:
-		[--ec=<expected exit code>]
-		[--stdout=<expected stdout>]
-		[--stderr=<expected stderr>]
-		[--debug]
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
+			FLAGS:
+			[--ec=<expected exit code>]
+			[--stdout=<expected stdout>]
+			[--stderr=<expected stderr>]
+			[--debug]
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item args=() option_ec='0' option_stdout='' option_stderr='' option_debug='no'
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--ec='*) option_ec="${item:5}" ;;
+		'--stdout='*) option_stdout="${item:9}" ;;
+		'--stderr='*) option_stderr="${item:9}" ;;
+		'--no-debug'* | '--debug'*)
+			option_debug="$(get-flag-value debug --missing="$option_debug" -- "$item" | echo-affirmative)"
+			;;
+		'--')
+			args+=("$@")
+			shift $#
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) help "An unrecognised argument was provided: $item" ;;
+		esac
+	done
+
+	# overrides
+	if test "$option_debug" = 'yes'; then
+		set -x
+		args=('debug-bash' "${args[@]}")
 	fi
-	return 22 # Invalid argument
-}
 
-# process
-option_ec='0'
-option_stdout=''
-option_stderr=''
-option_debug='no'
-args=()
-while test "$#" -ne 0; do
-	item="$1"
-	shift
-	case "$item" in
-	'help' | '--help' | '-h') help ;;
-	'--ec='*) option_ec="${item:5}" ;;
-	'--stdout='*) option_stdout="${item:9}" ;;
-	'--stderr='*) option_stderr="${item:9}" ;;
-	'--no-debug'* | '--debug'*) option_debug="$(get-flag-value debug --missing="$option_debug" -- "$item" | echo-affirmative)" ;;
-	'--')
-		args+=("$@")
-		shift $#
-		break
-		;;
-	'--'*) help "An unrecognised flag was provided: $item" ;;
-	*) help "An unrecognised argument was provided: $item" ;;
-	esac
-done
+	# =====================================
+	# Action
 
-# overrides
-if test "$option_debug" = 'yes'; then
-	set -x
-	args=('debug-bash' "${args[@]}")
-fi
+	# run the command
+	local stdout stderr cmd ec fail='no'
+	stdout="$(mktemp)"
+	stderr="$(mktemp)"
+	cmd="$(echo-quote "${args[@]}" | echo-join ' ')"
+	echo-segment --h3="$cmd"
+	ec=0 && ("${args[@]}") >"$stdout" 2>"$stderr" || ec="$?"
 
-# =====================================
-# Action
-
-# run the command
-fail='no'
-stdout="$(mktemp)"
-stderr="$(mktemp)"
-cmd="$(echo-quote "${args[@]}" | echo-join ' ')"
-echo-segment --h3="$cmd"
-ec=0 && ("${args[@]}") >"$stdout" 2>"$stderr" || ec="$?"
-
-# test exit code
-if test "$option_ec" -ne "$ec"; then
-	echo-style --red="Actual Exit Code [$ec]  !=  Expected Exit Code [$option_ec]"
-	fail='yes'
-else
-	echo-style --green="Actual Exit Code [$ec]  ==  Expected Exit Code [$option_ec]"
-fi
-
-# test stdout
-if test -n "$option_stdout"; then
-	if test "$option_stdout" != "$(cat "$stdout")"; then
-		echo-style --red="Actual Stdout  !=  Expected Stdout"
-		echo-style --h3='< actual stdout>'
-		cat "$stdout"
-		echo-style --h3='</ actual stdout>'
-		echo-style --h3='< expected stdout>'
-		echo "$option_stdout"
-		echo-style --h3='</ expected stdout>'
+	# test exit code
+	if test "$option_ec" -ne "$ec"; then
+		echo-style --red="Actual Exit Code [$ec]  !=  Expected Exit Code [$option_ec]"
 		fail='yes'
 	else
-		echo-style --green="Actual Stdout  ==  Expected Stdout"
+		echo-style --green="Actual Exit Code [$ec]  ==  Expected Exit Code [$option_ec]"
 	fi
-fi
 
-# test stderr
-if test -n "$option_stderr"; then
-	if test "$option_stderr" != "$(cat "$stderr")"; then
-		echo-style --red="Actual Stderr  !=  Expected Stderr"
-		echo-style --h3='< actual stderr>'
-		cat "$stderr"
-		echo-style --h3='</ actual stderr>'
-		echo-style --h3='< expected stderr>'
-		echo "$option_stderr"
-		echo-style --h3='</ expected stderr>'
-		fail='yes'
+	# test stdout
+	if test -n "$option_stdout"; then
+		if test "$option_stdout" != "$(cat "$stdout")"; then
+			echo-style --red="Actual Stdout  !=  Expected Stdout"
+			echo-style --h3='< actual stdout>'
+			cat "$stdout"
+			echo-style --h3='</ actual stdout>'
+			echo-style --h3='< expected stdout>'
+			echo "$option_stdout"
+			echo-style --h3='</ expected stdout>'
+			fail='yes'
+		else
+			echo-style --green="Actual Stdout  ==  Expected Stdout"
+		fi
+	fi
+
+	# test stderr
+	if test -n "$option_stderr"; then
+		if test "$option_stderr" != "$(cat "$stderr")"; then
+			echo-style --red="Actual Stderr  !=  Expected Stderr"
+			echo-style --h3='< actual stderr>'
+			cat "$stderr"
+			echo-style --h3='</ actual stderr>'
+			echo-style --h3='< expected stderr>'
+			echo "$option_stderr"
+			echo-style --h3='</ expected stderr>'
+			fail='yes'
+		else
+			echo-style --green="Actual Stderr  ==  Expected Stderr"
+		fi
+	fi
+
+	# pass or fail
+	if test "$fail" = 'yes'; then
+		echo-segment --e3="$cmd"
+		echo
+		return 1
 	else
-		echo-style --green="Actual Stderr  ==  Expected Stderr"
+		echo-segment --g3="$cmd"
+		echo
 	fi
-fi
+)
 
-# pass or fail
-if test "$fail" = 'yes'; then
-	echo-segment --e3="$cmd"
-	echo
-	exit 1
-else
-	echo-segment --g3="$cmd"
-	echo
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	eval-tester "$@"
 fi
diff --git a/commands/flush-dns b/commands/flush-dns
--- a/commands/flush-dns
+++ b/commands/flush-dns
@@ -1,50 +1,79 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
-source "$(which eval-collapse)"
 
-# =====================================
-# Start
+function flush-dns() (
+	# =====================================
+	# Arguments
 
-echo-segment --h1="Flush DNS"
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Flush the system's DNS cache.
 
-# =====================================
-# Acction
+			USAGE:
+			flush-dns
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
 
-# https://support.apple.com/en-us/HT202516
-if is-mac; then
-	if command-exists mDNSResponder; then
-		eval_collapse \
-			--pending="$(echo-style --bold='Restarting [mDNSResponder]...')" \
-			--success="$(echo-style --success='Restarted [mDNSResponder].')" \
-			--failure="$(echo-style --error='Failed to restart [mDNSResponder].')" \
-			-- sudo killall -HUP mDNSResponder
+	# process
+	local item
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) help "An unrecognised argument was provided: $item" ;;
+		esac
+	done
+
+	# =====================================
+	# Acction
+
+	echo-segment --h1="Flush DNS"
+
+	# https://support.apple.com/en-us/HT202516
+	if is-mac; then
+		if command-exists mDNSResponder; then
+			eval-collapse \
+				--pending="$(echo-style --bold='Restarting [mDNSResponder]...')" \
+				--success="$(echo-style --success='Restarted [mDNSResponder].')" \
+				--failure="$(echo-style --error='Failed to restart [mDNSResponder].')" \
+				-- sudo killall -HUP mDNSResponder
+		fi
+		if command-exists dscacheutil; then
+			eval-collapse \
+				--pending="$(echo-style --bold='Flushing [dscacheutil]...')" \
+				--success="$(echo-style --success='Flushed [dscacheutil].')" \
+				--failure="$(echo-style --error='Failed to flush [dscacheutil].')" \
+				-- sudo dscacheutil -flushcache
+		fi
+		if command-exists discoveryutil; then
+			eval-collapse \
+				--pending="$(echo-style --bold='Flushing [discoveryutil]...')" \
+				--success="$(echo-style --success='Flushed [discoveryutil].')" \
+				--failure="$(echo-style --error='Failed to flush [discoveryutil].')" \
+				-- sudo discoveryutil mdnsflushcache
+		fi
+	elif command-exists systemd-resolve; then
+		eval-collapse \
+			--pending="$(echo-style --bold='Flushing DNS cache via [systemd-resolve]...')" \
+			--success="$(echo-style --success='Flushed DNS cache via [systemd-resolve]')" \
+			--failure="$(echo-style --error='Failed to flush DNS cache via [systemd-resolve].') $(echo-style --notice='If using an alternative DNS service, then this is expected.')" \
+			-- systemd-resolve --flush-caches || :
+	else
+		echo-style --error='DNS flushing not yet implemented for this operating system.' >/dev/stderr
+		return 19 # Operation not supported by device
 	fi
-	if command-exists dscacheutil; then
-		eval_collapse \
-			--pending="$(echo-style --bold='Flushing [dscacheutil]...')" \
-			--success="$(echo-style --success='Flushed [dscacheutil].')" \
-			--failure="$(echo-style --error='Failed to flush [dscacheutil].')" \
-			-- sudo dscacheutil -flushcache
-	fi
-	if command-exists discoveryutil; then
-		eval_collapse \
-			--pending="$(echo-style --bold='Flushing [discoveryutil]...')" \
-			--success="$(echo-style --success='Flushed [discoveryutil].')" \
-			--failure="$(echo-style --error='Failed to flush [discoveryutil].')" \
-			-- sudo discoveryutil mdnsflushcache
-	fi
-elif command-exists systemd-resolve; then
-	eval_collapse \
-		--pending="$(echo-style --bold='Flushing DNS cache via [systemd-resolve]...')" \
-		--success="$(echo-style --success='Flushed DNS cache via [systemd-resolve]')" \
-		--failure="$(echo-style --error='Failed to flush DNS cache via [systemd-resolve].') $(echo-style --notice='If using an alternative DNS service, then this is expected.')" \
-		-- systemd-resolve --flush-caches || :
-else
-	echo-style --error='DNS flushing not yet implemented for this operating system.' >/dev/stderr
-	exit 19 # Operation not supported by device
+
+	echo-segment --g1="Flush DNS"
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	flush-dns "$@"
 fi
-
-# =====================================
-# Finish
-
-echo-segment --g1="Flush DNS"
diff --git a/commands/fs-mount b/commands/fs-mount
--- a/commands/fs-mount
+++ b/commands/fs-mount
@@ -1,160 +1,163 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# =====================================
-# Arguments
+function fs-mount() (
+	# =====================================
+	# Arguments
 
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Mounts a source (be it a drive or gocryptfs vault) to a mount point.
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Mounts a source (be it a drive or gocryptfs vault) to a mount point.
 
-		USAGE:
-		fs-mount [--] <source> <mount-point> [<owner>]
-		fs-mount [--] [--source=<source>] [--target=<mount-point>] [--owner=<owner>] [--user=<user>] [--group=<group>]
+			USAGE:
+			fs-mount [...options] <source> <mount-point> [<owner>]
+			fs-mount [...options] --source=<source> --target=<mount-point>
 
-		QUIRKS:
-		If [owner/user/group] is provided, then the mount point will be enforced to that owner/user/group.
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
-	fi
-	return 22 # Invalid argument
-}
+			OPTIONS:
+			--source=<source>
+			--target=<mount-point>
+			--owner=<owner>
+			--user=<user>
+			--group=<group>
 
-# prepare
-while test "${1-}" = '--'; do
-	shift
-done
-
-# process
-paths=()
-mount_source=''
-mount_target=''
-option_owner=''
-option_user=''
-option_group=''
-while test "$#" -ne 0; do
-	item="$1"
-	shift
-	case "$item" in
-	'help' | '--help' | '-h') help ;;
-	'--source='*) mount_source="${item:9}" ;;
-	'--target='*) mount_target="${item:9}" ;;
-	'--owner='*) option_owner="${item:8}" ;;
-	'--user='*) option_user="${item:7}" ;;
-	'--group='*) option_group="${item:8}" ;;
-	'--')
-		paths+=("$@")
-		shift $#
-		break
-		;;
-	'--'*) help "An unrecognised flag was provided: $item" ;;
-	*)
-		if test -z "$mount_source"; then
-			mount_source="$item"
-		elif test -z "$mount_target"; then
-			mount_target="$item"
-		elif test -z "$option_owner"; then
-			option_owner="$item"
-		else
-			help "An unrecognised argument was provided: $item"
+			QUIRKS:
+			If [owner/user/group] is provided, then the mount point will be enforced to that owner/user/group.
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
 		fi
-		;;
-	esac
-done
-
-# check
-if test -z "$mount_source" -o -z "$mount_target"; then
-	help "No paths were provided."
-fi
-
-# =====================================
-# Helpers
-
-function is_drive {
-	[[ "$1" = '/dev/'* ]]
-}
-
-# =====================================
-# Act
-
-title="fs-mount ${mount_source@Q}"
-conclusion=''
-mount_cmd=()
-
-function fs_mount() {
-	local chown='no'
-
-	# verify and prep
-	if is_drive "$mount_source"; then
-		# mount drive
-		mount_cmd+=(
-			'sudo'
-			'mount'
-			"$mount_source"
-			"$mount_target"
-		)
-		# instruct to chown
-		chown='yes'
-	elif gocryptfs-helper verify -- "$mount_source" &>/dev/null; then
-		# mount vault
-		mount_cmd+=(
-			'gocryptfs-helper'
-			'mount'
-			'--'
-			"$mount_source"
-			"$mount_target"
-			"--owner=$option_owner"
-			"--user=$option_user"
-			"--group=$option_group"
-		)
-	else
-		conclusion="$(
-			echo-style --red="invalid mount source."
-		)"
-		echo-style --error="fs-mount doesn't know how to mount ${mount_source@Q}, it is neither a drive nor a gocryptfs vault"
 		return 22 # Invalid argument
+	}
+
+	# prepare
+	while test "${1-}" = '--'; do
+		shift
+	done
+
+	# process
+	local item mount_source='' mount_target='' option_owner='' option_user='' option_group=''
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--source='*) mount_source="${item:9}" ;;
+		'--target='*) mount_target="${item:9}" ;;
+		'--owner='*) option_owner="${item:8}" ;;
+		'--user='*) option_user="${item:7}" ;;
+		'--group='*) option_group="${item:8}" ;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*)
+			if test -z "$mount_source"; then
+				mount_source="$item"
+			elif test -z "$mount_target"; then
+				mount_target="$item"
+			elif test -z "$option_owner"; then
+				option_owner="$item"
+			else
+				help "An unrecognised argument was provided: $item"
+			fi
+			;;
+		esac
+	done
+
+	# check
+	if test -z "$mount_source" -o -z "$mount_target"; then
+		help "No paths were provided."
 	fi
 
-	# if already mounted, then only do perms
-	if test -d "$mount_target"; then
-		if is-mounted --source="$mount_source" --target="$mount_target"; then
-			echo-style --bold="${mount_source@Q}" " already mounted to " --bold="${mount_target@Q}"
-			if ! confirm-bool --ppid=$$ -- 'Do you wish to remount?'; then
-				conclusion="$(
-					echo-style --green="was previously mounted."
-				)"
-				return "$?"
-			fi
+	# =====================================
+	# Helpers
+
+	function is_drive {
+		[[ $1 == '/dev/'* ]]
+	}
+
+	# =====================================
+	# Act
+
+	local title conclusion='' mount_cmd=()
+	title="fs-mount $(echo-quote "$mount_source")"
+	conclusion=''
+
+	function fs_mount {
+		local chown='no'
+
+		# verify and prep
+		if is_drive "$mount_source"; then
+			# mount drive
+			mount_cmd+=(
+				'sudo'
+				'mount'
+				"$mount_source"
+				"$mount_target"
+			)
+			# instruct to chown
+			chown='yes'
+		elif gocryptfs-helper verify -- "$mount_source" &>/dev/null; then
+			# mount vault
+			mount_cmd+=(
+				'gocryptfs-helper'
+				'mount'
+				'--'
+				"$mount_source"
+				"$mount_target"
+				"--owner=$option_owner"
+				"--user=$option_user"
+				"--group=$option_group"
+			)
+		else
+			conclusion="$(
+				echo-style --red="invalid mount source."
+			)"
+			echo-style --error="fs-mount doesn't know how to mount ${mount_source@Q}, it is neither a drive nor a gocryptfs vault"
+			return 22 # Invalid argument
 		fi
 
-		# if mount is invalid, then unmount the directory
-		fs-unmount -- "$mount_target"
-	fi
+		# if already mounted, then only do perms
+		if test -d "$mount_target"; then
+			if is-mounted --source="$mount_source" --target="$mount_target"; then
+				echo-style --bold="${mount_source@Q}" " already mounted to " --bold="${mount_target@Q}"
+				if ! confirm-bool --ppid=$$ -- 'Do you wish to remount?'; then
+					conclusion="$(
+						echo-style --green="was previously mounted."
+					)"
+					return "$?"
+				fi
+			fi
 
-	# if not mounted, go through the process
-	sudo mkdir -p "$mount_target"
-	fs-own --owner="$option_owner" --user="$option_user" --group="$option_group" -- "$mount_target"
+			# if mount is invalid, then unmount the directory
+			fs-unmount -- "$mount_target"
+		fi
 
-	# mount
-	echo-eval -- "${mount_cmd[@]}"
-	echo-style --success="${mount_source@Q} was mounted."
-	if test "$chown" = 'yes'; then
+		# if not mounted, go through the process
+		sudo mkdir -p "$mount_target"
 		fs-own --owner="$option_owner" --user="$option_user" --group="$option_group" -- "$mount_target"
+
+		# mount
+		echo-eval -- "${mount_cmd[@]}"
+		echo-style --success="${mount_source@Q} was mounted."
+		if test "$chown" = 'yes'; then
+			fs-own --owner="$option_owner" --user="$option_user" --group="$option_group" -- "$mount_target"
+		fi
+
+		# success
+		conclusion="$(
+			echo-style --green="mounted successfully."
+		)"
+	}
+
+	# act
+	echo-segment --h2="$title"
+	if fs_mount; then
+		echo-segment --g2="$title" " $conclusion"
+	else
+		echo-segment --e2="$title" " $conclusion"
 	fi
+)
 
-	# success
-	conclusion="$(
-		echo-style --green="mounted successfully."
-	)"
-}
-
-# act
-echo-segment --h2="$title"
-if fs_mount; then
-	echo-segment --g2="$title" " $conclusion"
-else
-	echo-segment --e2="$title" " $conclusion"
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	fs-mount "$@"
 fi
diff --git a/commands/fs-own b/commands/fs-own
--- a/commands/fs-own
+++ b/commands/fs-own
@@ -1,233 +1,248 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# =====================================
-# Arguments
+function fs-own() (
+	# =====================================
+	# Arguments
 
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Claim ownership of a path, by updating its permissions via chmod and chown.
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Claim ownership of a path, by updating its permissions via chmod and chown.
 
-		USAGE:
-		fs-own [...flags] [--] <...paths>
+			USAGE:
+			fs-own [...flags] [--] <...paths>
 
-		FLAGS:
-		[--verbose] if provied, will output the executed commands.
-		[--permissions=<permissions>] sets file and directory permissions
-		[--directory-permissions=<permissions>] sets directory permisisons
-		[--file-permissions=<permissions>] set file permissions
-		[--admin] if provided, will use the platform specific admin values.
-		[--owner=<owner>] if provided, will set the path owner to this.
-		[--user=<user>] if provided, will set the path owner to this user.
-		[--group=<group>] if provided, will set the path owner to this group.
-		[--sudo] if provided, sudo will be used, automatically enabled when admin/owner/user/group is provided.
-		[--partial] if provided, failures will be ignored.
-		[--no-changes] if provided, changes will not be reported if the operating system supports it.
-		[--no-recursive] if provided, only the exact path will be used, not any child paths.
+			FLAGS:
+			[--verbose] if provied, will output the executed commands.
+			[--permissions=<permissions>] sets file and directory permissions
+			[--directory-permissions=<permissions>] sets directory permisisons
+			[--file-permissions=<permissions>] set file permissions
+			[--admin] if provided, will use the platform specific admin values.
+			[--owner=<owner>] if provided, will set the path owner to this.
+			[--user=<user>] if provided, will set the path owner to this user.
+			[--group=<group>] if provided, will set the path owner to this group.
+			[--sudo] if provided, sudo will be used, automatically enabled when admin/owner/user/group is provided.
+			[--partial] if provided, failures will be ignored.
+			[--no-changes] if provided, changes will not be reported if the operating system supports it.
+			[--no-recursive] if provided, only the exact path will be used, not any child paths.
 
-		QUIRKS:
-		If [--permissions=...], [--directory-permissions=...], [--file-permissions=...] are all omitted, then the directory permissions will be set to 755 and the file permissions set to 644.
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
-	fi
-	return 22 # Invalid argument
-}
-
-# process
-paths=()
-option_verbose='no'
-option_owner=''
-option_user=''
-option_group=''
-option_admin='no'
-option_permissions=''
-option_directory_permissions=''
-option_file_permissions=''
-option_sudo='no'
-option_changes='yes'
-option_partial='no'
-option_recursive='yes'
-while test "$#" -ne 0; do
-	item="$1"
-	shift
-	case "$item" in
-	'help' | '--help' | '-h') help ;;
-	'--no-verbose'* | '--verbose'*) option_verbose="$(
-		get-flag-value verbose --missing="$option_verbose" -- "$item" | echo-affirmative
-	)" ;;
-	'--no-admin'* | '--admin'*) option_admin="$(
-		get-flag-value admin --missing="$option_admin" -- "$item" | echo-affirmative
-	)" ;;
-	'--no-sudo'* | '--sudo'*) option_sudo="$(
-		get-flag-value sudo --missing="$option_sudo" -- "$item" | echo-affirmative
-	)" ;;
-	'--no-changes'* | '--changes'*) option_changes="$(
-		get-flag-value changes --missing="$option_changes" -- "$item" | echo-affirmative
-	)" ;;
-	'--no-partial'* | '--partial'*) option_partial="$(
-		get-flag-value partial --missing="$option_partial" -- "$item" | echo-affirmative
-	)" ;;
-	'--no-recursive'* | '--recursive'*) option_recursive="$(
-		get-flag-value recursive --missing="$option_recursive" -- "$item" | echo-affirmative
-	)" ;;
-	'--permissions='*) option_permissions="${item:14}" ;;
-	'--directory-permissions='*) option_directory_permissions="${item:24}" ;;
-	'--file-permissions='*) option_file_permissions="${item:19}" ;;
-	'--owner='*) option_owner="${item:8}" ;;
-	'--user='*) option_user="${item:7}" ;;
-	'--group='*) option_group="${item:8}" ;;
-	'--')
-		paths+=("$@")
-		shift $#
-		break
-		;;
-	'--'*) help "An unrecognised flag was provided: $item" ;;
-	*) paths+=("$item") ;;
-	esac
-done
-
-# check
-if test "${#paths[@]}" -eq 0; then
-	help "No paths were provided."
-fi
-for path in "${paths[@]}"; do
-	if test -z "$path"; then
-		help "An empty path was provided."
-	fi
-	if test ! -e "$path" -a ! -L "$path"; then
-		# symlinks fail -e
-		help "A path was provided, that does not exist:" "$path"
-	fi
-done
-
-# adjustments: permissions
-if test -z "$option_permissions" -a -z "$option_directory_permissions" -a -z "$option_file_permissions"; then
-	option_directory_permissions='755'
-	option_file_permissions='644'
-fi
-
-# adjustments: admin
-if test "$option_admin" = 'yes'; then
-	if is-mac; then
-		option_user="$(whoami)"
-		option_group='admin'
-		# ^ https://superuser.com/a/20430/32418
-	else
-		option_user='root'
-		option_group='root'
-	fi
-fi
-
-# adjustments: owner
-owner=''
-if test -n "$option_owner"; then
-	owner="$option_owner"
-elif test -n "$option_user" -a -n "$option_group"; then
-	owner="$option_user:$option_group"
-elif test -n "$option_user"; then
-	owner="$option_user"
-elif test -n "$option_group"; then
-	owner=":$option_group"
-fi
-
-# adjustments: recursive, changes
-ch_args=()
-if test "$option_recursive" = 'yes'; then
-	if is-mac; then
-		ch_args+=('-R')
-	else
-		ch_args+=('--recursive')
-	fi
-fi
-if test "$option_changes" = 'yes'; then
-	if is-mac; then
-		echo-style --dim='Reporting permission changes is not provided by macOS.' >/dev/stderr
-	else
-		ch_args+=('--changes')
-	fi
-fi
-
-# =====================================
-# Helpers
-
-function do_sudo_as_user {
-	local cmd=()
-
-	# verbose if provided
-	if test "$option_verbose" = 'yes'; then
-		cmd+=('echo-eval' '--')
-	fi
-
-	# use sudo only if custom owner
-	if test -n "$owner" -o "$option_sudo" = 'yes'; then
-		cmd+=(
-			'sudo'
-			'--set-home'
-		)
-
-		# add the user and group if provided
-		if test -n "$option_user"; then
-			cmd+=("--user=$option_user")
+			QUIRKS:
+			If [--permissions=...], [--directory-permissions=...], [--file-permissions=...] are all omitted, then the directory permissions will be set to 755 and the file permissions set to 644.
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
 		fi
-		if test -n "$option_group"; then
-			cmd+=("--group=$option_group")
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item paths=()
+	local option_verbose='no'
+	local option_owner=''
+	local option_user=''
+	local option_group=''
+	local option_admin='no'
+	local option_permissions=''
+	local option_directory_permissions=''
+	local option_file_permissions=''
+	local option_sudo='no'
+	local option_changes=''
+	local option_partial='no'
+	local option_recursive='yes'
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--no-verbose'* | '--verbose'*) option_verbose="$(
+			get-flag-value verbose --missing="$option_verbose" -- "$item" | echo-affirmative
+		)" ;;
+		'--no-admin'* | '--admin'*) option_admin="$(
+			get-flag-value admin --missing="$option_admin" -- "$item" | echo-affirmative
+		)" ;;
+		'--no-sudo'* | '--sudo'*) option_sudo="$(
+			get-flag-value sudo --missing="$option_sudo" -- "$item" | echo-affirmative
+		)" ;;
+		'--no-changes'* | '--changes'*) option_changes="$(
+			get-flag-value changes --missing="$option_changes" -- "$item" | echo-affirmative
+		)" ;;
+		'--no-partial'* | '--partial'*) option_partial="$(
+			get-flag-value partial --missing="$option_partial" -- "$item" | echo-affirmative
+		)" ;;
+		'--no-recursive'* | '--recursive'*) option_recursive="$(
+			get-flag-value recursive --missing="$option_recursive" -- "$item" | echo-affirmative
+		)" ;;
+		'--permissions='*) option_permissions="${item:14}" ;;
+		'--directory-permissions='*) option_directory_permissions="${item:24}" ;;
+		'--file-permissions='*) option_file_permissions="${item:19}" ;;
+		'--owner='*) option_owner="${item:8}" ;;
+		'--user='*) option_user="${item:7}" ;;
+		'--group='*) option_group="${item:8}" ;;
+		'--')
+			paths+=("$@")
+			shift $#
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) paths+=("$item") ;;
+		esac
+	done
+
+	# check
+	if test "${#paths[@]}" -eq 0; then
+		help "No paths were provided."
+	fi
+	for path in "${paths[@]}"; do
+		if test -z "$path"; then
+			help "An empty path was provided."
+		fi
+		if test ! -e "$path" -a ! -L "$path"; then
+			# symlinks fail -e
+			help "A path was provided, that does not exist:" "$path"
+		fi
+	done
+
+	# adjustments: permissions
+	if test -z "$option_permissions" -a -z "$option_directory_permissions" -a -z "$option_file_permissions"; then
+		option_directory_permissions='755'
+		option_file_permissions='644'
+	fi
+
+	# adjustments: admin
+	if test "$option_admin" = 'yes'; then
+		if is-mac; then
+			option_user="$(whoami)"
+			option_group='admin'
+			# ^ https://superuser.com/a/20430/32418
+		else
+			option_user='root'
+			option_group='root'
 		fi
 	fi
 
-	# run
-	"${cmd[@]}" "$@"
-}
-function do_sudo_as_admin {
-	local cmd=()
-
-	# verbose if provided
-	if test "$option_verbose" = 'yes'; then
-		cmd+=('echo-eval' '--')
+	# adjustments: owner
+	local owner=''
+	if test -n "$option_owner"; then
+		owner="$option_owner"
+	elif test -n "$option_user" -a -n "$option_group"; then
+		owner="$option_user:$option_group"
+	elif test -n "$option_user"; then
+		owner="$option_user"
+	elif test -n "$option_group"; then
+		owner=":$option_group"
 	fi
 
-	# use sudo only if custom owner
-	if test -n "$owner" -o "$option_sudo" = 'yes'; then
-		cmd+=(
-			'sudo'
-			'--set-home'
-		)
+	# adjustments: recursive
+	local ch_args=()
+	if test "$option_recursive" = 'yes'; then
+		if is-mac; then
+			ch_args+=('-R')
+		else
+			ch_args+=('--recursive')
+		fi
 	fi
 
-	# run
-	"${cmd[@]}" "$@"
-}
-function fs_own {
-	local path="$1"
-
-	# chown
-	if test -n "$owner"; then
-		do_sudo_as_admin chown "${ch_args[@]}" "$owner" "$path"
+	# adjustments: changes
+	if test -z "$option_changes"; then
+		if is-mac; then
+			option_changes='no'
+		else
+			option_changes='yes'
+		fi
+	fi
+	if test "$option_changes" = 'yes'; then
+		if is-mac; then
+			echo-style --dim='Reporting permission changes is not provided by macOS.' >/dev/stderr
+		else
+			ch_args+=('--changes')
+		fi
 	fi
 
-	# chmod
-	if test -n "$option_permissions"; then
-		do_sudo_as_user chmod "${ch_args[@]}" "$option_permissions" "$path"
-	fi
-	if test -n "$option_directory_permissions"; then
-		do_sudo_as_user find "$path" -type d -exec chmod "${ch_args[@]}" "$option_directory_permissions" {} \;
-	fi
-	if test -n "$option_file_permissions"; then
-		do_sudo_as_user find "$path" -type f -exec chmod "${ch_args[@]}" "$option_file_permissions" {} \;
-	fi
-}
+	# =====================================
+	# Helpers
 
-# =====================================
-# Act
+	function do_sudo_as_user {
+		local cmd=()
 
-if test "$option_partial" = 'yes'; then
-	for path in "${paths[@]}"; do
-		fs_own "$path" || :
-	done
-else
-	for path in "${paths[@]}"; do
-		fs_own "$path"
-	done
+		# verbose if provided
+		if test "$option_verbose" = 'yes'; then
+			cmd+=('echo-eval' '--')
+		fi
+
+		# use sudo only if custom owner
+		if test -n "$owner" -o "$option_sudo" = 'yes'; then
+			cmd+=(
+				'sudo'
+				'--set-home'
+			)
+
+			# add the user and group if provided
+			if test -n "$option_user"; then
+				cmd+=("--user=$option_user")
+			fi
+			if test -n "$option_group"; then
+				cmd+=("--group=$option_group")
+			fi
+		fi
+
+		# run
+		"${cmd[@]}" "$@"
+	}
+	function do_sudo_as_admin {
+		local cmd=()
+
+		# verbose if provided
+		if test "$option_verbose" = 'yes'; then
+			cmd+=('echo-eval' '--')
+		fi
+
+		# use sudo only if custom owner
+		if test -n "$owner" -o "$option_sudo" = 'yes'; then
+			cmd+=(
+				'sudo'
+				'--set-home'
+			)
+		fi
+
+		# run
+		"${cmd[@]}" "$@"
+	}
+	function fs_own {
+		local path="$1"
+
+		# chown
+		if test -n "$owner"; then
+			do_sudo_as_admin chown "${ch_args[@]}" "$owner" "$path"
+		fi
+
+		# chmod
+		if test -n "$option_permissions"; then
+			do_sudo_as_user chmod "${ch_args[@]}" "$option_permissions" "$path"
+		fi
+		if test -n "$option_directory_permissions"; then
+			do_sudo_as_user find "$path" -type d -exec chmod "${ch_args[@]}" "$option_directory_permissions" {} \;
+		fi
+		if test -n "$option_file_permissions"; then
+			do_sudo_as_user find "$path" -type f -exec chmod "${ch_args[@]}" "$option_file_permissions" {} \;
+		fi
+	}
+
+	# =====================================
+	# Act
+
+	if test "$option_partial" = 'yes'; then
+		for path in "${paths[@]}"; do
+			fs_own "$path" || :
+		done
+	else
+		for path in "${paths[@]}"; do
+			fs_own "$path"
+		done
+	fi
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	fs-own "$@"
 fi
diff --git a/commands/fs-parent b/commands/fs-parent
--- a/commands/fs-parent
+++ b/commands/fs-parent
@@ -2,38 +2,83 @@
 # shellcheck disable=SC2164,SC2103
 source "$DOROTHY/sources/strict.bash"
 
-path="${1-}"
-if test -z "$path" -o "$path" = '.'; then
-	# handles [fs-parent] and [fs-parent .]
-	cd ..
-	pwd
-elif test -d "$path"; then
-	# handles [fs-parent ..] and [fs-parent ./..]
-	cd "$path"
-	cd ..
-	pwd
-elif test -e "$path"; then
-	# handles files, in which case we just want the directory that contains the file
-	# not the directory that contains the direcvtory that contains the file
-	cd "$(dirname "$path")"
-	pwd
-else
-	# the path doesn't exist, so just infer it by trimming the basename
-	basename="$(basename "$path")"
-	parent="${path%"/$basename"}"
-	if test "$parent" != "$path"; then
-		echo "$parent"
-	else
-		cat <<-EOF >/dev/stderr
-			$(echo-style --error="ERROR:")
-			Unable to determine the parent directory for the non-existent path: $(echo-style --code="$path")
-		EOF
-		exit 1
-	fi
-fi
+function fs-parent() (
+	# =====================================
+	# Arguments
 
-# Why?
-# [dirname .] outputs [.]
-# [dirname ..] outputs [.]
-# [dirname <a-symlinked-directory>] outputs [.]
-# [dirname "$HOME"] outputs [/Users]
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Get the expanded parent path of a path.
+
+			USAGE:
+			fs-parent <path>
+
+			WHY:
+			[dirname .] outputs [.]
+			[dirname ..] outputs [.]
+			[dirname <a-symlinked-directory>] outputs [.]
+			[dirname "$HOME"] outputs [/Users]
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item path=''
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*)
+			if test -z "$path"; then
+				path="$item"
+			else
+				help "An unrecognised argument was provided: $item"
+			fi
+			;;
+		esac
+	done
+
+	# =====================================
+	# Action
+
+	if test -z "$path" -o "$path" = '.'; then
+		# handles [fs-parent] and [fs-parent .]
+		cd ..
+		pwd
+	elif test -d "$path"; then
+		# handles [fs-parent ..] and [fs-parent ./..]
+		cd "$path"
+		cd ..
+		pwd
+	elif test -e "$path"; then
+		# handles files, in which case we just want the directory that contains the file
+		# not the directory that contains the direcvtory that contains the file
+		cd "$(dirname "$path")"
+		pwd
+	else
+		# the path doesn't exist, so just infer it by trimming the basename
+		local basename parent
+		basename="$(basename "$path")"
+		parent="${path%"/$basename"}"
+		if test "$parent" != "$path"; then
+			echo "$parent"
+		else
+			cat <<-EOF >/dev/stderr
+				$(echo-style --error="ERROR:")
+				Unable to determine the parent directory for the non-existent path: $(echo-style --code="$path")
+			EOF
+			exit 1
+		fi
+	fi
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	fs-parent "$@"
+fi
diff --git a/commands/fs-unmount b/commands/fs-unmount
--- a/commands/fs-unmount
+++ b/commands/fs-unmount
@@ -1,122 +1,124 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# =====================================
-# Arguments
+function fs-unmount() (
+	# =====================================
+	# Arguments
 
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Unmounts a mount point.
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Unmounts a mount point.
 
-		USAGE:
-		fs-unmount [--] ...<mount-point>
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
-	fi
-	return 22 # Invalid argument
-}
-
-# process
-option_paths=()
-while test "$#" -ne 0; do
-	item="$1"
-	shift
-	case "$item" in
-	'help' | '--help' | '-h') help ;;
-	'--')
-		option_paths+=("$@")
-		shift "$#"
-		break
-		;;
-	'--'*) help "An unrecognised flag was provided: $item" ;;
-	*) option_paths+=("$item") ;;
-	esac
-done
-
-# =====================================
-# Action
-
-function fs_unmount_single {
-	# prepare
-	local mount_point was_mounted success title ec
-	mount_point="$(fs-realpath "$1")"
-	was_mounted='maybe'
-
-	# wrap in logs
-	title="fs-unmount ${mount_point@Q}"
-	success='no'
-	echo-segment --h2="$title"
-	function fs_unmount_single_return() {
-		if test "$success" = 'yes'; then
-			echo-segment --g2="$title"
-		else
-			echo-segment --e2="$title"
+			USAGE:
+			fs-unmount [--] ...<mount-point>
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
 		fi
+		return 22 # Invalid argument
 	}
-	trap fs_unmount_single_return RETURN
 
-	# is the path missing
-	if test ! -e "$mount_point"; then
-		echo-style --code="$mount_point" ' ' --success="was previously unmounted"
-		success='yes'
-		return
-	fi
-	# path exists
-
-	# is mounted? then unmount
-	while true; do
-		if is-mounted --target="$mount_point"; then
-			was_mounted='yes'
-			sudo umount --verbose --recursive "$mount_point" || {
-				# https://github.com/rfjakob/gocryptfs/issues/459
-				what-is-using "$mount_point" >/dev/tty
-				ec=0 && confirm-positive --ppid=$$ -- "Yes for try again, no for force, ctrl+c for abort" || ec="$?"
-				if test "$ec" -eq 1; then
-					sudo umount --verbose --recursive --force "$mount_point"
-				fi
-			}
-		else
-			was_mounted='no'
-			echo-style --code="$mount_point" ' ' --notice="was not an active mount"
+	# process
+	local item option_paths=()
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--')
+			option_paths+=("$@")
+			shift "$#"
 			break
-		fi
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) option_paths+=("$item") ;;
+		esac
 	done
 
-	# check if still mounted
-	if is-mounted --target="$mount_point"; then
-		echo-style --code="$mount_point" ' ' --error="failed to unmount"
-		return 66 # Directory not empty
-	fi
-	if test "$was_mounted" = 'yes'; then
-		echo-style --code="$mount_point" ' ' --success="was unmounted successfully"
-	fi
+	# =====================================
+	# Action
 
-	# clean up
-	if test -e "$mount_point"; then
-		sudo-inherit -- fs-rm "$mount_point"
-	fi
-	if test -e "$mount_point"; then
-		echo-style --code="$mount_point" ' ' --success="was unmounted successfully" ', ' --error="but failed to clean up"
-		return 66 # Directory not empty
-	fi
-	echo-style --code="$mount_point" ' ' --success="was cleaned successfully"
+	function fs_unmount_single {
+		# prepare
+		local mount_point was_mounted success title ec
+		mount_point="$(fs-realpath "$1")"
+		was_mounted='maybe'
 
-	# success
-	echo-style --code="$mount_point" ' ' --success="was unmounted and cleaned successfully"
-}
-function fs_unmount {
+		# wrap in logs
+		title="fs-unmount ${mount_point@Q}"
+		success='no'
+		echo-segment --h2="$title"
+		function fs_unmount_single_return {
+			if test "$success" = 'yes'; then
+				echo-segment --g2="$title"
+			else
+				echo-segment --e2="$title"
+			fi
+		}
+		trap fs_unmount_single_return RETURN
+
+		# is the path missing
+		if test ! -e "$mount_point"; then
+			echo-style --code="$mount_point" ' ' --success="was previously unmounted"
+			success='yes'
+			return
+		fi
+		# path exists
+
+		# is mounted? then unmount
+		while true; do
+			if is-mounted --target="$mount_point"; then
+				was_mounted='yes'
+				sudo umount --verbose --recursive "$mount_point" || {
+					# https://github.com/rfjakob/gocryptfs/issues/459
+					what-is-using "$mount_point" >/dev/tty
+					ec=0 && confirm-positive --ppid=$$ -- "Yes for try again, no for force, ctrl+c for abort" || ec="$?"
+					if test "$ec" -eq 1; then
+						sudo umount --verbose --recursive --force "$mount_point"
+					fi
+				}
+			else
+				was_mounted='no'
+				echo-style --code="$mount_point" ' ' --notice="was not an active mount"
+				break
+			fi
+		done
+
+		# check if still mounted
+		if is-mounted --target="$mount_point"; then
+			echo-style --code="$mount_point" ' ' --error="failed to unmount"
+			return 66 # Directory not empty
+		fi
+		if test "$was_mounted" = 'yes'; then
+			echo-style --code="$mount_point" ' ' --success="was unmounted successfully"
+		fi
+
+		# clean up
+		if test -e "$mount_point"; then
+			sudo-inherit -- fs-rm "$mount_point"
+		fi
+		if test -e "$mount_point"; then
+			echo-style --code="$mount_point" ' ' --success="was unmounted successfully" ', ' --error="but failed to clean up"
+			return 66 # Directory not empty
+		fi
+		echo-style --code="$mount_point" ' ' --success="was cleaned successfully"
+
+		# success
+		echo-style --code="$mount_point" ' ' --success="was unmounted and cleaned successfully"
+	}
+
+	# action
+	local mount_point
 	if test "${#option_paths[@]}" -eq 0; then
 		help "No paths were provided"
 	fi
-	for mount_point in "$@"; do
+	for mount_point in "${option_paths[@]}"; do
 		fs_unmount_single "$mount_point"
 	done
-}
+)
 
 # fire if invoked standalone
 if test "$0" = "${BASH_SOURCE[0]}"; then
-	fs_unmount "${option_paths[@]}"
+	fs-unmount "$@"
 fi
diff --git a/commands/get-os-theme b/commands/get-os-theme
--- a/commands/get-os-theme
+++ b/commands/get-os-theme
@@ -1,45 +1,47 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# =====================================
-# Arguments
+function get-os-theme() (
+	# =====================================
+	# Arguments
 
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Output $(echo-style --code="light") or $(echo-style --code="dark") based on the theme of the Operating System.
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Output $(echo-style --code="light") or $(echo-style --code="dark") based on the theme of the Operating System.
 
-		USAGE:
-		get-os-theme
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
-	fi
-	return 22 # Invalid argument
-}
+			USAGE:
+			get-os-theme
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
 
-# process
-while test "$#" -ne 0; do
-	item="$1"
-	shift
-	case "$item" in
-	'help' | '--help' | '-h') help ;;
-	'--'*) help "An unrecognised flag was provided: $item" ;;
-	*) help "An unrecognised argument was provided: $item" ;;
-	esac
-done
+	# process
+	local item
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) help "An unrecognised argument was provided: $item" ;;
+		esac
+	done
 
-# =====================================
-# Action
+	# =====================================
+	# Action
 
-function get_os_theme_unsupported {
-	echo-style --error="Unable to determine the Operating System theme." >/dev/stderr
-	return 19 # ENODEV 19 Operation not supported by device
-}
-function get_os_theme {
+	function get_os_theme_unsupported {
+		echo-style --error="Unable to determine the Operating System theme." >/dev/stderr
+		return 19 # ENODEV 19 Operation not supported by device
+	}
+
+	local result
 	if is-mac; then
-		result="$(osascript -e "tell application \"System Events\" to tell appearance preferences to get dark mode" || :)"
+		result="$(osascript -e 'tell application "System Events" to tell appearance preferences to get dark mode' || :)"
 		if test "$result" = 'true'; then
 			echo 'dark'
 		elif test "$result" = 'false'; then
@@ -58,9 +60,10 @@ function get_os_theme {
 	else
 		get_os_theme_unsupported
 	fi
-}
+
+)
 
 # fire if invoked standalone
 if test "$0" = "${BASH_SOURCE[0]}"; then
-	get_os_theme
+	get-os-theme "$@"
 fi
diff --git a/commands/itunes-owners b/commands/itunes-owners
--- a/commands/itunes-owners
+++ b/commands/itunes-owners
@@ -2,60 +2,111 @@
 # dependencies: ffmpeg, php, pv
 source "$DOROTHY/sources/strict.bash"
 
-# dependencies
-env QUIET=yes setup-util-pv
+function itunes-owners() (
+	# =====================================
+	# Arguments
 
-song_list="$(mktemp)"
-owner_list="$(mktemp)"
-database="$HOME/Music/iTunes/iTunes Music Library.xml"
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Outputs ownership data for your iTunes media library.
 
-function decode {
-	# url
-	# node: node -e "process.stdout.write(decodeURI(require('fs').readFileSync(0, 'utf8')))"
-	# perl: perl -pe 's/\%(\w\w)/chr hex $1/ge'
-	# php -R 'echo urldecode($argn);'
+			USAGE:
+			itunes-owners
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
 
-	# html
-	# recode: recode html..utf8
-	# php: php -R 'echo html_entity_decode($argn);'
+	# process
+	local item
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) help "An unrecognised argument was provided: $item" ;;
+		esac
+	done
 
-	# php
-	# stdin: file_get_contents("php://stdin", "r")
-	# args: $argn
+	# =====================================
+	# Dependencies
 
-	# shellcheck disable=SC2016
-	php -R 'echo html_entity_decode(urldecode($argn));' <<<"$1"
-}
+	env QUIET=yes setup-util-pv
+	source "$DOROTHY/sources/ripgrep.bash"
 
-echo-style --h2="Fetching music to [$song_list]..."
-grep '<key>Location</key><string>file://' <"$database" | sed 's/.*<string>file:..//; s/<\/string>//' >"$song_list"
-song_count="$(wc -l <"$song_list" | xargs)"
-echo-style --g2="...fetched $song_count songs"
+	# =====================================
+	# Action
 
-echo-style --h2="Fetching owners to [$owner_list]..."
-while read -r line; do
-	echo -n X # why? perhaps for pv?
-	file="$(decode "$line")"
-	# echo "analysing: $file"
-	# if test -f "$file"; then
-	# 	echo "missing: $file"
-	# 	exit 1
-	# fi
-	owner="$(ffprobe -i "$file" |& grep 'account_id' | sed 's/.*account_id.*: //')"
-	if test -n "$owner"; then
-		# echo "found owner: $owner"
-		printf '%s\t%s' "$owner" "$file" >>"$owner_list"
-	fi
-done <"$song_list" | pv -s "$song_count" - >/dev/null
-# extract
-owners="$(cut -f1 -s <"$owner_list" | sort | uniq)"
-owners_count="$(echo "$owners" | wc -l | xargs)"
-owned_count="$(wc -l <"$owner_list" | xargs)"
-echo-style --g2="...found $owned_count owned media files, with $owners_count unique owners."
+	local song_list owner_list missing_list database
+	song_list="$(fs-temp --directory='itunes-owners' --file='songs.txt' --touch)"
+	owner_list="$(fs-temp --directory='itunes-owners' --file='owner.txt' --touch)"
+	missing_list="$(fs-temp --directory='itunes-owners' --file='missing.txt' --touch)"
+	database="$HOME/Music/iTunes/iTunes Music Library.xml"
+	echo-style --h2="Reading $database"
 
-echo-style --h2="UNIQUE OWNERS:"
-echo "$owners"
-echo
-echo-style --h2="OWNED MEDIA:"
-sort <"$owner_list" | column -t -s $'\t'
-echo
+	# fetch songs
+	local song_count=0
+	function fetch_songs {
+		echo-style --h2="Fetching songs to $song_list"
+		grep '<key>Location</key><string>file://' <"$database" | sed 's/.*<string>file:..//; s/<\/string>//' | echo-decode-url | echo-decode-html >"$song_list"
+		song_count="$(wc -l <"$song_list" | xargs)"
+		echo-style --g2="...found $song_count media files."
+	}
+	fetch_songs # @todo use eval-collapse
+
+	# fetch owners
+	function fetch_owners {
+		local song owner
+		echo-style --h2="Fetching owners to $owner_list"
+		while read -r song; do
+			# echo -n X # why? perhaps for pv?
+
+			# check
+			if test ! -f "$song"; then
+				echo-style "$song" ' ' --notice='is missing'
+				echo "$song" >>"$missing_list"
+				continue
+			fi
+
+			# fetch owner
+			# trunk-ignore(shellcheck/SC2016)
+			owner="$(ffprobe -i "$song" |& rg -o 'account_id\s*:\s*(.+)' --replace '$1' || :)"
+
+			# write
+			if test -n "$owner"; then
+				echo-style "$song" ' ' --green='owner is' ' ' --bold="$owner"
+				printf '%s\t%s' "$owner" "$song" >>"$owner_list"
+				# else
+				# echo-style --notice='👆 owner is missing'
+			fi
+		done <"$song_list" # | pv -s "$song_count" - >/dev/null
+	}
+	fetch_owners
+
+	# extract
+	local owners owner_count owned_count
+	owners="$(cut -f1 -s <"$owner_list" | sort | uniq)"
+	owner_count="$(echo "$owners" | wc -l | xargs)"
+	owned_count="$(wc -l <"$owner_list" | xargs)"
+
+	echo-style --h2="$owner_count UNIQUE OWNERS:"
+	echo "$owners"
+	echo
+
+	echo-style --h2="$owned_count OWNED MEDIA:"
+	sort <"$owner_list" | column -t -s $'\t'
+	echo
+
+	echo-style --h2="$(wc -l <"$missing_list" | xargs) MISSING MEDIA:"
+	sort <"$missing_list"
+	echo
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	itunes-owners "$@"
+fi
diff --git a/commands/pdf-decrypt b/commands/pdf-decrypt
--- a/commands/pdf-decrypt
+++ b/commands/pdf-decrypt
@@ -1,30 +1,70 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-p="$(pwd)"
-password="$1"
-outdir="${2:-out}"
-outdir="$(fs-absolute "$outdir")"
-mkdir -p "$outdir"
+function to-png() (
+	# =====================================
+	# Arguments
 
-function decrypt {
-	local input inputdir output
-	input="$(fs-absolute "$1")"
-	inputdir="$(dirname "$input")"
-	output="$outdir/$(basename "$1")"
-	cd "$inputdir" || exit 1
-	echo "$1 to $output"
-	while test -f "$output"; do
-		output="$(fs-filename "$output")!.pdf"
-	done
-	(qpdf -password="$password" -decrypt "$input" "$output" && echo "SUCCESS") || echo "FAILURE"
-	cd "$p" || exit 1
-}
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Save decrypted copies of the PDF inputs.
 
-if test -n "$password"; then
-	find-files --extension=pdf | while read -r file; do
-		decrypt "$file" "$2" "$1"
+			USAGE:
+			pdf-decrypt [--password=<password>] ...<input>
+
+			EXAMPLE:
+			pdf-decrypt *.pdf
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item files=() password=''
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--password='*) password="${item:11}" ;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) files+=("$item") ;;
+		esac
 	done
-else
-	echo "decrypt <password>"
+
+	# =====================================
+	# Dependencies
+
+	if command-missing qpdf; then
+		echo-style --error="[qpdf] is missing, install it first." >/dev/stderr
+		return 1
+	fi
+
+	# =====================================
+	# Act
+
+	local input output current_password
+	for input in "${files[@]}"; do
+		output="$(fs-filename "$input") [decrypted].pdf"
+		current_password="$(
+			ask --required --password \
+				--question="Enter the password for $input" \
+				--default="$password"
+		)"
+
+		eval-collapse \
+			--pending="$(echo-style --bold="Decrypting " --code="$input" --bold=" to " --code="$output")" \
+			--success="$(echo-style --bold+green="Decrypted " --code="$input" --bold=" to " --code="$output")" \
+			--failure="$(echo-style --bold+red="Failed to decrypt " --code="$input" --bold=" to " --code="$output")" \
+			-- qpdf -password="$current_password" -decrypt "$input" "$output" || :
+	done
+
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	svg-export "$@"
 fi
diff --git a/commands/select-shell b/commands/select-shell
--- a/commands/select-shell
+++ b/commands/select-shell
@@ -2,170 +2,177 @@
 source "$DOROTHY/sources/strict.bash"
 source "$DOROTHY/sources/environment.sh" # ensure new installations are detected
 
-# =====================================
-# Arguments
+function select-shell() (
+	# =====================================
+	# Arguments
 
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Set your user's login shell to become the first available shell of your preferences.
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Set your user's login shell to become the first available shell of your preferences.
 
-		USAGE:
-		select-shell [--] ...<preference>
+			USAGE:
+			select-shell [--] ...<preference>
 
-		OPTIONS:
-		If no preferences are provided,
-		then [USER_SHELLS] from your [shell.bash] user configuration file will be used.
+			OPTIONS:
+			If no preferences are provided,
+			then [USER_SHELLS] from your [shell.bash] user configuration file will be used.
 
-		QUIRKS:
-		You can use a command name, such as [bash] to select the preferred variation of the shell.
-		You can use a full path, such as [/bin/bash] to select a specific variation of the shell.
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
-	fi
-	return 22 # Invalid argument
-}
-
-# process
-option_shells=()
-while test "$#" -ne 0; do
-	item="$1"
-	shift
-	case "$item" in
-	'help' | '--help' | '-h') help ;;
-	'--')
-		option_shells+=("$@")
-		shift "$#"
-		break
-		;;
-	'--'*) help "An unrecognised flag was provided: $item" ;;
-	*) option_shells+=("$item") ;;
-	esac
-done
-
-# =====================================
-# Helpers
-
-function none_available {
-	# no shell was selected, error
-	echo-style --error="No preferred shell was currently installed, as such none were able to be selected." >/dev/stderr
-	return 3 # ESRCH 3 No such process
-}
-function use_shell {
-	# use this specific shell
-	local input="$1" path
-
-	# if name, expand the name into a path
-	# if path, validate the path exists
-	path="$(command -v "$input" || :)"
-	if test -z "$shell"; then
-		echo-segment --error="Failed to verify that shell [$path] exists and is executable." >/dev/stderr
-		return 8 # ENOEXEC 8 Exec format error
-	fi
-
-	# log
-	echo-segment --h1="Selected the shell [$input] at [$path]" >/dev/tty
-
-	# add the shell to the system whitelist
-	echo-segment --h2="Whitelisting as a login shell" >/dev/tty
-	if contains-line "$path" </etc/shells; then
-		echo-segment --green="Already within the system whitelist [/etc/shells]" >/dev/tty
-	else
-		echo-segment --h3="Add to system whitelist [/etc/shells]" >/dev/tty
-		echo "$path" | sudo tee -a /etc/shells
-		echo-segment --g3="Add to system whitelist [/etc/shells]" >/dev/tty
-	fi
-	echo-segment --g2="Whitelisting as a login shell" >/dev/tty
-
-	echo-segment --h2="Set as the login shell for [$USER]" >/dev/tty
-	if command-exists chpass; then
-		echo-style --dim="You can ignore [chpass: no changes made] warnings." >/dev/tty
-		# mac
-		chpass -s "$path" -u "$USER"
-	elif command-exists chsh; then
-		# ubuntu
-		chsh -s "$path" "$USER"
-	else
-		# unknown fail
-		echo-style --error="Unable to apply the shell on this system, as neither of the tools to do it [chpass] nor [chsh] exist on this sytem." >/dev/stderr
-		echo-segment --e2="Set as the login shell for [$USER]" >/dev/tty
-		return 19 # ENODEV 19 Operation not supported by device
-	fi
-	echo-segment --g2="Set as the login shell for [$USER]" >/dev/tty
-
-	# success case
-	echo-segment --g1="Selected the shell [$input] at [$path]" >/dev/tty
-	echo-style --notice="Restart your terminal, or open a new one, for the change to take effect." >/dev/tty
-}
-function use_first_available {
-	# use the first available preference passed to us
-	local shell
-	for shell in "$@"; do
-		if test -z "$shell"; then
-			help "Invalid configuration was received, there was an empty item:" "$(echo-verbose "$@")" >/dev/tty
+			QUIRKS:
+			You can use a command name, such as [bash] to select the preferred variation of the shell.
+			You can use a full path, such as [/bin/bash] to select a specific variation of the shell.
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
 		fi
-		if command-exists "$shell"; then
-			echo-style --success="Preference available on this system:" ' ' --code="$shell" >/dev/tty
-			if use_shell "$shell"; then
-				return
-			fi # else continue
-		else
-			echo-style --notice="Preference not yet installed on this system:" ' ' --code="$shell" >/dev/tty
-		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item shells=()
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--')
+			shells+=("$@")
+			shift "$#"
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) shells+=("$item") ;;
+		esac
 	done
-	none_available
-}
-function use_selection {
-	# prompt the user which available shell to use
-	if test "$#" -eq 0; then
-		none_available
-	fi
-	use_shell "$(
-		choose-option --required \
-			--question="Which shell to use as your login shell?" \
-			-- "$@"
-	)"
-}
 
-# =====================================
-# Action
+	# =====================================
+	# Helpers
 
-# arguments
-if test "${#option_shells[@]}" -ne 0; then
-	use_first_available "${option_shells[@]}"
-else
-	# configuration
-	source "$DOROTHY/sources/config.sh"
-	USER_SHELLS=()
-	load_dorothy_config 'shells.bash'
-	option_shells=("${USER_SHELLS[@]}")
-	if test "${#option_shells[@]}" -ne 0; then
-		echo-style --notice="No argument configuration found, using user configuration." >/dev/tty
-		use_first_available "${USER_SHELLS[@]}"
-	else
-		# system
-		echo-style --notice="No user configuration found, attempting known POSIX shells." >/dev/tty
-		known_posix_shells=(
-			# POSIX SHELLS
-			fish
-			zsh  # Z shell
-			bash # bourne again shell
-			sh   # bourne shell
-			ash  # almquist shell
-			dash # debian almquist shell
-			ksh  # korn shell
-			hush # hush, an independent implementation of a Bourne shell for BusyBox
-			# NON-POSIX SHELLS, do not enable, as Dorothy does not support
-			# tsch
-		)
-		available_posix_shells=()
-		for shell in "${known_posix_shells[@]}"; do
+	function none_available {
+		# no shell was selected, error
+		echo-style --error="No preferred shell was currently installed, as such none were able to be selected." >/dev/stderr
+		return 3 # ESRCH 3 No such process
+	}
+	function use_shell {
+		# use this specific shell
+		local shell="$1" path
+
+		# if name, expand the name into a path
+		# if path, validate the path exists
+		path="$(command -v "$shell" || :)"
+		if test -z "$path"; then
+			echo-segment --error="Failed to verify that shell [$shell] exists and is executable." >/dev/stderr
+			return 8 # ENOEXEC 8 Exec format error
+		fi
+
+		# log
+		echo-segment --h1="Selected the shell [$shell] at [$path]" >/dev/tty
+
+		# add the shell to the system whitelist
+		echo-segment --h2="Whitelisting as a login shell" >/dev/tty
+		if contains-line "$path" </etc/shells; then
+			echo-segment --green="Already within the system whitelist [/etc/shells]" >/dev/tty
+		else
+			echo-segment --h3="Add to system whitelist [/etc/shells]" >/dev/tty
+			echo "$path" | sudo tee -a /etc/shells
+			echo-segment --g3="Add to system whitelist [/etc/shells]" >/dev/tty
+		fi
+		echo-segment --g2="Whitelisting as a login shell" >/dev/tty
+
+		echo-segment --h2="Set as the login shell for [$USER]" >/dev/tty
+		if command-exists chpass; then
+			echo-style --dim="You can ignore [chpass: no changes made] warnings." >/dev/tty
+			# mac
+			chpass -s "$path" -u "$USER"
+		elif command-exists chsh; then
+			# ubuntu
+			chsh -s "$path" "$USER"
+		else
+			# unknown fail
+			echo-style --error="Unable to apply the shell on this system, as neither of the tools to do it [chpass] nor [chsh] exist on this sytem." >/dev/stderr
+			echo-segment --e2="Set as the login shell for [$USER]" >/dev/tty
+			return 19 # ENODEV 19 Operation not supported by device
+		fi
+		echo-segment --g2="Set as the login shell for [$USER]" >/dev/tty
+
+		# success case
+		echo-segment --g1="Selected the shell [$shell] at [$path]" >/dev/tty
+		echo-style --notice="Restart your terminal, or open a new one, for the change to take effect." >/dev/tty
+	}
+	function use_first_available {
+		# use the first available preference passed to us
+		local shell
+		for shell in "$@"; do
+			if test -z "$shell"; then
+				help "Invalid configuration was received, there was an empty item:" "$(echo-verbose "$@")" >/dev/tty
+			fi
 			if command-exists "$shell"; then
-				available_posix_shells+=("$shell")
+				echo-style --success="Preference available on this system:" ' ' --code="$shell" >/dev/tty
+				if use_shell "$shell"; then
+					return
+				fi # else continue
+			else
+				echo-style --notice="Preference not yet installed on this system:" ' ' --code="$shell" >/dev/tty
 			fi
 		done
-		use_selection "${available_posix_shells[@]}"
+		none_available
+	}
+	function use_selection {
+		# prompt the user which available shell to use
+		if test "$#" -eq 0; then
+			none_available
+		fi
+		use_shell "$(
+			choose-option --required \
+				--question="Which shell to use as your login shell?" \
+				-- "$@"
+		)"
+	}
+
+	# =====================================
+	# Action
+
+	# arguments
+	local known_posix_shells available_posix_shells shell
+	if test "${#shells[@]}" -ne 0; then
+		use_first_available "${shells[@]}"
+	else
+		# configuration
+		source "$DOROTHY/sources/config.sh"
+		USER_SHELLS=()
+		load_dorothy_config 'shells.bash'
+		shells=("${USER_SHELLS[@]}")
+		if test "${#shells[@]}" -ne 0; then
+			echo-style --notice="No argument configuration found, using user configuration." >/dev/tty
+			use_first_available "${USER_SHELLS[@]}"
+		else
+			# system
+			echo-style --notice="No user configuration found, attempting known POSIX shells." >/dev/tty
+			known_posix_shells=(
+				# POSIX SHELLS
+				fish
+				zsh  # Z shell
+				bash # bourne again shell
+				sh   # bourne shell
+				ash  # almquist shell
+				dash # debian almquist shell
+				ksh  # korn shell
+				hush # hush, an independent implementation of a Bourne shell for BusyBox
+				# NON-POSIX SHELLS, do not enable, as Dorothy does not support
+				# tsch
+			)
+			available_posix_shells=()
+			for shell in "${known_posix_shells[@]}"; do
+				if command-exists "$shell"; then
+					available_posix_shells+=("$shell")
+				fi
+			done
+			use_selection "${available_posix_shells[@]}"
+		fi
 	fi
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	select-shell "$@"
 fi
diff --git a/commands/setup-utils b/commands/setup-utils
--- a/commands/setup-utils
+++ b/commands/setup-utils
@@ -1,108 +1,113 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# =====================================
-# Arguments
+function setup-utils() (
+	# =====================================
+	# Arguments
 
-# local
-utils=()
-reconfigure='no'
+	function help {
+		cat <<-EOF >/dev/stderr
+			USAGE:
+			setup-utils
+			# ^ install the [SETUP_UTILS] listed in your [setup.bash] configuration file
 
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		USAGE:
-		setup-utils
-		# ^ install the [SETUP_UTILS] listed in your [setup.bash] configuration file
+			setup-utils -- <...util>
+			# ^ install the specified utilities
 
-		setup-utils -- <...util>
-		# ^ install the specified utilities
+			setup-utils --configure
+			# ^ prompt for which utilities you wish to setup, and update [SETUP_UTILS] accordingly
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
 
-		setup-utils --configure
-		# ^ prompt for which utilities you wish to setup, and update [SETUP_UTILS] accordingly
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
-	fi
-	return 22 # Invalid argument
-}
+	# process
+	local item utils=() reconfigure='no'
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--configure') reconfigure='yes' ;;
+		'--')
+			utils+=("$@")
+			shift $#
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) help "An unrecognised argument was provided: $item" ;;
+		esac
+	done
 
-# process
-while test "$#" -ne 0; do
-	item="$1"
-	shift
-	case "$item" in
-	'help' | '--help' | '-h') help ;;
-	'--configure') reconfigure='yes' ;;
-	'--')
-		utils+=("$@")
-		shift $#
-		break
-		;;
-	'--'*) help "An unrecognised flag was provided: $item" ;;
-	*) help "An unrecognised argument was provided: $item" ;;
-	esac
-done
+	# =====================================
+	# Configuration
 
-# =====================================
-# Configuration
+	# if args, don't use config
+	if test "${#utils[@]}" -eq 0; then
+		# no args, so use configuration
+		source "$DOROTHY/sources/config.bash"
 
-# if args, don't use config
-if test "${#utils[@]}" -eq 0; then
-	# no args, so use configuration
-	source "$DOROTHY/sources/config.bash"
+		# setup.bash provides:
+		local SETUP_UTILS=()
+		load_dorothy_config 'setup.bash'
 
-	# setup.bash provides:
-	SETUP_UTILS=()
-	load_dorothy_config 'setup.bash'
+		# if empty, or --configure is specified, then prompt the user which ones
+		local options file __basename name
+		if test "${#SETUP_UTILS[@]}" -eq 0 -o "$reconfigure" = 'yes'; then
+			source "$DOROTHY/sources/nullglob.bash"
+			options=()
+			for file in "$DOROTHY/commands/setup-util-"*; do
+				__basename="$(basename "$file")"
+				name="${__basename:11}"
+				options+=("$name")
+			done
+			mapfile -t utils < <(
+				choose-option --multi \
+					--question="Which utilities to install?" \
+					-- "${options[@]}"
+			)
 
-	# if empty, or --configure is specified, then prompt the user which ones
-	if test "${#SETUP_UTILS[@]}" -eq 0 -o "$reconfigure" = 'yes'; then
-		source "$DOROTHY/sources/nullglob.bash"
-		options=()
-		for file in "$DOROTHY/commands/setup-util-"*; do
-			basename="$(basename "$file")"
-			name="${basename:11}"
-			options+=("$name")
-		done
-		mapfile -t utils < <(
-			choose-option --multi \
-				--question="Which utilities to install?" \
-				-- "${options[@]}"
-		)
-
-		# save
-		update_dorothy_user_config 'setup.bash' -- \
-			--field='SETUP_UTILS' --array="$(echo-lines -- "${utils[@]}")"
-	else
-		utils=("${SETUP_UTILS[@]}")
-	fi
-fi
-
-# =====================================
-# Action
-
-echo-segment --h1="Setup ${#utils[@]} utilities"
-for item in "${utils[@]}"; do
-	if test -n "$item"; then
-		cmd="setup-util-${item}"
-		if command-exists "$cmd"; then
-			"$cmd"
+			# save
+			update_dorothy_user_config 'setup.bash' -- \
+				--field='SETUP_UTILS' --array="$(echo-lines -- "${utils[@]}")"
 		else
-			# can't use -EOF, as we want to print spacing
-			{
-				echo-style --e1="Unable to install [$item], as [$cmd] doesn't exist." $'\n' \
-					$'\n' \
-					--red="You can create the missing command by running:" $'\n' \
-					$'\n' \
-					--dim="    touch $DOROTHY/user/$cmd" $'\n' \
-					--dim="    edit $DOROTHY/user/$cmd" $'\n' \
-					--dim="    open https://github.com/bevry/dorothy/discussions/73" $'\n' \
-					$'\n' \
-					--red="Once the command is created, re-run your prior command."
-				exit 1
-			} >/dev/stderr
+			utils=("${SETUP_UTILS[@]}")
 		fi
 	fi
-done
-echo-segment --g1="Setup ${#utils[@]} utilities"
+
+	# =====================================
+	# Action
+
+	local item cmd
+	echo-segment --h1="Setup ${#utils[@]} utilities"
+	for item in "${utils[@]}"; do
+		if test -n "$item"; then
+			cmd="setup-util-${item}"
+			if command-exists "$cmd"; then
+				"$cmd"
+			else
+				# can't use -EOF, as we want to print spacing
+				{
+					echo-style --e1="Unable to install [$item], as [$cmd] doesn't exist." $'\n' \
+						$'\n' \
+						--red="You can create the missing command by running:" $'\n' \
+						$'\n' \
+						--dim="    touch $DOROTHY/user/$cmd" $'\n' \
+						--dim="    edit $DOROTHY/user/$cmd" $'\n' \
+						--dim="    open https://github.com/bevry/dorothy/discussions/73" $'\n' \
+						$'\n' \
+						--red="Once the command is created, re-run your prior command."
+					exit 1
+				} >/dev/stderr
+			fi
+		fi
+	done
+	echo-segment --g1="Setup ${#utils[@]} utilities"
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	setup-utils "$@"
+fi
diff --git a/commands/ssh-helper b/commands/ssh-helper
--- a/commands/ssh-helper
+++ b/commands/ssh-helper
@@ -2,220 +2,229 @@
 source "$DOROTHY/sources/strict.bash"
 source "$DOROTHY/sources/nullglob.bash"
 
-# =====================================
-# Arguments
+function ssh-helper() (
+	# =====================================
+	# Arguments
 
-# prepare
-actions=(
-	'new'
-	'add'
-	'permissions'
-	'test'
-	'connect'
-)
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Helpers for interacting with SSH.
 
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Helpers for interacting with SSH.
+			USAGE:
 
-		USAGE:
+			ssh-helper new
+			  <filename>
+			  <comment, e.g. your email>
 
-		ssh-helper new
-		  <filename>
-		  <comment, e.g. your email>
+			    Generate a new SSH key with appropriate conventions.
 
-		    Generate a new SSH key with appropriate conventions.
+			ssh-helper add
 
-		ssh-helper add
+			    Make the SSH agent aware of all your SSH keys.
 
-		    Make the SSH agent aware of all your SSH keys.
+			ssh-helper permissions
 
-		ssh-helper permissions
+			    Correct the permissions for the SSH files.
 
-		    Correct the permissions for the SSH files.
+			ssh-helper test
+			  <server URI>
 
-		ssh-helper test
-		  <server URI>
+			    Test whether or not your SSH agent can correctly authenticate to the server.
 
-		    Test whether or not your SSH agent can correctly authenticate to the server.
+			ssh-helper connect
+			  <...ssh args, e.g. server URI>
 
-		ssh-helper connect
-		  <...ssh args, e.g. server URI>
+			    Keep trying to connect (login) to the server until there is a successful connection. All the flags/arguments are the same as the [ssh] command, as they are passed directly to it.
 
-		    Keep trying to connect (login) to the server until there is a successful connection. All the flags/arguments are the same as the [ssh] command, as they are passed directly to it.
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
 
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
-	fi
-	return 22 # Invalid argument
-}
-
-# process
-action=''
-action_args=()
-while test "$#" -ne 0; do
-	item="$1"
-	shift
-	case "$item" in
-	'help' | '--help' | '-h') help ;;
-	'--'*) help "An unrecognised flag was provided: $item" ;;
-	*)
-		action="$item"
-		action_args+=("$@")
-		shift $#
-		break
-		;;
-	esac
-done
-
-# ensure valid action
-action="$(
-	choose-option --required \
-		--question='which action to perform?' \
-		--filter="$action" -- "${actions[@]}"
-)"
-
-# =====================================
-# Actions
-
-function ssh_new {
-	local name comment path
-	name="${1:?"USAGE: ssh-helper new <key name> [key comment, e.g. your email]"}"
-	comment="${2:-"$name"}"
-
-	# prepare
-	mkdir -p "$HOME/.ssh"
-	touch "$HOME/.ssh/config"
-
-	# make the new key
-	path="$HOME/.ssh/$name"
-	for old_public_or_private_key in "$path"*; do
-		rm -v "$old_public_or_private_key"
+	# process
+	local item action='' args=()
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*)
+			action="$item"
+			args+=("$@")
+			shift $#
+			break
+			;;
+		esac
 	done
-	echo "Creating new ssh-key at $path with comment $comment"
-	ssh-keygen -t rsa -b 4096 -C "$comment" -f "$path"
 
-	# add the new key to ssh configuration
-	# http://stackoverflow.com/a/33228296/130638
-	printf '\nIdentityFile ~/.ssh/%s' "$name" >>"$HOME/.ssh/config"
+	# ensure valid action
+	local actions=(
+		'new'
+		'add'
+		'permissions'
+		'test'
+		'connect'
+	)
+	action="$(
+		choose-option --required \
+			--question='which action to perform?' \
+			--filter="$action" -- "${actions[@]}"
+	)"
 
-	# output the public key so the user can add it to the service
-	cat <<-EOF
-		Public key that you can share is outputted below
-		------------------------------------------------
-		$(cat "${path}.pub")
-	EOF
-}
+	# =====================================
+	# Actions
 
-function act_add {
-	local ssh_add_new ssh_add_known private_key public_key
+	function ssh_new {
+		local name comment path
+		name="${1-}"
+		comment="${2:-"$name"}"
+		path="$HOME/.ssh/$name"
 
-	# ensure dir and permissions
-	act_permissions
+		# check
+		if test -z "$name"; then
+			help "Missing <filename> in [ssh-helper new <filename>]."
+		fi
 
-	# which command
-	ssh_add_new=()
-	ssh_add_known=()
-	if is-mac; then
-		if test "$(uname -r | cut -d . -f1)" -ge 21; then
-			ssh_add_new=(
-				'/usr/bin/ssh-add'
-				'--apple-use-keychain'
-			)
-			ssh_add_known=(
-				'/usr/bin/ssh-add'
-				'--apple-load-keychain'
-			)
+		# prepare
+		mkdir -p "$HOME/.ssh"
+		touch "$HOME/.ssh/config"
+
+		# remove the old keys
+		rm -v "$path"*
+
+		# make the new key
+		echo "Creating new ssh-key at $path with comment $comment"
+		ssh-keygen -t rsa -b 4096 -C "$comment" -f "$path"
+
+		# add the new key to ssh configuration
+		# http://stackoverflow.com/a/33228296/130638
+		printf '\nIdentityFile ~/.ssh/%s' "$name" >>"$HOME/.ssh/config"
+
+		# output the public key so the user can add it to the service
+		cat <<-EOF
+			Public key that you can share is outputted below
+			------------------------------------------------
+			$(cat "${path}.pub")
+		EOF
+	}
+
+	function ssh_add {
+		local add_new add_known
+
+		# ensure dir and permissions
+		act_permissions
+
+		# which command
+		add_new=()
+		add_known=()
+		if is-mac; then
+			if test "$(uname -r | cut -d . -f1)" -ge 21; then
+				add_new=(
+					'/usr/bin/ssh-add'
+					'--apple-use-keychain'
+				)
+				add_known=(
+					'/usr/bin/ssh-add'
+					'--apple-load-keychain'
+				)
+			else
+				add_new=(
+					'/usr/bin/ssh-add'
+					'-K'
+				)
+				add_known=(
+					'/usr/bin/ssh-add'
+					'-A'
+				)
+			fi
 		else
-			ssh_add_new=(
-				'/usr/bin/ssh-add'
+			add_new=(
+				'ssh-add'
 				'-K'
 			)
-			ssh_add_known=(
-				'/usr/bin/ssh-add'
+			add_known=(
+				'ssh-add'
 				'-A'
 			)
 		fi
-	else
-		ssh_add_new=(
-			'ssh-add'
-			'-K'
-		)
-		ssh_add_known=(
-			'ssh-add'
-			'-A'
-		)
-	fi
 
-	# for found keys, correct permissions, add to keychain, add to agent
-	find "$HOME/.ssh/"*.pub | while read -r public_key; do
-		chmod 600 "$public_key" || :
-		private_key="${public_key%.pub}"
-		if test -f "$private_key"; then
-			chmod 600 "$private_key" || :
-			("${ssh_add_new[@]}" "$private_key") || :
-		fi
-	done
+		# for found keys, correct permissions, add to keychain, add to agent
+		local public_key private_key
+		find "$HOME/.ssh/"*.pub | while read -r public_key; do
+			chmod 600 "$public_key" || :
+			private_key="${public_key%.pub}"
+			if test -f "$private_key"; then
+				chmod 600 "$private_key" || :
+				("${add_new[@]}" "$private_key") || :
+			fi
+		done
 
-	# add known keys to keychain and agent
-	("${ssh_add_known[@]}") || :
-}
-
-# permissions
-function act_permissions {
-	# create .ssh config file if necessary
-	mkdir -p "$HOME/.ssh"
-	if test ! -f "$HOME/.ssh/config"; then
-		touch "$HOME/.ssh/config"
-	fi
-
-	# ensure correct permissions
-	fs-own --changes --directory-permissions='700' --file-permissions='600' -- "$HOME/.ssh"
-}
-
-function act_test {
-	local uri ec
-
-	# options
-	uri="$(
-		ask --required \
-			--question='Which SSH URI to test the connection to?' \
-			--default="${1:-"git@github.com"}"
-	)"
-
-	# test and fetch exit code
-	ec=0 && silent ssh -qT "$uri" || ec="$?"
-
-	# 0 no error
-	# 1 success but error - this is what github does, as is not a real ssh terminal
-	# 255 configuration error - this is what we are after
-	test "$ec" -le 1
-}
-
-function act_connect {
-	local ec
-
-	# act
-	(ssh "$@") || {
-		ec="$?" # 130 is ssh open then closed
-		if test "$ec" -ne 130; then
-			stderr echo "failed with $ec will try again in 10 seconds..."
-			sleep 5
-			act_connect "$@"
-		fi
+		# add known keys to keychain and agent
+		("${add_known[@]}") || :
 	}
-}
 
-# =====================================
-# Act
+	# permissions
+	function ssh_permissions {
+		# create .ssh config file if necessary
+		mkdir -p "$HOME/.ssh"
+		if test ! -f "$HOME/.ssh/config"; then
+			touch "$HOME/.ssh/config"
+		fi
 
-if test "$(type -t "act_$action")" = 'function'; then
-	"act_$action" "${action_args[@]}"
-	exit "$?"
-else
-	echo-style --error="Action [$action] not yet implemented." >/dev/stderr
-	exit 78 # Function not implemented
+		# ensure correct permissions
+		fs-own --changes --directory-permissions='700' --file-permissions='600' -- "$HOME/.ssh"
+	}
+
+	function ssh_test {
+		local uri="${1-}" ec
+
+		# ensure
+		if test -z "$uri"; then
+			uri="$(
+				ask --required \
+					--question='Which SSH URI to test the connection to?' \
+					--default="git@github.com"
+			)"
+		fi
+
+		# test and fetch exit code
+		ec=0 && silent ssh -qT "$uri" || ec="$?"
+
+		# 0 no error
+		# 1 success but error - this is what github does, as is not a real ssh terminal
+		# 255 configuration error - this is what we are after
+		test "$ec" -le 1
+	}
+
+	function ssh_connect {
+		local ec
+		(ssh "$@") || {
+			ec="$?" # 130 is ssh open then closed
+			if test "$ec" -ne 130; then
+				echo-style --notice="Failed with exit code [$ec], will try again in 10 seconds..." >/dev/stderr
+				sleep 5
+				ssh_connect "$@"
+			fi
+		}
+	}
+
+	# =====================================
+	# Act
+
+	if test "$(type -t "ssh_$action")" = 'function'; then
+		"ssh_$action" "${args[@]}"
+		return "$?"
+	else
+		echo-style --error="Action [$action] not yet implemented." >/dev/stderr
+		return 78 # Function not implemented
+	fi
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	ssh-helper "$@"
 fi
diff --git a/commands/svg-export b/commands/svg-export
--- a/commands/svg-export
+++ b/commands/svg-export
@@ -1,125 +1,134 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
-source "$(which eval-collapse)"
 
-# =====================================
-# Dependencies
+function svg-export() (
+	local formats=(
+		png
+		pdf
+		svg
+		eps
+		ps
+	)
 
-# https://github.com/sharkdp/bat
-# cat alternative
+	# =====================================
+	# Arguments
 
-env CLI='cairosvg' \
-	PIP='cairosvg' \
-	setup-util pip
+	# help
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Convert SVGs into PNGs.
 
-# =====================================
-# Arguments
+			USAGE:
+			svg-export [...options] -- <..inputs>
 
-# prepare
-formats=(
-	png
-	pdf
-	svg
-	eps
-	ps
-)
+			OPTIONS:
+			--dpi=<dpi>
+			    Set the display pixels per inch, e.g. [150].
 
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Convert SVGs into PNGs.
+			--scale=<scale>
+			    Set the scale factor, e.g. [2] for 2x.
 
-		USAGE:
-		svg-export [--dpi=...] [--scale=...] [--background=...] [--format=...] -- *.svg
+			--background=<background-color>
+			    Set the background color, defaults to [white].
+			    To keep transparency, use [--background=].
 
-		QUIRKS:
-		Background defaults to [white], to keep transparency, use [--background=].
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
+			--format=$(
+				echo-join '|' -- "${formats[@]}"
+			)]
+
+			EXAMPLE:
+			svg-export -- *.svg
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item files=() dpi='' scale='' background='white' format=''
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--dpi='*) dpi="${item:6}" ;;
+		'--scale='*) scale="${item:8}" ;;
+		'--bg='*) background="${item:5}" ;;
+		'--background='*) background="${item:13}" ;;
+		'--format='*) format="${item:9}" ;;
+		'--')
+			files+=("$@")
+			shift $#
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) help "An unrecognised argument was provided: $item" ;;
+		esac
+	done
+
+	# if no files, fail
+	if test "${#files[@]}" -eq 0; then
+		help "No files were provided."
 	fi
-	return 22 # Invalid argument
-}
 
-# process
-files=()
-dpi=''
-scale=''
-background='white'
-format=''
-while test "$#" -ne 0; do
-	item="$1"
-	shift
-	case "$item" in
-	'help' | '--help' | '-h') help ;;
-	'--dpi='*) dpi="${item:6}" ;;
-	'--scale='*) scale="${item:8}" ;;
-	'--bg='*) background="${item:5}" ;;
-	'--background='*) background="${item:13}" ;;
-	'--format='*) format="${item:9}" ;;
-	'--')
-		files+=("$@")
-		shift $#
-		break
-		;;
-	'--'*) help "An unrecognised flag was provided: $item" ;;
-	*) help "An unrecognised argument was provided: $item" ;;
-	esac
-done
+	# ensure correct format
+	format="$(
+		choose-option --required \
+			--question='Which format to export to?' \
+			--filter="$format" -- "${formats[@]}"
+	)"
 
-# if no files, fail
-if test "${#files[@]}" -eq 0; then
-	help "No files were provided."
-fi
+	# =====================================
+	# Dependencies
 
-# ensure correct format
-format="$(
-	choose-option --required \
-		--question='Which format to export to?' \
-		--filter="$format" -- "${formats[@]}"
-)"
+	# https://github.com/sharkdp/bat
+	# cat alternative
 
-# =====================================
-# Act
+	env CLI='cairosvg' \
+		PIP='cairosvg' \
+		setup-util pip
 
-# adjustments
-suffix=''
-args=(
-	--format "$format"
-)
-if test -n "$scale"; then
-	suffix+=" [scale=$scale]"
-	args+=(--scale "$scale")
-fi
-if test -n "$dpi"; then
-	suffix+=" [dpi=$dpi]"
-	args+=(--dpi "$dpi")
-fi
-if test -n "$background"; then
-	suffix+=" [bg=$background]"
-	args+=(--background "$background")
-fi
-suffix+=".$format"
+	# =====================================
+	# Act
 
-# helper
-function convert {
+	# adjustments
+	local suffix='' args=(
+		--format "$format"
+	)
+	if test -n "$scale"; then
+		suffix+=" [scale=$scale]"
+		args+=(--scale "$scale")
+	fi
+	if test -n "$dpi"; then
+		suffix+=" [dpi=$dpi]"
+		args+=(--dpi "$dpi")
+	fi
+	if test -n "$background"; then
+		suffix+=" [bg=$background]"
+		args+=(--background "$background")
+	fi
+	suffix+=".$format"
+
+	# convert
 	local input output
-	input="$1"
-	output="$(fs-filename "$input")$suffix"
+	for input in "${files[@]}"; do
+		output="$(fs-filename "$input")$suffix"
 
-	eval_collapse \
-		--pending="$(echo-style --bold="Converting " --code="$input" --bold=" to " --code="$output")" \
-		--success="$(echo-style --bold+green="Converted " --code="$input" --bold=" to " --code="$output")" \
-		--failure="$(echo-style --bold+red="Failed to convert " --code="$input" --bold=" to " --code="$output")" \
-		-- cairosvg "${args[@]}" --output "$output" "$input" || :
+		eval-collapse \
+			--pending="$(echo-style --bold="Converting " --code="$input" --bold=" to " --code="$output")" \
+			--success="$(echo-style --bold+green="Converted " --code="$input" --bold=" to " --code="$output")" \
+			--failure="$(echo-style --bold+red="Failed to convert " --code="$input" --bold=" to " --code="$output")" \
+			-- cairosvg "${args[@]}" --output "$output" "$input" || :
 
-	# svg2png doesn't work well
-	# https://github.com/domenic/svg2png
-	# svg2png --scale="$scale" "$svg" "$png"
-}
+		# svg2png doesn't work well
+		# https://github.com/domenic/svg2png
+		# svg2png --scale="$scale" "$input" "$output"
+	done
+)
 
-# convert a specific set of file(s)
-for file in "${files[@]}"; do
-	convert "$file"
-done
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	svg-export "$@"
+fi
