`alias-*`: redo with modern dorothy conventions

diff --git a/commands/alias-details b/commands/alias-details
--- a/commands/alias-details
+++ b/commands/alias-details
@@ -1,11 +1,26 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# Alias
-src=$(alias-verify "$1")
-out=$(alias-path "$1")
-if is-file "$out"; then
-	echo "$src -> $out"
-else
-	echo "$src -> $out <- missing"
+# inputs
+path="$(ask --question="Enter path of the macOS alias file that you want the details for." --default="${1-}" --required)"
+
+# verify
+src="$(alias-verify "$path" || :)"
+if test -z "$src"; then
+	stderr echo-color --bold+red="$path" ' ' --error='← not an alias'
+	exit 1
 fi
+
+# target
+target="$(alias-target "$path" || :)"
+if test -z "$target"; then
+	stderr echo-color --bold="$src" --dim=' → ' --bold+red="$target" ' ' --error='← target broken'
+	exit 1
+fi
+if test ! -e "$target"; then
+	stderr echo-color --bold="$src" --dim=' → ' --bold+red="$target" ' ' --error='← target missing'
+	exit 1
+fi
+
+# success
+echo-color --bold="$src" --dim=' -> ' --bold+green="$target"
diff --git a/commands/alias-to-symlink b/commands/alias-to-symlink
--- a/commands/alias-to-symlink
+++ b/commands/alias-to-symlink
@@ -1,20 +1,32 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# Alias to Symlink
-src="$(alias-verify "$1")"
-if is-empty-string "$src"; then
-	echo "skipped $1"
-else
-	out="$(alias-path "$1")"
+# inputs
+path="$(ask --question="Enter the path of the macOS alias file that you want converted into a symlink." --default="${1-}" --required)"
 
-	if is-file "$out"; then
-		ln -nfs "$out" "$src"
-		echo "converted $1 -> $out"
-	elif is-dir "$out"; then
-		ln -nfs "$out" "$src"
-		echo "converted $1 -> $out"
-	else
-		echo "missing $1 -> $out"
-	fi
+# verify alias
+src="$(alias-verify "$path" || :)"
+if test -z "$src"; then
+	stderr echo-color --bold+red="$path" ' ' --error='<- not an alias'
+	exit 1
+fi
+
+# verify target
+target="$(alias-target "$path" || :)"
+if test -z "$target"; then
+	stderr echo-color --bold="$src" --dim=' → ' --bold+red="$target" ' ' --error='← target broken'
+	exit 1
+fi
+if test ! -e "$target"; then
+	stderr echo-color --bold="$src" --dim=' → ' --bold+red="$target" ' ' --error='← target missing'
+	exit 1
+fi
+
+# convert
+if test -f "$target"; then
+	ln -nfs "$target" "$src"
+	echo "converted $path -> $target"
+elif test -d "$target"; then
+	ln -nfs "$target" "$src"
+	echo "converted $path -> $target"
 fi
