`fs-parent` => `fs-dirname`, impove `alias-helper`
`alias-helper` `verify` and `target` actions work as expected

diff --git a/commands/alias-helper b/commands/alias-helper
--- a/commands/alias-helper
+++ b/commands/alias-helper
@@ -61,9 +61,9 @@ function alias-helper() (
 	# =====================================
 	# Actions
 
-	function alias_verify {
+	function get_alias_origin {
 		local path="$1"
-		silent-stderr osascript <<-EOF
+		osascript <<-EOF
 			tell application "Finder"
 				set theItem to (POSIX file "$path") as alias
 				if the kind of theItem is "alias" then
@@ -73,7 +73,7 @@ function alias-helper() (
 		EOF
 	}
 
-	function alias_target {
+	function get_alias_target {
 		local path="$1"
 		silent-stderr osascript <<-EOF
 			tell application "Finder"
@@ -85,12 +85,46 @@ function alias-helper() (
 		EOF
 	}
 
-	function alias_info {
-		local path="$1" src target
+	function do_verify {
+		local path="$1" alias
+		if test -L "$path"; then
+			echo-style --bold+red="$path" ' ' --error='<- origin is a symlink not an alias' >/dev/stderr
+			return 22 # EINVAL Invalid argument
+		elif test -e "$path"; then
+			alias="$(get_alias_origin "$path" || :)"
+			if test -n "$alias"; then
+				# don't output anything, we are just verifying
+				return 0
+			else
+				echo-style --bold+red="$path" ' ' --error='<- origin is not an alias' >/dev/stderr
+				return 22 # EINVAL Invalid argument
+			fi
+		else
+			echo-style --bold+red="$path" ' ' --error='<- origin does not exist' >/dev/stderr
+			return 22 # EINVAL Invalid argument
+		fi
+	}
+
+	function do_target {
+		local path="$1" target
+		if do_verify "$path"; then
+			target="$(get_alias_target "$path" || :)"
+			if test -n "$target"; then
+				echo "$target" # output the target from the origin
+				return 0
+			else
+				echo-style --bold+red="$path" ' ' --error='<- alias target is broken' >/dev/stderr
+				return 22 # EINVAL Invalid argument
+			fi
+		fi
+	}
+
+	function do_info {
+		local path="$1" origin target
 
 		# verify
-		src="$(alias_verify "$path" || :)"
-		if test -z "$src"; then
+		origin="$(get_alias_origin "$path" || :)"
+		if test -z "$origin"; then
 			{
 				echo-style \
 					--bold+red="$path" \
@@ -101,11 +135,11 @@ function alias-helper() (
 		fi
 
 		# target
-		target="$(aliastarget "$path" || :)"
+		target="$(get_alias_target "$path" || :)"
 		if test -z "$target"; then
 			{
-				stderr echo-style \
-					--bold="$src" \
+				echo-style \
+					--bold="$origin" \
 					$'\t' \
 					$'\t' --error='← target broken'
 				return 9 # EBADF Bad file descriptor
@@ -113,8 +147,8 @@ function alias-helper() (
 		fi
 		if test ! -e "$target"; then
 			{
-				stderr echo-style \
-					--bold="$src" \
+				echo-style \
+					--bold="$origin" \
 					--nocolor=$'\t' --color+dim=$'\t→\t' --bold+red="$target" \
 					$'\t' --error='← target missing'
 				return 2 # ENOENT No such file or directory
@@ -123,15 +157,15 @@ function alias-helper() (
 
 		# success
 		echo-style \
-			--bold="$src" \
+			--bold="$origin" \
 			--nocolor=$'\t' --color+dim=$'\t→\t' --bold+green="$target"
 	}
 
-	function alias_new {
+	function do_new {
 		local path="$1" target="$2" type target_absolute path_absolute path_directory path_filename
 		target_absolute="$(fs-absolute "$target")"
 		path_absolute="$(fs-absolute "$path")"
-		path_directory="$(dirname "$path_absolute")"
+		path_directory="$(fs-dirname "$path_absolute")"
 		path_filename="$(basename "$path_absolute")"
 
 		# act
@@ -162,12 +196,12 @@ function alias-helper() (
 		#chmod --reference="$targetPath" "$path_absolute"
 	}
 
-	function alias_symlink {
-		local path="$1" src target
+	function do_symlink {
+		local path="$1" origin target
 
 		# verify alias
-		src="$(alias_verify "$path" || :)"
-		if test -z "$src"; then
+		origin="$(get_alias_origin "$path" || :)"
+		if test -z "$origin"; then
 			{
 				echo-style --bold+red="$path" ' ' --error='<- not an alias'
 				return 22 # EINVAL Invalid argument
@@ -175,26 +209,26 @@ function alias-helper() (
 		fi
 
 		# verify target
-		target="$(alias_target "$path" || :)"
+		target="$(get_alias_target "$path" || :)"
 		if test -z "$target"; then
 			{
-				echo-style --bold="$src" --dim=' → ' --bold+red="$target" ' ' --error='← target broken'
+				echo-style --bold="$origin" --dim=' → ' --bold+red="$target" ' ' --error='← target broken'
 				return 9 # EBADF Bad file descriptor
 			} >/dev/stderr
 		fi
 		if test ! -e "$target"; then
 			{
-				echo-style --bold="$src" --dim=' → ' --bold+red="$target" ' ' --error='← target missing'
+				echo-style --bold="$origin" --dim=' → ' --bold+red="$target" ' ' --error='← target missing'
 				return 2 # ENOENT No such file or directory
 			} >/dev/stderr
 		fi
 
 		# convert
 		if test -f "$target"; then
-			ln -nfs "$target" "$src"
+			ln -nfs "$target" "$origin"
 			echo "converted $path -> $target"
 		elif test -d "$target"; then
-			ln -nfs "$target" "$src"
+			ln -nfs "$target" "$origin"
 			echo "converted $path -> $target"
 		fi
 	}
@@ -202,8 +236,8 @@ function alias-helper() (
 	# =====================================
 	# Act
 
-	if test "$(type -t "alias_$action")" = 'function'; then
-		"alias_$action" "${args[@]}"
+	if test "$(type -t "do_$action")" = 'function'; then
+		"do_$action" "${args[@]}"
 		return "$?"
 	else
 		echo-style --error="Action [$action] not yet implemented." >/dev/stderr
