ensure errors are written to stderr

diff --git a/commands/alias-helper b/commands/alias-helper
--- a/commands/alias-helper
+++ b/commands/alias-helper
@@ -176,10 +176,8 @@ function alias_helper() (
 		elif test -f "$target_absolute"; then
 			type="file"
 		else
-			{
-				echo-style --error='Invalid path or unsupported type:' ' ' --code="$path"
-				return 22 # EINVAL 22 Invalid argument
-			} >/dev/stderr
+			echo-error 'Invalid path or unsupported type:' ' ' --code="$path"
+			return 22 # EINVAL 22 Invalid argument
 		fi
 
 		if test -f "$path_absolute"; then
@@ -241,7 +239,7 @@ function alias_helper() (
 	if test "$(type -t "do_$action")" = 'function'; then
 		"do_$action" "${args[@]}"
 	else
-		echo-style --error="Action [$action] not yet implemented." >/dev/stderr
+		help "<action> unsupported or yet implemented: $action" || :
 		return 78 # ENOSYS 78 Function not implemented
 	fi
 )
diff --git a/commands/btrfs-helper b/commands/btrfs-helper
--- a/commands/btrfs-helper
+++ b/commands/btrfs-helper
@@ -242,11 +242,11 @@ function btrfs_helper() (
 
 		# validate
 		if test "$existing_node" = "$extra_node"; then
-			echo-style --error='You cannot add the same device to itself.'
+			echo-style --error='You cannot add the same device to itself.' >/dev/stderr
 			return 22 # EINVAL 22 Invalid argument
 		fi
 		if test "$existing_uuid" = "$extra_uuid"; then
-			echo-style --error='The device is already part of the intended filesystem.'
+			echo-style --error='The device is already part of the intended filesystem.' >/dev/stderr
 			return 22 # EINVAL 22 Invalid argument
 		fi
 
@@ -371,7 +371,7 @@ function btrfs_helper() (
 	elif test "$(type -t "act_$action")" = 'function'; then
 		"act_$action" "${args[@]}"
 	else
-		echo-error "$0: Action not yet implemented: $action"
+		help "<action> unsupported or yet implemented: $action" || :
 		return 78 # ENOSYS 78 Function not implemented
 	fi
 )
diff --git a/commands/ssh-helper b/commands/ssh-helper
--- a/commands/ssh-helper
+++ b/commands/ssh-helper
@@ -167,7 +167,7 @@ function ssh_helper() (
 
 		if test "$SSH_IDENTITY_AGENT" = '1password'; then
 			if ! sock_exists "$op_sock"; then
-				echo-error "$0: Invalid state: invalid sock: $op_sock"
+				echo-error "Invalid SSH Socket: $op_sock"
 				return 1
 			fi
 			SSH_IDENTITY_AGENT="$op_sock"
@@ -437,7 +437,7 @@ function ssh_helper() (
 	if test "$(type -t "ssh_$action")" = 'function'; then
 		"ssh_$action" "${args[@]}"
 	else
-		echo-error "$0: Action not yet implemented: $action"
+		help "<action> unsupported or yet implemented: $action" || :
 		return 78 # ENOSYS 78 Function not implemented
 	fi
 )
