ask/choose/confirm: complete no-TTY support
/close #253

- shellcheckrc: add `SC2059`, and add docs on all the disabled rules
- ask: rewrote for modern conventions, support no-TTY, fix read failures not being output
- ask/choose/confirm: consistent commentary styling
- choose: fix blockquote line being a different color or breaking colors
- confirm: fix and improve the WIP no-TTY support, now complete
- dorothy: prompt for lint upgrade before dev deps, to speed up UX
- echo-clear-lines: rewrote to support all known edge cases
- echo-count-lines: add note that it doesn't wrap
- echo-escape-command: use new `__quote` helped in `bash.bash` to support ANSI Escape Codes
- echo-quote: add tests, add support for `--single` and `--double` arguments
- echo-regexp(.ts)?: better support for character classes, supporting `[[:XXX:]]` and `[:XXX:]` forms
- echo-revolving-door: rewrote to support all known edge cases
- added `echo-substr`: as command alias for `__substr` helper in `bash.bash`
- echo-wrap: fix help errors not showing, support --column=* alias for --width=*
- eval-helper: updated for TTY changes, aand fix all known edge cases
- expand-path.zsh: same functionality, but rewrote for clarity
- setup-util: linting, and only output the output if there is output
- setup-util-bash: compact `echo-style` calls for performance, include `setup-util --check` for performance
- until-success: rewrote for new TTY conventions
- echo-escape-special: fix everything being dumped together
- is-shapeshifter: rewrote and add tests, to fix all known edge cases, and now uses `bash.bash` helpers
- bash.bash:
    - remove deprecated usage of `__print_line ...` use `__print_lines ...` instead
    - support initial `--` argument in appropriate functions
    - rewrite to use [[ ... ]] instead of test/[ to better handle edge cases
- stdinargs.bash:
    - rewrite to use [[ ... ]] instead of test/[ to better handle edge cases, such as a trailing line containing only `>`
- zsh.zsh:
    - consistency with `bash.bash` changes
    - rewrote and fixed `__substr` helper for edge cases
    - added `is_shapeshifter` and `__escape_shapeshifting` helpers, used in `is-shapeshifter`
- ansi-escape-codes.md: removed excess docs

todos:

- decide if ask/choose/confirm linger should be outputted to stderr if there is commentary and a sucess code but no linger, check if consistent with choose
- setup-util: consider new wrapper for the font selection too

diff --git a/commands/ask b/commands/ask
--- a/commands/ask
+++ b/commands/ask
@@ -190,11 +190,6 @@ function ask_() (
 		question_body=''
 	fi
 
-	# enforce question if lingering
-	if test "$option_linger" = 'yes' -a -z "$question_title"; then
-		help 'A <question> is required when using --linger'
-	fi
-
 	# =====================================
 	# Styles
 
@@ -205,16 +200,17 @@ function ask_() (
 	load_dorothy_config 'styles.bash'
 
 	# refresh the styles
-	refresh_style_cache -- 'question_title_prompt' 'question_title_result' 'question_body' 'input_warning' 'input_error' 'icon_prompt' 'result_value' 'icon_nothing_provided' 'icon_using_password' 'blockquote'
+	refresh_style_cache -- 'question_title_prompt' 'question_title_result' 'question_body' 'input_warning' 'input_error' 'icon_prompt' 'result_line' 'empty_line' 'commentary_nothing_provided' 'commentary_using_password' 'indent_blockquote' 'commentary_timeout_default' 'commentary_timeout_required' 'commentary_timeout_optional' 'commentary_input_failure' 'result_commentary_spacer' 'key' 'code'
 
 	# style the question
-	local question_title_prompt='' question_title_result='' question_body_prompt=''
+	local question_title_and_body_and_newline='' question_title_result=''
 	if test -n "$question_title"; then
-		question_title_prompt="${style__question_title_prompt}${question_title}${style__end__question_title_prompt}"
+		if test -n "$question_body"; then
+			question_title_and_body_and_newline="${style__question_title_prompt}${question_title}${style__end__question_title_prompt}"$'\n'"${style__question_body}${question_body}${style__end__question_body}"$'\n'
+		else
+			question_title_and_body_and_newline="${style__question_title_prompt}${question_title}${style__end__question_title_prompt}"$'\n'
+		fi
 		question_title_result="${style__question_title_result}${question_title}${style__end__question_title_result}"
-	fi
-	if test -n "$question_body"; then
-		question_body_prompt="${style__question_body}${question_body}${style__end__question_body}"
 	fi
 
 	# =====================================
@@ -228,6 +224,14 @@ function ask_() (
 		option_timeout=60
 	fi
 
+	# adjust read args based on timeout
+	local read_args=('-r')
+	if test -n "$option_timeout"; then
+		read_args+=(
+			-t "$option_timeout"
+		)
+	fi
+
 	# adjust tty
 	local terminal_device_file is_interactive='yes'
 	terminal_device_file="$(get-terminal-device-file)"
@@ -236,44 +240,39 @@ function ask_() (
 		is_interactive='no'
 	fi
 
+	# adjust prompt
+	local input_prompt_and_newline=''
+	if test "$is_interactive" = 'no' -a -n "$option_default"; then
+		input_prompt_and_newline="Press ${style__key}ENTER${style__end__key} to use the default value of ${style__code}${option_default}${style__end__code}. Press ${style__key}ESC${style__end__key} then ${style__key}ENTER${style__end__key} to use no value."$'\n'
+	fi
+
 	# helpers
 	local ASKED='no' commentary=''
 	function on_timeout {
 		if is-value -- "$RESULT"; then
-			commentary="${style__input_warning}[timed out: using fallback]${style__end__input_warning}"
+			# default
+			commentary="${style__result_commentary_spacer}${style__commentary_timeout_default}"
 			return 0
 		elif test "$option_required" = 'no'; then
-			commentary="${style__input_warning}[timed out: optional]${style__end__input_warning}"
+			# optional
+			commentary="${style__result_commentary_spacer}${style__commentary_timeout_optional}"
 			return 0
 		else
-			commentary="${style__input_error}[input failure: timed out: required]${style__end__input_error}"
+			# required
+			commentary="${style__result_commentary_spacer}${style__commentary_timeout_required}"
 			return 60 # ETIMEDOUT 60 Operation timed out
 		fi
 	}
 	function do_prompt { # has sideffects: RESULT, ASKED
-		local input_prompt='' __read_status __input_result result_prompt result_prompt_row_count clear='' p='' read_args=('-r')
-		if test -n "$option_timeout"; then
-			read_args+=(
-				-t "$option_timeout"
-			)
-		fi
-
-		if test -n "$question_title_prompt"; then
-			input_prompt+="$question_title_prompt"$'\n'
-		fi
-		if test -n "$question_body_prompt"; then
-			input_prompt+="$question_body_prompt"$'\n'
-		fi
-		input_prompt+="$style__icon_prompt"
+		local __read_status __input_result read_prompt="${question_title_and_body_and_newline}${input_prompt_and_newline}${style__icon_prompt}" read_prompt_lines=0 result_prompt result_prompt_lines=0 clear=''
+		read_prompt_lines="$(echo-clear-lines --count-only --here-string <<<"$read_prompt")"
 
 		ASKED='yes' # not local
 		while true; do
 			# reset
 			__read_status=0
 			__input_result=''
-			result_prompt="$input_prompt"
-			p="${clear}${result_prompt}"
-			clear=''
+			result_prompt=''
 
 			# adapt according to read mode
 			if test "$is_interactive" = 'no'; then
@@ -281,47 +280,51 @@ function ask_() (
 				# [-p <prompt>] is discarded, no prompt is shown
 				# [-i <default>] is discarded, no default value is handled
 				# as such, do not pass such to read, do the prompt and handling of the default value ourself
-				__print_string "$p" >"$terminal_device_file"
+				__print_string "${clear}${read_prompt}" >"$terminal_device_file"
 				# trunk-ignore(shellcheck/SC2162)
 				IFS='' read "${read_args[@]}" __input_result || __read_status=$?
 				if test "$__read_status" -eq 0; then
-					# the user has pressed enter, so trim it
-					result_prompt+="$RESULT"$'\n'
-
+					# process the input result to the actual RESULT
 					if test -z "$__input_result" -o "$__input_result" = $'\n'; then
 						# treat empty string and newline as default
 						:
-					elif [[ $__input_result =~ ^[\s]*$ ]]; then
-						# treat only whitespace as empty value
+					elif [[ $__input_result =~ ^[[:cntrl:][:space:]]*$ ]]; then
+						# if it is only control characters, e.g. escape, and whitespace characters, then treat as empty
 						RESULT=''
 					else
 						# treat everything else as manual __input_result
 						RESULT="$__input_result"
 					fi
+					# the user has pressed enter. which will be added to the TTY, so trim it and trim a possibly very long input
+					result_prompt+="$RESULT"$'\n'
 				fi
 			else
 				# clear and prompt
 				# -i requires -e
 				# trunk-ignore(shellcheck/SC2162)
-				IFS= read "${read_args[@]}" -ei "$RESULT" -p "$p" __input_result || __read_status=$?
+				IFS= read "${read_args[@]}" -ei "$RESULT" -p "${clear}${read_prompt}" __input_result || __read_status=$?
 
 				# update the value on successful read, and prepare the clear
 				# note if there was a default value, pressing enter will set [__input_result] to it
 				if test "$__read_status" -eq 0; then
 					# only update RESULT on successful read status, as [__input_result] will be empty on timeout
 					RESULT="$__input_result"
-					# the user has pressed enter, so note that an enter was rendered to the TTY so that it can be erased, and append a space so that it is not trimmed by "$(...)" usage
+					# the user has pressed enter. which will be added to the TTY, so trim it and trim a possibly very long input
 					result_prompt+="$RESULT"$'\n'
 				fi # otherwise it has timed out. ctrl+c is not caught as we are not trapping it
 			fi
 
-			# generate our erasure
-			result_prompt_row_count="$(echo-wrap -- "$result_prompt" | echo-count-lines --stdin)"
-			clear=$'\e['"$result_prompt_row_count"$'F\e[G\e[J'
+			# prepare the new erasure, this is done like so, because it is quicker, which is important for multiple enter presses on --required
+			# it is quicker because processing the read_prompt takes time, as it has ANSI Escape Codes, which requires invoking deno behind the scenes for more advanced detection, so we do that processing once beforehand
+			# then we do the quick result processing here and combine the two
+			result_prompt_lines="$(echo-clear-lines --count-only --here-string <<<"$result_prompt")"
+			clear="$(echo-clear-lines --count="$((read_prompt_lines + result_prompt_lines))")"
+			# this is too slow: clear="$(echo-clear-lines --count-only --here-string <<<"$read_prompt$result_prompt")"
 
 			# handle the result
 			if test "$__read_status" -eq 142; then
-				return 60 # ETIMEDOUT 60 Operation timed out
+				__read_status=60 # ETIMEDOUT 60 Operation timed out
+				break
 			fi
 			if is-value -- "$RESULT"; then
 				# we have a value, proceed
@@ -341,6 +344,9 @@ function ask_() (
 			__print_string "$clear" >"$terminal_device_file"
 		fi
 		# done
+		if test "$__read_status" -ne 0; then
+			return "$__read_status"
+		fi
 		do_validate
 	}
 	function do_validate {
@@ -390,7 +396,7 @@ function ask_() (
 				on_timeout
 				return
 			elif test "$choose_status" -ne 0; then
-				commentary="${style__input_error}[input failure: choose failure: $choose_status]${style__end__input_error}"
+				commentary="${style__result_commentary_spacer}$(printf "$style__commentary_input_failure" "choose failure: $choose_status")"
 				return "$choose_status"
 			fi
 
@@ -406,7 +412,7 @@ function ask_() (
 				return 0
 			else
 				# unknown error
-				commentary="${style__input_error}[input failure: invalid choice: $choice]${style__end__input_error}"
+				commentary="${style__result_commentary_spacer}$(printf "$style__commentary_input_failure" "invalid choice: $choice")"
 				return 14 # EFAULT 14 Bad address
 			fi
 		fi
@@ -427,50 +433,34 @@ function ask_() (
 
 	# act
 	eval_capture --statusvar=result_status -- do_validate
-	local render="$question_title_result"
-	if test -n "$commentary"; then
-		if test -n "$render"; then
-			render+=" $commentary"
-		else
-			render="$commentary"
-		fi
-	fi
-	if test -n "$render"; then
-		render+=$'\n'
-	fi
+	local render="$question_title_result$commentary"
 	if test "$result_status" -eq 0; then
-		# add the results only if lingering
+		# success response
+		# inform if requested
 		if test "$option_linger" = 'yes'; then
-			local content
+			local result
 			if test -z "$RESULT"; then
-				content="$style__icon_nothing_provided"
+				result="${style__commentary_nothing_provided}"
 			elif test "$option_password" = 'yes'; then
-				content="$style__icon_using_password"
+				result="${style__commentary_using_password}"
 			else
-				content="$RESULT"
+				result="${RESULT//$'\n'/$'\n'"${style__indent_blockquote}"}" # add the necessary indentation
+				result="${style__result_line}${style__indent_blockquote}${result}${style__end__result_line}"
 			fi
-			content="${content//$'\n'/$'\n'"${style__blockquote}"}" # add the necessary indentation
-			render+="${style__result_value}${style__blockquote}${content}${style__end__result_value}"$'\n'
-			# inform
+			render+=$'\n'"$result"$'\n'
 			__print_string "$render" >"$terminal_device_file"
-		elif test -n "$commentary"; then
-			# inform to stderr, consistent with ask, choose, confirm
-			__print_string "$render" >/dev/stderr
 		fi
 		# stdout
-		if test -z "$RESULT"; then
-			__print_string "$RESULT" # empty string
-		else
-			__print_lines "$RESULT"
+		if test -n "$RESULT"; then
+			__print_lines "$RESULT" # stdout, so use __print_lines
 		fi
 	else
-		# inform
-		if test -n "$commentary"; then
-			if test "$option_linger" = 'yes'; then
-				__print_string "$render" >"$terminal_device_file"
-			else
-				__print_string "$render" >/dev/stderr
-			fi
+		# failure response
+		# always inform
+		if test "$option_linger" = 'yes'; then
+			__print_string "$render" >"$terminal_device_file"
+		else
+			__print_string "$render" >/dev/stderr
 		fi
 		return "$result_status"
 	fi
