*: fix false linting on status variables
rename them to no longer require the `__` prefix for safety functions

diff --git a/commands/ask b/commands/ask
--- a/commands/ask
+++ b/commands/ask
@@ -284,16 +284,16 @@ function ask_() (
 
 		ASKED='yes' # not local
 		local result_prompt result_prompt_lines
-		local -i __read_status
+		local -i read_status
 		while :; do
 			# reset
-			__read_status=0
+			read_status=0
 			READ_RESULT=''
 
 			# adapt according to read mode
 			if [[ $inline == 'no' ]]; then
-				__read || __read_status=$?
-				if [[ $__read_status -eq 0 ]]; then
+				__read || read_status=$?
+				if [[ $read_status -eq 0 ]]; then
 					# process the input result to the actual RESULT
 					if [[ -z $READ_RESULT || $READ_RESULT == $'\n' ]]; then
 						# treat empty string and newline as default
@@ -309,11 +309,11 @@ function ask_() (
 				fi
 			else
 				result_prompt=''
-				__read || __read_status=$?
+				__read || read_status=$?
 
 				# update the value on successful read, and prepare the clear
 				# note if there was a default value, pressing enter will set `READ_RESULT` to it
-				if [[ $__read_status -eq 0 ]]; then
+				if [[ $read_status -eq 0 ]]; then
 					# only update RESULT on successful read status, as `READ_RESULT` will be empty on timeout
 					RESULT="$READ_RESULT"
 					# the user has pressed enter. which will be added to the TTY, so trim it and trim a possibly very long input
@@ -329,8 +329,8 @@ function ask_() (
 			fi
 
 			# handle the result
-			if [[ $__read_status -eq 142 ]]; then
-				__read_status=60 # ETIMEDOUT 60 Operation timed out
+			if [[ $read_status -eq 142 ]]; then
+				read_status=60 # ETIMEDOUT 60 Operation timed out
 				break
 			fi
 			if is-value -- "$RESULT"; then
@@ -354,8 +354,8 @@ function ask_() (
 			__value_to_tty "$CLEAR" || return $?
 		fi
 		# done
-		if [[ $__read_status -ne 0 ]]; then
-			return "$__read_status"
+		if [[ $read_status -ne 0 ]]; then
+			return "$read_status"
 		fi
 		do_validate
 	}
@@ -389,14 +389,14 @@ function ask_() (
 
 			# choose and check for failure
 			local choice
-			local -i __choose_status=0
-			choice="$(choose "${option_question[@]}" --timeout="$option_timeout" --label -- "${choices[@]}")" || __choose_status=$?
-			if [[ $__choose_status -eq 60 ]]; then
+			local -i choose_status=0
+			choice="$(choose "${option_question[@]}" --timeout="$option_timeout" --label -- "${choices[@]}")" || choose_status=$?
+			if [[ $choose_status -eq 60 ]]; then
 				on_timeout
 				return $?
-			elif [[ $__choose_status -ne 0 ]]; then
-				commentary="${STYLE__result_commentary_spacer}$(printf "$STYLE__commentary_input_failure" "choose failure: $__choose_status")"
-				return "$__choose_status"
+			elif [[ $choose_status -ne 0 ]]; then
+				commentary="${STYLE__result_commentary_spacer}$(printf "$STYLE__commentary_input_failure" "choose failure: $choose_status")"
+				return "$choose_status"
 			fi
 
 			# process the confirmation
diff --git a/commands/choose b/commands/choose
--- a/commands/choose
+++ b/commands/choose
@@ -2150,7 +2150,7 @@ function choose_() (
 	}
 	function handle_menu {
 		local input keys skips
-		local -i __read_status
+		local -i read_status
 		# action
 		reset_terminal_modifications_on_exit
 		__value_to_tty "$STYLE__alternative_screen_buffer"
@@ -2162,9 +2162,9 @@ function choose_() (
 			menu_skip_render='no'
 
 			# handle the response
-			__read_status=0
-			input="$(__read_key --timeout="$option_timeout")" || __read_status=$?
-			if [[ $__read_status -eq 60 ]]; then
+			read_status=0
+			input="$(__read_key --timeout="$option_timeout")" || read_status=$?
+			if [[ $read_status -eq 60 ]]; then
 				if [[ $selected_count -ne 0 ]]; then
 					# default
 					commentary="${STYLE__result_commentary_spacer}${STYLE__commentary_timeout_default}"
@@ -2180,19 +2180,19 @@ function choose_() (
 				else
 					# required
 					commentary="${STYLE__result_commentary_spacer}${STYLE__commentary_timeout_required}"
-					menu_status="$__read_status"
+					menu_status="$read_status"
 					set_menu_mode 'exit'
 					break
 				fi
-			elif [[ $__read_status -eq 94 ]]; then
+			elif [[ $read_status -eq 94 ]]; then
 				# unknown character, send bell and continue
 				menu_skip_render='yes'
 				__value_to_tty "$STYLE__bell"
 				continue
-			elif [[ $__read_status -ne 0 ]]; then
+			elif [[ $read_status -ne 0 ]]; then
 				# failure
-				commentary="${STYLE__result_commentary_spacer}$(printf "$STYLE__commentary_input_failure" "read status: $__read_status")"
-				menu_status="$__read_status" # error causes no selection
+				commentary="${STYLE__result_commentary_spacer}$(printf "$STYLE__commentary_input_failure" "read status: $read_status")"
+				menu_status="$read_status" # error causes no selection
 				set_menu_mode 'exit'
 				break
 			elif [[ $terminal_too_short != 'no' ]]; then
diff --git a/commands/setup-shell b/commands/setup-shell
--- a/commands/setup-shell
+++ b/commands/setup-shell
@@ -373,20 +373,20 @@ function setup_shell() (
 		# the alternative was `... 2> >(tee "$login_shell_temp" >&2)` however from user feedback, we want to communicate the command to the user
 		local login_shell_temp
 		login_shell_temp="$(fs-temp --directory='setup-shell' --file)"
-		local -i __login_shell_status
+		local -i login_shell_status
 		while :; do
-			__login_shell_status=0
+			login_shell_status=0
 			set -m # enable job control to not bubble SIGINT up to us
-			LC_ALL=C eval-helper --wrap --copy-stderr="$login_shell_temp" -- "${LOGIN_SHELL_COMMAND[@]}" || __login_shell_status=$?
+			LC_ALL=C eval-helper --wrap --copy-stderr="$login_shell_temp" -- "${LOGIN_SHELL_COMMAND[@]}" || login_shell_status=$?
 			set +m
 			if grep --fixed-strings --regexp="$LOGIN_SHELL_UNCHANGED" <"$login_shell_temp"; then
 				# already configured
 				__print_style --success='Your login shell is already ' --path="$LOGIN_SHELL_PATH" || return $?
-			elif [[ $__login_shell_status -eq 0 ]]; then
+			elif [[ $login_shell_status -eq 0 ]]; then
 				# successfully updated
 				__print_style --success='Your login shell is now ' --path="$LOGIN_SHELL_PATH" || return $?
 				break
-			elif [[ $__login_shell_status -eq 1 ]]; then
+			elif [[ $login_shell_status -eq 1 ]]; then
 				# incorrect password or other failure
 				# just try again rather than do another prompt
 				# if grep --fixed-strings --regexp='Authentication failure' <"$chsh_temp"; then
@@ -395,16 +395,16 @@ function setup_shell() (
 				# 	fi
 				# fi
 				continue # try again until ctrl+c abort
-			elif [[ $__login_shell_status -eq 130 ]]; then
+			elif [[ $login_shell_status -eq 130 ]]; then
 				# 130 = SIGINT = ctrl+c = abort
 				# we don't want o fail on abort, just skip the login shell, let them press ctrl+c again if they want to abort everything
-				# __print_error 'Updating the login shell to ' --path="$LOGIN_SHELL_PATH" ' failed because ' --code="$apply_login_shell_method" ' was aborted with exit status ' --status="$__login_shell_status" || return $?
+				# __print_error 'Updating the login shell to ' --path="$LOGIN_SHELL_PATH" ' failed because ' --code="$apply_login_shell_method" ' was aborted with exit status ' --status="$login_shell_status" || return $?
 				# return 125 # ECANCELED 125 Operation cancelled
 				break
 			else
 				# error message no longer needed due to `eval-helper --wrap``
-				# __print_error 'Updating the login shell to ' --path="$LOGIN_SHELL_PATH" ' failed because ' --code="$apply_login_shell_method" ' failed with exit status ' --status="$__login_shell_status" || return $?
-				return "$__login_shell_status"
+				# __print_error 'Updating the login shell to ' --path="$LOGIN_SHELL_PATH" ' failed because ' --code="$apply_login_shell_method" ' failed with exit status ' --status="$login_shell_status" || return $?
+				return "$login_shell_status"
 			fi
 		done
 	}
