better error handling
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/ask b/commands/ask
--- a/commands/ask
+++ b/commands/ask
@@ -18,18 +18,18 @@ result="$option_default"
 asked='no'
 function handle_timeout () {
 	if is-value "$result"; then
-		stderr echo "Timed out, using fallback value: $result"
+		stderr echo "Ask timed out, using fallback value: $result"
 		sleep 10
 		echo "$result"
 		return 0
 	elif test "$option_required" != 'yes'; then
-		stderr echo 'Timed out, as the field was optional will use no value.'
+		stderr echo 'Ask timed out, as the field was optional will use no value.'
 		sleep 10
 		return 0
 	else
-		stderr echo 'Timed out.'
+		stderr echo 'Ask timed out, with no fallback.'
 		sleep 10
-		return 1
+		return 84  # timeout (ascii char code 84 'T')
 	fi
 }
 function ask () {
@@ -39,11 +39,11 @@ function ask () {
 		echo -e "$1" > /dev/tty
 	fi
 	while true; do
-		strict_e_pause; local e="$?"
-		read "${flags[@]}" -t 300 -r -p "> " result; local ec="$?"
-		strict_e_restore "$e"
+		strict_e_pause; local eo="$?"
+		read "${flags[@]}" -t 300 -r -p "> " result
+		local ec="$?"; strict_e_restore "$eo"
 		if test "$ec" -gt 128; then
-			return 1  # timeout
+			return 84  # timeout (ascii char code 84 'T')
 		fi
 		if is-value "$result"; then
 			break
@@ -93,39 +93,43 @@ function validate () {
 	fi
 
 	# ask
-	strict_e_pause; local e="$?"
+	strict_e_pause; local eo="$?"
 	choice="$(choose-option \
 		--question="$option_question" \
 		--timeout="$option_timeout" \
 		--label \
-		-- "${choices[@]}")"; local ec="$?"
-	strict_e_restore "$e"
+		-- "${choices[@]}")"
+	local ec="$?"; strict_e_restore "$eo"
 
 	# check
 	if test "$ec" -ne 0; then
+		# timeout probably
 		handle_timeout
-		exit $?
+		exit "$?"  # exit with the above on success and failure
 	fi
 
 	# handle
 	if test "$choice" = 'existing'; then
+		# done, sucess
 		echo "$result"
 		exit
 	elif test "$choice" = 'custom'; then
 		# ask
-		strict_e_pause; local e="$?"
-		ask "$option_question"; local ec="$?"
-		strict_e_restore "$e"
+		strict_e_pause; local eo="$?"
+		ask "$option_question"
+		local ec="$?"; strict_e_restore "$eo"
 
-		# check
+		# check for failure
 		if test "$ec" -ne 0; then
-			# timeout
+			# timeout probably
 			handle_timeout
+			exit "$?"  # exit with the above on success and failure
 		fi
 
-		# done
-		exit "$ec"
+		# done, success
+		exit
 	elif test "$choice" = 'none'; then
+		# done, sucess
 		echo
 		exit
 	else
diff --git a/commands/choose-option b/commands/choose-option
--- a/commands/choose-option
+++ b/commands/choose-option
@@ -194,7 +194,8 @@ function act () {
 	if is-array-empty-or-partial "${filtered_values[@]}"; then
 		echo "Filter [$option_filter] returned no results, providing you all the results to select from." > /dev/tty
 		option_filter=''
-		act; exit $?
+		act
+		exit "$?"  # exit with the above on success and failure
 	fi
 
 	# if we have only one option, then use that
@@ -202,17 +203,17 @@ function act () {
 		send_result "${filtered_values[0]}" "${filtered_labels[0]}" "${filtered_visuals[0]}"
 	else
 		# ask
-		strict_e_pause; local e="$?"
+		strict_e_pause; local eo="$?"
 		results="$(choose-menu \
 			--question="$option_question" \
 			--multi="$option_multi" \
 			--timeout="$option_timeout" \
-			-- "${filtered_visuals[@]}")"; local ec="$?"
-		strict_e_restore "$e"
+			-- "${filtered_visuals[@]}")"
+		local ec="$?"; strict_e_restore "$eo"
 
 		# check
 		if test "$ec" -ne 0; then
-			echo "Timed out." > /dev/stderr
+			echo "Menu timed out." > /dev/stderr
 			sleep 10
 			exit 1
 		fi
@@ -228,11 +229,11 @@ function act () {
 	if test "${#values[@]}" -gt 1 -a "$option_confirm" = 'yes'; then
 		# timeout of one minute for confirms of existing values
 		confirm_value="$(echo -n "${final_results[@]}")"
-		strict_e_pause; local e="$?"
+		strict_e_pause; local eo="$?"
 		confirmed="$(choose-option --timeout=60 --question="$option_question" --label -- \
 			yes "Use: $confirm_value" \
-			no  "Select something else.")"; local ec="$?"
-		strict_e_restore "$e"
+			no  "Select something else.")"
+		local ec="$?"; strict_e_restore "$eo"
 
 		# check
 		if test "$ec" -ne 0; then
@@ -243,7 +244,8 @@ function act () {
 		# results
 		if test "$confirmed" = 'no'; then
 			option_filter=''
-			act; exit $?
+			act
+			exit "$?"  # exit with the above on success and failure
 		fi
 	fi
 
@@ -252,4 +254,5 @@ function act () {
 }
 
 # do the action
-act; exit $?
+act
+exit "$?"  # exit with the above on success and failure
diff --git a/commands/setup-mac-brew b/commands/setup-mac-brew
--- a/commands/setup-mac-brew
+++ b/commands/setup-mac-brew
@@ -27,7 +27,7 @@ source "$DOROTHY/sources/arrays.bash"
 if test "$ARRAYS" = 'no'; then
 	brew install bash
 	setup-mac-brew "$@"
-	exit "$?"
+	exit "$?"  # exit with the above on success and failure
 fi
 
 # Helpers
diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -5,10 +5,10 @@ if test "$ARRAYS" = 'no'; then
 	exit 1
 fi
 
-# if quiet, log to stderr
+# if quiet, redo but log to stderr
 if is-affirmative "${QUIET-}"; then
-	env QUIET='' stderr setup-util
-	exit $?
+	env QUIET='' setup-util > /dev/stderr
+	exit "$?"  # exit with the above on success and failure
 fi
 
 # prepare
diff --git a/commands/until-success b/commands/until-success
--- a/commands/until-success
+++ b/commands/until-success
@@ -1,8 +1,6 @@
 #!/usr/bin/env bash
-# source "$DOROTHY/sources/strict.bash"
+# no strict as we need exit codes
 
-"$@"
-while [ $? -ne 0 ]; do
-	sleep 1000
-	"$@"
+( "$@" ); while test "$?" -ne 0; do
+	sleep 1000; ( "$@" )
 done
