setup-shell: safety, bash.bash: new helpers
- `bash.bash`:
    - new performant `__string_to_variable`, `__variable_to_variable`, `__value_to_tty`, `__value_to_target`
        - improves and deprecates some of t he WIP work in 30495fcbcb60a44c53144c58e8aba85ac3ac45bb
        - these are now used within `__to` and `__print_style` and throughout, replacing a lot of simpler usages of `__to` and `__do`

- `waiter`:
    - remove custom duration handling for `echo-duration`

- `setup-shell`:
    - use safety conventions

diff --git a/commands/ask b/commands/ask
--- a/commands/ask
+++ b/commands/ask
@@ -235,13 +235,13 @@ function ask_() (
 		if [[ -n $option_timeout ]]; then
 			function __read {
 				READ_RESULT=''
-				__do --redirect-stdout=TTY -- __print_string "${CLEAR}${READ_PROMPT}" || return
+				__value_to_tty "${CLEAR}${READ_PROMPT}" || return
 				IFS= read -rt "$option_timeout" READ_RESULT || return
 			}
 		else
 			function __read {
 				READ_RESULT=''
-				__do --redirect-stdout=TTY -- __print_string "${CLEAR}${READ_PROMPT}" || return
+				__value_to_tty "${CLEAR}${READ_PROMPT}" || return
 				IFS= read -r READ_RESULT || return
 			}
 		fi
@@ -278,8 +278,6 @@ function ask_() (
 		fi
 	}
 	function do_prompt { # has side-effects: RESULT, ASKED
-		local __read_status result_prompt result_prompt_lines
-
 		# reset clear, in case a choose/confirm failed and we are re-prompting
 		if [[ $inline == 'no' ]]; then
 			CLEAR="$STYLE__alternative_screen_buffer"
@@ -288,6 +286,8 @@ function ask_() (
 		fi
 
 		ASKED='yes' # not local
+		local result_prompt result_prompt_lines
+		local -i __read_status
 		while :; do
 			# reset
 			__read_status=0
@@ -354,7 +354,7 @@ function ask_() (
 			CLEAR="$STYLE__default_screen_buffer"
 		fi
 		if [[ -n $CLEAR ]]; then
-			__do --redirect-stdout=TTY -- __print_string "$CLEAR"
+			__value_to_tty "$CLEAR" || return
 		fi
 		# done
 		if [[ $__read_status -ne 0 ]]; then
@@ -363,8 +363,6 @@ function ask_() (
 		do_validate
 	}
 	function do_validate {
-		local choose_args=() choose_status choice choices=()
-
 		# have we prompted?
 		if [[ $ASKED == 'no' ]]; then
 			# do we want to confirm the default value
@@ -381,6 +379,7 @@ function ask_() (
 			fi
 
 			# redo choices, has to be redone each time due to result
+			local choices=()
 			if [[ $option_password == 'yes' ]]; then
 				choices+=('existing' 'use the entered password')
 			else
@@ -391,22 +390,16 @@ function ask_() (
 				choices+=('none' 'use no value')
 			fi
 
-			# we want to confirm
-			choose_args+=(
-				"${option_question[@]}"
-				--timeout="$option_timeout"
-				--label -- "${choices[@]}"
-			)
-
 			# choose and check for failure
-			local choose_status=0
-			__do --redirect-status={choose_status} --redirect-stdout={choice} -- choose "${choose_args[@]}"
-			if [[ $choose_status -eq 60 ]]; then
+			local choice
+			local -i __choose_status=0
+			choice="$(choose "${option_question[@]}" --timeout="$option_timeout" --label -- "${choices[@]}")" || __choose_status=$?
+			if [[ $__choose_status -eq 60 ]]; then
 				on_timeout
 				return
-			elif [[ $choose_status -ne 0 ]]; then
-				commentary="${STYLE__result_commentary_spacer}$(printf "$STYLE__commentary_input_failure" "choose failure: $choose_status")"
-				return "$choose_status"
+			elif [[ $__choose_status -ne 0 ]]; then
+				commentary="${STYLE__result_commentary_spacer}$(printf "$STYLE__commentary_input_failure" "choose failure: $__choose_status")"
+				return "$__choose_status"
 			fi
 
 			# process the confirmation
@@ -457,19 +450,19 @@ function ask_() (
 				result="${STYLE__result_line}${STYLE__indent_blockquote}${result}${STYLE__END__result_line}"
 			fi
 			render+=$'\n'"$result"$'\n'
-			__do --redirect-stdout=TTY -- __print_string "$render"
+			__value_to_tty "$render" || return
 		fi
 		# stdout
 		if [[ -n $RESULT ]]; then
-			__print_lines "$RESULT" # stdout, so use __print_lines
+			__print_lines "$RESULT" || return # stdout, so use __print_lines
 		fi
 	else
 		# failure response
 		# always inform
 		if [[ $option_linger == 'yes' ]]; then
-			__do --redirect-stdout=TTY -- __print_string "$render"
+			__value_to_tty "$render" || return
 		else
-			__print_string "$render" >&2
+			__print_string "$render" >&2 || return
 		fi
 		return "$validate_status"
 	fi
