`ask` and `choose` use their own TTY
This enables them to isolate the context of interactivity, yet keep the parent TTY history and context from being cleared afterwards.

The TTY cursor work was not successful, as if the current row is nearing the terminal's total viewport lines, then it falls apart. As such the alternative TTY was the option.

Unfortunatey, the alternative TTY option has no way of keeping the stderr, despite efforts. As such, stderr will sleep for 10 seconds instead before the exit clears. This allows the rare error condition to be visible.

The other change this does is fix/improve `set (+|-)e` handling, as if a child did `set -e` then the return would exit the program. As such, this restores to what it was prior, which allows returns to not exit.

The next commit will trim the testing code and commentary.

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/ask b/commands/ask
--- a/commands/ask
+++ b/commands/ask
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+source "$DOROTHY/sources/tty.bash"
 source "$DOROTHY/sources/strict.bash"
 
 # options
@@ -17,25 +18,34 @@ result="$option_default"
 asked='no'
 function handle_timeout () {
 	if is-value "$result"; then
-		echo "Timed out, using fallback value: $result" > /dev/stderr
-		sleep 2
+		stderr echo "Timed out, using fallback value: $result"
+		sleep 10
 		echo "$result"
 		return 0
 	elif test "$option_required" != 'yes'; then
-		echo 'Timed out, as the field was optional will use no value.' > /dev/stderr
-		sleep 2
+		stderr echo 'Timed out, as the field was optional will use no value.'
+		sleep 10
 		return 0
 	else
-		echo 'Timed out.' > /dev/stderr
-		sleep 2
+		stderr echo 'Timed out.'
+		sleep 10
 		return 1
 	fi
 }
 function ask () {
+	#set -x
+	tty_auto
+	#tty_start
 	asked='yes'
+	if test -n "${1-}"; then
+		echo -e "$1" > /dev/tty
+	fi
 	while true; do
-		read "${flags[@]}" -t 300 -r -p "> " result
-		if test "$?" -gt 128; then
+		strict_e_pause; local e="$?"
+		read "${flags[@]}" -t 300 -r -p "> " result; local ec="$?"
+		strict_e_restore "$e"
+		if test "$ec" -gt 128; then
+			# tty_finish
 			return 1  # timeout
 		fi
 		if is-value "$result"; then
@@ -45,7 +55,7 @@ function ask () {
 			break
 		fi
 	done
-	clear > /dev/tty
+	# tty_finish
 	validate
 }
 function validate () {
@@ -87,9 +97,13 @@ function validate () {
 	fi
 
 	# ask
-	set +e # disable hard fail so we can get the exit code
-	choice="$(choose-option --question="$option_question" --timeout="$option_timeout" --label -- "${choices[@]}")"; ec="$?"
-	set -e # reenable hard fail
+	strict_e_pause; local e="$?"
+	choice="$(choose-option \
+		--question="$option_question" \
+		--timeout="$option_timeout" \
+		--label \
+		-- "${choices[@]}")"; local ec="$?"
+	strict_e_restore "$e"
 
 	# check
 	if test "$ec" -ne 0; then
@@ -102,12 +116,10 @@ function validate () {
 		echo "$result"
 		exit
 	elif test "$choice" = 'custom'; then
-		if test -n "$option_question"; then
-			echo -e "$option_question" > /dev/tty
-		fi
-
 		# ask
-		ask; ec="$?"
+		strict_e_pause; local e="$?"
+		ask "$option_question"; local ec="$?"
+		strict_e_restore "$e"
 
 		# check
 		if test "$ec" -ne 0; then
@@ -122,8 +134,8 @@ function validate () {
 		exit
 	else
 		# unknown error
-		echo "invalid choice: [$result]" > /dev/stderr
-		sleep 2
+		stderr echo "invalid choice: [$result]"
+		sleep 10
 		exit 1
 	fi
 }
diff --git a/commands/test-exit b/commands/test-exit
--- a/commands/test-exit
+++ b/commands/test-exit
@@ -12,26 +12,19 @@
 
 set -Eeuo pipefail
 
-# the below functions are essential to prevent nested functions that check for exit codes
-# from having their set -e negate a parent set +e, which would cause a return 1 on the function call
-# to cause to the program to exit immediately, as the parents set +e was negated by the child's set -e
-# as such, the below returns the state of the current e status, and restores to it
+set -x
 
-# strict_e_pause; local e="$?"
-# strict_e_resume "$e"
-
-function strict_e_pause () {
-	if [[ "$-" = *e* ]]; then
-		set +e
-		return 1
-	else
-		set +e
-		return 0
-	fi
-}
-
-function strict_e_restore () {
-	if test "$1" -eq 1; then
+function myfn () {
+	{
 		set -e
-	fi
+		read -r -t 1 asd
+		return $?
+	}
 }
+
+echo 'before'
+set +e # disable hard fail so we can get the exit code
+myfn
+ec="$?"
+set -e
+echo "after $ec"
