ask: support `--default=<value>`, close #99 (#213)
* ask: support editing the default value /ref 6357faca25eafcc47d70bf11e9d75d1bbd12e616
* ask: as read now supports defaults, redo the confirm flow /ref ddff4672561f5266cf96901b9875fc98fb28d211
* ask: use cursor rather than alt tty, implement --linger /ref 4d3e6fb48e5e0b58fb31cbc7c3431decc9de386b

diff --git a/commands/ask b/commands/ask
--- a/commands/ask
+++ b/commands/ask
@@ -101,7 +101,7 @@ function ask_() (
 	}
 
 	# process
-	local item args=() option_question='' option_default='' option_password='no' option_required='no' option_confirm='no' option_timeout=''
+	local item args=() option_question='' option_default='' option_timeout='' option_password='no' option_required='no' option_linger='no' option_confirm_default='yes' option_confirm_input='no'
 	while test "$#" -ne 0; do
 		item="$1"
 		shift
@@ -116,8 +116,14 @@ function ask_() (
 		'--no-required'* | '--required'*)
 			option_required="$(get-flag-value --affirmative --fallback="$option_required" -- "$item")"
 			;;
-		'--no-confirm'* | '--confirm'*)
-			option_confirm="$(get-flag-value --affirmative --fallback="$option_confirm" -- "$item")"
+		'--no-linger'* | '--linger'*)
+			option_linger="$(get-flag-value --affirmative --fallback="$option_linger" -- "$item")"
+			;;
+		'--no-confirm-default'* | '--confirm-default'*)
+			option_confirm_default="$(get-flag-value --affirmative --fallback="$option_confirm_default" -- "$item")"
+			;;
+		'--no-confirm-input'* | '--confirm-input'*)
+			option_confirm_input="$(get-flag-value --affirmative --fallback="$option_confirm_input" -- "$item")"
 			;;
 		'--')
 			args+=("$@")
@@ -133,46 +139,94 @@ function ask_() (
 	# Action
 
 	# prepare
-	local RESULT ASKED='no' tty_target
+	# @todo implement cursor move fallback
+	local tty_target
 	tty_target="$(is-tty --fallback)"
+
+	# adjust result
+	local RESULT
 	if test -n "$option_default"; then
 		RESULT="$option_default"
 	else
 		RESULT=''
 	fi
 
+	# adjust timeout to one minute if we have a default value, or if optional
+	if test -z "$option_timeout" && (is-value -- "$RESULT" || test "$option_required" = 'no'); then
+		option_timeout=60
+	fi
+
+	# adjust question
+	local question_render prompt
+	prompt='> '
+	question_render="$(echo-style --bold="$option_question")"
+
+	# adjust tty
+	local size_columns bin_gfold bin_gwc
+	size_columns="$(tput cols)"
+	if is-mac; then
+		bin_gfold="$(type -P 'gfold' 2>/dev/null || :)"
+		bin_gwc="$(type -P 'gwc' 2>/dev/null || :)"
+	else
+		bin_gfold="$(type -P 'fold' 2>/dev/null || :)"
+		bin_gwc="$(type -P 'wc' 2>/dev/null || :)"
+	fi
+
 	# helpers
+	local ASKED='no'
+	function send_result {
+		if test "$option_linger" = 'yes'; then
+			print_line "$question_render"$'\n'"$RESULT" >"$tty_target"
+		fi
+		print_line "$RESULT"
+	}
 	function on_timeout {
 		if is-value -- "$RESULT"; then
-			echo-style --notice="Ask timed out, using fallback value: " --code="$RESULT" >/dev/stderr
+			echo-style --notice="Ask timed out. Using the fallback value: " --code="$RESULT" >/dev/stderr
 			sleep 5
-			print_line "$RESULT"
+			send_result
 			return 0
 		elif test "$option_required" = 'no'; then
-			echo-style --notice='Ask timed out, as the field was optional will use no value.' >/dev/stderr
+			echo-style --notice='Ask timed out. Had no fallback value, this is fine as the field was optional.' >/dev/stderr
 			sleep 5
 			return 0
 		else
-			echo-style --warning='Ask timed out, with no fallback.' >/dev/stderr
+			echo-style --warning='Ask timed out. Had no fallback value... the field was required.' >/dev/stderr
 			sleep 5
 			return 60 # ETIMEDOUT 60 Operation timed out
 		fi
 	}
-	function do_ask { # has sideffects: RESULT, ASKED
-		local __read_status
-		tty_auto
+	function do_prompt { # has sideffects: RESULT, ASKED
+		local __read_status render render_rows
+
+		# tty_auto
 		ASKED='yes' # not local
-		if test -n "${1-}"; then
-			print_line "$1" >"$tty_target"
+		if test -n "$question_render"; then
+			print_line "$question_render" >"$tty_target"
 		fi
 		while true; do
-			__read_status=0 && read -r -t 300 -r -p '> ' RESULT || __read_status=$?
+			# -i requires -e
+			__read_status=0 && read -r -t 300 -ei "$RESULT" -p "$prompt" RESULT || __read_status=$?
+
+			# \n at the end to factor in the enter key
+			render="$(echo-trim-colors -- "$question_render"$'\n'"$prompt$RESULT")"
+			render="$("$bin_gfold" -w "$size_columns" <<<"$render")"
+			render_rows="$("$bin_gwc" -l <<<"$render")"
+
+			# move these lines up and erase
+			printf '\e[%sF\e[G\e[J' "$render_rows" >"$tty_target"
+
 			if test "$__read_status" -eq 142; then
 				return 60 # ETIMEDOUT 60 Operation timed out
 			fi
 			if is-value -- "$RESULT"; then
+				# we have a value, proceed
 				break
-			elif test "$option_required" = 'no'; then
+			elif test "$option_required" = 'yes'; then
+				# ask again
+				continue
+			else
+				# no result, optional, set value to empty, and proceed
 				RESULT=''
 				break
 			fi
@@ -180,89 +234,82 @@ function ask_() (
 		do_validate
 	}
 	function do_validate {
-		local choose_status ask_status choice choices=()
-		if is-value -- "$RESULT"; then
-			# we have a value, so go for it
-			if test "$option_confirm" != 'yes'; then
-				print_line "$RESULT"
+		local choose_status prompt_status choice choices=()
+
+		# have we prompted?
+		if test "$ASKED" = 'no'; then
+			# do we want to confirm the default value
+			if is-value -- "$RESULT" && test "$option_confirm_default" = 'no'; then
+				send_result
 				return 0
 			fi
-			# proceed with confirm
-			if test "$ASKED" = 'yes'; then
-				if test "$option_password" = 'yes'; then
-					choices+=('existing' 'use the entered password')
-				else
-					choices+=('existing' "use the entered value: [$RESULT]")
-				fi
-			else
-				if test "$option_password" = 'yes'; then
-					choices+=('existing' 'use the preconfigured password')
-				else
-					choices+=('existing' "use the preconfigured value: [$RESULT]")
-				fi
-			fi
-		fi
-		if test "$ASKED" = 'yes'; then
-			choices+=('custom' 'redo the entered value')
 		else
-			choices+=('custom' 'enter a value')
-		fi
-		if test "$option_required" = 'no'; then
-			choices+=('none' 'use no value')
-		fi
+			# we have asked, do we want to confirm the input value
+			if test "$option_confirm_input" = 'no'; then
+				send_result
+				return 0
+			fi
 
-		# as need to confirm, adjust the timeout
-		if test -z "$option_timeout" && (is-value -- "$RESULT" || test "$option_required" = 'no'); then
-			# timeout of one minute for confirms of existing values, or optional values
-			option_timeout=60
-		fi
+			# redo choices, has to be redone each time due to result
+			if test "$option_password" = 'yes'; then
+				choices+=('existing' 'use the entered password')
+			else
+				choices+=('existing' "use the entered value: [$RESULT]")
+			fi
+			choices+=('custom' 'redo the entered value')
+			if test "$option_required" = 'no'; then
+				choices+=('none' 'use no value')
+			fi
 
-		# ask
-		eval_capture --statusvar=choose_status --stdoutvar=choice -- \
-			choose-option \
-			--timeout="$option_timeout" \
-			--question="$option_question" \
-			--label -- "${choices[@]}"
+			# we want to confirm
+			eval_capture --statusvar=choose_status --stdoutvar=choice -- \
+				choose-option \
+				--timeout="$option_timeout" \
+				--question="$option_question" \
+				--label -- "${choices[@]}"
 
-		# check
-		if test "$choose_status" -eq 60; then
-			echo-style --error="Choose timed out: $choose_status" >/dev/stderr
-			on_timeout
-			return
-		elif test "$choose_status" -ne 0; then
-			echo-style --error="Choose failed: $choose_status" >/dev/stderr
-			sleep 3
-			return "$choose_status"
-		fi
-
-		# handle
-		if test "$choice" = 'existing'; then
-			# done, sucess
-			print_line "$RESULT"
-			return 0
-		elif test "$choice" = 'custom'; then
-			# ask
-			eval_capture --statusvar=ask_status -- do_ask "$option_question"
-
-			# check for failure
-			if test "$ask_status" -ne 0; then
-				# timeout probably
+			# check the confirmation
+			if test "$choose_status" -eq 60; then
+				echo-style --error="Choose timed out: $choose_status" >/dev/stderr
 				on_timeout
 				return
+			elif test "$choose_status" -ne 0; then
+				echo-style --error="Choose failed: $choose_status" >/dev/stderr
+				sleep 3
+				return "$choose_status"
 			fi
 
-			# done, success
-			return 0
-		elif test "$choice" = 'none'; then
-			# done, sucess
-			echo
-			return 0
-		else
-			# unknown error
-			echo-style --error="Invalid choice: $choice" >/dev/stderr
-			sleep 3
-			return 14 # EFAULT 14 Bad address
+			# proceess the confirmation
+			if test "$choice" = 'existing'; then
+				# done, sucess
+				send_result
+				return 0
+			elif test "$choice" = 'custom'; then
+				: # proceed with prompt
+			elif test "$choice" = 'none'; then
+				# done, sucess
+				echo
+				return 0
+			else
+				# unknown error
+				echo-style --error="Invalid choice: $choice" >/dev/stderr
+				sleep 3
+				return 14 # EFAULT 14 Bad address
+			fi
 		fi
+
+		# prompt
+		eval_capture --statusvar=prompt_status -- do_prompt
+
+		# check for failure
+		if test "$prompt_status" -ne 0; then
+			# timeout probably
+			on_timeout
+			return
+		fi
+
+		# done, success
+		return 0
 	}
 
 	# act
