confirm: new styles, styles.bash: rework
- `styles.bash`:
    - `__refresh_style_cache` is now `__load_styles --save` and `__append_style` is now `__load_styles --begin={...} --end={...} --`
    - fixed missing style detection, which allowed me to catch that `choose` has had incorrect legend styles for a year due to it missing on dark mode due to this regression: https://github.com/bevry/dorothy/commit/c4d1e1fb92eb60e82a5501b4c017e58d81c364ce#diff-8ea345ed887e934d2d76141ab54769e37b41585ce9bc21569b1a622147e91970L505
    - fixed caching interfering with color switching, as it previously it would prefer say a cached coloured value, even if now we want no colours (in practice this wasn't encountered, as such caching only happened once)
    - renamed the internal for color / for without color toggles `multicolor` and `monocolor`, so there is no longer conflation/confliction with `--[no-]color`
    - the variable convention is now `STYLE__[(MULTI|MONO)COLOR][__END]__<style_name>`
    - `__print_style` now properly supports tailing `+(multi|mono)color=...` and generic `--(multi|mono)color ...` modifiers
     - support uppercase flags/targets (they are converted to lowercase), this is a step to supporting `--target=(STDOUT|...)` generics
    - this work is a stepping stone to getting `__print_style` into `bash.bash` which should improve performance
    - moved `confirm` styles into `confirm`, which is also a stepping stone for improving performance, as only generic/commonly useful styles should be bundled

- `confirm`: new styles, and easier styling, thanks to the improved performance of styling

- add/updated several font installers `setup-util-(fira-code|ibm-plex|intel-one-mono|maple-mono|monaspace|source-code-pro)`

diff --git a/commands/ask b/commands/ask
--- a/commands/ask
+++ b/commands/ask
@@ -90,7 +90,7 @@ function ask_test() (
 )
 function ask_() (
 	source "$DOROTHY/sources/bash.bash"
-	source "$DOROTHY/sources/styles.bash" # __refresh_style_cache
+	source "$DOROTHY/sources/styles.bash" # __load_styles
 	source "$(type -P echo-clear-lines)"
 
 	# =====================================
@@ -190,17 +190,17 @@ function ask_() (
 	# =====================================
 	# Styles
 
-	__refresh_style_cache -- question_title_prompt question_title_result question_body input_warning input_error icon_prompt result_line empty_line commentary_nothing_provided commentary_using_password indent_blockquote commentary_timeout_default commentary_timeout_required commentary_timeout_optional commentary_input_failure result_commentary_spacer key code alternative_screen_buffer default_screen_buffer clear_screen || return
+	__load_styles --save -- question_title_prompt question_title_result question_body input_warning input_error icon_prompt result_line empty_line commentary_nothing_provided commentary_using_password indent_blockquote commentary_timeout_default commentary_timeout_required commentary_timeout_optional commentary_input_failure result_commentary_spacer key code alternative_screen_buffer default_screen_buffer clear_screen || return
 
 	# style the question
 	local question_title_and_body_and_newline='' question_title_result=''
 	if [[ -n $question_title ]]; then
 		if [[ -n $question_body ]]; then
-			question_title_and_body_and_newline="${style__question_title_prompt}${question_title}${style__end__question_title_prompt}"$'\n'"${style__question_body}${question_body}${style__end__question_body}"$'\n'
+			question_title_and_body_and_newline="${STYLE__question_title_prompt}${question_title}${STYLE__END__question_title_prompt}"$'\n'"${STYLE__question_body}${question_body}${STYLE__END__question_body}"$'\n'
 		else
-			question_title_and_body_and_newline="${style__question_title_prompt}${question_title}${style__end__question_title_prompt}"$'\n'
+			question_title_and_body_and_newline="${STYLE__question_title_prompt}${question_title}${STYLE__END__question_title_prompt}"$'\n'
 		fi
-		question_title_result="${style__question_title_result}${question_title}${style__end__question_title_result}"
+		question_title_result="${STYLE__question_title_result}${question_title}${STYLE__END__question_title_result}"
 	fi
 
 	# =====================================
@@ -220,7 +220,7 @@ function ask_() (
 	# adjust prompt
 	local input_prompt_and_newline=''
 	if [[ $IS_STDIN_LINE_BUFFERED == 'yes' && -n $option_default ]]; then
-		input_prompt_and_newline="Press ${style__key}ENTER${style__end__key} to use the default value of ${style__code}${option_default}${style__end__code}. Press ${style__key}ESC${style__end__key} then ${style__key}ENTER${style__end__key} to use no value."$'\n'
+		input_prompt_and_newline="Press ${STYLE__key}ENTER${STYLE__END__key} to use the default value of ${STYLE__code}${option_default}${STYLE__END__code}. Press ${STYLE__key}ESC${STYLE__END__key} then ${STYLE__key}ENTER${STYLE__END__key} to use no value."$'\n'
 	fi
 
 	# adjust timeout to one minute if we have a default value, or if optional
@@ -230,7 +230,7 @@ function ask_() (
 
 	# adjust read args based on timeout
 	# @todo use expanded arrays to make this smaller
-	local READ_RESULT READ_PROMPT="${question_title_and_body_and_newline}${input_prompt_and_newline}${style__icon_prompt}" READ_PROMPT_LINES CLEAR
+	local READ_RESULT READ_PROMPT="${question_title_and_body_and_newline}${input_prompt_and_newline}${STYLE__icon_prompt}" READ_PROMPT_LINES CLEAR
 	if [[ $inline == 'no' ]]; then
 		if [[ -n $option_timeout ]]; then
 			function __read {
@@ -265,15 +265,15 @@ function ask_() (
 	function on_timeout {
 		if is-value -- "$RESULT"; then
 			# default
-			commentary="${style__result_commentary_spacer}${style__commentary_timeout_default}"
+			commentary="${STYLE__result_commentary_spacer}${STYLE__commentary_timeout_default}"
 			return 0
 		elif [[ $option_required == 'no' ]]; then
 			# optional
-			commentary="${style__result_commentary_spacer}${style__commentary_timeout_optional}"
+			commentary="${STYLE__result_commentary_spacer}${STYLE__commentary_timeout_optional}"
 			return 0
 		else
 			# required
-			commentary="${style__result_commentary_spacer}${style__commentary_timeout_required}"
+			commentary="${STYLE__result_commentary_spacer}${STYLE__commentary_timeout_required}"
 			return 60 # ETIMEDOUT 60 Operation timed out
 		fi
 	}
@@ -282,7 +282,7 @@ function ask_() (
 
 		# reset clear, in case a choose/confirm failed and we are re-prompting
 		if [[ $inline == 'no' ]]; then
-			CLEAR="$style__alternative_screen_buffer"
+			CLEAR="$STYLE__alternative_screen_buffer"
 		else
 			CLEAR=''
 		fi
@@ -308,7 +308,7 @@ function ask_() (
 						# treat everything else as custom input
 						RESULT="$READ_RESULT"
 					fi
-					CLEAR="$style__clear_screen"
+					CLEAR="$STYLE__clear_screen"
 				fi
 			else
 				result_prompt=''
@@ -351,7 +351,7 @@ function ask_() (
 		done
 		# do the final erasure if necessary
 		if [[ $inline == 'no' ]]; then
-			CLEAR="$style__default_screen_buffer"
+			CLEAR="$STYLE__default_screen_buffer"
 		fi
 		if [[ -n $CLEAR ]]; then
 			__do --redirect-stdout=TTY -- __print_string "$CLEAR"
@@ -405,7 +405,7 @@ function ask_() (
 				on_timeout
 				return
 			elif [[ $choose_status -ne 0 ]]; then
-				commentary="${style__result_commentary_spacer}$(printf "$style__commentary_input_failure" "choose failure: $choose_status")"
+				commentary="${STYLE__result_commentary_spacer}$(printf "$STYLE__commentary_input_failure" "choose failure: $choose_status")"
 				return "$choose_status"
 			fi
 
@@ -421,7 +421,7 @@ function ask_() (
 				return 0
 			else
 				# unknown error
-				commentary="${style__result_commentary_spacer}$(printf "$style__commentary_input_failure" "invalid choice: $choice")"
+				commentary="${STYLE__result_commentary_spacer}$(printf "$STYLE__commentary_input_failure" "invalid choice: $choice")"
 				return 14 # EFAULT 14 Bad address
 			fi
 		fi
@@ -449,12 +449,12 @@ function ask_() (
 		if [[ $option_linger == 'yes' ]]; then
 			local result
 			if [[ -z $RESULT ]]; then
-				result="${style__commentary_nothing_provided}"
+				result="${STYLE__commentary_nothing_provided}"
 			elif [[ $option_password == 'yes' ]]; then
-				result="${style__commentary_using_password}"
+				result="${STYLE__commentary_using_password}"
 			else
-				result="${RESULT//$'\n'/$'\n'"${style__indent_blockquote}"}" # add the necessary indentation
-				result="${style__result_line}${style__indent_blockquote}${result}${style__end__result_line}"
+				result="${RESULT//$'\n'/$'\n'"${STYLE__indent_blockquote}"}" # add the necessary indentation
+				result="${STYLE__result_line}${STYLE__indent_blockquote}${result}${STYLE__END__result_line}"
 			fi
 			render+=$'\n'"$result"$'\n'
 			__do --redirect-stdout=TTY -- __print_string "$render"
diff --git a/commands/confirm b/commands/confirm
--- a/commands/confirm
+++ b/commands/confirm
@@ -61,7 +61,7 @@ function confirm_test() (
 )
 function confirm_() (
 	source "$DOROTHY/sources/bash.bash"
-	source "$DOROTHY/sources/styles.bash" # __refresh_style_cache
+	source "$DOROTHY/sources/styles.bash" # __load_styles
 	source "$(type -P echo-clear-lines)"
 	source "$(type -P read-key)"
 
@@ -172,38 +172,37 @@ function confirm_() (
 	# =====================================
 	# Styles
 
-	__refresh_style_cache -- question_title_prompt question_title_result question_body input_warning input_error confirm_positive_active confirm_positive_inactive confirm_positive_result confirm_negative_active confirm_negative_inactive confirm_negative_result confirm_abort_inactive confirm_abort_result confirm_proceed_active confirm_proceed_result commentary_timeout_default commentary_timeout_required commentary_input_failure result_commentary_spacer || return
+	__load_styles --save -- commentary_timeout_default commentary_timeout_required commentary_input_failure result_commentary_spacer || return
 
 	# style the question
-	local question_title_and_body='' question_title_result='' title_result_spacer legend_legend_spacer='   ' legend_indent='  '
+	local question_title_and_body='' question_title_result='' title_result_spacer legend_legend_spacer='  ' legend_indent=''
 	if [[ -n $question_title ]]; then
 		if [[ -n $question_body ]]; then
-			question_title_and_body="${style__question_title_prompt}${question_title}${style__end__question_title_prompt}"$'\n'"${style__question_body}${question_body}${style__end__question_body}"$'\n'
+			question_title_and_body="$(__print_style --question-title-prompt="$question_title" --newline --question-body="$question_body" --newline)"
 		else
-			question_title_and_body="${style__question_title_prompt}${question_title}${style__end__question_title_prompt}"$'\n'
+			question_title_and_body="$(__print_style --question-title-prompt="$question_title" --newline)"
 		fi
-		question_title_result="${style__question_title_result}${question_title}${style__end__question_title_result}"
+		question_title_result="$(__print_style --question-title="$question_title")"
 		title_result_spacer='  '
 	else
 		title_result_spacer=''
 	fi
 
 	# renders
+	# 🯟
 	local options_unselected=() options_selected=() options_results=() selected_index='' selectable_count selectable_last yes_index no_index='' abort_index
 	if [[ $option_mode =~ ^(positive|negative|bool)$ ]]; then
 		options_selected+=(
-			"${legend_indent}${style__confirm_positive_active}"
-			"${legend_legend_spacer}${style__confirm_negative_active}"
+			"$(__print_style --monocolor='*YES* [Y]' --multicolor --background-green+intense-white+bold='👉 YES ' --background-white --green='🭬' --intense-black=' Y  ')"
+			"   $(__print_style --monocolor='*NO* [N]' --multicolor --background-red+intense-white+bold='👉 NO ' --background-white --red='🭬' --intense-black=' N  ')"
 		)
 		options_unselected+=(
-			"${legend_indent}${style__confirm_positive_inactive}"
-			"${legend_legend_spacer}${style__confirm_negative_inactive}"
-			"${legend_legend_spacer}${style__confirm_abort_inactive}"
+			"   $(__print_style --monocolor=' YES  [Y]' --multicolor --green='YES' --dim=' ' --invert+white='🭬' --background-white+intense-black=' Y  ')"
+			"      $(__print_style --monocolor=' NO  [N]' --multicolor --red='NO' --dim=' ' --invert+white='🭬' --background-white+intense-black=' N  ')"
 		)
 		options_results=(
-			"${title_result_spacer}${style__confirm_positive_result}"
-			"${title_result_spacer}${style__confirm_negative_result}"
-			"${title_result_spacer}${style__confirm_abort_result}"
+			"$(__print_style --monocolor='[YES]' --multicolor+background-green+intense-white+bold=' YES ')"
+			"$(__print_style --monocolor='[NO]' --multicolor+background-red+intense-white+bold=' NO ')"
 		)
 		if [[ $option_mode == 'positive' ]]; then
 			selected_index=0
@@ -215,20 +214,24 @@ function confirm_() (
 		abort_index=2
 	elif [[ $option_mode == 'confirm' ]]; then
 		options_selected+=(
-			"${legend_indent}${style__confirm_proceed_active}"
+			"$(__print_style --monocolor='*PROCEED* [ENTER|SPACE|Y]' --multicolor --background-green+intense-white+bold='👉 PROCEED ' --background-white --green='🭬' --intense-black=' ENTER │ SPACE │ Y  ')"
 		)
 		options_unselected+=(
 			'' # never used
-			"${legend_legend_spacer}${style__confirm_abort_inactive}"
 		)
 		options_results=(
-			"${title_result_spacer}${style__confirm_proceed_result}"
-			"${title_result_spacer}${style__confirm_abort_result}"
+			"$(__print_style --monocolor='[PROCEED]' --multicolor+background-green+intense-white+bold=' PROCEED ')"
 		)
 		selected_index=0
 		yes_index=1
 		abort_index=1
 	fi
+	options_unselected+=(
+		"            $(__print_style --monocolor=' ABORT  [ESC|Q]' --multicolor --dim+red='ABORT' --dim=' ' --invert+white='🭬' --dim+background-white+intense-black=' ESC │ Q  ')"
+	)
+	options_results+=(
+		"$(__print_style --monocolor='[ABORT]' --multicolor+background-red+intense-white+bold=' ABORT ')"
+	)
 	selectable_count="${#options_selected[@]}"
 	selectable_last="$((selectable_count - 1))"
 
@@ -343,7 +346,7 @@ function confirm_() (
 		if [[ $read_status -eq 60 ]]; then
 			# timeout
 			# default
-			commentary="${style__result_commentary_spacer}${style__commentary_timeout_default}"
+			commentary="${STYLE__result_commentary_spacer}${STYLE__commentary_timeout_default}"
 			if [[ $option_mode == 'positive' ]]; then
 				RESULT=0
 				break
@@ -353,7 +356,7 @@ function confirm_() (
 			else
 				# bool, confirm
 				# required
-				commentary="${style__result_commentary_spacer}${style__commentary_timeout_required}"
+				commentary="${STYLE__result_commentary_spacer}${STYLE__commentary_timeout_required}"
 				RESULT="$read_status"
 				break
 			fi
@@ -363,7 +366,7 @@ function confirm_() (
 			continue
 		elif [[ $read_status -ne 0 ]]; then
 			# failure
-			commentary="${style__result_commentary_spacer}$(printf "$style__commentary_input_failure" "read status: $read_status")"
+			commentary="${STYLE__result_commentary_spacer}$(printf "$STYLE__commentary_input_failure" "read status: $read_status")"
 			RESULT="$read_status"
 			break
 		fi
