ask: support editing the default value

diff --git a/commands/ask b/commands/ask
--- a/commands/ask
+++ b/commands/ask
@@ -83,7 +83,13 @@ function ask_() (
 				Specifies the default value if no user specified value is entered.
 
 			--confirm
-			    Specifies that the prompt should confirm the value before continuing.
+			    Specifies that the prompt should confirm the (default/entered) value before continuing.
+
+			--confirm-default
+			    Specifies that the prompt should confirm the default value (if provided) before continuing. Defaults to enabled.
+
+			--confirm-input
+			    Specifies that the prompt should confirm the entered value before continuing. Defaults to disabled.
 
 			--password
 			    Specifies that the prompt should hide the value when entering by using password mode.
@@ -101,7 +107,7 @@ function ask_() (
 	}
 
 	# process
-	local item args=() option_question='' option_default='' option_password='no' option_required='no' option_confirm='no' option_timeout=''
+	local item args=() option_question='' option_default='' option_password='no' option_required='no' option_confirm_default='yes' option_confirm_input='no' option_timeout=''
 	while test "$#" -ne 0; do
 		item="$1"
 		shift
@@ -116,8 +122,15 @@ function ask_() (
 		'--no-required'* | '--required'*)
 			option_required="$(get-flag-value --affirmative --fallback="$option_required" -- "$item")"
 			;;
+		'--no-confirm-default'* | '--confirm-default'*)
+			option_confirm_default="$(get-flag-value --affirmative --fallback="$option_confirm_default" -- "$item")"
+			;;
+		'--no-confirm-input'* | '--confirm-input'*)
+			option_confirm_input="$(get-flag-value --affirmative --fallback="$option_confirm_input" -- "$item")"
+			;;
 		'--no-confirm'* | '--confirm'*)
-			option_confirm="$(get-flag-value --affirmative --fallback="$option_confirm" -- "$item")"
+			option_confirm_default="$(get-flag-value --affirmative --fallback="$option_confirm_default" -- "$item")"
+			option_confirm_input="$(get-flag-value --affirmative --fallback="$option_confirm_input" -- "$item")"
 			;;
 		'--')
 			args+=("$@")
@@ -144,16 +157,16 @@ function ask_() (
 	# helpers
 	function on_timeout {
 		if is-value -- "$RESULT"; then
-			echo-style --notice="Ask timed out, using fallback value: " --code="$RESULT" >/dev/stderr
+			echo-style --notice="Ask timed out. Using the fallback value: " --code="$RESULT" >/dev/stderr
 			sleep 5
 			print_line "$RESULT"
 			return 0
 		elif test "$option_required" = 'no'; then
-			echo-style --notice='Ask timed out, as the field was optional will use no value.' >/dev/stderr
+			echo-style --notice='Ask timed out. Had no fallback value, this is fine as the field was optional.' >/dev/stderr
 			sleep 5
 			return 0
 		else
-			echo-style --warning='Ask timed out, with no fallback.' >/dev/stderr
+			echo-style --warning='Ask timed out. Had no fallback value... the field was required.' >/dev/stderr
 			sleep 5
 			return 60 # ETIMEDOUT 60 Operation timed out
 		fi
@@ -163,10 +176,11 @@ function ask_() (
 		tty_auto
 		ASKED='yes' # not local
 		if test -n "${1-}"; then
-			print_line "$1" >"$tty_target"
+			echo-style --bold="$1" >"$tty_target"
 		fi
 		while true; do
-			__read_status=0 && read -r -t 300 -r -p '> ' RESULT || __read_status=$?
+			# -i requires -e
+			__read_status=0 && read -r -t 300 -ei "$RESULT" -p '> ' RESULT || __read_status=$?
 			if test "$__read_status" -eq 142; then
 				return 60 # ETIMEDOUT 60 Operation timed out
 			fi
@@ -182,19 +196,24 @@ function ask_() (
 	function do_validate {
 		local choose_status ask_status choice choices=()
 		if is-value -- "$RESULT"; then
-			# we have a value, so go for it
-			if test "$option_confirm" != 'yes'; then
-				print_line "$RESULT"
-				return 0
-			fi
-			# proceed with confirm
+			# we have an input
 			if test "$ASKED" = 'yes'; then
+				# do we want to confirm the input value
+				if test "$option_confirm_input" = 'no'; then
+					print_line "$RESULT"
+					return 0
+				fi
 				if test "$option_password" = 'yes'; then
 					choices+=('existing' 'use the entered password')
 				else
 					choices+=('existing' "use the entered value: [$RESULT]")
 				fi
 			else
+				# do we want to confirm the default value
+				if test "$option_confirm_default" = 'no'; then
+					print_line "$RESULT"
+					return 0
+				fi
 				if test "$option_password" = 'yes'; then
 					choices+=('existing' 'use the preconfigured password')
 				else
