2022 Q1 (#121)
Discussion:
- https://github.com/bevry/dorothy/discussions/118

Closes:
- https://github.com/bevry/dorothy/issues/120
- https://github.com/bevry/dorothy/issues/7

Most of the work done in:
- https://github.com/bevry/dorothy/commit/de2170e6a3471b1c3f55cea1f7ebc032f2755cb3

diff --git a/commands/ask b/commands/ask
--- a/commands/ask
+++ b/commands/ask
@@ -5,203 +5,215 @@ source "$DOROTHY/sources/tty.bash"
 source "$DOROTHY/sources/arrays.bash"
 may_require_array_support 'mapfile' 'empty'
 
-# =====================================
-# Arguments
+function ask() (
+	# =====================================
+	# Arguments
 
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Prompt the user for an input value in a clean and robust way.
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Prompt the user for an input value in a clean and robust way.
 
-		USAGE:
-		ask [...flags] [--flag=... -- ...args]
+			USAGE:
+			ask [...options]
 
-		FLAGS:
-		Provide [--question=...] to specify the question that the prompt will be answering.
-		Provide [--default=...] to specify the default value if no user specified value is entered.
-		Provide [--confirm] to specify that the prompt should confirm the value before continuing.
-		Provide [--password] to specify that the prompt should hide the value when entering by using password mode.
-		Provide [--required] to specify that the prompt should not continue until a value is provided.
-		Provide [--timeout=...] to specify a custom timeout value in seconds.
-		Provide [--flag=... -- ...args] to specify a flag to search the arguments for, to set a default value.
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
-	fi
-	return 22 # Invalid argument
-}
+			OPTIONS:
+			--question=<string>
+			    Specifies the question that the prompt will be answering.
 
-# process
-args=() # used with option_flag
-option_question=''
-option_default=''
-option_password='no'
-option_required='no'
-option_confirm='no'
-option_timeout=''
-option_flag=''
-while test "$#" -ne 0; do
-	item="$1"
-	shift
-	case "$item" in
-	'help' | '--help' | '-h') help ;;
-	'--question='*) option_question="${item:11}" ;;
-	'--default='*) option_default="${item:10}" ;;
-	'--timeout='*) option_timeout="${item:10}" ;;
-	'--flag='*) option_flag="${item:7}" ;;
-	'--no-password'* | '--password'*)
-		option_password="$(get-flag-value password --missing="$option_password" -- "$item" | echo-affirmative)"
-		;;
-	'--no-required'* | '--required'*)
-		option_required="$(get-flag-value required --missing="$option_required" -- "$item" | echo-affirmative)"
-		;;
-	'--no-confirm'* | '--confirm'*)
-		option_confirm="$(get-flag-value confirm --missing="$option_confirm" -- "$item" | echo-affirmative)"
-		;;
-	'--')
-		args+=("$@")
-		shift $#
-		break
-		;;
-	'--'*) help "An unrecognised flag was provided: $item" ;;
-	*) help "An unrecognised argument was provided: $item" ;;
-	esac
-done
+			--default=<value>
+				Specifies the default value if no user specified value is entered.
 
-# prepare flags
-flags=('-r')
-if test -n "$option_default"; then
-	result="$option_default"
-elif test -n "$option_flag"; then
-	result="$(get-flag-value "$option_flag" -- "${args[@]}")"
-else
-	result=''
-fi
+			--confirm
+			    Specifies that the prompt should confirm the value before continuing.
 
-# helpers
-asked='no'
-function handle_timeout() {
-	if is-value "$result"; then
-		echo "Ask timed out, using fallback value: $result" >/dev/stderr
-		sleep 5
-		echo "$result"
-		return 0
-	elif test "$option_required" = 'no'; then
-		echo 'Ask timed out, as the field was optional will use no value.' >/dev/stderr
-		sleep 5
-		return 0
+			--password
+			    Specifies that the prompt should hide the value when entering by using password mode.
+
+			--required
+			    Specifies that the prompt should not continue until a value is provided.
+
+			--timeout=<seconds>
+			    Specifies a custom timeout value in seconds.
+
+			--flag=<string> -- <...args>
+			    Specifies a flag to search the arguments for, to set a default value.
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item args=() option_question='' option_default='' option_password='no' option_required='no' option_confirm='no' option_timeout='' option_flag=''
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--question='*) option_question="${item:11}" ;;
+		'--default='*) option_default="${item:10}" ;;
+		'--timeout='*) option_timeout="${item:10}" ;;
+		'--flag='*) option_flag="${item:7}" ;;
+		'--no-password'* | '--password'*)
+			option_password="$(get-flag-value password --missing="$option_password" -- "$item" | echo-affirmative)"
+			;;
+		'--no-required'* | '--required'*)
+			option_required="$(get-flag-value required --missing="$option_required" -- "$item" | echo-affirmative)"
+			;;
+		'--no-confirm'* | '--confirm'*)
+			option_confirm="$(get-flag-value confirm --missing="$option_confirm" -- "$item" | echo-affirmative)"
+			;;
+		'--')
+			args+=("$@")
+			shift $#
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) help "An unrecognised argument was provided: $item" ;;
+		esac
+	done
+
+	# prepare flags
+	local result read_flags=('-r')
+	if test -n "$option_default"; then
+		result="$option_default"
+	elif test -n "$option_flag"; then
+		result="$(get-flag-value "$option_flag" -- "${args[@]}")"
 	else
-		echo 'Ask timed out, with no fallback.' >/dev/stderr
-		sleep 5
-		return 62 # Timer expired
+		result=''
 	fi
-}
-function ask() {
-	local ec
-	tty_auto
-	asked='yes' # not lcoal
-	if test -n "${1-}"; then
-		echo "$1" >/dev/tty
-	fi
-	while true; do
-		ec=0 && read "${flags[@]}" -t 300 -r -p "> " result || ec="$?"
-		if test "$ec" -gt 128; then
+
+	# helpers
+	local asked='no'
+	function on_timeout {
+		if is-value "$result"; then
+			echo "Ask timed out, using fallback value: $result" >/dev/stderr
+			sleep 5
+			echo "$result"
+			return 0
+		elif test "$option_required" = 'no'; then
+			echo 'Ask timed out, as the field was optional will use no value.' >/dev/stderr
+			sleep 5
+			return 0
+		else
+			echo 'Ask timed out, with no fallback.' >/dev/stderr
+			sleep 5
 			return 62 # Timer expired
 		fi
+	}
+	function ask {
+		local ec
+		tty_auto
+		asked='yes' # not lcoal
+		if test -n "${1-}"; then
+			echo "$1" >/dev/tty
+		fi
+		while true; do
+			ec=0 && read "${read_flags[@]}" -t 300 -r -p "> " result || ec="$?"
+			if test "$ec" -gt 128; then
+				return 62 # Timer expired
+			fi
+			if is-value "$result"; then
+				break
+			elif test "$option_required" = 'no'; then
+				result=''
+				break
+			fi
+		done
+		validate
+	}
+	function validate {
+		local ec choice choices=()
 		if is-value "$result"; then
-			break
-		elif test "$option_required" = 'no'; then
-			result=''
-			break
+			# we have a value, so go for it
+			if test "$option_confirm" != 'yes'; then
+				echo "$result"
+				return
+			fi
+			# proceed with confirm
+			if test "$asked" = 'yes'; then
+				if test "$option_password" = 'yes'; then
+					choices+=('existing' 'use the entered password')
+				else
+					choices+=('existing' "use the entered value: [$result]")
+				fi
+			else
+				if test "$option_password" = 'yes'; then
+					choices+=('existing' 'use the preconfigured password')
+				else
+					choices+=('existing' "use the preconfigured value: [$result]")
+				fi
+			fi
 		fi
-	done
-	validate
-}
-function validate() {
-	local ec choices=()
-	if is-value "$result"; then
-		# we have a value, so go for it
-		if test "$option_confirm" != 'yes'; then
-			echo "$result"
-			exit
-		fi
-		# proceed with confirm
 		if test "$asked" = 'yes'; then
-			if test "$option_password" = 'yes'; then
-				choices+=('existing' 'use the entered password')
-			else
-				choices+=('existing' "use the entered value: [$result]")
-			fi
+			choices+=('custom' 'redo the entered value')
 		else
-			if test "$option_password" = 'yes'; then
-				choices+=('existing' 'use the preconfigured password')
-			else
-				choices+=('existing' "use the preconfigured value: [$result]")
-			fi
+			choices+=('custom' 'enter a value')
 		fi
-	fi
-	if test "$asked" = 'yes'; then
-		choices+=('custom' 'redo the entered value')
-	else
-		choices+=('custom' 'enter a value')
-	fi
-	if test "$option_required" = 'no'; then
-		choices+=('none' 'use no value')
-	fi
+		if test "$option_required" = 'no'; then
+			choices+=('none' 'use no value')
+		fi
 
-	# as need to confirm, adjust the timeout
-	if test -z "$option_timeout" && (is-value "$result" || test "$option_required" = 'no'); then
-		# timeout of one minute for confirms of existing values, or optional values
-		option_timeout=60
-	fi
+		# as need to confirm, adjust the timeout
+		if test -z "$option_timeout" && (is-value "$result" || test "$option_required" = 'no'); then
+			# timeout of one minute for confirms of existing values, or optional values
+			option_timeout=60
+		fi
 
-	# ask
-	ec=0 && choice="$(choose-option \
-		--timeout="$option_timeout" \
-		--question="$option_question" \
-		--label -- "${choices[@]}")" || ec="$?"
-
-	# check
-	if test "$ec" -eq 62; then
-		echo "Choose timed out [$ec]." >/dev/stderr
-		handle_timeout
-		exit "$?" # exit with the above on success and failure
-	elif test "$ec" -ne 0; then
-		echo "Choose failed [$ec]." >/dev/stderr
-		sleep 5
-		exit "$ec"
-	fi
-
-	# handle
-	if test "$choice" = 'existing'; then
-		# done, sucess
-		echo "$result"
-		exit
-	elif test "$choice" = 'custom'; then
 		# ask
-		ec=0 && ask "$option_question" || ec="$?"
+		ec=0 && choice="$(choose-option \
+			--timeout="$option_timeout" \
+			--question="$option_question" \
+			--label -- "${choices[@]}")" || ec="$?"
 
-		# check for failure
-		if test "$ec" -ne 0; then
-			# timeout probably
-			handle_timeout
-			exit "$?" # exit with the above on success and failure
+		# check
+		if test "$ec" -eq 62; then
+			echo-style --error="Choose timed out: $ec" >/dev/stderr
+			on_timeout
+			return "$?" # exit with the above on success and failure
+		elif test "$ec" -ne 0; then
+			echo-style --error="Choose failed: $ec" >/dev/stderr
+			sleep 5
+			return "$ec"
 		fi
 
-		# done, success
-		exit
-	elif test "$choice" = 'none'; then
-		# done, sucess
-		echo
-		exit
-	else
-		# unknown error
-		echo "invalid choice: [$result]" >/dev/stderr
-		sleep 5
-		exit 1
-	fi
-}
+		# handle
+		if test "$choice" = 'existing'; then
+			# done, sucess
+			echo "$result"
+			return
+		elif test "$choice" = 'custom'; then
+			# ask
+			ec=0 && ask "$option_question" || ec="$?"
 
-# act
-validate
+			# check for failure
+			if test "$ec" -ne 0; then
+				# timeout probably
+				on_timeout
+				return "$?" # exit with the above on success and failure
+			fi
+
+			# done, success
+			return
+		elif test "$choice" = 'none'; then
+			# done, sucess
+			echo
+			return
+		else
+			# unknown error
+			echo-style --error="Invalid choice: $choice" >/dev/stderr
+			sleep 5
+			return 14 # EFAULT 14 Bad address
+		fi
+	}
+
+	# act
+	validate
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	ask "$@"
+fi
diff --git a/commands/brew-installed b/commands/brew-installed
--- a/commands/brew-installed
+++ b/commands/brew-installed
@@ -1,101 +1,111 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# =====================================
-# Arguments
+function brew-installed() (
+	# =====================================
+	# Arguments
 
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Outputs the names of the installed packages.
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Outputs the names of the installed packages.
 
-		USAGE:
-		brew-installed [--requested] [--formula] [--cask] -- [...packages]
+			USAGE:
+			brew-installed [...options] -- [...packages]
 
-		FLAGS:
-		--requested    Output only packages that were manually installed, not packages that were only dependencies.
-		--formula      Output only packages that are formulas.
-		--cask         Output only packages that are casks.
-		[...packages]  If provided, only get details for these packages. Fail if one of them has not yet been installed.
-	EOF
-	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
+			OPTIONS:
+			--requested
+			    Output only packages that were manually installed, not packages that were only dependencies.
+
+			--formula
+			    Output only packages that are formulas.
+
+			--cask
+			    Output only packages that are casks.
+
+			ARGUMENTS:
+			...packages
+			    If provided, only get details for these packages. Fail if one of them has not yet been installed.
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item requested='no' packages brew_type brew_list_cmd brew_info_cmd deno_script_args
+	packages=()
+	brew_type='' # empty, formula, cask
+	brew_list_cmd=(
+		'brew'
+		'list'
+		'--versions' # --versions is necessary to limit to installed packages, as --full-name/-1 doesn't
+	)
+	brew_info_cmd=(
+		'brew'
+		'info'
+	)
+	deno_script_args=(
+		'--requested' # the deno script only runs with brew info, which is only run when --requested is provided
+	)
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--formula' | '--formulae') brew_type='formula' ;;
+		'--cask' | '--casks') brew_type='cask' ;;
+		'--no-requested'* | '--requested'*) requested="$(
+			get-flag-value requested --missing="$requested" -- "$item" | echo-affirmative
+		)" ;;
+		'--')
+			packages+=("$@")
+			shift $#
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) help "An unrecognised argument was provided: $item" ;;
+		esac
+	done
+
+	# add the filter
+	if test -n "$brew_type"; then
+		brew_list_cmd+=("--$brew_type")
+		brew_info_cmd+=("--$brew_type")
+		deno_script_args+=("--$brew_type")
 	fi
-	return 22 # Invalid argument
-}
 
-# process
-brew_packages=()
-brew_list=(
-	'brew'
-	'list'
-	'--versions' # --versions is necessary to limit to installed packages, as --full-name/-1 doesn't
-)
-brew_info=(
-	'brew'
-	'info'
-)
-deno_script_args=(
-	'--requested' # the deno script only runs with brew info, which is only run when --requested is provided
-)
-brew_type='' # empty, formula, cask
-option_requested='no'
-while test "$#" -ne 0; do
-	item="$1"
-	shift
-	case "$item" in
-	'help' | '--help' | '-h') help ;;
-	'--formula' | '--formulae') brew_type='formula' ;;
-	'--cask' | '--casks') brew_type='cask' ;;
-	'--no-requested'* | '--requested'*) option_requested="$(
-		get-flag-value requested --missing="$option_requested" -- "$item" | echo-affirmative
-	)" ;;
-	'--')
-		brew_packages+=("$@")
-		shift $#
-		break
-		;;
-	'--'*) help "An unrecognised flag was provided: $item" ;;
-	*) help "An unrecognised argument was provided: $item" ;;
-	esac
-done
+	# add the packages
+	if test "${#packages[@]}" -ne 0; then
+		brew_list_cmd+=("${packages[@]}")
+		brew_info_cmd+=(
+			'--json=v2'
+			"${packages[@]}"
+		)
+	else
+		brew_info_cmd+=(
+			'--json=v2'
+			'--installed'
+		)
+	fi
 
-# add the filter
-if test -n "$brew_type"; then
-	brew_list+=(--"${brew_type}")
-	brew_info+=(--"${brew_type}")
-	deno_script_args+=(--"${brew_type}")
-fi
+	# helpers
+	function do_brew_list {
+		"${brew_list_cmd[@]}" | cut -d' ' -f1 | sort | uniq
+		# returns 1 if one of them was missing
+		# if you want to check if any were present, do
+		# test -n "$(brew-installed -- rustup rust || :)"
+	}
+	function do_brew_info {
+		local temp_deno_script temp_file lines_in_temp_file
 
-# add the packages
-if test "${#brew_packages[@]}" -ne 0; then
-	brew_list+=("${brew_packages[@]}")
-	brew_info+=(
-		'--json=v2'
-		"${brew_packages[@]}"
-	)
-else
-	brew_info+=(
-		'--json=v2'
-		'--installed'
-	)
-fi
+		# ensure deno exists
+		env QUIET=yes setup-util-deno
 
-# helpers
-function do_brew_list() {
-	"${brew_list[@]}" | cut -d' ' -f1 | sort | uniq
-	# returns 1 if one of them was missing
-	# if you want to check if any were present, do
-	# test -n "$(brew-installed -- rustup rust || :)"
-}
-function do_brew_info() {
-	# ensure deno exists
-	env QUIET=yes setup-util-deno
-
-	# prepare as the .ts extension is essential
-	deno_script="$(fs-temp --xdg --filename="brew-installed-deno.ts")"
-	cat <<EOF >"$deno_script"
+		# prepare as the .ts extension is essential
+		temp_deno_script="$(fs-temp --directory='brew-installed' --file='deno.ts')"
+		cat <<EOF >"$temp_deno_script"
 // parse stdin
 import { readLines } from "https://deno.land/std/io/bufio.ts";
 let data = "";
@@ -140,23 +150,29 @@ if (names.size) {
 }
 EOF
 
-	# run
-	"${brew_info[@]}" | deno run --quiet "$deno_script" "${deno_script_args[@]}"
-}
+		# run
+		"${brew_info_cmd[@]}" | deno run --quiet "$temp_deno_script" "${deno_script_args[@]}"
+	}
 
-# get names of requested packages
-if test "$option_requested" = 'no'; then
-	do_brew_list
-else
-	# as brew_info doesn't do the missing exit code like brew_list does, we need to do it ourselves
-	if test "${#brew_packages[@]}" -eq 0; then
-		do_brew_info
+	# get names of requested packages
+	if test "$requested" = 'no'; then
+		do_brew_list
 	else
-		temp="$(mktemp)"
-		do_brew_info | tee "$temp"
-		lines="$(echo-count-lines --no-inline <"$temp")"
-		if test "$lines" -ne "${#brew_packages[@]}"; then
-			exit 1
+		# as brew_info doesn't do the missing exit code like brew_list does, we need to do it ourselves
+		if test "${#packages[@]}" -eq 0; then
+			do_brew_info
+		else
+			temp_file="$(mktemp)"
+			do_brew_info | tee "$temp_file"
+			lines_in_temp_file="$(echo-count-lines --no-inline <"$temp_file")"
+			if test "$lines_in_temp_file" -ne "${#packages[@]}"; then
+				return 1
+			fi
 		fi
 	fi
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	brew-installed "$@"
 fi
diff --git a/commands/choose-menu b/commands/choose-menu
--- a/commands/choose-menu
+++ b/commands/choose-menu
@@ -1,216 +1,238 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 source "$DOROTHY/sources/tty.bash"
+source "$DOROTHY/sources/arrays.bash"
+requires_array_support 'mapfile'
 
 # NOTES:
-# - [--default] and [--required] do not make sense here, as those are for high-level handling, this is just menu navigation
+# - [--required] do not make sense here, as those are for high-level handling, this is just menu navigation
 
 # QUIRKS:
 # - if there are more options than [$LINES - header], then this will fall apart
 
 # TODOS:
-# - [ ] adopt modern arg and help and invalid arg handling
 # - [ ] limit the options output to [$LINES - header]
 # - [ ] if one gets to $LINES, and there are truncated values, then "scroll" downwards
 # - [ ] support $COLUMNS - if a menu item is larger than the column, then it will show all of it when active
 
-# validate
-if is-help-separator "$@"; then
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Display a menu that the user can navigate using the keyboard.
+function choose-menu() (
+	# =====================================
+	# Arguments
 
-		USAGE:
-		choose-menu [...flags] -- <...items>
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Display a menu that the user can navigate using the keyboard.
 
-		RETURNS:
-		the index of the result
+			USAGE:
+			choose-menu [...options] -- ...<items>
 
-		FLAGS:
-		Provide [--question=...] to specify the question that the prompt will be answering.
-		Provide [--multi] to specify that multiple menu items should be able to be selected.
-		Provide [--timeout=...] to specify a custom timeout value in seconds.
-	EOF
-	exit 22 # Invalid argument
-fi
+			RETURNS:
+			The index of the result
 
-# now that we have ensured separator exists, we don't need empty, only mapfile
-source "$DOROTHY/sources/arrays.bash"
-requires_array_support 'mapfile'
+			OPTIONS:
+			--question=<question>
+			    Question to display as the prompt.
 
-# fetch options in a way that works with multi-line values
-options=()
-while [ $# -gt 0 ]; do
-	if [ "$1" = '--' ]; then
+			--multi
+			    Multiple menu items can be selected.
+
+			--timeout=<timeout>
+			    Custom timeout value in seconds.
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item='' items=() option_question='' option_timeout='' option_multi='no' option_required='no'
+	while test "$#" -ne 0; do
+		item="$1"
 		shift
-		break
-	fi
-	options+=("$1")
-	shift
-done
-option_question="$(get-flag-value question -- "${options[@]}")"
-option_timeout="$(get-flag-value timeout -- "${options[@]}")"
-option_multi="$(get-flag-value multi --missing=no -- "${options[@]}" | echo-affirmative)"
-option_required="$(get-flag-value required --missing=no -- "${options[@]}" | echo-affirmative)"
-
-# prepare choices
-choices=("$@")
-
-# ensure we have items
-if test "${#choices[@]}" -eq 0; then
-	{
-		echo-style --error="No items were provided. See [$0 --help] for usage."
-		sleep 5
-		exit 22 # Invalid argument
-	} >/dev/stderr
-elif is-array-partial "${choices[@]}"; then
-	{
-		echo-style --error="Empty items were provided. See [$0 --help] for usage."
-		echo-verbose "${choices[@]}"
-		sleep 5
-		exit 22 # Invalid argument
-	} >/dev/stderr
-fi
-
-# prepare
-tty_auto
-cursor=0
-count="${#choices[@]}"
-last="$((count - 1))"
-action=''
-mapfile -t selections < <(get-array "$count")
-
-# commence
-while test "$action" != 'done'; do
-	# question
-	if test -n "$option_question"; then
-		echo "$option_question" >/dev/tty
-	fi
-
-	# show the menu
-	for i in "${!choices[@]}"; do
-		if test "$i" -eq "$cursor"; then
-			echo -n ">" >/dev/tty
-		else
-			echo -n ' ' >/dev/tty
-		fi
-		if test "${selections[$i]-}" = 'yes'; then
-			echo -n "*" >/dev/tty
-		else
-			echo -n ' ' >/dev/tty
-		fi
-		choice="${choices[$i]}"
-		echo "$choice" >/dev/tty
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--question='*) option_question="${item:11}" ;;
+		'--timeout='*) option_timeout="${item:10}" ;;
+		'--no-multi'* | '--multi'*) option_multi="$(
+			get-flag-value multi --missing="$option_multi" -- "$item" | echo-affirmative
+		)" ;;
+		'--no-required'* | '--required'*) option_required="$(
+			get-flag-value required --missing="$option_required" -- "$item" | echo-affirmative
+		)" ;;
+		'--')
+			items+=("$@")
+			shift $#
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) help "An unrecognised argument was provided: $item" ;;
+		esac
 	done
 
-	# handle the response
-	ec=0 && action="$(read-arrow --timeout="$option_timeout")" || ec="$?"
-
-	# check
-	if test "$ec" -eq 62; then
-		echo "Input timed out [$ec]." >/dev/stderr
-		sleep 5
-		exit "$ec"
-	elif test "$ec" -ne 0; then
-		echo "Input failed [$ec]." >/dev/stderr
-		# some other failure
-		sleep 5
-		exit "$ec"
+	# ensure we have items
+	if test "${#items[@]}" -eq 0; then
+		{
+			echo-style --error="No options were provided. See [$0 --help] for usage."
+			sleep 5
+			exit 22 # Invalid argument
+		} >/dev/stderr
+	elif is-array-partial "${items[@]}"; then
+		{
+			echo-style --error="Empty options were provided. See [$0 --help] for usage."
+			echo-verbose "${items[@]}"
+			sleep 5
+			exit 22 # Invalid argument
+		} >/dev/stderr
 	fi
 
-	# handle special cases and remaps
-	# such as numbers, wasd, and vim movers
-	if is-digit "$action"; then
-		# number jump
-		if test "$action" -le 1; then
+	# prepare
+	local count last selections=()
+	count="${#items[@]}"
+	last="$((count - 1))"
+	mapfile -t selections < <(get-array "$count")
+
+	# commence
+	tty_auto
+	local index choice='' ec=0 cursor=0 action=''
+	while test "$action" != 'done'; do
+		# question
+		if test -n "$option_question"; then
+			echo "$option_question" >/dev/tty
+		fi
+
+		# show the menu
+		for index in "${!items[@]}"; do
+			if test "$index" -eq "$cursor"; then
+				echo -n ">" >/dev/tty
+			else
+				echo -n ' ' >/dev/tty
+			fi
+			if test "${selections[index]-}" = 'yes'; then
+				echo -n "*" >/dev/tty
+			else
+				echo -n ' ' >/dev/tty
+			fi
+			choice="${items[index]}"
+			echo "$choice" >/dev/tty
+		done
+
+		# handle the response
+		ec=0 && action="$(read-key --timeout="$option_timeout")" || ec="$?"
+
+		# check
+		if test "$ec" -eq 62; then
+			echo "Input timed out [$ec]." >/dev/stderr
+			sleep 5
+			exit "$ec"
+		elif test "$ec" -ne 0; then
+			echo "Input failed [$ec]." >/dev/stderr
+			# some other failure
+			sleep 5
+			exit "$ec"
+		fi
+
+		# handle special cases and remaps
+		# such as numbers, wasd, and vim movers
+		if is-digit "$action"; then
+			# number jump
+			if test "$action" -le 1; then
+				cursor=0
+			elif test "$action" -le "$count"; then
+				cursor="$((action - 1))"
+			else
+				cursor="$last"
+			fi
+			action='space'
+		elif test "$action" = "left" -o "$action" = "h" -o "$action" = "k" -o "$action" = "a" -o "$action" = "w"; then
+			action='up'
+		elif test "$action" = "right" -o "$action" = "l" -o "$action" = "j" -o "$action" = "d" -o "$action" = "s"; then
+			action='down'
+		fi
+
+		# control key
+		if test "$action" = "up"; then
+			if test "$cursor" -ne 0; then
+				cursor="$((cursor - 1))"
+			fi
+		elif test "$action" = "down"; then
+			if test "$cursor" -ne "$last"; then
+				cursor="$((cursor + 1))"
+			fi
+		elif test "$action" = "home"; then
 			cursor=0
-		elif test "$action" -le "$count"; then
-			cursor="$((action - 1))"
-		else
+		elif test "$action" = "end"; then
 			cursor="$last"
-		fi
-		action='space'
-	elif test "$action" = "left" -o "$action" = "h" -o "$action" = "k" -o "$action" = "a" -o "$action" = "w"; then
-		action='up'
-	elif test "$action" = "right" -o "$action" = "l" -o "$action" = "j" -o "$action" = "d" -o "$action" = "s"; then
-		action='down'
-	fi
-
-	# control key
-	if test "$action" = "up"; then
-		if test "$cursor" -ne 0; then
-			cursor="$((cursor - 1))"
-		fi
-	elif test "$action" = "down"; then
-		if test "$cursor" -ne "$last"; then
-			cursor="$((cursor + 1))"
-		fi
-	elif test "$action" = "home"; then
-		cursor=0
-	elif test "$action" = "end"; then
-		cursor="$last"
-	elif test "$action" = "backspace"; then
-		# unselect everything
-		for i in "${!choices[@]}"; do
-			selections[$i]=''
-		done
-	elif test "$action" = "all" -a "$option_multi" = 'yes'; then
-		# select everything
-		for i in "${!choices[@]}"; do
-			selections[$i]='yes'
-		done
-	elif test "$action" = 'tab'; then
-		# select and move to next line
-		selections[$cursor]='yes'
-		if test "$cursor" -eq "$last"; then
-			cursor=0
-		elif test "$cursor" -lt "$last"; then
-			cursor="$((cursor + 1))"
-		fi
-	elif test "$action" = 'space'; then
-		# toggle single
-		if test "${selections[$cursor]}" = 'yes'; then
-			selections[$cursor]=''
-		else
-			selections[$cursor]='yes'
+		elif test "$action" = "backspace"; then
+			# unselect everything
+			for index in "${!items[@]}"; do
+				selections[index]=''
+			done
+		elif test "$action" = "all" -a "$option_multi" = 'yes'; then
+			# select everything
+			for index in "${!items[@]}"; do
+				selections[index]='yes'
+			done
+		elif test "$action" = 'tab'; then
+			# select and move to next line
+			selections[cursor]='yes'
+			if test "$cursor" -eq "$last"; then
+				cursor=0
+			elif test "$cursor" -lt "$last"; then
+				cursor="$((cursor + 1))"
+			fi
+		elif test "$action" = 'space'; then
+			# toggle single
+			if test "${selections[cursor]}" = 'yes'; then
+				selections[cursor]=''
+			else
+				selections[cursor]='yes'
+				if test "$option_multi" != 'yes'; then
+					break
+				fi
+			fi
+		elif test "$action" = "enter"; then
 			if test "$option_multi" != 'yes'; then
+				selections[cursor]='yes'
+			fi
+			break
+		elif test "$action" = "escape"; then
+			# todo implement --required with --multi fallback properly here
+			if test "$option_required" = 'no'; then
 				break
 			fi
 		fi
-	elif test "$action" = "enter"; then
-		if test "$option_multi" != 'yes'; then
-			selections[$cursor]='yes'
+
+		# no break, so repeat the menu
+		tty_clear
+	done
+
+	# if break, then no clear occured, so clear it here
+	tty_clear
+
+	# if multi with no selection then ask for everything
+	# todo implement --required properly here
+	if is-array-empty "${selections[@]}" && test "$option_multi" = 'yes'; then
+		if confirm-positive --ppid=$$ -- "You exited without selecting anything, do you wish to select all?" >/dev/tty; then
+			for index in "${!items[@]}"; do
+				selections[index]='yes'
+			done
 		fi
-		break
-	elif test "$action" = "escape"; then
-		# todo implement --required with --multi fallback properly here
-		if test "$option_required" = 'no'; then
-			break
-		fi
+		tty_clear
 	fi
 
-	# no break, so repeat the menu
-	tty_clear
-done
+	# output the custom selections
+	local index selection
+	for index in "${!selections[@]}"; do
+		selection="${selections[index]}"
+		if test "$selection" = 'yes'; then
+			echo "$index"
+		fi
+	done
+)
 
-# if break, then no clear occured, so clear it here
-tty_clear
-
-# if multi with no selection then ask for everything
-# todo implement --required properly here
-if is-array-empty "${selections[@]}" && test "$option_multi" = 'yes'; then
-	if confirm-positive --ppid=$$ -- "You exited without selecting anything, do you wish to select all?" >/dev/tty; then
-		for i in "${!choices[@]}"; do
-			selections[$i]='yes'
-		done
-	fi
-	tty_clear
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	choose-menu "$@"
 fi
-
-# output the custom selections
-for i in "${!selections[@]}"; do
-	selection="${selections[$i]}"
-	if test "$selection" = 'yes'; then
-		echo "$i"
-	fi
-done
diff --git a/commands/echo-exit-affirmative b/commands/echo-exit-affirmative
--- a/commands/echo-exit-affirmative
+++ b/commands/echo-exit-affirmative
@@ -1,26 +1,68 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-if is-help "$@"; then
-	cat <<-EOF >/dev/stderr
-		USAGE:
-		echo-exit-affirmative exit 0
-		# ^ echos yes
+function echo-exit-affirmative() (
+	# =====================================
+	# Arguments
 
-		echo-exit-affirmative exit 1
-		# ^ echos no
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Given a command as arguments, execute it, and:
+			if [0] was the exit code, output [yes]
+			if [1] was the exit code, output [no]
+			if anything else was the exit code, propagate that exit code
 
-		echo-exit-affirmative exit 2
-		# ^ returns the failure code
-	EOF
-	exit 22 # Invalid argument
-fi
+			USAGE:
+			echo-exit-affirmative [--] ...<command>
 
-ec=0 && ("$@") || ec="$?"
-if test "$ec" -eq 0; then
-	echo 'yes'
-elif test "$ec" -eq 1; then
-	echo 'no'
-else
-	exit "$ec"
+			EXAMPLES:
+			echo-exit-affirmative -- exit 0    # outputs: yes    exit code: 0
+			echo-exit-affirmative -- exit 1    # outputs: no     exit code: 0
+			echo-exit-affirmative -- exit 2    # exit code: 2
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item cmd=()
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--')
+			cmd+=("$@")
+			shift "$#"
+			break
+			;;
+		*) cmd+=("$item") ;;
+		esac
+	done
+
+	# check
+	if test "${#cmd[@]}" -eq 0; then
+		help "No <command> was provided."
+	fi
+
+	# =====================================
+	# Action
+
+	local ec
+	ec=0 && ("${cmd[@]}") || ec="$?"
+	if test "$ec" -eq 0; then
+		echo 'yes'
+	elif test "$ec" -eq 1; then
+		echo 'no'
+	else
+		return "$ec"
+	fi
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	echo-exit-affirmative "$@"
 fi
diff --git a/commands/echo-exit-code b/commands/echo-exit-code
--- a/commands/echo-exit-code
+++ b/commands/echo-exit-code
@@ -1,21 +1,59 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-if is-help "$@"; then
-	cat <<-EOF >/dev/stderr
-		USAGE:
-		echo-exit-code exit 0
-		# ^ echos 0, returns 0
+function echo-exit-code() (
+	# =====================================
+	# Arguments
 
-		echo-exit-code exit 1
-		# ^ echos 1, returns 0
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Given a command as arguments, execute it, output the exit code.
 
-		echo-exit-code exit 2
-		# ^ echos 2, returns 0
-	EOF
-	exit 22 # Invalid argument
+			USAGE:
+			echo-exit-affirmative [--] ...<command>
+
+			EXAMPLES:
+			echo-exit-affirmative -- exit 0    # outputs: 0    exit code: 0
+			echo-exit-affirmative -- exit 1    # outputs: 1    exit code: 0
+			echo-exit-affirmative -- exit 2    # outputs: 2    exit code: 0
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item cmd=()
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--')
+			cmd+=("$@")
+			shift "$#"
+			break
+			;;
+		*) cmd+=("$item") ;;
+		esac
+	done
+
+	# check
+	if test "${#cmd[@]}" -eq 0; then
+		help "No <command> was provided."
+	fi
+
+	# =====================================
+	# Action
+
+	local ec
+	ec=0 && ("${cmd[@]}") || ec="$?"
+	echo "$ec"
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	echo-exit-code "$@"
 fi
-
-ec=0 && ("$@") || ec="$?"
-echo "$ec"
-exit 0
diff --git a/commands/echo-mkdir b/commands/echo-mkdir
--- a/commands/echo-mkdir
+++ b/commands/echo-mkdir
@@ -1,6 +1,33 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
+function help {
+	cat <<-EOF >/dev/stderr
+		ABOUT:
+		Make a directory at each input path, if it was not already one, and output its absolute path.
+
+		USAGE:
+		echo-mkdir [...options] <...input>
+		echo-lines <...input> | echo-mkdir [...options]
+
+		OPTIONS:
+		--sudo
+		    If provided, use sudo to make the directory.
+
+		EXAMPLE:
+
+		echo-mkdir ./temp
+
+		    $(pwd)/temp
+		    # exit status: 0
+
+	EOF
+	return 22 # Invalid argument
+}
+
+# stip --sudo option if it exists
+# and construct our cmd
+cmd=()
 if test "$1" = '--sudo'; then
 	shift
 	cmd=('sudo' 'mkdir' '-p')
@@ -8,9 +35,10 @@ else
 	cmd=('mkdir' '-p')
 fi
 
-function act() {
-	if "${cmd[@]}" "$1"; then
-		echo "$1"
+function on_input {
+	if test -d "$1" || ( "${cmd[@]}" "$1" ); then
+		fs-absolute "$1"
+		return 0
 	else
 		return 1
 	fi
diff --git a/commands/echo-numeric b/commands/echo-numeric
--- a/commands/echo-numeric
+++ b/commands/echo-numeric
@@ -1,17 +1,55 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-function act {
+function help {
+	cat <<-EOF >/dev/stderr
+		ABOUT:
+		Outputs inputs that are numbers, otherwise note their invalidity to stderr.
+		Using [is-number] for the validation.
+
+		USAGE:
+		echo-numeric <...input>
+		echo-lines <...input> | echo-numeric
+
+		EXAMPLE:
+
+		echo-numeric 1 2
+
+		    1
+		    2
+		    # exit status: 0
+
+		echo-numeric 1 a ''
+
+		    1
+		    [a] is not a number
+		    [] is not a number
+		    # exit status: 1
+
+		silent-stderr echo-numeric 1 a '' || :
+
+		    1
+		    # exit status: 0, it was ignored due to || :
+
+	EOF
+	return 22 # Invalid argument
+}
+
+any_invalid=no
+
+function on_input {
 	if is-number "$1"; then
 		echo "$1"
 	else
 		echo-style --error="[$1] is not a number" >/dev/stderr
-		return 22 # Invalid argument
+		any_invalid=yes
 	fi
 }
 
-function noact {
-	return 96 # No message available on STREAM
+function on_finish {
+	if test "$any_invalid" = yes; then
+		return 22 # Invalid argument
+	fi
 }
 
 source "$DOROTHY/sources/stdinargs.bash"
diff --git a/commands/echo-style b/commands/echo-style
--- a/commands/echo-style
+++ b/commands/echo-style
@@ -3,221 +3,243 @@
 source "$DOROTHY/sources/strict.bash"
 source "$DOROTHY/sources/shims.bash"
 
-# =====================================
-# Configuration
-
-source "$DOROTHY/sources/config.bash"
-
-# styles.bash provides:
-# all style variables
-load_dorothy_config 'styles.bash'
-
-# =====================================
-# Arguments
-
 # @todo
 # redo this command to only reset what was necessary, so that this works:
 # echo-style --blink '(' --green+bold='Y' '/n)')
 
-if is-help-empty "$@"; then
-	cat <<-EOF >/dev/stderr
-		USAGE:
+function echo-style() (
+	# =====================================
+	# Arguments
 
-		echo-style [-n] [--!style] [--!style+!style] value [--!style=value] [--!style+!style=value]
+	function help {
+		cat <<-EOF >/dev/stderr
+			USAGE:
 
-		EXAMPLES:
+			echo-style [...options] [--!style] [--!style+!style] value [--!style=value] [--!style+!style=value]
 
-		echo-style --bold --blue 'this is bold and blue' 'so is this' --yellow ' but this is bold and yellow'
-		echo-style --bg-red+hi-white='this is very bad' --green+bold=' while this is good'
+			OPTIONS:
+			--no-trail
+			    Disables outputting a trailing newline.
 
-		STYLES:
+			--no-color
+			    Disables styles.
 
-		Colors: black, red, green, yellow, blue, magenta, cyan, white
-		Modifiers: background_*, intense_*, background_intense_*
-		Modifier aliases: bg-*, hi-*, bg-hi-*
-		Modes: reset, bold, dim, underline, blink, invert
-		Targets: nocolor, color
-		Special: h1, e1, g1, header, error
+			EXAMPLES:
 
-		QUIRKS:
+			echo-style --bold --blue 'this is bold and blue' 'so is this' --yellow ' but this is bold and yellow'
+			echo-style --bg-red+hi-white='this is very bad' --green+bold=' while this is good'
 
-		Hyphens (-) in style names are converted to underscores (_).
+			STYLES:
 
-		If [env NO_COLOR=yes] or [env COLOR=no] then styles will be omitted.
+			Colors: black, red, green, yellow, blue, magenta, cyan, white
+			Modifiers: background_*, intense_*, background_intense_*
+			Modifier aliases: bg-*, hi-*, bg-hi-*
+			Modes: reset, bold, dim, underline, blink, invert
+			Targets: nocolor, color
+			Special: h1, e1, g1, header, error
 
-		Use [--color] to indicate the value should only be outputted if colors are.
+			QUIRKS:
 
-		Use [--nocolor] to indicate the value should only be outputted if colors are not.
+			Hyphens (-) in style names are converted to underscores (_).
 
-		value="\$(echo-style --bold="first" --nocolor=' ' --color+dim=' → ' --bold="second")"; echo "\$value"
-		# outputs colorised: first → second
+			If [env NO_COLOR=yes] or [env COLOR=no] then styles will be omitted.
 
-		value="\$(env NO_COLOR=yes echo-style --bold="first" --nocolor=' ' --color+dim=' → ' --bold="second")"; echo "\$value"
-		# outputs no-colors: first second
+			Use [--color] to indicate the value should only be outputted if colors are.
 
-		EXPLANATION:
+			Use [--nocolor] to indicate the value should only be outputted if colors are not.
 
-		[--style=value] will apply the style only to that value.
-		[--style value value] will apply the style to all subsequent values, until [--reset] is provided.
-		[--blue --bold value] will make value be blue and bold.
+			value="\$(echo-style --bold="first" --nocolor=' ' --color+dim=' → ' --bold="second")"; echo "\$value"
+			# outputs colorised: first → second
 
-		TIPS:
+			value="\$(env NO_COLOR=yes echo-style --bold="first" --nocolor=' ' --color+dim=' → ' --bold="second")"; echo "\$value"
+			# outputs no-colors: first second
 
-		[-n] at the start to avoid printing the trailing newline
-		[--h1=value] for segment headers
-		[--e1=value] for segment failure footers
-		[--g1=value] for segment success footers
-		[--error=value] for unexpected errors
-		[--header] for general headers
-		[--dim] for quoting
+			EXPLANATION:
 
-		Remember [\$'\n'] is available to you to place newlines between arguments, e.g.
-		echo-style value \$'\n' value
-	EOF
-	exit 22 # Invalid argument
-fi
+			[--style=value] will apply the style only to that value.
+			[--style value value] will apply the style to all subsequent values, until [--reset] is provided.
+			[--blue --bold value] will make value be blue and bold.
 
-# check if callar wants no trailing newline
-trail='yes'
-if test "$1" = '-n'; then
-	trail='no'
-	shift
-fi
+			TIPS:
 
-# check if no color
-color_target='/dev/stdout'
-if test "${1-}" = '--no-color'; then
-	color_target='/dev/null'
-	shift
-elif is-affirmative "${NO_COLOR-}" || test "$(echo-exit-code is-affirmative "${COLOR-}")" -eq 1; then
-	color_target='/dev/null'
-fi
+			[-n] at the start to avoid printing the trailing newline
+			[--h1=value] for segment headers
+			[--e1=value] for segment failure footers
+			[--g1=value] for segment success footers
+			[--error=value] for unexpected errors
+			[--header] for general headers
+			[--dim] for quoting
 
-# =====================================
-# Action
-
-# shared vars
-disable=''
-
-# helper
-function colorize() {
-	local style="$1" disable_style
-
-	# convert hyphens to underscores
-	style="${style//-/_}"
-
-	# expand shortcuts
-	case "$style" in
-	'bg_hi_'*) style="background_intense_${style:6}" ;;
-	*'_hi_bg') style=style="background_intense_${style:0:-6}" ;;
-
-	'fg_hi_'*) style="foreground_intense_${style:6}" ;;
-	*'_hi_fg') style=style="foreground_intense_${style:0:-6}" ;;
-
-	'fg_'*) style="foreground_${style:3}" ;;
-	*'_fg') style="foreground_${style:0:-3}" ;;
-
-	'bg_'*) style="background_${style:3}" ;;
-	*'_bg') style="background_${style:0:-3}" ;;
-
-	'hi_'*) style="intense_${style:3}" ;;
-	*'_hi') style="intense_${style:0:-3}" ;;
-	esac
-
-	# if it don't exist, it may be a foreground shorthand
-	if ! testv "$style" && testv "foreground_$style"; then
-		style="foreground_$style"
-	fi
-
-	# return the color value
-	if testv "$style"; then
-		echo -n "${!style}"
-
-		# determine the disable style
-		# don't convert to case/esac, too complicated
-		# check earlier echo did not already output the disable
-		if [[ "$style" != 'disable_'* ]]; then
-			if [[ "$style" = 'foreground_'* ]]; then
-				disable+="$disable_foreground"
-			elif [[ "$style" = 'background_'* ]]; then
-				disable+="$disable_background"
-			else
-				# custom disable, check if it exits
-				disable_style="disable_$style"
-				if testv "$disable_style"; then
-					# if it does, use it
-					disable+="${!disable_style}"
-				else
-					# otherwise use a generic reset
-					disable+="$reset"
-				fi
-			fi
-		fi
-
-	elif [[ "$style" != *'_open' ]] && [[ "$style" != *'_close' ]]; then
-		# ^ ignore errors on *_open and *_close, as they are optional
-		echo "Style [$style] is missing." >/dev/stderr
+			Remember [\$'\n'] is available to you to place newlines between arguments, e.g.
+			echo-style value \$'\n' value
+		EOF
 		return 22 # Invalid argument
-	fi
-}
+	}
 
-# act
-for arg in "$@"; do
-	flag=''
-	value=''
-
-	# check flag status
-	if test "${arg:0:2}" != '--'; then
-		# not a flag
-		echo -n "$arg"
-		continue
-	fi
-	flag="${arg:2}"
-
-	# get the flag and value combo
-	for ((i = 0; i < ${#flag}; i++)); do
-		if test "${flag:i:1}" = '='; then
-			value="${flag:i+1}"
-			flag="${flag:0:i}"
-			break
-		fi
+	# process
+	local item trail='yes' items=() use_colors
+	use_colors="$(echo-color yes -- "$@")"
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--no-trail'* | '--trail'*)
+			trail="$(get-flag-value trail --missing="$trail" -- "$item" | echo-affirmative)"
+			;;
+		'--no-color'* | '--color'*) ;; # handled by echo-color
+		*) items+=("$item") ;;
+		esac
 	done
 
-	# handle style+style combinations
-	value_target='/dev/stdout'
-	last_i=0
-	disable=''
-	for ((i = 0; i <= ${#flag}; i++)); do
-		if test "${flag:i:1}" = '+' -o "$i" -eq "${#flag}"; then
-			style="${flag:last_i:i-last_i}"
-			last_i="$((i + 1))"
-			if test "$style" = 'color'; then
-				value_target="$color_target"
-			elif test "$style" = 'nocolor'; then
-				if test "$color_target" != '/dev/null'; then
-					value_target="/dev/null"
+	# check if no color
+	color_target='/dev/stdout'
+	if test "$use_colors" = 'no'; then
+		color_target='/dev/null'
+	fi
+
+	# =====================================
+	# Configuration
+
+	source "$DOROTHY/sources/config.bash"
+
+	# styles.bash provides:
+	# all style variables
+	load_dorothy_config 'styles.bash'
+
+	# =====================================
+	# Action
+
+	# shared vars
+	local DISABLE=''
+
+	# helper
+	function colorize {
+		local style="$1" disable_style
+
+		# convert hyphens to underscores
+		style="${style//-/_}"
+
+		# expand shortcuts
+		# trunk-ignore(shellcheck/SC2249)
+		case "$style" in
+		'bg_hi_'*) style="background_intense_${style:6}" ;;
+		*'_hi_bg') style=style="background_intense_${style:0:-6}" ;;
+
+		'fg_hi_'*) style="foreground_intense_${style:6}" ;;
+		*'_hi_fg') style=style="foreground_intense_${style:0:-6}" ;;
+
+		'fg_'*) style="foreground_${style:3}" ;;
+		*'_fg') style="foreground_${style:0:-3}" ;;
+
+		'bg_'*) style="background_${style:3}" ;;
+		*'_bg') style="background_${style:0:-3}" ;;
+
+		'hi_'*) style="intense_${style:3}" ;;
+		*'_hi') style="intense_${style:0:-3}" ;;
+		esac
+
+		# if it don't exist, it may be a foreground shorthand
+		if ! testv "$style" && testv "foreground_$style"; then
+			style="foreground_$style"
+		fi
+
+		# return the color value
+		if testv "$style"; then
+			echo -n "${!style}"
+
+			# determine the disable style
+			# don't convert to case/esac, too complicated
+			# check earlier echo did not already output the disable
+			if [[ $style != 'disable_'* ]]; then
+				if [[ $style == 'foreground_'* ]]; then
+					DISABLE+="$disable_foreground"
+				elif [[ $style == 'background_'* ]]; then
+					DISABLE+="$disable_background"
+				else
+					# custom disable, check if it exits
+					disable_style="disable_$style"
+					if testv "$disable_style"; then
+						# if it does, use it
+						DISABLE+="${!disable_style}"
+					else
+						# otherwise use a generic reset
+						DISABLE+="$reset"
+					fi
 				fi
-			else
-				styles+=("$style")
-				colorize "$style" >"$color_target" || {
-					ec="$?"
-					echo "[$0 $*] FAILED" >/dev/stderr
-					exit "$ec"
-				}
-				# colorize also adjusts `disable` property
 			fi
+
+		elif [[ $style != *'_open' ]] && [[ $style != *'_close' ]]; then
+			# ^ ignore errors on *_open and *_close, as they are optional
+			echo "Style [$style] is missing." >/dev/stderr
+			return 22 # Invalid argument
+		fi
+	}
+
+	# act
+	local item flag value value_target last_i
+	for item in "${items[@]}"; do
+		flag=''
+		value=''
+
+		# check flag status
+		if test "${item:0:2}" != '--'; then
+			# not a flag
+			echo -n "$item"
+			continue
+		fi
+		flag="${item:2}"
+
+		# get the flag and value combo
+		for ((i = 0; i < ${#flag}; i++)); do
+			if test "${flag:i:1}" = '='; then
+				value="${flag:i+1}"
+				flag="${flag:0:i}"
+				break
+			fi
+		done
+
+		# handle style+style combinations
+		value_target='/dev/stdout'
+		last_i=0
+		DISABLE=''
+		for ((i = 0; i <= ${#flag}; i++)); do
+			if test "${flag:i:1}" = '+' -o "$i" -eq "${#flag}"; then
+				style="${flag:last_i:i-last_i}"
+				last_i="$((i + 1))"
+				if test "$style" = 'color'; then
+					value_target="$color_target"
+				elif test "$style" = 'nocolor'; then
+					if test "$color_target" != '/dev/null'; then
+						value_target="/dev/null"
+					fi
+				else
+					styles+=("$style")
+					colorize "$style" >"$color_target" || {
+						ec="$?"
+						echo "[$0 $*] FAILED" >/dev/stderr
+						exit "$ec"
+					}
+					# colorize also adjusts `disable` property
+				fi
+			fi
+		done
+
+		# value
+		if test -n "$value"; then
+			echo -n "$value" >"$value_target"
+			echo -n "$DISABLE" >"$color_target"
 		fi
 	done
 
-	# value
-	if test -n "$value"; then
-		echo -n "$value" >"$value_target"
-		echo -n "$disable" >"$color_target"
+	# finish up
+	# echo -n "$reset" >"$color_target"
+	if test "$trail" = 'yes'; then
+		echo >/dev/stdout
 	fi
-done
+)
 
-# finish up
-# echo -n "$reset" >"$color_target"
-if test "$trail" = 'yes'; then
-	echo >/dev/stdout
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	echo-style "$@"
 fi
diff --git a/commands/fs-rm b/commands/fs-rm
--- a/commands/fs-rm
+++ b/commands/fs-rm
@@ -1,76 +1,122 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# dependencies
-env QUIET=yes setup-util-dust
+function fs-rm() (
+	# =====================================
+	# Arguments
 
-# prepare
-prompt_remove='yes'
-if test "${1-}" = '--no-remove'; then
-	prompt_remove='no'
-fi
-path="$1"
-path_absolute="$(fs-absolute "$path")"
-conclusion=''
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Remove the paths from the file system, with some safety checks in place.
 
-# helper
-function fs_rm() {
-	# is the path missing
-	if test ! -e "$path"; then
+			USAGE:
+			fs-size [--] ...<paths>
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item paths=()
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--')
+			paths+=("$@")
+			shift $#
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) paths+=("$item") ;;
+		esac
+	done
+
+	# =====================================
+	# Dependencies
+
+	env QUIET=yes setup-util-dust
+
+	# =====================================
+	# Action
+
+	local conclusion
+	function act {
+		local path="$1"
+		path="$(fs-absolute "$path")"
+
+		# is the path missing
+		if test ! -e "$path"; then
+			conclusion="$(
+				echo-style --green="was previously removed."
+			)"
+			return
+		fi
+		# path exists
+
+		# note its size
+		find "$path" -empty -type d -delete || :
+		if test ! -e "$path"; then
+			conclusion="$(
+				echo-style --green="was only empty directories, it has been removed."
+			)"
+			return
+		fi
+		# there are leftovers
+
+		# log them
+		cat <<-EOF
+
+			$(eval-helper -- ls -la "$path")
+
+			$(eval-helper -- dust --no-percent-bars "$path")
+
+			$(eval-helper -- dust --no-percent-bars --filecount "$path")
+
+		EOF
+
+		# confirm their removal
+		if confirm-positive --ppid=$$ -- "$(
+			echo-style --notice="Confirm removal of non-empty" --bold=" $path " --notice="?"
+		)"; then
+			rm -Rfv "$path" || : # may or may not remove
+		fi
+
+		# fail if not removed
+		if test -e "$path"; then
+			conclusion="$(
+				echo-style --red="has non-empty files, it has been kept."
+			)"
+			return 66 # Directory not empty
+		fi
+
+		# success if removed
 		conclusion="$(
-			echo-style --green="was previously removed."
+			echo-style --green="had non-empty files, it was manually removed."
 		)"
-		return
-	fi
-	# path exists
+	}
 
-	# note its size
-	find "$path" -empty -type d -delete || :
-	if test ! -e "$path"; then
-		conclusion="$(
-			echo-style --green="was only empty directories, it has been removed."
-		)"
-		return
-	fi
-	# there are leftovers
+	# act with wrapping of success
+	local path title result=0
+	for path in "${paths[@]}"; do
+		title="fs-rm $(echo-quote "$path")"
+		echo-segment --h2="$title"
+		if act "$path"; then
+			echo-segment --g2="$title" " $conclusion"
+		else
+			result="$?"
+			echo-segment --e2="$title" " $conclusion"
+		fi
+	done
 
-	# log them
-	cat <<-EOF
+	return "$result"
+)
 
-		$(echo-eval ls -la "$path")
-
-		$(echo-eval dust --no-percent-bars "$path")
-
-		$(echo-eval dust --no-percent-bars --filecount "$path")
-
-	EOF
-
-	# confirm their removal
-	if test "$prompt_remove" = 'yes' && confirm-positive --ppid=$$ -- "$(
-		echo-style --notice="Confirm removal of non-empty" --bold=" $path_absolute " --notice="?"
-	)"; then
-		rm -Rfv "$path" || : # may or may not remove
-	fi
-
-	# fail if not removed
-	if test -e "$path"; then
-		conclusion="$(
-			echo-style --red="has non-empty files, it has been kept."
-		)"
-		return 66 # Directory not empty
-	fi
-
-	# success if removed
-	conclusion="$(
-		echo-style --green="had non-empty files, it was manually removed."
-	)"
-}
-
-# act with wrapping of success
-title="fs-rm $(echo-quote "$path" || :)"
-echo-segment --h2="$title"
-if fs_rm; then
-	echo-segment --g2="$title" " $conclusion"
-else
-	echo-segment --e2="$title" " $conclusion"
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	checksum "$@"
 fi
diff --git a/commands/fs-speed b/commands/fs-speed
--- a/commands/fs-speed
+++ b/commands/fs-speed
@@ -2,58 +2,106 @@
 source "$DOROTHY/sources/strict.bash"
 source "$DOROTHY/sources/ripgrep.bash"
 
-# notes
+# NOTES:
 # use /dev/random as on macos /dev/zero is instant
 # |& is because dd writes to something other than stdout
 
-# vars
-if is-mac; then
-	bs="1m" # mac only
-else
-	bs="1M" # linux only
+function fs-speed() (
+	# =====================================
+	# Arguments
+
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Calculate the speed at a directory path.
+
+			USAGE:
+			fs-speed [--] ...<paths>
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item paths=()
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--')
+			paths+=("$@")
+			shift $#
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) paths+=("$item") ;;
+		esac
+	done
+
+	# prepare
+	local megabytes_in_gigabyte=1024 bs
+	if is-mac; then
+		bs="1m" # mac only
+	else
+		bs="1M" # linux only
+	fi
+
+	# =====================================
+	# Action
+
+	local scratchpad log bytes path
+	for path in "${paths[@]}"; do
+		# start
+		echo-segment --h1="Speed Test: $path"
+
+		# prepare a temporary file in the path we wish to speed test
+		scratchpad="$(fs-temp --root="$path" --file)"
+
+		# prepare a temporary file in our temp directory, to store the output
+		# which we use for the speed analysis
+		log="$(fs-temp --directory='fs-speed' --file="$(basename "$scratchpad").log")"
+
+		# ensure they are empty
+		rm -f "$scratchpad" "$log"
+
+		# @todo add some type of DEBUG=yes flag to avoid helpers, so we can still see block and time per block calculations
+
+		# write performance
+		eval-helper --quiet \
+			--pending="$(echo-style --bold="Calculating write performance...")" \
+			--success="$(echo-style --success="Calculated write performance.")" \
+			--failure="$(echo-style --error="Failed calculate write.")" \
+			-- dd if=/dev/random of="$scratchpad" bs="$bs" count="$megabytes_in_gigabyte" |& tee "$log"
+		# trunk-ignore(shellcheck/SC2016)
+		bytes="$(rg -o '(\d+) bytes/sec' --replace '$1' <"$log" || :)"
+		if test -n "$bytes"; then
+			echo-style "Writes at " --bold="$((bytes / 1024 / 1024)) megabytes" " a second."
+		fi
+
+		# read performance
+		eval-helper --quiet \
+			--pending="$(echo-style --bold="Calculating read performance...")" \
+			--success="$(echo-style --success="Calculated read performance.")" \
+			--failure="$(echo-style --error="Failed calculate read.")" \
+			-- dd if="$scratchpad" of=/dev/null bs="$bs" |& tee "$log"
+		# trunk-ignore(shellcheck/SC2016)
+		bytes="$(rg -o '(\d+) bytes/sec' --replace '$1' <"$log" || :)"
+		if test -n "$bytes"; then
+			echo-style "Reads at " --bold="$((bytes / 1024 / 1024)) megabytes" " a second."
+		fi
+
+		# cleanup
+		rm -f "$scratchpad" "$log"
+
+		# done
+		echo-segment --g1="Speed Test: $path"
+	done
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	fs-speed "$@"
 fi
-megabytes_in_gigabyte=1024
-
-# options
-path="${1-}"
-if test -z "$path" -o ! -d "$path"; then
-	cat <<-EOF
-		USAGE:
-		fs-speed <directory>
-
-		ABOUT:
-		Performs a speed test of <directory>.
-	EOF
-	exit 1
-fi
-
-# prepare
-scratchpad="$(fs-temp --directory="$path")"
-log="$(mktemp)"
-function finish() {
-	silent rm -rf "$scratchpad" "$log"
-}
-trap finish EXIT
-
-# start
-echo-segment --h1="Speed Test: $path"
-# write performance
-echo-segment --h2="Write Performance"
-echo-eval dd if=/dev/random of="$scratchpad" bs="$bs" count="$megabytes_in_gigabyte" |& tee "$log"
-bytes="$(rg -o '(\d+) bytes/sec' --replace '$1' <"$log" || :)"
-if test -n "$bytes"; then
-	echo-style "Writes at " --bold="$((bytes / 1024 / 1024)) megabytes" " a second"
-fi
-echo-segment --g2="Write Performance"
-
-# read performance
-echo-segment --h2="Read Performance"
-echo-eval dd if="$scratchpad" of=/dev/null bs="$bs" |& tee "$log"
-bytes="$(rg -o '(\d+) bytes/sec' --replace '$1' <"$log" || :)"
-if test -n "$bytes"; then
-	echo-style "Reads at " --bold="$((bytes / 1024 / 1024)) megabytes" " a second"
-fi
-echo-segment --g2="Read Performance"
-
-# done
-echo-segment --g1="Speed Test: $path"
diff --git a/commands/get-size b/commands/get-size
--- a/commands/get-size
+++ b/commands/get-size
@@ -1,120 +1,158 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# help
-if is-help "$@"; then
-	cat <<-EOF >/dev/stderr
-		USAGE:
-		get-size
-		^ show the size information for the attached drives and their mounts
+function get-size() (
+	# =====================================
+	# Arguments
 
-		get-size <path>
-		^ if <path> is a btrfs mount, it will show the btrfs information for the mount
-		^ otherwise will show the size information for the path
-	EOF
-	exit 22 # Invalid argument
-fi
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Get the size information of all attached drives and mounts, or of specific paths.
 
-# prepare
-path="${1-}"
-if test -n "$path"; then
-	path="$(fs-absolute "$path")"
-fi
+			USAGE:
+			get-size [...paths]
 
-# act
-if test -n "$path"; then
-	if is-btrfs "$path"; then
-		# Show the structure of a filesystem
-		echo-eval sudo btrfs filesystem show
+			QUIRKS:
+			If no paths are provided, the size of all attached drives and their mounts are returned.
 
-		# Show detailed information about internal allocations in devices.
-		echo-eval sudo btrfs device usage "$path"
+			If the path is a BTRFS mount, it will show the BTRFS information for the mount.
 
-		# Show detailed information about internal filesystem usage .
-		echo-eval sudo btrfs filesystem usage "$path"
-
-		# Show space usage information for a mount point
-		echo-eval sudo btrfs filesystem df "$path"
-
-		# Show space usage via system
-		# -a, --all             include pseudo, duplicate, inaccessible file systems
-		# -h, --human-readable  print sizes in powers of 1024 (e.g., 1023M)
-		echo-eval df -ha "$path"
-
-		# Show status
-		echo-eval sudo btrfs device stats "$path"
-		echo-eval sudo btrfs scrub status "$path" || :   # if still running, exit code 1
-		echo-eval sudo btrfs balance status "$path" || : # if still running, exit code 1
-
-		# Summarize disk usage of every nested file inside the directory
-		# sudo btrfs filesystem du --summarize --human-readable "$path"
-
-		# Rename
-		# sudo btrfs filesystem label "$path" "$name"
-
-		# Change unallocated to free
-		# sudo btrfs filesystem resize max "$path"
-
-		# Defragment (balance also defrags)
-		# sudo btrfs filesystem defragment "$path"
-
-		# Balance as raid1
-		# sudo btrfs balance start --background -dconvert=raid1 -mconvert=raid1 "$path"
-
-		# Scrub (check filesystem for errors and auto-heal)
-		# sudo btrfs scrub start "$path"
-
-		# Check devices for errors
-		# WARNING: the repair mode is considered dangerous and should not be used without prior analysis of problems found on the filesystem.
-		# sudo btrfs check --repair --progress /dev/...
-
-		# Logs
-		# tail -n 1000 -f /var/log/syslog | grep "BTRFS"
-
-	elif command-exists dust; then
-		dust -d 1 "$path"
-		#     -s, --apparent-size       Use file length instead of blocks
-		#     -d, --depth <depth>                             Depth to show
-
-	elif
-		test -f "$path"
-	then
-		# path is a file
-		#   -h, --human-readable  print sizes in human readable format (e.g., 1K 234M 2G)
-		echo-eval du -h "$path"
-
-	else
-		# path is a directory
-		opts=()
-		if is-mac; then
-			opts+=(
-				'-hd'
-				1
-			)
-			# -A         Display the apparent size instead of the disk usage.  This can be helpful when operating on compressed volumes or sparse files.
-			# -a         Display an entry for each file in a file hierarchy.
-			# ^ incompatible with -d
-			# -s         Display an entry for each specified file.  (Equivalent to -d 0)
-			# ^ incompatible with -d
-			# -h         Human-readable output.
-			# -d depth   Display an entry for all files and directories depth directories deep.
-		else
-			opts+=(
-				'-aschd'
-				1
-			)
-			#   -a, --all             write counts for all files, not just directories
-			#   -s, --summarize       display only a total for each argument
-			#   -c, --total           produce a grand total
-			#   -h, --human-readable  print sizes in human readable format (e.g., 1K 234M 2G)
-			#   -d, --max-depth=N     print the total for a directory (or file, with --all)
+			If the path is a file or directory and dust is installed (can be installed via setup-util-dust), dust will be used to fetch size information, otherwise du will be used.
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
 		fi
-		echo-eval du "${opts[@]}" "$path"
-	fi
-else
-	# size of the drives
-	echo-eval sudo fdisk -l
+		return 22 # Invalid argument
+	}
 
-	# size of the mounts
-	echo-eval sudo lsblk -e7
+	# process
+	local item option_paths=()
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--')
+			option_paths+=("$@")
+			shift "$#"
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) option_paths+=("$item") ;;
+		esac
+	done
+
+	# allow no paths, as that returns details for attached volumes
+
+	# =====================================
+	# Action
+
+	local path
+	if test "$#" -eq 0; then
+		if is-mac; then
+			# size of the drives
+			eval-helper -- sudo diskutil list
+		else
+			# size of the drives
+			eval-helper -- sudo fdisk -l
+			# size of the mounts
+			eval-helper -- sudo lsblk -e7
+		fi
+	else
+		for path in "${option_paths[@]}"; do
+			path="$(fs-absolute "$path")"
+			if is-btrfs "$path"; then
+				# Show the structure of a filesystem
+				eval-helper -- sudo btrfs filesystem show
+
+				# Show detailed information about internal allocations in devices.
+				eval-helper -- sudo btrfs device usage "$path"
+
+				# Show detailed information about internal filesystem usage .
+				eval-helper -- sudo btrfs filesystem usage "$path"
+
+				# Show space usage information for a mount point
+				eval-helper -- sudo btrfs filesystem df "$path"
+
+				# Show space usage via system
+				# -a, --all             include pseudo, duplicate, inaccessible file systems
+				# -h, --human-readable  print sizes in powers of 1024 (e.g., 1023M)
+				eval-helper -- df -ha "$path"
+
+				# Show status
+				eval-helper -- sudo btrfs device stats "$path"
+				eval-helper -- sudo btrfs scrub status "$path" || :   # if still running, exit code 1
+				eval-helper -- sudo btrfs balance status "$path" || : # if still running, exit code 1
+
+				# Summarize disk usage of every nested file inside the directory
+				# sudo btrfs filesystem du --summarize --human-readable "$path"
+
+				# Rename
+				# sudo btrfs filesystem label "$path" "$name"
+
+				# Change unallocated to free
+				# sudo btrfs filesystem resize max "$path"
+
+				# Defragment (balance also defrags)
+				# sudo btrfs filesystem defragment "$path"
+
+				# Balance as raid1
+				# sudo btrfs balance start --background -dconvert=raid1 -mconvert=raid1 "$path"
+
+				# Scrub (check filesystem for errors and auto-heal)
+				# sudo btrfs scrub start "$path"
+
+				# Check devices for errors
+				# WARNING: the repair mode is considered dangerous and should not be used without prior analysis of problems found on the filesystem.
+				# sudo btrfs check --repair --progress /dev/...
+
+				# Logs
+				# tail -n 1000 -f /var/log/syslog | grep "BTRFS"
+
+			elif command-exists dust; then
+				dust -d 1 "$path"
+				#     -s, --apparent-size       Use file length instead of blocks
+				#     -d, --depth <depth>                             Depth to show
+
+			elif test -f "$path"; then
+				# path is a file
+				#   -h, --human-readable  print sizes in human readable format (e.g., 1K 234M 2G)
+				eval-helper -- du -h "$path"
+
+			else
+				# path is a directory
+				opts=()
+				if is-mac; then
+					opts+=(
+						'-hd'
+						1
+					)
+					# -A         Display the apparent size instead of the disk usage.  This can be helpful when operating on compressed volumes or sparse files.
+					# -a         Display an entry for each file in a file hierarchy.
+					# ^ incompatible with -d
+					# -s         Display an entry for each specified file.  (Equivalent to -d 0)
+					# ^ incompatible with -d
+					# -h         Human-readable output.
+					# -d depth   Display an entry for all files and directories depth directories deep.
+				else
+					opts+=(
+						'-aschd'
+						1
+					)
+					#   -a, --all             write counts for all files, not just directories
+					#   -s, --summarize       display only a total for each argument
+					#   -c, --total           produce a grand total
+					#   -h, --human-readable  print sizes in human readable format (e.g., 1K 234M 2G)
+					#   -d, --max-depth=N     print the total for a directory (or file, with --all)
+				fi
+				eval-helper -- du "${opts[@]}" "$path"
+			fi
+		done
+	fi
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	get-size "$@"
 fi
diff --git a/commands/macos-drive b/commands/macos-drive
--- a/commands/macos-drive
+++ b/commands/macos-drive
@@ -3,44 +3,87 @@ source "$DOROTHY/sources/strict.bash"
 source "$DOROTHY/sources/arrays.bash"
 requires_array_support 'mapfile'
 
-# find the installer, and download it if necessary
-function select_installer() {
-	local installers
-	mapfile -t installers < <(echo-lines -- '/Applications/Install macOS'*)
-	if test "${#installers[@]}" -eq 0; then
-		if test "${1-}" = '--downloaded'; then
-			cat <<-EOF >/dev/stderr
-				$(echo-style --error='Even after fetching the installer, we could not find it. This is unexpected.')
-				$(echo-style --error='Report an issue at: https://github.com/bevry/dorothy/issues')
-			EOF
-			return 65 # Package not installed
-		fi
-		if confirm-positive --ppid=$$ -- \
-			'An existing macOS installer was not present on your system.' $'\n' \
-			'We can automatically fetch the latest installer from Apple now if you would like?'; then
-			softwareupdate --fetch-full-installer
-			# ^ --download flag doesn't work, despite documentation
-			select_installer --downloaded # try again
-			return "$?"
-		else
-			return 125 # Operation canceled
-		fi
-	fi
-	# select
-	choose-path --required --question="Which macOS installer to use?" -- "${installers[@]}"
-}
+function macos-drive() (
+	# =====================================
+	# Arguments
 
-# select the installer
-installer="$(select_installer)"
-name="$(basename "$installer")"
-volume="$(
-	choose-option --required \
-		--question="Install $name to which volume?" \
-		-- /Volumes/*
-)"
-if confirm-bool --ppid=$$ -- "Confirm installation of $name to $volume?"; then
-	sudo "$installer/Contents/Resources/createinstallmedia" --volume "$volume"
-	exit "$?"
-else
-	exit 125 # Operation canceled
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Guides you through creating a macOS installation media.
+
+			USAGE:
+			macos-drive
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) help "An unrecognised argument was provided: $item" ;;
+		esac
+	done
+
+	# =====================================
+	# Action
+
+	# find the installer, and download it if necessary
+	function select_installer {
+		local installers=() downloaded
+		if test "${1-}" = '--downloaded'; then
+			downloaded='yes'
+		fi
+		mapfile -t installers < <(echo-lines -- '/Applications/Install macOS'*)
+		if test "${#installers[@]}" -eq 0; then
+			if test "$downloaded" = 'yes'; then
+				cat <<-EOF >/dev/stderr
+					$(echo-style --error='Even after fetching the installer, we could not find it. This is unexpected.')
+					$(echo-style --error='Report an issue at: https://github.com/bevry/dorothy/issues')
+				EOF
+				return 65 # Package not installed
+			fi
+			if confirm-positive --ppid=$$ -- \
+				'An existing macOS installer was not present on your system.' $'\n' \
+				'We can automatically fetch the latest installer from Apple now if you would like?'; then
+				softwareupdate --fetch-full-installer
+				# ^ --download flag doesn't work, despite documentation
+				select_installer --downloaded # try again
+				return "$?"
+			else
+				return 125 # Operation canceled
+			fi
+		fi
+		# select
+		choose-path --required --question="Which macOS installer to use?" -- "${installers[@]}"
+	}
+
+	# select the installer
+	local installer name volume
+	installer="$(select_installer)"
+	name="$(basename "$installer")"
+	volume="$(
+		choose-option --required \
+			--question="Install $name to which volume?" \
+			-- /Volumes/*
+	)"
+	if confirm-bool --ppid=$$ -- "Confirm installation of $name to $volume?"; then
+		sudo "$installer/Contents/Resources/createinstallmedia" --volume "$volume"
+		return "$?"
+	else
+		return 125 # Operation canceled
+	fi
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	macos-drive "$@"
 fi
diff --git a/commands/mail-sync b/commands/mail-sync
--- a/commands/mail-sync
+++ b/commands/mail-sync
@@ -1,24 +1,215 @@
 #!/usr/bin/env bash
 
-export ssl1="--ssl1"
-export ssl2="--ssl2"
+# https://github.com/imapsync/imapsync
+#
+# gmail:
+# https://support.google.com/mail/answer/7126229?hl=en#zippy=%2Cstep-change-smtp-other-settings-in-your-email-client
+# https://imapsync.lamiral.info/FAQ.d/FAQ.Gmail.txt
+#
+# apple:
+# https://support.apple.com/en-us/HT202304
+# imap.mail.me.com
 
-if test "$PORT1" -ne "993"; then
-	ssl1=""
+function mail-sync() (
+	local _types=(
+		gmail
+		icloud
+		custom
+	)
+
+	# =====================================
+	# Arguments
+
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Uses imapsync to sync two mailboxes.
+
+			USAGE:
+			mail-sync [--flags...] -- [...args to be forwarded to imapsync]
+
+			FLAGS:
+			--user1=...
+			--user2=...
+			--pass1=... aka --password1=...
+			--pass2=... aka --password2=...
+			--type1=<$(echo-join '|' -- "${_types[@]}")>
+			--type2=<$(echo-join '|' -- "${_types[@]}")>
+			If not supplied, you will be prompted.
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item args=() user1='' user2='' password1='' password2='' type1='' type2=''
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--user1='*) user1="${item:8}" ;;
+		'--user2='*) user2="${item:8}" ;;
+		'--pass1='*) password1="${item:8}" ;;
+		'--pass2='*) password2="${item:8}" ;;
+		'--password1='*) password1="${item:12}" ;;
+		'--password2='*) password2="${item:12}" ;;
+		'--type1='*) type1="${item:8}" ;;
+		'--type2='*) type2="${item:8}" ;;
+		'--')
+			args+=("$@")
+			shift $#
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) help "An unrecognised argument was provided: $item" ;;
+		esac
+	done
+
+	# =====================================
+	# Action
+
+	# origin IMAP server
+	local type1="$(
+		choose-option --required \
+			--question='Who is the host of the origin IMAP server?' \
+			--filter="$type1" -- "${_types[@]}"
+	)"
+	if test "$type1" = 'gmail'; then
+		args+=(
+			--host1 imap.gmail.com
+			--gmail1
+			--compress1
+		)
+	elif test "$type1" = 'icloud'; then
+		args+=(
+			--host1 imap.mail.me.com
+			--ssl1 --port1 993
+			--authmech1 LOGIN
+			--nocompress1
+		)
+	else
+		args+=(
+			--host1 "$(
+				ask --required \
+					--question="What is the origin IMAP server hostname?"
+			)"
+		)
+		if confirm-positive --ppid=$$ -- "Does the origin server use SSL?"; then
+			args+=(--ssl1)
+		fi
+		args+=(
+			--port1 "$(
+				ask --required \
+					--question="What is the origin IMAP server's port?"
+			)"
+		)
+	fi
+	args+=(
+		--user1 "$(
+			ask --required \
+				--question="What is the origin IMAP server's username?" \
+				--default="$user1"
+		)"
+		--password1 "$(
+			ask --required --password \
+				--question="What is the origin IMAP server's password?" \
+				--default="$password1"
+		)"
+	)
+
+	# target IMAP server
+	type2="$(
+		choose-option --required \
+			--question='Who is the host of the target IMAP server?' \
+			--filter="$type2" -- "${_types[@]}"
+	)"
+	if test "$type2" = 'gmail'; then
+		args+=(
+			--host2 imap.gmail.com
+			--gmail2
+			--compress2
+		)
+	elif test "$type2" = 'icloud'; then
+		args+=(
+			--host2 imap.mail.me.com
+			--ssl2 --port1 993
+			--authmech2 LOGIN
+			--nocompress2
+		)
+	else
+		args+=(
+			--host1 "$(
+				ask --required \
+					--question="What is the target IMAP server's hostname?"
+			)"
+		)
+		if confirm-positive --ppid=$$ -- "Does the target server use SSL?"; then
+			args+=(--ssl2)
+		fi
+		args+=(
+			--port2 "$(
+				ask --required \
+					--question="What is the target IMAP server's port?"
+			)"
+		)
+	fi
+	args+=(
+		--user2 "$(
+			ask --required \
+				--question="What is the target IMAP server's username?" \
+				--default="$user2"
+		)"
+		--password2 "$(
+			ask --required --password \
+				--question="What is the target IMAP server's password?" \
+				--default="$password2"
+		)"
+	)
+
+	# adjustments
+	if test "$type1" = 'gmail' -a "$type2" = 'icloud'; then
+		args+=(
+			# Business Gmail
+			--folderlast '[Gmail]/All Mail' --f1f2 '[Gmail]/All Mail=Archive'
+			# Personal Gmail
+			--folderlast '[Google Mail]/All Mail' --f1f2 '[Google Mail]/All Mail=Archive'
+		)
+	fi
+
+	# delete?
+	if confirm-negative --ppid=$$ -- "Delete messages from the origin IMAP server?" "Do this only once you have already completed a successful synchronisation, otherwise only the first label/folder will be applied."; then
+		args+=(--delete1 --delete1emptyfolders --expunge1) # --noexpungeaftereach
+	fi
+
+	# act and continue until success
+	# --usecache
+	# --useuid
+	local ec
+	while true; do
+		ec=0 && imapsync \
+			--automap \
+			--skipcrossduplicates \
+			--addheader --useheader 'Message-Id' \
+			--syncinternaldates \
+			--nofoldersizes --nofoldersizesatend --no-modulesversion --nolog \
+			"${args[@]}" || ec="$?"
+		if test "$ec" -eq 0; then
+			echo-style --success='Success!'
+			break
+		elif test "$ec" -eq 143; then
+			echo-style --error="Manually terminated [$ec]..."
+			break
+			return "$ec"
+		else
+			echo-style --notice="Failure with exit code [$ec] restarting..."
+		fi
+	done
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	mail-sync "$@"
 fi
-
-if test "$PORT2" -ne "993"; then
-	ssl2=""
-fi
-
-imapsync \
-	--host1 "$HOST1" --port1 "$PORT1" --user1 "$USER1" --password1 "$PASS1" \
-	--host2 "$HOST2" --port2 "$PORT2" --user2 "$USER2" --password2 "$PASS2" \
-	"$ssl1" "$ssl2" \
-	--authmech1 LOGIN --authmech2 LOGIN \
-	--exclude "Drafts|Trash|Bin|Spam|Junk|Starred|Important" \
-	--addheader --useheader "Message-Id" \
-	--syncinternaldates \
-	--nofoldersizes --nofoldersizesatend
-
-# \	--maxbytespersecond 10000
diff --git a/commands/setup-linux b/commands/setup-linux
--- a/commands/setup-linux
+++ b/commands/setup-linux
@@ -1,56 +1,97 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
+source "$DOROTHY/sources/shims.bash"
 
-# =====================================
-# Checks
+function setup-linux() (
+	# =====================================
+	# Arguments
 
-# check that an accident has not occured
-if ! is-linux; then
-	echo-style --notice="[$0] is only intended to be run on Linux systems, skipping." >/dev/stderr
-	exit 0
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Configure Linux to our expectations.
+
+			USAGE:
+			setup-linux <install|update>
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item action=''
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*)
+			if test -z "$action"; then
+				action="$item"
+			else
+				help "An unrecognised argument was provided: $item"
+			fi
+			;;
+		esac
+	done
+
+	# assert operating system
+	if ! is-linux; then
+		help "This command is only purposeful on Linux systems, which you are not running."
+	fi
+
+	# assert action
+	if test -z "$action"; then
+		help "No action provided."
+	fi
+
+	# generate log title
+	local title
+	title="$(ucf "$action") Linux"
+
+	# =====================================
+	# Action
+
+	# log
+	echo-segment --h1="$title"
+
+	# forward action to dorothy
+	dorothy "$action"
+
+	# system
+	setup-linux-raspi
+	setup-linux-recovery
+
+	# package managers and utilities
+	setup-util-apt
+	setup-util-apk
+	setup-util-yum
+	if test "$action" = 'install'; then
+		env CONFIRM=yes setup-util-gnome-software || :
+		env CONFIRM=yes setup-util-snap || :
+		env CONFIRM=yes setup-util-flatpak || :
+		env CONFIRM=yes setup-util-pamac || :
+		setup-linux-fonts
+	else
+		env ACTION=update setup-util-snap || :
+		env ACTION=update setup-util-flatpak || :
+		env ACTION=update setup-util-pamac || :
+	fi
+
+	# cross-platform
+	setup-extras "$action"
+
+	# cleanup
+	setup-linux-clean
+
+	# log
+	echo-segment --g1="$title"
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	setup-linux "$@"
 fi
-
-# =====================================
-# Action
-
-# action
-action="$(
-	choose-option \
-		--question='Do you want to install or update this system?' \
-		--filter="${1-}" -- 'install' 'update'
-)"
-
-# log
-echo-segment --h1="${action@u} Linux"
-
-# dorothy install/update
-dorothy "$action"
-
-# system
-setup-linux-raspi
-setup-linux-recovery
-
-# package managers and utilities
-setup-util-apt
-setup-util-apk
-setup-util-yum
-if test "$action" = 'install'; then
-	env CONFIRM=yes setup-util-gnome-software || :
-	env CONFIRM=yes setup-util-snap || :
-	env CONFIRM=yes setup-util-flatpak || :
-	env CONFIRM=yes setup-util-pamac || :
-	setup-linux-fonts
-else
-	env ACTION=update setup-util-snap || :
-	env ACTION=update setup-util-flatpak || :
-	env ACTION=update setup-util-pamac || :
-fi
-
-# cross-platform
-setup-extras "$action"
-
-# cleanup
-setup-linux-clean
-
-# log
-echo-segment --g1="${action@u} Linux"
diff --git a/commands/setup-mac b/commands/setup-mac
--- a/commands/setup-mac
+++ b/commands/setup-mac
@@ -1,76 +1,120 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
+source "$DOROTHY/sources/shims.bash"
 
-# =====================================
-# Prepare
+function setup-mac() (
+	# =====================================
+	# Arguments
 
-# check that an accident has not occured
-if ! is-mac; then
-	echo-style --error='[setup-mac] is only intended to be run on macOS systems...'
-	exit 2
-fi
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Configure macOS to our expectations.
 
-# Make sure CLI tools are installed
-echo-style --h2='Ensuring Apple Command Line Tool are installed...'
-while true; do
-	if ! xcode-select --install; then
-		echo-style --g2='...Apple Command Line Tool are installed.'
-		break
-	else
-		confirm --ppid=$$ -- "Press any key once the Apple Command Line Tool have been installed"
+			USAGE:
+			setup-mac <install|update>
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item action=''
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*)
+			if test -z "$action"; then
+				action="$item"
+			else
+				help "An unrecognised argument was provided: $item"
+			fi
+			;;
+		esac
+	done
+
+	# assert operating system
+	if ! is-mac; then
+		help "This command is only purposeful on macOS, which you are not running."
 	fi
-done
 
-# Make sure Xcode license is accepted
-if get-app --quiet 'Xcode' || get-app --quiet 'Xcode-beta'; then
-	echo-style --h2='Ensuring the Xcode license is accepted...'
-	sudo xcodebuild -license accept
-	echo-style --g2='...Xcode license accepted.'
-fi
-
-# action
-action="$(
-	choose-option \
-		--question='Do you want to install or update this system?' \
-		--filter="${1-}" -- 'install' 'update' || echo "${1:-install}"
-)" # or condition here is for bash v3, which choose-option will fail on, as bash v3 does not yet support arrays
-
-# =====================================
-# Start
-
-# log
-echo-segment --h1="${action@u} macOS"
-
-# dorothy install/update
-dorothy "$action"
-
-# mac
-setup-mac-brew "$action"                 # setup-util-devel done as part of this
-source "$DOROTHY/sources/environment.sh" # ensure the updated bash is available to what comes after
-if test "$action" = 'install'; then
-	setup-mac-apps
-fi
-
-# cross-platform
-setup-extras "$action"
-
-# cleanup
-setup-mac-clean
-
-# restore
-if test "$action" = 'install'; then
-	echo
-	echo-segment --h2="Configure macOS"
-	if confirm-bool --ppid=$$ -- "Would you like to also restore from backup?"; then
-		macos-state restore
+	# assert action
+	if test -z "$action"; then
+		help "No action provided."
 	fi
-	echo
-	if confirm-bool --ppid=$$ -- "Would you like to also configure macOS settings?"; then
-		macos-settings
-	fi
-	echo
-	echo-segment --g2="Configure macOS"
-fi
 
-# log
-echo-segment --g1="${action@u} macOS"
+	# generate log title
+	local title
+	title="$(ucf "$action") macOS"
+
+	# =====================================
+	# Dependencies
+
+	# Make sure CLI tools are installed
+	echo-style --h2='Ensuring Apple Command Line Tool are installed...'
+	while true; do
+		if ! xcode-select --install; then
+			echo-style --g2='...Apple Command Line Tool are installed.'
+			break
+		else
+			confirm --ppid=$$ -- "Press any key once the Apple Command Line Tool have been installed"
+		fi
+	done
+
+	# Make sure Xcode license is accepted
+	if get-app --quiet 'Xcode' || get-app --quiet 'Xcode-beta'; then
+		echo-style --h2='Ensuring the Xcode license is accepted...'
+		sudo xcodebuild -license accept
+		echo-style --g2='...Xcode license accepted.'
+	fi
+
+	# =====================================
+	# Action
+
+	# log
+	echo-segment --h1="$title"
+
+	# forward action to dorothy
+	dorothy "$action"
+
+	# mac
+	setup-mac-brew "$action"                 # setup-util-devel done as part of this
+	source "$DOROTHY/sources/environment.sh" # ensure the updated bash is available to what comes after
+	if test "$action" = 'install'; then
+		setup-mac-apps
+	fi
+
+	# cross-platform
+	setup-extras "$action"
+
+	# cleanup
+	setup-mac-clean
+
+	# restore
+	if test "$action" = 'install'; then
+		echo
+		echo-segment --h2="Configure macOS"
+		if confirm-bool --ppid=$$ -- "Would you like to also restore from backup?"; then
+			macos-state restore
+		fi
+		echo
+		if confirm-bool --ppid=$$ -- "Would you like to also configure macOS settings?"; then
+			macos-settings
+		fi
+		echo
+		echo-segment --g2="Configure macOS"
+	fi
+
+	# log
+	echo-segment --g1="$title"
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	setup-mac "$@"
+fi
diff --git a/commands/sparse-vault b/commands/sparse-vault
--- a/commands/sparse-vault
+++ b/commands/sparse-vault
@@ -1,65 +1,188 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# options
-action="$(choose-option --question='What action would you like to do?' --filter="${1-}" -- create open)"
-if test "$action" = 'open'; then
-	option_path="$(
-		ask \
-			--question='Enter its path.'
-	)"
+function sparse-vault() (
+	# =====================================
+	# Arguments
 
-	echo
-	echo 'Compacting...'
-	(hdiutil compact "$option_path" && echo 'Compacted.') || echo 'Compact failed, not an issue, continuing.'
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Helpers for working with macOS sparse vaults (encrypted DMGs).
 
-	echo
-	echo 'Mounting...'
-	hdiutil mount "$option_path"
-	echo 'Mounted.'
-else
-	option_name="$(
-		ask \
-			--question='Enter its name.'
-	)"
-	option_size="$(
-		ask \
-			--question='Enter its maximum size. E.g. MAXSIZE|100g|1t'
-	)"
-	option_type="$(
-		choose-option \
-			--question='Enter its type.' \
-			-- sparseimage sparsebundle
-	)"
+			USAGE:
+			sparse-vault mount|open <path>
 
-	vol=$(basename "$option_name")
-	version=$(sw_vers -productVersion | awk -F '.' '{print $2}')
-	create_args=(
-		'-encryption' 'AES-256'
-		'-size' "$option_size"
-		'-volname' "$vol"
+			    Mounts an existing sparse vault.
+
+			sparse-vault unmount|eject <path>
+
+			    Unmount an existing sparse vault.
+
+			sparse-vault create|make <path>
+			  [--name=...]  # Volume name
+			  [--size=...]  # Examples: MAXSIZE, 100g, 1t
+			  [--type=<sparseimage|sparsebundle>]
+
+			    Creates a new sparse vault.
+			    Note that the extension of ".<type>" appended onto the <path>.
+
+			    Use [--type=sparseimage] for a single file.
+			    Use [--type=sparsebundle] for a directory style file, made up of dozens of block files.
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item action='' path='' name='' size='' __type=''
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'create' | 'make') action='create' ;;
+		'mount' | 'open') action='mount' ;;
+		'unmount' | 'eject') action='unmount' ;;
+		'--path='*) path="${item:7}" ;;
+		'--name='*) name="${item:7}" ;;
+		'--size='*) size="${item:7}" ;;
+		'--type='*) __type="${item:7}" ;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*)
+			if test -z "$action"; then
+				action="$item"
+			elif test -z "$path"; then
+				path="$item"
+			else
+				help "An unrecognised argument was provided: $item"
+			fi
+			;;
+		esac
+	done
+
+	# ensure valid action
+	local actions=(
+		'mount'
+		'unmount'
+		'create'
 	)
+	action="$(
+		choose-option --required \
+			--question='which action to perform?' \
+			--filter="$action" -- "${actions[@]}"
+	)"
 
-	if test "$version" -ge "13"; then
-		create_args+=('-fs' 'APFS')
-	else
-		create_args+=('-fs' 'Journaled HFS+')
+	# adjustments: path
+	path="$(
+		ask --required \
+			--question='Enter its path.' \
+			--default="$path"
+	)"
+	path="$(fs-absolute "$path")"
+
+	# adjustments: create
+	if test "$action" = 'create'; then
+		name="$(
+			ask --required --confirm \
+				--question='Enter the volume name.' \
+				--default="$name"
+		)"
+		size="$(
+			ask --required --confirm \
+				--question='Enter its maximum size. E.g. MAXSIZE|100g|1t' \
+				--default="$size"
+		)"
+		__type="$(
+			choose-option \
+				--question='Enter its type.' \
+				--filter="$__type" -- sparseimage sparsebundle
+		)"
 	fi
-	if test "$option_type" = 'sparseimage'; then
-		create_args+=('-type' 'SPARSE')
-		filename="${option_name}.sparseimage"
+
+	# =====================================
+	# Helpers
+
+	function get_macos_version {
+		sw_vers -productVersion | awk -F '.' '{print $2}'
+	}
+
+	# =====================================
+	# Actions
+
+	function act_mount {
+		eval-helper --quiet \
+			--pending="$(echo-style --bold="Compacting...")" \
+			--success="$(echo-style --success="Compacted.")" \
+			--failure="$(echo-style --error="Failed to compact.")" \
+			-- hdiutil compact "$path"
+
+		eval-helper --quiet \
+			--pending="$(echo-style --bold="Mounting...")" \
+			--success="$(echo-style --success="Mounted.")" \
+			--failure="$(echo-style --error="Failed to mount.")" \
+			-- hdiutil mount "$path"
+	}
+
+	function act_create {
+		local args=(
+			'-encryption' 'AES-256'
+			'-size' "$size"
+			'-volname' "$name"
+		)
+		if test "$(get_macos_version)" -ge 13; then
+			args+=('-fs' 'APFS')
+		else
+			args+=('-fs' 'Journaled HFS+')
+		fi
+		if test "$__type" = 'sparseimage'; then
+			args+=('-type' 'SPARSE')
+			if [[ $path != *'.sparseimage' ]]; then
+				path="${path}.sparseimage"
+			fi
+		else
+			args+=('-type' 'SPARSEBUNDLE')
+			if [[ $path != *'.sparsebundle' ]]; then
+				path="${path}.sparsebundle"
+			fi
+		fi
+
+		eval-helper --quiet \
+			--pending="$(echo-style --bold="Creating...")" \
+			--success="$(echo-style --success="Created.")" \
+			--failure="$(echo-style --error="Failed to create.")" \
+			-- hdiutil create "${args[@]}" "$path"
+
+		eval-helper --quiet \
+			--pending="$(echo-style --bold="Mounting...")" \
+			--success="$(echo-style --success="Mounted.")" \
+			--failure="$(echo-style --error="Failed to mount.")" \
+			-- hdiutil mount "$path"
+	}
+
+	function act_unmount {
+		eval-helper --quiet \
+			--pending="$(echo-style --bold="Unmounting...")" \
+			--success="$(echo-style --success="Unmount.")" \
+			--failure="$(echo-style --error="Failed to unmount.")" \
+			-- hdiutil unmount "$path"
+	}
+
+	# =====================================
+	# Act
+
+	if test "$(type -t "act_$action")" = 'function'; then
+		"act_$action"
+		return "$?"
 	else
-		create_args+=('-type' 'SPARSEBUNDLE')
-		filename="${option_name}.sparsebundle"
+		echo-style --error="Action [$action] not yet implemented." >/dev/stderr
+		return 78 # Function not implemented
 	fi
+)
 
-	echo
-	echo 'Creating...'
-	hdiutil create "${create_args[@]}" "$option_name"
-	echo 'Created.'
-
-	echo
-	echo 'Mounting...'
-	hdiutil mount "$filename"
-	echo 'Mounted.'
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	twitter-helper "$@"
 fi
diff --git a/commands/svg-export b/commands/svg-export
--- a/commands/svg-export
+++ b/commands/svg-export
@@ -1,30 +1,134 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-scale=3
-dpi=1200
+function svg-export() (
+	local formats=(
+		png
+		pdf
+		svg
+		eps
+		ps
+	)
 
-function convert {
-	local svg png
+	# =====================================
+	# Arguments
 
-	svg="$1"
-	png="$(fs-filename "$svg").png" # [scale=$scale] [dpi=$dpi].png"
+	# help
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Convert SVGs into PNGs.
 
-	echo "$svg to $png"
+			USAGE:
+			svg-export [...options] -- <..inputs>
 
-	cairosvg --format "png" --scale "$scale" --dpi "$dpi" --output "$png" "$svg"
+			OPTIONS:
+			--dpi=<dpi>
+			    Set the display pixels per inch, e.g. [150].
 
-	# svg2png doesn't work well
-	# https://github.com/domenic/svg2png
-	# svg2png --scale="$scale" "$svg" "$png"
-}
+			--scale=<scale>
+			    Set the scale factor, e.g. [2] for 2x.
 
-if test "$#" -eq 0; then
-	# convert all svg files
-	find-files --extension=svg | while read -r file; do
-		convert "$file"
+			--background=<background-color>
+			    Set the background color, defaults to [white].
+			    To keep transparency, use [--background=].
+
+			--format=$(
+				echo-join '|' -- "${formats[@]}"
+			)]
+
+			EXAMPLE:
+			svg-export -- *.svg
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item files=() dpi='' scale='' background='white' format=''
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--dpi='*) dpi="${item:6}" ;;
+		'--scale='*) scale="${item:8}" ;;
+		'--bg='*) background="${item:5}" ;;
+		'--background='*) background="${item:13}" ;;
+		'--format='*) format="${item:9}" ;;
+		'--')
+			files+=("$@")
+			shift $#
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) help "An unrecognised argument was provided: $item" ;;
+		esac
 	done
-else
-	# convert a specific file
-	convert "$1"
+
+	# if no files, fail
+	if test "${#files[@]}" -eq 0; then
+		help "No files were provided."
+	fi
+
+	# ensure correct format
+	format="$(
+		choose-option --required \
+			--question='Which format to export to?' \
+			--filter="$format" -- "${formats[@]}"
+	)"
+
+	# =====================================
+	# Dependencies
+
+	# https://github.com/sharkdp/bat
+	# cat alternative
+
+	env CLI='cairosvg' \
+		PIP='cairosvg' \
+		setup-util pip
+
+	# =====================================
+	# Act
+
+	# adjustments
+	local suffix='' args=(
+		--format "$format"
+	)
+	if test -n "$scale"; then
+		suffix+=" [scale=$scale]"
+		args+=(--scale "$scale")
+	fi
+	if test -n "$dpi"; then
+		suffix+=" [dpi=$dpi]"
+		args+=(--dpi "$dpi")
+	fi
+	if test -n "$background"; then
+		suffix+=" [bg=$background]"
+		args+=(--background "$background")
+	fi
+	suffix+=".$format"
+
+	# convert
+	local input output
+	for input in "${files[@]}"; do
+		output="$(fs-filename "$input")$suffix"
+
+		eval-helper --quiet \
+			--pending="$(echo-style --bold="Converting " --code="$input" --bold=" to " --code="$output")" \
+			--success="$(echo-style --bold+green="Converted " --code="$input" --bold=" to " --code="$output")" \
+			--failure="$(echo-style --bold+red="Failed to convert " --code="$input" --bold=" to " --code="$output")" \
+			-- cairosvg "${args[@]}" --output "$output" "$input" || :
+
+		# svg2png doesn't work well
+		# https://github.com/domenic/svg2png
+		# svg2png --scale="$scale" "$input" "$output"
+	done
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	svg-export "$@"
 fi
diff --git a/commands/until-success b/commands/until-success
--- a/commands/until-success
+++ b/commands/until-success
@@ -1,8 +1,62 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-("$@") || {
-	stderr echo "failed with $? will try again in 10 seconds..."
-	sleep 5
+function until-success() (
+	# =====================================
+	# Arguments
+
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Run a command until it succeeds.
+
+			USAGE:
+			until-success [--timeout=10] [--] <command ...>
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item command=() timeout=5
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--timeout='*) timeout="${item:10}" ;;
+		'--')
+			command+=("$@")
+			shift "$#"
+			break
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) command+=("$item") ;;
+		esac
+	done
+
+	# check
+	if test "${#command[@]}" -eq 0; then
+		help "No command was provided"
+	fi
+
+	# =====================================
+	# Action
+
+	function attempt {
+		("$@") || {
+			echo-style --notice="FAILURE"
+			echo-style --code="$*" " failed with exit code " --code="$?" ", trying again in " --code="$timeout" " seconds..."
+			sleep "$timeout"
+			attempt "$@"
+		}
+	}
+	attempt "${command[@]}"
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
 	until-success "$@"
-}
+fi
