ask: first help redo for #45

diff --git a/commands/ask b/commands/ask
--- a/commands/ask
+++ b/commands/ask
@@ -4,23 +4,24 @@ source "$DOROTHY/sources/strict.bash"
 
 # help
 if is-help "$@"; then
-	stderr echo-lines \
-		'ABOUT:' \
-		'Prompt the user for an input value in a clean and robust way.' \
-		'' \
-		'USAGE:' \
-		'ask [...flags]' \
-		'ask [...flags] <--flag=...> -- <...args>' \
-		'' \
-		'FLAGS:' \
-		'Provide [--question=...] to specify the question that the prompt will be answering.' \
-		'Provide [--default=...] to specify the default value if no user specified value is entered.' \
-		'Provide [--confirm] to specify that the prompt should confirm the value before continuing.' \
-		'Provide [--password] to specify that the prompt should hide the value when entering by using password mode.' \
-		'Provide [--required] to specify that the prompt should not continue until a value is provided.' \
-		'Provide [--timeout=...] to specify a custom timeout value in seconds.' \
-		'Provide [--flag=...] -- <...args> to specify a flag to search the arguments for, to set a default value.' \
-		'Provide [--main] to not create an alternative TTY shell when promting for questions.'
+	stderr cat <<-EOF
+		ABOUT:
+		Prompt the user for an input value in a clean and robust way.
+
+		USAGE:
+		ask [...flags]
+		ask [...flags] <--flag=...> -- <...args>
+
+		FLAGS:
+		Provide [--question=...] to specify the question that the prompt will be answering.
+		Provide [--default=...] to specify the default value if no user specified value is entered.
+		Provide [--confirm] to specify that the prompt should confirm the value before continuing.
+		Provide [--password] to specify that the prompt should hide the value when entering by using password mode.
+		Provide [--required] to specify that the prompt should not continue until a value is provided.
+		Provide [--timeout=...] to specify a custom timeout value in seconds.
+		Provide [--flag=...] -- <...args> to specify a flag to search the arguments for, to set a default value.
+		Provide [--main] to not create an alternative TTY shell when promting for questions.
+	EOF
 	exit 22 # Invalid argument
 fi
 
@@ -48,7 +49,7 @@ fi
 
 # helpers
 asked='no'
-function handle_timeout () {
+function handle_timeout() {
 	if is-value "$result"; then
 		stderr echo "Ask timed out, using fallback value: $result"
 		sleep 10
@@ -64,18 +65,19 @@ function handle_timeout () {
 		return 62 # Timer expired
 	fi
 }
-function ask () {
+function ask() {
 	if test "$option_main" = 'no'; then
 		tty_auto
 	fi
 	asked='yes'
 	if test -n "${1-}"; then
-		echo -e "$1" > /dev/tty
+		echo -e "$1" >/dev/tty
 	fi
 	while true; do
-		local ec=0; read "${flags[@]}" -t 300 -r -p "> " result || ec="$?"
+		local ec=0
+		read "${flags[@]}" -t 300 -r -p "> " result || ec="$?"
 		if test "$ec" -gt 128; then
-			return 62  # Timer expired
+			return 62 # Timer expired
 		fi
 		if is-value "$result"; then
 			break
@@ -86,7 +88,7 @@ function ask () {
 	done
 	validate
 }
-function validate () {
+function validate() {
 	choices=()
 	if is-value "$result"; then
 		# we have a value, so go for it
@@ -125,7 +127,8 @@ function validate () {
 	fi
 
 	# ask
-	local ec=0; choice="$(choose-option \
+	local ec=0
+	choice="$(choose-option \
 		--question="$option_question" \
 		--timeout="$option_timeout" \
 		--main="$option_main" \
@@ -134,11 +137,11 @@ function validate () {
 
 	# check
 	if test "$ec" -eq 62; then
-		echo "Choose timed out [$ec]." > /dev/stderr
+		echo "Choose timed out [$ec]." >/dev/stderr
 		handle_timeout
-		exit "$?"  # exit with the above on success and failure
+		exit "$?" # exit with the above on success and failure
 	elif test "$ec" -ne 0; then
-		echo "Choose failed [$ec]." > /dev/stderr
+		echo "Choose failed [$ec]." >/dev/stderr
 		sleep 10
 		exit "$ec"
 	fi
@@ -150,13 +153,14 @@ function validate () {
 		exit
 	elif test "$choice" = 'custom'; then
 		# ask
-		local ec=0; ask "$option_question" || ec="$?"
+		local ec=0
+		ask "$option_question" || ec="$?"
 
 		# check for failure
 		if test "$ec" -ne 0; then
 			# timeout probably
 			handle_timeout
-			exit "$?"  # exit with the above on success and failure
+			exit "$?" # exit with the above on success and failure
 		fi
 
 		# done, success
