major and minor bugfixes
- ask, choose, confirm scripts now respect ctrl+c and other error codes once again

- setup-util now has a more sensible QUIET mode, no more success messages for quiet dependencies

- chmod-partial introduced to make setup-dorothy-permissions more readable

- is-mounted added to check if a source is mounted to a target

 - echo-(black|bold|green|red) added

 - is-empty-ls, is-empty-size added

 - get-size now shows drive size too in no arg mode

 - checksum, and is-same no longer fail due to parent directory being different (required update to fs-structure - `ls -a` to `ls -A`) and filenames causing differences in summary mode

 - cpr now supports CPR_REMOVE env var, todo will be move to flags instead of env vrs

 - ask now supports `--flag` value and accepting flags, to shortcut a common use case

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/ask b/commands/ask
--- a/commands/ask
+++ b/commands/ask
@@ -3,16 +3,25 @@ source "$DOROTHY/sources/tty.bash"
 source "$DOROTHY/sources/strict.bash"
 
 # options
-option_question="$(get-flag-value question -- "$@")"
-option_default="$(get-flag-value default -- "$@")"
-option_confirm="$(get-flag-value confirm -- "$@")"
-option_password="$(get-flag-value password -- "$@")"
-option_required="$(get-flag-value required -- "$@")"
-option_timeout="$(get-flag-value timeout -- "$@")"
+mapfile -t options < <(echo-before-separator "$@")
+option_question="$(get-flag-value question -- "${options[@]}")"
+option_default="$(get-flag-value default -- "${options[@]}")"
+option_confirm="$(get-flag-value confirm -- "${options[@]}")"
+option_password="$(get-flag-value password -- "${options[@]}")"
+option_required="$(get-flag-value required -- "${options[@]}")"
+option_timeout="$(get-flag-value timeout -- "${options[@]}")"
+option_flag="$(get-flag-value flag -- "${options[@]}")"
+mapfile -t args < <(echo-after-separator "$@")
 
 # prepare
 flags=('-r')
-result="$option_default"
+if test -n "$option_default"; then
+	result="$option_default"
+elif test -n "$option_flag"; then
+	result="$(get-flag-value "$option_flag" -- "${args[@]}")"
+else
+	result=''
+fi
 
 # helpers
 asked='no'
@@ -29,7 +38,7 @@ function handle_timeout () {
 	else
 		stderr echo 'Ask timed out, with no fallback.'
 		sleep 10
-		return 62  # Timer expired
+		return 62 # Timer expired
 	fi
 }
 function ask () {
@@ -98,10 +107,14 @@ function validate () {
 		-- "${choices[@]}")" || ec="$?"
 
 	# check
-	if test "$ec" -ne 0; then
-		# timeout probably
+	if test "$ec" -eq 62; then
+		echo "Choose timed out [$ec]." > /dev/stderr
 		handle_timeout
 		exit "$?"  # exit with the above on success and failure
+	elif test "$ec" -ne 0; then
+		echo "Choose failed [$ec]." > /dev/stderr
+		sleep 10
+		exit "$ec"
 	fi
 
 	# handle
diff --git a/commands/choose-menu b/commands/choose-menu
--- a/commands/choose-menu
+++ b/commands/choose-menu
@@ -78,11 +78,20 @@ while test "$action" != 'done'; do
 	# handle the response
 	ec=0; action="$(read-arrow --timeout="$option_timeout")" || ec="$?"
 
-	# handle special cases
-	if test "$ec" -ne 0; then
-		# timeout probably, let the caller figure it out
+	# check
+	if test "$ec" -eq 62; then
+		echo "Input timed out [$ec]." > /dev/stderr
+		sleep 10
 		exit "$ec"
-	elif is-digit "$action"; then
+	elif test "$ec" -ne 0; then
+		echo "Input failed [$ec]." > /dev/stderr
+		# some other failure
+		sleep 10
+		exit "$ec"
+	fi
+
+	# handle special cases
+	if is-digit "$action"; then
 		# number jump
 		if test "$action" -le 1; then
 			cursor=0
diff --git a/commands/choose-option b/commands/choose-option
--- a/commands/choose-option
+++ b/commands/choose-option
@@ -210,10 +210,15 @@ function act () {
 			-- "${filtered_visuals[@]}")" || ec="$?"
 
 		# check
-		if test "$ec" -ne 0; then
+		if test "$ec" -eq 62; then
 			echo "Menu timed out [$ec]." > /dev/stderr
 			sleep 10
-			exit 1
+			exit "$ec"
+		elif test "$ec" -ne 0; then
+			echo "Menu failed [$ec]." > /dev/stderr
+			# some other failure
+			sleep 10
+			exit "$ec"
 		fi
 
 		# results
diff --git a/commands/is-same b/commands/is-same
--- a/commands/is-same
+++ b/commands/is-same
@@ -51,14 +51,18 @@ fi
 option_algorithm="$(get-flag-value algorithm -- "${options[@]}")"
 option_algorithm="$(choose-option --question='Which checksum algorithm do you wish to use?' --filter="$option_algorithm" -- 'md5sum' 'shasum' 'sha256sum')"
 
-# checksum checks
-first_checksum="$(checksum --action=summary --algorithm="$option_algorithm" -- "$first_path")"
-echo "$first_checksum"
-second_checksum="$(checksum --action=summary --algorithm="$option_algorithm" -- "$second_path")"
-echo "$second_checksum"
+# checksum, trim the filenames
+mapfile -t checksums < <(checksum --no-name --action=summary --algorithm="$option_algorithm" -- "$first_path" "$second_path")  # instead of --no-name, `| cut -d' ' -f1` would have sufficed
+echo-lines "${checksums[@]}"
+
+# sanity
+if test "${#checksums[@]}" -ne 2; then
+	echo 'invalid amount of checksums'
+	exit 1
+fi
 
 # same checksum
-if test "$first_checksum" = "$second_checksum"; then
+if test "${checksums[0]}" = "${checksums[1]}"; then
 	echo "^ same because their checksums match"
 	exit 0
 fi
