redid array parsing to fix subtle issues
- TIPS.md now includes a lengthy explanation to these issues and what can be done

- overall changes:

	- `readarray` changed with what it aliases `mapfile`

	- `read -ra` calls have been changed to `mapfile -t` calls, and if they are using a custom deliminator then `echo-split` is used

	- `read` calls where appropriate have been replaced with superior ask calls, that guide the user through the command

	- `read` calls that still make sense, have had their arguments compressed to indicate intention

	- `is-string` calls have been repaced with `test -n` where appropriate

	- `is-present` calls have been repaced with `test -v` or `test -n` where appropriate

	- fixed more linting issues throughout

- `ask*` and `confirm*` changes:

	- `ask*` and `confirm*` scripts have changed their timeouts from 15 seconds to 60 seconds, and if they did not have a timeout, there is now a 1 hour timeout which is equivalent to pressing escape

	- `ask*` calls still need to be merged into a single command with options for default, required, confirm, as the swap to ask calls to guide cli arguments will cause certain ones to prompt for confirm, such as `down` for target

	- `ask-default` renamed to `ask-confirm`

- `is*` changes:

	- `is-empty-value` no longer consider `0` an empty value, as `version-compare` considers it signficant

	- `is-empty-string` considers a string only comprised of whitespace to be empty, is now also used by `is-empty-value`

- `echo*` changes:

	- added `echo-first-line` to output only the first line of stdin

	- added `echo-nonempty` for outputting only lines that aren't just whitespace

	- added `echo-split` to correct split the arguments against a custom deliminator

	- renamed `echo-lines-verbose` to `echo-verbose`

	- `echo-verbose`, `echo-nonempty`, `echo-value` all support stdin or arguments

- `setup*` changes:

	- `setup-linux-apk`, `setup-linux-apt`, `setup-linux-snap`, `setup-rust`, `setup-node` now use `setup-util` for snap and cargo installs respectively

	- `setup-util` now supports args for snaps

	- `setup-mac-apps` rewrote for latest tooling

	- `setup-node` and `setup-git` configuration prompts now use `ask*` commands

- added `fail-on-empty-stdin` to fail a pipe if the stdin became empty

- `key` fixed `encrypt` action `you` argument

- `github-release-file` now outputs all files if no filter was specified, and outputs all matching files if a filter is provided

- added `sources/stdinargs.bash` for stdin or args compatible commands

- fixed `reach-choices` from outputting failing garbage due to [a leftover debug line](https://github.com/bevry/dorothy/commit/df4fa96d4eddf4332ac91da3db893cd92bd476ec#diff-5cb5ff247d7c01022cb0e91253c9c48576d6f1b38084052016c0d2e75f94204cR62)

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/ask b/commands/ask
--- a/commands/ask
+++ b/commands/ask
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
-source "$DOROTHY/sources/strict.bash"
+# don't use strict, as we need exit codes
+# strict mode, will cause exit code of 2 to explode and be exited
+
+# todo, bring in default/fallback, confirm, and required/mandatory flags into this
 
 question="${1:?"USAGE: ask <QUESTION>"}"
 flags=()
@@ -8,5 +11,9 @@ if is-affirmative "${PASS-}"; then
 fi
 
 stderr echo -e "$question"
-read "${flags[@]}" -r -p "> " result
+read "${flags[@]}" -t 3600 -r -p "> " result
+if test "$?" -gt 128; then
+	# timeout occured
+	exit 1
+fi
 echo "$result"
diff --git a/commands/github-release-file-download b/commands/github-release-file-download
--- a/commands/github-release-file-download
+++ b/commands/github-release-file-download
@@ -5,18 +5,19 @@ source "$DOROTHY/sources/strict.bash"
 env QUIET=y setup-util-ripgrep
 
 # act
-url="$(github-release-file "$1" "$2")"
-if test -z "$url"; then
-	stderr echo "failed to determine the release file for [$1] [$2]"
-	exit 1
-fi
+github-release-file "$1" "$2" | while read -r url; do
+	if test -z "$url"; then
+		stderr echo "failed to determine the release file for [$1] [$2]"
+		exit 1
+	fi
 
-if echo "$url" | rg '.(tar|gz|zip)'; then
-	# may include arguments for subfile and destination
-	echo "extracting [$url] to [${*:3}]"
-	down-zip-file "$url" "${@:3}"
-else
-	# may include argument for destination
-	echo "downloading [$url] to [${3-}]"
-	down "$url" "${3-}"
-fi
+	if echo "$url" | rg '.(tar|gz|zip)'; then
+		# may include arguments for subfile and destination
+		echo "extracting [$url] to [${*:3}]"
+		down-zip-file "$url" "${@:3}"
+	else
+		# may include argument for destination
+		echo "downloading [$url] to [${3-}]"
+		down "$url" "${3-}"
+	fi
+done
diff --git a/commands/is-empty-string b/commands/is-empty-string
--- a/commands/is-empty-string
+++ b/commands/is-empty-string
@@ -1,3 +1,23 @@
 #!/usr/bin/env bash
+source "$DOROTHY/sources/strict.bash"
 
-test -z "${1-}"
+# prepare
+v="${1-}"
+
+# check if it is empty
+if test -z "$v"; then
+	exit 0
+fi
+
+# cycle through the characters
+for (( i=0; i<${#v}; i++ )); do
+	c="${v:$i:1}"
+	# check for non-empty characters
+	if ! test -z "$c" -o "$c" = $'\n' -o "$c" = $'\t' -o "$c" = ' '; then
+		# non-empty character found, fail
+		exit 1
+	fi
+done
+
+# all characters where empty, success
+exit 0
diff --git a/commands/read-choices b/commands/read-choices
--- a/commands/read-choices
+++ b/commands/read-choices
@@ -24,7 +24,7 @@ while test "$action" != "done"; do
 		else
 			echo -n ' ' > /dev/tty
 		fi
-		if is-string "${selections[$index]}"; then
+		if test -n "${selections[$index]}"; then
 			echo -n "*" > /dev/tty
 		else
 			echo -n ' ' > /dev/tty
@@ -64,7 +64,7 @@ while test "$action" != "done"; do
 			ii="$((ii + 1))"
 		done
 	elif test "$action" = "space" -o "$action" = "tab"; then
-		if is-string "${selections[$cursor]}"; then
+		if test -n "${selections[$cursor]}"; then
 			selections[$cursor]=""
 		else
 			choice="${choices[$cursor]}"
@@ -75,16 +75,13 @@ while test "$action" != "done"; do
 		break
 	fi
 
-	echo "$cursor/$count"
 	clear > /dev/tty
 done
 
 if is-array-partial "${selections[@]}"; then
-	stderr echo "an invalid selection occured:"
-	stderr echo-lines-verbose "${selections[@]}"
-	stderr echo
-	stderr echo "will continue as if nothing was selected..."
-	selections=()
+	stderr echo "An invalid selection occured, this should not be possible."
+	stderr echo-verbose "${selections[@]}"
+	exit 1
 fi
 
 if is-array-empty "${selections[@]}"; then
