more bash v3 compat

diff --git a/commands/ask b/commands/ask
--- a/commands/ask
+++ b/commands/ask
@@ -1,7 +1,12 @@
 #!/usr/bin/env bash
 # shellcheck disable=SC2164,SC1091
-source "$DOROTHY/sources/tty.bash"
 source "$DOROTHY/sources/strict.bash"
+source "$DOROTHY/sources/tty.bash"
+source "$DOROTHY/sources/arrays.bash"
+if test "$ARRAYS" = 'no'; then
+	echo "Array support required for: $0 $*" >/dev/stderr
+	exit 95 # Operation not supported
+fi
 
 # help
 if is-help "$@"; then
diff --git a/commands/cpr b/commands/cpr
--- a/commands/cpr
+++ b/commands/cpr
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
+source "$DOROTHY/sources/arrays.bash"
+if test "$ARRAYS" = 'no'; then
+	echo "Array support required for: $0 $*" >/dev/stderr
+	exit 95 # Operation not supported
+fi
 
 # @todo figure out how to make --eval compatible with paths that have spaces
 
diff --git a/commands/setup-dorothy-permissions b/commands/setup-dorothy-permissions
--- a/commands/setup-dorothy-permissions
+++ b/commands/setup-dorothy-permissions
@@ -5,6 +5,11 @@ source "$DOROTHY/sources/nullglob.bash"
 if test "$NULLGLOB" = 'no' -o "$GLOBSTAR" = 'no'; then
 	exit 95 # Operation not supported
 fi
+source "$DOROTHY/sources/arrays.bash"
+if test "$ARRAYS" = 'no'; then
+	echo "Array support required for: $0 $*" >/dev/stderr
+	exit 95 # Operation not supported
+fi
 
 # perform the act
 cd "$DOROTHY" || exit 2 # No such file or directory
