secret: vault options, fix clear, fix returns
- clear now works

- returns are now handled correctly

- OTP codes work again

- initial work for item selection, but too complicated for now

- add `echo-values` and `is-values`, and update `ask-options` to use them, to ensure that falsey values are not being asked for

diff --git a/commands/ask-options b/commands/ask-options
--- a/commands/ask-options
+++ b/commands/ask-options
@@ -3,13 +3,27 @@ source "$DOROTHY/sources/strict.bash"
 
 # extract options
 if test "$#" -eq 3; then
-	# supports the case where the options are squashed together into one argument, yet still maintaining newlines
-	mapfile -t options <<<"$3"
+	if is-value "$3"; then
+		# supports the case where the options are squashed together into one argument, yet still maintaining newlines
+		mapfile -t options <<<"$3"
+	else
+		options=()
+	fi
 else
 	# supports the case where each option is its own argument
 	options=("${@:3}")
 fi
 
+# keep only positive
+mapfile -t options <<<"$(echo-values "${options[@]}")"
+
+# check that options were provided
+if ! is-values "${options[@]}"; then
+	stderr echo "unable to provide you options for the question [$1]"
+	exit 1
+fi
+
+# check if a default value was provided
 if is-value "${2-}"; then
 	if ! is-needle "$2" "${options[@]}"; then
 		stderr echo "invalid selection [$2], the selection must be one of these:"
diff --git a/commands/secret b/commands/secret
--- a/commands/secret
+++ b/commands/secret
@@ -80,7 +80,7 @@ function secret_write() {
 function secret_clear() {
 	t="$(mktemp)"
 	mv "$database" "$t"
-	sudo rm -Rf "$SECRETS/*"
+	sudo rm -Rf "$SECRETS/"*
 	mv "$t" "$database"
 }
 
@@ -117,10 +117,10 @@ function secret_signout() {
 	if is-empty-string "${OP_SESSION-}"; then
 		if secret_exists "OP_SESSION"; then
 			OP_SESSION="$(secret_read OP_SESSION)"
-			ok op signout --session="$OP_SESSION"
+			op signout --session="$OP_SESSION" 2>&1 || :
 		fi
 	else
-		ok op signout --session="$OP_SESSION"
+		op signout --session="$OP_SESSION" 2>&1 || :
 	fi
 	secret_delete "OP_SESSION"
 	secret_delete "OP_SUBDOMAIN"
@@ -139,32 +139,50 @@ function secret_signin() {
 					secret_write "OP_SUBDOMAIN" "$OP_SUBDOMAIN"
 				fi
 			fi
+			stderr echo "Logging into [$OP_SUBDOMAIN], if that is incorrect use [secret clear]."
 			# email
 			email="$(ask-mandatory 'What is your 1password email? This is not stored.')"
 			# secret
 			key="$(ask-mandatory 'What is your 1password account key? This is not stored.')"
 			# signin
-			OP_SESSION="$(op signin "$OP_SUBDOMAIN" "$email" "$key" --output=raw)"
+			OP_SESSION="$(op signin "$OP_SUBDOMAIN" "$email" "$key" --output=raw)"  # don't pipe to anything else, as it breaks the OTP question
+			if test "$?" -ne 0; then
+				stderr echo "ERROR: Failed to sign into [$OP_SUBDOMAIN] via the email [$email] and account key [$key]."
+				stderr echo "$OP_SESSION"
+				return 1
+			fi
 			secret_write "OP_SESSION" "$OP_SESSION"
+			stderr echo 'Signed in successfully.'
 		fi
 	fi
 }
 
 function secret_grab() {
-	vault="$1"
-	item="$2"
 	secret_signin
-	result="$(op get item "$item" --vault="$vault" --session="$OP_SESSION" 2>&1 || :)"
+	vault="${1-}"
+	item="${2-}"
+	if is-empty-value "$vault"; then
+		# fetch available values
+		result="$(op list vaults --session="$OP_SESSION" 2>&1 || :)"
+	else
+		if is-empty-value "$item"; then
+			# fetch available items
+			result="$(op list items --vault="$vault" --session="$OP_SESSION" 2>&1 || :)"
+		else
+			# fetch item
+			result="$(op get item "$item" --vault="$vault" --session="$OP_SESSION" 2>&1 || :)"
+		fi
+	fi
+	# process result
 	if is-empty-value "$result"; then
-		stderr echo "ERROR: Failed to fetch item ${item} from vault ${vault}."
-		stderr echo "Nothing was returned: [$item]=[$result]"
+		stderr echo "ERROR: Nothing was returned: value=[$vault], item=[$item], result=[$result]"
 		return 1
 	elif [[ "$result" = *'signed in'* ]]; then
-		stderr echo "ERROR: Failed to fetch item ${item} from vault ${vault}."
+		stderr echo "ERROR: Unable to return: value=[$vault], item=[$item]"
 		stderr echo "Session expired, run [secret signin] and try again."
 		return 1
 	elif [[ "$result" = *'ERROR'* ]]; then
-		stderr echo "ERROR: Failed to fetch item ${item} from vault ${vault}."
+		stderr echo "ERROR: Failed to return: value=[$vault], item=[$item]"
 		stderr echo "$result"
 		return 1
 	else
@@ -173,11 +191,37 @@ function secret_grab() {
 }
 
 function secret_fetch() {
-	vault="$1"
-	item="$2"
+	vault="${1-}"
+	if is-empty-value "$vault"; then
+		# fetch available vaults
+		data="$(secret_grab)"
+		if test "$?" -ne 0 || is-empty-value "$data"; then
+			return 1
+		fi
+		# output options
+		echo "$data" | jq -r '.[].name' # | (.uuid, .name)'
+		return
+	fi
+	item="${2-}"
+	if is-empty-value "$item"; then
+		stderr echo "ERROR: Vault was provided [$vault] but item was missing [$item]"
+		return 1
+		# # fetch available items
+		# data="$(secret_grab "$vault")"
+		# if test "$?" -ne 0 || is-empty-value "$data"; then
+		# 	return 1
+		# fi
+		# # output options
+		# echo "$data" | jq -r '.[] | (.uuid, .overview.title)'
+		# return
+	fi
 	field="${3-}"
 	data="$(secret_grab "$vault" "$item")"
-	# fetch value, or fetch options
+	if test "$?" -ne 0; then
+		return 1
+	fi
+
+	# fetch field value
 	if is-value "$field"; then
 		# fetch based on section
 		result="$(echo "$data" | jq -r --arg key "$field" ".details.sections[] | select(.fields).fields[] | select(.t==\$key).v")"
@@ -192,6 +236,7 @@ function secret_fetch() {
 		# output
 		echo -n "$result"
 	else
+		# fetch available field values
 		# fetch based on section
 		echo "$data" | jq -r ".details.sections[] | select(.fields).fields[] | .t"
 		# fetch based on standalone
@@ -203,7 +248,7 @@ function secret_fetch() {
 
 function secret_map() {
 	secret="$(ask-mandatory 'What shall the name of the environment variable (secret) be?' "${1-}")"
-	vault="$(ask-mandatory 'What vault should it map to?' "${2:-personal}")"
+	vault="$(ask-options 'What vault should it map to?' "${2-}" "$(secret_fetch)")"
 	item="$(ask-mandatory 'What item should it map to?' "${3-}")"
 	field="$(ask-options 'What field should it map to?' "${4-}" "$(secret_fetch "$vault" "$item")")"
 	result="$(sudo jq -r \
@@ -292,7 +337,7 @@ if test -n "${1-}"; then
 	if test "$1" = "env"; then
 		secret_env "${@:2}"
 	elif test "$1" = "clear" -o "$1" = "delete"; then
-		if is-string "$2"; then
+		if is-string "${2-}"; then
 			secret_delete "${@:2}"
 		else
 			secret_clear
