redid array parsing to fix subtle issues
- TIPS.md now includes a lengthy explanation to these issues and what can be done

- overall changes:

	- `readarray` changed with what it aliases `mapfile`

	- `read -ra` calls have been changed to `mapfile -t` calls, and if they are using a custom deliminator then `echo-split` is used

	- `read` calls where appropriate have been replaced with superior ask calls, that guide the user through the command

	- `read` calls that still make sense, have had their arguments compressed to indicate intention

	- `is-string` calls have been repaced with `test -n` where appropriate

	- `is-present` calls have been repaced with `test -v` or `test -n` where appropriate

	- fixed more linting issues throughout

- `ask*` and `confirm*` changes:

	- `ask*` and `confirm*` scripts have changed their timeouts from 15 seconds to 60 seconds, and if they did not have a timeout, there is now a 1 hour timeout which is equivalent to pressing escape

	- `ask*` calls still need to be merged into a single command with options for default, required, confirm, as the swap to ask calls to guide cli arguments will cause certain ones to prompt for confirm, such as `down` for target

	- `ask-default` renamed to `ask-confirm`

- `is*` changes:

	- `is-empty-value` no longer consider `0` an empty value, as `version-compare` considers it signficant

	- `is-empty-string` considers a string only comprised of whitespace to be empty, is now also used by `is-empty-value`

- `echo*` changes:

	- added `echo-first-line` to output only the first line of stdin

	- added `echo-nonempty` for outputting only lines that aren't just whitespace

	- added `echo-split` to correct split the arguments against a custom deliminator

	- renamed `echo-lines-verbose` to `echo-verbose`

	- `echo-verbose`, `echo-nonempty`, `echo-value` all support stdin or arguments

- `setup*` changes:

	- `setup-linux-apk`, `setup-linux-apt`, `setup-linux-snap`, `setup-rust`, `setup-node` now use `setup-util` for snap and cargo installs respectively

	- `setup-util` now supports args for snaps

	- `setup-mac-apps` rewrote for latest tooling

	- `setup-node` and `setup-git` configuration prompts now use `ask*` commands

- added `fail-on-empty-stdin` to fail a pipe if the stdin became empty

- `key` fixed `encrypt` action `you` argument

- `github-release-file` now outputs all files if no filter was specified, and outputs all matching files if a filter is provided

- added `sources/stdinargs.bash` for stdin or args compatible commands

- fixed `reach-choices` from outputting failing garbage due to [a leftover debug line](https://github.com/bevry/dorothy/commit/df4fa96d4eddf4332ac91da3db893cd92bd476ec#diff-5cb5ff247d7c01022cb0e91253c9c48576d6f1b38084052016c0d2e75f94204cR62)

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/ask-mandatory b/commands/ask-mandatory
--- a/commands/ask-mandatory
+++ b/commands/ask-mandatory
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-source "$DOROTHY/sources/strict.bash"
+# don't use strict, as we need exit codes
+# strict mode, will cause exit code of 2 to explode and be exited
 
 question="${1:-?"USAGE: ask-mandatory <QUESTION> [an-existing-answer]"}"
 result="${2-}"
@@ -8,10 +9,16 @@ if is-affirmative "${PASS-}"; then
 	flags+=('-s')
 fi
 
-if test -z "$result"; then
+if is-empty-value "$result"; then
 	stderr echo -e "$question"
-	while test -z "$result"; do
-		read "${flags[@]}" -r -p "> " result
+	while true; do
+		read "${flags[@]}" -t 300 -r -p "> " result
+		if test "$?" -gt 128; then
+			exit 1  # failure
+		fi
+		if is-value "$result"; then
+			break
+		fi
 	done
 fi
 
