arm64 and x86_64 support for apple silicon
- accomodations for outdated bash
  - array, nullglob, extglob, and globstar now export a variable that can be checked for the sourcing script to fail on if necessary
  - expand-path is now split into bash and zsh implementations

- support for when all deps are installed
  - curl usage changed to `fetch` or `down` where appropriate
  - git is checked in setup-dorothy

- setup-paths-commands now ensures HOMEBREW_* env vars are set, and now operates without the need for paths to already be set
  - this will eventually mean a lot of sourcing `essentials.sh` may now be unnecessary

- as nvm now supports apple arm, we now also support falling back to x86_64 when node arm builds aren't available

- sources renamed
  - `functions.*` renamed to `history.*`
  - `getshell` renamed to `shell`

- `fs-absolute` now checks that fish exists before trying to call it

- `setup-util-gocryptfs` now `mkdir -p /usr/local/bin` in case brew isn't installed there

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/brew b/commands/brew
--- a/commands/brew
+++ b/commands/brew
@@ -1,6 +1,21 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
-source "$DOROTHY/sources/essentials.sh"
+# we can assume [HOMEBREW_ARCH, HOMEBREW_PREFIX] have already been provided
 
+# Without this command, using HOMEBREW_ARCH=x86_64 on Apple Silicon will fail with:
+# ```
+# Error: Cannot install in Homebrew on ARM processor in Intel default prefix (/usr/local)!
+# Please create a new installation in /opt/homebrew using one of the
+# "Alternative Installs" from:
+#   https://docs.brew.sh/Installation
+# You can migrate your previously installed formula list with:
+#   brew bundle dump
 # brew on desired architecture
-arch "-${HOMEBREW_ARCH:-x86_64}" "${HOMEBREW_PREFIX:-"/usr/local"}/bin/brew" "$@"
+# ```
+
+if test -x "${HOMEBREW_PREFIX}/bin/brew"; then
+	arch "-${HOMEBREW_ARCH}" "${HOMEBREW_PREFIX}/bin/brew" "$@"
+else
+	stderr echo 'brew not installed'
+	exit 1
+fi
diff --git a/commands/setup-paths-commands b/commands/setup-paths-commands
--- a/commands/setup-paths-commands
+++ b/commands/setup-paths-commands
@@ -40,12 +40,16 @@ function vset {
 }
 function rubygems {
 	vset GEM_HOME "$HOME/.gem"
-	if command-exists "$1"; then
+	if test -x "$1"; then
 		rubydirs="$("$1" environment gempath | tr ":" "\n")"
 		for i in $rubydirs; do
 			vadd PATH "$i/bin"
 		done
 	fi
+}
+function command-exists {
+	stderr echo "cannot use [command-exists $*] yet, as paths have not been setup yet"
+	exit 1
 }
 
 # reset
@@ -80,14 +84,68 @@ if is-dir "/usr/local/man"; then
 fi
 
 # Homebrew
-if is-brew; then
-	if test -z "${HOMEBREW_PREFIX-}"; then
-		export HOMEBREW_PREFIX; HOMEBREW_PREFIX="/usr/local"
-		# HOMEBREW_PREFIX="$(brew --prefix)"
+if is-mac; then
+	# ensure the brew vars [HOMEBREW_ARCH, HOMEBREW_PREFIX, HOMEBREW_CELLAR, HOMEBREW_REPOSITORY, HOMEBREW_SHELLENV_PREFIX] are set even if brew is not yet installed
+	if test -z "${HOMEBREW_ARCH-}"; then
+		export HOMEBREW_ARCH
+		if test "$(uname -p)" = 'arm' -o "$(uname -m)" = 'arm64'; then
+			HOMEBREW_ARCH='arm64e'
+		else
+			HOMEBREW_ARCH='x86_64'
+		fi
+		vset HOMEBREW_ARCH "$HOMEBREW_ARCH"
 	fi
-	# if test -z "${HOMEBREW_CELLAR-}"; then
-	# 	export HOMEBREW_CELLAR; HOMEBREW_CELLAR="$("$HOMEBREW_PREFIX/bin/brew" --cellar)"
-	# fi
+	if test -z "${HOMEBREW_PREFIX-}"; then
+		if test "$HOMEBREW_ARCH" = 'arm64e'; then
+			export HOMEBREW_PREFIX; HOMEBREW_PREFIX='/opt/homebrew'
+		else
+			export HOMEBREW_PREFIX; HOMEBREW_PREFIX='/usr/local'
+		fi
+		vset HOMEBREW_PREFIX "$HOMEBREW_PREFIX"
+	fi
+	if test -z "${HOMEBREW_CELLAR-}"; then
+		export HOMEBREW_CELLAR
+		if test -x "${HOMEBREW_PREFIX}/bin/brew"; then
+			HOMEBREW_CELLAR="$(${HOMEBREW_PREFIX}/bin/brew --cellar)"
+		else
+			HOMEBREW_CELLAR="$HOMEBREW_PREFIX/Cellar"
+		fi
+		vset HOMEBREW_CELLAR "$HOMEBREW_CELLAR"
+	fi
+	if test -z "${HOMEBREW_REPOSITORY-}"; then
+		export HOMEBREW_REPOSITORY;
+		if test -x "${HOMEBREW_PREFIX}/bin/brew"; then
+			HOMEBREW_REPOSITORY="$(${HOMEBREW_PREFIX}/bin/brew --repo)"
+		else
+			HOMEBREW_REPOSITORY="$HOMEBREW_PREFIX"
+		fi
+		vset HOMEBREW_REPOSITORY "$HOMEBREW_REPOSITORY"
+	fi
+	if test -z "${HOMEBREW_SHELLENV_PREFIX-}"; then
+		export HOMEBREW_SHELLENV_PREFIX; HOMEBREW_SHELLENV_PREFIX="$HOMEBREW_PREFIX"
+		vset HOMEBREW_SHELLENV_PREFIX "$HOMEBREW_SHELLENV_PREFIX"
+	fi
+fi
+# if homebrew is installed, then add its paths
+# we can't use command-exists yet, as the paths haven't been setup for it
+if test -x "${HOMEBREW_PREFIX}/bin/brew"; then
+	# /usr/local already added, so only add these if different
+	if test "$HOMEBREW_PREFIX" != '/usr/local'; then
+		if is-dir "$HOMEBREW_PREFIX/bin"; then
+			vadd PATH "$HOMEBREW_PREFIX/bin"
+		fi
+		if is-dir "$HOMEBREW_PREFIX/sbin"; then
+			vadd PATH "$HOMEBREW_PREFIX/sbin"
+		fi
+	fi
+
+	# add the rest
+	if is-dir "$HOMEBREW_PREFIX/share/man"; then
+		vadd MANPATH "$HOMEBREW_PREFIX/share/man"
+	fi
+	if is-dir "$HOMEBREW_PREFIX/share/info"; then
+		vadd INFOPATH "$HOMEBREW_PREFIX/share/info"
+	fi
 
 	# for compilers to find homebrew
 	vadd LDFLAGS "-L$HOMEBREW_PREFIX/lib"
@@ -163,7 +221,7 @@ if is-brew; then
 	fi
 
 	# Node
-	nodedirs="$(expand-path "$HOMEBREW_PREFIX/Cellar/node/*/bin")"
+	nodedirs="$(expand-path "$HOMEBREW_CELLAR/node/*/bin")"
 	for nodedir in $nodedirs; do
 		vadd PATH "$nodedir"
 	done
@@ -237,16 +295,21 @@ if is-dir "$HOME/.cargo/bin"; then
 fi
 
 # Go
-if command-exists go; then
+export GO=''; if test -n "${HOMEBREW_PREFIX-}" -a -x "$HOMEBREW_PREFIX/bin/go"; then
+	GO="$HOMEBREW_PREFIX/bin/go"
+else
+	GO="$(first-executable /usr/local/bin/go /bin/go || :)"
+fi
+if test -n "$GO" -a -x "$GO"; then
 	# root: where go is installed
-	export GOROOT; GOROOT="$(echo-or-fail go env GOROOT || first-path "${HOMEBREW_CELLAR-}/go")"
+	export GOROOT; GOROOT="$(echo-or-fail $GO env GOROOT || first-path "${HOMEBREW_CELLAR:-"$HOME"}/go")"
 	if is-dir "$GOROOT/libexec"; then
 		GOROOT="$GOROOT/libexec"
 	fi
 	vset GOROOT "$GOROOT"
 
 	# path: where modules are installed
-	export GOPATH; GOPATH="$(echo-or-fail go env GOPATH || echo-mkdirp "$HOME/go")"
+	export GOPATH; GOPATH="$(echo-or-fail $GO env GOPATH || echo-mkdirp "$HOME/go")"
 	vset GOPATH "$GOPATH"
 	if is-dir "$GOPATH/bin"; then
 		vadd PATH "$GOPATH/bin"
@@ -268,7 +331,12 @@ if is-dir "$HOME/.clojure/clojure-1.8"; then
 fi
 
 # Yarn
-if command-exists yarn; then
+export YARN=''; if test -n "${HOMEBREW_PREFIX-}" -a -x "$HOMEBREW_PREFIX/bin/yarn"; then
+	YARN="$HOMEBREW_PREFIX/bin/yarn"
+else
+	YARN="$(first-executable /usr/local/bin/yarn /bin/yarn || :)"
+fi
+if test -n "$YARN" -a -x "$YARN"; then
 	vadd PATH "$(yarn global bin)"
 fi
 
