`btrfs` support, `choose-option` confirmations
- choose-option:
    - now uses VISUAL for confirmations
    - `--confirm` will now also confirm if only one result
- get-devices:
    - rewrote to support multiple returns, selection, and filtering, this makes it an incredibly powerful tool for understanding devices, filtering devices, selecting devices, and validating devices
- get-size, get-filesystem
    - cleanup as `btrfs-helper` is now more powerful
- gid:
    - comments about its complexity
- btrfs-helper:
    - rewrote to make use of new `get-devices` and `mount-helper`, which now empowers new and validated commands
- mount-helper:
    - add  and verify btrfs support
    - redid ownership/root distinction, now works correctly, add `--own` flag

diff --git a/commands/btrfs-helper b/commands/btrfs-helper
--- a/commands/btrfs-helper
+++ b/commands/btrfs-helper
@@ -5,6 +5,299 @@ function btrfs-helper() (
 	require_array 'mapfile'
 
 	# =====================================
+	# Actions
+
+	function act_devices {
+		get-devices --filesystem=btrfs "$@"
+	}
+	function act_info {
+		# @todo have [get-size] use this perhaps
+		# Get details about a btrfs device / filesystem
+		local temp existing_node existing_mount path
+
+		# fetch existing
+		temp="$(
+			get-devices --result=node,mount --node --uuid --filesystem=btrfs \
+				--select="$(echo-style --positive='Which btrfs device / filesystem to get information about?')"
+		)"
+		IFS=$'\t' read -rd $'\n' existing_node existing_mount <<<"$temp"
+		path="${existing_mount:-"$existing_node"}"
+
+		# Show the structure of a filesystem
+		# usage: btrfs filesystem show [options] [<path>|<uuid>|<device>|label]
+		eval-helper --no-quiet \
+			-- sudo-helper \
+			-- btrfs filesystem show "$path"
+
+		if test -n "$existing_mount"; then
+			# Show detailed information about internal allocations in devices.
+			# usage: btrfs device usage [options] <path> [<path>..]
+			eval-helper --no-quiet \
+				-- sudo-helper \
+				-- btrfs device usage "$existing_mount"
+
+			# Show detailed information about internal filesystem usage .
+			# usage: btrfs filesystem usage [options] <path> [<path>..]
+			eval-helper --no-quiet \
+				-- sudo-helper \
+				-- btrfs filesystem usage "$existing_mount"
+
+			# Show space usage information for a mount point
+			# usage: btrfs filesystem df [options] <path>
+			eval-helper --no-quiet \
+				-- sudo-helper \
+				-- btrfs filesystem df "$existing_mount"
+
+			# Show space usage via system
+			# -a, --all             include pseudo, duplicate, inaccessible file systems
+			# -h, --human-readable  print sizes in powers of 1024 (e.g., 1023M)
+			eval-helper --no-quiet \
+				-- sudo-helper \
+				-- df -ah "$existing_mount"
+		fi
+
+		# Show status
+		eval-helper --no-quiet \
+			-- sudo-helper \
+			-- btrfs device stats "$path"
+		eval-helper --no-quiet \
+			-- sudo-helper \
+			-- btrfs scrub status "$path" || : # if still running, exit code 1
+		eval-helper --no-quiet \
+			-- sudo-helper \
+			-- btrfs balance status "$path" || : # if still running, exit code 1
+
+		# Summarize disk usage of every nested file inside the directory
+		# eval-helper --no-quiet \
+		#	-- sudo-helper \
+		#	-- btrfs filesystem du --summarize --human-readable "$path"
+
+		# Rename
+		# eval-helper --no-quiet \
+		#	-- sudo-helper \
+		#	-- btrfs filesystem label "$path" "$name"
+
+		# Change unallocated to free
+		# eval-helper --no-quiet \
+		#	-- sudo-helper \
+		#	-- btrfs filesystem resize max "$path"
+
+		# Defragment (balance also defrags)
+		# eval-helper --no-quiet \
+		#	-- sudo-helper \
+		#	-- btrfs filesystem defragment "$path"
+
+		# Balance as raid1
+		# eval-helper --no-quiet \
+		#	-- sudo-helper \
+		#	-- btrfs balance start --background -dconvert=raid1 -mconvert=raid1 "$path"
+
+		# Scrub (check filesystem for errors and auto-heal)
+		# eval-helper --no-quiet \
+		#	-- sudo-helper \
+		#	-- btrfs scrub start "$path"
+
+		# Check devices for errors
+		# WARNING: the repair mode is considered dangerous and should not be used without prior analysis of problems found on the filesystem.
+		# eval-helper --no-quiet \
+		#	-- sudo-helper \
+		#	-- btrfs check --repair --progress /dev/...
+
+		# Logs
+		# tail -n 1000 -f /var/log/syslog | grep --fixed-strings --regexp='BTRFS'
+	}
+	function act_new {
+		# Reformat a device as btrfs
+		local node label
+		node="$(
+			get-devices --result=node --no-mount \
+				--select="$(echo-style --negative='Which device to erase and format as btrfs?')" \
+				--missing='Did not find any non-mounted devices.'
+		)"
+		label="$(
+			ask --required \
+				--question="What label to use for the new btrfs filesystem that will be attached to the device $(echo-style --invert="$node") ?"
+		)"
+
+		# format
+		eval-helper --no-quiet --wrap --confirm \
+			-- sudo-helper \
+			-- mkfs.btrfs -f -L "$label" "$node"
+	}
+	function act_mount {
+		# Mount a btrfs device
+		local node target
+		node="$(
+			get-devices --result=node --no-mount --filesystem=btrfs \
+				--select="$(echo-style --positive='Which btrfs device to mount?')" \
+				--missing='Did not find any non-mounted btrfs devices.'
+		)"
+		target="$(
+			ask --required \
+				--question="Which target path to mount $(echo-style --invert="$node") ?"
+		)"
+
+		# mount
+		mount-helper --btrfs --share="$node" --target="$target" --mount
+	}
+	function act_unmount {
+		# Unmount a btrfs device
+		local existing_mount
+		existing_mount="$(
+			get-devices --result=mount --mount --filesystem=btrfs \
+				--select="$(echo-style --positive='Which btrfs filesystem to unmount?')" \
+				--missing='Did not find any mounted btrfs devices.'
+		)"
+
+		# mount
+		mount-helper --btrfs --target="$existing_mount" --unmount
+	}
+	function act_add {
+		# Add a device to a btrfs filesystem
+		local temp existing_node existing_uuid existing_mount extra_node extra_uuid
+
+		# fetch existing
+		temp="$(
+			get-devices --result=node,uuid,mount --node --uuid --mount --count --filesystem=btrfs \
+				--select="$(echo-style --positive='Which btrfs filesystem to add the new device to?')" \
+				--missing='You must mount the btrfs filesystem first before you can add to it.'
+		)"
+		IFS=$'\t' read -rd $'\n' existing_node existing_uuid existing_mount <<<"$temp"
+
+		# fetch addition
+		temp="$(
+			get-devices --result=node,uuid --no-mount \
+				--select="$(echo-style --negative='WHICH DEVICE TO ERASE AND ADD TO THE BTRFS FILESYSTEM?')" \
+				--missing='Did not find any non-mounted devices.'
+		)"
+		IFS=$'\t' read -rd $'\n' extra_node extra_uuid <<<"$temp"
+
+		# validate
+		if test "$existing_node" = "$extra_node"; then
+			echo-style --error='You cannot add the same device to itself.'
+			return 22 # Invalid argument
+		fi
+		if test "$existing_uuid" = "$extra_uuid"; then
+			echo-style --error='The device is already part of the intended filesystem.'
+			return 22 # Invalid argument
+		fi
+
+		# usage: btrfs device add [options] <device> [<device>...] <path>
+		# Add one or more devices to a mounted filesystem.
+		# -K|--nodiscard            do not perform whole device TRIM on devices that report such capability
+		# -f|--force                force overwrite existing filesystem on the disk
+		# --enqueue                 wait if there's another exclusive operation running, otherwise continue
+		eval-helper --no-quiet --wrap --confirm \
+			-- sudo-helper \
+			-- btrfs device add --force --enqueue "$extra_node" "$existing_mount"
+
+		# run a balance
+		echo-style --notice='Once you a done with adding devices, you should run a balance now on the mount.'
+	}
+	function act_remove {
+		# Remove a device from a btrfs cluster
+		local temp existing_node existing_uuid existing_mount existing_count extra_node
+
+		# fetch existing
+		temp="$(
+			get-devices --result=node,uuid,mount,count --node --uuid --mount --count --filesystem=btrfs \
+				--select="$(echo-style --notice='Which btrfs filesystem to remove the old device from?')" \
+				--missing='You must mount the btrfs filesystem first before you can remove from it.'
+		)"
+		IFS=$'\t' read -rd $'\n' existing_node existing_uuid existing_mount existing_count <<<"$temp"
+
+		# fetch extra
+		extra_node="$(
+			get-devices --result=node --no-mount --uuid="$existing_uuid" --count="$existing_count" --filesystem=btrfs \
+				--select="$(echo-style --negative='WHICH DEVICE TO ERASE AND REMOVE FROM THE BTRFS FILESYSTEM?')" \
+				--missing='Did not find any additional btrfs devices.'
+		)"
+
+		# check count
+		if test "$existing_count" -eq 2; then
+			if confirm --positive --ppid=$$ -- "$(echo-style --notice="Removing a device from a btrfs filesystem with only 2 devices, requires the balance to be set to single rather than raid1. Do you wish to continue?")"; then
+				act_balance "$existing_mount" 'single'
+			else
+				return 1
+			fi
+		fi
+
+		# wait until balance completes
+		while ! eval-helper --no-quiet --wrap \
+			-- sudo-helper \
+			-- btrfs balance status --verbose "$existing_mount"; do
+			waiter
+		done
+
+		# usage: btrfs device remove <device>|<devid> [<device>|<devid>...] <path>
+		# Remove a device from a filesystem, specified by a path to the device or as a device id in the filesystem. The btrfs signature is removed from the device.
+		# --enqueue                 wait if there's another exclusive operation running, otherwise continue
+		eval-helper --no-quiet --wrap --confirm \
+			-- sudo-helper \
+			-- btrfs device remove --enqueue "$extra_node" "$existing_mount"
+
+		# run a balance
+		echo-style --notice='Once you a done with removing devices, you should run a balance now on the mount.'
+	}
+	function act_balance {
+		# Resume a balance
+		local temp existing_mount="${1-}" existing_count='' strategy="${2:-"raid1"}" action='start' args=()
+		if test -z "$existing_mount"; then
+			temp="$(
+				get-devices --result=mount,count --mount --count --filesystem=btrfs \
+					--select="$(echo-style --notice="Which btrfs filesystem to balance as $strategy?")" \
+					--missing='You must mount the btrfs filesystem first before you can balance it.'
+			)"
+			IFS=$'\t' read -rd $'\n' existing_mount existing_count <<<"$temp"
+		fi
+
+		# validate
+		if test -n "$existing_count" && test "$existing_count" -eq 1 -a "$strategy" = 'raid1'; then
+			echo-style --error='You cannot balance a btrfs filesystem with only 1 device as raid1.'
+			return 22 # Invalid argument
+		fi
+
+		# usage: btrfs balance status [-v] <path>
+		# Show status of running or paused balance
+		# -v|--verbose              increase output verbosity
+		if ! eval-helper --no-quiet --wrap \
+			-- sudo-helper \
+			-- btrfs balance status --verbose "$existing_mount"; then
+
+			# balance is running, ask what to do
+			if test "$(choose-option --required --label --question="Do you wish to?" -- 'resume' "Resume the existing balance, and abort a new $strategy balance." 'start' "Cancel the existing balance and resume, and start a new $strategy balance.")" = 'resume'; then
+				# usage: btrfs balance resume <path>
+				# Resume interrupted balance
+				eval-helper --no-quiet --wrap --confirm \
+					-- sudo-helper \
+					-- btrfs balance resume "$existing_mount"
+				return "$?"
+			else
+				# usage: btrfs balance cancel <path>
+				# Cancel running or paused balance
+				eval-helper --no-quiet --wrap --confirm \
+					-- sudo-helper \
+					-- btrfs balance cancel "$existing_mount"
+			fi
+		fi
+
+		# usage: btrfs balance start [options] <path>
+		# -v|--verbose              increase output verbosity
+		# -f|--force                force a reduction of metadata integrity, or skip timeout when converting to RAID56 profiles
+		# --background|--bg         run the balance as a background process
+		# --enqueue                 wait if there's another exclusive operation running, otherwise continue
+		# -d[filters]               act on data chunks with optional filters (no space in between)
+		# -m[filters]               act on metadata chunks with optinal filters (no space in between)
+		# -s[filters]               act on system chunks (only under -f) with optional filters (no space in between)
+		if test "$strategy" = 'single'; then
+			args+=('--force')
+		fi
+		eval-helper --no-quiet --wrap --confirm \
+			-- sudo-helper \
+			-- btrfs balance start --verbose --background --enqueue "${args[@]}" -dconvert="$strategy" -mconvert="$strategy" "$existing_mount"
+	}
+
+	# =====================================
 	# Arguments
 
 	function help {
@@ -16,29 +309,29 @@ function btrfs-helper() (
 			btrfs-helper <action>
 
 			ACTIONS:
-			<devices|drives>
-			    Lists all btrfs formatted devices.
+			devices [<...args>]
+			    Forwards to [get-devices <...args>] to fetch all devices with a btrfs filesystem.
 
-			<device|drive> -- <btrfs-filesystem-label>
-			    Gets the primary device for a btrfs filesystem label.
-
-			mounts
-			    Lists all mount points of btrfs formatted devices.
+			info
+			    Gets information about a btrfs device / filesystem.
 
 			new
 			    Formats a selected device to btrfs.
 
+			mount
+			    Mount a selected btrfs device.
+
+			unmount
+			    Unmount a selected btrfs device.
+
 			add
-			    Adds a selected device to an selected btrfs mount point.
+			    Adds a selected device to a selected btrfs filesystem.
+
+			remove
+			    Removes a selected device from a selected btrfs filesystem.
 
 			balance
-			    Runs a btrfs raid1 balance on a selected btrfs mount point.
-
-			verify -- <btrfs-filesystem-label> <expected-count-of-btrfs-filesystem-devices>
-			    Verifies that the device count for a btrfs filesystem label is correct.
-
-			mounted -- <btrfs-filesystem-label> <expected-mount-point>
-			    Verifies that the btrfs filesystem label is mounted to the expected mount point.
+			    Runs a btrfs raid1 balance on a selected btrfs filesystem.
 		EOF
 		if test "$#" -ne 0; then
 			echo-error "$@"
@@ -53,213 +346,25 @@ function btrfs-helper() (
 		shift
 		case "$item" in
 		'--help' | '-h') help ;;
-		'--')
+		'devices')
+			action="$item"
+			if test "${1-}" = '--'; then
+				shift
+			fi
 			args+=("$@")
 			shift $#
 			break
 			;;
+		'info' | 'new' | 'mount' | 'unmount' | 'add' | 'remove' | 'balance') action="$item" ;;
 		'--'*) help "An unrecognised flag was provided: $item" ;;
-		*)
-			if test -z "$action"; then
-				action="$item"
-			else
-				help "An unrecognised argument was provided: $item"
-			fi
-			;;
+		*) help "An unrecognised argument was provided: $item" ;;
 		esac
 	done
 
-	# convert
-	if test "$action" = 'drives'; then
-		action='devices'
-	elif test "$action" = 'drive'; then
-		action='device'
-	fi
-
-	# ensure valid action
-	local actions=(
-		devices
-		device
-		mounts
-		new
-		add
-		balance
-		verify
-		mounted
-	)
-	action="$(
-		choose-option --required \
-			--question='What action to perform?' \
-			--filter="$action" -- "${actions[@]}"
-	)"
-
-	# =====================================
-	# Dependencies
-
-	source "$DOROTHY/sources/ripgrep.bash"
-
-	# =====================================
-	# Helpers
-
-	# Get all the mount points which btrfs devices are mounted to
-	function get_btrfs_mounts {
-		if is-mac; then
-			df -T btrfs
-		else
-			df --type=btrfs
-			# df -Th | awk '($2 == "btrfs") {print $7}'
-			# lsblk -f | awk '($2 == "btrfs" && $7) {print $7}'
-		fi
-	}
-
-	# Prompt for a specific btrfs mount point
-	function get_btrfs_mount {
-		local question="$1" mounts
-		mapfile -t mounts < <(btrfs_mounts)
-		choose-option --required \
-			--question="$question" \
-			-- "${mounts[@]}"
-	}
-
-	# Prompt for a specific device
-	function get_any_device {
-		local question="$1" devices=()
-		mapfile -t devices < <(get-devices)
-		choose-option --required \
-			--question="$question" \
-			-- "${devices[@]}"
-	}
-
-	# Get all the devices which are formatted to btrfs
-	function get_btrfs_devices {
-		lsblk -f | awk '/btrfs/ {print "/dev/"$1}'
-	}
-
-	# Prompt for a specific btrfs device
-	function get_btrfs_device {
-		local question="$1" devices=()
-		mapfile -t devices < <(get_btrfs_devices)
-		choose-option --required \
-			--question="$question" \
-			-- "${devices[@]}"
-	}
-
-	# Get the primary device of a btrfs filesystem label
-	function get_btrfs_device_for_label {
-		local label="$1"
-		blkid -L "$label"
-	}
-
-	# Get the devices of a btrfs filesystem label
-	function get_btrfs_devices_for_label {
-		local label="$1"
-		sudo-helper \
-			-- btrfs filesystem show "$label" | rg -o 'path ([a-z0-9/]+)' --replace '$1'
-	}
-
-	# Count the devices of a btrfs filesystem label
-	function get_btrfs_count_for_label {
-		local label="$1"
-		sudo-helper \
-			-- btrfs filesystem show "$label" | rg -o 'Total devices ([0-9]+)' --replace '$1'
-	}
-
-	# =====================================
-	# Actions
-
-	function act_mounts {
-		get_btrfs_mounts
-	}
-
-	function act_devices {
-		get_btrfs_devices
-	}
-
-	function act_new {
-		local device label
-		device="$(
-			get_any_device "Which device to erase and format as btrfs?"
-		)"
-		label="$(
-			ask --required \
-				--question="What label to use for the new btrfs filesystem that will be attached to the device [$device]?"
-		)"
-		eval-helper --no-quiet --wrap --confirm \
-			-- sudo-helper \
-			-- mkfs.btrfs -f -L "$label" "$device"
-	}
-
-	# Add a device to a btrfs cluster
-	function act_add {
-		local device mount
-		echo 'You will now specify a mount point of an existing btrfs cluster, and a device that you wish to be erased and added to it.'
-		mount="$(get_btrfs_mount "Which mount point is the btrfs cluster that will house the new device?")"
-		device="$(get_any_device "Which device is the one to be erased then added into the btrfs cluster?")"
-
-		# add the device to the mount point
-		eval-helper --no-quiet --wrap --confirm \
-			-- sudo-helper \
-			-- btrfs device add -f "$device" "$mount"
-
-		# balance the devices of the mount point
-		eval-helper --no-quiet --wrap --confirm \
-			-- sudo-helper \
-			-- btrfs balance start --background -dconvert=raid1 -mconvert=raid1 "$mount"
-	}
-
-	# Resume a balance
-	function act_balance {
-		local mount
-		mount="$(get_btrfs_mount "Which btrfs mount point should we resume/start a btrfs raid1 balance operation on?")"
-
-		if eval-helper --no-quiet --wrap \
-			-- sudo-helper \
-			-- btrfs balance status -v "$mount"; then
-
-			# finished
-			eval-helper --no-quiet --wrap \
-				-- sudo-helper \
-				-- btrfs balance start --background -dconvert=raid1 -mconvert=raid1 "$mount"
-		else
-			# in progress
-			eval-helper --no-quiet --wrap \
-				-- sudo-helper \
-				-- btrfs balance resume "$mount"
-		fi
-	}
-
-	# Verify the amount of btrfs devices matches the expected ount
-	function act_verify {
-		local label="$1" expected="$2" actual
-		actual="$(get_btrfs_count_for_label "$label")"
-		if test "$actual" -ne "$expected"; then
-			{
-				echo-style --error="$actual out of $expected devices available"
-				echo-style --warning="Try again when all devices are available."
-			} >/dev/stderr
-			return 1
-		fi
-	}
-
-	function act_mounted {
-		local label="$1" mount="$2" device
-		device="$(get_btrfs_device_for_label "$label")"
-		mount-helper --mounted --source="$device" --target="$mount"
-	}
-
-	function act_device {
-		local label="${1-}"
-		if test -n "$label"; then
-			get_btrfs_device_for_label "$label"
-		else
-			get_btrfs_device 'Which btrfs device to select?'
-		fi
-	}
-
-	# =====================================
-	# Act
-
-	if test "$(type -t "act_$action")" = 'function'; then
+	# act
+	if test -z "$action"; then
+		help 'No <action> specified.'
+	elif test "$(type -t "act_$action")" = 'function'; then
 		"act_$action" "${args[@]}"
 		return "$?"
 	else
diff --git a/commands/get-devices b/commands/get-devices
--- a/commands/get-devices
+++ b/commands/get-devices
@@ -18,6 +18,12 @@
 # UASP supported is needed by the USB Hubs for UASP boost, as stated by StarTech in a support chat:
 # > All hubs support the use of UASP enabled devices, but hubs that do not have the feature built in will not operate at the boosted speed that UASP devices can function at. If you require the UASP boosted speed, then look for a hub that has it built in. If the speed is not crucial and the standard 5Gbps that USB 3.0 offers will suffice, it won't matter the hub you use as long as its a USB 3.0 hub.
 
+# Other useful commands that we didn't use:
+# df -T "$filesystem" # macos
+# df --type="$filesystem" # linux
+# blkid -L "$label"
+# lsblk -f | awk "/$filesystem/" {print "/dev/"$1}'
+
 function get-devices() (
 	source "$DOROTHY/sources/bash.bash"
 
@@ -33,46 +39,85 @@ function get-devices() (
 			get-devices [...options] [-- ...<node>]
 
 			OPTIONS:
-			--node
+			--result=<detail>
+			    What to output as the result. If CSV values provided, they will be tabbed separated.
+
+			--details=<detail>
+			    What to output as the label (accepts CSV values).
+			    Defaults to all details.
+
+			--select=<question>
+			    If provided, prompts the user to select one of the matched devices with the <question>.
+			    Defaults <result> to <node>.
+
+			--missing=<missing>
+			    If provided, and no results were found, then output this <missing> message instead of the default one.
+
+			--debug
+			    Output debug information.
+
+			FILTERS:
+			--node=<node>
+			    Filter devices, only returning those of <node>.
+
+			--uuid=<uuid>
+			    Filter devices, only returning those of <uuid>.
+
+			--label=<label>
+			    Filter devices, only returning those of <label>.
+
+			--filesystem=<filesystem>
+			    Filter devices, only returning those of <filesystem>.
+
+			--mount=<mount>
+			    Filter devices, only returning those mounted to <mount>.
+
+			--mounted
+			    Filter devices, only returning those that are mounted.
+
+			--count=<count>
+			    Filter devices, only returning those of <count>.
+			    Currently only supports btrfs.
+
+			DETAILS:
+			node
 			    Get device node, e.g. [/dev/sda]
 
-			--size
+			size
 			    Get device size, e.g. [10.91 TiB]
 
-			--model
-			    Get device model, e.g. [My Book 25EE]
+			label
+			    Get device label, e.g. [TANKER]
 
+			filesystem
+			    Get device filesystem/type, e.g. [btrfs|ext4]
 
-			--label
-			    Get device label, e.g. [writable]
+			mount
+			    Get device mount point, e.g. [/boot/firmware]
 
-			--uuid
-			    Get device uuid, e.g. [1aa1aa11-1aa1-aa11-1aa1-aa1aa1aa1aa1]
+			count
+				Get how many devices are attached to the filesystem (btrfs only), e.g. [1]
 
-			--block
-			    Get device block size, e.g. [4096]
-
-			--<type|filesystem>
-			    Get device filesystem, e.g. [btrfs|ext4]
-
-
-			--serial
-			    Get device serial number, e.g. [1AA1AA11]
-
-			--vendor
+			vendor
 			    Get device vendor, e.g. [Seagate]
 
-			--product
+			model
+			    Get device model, e.g. [My Book 25EE]
+
+			product
 			    Get device product, e.g. [Expansion Desk]
 
-			--revision
+			revision
 			    Get device revision, e.g. [0915]
 
-			--tabbed
-			    Output tab separated values instead of key value pairs.
+			serial
+			    Get device serial number, e.g. [1AA1AA11]
 
-			<node>
-			    Filter devices, only returning those of <node>.
+			uuid
+			    Get device uuid, e.g. [1aa1aa11-1aa1-aa11-1aa1-aa1aa1aa1aa1]
+
+			block
+			    Get device block size, e.g. [4096]
 		EOF
 		if test "$#" -ne 0; then
 			echo-error "$@"
@@ -81,60 +126,116 @@ function get-devices() (
 	}
 
 	# process
-	local item details=() nodes=() tabbed='no' debug='no'
+	local item option_results=() option_select='' option_missing='' option_debug='no'
+	local option_has_node='' option_node=''
+	local option_has_label='' option_label=''
+	local option_has_filesystem='' option_filesystem=''
+	local option_has_mount='' option_mount=''
+	local option_has_count='' option_count=''
+	local option_has_uuid='' option_uuid=''
+	local option_details=(
+		node
+		size
+		label
+		filesystem
+		mount
+		count
+		vendor
+		model
+		product
+		revision
+		serial
+		uuid
+		block
+	)
+	local filters=(
+		node
+		label
+		filesystem
+		mount
+		count
+		uuid
+	)
 	while test "$#" -ne 0; do
 		item="$1"
 		shift
 		case "$item" in
 		'--help' | '-h') help ;;
 
-		'--node') details+=('node') ;;
-		'--size') details+=('size') ;;
-		'--model') details+=('model') ;;
-
-		'--serial') details+=('serial') ;;
-		'--vendor') details+=('vendor') ;;
-		'--product') details+=('product') ;;
-		'--revision') details+=('revision') ;;
-
-		'--label') details+=('label') ;;
-		'--uuid') details+=('uuid') ;;
-		'--block') details+=('block') ;;
-		'--type' | '--filesystem') details+=('filesystem') ;;
-
-		'--tabbed') tabbed='yes' ;;
+		'--result='*)
+			mapfile -t option_results < <(echo-split ',' -- "${item#*--result=}")
+			;;
+		'--detail='*)
+			mapfile -t option_details < <(echo-split ',' -- "${item#*--detail=}")
+			;;
+		'--select='*) option_select="${item#*--select=}" ;;
+		'--missing='*) option_missing="${item#*--missing=}" ;;
 		'--no-debug'* | '--debug'*)
-			debug="$(
-				get-flag-value debug --missing="$debug" -- "$item" | echo-affirmative
+			option_debug="$(
+				get-flag-value debug --missing="$option_debug" -- "$item" | echo-affirmative
 			)"
 			;;
 
-		'--')
-			nodes+=("$@")
-			shift "$#"
-			break
+		'--node='*) option_node="${item#*--node=}" ;;
+		'--no-node' | '--node')
+			option_has_node="$(
+				get-flag-value node --missing="$option_has_node" -- "$item" | echo-affirmative
+			)"
 			;;
+		'--label='*) option_label="${item#*--label=}" ;;
+		'--no-label' | '--label')
+			option_has_label="$(
+				get-flag-value label --missing="$option_has_label" -- "$item" | echo-affirmative
+			)"
+			;;
+		'--filesystem='*) option_filesystem="${item#*--filesystem=}" ;;
+		'--no-filesystem' | '--filesystem')
+			option_has_filesystem="$(
+				get-flag-value filesystem --missing="$option_has_filesystem" -- "$item" | echo-affirmative
+			)"
+			;;
+		'--mount='*) option_mount="${item#*--mount=}" ;;
+		'--no-mount' | '--mount')
+			option_has_mount="$(
+				get-flag-value mount --missing="$option_has_mount" -- "$item" | echo-affirmative
+			)"
+			;;
+		'--no-mounted'* | '--mounted'*)
+			option_has_mount="$(
+				get-flag-value mounted --missing="$option_has_mount" -- "$item" | echo-affirmative
+			)"
+			;;
+		'--count='*) option_count="${item#*--count=}" ;;
+		'--no-count' | '--count')
+			option_has_count="$(
+				get-flag-value count --missing="$option_has_count" -- "$item" | echo-affirmative
+			)"
+			;;
+		'--uuid='*) option_uuid="${item#*--uuid=}" ;;
+		'--no-uuid' | '--uuid')
+			option_has_uuid="$(
+				get-flag-value uuid --missing="$option_has_uuid" -- "$item" | echo-affirmative
+			)"
+			;;
+
 		'--'*) help "An unrecognised flag was provided: $item" ;;
 		*) help "An unrecognised argument was provided: $item" ;;
 		esac
 	done
 
-	if test "${#details[@]}" -eq 0; then
-		details+=(
-			'node'
-			'size'
-			'model'
+	# if select is provided, yet no results are provided, then default to node
+	if test -n "$option_select" -a "${#option_results[@]}" -eq 0; then
+		option_results=('node')
+	fi
 
-			'label'
-			'uuid'
-			'block'
-			'filesystem'
+	# if no select is provided, yet results are provided, then ignore display
+	if test -z "$option_select" -a "${#option_results[@]}" -ne 0; then
+		option_details=()
+	fi
 
-			'serial'
-			'vendor'
-			'product'
-			'revision'
-		)
+	# if no missing, default to a generic message
+	if test -z "$option_missing"; then
+		option_missing='No matching devices found.'
 	fi
 
 	# =====================================
@@ -142,203 +243,221 @@ function get-devices() (
 
 	# dependencies
 	source "$DOROTHY/sources/ripgrep.bash"
+	if is-linux; then
+		setup-util --quiet --cli='sginfo' \
+			APT='sg3-utils'
+	fi
 
 	# helpers
 	function get_key {
-		rg -o "$1=\"(.+?)\"" --replace '$1' || :
+		rg -o "$1=\"([^\"]+)" --replace '$1' || :
 	}
 	function get_property {
-		rg -o "$1[: ']+(.+)[']?" --replace '$1' || :
+		rg -o "$1[: '\"]+([^'\"]+)" --replace '$1' || :
 	}
-	if test "$tabbed" = 'yes'; then
-		function output {
-			printf '%s\t' "$2"
-		}
-	else
-		function output {
-			printf '%s=[%s] ' "$1" "$2"
-
-		}
-	fi
-	if command-exists smartctl; then
-		function smart_debug_one {
-			local node="$1"
-
-			eval-helper --no-quiet \
-				-- sudo-helper \
-				-- smartctl -a "$node" || :
-			# ^ -i: model, serial, firmware, pci id, ieee id, controller id, nvme version, etc.
-			# ^ -a: same as -i, but includes SMART specific details that we don't care for
-		}
-	else
-		function smart_debug_one {
-			true
-		}
-	fi
-
-	# environment specific helpers
-	if is-mac; then
-		function debug_one {
-			local node="$1"
-
-			# model, serial, uuid, filesystem, size, block, label
-			eval-helper --no-quiet \
-				-- sudo-helper \
-				-- diskutil info "$node" || :
-
-			# finish
-			smart_debug_one "$node"
-			echo
-		}
-		function get_one {
-			local detail node="$1" __info size='' model='' label='' uuid='' block='' filesystem='' serial='' vendor='' product='' revision=''
-
-			__info="$(sudo-helper -- diskutil info "$node")"
-			model="$(get_property 'Device [/] Media Name' <<<"$__info")"
-			serial="$(get_property 'Content [(]IOContent[)]' <<<"$__info")"
-			uuid="$(get_property 'Disk [/] Partition UUID' <<<"$__info")"
-			filesystem="$(get_property 'Type [(]Bundle[)]' <<<"$__info")"
-			size="$(get_property 'Disk Size' <<<"$__info")"          # 5.0 TB (5034252828672 Bytes) (exactly 9832525056 512-Byte-Units)
-			block="$(get_property 'Device Block Size' <<<"$__info")" # 512 Bytes
-			label="$(get_property 'Volume Name' <<<"$__info")"       # 512 Bytes
-			if test -z "$label" -o "$label" = ' '; then
-				label="$(get_property 'Set Name' <<<"$__info")"
+	function check_exclude {
+		local name="$1" value="$2"
+		local option="option_$name"
+		option="${!option}"
+		local has="option_has_$name"
+		has="${!has}"
+		if test -n "$option" -a "$option" != "$value"; then
+			return
+		fi
+		if test -n "$has"; then
+			if test "$has" = 'yes' -a -z "$value" || test "$has" = 'no' -a -n "$value"; then
+				return
 			fi
+		fi
+		return 1
+	}
 
-			for detail in "${details[@]}"; do
-				output "$detail" "${!detail}"
-			done
-			echo
+	# debug
+	if test "$option_debug" = 'yes'; then
+		{
+			if test -n "$option_node"; then
+				# model, serial, uuid, filesystem, size, block, label
+				eval-helper --no-quiet \
+					-- sudo-helper \
+					-- diskutil info "$option_node" || :
 
-			if test "$debug" = 'yes'; then
-				debug_one "$node" >/dev/stderr
-			fi
-		}
-		function debug_all {
-			eval-helper --no-quiet \
-				-- sudo-helper \
-				-- diskutil list || :
+				# label, uuid, block, filesystem
+				eval-helper --no-quiet \
+					-- sudo-helper \
+					-- blkid "$option_node" || :
 
-			# trail
-			echo
-		}
-		function get_all {
-			sudo-helper -- diskutil list | rg -o '/dev/[^ ]+'
+				# serial, vendor, product, revision
+				eval-helper --no-quiet \
+					-- sudo-helper \
+					-- sginfo -a "$option_node" || :
 
-			if test "$debug" = 'yes'; then
-				debug_all >/dev/stderr
-			fi
-		}
-		function act {
-			local node
-			if test "${#nodes[@]}" -ne 0; then
-				for node in "${nodes[@]}"; do
-					get_one "$node"
-				done
+				eval-helper --no-quiet \
+					-- sudo-helper \
+					-- hdparm -I "$option_node" || :
+
+				eval-helper --no-quiet \
+					-- sudo-helper \
+					-- sdparm -i "$option_node" || :
+
+				# -i: model, serial, firmware, pci id, ieee id, controller id, nvme version, etc.
+				# -a: same as -i, but includes SMART specific details that we don't care for
+				eval-helper --no-quiet \
+					-- sudo-helper \
+					-- smartctl -a "$option_node" || :''
+
+				#  btrfs filesystem show [options] [<path>|<uuid>|<device>|label]
+				eval-helper --no-quiet \
+					-- sudo-helper \
+					-- btrfs filesystem show "$option_node"
 			else
-				while IFS=$'\t' read -rd $'\n' node; do
-					get_one "$node"
-				done < <(get_all)
-			fi
-		}
-	elif is-linux; then
-		setup-util --quiet --cli='sginfo' \
-			APT='sg3-utils'
+				if is-linux; then
+					# macos doesn't support fdisk for listing
+					eval-helper --no-quiet \
+						-- sudo-helper \
+						-- fdisk -l || :
 
-		function debug_one {
-			local node="$1"
+					# Gets all the details for the drives, including the vendor, model, serial, driver capabilities, etc.
+					# UASP unsupported: configuration: driver=usb-storage
+					# UASP supported: configuration: driver=uas maxpower=... speed=...
+					eval-helper --no-quiet \
+						-- sudo-helper \
+						-- lshw -class disk -class storage || :
 
-			# label, uuid, block, filesystem
-			eval-helper --no-quiet \
-				-- sudo-helper \
-				-- blkid "$node" || :
-
-			# serial, vendor, product, revision
-			eval-helper --no-quiet \
-				-- sudo-helper \
-				-- sginfo -a "$node" || :
-
-			eval-helper --no-quiet \
-				-- sudo-helper \
-				-- hdparm -I "$node" || :
-
-			eval-helper --no-quiet \
-				-- sudo-helper \
-				-- sdparm -i "$node" || :
-
-			# finish
-			smart_debug_one "$node"
-			echo
-		}
-		function get_one {
-			# trunk-ignore-all(shellcheck/SC2034)
-			local detail node="$1" size="$2" model="$3" __blkid label='' uuid='' block='' filesystem='' __sginfo serial='' vendor='' product='' revision=''
-
-			__blkid="$(sudo-helper -- blkid "$node")"
-			label="$(get_key 'LABEL' <<<"$__blkid")"
-			uuid="$(get_key 'UUID' <<<"$__blkid")"
-			block="$(get_key 'BLOCK_SIZE' <<<"$__blkid")"
-			filesystem="$(get_key 'TYPE' <<<"$__blkid")"
-
-			__sginfo="$(sudo-helper -- sginfo -a "$node")"
-			serial="$(get_property 'Serial Number' <<<"$__sginfo")"
-			vendor="$(get_property 'Vendor' <<<"$__sginfo")"
-			product="$(get_property 'Product' <<<"$__sginfo")"
-			revision="$(get_property 'Revision level' <<<"$__sginfo")"
-
-			for detail in "${details[@]}"; do
-				output "$detail" "${!detail}"
-			done
-			echo
-
-			if test "$debug" = 'yes'; then
-				debug_one "$node" >/dev/stderr
-			fi
-		}
-		function debug_all {
-			# macos does not support the -l flag
-			eval-helper --no-quiet \
-				-- sudo-helper \
-				-- fdisk -l || :
-
-			# Gets all the details for the drives, including the vendor, model, serial, driver capabilities, etc.
-			# UASP unsupported: configuration: driver=usb-storage
-			# UASP supported: configuration: driver=uas maxpower=... speed=...
-			eval-helper --no-quiet \
-				-- sudo-helper \
-				-- lshw -class disk -class storage || :
-
-			# Fetch filesystems and mounts for all drives
-			eval-helper --no-quiet \
-				-- sudo-helper \
-				-- lsblk -f || :
-
-			# trail
-			echo
-		}
-		function get_all {
-			sudo-helper -- fdisk -l "${devices[@]}" | rg -Uo 'Disk (/dev/.+?): (.+?),.+\nDisk model: (.+?)\s' --replace $'$1\t$2\t$3'
-
-			if test "$debug" = 'yes'; then
-				debug_all >/dev/stderr
-			fi
-		}
-		function act {
-			local node size model
-			while IFS=$'\t' read -rd $'\n' node size model; do
-				if test "${#nodes[@]}" -ne 0 && ! is-needle "$node" "${nodes[@]}"; then
-					continue
+					# Fetch filesystems and mounts for all drives
+					eval-helper --no-quiet \
+						-- sudo-helper \
+						-- lsblk -f || :
+				else
+					eval-helper --no-quiet \
+						-- sudo-helper \
+						-- diskutil list || :
 				fi
-				get_one "$node" "$size" "$model"
-			done < <(get_all)
-		}
-	else
-		echo-error "$0: Unsupported OS"
-		return 19 # ENODEV 19 Operation not supported by device
+
+				#  btrfs filesystem show [options]
+				eval-helper --no-quiet \
+					-- sudo-helper \
+					-- btrfs filesystem show
+
+				# trail
+				echo
+			fi
+		} >/dev/stderr
 	fi
+
+	# action
+	local mount_haystack results=()
+	mount_haystack="$(mount)"
+	function get_one {
+		# trunk-ignore-all(shellcheck/SC2034)
+		local temp node="$1" size="${2-}" model="${3-}" label='' uuid='' block='' filesystem='' mount='' count='' serial='' vendor='' product='' revision=''
+
+		# check node quickly
+		if check_exclude 'node' "$node"; then
+			return
+		fi
+
+		# fetch properties
+		if is-mac; then
+			# fetch diskutil properties
+			temp="$(sudo-helper -- diskutil info "$node")"
+			filesystem="$(get_property 'Type [(]Bundle[)]' <<<"$temp")"
+			label="$(get_property 'Volume Name' <<<"$temp")" # 512 Bytes
+			if test -z "$label" -o "$label" = ' '; then      # label fallback
+				label="$(get_property 'Set Name' <<<"$temp")"
+			fi
+			uuid="$(get_property 'Disk [/] Partition UUID' <<<"$temp")"
+			model="$(get_property 'Device [/] Media Name' <<<"$temp")"
+			serial="$(get_property 'Content [(]IOContent[)]' <<<"$temp")"
+			size="$(get_property 'Disk Size' <<<"$temp")"          # 5.0 TB (5034252828672 Bytes) (exactly 9832525056 512-Byte-Units)
+			block="$(get_property 'Device Block Size' <<<"$temp")" # 512 Bytes
+
+			# fetch mount
+			mount="$(rg -o "$node on (.+?) \($filesystem" --replace '$1' <<<"$mount_haystack" || :)"
+		else
+			# fetch blkid properties
+			temp="$(sudo-helper -- blkid "$node" || :)" # can fail if recently removed from a btrfs cluster
+			if test -n "$temp"; then
+				filesystem="$(get_key 'TYPE' <<<"$temp")"
+				label="$(get_key 'LABEL' <<<"$temp")"
+				uuid="$(get_key 'UUID' <<<"$temp")"
+				block="$(get_key 'BLOCK_SIZE' <<<"$temp")"
+			fi
+
+			# fetch sginfo properties
+			temp="$(sudo-helper -- sginfo -a "$node")"
+			serial="$(get_property 'Serial Number' <<<"$temp")"
+			vendor="$(get_property 'Vendor' <<<"$temp")"
+			product="$(get_property 'Product' <<<"$temp")"
+			revision="$(get_property 'Revision level' <<<"$temp")"
+
+			# fetch mount
+			mount="$(rg -o "$node on (.+?) type $filesystem" --replace '$1' <<<"$mount_haystack" || :)"
+		fi
+
+		# fetch count
+		if test "$filesystem" = 'btrfs'; then
+			count="$(sudo-helper -- btrfs filesystem show "$node" | rg -o 'Total devices ([0-9]+)' --replace '$1' || :)"
+		fi
+
+		# check filters
+		local filter
+		for filter in "${filters[@]}"; do
+			if check_exclude "$filter" "${!filter}"; then
+				return
+			fi
+		done
+
+		# output
+		local result
+		if test "${#option_results[@]}" -ne 0; then
+			if test "${#option_results[@]}" -eq 1; then
+				printf '%s' "${!option_results[0]}"
+			else
+				for temp in "${option_results[@]}"; do
+					printf '%s\t' "${!temp}"
+				done
+			fi
+			printf '\n'
+		fi
+		if test "${#option_details[@]}" -ne 0; then
+			if test "${#option_details[@]}" -eq 1; then
+				printf '%s=[%s]' "${option_details[0]}" "${!option_details[0]}"
+			else
+				for temp in "${option_details[@]}"; do
+					printf '%s=[%s] ' "$temp" "${!temp}"
+				done
+			fi
+			printf '\n'
+		fi
+	}
+	function get_all {
+		if is-mac; then
+			sudo-helper -- diskutil list | rg -o '/dev/[^ ]+'
+		else
+			sudo-helper -- fdisk -l | rg -Uo 'Disk (/dev/.+?): (.+?),.+\nDisk model: (.+?)\s' --replace $'$1\t$2\t$3'
+		fi
+	}
+	function action {
+		local node size='' model='' result
+		while IFS=$'\t' read -rd $'\n' node size model; do
+			get_one "$node" "$size" "$model"
+		done < <(get_all)
+	}
 
 	# act
-	act
+	local results
+	mapfile -t results < <(action)
+	if test "${#results[@]}" -eq 0; then
+		echo-style --error="$option_missing" >/dev/stderr
+		return 19 # ENODEV 19 Operation not supported by device
+	fi
+	if test -n "$option_select"; then
+		choose-option --required --confirm --label \
+			--question="$option_select" \
+			-- "${results[@]}"
+	else
+		echo-lines "${results[@]}"
+	fi
 )
 
 # fire if invoked standalone
