btrfs-helper: usability improvements
- add action: when asking for devices to erase to add, don't show
  devices already part of the volume
- info action: place errors last, and output devices that share the
  volume, to better identify which device has the errors

diff --git a/commands/btrfs-helper b/commands/btrfs-helper
--- a/commands/btrfs-helper
+++ b/commands/btrfs-helper
@@ -13,14 +13,14 @@ function btrfs-helper() (
 	function act_info {
 		# @todo have [get-size] use this perhaps
 		# Get details about a btrfs device / filesystem
-		local temp existing_node existing_mount path
+		local temp existing_node existing_mount existing_count existing_uuid path
 
 		# fetch existing
 		temp="$(
-			get-devices --result=node,mount --node --uuid --filesystem=btrfs \
+			get-devices --result=node,mount,count,uuid --node --uuid --filesystem=btrfs \
 				--select="$(echo-style --positive='Which btrfs device / filesystem to get information about?')"
 		)"
-		IFS=$'\t' read -rd $'\n' existing_node existing_mount <<<"$temp"
+		IFS=$'\t' read -rd $'\n' existing_node existing_mount existing_count existing_uuid <<<"$temp"
 		path="${existing_mount:-"$existing_node"}"
 
 		# Show the structure of a filesystem
@@ -59,13 +59,18 @@ function btrfs-helper() (
 		# Show status
 		eval-helper --no-quiet \
 			-- sudo-helper \
-			-- btrfs device stats "$path"
+			-- btrfs balance status "$path" || : # if still running, exit code 1
 		eval-helper --no-quiet \
 			-- sudo-helper \
 			-- btrfs scrub status "$path" || : # if still running, exit code 1
 		eval-helper --no-quiet \
 			-- sudo-helper \
-			-- btrfs balance status "$path" || : # if still running, exit code 1
+			-- btrfs device stats "$path"
+
+		# Get all devices of the mount
+		if test -n "$existing_uuid" && test "$existing_count" -gt 1; then
+			get-devices --uuid="$existing_uuid" --filesystem=btrfs
+		fi
 
 		# Summarize disk usage of every nested file inside the directory
 		# eval-helper --no-quiet \
@@ -166,7 +171,7 @@ function btrfs-helper() (
 
 		# fetch addition
 		temp="$(
-			get-devices --result=node,uuid --no-mount \
+			get-devices --result=node,uuid --no-mount --no-label \
 				--select="$(echo-style --negative='WHICH DEVICE TO ERASE AND ADD TO THE BTRFS FILESYSTEM?')" \
 				--missing='Did not find any non-mounted devices.'
 		)"
