rewrite of user config, major improvements
For the full changelog and remaining todos, refer to:

https://github.com/bevry/dorothy/discussions/24

Closes #23 #17

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/chmod-partial b/commands/chmod-partial
--- a/commands/chmod-partial
+++ b/commands/chmod-partial
@@ -2,18 +2,18 @@
 source "$DOROTHY/sources/strict.bash"
 
 # options
-mapfile -t options < <(echo-before-separator "$@")
+mapfile -t permissions < <(echo-before-separator "$@")
 mapfile -t paths < <(echo-after-separator "$@")
 
-if is-array-empty-or-partial "${options[@]}" || is-array-empty-or-partial "${paths[@]}"; then
+if is-array-empty-or-partial "${permissions[@]}" || is-array-empty-or-partial "${paths[@]}"; then
 	stderr echo "USAGE:"
-	stderr echo "chmod-partial <options> -- <paths...>"
+	stderr echo "chmod-partial <permissions> -- <paths...>"
 	stderr echo ""
 	stderr echo "EXAPLE:"
-	stderr echo "chmod-partial -f +x -- path path path"
+	stderr echo "chmod-partial +x -- path path path"
 	exit 1
 fi
 
 for path in "${paths[@]}"; do
-	chmod "${options[@]}" "$path" || echo "unable to ${options[*]}: $path"
+	chmod --changes --recursive "${permissions[@]}" "$path" || echo "unable to ${permissions[*]}: $path"
 done
