ansi.bash: inline `__read_key`, confirm: fix clearing
This commit fixes `confirm` not clearing after `enter` correctly on slow machines. This was due to the `read` call in `read-key` then calling `add`, which then delayed the subsequent `read` which could cause an echo as no `read` would be active. This now captures the readings, then processes it, to ensure that the entire read is captured, even on slow machines.

Furthermore, this also improves performance by inlining `read-key` into `ansi.bash` as `__read_key`.

The remaining significant delay is now with `echo-clear-lines` calling `echo-wrap`, however this is worked around somewhat by the new `ansi.bash:__should_wrap` helper.

Note, that this does not prevent multiple enter presses from stuffing uup the clearing. This will be worked around by using `stty -echo` and `stty +echo` in a future commit.

Finally, this inlines `is-number` to `bash.bash:__is_number`.

diff --git a/commands/choose b/commands/choose
--- a/commands/choose
+++ b/commands/choose
@@ -624,7 +624,7 @@ function choose_test() (
 function choose_() (
 	source "$DOROTHY/sources/bash.bash"
 	source "$DOROTHY/sources/styles.bash" # __load_styles
-	source "$(type -P read-key)"
+	source "$DOROTHY/sources/ansi.bash"   # __read_key
 
 	# =====================================
 	# Arguments
@@ -2151,7 +2151,8 @@ function choose_() (
 		debug_counter="$((debug_counter + 1))"
 	}
 	function handle_menu {
-		local read_status input keys skips
+		local input keys skips
+		local -i __read_status
 		# action
 		reset_terminal_modifications_on_exit
 		__do --redirect-stdout=TTY -- __print_string "$STYLE__alternative_screen_buffer"
@@ -2163,9 +2164,9 @@ function choose_() (
 			menu_skip_render='no'
 
 			# handle the response
-			__do --redirect-status={read_status} --redirect-stdout={input} -- \
-				read_key --timeout="$option_timeout"
-			if [[ $read_status -eq 60 ]]; then
+			__read_status=0
+			input="$(__read_key --timeout="$option_timeout")" || __read_status=$?
+			if [[ $__read_status -eq 60 ]]; then
 				if [[ $selected_count -ne 0 ]]; then
 					# default
 					commentary="${STYLE__result_commentary_spacer}${STYLE__commentary_timeout_default}"
@@ -2181,19 +2182,19 @@ function choose_() (
 				else
 					# required
 					commentary="${STYLE__result_commentary_spacer}${STYLE__commentary_timeout_required}"
-					menu_status="$read_status"
+					menu_status="$__read_status"
 					set_menu_mode 'exit'
 					break
 				fi
-			elif [[ $read_status -eq 94 ]]; then
+			elif [[ $__read_status -eq 94 ]]; then
 				# unknown character, send bell and continue
 				menu_skip_render='yes'
 				__do --redirect-stdout=TTY -- __print_string "$STYLE__bell"
 				continue
-			elif [[ $read_status -ne 0 ]]; then
+			elif [[ $__read_status -ne 0 ]]; then
 				# failure
-				commentary="${STYLE__result_commentary_spacer}$(printf "$STYLE__commentary_input_failure" "read status: $read_status")"
-				menu_status="$read_status" # error causes no selection
+				commentary="${STYLE__result_commentary_spacer}$(printf "$STYLE__commentary_input_failure" "read status: $__read_status")"
+				menu_status="$__read_status" # error causes no selection
 				set_menu_mode 'exit'
 				break
 			elif [[ $terminal_too_short != 'no' ]]; then
diff --git a/commands/confirm b/commands/confirm
--- a/commands/confirm
+++ b/commands/confirm
@@ -62,8 +62,8 @@ function confirm_test() (
 function confirm_() (
 	source "$DOROTHY/sources/bash.bash"
 	source "$DOROTHY/sources/styles.bash" # __load_styles
+	source "$DOROTHY/sources/ansi.bash"   # __read_key
 	source "$(type -P echo-clear-lines)"
-	source "$(type -P read-key)"
 
 	# =====================================
 	# Arguments
@@ -316,13 +316,14 @@ function confirm_() (
 	trap on_confirm_terminate SIGINT SIGTERM # this is necessary to always show ABORT message
 
 	local input keys commentary='' RESULT='' bell=$'\a'
+	local -i __read_status
 	while :; do
 		# render
 		refresh
 
 		# capture
-		__do --redirect-status={read_status} --redirect-stdout={input} -- \
-			read_key --keep-line-buffer-newlines --timeout="$option_timeout"
+		__read_status=0
+		input="$(__read_key --keep-line-buffer-newlines --timeout="$option_timeout")" || __read_status=$?
 
 		# input => keys => key
 		keys=()
@@ -340,7 +341,7 @@ function confirm_() (
 		fi
 
 		# handle status
-		if [[ $read_status -eq 60 ]]; then
+		if [[ $__read_status -eq 60 ]]; then
 			# timeout
 			# default
 			commentary="${STYLE__result_commentary_spacer}${STYLE__commentary_timeout_default}"
@@ -354,17 +355,17 @@ function confirm_() (
 				# bool, confirm
 				# required
 				commentary="${STYLE__result_commentary_spacer}${STYLE__commentary_timeout_required}"
-				RESULT="$read_status"
+				RESULT="$__read_status"
 				break
 			fi
-		elif [[ $read_status -eq 94 ]]; then
+		elif [[ $__read_status -eq 94 ]]; then
 			# unknown character, send bell and continue
 			__to --source={bell} --target=TTY
 			continue
-		elif [[ $read_status -ne 0 ]]; then
+		elif [[ $__read_status -ne 0 ]]; then
 			# failure
-			commentary="${STYLE__result_commentary_spacer}$(printf "$STYLE__commentary_input_failure" "read status: $read_status")"
-			RESULT="$read_status"
+			commentary="${STYLE__result_commentary_spacer}$(printf "$STYLE__commentary_input_failure" "read status: $__read_status")"
+			RESULT="$__read_status"
 			break
 		fi
 
