shellcheck, shellformat, help redo #45
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/choose-menu b/commands/choose-menu
--- a/commands/choose-menu
+++ b/commands/choose-menu
@@ -12,21 +12,22 @@ fi
 
 # validate
 if is-help-separator "$@"; then
-	stderr echo-lines \
-		'ABOUT:' \
-		'Display a menu that the user can navigate using the keyboard.' \
-		'' \
-		'USAGE:' \
-		'choose-menu [...flags] -- <...items>' \
-		'' \
-		'RETURNS:' \
-		'the index of the result' \
-		'' \
-		'FLAGS:' \
-		'Provide [--question=...] to specify the question that the prompt will be answering.' \
-		'Provide [--multi] to specify that multiple menu items should be able to be selected.' \
-		'Provide [--timeout=...] to specify a custom timeout value in seconds.' \
-		'Provide [--main] to not create an alternative TTY shell when promting for questions.'
+	stderr cat <<-EOF
+		ABOUT:
+		Display a menu that the user can navigate using the keyboard.
+
+		USAGE:
+		choose-menu [...flags] -- <...items>
+
+		RETURNS:
+		the index of the result
+
+		FLAGS:
+		Provide [--question=...] to specify the question that the prompt will be answering.
+		Provide [--multi] to specify that multiple menu items should be able to be selected.
+		Provide [--timeout=...] to specify a custom timeout value in seconds.
+		Provide [--main] to not create an alternative TTY shell when promting for questions.
+	EOF
 	exit 22 # Invalid argument
 fi
 
@@ -53,7 +54,7 @@ if test "$option_main" = 'no'; then
 fi
 cursor=0
 count="${#choices[@]}"
-last="$((count - 1 ))"
+last="$((count - 1))"
 action=''
 mapfile -t selections < <(get-array "$count")
 
@@ -61,35 +62,36 @@ mapfile -t selections < <(get-array "$count")
 while test "$action" != 'done'; do
 	# question
 	if test -n "$option_question"; then
-		echo -e "$option_question" > /dev/tty
+		echo -e "$option_question" >/dev/tty
 	fi
 
 	# show the menu
 	for i in "${!choices[@]}"; do
 		if test "$i" -eq "$cursor"; then
-			echo -n ">" > /dev/tty
+			echo -n ">" >/dev/tty
 		else
-			echo -n ' ' > /dev/tty
+			echo -n ' ' >/dev/tty
 		fi
 		if test "${selections[$i]-}" = 'yes'; then
-			echo -n "*" > /dev/tty
+			echo -n "*" >/dev/tty
 		else
-			echo -n ' ' > /dev/tty
+			echo -n ' ' >/dev/tty
 		fi
 		choice="${choices[$i]}"
-		echo "$choice" > /dev/tty
+		echo "$choice" >/dev/tty
 	done
 
 	# handle the response
-	ec=0; action="$(read-arrow --timeout="$option_timeout")" || ec="$?"
+	ec=0
+	action="$(read-arrow --timeout="$option_timeout")" || ec="$?"
 
 	# check
 	if test "$ec" -eq 62; then
-		echo "Input timed out [$ec]." > /dev/stderr
+		echo "Input timed out [$ec]." >/dev/stderr
 		sleep 10
 		exit "$ec"
 	elif test "$ec" -ne 0; then
-		echo "Input failed [$ec]." > /dev/stderr
+		echo "Input failed [$ec]." >/dev/stderr
 		# some other failure
 		sleep 10
 		exit "$ec"
@@ -175,7 +177,7 @@ fi
 # if multi with no selection then ask for everything
 # todo implement --required properly here
 if is-array-empty "${selections[@]}" && test "$option_multi" = 'yes'; then
-	if confirm-positive "You exited without selecting anything, do you wish to select all?" > /dev/tty; then
+	if confirm-positive "You exited without selecting anything, do you wish to select all?" >/dev/tty; then
 		for i in "${!choices[@]}"; do
 			selections[$i]='yes'
 		done
diff --git a/commands/choose-option b/commands/choose-option
--- a/commands/choose-option
+++ b/commands/choose-option
@@ -8,61 +8,62 @@ fi
 
 # validate
 if is-help-separator "$@"; then
-	stderr echo-lines \
-		'ABOUT:' \
-		'Prompt the user to select a value from a list of values, in a clean and robust way.' \
-		'' \
-		'USAGE:' \
-		'choose-option \ ' \
-		'  [--question=question] \ ' \
-		'  [--filter=filter] \ ' \
-		'  [--label[=first]] \ ' \
-		"  [--return='\$label'] \ " \
-		"  [--visual='\$label [\$value]'] \ " \
-		'  [--required] \ ' \
-		"  [--multi] \ " \
-		"  [--confirm] \ " \
-		"  [--main] \ " \
-		'  -- <[value]...> <value> <value>' \
-		'' \
-		'If you wish to show a question above the menu:' \
-		'--question=question -- <...>' \
-		'' \
-		'If you wish to filter the value and/or labels, use:' \
-		'--filter=filter -- <...>' \
-		'' \
-		'If you wish to prevent using the escape key to provide no selection, use:' \
-		'--required -- <...>' \
-		'' \
-		'If you wish to allow multiple selections:' \
-		'--multi -- <...>' \
-		'' \
-		'If you wish to confirm the selection with the user:' \
-		'--confirm -- <...>' \
-		'' \
-		'If you wish to pass values and labels, use:' \
-		'--label -- <[value, label]...> <value> <label> <value> <label>' \
-		'' \
-		'If you wish to pass label then value, use:' \
-		'--label=first -- <[label, value]...> <label> <value> <label> <value>' \
-		'' \
-		'By default, if the label and value differ, both will be displayed,' \
-		' and if they are the same, then only the value will be displayed.' \
-		'' \
-		'If you wish to customise what is displayed:' \
-		"--label --visual='\$label [\$value]' -- <[value, label]...>" \
-		"^ the value is eval'd" \
-		'' \
-		'If you wish to return the label use:' \
-		"--label --return='\$label' -- <[value, label]...>" \
-		"^ the value is eval'd" \
-		'' \
-		'If you wish to return the visual use:' \
-		"--label --return='\$visual' -- <[value, label]...>" \
-		"^ the value is eval'd" \
-		'' \
-		'If you wish to not use an alternative TTY shell, use:' \
-		'--main -- <[value, label]...>'
+	stderr cat <<-EOF
+		ABOUT:
+		Prompt the user to select a value from a list of values, in a clean and robust way.
+
+		USAGE:
+		choose-option \\
+			[--question=question] \\
+			[--filter=filter] \\
+			[--label[=first]] \\
+			[--return='\$label'] \\
+			[--visual='\$label [\$value]'] \\
+			[--required] \\
+			[--multi] \\
+			[--confirm] \\
+			[--main] \\
+			-- <[value]...> <value> <value>
+
+		If you wish to show a question above the menu:
+		--question=question -- <...>
+
+		If you wish to filter the value and/or labels, use:
+		--filter=filter -- <...>
+
+		If you wish to prevent using the escape key to provide no selection, use:
+		--required -- <...>
+
+		If you wish to allow multiple selections:
+		--multi -- <...>
+
+		If you wish to confirm the selection with the user:
+		--confirm -- <...>
+
+		If you wish to pass values and labels, use:
+		--label -- <[value, label]...> <value> <label> <value> <label>
+
+		If you wish to pass label then value, use:
+		--label=first -- <[label, value]...> <label> <value> <label> <value>
+
+		By default, if the label and value differ, both will be displayed,
+		 and if they are the same, then only the value will be displayed.
+
+		If you wish to customise what is displayed:
+		--label --visual='\$label [\$value]' -- <[value, label]...>
+		^ the value is eval'd
+
+		If you wish to return the label use:
+		--label --return='\$label' -- <[value, label]...>
+		^ the value is eval'd
+
+		If you wish to return the visual use:
+		--label --return='\$visual' -- <[value, label]...>
+		^ the value is eval'd
+
+		If you wish to not use an alternative TTY shell, use:
+		--main -- <[value, label]...>
+	EOF
 	exit 22 # Invalid argument
 fi
 
@@ -106,16 +107,16 @@ if test "$option_label" != 'no' && is-odd "${#items[@]}"; then
 fi
 
 # iterate our items
-for ((i = 0; i < ${#items[@]}; i=i+items_step)); do
+for ((i = 0; i < ${#items[@]}; i = i + items_step)); do
 	# order of
 	if test "$option_label" = 'no'; then
 		value="${items[$i]}"
 		label="${items[$i]}"
 	elif test "$option_label" = 'yes'; then
 		value="${items[$i]}"
-		label="${items[$i+1]}"
+		label="${items[$i + 1]}"
 	elif test "$option_label" = 'first'; then
-		value="${items[$i+1]}"
+		value="${items[$i + 1]}"
 		label="${items[$i]}"
 	else
 		stderr echo "bad configuration: the --label value is invalid: [$option_label]"
@@ -170,7 +171,7 @@ fi
 
 # helpers
 final_results=()
-function send_result () {
+function send_result() {
 	value="$1"
 	label="$2"
 	visual="$3"
@@ -178,7 +179,7 @@ function send_result () {
 	eval "result=\"$option_return\""
 	final_results+=("$result")
 }
-function act () {
+function act() {
 	final_results=()
 	filtered_values=()
 	filtered_labels=()
@@ -205,10 +206,10 @@ function act () {
 
 	# todo, have this reprompt
 	if is-array-empty-or-partial "${filtered_values[@]}"; then
-		echo "Filter [$option_filter] returned no results, providing you all the results to select from." > /dev/tty
+		echo "Filter [$option_filter] returned no results, providing you all the results to select from." >/dev/tty
 		option_filter=''
 		act
-		exit "$?"  # exit with the above on success and failure
+		exit "$?" # exit with the above on success and failure
 	fi
 
 	# if we have only one option, then use that
@@ -216,7 +217,8 @@ function act () {
 		send_result "${filtered_values[0]}" "${filtered_labels[0]}" "${filtered_visuals[0]}"
 	else
 		# ask
-		local ec=0; results="$(choose-menu \
+		local ec=0
+		results="$(choose-menu \
 			--question="$option_question" \
 			--multi="$option_multi" \
 			--main="$option_main" \
@@ -226,11 +228,11 @@ function act () {
 
 		# check
 		if test "$ec" -eq 62; then
-			echo "Menu timed out [$ec]." > /dev/stderr
+			echo "Menu timed out [$ec]." >/dev/stderr
 			sleep 10
 			exit "$ec"
 		elif test "$ec" -ne 0; then
-			echo "Menu failed [$ec]." > /dev/stderr
+			echo "Menu failed [$ec]." >/dev/stderr
 			# some other failure
 			sleep 10
 			exit "$ec"
@@ -239,14 +241,14 @@ function act () {
 			if test "$option_required" = 'no'; then
 				exit 0
 			else
-				echo "No input returned, despite required." > /dev/stderr
+				echo "No input returned, despite required." >/dev/stderr
 				sleep 10
 				exit 5 # Input/output error
 			fi
 		fi
 
 		# results
-		mapfile -t results <<< "$results"
+		mapfile -t results <<<"$results"
 		for i in "${results[@]}"; do
 			send_result "${filtered_values[$i]}" "${filtered_labels[$i]}" "${filtered_visuals[$i]}"
 		done
@@ -256,7 +258,8 @@ function act () {
 	if test "${#values[@]}" -gt 1 -a "$option_confirm" = 'yes'; then
 		# timeout of one minute for confirms of existing values
 		confirm_value="$(echo -n "${final_results[@]}")"
-		local ec=0; confirmed="$(choose-option \
+		local ec=0
+		confirmed="$(choose-option \
 			--timeout=60 \
 			--question="$option_question" \
 			--main="$option_main" \
@@ -264,11 +267,11 @@ function act () {
 			--label \
 			-- \
 			yes "Use: $confirm_value" \
-			no  "Select something else.")" || ec="$?"
+			no "Select something else.")" || ec="$?"
 
 		# check
 		if test "$ec" -ne 0; then
-			echo "Timed out, using fallback value: $confirm_value" > /dev/stderr
+			echo "Timed out, using fallback value: $confirm_value" >/dev/stderr
 			sleep 10
 		fi
 
@@ -276,7 +279,7 @@ function act () {
 		if test "$confirmed" = 'no'; then
 			option_filter=''
 			act
-			exit "$?"  # exit with the above on success and failure
+			exit "$?" # exit with the above on success and failure
 		fi
 	fi
 
@@ -286,4 +289,4 @@ function act () {
 
 # do the action
 act
-exit "$?"  # exit with the above on success and failure
+exit "$?" # exit with the above on success and failure
