WIP: removed `tty.bash` for `get-terminal-*` commands
todos:
- `ask` no-tty support
- documentation of fixes, new features, changes, deprecations

diff --git a/commands/choose b/commands/choose
--- a/commands/choose
+++ b/commands/choose
@@ -462,7 +462,6 @@ function choose_test() (
 )
 function choose_() (
 	source "$DOROTHY/sources/bash.bash"
-	source "$DOROTHY/sources/tty.bash"
 	__require_array 'mapfile'
 
 	# =====================================
@@ -642,7 +641,7 @@ function choose_() (
 	load_dorothy_config 'styles.bash'
 
 	# refresh the styles
-	refresh_style_cache -- 'question_title_prompt' 'question_title_result' 'question_body' 'input_warning' 'input_error' 'icon_prompt' 'result_value' 'error' 'notice' 'count_spacer' 'result_line' 'active_line' 'selected_line' 'default_line' 'empty_line' 'inactive_line' 'legend' 'key' 'count_more' 'count_selected' 'count_defaults' 'count_empty' 'bar_top' 'bar_middle' 'bar_bottom' 'icon_multi_selected' 'icon_multi_default' 'icon_multi_active' 'icon_multi_standard' 'icon_single_selected' 'icon_single_default' 'icon_single_active_required' 'icon_single_active_optional' 'icon_single_standard' 'icon_nothing_provided' 'icon_no_selection' 'icon_nothing_selected' 'legend_legend_spacer' 'legend_key_spacer' 'key_key_spacer' 'indent_bar' 'indent_active' 'indent_inactive' 'blockquote' 'nocolor__count_spacer' 'color__count_spacer'
+	refresh_style_cache -- 'question_title_prompt' 'question_title_result' 'question_body' 'input_warning' 'input_error' 'icon_prompt' 'result_value' 'error' 'notice' 'count_spacer' 'result_line' 'active_line' 'selected_line' 'default_line' 'empty_line' 'inactive_line' 'legend' 'key' 'count_more' 'count_selected' 'count_defaults' 'count_empty' 'bar_top' 'bar_middle' 'bar_bottom' 'icon_multi_selected' 'icon_multi_default' 'icon_multi_active' 'icon_multi_standard' 'icon_single_selected' 'icon_single_default' 'icon_single_active_required' 'icon_single_active_optional' 'icon_single_standard' 'icon_nothing_provided' 'icon_no_selection' 'icon_nothing_selected' 'legend_legend_spacer' 'legend_key_spacer' 'key_key_spacer' 'indent_bar' 'indent_active' 'indent_inactive' 'blockquote' 'nocolor__count_spacer' 'color__count_spacer' 'alternative_screen_buffer' 'default_screen_buffer'
 
 	# select icons
 	if test "$option_multi" = 'yes'; then
@@ -849,12 +848,12 @@ function choose_() (
 		text__pick_confirm \
 		terminal_columns_prior=-1 \
 		terminal_columns \
+		terminal_device_file \
 		terminal_margin=0 \
-		terminal_rows_prior=-1 \
-		terminal_rows \
+		terminal_lines_prior=-1 \
+		terminal_lines \
 		terminal_too_short='no' \
-		title_supported='yes' \
-		tty_target
+		title_supported='yes'
 	items_last="$((items_count - 1))"
 
 	# pick language
@@ -876,13 +875,13 @@ function choose_() (
 	fi
 
 	# prepare paging
-	tty_target="$(is-tty --fallback)"
-	if test "$tty_target" = '/dev/stderr' || __command_missing -- tput; then
+	terminal_device_file="$(get-terminal-device-file)"
+	if ! get-terminal-size-support --quiet; then
 		# fix [tput: No value for $TERM and no -T specified] errors when fetching columns and rows on CI
 		paging_supported='no'
 	fi
-	if is-ci; then
-		# [ssh -T ...] passes [test ! -t 0] [test "$tty_target" = '/dev/stderr'] [__command_exists tput]
+	if ! get-terminal-title-support --quiet; then
+		# [ssh -T ...] passes [test ! -t 0] [test "$terminal_device_file" = '/dev/stderr'] [__command_exists tput]
 		title_supported='no'
 	fi
 
@@ -994,7 +993,7 @@ function choose_() (
 		# no need for paging
 		paging_used='no'
 		# no need for row and column sizes
-		terminal_rows=0
+		terminal_lines=0
 		terminal_columns=0
 		content_columns=0
 		menu_header_rows=0
@@ -1014,18 +1013,20 @@ function choose_() (
 		# paging support is eternal, so we need to refresh if enabled
 		function refresh_terminal_size {
 			# refresh
-			terminal_rows="$(tput lines)"
-			terminal_columns="$(tput cols)"
+			local terminal_size=()
+			mapfile -t terminal_size < <(get-terminal-lines-and-columns)
+			terminal_lines="${terminal_size[0]}"
+			terminal_columns="${terminal_size[1]}"
 
 			# only recalculate everything if the size actually changed from last time
-			if test "$terminal_rows" -ne "$terminal_rows_prior" -o "$terminal_columns" -ne "$terminal_columns_prior"; then
+			if test "$terminal_lines" -ne "$terminal_lines_prior" -o "$terminal_columns" -ne "$terminal_columns_prior"; then
 				content_columns="$((terminal_columns - terminal_margin))"
 				# refresh header to column size
 				menu_header_rows="$(echo-wrap --width="$content_columns" -- "$menu_header" | echo-count-lines --stdin)"
 				# refresh the legends
 				render_lengends
 				# move start index to current item, as otherwise it could be out of range
-				if test "$terminal_rows" -lt "$terminal_rows_prior" -o "$terminal_columns" -lt "$terminal_columns_prior"; then
+				if test "$terminal_lines" -lt "$terminal_lines_prior" -o "$terminal_columns" -lt "$terminal_columns_prior"; then
 					# @todo we should detect if showing everything is possible before resorting to this
 					menu_top_index_choose="$menu_cursor_choose"
 					menu_bottom_index_choose="$menu_cursor_choose"
@@ -1037,10 +1038,10 @@ function choose_() (
 				mapfile -t items_renders < <(get-array "$items_count")
 				mapfile -t items_rows < <(get-array "$items_count")
 				# update priors
-				terminal_rows_prior="$terminal_rows"
+				terminal_lines_prior="$terminal_lines"
 				terminal_columns_prior="$terminal_columns"
 			fi
-			if test -n "$menu_resized_to" && test "$menu_resized_to" -gt "$terminal_rows"; then
+			if test -n "$menu_resized_to" && test "$menu_resized_to" -gt "$terminal_lines"; then
 				terminal_too_short='yes'
 			else
 				terminal_too_short='no'
@@ -1357,7 +1358,7 @@ function choose_() (
 			then
 				menu_skip_render='yes'
 				menu_mode='choose'
-				__print_string "$style__bell" >"$tty_target"
+				__print_string "$style__bell" >"$terminal_device_file"
 				return 0
 			fi
 		fi
@@ -1474,7 +1475,7 @@ function choose_() (
 		menu_resized_to=''
 		# debug
 		function debug {
-			printf '%s' $'\e]0;'"c=$menu_cursor,mi=$menu_index,ii=$item_index,d=$menu_direction,t=$menu_top_index,b=$menu_bottom_index,l=$menu_last,u=$paging_used,r=$menu_rows,mr=$menu_resized_to,tr=$terminal_rows,tts=$terminal_too_short,c=$debug_counter"$'\a' >"$tty_target"
+			printf '%s' $'\e]0;'"c=$menu_cursor,mi=$menu_index,ii=$item_index,d=$menu_direction,t=$menu_top_index,b=$menu_bottom_index,l=$menu_last,u=$paging_used,r=$menu_rows,mr=$menu_resized_to,tr=$terminal_lines,tts=$terminal_too_short,c=$debug_counter"$'\a' >"$terminal_device_file"
 			debug_counter="$((debug_counter + 1))"
 		}
 		# e.g. go to second page, navigate half way, go page up
@@ -1553,7 +1554,7 @@ function choose_() (
 				menu_rows="$((menu_header_rows + items_bundled_rows + item_rows + menu_legend_rows + 3))"
 				item_line="${line_prefix}${item_rendered}${line_end}"$'\n'
 				items_bundled_rows="$((items_bundled_rows + item_rows))"
-				if test "$menu_rows" -gt "$terminal_rows"; then
+				if test "$menu_rows" -gt "$terminal_lines"; then
 					if test -z "$items_bundled"; then
 						# we need to reszie the terminal
 						menu_resized_to="$menu_rows"
@@ -1597,7 +1598,7 @@ function choose_() (
 
 		# if paging was used, and we could support more rows, then re-render in the other direction
 		# @todo update menu_index instead of cursor, so that cursor remains sensible (optional, may not be a good idea)
-		if test "$paging_used" = 'yes' -a "$menu_rows" -lt "$terminal_rows"; then
+		if test "$paging_used" = 'yes' -a "$menu_rows" -lt "$terminal_lines"; then
 			if test "$menu_direction" -eq -1 -a "$menu_top_index" -eq 0; then
 				menu_direction=1
 				render_menu 0
@@ -1793,13 +1794,13 @@ function choose_() (
 		else
 			menu_title+=$'\e]0;'"👉 ${verb} ${verb_total} of ${items_count} items 👈"$'\a'
 		fi
-		printf '%s' "${style__clear_screen}${style__hide_cursor}${menu_title}${menu_header}${bar_top_content}${bar_middle_content}${items_bundled}${bar_bottom_content}${menu_legend_content}" >"$tty_target"
+		printf '%s' "${style__clear_screen}${style__hide_cursor}${menu_title}${menu_header}${bar_top_content}${bar_middle_content}${items_bundled}${bar_bottom_content}${menu_legend_content}" >"$terminal_device_file"
 		if test -n "$menu_resized_to"; then
 			refresh_terminal_size
 			if test "$terminal_too_short" = 'yes'; then
 				menu_title=$'\e]0;'"‼️ TERMINAL TOO SHORT ‼️"$'\a'
-				local additional_rows="$((menu_resized_to - terminal_rows))"
-				printf '%s' "${style__clear_screen}${style__hide_cursor}${menu_title}${style__error}You have been prompted to make a menu selection, however the terminal does not have enough vertical height to make that selection.${style__end__error}"$'\n'"${style__notice}Increase the terminal height or reduce font size to proceed, then press any key.${style__end__notice}"$'\n'"Terminal rows = ${terminal_rows}, Needed rows = ${menu_resized_to}, Additional rows = ${additional_rows}"$'\n' >"$tty_target"
+				local additional_rows="$((menu_resized_to - terminal_lines))"
+				printf '%s' "${style__clear_screen}${style__hide_cursor}${menu_title}${style__error}You have been prompted to make a menu selection, however the terminal does not have enough vertical height to make that selection.${style__end__error}"$'\n'"${style__notice}Increase the terminal height or reduce font size to proceed, then press any key.${style__end__notice}"$'\n'"Terminal rows = ${terminal_lines}, Needed rows = ${menu_resized_to}, Additional rows = ${additional_rows}"$'\n' >"$terminal_device_file"
 			fi
 		fi
 	}
@@ -1830,7 +1831,7 @@ function choose_() (
 					render+="${style__result_line}${style__icon_nothing_selected}${style__end__result_line}"$'\n'
 				fi
 				# inform
-				__print_string "$render" >"$tty_target"
+				__print_string "$render" >"$terminal_device_file"
 			elif test -n "$commentary"; then
 				# inform to stderr, consistent with ask, choose, confirm
 				__print_string "$render" >/dev/stderr
@@ -1845,7 +1846,7 @@ function choose_() (
 			# inform
 			if test -n "$commentary"; then
 				if test "$option_linger" = 'yes'; then
-					__print_string "$render" >"$tty_target"
+					__print_string "$render" >"$terminal_device_file"
 				else
 					__print_string "$render" >/dev/stderr
 				fi
@@ -1857,11 +1858,11 @@ function choose_() (
 		local input read_status keys skips
 		# action
 		function show_cursor {
-			__print_string "$style__show_cursor" >"$tty_target"
+			__print_string "$style__show_cursor" >"$terminal_device_file"
 			trap - EXIT
 		}
 		trap show_cursor EXIT
-		tty_start
+		__print_string "$style__alternative_screen_buffer" >"$terminal_device_file"
 		while true; do
 			# (re-)render the menu?
 			if test "$menu_skip_render" = 'no'; then
@@ -2021,7 +2022,7 @@ function choose_() (
 			fi
 		done
 		show_cursor
-		tty_finish
+		__print_string "$style__default_screen_buffer" >"$terminal_device_file"
 	}
 
 	# select the defaults
