fixes
- fix command-working's command-exists identity crisis
- config-helper internal improvement
- echo-quiet prevent empty quiet values from erroring, allowing quiet arguments to be passed along
- github-download now prevents more signature files from interfering with downloads
- setup-util now passes quiet status to github-download and down
- setup-util-{sd,tealdeer,teip} now only add github option if there is platform support
- add setup-util-teip

diff --git a/commands/command-working b/commands/command-working
--- a/commands/command-working
+++ b/commands/command-working
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-function command-exists() (
+function command-working() (
 	# =====================================
 	# Arguments
 
@@ -44,13 +44,44 @@ function command-exists() (
 	fi
 
 	# =====================================
-	# Action
+	# Helpers
 
-	# helper
-	function check_working {
-		type -P "$command"
-		"$command" --help || "$command" --version || "$command" -h || "$command" version
+	# https://github.com/greymd/teip/issues/29
+	local exceptions=(
+		teip
+	)
+	function check_status {
+		local ec=0
+		("$@") || ec="$?"
+		# check for correct failure codes
+		if test "$ec" -eq 22; then
+			return 0
+		else
+			# otherwise return success or failure code
+			return "$ec"
+		fi
 	}
+	function check_working {
+		# check it exists first
+		type -P "$command"
+
+		# check if presence is enough for this command
+		local exception
+		for exception in "${exceptions[@]}"; do
+			if [[ $command == */"$exception" ]]; then
+				return 0
+			fi
+		done
+
+		# it does exist, now check its return code
+		check_status "$command" --version ||
+			check_status "$command" version ||
+			check_status "$command" --help ||
+			check_status "$command" -h
+	}
+
+	# =====================================
+	# Action
 
 	# -P  force a PATH search for each NAME, even if it is an alias,
 	#     builtin, or function, and returns the name of the disk file
@@ -64,5 +95,5 @@ function command-exists() (
 
 # fire if invoked standalone
 if test "$0" = "${BASH_SOURCE[0]}"; then
-	command-exists "$@"
+	command-working "$@"
 fi
