*: fix bash 5.1 (perhaps more) return issue, env: fix/improve caching

diff --git a/commands/command-working b/commands/command-working
--- a/commands/command-working
+++ b/commands/command-working
@@ -128,19 +128,19 @@ function command_working() (
 		# continue with the command
 		cmd+=("$@")
 		# run the command hiding the output
-		__do --redirect-status={cmd_exit_status} --redirect-output={cmd_output} -- command "${cmd[@]}" || return # eval
-		__return $? || return
+		__do --redirect-status={cmd_exit_status} --redirect-output={cmd_output} -- command "${cmd[@]}" || return $? # eval
+		__return $? || return $?
 		# check for correct failure codes
 		if [[ $cmd_exit_status -eq 22 || $cmd_exit_status -eq 200 ]]; then
 			return 0
 		else
 			# otherwise return success or failure code
-			cmd_string="$(echo-escape-command -- "${cmd[@]}")" || return
+			cmd_string="$(echo-escape-command -- "${cmd[@]}")" || return $?
 			if [[ -n $cmd_output ]]; then
 				cmd_output+=$'\n'
 			fi
 			local styled
-			styled="$(__print_style --element+red="$cmd_string" $'\n' "$cmd_output" --/element+red="$cmd_string" --status="$cmd_exit_status")" || return
+			styled="$(__print_style --element+red="$cmd_string" $'\n' "$cmd_output" --/element+red="$cmd_string" --status="$cmd_exit_status")" || return $?
 			failures+=("$styled")
 			return "$cmd_exit_status"
 		fi
@@ -151,23 +151,23 @@ function command_working() (
 
 		# check it exists first
 		local cmd cmd_string executable_status
-		cmd_string="$(echo-escape-command -- "$1")" || return
+		cmd_string="$(echo-escape-command -- "$1")" || return $?
 		cmd="$(type -P "$1" 2>/dev/null || :)"
 		if [[ -z $cmd ]]; then
 			# we must at least find it
-			__print_style --stderr --element/+red="$cmd_string" --status=3 ' ' --error='not working because it is missing' || return
+			__print_style --stderr --element/+red="$cmd_string" --status=3 ' ' --error='not working because it is missing' || return $?
 			return 3 # ESRCH 3 No such process
 		fi
 
 		__try {executable_status} -- is-executable --quiet -- "$cmd"
 		if [[ $executable_status -ne 0 ]]; then
 			case "$executable_status" in
-			2) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is missing.' || return ;;
-			9) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is a broken symlink.' || return ;;
-			13) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is not accessible.' || return ;;
-			22) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is not a valid argument.' || return ;;
-			93) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is not executable.' || return ;;
-			*) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because of unknown failure.' || return ;;
+			2) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is missing.' || return $? ;;
+			9) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is a broken symlink.' || return $? ;;
+			13) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is not accessible.' || return $? ;;
+			22) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is not a valid argument.' || return $? ;;
+			93) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is not executable.' || return $? ;;
+			*) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because of unknown failure.' || return $? ;;
 			esac
 			return "$executable_status"
 		fi
@@ -189,7 +189,7 @@ function command_working() (
 				__print_style --stderr \
 					--element+red="$cmd_string" --newline \
 					--="$(__print_lines "${failures[@]}")" --newline \
-					--/element+red="$cmd_string" --status=1 ' ' --error='not working because it is failing' || return
+					--/element+red="$cmd_string" --status=1 ' ' --error='not working because it is failing' || return $?
 				return 1 # command not working
 			}
 	}
@@ -199,7 +199,7 @@ function command_working() (
 
 	local command
 	for command in "${option_commands[@]}"; do
-		__check_working "$command" || return
+		__check_working "$command" || return $?
 	done
 	return 0 # all commands are working
 )
diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -92,7 +92,7 @@ function dorothy_() (
 	# if we are remove, but dorothy exists locally, defer to local, as otherwise we are making expectations about dorothy commands that may be newer than present
 	if [[ $is_remote == 'yes' && -x "$DOROTHY/commands/dorothy" ]]; then
 		"$DOROTHY/commands/dorothy" "$@"
-		return
+		return $?
 	fi
 
 	# =====================================
@@ -126,20 +126,20 @@ function dorothy_() (
 
 	function __print_help {
 		if [[ -n $DOROTHY && -f "$DOROTHY/sources/bash.bash" ]]; then
-			__source 'sources/bash.bash' || return
-			__source 'sources/styles.bash' || return
-			__print_help "$@" || return
+			__source 'sources/bash.bash' || return $?
+			__source 'sources/styles.bash' || return $?
+			__print_help "$@" || return $?
 		else
-			cat >&2 || return
+			cat >&2 || return $?
 			if [[ $# -ne 0 ]]; then
 				# use printf, as __print_line not loaded yet
-				printf '\nERROR:\n%s\n' "$*" >&2 || return
+				printf '\nERROR:\n%s\n' "$*" >&2 || return $?
 			fi
 		fi
 	}
 
 	function help {
-		__print_help "$@" <<-EOF || return
+		__print_help "$@" <<-EOF || return $?
 			ABOUT:
 			Manipulate the Dorothy dotfile ecosystem.
 
@@ -235,11 +235,11 @@ function dorothy_() (
 	local item action='' option_xdg='' option_deps='' option_branch='' option_remote='' option_user='' option_args=() # option_slug option_reference defined earlier
 	function __affirm_action_is_undefined {
 		if [[ -n $action ]]; then
-			help 'Only one <action> may be provided.' || return
+			help 'Only one <action> may be provided.' || return $?
 		fi
 	}
 	function __set_action {
-		__affirm_action_is_undefined || return
+		__affirm_action_is_undefined || return $?
 		action="$1"
 	}
 	while [[ $# -ne 0 ]]; do
@@ -389,12 +389,12 @@ function dorothy_() (
 
 	# see [commands/is-mac] for details
 	function __is_mac {
-		[[ $OSTYPE == darwin* ]] || return
+		[[ $OSTYPE == darwin* ]] || return $?
 	}
 
 	# see [commands/is-alpine] for details
 	function __is_alpine {
-		[[ -f /etc/os-release ]] && grep --quiet --ignore-case --fixed-strings --regexp='ID=alpine' -- /etc/os-release 2>/dev/null || return
+		[[ -f /etc/os-release ]] && grep --quiet --ignore-case --fixed-strings --regexp='ID=alpine' -- /etc/os-release 2>/dev/null || return $?
 	}
 
 	# =====================================
@@ -577,23 +577,23 @@ function dorothy_() (
 		function __traverse() (
 			local path="$1"
 			if [[ ! -d $path ]]; then
-				return
+				return $?
 			fi
-			cd "$path" || return
-			__print_style --h3="Dependencies: $path" || return
+			cd "$path" || return $?
+			__print_style --h3="Dependencies: $path" || return $?
 			if [[ -f package.json ]] && __command_exists -- npx npm; then
 				if [[ $upgrade == 'yes' ]]; then
 					npx npm-check-updates -u || :
 				fi
-				npm install || return
+				npm install || return $?
 			fi
 			if [[ -d .trunk && ! -e .git/hooks/pre-push ]]; then
-				printf 'trunk check --ci --no-progress --trigger=git-push\n' >.git/hooks/pre-push || return
+				printf 'trunk check --ci --no-progress --trigger=git-push\n' >.git/hooks/pre-push || return $?
 				if [[ $upgrade == 'yes' ]]; then
-					trunk upgrade || return
+					trunk upgrade || return $?
 				fi
 			fi
-			__print_style --g3="Dependencies: $path" || return
+			__print_style --g3="Dependencies: $path" || return $?
 		)
 		__traverse "$DOROTHY"
 		__traverse "$DOROTHY/user"
@@ -737,21 +737,21 @@ function dorothy_() (
 		}
 		function __update_modern_dorothy {
 			if __command_exists -- git-helper; then
-				__print_style --h2="Syncing the Dorothy installation at $DOROTHY" || return
+				__print_style --h2="Syncing the Dorothy installation at $DOROTHY" || return $?
 				# verify, so we don't have to do it via `--verify` later
-				git-helper verify --path="$DOROTHY" || return
+				git-helper verify --path="$DOROTHY" || return $?
 				# sync with its configured remote first (their upstream)
-				git-helper sync --path="$DOROTHY" || return
+				git-helper sync --path="$DOROTHY" || return $?
 				# sync with our intended remote second (the upstream)
-				git-helper sync --path="$DOROTHY" --remote="$the_upstream_remote" --url="$the_upstream_git_https" || return
-				__print_style --g2="Syncing the Dorothy installation at $DOROTHY" || return
+				git-helper sync --path="$DOROTHY" --remote="$the_upstream_remote" --url="$the_upstream_git_https" || return $?
+				__print_style --g2="Syncing the Dorothy installation at $DOROTHY" || return $?
 			else
 				return 1
 			fi
 		}
 		function update_dorothy {
 			# https://github.com/bevry/dorothy/issues/215
-			__update_modern_dorothy || __return $? -- __print_error 'Dorothy was unable to be automatically updated. Update Dorothy manually then try again.' || return
+			__update_modern_dorothy || __return $? -- __print_error 'Dorothy was unable to be automatically updated. Update Dorothy manually then try again.' || return $?
 		}
 
 		# install dorothy if necessary
@@ -809,9 +809,9 @@ function dorothy_() (
 		fi
 
 		# create/update
-		__print_style --h2="Syncing the Dorothy User Configuration at $DOROTHY_USER" || return
+		__print_style --h2="Syncing the Dorothy User Configuration at $DOROTHY_USER" || return $?
 		git-helper sync --path="$DOROTHY_USER" --label='Dorothy User Configuration' --new --update=optional --project='dotfiles' --description="$dorothy_user_description" --homepage="$dorothy_homepage" --url="$option_user"
-		__print_style --g2="Syncing the Dorothy User Configuration at $DOROTHY_USER" || return
+		__print_style --g2="Syncing the Dorothy User Configuration at $DOROTHY_USER" || return $?
 
 		# move if necessary, and fix permissions
 		relocate_user_if_necessary
@@ -923,7 +923,7 @@ function dorothy_() (
 	}
 
 	function act_uninstall {
-		__unrecognised_arguments "$@" || return
+		__unrecognised_arguments "$@" || return $?
 
 		# log
 		__print_style --h1='Uninstall Dorothy'
@@ -952,7 +952,7 @@ function dorothy_() (
 	}
 
 	function act_update {
-		__unrecognised_arguments "$@" || return
+		__unrecognised_arguments "$@" || return $?
 
 		# log
 		__print_style --h1='Update Dorothy'
@@ -1017,7 +1017,7 @@ function dorothy_() (
 				. '$DOROTHY/init.sh'
 				echo-style 'Your are now using the ' --invert='$ACTIVE_POSIX_SHELL' ' shell with Dorothy loaded from ' --code='$DOROTHY' \$'\n' 'Use the ' --code='exit' ' command to return to your parent shell.' \$'\n' 'Use ' --code='dorothy commands' ' to see available commands.'
 			EOF
-			"$shell" --interactive --rcfile "$rcfile" || return
+			"$shell" --interactive --rcfile "$rcfile" || return $?
 		}
 		function __repl_fish {
 			"$shell" --interactive --login --no-config --init-command="$(
@@ -1027,12 +1027,12 @@ function dorothy_() (
 					source '$DOROTHY/init.fish'
 					echo-style 'Your are now using the ' --invert='fish' ' shell with Dorothy loaded from ' --code='$DOROTHY' \n 'Use the ' --code='exit' ' command to return to your parent shell.' \n 'Use ' --code='dorothy commands' ' to see available commands.'
 				EOF
-			)" || return
+			)" || return $?
 		}
 		function __repl_nu {
 			# No longer supported:
 			# Error:   × Nushell launched as a REPL, but STDIN is not a TTY; either launch in a valid terminal or provide arguments to invoke a script!
-			setup-util-nu --quiet || return
+			setup-util-nu --quiet || return $?
 			"$shell" --interactive --login --no-config-file --execute "$(
 				cat <<-EOF
 					#!/usr/bin/env nu
@@ -1040,15 +1040,15 @@ function dorothy_() (
 					source '$DOROTHY/init.nu'
 					echo-style 'Your are now using the ' --invert='nu' ' shell with Dorothy loaded from ' --code='$DOROTHY' "\n" 'Use the ' --code='exit' ' command to return to your parent shell.' "\n" 'Use ' --code='dorothy commands' ' to see available commands.'
 				EOF
-			)" || return
+			)" || return $?
 		}
 
 		# act, installing the shell if it is missing
 		if __has --source={shells} -- "$shell"; then
-			setup-util-"$shell" --quiet || return
+			setup-util-"$shell" --quiet || return $?
 			# TERM dumb fallback solves: warning: Could not set up terminal because $TERM is unset. Falling back to hardcoded xterm-256color values
 			export DOROTHY_RUN=yes TERM="${TERM:-"dumb"}"
-			__repl_"$shell" || return
+			__repl_"$shell" || return $?
 		else
 			__print_error 'Cannot use ' --invert="$shell" ' as that shell does not support REPLs with custom configuration.'
 			return 93 # EPROTONOSUPPORT 93 Protocol not supported
@@ -1081,14 +1081,14 @@ function dorothy_() (
 		# now that our environment is setup, run the command
 		export DOROTHY_RUN=yes
 		command "${args[@]}" # eval
-		return
+		return $?
 	}
 
 	# =====================================
 	# Actions: ...
 
 	function act_commands {
-		__unrecognised_arguments "$@" || return
+		__unrecognised_arguments "$@" || return $?
 
 		# pre-requisites
 		assert_dorothy_configured
@@ -1107,7 +1107,7 @@ function dorothy_() (
 	}
 
 	function act_permissions {
-		__unrecognised_arguments "$@" || return
+		__unrecognised_arguments "$@" || return $?
 
 		# log
 		__print_style --h1='Correct Dorothy Permissions'
@@ -1124,7 +1124,7 @@ function dorothy_() (
 	}
 
 	function act_edit {
-		__unrecognised_arguments "$@" || return
+		__unrecognised_arguments "$@" || return $?
 
 		# log
 		__print_style --h1='Edit Dorothy'
@@ -1146,7 +1146,7 @@ function dorothy_() (
 	}
 
 	function act_review {
-		__unrecognised_arguments "$@" || return
+		__unrecognised_arguments "$@" || return $?
 
 		# log
 		__print_style --h1='Review Dorothy'
@@ -1165,11 +1165,11 @@ function dorothy_() (
 	}
 
 	function __get_themes {
-		__print_lines 'system' || return
-		fs-path --no-parents --no-extensions -- "$DOROTHY/themes/"*.* "$DOROTHY/user/themes/"*.* | echo-unique --stdin || return
+		__print_lines 'system' || return $?
+		fs-path --no-parents --no-extensions -- "$DOROTHY/themes/"*.* "$DOROTHY/user/themes/"*.* | echo-unique --stdin || return $?
 	}
 	function act_theme {
-		__unrecognised_arguments "$@" || return
+		__unrecognised_arguments "$@" || return $?
 
 		# log
 		__print_style --h1='Select Dorothy Theme'
@@ -1219,8 +1219,8 @@ function dorothy_() (
 			item="$1"
 			shift
 			case "$item" in
-			--no-upgrade* | --upgrade*) __flag --source={item} --target={upgrade} --affirmative --coerce || return ;;
-			*) __unrecognised_arguments "$item" "$@" || return ;;
+			--no-upgrade* | --upgrade*) __flag --source={item} --target={upgrade} --affirmative --coerce || return $? ;;
+			*) __unrecognised_arguments "$item" "$@" || return $? ;;
 			esac
 		done
 
@@ -1250,11 +1250,11 @@ function dorothy_() (
 			item="$1"
 			shift
 			case "$item" in
-			--no-check* | --check*) __flag --source={item} --target={check} --affirmative --coerce || return ;;
-			--no-format* | --format*) __flag --source={item} --target={format} --affirmative --coerce || return ;;
-			--no-backers* | --backers*) __flag --source={item} --target={backers} --affirmative --coerce || return ;;
-			--no-upgrade* | --upgrade*) __flag --source={item} --target={upgrade} --affirmative --coerce || return ;;
-			*) __unrecognised_arguments "$item" "$@" || return ;;
+			--no-check* | --check*) __flag --source={item} --target={check} --affirmative --coerce || return $? ;;
+			--no-format* | --format*) __flag --source={item} --target={format} --affirmative --coerce || return $? ;;
+			--no-backers* | --backers*) __flag --source={item} --target={backers} --affirmative --coerce || return $? ;;
+			--no-upgrade* | --upgrade*) __flag --source={item} --target={upgrade} --affirmative --coerce || return $? ;;
+			*) __unrecognised_arguments "$item" "$@" || return $? ;;
 			esac
 		done
 
@@ -1299,9 +1299,9 @@ function dorothy_() (
 		# backers
 		if [[ $backers == 'yes' ]]; then
 			function __traverse() (
-				cd "$1" || return
+				cd "$1" || return $?
 				if [[ -f package.json ]] && __command_exists -- npx npm; then
-					github-auth -- npm run our:meta || return # this requires reformatting afterwards
+					github-auth -- npm run our:meta || return $? # this requires reformatting afterwards
 				fi
 			)
 			__traverse "$DOROTHY"
@@ -1383,20 +1383,20 @@ function dorothy_() (
 		function __traverse() (
 			local path="$1"
 			if [[ ! -d "$path/.trunk" ]]; then
-				return
+				return $?
 			fi
-			cd "$path" || return
-			__print_style --h3="$intent: $path" || return
+			cd "$path" || return $?
+			__print_style --h3="$intent: $path" || return $?
 			if [[ $format == 'yes' && $check == 'yes' ]]; then
 				# if format fails, it is likely for a check failure, so ensure check is run before crashing
-				trunk fmt --all "${trunk_args[@]}" || __return $? -- trunk check --all "${trunk_args[@]}" || return
-				trunk check --all "${trunk_args[@]}" || return
+				trunk fmt --all "${trunk_args[@]}" || __return $? -- trunk check --all "${trunk_args[@]}" || return $?
+				trunk check --all "${trunk_args[@]}" || return $?
 			elif [[ $format == 'yes' ]]; then
-				trunk fmt --all "${trunk_args[@]}" || return
+				trunk fmt --all "${trunk_args[@]}" || return $?
 			else
-				trunk check --all "${trunk_args[@]}" || return
+				trunk check --all "${trunk_args[@]}" || return $?
 			fi
-			__print_style --g3="$intent: $path" || return
+			__print_style --g3="$intent: $path" || return $?
 		)
 		__traverse "$DOROTHY"
 		__traverse "$DOROTHY/user"
@@ -1428,7 +1428,7 @@ function dorothy_() (
 				;;
 			--*)
 				help 'An unrecognised flag was provided: ' --variable-value={item}
-				return
+				return $?
 				;;
 			*) only+=("$item") ;;
 			esac
@@ -1444,7 +1444,7 @@ function dorothy_() (
 		source "$DOROTHY/sources/ripgrep.bash"
 
 		# fixtures
-		git-helper sync --path="$DOROTHY/fixtures" --label='Dorothy Fixtures' --update=optional --url="$dorothy_fixtures_uri" || return
+		git-helper sync --path="$DOROTHY/fixtures" --label='Dorothy Fixtures' --update=optional --url="$dorothy_fixtures_uri" || return $?
 
 		# load bash binaries
 		local environment_bash_binary other_bash_binaries=() user_bash_binaries_string user_bash_binary
@@ -1615,7 +1615,7 @@ function dorothy_() (
 	}
 
 	function act_todos {
-		__unrecognised_arguments "$@" || return
+		__unrecognised_arguments "$@" || return $?
 
 		# action
 		__print_style --h1='Dorothy Todos'
@@ -1633,7 +1633,7 @@ function dorothy_() (
 		)
 		function __todos_scan {
 			local filepath filename messages file_status success_count=0 fail_count=0 matches
-			__print_style --h2="$1" || return
+			__print_style --h2="$1" || return $?
 			for filepath in "$DOROTHY/$1/"*; do
 				filename="$(basename -- "$filepath")"
 				messages=()
@@ -1704,9 +1704,9 @@ function dorothy_() (
 				__print_style --element/="$filename" --status="$file_status" "${messages[@]}"
 			done
 			if [[ $fail_count -eq 0 ]]; then
-				__print_style --g2="$1" ' ' --code-good1="$success_count" --good1=' successes' || return
+				__print_style --g2="$1" ' ' --code-good1="$success_count" --good1=' successes' || return $?
 			else
-				__print_style --e2="$1" ' ' --code-good1="$success_count" --good1=' successes' ' ' --code-error1="$fail_count" --error1=' failures' || return
+				__print_style --e2="$1" ' ' --code-good1="$success_count" --good1=' successes' ' ' --code-error1="$fail_count" --error1=' failures' || return $?
 				return 1
 			fi
 		}
diff --git a/commands/dorothy-internals b/commands/dorothy-internals
--- a/commands/dorothy-internals
+++ b/commands/dorothy-internals
@@ -22,7 +22,7 @@ source "$DOROTHY/sources/ansi.bash"
 # Then an ERR trap will be thrown, causing unintended logic paths
 
 # Bash versions prior to 4.4, have a bug where `return <non-zero>` becomes `return 0` within traps
-# > _run_trap_internal: make sure to catch and use return values supplied as arguments to return; instead of just catching return, make sure we use return_catch_value as well. Affects RETURN, DEBUG, ERROR traps.
+# > _run_trap_internal: make sure to catch and use return values supplied as arguments to return $?; instead of just catching return, make sure we use return_catch_value as well. Affects RETURN, DEBUG, ERROR traps.
 # > https://stackoverflow.com/q/79495360/130638
 # There are some ways to work around this, such as leveraging difference between bash 4.2 and 4.3; however nothing is perfect, as such detection, prevention, and crashing for consistency and safety is essential
 # This is likely what actually caused this bug report:
@@ -164,7 +164,7 @@ function __render_csv {
 	local result_length=6
 
 	# csv file handling
-	echo-file --raw -- "$option_csv_file" | echo-write --atomic -- "$option_csv_file" || return
+	echo-file --raw -- "$option_csv_file" | echo-write --atomic -- "$option_csv_file" || return $?
 
 	# fetch details
 	local implementation version test result
@@ -252,7 +252,7 @@ function __render_csv {
 	result_length=$((result_length + 20))
 
 	# output result
-	printf "%-${implementation_length}s%-${version_length}s%-${test_length}s%-${result_length}s${c_end_line}\n" "${parts[@]}" || return
+	printf "%-${implementation_length}s%-${version_length}s%-${test_length}s%-${result_length}s${c_end_line}\n" "${parts[@]}" || return $?
 }
 
 # handle multiple bash versions
@@ -346,7 +346,7 @@ function __begin_test_block {
 	fi
 
 	# verify all test data is as expected
-	__verify_test_blocks || exit
+	__verify_test_blocks || exit $?
 
 	# note the test exists
 	TEST_NAME="$option_name" TEST_DURATION=''
@@ -376,8 +376,8 @@ function __begin_test_block {
 		# note the test is skipped
 		TESTS_SKIP+=("$TEST_NAME")
 		CSV_UPDATES+="$option_implementation,$SUITE_NAME,$TEST_NAME,SKIPPED"$'\n'
-		__complete_test_block || exit
-		# __print_style --stderr --h2="$TEST_NAME" --newline --warning='SKIPPED MANUAL' --newline --e2="$TEST_NAME" || return
+		__complete_test_block || exit $?
+		# __print_style --stderr --h2="$TEST_NAME" --newline --warning='SKIPPED MANUAL' --newline --e2="$TEST_NAME" || return $?
 		# return non-zero such that the begin block is not entered
 		return 1
 	fi
@@ -446,7 +446,7 @@ function __begin_test_block {
 		fi
 
 		# now that the result is noted, remove from pending
-		__complete_test_block || exit
+		__complete_test_block || exit $?
 
 		# return non-zero such that the begin block is not entered
 		return 1
@@ -457,10 +457,10 @@ function __begin_test_block {
 }
 function __run_test_block {
 	local results time_before time_after
-	time_before="$(__get_epoch_time)" || return
+	time_before="$(__get_epoch_time)" || return $?
 	results="$(tests 2>&1)"
-	time_after="$(__get_epoch_time)" || return
-	TEST_DURATION="$(echo-duration --before="$time_before" --after="$time_after")" || return
+	time_after="$(__get_epoch_time)" || return $?
+	TEST_DURATION="$(echo-duration --before="$time_before" --after="$time_after")" || return $?
 	__end_test_block {results} "$@"
 }
 function __end_test_block {
@@ -539,7 +539,7 @@ function __end_test_block {
 		__print_style --stderr --e2="$TEST_NAME" "${duration_args[@]}" || __crash_broken
 	fi
 	# now that the result is noted, remove from pending
-	__complete_test_block || exit
+	__complete_test_block || exit $?
 }
 function __complete_test_block {
 	# run once the test is ended, and on crash test ending
@@ -573,7 +573,7 @@ function __complete_test_block {
 		fi
 	fi
 	# verify all test data is as expected
-	__verify_test_blocks || exit
+	__verify_test_blocks || exit $?
 }
 function __verify_test_blocks {
 	local -i count_tests="${#TESTS[@]}" count_pending="${#TESTS_PENDING[@]}" count_ok="${#TESTS_OK[@]}" count_fail="${#TESTS_FAIL[@]}" count_skip="${#TESTS_SKIP[@]}" count_finished
@@ -677,10 +677,10 @@ function __apply_escaped_command {
 	local var="$1" pieces='' piece escaped
 	shift
 	for piece in "$@"; do
-		printf -v escaped '%q' "$piece" || return
+		printf -v escaped '%q' "$piece" || return $?
 		pieces+="$escaped "
 	done
-	printf -v "$var" '%s' "${pieces% }" || return
+	printf -v "$var" '%s' "${pieces% }" || return $?
 }
 
 function __eval { # this cannot be a subshell function
@@ -1273,9 +1273,9 @@ if __begin_test_block --name='__return'; then
 		COLOR=no
 		set +e
 
-		__eval __return
+		__eval __return $?
 		[[ 1 -eq 2 ]]
-		__return # don't use eval, as it has preceeding commands
+		__return $? # don't use eval, as it has preceeding commands
 		__print_lines "$S2" "__return" "[status = $?]"
 
 		__eval __return 0
@@ -2338,7 +2338,7 @@ function recursed_standard {
 	__print_lines "caught_do_03 = $caught_do_03 ?= $?"
 	__do --copy-status={caught_do_04} -- __return 204
 	__print_lines "caught_do_04 = $caught_do_04 ?= $?"
-	__do --copy-status={caught_do_05} -- __return 205 || return
+	__do --copy-status={caught_do_05} -- __return 205 || return $?
 	__print_lines "caught_do_05 = $caught_do_05 ?= $?"
 	return 99
 }
@@ -2359,7 +2359,7 @@ function recursed_subshell() (
 	__print_lines "caught_do_03 = $caught_do_03 ?= $?"
 	__do --copy-status={caught_do_04} -- __return 204
 	__print_lines "caught_do_04 = $caught_do_04 ?= $?"
-	__do --copy-status={caught_do_05} -- __return 205 || return
+	__do --copy-status={caught_do_05} -- __return 205 || return $?
 	__print_lines "caught_do_05 = $caught_do_05 ?= $?"
 	return 99
 )
