inline `echo-style` as `__print_style`
- `edit`: fix error if no editors
- `is-bash-version-outdated`: better verbose and tests
- `dorothy-internals`: no longer only do `__iterate` tests under certain conditions as performance is now good enough we test it under all conditions

/ref
- dad7055f06d81f7a8cd6231dbb998b8bf6fbf555
- ab3dc085c1abd04855c7264eedab305f968a9a60
- 1ffa88614ab3f3a24960a8a197e4219bbc03a658
- a2bc96f638f44715cadb994123c0d8af477b97f9

diff --git a/commands/command-working b/commands/command-working
--- a/commands/command-working
+++ b/commands/command-working
@@ -49,7 +49,7 @@ function command_working() (
 			Returns on first failure.
 		EOF
 		if [[ $# -ne 0 ]]; then
-			echo-error "$@"
+			__print_error "$@"
 		fi
 		return 22 # EINVAL 22 Invalid argument
 	}
@@ -126,7 +126,7 @@ function command_working() (
 		# continue with the command
 		cmd+=("$@")
 		# run the command hiding the output
-		__do --redirect-status={cmd_exit_status} --redirect-output={cmd_output} -- command "${cmd[@]}" # eval
+		__do --redirect-status={cmd_exit_status} --redirect-output={cmd_output} -- command "${cmd[@]}" || return # eval
 		__return $? || return
 		# check for correct failure codes
 		if [[ $cmd_exit_status -eq 22 || $cmd_exit_status -eq 200 ]]; then
@@ -137,9 +137,9 @@ function command_working() (
 			if [[ -n $cmd_output ]]; then
 				cmd_output+=$'\n'
 			fi
-			failures+=("$(
-				echo-style --element+red="$cmd_string" $'\n' "$cmd_output" --/element+red="$cmd_string" --status="$cmd_exit_status"
-			)")
+			local styled
+			styled="$(__print_style --element+red="$cmd_string" $'\n' "$cmd_output" --/element+red="$cmd_string" --status="$cmd_exit_status")" || return
+			failures+=("$styled")
 			return "$cmd_exit_status"
 		fi
 	}
@@ -153,19 +153,19 @@ function command_working() (
 		cmd="$(type -P "$1" 2>/dev/null || :)"
 		if [[ -z $cmd ]]; then
 			# we must at least find it
-			echo-style --stderr --element/+red="$cmd_string" --status=3 ' ' --error='not working because it is missing' || return
+			__print_style --stderr --element/+red="$cmd_string" --status=3 ' ' --error='not working because it is missing' || return
 			return 3 # ESRCH 3 No such process
 		fi
 
 		__try {executable_status} -- is-executable --quiet -- "$cmd"
 		if [[ $executable_status -ne 0 ]]; then
 			case "$executable_status" in
-			2) echo-style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is missing.' ;;
-			9) echo-style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is a broken symlink.' ;;
-			13) echo-style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is not accessible.' ;;
-			22) echo-style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is not a valid argument.' ;;
-			93) echo-style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is not executable.' ;;
-			*) echo-style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because of unknown failure.' ;;
+			2) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is missing.' || return ;;
+			9) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is a broken symlink.' || return ;;
+			13) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is not accessible.' || return ;;
+			22) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is not a valid argument.' || return ;;
+			93) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is not executable.' || return ;;
+			*) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because of unknown failure.' || return ;;
 			esac
 			return "$executable_status"
 		fi
@@ -184,7 +184,7 @@ function command_working() (
 			__check_status "$cmd" --help ||
 			__check_status "$cmd" -h ||
 			{
-				echo-style --stderr \
+				__print_style --stderr \
 					--element+red="$cmd_string" --newline \
 					--="$(__print_lines "${failures[@]}")" --newline \
 					--/element+red="$cmd_string" --status=1 ' ' --error='not working because it is failing' || return
diff --git a/commands/down b/commands/down
--- a/commands/down
+++ b/commands/down
@@ -37,7 +37,7 @@ function down_test() (
 	tempdir="$(fs-temp --directory='down' --directory='tests' --touch)"
 	cd "$tempdir" || return
 
-	if ! is-ci; then
+	if [[ -z $CI ]]; then
 		eval-tester --ignore-stderr --ignore-tty -- down "$large"
 	fi
 	eval-tester --ignore-stderr --ignore-tty -- down "$zip"
@@ -114,7 +114,7 @@ function down_() (
 			Exact failure exit status is dependent on the tool used.
 		EOF
 		if [[ $# -ne 0 ]]; then
-			echo-error "$@"
+			__print_error "$@"
 		fi
 		return 22 # EINVAL 22 Invalid argument
 	}
@@ -225,15 +225,15 @@ function down_() (
 	# quiet / progress
 	local pending='Downloading' success='Downloaded' failure='Failed to download'
 	failure="$(
-		echo-style --error="$failure" ' ' --link="$option_url" ' ' --bold='to' ' ' --path="$download_directory/$download_file"
+		__print_style --error="$failure" ' ' --link="$option_url" ' ' --bold='to' ' ' --path="$download_directory/$download_file"
 	)"
 	local eval_options=(--failure="$failure")
 	if [[ $option_quiet != 'yes' ]]; then
 		pending="$(
-			echo-style --bold="$pending" ' ' --link="$option_url" ' ' --bold='to' ' ' --path="$download_directory/$download_file"
+			__print_style --bold="$pending" ' ' --link="$option_url" ' ' --bold='to' ' ' --path="$download_directory/$download_file"
 		)"
 		success="$(
-			echo-style --success="$success" ' ' --link="$option_url" ' ' --bold='to' ' ' --path="$download_directory/$download_file"
+			__print_style --success="$success" ' ' --link="$option_url" ' ' --bold='to' ' ' --path="$download_directory/$download_file"
 		)"
 		eval_options+=(--quiet --pending="$pending" --success="$success")
 	fi
@@ -277,11 +277,11 @@ function down_() (
 	if [[ $option_tool == 'wget' ]]; then
 		# install wget if it is is missing
 		if __command_missing -- wget; then
-			setup-util-wget --quiet
+			setup-util-wget --quiet || return
 		fi
 		if [[ -z $wget_binary ]]; then
 			__prepare_wget || {
-				echo-error 'down is only compatible with wget version 1, as wget2 does not return failure exit status'
+				__print_error 'down is only compatible with wget version 1, as wget2 does not return failure exit status'
 				return 75 # EPROGMISMATCH 75 Program version wrong
 			}
 		fi
@@ -381,7 +381,7 @@ function down_() (
 
 	# sanity check
 	if [[ -n $download_file ]] && is-missing -- "$download_directory/$download_file"; then
-		echo-error --="$failure"
+		__print_error --="$failure"
 		return 5 # EIO 5 Input/output error
 	fi
 
@@ -396,7 +396,7 @@ function down_() (
 
 		# sanity check
 		if [[ -n $option_file ]] && is-missing -- "$option_filepath"; then
-			echo-error 'Failed to extract ' --code="$option_url" ' to ' --code="$option_filepath"
+			__print_error 'Failed to extract ' --code="$option_url" ' to ' --code="$option_filepath"
 			return 5 # EIO 5 Input/output error
 		fi
 	fi
diff --git a/commands/eval-tester b/commands/eval-tester
--- a/commands/eval-tester
+++ b/commands/eval-tester
@@ -37,7 +37,7 @@ function eval_tester() (
 			    Preserve trailing newlines on STDOUT, STDERR, and TTY comparisons.
 		EOF
 		if [[ $# -ne 0 ]]; then
-			echo-error "$@"
+			__print_error "$@"
 		fi
 		return 22 # EINVAL 22 Invalid argument
 	}
@@ -84,7 +84,12 @@ function eval_tester() (
 
 	# quiet already defaults to yes, but if they did --quiet= or so, then change it to CI status
 	if [[ -z $option_quiet ]]; then
-		option_quiet="$(is-ci --verbose)"
+		# is-ci --verbose
+		if [[ -n $CI ]]; then
+			option_quiet='yes'
+		else
+			option_quiet='no'
+		fi
 	fi
 
 	# if debugging, or custom bash, wrap in debug_bash, keep it clean
@@ -114,7 +119,7 @@ function eval_tester() (
 			__split --target={versions} --no-zero-length --invoke -- \
 				__get_bash_binary_version "$option_bash"
 			if [[ ${#versions[@]} -lt 2 ]]; then
-				echo-style --error="Unable to determine bash version from $option_bash"
+				__print_style --error="Unable to determine bash version from $option_bash"
 				return 1
 			fi
 			bash_version_major="${versions[0]}"
@@ -135,9 +140,9 @@ function eval_tester() (
 	function __element {
 		local label="$1" style="$2" value="$3"
 		if [[ -n $value ]]; then
-			echo-style --"$style"+element="$label" --newline --="$value" --newline --"$style"+/element="$label" || return 223 # ECUSTOM 223 Tests broken
+			__print_style --"$style"+element="$label" --newline --="$value" --newline --"$style"+/element="$label" || return 223 # ECUSTOM 223 Tests broken
 		else
-			echo-style --"$style"+element/="$label" --commentary-empty || return 223 # ECUSTOM 223 Tests broken
+			__print_style --"$style"+element/="$label" --commentary-empty || return 223 # ECUSTOM 223 Tests broken
 		fi
 	}
 	function __escaped_element {
@@ -145,7 +150,7 @@ function eval_tester() (
 		if [[ -n $value ]]; then
 			__element "$label escaped" "$style" "$(printf '%q' "$value")" || return
 		else
-			echo-style --"$style"+element/="$label escaped" --commentary-empty || return 223 # ECUSTOM 223 Tests broken
+			__print_style --"$style"+element/="$label escaped" --commentary-empty || return 223 # ECUSTOM 223 Tests broken
 		fi
 	}
 	function __compare {
@@ -154,17 +159,17 @@ function eval_tester() (
 			__print_line || return 223 # ECUSTOM 223 Tests broken
 		fi
 		if [[ $name == 'STDERR' && -n $stderr_unable_reason ]]; then
-			echo-style --stderr --notice="$stderr_unable_reason" || return 223 # ECUSTOM 223 Tests broken
+			__print_style --stderr --notice="$stderr_unable_reason" || return 223 # ECUSTOM 223 Tests broken
 		elif [[ $name == 'STATUS' ]]; then
 			if [[ $expected == "$ignore_value" ]]; then
-				echo-style --note="${name} is IGNORED [$actual]" || return 223 # ECUSTOM 223 Tests broken
+				__print_style --note="${name} is IGNORED [$actual]" || return 223 # ECUSTOM 223 Tests broken
 			elif [[ $actual == "$expected" ]]; then
-				echo-style --success="${name} is EXPECTED [$expected]" || return 223 # ECUSTOM 223 Tests broken
+				__print_style --success="${name} is EXPECTED [$expected]" || return 223 # ECUSTOM 223 Tests broken
 			else
-				echo-style --error="${name} [$actual] is NOT EXPECTED [$expected]" || return 223 # ECUSTOM 223 Tests broken
+				__print_style --error="${name} [$actual] is NOT EXPECTED [$expected]" || return 223 # ECUSTOM 223 Tests broken
 			fi
 		elif [[ $expected == "$ignore_value" ]]; then
-			echo-style --note="${name} is IGNORED" || return 223 # ECUSTOM 223 Tests broken
+			__print_style --note="${name} is IGNORED" || return 223 # ECUSTOM 223 Tests broken
 			if [[ $option_quiet == 'no' ]]; then
 				if ! __is_shapeshifter -- "$actual"; then
 					__element "$name" blue "$actual" || return
@@ -175,7 +180,7 @@ function eval_tester() (
 			fi
 		else
 			if [[ $actual == "$expected" ]]; then
-				echo-style --success="${name} is EXPECTED" || return 223 # ECUSTOM 223 Tests broken
+				__print_style --success="${name} is EXPECTED" || return 223 # ECUSTOM 223 Tests broken
 				if [[ $option_quiet == 'no' ]]; then
 					if ! __is_shapeshifter -- "$actual"; then
 						__element "$name" green "$actual" || return
@@ -185,7 +190,7 @@ function eval_tester() (
 					fi
 				fi
 			else
-				echo-style --error="${name} is NOT EXPECTED" || return 223 # ECUSTOM 223 Tests broken
+				__print_style --error="${name} is NOT EXPECTED" || return 223 # ECUSTOM 223 Tests broken
 				if ! __is_shapeshifter -- "$actual$expected"; then
 					__element "actual $name" red "$actual" || return
 					__element "expected $name" red "$expected" || return
@@ -258,7 +263,7 @@ function eval_tester() (
 		args+=(--copy-stderr={actual_stderr})
 	fi
 	command_string="$(echo-escape-command -- "${option_cmd[@]}")"
-	echo-style --h2="$title" --newline --element+bold="$command_string"
+	__print_style --h2="$title" --newline --element+bold="$command_string"
 	time_before="$(__get_epoch_time)"
 	# __eval_helper --quiet="$option_quiet" --wrap <-- if this is done, element rendering, quite mode, and time duration can all be moved to eval-helper
 	__do "${args[@]}" -- "${option_cmd[@]}"
@@ -269,7 +274,7 @@ function eval_tester() (
 	fi
 	__close_fd {TERMINAL_OUTPUT_TARGET}
 	TERMINAL_OUTPUT_TARGET="$TERMINAL_OUTPUT_TARGET__original"
-	echo-style --/element+bold="$command_string"
+	__print_style --/element+bold="$command_string"
 	__wait_for_and_return_semaphores "${semaphores_status[@]}"
 	__wait_for_semaphores "$semaphore_tty_content"
 	if [[ $option_trailing_newlines == 'no' ]]; then
@@ -301,10 +306,10 @@ function eval_tester() (
 
 	# pass or fail
 	if [[ $FAIL == 'yes' ]]; then
-		echo-style --e2="$title" ' ' --code="in $time_delta seconds" $'\n'
+		__print_style --e2="$title" ' ' --code="in $time_delta seconds" $'\n'
 		return 221 # ECUSTOM 221 Tests failed
 	else
-		echo-style --g2="$title" ' ' --code="in $time_delta seconds" $'\n'
+		__print_style --g2="$title" ' ' --code="in $time_delta seconds" $'\n'
 	fi
 )
 
diff --git a/commands/setup-shell b/commands/setup-shell
--- a/commands/setup-shell
+++ b/commands/setup-shell
@@ -9,6 +9,7 @@
 function setup_shell() (
 	source "$DOROTHY/sources/bash.bash"
 	source "$DOROTHY/sources/environment.sh" # ensure new installations are detected
+	source "$DOROTHY/sources/styles.bash"
 
 	# used by these helpers
 	local option_brew='' option_exclusions=()
@@ -60,9 +61,9 @@ function setup_shell() (
 		name="$(get_name_of_basename_of_shell "$shell")"
 		url="$(get_url_of_basename_of_shell "$shell")"
 		if [[ -n $url ]]; then
-			echo-style --bold="$name: " --dim="$url"
+			__print_style --bold="$name: " --dim="$url"
 		else
-			echo-style --bold="$name"
+			__print_style --bold="$name"
 		fi
 	}
 
@@ -100,7 +101,7 @@ function setup_shell() (
 		else
 			args=(--bold="$name" ' ' --dim="$path")
 		fi
-		echo-style "${args[@]}"
+		__print_style "${args[@]}"
 	}
 
 	function __is_permitted_shell {
@@ -270,17 +271,17 @@ function setup_shell() (
 				chpass -s "$login_shell_path" -u "$USER" || __chpass_status=$?
 				if [[ $__chpass_status -eq 0 ]]; then
 					# successfully updated
-					echo-style --tty --dim='You can ignore [chpass: no changes made] warnings.' || return
+					__print_style --tty --dim='You can ignore [chpass: no changes made] warnings.' || return
 					break
 				elif [[ $__chpass_status -eq 1 ]]; then
 					# incorrect password
 					continue # try again
 				elif [[ $__chpass_status -eq 130 ]]; then
 					# 130 = SIGINT = ctrl+c = abort
-					echo-style --stderr --error="Updating the login shell failed because [chpass] was aborted with exit status [$__chpass_status]." || return
+					__print_style --stderr --error="Updating the login shell failed because [chpass] was aborted with exit status [$__chpass_status]." || return
 					return 125 # ECANCELED 125 Operation cancelled
 				else
-					echo-style --stderr --error="Updating the login shell failed because [chpass] failed with exit status [$__chpass_status]." || return
+					__print_style --stderr --error="Updating the login shell failed because [chpass] failed with exit status [$__chpass_status]." || return
 					return "$__chpass_status"
 				fi
 			done
@@ -543,7 +544,7 @@ function setup_shell() (
 			You can use a full path, such as [/bin/bash] to select a specific variation of the shell.
 		EOF
 		if [[ $# -ne 0 ]]; then
-			echo-error "$@"
+			__print_error "$@"
 		fi
 		return 22 # EINVAL 22 Invalid argument
 	}
@@ -659,7 +660,7 @@ function setup_shell() (
 		__do --redirect-status={status} --redirect-stdout={result} -- \
 			choose --linger --multi "$question" "$details" --defaults="$defaults_string" --label -- "${choices[@]}"
 		if [[ $status -eq 130 ]]; then
-			echo-style --tty --notice='No changes to installed shells were desired.'
+			__print_style --tty --notice='No changes to installed shells were desired.'
 			return 0
 		elif [[ $status -ne 0 ]]; then
 			return "$status"
@@ -752,7 +753,7 @@ function setup_shell() (
 		__do --redirect-status={status} --redirect-stdout={result} -- \
 			choose --linger --multi "$question" "$details" --defaults="$defaults_string" --label -- "${choices[@]}"
 		if [[ $status -eq 130 ]]; then
-			echo-style --tty --notice='No changes to configured shells were desired.'
+			__print_style --tty --notice='No changes to configured shells were desired.'
 			return 0
 		elif [[ $status -ne 0 ]]; then
 			return "$status"
@@ -876,7 +877,7 @@ function setup_shell() (
 		__do --redirect-status={status} --redirect-stdout={result} -- \
 			choose --linger --required --multi "$question" "$details" --defaults="$defaults_string" --label -- "${choices_with_labels[@]}"
 		if [[ $status -eq 130 ]]; then
-			echo-style --tty --notice='No changes to system login shells were desired.'
+			__print_style --tty --notice='No changes to system login shells were desired.'
 			return 0
 		elif [[ $status -ne 0 ]]; then
 			return "$status"
@@ -889,7 +890,7 @@ function setup_shell() (
 		if [[ ${#selected_shells[@]} -eq 0 ]]; then
 			# disallow everything
 			if [[ $option_disallow != 'no' ]]; then
-				echo-style --tty --notice='Skipping disallowing all shells form being used as a login shell, as that is a mistake.'
+				__print_style --tty --notice='Skipping disallowing all shells form being used as a login shell, as that is a mistake.'
 				return 0
 			fi
 		else
@@ -914,7 +915,7 @@ function setup_shell() (
 
 		# check
 		if [[ $can_apply_login_shell == 'no' ]]; then
-			echo-style --tty --notice="Dorothy doesn't know how to set the login shell on this Operating System."
+			__print_style --tty --notice="Dorothy doesn't know how to set the login shell on this Operating System."
 			return 0
 			# return 19 # ENODEV 19 Operation not configurable by device
 		fi
@@ -946,7 +947,7 @@ function setup_shell() (
 			choose --linger --no-multi "$question" "$details" --defaults="$defaults_string" --label -- "${choices[@]}" || :
 		)"
 		if [[ -z $login_shell_path ]]; then
-			echo-style --tty --notice='No changes to the default login shell were desired.'
+			__print_style --tty --notice='No changes to the default login shell were desired.'
 			return 0
 		fi
 
