command-working: support ffmpeg

diff --git a/commands/command-working b/commands/command-working
--- a/commands/command-working
+++ b/commands/command-working
@@ -144,21 +144,32 @@ function command_working() (
 			return "$cmd_exit_status"
 		fi
 	}
+	function __check_cmd {
+		local cmd_path="$1"
+		if [[ $cmd_path == */ffmpeg ]]; then
+			__check_status "$cmd_path" -version || return $?
+		else
+			__check_status "$cmd_path" --version ||
+				__check_status "$cmd_path" version ||
+				__check_status "$cmd_path" --help ||
+				__check_status "$cmd_path" -h || return $?
+		fi
+	}
 	function __check_working {
 		# reset debug
 		failures=()
 
 		# check it exists first
-		local cmd cmd_string executable_status
+		local cmd_path cmd_string executable_status
 		cmd_string="$(echo-escape-command -- "$1")" || return $?
-		cmd="$(type -P "$1" 2>/dev/null || :)"
-		if [[ -z $cmd ]]; then
+		cmd_path="$(type -P "$1" 2>/dev/null || :)"
+		if [[ -z $cmd_path ]]; then
 			# we must at least find it
 			__print_style --stderr --element/+red="$cmd_string" --status=3 ' ' --error='not working because it is missing' || return $?
 			return 3 # ESRCH 3 No such process
 		fi
 
-		__try {executable_status} -- is-executable --quiet -- "$cmd"
+		__try {executable_status} -- is-executable --quiet -- "$cmd_path"
 		if [[ $executable_status -ne 0 ]]; then
 			case "$executable_status" in
 			2) __print_style --stderr --element/+red="$cmd_string" --status="$executable_status" ' ' --error='not working because it is missing.' || return $? ;;
@@ -174,23 +185,19 @@ function command_working() (
 		# check if presence is enough for this cmd
 		local exception
 		for exception in "${exceptions[@]}"; do
-			if [[ $cmd == */"$exception" ]]; then
+			if [[ $cmd_path == */"$exception" ]]; then
 				return 0
 			fi
 		done
 
 		# it does exist, now check its return code
-		__check_status "$cmd" --version ||
-			__check_status "$cmd" version ||
-			__check_status "$cmd" --help ||
-			__check_status "$cmd" -h ||
-			{
-				__print_style --stderr \
-					--element+red="$cmd_string" --newline \
-					--="$(__print_lines "${failures[@]}")" --newline \
-					--/element+red="$cmd_string" --status=1 ' ' --error='not working because it is failing' || return $?
-				return 1 # command not working
-			}
+		__check_cmd "$cmd_path" || {
+			__print_style --stderr \
+				--element+red="$cmd_string" --newline \
+				--="$(__print_lines "${failures[@]}")" --newline \
+				--/element+red="$cmd_string" --status=1 ' ' --error='not working because it is failing' || return $?
+			return 1 # command not working
+		}
 	}
 
 	# =====================================
