rewrote `confirm*`, `setup-node`, `eval-collapse`
user facing changes:

- `confirm*` scripts have been reworked to:
    - support question details
    - output question with blink options, and upon finale, with its selection
    - support ctrl+c terminations, passing along exit code and indicating with ABORT
    - support spacebar for defaults, for items that support it
    - much more effecient too, no longer have to redo everything each invalid keypress
- `setup-node` now cleans nvm versions, and if that fails, then cleans nvm, this can be prevented via NVM_CLEAN=no
- `setup-node` also uses the new `eval-collapse` and `confirm` features for a cleaner experience
- `setup-vim` now outputs successful replacements

major internal changes:

- added `echo-count-lines` to count lines
- `echo-clear-lines` has been rejigged to support more edge cases, such as non-terminating lines, piped output, and erasing already outputted content
- `eval-collapse` has been redone to be more reliable and easier to understand
- `stdinargs` can now use `line` and `inline` and `arg` functions, this is used by `echo-count-lines`

other changes:

- `git-remote-apply` no longer does tty and stderr stuff, as it was interfering with `eval-collapse`
- `setup-mac` cleaner success output

diff --git a/commands/confirm b/commands/confirm
--- a/commands/confirm
+++ b/commands/confirm
@@ -1,31 +1,166 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# anything besides enter/space/y is ask again
-function confirmer() {
-	local ec
+# =====================================
+# Options
 
-	# timeout one hour
-	echo -en "$@"
-	answer="$(read-arrow --timeout 3600)" || return "$?"
-
-	# check their answer
-	ec=0 && is-affirmative "$answer" || ec="$?"
-	if test "$ec" -lt 2; then
-		return "$ec"
-	elif test "$answer" = 'enter' -o "$answer" = 'space'; then
-		return 0
-	elif test "$answer" = 'escape'; then
-		return 1
-	else
-		# ask again
-		echo # newline, otherwise everything on same line
-		confirmer "$@"
-		return "$?" # return with the above on success and failure
+timeout='3600' # one hour
+option_mode='confirm'
+option_yes='OK'
+option_no='CANCEL'
+while is-needle '--' "$@"; do
+	if [[ "$1" = '--mode='* ]]; then
+		option_mode="${1:7}" # bool/positive/negative/confirm
+		if test "$option_mode" = 'positive' -o "$option_mode" = 'negative'; then
+			timeout='60' # one minute
+			option_yes='YES'
+			option_no='NO'
+		elif test "$option_mode" = 'bool'; then
+			option_yes='YES'
+			option_no='NO'
+		fi
 	fi
+	shift
+done
+
+# =====================================
+# Helpers
+
+# used to process the input
+function confirmer() {
+	local ec answer
+
+	# ask and timeout
+	ec=0 && answer="$(read-arrow --timeout "$timeout")" || ec="$?"
+
+	# process
+	if test "$option_mode" = 'positive'; then
+		# positive
+		if test "$ec" -eq 62; then
+			return 0 # timeout
+		elif test "$ec" -ne 0; then
+			return "$ec" # failure
+		fi
+		ec=0 && is-affirmative "$answer" || ec="$?"
+		if test "$ec" -lt 2; then
+			return "$ec"
+		elif test "$answer" = 'enter' -o "$answer" = 'space'; then
+			return 0
+		elif test "$answer" = 'escape' -o "$answer" = 'q'; then
+			return 125 # Operation canceled
+		fi
+
+	elif test "$option_mode" = 'negative'; then
+		# negative
+		if test "$ec" -eq 62; then
+			return 1 # timeout
+		elif test "$ec" -ne 0; then
+			return "$ec" # failure
+		fi
+		ec=0 && is-affirmative "$answer" || ec="$?"
+		if test "$ec" -lt 2; then
+			return "$ec"
+		elif test "$answer" = 'enter' -o "$answer" = 'space'; then
+			return 1
+		elif test "$answer" = 'escape' -o "$answer" = 'q'; then
+			return 125 # Operation canceled
+		fi
+
+	elif test "$option_mode" = 'bool'; then
+		# bool
+		if test "$ec" -ne 0; then
+			return "$ec" # timeout and failure
+		fi
+		ec=0 && is-affirmative "$answer" || ec="$?"
+		if test "$ec" -lt 2; then
+			return "$ec"
+		elif test "$answer" = 'escape' -o "$answer" = 'q'; then
+			return 125 # Operation canceled
+		fi
+
+	else
+		# confirm
+		if test "$ec" -ne 0; then
+			return "$ec" # timeout and failure
+		fi
+		if test "$answer" = 'escape'; then
+			return 125 # Operation canceled
+		else
+			# @todo what happens here if scrolling on ssh
+			return 0
+		fi
+	fi
+
+	# try again, and erase any leaked characters
+	echo -en "\e[${hx}G\e[K"
+	confirmer "$@"
+	return "$?" # return with the above on success and failure
 }
 
-# confirm with the user
-ec=0 && confirmer "$@" || ec="$?"
-echo       # newline, as y/n do not
+# =====================================
+# Question
+
+# prepare
+question_first_part="${1-} " # this is stored for the finale
+question_parts=("$@")
+question_parts_total="$(($# - 1))"
+header="$(mktemp)"
+lines=0
+ec=0
+
+# update the first question part
+if test "$option_mode" = 'positive'; then
+	question_parts[0]+=" $(echo-color --blink='(' --blink+green+bold='Y' --blink='/n)')"
+elif test "$option_mode" = 'negative'; then
+	question_parts[0]+=" $(echo-color --blink='(y/' --blink+red+bold='N' --blink=')')"
+elif test "$option_mode" = 'bool'; then
+	question_parts[0]+=" $(echo-color --blink='(y/n)')"
+fi
+for ((i = 0; i <= "$question_parts_total"; i++)); do
+	echo -n "${question_parts[i]} " | tee -a "$header"
+	if test "$i" -eq 0; then
+		# read cursor x y, discard y, set hx to y
+		IFS='[;' read -srd R -p $'\e[6n' _ _ hx
+	fi
+	if test "$i" -ne "$question_parts_total"; then
+		echo | tee -a "$header"
+	fi
+done
+
+# output question, and handle terminations
+if test "$question_parts_total" -ne 0; then
+	# reposition the cursor, to after the options in the first part
+	lines="$(echo-count-lines --no-inline <"$header")"
+	# move these lines up, and to the hx column
+	echo -en "\e[${lines}F\e[${hx}G"
+fi
+function failure() {
+	ec="$?"
+}
+function finish() {
+	# in case we were called naturally, erase the listen
+	trap - EXIT
+	# make sure to erase question, as ctrl+c buggers everything
+	echo -n $'\e[G\e[J'
+	# output the finale
+	if test "$ec" -eq 0; then
+		echo-color "$question_first_part" --green+bold="$option_yes"
+	elif test "$ec" -eq 1; then
+		echo-color "$question_first_part" --red+bold="$option_no"
+	else
+		echo-color "$question_first_part" --red+bold="ABORT"
+	fi
+}
+trap failure SIGINT SIGTERM
+trap finish EXIT
+
+# read and handle answer
+confirmer || ec="$?"
+finish
 exit "$ec" # exit with the result
+
+# @todo
+# an alternative implementation could be a new line like this at the end, with ENTER and ESCAPE and SPACE as the correct outputs
+# echo-color --blink='Press: ' --blink+green+bold='y ' --blink='for ' --blink+green='YES' --blink=', ' --blink+red+bold='n ' --blink='for ' --blink+red='NO' --blink=', ' --blink+bold='ENTER '  --blink='for ' --blink+red='NO'
+
+# using \e[s (save) and \e[u (restore) for ctrl+c handling did not work
diff --git a/commands/setup-node b/commands/setup-node
--- a/commands/setup-node
+++ b/commands/setup-node
@@ -1,29 +1,89 @@
 #!/usr/bin/env bash
-# shellcheck disable=SC2164,SC1091
+# shellcheck disable=SC2164,SC1091,SC2016
 source "$DOROTHY/sources/strict.bash"
 source "$(which eval-collapse)"
-
-# setup-environment-commands provides: NVM_DIR
-if test -z "${NVM_DIR-}"; then
-	export NVM_DIR="$HOME/.nvm"
-fi
 
 # =====================================
 # Configuration
 
 source "$DOROTHY/sources/config.sh"
 load_dorothy_config 'setup.bash'
-# ^ provides: NPM_INSTALL/NODE_INSTALL
+# setup.bash provides:
+# CLEAN_NVM, NPM_INSTALL/NODE_INSTALL
+
+# environment.bash provides:
+# NVM_DIR
+# but in case it failed to:
+if test -z "${NVM_DIR-}"; then
+	export NVM_DIR="$HOME/.nvm"
+fi
 
 # =====================================
 # Prepare
 
 echo-segment --h1="Setup Node.js"
-echo-color --dim "NVM_DIR=$NVM_DIR"
+# cat <<-EOF
 
-# Wiping nvm, positive as we want to clear npm packages on outdated node versions
-if test -d "$NVM_DIR" && confirm-positive "Clean NVM installation? [$NVM_DIR]"; then
+# 	The following will be installed and upgraded:
+# 	- Node.js Version Manager (NVM)
+# 	- Node.js
+# 	- npm
+# 	- global packages
+
+# EOF
+
+# clean NVM unless configured otherwise
+# the intent of this is to purge unused global Node.js versions and packages
+# we use a configuration variable to change this, as interuppting the flow and asking the user creates too much confusion
+# as such a question is only necessary to experienced users
+function get_nvm_versions() {
+	source "$DOROTHY/sources/ripgrep.bash"
+	source "$DOROTHY/sources/nvm.sh"
+	nvm ls --no-colors --no-alias | rg -o 'v([^\s]+)' --replace '$1' || :
+}
+function clean_nvm() {
+	# run a subshell, so nvm is only loaded for this
+	# can't just do `trap 'nvm unload' RETURN` as `nvm unload` unsets NVM_DIR
+	(
+		source "$DOROTHY/sources/nvm.sh"
+		# fetch versions
+		mapfile -t versions < <(get_nvm_versions)
+		if test "${#versions[@]}" -eq 0; then
+			# already clean
+			return 0
+		fi
+		# clean versions
+		for version in "${versions[@]}"; do
+			nvm uninstall "$version" | sed 's/Uninstalled node /Uninstalled: /'
+		done
+		# confirm clean was successful
+		mapfile -t versions < <(get_nvm_versions)
+		test "${#versions[@]}" -eq 0
+	)
+}
+function wipe_nvm() {
 	rm -Rf "$NVM_DIR"
+}
+function clean_otherwise_wipe_nvm() {
+	# clean only what is necessary
+	echo-segment --h3='Clean Node.js versions and packages'
+	echo-color --dim='The desired versions and packages will be cleaned installed later.'
+	# echo-color --dim='Use `CLEAN_NVM=no` in your `setup.bash` configuration file to disable this recommendation.'
+	# ^ once this functionality is stabised for few months, make it official and annouce with the above
+	# ^ as perhaps calling it CLEAN_NODE or NODE_CLEAN makes more sense
+	# ^ NODE_CLEAN makes most sense, but implies we also clean packages from system node, which we don't yet
+	if clean_nvm; then
+		echo-segment --g3='Clean Node.js versions and packages'
+	else
+		# nvm buggered, clean it all
+		echo-segment --e3='Clean Node.js versions and packages'
+		echo-segment --h3='Clean Node.js Version Manager (NVM) instead'
+		wipe_nvm
+		echo-segment --g3='Clean Node.js Version Manager (NVM) instead'
+	fi
+}
+if test -d "$NVM_DIR" -a "${CLEAN_NVM-}" != 'no'; then
+	clean_otherwise_wipe_nvm
 fi
 
 # =====================================
@@ -31,14 +91,17 @@ fi
 
 # setup system node for global installs and vscode on mac
 function install_homebrew_node() {
-	brew install node || brew upgrade node || :
+	# `reinstall ... || :` as well as `install ... || upgrade ... || :` are no longer necessary,
+	# install does upgrade if it is already installed:
+	# https://github.com/Homebrew/brew/pull/11525
+	brew install node
 	npm cache clean --force
-	brew cleanup
 }
 if is-brew; then
-	echo-segment --h2='Install System Node.js'
-	eval_collapse -- install_homebrew_node
-	echo-segment --g2='Install System Node.js'
+	echo-segment --h2='Install Node.js via Homebrew'
+	eval_collapse --no-wrap -- install_homebrew_node
+	echo "Installed: $(node --version)"
+	echo-segment --g2='Install Node.js via Homebrew'
 fi
 
 # install nvm
@@ -60,9 +123,10 @@ function install_nvm() {
 	# shellcheck disable=SC2006,SC2046
 	git checkout "$(git describe --abbrev=0 --tags --match "v[0-9]*" "$(git rev-list --tags --max-count=1)")"
 }
-echo-segment --h2='Install Node Version Manager'
-eval_collapse -- install_nvm
-echo-segment --g2='Install Node Version Manager'
+echo-segment --h2='Install Node.js Version Manager (NVM)'
+echo-color --dim "NVM_DIR=$NVM_DIR"
+eval_collapse --no-wrap -- install_nvm
+echo-segment --g2='Install Node.js Version Manager (NVM)'
 
 # install nvm node
 function install_nvm_node() {
@@ -85,22 +149,50 @@ function install_nvm_node() {
 	nvm use default
 }
 echo-segment --h2='Install Node.js via NVM'
-eval_collapse -- install_nvm_node
+echo-color --dim='Installs active and LTS versions.'
+eval_collapse --no-wrap -- install_nvm_node
+mapfile -t versions < <(get_nvm_versions)
+for version in "${versions[@]}"; do
+	echo "Installed: v$version"
+done
 echo-segment --g2='Install Node.js via NVM'
 
 # npm
 echo-segment --h2='Upgrade npm'
-echo-color --dim="   npm version: $(npm --version)"
+echo-color --dim="Before: $(npm --version)"
 eval_collapse -- npm install -g npm --force
-echo-color --dim+green="   npm version: $(npm --version)"
+echo "After:  $(npm --version)"
 echo-segment --g2='Upgrade npm'
 
 # configure
 echo-segment --h2='Configure npm'
-npm config set init.author.name "$(ask --question="What is your name that you want to configure npm with?" --default="$(npm config get init.author.name)" --required --confirm)"
-npm config set init.author.email "$(ask --question="What is your email that you want to configure npm with?" --default="$(npm config get init.author.email)" --required --confirm)"
-npm config set init.author.url "$(ask --question="What is your homepage that you want to configure npm with?" --default="$(npm config get init.author.url)" --required --confirm)"
-npm config set init.license "$(ask --question="What license do you want to configure npm to default to?" --default="$(npm config get init.license)" --required --confirm)"
+settings_all_set='yes'
+settings=(
+	'Your Name'
+	init.author.name
+	'Your Email'
+	init.author.email
+	'Your Homepage'
+	init.author.url
+	'Your License'
+	init.license
+)
+settings_confirm_details=()
+for ((i = 0; i < ${#settings[@]}; i += 2)); do
+	label="${settings[i]}"
+	key="${settings[i + 1]}"
+	value="$(npm config get "$key")" # returns undefined if unset
+	settings_confirm_details+=("$label: $value")
+	if is-empty-string "$value"; then
+		settings_all_set='no'
+	fi
+done
+if test "$settings_all_set" = 'no' || confirm-negative "Do you wish to change your npm configuration?" "${settings_confirm_details[@]}"; then
+	npm config set init.author.name "$(ask --question="What is your name that you want to configure npm with?" --default="$(npm config get init.author.name)" --required --confirm)"
+	npm config set init.author.email "$(ask --question="What is your email that you want to configure npm with?" --default="$(npm config get init.author.email)" --required --confirm)"
+	npm config set init.author.url "$(ask --question="What is your homepage that you want to configure npm with?" --default="$(npm config get init.author.url)" --required --confirm)"
+	npm config set init.license "$(ask --question="What license do you want to configure npm to default to?" --default="$(npm config get init.license)" --required --confirm)"
+fi
 echo-segment --g2='Configure npm'
 
 # https://github.com/yarnpkg/yarn/issues/2993
@@ -119,4 +211,4 @@ fi
 # =====================================
 # Done
 
-echo-segment --h1='Setup Node.js'
+echo-segment --g1='Setup Node.js'
