major convention upgrades
- place sources inside the subshell function, as subshells do not inherit shell options
    - without this change, aborting confirms could cause unexpected behaviour, especially in `setup-dns` on removals
    - as sources are now done inside the subshells, trimmed some now useless shellcheck ignores
    - source strict in commands it wasn't sourced in
- `confirm-*` is now `confirm --*`
    - this should make the parent exiting more robust as there is less processes created
- `confirm` traps and exit enforcement improved to guarantee exit
    - without this, the nesting of multiple sub-shells in `setup-dns` was causing unexpected behviour with aborts
- `sources/strict.bash` sets more sensible defaults, with `globstar` and `extglob` being for enforcement
- usage of `fs-*` commands updated to prefer `-- ...` usage, to avoid errors when paths start with `-`
- usage of `echo-errors` udpated to always start with `$0`
- `fs-{bytes,dirname,extension,filename,kilobytes,megabytes,realpath,temp` support multi args
- `fs-{size,speed,structure}` now fail correctly if not receiving any args
- re-add failure returns after `echo-error` calls, had wrongly assumed `echo-error` returned failures
- `fs-rm` now supports `--sudo`
- enforce consistent conventions around multi-line command calls, put the `--` on the newline once a new command follows or a new `--`
- icloud-helper: avoid need for shellcheck ignore by using "$0" instead
- rename a few flag vars to remove the `option_` prefix, it is outdated under most cases
    - only needed for huge commands where overlaps can happen (it was done prior to the discovery of subshells and local)
- correct `echo-style --error` to `echo-error` or `echo-style --notice`
- service-helper: added macos and alpine support, also added `--optional` support to ignore failures and added `--quiet` support
- setup-dns: more consistent `eval-helper` usage, for a cleaner output
- setup-linux-raspi: use service-helper instead, and actually enable autostart rather than just enable it (`unmask` and `enable` are different)
- `setup-util-{plex,resilio,samba}`: continued compatibility improvements

diff --git a/commands/confirm b/commands/confirm
--- a/commands/confirm
+++ b/commands/confirm
@@ -1,5 +1,4 @@
 #!/usr/bin/env bash
-source "$DOROTHY/sources/strict.bash"
 
 # NOTES:
 # [echo -en] doesn't work with escape codes on bash v3, [printf ...] does
@@ -7,6 +6,8 @@ source "$DOROTHY/sources/strict.bash"
 #    why would anyone use confirm in that way? they don't but confirm within a getter does, such as [select_installer] within [macos-drive]
 
 function confirm() (
+	source "$DOROTHY/sources/strict.bash"
+
 	# =====================================
 	# Arguments
 
@@ -16,11 +17,11 @@ function confirm() (
 			confirm --ppid=\$\$ [...options] -- <question> ...[detail]
 
 			OPTIONS:
-			--mode=<bool|positive|negative|confirm>
+			--bool | --positive | --negative | --confirm || --mode=<bool|positive|negative|confirm>
 			    [bool] mode forces a positive or negative confirmation, with no default.
 			    [positive] mode defaults to a positive confirmation.
 			    [negative] mode defaults to a negative confirmation.
-			    [confirm] mode forces a confirmation, with no default.
+			    [confirm] mode forces a confirmation, with no default; it is the default mode.
 
 			--timeout=<timeout>
 			    Specify the timeout in seconds.
@@ -59,17 +60,11 @@ function confirm() (
 		shift
 		case "$item" in
 		'--help' | '-h') help ;;
-		'--mode='*)
-			mode="${item:7}" # bool/positive/negative/confirm
-			if test "$mode" = 'positive' -o "$mode" = 'negative'; then
-				timeout='60' # one minute
-				yes='YES'
-				no='NO'
-			elif test "$mode" = 'bool'; then
-				yes='YES'
-				no='NO'
-			fi
-			;;
+		'--bool') mode='bool' ;;
+		'--positive') mode='positive' ;;
+		'--negative') mode='negative' ;;
+		'--confirm') mode='confirm' ;;
+		'--mode='*) mode="${item:7}" ;;
 		'--timeout='*) timeout="${item:10}" ;;
 		'--yes='*) yes="${item:6}" ;;
 		'--no='*) no="${item:5}" ;;
@@ -84,6 +79,16 @@ function confirm() (
 		*) help "An unrecognised argument was provided: $item" ;;
 		esac
 	done
+
+	# mode
+	if test "$mode" = 'positive' -o "$mode" = 'negative'; then
+		timeout='60' # one minute
+		yes='YES'
+		no='NO'
+	elif test "$mode" = 'bool'; then
+		yes='YES'
+		no='NO'
+	fi
 
 	# requirements
 	if test -z "$ppid"; then
@@ -173,13 +178,51 @@ function confirm() (
 	# =====================================
 	# Question
 
-	local question_first_part="${question_parts[0]} " # this is stored for the finale
-	local question_parts_total="${#question_parts[@]}"
-	local question_parts_last="$((question_parts_total - 1))"
-	local index header lines=0 result=0 hx=''
-	header="$(mktemp)"
+	# handle termination
+	local result=0 question_first_part="${question_parts[0]} " # this is stored for the finale
+	function failure {
+		result="$?"
+		if test -z "$result" -o "$result" -eq 0; then
+			result=100 # EPROTO 100 Protocol error
+		fi
+		finish
+	}
+	function finish {
+		trap - EXIT SIGINT SIGTERM ERR
+		# make sure to erase question, as ctrl+c buggers everything
+		printf '\e[G\e[J' >/dev/tty
+		# output the finale
+		if test "$result" -eq 0; then
+			echo-style "$question_first_part" --green+bold="$yes" >/dev/tty
+		elif test "$result" -eq 1; then
+			echo-style "$question_first_part" --red+bold="$no" >/dev/tty
+		else
+			echo-style "$question_first_part" --red+bold="$abort" >/dev/tty
+			# kill caller's parent
+			if test -n "$ppid"; then
+				# kill "-$ppid" ...
+				# ^ fails because 130 isn't supported
+				# kill -n ... ...
+				# kill "-$(kill -l "$ppid")" ...
+				# ^ works but isn't serious enough to cause the termination
+				# "$(ps -p $$ -o ppid=)"
+				# ^ doesn't work, as is different pid than manual
+				kill "$ppid"
+			fi
+			# kill our parent
+			kill "$$"
+			# kill our subshell
+			kill 0
+			# kill our shell
+			exit "$result"
+		fi
+		# kill this
+		return "$result"
+	}
+	trap failure SIGINT SIGTERM ERR
+	trap finish EXIT
 
-	# update the first question part
+	# add the confirmation to the first question part
 	if test "$mode" = 'positive'; then
 		question_parts[0]+=" $(echo-style --blink='(' --blink+green+bold='Y' --blink='/n)')"
 	elif test "$mode" = 'negative'; then
@@ -195,6 +238,10 @@ function confirm() (
 	# output the question parts
 	# saving the cursor position of the first line
 	# and outputting a newline beteen all lines, except the last, which should not have a trailing line
+	local question_parts_total="${#question_parts[@]}"
+	local question_parts_last="$((question_parts_total - 1))"
+	local index hx='' header
+	header="$(mktemp)"
 	for ((index = 0; index < "$question_parts_total"; index++)); do
 		echo -n "${question_parts[index]} " | tee -a "$header" >/dev/tty
 		if test "$index" -eq 0; then
@@ -207,6 +254,7 @@ function confirm() (
 	done
 
 	# move the cursor
+	local lines=0
 	if test "$question_parts_total" -ne 0; then
 		# reposition the cursor, to after the options in the first part
 		lines="$(echo-count-lines --no-inline <"$header")"
@@ -217,37 +265,6 @@ function confirm() (
 		# move to the hx column
 		printf '\e[%sG' "$hx" >/dev/tty
 	fi
-
-	# handle terminations
-	function failure {
-		result="$?"
-	}
-	function finish {
-		# in case we were called naturally, erase the listen
-		trap - EXIT
-		# make sure to erase question, as ctrl+c buggers everything
-		printf '\e[G\e[J' >/dev/tty
-		# output the finale
-		if test "$result" -eq 0; then
-			echo-style "$question_first_part" --green+bold="$yes" >/dev/tty
-		elif test "$result" -eq 1; then
-			echo-style "$question_first_part" --red+bold="$no" >/dev/tty
-		else
-			echo-style "$question_first_part" --red+bold="$abort" >/dev/tty
-			if test -n "$ppid"; then
-				# kill "-$ppid" ...
-				# ^ fails because 130 isn't supported
-				# kill -n ... ...
-				# kill "-$(kill -l "$ppid")" ...
-				# ^ works but isn't serious enough to cause the termination
-				# "$(ps -p $$ -o ppid=)"
-				# ^ doesn't work, as is different pid than manual
-				kill "$ppid"
-			fi
-		fi
-	}
-	trap failure SIGINT SIGTERM
-	trap finish EXIT
 
 	# read and handle answer
 	confirmer || result="$?"
diff --git a/commands/seedbox b/commands/seedbox
--- a/commands/seedbox
+++ b/commands/seedbox
@@ -1,9 +1,10 @@
 #!/usr/bin/env bash
-source "$DOROTHY/sources/strict.bash"
-source "$DOROTHY/sources/arrays.bash"
-requires_array_support 'mapfile'
 
 function seedbox() (
+	source "$DOROTHY/sources/strict.bash"
+	source "$DOROTHY/sources/arrays.bash"
+	requires_array_support 'mapfile'
+
 	# =====================================
 	# Arguments
 
@@ -87,23 +88,22 @@ function seedbox() (
 
 	# check for support
 	if ! is-ubuntu; then
-		echo-style --error="[$0] is implemented for Ubuntu systems..." >/dev/stderr
-		if ! confirm-negative --ppid=$$ -- 'Proceed at your own risk?'; then
-			return 1
+		echo-style --notice="[$0] is implemented for Ubuntu systems..." >/dev/stderr
+		if ! confirm --negative --ppid=$$ -- 'Proceed at your own risk?'; then
+			return 0
 		fi
 	fi
 
 	# dependencies
 	if ! command-exists docker; then
-		echo-style --error="Docker not found, install it first with [setup-docker]." >/dev/stderr
+		echo-error "$0: Docker not found, install it first with [setup-docker]."
 		return 1
 	fi
 
 	# check docker is working
 	eval-helper --quiet=yes \
-		-- sudo-helper \
-		-- systemctl status docker --no-pager || {
-		echo-style --error='Docker not ready.' >/dev/stderr
+		-- service-helper --status -- docker || {
+		echo-error "$0: Docker not ready."
 		return 1
 	}
 
@@ -246,7 +246,7 @@ function seedbox() (
 				echo-style --error='The seedbox failed to connect to the VPN.'
 				echo-lines -- "${details[@]}"
 				echo
-				if confirm-positive --ppid=$$ -- 'Would you like to debug it?'; then
+				if confirm --positive --ppid=$$ -- 'Would you like to debug it?'; then
 					seedbox_debug
 				fi
 			} >/dev/stderr
diff --git a/commands/setup-dns b/commands/setup-dns
--- a/commands/setup-dns
+++ b/commands/setup-dns
@@ -1,15 +1,16 @@
 #!/usr/bin/env bash
-source "$DOROTHY/sources/strict.bash"
-source "$DOROTHY/sources/nullglob.bash"
-source "$DOROTHY/sources/shims.bash"
-source "$DOROTHY/sources/arrays.bash"
-requires_array_support 'mapfile' 'empty'
 
 function setup-dns() (
+	source "$DOROTHY/sources/strict.bash"
+	source "$DOROTHY/sources/nullglob.bash"
+	source "$DOROTHY/sources/shims.bash"
+	source "$DOROTHY/sources/arrays.bash"
+	requires_array_support 'mapfile' 'empty'
+
 	# check for support
 	if ! (is-mac || is-ubuntu); then
 		echo-style --notice="[$0] is implemented for macOS and Ubuntu systems..." >/dev/stderr
-		if ! confirm-negative --ppid=$$ -- 'Proceed at your own risk?'; then
+		if ! confirm --negative --ppid=$$ -- 'Proceed at your own risk?'; then
 			return 0
 		fi
 	fi
@@ -122,12 +123,14 @@ function setup-dns() (
 	}
 
 	# process
-	local item option_service=''
+	local item quiet option_service=''
+	quiet="$(echo-quiet -- "$@")"
 	while test "$#" -ne 0; do
 		item="$1"
 		shift
 		case "$item" in
 		'--help' | '-h') help ;;
+		'--no-quiet'* | '--quiet'* | '--no-verbose'* | '--verbose'*) ;; # handled by echo-quiet
 		'--'*) help "An unrecognised flag was provided: $item" ;;
 		*)
 			if test -z "$option_service"; then
@@ -229,10 +232,10 @@ function setup-dns() (
 		# it does exist
 		if is-mac; then
 			# get its basename which is the service id
-			id="$(fs-filename --basename "$file")"
-			eval-helper -- sudo-helper -- launchctl stop "$id" || :
+			id="$(fs-filename --basename -- "$file")"
+			service-helper --quiet="$quiet" --stop -- "$id" || :
 		else
-			sudo-helper -- systemctl stop "$file" || :
+			service-helper --quiet="$quiet" --stop -- "$file" || :
 		fi
 	}
 
@@ -248,19 +251,19 @@ function setup-dns() (
 
 		# it does exist
 		# get its basename which is the service id
-		id="$(fs-filename --basename "$file")"
+		id="$(fs-filename --basename -- "$file")"
 		if is-mac; then
 			# Usage: launchctl unload <service-path, service-path2, ...>
 			# -w      Additionally disables the service such that future load
 			#         operations will result in a service which launchd tracks but
 			#         cannot be launched or discovered in any way.
-			eval-helper -- sudo-helper -- launchctl disable "system/$id" || :
-			eval-helper -- sudo-helper -- launchctl stop "$id" || :
-			eval-helper -- sudo-helper -- launchctl unload -w "$file" || :
-			do_rm -- /Library/Logs/*"$id"*.log || :
+			service-helper --quiet="$quiet" --disable -- "system/$id" || :
+			service-helper --quiet="$quiet" --stop -- "$id" || :
+			service-helper --quiet="$quiet" --unload -- "$file" || :
+			do_rm -- /Library/Logs/*"$id"*.log
 		else
-			sudo-helper -- systemctl disable --now "$file" || :
-			sudo-helper -- systemctl status "$id" --no-pager || :
+			service-helper --quiet="$quiet" --disable --stop -- "$file" || :
+			service-helper --quiet="$quiet" --status -- "$id" || :
 		fi
 		do_rm -- "$file"
 	}
@@ -268,38 +271,25 @@ function setup-dns() (
 	# loads/installs the service, then enables and starts it
 	function service_enable {
 		local file="$1" id
-		id="$(fs-filename --basename "$file")"
+		id="$(fs-filename --basename -- "$file")"
 		if is-mac; then
 			# ensure correct permissions, not sure why
 			# but [homebrew services] does this, so doing it here
 			sudo-helper -- chown root:admin "$file"
 			sudo-helper -- chmod +t "$file"
-
-			# Usage: launchctl load <service-path, service-path2, ...>
-			# -w      If the service is disabled, it will be enabled. In previous
-			#         versions of launchd, being disabled meant that a service was
-			#         not loaded. Now, services are always loaded. If a service is
-			#         disabled, launchd does not advertise its service endpoints
-			#         (sockets, Mach ports, etc.).
-			# -F      Forcibly load the service. This flag will ignore the service's
-			#         disabled state. In previous versions of launchd, this flag
-			#         would also ignore the ownership and permissions of the
-			#         specified launchd.plist. This is no longer the case. Note that,
-			#         unlike the -w flag, this flag will not  modify the service's
-			#         disabled state; it will instead only ignore it for the load
-			#         operation.
-			eval-helper -- sudo-helper -- launchctl load -w "$file" || :
-			# eval-helper -- sudo-helper -- launchctl enable "system/$id" || :
-			eval-helper -- sudo-helper -- launchctl start "$id" || :
+			service-helper --quiet="$quiet" --load -- "$file" || :
+			# service-helper --quiet="$quiet" --start -- "system/$id" || :
+			service-helper --quiet="$quiet" --start -- "$id" || :
 			sleep 2
-			cat /Library/Logs/*"$id"*.log || :
+			eval-helper --no-quiet -- cat /Library/Logs/*"$id"*.log || :
 		else
-			sudo-helper -- systemctl enable --now "$file" || :
-			sudo-helper -- systemctl status "$id" --no-pager || :
+			service-helper --quiet="$quiet" --enable --start -- "$file" || :
+			service-helper --quiet="$quiet" --status -- "$id" || :
 		fi
 	}
 
 	function do_rm {
+		# never "do_rm ... || :" as that will cause aborts to fail
 		local id rm_paths=() rm_path
 
 		# remove all files associated with an id
@@ -348,7 +338,7 @@ function setup-dns() (
 		# remove them
 		for rm_path in "${rm_paths[@]}"; do
 			if test -e "$rm_path"; then
-				if confirm-positive --ppid=$$ -- "Remove $(echo-style --bold="$rm_path")?" "$(
+				if confirm --positive --ppid=$$ -- "Remove $(echo-style --bold="$rm_path")?" "$(
 					echo-style --dim="$(
 						ls -la "$rm_path"
 					)"
@@ -360,7 +350,7 @@ function setup-dns() (
 
 		# after service additions/removals
 		# systemctl needs to be reloaded apparently
-		if is-linux; then
+		if command-exists systemctl; then
 			sudo-helper -- systemctl daemon-reload
 			sudo-helper -- systemctl reset-failed
 			# ^ use sudo, otherwise prompted via ubuntu user password
@@ -786,8 +776,8 @@ function setup-dns() (
 			echo-segment --h1="Configure and $action_title $systemd_title"
 
 			# apply changes to services
-			sudo-helper -- systemctl stop systemd-networkd || :
-			sudo-helper -- systemctl stop systemd-resolved || :
+			service-helper --quiet="$quiet" --stop -- systemd-networkd || :
+			service-helper --quiet="$quiet" --stop -- systemd-resolved || :
 
 			# make life simple, using only /etc/resolv.conf
 			# https://www.freedesktop.org/software/systemd/man/resolved.conf.html
@@ -834,8 +824,8 @@ function setup-dns() (
 
 			# temporarily start system services, so that changes can be applied to them
 			# sudo-helper -- systemctl daemon-reload
-			# sudo-helper -- systemctl start systemd-networkd
-			sudo-helper -- systemctl start systemd-resolved
+			# service-helper --quiet="$quiet" --start -- systemd-networkd
+			service-helper --quiet="$quiet" --start -- systemd-resolved
 
 			# flush any caches
 			sudo-helper -- resolvectl flush-caches --no-pager || :
@@ -866,12 +856,12 @@ function setup-dns() (
 			# now that it is all done, enable or disable
 			if test "$action" = 'enable'; then
 				# enable
-				sudo-helper -- systemctl enable --now systemd-resolved
+				service-helper --quiet="$quiet" --enable --start -- systemd-resolved
 
 				# verify
 				verify_dns_resolvectl
 			else
-				sudo-helper -- systemctl disable --now systemd-resolved
+				service-helper --quiet="$quiet" --disable --stop -- systemd-resolved
 			fi
 
 			# after significant systemd changes, it may need to be reloaded
@@ -1329,10 +1319,10 @@ function setup-dns() (
 		if test "${#CLOUDFLARED_TUNNELS[@]}" -ne 0; then
 			# only remove the service file
 			# as tunnels uses the same binary
-			do_rm -- "$cloudflared_proxy_service_file" || :
+			do_rm -- "$cloudflared_proxy_service_file"
 		else
 			# ensure everything related to the proxy is removed
-			do_rm "$cloudflared_id" -- "$cloudflared_proxy_service_file" || :
+			do_rm "$cloudflared_id" -- "$cloudflared_proxy_service_file"
 		fi
 
 		# log
@@ -1556,16 +1546,19 @@ EOF
 
 		# cleanup old login details and login again
 		do_rm -- "$tunnel_user_pem"
-		"$cloudflared_bin_file" tunnel login
+		eval-helper --quiet --shapeshifter \
+			-- "$cloudflared_bin_file" tunnel login
 		chmod 600 "$tunnel_user_pem"
 		# creates $tunnel_user_pem no need to move it though
 
 		# cleanup the old tunnel remote connections and registration
-		"$cloudflared_bin_file" tunnel cleanup "$tunnel" || : # cleanup connections
-		"$cloudflared_bin_file" tunnel delete "$tunnel" || :  # delete tunnel
+		eval-helper --quiet \
+			-- "$cloudflared_bin_file" tunnel cleanup "$tunnel" || : # cleanup connections
+		eval-helper --quiet \
+			-- "$cloudflared_bin_file" tunnel delete "$tunnel" || : # delete tunnel
 
 		# cleanup the old tunnel files
-		do_rm "cloudflared-tunnel-$tunnel" -- "$tunnel_conf_file" "$tunnel_cred_file" || :
+		do_rm "cloudflared-tunnel-$tunnel" -- "$tunnel_conf_file" "$tunnel_cred_file"
 
 		# create the new tunnel again
 		temp_cred_file="$(
@@ -1574,7 +1567,8 @@ EOF
 				--directory="cloudflared-tunnel-$tunnel" \
 				--file="$tunnel_service_id-$tunnel.json" --no-touch
 		)"
-		"$cloudflared_bin_file" tunnel create \
+		eval-helper --quiet \
+			-- "$cloudflared_bin_file" tunnel create \
 			--credentials-file "$temp_cred_file" \
 			"$tunnel"
 		chmod 660 "$temp_cred_file"
@@ -1589,7 +1583,8 @@ EOF
 
 		# tunnel route
 		for hostname in "${hostnames[@]}"; do
-			"$cloudflared_bin_file" tunnel route dns \
+			eval-helper --no-quiet \
+				-- "$cloudflared_bin_file" tunnel route dns \
 				--overwrite-dns "$tunnel" "$hostname"
 		done
 
@@ -1671,7 +1666,7 @@ EOF
 				# if no env, call single without args so it pompts
 				tunnel_configure_single
 				# and ask again until the user is done adding tunnels
-				while confirm-negative --ppid=$$ -- "Do you wish to add another tunnel?"; do
+				while confirm --negative --ppid=$$ -- "Do you wish to add another tunnel?"; do
 					tunnel_configure_single
 				done
 			else
@@ -1716,7 +1711,7 @@ EOF
 	cloudflared_tunnels='no'
 	if test "${#CLOUDFLARED_TUNNELS[@]}" -ne 0; then
 		cloudflared_tunnels='yes'
-	elif confirm-negative --ppid=$$ -- "Do you wish to create a Cloudflare tunnel?"; then
+	elif confirm --negative --ppid=$$ -- "Do you wish to create a Cloudflare tunnel?"; then
 		cloudflared_tunnels='yes'
 	fi
 
@@ -1787,7 +1782,7 @@ EOF
 	# echo "DNS service setup succesfully ✅"
 
 	# 7. Configure the tunnel
-	if test "$cloudflared_tunnels" = 'yes' && confirm-positive --ppid=$$ -- "Reinstall cloudflare tunnels?"; then
+	if test "$cloudflared_tunnels" = 'yes' && confirm --positive --ppid=$$ -- "Reinstall cloudflare tunnels?"; then
 		tunnel_configure
 		# verify tunnels works
 	fi
