is-tty: add `--fallback` option to get the tty target with stderr fallback
use `is-tty --fallback` throughout dorothy, to prevent crashes when TTY is not accessible

diff --git a/commands/confirm b/commands/confirm
--- a/commands/confirm
+++ b/commands/confirm
@@ -2,7 +2,7 @@
 
 # NOTES:
 # [echo -en] doesn't work with escape codes on bash v3, [printf ...] does
-# [/dev/tty] is used as otherwise "$(confirm ...)" will not output anything to the user, as stdout gets captured in those situations
+# ["$tty_target"] is used as otherwise "$(confirm ...)" will not output anything to the user, as stdout gets captured in those situations
 #    why would anyone use confirm in that way? they don't but confirm within a getter does, such as [select_installer] within [macos-drive]
 
 function confirm_test() (
@@ -135,6 +135,9 @@ function confirm() (
 	# =====================================
 	# Helpers
 
+	local tty_target
+	tty_target="$(is-tty --fallback)"
+
 	# used to process the input
 	function do_read {
 		local answer read_status
@@ -211,7 +214,7 @@ function confirm() (
 		fi
 
 		# try reading again, and erase any leaked characters
-		printf '\e[%sG\e[K' "$hx" >/dev/tty
+		printf '\e[%sG\e[K' "$hx" >"$tty_target"
 		do_read
 	}
 
@@ -239,13 +242,13 @@ function confirm() (
 		header="$(mktemp)"
 		hx=''
 		for ((question_index = 0; question_index < "$question_parts_total"; question_index++)); do
-			print_string "${option_question_parts[question_index]} " | tee -a "$header" >/dev/tty
+			print_string "${option_question_parts[question_index]} " | tee -a "$header" >"$tty_target"
 			if test "$question_index" -eq 0; then
 				# read cursor x y, discard y, set hx to y
-				IFS='[;' read -t "$(get_read_decimal_timeout 0.01)" -srd R -p $'\e[6n' _ _ hx </dev/tty || :
+				IFS='[;' read -t "$(get_read_decimal_timeout 0.01)" -srd R -p $'\e[6n' _ _ hx <"$tty_target" || :
 			fi
 			if test "$question_index" -ne "$question_parts_last"; then
-				echo | tee -a "$header" >/dev/tty
+				echo | tee -a "$header" >"$tty_target"
 			fi
 		done
 
@@ -256,11 +259,11 @@ function confirm() (
 			lines="$(echo-count-lines --no-inline <"$header")"
 			# move these lines up
 			if test "$lines" -ne 0; then
-				printf '\e[%sF' "$lines" >/dev/tty
+				printf '\e[%sF' "$lines" >"$tty_target"
 			fi
 			# move to the hx column
 			if test -n "$hx"; then
-				printf '\e[%sG' "$hx" >/dev/tty
+				printf '\e[%sG' "$hx" >"$tty_target"
 			fi
 		fi
 
@@ -284,18 +287,18 @@ function confirm() (
 		trap - SIGINT SIGTERM
 
 		# make sure to erase question, as ctrl+c buggers everything
-		printf '\e[G\e[J' >/dev/tty
+		printf '\e[G\e[J' >"$tty_target"
 
 		# output the finale
 		if test "$RESULT" -eq 0; then
 			# positive response
-			echo-style "$question_first_part" --green+bold="$option_yes" >/dev/tty
+			echo-style "$question_first_part" --green+bold="$option_yes" >"$tty_target"
 		elif test "$RESULT" -eq 1; then
 			# negative response
-			echo-style "$question_first_part" --red+bold="$option_no" >/dev/tty
+			echo-style "$question_first_part" --red+bold="$option_no" >"$tty_target"
 		else
 			# crash response
-			echo-style "$question_first_part" --red+bold="$option_abort" >/dev/tty
+			echo-style "$question_first_part" --red+bold="$option_abort" >"$tty_target"
 			# kill caller's parent
 			if test "$option_ppid" -ge 0; then
 				if test "$option_ppid" -ge 1; then
diff --git a/commands/is-tty b/commands/is-tty
--- a/commands/is-tty
+++ b/commands/is-tty
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+# trunk-ignore-all(shellcheck/SC2217)
 
 function is_tty_test() (
 	source "$DOROTHY/sources/bash.bash"
@@ -6,7 +7,6 @@ function is_tty_test() (
 	echo-segment --h1="TEST: $0"
 
 	function do_test {
-		# trunk-ignore-all(shellcheck/SC2217)
 		print_line "\$- = $-"
 
 		print_line 'tty:'
@@ -45,15 +45,10 @@ function is_tty_test() (
 		( (printf '' >/dev/stderr && echo printf_to_stderr_pass) || echo printf_to_stderr_fail) || :
 		( (printf '' >/dev/tty && echo printf_to_tty_pass) || echo printf_to_tty_fail) || :
 
-		( (true </dev/stdin && echo true_from_stdin_pass) || echo true_from_stdin_fail) || :
-		( (true </dev/stdout && echo true_from_stdout_pass) || echo true_from_stdout_fail) || :
-		( (true </dev/stderr && echo true_from_stderr_pass) || echo true_from_stderr_fail) || :
-		( (true </dev/tty && echo true_from_tty_pass) || echo true_from_tty_fail) || :
-
-		( (true >/dev/stdin && echo true_to_stdin_pass) || echo true_to_stdin_fail) || :
-		( (true >/dev/stdout && echo true_to_stdout_pass) || echo true_to_stdout_fail) || :
-		( (true >/dev/stderr && echo true_to_stderr_pass) || echo true_to_stderr_fail) || :
-		( (true >/dev/tty && echo true_to_tty_pass) || echo true_to_tty_fail) || :
+		( (printf '' </dev/stdin >/dev/stdin && echo printf_bidirectional_stdin_pass) || echo printf_bidirectional_stdin_fail) || :
+		( (printf '' </dev/stdout >/dev/stdout && echo printf_bidirectional_stdout_pass) || echo printf_bidirectional_stdout_fail) || :
+		( (printf '' </dev/stderr >/dev/stderr && echo printf_bidirectional_stderr_pass) || echo printf_bidirectional_stderr_fail) || :
+		( (printf '' </dev/tty >/dev/tty && echo printf_bidirectional_tty_pass) || echo printf_bidirectional_tty_fail) || :
 
 		( (: </dev/stdin && echo noop_from_stdin_pass) || echo noop_from_stdin_fail) || :
 		( (: </dev/stdout && echo noop_from_stdout_pass) || echo noop_from_stdout_fail) || :
@@ -65,10 +60,10 @@ function is_tty_test() (
 		( (: >/dev/stderr && echo noop_to_stderr_pass) || echo noop_to_stderr_fail) || :
 		( (: >/dev/tty && echo noop_to_tty_pass) || echo noop_to_tty_fail) || :
 
-		( (: </dev/stdin >/dev/stdin && echo noop_from_to_stdin_pass) || echo noop_from_to_stdin_fail) || :
-		( (: </dev/stdout >/dev/stdout && echo noop_from_to_stdout_pass) || echo noop_from_to_stdout_fail) || :
-		( (: </dev/stderr >/dev/stderr && echo noop_from_to_stderr_pass) || echo noop_from_to_stderr_fail) || :
-		( (: </dev/tty >/dev/tty && echo noop_from_to_tty_pass) || echo noop_from_to_tty_fail) || :
+		( (: </dev/stdin >/dev/stdin && echo noop_bidirectonal_stdin_pass) || echo noop_bidirectonal_stdin_fail) || :
+		( (: </dev/stdout >/dev/stdout && echo noop_bidirectonal_stdout_pass) || echo noop_bidirectonal_stdout_fail) || :
+		( (: </dev/stderr >/dev/stderr && echo noop_bidirectonal_stderr_pass) || echo noop_bidirectonal_stderr_fail) || :
+		( (: </dev/tty >/dev/tty && echo noop_bidirectonal_tty_pass) || echo noop_bidirectonal_tty_fail) || :
 
 		print_line '-----------'
 
@@ -141,7 +136,11 @@ function is_tty() (
 			This is important, as otherwise calls to [tty] will result in "not a tty" being output.
 
 			USAGE:
-			is-tty
+			is-tty [..options]
+
+			OPTIONS:
+			--fallback
+			    Output /dev/tty if available, otherwise output /dev/stderr. Always return success status.
 		EOF
 		if test "$#" -ne 0; then
 			echo-error "$@"
@@ -150,12 +149,15 @@ function is_tty() (
 	}
 
 	# process
-	local item
+	local item option_fallback='no'
 	while test "$#" -ne 0; do
 		item="$1"
 		shift
 		case "$item" in
 		'--help' | '-h') help ;;
+		'--no-fallback'* | '--fallback'*)
+			option_fallback="$(get-flag-value fallback --missing="$option_fallback" -- "$item" | echo-affirmative)"
+			;;
 		'--'*) help "An unrecognised flag was provided: $item" ;;
 		*) help "An unrecognised argument was provided: $item" ;;
 		esac
@@ -164,9 +166,18 @@ function is_tty() (
 	# =====================================
 	# Action
 
-	# correctly and safely if TTY is writable
-	(printf '' >/dev/tty) &>/dev/null
-	return $?
+	# correctly, safely, and without side-effects, determine if the TTY is attached, readable, and writable
+	if test "$option_fallback" = 'yes'; then
+		if (: </dev/tty >/dev/tty) &>/dev/null; then
+			print_line '/dev/tty'
+		else
+			print_line '/dev/stderr'
+		fi
+		return 0
+	else
+		(: </dev/tty >/dev/tty) &>/dev/null
+		return $?
+	fi
 )
 
 # fire if invoked standalone
