confirm* scripts now work with screen
screen would translate scrollling into key up/down combinations, as such `read-arrow` is now used instead, this actually works out a lot better

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/confirm-bool b/commands/confirm-bool
--- a/commands/confirm-bool
+++ b/commands/confirm-bool
@@ -3,46 +3,30 @@ source "$DOROTHY/sources/strict.bash"
 
 # 0=yes
 # 1=no
+# timeout=failure
 
 function confirmer() {
 	local ec
 
-	# prompt the user
 	# timeout one hour
-	ec=0; read -t 3600 -r -n 1 -p "$1 (y/n) " answer || ec="$?"
-	if test "$ec" -gt 128; then
-		return 62 # Timer expired
-	elif test "$ec" -ne 0; then
-		return "$ec"
-	fi
-
-	# check for strange answers
-	if test "$answer" = $'\x1b'; then
-		# escape key should equal no
-		return 1  # 1=n0
-	elif test "$answer" = ''; then
-		# no answer / enter key
-		echo  # newline, otherwise everything on same line
-		# ask again
-		confirmer "$1"
-		return "$?"  # return with the above on success and failure
-	fi
+	echo -en "$@ (y/n) "
+	answer="$(read-arrow --timeout 3600)" || return "$?"
 
 	# check their answer
 	ec=0; is-affirmative "$answer" || ec="$?"
-
-	# check if indeterminate, if so, ask again
-	if test "$ec" -eq 2; then
+	if test "$ec" -lt 2; then
+		return "$ec"
+	elif test "$answer" = 'escape'; then
+		return 1
+	else
+		# ask again
 		echo  # newline, otherwise everything on same line
-		confirmer "$1"
+		confirmer "$@"
 		return "$?"  # return with the above on success and failure
 	fi
-
-	# return if determinate
-	echo # also add a newline as y/n do not
-	return "$ec"
 }
 
 # confirm with the user
-confirmer "$1"
-exit "$?"  # exit with the above on success and failure
+ec=0; confirmer "$@" || ec="$?"
+echo  # newline, as y/n do not
+exit "$ec"  # exit with the result
diff --git a/commands/confirm-negative b/commands/confirm-negative
--- a/commands/confirm-negative
+++ b/commands/confirm-negative
@@ -10,13 +10,34 @@ source "$DOROTHY/sources/strict.bash"
 # yes being a success exit code (0)
 # no being a failure exit code (1)
 
-echo -ne "${1?"USAGE: confirm-negative <message>"} (y/N) "
-ec=0; read -t 60 -r -n 1 answer || ec="$?"
-if test "$ec" -gt 128; then
-	exit 62 # Timer expired
-elif test "$ec" -ne 0; then
-	exit "$ec"
-fi
-echo ""
+# special characters, like scroll during `screen` usage, should be ask again
+function confirmer() {
+	local ec
 
-test "$answer" = 'y' -o "$answer" = 'Y'
+	# timeout one minute
+	echo -en "$@ (y/N) "
+	ec=0; answer="$(read-arrow --timeout 60)" || ec="$?"
+	if test "$ec" -eq 62; then
+		return 1
+	elif test "$ec" -ne 0; then
+		return "$ec"
+	fi
+
+	# check their answer
+	ec=0; is-affirmative "$answer" || ec="$?"
+	if test "$ec" -lt 2; then
+		return "$ec"
+	elif test "$answer" = 'enter' -o "$answer" = 'escape'; then
+		return 1
+	else
+		# ask again
+		echo  # newline, otherwise everything on same line
+		confirmer "$@"
+		return "$?"  # return with the above on success and failure
+	fi
+}
+
+# confirm with the user
+ec=0; confirmer "$@" || ec="$?"
+echo  # newline, as y/n do not
+exit "$ec"  # exit with the result
