redo `config-helper` to unify approaches
- `TIPS.md` added a note about file replacements
- `config.bash` created for updating config files, and getting
   - `config.sh` is now only the getter
   - this was necessary to properly support the complexity of updating
- `config-helper` has been rewritten
   - array replacements done via array flag
   - value replacements done via value flag
   - full replacements done via replacement flag
   - gets and replacements can happen on the same call
   - multiple array and values are now trimmed
   - value and array indentation now works correctly
   - array multi-line support properly works
   - no longer supports commenting the old value, though
- `confirm` can now customise more implicit things, and has a `--help`
   - seems the need to do a total - 1, was due to two `--` arguments being passed in practice
- `echo-lines` now supports `--indent=` and `--quoted` flags
- `eval-tester` now has `--help` and `--debug` flags
   - it also outputs quoted arguments in logs, for easy manual reproduction
- `setup-*`: made the `is-whatever` notices more consistent
- `setup-mac-apps` is now more powerful, and now has `--help` and `--configure` flags
   - this was the crux of the config helper redos in this commit
- `setup-util-plex` add brew installer
- `setup-utils` add docs for the `--configure` flag
- fix `config.fish` and `config.sh` both loading config differently, they now are simpler and work the way they are meant to

diff --git a/commands/confirm b/commands/confirm
--- a/commands/confirm
+++ b/commands/confirm
@@ -2,28 +2,68 @@
 source "$DOROTHY/sources/strict.bash"
 
 # =====================================
-# Options
+# Arguments
 
-timeout='3600' # one hour
+# help
+function help() {
+	cat <<-EOF >/dev/stderr
+		USAGE:
+		confirm [<...flags>] -- [<question> [<...details>]]
+
+		FLAGS:
+		[--mode=<bool, positive, negative, confirm>]
+		[--timeout=<timeout in seconds>]
+		[--yes=<on positive confirmations, what value to display>]
+		[--no=<on negative confirmations, what value to display>]
+		[--abort=<on aborted confirmations, what value to display>]
+		[--term=<on aborted ocnfirmations, terminate this process id>]
+
+		QUIRKS:
+		As negative confirmations return a failure exit code, and abortions a different failure exit code, you probably need to use [--term=$$] so that confirmation abortions actually continue the abortion, and are not just considered a negative confirmation.
+	EOF
+	if test "$#" -ne 0; then
+		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines "$@")" >/dev/stderr
+	fi
+	return 22 # Invalid argument
+}
+
+# process
 option_mode='confirm'
+option_timeout='3600' # one hour
 option_yes='OK'
 option_no='CANCEL'
+option_abort='ABORT'
 option_term=''
-while is-needle '--' "$@"; do
-	if [[ "$1" = '--mode='* ]]; then
-		option_mode="${1:7}" # bool/positive/negative/confirm
+question_parts=()
+while test "$#" -ne 0; do
+	item="$1"
+	shift
+	case "$item" in
+	'--help' | '-h') help ;;
+	'--mode='*)
+		option_mode="${item:7}" # bool/positive/negative/confirm
 		if test "$option_mode" = 'positive' -o "$option_mode" = 'negative'; then
-			timeout='60' # one minute
+			option_timeout='60' # one minute
 			option_yes='YES'
 			option_no='NO'
 		elif test "$option_mode" = 'bool'; then
 			option_yes='YES'
 			option_no='NO'
 		fi
-	elif [[ "$1" = '--term='* ]]; then
-		option_term="${1:7}"
-	fi
-	shift
+		;;
+	'--timeout='*) option_timeout="${item:10}" ;;
+	'--yes='*) option_yes="${item:6}" ;;
+	'--no='*) option_no="${item:5}" ;;
+	'--abort='*) option_abort="${item:8}" ;;
+	'--term='*) option_term="${item:7}" ;;
+	'--')
+		question_parts+=("$@")
+		shift $#
+		break
+		;;
+	'--'*) help "An unrecognised flag was provided: $item" ;;
+	*) help "An unrecognised argument was provided: $item" ;;
+	esac
 done
 
 # =====================================
@@ -34,7 +74,7 @@ function confirmer() {
 	local ec answer
 
 	# ask and timeout
-	ec=0 && answer="$(read-arrow --timeout "$timeout")" || ec="$?"
+	ec=0 && answer="$(read-arrow --timeout "$option_timeout")" || ec="$?"
 
 	# process
 	if test "$option_mode" = 'positive'; then
@@ -104,9 +144,8 @@ function confirmer() {
 # Question
 
 # prepare
-question_first_part="${1-} " # this is stored for the finale
-question_parts=("$@")
-question_parts_total="$(($# - 1))"
+question_first_part="${question_parts[0]} " # this is stored for the finale
+question_parts_total="${#question_parts[@]}"
 header="$(mktemp)"
 lines=0
 ec=0
@@ -119,13 +158,13 @@ elif test "$option_mode" = 'negative'; then
 elif test "$option_mode" = 'bool'; then
 	question_parts[0]+=" $(echo-style --blink='(y/n)')"
 fi
-for ((i = 0; i <= "$question_parts_total"; i++)); do
+for ((i = 0; i < "$question_parts_total"; i++)); do
 	echo -n "${question_parts[i]} " | tee -a "$header"
 	if test "$i" -eq 0; then
 		# read cursor x y, discard y, set hx to y
 		IFS='[;' read -srd R -p $'\e[6n' _ _ hx
 	fi
-	if test "$i" -ne "$question_parts_total"; then
+	if test "$((i + 1))" -ne "$question_parts_total"; then
 		echo | tee -a "$header"
 	fi
 done
@@ -151,7 +190,7 @@ function finish() {
 	elif test "$ec" -eq 1; then
 		echo-style "$question_first_part" --red+bold="$option_no"
 	else
-		echo-style "$question_first_part" --red+bold="ABORT"
+		echo-style "$question_first_part" --red+bold="$option_abort"
 		if test -n "$option_term"; then
 			# kill "-$ec" ...
 			# ^ fails because 130 isn't supported
diff --git a/commands/setup-mac-apps b/commands/setup-mac-apps
--- a/commands/setup-mac-apps
+++ b/commands/setup-mac-apps
@@ -4,9 +4,69 @@ source "$DOROTHY/sources/arrays.bash"
 requires_array_support 'mapfile' 'empty'
 
 # =====================================
+# Checks
+
+# check that an accident has not occured
+if ! is-mac; then
+	echo-style --notice="[$0] is only intended to be run on macOS systems, skipping." >/dev/stderr
+	exit 0
+fi
+
+# dependencies
+env NAME='Mac App Store command-line interface' CLI='mas' \
+	BREW='mas' \
+	setup-util brew
+
+# log
+echo-segment --h1="Install macOS apps"
+
+# =====================================
+# Arguments
+
+# local
+apps=()
+reconfigure='no'
+
+# help
+function help() {
+	cat <<-EOF >/dev/stderr
+		USAGE:
+		setup-mac-apps
+		# ^ install using [MAS_INSTALL] from your [setup.bash] configuration file
+
+		setup-utils -- <...name/id>
+		# ^ install the specified Mac App Store apps
+
+		setup-utils --configure
+		# ^ Prompts to configure [MAS_INSTALL] with what you currently have installed.
+	EOF
+	if test "$#" -ne 0; then
+		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines "$@")" >/dev/stderr
+	fi
+	return 22 # Invalid argument
+}
+
+# process
+while test "$#" -ne 0; do
+	item="$1"
+	shift
+	case "$item" in
+	'--help' | '-h') help ;;
+	'--configure') reconfigure='yes' ;;
+	'--')
+		apps+=("$@")
+		shift $#
+		break
+		;;
+	'--'*) help "An unrecognised flag was provided: $item" ;;
+	*) help "An unrecognised argument was provided: $item" ;;
+	esac
+done
+
+# =====================================
 # Configuration
 
-source "$DOROTHY/sources/config.sh"
+source "$DOROTHY/sources/config.bash"
 
 # setup.bash provides:
 MAS_INSTALL=() # tupe array of id, label
@@ -15,31 +75,93 @@ load_dorothy_config 'setup.bash'
 # =====================================
 # Action
 
-function mas_prepare() {
+# local variables
+prepared='no'
+
+function do_signin() {
+	if test "$prepared" = 'yes'; then
+		return 0
+	fi
 	local email
-	email="$(ask --question="The macOS application installer requires your Apple App Store email, enter it now." --require)"
+	email="$(
+		ask --required \
+			--question="The macOS application installer requires your Apple App Store email, enter it now."
+	)"
 	if is-value "$email"; then
 		mas signout
 		mas signin --dialog "$email"
+		prepared='yes'
 	else
 		return 1
 	fi
 }
-function mas_install() {
-	env NAME='Mac App Store command-line interface' CLI='mas' BREW='mas' setup-util brew
-	echo-segment --h2="Install $# macOS apps"
-	if test "$#" -ne 0; then
-		mas_prepare
+function do_install() {
+	if test "$prepared" = 'no'; then
+		mas install "$@" || {
+			do_signin
+			mas install "$@"
+		}
+	else
 		mas install "$@"
 	fi
-	echo-segment --g2="Install $# macOS apps"
 }
-function mas_ask() {
-	local choices fodder
+function do_install_bulk() {
 	if test "$#" -ne 0; then
-		fodder="$(choose-option --multi --question="Which Mac App Store apps would you like to install?" --label -- "${MAS_INSTALL[@]}")"
-		mapfile -t choices <<<"$fodder" # <( destroys stdin
-		mas_install "${choices[@]}"
+		do_install "$@"
 	fi
 }
-mas_ask "${MAS_INSTALL[@]}"
+function mas_config() {
+	local choices
+	if test "$#" -ne 0; then
+		mapfile -t choices < <(
+			choose-option --multi \
+				--question="Which Mac App Store apps would you like to install?" \
+				--label -- "$@"
+		)
+		do_install_bulk "${choices[@]}"
+	fi
+}
+function mas_args() {
+	local options option
+	for arg in "$@"; do
+		if is-numeric "$arg"; then
+			# if id, install directly
+			do_install "$arg"
+		else
+			# if name, find the id
+			mapfile -t options <(mas search "$arg" | cut -w -f1,2)
+			option="$(
+				choose-option \
+					--question="Which Mac App Store app was intended for $arg?" \
+					--label -- "${options[@]}"
+			)"
+			do_install "$option"
+		fi
+	done
+}
+
+# overrides
+if test "${#apps[@]}" -ne 0; then
+	mas_args "${apps[@]}"
+elif test "${#MAS_INSTALL[@]}" -ne 0; then
+	mas_config "${MAS_INSTALL[@]}"
+else
+	reconfigure='yes'
+fi
+
+# reconfigure
+if test "$reconfigure" = 'yes'; then
+	# add installed, which will include config and arg installations
+	while read -r id name; do
+		if ! is-needle "$id" "${MAS_INSTALL[@]}"; then
+			MAS_INSTALL+=("$id" "$name")
+		fi
+	done <<<"$(mas list | cut -w -f1,2 | sort -k 2)"
+
+	# save
+	update_dorothy_user_config 'setup.bash' -- \
+		--field='MAS_INSTALL' --array="$(echo-lines --quoted --columns=2 "${MAS_INSTALL[@]}" | sort -k 2)"
+fi
+
+# log
+echo-segment --g1="Install macOS apps"
