confirm* scripts now work with screen
screen would translate scrollling into key up/down combinations, as such `read-arrow` is now used instead, this actually works out a lot better

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/confirm b/commands/confirm
--- a/commands/confirm
+++ b/commands/confirm
@@ -1,10 +1,31 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# timeout one hour
-ec=0; read -t 3600 -r -n 1 -p "${1-}" || ec="$?"
-if test "$ec" -gt 128; then
-	exit 62 # Timer expired
-elif test "$ec" -ne 0; then
-	exit "$ec"
-fi
+# anything besides enter/space/y is ask again
+function confirmer() {
+	local ec
+
+	# timeout one hour
+	echo -en "$@"
+	answer="$(read-arrow --timeout 3600)" || return "$?"
+
+	# check their answer
+	ec=0; is-affirmative "$answer" || ec="$?"
+	if test "$ec" -lt 2; then
+		return "$ec"
+	elif test "$answer" = 'enter' -o "$answer" = 'space'; then
+		return 0
+	elif test "$answer" = 'escape'; then
+		return 1
+	else
+		# ask again
+		echo  # newline, otherwise everything on same line
+		confirmer "$@"
+		return "$?"  # return with the above on success and failure
+	fi
+}
+
+# confirm with the user
+ec=0; confirmer "$@" || ec="$?"
+echo  # newline, as y/n do not
+exit "$ec"  # exit with the result
