config-helper: more tests and comments

diff --git a/commands/config-helper b/commands/config-helper
--- a/commands/config-helper
+++ b/commands/config-helper
@@ -31,11 +31,13 @@ if is-needle '--test' "$@"; then
 
 		# test find only, used by <sharebox> commandd
 		# this is only for fetching config values, not for fetching lines, so the .gitignore style stuff isn't for this
-		echo $'User=uu\nGroup=gg' >>"$file"
+		echo $'User=uu\nGroup=gg\n# Party=pp' >>"$file"
 		eval-tester --stdout='uu' -- \
 			config-helper --file="$file" --find='User=(.*)'
 		eval-tester --stdout=$'uu\ngg' -- \
 			config-helper --file="$file" --find='User=(.*)' --find='Group=(.*)'
+		eval-tester --stdout=$'uu\ngg' -- \
+			config-helper --file="$file" --find='User' --find='Group' --find='Party'
 
 		# done
 		echo-segment --g1="TEST: $0"
@@ -75,7 +77,9 @@ if test "$replace_count" -eq 0; then
 	# we are find only
 	for find in "${find_array[@]}"; do
 		pattern="^[ 	]*($find)=?(.*)$"
-		rg -o "$pattern" --replace '$2' "$file" || : # don't fail on no results
+		# ^ with indentation but no comment (so we only get real values), and with value group so that $2 is consistent with overrides
+		rg -o "$pattern" --replace '$2' "$file" || :
+		# ^ don't fail on no results
 	done
 	exit
 fi
@@ -100,7 +104,7 @@ for find_index in "${!find_array[@]}"; do
 	# prepare
 	find="${find_array[find_index]}"
 	replace="${replace_array[find_index]}"
-	pattern="^([ 	]*)[# 	]*($find)$"
+	pattern="^([ 	]*)[# 	]*($find)$" # with indentation, with comment
 	found='no'
 	stack=()
 	results=()
