WIP: fix config-helper tests
- config-helper: instead of removing a line by replacing it with its indentation, it is now removed, as per the prior expectation
- add `echo-escape-backslashes` and remove it from `echo-escape-regexp-replacement` for compat with JavaScript Regular Expressions
- update some `bash.bash` deprecations
- bash.bash: add explicit names for `__print*` helpers, and slightly change their functionality to be aligned with expectations

diff --git a/commands/config-helper b/commands/config-helper
--- a/commands/config-helper
+++ b/commands/config-helper
@@ -43,7 +43,7 @@ function config_helper_test() (
 	sleep "$delay"
 	eval-tester --name='test-invalid-find-and-replace-arguments-02' --status=22 --ignore-stderr \
 		-- eval-no-color -- config-helper --no-quiet --file="$test_file" -- --find='a' --replace='one' --replace='two'
-	# ^ first find and replace succeeds, hence [one], second find and replace failed, hence no two
+	# ^ first find and replace succeeds on the empty test_file, hence [one], second find and replace failed, hence no two
 	sleep "$delay"
 	eval-tester --name='test-invalid-find-and-replace-arguments-03' --stdout='one' \
 		-- cat "$test_file"
@@ -294,15 +294,15 @@ function config_helper() (
 			elif [[ $option_search == '--find='* ]]; then
 				# indentable, commentable, pattern
 				find="${option_search#*=}"
-				search_pattern="^(?P<indent>[[:blank:]]*)(?P<comment>(?:#|[[:blank:]])*)(?P<value>$find)$"
-				get_value_pattern="^(?P<indent>[[:blank:]]*)(?P<value>$find)$" # ignore comments
-				remove_pattern='${indent}'
+				search_pattern="^(?P<indent>[[:blank:]]*)(?P<comment>(?:#|[[:blank:]])*)(?P<value>$find)(?P<trail>\n|$)"
+				get_value_pattern="^(?P<indent>[[:blank:]]*)(?P<value>$find)(?P<trail>\n|$)" # ignore comments
+				#remove_pattern='${indent}'
 			elif [[ $option_search == '--field='* ]]; then
 				# field that can be an array and value
 				field="${option_search#*=}"
-				search_pattern="^(?P<indent>[[:blank:]]*)(?P<comment>(?:#|[[:blank:]])*)$field *= *(?P<value>[(](?ms:.*?)[)]|[^\n]*)$"
-				get_value_pattern="^(?P<indent>[[:blank:]]*)$field *= *(?P<value>[(](?ms:.*?)[)]|[^\n]*)$" # ignore comments
-				remove_pattern='${indent}'
+				search_pattern="^(?P<indent>[[:blank:]]*)(?P<comment>(?:#|[[:blank:]])*)$field *= *(?P<value>[(](?ms:.*?)[)]|[^\n]*)(?P<trail>\n|$)"
+				get_value_pattern="^(?P<indent>[[:blank:]]*)$field *= *(?P<value>[(](?ms:.*?)[)]|[^\n]*)(?P<trail>\n|$)" # ignore comments
+				#remove_pattern='${indent}'
 			else
 				help "Invalid search argument [$option_search] it must be either --find=<pattern> or --field=<field>"
 			fi
@@ -367,21 +367,32 @@ function config_helper() (
 			shift
 			# then perform the replace
 
-			# remove superflous trailing lines, to ensure there is only one, and at least one
+			# ensure if there is a value, it only has a single trailing line, and if there isn't a value, it is empty
 			content="$(cat "$option_file")"
 			content="${content%$'\n'}"
+			if test -n "$content"; then
+				content+=$'\n'
+			fi
+			addition="${addition%$'\n'}"
+			if test -n "$addition"; then
+				addition+=$'\n'
+			fi
+			replace_pattern="${replace_pattern%$'\n'}"
+			if test -n "$replace_pattern"; then
+				replace_pattern+=$'\n'
+			fi
 
 			# do the replacement or addition
-			count="$(__print_values_print "$content" | echo-regexp -cm --find="$search_pattern" || :)"
+			count="$(__print_value_strings_or_nothing "$content" | echo-regexp -cm --find="$search_pattern" || :)"
 			if test -z "$count" || test "$count" -eq 0; then
 				# it wasn't found, so add manually if it's not empty
 				if test -n "$addition"; then
-					__print_values_print "$content" "$addition" >"$option_file"
+					__print_value_strings_or_nothing "$content" "$addition" >"$option_file"
 					UPDATED='yes' # a valid update occured, note for logging
 				fi
 			elif test "$count" -eq 1 -o "$option_multiple" = 'ok'; then
 				# first match replaced, subsequent matches removed
-				__print_values_print "$content" | echo-regexp -gm --find="$search_pattern" --replace="$replace_pattern" --replace="$remove_pattern" >"$option_file"
+				__print_value_strings_or_nothing "$content" | echo-regexp -gm --find="$search_pattern" --replace="$replace_pattern" --replace="$remove_pattern" >"$option_file"
 				UPDATED='yes' # a valid update occured, note for logging
 				# notes:
 				# sd only supports replacing every match with the same replacement
@@ -396,7 +407,7 @@ function config_helper() (
 				)"
 				if test "$option_multiple" = 'warn-skip'; then
 					# write update to temp file (for diff), do not update intended file
-					__print_values_print "$content" | echo-regexp -gm --find="$search_pattern" --replace="$replace_pattern" --replace="$remove_pattern" >"$temp_file"
+					__print_value_strings_or_nothing "$content" | echo-regexp -gm --find="$search_pattern" --replace="$replace_pattern" --replace="$remove_pattern" >"$temp_file"
 					{
 						echo-style --notice1='The configuration file ' --code-error1="$option_file" --error1=' was not saved' --notice1=' as multiple value instances exist within the configuration file, which may be computational conditions that our automation would be fraught to update.' $'\n' --info1='When you can' --notice1=' manually apply the requested changes to your configuration such that this automated update will not be attempted again.' $'\n' --notice1='Below is our unapplied automated attempt, saved to ' --code-notice1="$temp_file"
 						fs-diff -- "$option_file" "$temp_file" || :
@@ -404,7 +415,7 @@ function config_helper() (
 					} >/dev/stderr
 				elif test "$option_multiple" = 'warn-apply'; then
 					# write backup to temp file, write update to intended file
-					__print_values_print "$content" >"$temp_file"
+					__print_value_strings_or_nothing "$content" >"$temp_file"
 					echo-regexp -gm --find="$search_pattern" --replace="$replace_pattern" --replace="$remove_pattern" <"$temp_file" >"$option_file"
 					UPDATED='yes' # a valid update occured, note for logging
 					{
