confirm: fix tests, support `--no-color`
tests were broken just because of STDERR and TTY are now separated, and also because a bell output was not going to TTY

also change `...=tty` to `...=TTY`

diff --git a/commands/confirm b/commands/confirm
--- a/commands/confirm
+++ b/commands/confirm
@@ -9,55 +9,53 @@ function confirm_test() (
 	source "$DOROTHY/sources/bash.bash"
 	echo-style --h1="TEST: $0"
 
-	# --ignore-stderr otherwise only \n^[[68;1R is output
-
 	local escape=$'\e'
 
 	{
 		sleep 3
 		__print_line
-	} | eval-tester --name='receive positive response by enter key' --ignore-stderr -- \
+	} | eval-tester --name='receive positive response by enter key' --ignore-tty -- \
 		confirm --ppid=$$ --positive --timeout=5 -- 'What is your response?'
 
 	{
 		sleep 3
 		__print_line
-	} | eval-tester --name='receive negative response by enter key' --status=1 --ignore-stderr -- \
+	} | eval-tester --name='receive negative response by enter key' --status=1 --ignore-tty -- \
 		confirm --ppid=$$ --negative --timeout=5 -- 'What is your response?'
 
 	{
 		sleep 3
 		__print_lines 'y'
-	} | eval-tester --name='receive positive response by y key' --ignore-stderr -- \
+	} | eval-tester --name='receive positive response by y key' --ignore-tty -- \
 		confirm --ppid=-1 --bool --timeout=5 -- 'What is your response?'
 
 	{
 		sleep 3
 		__print_lines 'n'
-	} | eval-tester --name='receive negative response by n key' --status=1 --ignore-stderr -- \
+	} | eval-tester --name='receive negative response by n key' --status=1 --ignore-tty -- \
 		confirm --ppid=-1 --bool --timeout=5 -- 'What is your response?'
 
 	{
 		sleep 3
 		__print_line
-	} | eval-tester --name='receive timeout response by timeout and enter key rejected by require' --status=60 --ignore-stderr -- \
-		confirm --ppid=-1 --bool --timeout=5 -- 'What is your response?'
+	} | eval-tester --name='receive timeout response by timeout and enter key rejected by require' --status=60 --ignore-tty --stderr='What is your response?  [ABORT] [ input failure: timed out: required ]' -- \
+		confirm --no-color --ppid=-1 --bool --timeout=5 -- 'What is your response?'
 
-	eval-tester --name='receive positive response by timeout and no input' --ignore-stderr -- \
-		confirm --ppid=$$ --positive --timeout=5 -- 'What is your response?'
+	eval-tester --name='receive positive response by timeout and no input' --ignore-tty -- \
+		confirm --no-color --ppid=$$ --positive --timeout=5 -- 'What is your response?'
 
-	eval-tester --name='receive negative response by timeout and no input' --status=1 --ignore-stderr -- \
-		confirm --ppid=$$ --negative --timeout=5 -- 'What is your response?'
+	eval-tester --name='receive negative response by timeout and no input' --status=1 --ignore-tty -- \
+		confirm --no-color --ppid=$$ --negative --timeout=5 -- 'What is your response?'
 
-	eval-tester --name='receive timeout response by timeout and no input' --status=60 --ignore-stderr -- \
-		confirm --ppid=-1 --bool --timeout=5 -- 'What is your response?'
+	eval-tester --name='receive timeout response by timeout and no input' --status=60 --ignore-tty --stderr='What is your response?  [ABORT] [ input failure: timed out: required ]' -- \
+		confirm --no-color --ppid=-1 --bool --timeout=5 -- 'What is your response?'
 
 	{
 		# press escape key
 		sleep 3
 		__print_string "$escape"
-	} | eval-tester --name='receive abort response by escape key' --status=125 --ignore-stderr -- \
-		confirm --ppid=-1 --bool --timeout=5 -- 'What is your response?'
+	} | eval-tester --name='receive abort response by escape key' --status=125 --ignore-tty --stderr='What is your response?  [ABORT]' -- \
+		confirm --no-color --ppid=-1 --bool --timeout=5 -- 'What is your response?'
 
 	echo-style --g1="TEST: $0"
 	return 0
@@ -124,6 +122,10 @@ function confirm_() (
 		shift
 		case "$item" in
 		'--help' | '-h') help ;;
+		'--no-color'* | '--color'*)
+			export COLOR
+			COLOR="$(get-flag-value --affirmative --fallback=yes -- "$item")"
+			;;
 		'--question='*) option_question+=("${item#*=}") ;;
 		'--bool') option_mode='bool' ;;
 		'--positive' | '--positive=yes' | '--negative=no' | '--no-negative') option_mode='positive' ;;
@@ -246,7 +248,7 @@ function confirm_() (
 	# Action
 
 	local question_confirm_and_input_lines='' FINISHED=''
-	__do --redirect-stdout=tty -- __print_value_strings_or_nothing "$question_title_and_body"
+	__do --redirect-stdout=TTY -- __print_value_strings_or_nothing "$question_title_and_body"
 	function refresh {
 		# clear the prompt and any input lines
 		echo_clear_lines --target=TTY -- "$question_confirm_and_input_lines"
@@ -260,7 +262,7 @@ function confirm_() (
 				str+="${options_unselected[index]}"
 			fi
 		done
-		__do --redirect-stdout=tty -- __print_string "$str  "
+		__do --redirect-stdout=TTY -- __print_string "$str  "
 	}
 	function on_confirm_terminate {
 		RESULT=$?
@@ -288,14 +290,14 @@ function confirm_() (
 			# inform if requested
 			if [[ $option_linger == 'yes' ]]; then
 				result="${options_results[RESULT]}"
-				__do --redirect-stdout=tty -- __print_lines "$question_title_result$result$commentary"
+				__do --redirect-stdout=TTY -- __print_lines "$question_title_result$result$commentary"
 			fi
 		else
 			# failure response
 			# always inform
 			result="${options_results[abort_index]}"
 			if [[ $option_linger == 'yes' ]]; then
-				__do --redirect-stdout=tty -- __print_lines "$question_title_result$result$commentary"
+				__do --redirect-stdout=TTY -- __print_lines "$question_title_result$result$commentary"
 			else
 				# even if not lingering, ensure crash response is shown
 				__print_lines "$question_title_result$result$commentary" >&2
@@ -369,7 +371,7 @@ function confirm_() (
 			fi
 		elif [[ $read_status -eq 94 ]]; then
 			# unknown character, send bell and continue
-			__do --redirect-stdout=tty -- __print_string $'\a' # bell
+			__do --redirect-stdout=TTY -- __print_string $'\a' # bell
 			continue
 		elif [[ $read_status -ne 0 ]]; then
 			# failure
@@ -386,7 +388,7 @@ function confirm_() (
 					RESULT="$yes_index"
 					break
 				else
-					__do --redirect-stdout=tty -- __print_string $'\a' # bell
+					__do --redirect-stdout=TTY -- __print_string $'\a' # bell
 				fi
 				;;
 			'N' | 'n')
@@ -394,7 +396,7 @@ function confirm_() (
 					RESULT="$no_index"
 					break
 				else
-					__do --redirect-stdout=tty -- __print_string $'\a' # bell
+					__do --redirect-stdout=TTY -- __print_string $'\a' # bell
 				fi
 				;;
 			'left' | 'right' | 'up' | 'down')
@@ -433,7 +435,7 @@ function confirm_() (
 						break
 					fi
 				fi
-				__print_string $'\a' >&2 # bell
+				__do --redirect-stdout=TTY -- __print_string $'\a' >&2 # bell
 				;;
 			'escape' | 'Q' | 'q')
 				RESULT=125 # abort
