better error handling
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/confirm-bool b/commands/confirm-bool
--- a/commands/confirm-bool
+++ b/commands/confirm-bool
@@ -9,32 +9,32 @@ function confirmer() {
 	# timeout one hour
 	read -t 3600 -r -n 1 -p "$1 (y/n) " answer
 	if test "$?" -gt 128; then
-		# timeout occured, should equal no
-		exit 1
+		# timeout
+		return 1  # 1=no
 	fi
 
 	# check for strange answers
 	if test "$answer" = $'\x1b'; then
 		# escape key should equal no
-		return 1
+		return 1  # 1=n0
 	elif test "$answer" = ''; then
 		# no answer / enter key
 		echo  # newline, otherwise everything on same line
 		# ask again
 		confirmer "$1"
-		return "$?"
+		return "$?"  # return with the above on success and failure
 	fi
 
 	# check their answer
-	strict_e_pause; local e="$?"
-	is-affirmative "$answer"; local ec="$?"
-	strict_e_restore "$e"
+	strict_e_pause; local eo="$?"
+	is-affirmative "$answer"
+	local ec="$?"; strict_e_restore "$eo"
 
 	# check if indeterminate, if so, ask again
 	if test "$ec" -eq 2; then
 		echo  # newline, otherwise everything on same line
 		confirmer "$1"
-		return "$?"
+		return "$?"  # return with the above on success and failure
 	fi
 
 	# return if determinate
@@ -44,3 +44,4 @@ function confirmer() {
 
 # confirm with the user
 confirmer "$1"
+exit "$?"  # exit with the above on success and failure
diff --git a/commands/echo-exit-code b/commands/echo-exit-code
--- a/commands/echo-exit-code
+++ b/commands/echo-exit-code
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
-# don't use strict mode, as we want the exit code
+# no strict as we need exit codes
 
-"$@"
-echo "$?"
+( "$@" ); echo "$?"
 exit 0
diff --git a/commands/echo-split b/commands/echo-split
--- a/commands/echo-split
+++ b/commands/echo-split
@@ -16,7 +16,7 @@ fi
 # just echo each argument, which will put each part on a newline
 if test -z "${1-}" -o "${1-}" = $'\n'; then
 	echo-lines "${@:3}"
-	exit $?
+	exit "$?"  # exit with the above on success and failure
 fi
 
 # we have a delim, so split each argument by it
diff --git a/commands/get-url-upgrade b/commands/get-url-upgrade
--- a/commands/get-url-upgrade
+++ b/commands/get-url-upgrade
@@ -16,7 +16,7 @@ if test -z "$protocol"; then
 	# try http, which tries https first, otherwise fail
 	stderr echo "[$url] missing protocol, will try variations"
 	get-url-upgrade "http://$url"
-	exit $?
+	exit "$?"  # exit with the above on success and failure
 elif test "$protocol" = 'https'; then
 	# test original url works
 	if ! http-ok "$url"; then
diff --git a/commands/secret b/commands/secret
--- a/commands/secret
+++ b/commands/secret
@@ -45,8 +45,10 @@ function cache_clear() {
 
 function cache_exists() {
 	for key in "$@"; do
+		strict_e_pause; local eo="$?"
 		sudo test -f "$SECRETS/$key"
-		if test "$?" -ne 0; then
+		local ec="$?"; strict_e_restore "$eo"
+		if test "$ec" -ne 0; then
 			return 1
 		fi
 	done
@@ -54,8 +56,10 @@ function cache_exists() {
 
 function cache_delete() {
 	for key in "$@"; do
+		strict_e_pause; local eo="$?"
 		sudo rm -f "$SECRETS/$key"
-		if test "$?" -ne 0; then
+		local ec="$?"; strict_e_restore "$eo"
+		if test "$ec" -ne 0; then
 			return 1
 		fi
 	done
@@ -96,8 +100,10 @@ function secret_get() {
 	# many
 	if test "${#@}" -gt '1'; then
 		for var in "$@"; do
+			strict_e_pause; local eo="$?"
 			value="$(secret_get "$var")"
-			if test "$?" -ne 0; then
+			local ec="$?"; strict_e_restore "$eo"
+			if test "$ec" -ne 0; then
 				stderr echo "ERROR: Unable to fetch the secret [$var] of many"
 				return 1
 			fi
@@ -108,8 +114,10 @@ function secret_get() {
 
 	# singular
 	key="$1"
+	strict_e_pause; local eo="$?"
 	result="$( (cache_exists "$key" && cache_read "$key") || :)"
-	if test "$?" -ne 0; then
+	local ec="$?"; strict_e_restore "$eo"
+	if test "$ec" -ne 0; then
 		stderr echo "ERROR: Unable to fetch the secret [$var]"
 		return 1
 	fi
@@ -181,8 +189,10 @@ function secret_signin() {
 			# signin
 			# unfortunately, this still leaks email and subdomain
 			# https://1password.community/discussion/122030/flag-to-disable-op-signin-from-outputting-email-and-subdomain/p1?new=1
+			strict_e_pause; local eo="$?"
 			OP_SESSION="$(op signin "$OP_SUBDOMAIN" "$email" "$key" --raw)"  # don't pipe to anything else, as it breaks the OTP question
-			if test "$?" -ne 0; then
+			local ec="$?"; strict_e_restore "$eo"
+			if test "$ec" -ne 0; then
 				stderr echo "ERROR: Failed to sign into [$OP_SUBDOMAIN] via the email [$email] and account key [$key]."
 				stderr echo "$OP_SESSION"
 				return 1
@@ -196,8 +206,10 @@ function secret_signin() {
 }
 
 function opwrap () {
+	strict_e_pause; local eo="$?"
 	result="$(op "$@" 2>&1 || :)"
-	if test "$?" -ne 0 || [[ "$result" = '[ERROR]'* ]]; then
+	local ec="$?"; strict_e_restore "$eo"
+	if test "$ec" -ne 0 || [[ "$result" = '[ERROR]'* ]]; then
 		if [[ "$result" = *'signed in'* ]] || [[ "$result" = *'session expired'* ]]; then
 			stderr echo "ERROR: Session expired, run [secret login] and try again."
 			return 1
@@ -213,6 +225,7 @@ function opgrab() {
 	vault="${1-}"
 	item="${2-}"
 
+	strict_e_pause; local eo="$?"
 	if is-empty-value "$vault"; then
 		# fetch available values
 		opwrap list vaults --session="$OP_SESSION"
@@ -223,8 +236,8 @@ function opgrab() {
 		# fetch item
 		opwrap get item "$item" --vault="$vault" --session="$OP_SESSION"
 	fi
-
-	return "$?"
+	local ec="$?"; strict_e_restore "$eo"
+	return "$ec"
 }
 
 function fetch_vault () {
@@ -240,7 +253,7 @@ function fetch_vault () {
 
 	# filter or ask
 	choose-option --question='Which vault do you want?' --filter="$vault" --label --visual="\$label [\$value]" -- "${tuples[@]}"
-	return "$?"
+	return "$?"  # return with the above on success and failure
 }
 
 function fetch_item () {
@@ -257,7 +270,7 @@ function fetch_item () {
 
 	# filter or ask
 	choose-option --question='Which item do you want?' --filter="$item" --label --visual="\$label [\$value]" -- "${tuples[@]}"
-	return "$?"
+	return "$?"  # return with the above on success and failure
 }
 
 function fetch_field () {
@@ -294,7 +307,7 @@ function fetch_field () {
 
 	# filter or ask
 	choose-option --question='Which field do you want?' --filter="$field" --return="$wants" --label --visual="\$label [\$value]" -- "${fields[@]}"
-	return "$?"
+	return "$?"  # return with the above on success and failure
 }
 
 function get_job_count () {
@@ -305,8 +318,10 @@ function item_upgrade () {
 	vault="$1"
 	item="$2"
 	# fetch
+	strict_e_pause; local eo="$?"
 	website="$(opwrap get item --session="$OP_SESSION" --vault "$vault" "$item" - --fields website)"
-	if test "$?" -ne 0; then
+	local ec="$?"; strict_e_restore "$eo"
+	if test "$ec" -ne 0; then
 		echo "[$item] [$website] failed to fetch"
 		return 1
 	fi
@@ -329,8 +344,10 @@ function item_upgrade () {
 	# echo to stdout, as is actionable for user if they are piping
 	echo "[$item] [$website] => [$result]"
 	# apply
+	strict_e_pause; local eo="$?"
 	opwrap edit item --session="$OP_SESSION" --vault "$vault" "$item" website="$result"
-	if test "$?" -ne 0; then
+	local ec="$?"; strict_e_restore "$eo"
+	if test "$ec" -ne 0; then
 		stderr echo "[$item] [$website] failed to save"
 		return 1
 	fi
@@ -338,14 +355,18 @@ function item_upgrade () {
 
 function secret_https() {
 	last="${1-}"
+	strict_e_pause; local eo="$?"
 	vaults="$(opwrap list vaults --session="$OP_SESSION" | jq -r '.[].uuid' | sort || :)"
-	if test "$?" -ne 0 -o -z "$vaults"; then
+	local ec="$?"; strict_e_restore "$eo"
+	if test "$ec" -ne 0 -o -z "$vaults"; then
 		stderr echo "failed to fetch vaults..."
 		return 1
 	fi
 	for vault in $vaults; do
+		strict_e_pause; local eo="$?"
 		items="$(opwrap list items --session="$OP_SESSION" --categories Login --vault "$vault" | jq -r '.[].uuid' | sort || :)"
-		if test "$?" -ne 0 -o -z "$vaults"; then
+		local ec="$?"; strict_e_restore "$eo"
+		if test "$ec" -ne 0 -o -z "$vaults"; then
 			stderr echo "failed to fetch items from vault [$vault]"
 			return 1
 		fi
@@ -381,7 +402,7 @@ function secret_fetch() {
 	vault="$(fetch_vault "${1-}")"
 	item="$(fetch_item "$vault" "${2-}")"
 	fetch_field "$vault" "$item" "${3-}"
-	return "$?"
+	return "$?"  # return with the above on success and failure
 }
 
 function secret_map() {
