shellcheck improvements, among misc fixes
alias-details: don't error color the tab

ask, choose-menu: properly remove `--main` flag

cert: source `strict.bash`

chmod-helper: fix `--partial` argument default to `yes`

choose-option: `local` more variables

cpr: fix `different` tangent detection

echo-eval: no uses the new `echo-color` and makes status code red if failed

echo-exit-code: source `strict.bash`

secret: `envrg` => `envArg`

setup-docker: fix bad cleanup

ssh-ok: rewrote for new exit code convention

tmutil-evict: fix for modern conventions

diff --git a/commands/confirm-bool b/commands/confirm-bool
--- a/commands/confirm-bool
+++ b/commands/confirm-bool
@@ -9,24 +9,24 @@ function confirmer() {
 	local ec
 
 	# timeout one hour
-	echo -en "$@ (y/n) "
+	echo -en "$* (y/n) "
 	answer="$(read-arrow --timeout 3600)" || return "$?"
 
 	# check their answer
-	ec=0; is-affirmative "$answer" || ec="$?"
+	ec=0 && is-affirmative "$answer" || ec="$?"
 	if test "$ec" -lt 2; then
 		return "$ec"
 	elif test "$answer" = 'escape'; then
 		return 1
 	else
 		# ask again
-		echo  # newline, otherwise everything on same line
+		echo # newline, otherwise everything on same line
 		confirmer "$@"
-		return "$?"  # return with the above on success and failure
+		return "$?" # return with the above on success and failure
 	fi
 }
 
 # confirm with the user
-ec=0; confirmer "$@" || ec="$?"
-echo  # newline, as y/n do not
-exit "$ec"  # exit with the result
+ec=0 && confirmer "$@" || ec="$?"
+echo       # newline, as y/n do not
+exit "$ec" # exit with the result
diff --git a/commands/confirm-negative b/commands/confirm-negative
--- a/commands/confirm-negative
+++ b/commands/confirm-negative
@@ -15,8 +15,8 @@ function confirmer() {
 	local ec
 
 	# timeout one minute
-	echo -en "$@ (y/N) "
-	ec=0; answer="$(read-arrow --timeout 60)" || ec="$?"
+	echo -en "$* (y/N) "
+	ec=0 && answer="$(read-arrow --timeout 60)" || ec="$?"
 	if test "$ec" -eq 62; then
 		return 1
 	elif test "$ec" -ne 0; then
@@ -24,20 +24,20 @@ function confirmer() {
 	fi
 
 	# check their answer
-	ec=0; is-affirmative "$answer" || ec="$?"
+	ec=0 && is-affirmative "$answer" || ec="$?"
 	if test "$ec" -lt 2; then
 		return "$ec"
 	elif test "$answer" = 'enter' -o "$answer" = 'escape'; then
 		return 1
 	else
 		# ask again
-		echo  # newline, otherwise everything on same line
+		echo # newline, otherwise everything on same line
 		confirmer "$@"
-		return "$?"  # return with the above on success and failure
+		return "$?" # return with the above on success and failure
 	fi
 }
 
 # confirm with the user
-ec=0; confirmer "$@" || ec="$?"
-echo  # newline, as y/n do not
-exit "$ec"  # exit with the result
+ec=0 && confirmer "$@" || ec="$?"
+echo       # newline, as y/n do not
+exit "$ec" # exit with the result
diff --git a/commands/podvideo b/commands/podvideo
--- a/commands/podvideo
+++ b/commands/podvideo
@@ -6,7 +6,7 @@ function convert {
 	input="$1"
 	output="$(fs-filename "$1")-h264.mp4"
 	echo "converting $input to $output"
-	ffmpeg -i "$input" -c:v libx264 -c:a libfdk_aac "$output" < /dev/null && echo "converted $input to $output" || echo "conversion of $input to $output FAILED"
+	ffmpeg -i "$input" -c:v libx264 -c:a libfdk_aac "$output" </dev/null && echo "converted $input to $output" || echo "conversion of $input to $output FAILED"
 }
 
 if is-empty-string "${1-}"; then
diff --git a/commands/setup-mac b/commands/setup-mac
--- a/commands/setup-mac
+++ b/commands/setup-mac
@@ -28,7 +28,7 @@ fi
 echo
 
 # action
-action="$(choose-option --question='Do you want to install or update this system?' --filter="${1-}" -- 'install' 'update' || echo "${1:-install}")"  # or condition here is for bash v3, which choose-option will fail on, as bash v3 does not yet support arrays
+action="$(choose-option --question='Do you want to install or update this system?' --filter="${1-}" -- 'install' 'update' || echo "${1:-install}")" # or condition here is for bash v3, which choose-option will fail on, as bash v3 does not yet support arrays
 
 # log
 echo -e "\nThe $action of the macOS system has commenced... ⏲"
@@ -37,8 +37,8 @@ echo -e "\nThe $action of the macOS system has commenced... ⏲"
 setup-dorothy "$action"
 
 # mac
-setup-mac-brew "$action"  # setup-util-devel done as part of this
-source "$DOROTHY/sources/environment.sh"  # ensure the updated bash is available to what comes after
+setup-mac-brew "$action"                 # setup-util-devel done as part of this
+source "$DOROTHY/sources/environment.sh" # ensure the updated bash is available to what comes after
 if test "$action" = 'install'; then
 	setup-mac-apps
 	setup-mac-fonts
@@ -66,4 +66,3 @@ if test "$action" = 'install'; then
 	echo ''
 	echo -e "\nAll done. ✅"
 fi
-
