bash v3 compat for essentials
todos:

`if test "$ARRAYS" = 'no'; then` is a no-op now,
as it will only be `yes` or `shim`,
so one should go through such scripts and figure out if the shim is enough,
if the shim is enough, then such check can be removed,
if the shim is not enough, then use:
`if test "$ARRAYS" != 'yes'; then`

notable changes:

- `arrays.bash` adds a `mapfile` shim
- added `shims.bash` with a few shims
- `confirm` now supports `--term=$$` flag for supporting ctrl+c bubbling
- `eval-collapse` will run in a simplified mode under bash v3
- fixed `fs-extension` and `fs-filename` for edge cases

diff --git a/commands/config-helper b/commands/config-helper
--- a/commands/config-helper
+++ b/commands/config-helper
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
+source "$DOROTHY/sources/arrays.bash"
+if test "$ARRAYS" = 'no'; then
+	echo "Array support required for: $0 $*" >/dev/stderr
+	exit 95 # Operation not supported
+fi
 
 # dependencies
 source "$DOROTHY/sources/ripgrep.bash"
@@ -47,7 +52,8 @@ touch "$file"
 mapfile -t lines <"$file"
 
 # cycle through each find and replace pair
-for find_index in "${!find_array[@]}"; do
+# bash v4: for find_index in "${!find_array[@]}"; do
+for ((find_index = 0; find_index < "${#find_array[@]}"; find_index++)); do
 	# prepare
 	find="${find_array[find_index]}"
 	replace="${replace_array[find_index]}"
@@ -57,7 +63,8 @@ for find_index in "${!find_array[@]}"; do
 	results=()
 
 	# cycle through the lines
-	for line in "${lines[@]}"; do
+	# `test ... && for ...` is for bash v3 compatibility
+	test "${#lines[@]}" -ne 0 && for line in "${lines[@]}"; do
 		# check if the lines matches the pattern
 		if prefix="$(rg -qo "$pattern" --replace '$1' <<<"$line")"; then
 			# if not found, add the replacement line to the stack, to be added when we get back to normal lines
diff --git a/commands/setup-environment-commands b/commands/setup-environment-commands
--- a/commands/setup-environment-commands
+++ b/commands/setup-environment-commands
@@ -2,6 +2,11 @@
 # shellcheck disable=SC1091
 source "$DOROTHY/sources/strict.bash"
 source "$DOROTHY/sources/config.sh"
+source "$DOROTHY/sources/arrays.bash"
+if test "$ARRAYS" = 'no'; then
+	echo "Array support required for: $0 $*" >/dev/stderr
+	exit 95 # Operation not supported
+fi
 
 # =====================================
 # Notes
diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -3,6 +3,7 @@
 source "$DOROTHY/sources/strict.bash"
 source "$DOROTHY/sources/arrays.bash"
 if test "$ARRAYS" = 'no'; then
+	echo "Array support required for: $0 $*" >/dev/stderr
 	exit 95 # Operation not supported
 fi
 
@@ -1026,82 +1027,82 @@ function do_aur() {
 # -------------------------------------
 
 # arguments specify the order
-order=("$@")
-if is-array-partial "${order[@]}"; then
+order_defaults=(
+	# intelligent
+	brew
+	cask
+
+	# precompiled
+	pacman
+	apt
+	apk
+	yum # also rpm
+
+	# precompiled containers
+	snap
+
+	# source containers
+	flatpak
+
+	# aur
+	# https://itsfoss.com/paru-aur-helper/
+	# https://itsfoss.com/best-aur-helpers/
+	yay
+	pakku
+	paru
+	aurutils
+	pamac
+
+	# source
+	cargo
+	npm
+	go
+	pip
+	pipx
+	gem
+
+	# unknown
+	cabal
+	choco
+	conda
+	dnf
+	doas
+	dpkg
+	emerge
+	eopkg
+	guix
+	huber
+	nix
+	pkg
+	pkgin
+	pkgman
+	pkgutil
+	port
+	scoop
+	stack
+	winget
+	xbps
+	zypper
+
+	# custom
+	curl
+	zip
+	installer
+	cmd
+)
+# fallback the order to defaults if no custom order provided
+if test "$#" -eq 0; then
+	# ^ bash v3 compat
+	order=("${order_defaults[@]}")
+
+elif is-array-partial "$@"; then
 	stderr cat <<-EOF
 		an invalid order value was present:
 		$(echo-verbose "${order[@]}")
 
 		will set the order to the defaults...
 	EOF
-	order=()
-fi
-
-# fallback the order to defaults if no custom order provided
-if is-array-empty "${order[@]}"; then
-	order=(
-		# intelligent
-		brew
-		cask
-
-		# precompiled
-		pacman
-		apt
-		apk
-		yum # also rpm
-
-		# precompiled containers
-		snap
-
-		# source containers
-		flatpak
-
-		# aur
-		# https://itsfoss.com/paru-aur-helper/
-		# https://itsfoss.com/best-aur-helpers/
-		yay
-		pakku
-		paru
-		aurutils
-		pamac
-
-		# source
-		cargo
-		npm
-		go
-		pip
-		pipx
-		gem
-
-		# unknown
-		cabal
-		choco
-		conda
-		dnf
-		doas
-		dpkg
-		emerge
-		eopkg
-		guix
-		huber
-		nix
-		pkg
-		pkgin
-		pkgman
-		pkgutil
-		port
-		scoop
-		stack
-		winget
-		xbps
-		zypper
-
-		# custom
-		curl
-		zip
-		installer
-		cmd
-	)
+	exit 1
 fi
 
 # cycle through the order
@@ -1116,7 +1117,7 @@ for item in "${order[@]}"; do
 done
 
 # fallback for failed packages which are missing their package system
-for item in "${fallbacks[@]}"; do
+test "${#fallbacks[@]}" -ne 0 && for item in "${fallbacks[@]}"; do
 	pass='y'
 	"do_${item}_fallback" >/dev/tty || pass='n'
 	if test "${pass}" = 'y'; then
