many various improvements
- add `setup-linux-safegraphics`, `update-grub-universal`, `conf-update`
- improve sed usage
- fix `set-hostname`
- remove need for `$DOROTHY/commands/...` on certain scripts
- renamed `sources/env.sh` to `sources/home.sh` to prevent it from being gitignored
- `setup-dns` no longer confirms for backup dns
- `setup-dns` and `select-dns` both output success
- fix `down` file saving
- fix `edit-env` which was still prior `$DOROTHY/user` change

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/confirm-bool b/commands/confirm-bool
--- a/commands/confirm-bool
+++ b/commands/confirm-bool
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
-# don't use strict, as we need exit codes
-# strict mode, will cause exit code of 2 to explode and be exited
+source "$DOROTHY/sources/strict.bash"
 
 # 0=yes
 # 1=no
@@ -27,8 +26,9 @@ function confirmer() {
 	fi
 
 	# check their answer
-	"$DOROTHY/commands/is-affirmative" "$answer"
-	ec="$?"
+	set +e # disable hard fail so we can get the exit code
+	is-affirmative "$answer"; ec="$?"
+	set -e # reenable hard fail
 
 	# check if indeterminate, if so, ask again
 	if test "$ec" -eq 2; then
