improvements to help, sourcing, and fixes
- `ci`:
	- `shellcheck`: ignore `SC2119`, `SC2120`, and add reasons to all ignored rules
	- strip ANSI escape sequences from markdown colours
- `*`:
	- use `__print_help` for all commands that have help
	- add help to more commands
	- use new example conventions
	- `checksum`: help now outputs the algorithms
	- `config-helper`: added missing options to help
	- `contains-line`, `echo-clear-lines`, `echo-count-lines`, `echo-escape-backslashes`, `echo-escape-regexp-replacement`, `echo-fstab-(en|de)code`: corrected examples
	- `debug-bash`: fixed about help text, as it now only injects `-x` if specified
	- `dorothy-config`: corrected examples, added missing options to help
	- `fs-copy`: styled tooling options in help
	- `get-devices`: styled fields in help
	- `git-helper`: fixed bad indentation in help
	- `echo-style`: remove the help for hte removed `bg` and `hi` aliases
- `echo-error`:
    - fixed error message not showing
- `echo-join`, `bash.bash`:
    - removed `__print_join`, now only the more powerful `__join`
    - `echo-join` now delegates to `__join`
    - enhanced `__join` with advanced capabilities to make the above possible
    - `echo-join ', ' a b` will now `22` fail, use `echo-join --between=', ' -- a b`
- `get-devices`:
	- fixed crash from typo in `__join` argument
- `bash.bash`:
    - sourcing `ansi.bash` and `styles.bash` for their functions is now optional, as added `__invoke_function_from_source` to source their implementions automatically
- `styles.bash`
    - `__print_help`
        - fix `[*]`, `<<<`, `<(...)`, `[[ ... ]]`, `[a-z]`
        - support `<http...>`
- deleted `twitter-helper`, Musk killed the API

diff --git a/commands/contains-line b/commands/contains-line
--- a/commands/contains-line
+++ b/commands/contains-line
@@ -7,28 +7,27 @@ function contains_line() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >&2
+		__print_help "$@" <<-EOF || return $?
 			ABOUT:
 			Returns [0] if any <input> line matched a <needle> line, otherwise returns [1].
 
 			USAGE:
-			contains-line <needle> [...options] [--] ...<input>
-			echo-lines ...<input> | contains-line <needle> [...options]
+			\`contains-line <needle> [...options] [--] ...<input>\`
+			\`echo-lines ...<input> | contains-line <needle> [...options]\`
+
+			\`echo-lines -- 'one' 'two' 'three'   | contains-line --needle='two'    # success\`
+			\`echo-lines -- 'one' 'two' 'three'   | contains-line --needle='three'  # success\`
+			\`echo-lines -- 'one' 'two' 'three'   | contains-line --needle='z'      # failure\`
+			\`echo-lines -- 'one' 'two' 'three'   | contains-line --needle=''       # failure\`
+			\`echo-lines -- 'one' ' two' 'three'  | contains-line --needle='two'    # failure\`
+			\`echo-lines -- 'one' '' 'three'      | contains-line --needle=''       # success\`
 
 			OPTIONS:
 			<needle> | --needle=<needle>
 			    Compare each <input> line with this <needle> line.
-			    Use [--needle=<needle>] to provide multiple needles.
+			    Use \`--needle=<needle> ...[--needle=<needle>]\` to provide multiple needles.
 
 			$(__stdinargs__help_options --)
-
-			USAGE:
-			echo-lines -- 'one' 'two' 'three'  | contains-line --needle='two'    # success
-			echo-lines -- 'one' 'two' 'three'  | contains-line --needle='three'  # success
-			echo-lines -- 'one' 'two' 'three'  | contains-line --needle='z'      # failure
-			echo-lines -- 'one' 'two' 'three'  | contains-line --needle=''       # failure
-			echo-lines -- 'one' ' two' 'three'  | contains-line --needle='two'   # failure
-			echo-lines -- 'one' '' 'three'  | contains-line --needle=''          # success
 
 			RETURNS:
 			[0] if ANY <input> line are a <needle> line.
@@ -37,9 +36,6 @@ function contains_line() (
 			QUIRKS:
 			Lines will not contain their trailing newline characters (if any) when compared.
 		EOF
-		if [[ $# -ne 0 ]]; then
-			__print_error "$@"
-		fi
 		return 22 # EINVAL 22 Invalid argument
 	}
 
