contains-line: modern conventions, stdinargs redo
stdinargs changes:

- `noact` is now `no_args_nor_stdin`
- `line` is fallback for `inline`
- add `no_stdin` and `no_args`
- cleaner code
- `require_stdin` option

These changes allow more robust usage, such as using args and stdin, in the case of `contains-lineq

diff --git a/commands/contains-line b/commands/contains-line
--- a/commands/contains-line
+++ b/commands/contains-line
@@ -3,23 +3,53 @@ source "$DOROTHY/sources/strict.bash"
 
 # @todo: what is the different between contains-string, contains-word, contains-line?
 
-# help
-if is-help "$@"; then
+function help() {
 	cat <<-EOF >/dev/stderr
 		ABOUT:
-		If input contains line exit 0, else exit with 1.
+		Checks whether the <line> is contained in stdin.
+
+		USAGE:
+		printf 'one\ntwo\nthree'   | contains-line 'two'      # success
+		printf 'one\ntwo\nthree'   | contains-line 'three'    # success
+		printf 'one\n\nthree\n'    | contains-line ''         # success
+		printf 'one\ntwo\nthree\n' | contains-line ''         # failure
+
+		RETURNS:
+		[0] if the line is contained in stdin.
+		[1] if the line is not contained in stdin.
 	EOF
-	# if test "$#" -ne 0; then
-	# 	echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
-	# fi
-	return 22 # Invalid argument
-fi
-
-while read -r line; do
-	if test "$line" = "$1"; then
-		exit 0
-		break
+	if test "$#" -ne 0; then
+		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
 	fi
-done <&0
+	return 22 # Invalid argument
+}
 
-exit 1
+option_line=''
+function arg {
+	if test -z "$option_line"; then
+		option_line="$1"
+	else
+		help "An unrecognised argument was provided: $1"
+	fi
+}
+function line {
+	if test "$1" = "$option_line"; then
+		# it was found, success case, exit immediately
+		exit 0
+	fi
+	# not found, continue reading
+}
+function finish {
+	# it was not found, failure case
+	return 1
+}
+
+export require_stdin='yes'
+function no_args {
+	help "Missing <line> argument."
+}
+function no_stdin {
+	help "Missing STDIN to check the <line> against." || :
+	return 96 # ENODATA 96 No message available on STREAM
+}
+source "$DOROTHY/sources/stdinargs.bash"
