cpr: ask for action first, then tool, this results in a better and smarter experience

diff --git a/commands/cpr b/commands/cpr
--- a/commands/cpr
+++ b/commands/cpr
@@ -5,64 +5,68 @@ source "$DOROTHY/sources/strict.bash"
 _remote="${1:?"USAGE: env [TOOL] [ACTION] cpr <REMOTE> <DESTINATION>"}"
 _destination="${2:?"USAGE: env [TOOL] [ACTION] cpr <remote> <DESTINATION>"}"
 
-# tool
+# Prepare
+actions=(
+	copy
+	verify
+)
+flags=()
 tools=()
-if command-exists rsync; then
-	tools+=(rsync)
+
+# Determine action
+echo 'Which action do you wish to take?'
+action="${ACTION:-"$(choose "${actions[@]}")"}"
+if ! is-needle "$action" "${actions[@]}"; then
+	stderr echo "invalid action [$action], the action must be one of these:"
+	stderr echo-lines "${actions[@]}"
+	exit 1
 fi
-if command-exists gcp; then
-	tools+=(gcp)
+
+# Determine available tools for the action
+if test "$action" = 'verify'; then
+	if command-exists rsync; then
+		tools+=(rsync)
+	fi
+	if command-exists diff; then
+		tools+=(diff)
+	fi
+	if command-exists git; then
+		tools+=(git)
+	fi
+elif test "$action" = 'copy'; then
+	if command-exists rsync; then
+		tools+=(rsync)
+	fi
+	if command-exists gcp; then
+		tools+=(gcp)
+	fi
+	if command-exists scp; then
+		tools+=(scp)
+	fi
+	if command-exists cp; then
+		tools+=(cp)
+	fi
+else
+	stderr echo "unkown action, available actions are:"
+	stderr echo-lines "${actions[@]}"
+	exit 1
 fi
-if command-exists scp; then
-	tools+=(scp)
-fi
-if command-exists cp; then
-	tools+=(cp)
-fi
-if command-exists diff; then
-	tools+=(diff)
-fi
-if command-exists git; then
-	tools+=(git)
-fi
+
+# Determine tool
 echo 'Which tool do you wish to use?'
 tool="${TOOL:-"$(choose "${tools[@]}")"}"
-
-# verify
-if test "$tool" = 'diff' -o "$tool" = 'git'; then
-	action='verify only'
-else
-	actions=()
-	if test "$tool" = 'rsync'; then
-		actions=(
-			'copy then verify'
-			'copy only'
-			'verify only'
-		)
-	else
-		actions=(
-			'copy then verify'
-			'copy only'
-		)
-	fi
-	echo 'Which action do you wish to take?'
-	action="${ACTION:-"$(choose "${actions[@]}")"}"
+if ! is-needle "$tool" "${tools[@]}"; then
+	stderr echo "invalid tool [$tool] for the action [$action], the tool must be one of these:"
+	stderr echo-lines "${tools[@]}"
+	exit 1
 fi
-
-# prepare
-flags=()
-# if test -d "${_destination}"; then
-# 	if confirm-bool "Destination directory [${_destination}] exists, confirm its deletion"; then
-# 		rm -Rf "${_destination}"
-# 	fi
-# fi
 
 # action
 if test "$tool" = 'rsync'; then
 	# via rsync, file by file progress
 
 	# verify
-	if test "$action" = 'verify only'; then
+	if test "$action" = 'verify'; then
 		# -i, --itemize-changes       output a change-summary for all updates
 		flags+=('--itemize-changes')
 		# -n, --dry-run               show what would have been transferred
@@ -114,16 +118,11 @@ if test "$tool" = 'rsync'; then
 	echo rsync "${flags[@]}" "${_remote}" "${_destination}"
 	rsync "${flags[@]}" "${_remote}" "${_destination}"
 
-	# repeat
-	if test "$action" = 'copy then verify'; then
-		env ACTION='verify only' cpr "${_remote}" "${_destination}"
-	fi
-
 elif test "$tool" = 'gcp'; then
 	# via gcp, overall progress
 
 	# verify
-	if test "$action" = 'verify only'; then
+	if test "$action" = 'verify'; then
 		stderr echo 'verify not supported with gcp'
 		exit 1
 	fi
@@ -141,16 +140,11 @@ elif test "$tool" = 'gcp'; then
 	echo gcp "${flags[@]}" "${_remote}" "${_destination}"
 	gcp "${flags[@]}" "${_remote}" "${_destination}"
 
-	# repeat
-	if test "$action" = 'copy then verify'; then
-		env ACTION='verify only' cpr "${_remote}" "${_destination}"
-	fi
-
 elif test "$tool" = 'scp'; then
 	# via scp
 
 	# verify
-	if test "$action" = 'verify only'; then
+	if test "$action" = 'verify'; then
 		stderr echo 'verify not supported with scp'
 		exit 1
 	fi
@@ -168,16 +162,11 @@ elif test "$tool" = 'scp'; then
 	echo scp "${flags[@]}" "${_remote}" "${_destination}"
 	scp "${flags[@]}" "${_remote}" "${_destination}"
 
-	# repeat
-	if test "$action" = 'copy then verify'; then
-		env ACTION='verify only' cpr "${_remote}" "${_destination}"
-	fi
-
 elif test "$tool" = 'cp'; then
 	# via cp
 
 	# verify
-	if test "$action" = 'verify only'; then
+	if test "$action" = 'verify'; then
 		stderr echo 'verify not supported with cp'
 		exit 1
 	fi
@@ -202,11 +191,6 @@ elif test "$tool" = 'cp'; then
 	# run
 	echo cp "${flags[@]}" "${_remote}" "${_destination}"
 	cp "${flags[@]}" "${_remote}" "${_destination}"
-
-	# repeat
-	if test "$action" = 'copy then verify'; then
-		env ACTION='verify only' cpr "${_remote}" "${_destination}"
-	fi
 
 elif test "$tool" = 'diff'; then
 
