cpr: signficant usability improvements
- if using rsync to copy with a remote that is locally mounted, then provide alternatives as that is slow

- if ACTION/TOOL provided, don't output question

- remove unnecessary {}

diff --git a/commands/cpr b/commands/cpr
--- a/commands/cpr
+++ b/commands/cpr
@@ -14,12 +14,15 @@ flags=()
 tools=()
 
 # Determine action
-echo 'Which action do you wish to take?'
-action="${ACTION:-"$(choose "${actions[@]}")"}"
+action="${ACTION-}"
 if ! is-needle "$action" "${actions[@]}"; then
-	stderr echo "invalid action [$action], the action must be one of these:"
-	stderr echo-lines "${actions[@]}"
-	exit 1
+	echo 'Which action do you wish to take?'
+	action="$(choose "${actions[@]}")"
+	if ! is-needle "$action" "${actions[@]}"; then
+		stderr echo "invalid action [$action], the action must be one of these:"
+		stderr echo-lines "${actions[@]}"
+		exit 1
+	fi
 fi
 
 # Determine available tools for the action
@@ -53,13 +56,40 @@ else
 fi
 
 # Determine tool
-echo 'Which tool do you wish to use?'
-tool="${TOOL:-"$(choose "${tools[@]}")"}"
+tool="${TOOL-}"
 if ! is-needle "$tool" "${tools[@]}"; then
-	stderr echo "invalid tool [$tool] for the action [$action], the tool must be one of these:"
-	stderr echo-lines "${tools[@]}"
-	exit 1
+	echo 'Which tool do you wish to use?'
+	tool="$(choose "${tools[@]}")"
+	if ! is-needle "$tool" "${tools[@]}"; then
+		stderr echo "invalid tool [$tool] for the action [$action], the tool must be one of these:"
+		stderr echo-lines "${tools[@]}"
+		exit 1
+	fi
 fi
+
+function rethink {
+	suggestion="$(get-local-to-remote "$1" || echo '')"
+	if test -n "$suggestion"; then
+		echo 'Using rsync with a remote directory that is mounted locally can be slow, you should probably try converting it to a local mount point.'
+		echo
+		echo "$suggestion"
+		echo
+		echo 'Alternatively, select copy via a different tool, as they can be faster are more reliable under these circumstances.'
+		echo ''
+		echo 'What would you like to do?'
+		tangent="$(choose 'rethink and exit' 'ignore suggestion and continue anyway' 'try a different tool')"
+		if [[ "$tangent" = *'exit'* ]]; then
+			return 1
+		elif [[ "$tangent" = *'ignore'* ]]; then
+			echo 'Continuing as is...'
+			return 0
+		elif [[ "$tangent" = *'different'* ]]; then
+			env TOOL='' ACTION="$action" cpr "$_remote" "$_destination"
+			return $?
+		fi
+	fi
+	return 0
+}
 
 # action
 if test "$tool" = 'rsync'; then
@@ -71,6 +101,10 @@ if test "$tool" = 'rsync'; then
 		flags+=('--itemize-changes')
 		# -n, --dry-run               show what would have been transferred
 		flags+=('--dry-run')
+	else
+		# check if remote and destination are locally mounted remote folders
+		rethink "$_remote"
+		rethink "$_destination"
 	fi
 
 	# --archive, -a: archive mode; equals -rlptgoD (no -H,-A,-X)
@@ -115,8 +149,8 @@ if test "$tool" = 'rsync'; then
 	fi
 
 	# run
-	echo rsync "${flags[@]}" "${_remote}" "${_destination}"
-	rsync "${flags[@]}" "${_remote}" "${_destination}"
+	echo rsync "${flags[@]}" "$_remote" "$_destination"
+	rsync "${flags[@]}" "$_remote" "$_destination"
 
 elif test "$tool" = 'gcp'; then
 	# via gcp, overall progress
@@ -137,8 +171,8 @@ elif test "$tool" = 'gcp'; then
 	flags+=('--verbose')
 
 	# run
-	echo gcp "${flags[@]}" "${_remote}" "${_destination}"
-	gcp "${flags[@]}" "${_remote}" "${_destination}"
+	echo gcp "${flags[@]}" "$_remote" "$_destination"
+	gcp "${flags[@]}" "$_remote" "$_destination"
 
 elif test "$tool" = 'scp'; then
 	# via scp
@@ -159,8 +193,8 @@ elif test "$tool" = 'scp'; then
 	flags+=('-r')
 
 	# run
-	echo scp "${flags[@]}" "${_remote}" "${_destination}"
-	scp "${flags[@]}" "${_remote}" "${_destination}"
+	echo scp "${flags[@]}" "$_remote" "$_destination"
+	scp "${flags[@]}" "$_remote" "$_destination"
 
 elif test "$tool" = 'cp'; then
 	# via cp
@@ -189,8 +223,8 @@ elif test "$tool" = 'cp'; then
 	flags+=('-v')
 
 	# run
-	echo cp "${flags[@]}" "${_remote}" "${_destination}"
-	cp "${flags[@]}" "${_remote}" "${_destination}"
+	echo cp "${flags[@]}" "$_remote" "$_destination"
+	cp "${flags[@]}" "$_remote" "$_destination"
 
 elif test "$tool" = 'diff'; then
 
@@ -201,8 +235,8 @@ elif test "$tool" = 'diff'; then
 	flags+=('--recursive')
 
 	# run
-	echo diff "${flags[@]}" "${_remote}" "${_destination}"
-	diff "${flags[@]}" "${_remote}" "${_destination}"
+	echo diff "${flags[@]}" "$_remote" "$_destination"
+	diff "${flags[@]}" "$_remote" "$_destination"
 
 elif test "$tool" = 'git'; then
 
@@ -210,8 +244,8 @@ elif test "$tool" = 'git'; then
 	flags+=('--no-index')
 
 	# run
-	echo git diff "${flags[@]}" "${_remote}" "${_destination}"
-	git diff "${flags[@]}" "${_remote}" "${_destination}"
+	echo git diff "${flags[@]}" "$_remote" "$_destination"
+	git diff "${flags[@]}" "$_remote" "$_destination"
 
 else
 
