cpr: confirm if trailing slashes are not present
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/cpr b/commands/cpr
--- a/commands/cpr
+++ b/commands/cpr
@@ -3,8 +3,6 @@ source "$DOROTHY/sources/strict.bash"
 
 # @todo figure out how to make --eval compatible with paths that have spaces
 
-# @todo warn if given a directory without the trailing slash, as that will not move contents, but move inside
-
 # copy everything from one location to another preserving properties
 if is-help "$@"; then
 	stderr echo "USAGE:"
@@ -19,10 +17,11 @@ if is-help "$@"; then
 	stderr echo "FLAGS:"
 	stderr echo "Provide [--tool=...] to skip tool prompt."
 	stderr echo "Provide [--action=...] to skip action prompt."
-	stderr echo "Provide [--checksum] to use checksum with rsync instead of the default file size and mod time."
+	stderr echo "Provide [--checksum] to have rsync compare by checksum instead of by the default of file size and mod time."
 	stderr echo "Provide [--remove] to have rsync remove source files as they are copied over."
 	stderr echo "Provide [--eval] to echo the command that would otherwise run, so that you can call it instead."
 	stderr echo "Provide [--sudo] to have the command run as sudo."
+	stderr echo "Provide [--no-confirm] to continue without trailing slashes if they are missing."
 	exit 1
 fi
 
@@ -37,6 +36,30 @@ _remove="$(get-flag-value remove -- "${options[@]}")"
 _sudo="$(get-flag-value sudo -- "${options[@]}")"
 _eval="$(get-flag-value 'eval' -- "${options[@]}")"
 _checksum="$(get-flag-value checksum -- "${options[@]}")"
+_confirm="$(get-flag-value confirm -- "${options[@]}")"
+
+# warn if given paths without trailing slashes
+if test "${_source:(-1)}" != '/' -o "${_destination:(-1)}" != '/'; then
+	if test "$_confirm" != 'no'; then
+		confirm="$(choose-option --question="You have provided paths that do not have trailing slashes:\nsource: ${_source}\ndestination: ${_destination}\n\nThis is fine if they are files, however if they are directories, this means the source directory will go inside the destination directory. Using trailing slashes to ensure that the contents of the source directory go inside the destination directory.\n\nWhat do you want to do?" -- 'add trailing slashes' 'ignore trailing slashes (they are files)' 'exit and rethink')"
+		if [[ "$confirm" = *'add'* ]]; then
+			echo 'adjusted:' > /dev/tty
+			if test "${_source:(-1)}" != '/'; then
+				_source="${_source}/"
+				echo "source: $_source" > /dev/tty
+			fi
+			if test "${_destination:(-1)}" != '/'; then
+				_destination="${_destination}/"
+				echo "destination: $_destination" > /dev/tty
+			fi
+		elif [[ "$confirm" = *'ignore'* ]]; then
+			echo 'ignoring'
+		else
+			exit 1
+		fi
+		sleep 5
+	fi
+fi
 
 # Prepare
 actions=(
