inline `echo-style` as `__print_style`
- `edit`: fix error if no editors
- `is-bash-version-outdated`: better verbose and tests
- `dorothy-internals`: no longer only do `__iterate` tests under certain conditions as performance is now good enough we test it under all conditions

/ref
- dad7055f06d81f7a8cd6231dbb998b8bf6fbf555
- ab3dc085c1abd04855c7264eedab305f968a9a60
- 1ffa88614ab3f3a24960a8a197e4219bbc03a658
- a2bc96f638f44715cadb994123c0d8af477b97f9

diff --git a/commands/debug-bash b/commands/debug-bash
--- a/commands/debug-bash
+++ b/commands/debug-bash
@@ -33,7 +33,7 @@ function debug_bash() (
 			    The command to run.
 		EOF
 		if [[ $# -ne 0 ]]; then
-			echo-error "$@"
+			__print_error "$@"
 		fi
 		return 22 # EINVAL 22 Invalid argument
 	}
@@ -105,7 +105,7 @@ function debug_bash() (
 		{
 			type -pa bash || :
 			expand-path -- "$XDG_BIN_HOME/bash-*" || :
-		} | echo-unique --stdin
+		} | echo-unique --stdin || return
 	}
 
 	# determine bash binaries
@@ -115,19 +115,19 @@ function debug_bash() (
 	fi
 	for bash_input in "${option_bash_binaries[@]}"; do
 		if [[ $bash_input == 'all' ]]; then
-			setup-util-bash --all-versions
+			setup-util-bash --all-versions || return
 			__split --target={bash_binaries} --no-zero-length --invoke -- \
-				__get_all_bash_binaries
+				__get_all_bash_binaries || return
 			continue
 		elif [[ $bash_input == 'all-versions' ]]; then
 			# install all versions, and use all binaries
-			setup-util-bash --all-versions
+			setup-util-bash --all-versions || return
 			__split --target={bash_binaries} --no-zero-length --invoke -- \
-				__get_all_bash_binaries
+				__get_all_bash_binaries || return
 			continue
 		elif [[ $bash_input == 'all-binaries' ]]; then
 			__split --target={bash_binaries} --no-zero-length --invoke -- \
-				__get_all_bash_binaries
+				__get_all_bash_binaries || return
 			continue
 		fi
 		# convert version to executable
@@ -148,7 +148,7 @@ function debug_bash() (
 		fi
 		# add binary path or note failure
 		if [[ -z $bash_binary ]]; then
-			echo-style --error='The bash binary ' --code="$bash_input" ' does not exist.'
+			__print_style --error='The bash binary ' --path="$bash_input" --error=' does not exist.' || return
 			__exit_status=2 # ENOENT 2 No such file or directory
 			continue
 		elif command-working -- "$bash_binary"; then # will output a error if it fails
@@ -159,7 +159,7 @@ function debug_bash() (
 	done
 	__unique --source+target={bash_binaries}
 	if [[ $option_only_print_binaries == 'yes' ]]; then
-		__print_lines "${bash_binaries[@]}"
+		__print_lines "${bash_binaries[@]}" || return
 		return "$__exit_status"
 	fi
 
diff --git a/commands/secret b/commands/secret
--- a/commands/secret
+++ b/commands/secret
@@ -108,7 +108,7 @@ function secret_() (
 			    Output this help message.
 		EOF
 		if [[ $# -ne 0 ]]; then
-			echo-error "$@"
+			__print_error "$@"
 		fi
 		return 22 # EINVAL 22 Invalid argument
 	}
@@ -255,7 +255,7 @@ function secret_() (
 			__print_string "$value" >"$state/$key" || return
 			__correct_key_permission "$state/$key" || return
 		else
-			echo-error "Attempted to write an empty secret key [$key]" || return
+			__print_error "Attempted to write an empty secret key [$key]" || return
 			return 1
 		fi
 	}
@@ -266,12 +266,12 @@ function secret_() (
 			if is-value -- "$value"; then
 				__print_string "$value" || return
 			else
-				echo-error "Cached secret key [$key] was empty [$value]" || return
+				__print_error "Cached secret key [$key] was empty [$value]" || return
 				__cache_delete "$key" || return
 				return 1
 			fi
 		else
-			echo-error "Cached secret key [$key] was missing." || return
+			__print_error "Cached secret key [$key] was missing." || return
 			return 1
 		fi
 	}
@@ -293,7 +293,7 @@ function secret_() (
 			for key in "$@"; do
 				__do --redirect-status={status} --redirect-stdout={value} -- __secret_get "$key" || return
 				if [[ $status -ne 0 ]]; then
-					echo-error "Unable to fetch the secret key [$key] of many." || return
+					__print_error "Unable to fetch the secret key [$key] of many." || return
 					return 1
 				fi
 				__print_lines "$key=$value" || return
@@ -305,7 +305,7 @@ function secret_() (
 			__split --target={secrets} --no-zero-length --invoke=try -- \
 				jq -r 'keys_unsorted[]' "$database" || return
 			if [[ ${#secrets[@]} -eq 0 ]]; then
-				echo-error 'No secrets are mapped yet, run [secret map] to map a secret.' || return
+				__print_error 'No secrets are mapped yet, run [secret map] to map a secret.' || return
 				return 6 # ENXIO 6 Device not configured
 			fi
 			__split --target={choices} --no-zero-length --invoke -- \
@@ -331,7 +331,7 @@ function secret_() (
 		if is-value -- "$vault" "$item" "$field"; then
 			value="$(__fetch_field "$vault" "$item" "$field")"
 		else
-			echo-error "Key [$key] was missing all three parts of its mapping:" || return
+			__print_error "Key [$key] was missing all three parts of its mapping:" || return
 			cat <<-EOF >&2
 				vault = [$vault]
 				item  = [$item]
@@ -343,7 +343,7 @@ function secret_() (
 			return 1
 		fi
 		if is-empty-value -- "$value"; then
-			echo-error "Key [$key] failed to resolve." || return
+			__print_error "Key [$key] failed to resolve." || return
 			return 1
 		fi
 		__cache_write "$key" "$value" || return
@@ -416,8 +416,7 @@ function secret_() (
 						op signin "$OP_SUBDOMAIN" "$email" "$key" --raw || return
 				fi
 				if [[ $status -ne 0 ]]; then
-					echo-error \
-						"Failed to sign into [$OP_SUBDOMAIN] via the email [$email] and account key [$key]." --newline \
+					__print_error "Failed to sign into [$OP_SUBDOMAIN] via the email [$email] and account key [$key]." --newline \
 						"STATUS = [$status]" --newline \
 						"OP_SESSION = [$OP_SESSION]" || return
 					return "$status"
@@ -444,7 +443,7 @@ function secret_() (
 		__do --redirect-status={status} --redirect-output={result} -- "${cmd[@]}" || return
 		if [[ $status -ne 0 || $result == '[ERROR]'* ]]; then
 			if [[ $result =~ (signed in|session expired) ]]; then
-				echo-style --tty --notice='Session expired. Logging in...' || return
+				__print_style --tty --notice='Session expired. Logging in...' || return
 				__do --redirect-stdout=TTY -- __secret_signin || return
 				__op_wrap "$@" || return
 				return 0
@@ -534,7 +533,7 @@ function secret_() (
 		__split --target={tuples} --no-zero-length --invoke=try -- \
 			__op_grab || return
 		if [[ ${#tuples[@]} -eq 0 ]]; then
-			echo-error 'Failed to fetch vault:' --newline --="$(__dump vault)" || return
+			__print_error 'Failed to fetch vault:' --newline --="$(__dump vault)" || return
 			return 1
 		fi
 
@@ -552,7 +551,7 @@ function secret_() (
 		__split --target={tuples} --no-zero-length --invoke=try -- \
 			__op_grab "$vault" || return
 		if [[ ${#tuples[@]} -eq 0 ]]; then
-			echo-error 'Failed to fetch item:' --newline --="$(__dump vault item)" || return
+			__print_error 'Failed to fetch item:' --newline --="$(__dump vault item)" || return
 			return 1
 		fi
 
@@ -576,7 +575,7 @@ function secret_() (
 		__split --target={tuples} --no-zero-length --invoke=try -- \
 			__op_grab "$vault" "$item" || return
 		if [[ ${#tuples[@]} -eq 0 ]]; then
-			echo-error 'Failed to fetch field:' --newline --="$(__dump vault item field)" || return
+			__print_error 'Failed to fetch field:' --newline --="$(__dump vault item field)" || return
 			return 1
 		fi
 
@@ -607,29 +606,29 @@ function secret_() (
 		# fetch
 		__do --redirect-status={status} --redirect-stdout={website} -- __get_website "$vault" "$item" || return
 		if [[ $status -ne 0 ]]; then
-			echo-style --stderr --error="[$item] [$website] failed to fetch" || return
+			__print_style --stderr --error="[$item] [$website] failed to fetch" || return
 			return 1
 		fi
 		if [[ -z $website ]]; then
-			echo-style --stderr --dim="[$item] no url to upgrade" || return
+			__print_style --stderr --dim="[$item] no url to upgrade" || return
 			return 0
 		fi
 
 		# upgrade
 		result="$(get-url-upgrade "$website" 2>/dev/null || :)" || return
 		if [[ -z $result ]]; then
-			echo-style --stderr --warning="[$item] [$website] unresponsive, consider archiving" || return
+			__print_style --stderr --warning="[$item] [$website] unresponsive, consider archiving" || return
 			return 1
 		fi
 
 		# check if changed
 		if [[ $result == "$website" ]]; then
-			echo-style --stderr --dim="[$item] [$website] already upgraded" || return
+			__print_style --stderr --dim="[$item] [$website] already upgraded" || return
 			return 0
 		fi
 
 		# log
-		echo-style --stderr --success="[$item] [$website] => [$result]" || return
+		__print_style --stderr --success="[$item] [$website] => [$result]" || return
 
 		# apply
 		if [[ $op_version -eq 2 ]]; then
@@ -638,7 +637,7 @@ function secret_() (
 			__try {status} -- __op_wrap edit item "$item" --vault "$vault" website="$result" || return
 		fi
 		if [[ $status -ne 0 ]]; then
-			echo-style --stderr --error="[$item] [$website] failed to save" || return
+			__print_style --stderr --error="[$item] [$website] failed to save" || return
 			return 1
 		fi
 	}
@@ -663,13 +662,13 @@ function secret_() (
 		local last="${1-}" status vault item
 		__do --redirect-status={status} --redirect-stdout={vaults} -- __get_vaults || return
 		if [[ $status -ne 0 || -z $vaults ]]; then
-			echo-error "Failed to fetch vaults..."
+			__print_error "Failed to fetch vaults..."
 			return 1
 		fi
 		for vault in $vaults; do
 			__do --redirect-status={status} --redirect-stdout={items} -- __get_items "$vault" || return
 			if [[ $status -ne 0 || -z $items ]]; then
-				echo-style --stderr --warning="Failed to fetch items for vault [$vault]" || return
+				__print_style --stderr --warning="Failed to fetch items for vault [$vault]" || return
 				continue
 			fi
 			# ignoring of status code is in case it returned a vault we don't have write access to
@@ -681,7 +680,7 @@ function secret_() (
 						last=''
 					else
 						# continue skipping
-						echo-style --stderr --dim="[$item] skipping" || return
+						__print_style --stderr --dim="[$item] skipping" || return
 						continue
 					fi
 				fi
@@ -694,11 +693,11 @@ function secret_() (
 
 		# wait for completed jobs, then note completion
 		while [[ "$(__get_job_count)" -ne 0 ]]; do
-			echo-style --tty --notice="Waiting on [$(__get_job_count)] jobs..." || return
+			__print_style --tty --notice="Waiting on [$(__get_job_count)] jobs..." || return
 			sleep 3
 			jobs &>/dev/null # for some reason, this seems necessary to prevent hung jobs
 		done
-		echo-style --stderr --success='All done.' || return
+		__print_style --stderr --success='All done.' || return
 	}
 
 	function __secret_fetch {
diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -17,9 +17,9 @@ function setup_util() (
 	fi
 
 	# helpers
-	function maybe_echo_style {
+	function __maybe_style {
 		if [[ $option_quiet != 'yes' ]]; then
-			echo-style "$@"
+			__print_style "$@" || return
 		fi
 	}
 
@@ -124,7 +124,7 @@ function setup_util() (
 		if __command_exists -- deno; then
 			installer_options="$(echo-regexp -smgf '.+# <installer-options>\s+|\s+# </installer-options>.+|\t|local ' '' <"${BASH_SOURCE[0]}")"
 		else
-			installer_options="$(echo-style --notice='[deno] is required to display the installer options, install with [setup-util-deno]')"
+			installer_options="$(__print_style --notice='[deno] is required to display the installer options, install with [setup-util-deno]')"
 		fi
 
 		# output the help
@@ -224,7 +224,7 @@ function setup_util() (
 			        CARGO='bottom'
 		EOF
 		if [[ $# -ne 0 ]]; then
-			echo-error "$@" $'\nFailed invocation: ' --code="$invocation"
+			__print_error "$@" $'\nFailed invocation: ' --code="$invocation"
 		fi
 		return 22 # EINVAL 22 Invalid argument
 	}
@@ -462,10 +462,10 @@ function setup_util() (
 
 	# prep terminal vars
 	local use_alt_screen_buffer alternative_screen_buffer default_screen_buffer
-	if [[ $option_quiet != 'no' ]] && get-terminal-alternative-support --quiet; then
+	if [[ $option_quiet != 'no' && $ALTERNATIVE_SCREEN_BUFFER_SUPPORTED == 'yes' ]]; then
 		use_alt_screen_buffer='yes'
 		source "$DOROTHY/sources/styles.bash"
-		refresh_style_cache -- alternative_screen_buffer default_screen_buffer
+		__refresh_style_cache -- alternative_screen_buffer default_screen_buffer
 		alternative_screen_buffer="$style__alternative_screen_buffer"
 		default_screen_buffer="$style__default_screen_buffer"
 	else
@@ -519,7 +519,7 @@ function setup_util() (
 			# missing, nothing installed
 			if [[ $option_action == 'uninstall' ]]; then
 				# nothing installed, so no need to uninstall
-				__do --redirect-stdout=TTY -- maybe_echo_style --good3="The [$option_name] utility was not found. Already uninstalled. ✅"
+				__do --redirect-stdout=TTY -- __maybe_style --good3="The [$option_name] utility was not found. Already uninstalled. ✅"
 				# exit
 				return 0
 			fi
@@ -531,7 +531,7 @@ function setup_util() (
 			# note that we aren't upgrading, which is used for logging
 			option_upgrade='no'
 			# perform install
-			__do --redirect-stdout=TTY -- maybe_echo_style --header3="The [$option_name] utility was not found. Installing automatically... ⏲"
+			__do --redirect-stdout=TTY -- __maybe_style --header3="The [$option_name] utility was not found. Installing automatically... ⏲"
 		elif [[ $option_action == 'uninstall' ]]; then
 			# exists, uninstall enabled, want to uninstall
 			if [[ $option_check == 'yes' ]]; then
@@ -541,7 +541,7 @@ function setup_util() (
 			# note that we aren't upgrading, which is used for logging
 			option_upgrade='no'
 			# perform uninstall
-			__do --redirect-stdout=TTY -- maybe_echo_style --header3="The [$option_name] utility is marked for uninstall. Uninstalling... ⏲"
+			__do --redirect-stdout=TTY -- __maybe_style --header3="The [$option_name] utility is marked for uninstall. Uninstalling... ⏲"
 		elif [[ $option_upgrade == 'yes' ]]; then
 			# exists, upgrade enabled, want to upgrade
 			if [[ $option_check == 'yes' ]]; then
@@ -549,7 +549,7 @@ function setup_util() (
 				return 1
 			fi
 			# perform upgrade
-			__do --redirect-stdout=TTY -- maybe_echo_style --header3="The [$option_name] utility is marked for upgrade. Upgrading... ⏲"
+			__do --redirect-stdout=TTY -- __maybe_style --header3="The [$option_name] utility is marked for upgrade. Upgrading... ⏲"
 		elif [[ $is_working == 'no' ]]; then
 			# exists, not working, want to fix
 			if [[ $option_check == 'yes' ]]; then
@@ -557,10 +557,10 @@ function setup_util() (
 				return 1
 			fi
 			# perform reinstall
-			__do --redirect-stdout=TTY -- maybe_echo_style --header3="The [$option_name] utility via [$option_cli] is misbehaving. Reinstalling automatically... ⏲"
+			__do --redirect-stdout=TTY -- __maybe_style --header3="The [$option_name] utility via [$option_cli] is misbehaving. Reinstalling automatically... ⏲"
 		elif [[ $is_working == 'yes' ]]; then
 			# exists, no upgrade, is working, no action necessary
-			__do --redirect-stdout=TTY -- maybe_echo_style --good3="The [$option_name] utility is already installed. ✅"
+			__do --redirect-stdout=TTY -- __maybe_style --good3="The [$option_name] utility is already installed. ✅"
 			return 0
 		else
 			# exists, don't care, proceed anyway
@@ -634,7 +634,7 @@ function setup_util() (
 
 		# verify
 		if is-missing -- "$path"; then
-			echo-style --stderr --error1='Failed to install: ' --code-error1="$path"
+			__print_style --stderr --error1='Failed to install: ' --code-error1="$path"
 			return 1
 		fi
 
@@ -655,7 +655,7 @@ function setup_util() (
 		fi
 
 		# failure
-		echo-style --stderr --error1='Failed to verify: ' --code-error1="$path"
+		__print_style --stderr --error1='Failed to verify: ' --code-error1="$path"
 		# remove so it doesn't interfere with other install methods and other processes
 		rm_helper "$path"
 		# return failure
@@ -1392,7 +1392,7 @@ function setup_util() (
 			if [[ -z $id ]]; then
 				if [[ ${#packages[@]} -gt 1 ]]; then
 					cat <<-EOF >&2
-						$(echo-style --error="If APT has multiple packages, then APT_ID must be specified.")
+						$(__print_style --error="If APT has multiple packages, then APT_ID must be specified.")
 
 						APT: ${packages[*]}
 					EOF
@@ -1407,7 +1407,7 @@ function setup_util() (
 		if [[ -n $key ]]; then
 			if [[ -z $repo ]]; then
 				cat <<-EOF >&2
-					$(echo-style --error="When APT_KEY is set, APT_REPO must also be set.")
+					$(__print_style --error="When APT_KEY is set, APT_REPO must also be set.")
 
 					APT: ${packages[*]}
 				EOF
@@ -1415,8 +1415,8 @@ function setup_util() (
 			fi
 			if [[ $repo != *'signed-by'* ]]; then
 				cat <<-EOF >&2
-					$(echo-style --error="When APT_KEY is set, APT_REPO must contain:")
-					$(echo-style --code="deb [signed-by={KEY}] https://...")
+					$(__print_style --error="When APT_KEY is set, APT_REPO must contain:")
+					$(__print_style --code="deb [signed-by={KEY}] https://...")
 
 					APT: ${packages[*]}
 					APT_REPO: $repo
@@ -1429,8 +1429,8 @@ function setup_util() (
 		if [[ -n $repo && $repo == 'deb '* ]]; then
 			if [[ $repo != *'arch={ARCH}'* ]]; then
 				cat <<-EOF >&2
-					$(echo-style --error="When APT_REPO is set, arch must be set to {ARCH}")
-					$(echo-style --code="deb [arch={ARCH}] https://...")
+					$(__print_style --error="When APT_REPO is set, arch must be set to {ARCH}")
+					$(__print_style --code="deb [arch={ARCH}] https://...")
 
 					APT: ${packages[*]}
 					APT_REPO: $repo
@@ -1439,8 +1439,8 @@ function setup_util() (
 			fi
 			if [[ -n $key && $repo != *'signed-by={KEY}'* ]]; then
 				cat <<-EOF >&2
-					$(echo-style --error="When APT_REPO and APT_KEY is set, signed-by must be set to {KEY}")
-					$(echo-style --code="deb [signed-by={KEY}] https://...")
+					$(__print_style --error="When APT_REPO and APT_KEY is set, signed-by must be set to {KEY}")
+					$(__print_style --code="deb [signed-by={KEY}] https://...")
 
 					APT: ${packages[*]}
 					APT_REPO: $repo
@@ -1449,7 +1449,7 @@ function setup_util() (
 			fi
 			if [[ $repo == *'http:'* ]]; then
 				# warn
-				echo-style --stderr --notice1='APT_REPO ' --code-notice1="$repo" --notice1=' contained ' --code-notice1='http:' --notice1=' instead of ' --code-notice1='https:' --notice1=' this may be an oversight. Packages affected: ' --code-notice1="${packages[*]}"
+				__print_style --stderr --notice1='APT_REPO ' --code-notice1="$repo" --notice1=' contained ' --code-notice1='http:' --notice1=' instead of ' --code-notice1='https:' --notice1=' this may be an oversight. Packages affected: ' --code-notice1="${packages[*]}"
 			fi
 		fi
 
@@ -1958,7 +1958,7 @@ function setup_util() (
 			# trapping 137 doesn't work either, one gets [bash: trap: 137: invalid signal specification]
 			# the only thing that works is invoking such a script with system bash, however there is no way to do that comprehensively, so we just warn by going back to the default terminal device immediately amd dump the warning, so that the warning persists in context of the need for the upgrade and the result of upgrade which is the upcoming crash
 			__do --redirect-stdout=TTY -- __print_string "$default_screen_buffer"
-			echo-style --stderr \
+			__print_style --stderr \
 				--notice1='Homebrew is about to delete the currently running bash executable, which will cause this sript to crash with exit status ' --code-notice1='137' --newline \
 				--notice1='Once crashed, please manually continue by re-running the prior script that you executed.'
 		fi
@@ -2118,7 +2118,7 @@ function setup_util() (
 		# 	if is-value -- "$email"; then
 		# 		# mas signout || :
 		# 		mas signin --dialog "$email" || {
-		# 			echo-style --notice='Failed to signin to the Mac App Store.''
+		# 			__print_style --notice='Failed to signin to the Mac App Store.''
 		# 			return 1
 		# 		}
 		# 		signed_in='yes'
@@ -2396,7 +2396,7 @@ function setup_util() (
 		elif [[ -n ${HOMEBREW_PREFIX-} && -x "${HOMEBREW_PREFIX-}/bin/pip" ]]; then
 			"${HOMEBREW_PREFIX}/bin/pip" "$@" || return
 		else
-			echo-style --stderr --error='[pip] nor its variations were found' || return
+			__print_style --stderr --error='[pip] nor its variations were found' || return
 			return 1
 		fi
 	}
@@ -3205,11 +3205,11 @@ function setup_util() (
 			return 200 # ECUSTOM 200 Not applicable yet but provided fallback
 		fi
 		if [[ -z $option_cli ]]; then
-			echo-style --stderr --error='TEA requires <cli>'
+			__print_style --stderr --error='TEA requires <cli>'
 			return 22 # EINVAL 22 Invalid argument
 		fi
 		if [[ -z $option_cli ]]; then
-			echo-style --stderr --error='TEA requires <cli>'
+			__print_style --stderr --error='TEA requires <cli>'
 			return 22 # EINVAL 22 Invalid argument
 		fi
 	}
@@ -3220,7 +3220,7 @@ function setup_util() (
 		for package in "${packages[@]}"; do
 			# check
 			if [[ $package != '+'* ]]; then
-				echo-style --stderr --error1='TEA packages must begin with a plus sign ' --code-error1='+' --error1=' e.g. ' --code-error1="--cli='jq' TEA='+stedolan.github.io/jq'"
+				__print_style --stderr --error1='TEA packages must begin with a plus sign ' --code-error1='+' --error1=' e.g. ' --code-error1="--cli='jq' TEA='+stedolan.github.io/jq'"
 				return 22 # EINVAL 22 Invalid argument
 			fi
 
@@ -3616,20 +3616,20 @@ function setup_util() (
 		if [[ -z $filename && -z $option_font ]]; then
 			filename="$option_cli"
 			if [[ -z $filename ]]; then
-				echo-style --stderr --error="DOWNLOAD requires DOWNLOAD_FILENAME or <cli>"
+				__print_style --stderr --error="DOWNLOAD requires DOWNLOAD_FILENAME or <cli>"
 				return 22 # EINVAL 22 Invalid argument
 			fi
 		fi
 		if [[ -n $build_install && -z $target_path && -z $build_glob ]]; then
-			echo-style --stderr --error="DOWNLOAD_BUILD_INSTALL requires DOWNLOAD_TARGET_PATH or DOWNLOAD_BUILD_GLOB"
+			__print_style --stderr --error="DOWNLOAD_BUILD_INSTALL requires DOWNLOAD_TARGET_PATH or DOWNLOAD_BUILD_GLOB"
 			return 22 # EINVAL 22 Invalid argument
 		fi
 		if [[ -n $build_uninstall && -z $target_path ]]; then
-			echo-style --stderr --error="DOWNLOAD_BUILD_UNINSTALL requires DOWNLOAD_TARGET_PATH"
+			__print_style --stderr --error="DOWNLOAD_BUILD_UNINSTALL requires DOWNLOAD_TARGET_PATH"
 			return 22 # EINVAL 22 Invalid argument
 		fi
 		if [[ -n $build_glob && -z $build_install && -z $build_uninstall ]]; then
-			echo-style --stderr --error="DOWNLOAD_BUILD_GLOB requires DOWNLOAD_BUILD_INSTALL or DOWNLOAD_BUILD_UNINSTALL"
+			__print_style --stderr --error="DOWNLOAD_BUILD_GLOB requires DOWNLOAD_BUILD_INSTALL or DOWNLOAD_BUILD_UNINSTALL"
 			return 22 # EINVAL 22 Invalid argument
 		fi
 
@@ -3689,14 +3689,14 @@ function setup_util() (
 					do_the_download
 					# build uninstall
 					local build_status
-					echo-style --info1='Uninstalling the built ' --code-info1="$option_name" --info1=' in ' --code-info1="$download_directory" --info1=' ...'
+					__print_style --info1='Uninstalling the built ' --code-info1="$option_name" --info1=' in ' --code-info1="$download_directory" --info1=' ...'
 					pushd "$download_directory" &>/dev/null
 					__try {build_status} -- "$build_uninstall"
 					popd &>/dev/null
 					if [[ $build_status -eq 0 ]]; then
-						echo-style --good1='Uninstalled the built ' --code-good1="$option_name" --good1=' in ' --code-good1="$download_directory"
+						__print_style --good1='Uninstalled the built ' --code-good1="$option_name" --good1=' in ' --code-good1="$download_directory"
 					else
-						echo-style --stderr --error1='Failed to uninstall the built ' --code-error1="$option_name" --error1=' in ' --code-error1="$download_directory"
+						__print_style --stderr --error1='Failed to uninstall the built ' --code-error1="$option_name" --error1=' in ' --code-error1="$download_directory"
 						return "$build_status"
 					fi
 				else
@@ -3719,15 +3719,15 @@ function setup_util() (
 		if [[ -n $build_install ]]; then
 			# build install
 			local build_status
-			echo-style --info1='Building ' --code-info1="$option_name" --info1=' in ' --code-info1="$download_directory" --info1=' ...'
+			__print_style --info1='Building ' --code-info1="$option_name" --info1=' in ' --code-info1="$download_directory" --info1=' ...'
 			# can't do cd in a subshell as we want to capture the status
 			pushd "$download_directory" &>/dev/null
 			__try {build_status} -- "$build_install"
 			popd &>/dev/null
 			if [[ $build_status -eq 0 ]]; then
-				echo-style --good1='Built ' --code-good1="$option_name" --good1=' in ' --code-good1="$download_directory"
+				__print_style --good1='Built ' --code-good1="$option_name" --good1=' in ' --code-good1="$download_directory"
 			else
-				echo-style --stderr --error1='Failed to build ' --code-error1="$option_name" --error1=' in ' --code-error1="$download_directory"
+				__print_style --stderr --error1='Failed to build ' --code-error1="$option_name" --error1=' in ' --code-error1="$download_directory"
 				return "$build_status"
 			fi
 			# move to target path if have pattern
@@ -3737,7 +3737,7 @@ function setup_util() (
 				__split --target={filtered_paths} --no-zero-length --invoke -- \
 					expand-path -- "$download_directory/$build_glob"
 				if [[ ${#filtered_paths[@]} -eq 0 ]]; then
-					echo-style --stderr --error1='No files matched the build filter ' --code-error1="$build_glob" --error1=' within ' --code-error1="$download_directory"
+					__print_style --stderr --error1='No files matched the build filter ' --code-error1="$build_glob" --error1=' within ' --code-error1="$download_directory"
 					fs-structure -- "$download_directory" >&2
 					return 1
 				elif [[ ${#filtered_paths[@]} -eq 1 ]]; then
@@ -3748,7 +3748,7 @@ function setup_util() (
 						mv -fv -- "${filtered_paths[@]}" "$target_path"
 					fi
 				else
-					echo-style --stderr --error1='Multiple files matched the build filter ' --code-error1="$build_glob" --error1=' within ' --code-error1="$download_directory"
+					__print_style --stderr --error1='Multiple files matched the build filter ' --code-error1="$build_glob" --error1=' within ' --code-error1="$download_directory"
 					fs-structure -- "$download_directory" >&2
 					return 1
 				fi
@@ -3768,11 +3768,11 @@ function setup_util() (
 		if [[ -z $filename ]]; then
 			if [[ -n $option_font ]]; then
 				if ! get-font --quiet -- "$option_font"; then
-					echo-style --stderr --error1='Failed to verify: ' --code-error1="$path"
+					__print_style --stderr --error1='Failed to verify: ' --code-error1="$path"
 					return 1
 				fi
 			else
-				echo-error 'Invalid state, filename should have already been verified.'
+				__print_error 'Invalid state, filename should have already been verified.'
 				return 3 # ESRCH 3 No such process
 			fi
 		else
@@ -3792,7 +3792,7 @@ function setup_util() (
 			return 200 # ECUSTOM 200 Not applicable to this utility
 		fi
 		if [[ $file_or_url == *'/setup-util-'* ]]; then
-			echo-error "Using INSTALLER=setup-util-* is deprecated, use an alternative: $option_name"
+			__print_error "Using INSTALLER=setup-util-* is deprecated, use an alternative: $option_name"
 			return 43 # EPROTONOSUPPORT 43 Protocol not supported
 		fi
 	}
@@ -3919,7 +3919,7 @@ function setup_util() (
 	fi
 	function log_fallback {
 		local installer="$1"
-		echo-style --tty --notice="[$option_name] via [$invocation] was unable to be installed by your system's existing package systems, we will now attempt to install it via by installing [$installer]"
+		__print_style --tty --notice="[$option_name] via [$invocation] was unable to be installed by your system's existing package systems, we will now attempt to install it via by installing [$installer]"
 	}
 	function log_pending {
 		local suffix='' method="${1-}"
@@ -3928,7 +3928,7 @@ function setup_util() (
 		else
 			suffix+='... ⏲'
 		fi
-		__do --redirect-stdout=TTY -- maybe_echo_style --good3="The [$option_name] utility is ${action_current}${suffix}"
+		__do --redirect-stdout=TTY -- __maybe_style --good3="The [$option_name] utility is ${action_current}${suffix}"
 	}
 	function log_success {
 		local suffix='' method="${1-}"
@@ -3937,7 +3937,7 @@ function setup_util() (
 		else
 			suffix+='. ✅'
 		fi
-		__do --redirect-stdout=TTY -- maybe_echo_style --good3="The [$option_name] utility was ${action_past}${suffix}"
+		__do --redirect-stdout=TTY -- __maybe_style --good3="The [$option_name] utility was ${action_past}${suffix}"
 	}
 	function log_failure {
 		local suffix='' method="${1-}"
@@ -3949,9 +3949,9 @@ function setup_util() (
 			suffix='. ❌'
 		fi
 		if [[ $option_optional == 'yes' ]]; then
-			maybe_echo_style --notice3="The [$option_name] optional utility was not ${action_past}${suffix}" >&2
+			__maybe_style --notice3="The [$option_name] optional utility was not ${action_past}${suffix}" >&2
 		else
-			echo-style --stderr --error3="The [$option_name] required utility was not ${action_past}${suffix}"
+			__print_style --stderr --error3="The [$option_name] required utility was not ${action_past}${suffix}"
 		fi
 		return 0
 	}
@@ -4035,8 +4035,8 @@ function setup_util() (
 			__do --redirect-stdout=TTY -- fc-cache -f
 		else
 			__do --redirect-stdout=TTY -- eval_helper --quiet --wrap \
-				--pending="$(echo-style --bold='Refreshing font cache...')" \
-				--failure="$(echo-style --error='Failed to refresh font cache.')" -- \
+				--pending="$(__print_style --bold='Refreshing font cache...')" \
+				--failure="$(__print_style --error='Failed to refresh font cache.')" -- \
 				fc-cache -f -v
 		fi
 	fi
