ci: fix lint issues throughout WIP commits
dorothy:
- if format fails, it is because of a check failure, so ensure check if run, so the lint issues can be detected and fixed and formatting can resume

diff --git a/commands/debug-network b/commands/debug-network
--- a/commands/debug-network
+++ b/commands/debug-network
@@ -14,13 +14,13 @@ if [ "$*" = '--help' ]; then
 fi
 
 # see [sources/bash.bash] for details
-function __command_exists {
+__command_exists() {
 	type "$1" >/dev/null 2>&1 || return
 	return
 }
-function __elevate {
+__elevate() {
 	# trim -- prefix
-	if [[ ${1-} == '--' ]]; then
+	if [ "${1-}" = '--' ]; then
 		shift
 	fi
 	# forward to [eval-helper --elevate] if it exists, as it is more detailed
@@ -29,10 +29,9 @@ function __elevate {
 		return
 	elif __command_exists -- sudo; then
 		# check if password is required
-		if ! sudo --non-interactive "$@" &>/dev/null; then
+		if ! sudo --non-interactive "$@" 2>/dev/null; then
 			# password is required, let the user know what they are being prompted for
-			__print_lines 'Your password is required to momentarily grant privileges to execute the command:' >&2
-			__print_lines "sudo $*" >&2
+			printf '%s\n' 'Your password is required to momentarily grant privileges to execute the command:' "sudo $*" >&2
 			sudo "$@"
 			return
 		else
@@ -41,14 +40,9 @@ function __elevate {
 			return
 		fi
 	elif __command_exists -- doas; then
-		local status=0
-		set -x # <inform the user of why they are being prompted for a doas password>
-		doas "$@" || status=$?
-		set +x # </inform>
-		return "$status"
+		doas "$@" || return
 	else
-		"$@"
-		return
+		"$@" || return
 	fi
 }
 
