reduce bash 4.2 and 4.3 to unsupported
due to their crashes not returning the correct exit status, mark them as unsupported / only partially supported for now, at a later point once this PR is merged, we can focus on more improvements here

diff --git a/commands/debug-bash b/commands/debug-bash
--- a/commands/debug-bash
+++ b/commands/debug-bash
@@ -115,7 +115,7 @@ function debug_bash() (
 	}
 
 	# determine bash binaries
-	local bash_input bash_binary bash_binaries=()
+	local bash_input bash_version bash_binary bash_binaries=()
 	if [[ ${#option_bash_binaries[@]} -eq 0 ]]; then
 		option_bash_binaries+=('bash')
 	fi
@@ -136,35 +136,31 @@ function debug_bash() (
 				__get_all_bash_binaries
 			continue
 		fi
+		# convert version to executable
 		if [[ $bash_input =~ ^[0-9] ]]; then
-			# convert version number to executable
-			setup-util-bash --version="$bash_input"
-			# should match [setup-util-bash]
-			case "$bash_input" in
-			3 | 3. | 3.2*) bash_input='3.2.57' ;;
-			4.0*) bash_input='4.0' ;;
-			4.2*) bash_input='4.2.53' ;;
-			4.3*) bash_input='4.3.30' ;;
-			4 | 4. | 4.4*) bash_input='4.4.18' ;;
-			5.0*) bash_input='5.0' ;;
-			5.1*) bash_input='5.1.16' ;;
-			5 | 5. | 5.2*) bash_input='5.2.37' ;;
-			5.3*) bash_input='5.3' ;; # still too new
-			*)
-				echo-style --error="The bash version [$item] is not supported by Dorothy."
-				return 75 # EPROGMISMATCH 75 Program version wrong
-				;;
-			esac
-			bash_input="$(expand-path -- "$XDG_BIN_HOME/bash-$bash_input*" | echo-first-line --stdin)"
-			# if it doesn't exist, install it
+			bash_version="$(__get_coerced_bash_version "$bash_input" || :)"
+			if [[ -n $bash_version ]]; then
+				bash_binary="$(expand-path -- "$XDG_BIN_HOME/bash-$bash_version*" | echo-first-line --stdin || :)"
+				if [[ -z $bash_binary ]]; then
+					if setup-util-bash --version="$bash_version"; then
+						bash_binary="$(expand-path -- "$XDG_BIN_HOME/bash-$bash_version*" | echo-first-line --stdin || :)"
+					fi
+				fi
+			else
+				bash_binary=''
+			fi
+		else
+			bash_binary="$(type -P "$bash_input" || :)"
 		fi
-		bash_binary="$(type -P "$bash_input" || :)"
+		# add binary path or note failure
 		if [[ -z $bash_binary ]]; then
 			echo-style --error='The bash binary ' --code="$bash_input" ' does not exist.'
 			__exit_status=2 # ENOENT 2 No such file or directory
 			continue
-		else
+		elif command-working -- "$bash_binary"; then # will output a error if it fails
 			bash_binaries+=("$bash_binary")
+		else
+			__exit_status=74 # EPROGUNAVAIL 74 RPC prog. not avail
 		fi
 	done
 	__unique --source+target={bash_binaries}
