ci: fix lint issues throughout WIP commits
dorothy:
- if format fails, it is because of a check failure, so ensure check if run, so the lint issues can be detected and fixed and formatting can resume

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -1775,50 +1775,44 @@ function dorothy_() (
 		fi
 
 		# on dorothy
-		echo-style --h3="$DOROTHY"
-		(
-			cd "$DOROTHY"
-			# upgrade
-			if [[ $upgrade_linting == 'yes' ]]; then
-				if __command_exists -- npx npm; then
-					npx npm-check-updates -u
-					npm install
-				fi
-				trunk upgrade
+		function __lint() (
+			local path="$1" status=0
+			if [[ -d "$path/.trunk" ]]; then
+				echo-style --h3="$path"
+				(
+					cd "$path"
+					# upgrade
+					if [[ $upgrade_linting == 'yes' ]]; then
+						if __command_exists -- npx npm; then
+							npx npm-check-updates -u
+							npm install
+						fi
+						trunk upgrade
+					fi
+					# format and check
+					trunk fmt --all "${args[@]}" || {
+						status=$?
+						# if format fails, it is likely for a check failure, so ensure check is run
+						trunk check --all "${args[@]}" || return
+						return "$status"
+					}
+					trunk check --all "${args[@]}"
+				)
+				echo-style --g3="$path"
 			fi
-			# format and check
-			# the below is currently broken, so commit it out
-			# # if balupton, update meta with auth
-			# if [[ $USER == 'balupton' ]] && __command_exists -- npm; then
-			# 	github-auth -- npm run our:meta # @todo currently broken
-			# 	# don't call [prettier] directly here to reformat, as that is handled by trunk, and trunk has different formatting rules, just have this before [trunk fmt]
-			#  fi
-			trunk fmt --all "${args[@]}"
-			trunk check --all "${args[@]}"
-			# update meta, only do this for balupton, as we can't guarantee up to date Node.js, as this requires Node.js 20
-			# https://github.com/bevry/dorothy/actions/runs/7636822585/job/20804540714#step:13:14
 		)
-		echo-style --g3="$DOROTHY"
+		__lint "$DOROTHY"
+		__lint "$DOROTHY/user"
 
 		# on user configuration
-		if [[ -d "$DOROTHY/user/.trunk" ]]; then
-			echo-style --h3="$DOROTHY/user"
-			(
-				cd "$DOROTHY/user"
-				# upgrade
-				if [[ $upgrade_linting == 'yes' ]]; then
-					if __command_exists -- npx npm; then
-						npx npm-check-updates -u
-						npm install
-					fi
-					trunk upgrade
-				fi
-				# format and check
-				trunk fmt --all "${args[@]}"
-				trunk check --all "${args[@]}"
-			)
-			echo-style --g3="$DOROTHY/user"
-		fi
+		# the below is currently broken, so commit it out
+		# update meta, only do this for balupton, as we can't guarantee up to date Node.js, as this requires Node.js 20
+		# https://github.com/bevry/dorothy/actions/runs/7636822585/job/20804540714#step:13:14
+		# # if balupton, update meta with auth
+		# if [[ $USER == 'balupton' ]] && __command_exists -- npm; then
+		# 	github-auth -- npm run our:meta # @todo currently broken
+		# 	# don't call [prettier] directly here to reformat, as that is handled by trunk, and trunk has different formatting rules, just have this before [trunk fmt]
+		#  fi
 
 		echo-style --g1='Dorothy Lint'
 	}
@@ -1943,7 +1937,7 @@ function dorothy_() (
 			if [[ $failed == 'no' ]]; then
 				for bash_binary in "${bash_binaries[@]}"; do
 					eval-helper --verbose --wrap -- debug-bash --bash="$bash_binary" -- "$filepath" --test || {
-						if [[ $bash_custom == 'no' ]] && __is_within "$filename" 'only_current_bash_version'; then
+						if [[ $bash_custom == 'no' ]] && __is_within "$filename" -- "${only_current_bash_version[@]}"; then
 							echo-style --warning='This test was expected to fail on other bash versions, marking as only warning instead of failure.'
 							warnings+=("$bash_binary $filepath --test")
 						else
