dorothy: during testing output information about command conventions and usage
also add the ability to pass additional styling arguments to `echo-element`

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -1427,6 +1427,51 @@ function dorothy() (
 		# 	echo-segment --g2="$filename"
 		# done
 
+		# check for usage
+		local commands matches file_problems
+		commands=("$DOROTHY/commands/"*)
+		for filepath in "${commands[@]}"; do
+			filename="$(basename "$filepath")"
+			file_problems=()
+
+			# test the file is used
+			matches="$(rg --files-with-matches --fixed-strings --regexp="$filename" "$DOROTHY" || :)"
+			if test "$matches" = "$filepath"; then
+				file_problems+=(
+					' '
+					--magenta='is not used anywhere besides itself.'
+				)
+			fi
+
+			# test the file has help
+			if ! rg --quiet --fixed-strings --regexp='function help {' "$filepath"; then
+				file_problems+=(
+					' '
+					--blue='no help.'
+				)
+			fi
+
+			# test the file has subshell
+			if ! rg --quiet --fixed-strings --regexp="${filename//-/_}() (" "$filepath"; then
+				file_problems+=(
+					' '
+					--cyan='no subshell wrapper.'
+				)
+			fi
+
+			# log
+			if test "${#file_problems[@]}" -eq 0; then
+				echo-element --openclose="$filename" --status=0
+			else
+				echo-element --openclose="$filename" --status=1 "${file_problems[@]}"
+			fi
+
+			# mapfile -t matched_files <(rg -l --regexp=".*$filename.*" "$DOROTHY")
+			# if test "${#matched_files[@]}" -eq 1; then
+			# 	echo-style --code="$filename" ' ' --error='is not used anywhere besides itself.'
+			# fi
+		done
+
 		# run tests on commands that have them
 		while read -r filepath; do
 			filename="$(basename "$filepath")"
@@ -1448,7 +1493,7 @@ function dorothy() (
 			if test -n "$bashv3"; then
 				eval-helper --no-quiet --wrap -- "$bashv3" "$filepath" --test
 			fi
-		done < <(rg --files-with-matches --regexp '--test' "$DOROTHY" | sort)
+		done < <(rg --files-with-matches --fixed-strings --regexp='--test' "$DOROTHY" | sort)
 
 		# log
 		popd >/dev/null
