another huge WIP commit:
- new `--elevated`, `--elevate`, `--user`, `--group`, `--reason` elevation args
- merging of `until-success` and `sudo-helper` into `eval-helper`
- change source code convention of having a newline follow `--`
- merged `fs-bytes`, `fs-kilobytes`, `fs-megabytes` into new `fs-size`
- merged various dirname/basename/filename commands into new `fs-path`
- renamed `echo-wait` to `echo-write`
- renamed `get-file` to `fs-type`
- add `is-exit`

todos:

- finish merged `eval-helper`
- finish new elevation args on `fs-*` commands
- finish new `fs-mkdir`

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -14,7 +14,7 @@
 # Environment configuration includes:
 #   homebrew path, homebrew architecture, ecosystem paths, etc.
 # Environment configuration is necessary so that:
-#   dependencies can be detected and installed, such as sd for config-helper
+#   dependencies can be detected and installed,
 #   test dependencies can correctly infer their environment's capabilities
 
 # =====================================
@@ -557,37 +557,37 @@ function dorothy_() (
 			if __command_exists -- apt-get; then
 				# for ubuntu/debian/kali
 				# E: Unable to locate package ncurses
-				__try_sudo apt-get install -y bash curl git coreutils gawk
+				__elevate apt-get install -y bash curl git coreutils gawk
 			elif __command_exists -- zypper; then
 				# for opensuse
-				__try_sudo zypper --non-interactive install bash curl git-core coreutils gawk
+				__elevate zypper --non-interactive install bash curl git-core coreutils gawk
 			elif __command_exists -- apk; then
 				# for alpine
-				__try_sudo apk add bash curl grep git coreutils gawk
+				__elevate apk add bash curl grep git coreutils gawk
 			elif __command_exists -- pamac; then
 				# for manjaro that has pamac installed
-				__try_sudo pamac install --no-confirm bash curl git coreutils gawk
+				__elevate pamac install --no-confirm bash curl git coreutils gawk
 			elif __command_exists -- pacman; then
 				# for manjaro and arch
-				__try_sudo pacman --noconfirm --refresh --sync --needed bash curl git coreutils gawk
+				__elevate pacman --noconfirm --refresh --sync --needed bash curl git coreutils gawk
 			elif __command_exists -- urpmi; then
 				# for mageia, prefer over fedora as mageia contains dnf
-				__try_sudo urpmi --auto bash curl git gawk
+				__elevate urpmi --auto bash curl git gawk
 			elif __command_exists -- dnf; then
 				# for fedora
-				__try_sudo dnf install --assumeyes --refresh --best --allowerasing bash curl git coreutils gawk
+				__elevate dnf install --assumeyes --refresh --best --allowerasing bash curl git coreutils gawk
 			elif [[ -n ${HOMEBREW_PREFIX-} && -x "$HOMEBREW_PREFIX/bin/brew" ]]; then
 				# this is here for consistency only, as it is unnecessary, all the commands already exist on macos without any need for homebrew
 				"$HOMEBREW_PREFIX/bin/brew" install bash curl git coreutils gawk
 			elif __command_exists -- xbps-install; then
 				# for void
-				__try_sudo xbps-install --sync --yes bash curl git coreutils gawk
+				__elevate xbps-install --sync --yes bash curl git coreutils gawk
 			elif __command_exists -- nix-env; then
 				# for nix
-				__try_sudo nix-env --install --attr nixpkgs.bash nixpkgs.curl nixpkgs.git nixpkgs.coreutils nixpkgs.gawk
+				__elevate nix-env --install --attr nixpkgs.bash nixpkgs.curl nixpkgs.git nixpkgs.coreutils nixpkgs.gawk
 			elif __command_exists -- emerge; then
 				# for gentoo
-				__try_sudo emerge app-shells/bash net-misc/curl dev-vcs/git sys-apps/coreutils sys-apps/gawk
+				__elevate emerge app-shells/bash net-misc/curl dev-vcs/git sys-apps/coreutils sys-apps/gawk
 			else
 				# for everything else
 				# @todo style with var_dump or something
@@ -609,7 +609,7 @@ function dorothy_() (
 		# ensure coreutils is installed on alpine, otherwise [env] won't support [-S]
 		# Usage: env [-i0] [-u NAME]... [-] [NAME=VALUE]... [PROG ARGS]
 		if __is_alpine && [[ "$(realpath "$(type -P 'env')" || :)" == "$(type -P busybox || :)" ]]; then
-			__try_sudo apk add coreutils
+			__elevate apk add coreutils
 		fi
 	}
 
@@ -637,7 +637,7 @@ function dorothy_() (
 		# [config-helper] uses [echo-regexp] which requires [deno]
 		if __command_missing -- jq deno; then
 			if __command_exists -- apt-get; then
-				__try_sudo apt-get -qq update # -qq: quiet
+				__elevate apt-get -qq update # -qq: quiet
 			fi
 			setup-util-jq --quiet
 			setup-util-deno --quiet
@@ -855,20 +855,20 @@ function dorothy_() (
 		eval_helper --quiet --no-wrap \
 			--pending="$(echo-style --bold='Correcting permissions...')" \
 			--success="$(echo-style --success='Corrected permissions.')" \
-			--failure="$(echo-style --error='Failed to correct permissions.')" \
-			-- correct_permissions
+			--failure="$(echo-style --error='Failed to correct permissions.')" -- \
+			correct_permissions
 
 		eval_helper --quiet --no-wrap \
 			--pending="$(echo-style --bold='Staging new files...')" \
 			--success="$(echo-style --success='Staged new files.')" \
-			--failure="$(echo-style --error='Failed to stage new files.')" \
-			-- stage_new_files "$DOROTHY"
+			--failure="$(echo-style --error='Failed to stage new files.')" -- \
+			stage_new_files "$DOROTHY"
 
 		eval_helper --quiet --no-wrap \
 			--pending="$(echo-style --bold='Staging changed files...')" \
 			--success="$(echo-style --success='Staged changed files.')" \
-			--failure="$(echo-style --error='Failed to stage changed files.')" \
-			-- stage_changed_files "$DOROTHY"
+			--failure="$(echo-style --error='Failed to stage changed files.')" -- \
+			stage_changed_files "$DOROTHY"
 	}
 
 	function ensure_dorothy_configured {
@@ -1013,8 +1013,8 @@ function dorothy_() (
 			if get-terminal-reactivity-support --quiet; then
 				where="$(
 					choose --linger --required --label --default="$where" \
-						--question='Where do you want to store your Dorothy user configuration?' \
-						-- \
+						--question='Where do you want to store your Dorothy user configuration?' -- \
+						\
 						github 'Use a GitHub repository for your user configuration.' \
 						gitlab 'Use a GitLab repository for your user configuration.' \
 						custom 'Manually specify a repository URL for your user configuration.' \
@@ -1419,8 +1419,8 @@ function dorothy_() (
 		if [[ -z $shell ]]; then
 			shell="$(
 				choose --linger --required \
-					--question='Which shell to use?' \
-					-- bash fish nu
+					--question='Which shell to use?' -- \
+					bash fish nu
 			)"
 		fi
 
@@ -1572,7 +1572,7 @@ function dorothy_() (
 		source "$DOROTHY/sources/config.sh"
 
 		# prepare
-		mapfile -t files < <(echo-filenames -- "$DOROTHY/themes/"*.* "$DOROTHY/user/themes/"*.* | echo-unique --stdin)
+		mapfile -t files < <(fs-path --no-parents --no-extensions -- "$DOROTHY/themes/"*.* "$DOROTHY/user/themes/"*.* | echo-unique --stdin)
 		themes=(
 			system
 			"${files[@]}"
@@ -1581,8 +1581,8 @@ function dorothy_() (
 		# ask
 		theme="$(
 			choose --linger --required \
-				--question='Which theme to use?' \
-				-- "${themes[@]}"
+				--question='Which theme to use?' -- \
+				"${themes[@]}"
 		)"
 
 		# apply
@@ -1622,12 +1622,12 @@ function dorothy_() (
 		fi
 
 		# versions
-		eval-helper --verbose -- bash --version || :
-		eval-helper --verbose -- prettier --version || :
-		eval-helper --verbose -- rg --version || :
-		eval-helper --verbose -- shellcheck --version || :
-		eval-helper --verbose -- shfmt --version || :
-		eval-helper --verbose -- trunk --version || :
+		eval-helper --verbose --wrap -- bash --version || :
+		eval-helper --verbose --wrap -- prettier --version || :
+		eval-helper --verbose --wrap -- rg --version || :
+		eval-helper --verbose --wrap -- shellcheck --version || :
+		eval-helper --verbose --wrap -- shfmt --version || :
+		eval-helper --verbose --wrap -- trunk --version || :
 
 		# log
 		echo-style --g1='Dorothy Development'
@@ -1866,7 +1866,7 @@ function dorothy_() (
 		# can't figure out how to sort array values
 		# # sort all array values in the cspell.json configuration file
 		# if __command_exists -- jq; then
-		# 	# jq --sort-keys . "$DOROTHY/cspell.json" | echo-wait --atomic -- "$DOROTHY/cspell.json"
+		# 	# jq --sort-keys . "$DOROTHY/cspell.json" | echo-write --atomic -- "$DOROTHY/cspell.json"
 		# fi
 
 		# run relevant debugs
@@ -1923,7 +1923,7 @@ function dorothy_() (
 			failed='no'
 
 			# check if we want to skip this test
-			if is-needle --needle="$filename" -- "${skips[@]}"; then
+			if __is_within "$filename" 'skips'; then
 				continue
 			fi
 
@@ -1940,7 +1940,7 @@ function dorothy_() (
 			if [[ $failed == 'no' ]]; then
 				for bash_binary in "${bash_binaries[@]}"; do
 					eval-helper --verbose --wrap -- debug-bash --bash="$bash_binary" -- "$filepath" --test || {
-						if [[ $bash_custom == 'no' && ${#only_current_bash_version[@]} -ne 0 ]] && is-needle --needle="$filename" -- "${only_current_bash_version[@]}"; then
+						if [[ $bash_custom == 'no' ]] && __is_within "$filename" 'only_current_bash_version'; then
 							echo-style --warning='This test was expected to fail on other bash versions, marking as only warning instead of failure.'
 							warnings+=("$bash_binary $filepath --test")
 						else
@@ -2047,8 +2047,8 @@ function dorothy_() (
 					)
 				fi
 
-				# is the file used by other commands?
-				matches="$(rg --files-with-matches --regexp="[^\[]${filename}" "${scan_paths[@]}" || :)"
+				# is the file used by other commands? excludes [cmd] and `cmd` usage which are in comments and messages
+				matches="$(rg --files-with-matches --regexp="[^\[\`]${filename}" "${scan_paths[@]}" || :)"
 				if [[ -z $matches || $matches == "$filepath" ]]; then
 					messages+=(
 						' '
diff --git a/commands/flush-dns b/commands/flush-dns
--- a/commands/flush-dns
+++ b/commands/flush-dns
@@ -40,36 +40,34 @@ function flush_dns() (
 	# https://support.apple.com/en-us/HT202516
 	if is-mac; then
 		if __command_exists -- mDNSResponder; then
-			eval-helper --shapeshifter --quiet \
+			eval-helper --quiet --wrap --elevate \
 				--pending="$(echo-style --bold='Restarting [mDNSResponder]...')" \
 				--success="$(echo-style --success='Restarted [mDNSResponder].')" \
-				--failure="$(echo-style --error='Failed to restart [mDNSResponder].')" \
-				-- sudo-helper \
-				-- killall -HUP mDNSResponder
+				--failure="$(echo-style --error='Failed to restart [mDNSResponder].')" -- \
+				killall -HUP mDNSResponder
 		fi
 		if __command_exists -- dscacheutil; then
-			eval-helper --shapeshifter --quiet \
+			eval-helper --quiet --wrap --elevate \
 				--pending="$(echo-style --bold='Flushing [dscacheutil]...')" \
 				--success="$(echo-style --success='Flushed [dscacheutil].')" \
-				--failure="$(echo-style --error='Failed to flush [dscacheutil].')" \
-				-- sudo-helper \
-				-- dscacheutil -flushcache
+				--failure="$(echo-style --error='Failed to flush [dscacheutil].')" -- \
+				dscacheutil -flushcache
 		fi
 		if __command_exists -- discoveryutil; then
-			eval-helper --shapeshifter --quiet \
+			eval-helper --quiet --wrap --elevate \
 				--pending="$(echo-style --bold='Flushing [discoveryutil]...')" \
 				--success="$(echo-style --success='Flushed [discoveryutil].')" \
-				--failure="$(echo-style --error='Failed to flush [discoveryutil].')" \
-				-- sudo-helper \
-				-- discoveryutil mdnsflushcache
+				--failure="$(echo-style --error='Failed to flush [discoveryutil].')" -- \
+				discoveryutil mdnsflushcache
 		fi
 	elif __command_exists -- resolvectl; then
-		eval-helper --shapeshifter --quiet \
+		eval-helper --quiet --wrap --elevate \
 			--pending="$(echo-style --bold='Flushing DNS cache via [Systemd]...')" \
 			--success="$(echo-style --success='Flushed DNS cache via [Systemd]')" \
-			--failure="$(echo-style --error='Failed to flush DNS cache via [Systemd].' ' ' --notice='If using an alternative DNS service, then this is expected.')" \
-			-- sudo-helper \
-			-- resolvectl flush-caches --no-pager || :
+			--failure="$(
+				echo-style --error='Failed to flush DNS cache via [Systemd].' ' ' --notice='If using an alternative DNS service, then this is expected.'
+			)" -- \
+			resolvectl flush-caches --no-pager || :
 	else
 		echo-error 'DNS flushing not yet implemented for this operating system.'
 		return 19 # ENODEV 19 Operation not supported by device
diff --git a/commands/get-devices b/commands/get-devices
--- a/commands/get-devices
+++ b/commands/get-devices
@@ -272,54 +272,54 @@ function get_devices() (
 		{
 			if [[ -n $option_node ]]; then
 				# model, serial, uuid, filesystem, size, block, label
-				sudo-helper --wrap \
-					-- diskutil info "$option_node" || :
+				eval-helper --elevate --wrap -- \
+					diskutil info "$option_node" || :
 
 				# label, uuid, block, filesystem
-				sudo-helper --wrap \
-					-- blkid "$option_node" || :
+				eval-helper --elevate --wrap -- \
+					blkid "$option_node" || :
 
 				# serial, vendor, product, revision
-				sudo-helper --wrap \
-					-- sginfo -a "$option_node" || :
+				eval-helper --elevate --wrap -- \
+					sginfo -a "$option_node" || :
 
-				sudo-helper --wrap \
-					-- hdparm -I "$option_node" || :
+				eval-helper --elevate --wrap -- \
+					hdparm -I "$option_node" || :
 
-				sudo-helper --wrap \
-					-- sdparm -i "$option_node" || :
+				eval-helper --elevate --wrap -- \
+					sdparm -i "$option_node" || :
 
 				# -i: model, serial, firmware, pci id, ieee id, controller id, nvme version, etc.
 				# -a: same as -i, but includes SMART specific details that we don't care for
-				# sudo-helper --wrap \
+				# eval-helper --elevate --wrap \
 				# 	-- smartctl -a "$option_node" ''
 
 				#  btrfs filesystem show [options] [<path>|<uuid>|<device>|label]
-				sudo-helper --wrap \
-					-- btrfs filesystem show "$option_node"
+				eval-helper --elevate --wrap -- \
+					btrfs filesystem show "$option_node"
 			else
 				if is-linux; then
 					# macos doesn't support fdisk for listing
-					sudo-helper --wrap \
-						-- fdisk -l || :
+					eval-helper --elevate --wrap -- \
+						fdisk -l || :
 
 					# Gets all the details for the drives, including the vendor, model, serial, driver capabilities, etc.
 					# UASP unsupported: configuration: driver=usb-storage
 					# UASP supported: configuration: driver=uas maxpower=... speed=...
-					sudo-helper --wrap \
-						-- lshw -class disk -class storage || :
+					eval-helper --elevate --wrap -- \
+						lshw -class disk -class storage || :
 
 					# Fetch filesystems and mounts for all drives
-					sudo-helper --wrap \
-						-- lsblk -f || :
+					eval-helper --elevate --wrap -- \
+						lsblk -f || :
 				else
-					sudo-helper --wrap \
-						-- diskutil list || :
+					eval-helper --elevate --wrap -- \
+						diskutil list || :
 				fi
 
 				#  btrfs filesystem show [options]
-				sudo-helper --wrap \
-					-- btrfs filesystem show
+				eval-helper --elevate --wrap -- \
+					btrfs filesystem show
 
 				# trail
 				__print_line
@@ -335,14 +335,15 @@ function get_devices() (
 			# if you attach a btrfs cluster to a new machine
 			# it may not be completely discovered until the btrfs agent scans for the devices
 			# and btrfs supports mounting partial filesystems, which cause innumerable errors
-			__do --redirect-stdout=tty -- eval-helper --quiet -- btrfs-helper discover
+			__do --redirect-stdout=tty -- eval-helper --quiet --wrap -- \
+				btrfs-helper discover
 			MOUNT_HAYSTACK="$(mount)"
 		fi
 		if is-mac; then
-			MOUNT_RAID="$(sudo-helper -- diskutil appleRAID list)"
-			sudo-helper -- diskutil list | echo-regexp -fong --regexp='/dev/[^ ]+'
+			MOUNT_RAID="$(eval-helper --elevate -- diskutil appleRAID list)"
+			eval-helper --elevate -- diskutil list | echo-regexp -fong --regexp='/dev/[^ ]+'
 		else
-			sudo-helper -- fdisk -l | echo-regexp -fongm --regexp='Disk (/dev/.+): (.+?),.+\nDisk model: (.+)' --replace=$'$1\t$2\t$3'
+			eval-helper --elevate -- fdisk -l | echo-regexp -fongm --regexp='Disk (/dev/.+): (.+?),.+\nDisk model: (.+)' --replace=$'$1\t$2\t$3'
 		fi
 	}
 	function get_one {
@@ -360,7 +361,7 @@ function get_devices() (
 			# macos doesn't seem to provide a way to find out if a node is actually mountable
 
 			# fetch diskutil properties
-			temp="$(sudo-helper -- diskutil info "$node")"
+			temp="$(eval-helper --elevate -- diskutil info "$node")"
 			uuid="$(get_property 'Disk [/] Partition UUID' "$temp")"
 			model="$(get_property 'Device [/] Media Name' "$temp")"
 			serial="$(get_property 'Disk [/] Partition UUID' "$temp")"
@@ -384,7 +385,7 @@ function get_devices() (
 				temp="${node##*/}" # /dev/disk7 => disk7
 				temp="$(echo-regexp -o --regexp="${temp}s\d+" -- "$MOUNT_RAID")"
 				if [[ -n $temp ]]; then
-					temp="$(sudo-helper -- diskutil info "$temp")"
+					temp="$(eval-helper --elevate -- diskutil info "$temp")"
 					uuid="$(get_property 'Parent RAID Set UUID' "$temp")"
 					label="$(get_property 'Parent Set Name' "$temp")"
 					serial="$(get_property 'Disk [/] Partition UUID' "$temp")"
@@ -396,7 +397,7 @@ function get_devices() (
 					# probably child device of label
 					temp="$(get_property 'APFS Physical Store' "$temp")"
 					if [[ -n $temp ]]; then
-						temp="$(sudo-helper -- diskutil info "$temp")"
+						temp="$(eval-helper --elevate -- diskutil info "$temp")"
 						uuid="$(get_property 'Disk [/] Partition UUID' "$temp")"
 						label="$(get_property 'Set Name' "$temp")"
 						filesystem="$(get_property 'Type [(]Bundle[)]' "$temp")"
@@ -422,7 +423,7 @@ function get_devices() (
 			fi
 		else
 			# fetch blkid properties
-			temp="$(sudo-helper -- blkid "$node" || :)" # can fail if recently removed from a btrfs cluster
+			temp="$(eval-helper --elevate -- blkid "$node" || :)" # can fail if recently removed from a btrfs cluster
 			if [[ -n $temp ]]; then
 				filesystem="$(get_key 'TYPE' "$temp")"
 				label="$(get_key 'LABEL' "$temp")"
@@ -431,7 +432,7 @@ function get_devices() (
 			fi
 
 			# fetch sginfo properties
-			temp="$(sudo-helper -- sginfo -a "$node")"
+			temp="$(eval-helper --elevate -- sginfo -a "$node")"
 			serial="$(get_property 'Serial Number' "$temp")"
 			vendor="$(get_property 'Vendor' "$temp")"
 			product="$(get_property 'Product' "$temp")"
@@ -443,7 +444,7 @@ function get_devices() (
 
 		# fetch count
 		if [[ $filesystem == 'btrfs' ]]; then
-			count_info="$(sudo-helper -- btrfs filesystem show "$node")"
+			count_info="$(eval-helper --elevate -- btrfs filesystem show "$node")"
 			count="$(echo-regexp -o --regexp='Total devices ([0-9]+)' --replace='$1' -- "$count_info")"
 			count_available="$(echo-regexp -c --regexp='devid' -- "$count_info")"
 		fi
@@ -568,8 +569,8 @@ function get_devices() (
 		# expand results into results and details
 		mapfile -t results < <(__print_lines "${results[@]}")
 		choose --required --confirm --label \
-			--question="$option_select" \
-			-- "${results[@]}"
+			--question="$option_select" -- \
+			"${results[@]}"
 	else
 		__print_lines "${results[@]}"
 	fi
diff --git a/commands/setup-dns b/commands/setup-dns
--- a/commands/setup-dns
+++ b/commands/setup-dns
@@ -45,7 +45,7 @@ function setup_dns() (
 		for path_var in "${path_vars[@]}"; do
 			values+=("${!path_var}")
 		done
-		__sudo_mkdirp "${values[@]}"
+		__elevate_mkdirp "${values[@]}"
 	}
 	function __check_env_vars {
 		local env_var missing_env_vars=()
@@ -227,8 +227,7 @@ function setup_dns() (
 
 		# it does exist
 		if is-mac; then
-			# get its basename which is the service id
-			id="$(fs-filename --basename -- "$file")"
+			id="$(fs-path --no-parents --no-extensions -- "$file")"
 			service-helper --stop -- "$id" || :
 		else
 			service-helper --stop -- "$id" || :
@@ -246,8 +245,7 @@ function setup_dns() (
 		fi
 
 		# it does exist
-		# get its basename which is the service id
-		id="$(fs-filename --basename -- "$file")"
+		id="$(fs-path --no-parents --no-extensions -- "$file")"
 		if is-mac; then
 			# Usage: launchctl unload <service-path, service-path2, ...>
 			# -w      Additionally disables the service such that future load
@@ -266,7 +264,7 @@ function setup_dns() (
 	# loads/installs the service, then enables and starts it
 	function dns_service_enable {
 		local file="$1" id
-		id="$(fs-filename --basename -- "$file")"
+		id="$(fs-path --no-parents --no-extensions -- "$file")"
 		if is-mac; then
 			# ensure correct permissions, not sure why
 			# but [homebrew services] does this, so doing it here
@@ -281,16 +279,16 @@ function setup_dns() (
 	}
 
 	function dns_service_logs {
-		eval-helper --no-quiet -- cat -- "$LOGS_DIR/"*"$id"*.log || :
+		echo-file -- "$LOGS_DIR/"*"$id"*.log || :
 	}
 
 	function dns_service_reload {
 		# after service additions/removals
 		# systemctl needs to be reloaded apparently
 		if __command_exists -- systemctl; then
-			sudo-helper -- systemctl daemon-reload
-			sudo-helper -- systemctl reset-failed
-			# ^ use sudo, otherwise prompted via ubuntu user password
+			eval-helper --elevate -- systemctl daemon-reload
+			eval-helper --elevate -- systemctl reset-failed
+			# ^ use elevation, otherwise prompted via ubuntu user password
 		fi
 	}
 
@@ -358,8 +356,8 @@ function setup_dns() (
 
 		# remove files
 		local had_removal='no'
-		mapfile -t remove_paths_that_exist < <(echo-if-present --sudo -- "${remove_paths[@]}")
-		if [[ ${#remove_paths_that_exist[@]} -ne 0 ]] && fs-rm --quiet --confirm --sudo -- "${remove_paths_that_exist[@]}"; then
+		mapfile -t remove_paths_that_exist < <(echo-if-present --elevate -- "${remove_paths[@]}")
+		if [[ ${#remove_paths_that_exist[@]} -ne 0 ]] && fs-rm --quiet --confirm --elevate -- "${remove_paths_that_exist[@]}"; then
 			had_removal='yes'
 		fi
 
@@ -405,7 +403,7 @@ function setup_dns() (
 			# apply
 			local interface
 			network-interface list | while read -r interface; do
-				sudo-helper -- networksetup -setdnsservers "$interface" "${servers[@]}"
+				eval-helper --elevate -- networksetup -setdnsservers "$interface" "${servers[@]}"
 			done
 
 			# log
@@ -445,7 +443,7 @@ function setup_dns() (
 			echo-style --h2="$action_title $system_dns__title"
 
 			# dump the data for where we are
-			sudo-helper -- resolvectl status --no-pager || :
+			eval-helper --elevate -- resolvectl status --no-pager || :
 
 			# temporarily disable these services while we redo the configuration files
 			# https://wiki.archlinux.org/title/systemd-networkd
@@ -454,16 +452,18 @@ function setup_dns() (
 
 			# allow modifications in case something has locked it
 			# for some reason this can fail
-			sudo-helper -- chattr -i /etc/resolv.conf || :
+			eval-helper --elevate -- chattr -i /etc/resolv.conf || :
 
 			# make life simple, using only /etc/resolv.conf
 			# https://www.freedesktop.org/software/systemd/man/resolved.conf.html
-			fs-rm --quiet --no-confirm --sudo -- \
-				/run/systemd/resolve/stub-resolv.conf \
-				/usr/lib/systemd/resolv.conf \
-				/run/systemd/resolve/resolv.conf \
-				/etc/systemd/resolved.conf \
+			local resolv_paths=(
+				/run/systemd/resolve/stub-resolv.conf
+				/usr/lib/systemd/resolv.conf
+				/run/systemd/resolve/resolv.conf
+				/etc/systemd/resolved.conf
 				/etc/resolv.conf
+			)
+			fs-rm --quiet --no-confirm --elevate -- "${resolv_paths[@]}"
 
 			# prepare config for file, and for interfaces
 			local Domains DNSOverTLS DNSSEC
@@ -480,7 +480,7 @@ function setup_dns() (
 			# apply specific config
 			if [[ $action == 'enable' ]]; then
 				# using systemd, the initial lines are for ping/nslookup/etc, the [Resolve] lines are for systemd-resolve
-				echo-wait -- /etc/resolv.conf <<-EOF
+				echo-write -- /etc/resolv.conf <<-EOF
 					nameserver 127.0.0.53
 					options edns0 trust-ad
 					search .
@@ -493,7 +493,7 @@ function setup_dns() (
 				EOF
 			else
 				# use custom service
-				echo-wait -- /etc/resolv.conf <<-EOF
+				echo-write -- /etc/resolv.conf <<-EOF
 					nameserver ${servers[0]}
 					options edns0 trust-ad
 				EOF
@@ -505,8 +505,8 @@ function setup_dns() (
 			service-helper --enable --start -- systemd-resolved systemd-networkd || :
 
 			# flush their caches
-			sudo-helper -- resolvectl flush-caches --no-pager || :
-			sudo-helper -- resolvectl reset-server-features --no-pager || :
+			eval-helper --elevate -- resolvectl flush-caches --no-pager || :
+			eval-helper --elevate -- resolvectl reset-server-features --no-pager || :
 
 			# apply the changes to their interfaces
 			mapfile -t interfaces < <(network-interface list | echo-values --stdin)
@@ -531,14 +531,14 @@ function setup_dns() (
 				fi
 
 				# remove other changes
-				sudo-helper -- resolvectl revert "$interface" || continue
+				eval-helper --elevate -- resolvectl revert "$interface" || continue
 
 				# apply intended changes
-				sudo-helper -- resolvectl default-route "$interface" "$default_route"
-				sudo-helper -- resolvectl domain "$interface" "$Domains"
-				sudo-helper -- resolvectl dnssec "$interface" "$DNSSEC"
-				sudo-helper -- resolvectl dnsovertls "$interface" "$DNSOverTLS"
-				sudo-helper -- resolvectl dns "$interface" "${servers[@]}"
+				eval-helper --elevate -- resolvectl default-route "$interface" "$default_route"
+				eval-helper --elevate -- resolvectl domain "$interface" "$Domains"
+				eval-helper --elevate -- resolvectl dnssec "$interface" "$DNSSEC"
+				eval-helper --elevate -- resolvectl dnsovertls "$interface" "$DNSOverTLS"
+				eval-helper --elevate -- resolvectl dns "$interface" "${servers[@]}"
 
 				# reboot the interface if it isn't a vpn
 				waiter 5
@@ -546,7 +546,7 @@ function setup_dns() (
 			done
 
 			# dump the status now that we are done
-			sudo-helper -- resolvectl status --no-pager || :
+			eval-helper --elevate -- resolvectl status --no-pager || :
 
 			# now that it is all done, enable or disable
 			if [[ $action == 'enable' ]]; then
@@ -557,8 +557,8 @@ function setup_dns() (
 			fi
 
 			# after significant systemd changes, it may need to be reloaded
-			# sudo-helper -- systemctl daemon-reload
-			# sudo-helper -- systemctl reset-failed
+			# eval-helper --elevate -- systemctl daemon-reload
+			# eval-helper --elevate -- systemctl reset-failed
 
 			# log
 			echo-style --g2="$action_title $system_dns__title"
@@ -687,7 +687,7 @@ function setup_dns() (
 		echo-style --h2="$action_title $adguard_home__title"
 
 		# ensure directories
-		__sudo_mkdirp "$adguard_home__conf_dir" "$adguard_home__data_dir" "$adguard_home__state_dir"
+		__elevate_mkdirp "$adguard_home__conf_dir" "$adguard_home__data_dir" "$adguard_home__state_dir"
 
 		# download the installer, prior to disabling
 		temp__bin_file="$(
@@ -704,12 +704,12 @@ function setup_dns() (
 
 		# now that we know if there is an installation, it is supported, check if it is installed, if so stop it
 		if __adguard_home__installed; then
-			sudo-helper -- "${adguard_home__bin_cmd[@]}" --service stop || :
+			eval-helper --elevate -- "${adguard_home__bin_cmd[@]}" --service stop || :
 		fi
 
 		# now that the service is intended, installed, and stopped, install/upgrade it
-		sudo-helper -- mv -- "$temp__bin_file" "$adguard_home__bin_file" || :
-		fs-own --sudo --x -- "$adguard_home__bin_file" || :
+		eval-helper --elevate -- mv -- "$temp__bin_file" "$adguard_home__bin_file" || :
+		fs-own --elevate --x -- "$adguard_home__bin_file" || :
 		# ^ allow failure, as we will check this later
 
 		# now check the install/upgrade worked
@@ -728,8 +728,8 @@ function setup_dns() (
 		echo-style --h2="Uninstall $adguard_home__title"
 
 		# stop and uninstall the service
-		sudo-helper -- "${adguard_home__bin_cmd[@]}" --service stop || :
-		sudo-helper -- "${adguard_home__bin_cmd[@]}" --service uninstall || :
+		eval-helper --elevate -- "${adguard_home__bin_cmd[@]}" --service stop || :
+		eval-helper --elevate -- "${adguard_home__bin_cmd[@]}" --service uninstall || :
 
 		# ensure adguard home has stopped
 		killall "$adguard_home__bin_id" || :
@@ -755,13 +755,13 @@ function setup_dns() (
 
 		# this is here, because we need to seed the configuration file before we can do changes to it
 		if [[ ! -s $adguard_home__conf_file && $action == 'enable' ]]; then
-			sudo-helper -- "${adguard_home__bin_cmd[@]}" --service install || :
-			sudo-helper -- "${adguard_home__bin_cmd[@]}" --service start || :
+			eval-helper --elevate -- "${adguard_home__bin_cmd[@]}" --service install || :
+			eval-helper --elevate -- "${adguard_home__bin_cmd[@]}" --service start || :
 			confirm --ppid=$$ -- "Press <enter> once you have completed the initial $adguard_home__title setup at http://127.0.0.1:3000"
 		fi
 
 		# stop before config update
-		sudo-helper -- "${adguard_home__bin_cmd[@]}" --service stop || :
+		eval-helper --elevate -- "${adguard_home__bin_cmd[@]}" --service stop || :
 
 		# prepare desired providers
 		upstream_servers=(
@@ -783,20 +783,21 @@ function setup_dns() (
 		for server in "${upstream_servers[@]}"; do
 			replace+="  - $server"$'\n'
 		done
-		sudo-helper --inherit \
-			-- sd "$pattern" "$replace" "$adguard_home__conf_file"
-		sudo-helper -- \
+		# @todo replace with `echo-regexp` and `echo-write`
+		eval-helper --elevate --inherit -- \
+			sd "$pattern" "$replace" "$adguard_home__conf_file"
+		eval-helper --elevate -- \
 			"${adguard_home__bin_cmd[@]}" --check-config
 
 		# enable or disable
 		# Service control action: status, install, uninstall, start, stop, restart, reload (configuration).
 		if [[ $action == 'enable' ]]; then
-			sudo-helper -- "${adguard_home__bin_cmd[@]}" --service install || :
-			sudo-helper -- "${adguard_home__bin_cmd[@]}" --service reload || :
-			sudo-helper -- "${adguard_home__bin_cmd[@]}" --service start || :
-			sudo-helper -- "${adguard_home__bin_cmd[@]}" --service status || :
+			eval-helper --elevate -- "${adguard_home__bin_cmd[@]}" --service install || :
+			eval-helper --elevate -- "${adguard_home__bin_cmd[@]}" --service reload || :
+			eval-helper --elevate -- "${adguard_home__bin_cmd[@]}" --service start || :
+			eval-helper --elevate -- "${adguard_home__bin_cmd[@]}" --service status || :
 		else
-			sudo-helper -- "${adguard_home__bin_cmd[@]}" --service uninstall || :
+			eval-helper --elevate -- "${adguard_home__bin_cmd[@]}" --service uninstall || :
 		fi
 
 		# log
@@ -861,8 +862,8 @@ function setup_dns() (
 		fi
 
 		# now that the service is intended, installed, and stopped, install/upgrade it
-		sudo-helper -- mv -- "$temp__bin_file" "$cloudflared__bin_file"
-		fs-own --sudo --x -- "$cloudflared__bin_file"
+		eval-helper --elevate -- mv -- "$temp__bin_file" "$cloudflared__bin_file"
+		fs-own --elevate --x -- "$cloudflared__bin_file"
 
 		# now check the install/upgrade worked
 		__fail_if_dns_service_is_not_installed "$cloudflared__bin_id" "$cloudflared__bin_file"
@@ -945,7 +946,7 @@ function setup_dns() (
 				# create service with custom upstreams
 				# <string>--address</string>
 				# <string>0.0.0.0</string>
-				echo-wait -- "$cloudflared__proxy_service_file" <<EOF
+				echo-write -- "$cloudflared__proxy_service_file" <<EOF
 <?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
@@ -981,7 +982,7 @@ EOF
 				done
 
 				# create service with custom upstreams
-				echo-wait -- "$cloudflared__proxy_service_file" <<-EOF
+				echo-write -- "$cloudflared__proxy_service_file" <<-EOF
 					[Unit]
 					Description=${cloudflared__proxy_service_id}
 					Wants=network-online.target nss-lookup.target
@@ -1077,7 +1078,7 @@ EOF
 		echo-style --h2="$action_title $dnscrypt_proxy__title"
 
 		# ensure directories
-		__sudo_mkdirp "$dnscrypt_proxy__conf_dir"
+		__elevate_mkdirp "$dnscrypt_proxy__conf_dir"
 
 		# validate dnscrypt names
 		validate_dnscrypt_names
@@ -1108,7 +1109,7 @@ EOF
 				--head \
 				--pathname="$dnscrypt_proxy__conf_pathname" \
 				--filepath="$temp_conf_file"
-			sudo-helper -- mv -- "$temp_conf_file" "$dnscrypt_proxy__conf_file"
+			eval-helper --elevate -- mv -- "$temp_conf_file" "$dnscrypt_proxy__conf_file"
 		fi
 
 		# now that we have downloaded everything, uninstall any unsupported installations, and check there are no remaining unsupported installations
@@ -1120,12 +1121,12 @@ EOF
 		# now that we know if there is an installation, it is supported, check if it is installed, if so stop it
 		if __dnscrypt_proxy__installed; then
 			# only tell prior cmd to stop if the prior cmd exists
-			sudo-helper -- "${dnscrypt_proxy__bin_cmd[@]}" --service stop || :
+			eval-helper --elevate -- "${dnscrypt_proxy__bin_cmd[@]}" --service stop || :
 		fi
 
 		# now that the service is intended, installed, and stopped, install/upgrade it
-		sudo-helper -- mv -- "$temp__bin_file" "$dnscrypt_proxy__bin_file"
-		fs-own --sudo --x -- "$dnscrypt_proxy__bin_file"
+		eval-helper --elevate -- mv -- "$temp__bin_file" "$dnscrypt_proxy__bin_file"
+		fs-own --elevate --x -- "$dnscrypt_proxy__bin_file"
 
 		# now check the install/upgrade worked
 		__fail_if_dns_service_is_not_installed "$dnscrypt_proxy__bin_id" "$dnscrypt_proxy__bin_file"
@@ -1143,8 +1144,8 @@ EOF
 		echo-style --h2="Uninstall $dnscrypt_proxy__title"
 
 		# stop and uninstall the service
-		sudo-helper -- "${dnscrypt_proxy__bin_cmd[@]}" --service stop || :
-		sudo-helper -- "${dnscrypt_proxy__bin_cmd[@]}" --service uninstall || :
+		eval-helper --elevate -- "${dnscrypt_proxy__bin_cmd[@]}" --service stop || :
+		eval-helper --elevate -- "${dnscrypt_proxy__bin_cmd[@]}" --service uninstall || :
 
 		# ensure adguard home has stopped
 		killall "$dnscrypt_proxy__bin_id" || :
@@ -1183,13 +1184,12 @@ EOF
 
 		# stop the service if it is installed, before config update
 		if [[ -s $dnscrypt_proxy__service_file ]]; then
-			sudo-helper -- "${dnscrypt_proxy__bin_cmd[@]}" --service stop || :
+			eval-helper --elevate -- "${dnscrypt_proxy__bin_cmd[@]}" --service stop || :
 		fi
 
 		# update the configuration with the new [dnscrypt_names], if any
 		if [[ ${#dnscrypt_names[@]} -ne 0 ]]; then
-			sudo-helper --inherit \
-				-- config-helper --file="$dnscrypt_proxy__conf_file" -- \
+			config-helper --elevate --file="$dnscrypt_proxy__conf_file" -- \
 				--field='ipv4_servers' --no-quote --value='true' \
 				--field='ipv6_servers' --no-quote --value='true' \
 				--field='dnscrypt_servers' --no-quote --value='true' \
@@ -1197,17 +1197,17 @@ EOF
 				--field='server_names' --no-quote --value="[$(
 					echo-quote -- "${dnscrypt_names[@]}" | echo-join ', ' --stdin
 				)]"
-			sudo-helper -- "${dnscrypt_proxy__bin_cmd[@]}" --check -config "$dnscrypt_proxy__conf_file"
+			eval-helper --elevate -- "${dnscrypt_proxy__bin_cmd[@]}" --check -config "$dnscrypt_proxy__conf_file"
 		fi
 
 		# enable or disable
 		if [[ $action == 'enable' ]]; then
-			sudo-helper -- "${dnscrypt_proxy__bin_cmd[@]}" --service uninstall || : # Needed before install, otherwise: Failed to install DNSCrypt client proxy: Init already exists: /Library/LaunchDaemons/dnscrypt-proxy.plist
-			sudo-helper -- "${dnscrypt_proxy__bin_cmd[@]}" --service install || :
-			sudo-helper -- "${dnscrypt_proxy__bin_cmd[@]}" --service start || :
+			eval-helper --elevate -- "${dnscrypt_proxy__bin_cmd[@]}" --service uninstall || : # Needed before install, otherwise: Failed to install DNSCrypt client proxy: Init already exists: /Library/LaunchDaemons/dnscrypt-proxy.plist
+			eval-helper --elevate -- "${dnscrypt_proxy__bin_cmd[@]}" --service install || :
+			eval-helper --elevate -- "${dnscrypt_proxy__bin_cmd[@]}" --service start || :
 		elif [[ -s $dnscrypt_proxy__service_file ]]; then
-			sudo-helper -- "${dnscrypt_proxy__bin_cmd[@]}" --service stop || :
-			sudo-helper -- "${dnscrypt_proxy__bin_cmd[@]}" --service uninstall || :
+			eval-helper --elevate -- "${dnscrypt_proxy__bin_cmd[@]}" --service stop || :
+			eval-helper --elevate -- "${dnscrypt_proxy__bin_cmd[@]}" --service uninstall || :
 		fi
 
 		# log
diff --git a/commands/setup-linux b/commands/setup-linux
--- a/commands/setup-linux
+++ b/commands/setup-linux
@@ -140,33 +140,33 @@ function setup_linux() (
 	}
 
 	function do_apt_update {
-		sudo-helper -- apt-get update -y
+		eval-helper --elevate -- apt-get update -y
 	}
 
 	function do_dnf_update {
-		sudo-helper -- dnf check-update --assumeyes
+		eval-helper --elevate -- dnf check-update --assumeyes
 	}
 
 	function do_pacman_update {
 		# init the local database
 		# this is needed on systems which pacman was installed
-		sudo-helper -- pacman-key --init
+		eval-helper --elevate -- pacman-key --init
 		# refresh the local database
-		sudo-helper -- pacman --noconfirm --refresh --sync
+		eval-helper --elevate -- pacman --noconfirm --refresh --sync
 	}
 
 	function do_urpmi_update {
 		# https://wiki.mageia.org/en/URPMI#Basic_commands:_Install.2C_remove.2C_update
-		sudo-helper -- urpmi.update -a
+		eval-helper --elevate -- urpmi.update -a
 	}
 
 	function do_yum_update {
-		sudo-helper -- yum check-update -y || :
+		eval-helper --elevate -- yum check-update -y || :
 		# ^ it always returns exit code 100
 	}
 
 	function do_zypper_update {
-		sudo-helper -- zypper --non-interactive --gpg-auto-import-keys refresh
+		eval-helper --elevate -- zypper --non-interactive --gpg-auto-import-keys refresh
 	}
 
 	# -------------------------------------
@@ -190,11 +190,11 @@ function setup_linux() (
 	}
 
 	function do_apt_upgrade {
-		sudo-helper -- apt-get full-upgrade -y
+		eval-helper --elevate -- apt-get full-upgrade -y
 	}
 
 	function do_urpmi_upgrade {
-		sudo-helper -- urpmi --auto-update --auto
+		eval-helper --elevate -- urpmi --auto-update --auto
 	}
 
 	function do_dnf_upgrade {
@@ -202,16 +202,16 @@ function setup_linux() (
 		# -y, --assumeyes Automatically answer yes for all questions.
 		# -b, --best Try the best available package versions in transactions. Specifically during dnf upgrade, which by default skips over updates that can not be installed for dependency reasons, the switch forces DNF to only consider the latest packages. When running into packages with broken dependencies, DNF will fail giving a reason why the latest version can not be installed. Note that the use of the newest available version is only guaranteed for the packages directly requested (e.g. as a command line arguments), and the solver may use older
 		# --allowerasing Allow erasing of installed packages to resolve dependencies. This option could be used as an alternative to the yum swap command where packages to remove are not explicitly defined.
-		sudo-helper -- dnf upgrade --assumeyes --refresh --best --allowerasing
+		eval-helper --elevate -- dnf upgrade --assumeyes --refresh --best --allowerasing
 	}
 
 	function do_flatpak_upgrade {
-		sudo-helper -- flatpak update -y
+		eval-helper --elevate -- flatpak update -y
 		# ^ sudo with flatpak avoids gui sudo prompt
 	}
 
 	function do_pamac_upgrade {
-		sudo-helper -- pamac upgrade --no-confirm
+		eval-helper --elevate -- pamac upgrade --no-confirm
 		# ^ sudo with pamac avoids gui sudo prompt
 		# ^ `pamac update` is an alias for `pamac upgrade`
 	}
@@ -220,15 +220,15 @@ function setup_linux() (
 		if ! is-snap; then
 			return 0
 		fi
-		sudo-helper -- snap refresh || : # if snap was just installed on fedora, this can fail initially
+		eval-helper --elevate -- snap refresh || : # if snap was just installed on fedora, this can fail initially
 	}
 
 	function do_yum_upgrade {
-		sudo-helper -- yum upgrade -y --best
+		eval-helper --elevate -- yum upgrade -y --best
 	}
 
 	function do_zypper_upgrade {
-		sudo-helper -- zypper --non-interactive --gpg-auto-import-keys update --no-confirm --best-effort
+		eval-helper --elevate -- zypper --non-interactive --gpg-auto-import-keys update --no-confirm --best-effort
 	}
 
 	# -------------------------------------
@@ -295,32 +295,32 @@ function setup_linux() (
 	)
 
 	function do_apt_clean {
-		sudo-helper -- apt-get autoremove -y --purge
-		sudo-helper -- apt-get autoclean -y
-		sudo-helper -- apt-get clean -y
+		eval-helper --elevate -- apt-get autoremove -y --purge
+		eval-helper --elevate -- apt-get autoclean -y
+		eval-helper --elevate -- apt-get clean -y
 	}
 
 	function do_dnf_clean {
-		sudo-helper -- dnf clean all
+		eval-helper --elevate -- dnf clean all
 	}
 
 	function do_pamac_clean {
-		sudo-helper -- pamac clean --no-confirm
+		eval-helper --elevate -- pamac clean --no-confirm
 		# ^ sudo with pamac avoids gui sudo prompt
 	}
 
 	function do_pacman_clean {
 		# -c, --clean
 		#   Remove packages that are no longer installed from the cache as well as currently unused sync databases to free up disk space.
-		sudo-helper -- pacman --sync --noconfirm --clean
+		eval-helper --elevate -- pacman --sync --noconfirm --clean
 	}
 
 	function do_yum_clean {
-		sudo-helper -- yum clean all
+		eval-helper --elevate -- yum clean all
 	}
 
 	function do_zypper_clean {
-		sudo-helper -- zypper --non-interactive --gpg-auto-import-keys clean --all
+		eval-helper --elevate -- zypper --non-interactive --gpg-auto-import-keys clean --all
 	}
 
 	# -------------------------------------
@@ -334,7 +334,7 @@ function setup_linux() (
 		if do-release-upgrade -c; then
 			# if there is one, then ask the user if they want to upgrade to it
 			if confirm --linger --negative --ppid=$$ -- 'Upgrade the distribution release?'; then
-				sudo-helper -- do-release-upgrade
+				eval-helper --elevate -- do-release-upgrade
 			fi
 		fi
 	}
@@ -350,11 +350,11 @@ function setup_linux() (
 		# clean ecosystems
 		for item in "${clean[@]}"; do
 			if __command_exists -- "$item"; then
-				eval_helper --shapeshifter --no-wrap \
+				eval_helper --no-wrap --shapeshifter \
 					--pending="$(echo-style --bold="Cleaning $item...")" \
 					--success="$(echo-style --success="Cleaned $item.")" \
-					--failure="$(echo-style --error="Failed to clean $item.")" \
-					-- "do_${item}_clean"
+					--failure="$(echo-style --error="Failed to clean $item.")" -- \
+					"do_${item}_clean"
 			fi
 		done
 	elif [[ $action =~ ^(install|update)$ ]]; then
@@ -364,11 +364,11 @@ function setup_linux() (
 		# update references
 		for item in "${updates[@]}"; do
 			if __command_exists -- "$item"; then
-				eval_helper --shapeshifter --no-wrap \
+				eval_helper --no-wrap --shapeshifter \
 					--pending="$(echo-style --bold="Updating references of $item...")" \
 					--success="$(echo-style --success="Updated references of $item.")" \
-					--failure="$(echo-style --error="Failed to update references of $item.")" \
-					-- "do_${item}_update"
+					--failure="$(echo-style --error="Failed to update references of $item.")" -- \
+					"do_${item}_update"
 			fi
 		done
 
@@ -391,11 +391,11 @@ function setup_linux() (
 		if confirm --linger --positive --ppid=$$ -- 'Upgrade existing packages?'; then
 			for item in "${upgrades[@]}"; do
 				if __command_exists -- "$item"; then
-					eval_helper --shapeshifter --no-wrap \
+					eval_helper --no-wrap --shapeshifter \
 						--pending="$(echo-style --bold="Upgrading packages of $item...")" \
 						--success="$(echo-style --success="Upgraded packages of $item.")" \
-						--failure="$(echo-style --error="Failed to upgrade packages of $item.")" \
-						-- "do_${item}_upgrade"
+						--failure="$(echo-style --error="Failed to upgrade packages of $item.")" -- \
+						"do_${item}_upgrade"
 				fi
 			done
 		fi
@@ -406,11 +406,11 @@ function setup_linux() (
 		# setup user packages
 		for item in "${packages[@]}"; do
 			if __command_exists -- "$item"; then
-				eval_helper --shapeshifter --no-wrap \
+				eval_helper --no-wrap --shapeshifter \
 					--pending="$(echo-style --bold="Installing packages of $item...")" \
 					--success="$(echo-style --success="Installed packages of $item.")" \
-					--failure="$(echo-style --error="Failed to install packages of $item.")" \
-					-- "do_${item}_packages"
+					--failure="$(echo-style --error="Failed to install packages of $item.")" -- \
+					"do_${item}_packages"
 			fi
 		done
 
diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -154,8 +154,8 @@ function setup_util() (
 			--no-xdg
 			    If truthy, place the binary in /usr/local/bin and symlink the XDG binary to it.
 
-			--sudo
-			    When testing the <cli>, use sudo.
+			--elevate
+			    Forwaded to [command-working].
 
 			--confirm
 			    Confirm installation of the utility before installing it.
@@ -272,7 +272,7 @@ function setup_util() (
 	# </installer-options>
 
 	# process
-	local item option_quiet='' option_action='install' option_check='' option_checker='' option_installer='' option_app='' option_cli='' option_font='' option_name='' option_xdg='yes' option_sudo='no' option_confirm='no' option_optional='no' option_fallback='yes' option_upgrade='no' option_force='no' option_order=()
+	local item option_quiet='' option_action='install' option_check='' option_checker='' option_installer='' option_app='' option_cli='' option_font='' option_name='' option_xdg='yes' option_elevate='no' option_confirm='no' option_optional='no' option_fallback='yes' option_upgrade='no' option_force='no' option_order=()
 	while [[ $# -ne 0 ]]; do
 		item="$1"
 		shift
@@ -306,11 +306,12 @@ function setup_util() (
 		'--cli='*) option_cli="${item#*=}" ;;
 		'--font='*) option_font="${item#*=}" ;;
 		'--name='*) option_name="${item#*=}" ;;
+		# @todo redo the elevate/xdg flow in this, make it like sbin instead
 		'--no-xdg'* | '--xdg'*)
 			option_xdg="$(get-flag-value --affirmative --fallback="$option_xdg" -- "$item")"
 			;;
-		'--no-sudo'* | '--sudo'*)
-			option_sudo="$(get-flag-value --affirmative --fallback="$option_sudo" -- "$item")"
+		'--no-elevate'* | '--elevate'*)
+			option_elevate="$(get-flag-value --affirmative --fallback="$option_elevate" -- "$item")"
 			;;
 		'--no-confirm'* | '--confirm'*)
 			option_confirm="$(get-flag-value --affirmative --fallback="$option_confirm" -- "$item")"
@@ -510,7 +511,7 @@ function setup_util() (
 		if [[ -n $option_cli ]]; then
 			if __command_exists -- "$option_cli"; then
 				is_missing='no'
-				if ! command-working --sudo="$option_sudo" -- "$option_cli"; then
+				if ! command-working --elevate="$option_elevate" -- "$option_cli"; then
 					is_working='no'
 				fi
 			else
@@ -601,7 +602,7 @@ function setup_util() (
 		for installer in "${option_order[@]}"; do
 			if [[ $installer == '...' ]]; then
 				for inject_installer in "${installers[@]}"; do
-					if is-needle --needle="$inject_installer" -- "${option_order[@]}"; then
+					if __is_within "$inject_installer" 'option_order'; then
 						continue
 					else
 						temp_order+=("$inject_installer")
@@ -633,7 +634,7 @@ function setup_util() (
 			__mkdirp "$APPIMAGE_HOME"
 			__print_lines "$APPIMAGE_HOME/$filename"
 		elif [[ $option_xdg == 'no' ]]; then
-			__sudo_mkdirp '/usr/local/bin'
+			__elevate_mkdirp '/usr/local/bin'
 			__print_lines "/usr/local/bin/$filename"
 		else
 			# macos $HOME/.local/bin/$filename
@@ -661,7 +662,7 @@ function setup_util() (
 			# check app or cli
 			if [[ $path == *'.app' && -d $path ]]; then
 				return 0
-			elif command-working --sudo="$option_sudo" -- "$path"; then
+			elif command-working --elevate="$option_elevate" -- "$path"; then
 				return 0
 			fi
 		fi
@@ -678,13 +679,13 @@ function setup_util() (
 		if [[ ${#remove_paths[@]} -eq 0 ]]; then
 			return 0
 		fi
-		mapfile -t remove_paths_present_unique < <(echo-if-present -- "${remove_paths[@]}" | echo-unique --stdin)
+		mapfile -t remove_paths_present_unique < <(echo-if-present --elevate="$option_elevate" -- "${remove_paths[@]}" | echo-unique --stdin)
 		if [[ ${#remove_paths_present_unique[@]} -eq 0 ]]; then
 			return 0
 		fi
 		# prefer moving to trash, because trash allows invocations to continue
-		# otherwise active invocations will crash (such as setup-util-bash uninstalling the bash it was invoked with)
-		fs-rm --quiet --no-confirm --trash --delete --sudo="$option_sudo" -- "${remove_paths_present_unique[@]}"
+		# otherwise active invocations will crash, such as [setup-util-bash] uninstalling the bash it was invoked with
+		fs-rm --quiet --no-confirm --trash --delete --elevate="$option_elevate" -- "${remove_paths_present_unique[@]}"
 		return
 	}
 	function rm_helper_which {
@@ -795,7 +796,7 @@ function setup_util() (
 		fi
 
 		# packages
-		sudo-helper -- "${args[@]}" "${packages[@]}"
+		eval-helper --elevate -- "${args[@]}" "${packages[@]}"
 	}
 
 	# -------------------------------------
@@ -853,7 +854,7 @@ function setup_util() (
 		fi
 
 		# packages
-		sudo-helper -- "${args[@]}" "${packages[@]}"
+		eval-helper --elevate -- "${args[@]}" "${packages[@]}"
 	}
 
 	# -------------------------------------
@@ -904,7 +905,7 @@ function setup_util() (
 
 		# packages
 		for package in "${packages[@]}"; do
-			sudo-helper -- "${args[@]}" "$package"
+			eval-helper --elevate -- "${args[@]}" "$package"
 		done
 	}
 
@@ -973,7 +974,7 @@ function setup_util() (
 		# Restrict or filter output to packages that are out-of-date on the local system. Only package versions are used to find outdated packages; replacements are not checked here. This option works best if the sync database is refreshed using -Sy.
 
 		# init the local database
-		sudo-helper -- pacman-key --init
+		eval-helper --elevate -- pacman-key --init
 
 		# args
 		if [[ $option_action == 'uninstall' ]]; then
@@ -1005,7 +1006,7 @@ function setup_util() (
 		fi
 
 		# packages
-		sudo-helper -- "${args[@]}" "${packages[@]}"
+		eval-helper --elevate -- "${args[@]}" "${packages[@]}"
 	}
 
 	# pakku / AUR / Arch Linux
@@ -1048,7 +1049,7 @@ function setup_util() (
 
 		# packages
 		for package in "${packages[@]}"; do
-			sudo-helper -- "${args[@]}" "$package"
+			eval-helper --elevate -- "${args[@]}" "$package"
 		done
 	}
 
@@ -1112,7 +1113,7 @@ function setup_util() (
 		fi
 
 		# packages
-		sudo-helper -- "${args[@]}" "${packages[@]}"
+		eval-helper --elevate -- "${args[@]}" "${packages[@]}"
 	}
 	function do_pamac_fallback {
 		if ! is-manjaro; then
@@ -1167,7 +1168,7 @@ function setup_util() (
 
 		# packages
 		for package in "${packages[@]}"; do
-			sudo-helper -- "${args[@]}" "$package"
+			eval-helper --elevate -- "${args[@]}" "$package"
 		done
 	}
 
@@ -1210,7 +1211,7 @@ function setup_util() (
 
 		# packages
 		for package in "${packages[@]}"; do
-			sudo-helper -- "${args[@]}" "$package"
+			eval-helper --elevate -- "${args[@]}" "$package"
 		done
 	}
 
@@ -1264,7 +1265,7 @@ function setup_util() (
 		fi
 
 		# packages
-		sudo-helper -- "${args[@]}" "${packages[@]}"
+		eval-helper --elevate -- "${args[@]}" "${packages[@]}"
 	}
 
 	# pkgadd / pkg_add / OpenBSD
@@ -1300,7 +1301,7 @@ function setup_util() (
 
 		# packages
 		for package in "${packages[@]}"; do
-			sudo-helper -- pkgadd "$package"
+			eval-helper --elevate -- pkgadd "$package"
 		done
 	}
 
@@ -1351,7 +1352,7 @@ function setup_util() (
 
 		# packages
 		for package in "${packages[@]}"; do
-			sudo-helper -- "${args[@]}" "$package"
+			eval-helper --elevate -- "${args[@]}" "$package"
 		done
 	}
 
@@ -1485,7 +1486,7 @@ function setup_util() (
 		# prepare APT with APT_KEY
 		if [[ -n $key ]]; then
 			# Deprecated technique is:
-			# fetch ... | sudo-helper -- apt-key add -
+			# fetch ... | eval-helper --elevate -- apt-key add -
 			# Modern and working technique is what we do below...
 			# which improves upon these incomplete and non-working suggestions:
 			# https://blog.jak-linux.org/2021/06/20/migrating-away-apt-key/
@@ -1499,23 +1500,23 @@ function setup_util() (
 			# prepare new location
 			# /usr/share/keyrings - system packagers
 			# /usr/local/share/keyrings - system operator
-			sudo-helper -- mkdir -p --mode=0755 -- /usr/share/keyrings /usr/local/share/keyrings
+			eval-helper --elevate -- mkdir -p --mode=0755 -- /usr/share/keyrings /usr/local/share/keyrings
 			keyring="/usr/local/share/keyrings/$id.gpg"
 
 			# remove old keys if they exist
-			fs-rm --quiet --sudo --no-confirm --optional -- /usr/local/share/keyrings/*"$id"* /etc/apt/trusted.gpg.d/*"$id"*
+			fs-rm --quiet --elevate --no-confirm --optional -- /usr/local/share/keyrings/*"$id"* /etc/apt/trusted.gpg.d/*"$id"*
 
 			# helper for quiet output
 			function do_apt_key_add {
 				# fetch and convert format, then import with export into correct format
-				do_apt_key_fetch "$key" | sudo-helper -- gpg \
+				do_apt_key_fetch "$key" | eval-helper --elevate -- gpg \
 					--no-default-keyring \
 					--keyring="gnupg-ring:$keyring" \
 					--import # uses stdin
 				# [gnupg-ring:] prefix creates keyring in apt compatible (legacy) v4 format
 
 				# adjust permission to fix [_apt access error] on ubuntu 21.10
-				fs-own --sudo --permissions='a+r' -- "$keyring"
+				fs-own --elevate --permissions='a+r' -- "$keyring"
 			}
 			if [[ $option_action != 'uninstall' ]]; then
 				do_apt_key_add
@@ -1525,7 +1526,7 @@ function setup_util() (
 		# prepare APT with APT_REPO
 		if [[ -n $repo ]]; then
 			# remove old listings if they exist
-			fs-rm --quiet --sudo --no-confirm --optional -- /etc/apt/sources.list.d/*"$id"* || :
+			fs-rm --quiet --elevate --no-confirm --optional -- /etc/apt/sources.list.d/*"$id"* || :
 
 			# add the repo with appropriate technique for the repo type
 			if [[ $repo == 'deb '* ]]; then
@@ -1544,7 +1545,7 @@ function setup_util() (
 
 				# use a non-deprecated technique that supports the deb modifiers
 				if [[ $option_action != 'uninstall' ]]; then
-					echo-wait -- "/etc/apt/sources.list.d/$id.list" <<<"$repo"
+					echo-write -- "/etc/apt/sources.list.d/$id.list" <<<"$repo"
 				fi
 			else
 				# @todo consider automatic rewrites to the above
@@ -1554,7 +1555,7 @@ function setup_util() (
 				# [apt-add-repository --help] notes [sudo apt-add-repository -y "$repo"] is deprecated
 				# however the alternative for `ppa:` and other syntax is too complicated
 				if [[ $option_action != 'uninstall' ]]; then
-					sudo-helper -- apt-add-repository -y --enable-source "$repo"
+					eval-helper --elevate -- apt-add-repository -y --enable-source "$repo"
 				fi
 			fi
 
@@ -1564,7 +1565,7 @@ function setup_util() (
 
 		# if we added a new repo or key, we need to refresh the apt references
 		if [[ -n $repo || -n $key ]]; then
-			sudo-helper -- apt-get update -y
+			eval-helper --elevate -- apt-get update -y
 		fi
 
 		# action args
@@ -1604,7 +1605,7 @@ function setup_util() (
 		# packages
 		# use `apt-get`, as `apt` produces this warning on Ubuntu 20.04.3 LTS
 		# WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
-		sudo-helper -- "${args[@]}" "${packages[@]}"
+		eval-helper --elevate -- "${args[@]}" "${packages[@]}"
 	}
 
 	# dpkg / Debian / Ubuntu / Linux Mint / elementary OS / etc
@@ -1670,7 +1671,7 @@ function setup_util() (
 		done
 
 		# packages
-		sudo-helper -- "${args[@]}" "${packages[@]}"
+		eval-helper --elevate -- "${args[@]}" "${packages[@]}"
 	}
 
 	# -------------------------------------
@@ -1728,7 +1729,7 @@ function setup_util() (
 			)
 		fi
 		for repo in "${repos[@]}"; do
-			sudo-helper -- "${args[@]}" "$repo"
+			eval-helper --elevate -- "${args[@]}" "$repo"
 		done
 
 		# args
@@ -1759,7 +1760,7 @@ function setup_util() (
 
 		# packages
 		for package in "${packages[@]}"; do
-			sudo-helper -- "${args[@]}" "$package"
+			eval-helper --elevate -- "${args[@]}" "$package"
 		done
 	}
 	function do_flatpak_fallback {
@@ -1810,7 +1811,7 @@ function setup_util() (
 		fi
 
 		# packages
-		sudo-helper -- "${args[@]}" "${packages[@]}"
+		eval-helper --elevate -- "${args[@]}" "${packages[@]}"
 	}
 
 	# -------------------------------------
@@ -1934,7 +1935,7 @@ function setup_util() (
 		fi
 
 		# packages
-		sudo-helper -- "${args[@]}" "${packages[@]}"
+		eval-helper --elevate -- "${args[@]}" "${packages[@]}"
 	}
 
 	# -------------------------------------
@@ -2020,7 +2021,7 @@ function setup_util() (
 		fi
 
 		# note if brew will cause us to crash
-		if [[ $brew_removal_operation == 'yes' ]] && is-needle --needle='bash' -- "${packages[@]}" && [[ -x "$HOMEBREW_PREFIX/bin/bash" && $BASH_VERSION == "$("$HOMEBREW_PREFIX/bin/bash" -c 'printf "%s" "$BASH_VERSION"')" ]]; then
+		if [[ $brew_removal_operation == 'yes' ]] && __is_within 'bash' 'packages' && [[ -x "$HOMEBREW_PREFIX/bin/bash" && $BASH_VERSION == "$("$HOMEBREW_PREFIX/bin/bash" -c 'printf "%s" "$BASH_VERSION"')" ]]; then
 			# moving the homebrew bash to trash, or a temp directory does not work
 			# as it seems bash requires the invoked bash path to exist, and if it doesn't, it crashes
 			# it is our own script crashing with 137 and not homebrew
@@ -2187,19 +2188,10 @@ function setup_util() (
 
 		# action args
 		if [[ $option_action == 'uninstall' ]]; then
-			args+=(
-				'sudo-helper'
-				'--inherit'
-				'--'
-				'mas'
-				'uninstall'
-			)
+			args+=(eval-helper --elevate --inherit -- mas uninstall)
 		else
 			# install / upgrade
-			args+=(
-				'mas'
-				'install'
-			)
+			args+=(mas install)
 		fi
 
 		# signin, signout, no longer supported
@@ -2296,7 +2288,7 @@ function setup_util() (
 
 		# packages
 		for package in "${packages[@]}"; do
-			sudo-helper -- "${args[@]}" "$package"
+			eval-helper --elevate -- "${args[@]}" "$package"
 		done
 	}
 
@@ -2352,12 +2344,12 @@ function setup_util() (
 		# profiles
 		if [[ ${#profiles[@]} -ne 0 ]]; then
 			for profile in "${profiles[@]}"; do
-				sudo-helper -- nix profile install "$profile"
+				eval-helper --elevate -- nix profile install "$profile"
 			done
 		fi
 
 		# packages
-		sudo-helper -- "${args[@]}" "${packages[@]}"
+		eval-helper --elevate -- "${args[@]}" "${packages[@]}"
 	}
 
 	# -------------------------------------
@@ -2660,19 +2652,19 @@ function setup_util() (
 
 		# copr
 		if [[ ${#copr[@]} -ne 0 ]]; then
-			sudo-helper -- dnf "${opts[@]}" copr enable "${copr[@]}"
+			eval-helper --elevate -- dnf "${opts[@]}" copr enable "${copr[@]}"
 		fi
 
 		# repos
 		if [[ ${#repos[@]} -ne 0 ]]; then
 			# fix https://github.com/bevry/dorothy/actions/runs/7622089094/job/20759534693#step:4:1514
-			sudo-helper -- dnf "${opts[@]}" install 'dnf-command(config-manager)'
-			sudo-helper -- dnf "${opts[@]}" config-manager --add-repo "${repos[@]}"
+			eval-helper --elevate -- dnf "${opts[@]}" install 'dnf-command(config-manager)'
+			eval-helper --elevate -- dnf "${opts[@]}" config-manager --add-repo "${repos[@]}"
 		fi
 
 		# groups
 		if [[ ${#groups[@]} -ne 0 ]]; then
-			sudo-helper -- dnf "${opts[@]}" groupinstall "${groups[@]}"
+			eval-helper --elevate -- dnf "${opts[@]}" groupinstall "${groups[@]}"
 		fi
 
 		# args
@@ -2698,7 +2690,7 @@ function setup_util() (
 
 		# packages
 		if [[ ${#packages[@]} -ne 0 ]]; then
-			sudo-helper -- "${args[@]}" "${packages[@]}"
+			eval-helper --elevate -- "${args[@]}" "${packages[@]}"
 		fi
 	}
 
@@ -2753,7 +2745,7 @@ function setup_util() (
 				# it was not a file, so this is not a suitable combination
 				return 1
 			fi
-			sudo-helper -- "${args[@]}" "$package"
+			eval-helper --elevate -- "${args[@]}" "$package"
 		done
 	}
 
@@ -2802,7 +2794,7 @@ function setup_util() (
 		fi
 
 		# packages
-		sudo-helper -- "${args[@]}" "${packages[@]}"
+		eval-helper --elevate -- "${args[@]}" "${packages[@]}"
 	}
 
 	# yum / rpm / RedHat / Fedora / CentOS / etc
@@ -2884,7 +2876,7 @@ function setup_util() (
 		fi
 
 		# packages
-		sudo-helper -- "${args[@]}" "${packages[@]}"
+		eval-helper --elevate -- "${args[@]}" "${packages[@]}"
 	}
 
 	# zypper / openSUSE / SLES
@@ -2936,16 +2928,16 @@ function setup_util() (
 		# repos
 		if [[ -n $repo ]]; then
 			if [[ -n $alias ]]; then
-				sudo-helper -- zypper "${cmd_opts[@]}" \
+				eval-helper --elevate -- zypper "${cmd_opts[@]}" \
 					addrepo --refresh "$repo" "$alias"
 
-				sudo-helper -- zypper "${cmd_opts[@]}" \
+				eval-helper --elevate -- zypper "${cmd_opts[@]}" \
 					dist-upgrade --auto-agree-with-licenses --no-confirm --from "$alias"
 			else
-				sudo-helper -- zypper "${cmd_opts[@]}" \
+				eval-helper --elevate -- zypper "${cmd_opts[@]}" \
 					addrepo --refresh "$repo"
 
-				sudo-helper -- zypper "${cmd_opts[@]}" \
+				eval-helper --elevate -- zypper "${cmd_opts[@]}" \
 					refresh
 			fi
 		fi
@@ -2980,7 +2972,7 @@ function setup_util() (
 		fi
 
 		# packages
-		sudo-helper -- "${cmd[@]}" "${packages[@]}"
+		eval-helper --elevate -- "${cmd[@]}" "${packages[@]}"
 	}
 
 	# -------------------------------------
@@ -3204,7 +3196,7 @@ function setup_util() (
 			if [[ $option_action == 'uninstall' ]]; then
 				parts=("${parts[0]}") # if uninstalling, trim --classic
 			fi
-			sudo-helper -- "${args[@]}" "${parts[@]}"
+			eval-helper --elevate -- "${args[@]}" "${parts[@]}"
 		done
 
 	}
@@ -3262,7 +3254,7 @@ function setup_util() (
 		fi
 
 		# packages
-		sudo-helper -- "${args[@]}" "${packages[@]}"
+		eval-helper --elevate -- "${args[@]}" "${packages[@]}"
 	}
 
 	# ---------------------------------
@@ -3419,7 +3411,7 @@ function setup_util() (
 		fi
 
 		# packages
-		sudo-helper -- "${args[@]}" "${packages[@]}"
+		eval-helper --elevate -- "${args[@]}" "${packages[@]}"
 	}
 
 	# -------------------------------------
@@ -3559,7 +3551,7 @@ function setup_util() (
 		"${args[@]}" "${packages[@]}"
 
 		# make alias available
-		if [[ -n $option_cli && $option_action == 'install' ]] && __command_missing -- "$option_cli" && command-working --sudo="$option_sudo" -- "$option_cli.exe"; then
+		if [[ -n $option_cli && $option_action == 'install' ]] && __command_missing -- "$option_cli" && command-working --elevate="$option_elevate" -- "$option_cli.exe"; then
 			__mkdirp "$XDG_BIN_HOME"
 			symlink-helper --quiet="$option_quiet" --existing="$(type -P "$option_cli.exe")" --symlink="$XDG_BIN_HOME/$option_cli"
 		fi
@@ -3680,8 +3672,8 @@ function setup_util() (
 
 		# repos
 		for repo in "${repos[@]}"; do
-			sudo-helper -- eselect repository enable "$repo"
-			sudo-helper -- emerge --sync guru
+			eval-helper --elevate -- eselect repository enable "$repo"
+			eval-helper --elevate -- emerge --sync guru
 		done
 
 		# args
@@ -3699,7 +3691,7 @@ function setup_util() (
 
 		# packages
 		for package in "${packages[@]}"; do
-			sudo-helper -- "${args[@]}" "$package"
+			eval-helper --elevate -- "${args[@]}" "$package"
 		done
 	}
 
@@ -3893,7 +3885,7 @@ function setup_util() (
 				elif [[ ${#filtered_paths[@]} -eq 1 ]]; then
 					# move the single file
 					if [[ $option_xdg == 'no' ]]; then
-						sudo-helper -- mv -fv -- "${filtered_paths[@]}" "$target_path"
+						eval-helper --elevate -- mv -fv -- "${filtered_paths[@]}" "$target_path"
 					else
 						mv -fv -- "${filtered_paths[@]}" "$target_path"
 					fi
@@ -3907,7 +3899,7 @@ function setup_util() (
 			# move to target path
 			if [[ -n $download_filepath && $download_filepath != "$target_path" ]]; then
 				if [[ $option_xdg == 'no' ]]; then
-					sudo-helper -- mv -fv -- "$download_filepath" "$target_path"
+					eval-helper --elevate -- mv -fv -- "$download_filepath" "$target_path"
 				else
 					mv -fv -- "$download_filepath" "$target_path"
 				fi
@@ -4185,10 +4177,10 @@ function setup_util() (
 		if [[ $option_quiet == 'yes' ]]; then
 			__do --redirect-stdout=tty -- fc-cache -f
 		else
-			__do --redirect-stdout=tty -- eval_helper --no-wrap --quiet \
+			__do --redirect-stdout=tty -- eval_helper --quiet --wrap \
 				--pending="$(echo-style --bold='Refreshing font cache...')" \
-				--failure="$(echo-style --error='Failed to refresh font cache.')" \
-				-- fc-cache -f -v
+				--failure="$(echo-style --error='Failed to refresh font cache.')" -- \
+				fc-cache -f -v
 		fi
 	fi
 	# determine failure
diff --git a/commands/setup-util-xcode b/commands/setup-util-xcode
--- a/commands/setup-util-xcode
+++ b/commands/setup-util-xcode
@@ -62,19 +62,20 @@ function setup_util_xcode() (
 		function __xcode_license_accepted {
 			# https://stackoverflow.com/a/60906147/130638
 			local xcode_version accepted_license_version
+			# @todo replace with `echo-regexp` and `echo-write`
 			xcode_version="$("$xcodebuild" -version | grep --regexp='^Xcode\s' | "$bin_gsed_or_sed" -E 's/^Xcode[[:space:]]+([0-9\.]+)/\1/' | cut -d '.' -f 1 || :)"
 			accepted_license_version="$(defaults read /Library/Preferences/com.apple.dt.Xcode 2>/dev/null | grep IDEXcodeVersionForAgreedToGMLicense | cut -d '"' -f 2 | cut -d '.' -f 1 || :)"
-			[[ $xcode_version -eq $accepted_license_version ]] || sudo-helper -- "$xcodebuild" -license accept || return
+			[[ $xcode_version -eq $accepted_license_version ]] || eval-helper --elevate -- "$xcodebuild" -license accept || return
 			return
 		}
 		if [[ $option_quiet == 'yes' ]]; then
 			__xcode_license_accepted || continue # try again
 		else
-			eval_helper --shapeshifter --quiet="$option_quiet" --no-wrap \
+			eval_helper --quiet="$option_quiet" --no-wrap --shapeshifter \
 				--pending="$(echo-style --bold="Accepting Xcode license...")" \
 				--success="$(echo-style --success="Accepted Xcode license.")" \
-				--failure="$(echo-style --error="Failed to accept Xcode license.")" \
-				-- __xcode_license_accepted || continue # try again
+				--failure="$(echo-style --error="Failed to accept Xcode license.")" -- \
+				__xcode_license_accepted || continue # try again
 		fi
 
 		# success
