dorothy: lint: fix failure headings for dirs

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -1391,13 +1391,8 @@ function dorothy_() (
 		fi
 
 		# lint with trunk
-		function __traverse() (
-			local path="$1"
-			if [[ ! -d "$path/.trunk" ]]; then
-				return $?
-			fi
+		function __lint() (
 			cd "$path" || return $?
-			__print_style --h3="$intent: $path" || return $?
 			if [[ $format == 'yes' && $check == 'yes' ]]; then
 				# if format fails, it is likely for a check failure, so ensure check is run before crashing
 				trunk fmt --all "${trunk_args[@]}" || __return $? -- trunk check --all "${trunk_args[@]}" || return $?
@@ -1407,8 +1402,20 @@ function dorothy_() (
 			else
 				trunk check --all "${trunk_args[@]}" || return $?
 			fi
-			__print_style --g3="$intent: $path" || return $?
 		)
+		function __traverse {
+			local path="$1"
+			if [[ ! -d "$path/.trunk" ]]; then
+				return 0
+			fi
+			__print_style --h3="$intent: $path" || return $?
+			if __lint; then
+				__print_style --g3="$intent: $path" || return $?
+			else
+				__print_style --e3="$intent: $path" || return $?
+				return 221 # ECUSTOM 221 Tests failed
+			fi
+		}
 		__traverse "$DOROTHY" || __lint_status=$?
 		__traverse "$DOROTHY/user" || __lint_status=$?
 
