bash.bash/dorothy-internals: debug user failures

diff --git a/commands/dorothy-internals b/commands/dorothy-internals
--- a/commands/dorothy-internals
+++ b/commands/dorothy-internals
@@ -1898,31 +1898,62 @@ fi
 
 if __begin_test_block --name='__prepare_(login|current)_(user|uid|group|gid|groups|gids)'; then
 	function tests {
+		function __debug_failure {
+			__print_lines "$@"
+
+			__print_lines 'users:'
+			users || __print_lines "users exit status: $?"
+
+			__print_lines 'who:'
+			who || __print_lines "who exit status: $?"
+
+			__print_lines 'whoami:'
+			whoami || __print_lines "whoami exit status: $?"
+
+			__print_lines 'id:'
+			id || __print_lines "id exit status: $?"
+
+			__print_lines 'id -u:'
+			id -u || __print_lines "id -u exit status: $?"
+
+			__print_lines 'id -g:'
+			id -g || __print_lines "id -g exit status: $?"
+
+			__print_lines 'id -gn:'
+			id -gn || __print_lines "id -gn exit status: $?"
+
+			__print_lines 'id -G:'
+			id -G || __print_lines "id -G exit status: $?"
+
+			__print_lines 'id -Gn:'
+			id -Gn || __print_lines "id -Gn exit status: $?"
+		}
+
 		__prepare_login_user || __print_lines 'Failed to prepare login user'
-		if [[ -n $LOGIN_USER ]]; then __print_lines 'LOGIN_USER is set'; else __print_lines 'LOGIN_USER is not set'; fi
+		if [[ -n $LOGIN_USER ]]; then __print_lines 'LOGIN_USER is set'; else __debug_failure 'LOGIN_USER is not set'; fi
 		__prepare_login_uid || __print_lines 'Failed to prepare login uid'
-		if [[ -n $LOGIN_UID ]]; then __print_lines 'LOGIN_UID is set'; else __print_lines 'LOGIN_UID is not set'; fi
+		if [[ -n $LOGIN_UID ]]; then __print_lines 'LOGIN_UID is set'; else __debug_failure 'LOGIN_UID is not set'; fi
 		__prepare_login_group || __print_lines 'Failed to prepare login group'
-		if [[ -n $LOGIN_GROUP ]]; then __print_lines 'LOGIN_GROUP is set'; else __print_lines 'LOGIN_GROUP is not set'; fi
+		if [[ -n $LOGIN_GROUP ]]; then __print_lines 'LOGIN_GROUP is set'; else __debug_failure 'LOGIN_GROUP is not set'; fi
 		__prepare_login_gid || __print_lines 'Failed to prepare login gid'
-		if [[ -n $LOGIN_GID ]]; then __print_lines 'LOGIN_GID is set'; else __print_lines 'LOGIN_GID is not set'; fi
+		if [[ -n $LOGIN_GID ]]; then __print_lines 'LOGIN_GID is set'; else __debug_failure 'LOGIN_GID is not set'; fi
 		__prepare_login_groups || __print_lines 'Failed to prepare login groups'
-		if [[ -n ${LOGIN_GROUPS[*]} ]]; then __print_lines 'LOGIN_GROUPS is set'; else __print_lines 'LOGIN_GROUPS is not set'; fi
+		if [[ -n ${LOGIN_GROUPS[*]} ]]; then __print_lines 'LOGIN_GROUPS is set'; else __debug_failure 'LOGIN_GROUPS is not set'; fi
 		__prepare_login_gids || __print_lines 'Failed to prepare login gids'
-		if [[ -n ${LOGIN_GIDS[*]} ]]; then __print_lines 'LOGIN_GIDS is set'; else __print_lines 'LOGIN_GIDS is not set'; fi
+		if [[ -n ${LOGIN_GIDS[*]} ]]; then __print_lines 'LOGIN_GIDS is set'; else __debug_failure 'LOGIN_GIDS is not set'; fi
 
 		__prepare_current_user || __print_lines 'Failed to prepare current user'
-		if [[ -n $CURRENT_USER ]]; then __print_lines 'CURRENT_USER is set'; else __print_lines 'CURRENT_USER is not set'; fi
+		if [[ -n $CURRENT_USER ]]; then __print_lines 'CURRENT_USER is set'; else __debug_failure 'CURRENT_USER is not set'; fi
 		__prepare_current_uid || __print_lines 'Failed to prepare current uid'
-		if [[ -n $CURRENT_UID ]]; then __print_lines 'CURRENT_UID is set'; else __print_lines 'CURRENT_UID is not set'; fi
+		if [[ -n $CURRENT_UID ]]; then __print_lines 'CURRENT_UID is set'; else __debug_failure 'CURRENT_UID is not set'; fi
 		__prepare_current_group || __print_lines 'Failed to prepare current group'
-		if [[ -n $CURRENT_GROUP ]]; then __print_lines 'CURRENT_GROUP is set'; else __print_lines 'CURRENT_GROUP is not set'; fi
+		if [[ -n $CURRENT_GROUP ]]; then __print_lines 'CURRENT_GROUP is set'; else __debug_failure 'CURRENT_GROUP is not set'; fi
 		__prepare_current_gid || __print_lines 'Failed to prepare current gid'
-		if [[ -n $CURRENT_GID ]]; then __print_lines 'CURRENT_GID is set'; else __print_lines 'CURRENT_GID is not set'; fi
+		if [[ -n $CURRENT_GID ]]; then __print_lines 'CURRENT_GID is set'; else __debug_failure 'CURRENT_GID is not set'; fi
 		__prepare_current_groups || __print_lines 'Failed to prepare current groups'
-		if [[ -n ${CURRENT_GROUPS[*]} ]]; then __print_lines 'CURRENT_GROUPS is set'; else __print_lines 'CURRENT_GROUPS is not set'; fi
+		if [[ -n ${CURRENT_GROUPS[*]} ]]; then __print_lines 'CURRENT_GROUPS is set'; else __debug_failure 'CURRENT_GROUPS is not set'; fi
 		__prepare_current_gids || __print_lines 'Failed to prepare current gids'
-		if [[ -n ${CURRENT_GIDS[*]} ]]; then __print_lines 'CURRENT_GIDS is set'; else __print_lines 'CURRENT_GIDS is not set'; fi
+		if [[ -n ${CURRENT_GIDS[*]} ]]; then __print_lines 'CURRENT_GIDS is set'; else __debug_failure 'CURRENT_GIDS is not set'; fi
 	}
 	results="$(tests)"
 	__end_test_block {results} "$(
