redo tty target handling
- redo terminal capability handling
    - merge `debug-terminal-stdin` and `debug-terminal-tty` into `debug-terminal` which is simpler, yet more advanced, and clearly showcases and consolidates terminal capaiblities
        - add new `echo-transpose` which is used by `debug-terminal`
    - `ask`/`choose`/`confirm`/`dorothy`/`read-key` correct their capability detection, using the appropriate variable for the capabilities they need
    - `get-terminal-*`: simplify checks
- redo tty and debug target handling
    - `eval-tester` can now and will now test stderr on all environments and tty (before stderr was only locally, not CI/no-TTY envs; and TTY was not able to be tested)
        - `eval-tester` will now also show elapsed time for each test
- add semlock helpers, and consolidated semlock/semaphore functionality
- discover mapfile doesn't support `-d` on bash versions earlier than 4.4
    - introduce WIP `bash.bash:__split` to replace `mapfile` due to this unpatchable deviation
- `down`: tests now work due to these changes
- `eval-helper`: correct `--` hadnling for `--elevate --inherit` commands
- `is-mac`: turns out bash provides `OSTYPE` global var, so there is no need for process invocation
- `is-user:` note some bash globals that could be used instead
- `setup-shell`: correct URL for dash
- `waiter`: add `--message-target=...` support
- `versions.md`: dodcument mapfile, `BASH_XTRACEFD`, `wait`, and other changes
- `bash.bash`:
    - add terminal capabilities
    - add semlock, fd, split, and epoch-time helpers
    - move version number definitions to the top, as they were too late
    - fix bugs in `__get_substring`

diff --git a/commands/dorothy-internals b/commands/dorothy-internals
--- a/commands/dorothy-internals
+++ b/commands/dorothy-internals
@@ -416,7 +416,7 @@ function __end_test_block {
 		expected="$1"
 		shift
 		if [[ $actual != "$expected" ]]; then
-			__print_lines "FAIL: [$actual_var] was [$actual] it should be [$expected]" || return
+			__print_lines "FAIL: [$actual_var]" "== IT WAS == " "$actual" '== IT SHOULD BE ==' "$expected" "== END FAILURE ==" || return
 			result='fail'
 		fi
 	done
@@ -1931,6 +1931,123 @@ if __begin_test_block --name='__get_substring_after_last'; then
 	}
 	substring_results="$(substring_tests)"
 	__end_test_block 'substring_results' $'b\nb\n\n1'
+fi
+
+if __begin_test_block --name='__split'; then
+	function split_tests {
+		local my_array=()
+
+		# @todo trailing delimiters need to matter
+		__print_lines 'split on single character delimiter'
+		__split --target='my_array' --delimiter=':' -- $'0:1:2\n3:4:5'
+		echo-verbose -- "${my_array[@]}"
+
+		__print_lines 'split on multiple character delimiter'
+		__split --target='my_array' --delimiter='::' -- $'0::1::2\n3::4::5'
+		echo-verbose -- "${my_array[@]}"
+
+		__print_lines 'split on multiple delimiters'
+		__split --target='my_array' --delimiter='::' --delimiters=$'!@\n' -- $'0::1:!2\n3@4'
+		echo-verbose -- "${my_array[@]}"
+
+		__print_lines 'split on newline via argument'
+		__split --target='my_array' --delimiter=$'\n' -- $'0\n1\n2'
+		echo-verbose -- "${my_array[@]}"
+
+		__print_lines 'split on newline via process substitution'
+		__split --target='my_array' --delimiter=$'\n' < <(__print_string $'0\n1\n2')
+		echo-verbose -- "${my_array[@]}"
+
+		__print_lines 'split on newline via here string'
+		__split --target='my_array' --delimiter=$'\n' <<<$'0\n1\n2' # <<< injects a trailing newline
+		echo-verbose -- "${my_array[@]}"
+
+		__print_lines 'split on newline via arguments'
+		__split --target='my_array' --delimiter=$'\n' -- 0 $'1' $'2\n' $'3\n\n' $'4' $'\n\n5' $'\n\n6\n\n'
+		echo-verbose -- "${my_array[@]}"
+
+		__print_lines 'split on newline via arguments without zero-length'
+		__split --target='my_array' --no-zero-length --delimiter=$'\n' -- 0 $'1' $'2\n' $'3\n\n' $'4' $'\n\n5' $'\n\n6\n\n'
+		echo-verbose -- "${my_array[@]}"
+
+		__print_lines 'append'
+		__split --target='my_array' --delimiter=$'\n' -- $'1\n2' 3 4
+		__split --target='my_array' --append --delimiter=$'\n' -- $'5\n6' $'7\n8'
+		echo-verbose -- "${my_array[@]}"
+	}
+	split_results="$(split_tests)"
+	__end_test_block 'split_results' "$(
+		cat <<-EOF
+			split on single character delimiter
+			[0] = [0]
+			[1] = [1]
+			[2] = [2
+			3]
+			[3] = [4]
+			[4] = [5]
+			split on multiple character delimiter
+			[0] = [0]
+			[1] = [1]
+			[2] = [2
+			3]
+			[3] = [4]
+			[4] = [5]
+			split on multiple delimiters
+			[0] = [0]
+			[1] = [1:]
+			[2] = [2]
+			[3] = [3]
+			[4] = [4]
+			split on newline via argument
+			[0] = [0]
+			[1] = [1]
+			[2] = [2]
+			split on newline via process substitution
+			[0] = [0]
+			[1] = [1]
+			[2] = [2]
+			split on newline via here string
+			[0] = [0]
+			[1] = [1]
+			[2] = [2]
+			[3] = []
+			split on newline via arguments
+			[0] = [0]
+			[1] = [1]
+			[2] = [2]
+			[3] = []
+			[4] = [3]
+			[5] = []
+			[6] = []
+			[7] = [4]
+			[8] = []
+			[9] = []
+			[10] = [5]
+			[11] = []
+			[12] = []
+			[13] = [6]
+			[14] = []
+			[15] = []
+			split on newline via arguments without zero-length
+			[0] = [0]
+			[1] = [1]
+			[2] = [2]
+			[3] = [3]
+			[4] = [4]
+			[5] = [5]
+			[6] = [6]
+			and append
+			[0] = [0]
+			[1] = [1]
+			[2] = [2]
+			[3] = [3]
+			[4] = [4]
+			[5] = [5]
+			[6] = [6]
+			[7] = [7]
+			[8] = [8]
+		EOF
+	)"
 fi
 
 # -------------------------------------
