convention updates:
- ensure mapfile is required on commands that use it
- use `sudo-helper` instead of `sudo`
- remove outdated todos and comments

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -238,7 +238,7 @@ function dorothy() (
 	# Helpers
 
 	# see commands/command-exists for details
-	function command-exists {
+	function command_exists {
 		local command commands=("$@")
 		for command in "${commands[@]}"; do
 			if type -P "$command" &>/dev/null; then
@@ -251,7 +251,7 @@ function dorothy() (
 	}
 
 	# see commands/command-missing for details
-	function command-missing {
+	function command_missing {
 		local command commands=("$@")
 		for command in "${commands[@]}"; do
 			if type -P "$command" &>/dev/null; then
@@ -263,12 +263,20 @@ function dorothy() (
 		return 1 # all commands are present
 	}
 
-	function try-sudo {
-		if command-exists sudo; then
-			set -x # <inform the user of why they are being prompted for a sudo password>
-			sudo "$@"
-			set +x # </inform>
-		elif command-exists doas; then
+	# see commands/sudo-helper for details
+	function try_sudo {
+		if command_exists sudo; then
+			# check if password is required
+			if sudo --validate --non-interactive &>/dev/null; then
+				# session still active, password not required
+				sudo "$@"
+			else
+				# password is required, let the user know what they are being prompted for
+				echo 'Your sudo/root/login password is required to execute the command:'
+				echo "sudo $*"
+				sudo "$@"
+			fi
+		elif command_exists doas; then
 			set -x # <inform the user of why they are being prompted for a doas password>
 			doas "$@"
 			set +x # </inform>
@@ -277,34 +285,35 @@ function dorothy() (
 		fi
 	}
 
-	function is-mac() {
+	# see commands/is-mac for details
+	function is_mac() {
 		test "$(uname -s)" = "Darwin"
 	}
 
 	function ensure_prereq_dependencies {
 		# dorothy has yet to be installed
-		if command-missing bash curl grep git tput; then
-			if command-exists apt-get; then
+		if command_missing bash curl grep git tput; then
+			if command_exists apt-get; then
 				# for ubuntu
-				try-sudo apt-get update
-				try-sudo apt-get install -y bash curl git
-			elif command-exists apk; then
+				try_sudo apt-get update
+				try_sudo apt-get install -y bash curl git
+			elif command_exists apk; then
 				# for alpine
-				try-sudo apk add bash curl grep git ncurses
-			elif command-exists zypper; then
+				try_sudo apk add bash curl grep git ncurses
+			elif command_exists zypper; then
 				# for opensuse
-				try-sudo zypper install -y --no-recommends bash curl git-core
-			elif command-exists pamac; then
+				try_sudo zypper install -y --no-recommends bash curl git-core
+			elif command_exists pamac; then
 				# for manjaro
-				try-sudo pamac install --no-confirm bash curl git
-			elif command-exists pacman; then
+				try_sudo pamac install --no-confirm bash curl git
+			elif command_exists pacman; then
 				# for arch besides manjaro
-				try-sudo pacman -S --needed --noconfirm bash curl git ncurses
-			elif command-exists yum; then
+				try_sudo pacman -S --needed --noconfirm bash curl git ncurses
+			elif command_exists yum; then
 				# for fedora
-				try-sudo yum install -y bash curl git ncurses
+				try_sudo yum install -y bash curl git ncurses
 			elif test -x "${HOMEBREW_PREFIX-}/bin/brew"; then
-				# for macos, don't use command-exists as dorothy has its own brew helper
+				# for macos, don't use command_exists as dorothy has its own brew helper
 				"${HOMEBREW_PREFIX-}/bin/brew" install bash curl git ncurses
 			else
 				# for everything else
@@ -324,17 +333,17 @@ function dorothy() (
 
 	function ensure_minimal_dependencies {
 		# dorothy is now installed
-		if is-mac; then
+		if is_mac; then
 			setup-util-xcode --quiet
 		fi
 
 		# [github-download] requires [jq]
 		# [set-hostname] requires [sd]
 		# [config-helper] requires [rg], [sd], [teip]
-		if command-missing jq rg sd sd teip; then
+		if command_missing jq rg sd sd teip; then
 			echo-segment --h2="Install required dependencies"
-			if command-exists apt-get; then
-				try-sudo apt-get update
+			if command_exists apt-get; then
+				try_sudo apt-get update
 			fi
 			setup-util-jq --quiet
 			setup-util-ripgrep --quiet
@@ -342,7 +351,7 @@ function dorothy() (
 			setup-util-teip --quiet
 			setup-util-bash --quiet # install last (as depends on above)
 			echo-segment --g2="Install required dependencies"
-		elif is-mac; then
+		elif is_mac; then
 			setup-util-bash --quiet
 		fi
 
@@ -727,9 +736,9 @@ function dorothy() (
 					--question="Where do you want to store your Dorothy user configuration?" \
 					-- github gitlab custom 'local'
 			)"
-			if test "$where" = 'github' && command-exists gh; then
+			if test "$where" = 'github' && command_exists gh; then
 				cli='gh'
-			elif test "$where" = 'gitlab' && command-exists glab; then
+			elif test "$where" = 'gitlab' && command_exists glab; then
 				cli='glab'
 			fi
 			if test "$where" = 'github' -o "$where" = 'gitlab'; then
@@ -1104,7 +1113,7 @@ function dorothy() (
 		ensure_minimal_dependencies
 
 		# compatibility
-		if command-missing "$shell"; then
+		if command_missing "$shell"; then
 			echo-error "$shell is not available on this system"
 			return 3 # ESRCH 3 No such process
 		fi
@@ -1370,7 +1379,7 @@ function dorothy() (
 		# able to test on bash v3?
 		local bash bashv3=''
 		bash="$(command -v bash)"
-		if is-mac && test "$bash" != '/bin/bash' && [[ "$(/bin/bash --version || :)" == 'GNU bash, version 3.'* ]]; then
+		if is_mac && test "$bash" != '/bin/bash' && [[ "$(/bin/bash --version || :)" == 'GNU bash, version 3.'* ]]; then
 			bashv3='/bin/bash'
 		fi
 
