dorothy: update trunk args
reproduces the crash locally, and therefor ignore trunk fmt failures

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -1397,7 +1397,7 @@ function dorothy_() (
 		fi
 
 		# adjust for ci
-		local trunk_args=()
+		local trunk_args=('--all' '--cache=false' '--ignore-git-state' '--print-failures')
 		if [[ -n $CI ]]; then
 			trunk_args+=('--ci' '--no-progress')
 		fi
@@ -1409,15 +1409,21 @@ function dorothy_() (
 			# if format fails, it is likely for a check failure
 			# `--ignore-git-state` is necessary to prevent trunk shfmt bugs
 			if [[ $format == 'yes' && $check == 'yes' ]]; then
-				if trunk fmt --all --ignore-git-state "${trunk_args[@]}"; then
+				if trunk fmt "${trunk_args[@]}"; then
 					return 0
 				else
-					trunk check --all "${trunk_args[@]}" || return $?
+					# only fail if check fails, as trunk's shfmt implementation is buggy (see later note)
+					trunk check "${trunk_args[@]}" || return $?
 				fi
 			elif [[ $format == 'yes' ]]; then
-				trunk fmt --all --ignore-git-state "${trunk_args[@]}" || return $?
+				# ignore format failures, as trunk's shfmt implementation is buggy, and crashes with
+				# ```
+				# A tool failed to run. You can open the details yaml file for more information.
+				# absl::container_internal::raw_hash_map<>::at
+				# ```
+				trunk fmt "${trunk_args[@]}" || :
 			else
-				trunk check --all "${trunk_args[@]}" || return $?
+				trunk check "${trunk_args[@]}" || return $?
 			fi
 		)
 		function __traverse {
