ci: lint, and work around trunk fmt crashes

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -1404,13 +1404,23 @@ function dorothy_() (
 
 		# lint with trunk
 		function __lint() (
+			local __status=0
 			cd "$path" || return $?
+			# if format fails, it is likely for a source format failure (in which try again if formatted), otherwise a check failure
 			if [[ $format == 'yes' && $check == 'yes' ]]; then
-				# if format fails, it is likely for a check failure, so ensure check is run before crashing
-				trunk fmt --all "${trunk_args[@]}" || __return $? -- trunk check --all "${trunk_args[@]}" || return $?
-				trunk check --all "${trunk_args[@]}" || return $?
+				if trunk fmt --all "${trunk_args[@]}"; then
+					return 0
+				elif trunk fmt "${trunk_args[@]}" -- "$DOROTHY/sources/"* && trunk fmt --all "${trunk_args[@]}"; then
+					return 0
+				else
+					trunk check --all "${trunk_args[@]}" || return $?
+				fi
 			elif [[ $format == 'yes' ]]; then
-				trunk fmt --all "${trunk_args[@]}" || return $?
+				if trunk fmt --all "${trunk_args[@]}"; then
+					return 0
+				else
+					{ trunk fmt "${trunk_args[@]}" -- "$DOROTHY/sources/"* && trunk fmt --all "${trunk_args[@]}"; } || return $?
+				fi
 			else
 				trunk check --all "${trunk_args[@]}" || return $?
 			fi
