dorothy: fix bad fix of #166
/ref 4e415959ab6af6dcf069050aabbbd36299109312

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -53,7 +53,7 @@ function dorothy() (
 		}
 	fi
 
-	# see commands/command-exists for details
+	# see commands/command_exists for details
 	function command_exists { # 👍 /docs/bash/errors: robust exit status
 		local command commands=("$@")
 		for command in "${commands[@]}"; do
@@ -106,8 +106,13 @@ function dorothy() (
 		test "$(uname -s)" = "Darwin"
 	}
 
+	# see commands/is-linux for details
+	function is_mac { # 👍 /docs/bash/errors: robust exit status
+		test "$(uname -s)" = "Linux"
+	}
+
 	# see commands/fs-realpath for details
-	function fs_realpath {
+	function fs_realpath { # 👍 /docs/bash/errors: robust exit status
 		# options
 		local item paths=()
 		while test "$#" -ne 0; do
@@ -126,26 +131,26 @@ function dorothy() (
 		done
 
 		local gnu_realpath=''
-		if command-exists grealpath; then
+		if command_exists grealpath; then
 			gnu_realpath='grealpath'
-		elif command-exists realpath && is-linux; then
+		elif command_exists realpath && is_linux; then
 			gnu_realpath='realpath'
 		fi
 
 		local gnu_readlink=''
-		if command-exists greadlink; then
+		if command_exists greadlink; then
 			gnu_readlink='greadlink'
-		elif command-exists readlink && is-linux; then
+		elif command_exists readlink && is_linux; then
 			gnu_readlink='readlink'
 		fi
 
 		local macos_readlink=''
-		if command-exists readlink && is-mac; then
+		if command_exists readlink && is_mac; then
 			macos_readlink='readlink'
 		fi
 
 		local macos_realpath=''
-		if command-exists realpath && is-mac; then
+		if command_exists realpath && is_mac; then
 			macos_realpath='realpath'
 		fi
 
@@ -153,17 +158,17 @@ function dorothy() (
 		local path
 		for path in "${paths[@]}"; do
 			if test -n "$gnu_realpath"; then
-				"$gnu_realpath" --canonicalize-existing "$path"
+				"$gnu_realpath" --canonicalize-existing "$path" || return
 			elif test -n "$gnu_readlink"; then
-				"$gnu_readlink" --canonicalize-existing "$path"
+				"$gnu_readlink" --canonicalize-existing "$path" || return
 			elif test -n "$macos_readlink"; then
-				"$macos_readlink" -f "$path"
+				"$macos_readlink" -f "$path" || return
 			elif test -n "$macos_realpath"; then
-				"$macos_realpath" "$path"
+				"$macos_realpath" "$path" || return
 			elif command_exists fish; then
 				# this isn't --validate, but it is a last resort
 				# trunk-ignore(shellcheck/SC2016)
-				fish -c 'builtin realpath "$argv[1]"' -- "$path"
+				fish -c 'builtin realpath "$argv[1]"' -- "$path" || return
 			else
 				print_line 'Dorothy requires readlink or realpath to be installed. https://github.com/bevry/dorothy#install' >/dev/stderr
 				return 6 # ENXIO 6 Device not configured
