eval-tester: attempt at fixing window ci failures
they seem related to `fs-diff` running on process substitutions instead of actual files

diff --git a/commands/dorothy-internals b/commands/dorothy-internals
--- a/commands/dorothy-internals
+++ b/commands/dorothy-internals
@@ -124,6 +124,13 @@ fi
 # =====================================
 # Handle Arguments
 
+function __crash_malformed {
+	exit 222 # ECUSTOM 222 Tests malformed
+}
+function __crash_broken {
+	exit 223 # ECUSTOM 223 Tests broken
+}
+
 function __render_csv {
 	if [[ $render_csv == 'no' ]]; then
 		return 0
@@ -243,7 +250,7 @@ if [[ ${#option_binaries[@]} -ne 0 ]]; then
 	__result_status=0
 	debug-bash --binaries="$(__print_lines "${option_binaries[@]}")" --no-wrap --continue -- \
 		dorothy-internals --skip="$(__print_lines "${option_skip[@]}")" --only="$(__print_lines "${option_only[@]}")" --csv="$option_csv" --csv="$option_csv_file" -- "${option_implementations[@]}" || __result_status=$?
-	__render_csv || exit 223
+	__render_csv || __crash_broken
 	exit "$__result_status"
 fi
 # we are now a single bash version
@@ -321,15 +328,15 @@ function __begin_test_block {
 			had_crash_stdout='yes'
 			option_crash_stdout="${item#*=}"
 			;;
-		--*) __unrecognised_flag "$item" || exit 223 ;;
-		*) __unrecognised_argument "$item" || exit 223 ;;
+		--*) __unrecognised_flag "$item" || __crash_broken ;;
+		*) __unrecognised_argument "$item" || __crash_broken ;;
 		esac
 	done
 
 	# ensure we have a name
 	if [[ -z $option_name ]]; then
-		__print_lines "ERROR: __begin_test_block: A name was not provided" >&2 || exit 223
-		exit 222
+		__print_lines "ERROR: __begin_test_block: A name was not provided" >&2 || __crash_broken
+		__crash_malformed
 	fi
 
 	# verify all test data is as expected
@@ -391,20 +398,20 @@ function __begin_test_block {
 		__crash_exit_status=$?
 		set -e
 		# we want to trim trailing newlines for consistency with bash, __do, and eval-tester
-		crash_stdout="$(<"$crash_stdout_file")" || exit 223
-		rm -f -- "$crash_stdout_file" || exit 223
+		crash_stdout="$(<"$crash_stdout_file")" || __crash_broken
+		rm -f -- "$crash_stdout_file" || __crash_broken
 
 		# @todo delegate the below to __end_test_block ???
 
 		# compare status
 		if [[ -n $option_crash_exit_status && $__crash_exit_status -ne $option_crash_exit_status ]]; then
 			crash_ok=no
-			echo-style --stderr --red --bold='Crashed Exit Status' ' ' --="$__crash_exit_status" ' ' --bold='Expected Exit Status:' ' ' --invert="$option_crash_exit_status" || exit 223
+			echo-style --stderr --red --bold='Crashed Exit Status' ' ' --="$__crash_exit_status" ' ' --bold='Expected Exit Status:' ' ' --invert="$option_crash_exit_status" || __crash_broken
 		elif [[ $__crash_exit_status -eq 0 ]]; then
 			crash_ok=no
-			echo-style --stderr --green --bold='Crashed Exit Status:' ' ' --invert="$__crash_exit_status" ' ' --bold='Expected Exit Status:' ' ' --invert="<non-zero>" || exit 223
+			echo-style --stderr --green --bold='Crashed Exit Status:' ' ' --invert="$__crash_exit_status" ' ' --bold='Expected Exit Status:' ' ' --invert="<non-zero>" || __crash_broken
 		else
-			echo-style --stderr --green --bold='Crashed Exit Status:' ' ' --invert="$__crash_exit_status" ' ' --bold='Expected Exit Status:' ' ' --invert="<non-zero>" || exit 223
+			echo-style --stderr --green --bold='Crashed Exit Status:' ' ' --invert="$__crash_exit_status" ' ' --bold='Expected Exit Status:' ' ' --invert="<non-zero>" || __crash_broken
 		fi
 
 		# compare crash stdout
@@ -417,9 +424,9 @@ function __begin_test_block {
 			fi
 			if [[ $crash_stdout != "$option_crash_stdout" ]]; then
 				crash_ok=no
-				echo-style --stderr --red --bold='Crashed STDOUT:' ' ' --invert="$crash_stdout" --newline --bold='Expected STDOUT:' ' ' --invert="$option_crash_stdout" || exit 223
+				echo-style --stderr --red --bold='Crashed STDOUT:' ' ' --invert="$crash_stdout" --newline --bold='Expected STDOUT:' ' ' --invert="$option_crash_stdout" || __crash_broken
 			else
-				echo-style --stderr --green --bold='Crashed STDOUT:' ' ' --invert="$crash_stdout" --newline --bold='Expected STDOUT:' ' ' --invert="$option_crash_stdout" || exit 223
+				echo-style --stderr --green --bold='Crashed STDOUT:' ' ' --invert="$crash_stdout" --newline --bold='Expected STDOUT:' ' ' --invert="$option_crash_stdout" || __crash_broken
 			fi
 		fi
 
@@ -427,11 +434,11 @@ function __begin_test_block {
 		if [[ $crash_ok == yes ]]; then
 			TESTS_OK+=("$TEST_NAME")
 			CSV_UPDATES+="$option_implementation,$SUITE_NAME,$TEST_NAME,crash ok"$'\n'
-			echo-style --stderr --g2="$TEST_NAME" ' ' --success='crash ok' || exit 223
+			echo-style --stderr --g2="$TEST_NAME" ' ' --success='crash ok' || __crash_broken
 		else
 			TESTS_FAIL+=("$TEST_NAME")
 			CSV_UPDATES+="$option_implementation,$SUITE_NAME,$TEST_NAME,CRASH DIVERGED"$'\n'
-			echo-style --stderr --e2="$TEST_NAME" ' ' --error='CRASH DIVERGED' || exit 223
+			echo-style --stderr --e2="$TEST_NAME" ' ' --error='CRASH DIVERGED' || __crash_broken
 		fi
 
 		# now that the result is noted, remove from pending
@@ -442,13 +449,13 @@ function __begin_test_block {
 	fi
 
 	# run the test in this context
-	echo-style --stderr --h2="$TEST_NAME" || exit 223
+	echo-style --stderr --h2="$TEST_NAME" || __crash_broken
 }
 function __end_test_block {
 	# runs once the test is ended, but not on crash test ending
 	local ok='yes' actual_var actual expected actual_file expected_file
 	while [[ $# -ne 0 ]]; do
-		__dereference --origin="$1" --name={actual_var} || exit 223
+		__dereference --origin="$1" --name={actual_var} || __crash_broken
 		actual="${!actual_var-}"
 		shift
 		expected="$1"
@@ -460,12 +467,12 @@ function __end_test_block {
 				"$actual" \
 				$'\e[7m''== IT SHOULD BE =='$'\e[0m' \
 				"$expected" \
-				$'\e[7m'"== END FAILURE =="$'\e[0m' || exit 223
+				$'\e[7m'"== END FAILURE =="$'\e[0m' || __crash_broken
 			actual_file="$(fs-temp --directory='dorothy-internals' --file)"
 			expected_file="$actual_file.expected"
 			actual_file="$actual_file.actual"
-			__print_string "$actual" >"$actual_file" || exit 223
-			__print_string "$expected" >"$expected_file" || exit 223
+			__print_string "$actual" >"$actual_file" || __crash_broken
+			__print_string "$expected" >"$expected_file" || __crash_broken
 			fs-diff --unchanged --before="$actual_file" --after="$expected_file" || :
 			ok='no'
 		fi
@@ -474,11 +481,11 @@ function __end_test_block {
 	if [[ $ok == 'yes' ]]; then
 		TESTS_OK+=("$TEST_NAME")
 		CSV_UPDATES+="$option_implementation,$SUITE_NAME,$TEST_NAME,ok"$'\n'
-		echo-style --stderr --g2="$TEST_NAME" || exit 223
+		echo-style --stderr --g2="$TEST_NAME" || __crash_broken
 	else
 		TESTS_FAIL+=("$TEST_NAME")
 		CSV_UPDATES+="$option_implementation,$SUITE_NAME,$TEST_NAME,FAIL"$'\n'
-		echo-style --stderr --e2="$TEST_NAME" || exit 223
+		echo-style --stderr --e2="$TEST_NAME" || __crash_broken
 	fi
 	# now that the result is noted, remove from pending
 	__complete_test_block || exit
@@ -487,31 +494,31 @@ function __complete_test_block {
 	# run once the test is ended, and on crash test ending
 	# ensure we are still relevant
 	if [[ -z $TEST_NAME ]]; then
-		echo-style --stderr --error="ERROR: ${FUNCNAME[0]}: Cannot complete a test block that has already cleaned itself up." || exit 223
-		return 222 # ECUSTOM 222 Tests malformed
+		echo-style --stderr --error="ERROR: ${FUNCNAME[0]}: Cannot complete a test block that has already cleaned itself up." || __crash_broken
+		__crash_malformed
 	fi
 	# remove the test from pending
 	local last
 	local -i count=${#TESTS_PENDING[@]} last_index
 	last_index=$((count - 1))
 	if [[ $count -eq 0 ]]; then
-		echo-style --stderr --error="ERROR: ${FUNCNAME[0]}: The test name $(__dump --value="$TEST_NAME" || :) has finished but it was not inside pending..." || exit 223
-		__dump {TESTS_PENDING} >&2 || exit 223
-		return 222 # ECUSTOM 222 Tests malformed
+		echo-style --stderr --error="ERROR: ${FUNCNAME[0]}: The test name $(__dump --value="$TEST_NAME" || :) has finished but it was not inside pending..." || __crash_broken
+		__dump {TESTS_PENDING} >&2 || __crash_broken
+		__crash_malformed
 	elif [[ $count -ne 1 ]]; then
-		echo-style --stderr --error="ERROR: ${FUNCNAME[0]}: The test name $(__dump --value="$TEST_NAME" || :) has finished but there were more than one pending test..." || exit 223
-		__dump {TESTS_PENDING} >&2 || exit 223
-		return 222 # ECUSTOM 222 Tests malformed
+		echo-style --stderr --error="ERROR: ${FUNCNAME[0]}: The test name $(__dump --value="$TEST_NAME" || :) has finished but there were more than one pending test..." || __crash_broken
+		__dump {TESTS_PENDING} >&2 || __crash_broken
+		__crash_malformed
 	else
 		last="${TESTS_PENDING[last_index]}"
 		if [[ $last == "$TEST_NAME" ]]; then
 			TEST_NAME=''
 			TESTS_PENDING=("${TESTS_PENDING[@]:0:last_index}")
 		else
-			echo-style --stderr --error="ERROR: ${FUNCNAME[0]}: The test name $(__dump --value="$TEST_NAME" || :) does not match the last pending test name of $(__dump --value="$last")" || exit 223
+			echo-style --stderr --error="ERROR: ${FUNCNAME[0]}: The test name $(__dump --value="$TEST_NAME" || :) does not match the last pending test name of $(__dump --value="$last")" || __crash_broken
 
-			__dump {TESTS_PENDING} >&2 || exit 223
-			return 222 # ECUSTOM 222 Tests malformed
+			__dump {TESTS_PENDING} >&2 || __crash_broken
+			__crash_malformed
 		fi
 	fi
 	# verify all test data is as expected
@@ -521,20 +528,20 @@ function __verify_test_blocks {
 	local -i count_tests="${#TESTS[@]}" count_pending="${#TESTS_PENDING[@]}" count_ok="${#TESTS_OK[@]}" count_fail="${#TESTS_FAIL[@]}" count_skip="${#TESTS_SKIP[@]}" count_finished
 	count_finished=$((count_ok + count_fail + count_skip))
 	if [[ -n $TEST_NAME ]]; then
-		echo-style --stderr --e2="$TEST_NAME" ' ' --error='PENDING' || exit 223
+		echo-style --stderr --e2="$TEST_NAME" ' ' --error='PENDING' || __crash_broken
 		CSV_UPDATES+="$option_implementation,$SUITE_NAME,$TEST_NAME,PENDING"$'\n'
 		return 221 # ECUSTOM 221 Tests failed
 	fi
 	if [[ $count_pending -ne 0 ]]; then
 		local pending_test_name
 		for pending_test_name in "${TESTS_PENDING[@]}"; do
-			echo-style --stderr --e2="$pending_test_name" ' ' --error='INCOMPLETE' || exit 223
+			echo-style --stderr --e2="$pending_test_name" ' ' --error='INCOMPLETE' || __crash_broken
 			CSV_UPDATES+="$option_implementation,$SUITE_NAME,$pending_test_name,INCOMPLETE"$'\n'
 		done
 		return 221 # ECUSTOM 221 Tests failed
 	fi
 	if [[ $count_tests -ne $count_finished ]]; then
-		echo-style --stderr --e2="$SUITE_NAME" ' ' --status="$exit_status" ' ' --error='UNFINISHED' || exit 223
+		echo-style --stderr --e2="$SUITE_NAME" ' ' --status="$exit_status" ' ' --error='UNFINISHED' || __crash_broken
 		CSV_UPDATES+="$option_implementation,$SUITE_NAME,$SUITE_NAME,UNFINISHED"$'\n'
 		return 221 # ECUSTOM 221 Tests failed
 	fi
@@ -565,12 +572,12 @@ function __on_exit {
 			CSV_UPDATES+="$option_implementation,$SUITE_NAME,$count_message,ok"$'\n'
 		fi
 		if [[ -n $option_csv_file ]]; then
-			__print_string "$CSV_UPDATES" >>"$option_csv_file" || exit 223
+			__print_string "$CSV_UPDATES" >>"$option_csv_file" || __crash_broken
 		fi
 	fi
 
 	# finish
-	__render_csv || exit 223
+	__render_csv || __crash_broken
 }
 
 # write everything at once on exit, as writing as it happens causes corruption
diff --git a/commands/eval-tester b/commands/eval-tester
--- a/commands/eval-tester
+++ b/commands/eval-tester
@@ -137,75 +137,77 @@ function eval_tester() (
 	function __element {
 		local label="$1" style="$2" value="$3"
 		if [[ -n $value ]]; then
-			echo-style --"$style"+element="$label" --newline --="$value" --newline --"$style"+/element="$label"
+			echo-style --"$style"+element="$label" --newline --="$value" --newline --"$style"+/element="$label" || return 223 # ECUSTOM 223 Tests broken
 		else
-			echo-style --"$style"+element/="$label" --commentary-empty
+			echo-style --"$style"+element/="$label" --commentary-empty || return 223 # ECUSTOM 223 Tests broken
 		fi
 	}
 	function __escaped_element {
 		local label="$1" style="$2" value="$3"
 		if [[ -n $value ]]; then
-			__element "$label escaped" "$style" "$(printf '%q' "$value")"
+			__element "$label escaped" "$style" "$(printf '%q' "$value")" || return
 		else
-			echo-style --"$style"+element/="$label escaped" --commentary-empty
+			echo-style --"$style"+element/="$label escaped" --commentary-empty || return 223 # ECUSTOM 223 Tests broken
 		fi
 	}
 	function __compare {
-		local name="$1" actual="$2" expected="$3" diff
+		local name="$1" actual="$2" expected="$3"
 		if [[ $option_quiet == 'no' && $name == 'STATUS' ]]; then
-			__print_line
+			__print_line || return 223 # ECUSTOM 223 Tests broken
 		fi
 		if [[ $name == 'STDERR' && -n $stderr_unable_reason ]]; then
-			echo-style --stderr --notice="$stderr_unable_reason"
+			echo-style --stderr --notice="$stderr_unable_reason" || return 223 # ECUSTOM 223 Tests broken
 		elif [[ $name == 'STATUS' ]]; then
 			if [[ $expected == "$ignore_value" ]]; then
-				echo-style --note="${name} is IGNORED [$actual]"
+				echo-style --note="${name} is IGNORED [$actual]" || return 223 # ECUSTOM 223 Tests broken
 			elif [[ $actual == "$expected" ]]; then
-				echo-style --success="${name} is EXPECTED [$expected]"
+				echo-style --success="${name} is EXPECTED [$expected]" || return 223 # ECUSTOM 223 Tests broken
 			else
-				echo-style --error="${name} [$actual] is NOT EXPECTED [$expected]"
+				echo-style --error="${name} [$actual] is NOT EXPECTED [$expected]" || return 223 # ECUSTOM 223 Tests broken
 			fi
 		elif [[ $expected == "$ignore_value" ]]; then
-			echo-style --note="${name} is IGNORED"
+			echo-style --note="${name} is IGNORED" || return 223 # ECUSTOM 223 Tests broken
 			if [[ $option_quiet == 'no' ]]; then
 				if ! __is_shapeshifter -- "$actual"; then
-					__element "$name" blue "$actual"
+					__element "$name" blue "$actual" || return
 				fi
 				if [[ $actual =~ [[:cntrl:]] ]]; then
-					__escaped_element "$name" blue "$actual"
+					__escaped_element "$name" blue "$actual" || return
 				fi
 			fi
 		else
 			if [[ $actual == "$expected" ]]; then
-				echo-style --success="${name} is EXPECTED"
+				echo-style --success="${name} is EXPECTED" || return 223 # ECUSTOM 223 Tests broken
 				if [[ $option_quiet == 'no' ]]; then
 					if ! __is_shapeshifter -- "$actual"; then
-						__element "$name" green "$actual"
+						__element "$name" green "$actual" || return
 					fi
 					if [[ $actual =~ [[:cntrl:]] ]]; then
-						__escaped_element "$name" green "$actual"
+						__escaped_element "$name" green "$actual" || return
 					fi
 				fi
 			else
-				echo-style --error="${name} is NOT EXPECTED"
+				echo-style --error="${name} is NOT EXPECTED" || return 223 # ECUSTOM 223 Tests broken
 				if ! __is_shapeshifter -- "$actual$expected"; then
-					__element "actual $name" red "$actual"
-					__element "expected $name" red "$expected"
+					__element "actual $name" red "$actual" || return
+					__element "expected $name" red "$expected" || return
 				fi
 				if [[ $actual$expected =~ [[:cntrl:]] ]]; then
-					__escaped_element "actual $name" red "$actual"
-					__escaped_element "expected $name" red "$expected"
+					__escaped_element "actual $name" red "$actual" || return
+					__escaped_element "expected $name" red "$expected" || return
 				fi
-				diff="$(
-					fs-diff --unchanged \
-						--before=<(__print_string "$actual") \
-						--after=<(__print_string "$expected") || :
-				)"
-				__element "diff $name" red "$diff"
+				local diff actual_file expected_file
+				actual_file="$(fs-temp --directory='eval-tester' --file)" || return 223 # ECUSTOM 223 Tests broken
+				expected_file="$actual_file.expected"
+				actual_file="$actual_file.actual"
+				__print_string "$actual" >"$actual_file" || return 223     # ECUSTOM 223 Tests broken
+				__print_string "$expected" >"$expected_file" || return 223 # ECUSTOM 223 Tests broken
+				diff="$(fs-diff --unchanged --before="$actual_file" --after="$expected_file" || :)"
+				__element "diff $name" red "$diff" || return
 			fi
 		fi
 		if [[ $option_quiet == 'no' && $name != 'TTY' ]]; then
-			__print_line
+			__print_line || return 223 # ECUSTOM 223 Tests broken
 		fi
 	}
 
@@ -301,7 +303,7 @@ function eval_tester() (
 	# pass or fail
 	if [[ $FAIL == 'yes' ]]; then
 		echo-style --e2="$title" ' ' --code="in $time seconds" $'\n'
-		return 1
+		return 221 # ECUSTOM 221 Tests failed
 	else
 		echo-style --g2="$title" ' ' --code="in $time seconds" $'\n'
 	fi
