dorothy: fix help formatting

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -135,9 +135,9 @@ function dorothy_() (
 			    If a shell is provided, invoke Dorothy within that shell, otherwise prompt for which REPL-supported shell to use.
 
 			dorothy run
-				-- <command> [...]
+			  -- <command> [...]
 
-				Invoke the <command> within the Dorothy environment, without the need to install Dorothy to access the command.
+			    Invoke the <command> within the Dorothy environment, without the need to install Dorothy to access the command.
 
 			dorothy update
 
@@ -198,7 +198,7 @@ function dorothy_() (
 		EOF
 		if [[ $# -ne 0 ]]; then
 			# use printf, as __print_line not loaded yet
-			printf '%s' "ERROR: $*" >&2
+			printf '\nERROR:\n%s\n' "$*" >&2
 		fi
 		return 22 # EINVAL 22 Invalid argument
 	}
