dorothy: test: rerun failed tests with debugging

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -1489,6 +1489,7 @@ function dorothy() (
 
 			# run the bash test
 			eval-helper --no-quiet --wrap -- "$bash" "$filepath" --test || {
+				eval-helper --no-quiet --wrap -- "$bash" -vx "$filepath" --test || :
 				failures+=("$bash" "$filepath" --test)
 			}
 
@@ -1500,6 +1501,7 @@ function dorothy() (
 			# run the bash v3 test
 			if test -n "$bashv3"; then
 				eval-helper --no-quiet --wrap -- "$bashv3" "$filepath" --test || {
+					eval-helper --no-quiet --wrap -- "$bashv3" -vx "$filepath" --test || :
 					failures+=("$bashv3" "$filepath" --test)
 				}
 			fi
@@ -1507,7 +1509,7 @@ function dorothy() (
 
 		# check for failures
 		if test "${#failures[@]}" -ne 0; then
-			echo-style --error='Following tests were failures:'
+			echo-style --error='The following tests were failures:'
 			echo-lines "${failures[@]}"
 			echo-segment --e1='Dorothy Tests'
 			return 1
