do: trailing-newlines now opt-in to mimic bash
this fixes the failing `ask` test, which was happening because capturing the `choose` output via `do` was leaving a trailing newline

other changes:

- dorothy-internals: add `do` redirection tests
- *: remove BASH_XTRACEFD modification as it didn't work
- *: rename `BASH_DEBUG` to `DOROTHY_DEBUG` and limit to our debug messaging
- *: trace functionality is now `set -xv` instead of just `set -x`
- dorothy: only check for leftovers on CI

diff --git a/commands/dorothy-internals b/commands/dorothy-internals
--- a/commands/dorothy-internals
+++ b/commands/dorothy-internals
@@ -324,7 +324,8 @@ function __begin_test_block {
 	fi
 
 	# check the prior test is ok
-	__dump {COUNT_TESTS} {COUNT_OK} {COUNT_FAIL} {TEST_NAME} >&2
+	# @todo improve this
+	# __dump {COUNT_TESTS} {COUNT_OK} {COUNT_FAIL} {TEST_NAME} >&2
 
 	# apply and reset shared vars
 	TEST_NAME="$option_name"
@@ -354,8 +355,9 @@ function __begin_test_block {
 		dorothy-internals --only="$TEST_NAME" --csv=no --implementation="$option_implementation" --version="$BASH" >"$crash_stdout_file"
 		__crash_exit_status=$?
 		set -e
-		__read_whole <"$crash_stdout_file" || return
-		crash_stdout="$REPLY"
+		# __read_whole <"$crash_stdout_file" || return
+		# crash_stdout="$REPLY"
+		crash_stdout="$(<"$crash_stdout_file")" || return # we want to trim trailing newlines for consistency with bash, __do, and eval-tester
 		rm -f -- "$crash_stdout_file"
 		# compare status
 		if [[ -n $option_crash_exit_status && $__crash_exit_status -ne $option_crash_exit_status ]]; then
@@ -843,15 +845,15 @@ if __begin_test_block --name='__dump'; then
 fi
 
 # can't test this otherwise
-if [[ $BASH_XTRACEFD -eq 2 ]]; then
+if [[ ${BASH_XTRACEFD:-"2"} -eq 2 ]]; then
 	if __begin_test_block --name='__debug_lines'; then
 		function tests() (
-			BASH_DEBUG=
+			DOROTHY_DEBUG=
 			__debug_lines
 			__debug_lines ''
 			__debug_lines a
 			__debug_lines a b
-			BASH_DEBUG=yes
+			DOROTHY_DEBUG=yes
 			__debug_lines
 			__debug_lines ''
 			__debug_lines a
@@ -1510,6 +1512,9 @@ fi
 # =====================================
 # Redirection & Error Handling Toolkit
 
+# -------------------------------------
+# __to
+
 if __begin_test_block --name='__to'; then
 	function tests() (
 		set +e
@@ -1603,6 +1608,36 @@ if __begin_test_block --name='__to'; then
 		EOF
 	)"
 fi
+
+# -------------------------------------
+# __try and __do: test their exit status handling, which requires overrides to monitor complexities
+
+function dorothy_try__context_lines {
+	printf '%s\n' "CONTEXT: $DOROTHY_TRY__CONTEXT" "COMMAND: ${DOROTHY_TRY__COMMAND[*]}" >&2
+	printf '         %s\n' "$@" >&2
+}
+
+function dorothy_try__dump_lines {
+	__print_lines "$@" \
+		"DOROTHY_TRY__COUNT    = ${DOROTHY_TRY__COUNT-}" \
+		"DOROTHY_TRY__STATUS   = ${DOROTHY_TRY__STATUS-}" \
+		"DOROTHY_TRY__CONTEXT  = ${DOROTHY_TRY__CONTEXT-}" \
+		"DOROTHY_TRY__COMMAND  = ${DOROTHY_TRY__COMMAND:+"${DOROTHY_TRY__COMMAND[*]}"}" \
+		"DOROTHY_TRY__SUBSHELL = ${DOROTHY_TRY__SUBSHELL-}" \
+		"BASH_SOURCE           = ${BASH_SOURCE[*]}" \
+		"BASH_LINENO           = ${BASH_LINENO[*]}" \
+		"LINENO                = ${LINENO}" \
+		"FUNCNAME              = ${FUNCNAME[*]}" \
+		"CHILD_MAX             = ${CHILD_MAX-}" \
+		"SHLVL                 = ${SHLVL-}" \
+		"BASH_SUBSHELL         = ${BASH_SUBSHELL-}" \
+		"BASH_COMMAND          = ${BASH_COMMAND-}" \
+		"BASH_CMDS             = ${BASH_CMDS[*]}" \
+		"BASH_ARGC             = ${BASH_ARGC[*]}" \
+		"BASH_ARGV             = ${BASH_ARGV[*]}" \
+		"BASH_VERSION          = ${BASH_VERSION}" \
+		"-                     = $-" >&2
+}
 
 # -------------------------------------
 
@@ -2164,7 +2199,7 @@ recursed_expected_errexit_stdout="$(
 		caught_do_02 = 202 ?= 0
 		caught_do_03 = 0 ?= 0
 	EOF
-)$newline" # 204 is not output as it is returned before the output
+)" # 204 is not output as it is returned before the output
 
 # test
 if __begin_test_block --name='try recursed' \
@@ -2232,7 +2267,7 @@ if __begin_test_block --name='do recursed[subshell] [--redirect-status] [--copy-
 				caught_do_03 = 0 ?= 0
 				caught_do_04 = 204 ?= 204
 			EOF
-		)$newline" # 205 is not output as it is returned before the output
+		)" # 205 is not output as it is returned before the output
 fi
 
 if __begin_test_block --name='do recursed[subshell] [--copy-status] [--copy-stdout] [errexit disabled via conditional]'; then
@@ -2243,6 +2278,85 @@ if __begin_test_block --name='do recursed[subshell] [--copy-status] [--copy-stdo
 		{__conditional_test_status} 205 \
 		{caught_test_stdout} '' # we do not have the stdout due to the failure not being ignored
 fi
+
+# -------------------------------------
+# now that the testing of exit status is finished, undo the overrides
+# and start testing content redirections instead
+
+function dorothy_try__context_lines { :; }
+function dorothy_try__dump_lines { :; }
+
+function __write_stdout_stderr {
+	printf '%s\n' 'stdout1' >&1
+	printf '%s\n' 'stderr1' >&2
+	printf '%s\n\n' 'stdout2' >&1
+	printf '%s\n\n' 'stderr2' >&2
+}
+
+if __begin_test_block --name='do [--redirect-stdout] [--redirect-stderr]'; then
+	__do \
+		--redirect-status={caught_test_status} \
+		--redirect-stdout={caught_test_stdout} \
+		--redirect-stderr={caught_test_stderr} \
+		-- \
+		__write_stdout_stderr
+	__end_test_block \
+		{caught_test_status} 0 \
+		{caught_test_stdout} $'stdout1\nstdout2' \
+		{caught_test_stderr} $'stderr1\nstderr2'
+fi
+if __begin_test_block --name='do [--redirect-stdout] [--redirect-stderr] [--trailing-newlines]'; then
+	__do --trailing-newlines \
+		--redirect-status={caught_test_status} \
+		--redirect-stdout={caught_test_stdout} \
+		--redirect-stderr={caught_test_stderr} \
+		-- \
+		__write_stdout_stderr
+	__end_test_block \
+		{caught_test_status} 0 \
+		{caught_test_stdout} $'stdout1\nstdout2\n\n' \
+		{caught_test_stderr} $'stderr1\nstderr2\n\n'
+fi
+if __begin_test_block --name='do [--redirect-output]'; then
+	__do \
+		--redirect-status={caught_test_status} \
+		--redirect-output={caught_test_output} \
+		-- \
+		__write_stdout_stderr
+	__end_test_block \
+		{caught_test_status} 0 \
+		{caught_test_output} $'stdout1\nstderr1\nstdout2\n\nstderr2'
+fi
+if __begin_test_block --name='do [--redirect-output] [--trailing-newlines]'; then
+	__do --trailing-newlines \
+		--redirect-status={caught_test_status} \
+		--redirect-output={caught_test_output} \
+		-- \
+		__write_stdout_stderr
+	__end_test_block \
+		{caught_test_status} 0 \
+		{caught_test_output} $'stdout1\nstderr1\nstdout2\n\nstderr2\n\n'
+fi
+
+# @todo resolve copy-output and expectations on how the below does not behave as intuited
+# if __begin_test_block --name='do stdout/stderr --trailing-newlines'; then
+# 	__do --trailing-newlines \
+# 		--redirect-status={caught_test_status} \
+# 		--copy-stdout={caught_test_stdout} \
+# 		--copy-stderr={caught_test_stderr_original} \
+# 		--redirect-stderr='(echo-uppercase --stdin >&2)' \
+# 		--copy-stderr={caught_test_stderr} \
+# 		--redirect-stderr=STDOUT \
+# 		--copy-stdout={caught_test_output} \
+# 		-- \
+# 		__write_stdout_stderr
+# 	__end_test_block \
+# 		{caught_test_status} 0 \
+# 		{caught_test_stdout} $'my-stdout\n\n' \
+# 		{caught_test_stderr_original} 'my-stderr' \
+# 		{caught_test_stderr} 'MY-STDERR' \
+# 		{caught_test_output} $'my-stdoutMY-STDERR\n\n'
+# fi
 
 # =============================================================================
 # Extra Toolkit
