lint 56e7f807a5199f3217cb683ba4562a6dbfb57624

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -59,17 +59,22 @@ action="${DOROTHY_ACTION-}" # used by dorothy cloudflare worker
 
 # =====================================
 # Helpers
+
+# check if all args exits
+# returns failure if any arg is missing
 function command-exists {
 	local command
 	for command in "$@"; do
-		type -P "$command" &>/dev/null
+		type -P "$command" &>/dev/null || return 1
 	done
 }
 
+# check if all args are missing
+# returns failure if any arg is present
 function command-missing {
 	local command
 	for command in "$@"; do
-		! type -P "$command" &>/dev/null
+		type -P "$command" &>/dev/null && return 1
 	done
 }
 
