process/command substitutions discard exit status
---

workaround that process/command substitutions discard exit status

this also resolves the long-standing problem of `git-helper update` continuing to prompt for which remote, when there are none, because:

``` bash
__split {remotes} --no-zero-length < <(get_remotes)
```

would discard the exit status

added `__split ... --invoke -- <command> ...` to make respecting exit status easier

added `__get_semaphores` as well to make it easier

see `errors.md` for details

---

secondly, this enforces the `{var_name}` covnention for any `bash.bash` function that uses variable references, which improves clarity

in doing so, the WIP `__is_within` is now just `__has`

this also remvoves unnecessary quoting of the var references

---

other changes:

- `secret` has been rewritten to use safety functions, as there was too much unnecessary comoplexity otherwise, it's ugly, but whatever
- `debug-bash` and `dorothy` now share their `__get_bash_barinaries`
- `debug-bash` now supports separators on `--bash=` and `--version` arguments, not just `--versions=`
- use `... || __return $? -- __print_lines || return` and `... || __return $? -- echo-error ... || return` as a a suitable shorthand for outputting additional debug information on failures
- `dorothy theme` now defaults to your current theme selection, there was code there before for this, but it was never implemented corretly
- migrated `get-url-upgrade` to bash associative arrays, for easier maintainability and intention
- `setup-util-docker`: fix a typo regressionin the debug command
- `arrays.md` note that it is outdated
- `errors.md` and `subshells.md` rewrote for modern conventions and awareness of stituations that discard exit status

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -917,10 +917,7 @@ function dorothy_() (
 		}
 		function update_dorothy {
 			# https://github.com/bevry/dorothy/issues/215
-			__update_modern_dorothy || {
-				__print_lines '...Dorothy was unable to be automatically updated. Please manually update Dorothy and try again.'
-				return 1
-			}
+			__update_modern_dorothy || __return $? -- __print_lines '...Dorothy was unable to be automatically updated. Please manually update Dorothy and try again.' || return
 		}
 
 		# check
@@ -1186,7 +1183,7 @@ function dorothy_() (
 							Dorothy User Configuration Repository: $(echo-style --code="$repo_git_url")
 							Dorothy User Configuration Strongbox keyid: $(echo-style --code="$strongbox_keyid")
 							This Machine's Strongbox keyring: $(echo-style --code="$local_strongbox_keyring")
-							This Machine's User: $(echo-style --code="$(whoami)")
+							This Machine's User: $(echo-style --code="$(whoami || :)")
 							This Machine's Local IP: $(echo-style --code="$local_ip")
 							Strongbox Documentation: $(echo-style --code='https://github.com/uw-labs/strongbox')
 							Dorothy's Strongbox Documentation: $(echo-style --code="$the_strongbox_url")
@@ -1469,7 +1466,7 @@ function dorothy_() (
 		}
 
 		# act, installing the shell if it is missing
-		if __is_within "$shell" 'shells'; then
+		if __has {shells} "$shell"; then
 			setup-util-"$shell" --quiet || return
 			# TERM dumb fallback solves: warning: Could not set up terminal because $TERM is unset. Falling back to hardcoded xterm-256color values
 			export DOROTHY_RUN=yes TERM="${TERM:-"dumb"}"
@@ -1518,7 +1515,7 @@ function dorothy_() (
 		assert_dorothy_configured
 
 		local paths=()
-		__split paths --no-zero-length < <(echo-if-present -- "$DOROTHY/commands" "$DOROTHY/commands.beta" "$DOROTHY/user/commands" "$DOROTHY/user/commands.local")
+		__split {paths} --no-zero-length --invoke -- echo-if-present -- "$DOROTHY/commands" "$DOROTHY/commands.beta" "$DOROTHY/user/commands" "$DOROTHY/user/commands.local"
 		setup-util-eza --quiet --optional
 		if __command_exists eza; then
 			eza "${paths[@]}"
@@ -1567,6 +1564,10 @@ function dorothy_() (
 		echo-style --g1='Review Dorothy'
 	}
 
+	function __get_themes {
+		__print_lines 'system' || return
+		fs-path --no-parents --no-extensions -- "$DOROTHY/themes/"*.* "$DOROTHY/user/themes/"*.* | echo-unique --stdin || return
+	}
 	function act_theme {
 		# pre-requisites
 		assert_dorothy_and_user_cloned
@@ -1576,25 +1577,17 @@ function dorothy_() (
 		ensure_minimal_dependencies
 
 		# features
-		local themes theme files
+		local DOROTHY_THEME='' themes
 		source "$DOROTHY/sources/config.sh"
-
-		# prepare
-		__split files --no-zero-length < <(fs-path --no-parents --no-extensions -- "$DOROTHY/themes/"*.* "$DOROTHY/user/themes/"*.* | echo-unique --stdin)
-		themes=(
-			system
-			"${files[@]}"
-		)
-
-		# ask
+		load_dorothy_config 'interactive.sh'
+		__split {themes} --no-zero-length --invoke -- __get_themes
 		theme="$(
-			choose --linger --required \
+			choose --linger --required --default="$DOROTHY_THEME" \
 				--question='Which theme to use?' -- \
 				"${themes[@]}"
 		)"
 
 		# apply
-		source "$DOROTHY/sources/config.sh"
 		dorothy-config 'interactive.sh' -- \
 			--find='export DOROTHY_THEME=(.*)' --replace="export DOROTHY_THEME=$(echo-escape-bash -- "$theme")"
 		if [[ -f "$DOROTHY/user/config/interactive.nu" ]]; then
@@ -1755,6 +1748,13 @@ function dorothy_() (
 		# @todo search for unsafe [[ .. ]]  usage
 		# ^\s+\[\[.+\](\s*#.+)?$
 
+		# @todo enforce that `<(...)` is always `<(set +e; ...)` or `<(... || :)` to make it known that the error status is discarded
+
+		# @todo enforce that process substitutions only occur one per assignment, and only for assignments, otherwise exit status is discarded
+		# in which they should enforce `$(... || :)`: \$\(.*\$\(
+
+		# @todo enforce that unnecessary quoting of var references is removed
+
 		# check for unsafe function calls, by checking for missing __* safety convention
 		# ((if|[&][&]|[|][|]|[!])\s)[a-z]+_[a-z_]+
 		# \s[a-z]+_[a-z_]+( ([&][&]|[|][|]))
@@ -1763,7 +1763,7 @@ function dorothy_() (
 		# To avoid matching: OR a_var=$?
 		# So for now, just modify the var names even though it is unnecessary.
 		local unsafe_regexp='((if|[&][&]|[|][|]|[!])\s)[a-z]+_[a-z_]+|\s[a-z]+_[a-z_]+( ([&][&]|[|][|]))' unsafe_contents='' unsafe_bundle='' unsafe_count=0
-		__split commands --no-zero-length < <(rg --files-with-matches --sortr modified --regexp="$unsafe_regexp" "${scan_paths[@]}")
+		__split {commands} --no-zero-length < <(rg --files-with-matches --sortr modified --regexp="$unsafe_regexp" "${scan_paths[@]}" || :)
 		for filepath in "${commands[@]}"; do
 			if [[ $filepath == "$DOROTHY/commands/dorothy-internals" ]]; then
 				continue
@@ -1796,12 +1796,8 @@ function dorothy_() (
 						trunk upgrade
 					fi
 					# format and check
-					trunk fmt --all "${args[@]}" || {
-						status=$?
-						# if format fails, it is likely for a check failure, so ensure check is run
-						trunk check --all "${args[@]}" || return
-						return "$status"
-					}
+					# if format fails, it is likely for a check failure, so ensure check is run
+					trunk fmt --all "${args[@]}" || __return $? -- trunk check --all "${args[@]}" || return
 					trunk check --all "${args[@]}"
 				)
 				echo-style --g3="$path"
@@ -1823,12 +1819,21 @@ function dorothy_() (
 		echo-style --g1='Dorothy Lint'
 	}
 
+	# this is shared between [debug-bash] and [dorothy]
+	function __get_bash_binaries {
+		{
+			type -pa bash || :
+			expand-path -- "$XDG_BIN_HOME/bash-*" || :
+		} | echo-unique --stdin
+	}
 	function act_test {
 		# pre-requisites
 		assert_dorothy_configured
 
 		# options
-		local item only=() skips=('dorothy' 'bash.bash') only_current_bash_version=('debug-terminal') bash_binaries=() bash_custom='no'
+		local item only=() skips=('dorothy' 'bash.bash') bash_binaries=() bash_custom='no'
+		# trunk-ignore(shellcheck/SC2034)
+		local only_current_bash_version=('debug-terminal')
 		while [[ $# -ne 0 ]]; do
 			item="$1"
 			shift
@@ -1881,12 +1886,7 @@ function dorothy_() (
 
 		# fetch the other bash locations to test against
 		if [[ ${#bash_binaries[@]} -eq 0 ]]; then
-			__split bash_binaries --no-zero-length < <(
-				{
-					type -pa bash
-					expand-path -- "$XDG_BIN_HOME/bash-*"
-				} | echo-unique --stdin
-			)
+			__split {bash_binaries} --no-zero-length --invoke -- __get_bash_binaries
 		fi
 
 		# prepare scan paths
@@ -1919,14 +1919,14 @@ function dorothy_() (
 				fi
 			done
 		else
-			__split commands --no-zero-length < <(rg --files-with-matches --sortr modified --fixed-strings --regexp='--test' "${scan_paths[@]}")
+			__split {commands} --no-zero-length < <(rg --files-with-matches --sortr modified --fixed-strings --regexp='--test' "${scan_paths[@]}")
 		fi
 		for filepath in "${commands[@]}"; do
 			filename="$(basename -- "$filepath")"
 			failed='no'
 
 			# check if we want to skip this test
-			if __is_within "$filename" 'skips'; then
+			if __has {skips} "$filename"; then
 				continue
 			fi
 
@@ -1940,10 +1940,10 @@ function dorothy_() (
 			fi
 
 			# run again, ensuring this specific bash version is preferred
-			if [[ $failed == 'no' ]] && ! __is_within "$filename" -- "${only_current_bash_version[@]}"; then
+			if [[ $failed == 'no' ]] && ! __has {only_current_bash_version} "$filename"; then
 				for bash_binary in "${bash_binaries[@]}"; do
 					eval-helper --verbose --wrap -- debug-bash --bash="$bash_binary" -- "$filepath" --test || {
-						# if [[ $bash_custom == 'no' ]] && __is_within "$filename" -- "${only_current_bash_version[@]}"; then
+						# if [[ $bash_custom == 'no' ]] && __has {only_current_bash_version} "$filename"; then
 						# 	echo-style --warning='This test was expected to fail on other bash versions, marking as only warning instead of failure.'
 						# 	warnings+=("$bash_binary $filepath --test")
 						# else
diff --git a/commands/get-github-release b/commands/get-github-release
--- a/commands/get-github-release
+++ b/commands/get-github-release
@@ -299,11 +299,7 @@ function get_github_release() (
 		fetch --bearer-token="$GITHUB_TOKEN" "$1"
 	}
 	function fetch_json_of_rate_limit {
-		fetch_json "$GITHUB_API_URL/rate_limit" || {
-			local exit_status="$?"
-			echo-style --stderr --error1='Failed to fetch the GitHub API Rate Limit.' --notice1=' Authorize with the GitHub CLI: ' --code-notice1='gh auth login'
-			return "$exit_status"
-		}
+		fetch_json "$GITHUB_API_URL/rate_limit" || __return $? -- echo-style --stderr --error1='Failed to fetch the GitHub API Rate Limit.' --notice1=' Authorize with the GitHub CLI: ' --code-notice1='gh auth login' || return
 	}
 	function extract_value_from_json_property_from_stdin {
 		local property="$1" awk_script
diff --git a/commands/setup-dns b/commands/setup-dns
--- a/commands/setup-dns
+++ b/commands/setup-dns
@@ -96,16 +96,16 @@ function setup_dns() (
 	local services_id=() services_about=() services_url=()
 
 	# load id
-	__split services_id --no-zero-length < <(jq -r '.services | keys_unsorted[]' "$DOROTHY/config/dns.json")
+	__split {services_id} --no-zero-length --invoke -- jq -r '.services | keys_unsorted[]' "$DOROTHY/config/dns.json"
 
 	# load about
-	__split services_about --no-zero-length < <(jq -r '.services[].about' "$DOROTHY/config/dns.json")
+	__split {services_about} --no-zero-length < <(jq -r '.services[].about' "$DOROTHY/config/dns.json" || :)
 	if [[ ${#services_id[@]} -ne ${#services_about[@]} ]]; then
 		help 'A DNS service is missing an about, or an about is multiline when it should be single line.'
 	fi
 
 	# load url
-	__split services_url --no-zero-length < <(jq -r '.services[].url' "$DOROTHY/config/dns.json")
+	__split {services_url} --no-zero-length < <(jq -r '.services[].url' "$DOROTHY/config/dns.json" || :)
 	if [[ ${#services_id[@]} -ne ${#services_url[@]} ]]; then
 		help 'A DNS service is missing a URL.'
 	fi
@@ -116,16 +116,16 @@ function setup_dns() (
 	local providers_id=() providers_url=() providers_about=()
 
 	# load id
-	__split providers_id --no-zero-length < <(jq -r '.providers | keys_unsorted[]' "$DOROTHY/config/dns.json")
+	__split {providers_id} --no-zero-length --invoke -- jq -r '.providers | keys_unsorted[]' "$DOROTHY/config/dns.json"
 
 	# load about
-	__split providers_about --no-zero-length < <(jq -r '.providers[].about' "$DOROTHY/config/dns.json")
+	__split {providers_about} --no-zero-length < <(jq -r '.providers[].about' "$DOROTHY/config/dns.json" || :)
 	if [[ ${#providers_id[@]} -ne ${#providers_about[@]} ]]; then
 		help 'A DNS provider is missing an about, or an about is multiline when it should be single line.'
 	fi
 
 	# load url
-	__split providers_url --no-zero-length < <(jq -r '.providers[].url' "$DOROTHY/config/dns.json")
+	__split {providers_url} --no-zero-length < <(jq -r '.providers[].url' "$DOROTHY/config/dns.json" || :)
 	if [[ ${#providers_id[@]} -ne ${#providers_url[@]} ]]; then
 		help 'A DNS provider is missing a URL.'
 	fi
@@ -356,7 +356,7 @@ function setup_dns() (
 
 		# remove files
 		local had_removal='no'
-		__split remove_paths_that_exist --no-zero-length < <(echo-if-present --elevate -- "${remove_paths[@]}")
+		__split {remove_paths_that_exist} --no-zero-length --invoke -- echo-if-present --elevate -- "${remove_paths[@]}"
 		if [[ ${#remove_paths_that_exist[@]} -ne 0 ]] && fs-rm --quiet --confirm --elevate -- "${remove_paths_that_exist[@]}"; then
 			had_removal='yes'
 		fi
@@ -509,7 +509,7 @@ function setup_dns() (
 			eval-helper --elevate -- resolvectl reset-server-features --no-pager || :
 
 			# apply the changes to their interfaces
-			__split interfaces --no-zero-length < <(network-interface list | echo-values --stdin)
+			__split {interfaces} --no-zero-length < <(network-interface list | echo-values --stdin || :)
 			if [[ ${#interfaces[@]} -eq 0 ]]; then
 				echo-style --stderr --error1='No interfaces were found.'
 				return 1
@@ -1023,7 +1023,7 @@ EOF
 		fi
 
 		# read the file into an array
-		__split available_dnscrypt_names --no-zero-length <"$dnscrypt_names_file"
+		__split {available_dnscrypt_names} --no-zero-length <"$dnscrypt_names_file"
 		if [[ ${#dnscrypt_names[@]} -ne 0 ]]; then
 			for a in "${dnscrypt_names[@]}"; do
 				found='no'
@@ -1224,10 +1224,7 @@ EOF
 			"${fn_id}__configure"
 		)
 		for fn in "${fns[@]}"; do
-			command -v "$fn" >/dev/null || {
-				echo-style --stderr --error1='The DNS service ' --code-error1="$fn_id" --error1=' is missing its helper: ' --code-error1="$fn"
-				return 1
-			}
+			command -v "$fn" >/dev/null || __return $? -- echo-style --stderr --error1='The DNS service ' --code-error1="$fn_id" --error1=' is missing its helper: ' --code-error1="$fn" || return
 		done
 		return 0
 	}
@@ -1512,13 +1509,11 @@ EOF
 			dnscrypt_names=("${DNS_DNSCRYPT_NAMES[@]}")
 		else
 			for property in "${properties[@]}"; do
-				__split "$property" --no-zero-length < <(
-					jq -r \
-						--arg provider "$provider" \
-						--arg property "$property" \
-						'.providers[$provider][$property][]' \
-						"$DOROTHY/config/dns.json" 2>/dev/null || :
-				)
+				__split "{$property}" --no-zero-length --invoke -- jq -r \
+					--arg provider "$provider" \
+					--arg property "$property" \
+					'.providers[$provider][$property][]' \
+					"$DOROTHY/config/dns.json" 2>/dev/null || :
 			done
 		fi
 	}
