echo-style: merge `echo-element`, `echo-segment`
changes:
- deprecated `echo-element` and `echo-segment`, as they are now supported by `echo-style`
- `echo-style` and `styles.bash` updated for begin/end and color/nocolor styles
- `echo-style` updated to do the minimal writes for performance and simplicity
- `styles.bash` now has the `choose` styles, so `choose` theme can be customised by the user
- `choose` fixed and styled no selection / no items

/close #232
/ref #231 #188

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -498,7 +498,7 @@ function dorothy_() (
 
 	function ensure_minimal_dependencies {
 		# dorothy has been installed
-		echo-segment --h2='Ensure required dependencies'
+		echo-style --h2='Ensure required dependencies'
 
 		# macos tooling
 		if __is_mac; then
@@ -529,18 +529,18 @@ function dorothy_() (
 		fi
 
 		# log
-		echo-segment --g2='Ensure required dependencies'
+		echo-style --g2='Ensure required dependencies'
 	}
 
 	function ensure_development_dependencies {
-		echo-segment --h2='Ensure development dependencies'
+		echo-style --h2='Ensure development dependencies'
 		setup-util-bash --quiet "$@"
 		setup-util-ripgrep --quiet "$@"
 		setup-util-prettier --quiet "$@"
 		setup-util-shellcheck --quiet "$@"
 		setup-util-shfmt --quiet "$@"
 		setup-util-trunk --quiet "$@"
-		echo-segment --g2='Ensure development dependencies'
+		echo-style --g2='Ensure development dependencies'
 	}
 
 	function assert_dorothy_configured {
@@ -855,13 +855,13 @@ function dorothy_() (
 			fi
 		}
 		function __update_modern_dorothy {
-			if __command_exists echo-segment git-helper; then
-				echo-segment --h2="Updating the Dorothy installation at $DOROTHY" || return
+			if __command_exists echo-style git-helper; then
+				echo-style --h2="Updating the Dorothy installation at $DOROTHY" || return
 				# update origin first
 				git-helper update --path="$DOROTHY" || return
 				# update upstream second
 				git-helper update --path="$DOROTHY" -- --remote-name="$dorothy_upstream_remote_name" --remote-url="$dorothy_upstream_git_https" || return
-				echo-segment --g2="Updating the Dorothy installation at $DOROTHY" || return
+				echo-style --g2="Updating the Dorothy installation at $DOROTHY" || return
 			else
 				return 1
 			fi
@@ -1122,11 +1122,11 @@ function dorothy_() (
 			fi
 		}
 		function update_user {
-			echo-segment --h2="Updating the Dorothy user configuration at $DOROTHY/user"
+			echo-style --h2="Updating the Dorothy user configuration at $DOROTHY/user"
 			if ! git-helper update --path="$DOROTHY/user"; then
 				__print_line '...Dorothy user configuration was unable to be updated, you will have to figure this out later...'
 			fi
-			echo-segment --g2="Updating the Dorothy user configuration at $DOROTHY/user"
+			echo-style --g2="Updating the Dorothy user configuration at $DOROTHY/user"
 		}
 
 		# update or install the user configuration based on its presence
@@ -1224,7 +1224,7 @@ function dorothy_() (
 			esac
 		done
 
-		echo-segment --h2='Dorothy Shell Configuration'
+		echo-style --h2='Dorothy Shell Configuration'
 
 		# if not uninstalling
 		if test "$option_uninstall" = 'no'; then
@@ -1254,7 +1254,7 @@ function dorothy_() (
 
 		# bash
 		if is-needle --needle=bash -- "${use_shells[@]}"; then
-			echo-segment --h3='Configuring Bash'
+			echo-style --h3='Configuring Bash'
 			setup-util-bash
 
 			# mac and raspi ubuntu
@@ -1265,7 +1265,7 @@ function dorothy_() (
 			config-helper --file="$HOME/.bashrc" -- \
 				--find='.+? # Dorothy' --replace="source \"$DOROTHY/init.sh\" # Dorothy"
 
-			echo-segment --g3='Configuring Bash'
+			echo-style --g3='Configuring Bash'
 		else
 			config-helper --file="$HOME/.bash_profile" -- \
 				--find='.+? # Dorothy' --replace=''
@@ -1275,14 +1275,14 @@ function dorothy_() (
 
 		# dash
 		if is-needle --needle=dash -- "${use_shells[@]}"; then
-			echo-segment --h3='Configuring Dash'
+			echo-style --h3='Configuring Dash'
 			setup-util-dash
 
 			# configure
 			config-helper --file="$HOME/.profile" -- \
 				--find='.+? # Dorothy' --replace=". \"$DOROTHY/init.sh\" # Dorothy"
 
-			echo-segment --g3='Configuring Dash'
+			echo-style --g3='Configuring Dash'
 		elif ! is-needle --needle=bash -- "${use_shells[@]}" && ! is-needle --needle=ksh -- "${use_shells[@]}"; then
 			config-helper --file="$HOME/.profile" -- \
 				--find='.+? # Dorothy' --replace=''
@@ -1293,7 +1293,7 @@ function dorothy_() (
 			# https://elv.sh/ref/command.html#rc-file
 			# https://elv.sh/ref/runtime.html
 			# https://github.com/elves/elvish/issues/1726
-			echo-segment --h3='Configuring Elvish'
+			echo-style --h3='Configuring Elvish'
 			setup-util-elvish
 			mkdir -p "$XDG_CONFIG_HOME/elvish"
 
@@ -1301,7 +1301,7 @@ function dorothy_() (
 			config-helper --file="$XDG_CONFIG_HOME/elvish/rc.elv" -- \
 				--find='.+? # Dorothy' --replace="eval (cat '$DOROTHY/init.elv' | slurp) # Dorothy"
 
-			echo-segment --h3='Configuring Elvish'
+			echo-style --h3='Configuring Elvish'
 		else
 			mkdir -p "$XDG_CONFIG_HOME/elvish"
 			config-helper --file="$XDG_CONFIG_HOME/elvish/rc.elv" -- \
@@ -1310,7 +1310,7 @@ function dorothy_() (
 
 		# fish
 		if is-needle --needle=fish -- "${use_shells[@]}"; then
-			echo-segment --h3='Configuring Fish'
+			echo-style --h3='Configuring Fish'
 			setup-util-fish
 			mkdir -p "$XDG_CONFIG_HOME/fish"
 
@@ -1318,7 +1318,7 @@ function dorothy_() (
 			config-helper --file="$XDG_CONFIG_HOME/fish/config.fish" -- \
 				--find='.+? # Dorothy' --replace="source '$DOROTHY/init.fish' # Dorothy"
 
-			echo-segment --g3='Configuring Zsh'
+			echo-style --g3='Configuring Zsh'
 		else
 			mkdir -p "$XDG_CONFIG_HOME/fish"
 			config-helper --file="$XDG_CONFIG_HOME/fish/config.fish" -- \
@@ -1327,14 +1327,14 @@ function dorothy_() (
 
 		# ksh
 		if is-needle --needle=ksh -- "${use_shells[@]}"; then
-			echo-segment --h3='Configuring KSH'
+			echo-style --h3='Configuring KSH'
 			setup-util-ksh
 
 			# configure
 			config-helper --file="$HOME/.profile" -- \
 				--find='.+? # Dorothy' --replace=". '$DOROTHY/init.sh' # Dorothy"
 
-			echo-segment --g3='Configuring KSH'
+			echo-style --g3='Configuring KSH'
 		elif ! is-needle --needle=bash -- "${use_shells[@]}" && ! is-needle --needle=dash -- "${use_shells[@]}"; then
 			config-helper --file="$HOME/.profile" -- \
 				--find='.+? # Dorothy' --replace=''
@@ -1342,14 +1342,14 @@ function dorothy_() (
 
 		# nu
 		if is-needle --needle=nu -- "${use_shells[@]}"; then
-			echo-segment --h3='Configuring Nu'
+			echo-style --h3='Configuring Nu'
 			setup-util-nu
 
 			# trunk-ignore(shellcheck/SC2016)
 			config-helper --file="$(nu -c 'echo $nu.loginshell-path')" -- \
 				--find='.+? # Dorothy' --replace="source '$DOROTHY/init.nu' # Dorothy"
 
-			echo-segment --g3='Configuring Nu'
+			echo-style --g3='Configuring Nu'
 		elif __command_exists nu; then
 			# trunk-ignore(shellcheck/SC2016)
 			config-helper --file="$(nu -c 'echo $nu.loginshell-path')" -- \
@@ -1359,7 +1359,7 @@ function dorothy_() (
 		# xonsh
 		if is-needle --needle=xonsh -- "${use_shells[@]}"; then
 			# https://xon.sh/xonshrc.html
-			echo-segment --h3='Configuring Xonsh'
+			echo-style --h3='Configuring Xonsh'
 			setup-util-xonsh
 			mkdir -p "$XDG_CONFIG_HOME/xonsh/rc.d"
 
@@ -1367,7 +1367,7 @@ function dorothy_() (
 			config-helper --file="$XDG_CONFIG_HOME/xonsh/rc.xsh" -- \
 				--find='.+? # Dorothy' --replace="execx(compilex(open('$DOROTHY/init.xsh').read())) # Dorothy"
 
-			echo-segment --g3='Configuring Xonsh'
+			echo-style --g3='Configuring Xonsh'
 		else
 			mkdir -p "$XDG_CONFIG_HOME/xonsh/rc.d"
 			config-helper --file="$XDG_CONFIG_HOME/xonsh/rc.xsh" -- \
@@ -1377,7 +1377,7 @@ function dorothy_() (
 		# zsh
 		# https://zsh.sourceforge.io/Intro/intro_3.html
 		if is-needle --needle=zsh -- "${use_shells[@]}"; then
-			echo-segment --h3='Configuring Zsh'
+			echo-style --h3='Configuring Zsh'
 			setup-util-zsh
 			mkdir -p "$ZDOTDIR"
 
@@ -1391,7 +1391,7 @@ function dorothy_() (
 			config-helper --file="$HOME/.zshenv" -- \
 				--find='ZDOTDIR=.+' --replace="ZDOTDIR='$ZDOTDIR'"
 
-			echo-segment --g3='Configuring Zsh'
+			echo-style --g3='Configuring Zsh'
 		else
 			mkdir -p "$ZDOTDIR"
 			config-helper --file="$ZDOTDIR/.zshrc" -- \
@@ -1402,7 +1402,7 @@ function dorothy_() (
 				--find='ZDOTDIR=.+' --replace="ZDOTDIR='$ZDOTDIR'"
 		fi
 
-		echo-segment --g2='Dorothy Shell Configuration'
+		echo-style --g2='Dorothy Shell Configuration'
 	}
 
 	# =====================================
@@ -1431,7 +1431,7 @@ function dorothy_() (
 		assert_dorothy_configured
 
 		# action
-		echo-segment --h1='Install Dorothy'
+		echo-style --h1='Install Dorothy'
 		if test "$option_skip_install" = 'no'; then
 			ensure_minimal_dependencies
 			ensure_machine_configured
@@ -1440,7 +1440,7 @@ function dorothy_() (
 		ensure_shell_configured --clean="$option_clean"
 
 		# log success
-		echo-segment --g1='Install Dorothy'
+		echo-style --g1='Install Dorothy'
 		echo-style --success='Dorothy is now setup.' ' ' --notice='Restart your terminal.'
 	}
 
@@ -1450,12 +1450,12 @@ function dorothy_() (
 		assert_dorothy_configured
 
 		# action
-		echo-segment --h1='Uninstall Dorothy'
+		echo-style --h1='Uninstall Dorothy'
 		ensure_minimal_dependencies
 		ensure_shell_configured --uninstall
 
 		# log success and instructions for removal
-		echo-segment --g1='Uninstall Dorothy'
+		echo-style --g1='Uninstall Dorothy'
 		echo-style --success='Dorothy is now uninstalled.' ' ' --notice='Restart your terminal.'
 		local paths=()
 		if test -d "$DOROTHY"; then
@@ -1475,14 +1475,14 @@ function dorothy_() (
 		assert_dorothy_configured
 
 		# action
-		echo-segment --h1='Update Dorothy'
+		echo-style --h1='Update Dorothy'
 		ensure_minimal_dependencies
 		ensure_dorothy_configured
 		ensure_user_configured
-		echo-segment --h2='Correct Dorothy Permissions'
+		echo-style --h2='Correct Dorothy Permissions'
 		ensure_permissions_configured # needed as new commands wouldn't be executable otherwise
-		echo-segment --g2='Correct Dorothy Permissions'
-		echo-segment --g1='Update Dorothy'
+		echo-style --g2='Correct Dorothy Permissions'
+		echo-style --g1='Update Dorothy'
 	}
 
 	# don't use [sh], as [sh] is [dash] on ubuntu, and [dash] doesn't support the [--...] args
@@ -1598,10 +1598,10 @@ function dorothy_() (
 		assert_dorothy_configured
 
 		# action
-		echo-segment --h1='Correct Dorothy Permissions'
+		echo-style --h1='Correct Dorothy Permissions'
 		ensure_minimal_dependencies
 		ensure_permissions_configured
-		echo-segment --g1='Correct Dorothy Permissions'
+		echo-style --g1='Correct Dorothy Permissions'
 	}
 
 	function act_edit {
@@ -1609,7 +1609,7 @@ function dorothy_() (
 		assert_dorothy_and_user_cloned
 
 		# action
-		echo-segment --h1='Edit Dorothy'
+		echo-style --h1='Edit Dorothy'
 		# ensure_minimal_dependencies <-- if they are editing, then we assume they are already setup
 		ensure_permissions_configured
 		if test "$(edit --dry --only-editor)" == 'code'; then
@@ -1617,7 +1617,7 @@ function dorothy_() (
 		else
 			edit -- "$DOROTHY"
 		fi
-		echo-segment --g1='Edit Dorothy'
+		echo-style --g1='Edit Dorothy'
 	}
 
 	function act_review {
@@ -1625,12 +1625,12 @@ function dorothy_() (
 		assert_dorothy_and_user_cloned
 
 		# action
-		echo-segment --h1='Review Dorothy'
+		echo-style --h1='Review Dorothy'
 		ensure_minimal_dependencies
 		ensure_permissions_configured
 		git-helper review "$DOROTHY/user" || :
 		git-helper review "$DOROTHY" || :
-		echo-segment --g1='Review Dorothy'
+		echo-style --g1='Review Dorothy'
 	}
 
 	function act_theme {
@@ -1638,7 +1638,7 @@ function dorothy_() (
 		assert_dorothy_and_user_cloned
 
 		# action
-		echo-segment --h1='Select Dorothy Theme'
+		echo-style --h1='Select Dorothy Theme'
 		ensure_minimal_dependencies
 
 		# features
@@ -1679,7 +1679,7 @@ function dorothy_() (
 
 		# log
 		echo-style --success='Configuration change applied, ' --notice='restart your terminal for the change to take effect.'
-		echo-segment --g1='Select Dorothy Theme'
+		echo-style --g1='Select Dorothy Theme'
 	}
 
 	function act_dev {
@@ -1687,7 +1687,7 @@ function dorothy_() (
 		assert_dorothy_configured
 
 		# action
-		echo-segment --h1='Dorothy Development'
+		echo-style --h1='Dorothy Development'
 		if is-ci; then
 			ensure_development_dependencies --no-quiet
 		else
@@ -1705,7 +1705,7 @@ function dorothy_() (
 		eval-helper --no-quiet -- trunk --version || :
 
 		# log
-		echo-segment --g1='Dorothy Development'
+		echo-style --g1='Dorothy Development'
 	}
 
 	function act_format {
@@ -1713,7 +1713,7 @@ function dorothy_() (
 		assert_dorothy_configured
 
 		# action
-		echo-segment --h1='Dorothy Format'
+		echo-style --h1='Dorothy Format'
 		ensure_development_dependencies
 
 		# adjust for ci
@@ -1723,26 +1723,26 @@ function dorothy_() (
 		fi
 
 		# on dorothy
-		echo-segment --h3="$DOROTHY"
+		echo-style --h3="$DOROTHY"
 		(
 			cd "$DOROTHY"
 			# format
 			trunk fmt --all "${args[@]}"
 		)
-		echo-segment --g3="$DOROTHY"
+		echo-style --g3="$DOROTHY"
 
 		# on user configuration
 		if test -d "$DOROTHY/user/.trunk"; then
-			echo-segment --h3="$DOROTHY/user"
+			echo-style --h3="$DOROTHY/user"
 			(
 				cd "$DOROTHY/user"
 				# format
 				trunk fmt --all "${args[@]}"
 			)
-			echo-segment --g3="$DOROTHY/user"
+			echo-style --g3="$DOROTHY/user"
 		fi
 
-		echo-segment --g1='Dorothy Format'
+		echo-style --g1='Dorothy Format'
 	}
 
 	function act_check {
@@ -1750,7 +1750,7 @@ function dorothy_() (
 		assert_dorothy_configured
 
 		# action
-		echo-segment --h1='Dorothy Checks'
+		echo-style --h1='Dorothy Checks'
 		ensure_development_dependencies
 
 		# adjust for ci
@@ -1760,26 +1760,26 @@ function dorothy_() (
 		fi
 
 		# on dorothy
-		echo-segment --h3="$DOROTHY"
+		echo-style --h3="$DOROTHY"
 		(
 			cd "$DOROTHY"
 			# check
 			trunk check --all "${args[@]}"
 		)
-		echo-segment --g3="$DOROTHY"
+		echo-style --g3="$DOROTHY"
 
 		# on user configuration
 		if test -d "$DOROTHY/user/.trunk"; then
-			echo-segment --h3="$DOROTHY/user"
+			echo-style --h3="$DOROTHY/user"
 			(
 				cd "$DOROTHY/user"
 				# check
 				trunk check --all "${args[@]}"
 			)
-			echo-segment --g3="$DOROTHY/user"
+			echo-style --g3="$DOROTHY/user"
 		fi
 
-		echo-segment --g1='Dorothy Checks'
+		echo-style --g1='Dorothy Checks'
 	}
 
 	function act_lint {
@@ -1787,7 +1787,7 @@ function dorothy_() (
 		assert_dorothy_configured
 
 		# action
-		echo-segment --h1='Dorothy Lint'
+		echo-style --h1='Dorothy Lint'
 		ensure_development_dependencies
 
 		# adjust for ci
@@ -1803,7 +1803,7 @@ function dorothy_() (
 		fi
 
 		# on dorothy
-		echo-segment --h3="$DOROTHY"
+		echo-style --h3="$DOROTHY"
 		(
 			cd "$DOROTHY"
 			# upgrade
@@ -1826,11 +1826,11 @@ function dorothy_() (
 				npx prettier --write README.md
 			fi
 		)
-		echo-segment --g3="$DOROTHY"
+		echo-style --g3="$DOROTHY"
 
 		# on user configuration
 		if test -d "$DOROTHY/user/.trunk"; then
-			echo-segment --h3="$DOROTHY/user"
+			echo-style --h3="$DOROTHY/user"
 			(
 				cd "$DOROTHY/user"
 				# upgrade
@@ -1845,10 +1845,10 @@ function dorothy_() (
 				trunk fmt --all "${args[@]}"
 				trunk check --all "${args[@]}"
 			)
-			echo-segment --g3="$DOROTHY/user"
+			echo-style --g3="$DOROTHY/user"
 		fi
 
-		echo-segment --g1='Dorothy Lint'
+		echo-style --g1='Dorothy Lint'
 	}
 
 	function act_test {
@@ -1857,7 +1857,7 @@ function dorothy_() (
 		# ^ no need for user config for tests
 
 		# action
-		echo-segment --h1='Dorothy Tests'
+		echo-style --h1='Dorothy Tests'
 		source "$DOROTHY/sources/ripgrep.bash"
 
 		# able to test on bash v3?
@@ -1892,11 +1892,11 @@ function dorothy_() (
 		if test "${#commands[@]}" -ne 0; then
 			echo-style --error='The following commands have unsafe function calls:'
 			for filepath in "${commands[@]}"; do
-				echo-element --open="$filepath"
+				echo-style --element="$filepath"
 				rg --regexp="$unsafe_regexp" "$filepath"
-				echo-element --close="$filepath"
+				echo-style --/element="$filepath"
 			done
-			echo-segment --e1='Dorothy Tests'
+			echo-style --e1='Dorothy Tests'
 			return 1
 		fi
 
@@ -1939,12 +1939,12 @@ function dorothy_() (
 		if test "${#failures[@]}" -ne 0; then
 			echo-style --error='The following tests were failures:'
 			__print_lines "${failures[@]}"
-			echo-segment --e1='Dorothy Tests'
+			echo-style --e1='Dorothy Tests'
 			return 1
 		fi
 
 		# log
-		echo-segment --g1='Dorothy Tests'
+		echo-style --g1='Dorothy Tests'
 	}
 
 	function act_todos {
@@ -1953,7 +1953,7 @@ function dorothy_() (
 		# ^ no need for user config for todos
 
 		# action
-		echo-segment --h1='Dorothy Todos'
+		echo-style --h1='Dorothy Todos'
 		source "$DOROTHY/sources/ripgrep.bash"
 
 		# verbose about command conventions and support
@@ -2015,11 +2015,11 @@ function dorothy_() (
 			if test "${#file_bad[@]}" -ne 0; then
 				file_status=1
 			fi
-			echo-element --openclose="$filename" --status="$file_status" "${file_good[@]}" "${file_bad[@]}"
+			echo-style --element/="$filename" --status="$file_status" "${file_good[@]}" "${file_bad[@]}"
 		done
 
 		# log
-		echo-segment --g1='Dorothy Todos'
+		echo-style --g1='Dorothy Todos'
 	}
 
 	# =====================================
