*: modern code comment conventions

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -23,7 +23,7 @@
 # do not use the cmd_ convention, as that would interfere with the dorothy worker
 function dorothy_() (
 	# sanity check that we are running in bash
-	# sanity check, as [function .. () (], [elif], [&>], [local] are all bashisms, so other shells should have failed by now
+	# sanity check, as `function .. () (`, `elif`, `&>`, `local` are all bashisms, so other shells should have failed by now
 	if [[ -z ${BASH_VERSION-} ]]; then
 		printf '%s\n' "Dorothy requires bash to run. Refer to the installation instructions: $dorothy_install" >&2
 		exit 6 # ENXIO 6 Device not configured
@@ -246,7 +246,7 @@ function dorothy_() (
 	local item action='' option_xdg='' option_deps='' option_branch='' option_remote='' option_user='' option_args=() # option_slug option_reference defined earlier
 	function __affirm_action_is_undefined {
 		if [[ -n $action ]]; then
-			help 'Only one <action> may be provided.' || return $?
+			help --help='Only one <action> may be provided.' || return $?
 		fi
 	}
 	function __set_action {
@@ -618,7 +618,7 @@ function dorothy_() (
 		# makes sure chmod isn't running on nothing, which can happen upon initial user installs
 		# dorothy may not have been loaded yet
 		if [[ $# -ne 0 ]]; then
-			# macos chmod doesn't support [--] as such don't both with it for linux either
+			# macos chmod doesn't support `--` as such don't both with it for linux either
 			chmod -f +x "$@"
 		fi
 	}
@@ -731,7 +731,7 @@ function dorothy_() (
 			# setup repo with branch
 			local clone_args=(
 				'--quiet'   # --quiet to suppress 'Cloning into...' feedback
-				'--no-tags' # don't do [--depth 1] and [--single-branch] as a full history is required to do any checkouts
+				'--no-tags' # don't do `--depth 1` and `--single-branch` as a full history is required to do any checkouts
 			)
 			if [[ -n $option_branch ]]; then
 				clone_args+=(
@@ -987,7 +987,7 @@ function dorothy_() (
 		__print_style --g1='Update Dorothy'
 	}
 
-	# don't use [sh], as [sh] is [dash] on ubuntu, and [dash] doesn't support the [--...] args
+	# don't use `sh`, as `sh` is `dash` on ubuntu, and `dash` doesn't support the `--...` args
 	function act_repl {
 		# process arguments
 		local item shell='' theme='' shells=(bash fish)
@@ -1214,7 +1214,7 @@ function dorothy_() (
 		if [[ -f "$DOROTHY/user/config/interactive.nu" ]]; then
 			# dorothy-config 'interactive.nu' -- --string-find="\$env.DOROTHY_THEME" --string-replace="\$env.DOROTHY_THEME = $(echo-quote -- "$theme")"
 			# ^ don't use that, as theming will always be in the config not config.local
-			# ^ at some point, [dorothy-config] should use [config-edit]
+			# ^ at some point, `dorothy-config` should use `config-edit`
 			config-edit --file="$DOROTHY/user/config/interactive.nu" --needle="\$env.DOROTHY_THEME" --line="\$env.DOROTHY_THEME = $(echo-quote -- "$theme")" --add
 		fi
 		if [[ -f "$DOROTHY/user/config/interactive.xsh" ]]; then
@@ -1459,7 +1459,7 @@ function dorothy_() (
 		return "$__lint_status"
 	}
 
-	# this is shared between [debug-bash] and [dorothy]
+	# this is shared between `debug-bash` and `dorothy`
 	function act_test {
 		# log
 		__print_style --h1='Dorothy Tests'
@@ -1756,7 +1756,7 @@ function dorothy_() (
 					)
 				fi
 
-				# is the file used by other commands? excludes [cmd] and `cmd` usage which are in comments and messages
+				# is the file used by other commands? excludes `cmd` and `cmd` comment usage which are in comments and messages
 				matches="$(rg --files-with-matches --regexp="[^\[\`]${filename}" "${scan_paths[@]}" || :)"
 				if [[ -z $matches || $matches == "$filepath" ]]; then
 					messages+=(
