dorothy: attempt to fix devuan openssl-client
/ref https://dev1galaxy.org/viewtopic.php?pid=59250#p59250
/ref https://github.com/bevry/dorothy/actions/runs/19154983185/job/54753604639

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -424,6 +424,21 @@ function dorothy_() (
 		# [readme.md] - popularity sorted, does updates, don't do noconfirm, skips extras
 		# https://repology.org/project/gawk/versions
 		if __command_missing -- bash curl grep git awk; then
+			# ensure that PATH locations are not writable by other, which causes various linux distros to fail if so
+			# https://dev1galaxy.org/viewtopic.php?pid=59250#p59250
+			# https://github.com/bevry/dorothy/actions/runs/19154983185/job/54753604639
+			# only have it if we need to install these dependencies, as if they are installed, we can assume that the environment is already configured correctly
+			local paths=()
+			__split --source={PATH} --delimiter=':' --no-zero-length --target={paths}
+			if [[ -n $CI ]]; then
+				# be verbose on CI, so we can let upstreams know of issues
+				chmod -fv o-w "${paths[@]}" || :
+			else
+				# be quiet locally, as it would confuse users
+				chmod -f o-w "${paths[@]}" &>/dev/null || :
+			fi
+			# fs-own --permissions='o-w' --optional --recursive --verbose -- "${paths[@]}" <-- not available yet, as Dorothy is not yet installed, yet it has to be this early, as the below installs can fail if this is not done
+
 			# preference sort
 			if __command_exists -- apt-get; then
 				# for ubuntu/debian/kali
