upgrade trunk and fix linting

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -188,7 +188,15 @@ function ensure_development_dependencies {
 	source "$DOROTHY/sources/environment.sh"
 }
 
-function load_nullglob {
+function require_globstar {
+	# can't source things, as may not be cloned yet
+	shopt -s globstar || {
+		echo "Missing globstar support." >/dev/stderr
+		return 1
+	}
+}
+
+function require_nullglob {
 	# can't source things, as may not be cloned yet
 	shopt -s nullglob || {
 		echo "Missing nullglob support." >/dev/stderr
@@ -280,7 +288,7 @@ function relocate_dorothy_if_necessary {
 		fi
 
 		# ensure correct permissions
-		load_nullglob
+		require_nullglob
 		make_executable "$DOROTHY/commands/"*
 	fi # else fresh install and no prior clones exist
 }
@@ -302,11 +310,11 @@ function relocate_user_if_necessary {
 
 		# ensure correct permissions
 		if test -d "$DOROTHY/user/commands"; then
-			load_nullglob
+			require_nullglob
 			make_executable "$DOROTHY/user/commands/"*
 		fi
 		if test -d "$DOROTHY/user/commands.local"; then
-			load_nullglob
+			require_nullglob
 			make_executable "$DOROTHY/user/commands.local/"*
 		fi
 	fi # else fresh install and no prior clones exist
@@ -394,8 +402,8 @@ function prepare_dorothy {
 }
 
 function stage_new_files {
-	source "$DOROTHY/sources/globstar.bash"
-	source "$DOROTHY/sources/nullglob.bash"
+	require_globstar
+	require_nullglob
 	local path="$1"
 	pushd "$path" >/dev/null
 	# The following paths are ignored by one of your .gitignore files: ...
@@ -415,7 +423,7 @@ function stage_changed_files {
 
 function correct_permissions {
 	# directories and commands must be executable
-	source "$DOROTHY/sources/nullglob.bash"
+	require_nullglob
 	require_array 'mapfile'
 	local directories commands
 	commands=(
@@ -429,7 +437,7 @@ function correct_permissions {
 }
 
 function ensure_permissions_configured {
-	source "$(which eval-helper)"
+	source "$(command -v eval-helper)"
 
 	eval-helper --quiet --no-wrap \
 		--pending="$(echo-style --bold="Correcting permissions...")" \
@@ -942,11 +950,11 @@ function act_review {
 function act_theme {
 	assert_dorothy_and_user_cloned
 	ensure_minimal_dependencies
+	require_nullglob
 
 	# features
 	echo-segment --h1='Select Dorothy Theme'
 	local themes theme files
-	source "$DOROTHY/sources/nullglob.bash"
 	source "$DOROTHY/sources/config.sh"
 	require_array 'mapfile'
 
@@ -1074,7 +1082,7 @@ function act_test {
 
 	# able to test on bash v3?
 	local bash bashv3=''
-	bash="$(which bash)"
+	bash="$(command -v bash)"
 	if is-mac && test "$bash" != '/bin/bash' && [[ "$(/bin/bash --version || :)" == 'GNU bash, version 3.'* ]]; then
 		bashv3='/bin/bash'
 	fi
