improvements to TTY and STDIN reporting
- add `debug-terminal-(stdin|tty)`
- simplify `get-terminal-*-support` checks
- `IFS=''` to `IFS=` as they are equivalent
- get-terminal-theme: add `--ignore-cache` option
- echo-file: correctly handle bat theme in cases where theme could not be detected, such as inside `ssh -T`

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -1905,6 +1905,13 @@ function dorothy_() (
 		echo-style --h1='Dorothy Tests'
 		source "$DOROTHY/sources/ripgrep.bash"
 
+		# run relevant debugs
+		__print_lines '' 'debug-terminal-stdin:'
+		debug-terminal-stdin || :
+		__print_lines '' 'debug-terminal-tty:'
+		debug-terminal-tty || :
+		__print_lines ''
+
 		# able to test on bash v3?
 		local bash has_macos_bash_v3='no'
 		bash="$(type -P bash)"
@@ -1916,7 +1923,7 @@ function dorothy_() (
 		local commands filepath filename failures=() scan_paths=(
 			"$DOROTHY/commands/"
 			"$DOROTHY/commands.beta/"
-			"$DOROTHY/commands.deprecated/"
+			# "$DOROTHY/commands.deprecated/" <-- don't run deprecated tests, as that will cause deprecated warnings, which cases dorothy-warnings test to fail
 		)
 		if test -d "$DOROTHY/user"; then
 			if test -d "$DOROTHY/user/commands"; then
