dorothy: attempt fix trunk shfmt bug

diff --git a/commands/dorothy b/commands/dorothy
--- a/commands/dorothy
+++ b/commands/dorothy
@@ -1406,21 +1406,16 @@ function dorothy_() (
 		function __lint() (
 			local __status=0
 			cd "$path" || return $?
-			# if format fails, it is likely for a source format failure (in which try again if formatted), otherwise a check failure
+			# if format fails, it is likely for a check failure
+			# `--ignore-git-state` is necessary to prevent trunk shfmt bugs
 			if [[ $format == 'yes' && $check == 'yes' ]]; then
-				if trunk fmt --all "${trunk_args[@]}"; then
-					return 0
-				elif trunk fmt "${trunk_args[@]}" -- "$DOROTHY/sources/"* && trunk fmt --all "${trunk_args[@]}"; then
+				if trunk fmt --all --ignore-git-state "${trunk_args[@]}"; then
 					return 0
 				else
 					trunk check --all "${trunk_args[@]}" || return $?
 				fi
 			elif [[ $format == 'yes' ]]; then
-				if trunk fmt --all "${trunk_args[@]}"; then
-					return 0
-				else
-					{ trunk fmt "${trunk_args[@]}" -- "$DOROTHY/sources/"* && trunk fmt --all "${trunk_args[@]}"; } || return $?
-				fi
+				trunk fmt --all --ignore-git-state "${trunk_args[@]}" || return $?
 			else
 				trunk check --all "${trunk_args[@]}" || return $?
 			fi
