down: fedora wget still trying to wget2

diff --git a/commands/down b/commands/down
--- a/commands/down
+++ b/commands/down
@@ -271,7 +271,6 @@ function down_() (
 	local wget_binary='wget' wget_busybox='no'
 	function __prepare_wget {
 		if __command_exists -- wget1; then
-			option_tool='wget'
 			wget_binary='wget1'
 		elif __command_exists -- wget && wget --version 2>/dev/null | grep --quiet --fixed-strings --regexp='Wget 1.'; then
 			option_tool='wget'
@@ -284,16 +283,22 @@ function down_() (
 			return 75 # EPROGMISMATCH 75 Program version wrong
 		fi
 	}
-	if [[ -z $option_tool ]]; then
-		__prepare_wget || {
+	if [[ -z $option_tool || $option_tool == 'wget' ]]; then
+		if __prepare_wget; then
+			# wget already correct, use wget
+			option_tool='wget'
+		elif [[ -z $option_tool ]]; then
+			# wget not correct, but wget is not explicitly desired, fallback to curl
 			option_tool='curl'
-		}
-	elif [[ $option_tool == 'wget' ]]; then
-		__prepare_wget || __command_required -- "$wget_binary" || __prepare_wget || {
+		elif __command_required -- "$wget_binary" && __prepare_wget; then
+			# wget now installed and correct, use wget
+			option_tool='wget'
+		else
+			# wget was requested, but failed to become correct, fail
 			__print_error --code='down' ' is only compatible with ' --code='wget' ' (version 1), as ' --code='wget2' ' does not return failure exit status'
-			"$wget_binary" --version >&2
+			"$wget_binary" --version >&2 || :
 			return 75 # EPROGMISMATCH 75 Program version wrong
-		}
+		fi
 	fi
 
 	# do download
