down: wget/wget1/wget2 detection

diff --git a/commands/down b/commands/down
--- a/commands/down
+++ b/commands/down
@@ -248,13 +248,28 @@ function down_() (
 		fi
 	fi
 
-	# prefer wget if it is installed, as it has a better progress bar
-	if [[ -z $option_tool ]]; then
-		if __command_exists -- wget; then
+	# workaround wget/wget1/wget2 discrepancies
+	# and prefer wget/wget1 if it is installed, as it has a better progress bar, otherwise use curl
+	# don't use wget2, as it doesn't return failure exit status, so it is not suitable for our use
+	local wget_binary=''
+	function __prepare_wget {
+		if __command_exists -- wget1; then
 			option_tool='wget'
+			wget_binary='wget1'
+		elif __command_exists -- wget && wget --version 2>/dev/null | grep --quiet --fixed-strings --regexp='Wget 1.'; then
+			option_tool='wget'
+			wget_binary='wget'
+		elif is-busybox -- wget; then
+			option_tool='wget'
+			wget_binary='wget'
 		else
-			option_tool='curl'
+			return 75 # EPROGMISMATCH 75 Program version wrong
 		fi
+	}
+	if [[ -z $option_tool ]]; then
+		__prepare_wget || {
+			option_tool='curl'
+		}
 	fi
 
 	# do download
@@ -264,6 +279,13 @@ function down_() (
 		if __command_missing -- wget; then
 			setup-util-wget --quiet
 		fi
+		if [[ -z $wget_binary ]]; then
+			__prepare_wget || {
+				echo-error 'down is only compatible with wget version 1, as wget2 does not return failure exit status'
+				return 75 # EPROGMISMATCH 75 Program version wrong
+			}
+		fi
+
 		# wget2 is different to wget, however fedora aliases wget to wget2, which is broken as wget2 does not return failure exit status
 		local wget_options=()
 		if is-busybox -- wget; then
@@ -308,7 +330,7 @@ function down_() (
 			if [[ -n $download_file ]]; then
 				fs-rm --quiet --no-confirm -- "$download_file"
 			fi
-			eval-helper "${eval_options[@]}" -- wget "${wget_options[@]}"
+			eval-helper "${eval_options[@]}" -- "$wget_binary" "${wget_options[@]}"
 		)
 	elif [[ $option_tool == 'curl' ]]; then
 		# install curl if it is is missing
