shellcheck, shellformat, help redo #45
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/echo-split b/commands/echo-split
--- a/commands/echo-split
+++ b/commands/echo-split
@@ -16,13 +16,13 @@ fi
 # just echo each argument, which will put each part on a newline
 if test -z "${1-}" -o "${1-}" = $'\n'; then
 	echo-lines "${@:3}"
-	exit "$?"  # exit with the above on success and failure
+	exit "$?" # exit with the above on success and failure
 fi
 
 # we have a delim, so split each argument by it
 for arg in "${@:3}"; do
 	# without a trailing delim added, then the last item will have a trailing newline attached
 	# so we add a trailing delim to ensure the last item will be an empty newline which can be ignored
-	mapfile -td "$1" parts <<< "${arg}${1}"
+	mapfile -td "$1" parts <<<"${arg}${1}"
 	echo-lines "${parts[@]::${#parts[@]}-1}"
 done
