echo-json and co: fix missing dependencies

diff --git a/commands/echo-math b/commands/echo-math
--- a/commands/echo-math
+++ b/commands/echo-math
@@ -132,10 +132,18 @@ function echo_math() (
 	# 0. becomes ., hence need for printf
 	# awk: 6 decimals by default
 
+	function __install_if_missing {
+		if __command_missing -- "$option_tool"; then
+			get-installer --first-success --invoke --quiet -- "$option_tool" || return
+		fi
+	}
+
 	function __wrap {
 		"$@" || {
 			local -i exit_status=$?
 			# use echo-quote over echo-escape-command as echo-escape-command uses too many slashes
+			# echo-quote: Failed to compute: awk -v precision=6 'BEGIN { printf "%." precision "f\n", / }'
+			# echo-escape-command: Failed to compute: awk -v precision=6 BEGIN\ \{\ printf\ \"%.\"\ precision\ \"f\\n\"\,\ /\ \}
 			__print_error 'Failed to compute: ' --code="$(echo-quote --always=no -- "$@" | echo-join --stdin || :)" --newline \
 				"With $1 binary: " --code="$(type -P "$1" || :)" --newline \
 				"With $1 version: " --code="$($1 --version 2>/dev/null || :)"
@@ -144,12 +152,14 @@ function echo_math() (
 	}
 
 	if [[ $option_tool == 'bc' ]]; then
+		__install_if_missing
 		function on_line {
 			local formula="$1" fodder_to_respect_exit_status
 			fodder_to_respect_exit_status="$(__wrap bc --mathlib --no-prompt --no-read-prompt --standard --warn --expression="$formula")"
 			printf "%.${option_precision}f\n" "$fodder_to_respect_exit_status"
 		}
 	elif [[ $option_tool == 'deno' ]]; then
+		__install_if_missing
 		local deno_script
 		deno_script="$(type -P echo-math.ts)"
 		function on_line {
@@ -157,16 +167,19 @@ function echo_math() (
 			__wrap "$deno_script" "$option_precision" "$formula"
 		}
 	elif [[ $option_tool == 'perl' ]]; then
+		__install_if_missing
 		function on_line {
 			local formula="$1"
 			__wrap perl -E "say sprintf '%.${option_precision}f', $formula"
 		}
 	elif [[ $option_tool == 'awk' ]]; then
+		__install_if_missing
 		function on_line {
 			local formula="$1"
 			__wrap awk -v precision="$option_precision" 'BEGIN { printf "%." precision "f\n", '"$formula"' }'
 		}
 	elif [[ $option_tool == 'gawk' ]]; then
+		__install_if_missing
 		function on_line {
 			local formula="$1"
 			__wrap gawk -v precision="$option_precision" 'BEGIN { printf "%." precision "f\n", '"$formula"' }'
