rename `config-exit-code` to `config-exit-status`
as that is what it is actually called

diff --git a/commands/echo-exit-status b/commands/echo-exit-status
--- a/commands/echo-exit-status
+++ b/commands/echo-exit-status
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-function echo_exit_code() (
+function echo_exit_status() (
 	source "$DOROTHY/sources/bash.bash"
 
 	# =====================================
@@ -9,15 +9,15 @@ function echo_exit_code() (
 	function help {
 		cat <<-EOF >/dev/stderr
 			ABOUT:
-			Given a command as arguments, execute it, output the exit code.
+			Given a command as arguments, execute it, output the exit status.
 
 			USAGE:
-			echo-exit-code [--] ...<command>
+			echo-exit-status [--] ...<command>
 
 			EXAMPLES:
-			echo-exit-code -- exit 0    # outputs: 0    exit code: 0
-			echo-exit-code -- exit 1    # outputs: 1    exit code: 0
-			echo-exit-code -- exit 2    # outputs: 2    exit code: 0
+			echo-exit-status -- exit 0    # outputs: 0    exit status: 0
+			echo-exit-status -- exit 1    # outputs: 1    exit status: 0
+			echo-exit-status -- exit 2    # outputs: 2    exit status: 0
 		EOF
 		return 22 # EINVAL 22 Invalid argument
 	}
@@ -54,5 +54,5 @@ function echo_exit_code() (
 
 # fire if invoked standalone
 if test "$0" = "${BASH_SOURCE[0]}"; then
-	echo_exit_code "$@"
+	echo_exit_status "$@"
 fi
