echo-exit-code: modern conventions

diff --git a/commands/echo-exit-code b/commands/echo-exit-code
--- a/commands/echo-exit-code
+++ b/commands/echo-exit-code
@@ -1,21 +1,60 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-if test "${1-}" = '--help'; then
+# =====================================
+# Arguments
+
+# help
+function help() {
 	cat <<-EOF >/dev/stderr
+		ABOUT:
+		Given a command as arguments, execute it, output the exit code.
+
 		USAGE:
-		echo-exit-code exit 0
-		# ^ echos 0, returns 0
+		echo-exit-affirmative [--] <command...>
 
-		echo-exit-code exit 1
-		# ^ echos 1, returns 0
-
-		echo-exit-code exit 2
-		# ^ echos 2, returns 0
+		EXAMPLES:
+		echo-exit-affirmative -- exit 0    # outputs: 0    exit code: 0
+		echo-exit-affirmative -- exit 1    # outputs: 1    exit code: 0
+		echo-exit-affirmative -- exit 2    # outputs: 2    exit code: 0
 	EOF
-	exit 22 # Invalid argument
+	if test "$#" -ne 0; then
+		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
+	fi
+	return 22 # Invalid argument
+}
+
+# process
+option_cmd=()
+while test "$#" -ne 0; do
+	item="$1"
+	shift
+	case "$item" in
+	'help' | '--help' | '-h') help ;;
+	'--')
+		option_cmd+=("$@")
+		shift "$#"
+		break
+		;;
+	*) option_cmd+=("$item") ;;
+	esac
+done
+
+# check
+if test "${#option_cmd[@]}" -eq 0; then
+	help "No command was provided."
 fi
 
-ec=0 && ("$@") || ec="$?"
-echo "$ec"
-exit 0
+# =====================================
+# Action
+
+function echo_exit_code {
+	local ec
+	ec=0 && ("$@") || ec="$?"
+	echo "$ec"
+}
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	echo_exit_code "${option_cmd[@]}"
+fi
