echo-math: add verbose failure messages
this is trying to determine why awk is failing on CI:

```
awk: syntax error at source line 1
 context is
	BEGIN { printf "%." precision "f\n", >>>  % <<< s }
awk: illegal statement at source line 1
```

diff --git a/commands/echo-math b/commands/echo-math
--- a/commands/echo-math
+++ b/commands/echo-math
@@ -134,10 +134,20 @@ function echo_math() (
 	# 0. becomes ., hence need for printf
 	# awk: 6 decimals by default
 
+	function __wrap {
+		"$@" || {
+			local -i exit_status=$?
+			echo-error 'Failed to compute: '  --code="$(echo-escape-command -- "$@" || :)" --newline \
+				"With $1: " --code="$(type -P "$1" || :)" --newline \
+				"With $1 version: " --code="$($1 --version 2>/dev/null || :)"
+			return "$exit_status"
+		}
+	}
+
 	if [[ $option_tool == 'bc' ]]; then
 		function on_line {
 			local formula="$1" fodder_to_respect_exit_status
-			fodder_to_respect_exit_status="$(bc --mathlib --no-prompt --no-read-prompt --standard --warn --expression="$formula")"
+			fodder_to_respect_exit_status="$(__wrap bc --mathlib --no-prompt --no-read-prompt --standard --warn --expression="$formula")"
 			printf "%.${option_precision}f\n" "$fodder_to_respect_exit_status"
 		}
 	elif [[ $option_tool == 'deno' ]]; then
@@ -145,22 +155,22 @@ function echo_math() (
 		deno_script="$(type -P echo-math.ts)"
 		function on_line {
 			local formula="$1"
-			"$deno_script" "$option_precision" "$formula"
+			__wrap "$deno_script" "$option_precision" "$formula"
 		}
 	elif [[ $option_tool == 'perl' ]]; then
 		function on_line {
 			local formula="$1"
-			perl -E "say sprintf '%.${option_precision}f', $formula"
+			__wrap perl -E "say sprintf '%.${option_precision}f', $formula"
 		}
 	elif [[ $option_tool == 'awk' ]]; then
 		function on_line {
 			local formula="$1"
-			awk -v precision="$option_precision" 'BEGIN { printf "%." precision "f\n", '"$formula"' }'
+			__wrap awk -v precision="$option_precision" 'BEGIN { printf "%." precision "f\n", '"$formula"' }'
 		}
 	elif [[ $option_tool == 'gawk' ]]; then
 		function on_line {
 			local formula="$1"
-			gawk -v precision="$option_precision" 'BEGIN { printf "%." precision "f\n", '"$formula"' }'
+			__wrap gawk -v precision="$option_precision" 'BEGIN { printf "%." precision "f\n", '"$formula"' }'
 		}
 	else
 		help "The tool [$option_tool] is not yet supported."
