modern function conventions everywhere
also fixes incorrect convention application to:

- edit-dns
- fs-rm
- pdf-decrypt
- rm-vmware
- version-compare

diff --git a/commands/echo-affirmative b/commands/echo-affirmative
--- a/commands/echo-affirmative
+++ b/commands/echo-affirmative
@@ -1,63 +1,70 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# turns affirmative arguments into yes
-# turns non-affirmative arguments into no
+function echo-affirmative() (
+	# turns affirmative arguments into yes
+	# turns non-affirmative arguments into no
 
-function help {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		For each input, output "yes" if affirmative, "no" if non-affirmative, otherwise note the invalidity to stderr.
-		Using [is-affirmative] for the validation.
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			For each input, output "yes" if affirmative, "no" if non-affirmative, otherwise note the invalidity to stderr.
+			Using [is-affirmative] for the validation.
 
-		USAGE:
-		echo-affirmative <...input>
-		echo-lines <...input> | echo-affirmative
+			USAGE:
+			echo-affirmative <...input>
+			echo-lines <...input> | echo-affirmative
 
-		EXAMPLE:
+			EXAMPLE:
 
-		# success case
-		echo-affirmative yes no true false
+			# success case
+			echo-affirmative yes no true false
 
-		    yes
-		    no
-		    yes
-		    no
-		    # exit status: 0
+			    yes
+			    no
+			    yes
+			    no
+			    # exit status: 0
 
-		# failure case
-		echo-affirmative yes no true false apple orange
+			# failure case
+			echo-affirmative yes no true false apple orange
 
-		    yes
-		    no
-		    yes
-		    no
-		    [apple] is neither affirmative or non-affirmative
-		    [orange] is neither affirmative or non-affirmative
-		    # exit status: 22
+			    yes
+			    no
+			    yes
+			    no
+			    [apple] is neither affirmative or non-affirmative
+			    [orange] is neither affirmative or non-affirmative
+			    # exit status: 22
 
-	EOF
-	return 22 # Invalid argument
-}
-
-any_invalid=no
-function on_input {
-	local ec
-	ec=0 && is-affirmative "$1" || ec="$?"
-	if test "$ec" -eq 0; then
-		echo 'yes'
-	elif test "$ec" -eq 1; then
-		echo 'no'
-	else
-		echo-style --error="[$1] is neither affirmative or non-affirmative" >/dev/stderr
-		any_invalid=yes
-	fi
-}
-
-function on_finish {
-	if test "$any_invalid" = yes; then
+		EOF
 		return 22 # Invalid argument
-	fi
-}
+	}
 
-source "$DOROTHY/sources/stdinargs.bash"
+	local any_invalid=no
+	function on_input {
+		local ec
+		ec=0 && is-affirmative "$1" || ec="$?"
+		if test "$ec" -eq 0; then
+			echo 'yes'
+		elif test "$ec" -eq 1; then
+			echo 'no'
+		else
+			echo-style --error="[$1] is neither affirmative or non-affirmative" >/dev/stderr
+			any_invalid=yes
+		fi
+	}
+
+	function on_finish {
+		if test "$any_invalid" = yes; then
+			return 22 # Invalid argument
+		fi
+	}
+
+	source "$DOROTHY/sources/stdinargs.bash"
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	echo-affirmative "$@"
+fi
diff --git a/commands/echo-if-nonempty b/commands/echo-if-nonempty
--- a/commands/echo-if-nonempty
+++ b/commands/echo-if-nonempty
@@ -1,37 +1,44 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-function help {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Output inputs that are non-empty.
+function echo-if-nonempty() (
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Output inputs that are non-empty.
 
-		USAGE:
-		echo-if-nonempty <...input>
-		echo-lines <...input> | echo-if-nonempty
+			USAGE:
+			echo-if-nonempty <...input>
+			echo-lines <...input> | echo-if-nonempty
 
-		EXAMPLES:
+			EXAMPLES:
 
-		echo-if-nonempty a '' c
+			echo-if-nonempty a '' c
 
-		    a
-			c
-		    # exit status: 0
+			    a
+				c
+			    # exit status: 0
 
-		echo-lines a '' c | echo-if-nonempty
+			echo-lines a '' c | echo-if-nonempty
 
-		    a
-			c
-		    # exit status: 0
+			    a
+				c
+			    # exit status: 0
 
-	EOF
-	return 22 # Invalid argument
-}
+		EOF
+		return 22 # Invalid argument
+	}
 
-function on_input {
-	if ! is-empty-string "$1"; then
-		echo "$1"
-	fi
-}
+	function on_input {
+		if ! is-empty-string "$1"; then
+			echo "$1"
+		fi
+	}
 
-source "$DOROTHY/sources/stdinargs.bash"
+	source "$DOROTHY/sources/stdinargs.bash"
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	echo-if-nonempty "$@"
+fi
diff --git a/commands/echo-mkdir b/commands/echo-mkdir
--- a/commands/echo-mkdir
+++ b/commands/echo-mkdir
@@ -1,47 +1,54 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-function help {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		Make a directory at each input path, if it was not already one, and output its absolute path.
+function echo-mkdir() (
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Make a directory at each input path, if it was not already one, and output its absolute path.
 
-		USAGE:
-		echo-mkdir [...options] <...input>
-		echo-lines <...input> | echo-mkdir [...options]
+			USAGE:
+			echo-mkdir [...options] <...input>
+			echo-lines <...input> | echo-mkdir [...options]
 
-		OPTIONS:
-		--sudo
-		    If provided, use sudo to make the directory.
+			OPTIONS:
+			--sudo
+			    If provided, use sudo to make the directory.
 
-		EXAMPLE:
+			EXAMPLE:
 
-		echo-mkdir ./temp
+			echo-mkdir ./temp
 
-		    $(pwd)/temp
-		    # exit status: 0
+			    $(pwd)/temp
+			    # exit status: 0
 
-	EOF
-	return 22 # Invalid argument
-}
+		EOF
+		return 22 # Invalid argument
+	}
 
-# stip --sudo option if it exists
-# and construct our cmd
-cmd=()
-if test "$1" = '--sudo'; then
-	shift
-	cmd=('sudo' 'mkdir' '-p')
-else
-	cmd=('mkdir' '-p')
-fi
-
-function on_input {
-	if test -d "$1" || ("${cmd[@]}" "$1"); then
-		fs-absolute "$1"
-		return 0
+	# stip --sudo option if it exists
+	# and construct our cmd
+	local cmd=()
+	if test "$1" = '--sudo'; then
+		shift
+		cmd=('sudo' 'mkdir' '-p')
 	else
-		return 1
+		cmd=('mkdir' '-p')
 	fi
-}
 
-source "$DOROTHY/sources/stdinargs.bash"
+	function on_input {
+		if test -d "$1" || ("${cmd[@]}" "$1"); then
+			fs-absolute "$1"
+			return
+		else
+			return 1
+		fi
+	}
+
+	source "$DOROTHY/sources/stdinargs.bash"
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	echo-mkdir "$@"
+fi
diff --git a/commands/echo-non-affirmative b/commands/echo-non-affirmative
--- a/commands/echo-non-affirmative
+++ b/commands/echo-non-affirmative
@@ -1,63 +1,70 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# turns affirmative arguments into no
-# turns non-affirmative arguments into yes
+function echo-non-affirmative() (
+	# turns affirmative arguments into no
+	# turns non-affirmative arguments into yes
 
-function help {
-	cat <<-EOF >/dev/stderr
-		ABOUT:
-		For each input, output "yes" if non-affirmative, "no" if affirmative, otherwise note the invalidity to stderr.
-		Using [is-affirmative] for the validation.
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			For each input, output "yes" if non-affirmative, "no" if affirmative, otherwise note the invalidity to stderr.
+			Using [is-affirmative] for the validation.
 
-		USAGE:
-		echo-non-affirmative <...input>
-		echo-lines <...input> | echo-non-affirmative
+			USAGE:
+			echo-non-affirmative <...input>
+			echo-lines <...input> | echo-non-affirmative
 
-		EXAMPLE:
+			EXAMPLE:
 
-		# success case
-		echo-non-affirmative yes no true false
+			# success case
+			echo-non-affirmative yes no true false
 
-		    no
-		    yes
-		    no
-		    yes
-		    # exit status: 0
+			    no
+			    yes
+			    no
+			    yes
+			    # exit status: 0
 
-		# failure case
-		echo-non-affirmative yes no true false apple orange
+			# failure case
+			echo-non-affirmative yes no true false apple orange
 
-		    no
-		    yes
-		    no
-		    yes
-		    [apple] is neither affirmative or non-affirmative
-		    [orange] is neither affirmative or non-affirmative
-		    # exit status: 22
+			    no
+			    yes
+			    no
+			    yes
+			    [apple] is neither affirmative or non-affirmative
+			    [orange] is neither affirmative or non-affirmative
+			    # exit status: 22
 
-	EOF
-	return 22 # Invalid argument
-}
-
-any_invalid=no
-function on_input {
-	local ec
-	ec=0 && is-affirmative "$1" || ec="$?"
-	if test "$ec" -eq 0; then
-		echo 'no'
-	elif test "$ec" -eq 1; then
-		echo 'yes'
-	else
-		echo-style --error="[$1] is neither affirmative or non-affirmative" >/dev/stderr
-		any_invalid=yes
-	fi
-}
-
-function on_finish {
-	if test "$any_invalid" = yes; then
+		EOF
 		return 22 # Invalid argument
-	fi
-}
+	}
 
-source "$DOROTHY/sources/stdinargs.bash"
+	local any_invalid=no
+	function on_input {
+		local ec
+		ec=0 && is-affirmative "$1" || ec="$?"
+		if test "$ec" -eq 0; then
+			echo 'no'
+		elif test "$ec" -eq 1; then
+			echo 'yes'
+		else
+			echo-style --error="[$1] is neither affirmative or non-affirmative" >/dev/stderr
+			any_invalid=yes
+		fi
+	}
+
+	function on_finish {
+		if test "$any_invalid" = yes; then
+			return 22 # Invalid argument
+		fi
+	}
+
+	source "$DOROTHY/sources/stdinargs.bash"
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	echo-non-affirmative "$@"
+fi
diff --git a/commands/echo-revolving-door b/commands/echo-revolving-door
--- a/commands/echo-revolving-door
+++ b/commands/echo-revolving-door
@@ -1,39 +1,46 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# the `|| test -n` trick is from https://unix.stackexchange.com/a/418067/50703
-# and allows trailing lines that do not have a trealing newline to still work
-# as is the case with:
-# sudo pacman -S --needed --noconfirm --quiet bash-completion |& echo-revolving-door
+function echo-revolving-door() (
+	# the `|| test -n` trick is from https://unix.stackexchange.com/a/418067/50703
+	# and allows trailing lines that do not have a trealing newline to still work
+	# as is the case with:
+	# sudo pacman -S --needed --noconfirm --quiet bash-completion |& echo-revolving-door
 
-# see echo-clear-line, and echo-clear-lines for similar commands
+	# see echo-clear-line, and echo-clear-lines for similar commands
 
-# cols is essential, as lines larger than the window will wrap and become two cusor lines
-#    and we can't have that
-# macos terminal will always have cols=80 (or whatever the terminal preferences set),
-#    and it does not adjust to resizes
-cols="$(tput cols 2>/dev/null || :)"
+	# cols is essential, as lines larger than the window will wrap and become two cusor lines
+	#    and we can't have that
+	# macos terminal will always have cols=80 (or whatever the terminal preferences set),
+	#    and it does not adjust to resizes
+	cols="$(tput cols 2>/dev/null || :)"
 
-# if we are not running in a TTY, [tput cols] will fail, so just dump stdin if that is the case
-# tput: No value for $TERM and no -T specified
-if test -z "$cols"; then
-	cat
-else
-	# we are in a TTY, so proceed with revolving door
-	queue=0
+	# if we are not running in a TTY, [tput cols] will fail, so just dump stdin if that is the case
+	# tput: No value for $TERM and no -T specified
+	if test -z "$cols"; then
+		cat
+	else
+		# we are in a TTY, so proceed with revolving door
+		queue=0
 
-	# timeout will cause read to emit a failure exit code, which causes the while loop to fail, which causes everything to fail
-	while read -r -n "$cols" line || test -n "$line"; do
+		# timeout will cause read to emit a failure exit code, which causes the while loop to fail, which causes everything to fail
+		while read -r -n "$cols" line || test -n "$line"; do
+			while test "$queue" -ne 0; do
+				printf '\e[F\e[J'
+				queue=$((queue - 1))
+			done
+			echo "$line"
+			queue=$((queue + 1))
+		done </dev/stdin
+
 		while test "$queue" -ne 0; do
 			printf '\e[F\e[J'
 			queue=$((queue - 1))
 		done
-		echo "$line"
-		queue=$((queue + 1))
-	done </dev/stdin
+	fi
+)
 
-	while test "$queue" -ne 0; do
-		printf '\e[F\e[J'
-		queue=$((queue - 1))
-	done
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	echo-revolving-door "$@"
 fi
diff --git a/commands/eval-no-color b/commands/eval-no-color
--- a/commands/eval-no-color
+++ b/commands/eval-no-color
@@ -1,6 +1,13 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# note: piping to echo-no-colors doesn't seem to work, hence why we use sed directly
-(env NO_COLOR=yes "$@") > >(sed 's/\x1b\[[0-9;]*m//g') 2> >(sed 's/\x1b\[[0-9;]*m//g' >&2)
-# ^ maintains stdout, stderr, and exit code
+function eval-no-color() ( 
+	# note: piping to echo-no-colors doesn't seem to work, hence why we use sed directly
+	(env NO_COLOR=yes "$@") > >(sed 's/\x1b\[[0-9;]*m//g') 2> >(sed 's/\x1b\[[0-9;]*m//g' >&2)
+	# ^ maintains stdout, stderr, and exit code
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	eval-no-color "$@"
+fi
diff --git a/commands/get-url-upgrade b/commands/get-url-upgrade
--- a/commands/get-url-upgrade
+++ b/commands/get-url-upgrade
@@ -1,104 +1,111 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# dependencies
-setup-util-sd --quiet
+function get-url-upgrade() (
+	# dependencies
+	setup-util-sd --quiet
 
-# prepare
-url="$1"
+	# prepare
+	local url="$1" protocol result
 
-# remove superflous trailing slash
-# shellcheck disable=SC2016
-url="$(echo "$url" | sd '([.][a-z]+)[/]$' '$1')"
+	# remove superflous trailing slash
+	# shellcheck disable=SC2016
+	url="$(echo "$url" | sd '([.][a-z]+)[/]$' '$1')"
 
-# test the original url
-protocol="$(get-url-protocol "$url" || :)"
-if test -z "$protocol"; then
-	# try http, which tries https first, otherwise fail
-	stderr echo "[$url] missing protocol, will try variations"
-	get-url-upgrade "http://$url"
-	exit "$?" # exit with the above on success and failure
-elif test "$protocol" = 'https'; then
-	# test original url works
-	if ! fetch --ok "$url"; then
-		stderr echo "[$url] failing, will try variations"
+	# test the original url
+	protocol="$(get-url-protocol "$url" || :)"
+	if test -z "$protocol"; then
+		# try http, which tries https first, otherwise fail
+		echo "[$url] missing protocol, will try variations" >/dev/stderr
+		get-url-upgrade "http://$url"
+		return "$?" # return with the above on success and failure
+	elif test "$protocol" = 'https'; then
+		# test original url works
+		if ! fetch --ok "$url"; then
+			echo "[$url] failing, will try variations" >/dev/stderr
+		fi
+	elif test "$protocol" = 'http'; then
+		# try upgrade to https
+		result="${url//http\:/https\:}"
+		result="$(get-url-upgrade "$result")"
+		if test -n "$result"; then
+			echo "$result"
+			return
+		fi
+		result=''
+	else
+		echo "[$url] invalid protocol, unable to upgrade" >/dev/stderr
+		return 1
 	fi
-elif test "$protocol" = 'http'; then
-	# try upgrade to https
-	result="${url//http\:/https\:}"
-	result="$(get-url-upgrade "$result")"
-	if test -n "$result"; then
-		echo "$result"
-		exit
+
+	# try removing www
+	result="${url//www./}"
+	if test "$result" != "$url"; then
+		result="$(get-url-upgrade "$result")"
+		if test -n "$result"; then
+			echo "$result"
+			return
+		fi
 	fi
 	result=''
-else
-	stderr echo "[$url] invalid protocol, unable to upgrade"
-	exit 1
-fi
 
-# try removing www
-result="${url//www./}"
-if test "$result" != "$url"; then
-	result="$(get-url-upgrade "$result")"
-	if test -n "$result"; then
-		echo "$result"
-		exit
+	# test the url
+	if fetch --ok "$url"; then
+		# try removing login items
+		if is-inside "$url" 'reg=' registration verify create signup signing reset token join register logout password forgot invitation invite; then
+			result="$(get-url-domain "$url")"
+			if test "$result" != "$url"; then
+				result="$(get-url-upgrade "$result")"
+				if test -n "$result"; then
+					echo "$result"
+					return
+				fi
+			fi
+			result=''
+		fi
+		echo "$url"
+		return
 	fi
-fi
-result=''
 
-# test the url
-if fetch --ok "$url"; then
-	# try removing login items
-	if is-inside "$url" 'reg=' registration verify create signup signing reset token join register logout password forgot invitation invite; then
+	# try removing path if ? is not present
+	if [[ $url != *'?'* ]]; then
 		result="$(get-url-domain "$url")"
 		if test "$result" != "$url"; then
 			result="$(get-url-upgrade "$result")"
 			if test -n "$result"; then
 				echo "$result"
-				exit
+				return
 			fi
 		fi
 		result=''
 	fi
-	echo "$url"
-	exit
-fi
 
-# try removing path if ? is not present
-if [[ $url != *'?'* ]]; then
+	# try removing path altogether
 	result="$(get-url-domain "$url")"
 	if test "$result" != "$url"; then
 		result="$(get-url-upgrade "$result")"
 		if test -n "$result"; then
 			echo "$result"
-			exit
+			return
 		fi
 	fi
 	result=''
-fi
 
-# try removing path altogether
-result="$(get-url-domain "$url")"
-if test "$result" != "$url"; then
-	result="$(get-url-upgrade "$result")"
-	if test -n "$result"; then
-		echo "$result"
-		exit
+	# check if it is a replaced domain
+	if is-needle "$url" 'https://login.live.com' 'https://account.live.com' 'https://account.microsoft.com'; then
+		echo 'https://account.microsoft.com' # curl fails for this, even though it exists, user agent change does nothing
+		return
+	elif is-needle "$url" 'https://signin.ebay.com.au'; then
+		echo 'https://www.ebay.com.au/signin/'
+		return
 	fi
-fi
-result=''
 
-# check if it is a replaced domain
-if is-needle "$url" 'https://login.live.com' 'https://account.live.com' 'https://account.microsoft.com'; then
-	echo 'https://account.microsoft.com' # curl fails for this, even though it exists, user agent change does nothing
-	exit
-elif is-needle "$url" 'https://signin.ebay.com.au'; then
-	echo 'https://www.ebay.com.au/signin/'
-	exit
-fi
+	# unable to make https
+	echo "[$url] unresponsive" >/dev/stderr
+	return 1
+)
 
-# unable to make https
-stderr echo "[$url] unresponsive"
-exit 1
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	get-url-upgrade "$@"
+fi
diff --git a/commands/setup-linux-fonts b/commands/setup-linux-fonts
--- a/commands/setup-linux-fonts
+++ b/commands/setup-linux-fonts
@@ -4,99 +4,106 @@ source "$DOROTHY/sources/strict.bash"
 source "$DOROTHY/sources/nullglob.bash"
 source "$(which eval-helper)"
 
-# =====================================
-# Checks
+function setup-linux-fonts() (
+	# =====================================
+	# Checks
 
-# check that an accident has not occured
-if ! is-linux; then
-	echo-style --notice="[$0] is only intended to be run on Linux systems, skipping." >/dev/stderr
-	exit 0
+	# check that an accident has not occured
+	if ! is-linux; then
+		echo-style --notice="[$0] is only intended to be run on Linux systems, skipping." >/dev/stderr
+		return
+	fi
+
+	# =====================================
+	# Dependencies
+
+	# as there are so many fonts, use the best downloader
+	setup-util-aria2 --quiet --optional
+
+	# =====================================
+	# Action
+
+	# prepare
+	local fonts="$HOME/.fonts"
+	mkdir -p "$fonts"
+
+	# helpers
+	function get_monoid {
+		down https://cdn.rawgit.com/larsenwork/monoid/2db2d289f4e61010dd3f44e09918d9bb32fb96fd/Monoid.zip \
+			--unzip-filter='*.ttf' \
+			--directory="$fonts"
+	}
+	function get_scp {
+		# http://askubuntu.com/a/193073/22776
+		# https://github.com/adobe-fonts/source-code-pro
+		github-download \
+			--slug='adobe-fonts/source-code-pro' \
+			--release='latest' \
+			--asset-filter='^[OT]TF-' \
+			--unzip-filter='*.{otf,ttf}' \
+			--directory="$fonts"
+	}
+	function get_monaco {
+		# https://github.com/showcases/fonts
+		# https://github.com/todylu/monaco.ttf
+		github-download \
+			--slug='todylu/monaco.ttf' \
+			--ref='master' \
+			--pathname='monaco.ttf' \
+			--directory="$fonts"
+	}
+	function get_nerd {
+		# https://www.nerdfonts.com/font-downloads
+		# https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.1.0
+		github-download \
+			--slug='ryanoasis/nerd-fonts' \
+			--release='latest' \
+			--asset-filter='.' \
+			--unzip-filter='*.{otf,ttf}' \
+			--directory="$fonts"
+	}
+	function get_fonts {
+		echo-segment --h1='Install Fonts'
+
+		eval-helper --no-wrap --quiet \
+			--pending="$(echo-style --bold="Installing Monoid...")" \
+			--success="$(echo-style --success="Installed Monoid.")" \
+			--failure="$(echo-style --error="Failed to install Monoid.")" \
+			-- get_monoid
+
+		eval-helper --no-wrap --quiet \
+			--pending="$(echo-style --bold="Installing Source Code Pro...")" \
+			--success="$(echo-style --success="Installed Source Code Pro.")" \
+			--failure="$(echo-style --error="Failed to install Source Code Pro.")" \
+			-- get_scp
+
+		eval-helper --no-wrap --quiet \
+			--pending="$(echo-style --bold="Installing Monaco...")" \
+			--success="$(echo-style --success="Installed Monaco.")" \
+			--failure="$(echo-style --error="Failed to install Monaco.")" \
+			-- get_monaco
+
+		# this one has multiple, so we want to see details for each one
+		eval-helper --no-wrap --no-quiet \
+			--pending="$(echo-style --bold="Installing Nerd Fonts...")" \
+			--success="$(echo-style --success="Installed Nerd Fonts.")" \
+			--failure="$(echo-style --error="Failed to install Nerd Fonts.")" \
+			-- get_nerd
+
+		eval-helper --no-wrap --quiet \
+			--pending="$(echo-style --bold="Refreshing font cache...")" \
+			--success="$(echo-style --success="Refreshed font cache.")" \
+			--failure="$(echo-style --error="Failed to refresh font cache.")" \
+			-- fc-cache -f -v
+
+		echo-segment --g1='Install Fonts'
+	}
+
+	# act
+	get_fonts
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	setup-linux-fonts "$@"
 fi
-
-# =====================================
-# Dependencies
-
-# as there are so many fonts, use the best downloader
-setup-util-aria2 --quiet --optional
-
-# =====================================
-# Action
-
-# prepare
-fonts="$HOME/.fonts"
-mkdir -p "$fonts"
-
-# helpers
-function get_monoid {
-	down https://cdn.rawgit.com/larsenwork/monoid/2db2d289f4e61010dd3f44e09918d9bb32fb96fd/Monoid.zip \
-		--unzip-filter='*.ttf' \
-		--directory="$fonts"
-}
-function get_scp {
-	# http://askubuntu.com/a/193073/22776
-	# https://github.com/adobe-fonts/source-code-pro
-	github-download \
-		--slug='adobe-fonts/source-code-pro' \
-		--release='latest' \
-		--asset-filter='^[OT]TF-' \
-		--unzip-filter='*.{otf,ttf}' \
-		--directory="$fonts"
-}
-function get_monaco {
-	# https://github.com/showcases/fonts
-	# https://github.com/todylu/monaco.ttf
-	github-download \
-		--slug='todylu/monaco.ttf' \
-		--ref='master' \
-		--pathname='monaco.ttf' \
-		--directory="$fonts"
-}
-function get_nerd {
-	# https://www.nerdfonts.com/font-downloads
-	# https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.1.0
-	github-download \
-		--slug='ryanoasis/nerd-fonts' \
-		--release='latest' \
-		--asset-filter='.' \
-		--unzip-filter='*.{otf,ttf}' \
-		--directory="$fonts"
-}
-function get_fonts {
-	echo-segment --h1='Install Fonts'
-
-	eval-helper --no-wrap --quiet \
-		--pending="$(echo-style --bold="Installing Monoid...")" \
-		--success="$(echo-style --success="Installed Monoid.")" \
-		--failure="$(echo-style --error="Failed to install Monoid.")" \
-		-- get_monoid
-
-	eval-helper --no-wrap --quiet \
-		--pending="$(echo-style --bold="Installing Source Code Pro...")" \
-		--success="$(echo-style --success="Installed Source Code Pro.")" \
-		--failure="$(echo-style --error="Failed to install Source Code Pro.")" \
-		-- get_scp
-
-	eval-helper --no-wrap --quiet \
-		--pending="$(echo-style --bold="Installing Monaco...")" \
-		--success="$(echo-style --success="Installed Monaco.")" \
-		--failure="$(echo-style --error="Failed to install Monaco.")" \
-		-- get_monaco
-
-	# this one has multiple, so we want to see details for each one
-	eval-helper --no-wrap --no-quiet \
-		--pending="$(echo-style --bold="Installing Nerd Fonts...")" \
-		--success="$(echo-style --success="Installed Nerd Fonts.")" \
-		--failure="$(echo-style --error="Failed to install Nerd Fonts.")" \
-		-- get_nerd
-
-	eval-helper --no-wrap --quiet \
-		--pending="$(echo-style --bold="Refreshing font cache...")" \
-		--success="$(echo-style --success="Refreshed font cache.")" \
-		--failure="$(echo-style --error="Failed to refresh font cache.")" \
-		-- fc-cache -f -v
-
-	echo-segment --g1='Install Fonts'
-}
-
-# act
-get_fonts
diff --git a/commands/setup-linux-raspi b/commands/setup-linux-raspi
--- a/commands/setup-linux-raspi
+++ b/commands/setup-linux-raspi
@@ -1,45 +1,52 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# =====================================
-# Checks
+function setup-linux-raspi() (
+	# =====================================
+	# Checks
 
-# check that an accident has not occured
-if ! is-raspi; then
-	echo-style --notice="[$0] is only intended to be run on Raspberry Pi systems, skipping." >/dev/stderr
-	exit 0
+	# check that an accident has not occured
+	if ! is-raspi; then
+		echo-style --notice="[$0] is only intended to be run on Raspberry Pi systems, skipping." >/dev/stderr
+		return
+	fi
+
+	# =====================================
+	# Action
+
+	# log
+	echo-segment --h1='Raspberry Pi Essentials'
+
+	# ensure raspi firmware is up to date
+	# otherwise newer operating system releases can cause issues
+
+	# install necessary packages
+	if is-apt; then
+		setup-util NAME='Raspberry Pi Firmware' APT='rpi-eeprom'
+		setup-util NAME='Raspberry Pi Configurator' APT='raspi-config'
+
+		# https://bugs.launchpad.net/ubuntu/+source/linux-raspi/+bug/1946368/comments/48
+		setup-util NAME='Raspberry Pi Kernel' APT='linux-raspi'
+
+		# Various kernel modules have been moved from the linux-modules-raspi package in order to reduce the initramfs size. This results in several applications (most notably Docker, bug 1947601 1) failing due to missing kernel modules. To work around this: sudo apt install linux-modules-extra-rapsi
+		# https://discourse.ubuntu.com/t/impish-indri-release-notes/21951
+		# ^ the docs are wrong `linux-modules-raspi` doesn't exist, only `linux-modules-extra-raspi` exists
+		setup-util NAME='Ubuntu 21.10 Raspberry Pi Modules' APT='linux-modules-extra-raspi' || :
+	fi
+
+	# ensure autoupdates on restart
+	sudo systemctl unmask rpi-eeprom-update
+
+	# prompt an update on next restart
+	if sudo rpi-eeprom-update -a | grep reboot; then
+		echo 'An eeprom update is pending for your Raspberry Pi, to continue further you must reboot your machine.'
+		return 1
+	fi
+
+	echo-segment --g1='Raspberry Pi Essentials'
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	setup-linux-raspi "$@"
 fi
-
-# =====================================
-# Action
-
-# log
-echo-segment --h1='Raspberry Pi Essentials'
-
-# ensure raspi firmware is up to date
-# otherwise newer operating system releases can cause issues
-
-# install necessary packages
-if is-apt; then
-	setup-util NAME='Raspberry Pi Firmware' APT='rpi-eeprom'
-	setup-util NAME='Raspberry Pi Configurator' APT='raspi-config'
-
-	# https://bugs.launchpad.net/ubuntu/+source/linux-raspi/+bug/1946368/comments/48
-	setup-util NAME='Raspberry Pi Kernel' APT='linux-raspi'
-
-	# Various kernel modules have been moved from the linux-modules-raspi package in order to reduce the initramfs size. This results in several applications (most notably Docker, bug 1947601 1) failing due to missing kernel modules. To work around this: sudo apt install linux-modules-extra-rapsi
-	# https://discourse.ubuntu.com/t/impish-indri-release-notes/21951
-	# ^ the docs are wrong `linux-modules-raspi` doesn't exist, only `linux-modules-extra-raspi` exists
-	setup-util NAME='Ubuntu 21.10 Raspberry Pi Modules' APT='linux-modules-extra-raspi' || :
-fi
-
-# ensure autoupdates on restart
-sudo systemctl unmask rpi-eeprom-update
-
-# prompt an update on next restart
-if sudo rpi-eeprom-update -a | grep reboot; then
-	echo 'An eeprom update is pending for your Raspberry Pi, to continue further you must reboot your machine.'
-	exit 1
-fi
-
-echo-segment --g1='Raspberry Pi Essentials'
diff --git a/commands/setup-linux-recovery b/commands/setup-linux-recovery
--- a/commands/setup-linux-recovery
+++ b/commands/setup-linux-recovery
@@ -4,29 +4,36 @@ source "$DOROTHY/sources/strict.bash"
 # https://www.kernel.org/doc/html/latest/admin-guide/sysrq.html
 # https://forum.manjaro.org/t/howto-reboot-turn-off-your-frozen-computer-reisub-reisuo/3855?u=balupton
 
-# =====================================
-# Checks
+function setup-linux-recovery() (
+	# =====================================
+	# Checks
 
-# check that an accident has not occured
-if ! is-linux; then
-	echo-style --notice="[$0] is only intended to be run on Linux systems, skipping." >/dev/stderr
-	exit 0
+	# check that an accident has not occured
+	if ! is-linux; then
+		echo-style --notice="[$0] is only intended to be run on Linux systems, skipping." >/dev/stderr
+		return
+	fi
+
+	# =====================================
+	# Action
+
+	echo-segment --h1='Update GRUB with Recovery Hotkeys'
+
+	sudo-inherit -- config-helper \
+		--file='/etc/sysctl.d/99-sysctl.conf' -- \
+		--field='kernel.sysrq' --no-quote --value=1
+
+	if grub-helper; then
+		echo "💁🏼‍♀️ If your Linux machine ever locks up, you can follow the instructions here to safely shutdown/reboot: 💁🏼‍♀️"
+		echo 'https://forum.manjaro.org/t/3855?u=balupton'
+	else
+		stderr echo-style --error='Failed to upgrade grub with the recovery options. Please send a PR to Dorothy to add support. Continuing...'
+	fi
+
+	echo-segment --g1='Update GRUB with Recovery Hotkeys'
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	setup-linux-recovery "$@"
 fi
-
-# =====================================
-# Action
-
-echo-segment --h1='Update GRUB with Recovery Hotkeys'
-
-sudo-inherit -- config-helper \
-	--file='/etc/sysctl.d/99-sysctl.conf' -- \
-	--field='kernel.sysrq' --no-quote --value=1
-
-if grub-helper; then
-	echo "💁🏼‍♀️ If your Linux machine ever locks up, you can follow the instructions here to safely shutdown/reboot: 💁🏼‍♀️"
-	echo 'https://forum.manjaro.org/t/3855?u=balupton'
-else
-	stderr echo-style --error='Failed to upgrade grub with the recovery options. Please send a PR to Dorothy to add support. Continuing...'
-fi
-
-echo-segment --g1='Update GRUB with Recovery Hotkeys'
diff --git a/commands/setup-node b/commands/setup-node
--- a/commands/setup-node
+++ b/commands/setup-node
@@ -6,256 +6,263 @@ requires_array_support 'mapfile' 'empty'
 # trunk-ignore(shellcheck/SC1090)
 source "$(which eval-helper)"
 
-# =====================================
-# Start
+function setup-node() (
+	# =====================================
+	# Start
 
-echo-segment --h1="Setup Node.js"
+	echo-segment --h1="Setup Node.js"
 
-# =====================================
-# Configuration
+	# =====================================
+	# Configuration
 
-source "$DOROTHY/sources/config.bash"
+	source "$DOROTHY/sources/config.bash"
 
-# environment.bash provides:
-# NVM_DIR
-# but in case it failed to:
-if test -z "${NVM_DIR-}"; then
-	export NVM_DIR="$HOME/.nvm"
-fi
-
-# setup.bash provides:
-NPM_INSTALL=()
-NODE_INSTALL=() # deprecated, use NPM_INSTALL
-load_dorothy_config 'setup.bash'
-
-# adjustments
-mapfile -t NPM_INSTALL < <(prepare_packages 'NPM_INSTALL' -- "${NPM_INSTALL[@]}" "${NODE_INSTALL[@]}")
-
-# =====================================
-# Arguments
-
-# help
-function help() {
-	cat <<-EOF >/dev/stderr
-		USAGE:
-		setup-node [--flags]
-
-		FLAGS:
-		--configure            Configuration guide.
-	EOF
-	if test "$#" -ne 0; then
-		echo-error "$@"
+	# environment.bash provides:
+	# NVM_DIR
+	# but in case it failed to:
+	if test -z "${NVM_DIR-}"; then
+		export NVM_DIR="$HOME/.nvm"
 	fi
-	return 22 # Invalid argument
-}
 
-# process
-reconfigure='no'
-while test "$#" -ne 0; do
-	item="$1"
-	shift
-	case "$item" in
-	'--help' | '-h') help ;;
-	'--no-configure'* | '--configure'*)
-		reconfigure="$(get-flag-value configure --missing="$reconfigure" -- "$item" | echo-affirmative)"
-		;;
-	'--'*) help "An unrecognised flag was provided: $item" ;;
-	*) help "An unrecognised argument was provided: $item" ;;
-	esac
-done
+	# setup.bash provides:
+	local NPM_INSTALL=()
+	local NODE_INSTALL=() # deprecated, use NPM_INSTALL
+	load_dorothy_config 'setup.bash'
 
-# =====================================
-# Install via System
+	# adjustments
+	mapfile -t NPM_INSTALL < <(prepare_packages 'NPM_INSTALL' -- "${NPM_INSTALL[@]}" "${NODE_INSTALL[@]}")
 
-# setup system node for global installs and vscode on mac
-function install_homebrew_node() {
-	# `reinstall ... || :` as well as `install ... || upgrade ... || :` are no longer necessary,
-	# install does upgrade if it is already installed:
-	# https://github.com/Homebrew/brew/pull/11525
-	brew install node
-	npm cache clean --force
-}
-if is-brew; then
-	echo-segment --h2='Install Node.js via Homebrew'
-	eval-helper --quiet --no-wrap -- install_homebrew_node
-	echo "Installed: $(node --version)"
-	echo-segment --g2='Install Node.js via Homebrew'
-fi
+	# =====================================
+	# Arguments
 
-# =====================================
-# Clean NVM
+	# help
+	function help() {
+		cat <<-EOF >/dev/stderr
+			USAGE:
+			setup-node [--flags]
 
-# clean NVM unless configured otherwise
-# the intent of this is to purge unused global Node.js versions and packages
-# we use a configuration variable to change this, as interuppting the flow and asking the user creates too much confusion
-# as such a question is only necessary to experienced users
-function get_nvm_versions() {
-	source "$DOROTHY/sources/ripgrep.bash"
-	source "$DOROTHY/sources/nvm.sh"
-	nvm ls --no-colors --no-alias | rg -o 'v([^\s]+)' --replace '$1' || :
-}
-function clean_nvm() (
-	# run this function as a subshell, so nvm is only loaded for this
-	# can't just do `trap 'nvm unload' RETURN` as `nvm unload` unsets NVM_DIR
-	source "$DOROTHY/sources/nvm.sh"
-	# swap to system
-	nvm use system || :
-	# fetch versions
-	mapfile -t versions < <(get_nvm_versions)
-	if test "${#versions[@]}" -eq 0; then
-		# already clean
-		return 0
-	fi
-	# clean versions
-	for version in "${versions[@]}"; do
-		nvm uninstall "$version" | sed 's/Uninstalled node /Uninstalled: /'
+			FLAGS:
+			--configure            Configuration guide.
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# process
+	local item reconfigure='no'
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--no-configure'* | '--configure'*)
+			reconfigure="$(get-flag-value configure --missing="$reconfigure" -- "$item" | echo-affirmative)"
+			;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) help "An unrecognised argument was provided: $item" ;;
+		esac
 	done
-	# confirm clean was successful
-	mapfile -t versions < <(get_nvm_versions)
-	test "${#versions[@]}" -eq 0
-)
-function wipe_nvm() {
-	rm -Rf "$NVM_DIR"
-}
-function clean_otherwise_wipe_nvm() {
-	# clean only what is necessary
-	echo-segment --h3='Clean Node.js versions and packages'
-	if clean_nvm; then
-		echo-segment --g3='Clean Node.js versions and packages'
-	else
-		# nvm buggered, clean it all
-		echo-segment --e3='Clean Node.js versions and packages'
-		echo-segment --h3='Clean Node.js Version Manager (NVM) instead'
-		wipe_nvm
-		echo-segment --g3='Clean Node.js Version Manager (NVM) instead'
+
+	# =====================================
+	# Install via System
+
+	# setup system node for global installs and vscode on mac
+	function install_homebrew_node() {
+		# `reinstall ... || :` as well as `install ... || upgrade ... || :` are no longer necessary,
+		# install does upgrade if it is already installed:
+		# https://github.com/Homebrew/brew/pull/11525
+		brew install node
+		npm cache clean --force
+	}
+	if is-brew; then
+		echo-segment --h2='Install Node.js via Homebrew'
+		eval-helper --quiet --no-wrap -- install_homebrew_node
+		echo "Installed: $(node --version)"
+		echo-segment --g2='Install Node.js via Homebrew'
 	fi
-}
-if test -d "$NVM_DIR"; then
-	clean_otherwise_wipe_nvm
-fi
 
-# =====================================
-# Install via NVM
+	# =====================================
+	# Clean NVM
 
-# install nvm
-function install_nvm() {
+	# clean NVM unless configured otherwise
+	# the intent of this is to purge unused global Node.js versions and packages
+	# we use a configuration variable to change this, as interuppting the flow and asking the user creates too much confusion
+	# as such a question is only necessary to experienced users
+	function get_nvm_versions() {
+		source "$DOROTHY/sources/ripgrep.bash"
+		source "$DOROTHY/sources/nvm.sh"
+		nvm ls --no-colors --no-alias | rg -o 'v([^\s]+)' --replace '$1' || :
+	}
+	function clean_nvm() (
+		# run this function as a subshell, so nvm is only loaded for this
+		# can't just do `trap 'nvm unload' RETURN` as `nvm unload` unsets NVM_DIR
+		source "$DOROTHY/sources/nvm.sh"
+		# swap to system
+		nvm use system || :
+		# fetch versions
+		mapfile -t versions < <(get_nvm_versions)
+		if test "${#versions[@]}" -eq 0; then
+			# already clean
+			return
+		fi
+		# clean versions
+		for version in "${versions[@]}"; do
+			nvm uninstall "$version" | sed 's/Uninstalled node /Uninstalled: /'
+		done
+		# confirm clean was successful
+		mapfile -t versions < <(get_nvm_versions)
+		test "${#versions[@]}" -eq 0
+	)
+	function wipe_nvm() {
+		rm -Rf "$NVM_DIR"
+	}
+	function clean_otherwise_wipe_nvm() {
+		# clean only what is necessary
+		echo-segment --h3='Clean Node.js versions and packages'
+		if clean_nvm; then
+			echo-segment --g3='Clean Node.js versions and packages'
+		else
+			# nvm buggered, clean it all
+			echo-segment --e3='Clean Node.js versions and packages'
+			echo-segment --h3='Clean Node.js Version Manager (NVM) instead'
+			wipe_nvm
+			echo-segment --g3='Clean Node.js Version Manager (NVM) instead'
+		fi
+	}
 	if test -d "$NVM_DIR"; then
-		cd "$NVM_DIR"
-	else
-		mkdir -p "$NVM_DIR"
-		cd "$NVM_DIR"
-		git init
-		git remote add origin 'https://github.com/nvm-sh/nvm.git'
+		clean_otherwise_wipe_nvm
 	fi
-	# ensure git remote is usable
-	git-helper protocol-update origin https
-	# fetch tags
-	git fetch --tags origin
-	# checkout latest stable tag
-	# shellcheck disable=SC2006,SC2046
-	git checkout "$(git describe --abbrev=0 --tags --match "v[0-9]*" "$(git rev-list --tags --max-count=1)")"
-}
-echo-segment --h2='Install Node.js Version Manager (NVM)'
-echo-style --dim "NVM_DIR=$NVM_DIR"
-eval-helper --quiet --no-wrap -- install_nvm
-echo-segment --g2='Install Node.js Version Manager (NVM)'
 
-# install nvm node
-function install_nvm_node() {
+	# =====================================
+	# Install via NVM
+
+	# install nvm
+	function install_nvm() {
+		if test -d "$NVM_DIR"; then
+			cd "$NVM_DIR"
+		else
+			mkdir -p "$NVM_DIR"
+			cd "$NVM_DIR"
+			git init
+			git remote add origin 'https://github.com/nvm-sh/nvm.git'
+		fi
+		# ensure git remote is usable
+		git-helper protocol-update origin https
+		# fetch tags
+		git fetch --tags origin
+		# checkout latest stable tag
+		# shellcheck disable=SC2006,SC2046
+		git checkout "$(git describe --abbrev=0 --tags --match "v[0-9]*" "$(git rev-list --tags --max-count=1)")"
+	}
+	echo-segment --h2='Install Node.js Version Manager (NVM)'
+	echo-style --dim "NVM_DIR=$NVM_DIR"
+	eval-helper --quiet --no-wrap -- install_nvm
+	echo-segment --g2='Install Node.js Version Manager (NVM)'
+
+	# install nvm node
+	function install_nvm_node() {
+		source "$DOROTHY/sources/nvm.sh"
+
+		# install
+		nvm install node       # latest active
+		nvm-2596 install --lts # latest LTS
+
+		# set default node version
+		if is-brew; then
+			nvm alias default system
+		else
+			# use latest lts
+			nvm alias default stable
+			# use current lts: "$(nvm version-remote --lts)"
+		fi
+
+		# default
+		nvm use default
+	}
+	echo-segment --h2='Install Node.js via NVM'
+	echo-style --dim='Installs active and LTS versions.'
+	eval-helper --quiet --no-wrap -- install_nvm_node
+	mapfile -t versions < <(get_nvm_versions)
+	for version in "${versions[@]}"; do
+		echo "Installed: v$version"
+	done
+	echo-segment --g2='Install Node.js via NVM'
+
+	# =====================================
+	# npm
+
 	source "$DOROTHY/sources/nvm.sh"
 
-	# install
-	nvm install node       # latest active
-	nvm-2596 install --lts # latest LTS
+	# -------------------------------------
+	# Upgrade
 
-	# set default node version
-	if is-brew; then
-		nvm alias default system
-	else
-		# use latest lts
-		nvm alias default stable
-		# use current lts: "$(nvm version-remote --lts)"
+	echo-segment --h2='Upgrade npm'
+	echo-style --dim="Before: $(npm --version)"
+	eval-helper --quiet -- npm install -g npm --force
+	echo "After:  $(npm --version)"
+	echo-segment --g2='Upgrade npm'
+
+	# -------------------------------------
+	# Reconfiguration
+
+	# check
+	if
+		is-empty-value "$(npm config get init.author.name)" ||
+			is-empty-value "$(npm config get init.author.email)" ||
+			is-empty-value "$(npm config get init.author.url)" ||
+			is-empty-value "$(npm config get init.license)"
+	then
+		reconfigure='yes'
 	fi
 
-	# default
-	nvm use default
-}
-echo-segment --h2='Install Node.js via NVM'
-echo-style --dim='Installs active and LTS versions.'
-eval-helper --quiet --no-wrap -- install_nvm_node
-mapfile -t versions < <(get_nvm_versions)
-for version in "${versions[@]}"; do
-	echo "Installed: v$version"
-done
-echo-segment --g2='Install Node.js via NVM'
-
-# =====================================
-# npm
-
-source "$DOROTHY/sources/nvm.sh"
-
-# -------------------------------------
-# Upgrade
-
-echo-segment --h2='Upgrade npm'
-echo-style --dim="Before: $(npm --version)"
-eval-helper --quiet -- npm install -g npm --force
-echo "After:  $(npm --version)"
-echo-segment --g2='Upgrade npm'
-
-# -------------------------------------
-# Reconfiguration
-
-# check
-if
-	is-empty-value "$(npm config get init.author.name)" ||
-		is-empty-value "$(npm config get init.author.email)" ||
-		is-empty-value "$(npm config get init.author.url)" ||
-		is-empty-value "$(npm config get init.license)"
-then
-	reconfigure='yes'
-fi
-
-# reconfigure
-if test "$reconfigure" = 'yes'; then
-	echo-segment --h2='Configure npm'
-	npm config set init.author.name "$(
-		ask --required --confirm \
-			--question="What is the profile name that you want to configure npm with?" \
-			--default="$(get-profile name -- npm ... || :)"
-	)"
-	npm config set init.author.email "$(
-		ask --required --confirm \
-			--question="What is the profile email that you want to configure npm with?" \
-			--default="$(get-profile email -- npm ... || :)"
-	)"
-	npm config set init.author.url "$(
-		ask --required --confirm \
-			--question="What is the profile homepage that you want to configure npm with?" \
-			--default="$(get-profile url -- npm ... || :)"
-	)"
-	npm config set init.license "$(
-		ask --required --confirm \
-			--question="What license do you want to configure npm to default to?" \
-			--default="$(npm config get init.license)"
-	)"
-	echo-segment --g2='Configure npm'
-fi
-
-# -------------------------------------
-# Packages
-
-# https://github.com/yarnpkg/yarn/issues/2993
-function npm_install_bulk() {
-	echo-segment --h2="Install $# npm packages"
-	if test "$#" -ne 0; then
-		setup-util NAME="npm:$*" NPM="$*"
+	# reconfigure
+	if test "$reconfigure" = 'yes'; then
+		echo-segment --h2='Configure npm'
+		npm config set init.author.name "$(
+			ask --required --confirm \
+				--question="What is the profile name that you want to configure npm with?" \
+				--default="$(get-profile name -- npm ... || :)"
+		)"
+		npm config set init.author.email "$(
+			ask --required --confirm \
+				--question="What is the profile email that you want to configure npm with?" \
+				--default="$(get-profile email -- npm ... || :)"
+		)"
+		npm config set init.author.url "$(
+			ask --required --confirm \
+				--question="What is the profile homepage that you want to configure npm with?" \
+				--default="$(get-profile url -- npm ... || :)"
+		)"
+		npm config set init.license "$(
+			ask --required --confirm \
+				--question="What license do you want to configure npm to default to?" \
+				--default="$(npm config get init.license)"
+		)"
+		echo-segment --g2='Configure npm'
 	fi
-	echo-segment --g2="Install $# npm packages"
-}
-npm_install_bulk "${NPM_INSTALL[@]}"
 
-# =====================================
-# Finish
+	# -------------------------------------
+	# Packages
 
-echo-segment --g1='Setup Node.js'
+	# https://github.com/yarnpkg/yarn/issues/2993
+	function npm_install_bulk() {
+		echo-segment --h2="Install $# npm packages"
+		if test "$#" -ne 0; then
+			setup-util NAME="npm:$*" NPM="$*"
+		fi
+		echo-segment --g2="Install $# npm packages"
+	}
+	npm_install_bulk "${NPM_INSTALL[@]}"
+
+	# =====================================
+	# Finish
+
+	echo-segment --g1='Setup Node.js'
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	setup-node "$@"
+fi
diff --git a/commands/setup-ruby b/commands/setup-ruby
--- a/commands/setup-ruby
+++ b/commands/setup-ruby
@@ -3,165 +3,173 @@ source "$DOROTHY/sources/strict.bash"
 source "$DOROTHY/sources/arrays.bash"
 requires_array_support 'mapfile' 'empty'
 
-# =====================================
-# Start
+function setup-ruby() (
+	# =====================================
+	# Start
 
-echo-segment --h1="Setup Ruby"
+	echo-segment --h1="Setup Ruby"
 
-# =====================================
-# Configuration
+	# =====================================
+	# Configuration
 
-source "$DOROTHY/sources/config.bash"
+	source "$DOROTHY/sources/config.bash"
 
-# environment provides:
-# GEM_HOME
+	# environment provides:
+	# GEM_HOME
 
-# environment.bash provides:
-# HOMEBREW_RUBY_VERSION
+	# environment.bash provides:
+	# HOMEBREW_RUBY_VERSION
 
-# setup.bash provides:
-GEM_INSTALL=()
-RUBY_INSTALL=() # deprecated, use GEM_INSTALL
-load_dorothy_config 'setup.bash'
+	# setup.bash provides:
+	local GEM_INSTALL=()
+	local RUBY_INSTALL=() # deprecated, use GEM_INSTALL
+	load_dorothy_config 'setup.bash'
 
-# adjustments
-mapfile -t GEM_INSTALL < <(prepare_packages 'GEM_INSTALL' -- "${GEM_INSTALL[@]}" "${RUBY_INSTALL[@]}")
+	# adjustments
+	mapfile -t GEM_INSTALL < <(prepare_packages 'GEM_INSTALL' -- "${GEM_INSTALL[@]}" "${RUBY_INSTALL[@]}")
 
-# =====================================
-# Install
+	# =====================================
+	# Install
 
-# install a specific ruby version via homebrew if supported
-brew_ruby='ruby'
-if test -n "${HOMEBREW_RUBY_VERSION-}" -a "${HOMEBREW_RUBY_VERSION-}" != 'default'; then
-	brew_ruby="ruby@${HOMEBREW_RUBY_VERSION}"
-fi
-
-# perform the installation
-setup-util CLI=ruby \
-	APK=ruby \
-	APT='ruby-full' \
-	BREW="$brew_ruby" \
-	PACMAN=ruby \
-	YUM=ruby-devel
-
-# =====================================
-# Selection
-
-# Use only a single ruby version
-if test -n "${HOMEBREW_PREFIX-}"; then
-	if test -z "${HOMEBREW_RUBY_VERSION-}" -o ! -d "$HOMEBREW_PREFIX/opt/ruby@${HOMEBREW_RUBY_VERSION-}"; then
-		# discover
-		__version_options=()
-		mapfile -t rubyBinDirectories < <(expand-path "$HOMEBREW_PREFIX/opt/ruby*/bin")
-		for __bin_directory in "${rubyBinDirectories[@]}"; do
-			__executable="$__bin_directory/ruby"
-			__directory="$(basename "$(fs-parent "$__bin_directory")")"
-			__directory_version="${__directory#*@}"
-			__full_version="$("$__executable" --version)"
-			if test "$__directory_version" = "$__directory"; then
-				__directory_version='default'
-			fi
-			__version_options+=(
-				"$__directory_version"
-				"$(
-					echo-style \
-						--bold="$__directory_version" \
-						$'\n  ' --dim="$__full_version" \
-						$'\n  ' --dim="$__executable"
-				)"
-			)
-		done
-
-		# select
-		HOMEBREW_RUBY_VERSION="$(
-			choose-option \
-				--question='There are multiple homebrew ruby versions installed, which version do you wish to prefer?' \
-				--label -- "${__version_options[@]}"
-		)"
-
-		# apply
-		config-helper \
-			--file="$DOROTHY/user/config/environment.bash" -- \
-			--field='HOMEBREW_RUBY_VERSION' --value="$HOMEBREW_RUBY_VERSION"
+	# install a specific ruby version via homebrew if supported
+	local brew_ruby='ruby'
+	if test -n "${HOMEBREW_RUBY_VERSION-}" -a "${HOMEBREW_RUBY_VERSION-}" != 'default'; then
+		brew_ruby="ruby@${HOMEBREW_RUBY_VERSION}"
 	fi
 
-	echo-style --dim="Homebrew Ruby Version: $HOMEBREW_RUBY_VERSION"
-fi
+	# perform the installation
+	setup-util CLI=ruby \
+		APK=ruby \
+		APT='ruby-full' \
+		BREW="$brew_ruby" \
+		PACMAN=ruby \
+		YUM=ruby-devel
 
-# =====================================
-# Caches
+	# =====================================
+	# Selection
 
-# Clear caches that can conflict with paths and old installs
-# Use only the intended one, which is GEM_HOME
+	# Use only a single ruby version
+	local __version_options __bin_directory __executable __directory __directory_version __full_version __version_options
+	if test -n "${HOMEBREW_PREFIX-}"; then
+		if test -z "${HOMEBREW_RUBY_VERSION-}" -o ! -d "$HOMEBREW_PREFIX/opt/ruby@${HOMEBREW_RUBY_VERSION-}"; then
+			# discover
+			__version_options=()
+			mapfile -t rubyBinDirectories < <(expand-path "$HOMEBREW_PREFIX/opt/ruby*/bin")
+			for __bin_directory in "${rubyBinDirectories[@]}"; do
+				__executable="$__bin_directory/ruby"
+				__directory="$(basename "$(fs-parent "$__bin_directory")")"
+				__directory_version="${__directory#*@}"
+				__full_version="$("$__executable" --version)"
+				if test "$__directory_version" = "$__directory"; then
+					__directory_version='default'
+				fi
+				__version_options+=(
+					"$__directory_version"
+					"$(
+						echo-style \
+							--bold="$__directory_version" \
+							$'\n  ' --dim="$__full_version" \
+							$'\n  ' --dim="$__executable"
+					)"
+				)
+			done
 
-echo-segment --h2="Pruning cache"
-if test -d "$HOME/.gem"; then
-	echo-style --dim="Pruning:       $HOME/.gem"
-	rm -Rf "$HOME/.gem"
-fi
-if test -d "$HOME/.ruby"; then
-	echo-style --dim="Pruning:       $HOME/.ruby"
-	rm -Rf "$HOME/.ruby"
-fi
-if test -n "${GEM_HOME-}"; then
-	if test -d "$GEM_HOME"; then
-		echo-style --dim="Pruning:       $GEM_HOME"
-		rm -Rf "$GEM_HOME"
-	fi
-	mkdir -p "$GEM_HOME"
-fi
-echo-segment --g2="Pruning cache"
+			# select
+			HOMEBREW_RUBY_VERSION="$(
+				choose-option \
+					--question='There are multiple homebrew ruby versions installed, which version do you wish to prefer?' \
+					--label -- "${__version_options[@]}"
+			)"
 
-# =====================================
-# Reload
-
-# reload
-echo-style --h2="Reload paths to help changes be detected..."
-source "$DOROTHY/sources/environment.sh"
-
-# check
-if ! command-exists gem; then
-	echo-style --e2='Unable to find [gem] executable, so cannot proceed... ❌' >/dev/stderr
-	exit 1
-fi
-echo-style \
-	--dim="Ruby Path:      $(which ruby)" $'\n' \
-	--dim="Ruby Version:   $(ruby --version)" $'\n' \
-	--dim="Gem Path:       $(which gem)" $'\n' \
-	--dim="Gem Version:    $(gem --version)"
-
-# =====================================
-# Update
-
-# As we wipe gems each time, this is no longer needed
-# also, it causes the following error on apt systems
-# ERROR:  Your RubyGems was installed trough APT, and upgrading it through RubyGems
-# 	itself is unsupported. If you really need the latest version of RubyGems (tip:
-# 	you usually don't), then you need to install RubyGems (and Ruby) manually,
-# 	maybe using tools like ruby-install, rvm, etc.
-# echo -e '\nUpdating ruby gems...'
-# gem update --system
-
-# =====================================
-# Packages
-
-# install
-function gem_install_each {
-	local name version
-	echo-segment --h2="Installing $# ruby gems"
-	for package in "$@"; do
-		name="${package% *}"
-		version="${package#* }" # will be the same as name, if no version was provided
-		if test "$version" = "$name"; then
-			version=''
+			# apply
+			config-helper \
+				--file="$DOROTHY/user/config/environment.bash" -- \
+				--field='HOMEBREW_RUBY_VERSION' --value="$HOMEBREW_RUBY_VERSION"
 		fi
-		setup-util NAME="gem:$name" GEM="$name" GEM_VERSION="$version"
-	done
-	echo-segment --g2="Installed $# ruby gems"
-}
-gem_install_each "${GEM_INSTALL[@]}"
 
-# =====================================
-# Finish
+		echo-style --dim="Homebrew Ruby Version: $HOMEBREW_RUBY_VERSION"
+	fi
 
-echo-segment --g1="Setup Ruby"
+	# =====================================
+	# Caches
+
+	# Clear caches that can conflict with paths and old installs
+	# Use only the intended one, which is GEM_HOME
+
+	echo-segment --h2="Pruning cache"
+	if test -d "$HOME/.gem"; then
+		echo-style --dim="Pruning:       $HOME/.gem"
+		rm -Rf "$HOME/.gem"
+	fi
+	if test -d "$HOME/.ruby"; then
+		echo-style --dim="Pruning:       $HOME/.ruby"
+		rm -Rf "$HOME/.ruby"
+	fi
+	if test -n "${GEM_HOME-}"; then
+		if test -d "$GEM_HOME"; then
+			echo-style --dim="Pruning:       $GEM_HOME"
+			rm -Rf "$GEM_HOME"
+		fi
+		mkdir -p "$GEM_HOME"
+	fi
+	echo-segment --g2="Pruning cache"
+
+	# =====================================
+	# Reload
+
+	# reload
+	echo-style --h2="Reload paths to help changes be detected..."
+	source "$DOROTHY/sources/environment.sh"
+
+	# check
+	if ! command-exists gem; then
+		echo-style --e2='Unable to find [gem] executable, so cannot proceed... ❌' >/dev/stderr
+		return 1
+	fi
+	echo-style \
+		--dim="Ruby Path:      $(which ruby)" $'\n' \
+		--dim="Ruby Version:   $(ruby --version)" $'\n' \
+		--dim="Gem Path:       $(which gem)" $'\n' \
+		--dim="Gem Version:    $(gem --version)"
+
+	# =====================================
+	# Update
+
+	# As we wipe gems each time, this is no longer needed
+	# also, it causes the following error on apt systems
+	# ERROR:  Your RubyGems was installed trough APT, and upgrading it through RubyGems
+	# 	itself is unsupported. If you really need the latest version of RubyGems (tip:
+	# 	you usually don't), then you need to install RubyGems (and Ruby) manually,
+	# 	maybe using tools like ruby-install, rvm, etc.
+	# echo -e '\nUpdating ruby gems...'
+	# gem update --system
+
+	# =====================================
+	# Packages
+
+	# install
+	function gem_install_each {
+		local name version
+		echo-segment --h2="Installing $# ruby gems"
+		for package in "$@"; do
+			name="${package% *}"
+			version="${package#* }" # will be the same as name, if no version was provided
+			if test "$version" = "$name"; then
+				version=''
+			fi
+			setup-util NAME="gem:$name" GEM="$name" GEM_VERSION="$version"
+		done
+		echo-segment --g2="Installed $# ruby gems"
+	}
+	gem_install_each "${GEM_INSTALL[@]}"
+
+	# =====================================
+	# Finish
+
+	echo-segment --g1="Setup Ruby"
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	setup-ruby "$@"
+fi
diff --git a/commands/setup-util-flatpak b/commands/setup-util-flatpak
--- a/commands/setup-util-flatpak
+++ b/commands/setup-util-flatpak
@@ -4,33 +4,40 @@ source "$DOROTHY/sources/strict.bash"
 # https://www.flatpak.org/setup/Ubuntu/
 # https://wiki.manjaro.org/index.php/Flatpak
 
-# =====================================
-# Checks
+function setup-util-flatpak() (
+	# =====================================
+	# Checks
 
-# check that an accident has not occured
-if ! is-linux; then
-	echo-style --notice="[$0] is only intended to be run on Linux systems, skipping." >/dev/stderr
-	exit 0
+	# check that an accident has not occured
+	if ! is-linux; then
+		echo-style --notice="[$0] is only intended to be run on Linux systems, skipping." >/dev/stderr
+		return
+	fi
+
+	# check applicability
+	if test "${ACTION-}" = 'update' && command-missing flatpak; then
+		echo-style --notice="[flatpak] is missing, and we are update only, skipping." >/dev/stderr
+		return
+	fi
+
+	# =====================================
+	# Action
+
+	setup-util "$@" NAME='Flatpak' CLI='flatpak' \
+		APT='flatpak' \
+		PAMAC='flatpak'
+
+	flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
+
+	if command-exists gnome-software; then
+		setup-util "$@" --optional NAME='Flatpak via Gnome Software' \
+			APT='gnome-software-plugin-flatpak'
+	fi
+
+	flatpak update -y
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	setup-util-flatpak "$@"
 fi
-
-# check applicability
-if test "${ACTION-}" = 'update' && command-missing flatpak; then
-	echo-style --notice="[flatpak] is missing, and we are update only, skipping." >/dev/stderr
-	exit 0
-fi
-
-# =====================================
-# Action
-
-setup-util "$@" NAME='Flatpak' CLI='flatpak' \
-	APT='flatpak' \
-	PAMAC='flatpak'
-
-flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
-
-if command-exists gnome-software; then
-	setup-util "$@" --optional NAME='Flatpak via Gnome Software' \
-		APT='gnome-software-plugin-flatpak'
-fi
-
-flatpak update -y
diff --git a/commands/setup-util-snap b/commands/setup-util-snap
--- a/commands/setup-util-snap
+++ b/commands/setup-util-snap
@@ -1,83 +1,90 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# =====================================
-# Checks
+function setup-util-snap() (
+	# =====================================
+	# Checks
 
-# check that an accident has not occured
-if ! is-linux; then
-	echo-style --notice="[$0] is only intended to be run on Linux systems, skipping." >/dev/stderr
-	exit 0
-fi
-
-# check applicability
-if test "${ACTION-}" = 'update' && command-missing snap; then
-	echo-style --notice="[snap] is missing, and we are [update] only, skipping." >/dev/stderr
-	exit 0
-fi
-
-# =====================================
-# Start
-
-echo-segment --h1='Setup Snap'
-
-# =====================================
-# Configuration
-
-source "$DOROTHY/sources/config.bash"
-
-# setup.bash provides:
-SNAP_INSTALL=()
-load_dorothy_config 'setup.bash'
-
-# adjustments
-mapfile -t SNAP_INSTALL < <(prepare_packages 'SNAP_INSTALL' -- "${SNAP_INSTALL[@]}")
-
-# =====================================
-# Action
-
-# https://wiki.manjaro.org/index.php/Snap
-# https://packages.ubuntu.com/bionic/gnome/gnome-software-plugin-snap
-
-setup-util "$@" NAME='snap' CLI='snap' \
-	DNF='snapd' \
-	PAMAC='snapd'
-
-if ! systemctl status snapd.socket --no-pager >/dev/null; then
-	sudo systemctl enable --now snapd.socket
-fi
-
-if test ! -d /snap; then
-	sudo ln -s /var/lib/snapd/snap /snap
-fi
-
-if command-exists gnome-software; then
-	# PAMAC='gnome-software-snap' \
-	# Error: target not found: gnome-software-snap
-	setup-util "$@" --optional NAME='Snap via Gnome Software' \
-		APT='gnome-software-plugin-snap'
-fi
-
-# snap update
-sudo snap refresh
-
-# =====================================
-# Packages
-
-function snap_install_bulk {
-	echo-segment --h2="Install $# snaps"
-	if test "$#" -ne 0; then
-		setup-util "$@" NAME="snap:$*" SNAP="$*"
+	# check that an accident has not occured
+	if ! is-linux; then
+		echo-style --notice="[$0] is only intended to be run on Linux systems, skipping." >/dev/stderr
+		return
 	fi
-	echo-segment --g2="Install $# snaps"
-}
 
-snap_install_bulk "${SNAP_INSTALL[@]}"
+	# check applicability
+	if test "${ACTION-}" = 'update' && command-missing snap; then
+		echo-style --notice="[snap] is missing, and we are [update] only, skipping." >/dev/stderr
+		return
+	fi
 
-# configure with
-# snap list --color=never | sed '1d' | cut -d' ' -f1 | grep --invert-match -E '^(core|snapd)'
+	# =====================================
+	# Start
 
-# =====================================
-# Finish
+	echo-segment --h1='Setup Snap'
 
-echo-segment --g1='Setup Snap'
+	# =====================================
+	# Configuration
+
+	source "$DOROTHY/sources/config.bash"
+
+	# setup.bash provides:
+	local SNAP_INSTALL=()
+	load_dorothy_config 'setup.bash'
+
+	# adjustments
+	mapfile -t SNAP_INSTALL < <(prepare_packages 'SNAP_INSTALL' -- "${SNAP_INSTALL[@]}")
+
+	# =====================================
+	# Action
+
+	# https://wiki.manjaro.org/index.php/Snap
+	# https://packages.ubuntu.com/bionic/gnome/gnome-software-plugin-snap
+
+	setup-util "$@" NAME='snap' CLI='snap' \
+		DNF='snapd' \
+		PAMAC='snapd'
+
+	if ! systemctl status snapd.socket --no-pager >/dev/null; then
+		sudo systemctl enable --now snapd.socket
+	fi
+
+	if test ! -d /snap; then
+		sudo ln -s /var/lib/snapd/snap /snap
+	fi
+
+	if command-exists gnome-software; then
+		# PAMAC='gnome-software-snap' \
+		# Error: target not found: gnome-software-snap
+		setup-util "$@" --optional NAME='Snap via Gnome Software' \
+			APT='gnome-software-plugin-snap'
+	fi
+
+	# snap update
+	sudo snap refresh
+
+	# =====================================
+	# Packages
+
+	function snap_install_bulk {
+		echo-segment --h2="Install $# snaps"
+		if test "$#" -ne 0; then
+			setup-util "$@" NAME="snap:$*" SNAP="$*"
+		fi
+		echo-segment --g2="Install $# snaps"
+	}
+
+	snap_install_bulk "${SNAP_INSTALL[@]}"
+
+	# configure with
+	# snap list --color=never | sed '1d' | cut -d' ' -f1 | grep --invert-match -E '^(core|snapd)'
+
+	# =====================================
+	# Finish
+
+	echo-segment --g1='Setup Snap'
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	setup-util-snap "$@"
+fi
