fixes for rust and revolving-door on CI
https://github.com/bevry/dorothy/runs/6016222115?check_suite_focus=true

diff --git a/commands/echo-revolving-door b/commands/echo-revolving-door
--- a/commands/echo-revolving-door
+++ b/commands/echo-revolving-door
@@ -10,20 +10,28 @@ source "$DOROTHY/sources/strict.bash"
 
 # cols is essential, as lines larger than the window will wrap and become two cusor lines
 # and we can't have that
-cols="$(tput cols)"
-queue=0
+cols="$(tput cols 2> /dev/null || :)"
 
-# timeout will cause read to emit a failure exit code, which causes the while loop to fail, which causes everything to fail
-while read -r -n "$cols" line || test -n "$line"; do
+# if we are not running in a TTY, [tput cols] will fail, so just dump stdin if that is the case
+# tput: No value for $TERM and no -T specified
+if test -z "$cols"; then
+	cat
+else
+	# we are in a TTY, so proceed with revolving door
+	queue=0
+
+	# timeout will cause read to emit a failure exit code, which causes the while loop to fail, which causes everything to fail
+	while read -r -n "$cols" line || test -n "$line"; do
+		while test "$queue" -ne 0; do
+			printf '\e[F\e[J'
+			queue=$((queue - 1))
+		done
+		echo "$line"
+		queue=$((queue + 1))
+	done </dev/stdin
+
 	while test "$queue" -ne 0; do
 		printf '\e[F\e[J'
 		queue=$((queue - 1))
 	done
-	echo "$line"
-	queue=$((queue + 1))
-done </dev/stdin
-
-while test "$queue" -ne 0; do
-	printf '\e[F\e[J'
-	queue=$((queue - 1))
-done
+fi
