ensure-trailing-slash: modern conventions

diff --git a/commands/ensure-trailing-slash b/commands/ensure-trailing-slash
--- a/commands/ensure-trailing-slash
+++ b/commands/ensure-trailing-slash
@@ -1,34 +1,74 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-if is-help-empty "$@"; then
+# =====================================
+# Arguments
+
+# help
+function help() {
 	cat <<-EOF >/dev/stderr
 		ABOUT:
 		Ensure directories have a trailing newline.
 		Ensure files do not have a trailing newline.
 
 		USAGE:
-		ensure-trialing-slash <path>...
+		ensure-trailing-slash [--] <...path>
 	EOF
-	exit 22 # Invalid argument
+	if test "$#" -ne 0; then
+		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
+	fi
+	return 22 # Invalid argument
+}
+
+# process
+option_paths=()
+while test "$#" -ne 0; do
+	item="$1"
+	shift
+	case "$item" in
+	'help' | '--help' | '-h') help ;;
+	'--')
+		option_paths+=("$@")
+		shift "$#"
+		break
+		;;
+	'--'*) help "An unrecognised flag was provided: $item" ;;
+	*) option_paths+=("$item") ;;
+	esac
+done
+
+# check
+if test "${#option_paths[@]}" -eq 0; then
+	help "No paths were provided"
 fi
 
-for arg in "$@"; do
-	if test -d "$arg"; then
-		if [[ "$arg" != */ ]]; then
-			echo "$arg/"
+# =====================================
+# Action
+
+function ensure_trailing_slash {
+	local path length
+	for path in "$@"; do
+		if test -d "$path"; then
+			if [[ "$path" != */ ]]; then
+				echo "$path/"
+			else
+				echo "$path"
+			fi
+		elif test -f "$path"; then
+			if [[ "$path" = */ ]]; then
+				length="${#path}"
+				echo "${path:0:length-1}"
+			else
+				echo "$path"
+			fi
 		else
-			echo "$arg"
+			echo-style --error="[$path] is not a file nor directory." >/dev/stderr
+			exit 1
 		fi
-	elif test -f "$arg"; then
-		if [[ "$arg" = */ ]]; then
-			length="${#arg}"
-			echo "${arg:0:length-1}"
-		else
-			echo "$arg"
-		fi
-	else
-		echo-style --error="[$arg] is not a file nor directory." >/dev/stderr
-		exit 1
-	fi
-done
+	done
+}
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	ensure_trailing_slash "${option_paths[@]}"
+fi
