eval-capture: fix cleanup of semaphores
the `eval-capture` semaphore cleanup had diverged from the conventions used in `__try`

this now converges the various semaphore contexts to a consistent `__get_context_prefix` which makes debugging easier

there is a risk of a large callstack exceeding the file system name length, however we will see what happens on CI as to whether that a risk in practice

diff --git a/commands/eval-capture b/commands/eval-capture
--- a/commands/eval-capture
+++ b/commands/eval-capture
@@ -4,12 +4,13 @@ source "$DOROTHY/sources/bash.bash"
 # disable strict mode so that we can test it specifically
 set +eu
 
+# handle macos expected crash
 expect_crash='no'
 if is-mac && [[ $BASH_VERSION_CURRENT == '3.2.57' && $BASH == '/bin/bash' ]]; then
 	expect_crash='yes'
-	# cleanup the expected leftover status file such that our dorothy tests do not fail on this expected leftover
+	# because of the crash, cleanup the leftover semaphores
 	function cleanup {
-		fs-remove --verbose --no-confirm -- "$TMPDIR/dorothy/try/3.2.57-testing_middle-"* >&2
+		rm -fv -- "$TMPDIR/dorothy/semaphores/[3.2.57] [main][testing_root][testing_middle] [__try] "* >&2
 	}
 	trap cleanup EXIT
 fi
