rewrote `confirm*`, `setup-node`, `eval-collapse`
user facing changes:

- `confirm*` scripts have been reworked to:
    - support question details
    - output question with blink options, and upon finale, with its selection
    - support ctrl+c terminations, passing along exit code and indicating with ABORT
    - support spacebar for defaults, for items that support it
    - much more effecient too, no longer have to redo everything each invalid keypress
- `setup-node` now cleans nvm versions, and if that fails, then cleans nvm, this can be prevented via NVM_CLEAN=no
- `setup-node` also uses the new `eval-collapse` and `confirm` features for a cleaner experience
- `setup-vim` now outputs successful replacements

major internal changes:

- added `echo-count-lines` to count lines
- `echo-clear-lines` has been rejigged to support more edge cases, such as non-terminating lines, piped output, and erasing already outputted content
- `eval-collapse` has been redone to be more reliable and easier to understand
- `stdinargs` can now use `line` and `inline` and `arg` functions, this is used by `echo-count-lines`

other changes:

- `git-remote-apply` no longer does tty and stderr stuff, as it was interfering with `eval-collapse`
- `setup-mac` cleaner success output

diff --git a/commands/eval-collapse b/commands/eval-collapse
--- a/commands/eval-collapse
+++ b/commands/eval-collapse
@@ -5,15 +5,17 @@ source "$DOROTHY/sources/strict.bash"
 # helper
 function eval_collapse() {
 	# prepare
-	local ec=0 status='' log options QUIET option_pending option_success option_failure args
-	log="$(mktemp)"
+	local ec=0 status='' headers body options QUIET option_pending option_success option_failure args
+	headers="$(mktemp)"
+	body="$(mktemp)"
 
 	# options
 	mapfile -t options < <(echo-before-separator "$@")
-	QUIET="$(get-flag-value quiet --missing="${QUIET-}" -- "${options[@]}" | echo-affirmative || get-flag-value verbose --missing="${VERBOSE-}" -- "$@" | echo-non-affirmative || :)"
+	QUIET="$(get-flag-value quiet --missing="${QUIET-}" -- "${options[@]}" | echo-affirmative || get-flag-value verbose --missing="${VERBOSE:-"no"}" -- "$@" | echo-non-affirmative || :)" # yes/no, default yes
 	option_pending="$(get-flag-value pending -- "${options[@]}")"
 	option_success="$(get-flag-value success -- "${options[@]}")"
 	option_failure="$(get-flag-value failure -- "${options[@]}")"
+	option_wrap="$(get-flag-value wrap --missing=yes -- "${options[@]}" | echo-affirmative)"
 	mapfile -t args < <(echo-after-separator "$@")
 
 	# footer
@@ -32,53 +34,54 @@ function eval_collapse() {
 	# shellcheck disable=SC2064
 	trap "eval_collapse_footer \$? ${option_success@Q} ${option_failure@Q}" RETURN
 
-	# header
+	# headers
 	if test -n "$option_pending"; then
-		echo "$option_pending"
+		echo "$option_pending" | tee -a "$headers"
 	fi
-	echo-color --oe --h3="${args[*]}" --ce
+	if test "$option_wrap" = 'yes'; then
+		echo-color --oe --h3="${args[*]}" --ce | tee -a "$headers"
+	fi
 
-	# command
-	ec=0 && ("${args[@]}" 2>&1 | tee "$log" | echo-revolving-door) || ec="$?"
+	# keep headers while we run the command and revolve door its output
+	ec=0 && ("${args[@]}" 2>&1 | tee "$body" | echo-revolving-door) || ec="$?"
+
+	# clear headers, we can re-add them if necessary
+	echo-clear-lines <"$headers"
+
+	# if queit, and successful, then we are done
+	if test "$QUIET" = 'yes' -a "$ec" -eq 0; then
+		return "$ec"
+	fi
+	# otherwise we want to output things
+
+	# prepare status output
 	if test "$ec" -eq 0; then
-		# unless QUIET=no (verbose mode) then
-		# hide header (the revolving door already hid the command output)
-		# and return
-		if test "$QUIET" != 'no'; then
-			# hide headers
-			if test -n "$option_pending"; then
-				echo-clear-line
-			fi
-			echo-clear-line
-			# return
-			return "$ec"
-		fi
-		# success status
+		# success
 		status="$(echo-color -n --g3="[$ec]")"
 	else
-		# failure status
+		# failure
 		status="$(echo-color -n --e3="[$ec]")"
 	fi
 
-	# did the command output anything?
-	if test -z "$(cat "$log")"; then
-		# if not, hide header
-		if test -n "$option_pending"; then
-			echo-clear-line
-		fi
-		echo-clear-line
-		# and output header footer combo
+	# if it didn't output anything, then output only the header footer combo, and be done
+	if test -z "$(cat "$body")"; then
 		echo-color --oe --h3="${args[*]}" --ces "$status"
-	else
-		# if it did
-		# then output its results (if error)
-		if test "$ec" -ne 0; then
-			cat "$log"
-		fi
-		# then output footer
+		return "$ec"
+	fi
+	# the command outputted things
+
+	# outpout wrap header
+	if test "$option_wrap" = 'yes'; then
+		echo-color --oe --h3="${args[*]}" --ce | tee -a "$headers"
+	fi
+	# if verbose, or failure, output body
+	if test "$QUIET" = 'no' -o "$ec" -ne 0; then
+		cat "$body"
+	fi
+	# outpout wrap footer
+	if test "$option_wrap" = 'yes'; then
 		echo-color --oes --h3="${args[*]}" --ce "$status"
 	fi
-
 	# done
 	return "$ec"
 }
