brew, eval-helper, setup-mac-brew: fixes
- `brew`: fix `--help` handling
- `brew-installed(.ts)?`: support tap detection
- `echo-revolving-door`: fix reinjection of old code taht needed modern convention
- `eval-helper`: fix wrap, sudo/elevate, quiet conflicts - re-add `--shapeshifter`
- `setup-mac-brew`: fix for changes to tap apis, fixes regarding `eval-helper`, prettified the output based on new `brew-installed` tap detection and `eval-helper` abilities

Note that if say `eval-helper --quiet --wrap -- setup-util-devel` isn't working, it is because it is going to TTY, so you need to do something like `TERMINAL_OUTPUT_TARGET=2 setup-util-devel 2>&1 | echo-revolving-door` to see the problem, in which case you want `--shapeshifter` anyway.

diff --git a/commands/eval-helper b/commands/eval-helper
--- a/commands/eval-helper
+++ b/commands/eval-helper
@@ -196,8 +196,9 @@ function eval_helper() ( # to use this as a function, it needs to change from a 
 
 	# process
 	local item option_cmd=() \
-	option_quiet='' option_persist='' option_wrap='' option_time='no' option_pending='' option_success='' option_failure='' \
-	option_do_args=() option_revolving_args=() option_alternative_screen_buffer='' \
+	option_quiet='' option_pending_on_success='' option_wrap_on_success='' option_body_on_success='' \
+	option_persist='' option_wrap='' option_time='no' option_pending='' option_success='' option_failure='' \
+	option_do_args=() option_revolving_args=() option_alternative_screen_buffer='' option_shapeshifter='' \
 	option_terminal_lines='' option_terminal_columns='' \
 	option_confirm='' \
 	option_until='' option_until_interval='' option_until_attempts='' \
@@ -211,8 +212,11 @@ function eval_helper() ( # to use this as a function, it needs to change from a 
 		'--no-color'* | '--color'*) __flag --source={item} --target={COLOR} --affirmative --export ;;
 		'--no-verbose'* | '--verbose'*) __flag --source={item} --target={option_quiet} --non-affirmative ;;
 		'--no-quiet'* | '--quiet'*) __flag --source={item} --target={option_quiet} --affirmative ;;
+		'--no-pending-on-success'* | '--pending-on-success'*) __flag --source={item} --target={option_pending_on_success} --affirmative --coerce ;;
+		'--no-wrap-on-success'* | '--wrap-on-success'*) __flag --source={item} --target={option_wrap_on_success} --affirmative --coerce ;;
+		'--no-body-on-success'* | '--body-on-success'*) __flag --source={item} --target={option_body_on_success} --affirmative --coerce ;;
 		'--persist='*) option_persist="${item#*=}" ;;
-		'--no-wrap'* | '--wrap'*) __flag --source={item} --target={option_wrap} --affirmative ;;
+		'--no-wrap'* | '--wrap'*) __flag --source={item} --target={option_wrap} --affirmative --coerce ;;
 		'--no-time'* | '--time'*) __flag --source={item} --target={option_time} --affirmative --coerce ;;
 		'--pending='*) option_pending="${item#*=}" ;;
 		'--success='*) option_success="${item#*=}" ;;
@@ -222,13 +226,14 @@ function eval_helper() ( # to use this as a function, it needs to change from a 
 		# '--redirect-status='*) option_redirect_status="${item#*=}" ;; <-- ^^
 		'--discard-'*'={'* | '--copy-'*'={'* | '--redirect-'*'={'*) help "Until eval-helper can be sourced as __eval_helper variable assignments will not work:, write to a file then read from it instead: $item" ;;
 		'--discard-'* | '--copy-'* | '--redirect-'*) option_do_args+=("$item") ;;
-		'--no-alternative-screen-buffer'* | '--alternative-screen-buffer'*) __flag --source={item} --target={option_alternative_screen_buffer} --affirmative ;;
+		'--no-alternative-screen-buffer'* | '--alternative-screen-buffer'*) __flag --source={item} --target={option_alternative_screen_buffer} --affirmative --coerce ;;
+		'--no-shapeshifter'* | '--shapeshifter'*) __flag --source={item} --target={option_shapeshifter} --affirmative --coerce ;;
 		'--revolving-'*) option_revolving_args+=("--${item#--revolving-}") ;;
 		# ...
 		'--terminal-lines='*) option_terminal_lines="${item#*=}" ;;
 		'--terminal-columns='*) option_terminal_columns="${item#*=}" ;;
 		# ...
-		'--no-confirm'* | '--confirm'*) __flag --source={item} --target={option_confirm} --affirmative ;;
+		'--no-confirm'* | '--confirm'*) __flag --source={item} --target={option_confirm} --affirmative --coerce ;;
 		# ...
 		'--until='*) option_until="${item#*=}" ;;
 		'--until-interval='* | '--until-delay='*) option_until_interval="${item#*=}" ;;
@@ -244,8 +249,8 @@ function eval_helper() ( # to use this as a function, it needs to change from a 
 		'--user='*) option_user="${item#*=}" ;;
 		'--group='*) option_group="${item#*=}" ;;
 		'--reason='*) option_reason="${item#*=}" ;;
-		'--no-inherit'* | '--inherit'*) __flag --source={item} --target={option_inherit} --affirmative ;;
-		'--no-home'* | '--home'*) __flag --source={item} --target={option_home} --affirmative ;;
+		'--no-inherit'* | '--inherit'*) __flag --source={item} --target={option_inherit} --affirmative --coerce ;;
+		'--no-home'* | '--home'*) __flag --source={item} --target={option_home} --affirmative --coerce ;;
 		'--invalidate-elevation')
 			if __command_exists -- sudo; then
 				sudo --reset-timestamp || :
@@ -274,6 +279,21 @@ function eval_helper() ( # to use this as a function, it needs to change from a 
 			option_quiet='no'
 		fi
 	fi
+	local verbose
+	if [[ $option_quiet == 'yes' ]]; then
+		verbose='no'
+	else
+		verbose='yes'
+	fi
+	if [[ -z $option_pending_on_success ]]; then
+		option_pending_on_success="$verbose"
+	fi
+	if [[ -z $option_wrap_on_success ]]; then
+		option_wrap_on_success="$verbose"
+	fi
+	if [[ -z $option_body_on_success ]]; then
+		option_body_on_success="$verbose"
+	fi
 
 	# home
 	if [[ -z $option_home ]]; then
@@ -281,6 +301,15 @@ function eval_helper() ( # to use this as a function, it needs to change from a 
 			option_home='no'
 		else
 			option_home='yes'
+		fi
+	fi
+
+	# if time, ensure wrap
+	if [[ $option_time == 'yes' ]]; then
+		if [[ -z $option_wrap ]]; then
+			option_wrap='yes'
+		elif [[ $option_wrap != 'yes' ]]; then
+			help 'The option ' --code='--time' ' requires ' --code='--wrap'
 		fi
 	fi
 
@@ -318,12 +347,12 @@ function eval_helper() ( # to use this as a function, it needs to change from a 
 	fi
 
 	# ensure shapeshifters that write to TTY are cleared correctly
-	if [[ -z $option_alternative_screen_buffer ]]; then
+	local is_potential_shapeshifter=''
+	if [[ -z $option_alternative_screen_buffer && -z $option_shapeshifter ]]; then
 		case "${option_cmd[*]}" in
-		'ssh '*) option_alternative_screen_buffer='yes' ;;
-		'sudo '*) option_alternative_screen_buffer='yes' ;;
-		'doas '*) option_alternative_screen_buffer='yes' ;;
-		*) option_alternative_screen_buffer='no' ;;
+		'ssh '*) is_potential_shapeshifter='yes' ;;
+		'sudo '*) is_potential_shapeshifter='yes' ;;
+		'doas '*) is_potential_shapeshifter='yes' ;;
 		esac
 	fi
 
@@ -380,12 +409,6 @@ function eval_helper() ( # to use this as a function, it needs to change from a 
 		fi
 	fi
 
-	# quiet, verbose, modes
-	# if [[ -n $option_success_verbosity ]]; then
-	# fi
-	# if [[ -n $option_failure_verbosity ]]; then
-	# fi
-
 	# =====================================
 	# Action
 
@@ -424,6 +447,23 @@ function eval_helper() ( # to use this as a function, it needs to change from a 
 		echo-revolving-door "${option_revolving_args[@]}" --lines="-$header_lines" --terminal-lines="$terminal_lines" --terminal-columns="$terminal_columns" --target=TTY "$@" || return
 	}
 
+	# time
+	if [[ $option_time == 'yes' ]]; then
+		local time_before time_after time_delta style_time_args
+		function __start_time {
+			style_time_args=()
+			time_before="$(__get_epoch_time)"
+		}
+		function __finish_time {
+			time_after="$(__get_epoch_time)"
+			time_delta="$(echo-math -- "$time_after - $time_before")"
+			style_time_args+=(' ' --code="in $time_delta seconds")
+		}
+	else
+		function __start_time { :; }
+		function __finish_time { :; }
+	fi
+
 	# run
 	# never execute [run_] in a conditional, as if command is an function, its behaviour will be altered
 	local run_status cmd_elevate=() next_attempt=1 elevate_prompt styled_standard_command_string styled_elevate_command_string styled_command_string
@@ -443,7 +483,13 @@ function eval_helper() ( # to use this as a function, it needs to change from a 
 		fi
 
 		# confirm
-		command="$(__print_style --element="$styled_command_string")"$'\n'
+		if [[ $option_wrap == 'yes' ]]; then
+			command="$(__print_style --element="$styled_command_string")"$'\n'
+		else
+			command="$styled_command_string"$'\n'
+		fi
+
+		# add reason, and if desired, confirm
 		if [[ $elevate_prompt == 'yes' ]]; then
 			# has a reason
 			messages+="$(__print_style --notice="$option_reason")"$'\n'
@@ -458,7 +504,7 @@ function eval_helper() ( # to use this as a function, it needs to change from a 
 			return 0
 		fi
 
-		# command
+		# add command
 		if [[ $option_wrap == 'yes' || $elevate_prompt == 'yes' ]]; then
 			messages+="$command"
 		fi
@@ -466,71 +512,79 @@ function eval_helper() ( # to use this as a function, it needs to change from a 
 		# refresh terminal size
 		__refresh_terminal_size
 
-		# output everything if in verbose mode
-		if [[ $option_quiet == 'no' || $terminal_lines -eq 0 || $terminal_columns -eq 0 ]]; then
+		# execution mode, either direct, alternative, or clear
+		# this must not break `p="$(eval-helper --inherit --elevated= --elevate=13  --user= --group= --reason= -- fs-path.bash --resolve=yes --validate=no -- /Users/balupton/.config/dorothy)"; echo "p=$p"`
+		local mode direct
+		if [[ $option_shapeshifter == 'yes' || $terminal_lines -eq 0 || $terminal_columns -eq 0 ]]; then
+			mode='direct'
+		elif [[ $option_alternative_screen_buffer == 'yes' ]]; then
+			mode='alternative'
+		else
+			# default to direct, as it still allows interpolation to work
+			# however, undo direct iff we have manually specified an option that undoes direct
+			local direct='yes'
+			if [[ $option_pending_on_success == 'no' && -n $option_pending ]]; then
+				direct='no'
+			elif [[ $option_wrap_on_success == 'no' && $option_wrap == 'yes' ]]; then
+				direct='no'
+			elif [[ $option_body_on_success == 'no' ]]; then
+				direct='no'
+			fi
+			# if we want direct, do direct, if we don't want direct, then figure out if we want alternative or clear mode
+			if [[ $direct == 'yes' ]]; then
+				mode='direct'
+			elif [[ $is_potential_shapeshifter == 'yes' || $elevate_prompt == 'yes' ]]; then
+				mode='alternative'
+			else
+				mode='clear'
+			fi
+		fi
+
+		# run it according to the mode
+		if [[ $mode == 'direct' ]]; then
+			# handle the persistence, this is used to say persist something we are interpolating
 			if [[ -n $option_persist ]]; then
 				do_args+=("--copy-$option_persist=TTY")
 			fi
 
-			# flush
+			# header
 			__flush_messages
 
-			# if time, fetch start time
-			if [[ $option_time == 'yes' ]]; then
-				local time_before time_after time_delta
-				time_before="$(__get_epoch_time)"
-			fi
-
-			# body
+			# execute
+			__start_time
 			__do --redirect-status={run_status} "${do_args[@]}" "${option_do_args[@]}" -- \
 				"${cmd[@]}"
+			__finish_time
 
-			# close wrap
+			# footer
 			if [[ $option_wrap == 'yes' ]]; then
-				if [[ $option_time == 'yes' ]]; then
-					time_after="$(__get_epoch_time)"
-					time_delta="$(echo-math -- "$time_after - $time_before")"
-					style_time_args+=(' ' --code="in $time_delta seconds")
-				fi
 				messages+="$(__print_style --/element="$styled_command_string" --status="$run_status" "${style_time_args[@]}")"$'\n'
 			fi
-
-			# success or failure
-			if [[ $run_status -eq 0 ]]; then
-				if [[ -n $option_success ]]; then
-					messages+="$option_success"$'\n'
-				fi
-			else
-				if [[ -n $option_failure ]]; then
-					messages+="$option_failure"$'\n'
-				fi
-			fi
-
-			# flush
-			__flush_messages
 		else
-			# direct STDOUT and STDERR to TTY, as they will be truncated and will be outputting clear ansi codes, which will confuse anything that is expecting legit STDOUT output, we cannot detect shapeshifting after the fact, as it occurs in the TTY, not STDOUT, nor STDERR
+			# direct STDOUT and STDERR to TTY, as they will be truncated and will be outputting clear ANSI codes, which will confuse anything that is expecting legit STDOUT output, we cannot detect shapeshifting after the fact, as it occurs in the TTY, not STDOUT, nor STDERR
 			local body
 			if [[ -n $option_persist ]]; then
 				do_args+=("--copy-$option_persist={persist}")
 			fi
 
-			if [[ $option_alternative_screen_buffer == 'yes' || $elevate_prompt == 'yes' ]]; then
+			if [[ $mode == 'alternative' ]]; then
 				# start alternative screen buffer, and redo header inside of it
 				__print_style --no-trail --tty --alternative-screen-buffer --="$messages"
 				__clear_messages
 
 				# run command, output to STDERR, capture, then to TTY
+				__start_time
 				__do --redirect-status={run_status} "${do_args[@]}" "${option_do_args[@]}" \
 					--redirect-output=STDERR \
 					--copy-stderr={body} \
 					--redirect-output=TTY \
 					-- \
 					"${cmd[@]}"
+				__finish_time
 
 				# restore the original screen buffer
 				__print_style --no-trail --tty --default-screen-buffer
-			else
+			elif [[ $mode == 'clear' ]]; then
 				# update header lines
 				if [[ -n $messages ]]; then
 					header_lines="$(echo-wrap --columns="$terminal_columns" -- "$messages" | echo-count-lines --stdin)"
@@ -540,87 +594,85 @@ function eval_helper() ( # to use this as a function, it needs to change from a 
 				fi
 
 				# trap '' SIGINT
+				__start_time
 				__do --redirect-status={run_status} "${do_args[@]}" "${option_do_args[@]}" \
 					--redirect-output=STDERR \
 					--copy-stderr={body} \
 					--redirect-output="(__revolving)" \
 					-- \
 					"${cmd[@]}"
+				__finish_time
 				# trap - SIGINT
 
 				# clear header, we can re-add them later if needed
 				if [[ $header_lines -ne 0 ]]; then
 					echo-clear-lines --lines="$header_lines" --target=TTY
 				fi
-			fi
-
-			# generate output
-			if [[ $option_quiet == 'no' || $run_status -ne 0 ]]; then
-				# verbose/failure: pending message, command output and status, and success or failure message
-
-				# add pending
-				if [[ -n $option_pending ]]; then
-					messages+="$option_pending"$'\n'
-				fi
-
-				# add body
-				if [[ $option_wrap == 'no' ]]; then
-					if [[ -n $body ]]; then
-						__flush_messages
-						__print_lines "$body" >&2
-					fi
-				else
-					if [[ -n $body ]]; then
-						messages+="$(__print_style --element="$styled_command_string")"$'\n'
-						__flush_messages
-						__print_lines "$body" >&2
-						messages+="$(__print_style --/element="$styled_command_string" --status="$run_status")"$'\n'
-					else
-						messages+="$(__print_style --element="$styled_command_string" --/fragment='' --status="$run_status")"$'\n'
-					fi
-				fi
-
-				# add success or failure
-				if [[ $run_status -eq 0 ]]; then
-					if [[ -n $option_success ]]; then
-						messages+="$option_success"$'\n'
-					fi
-				else
-					if [[ -n $option_failure ]]; then
-						messages+="$option_failure"$'\n'
-					fi
-				fi
-
 			else
-				# if wrap: pending message, command status, and success message
-				# if no wrap: success message
-
-				# truncate body if wrapping
-				if [[ $option_wrap == 'yes' ]]; then
-					# add pending
-					if [[ -n $option_pending ]]; then
-						messages+="$option_pending"$'\n'
-					fi
-
-					# wrap
-					if [[ -n $body ]]; then
-						# close fragment of ellipses as we have truncated
-						messages+="$(__print_style --element="$styled_command_string" --code=' … ' --/fragment --status="$run_status")"$'\n'
-					else
-						# self close, as no data
-						messages+="$(__print_style --element/="$styled_command_string" --status="$run_status")"$'\n'
-					fi
-				fi
-
-				# add success
-				if [[ -n $option_success ]]; then
-					messages+="$option_success"$'\n'
-				fi
+				__print_error "An invalid mode was encountered: $(__dump {mode} || :)"
+				return 104 # ENOTRECOVERABLE 104 State not recoverable
 			fi
 
-			# output
-			__flush_messages
+			# determine shows
+			local show_pending='yes' show_wrap="$option_wrap" show_body='yes'
+			if [[ -z $option_pending ]]; then
+				show_pending='no'
+			fi
+			if [[ $run_status -eq 0 ]]; then
+				if [[ $option_pending_on_success == 'no' ]]; then
+					show_pending='no'
+				fi
+				if [[ $option_wrap_on_success == 'no' || -z $show_wrap ]]; then
+					show_wrap='no'
+				fi
+				if [[ $option_body_on_success == 'no' ]]; then
+					show_body='no'
+				fi
+			elif [[ -z $show_wrap ]]; then
+				# while doing `=yes` is useful and intuitive to the user, it then means we are implicitly enabling wrap, which is counter-intuitive to the developer
+				# perhaps doing `=yes` makes sense at some point, iff TTY is available, so the wrap does not corrupt the STDOUT/STDERR
+				# see any of the usage of `is-fs.bash`, e.g. `is-present -- missing` for an example of when default `=yes` becomes silly
+				show_wrap='no'
+			fi
+
+			# add pending
+			if [[ $show_pending == 'yes' ]]; then
+				messages+="$option_pending"$'\n'
+			fi
+
+			# add body
+			if [[ $show_wrap == 'no' ]]; then
+				if [[ -n $body && $show_body == 'yes' ]]; then
+					__flush_messages
+					__print_lines "$body" >&2
+				fi
+			elif [[ -z $body ]]; then
+				# self close, as no data
+				messages+="$(__print_style --element/="$styled_command_string" --status="$run_status" "${style_time_args[@]}")"$'\n'
+			elif [[ $show_body == 'no' ]]; then
+				# close fragment of ellipses as we have truncated
+				messages+="$(__print_style --element="$styled_command_string" --code=' … ' --/fragment='' --status="$run_status" "${style_time_args[@]}")"$'\n'
+			else # show_body == yes
+				messages+="$(__print_style --element="$styled_command_string")"$'\n'
+				__flush_messages
+				__print_lines "$body" >&2
+				messages+="$(__print_style --/element="$styled_command_string" --status="$run_status" "${style_time_args[@]}")"$'\n'
+			fi
 		fi
+
+		# success or failure
+		if [[ $run_status -eq 0 ]]; then
+			if [[ -n $option_success ]]; then
+				messages+="$option_success"$'\n'
+			fi
+		else
+			if [[ -n $option_failure ]]; then
+				messages+="$option_failure"$'\n'
+			fi
+		fi
+
+		# output
+		__flush_messages
 	}
 	function run_args_with_optional_elevation {
 		# increment attempt
diff --git a/commands/flush-dns b/commands/flush-dns
--- a/commands/flush-dns
+++ b/commands/flush-dns
@@ -43,23 +43,23 @@ function flush_dns() (
 			eval-helper --quiet --elevate \
 				--pending="$(__print_style --bold='Restarting: mDNSResponder')" \
 				--success="$(__print_style --success='Restarted: mDNSResponder')" \
-				--failure="$(__print_style --error='Failed to restart: mDNSResponder')" -- \
-				killall -HUP mDNSResponder
+				--failure="$(__print_style --error='Failed to restart: mDNSResponder')" \
+				-- killall -HUP mDNSResponder
 		fi
 		if __command_exists -- dscacheutil; then
 			# doesn't need elevation
 			eval-helper --quiet \
 				--pending="$(__print_style --bold='Flushing: dscacheutil')" \
 				--success="$(__print_style --success='Flushed: dscacheutil')" \
-				--failure="$(__print_style --error='Failed to flush: dscacheutil')" -- \
-				dscacheutil -flushcache
+				--failure="$(__print_style --error='Failed to flush: dscacheutil')" \
+				-- dscacheutil -flushcache
 		fi
 		if __command_exists -- discoveryutil; then
 			eval-helper --quiet --elevate \
 				--pending="$(__print_style --bold='Flushing: discoveryutil')" \
 				--success="$(__print_style --success='Flushed: discoveryutil')" \
-				--failure="$(__print_style --error='Failed to flush: discoveryutil')" -- \
-				discoveryutil mdnsflushcache
+				--failure="$(__print_style --error='Failed to flush: discoveryutil')" \
+				-- discoveryutil mdnsflushcache
 		fi
 	elif __command_exists -- resolvectl; then
 		eval-helper --quiet --elevate \
@@ -67,8 +67,8 @@ function flush_dns() (
 			--success="$(__print_style --success='Flushed DNS cache via Systemd')" \
 			--failure="$(
 				__print_style --error='Failed to flush DNS cache via Systemd.' ' ' --notice='If using an alternative DNS service, then this is expected.'
-			)" -- \
-			resolvectl flush-caches --no-pager || :
+			)" \
+			-- resolvectl flush-caches --no-pager || :
 	else
 		__print_error 'DNS flushing not yet implemented for this operating system.'
 		return 19 # ENODEV 19 Operation not supported by device
diff --git a/commands/setup-mac-brew b/commands/setup-mac-brew
--- a/commands/setup-mac-brew
+++ b/commands/setup-mac-brew
@@ -253,8 +253,9 @@ function setup_mac_brew() (
 
 		# if yes, then install the linting tools
 		if [[ $HOMEBREW_ENCODING_INSTALL == 'yes' ]]; then
-			__print_style --h1='Homebrew encoding tools'
-			__print_style --notice='This can take a while... ⏲'
+			__print_style \
+				--h1='Homebrew encoding tools' --newline \
+				--notice='This can take a while... ⏲'
 
 			# install dependencies:
 			# https://github.com/varenc/homebrew-ffmpeg/issues/28
@@ -286,12 +287,13 @@ function setup_mac_brew() (
 			# parse the space separated options into an array
 			__split --source={ffmpeg_opts_string} --target={ffmpeg_opts_array} --delimiter=' ' --no-zero-length
 			# install with the build options
-			eval_helper --quiet --wrap --shapeshifter -- \
+			eval_helper --quiet --wrap -- \
 				brew install homebrew-ffmpeg/ffmpeg/ffmpeg "${ffmpeg_opts_array[@]}"
 
 			# log
-			__print_style --g2='Install ffmpeg with options'
-			__print_style --g1='Homebrew encoding tools'
+			__print_style \
+				--g2='Install ffmpeg with options' --newline \
+				--g1='Homebrew encoding tools'
 		else
 			__print_style --notice='Skipped encoding tools installation, due to preference.'
 		fi
@@ -393,17 +395,19 @@ function setup_mac_brew() (
 		local pkg
 		__print_style --h2="Uninstall $# packages"
 		if [[ $# -ne 0 ]]; then
-			if brew-installed -- "$@" &>/dev/null; then
-				__print_style --dim='You can ignore "No available ..." errors.'
-				__print_style --dim='You can ignore "No such keg: ..." errors.'
+			if brew-installed --quiet -- "$@"; then
 				for pkg in "$@"; do
-					brew uninstall --quiet --ignore-dependencies "$pkg" || :
+					if brew-installed --quiet -- "$pkg"; then
+						eval_helper --quiet --wrap \
+						--pending="$(__print_style --bold='Uninstalling: ' --code="$pkg")" \
+						--success="$(__print_style --success='Uninstalled: ' --code="$pkg")" \
+						--failure="$(__print_style --error='Failed to uninstall: ' --code="$pkg")" \
+						-- brew uninstall --quiet --ignore-dependencies "$pkg" || :
+					fi
 				done
 				# cleanup, used to fix any breaks after the removals, this is only here are is purges upgrade caches, which is undesirable on unreliable internet connections as it means re-runs always has to download everything again
 				source "$DOROTHY/sources/environment.sh"
 				clean_brew
-			else
-				__print_style --dim='Already uninstalled.'
 			fi
 		fi
 		__print_style --g2="Uninstall $# packages"
@@ -414,10 +418,17 @@ function setup_mac_brew() (
 		local tap
 		__print_style --h2="Untap $# repositories"
 		if [[ $# -ne 0 ]]; then
-			__print_style --dim='You can ignore "Error: No available tap ..." errors.'
-			for tap in "$@"; do
-				brew untap --quiet "$tap" || :
-			done
+			if brew-installed --quiet --tap -- "$@"; then
+				for tap in "$@"; do
+					if brew-installed --quiet -- "$tap"; then
+						eval_helper --quiet --wrap \
+							--pending="$(__print_style --bold='Untapping: ' --code="$tap")" \
+							--success="$(__print_style --success='Untapped: ' --code="$tap")" \
+							--failure="$(__print_style --error='Failed to untap: ' --code="$tap")" \
+							-- brew untap --quiet "$tap" || :
+					fi
+				done
+			fi
 		fi
 		__print_style --g2="Untap $# repositories"
 	}
@@ -428,9 +439,10 @@ function setup_mac_brew() (
 		__print_style --h2="Tap $# repositories"
 		for tap in "$@"; do
 			eval_helper --quiet --wrap \
-				--pending="Tap: $tap" \
-				--success="Tapped: $tap" -- \
-				brew tap --quiet "$tap"
+				--pending="$(__print_style --bold='Tap: ' --code="$tap")" \
+				--success="$(__print_style --success='Tapped: ' --code="$tap")" \
+				--failure="$(__print_style --error='Failed to tap: ' --code="$tap")" \
+				-- brew tap --quiet "$tap"
 		done
 		__print_style --g2="Tap $# repositories"
 	}
@@ -459,9 +471,10 @@ function setup_mac_brew() (
 		__print_style --h2="Update $# repositories"
 		for repo in "$@"; do
 			eval_helper --quiet --wrap \
-				--pending="Updating: $repo" \
-				--success="Updated: $repo" -- \
-				brew_update_repo "$repo"
+				--pending="$(__print_style --bold='Updating: ' --path="$repo")" \
+				--success="$(__print_style --success='Updated: ' --path="$repo")" \
+				--failure="$(__print_style --error='Failed to update: ' --path="$repo")" \
+				-- brew_update_repo "$repo"
 		done
 		__print_style --g2="Update $# repositories"
 	}
@@ -501,12 +514,18 @@ function setup_mac_brew() (
 	brew_tap "${HOMEBREW_TAPS[@]}"
 
 	# repositories
-	local font_cask_repo_path casks_repo_path repo_paths=()
-	font_cask_repo_path="$(brew --repo 'homebrew/cask-fonts')"
-	casks_repo_path="$(fs-path --parent -- "$font_cask_repo_path")"
-	__split --target={repo_paths} --no-zero-length --invoke -- \
-		echo-subpaths -- "$casks_repo_path"
-	brew_repo "${repo_paths[@]}"
+	if [[ "${#HOMEBREW_TAPS[@]}" -ne 0 ]]; then
+		local first_tap="${HOMEBREW_TAPS[0]}" first_tap_repo_path casks_repo_path repo_paths=()
+		first_tap_repo_path="$(brew --repo "$first_tap")"
+		casks_repo_path="$(fs-path --parents -- "$first_tap_repo_path")"
+		if [[ $first_tap == */* ]]; then
+			# homebrew-ffmpeg/ffmpeg => /opt/homebrew/Library/Taps/homebrew-ffmpeg/homebrew-ffmpeg => /opt/homebrew/Library/Taps
+			casks_repo_path="$(fs-path --parents -- "$casks_repo_path")"
+		fi
+		__split --target={repo_paths} --no-zero-length --invoke -- \
+			echo-subpaths -- "$casks_repo_path"
+		brew_repo "${repo_paths[@]}"
+	fi
 
 	# update
 	__print_style --h2='Update Homebrew'
@@ -528,8 +547,7 @@ function setup_mac_brew() (
 
 	# dependencies
 	__print_style --h2='Install build dependencies'
-	eval_helper --quiet --wrap -- \
-		setup-util-devel
+	setup-util-devel --quiet
 	__print_style --g2='Install build dependencies'
 
 	# install encoding tools
