move ask's stderr ignore due to no-tty into eval-tester

diff --git a/commands/eval-tester b/commands/eval-tester
--- a/commands/eval-tester
+++ b/commands/eval-tester
@@ -67,8 +67,11 @@ function eval_tester() (
 	# Action
 
 	# run the command
-	local args=() cmd_status stdout stderr cmd_string fail='no' title=''
+	local args=() cmd_status stdout stderr cmd_string fail='no' title='' using_tty_stderr_fallback='no'
 	cmd_string="$(echo-quote "${cmd[@]}" | echo-join ' ')"
+	if ! is-tty; then
+		using_tty_stderr_fallback='yes'
+	fi
 	if test -n "$option_name"; then
 		title="$option_name: $cmd_string"
 	else
@@ -82,7 +85,7 @@ function eval_tester() (
 	else
 		args+=('--no-stdout')
 	fi
-	if test "$option_debug" = 'yes'; then
+	if test "$option_debug" = 'yes' -o "$using_tty_stderr_fallback" = 'yes'; then
 		: # allow stdderr to go directly to stderr
 	elif test "$option_stderr" != "$ignore_option"; then
 		args+=('--stderrvar=stderr')
@@ -122,6 +125,8 @@ function eval_tester() (
 	if test "$option_stderr" != "$ignore_option"; then
 		if test "$option_debug" = 'yes'; then
 			echo-style --notice='Unable to test stderr, as debugging.'
+		elif test "$using_tty_stderr_fallback" = 'yes'; then
+			echo-style --notice='Unable to test stderr, as it will be filled with TTY output.'
 		elif test "$option_stderr" != "$stderr"; then
 			fail='yes'
 			echo-style --red="Actual Stderr  !=  Expected Stderr" $'\n' \
