major bugfix to semaphores, fix various tests
`command-working`, `fetch`, `get-devices`, `service-helper`, `setup-util-node`:
- remove unneeded use of `__return $? ...`
- ensure safety of safe functions by ensuring `|| return` usage

`eval-helper`:
- minor improvements to the WIP help text

`eval-no-color`:
- add tests
- use `__do` now that semaphores are working properly

`eval-tester`:
- now that semaphores are fixed, fix waiting forever for the custom TTY file descriptor as there wasn't a close call

`is-digit`, `is-integer`:
- use new helpers in `bash.bash`

`is-owner`:
- fix tests, ensure fodder usage

`waiter`:
- remove `--message-target=...` as it was there for debugging and now that `eval-tester` supports TTY testing natively, it isn't needed

`errors.md`:
- update documentation for deprecation of `eval-capture`, and new `__try` and `__do` functions, and the need for `fodder_to_respect_exit_status`

`bash.bash`:
- add `__is_reference`, `__get_reference_name`, `__is_positive_integer`, `__is_integer`, `__is_digit`
- fix `__elevate` having an incorret sudo necessary detection call, and support detection with doas, so it is more in parity with `eval-helper`
- update `__open_fd` and `__close_fd` to support references and integers
- fix the semaphore functions not clearing corretly due to a non-conventional and incorrect `[[ $# -eq 0 ]] || return 0` line that needed to be `-ne`, so using an expnaded version for clarity
- simplify and support consistent ref handling for functions that use or modify arguments are are variable references

diff --git a/commands/eval-tester b/commands/eval-tester
--- a/commands/eval-tester
+++ b/commands/eval-tester
@@ -194,28 +194,27 @@ function eval_tester() (
 	fi
 
 	# file descriptor magic
-	local semaphores=() output_file semaphore_context="eval-tester.$RANDOM$RANDOM"
-	output_file="$(fs-temp --directory='eval-tester' --file)"
-	# tty
-	local terminal_output_file_for_comparison="$output_file.tty" terminal_output_target_original="$TERMINAL_OUTPUT_TARGET" terminal_output_semaphore
+	local terminal_output_target_original="$TERMINAL_OUTPUT_TARGET"
 	export TERMINAL_OUTPUT_TARGET
-	terminal_output_semaphore="$(__get_semaphore "$semaphore_context.tty")"
-	semaphores+=("$terminal_output_semaphore")
-	__open_fd terminal_output_fd '>' >(
+	local semaphores_status=() semaphore_context="eval-tester.$RANDOM$RANDOM" semaphore_tty_content semaphore_tty_status
+	semaphore_tty_content="$(__get_semaphore "$semaphore_context.tty.content")"
+	semaphore_tty_status="$(__get_semaphore "$semaphore_context.tty.status")"
+	semaphores_status+=("$semaphore_tty_status")
+	__open_fd '{terminal_output_fd}' '>' >(
 		set +e
-		__do --redirect-stdout="$terminal_output_target_original" -- tee -- "$terminal_output_file_for_comparison"
-		printf '%s' "$?" >"$terminal_output_semaphore"
+		__do --copy-stdout="$semaphore_tty_content" --redirect-stdout="$terminal_output_target_original" -- cat
+		printf '%s' "$?" >"$semaphore_tty_status"
 	)
 	TERMINAL_OUTPUT_TARGET="$terminal_output_fd"
 	# debug
 	if [[ $option_debug == 'yes' ]]; then
-		local debug_output_target_original="$BASH_XTRACEFD" debug_output_semaphore
-		debug_output_semaphore="$(__get_semaphore "$semaphore_context.debug")"
-		semaphores+=("$debug_output_semaphore")
-		__open_fd debug_output_fd '>' >(
+		local debug_output_target_original="$BASH_XTRACEFD" semaphore_debug_status
+		semaphore_debug_status="$(__get_semaphore "$semaphore_context.debug.status")"
+		semaphores_status+=("$semaphore_debug_status")
+		__open_fd '{debug_output_fd}' '>' >(
 			set +e
 			__do --redirect-stdout="$debug_output_target_original" -- cat
-			printf '%s' "$?" >"$debug_output_semaphore"
+			printf '%s' "$?" >"$semaphore_debug_status"
 		)
 		BASH_XTRACEFD="$debug_output_fd"
 	fi
@@ -231,9 +230,19 @@ function eval_tester() (
 	# __eval_helper --quiet="$option_quiet" --wrap <-- if this is done, element rendering, quite mode, and time duration can all be moved to eval-helper
 	__do "${args[@]}" -- "${option_cmd[@]}"
 	time="$(echo-math -- "$(__get_epoch_time) - $time")"
+	__close_fd '{terminal_output_fd}'
+	if [[ $option_debug == 'yes' ]]; then
+		__close_fd '{debug_output_fd}'
+		BASH_XTRACEFD="$debug_output_target_original"
+	fi
 	echo-style --/element+bold="$command_string"
-	__return $? -- __wait_for_and_return_semaphores "${semaphores[@]}"
-	actual_tty="$(<"$terminal_output_file_for_comparison")"
+	__wait_for_and_return_semaphores "${semaphores_status[@]}" || {
+		echo-style --error="Unable to retrieve semaphores, something went wrong with exit status: $?"
+		return 5 # EIO 5 Input/output error
+	}
+	__wait_for_semaphores "$semaphore_tty_content"
+	actual_tty="$(<"$semaphore_tty_content")"
+	rm -f -- "$semaphore_tty_content"
 
 	# determine if we fail, then we can decide what we are outputting
 	if [[ 
diff --git a/commands/get-devices b/commands/get-devices
--- a/commands/get-devices
+++ b/commands/get-devices
@@ -252,7 +252,7 @@ function get_devices() (
 	function __progress {
 		local count="$1" total="$2" comment="${3-}" message
 		message="Fetching device information: $((count * 100 / total))% [$count/$total] $comment"
-		__do --redirect-output=TTY -- printf $'\r'"%-${terminal_columns}s" "$message"
+		__do --redirect-output=TTY -- printf $'\r'"%-${terminal_columns}s" "$message" || return
 		# local progress_decimal progress_size progress_step i message_size progress_segment progress_bar='['
 		# message_size="${#message}"
 		# if [[ $message_segment -eq 0 ]]; then
@@ -301,7 +301,7 @@ function get_devices() (
 			fi
 			value="${matches["$key"]}"
 			if ! [[ $value =~ ^(yes|no)$ ]]; then
-				echo-error "Invalid boolean value for [$key]: [$value]"
+				echo-error "Invalid boolean value for [$key]: [$value]" || return
 				return 22 # EINVAL 22 Invalid argument
 			fi
 		done
@@ -321,23 +321,23 @@ function get_devices() (
 		# could be multiple keys per line
 		local key="$1" haystack="$2"
 		# echo-regexp -o --regexp="${key}=\"([^\"\n]+)" --replace='$1' -- "$haystack" || return
-		value="$(__get_substring_after_first "$haystack" "$key=" '')"
+		value="$(__get_substring_after_first "$haystack" "$key=" '')" || return
 		if [[ -z $value ]]; then
 			return 0
 		fi
 		while [[ $value =~ ^[\n\ \'\"] ]]; do
-			value="$(__get_substring "$value" 1)"
+			value="$(__get_substring "$value" 1)" || return
 		done
 		local remaining=''
 		while ! [[ $value =~ ^[\n\'\"] ]]; do
-			remaining+="$(__get_substring "$value" 0 1)"
-			value="$(__get_substring "$value" 1)"
+			remaining+="$(__get_substring "$value" 0 1)" || return
+			value="$(__get_substring "$value" 1)" || return
 		done
 		value="$remaining"
 		while [[ $value =~ \ $ ]]; do
-			value="$(__get_substring "$value" -1)"
+			value="$(__get_substring "$value" -1)" || return
 		done
-		__print_string "$value"
+		__print_string "$value" || return
 	}
 	# __get_property <key> <haystack>
 	function __get_property {
@@ -346,20 +346,20 @@ function get_devices() (
 		# rk="$(echo-escape-regexp -- "$key")"
 		# rv="$(echo-regexp -o --regexp="${rk}:[ '\"]+([^'\"\n]+)" --replace='$1' -- "$haystack" | echo-trim-each-line --stdin || :)"
 		[[ $haystack == *"$key: "* ]] || return 0
-		value="$(__get_substring_after_first "$haystack" "$key: " '')"
-		value="$(__get_substring_before_first "$value" $'\n' "$value")" # can be the last line
+		value="$(__get_substring_after_first "$haystack" "$key: " '')" || return
+		value="$(__get_substring_before_first "$value" $'\n' "$value")" || return # can be the last line
 		# trim
 		while [[ $value =~ ^[\ \'\"] ]]; do
-			value="$(__get_substring "$value" 1)"
+			value="$(__get_substring "$value" 1)" || return
 		done
 		while [[ $value =~ [\ \'\"]$ ]]; do
-			value="$(__get_substring "$value" -1)"
+			value="$(__get_substring "$value" -1)" || return
 		done
 		# if [[ $value != "$rv" ]]; then
 		# 	echo-error "[$value] != [$rv] with [$key] on [$haystack]"
 		# 	exit 9
 		# fi
-		__print_string "$value"
+		__print_string "$value" || return
 	}
 	# __get_size <size>
 	function __get_size {
@@ -426,22 +426,21 @@ function get_devices() (
 					return_values+=('')
 				fi
 			done
-			result_lines+=("$(__join '  ' -- "${values[@]}")")
-			return_lines+=("$(__join $'\t' -- "${return_values[@]}")")
+			result_lines+=("$(__join '  ' -- "${values[@]}")") || return
+			return_lines+=("$(__join $'\t' -- "${return_values[@]}")") || return
 		}
 		function __render_results {
 			local index
-			index="$(choose --index "${option_choose_args[@]}" -- "${result_lines[@]}")"
-			__return $? || return
+			index="$(choose --index "${option_choose_args[@]}" -- "${result_lines[@]}")" || return
 			if [[ -z $index ]]; then
-				__print_error "$option_missing"
+				echo-error "$option_missing" || return
 				return 1
 			fi
 			if [[ $index -lt 0 || $index -ge ${#return_lines[@]} ]]; then
-				echo-error "Invalid index [$index] for [0, ${#return_lines[@]}]"
+				echo-error "Invalid index [$index] for [0, ${#return_lines[@]}]" || return
 			fi
 			local return_line="${return_lines[$index]}"
-			__print_lines "$return_line"
+			__print_lines "$return_line" || return
 		}
 	elif [[ ${#option_return[@]} -ne 0 ]]; then
 		# return for a program
@@ -454,10 +453,10 @@ function get_devices() (
 					return_values+=('')
 				fi
 			done
-			result_lines+=("$(__join $'\t' -- "${return_values[@]}")")
+			result_lines+=("$(__join $'\t' -- "${return_values[@]}")") || return
 		}
 		function __render_results {
-			__print_lines "${result_lines[@]}"
+			__print_lines "${result_lines[@]}" || return
 		}
 	else
 		# render for the user
@@ -473,12 +472,12 @@ function get_devices() (
 					values+=('')
 				fi
 			done
-			result_lines+=("$(__join $'\t' -- "${values[@]}")")
+			result_lines+=("$(__join $'\t' -- "${values[@]}")") || return
 		}
 		function __render_results {
-			result_lines=("$(__join $'\t' -- "${option_display[@]}")" "${result_lines[@]}")
-			__join $'\n' -- "${result_lines[@]}" >"$devices_tsv_file"
-			csvlens -t "$devices_tsv_file"
+			result_lines=("$(__join $'\t' -- "${option_display[@]}")" "${result_lines[@]}") || return
+			__join $'\n' -- "${result_lines[@]}" >"$devices_tsv_file" || return
+			csvlens -t "$devices_tsv_file" || return
 
 			# https://github.com/alexhallam/tv?tab=readme-ov-file#tools-to-pair-with-tv
 			# brew install tidy-viewer
