huge WIP commit
- new `__do` and `__try`, instead of `eval_capture`
    - better coverage and tests, see `dorothy-internals`
    - more powerful API
- new `is-fs` helpers
- new `echo-wait` (maybe should rename to `echo-write`)
    - no longer needs sponge
    - more powerful API
    - moreutils as such is no longer a dorothy recommended dep
- auto-sudo escalation on nearly everything
    - new sudo/elevate/elevated args
- use FDs instead of device files where sensible to avoid linux divergence from macos
- ... todo

diff --git a/commands/eval-tester b/commands/eval-tester
--- a/commands/eval-tester
+++ b/commands/eval-tester
@@ -8,7 +8,7 @@ function eval_tester() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			USAGE:
 			eval-tester [...options] -- <command> [...args]
 
@@ -21,6 +21,7 @@ function eval_tester() (
 			--stderr=<expected stderr> (defaults to empty)
 			--ignore-stderr
 			--debug (implies --ignore-stderr)
+			    Will run the command with debugging enabled.
 			--bash=<bash path>
 			    Used to ensure that the command is invoked through a specific bash binary.
 		EOF
@@ -31,7 +32,7 @@ function eval_tester() (
 	}
 
 	# process
-	local item option_cmd=() ignore_option=$'\e' option_name='' option_bash='' option_status='0' option_stdout='' option_stderr='' option_debug='no'
+	local item option_cmd=() ignore_option=$'\e' option_name='' option_bash='' option_status='0' option_stdout='' option_stderr='' option_debug=''
 	while [[ $# -ne 0 ]]; do
 		item="$1"
 		shift
@@ -70,91 +71,103 @@ function eval_tester() (
 	# =====================================
 	# Action
 
+	local FAIL='no'
+	function __compare {
+		local name="$1" actual="$2" expected="$3" actual_escaped expected_escaped actual_file expected_file
+		if [[ $actual == "$expected" ]]; then
+			echo-style --success="actual $name  ==  expected $name"
+		else
+			FAIL='yes'
+			if [[ $actual =~ [[:cntrl:]] || $expected =~ [[:cntrl:]] ]]; then
+				actual_escaped="$(printf '%q' "$actual")"
+				expected_escaped="$(printf '%q' "$expected")"
+				echo-style --header3+red="<actual escaped $name>" --newline \
+					"$actual_escaped" --newline \
+					--header3+red="</actual escaped $name>" --newline \
+					--header3+red="<expected escaped $name>" --newline \
+					"$expected_escaped" --newline \
+					--header3+red="</expected escaped $name>"
+			else
+				echo-style --error="actual $name  !=  expected $name" --newline \
+					--header3+red="<actual $name>" --newline \
+					"$actual" --newline \
+					--header3+red="</actual $name>" --newline \
+					--header3+red="<expected $name>" --newline \
+					"$expected" --newline \
+					--header3+red="</expected $name>"
+			fi
+			actual_file="$(fs-temp --directory='eval-tester' --file)"
+			expected_file="$actual_file.expected"
+			actual_file="$actual_file.actual"
+			__print_string "$actual" >"$actual_file"
+			__print_string "$expected" >"$expected_file"
+			fs-diff --before="$expected_file" --after="$actual_file" || :
+		fi
+	}
+	function __dump {
+		local name="$1" actual="$2"
+		echo-style \
+			--header3="<actual $name>" --newline \
+			"$actual" --newline \
+			--header3="</actual $name>"
+		if [[ $actual =~ [[:cntrl:]] ]]; then
+			echo-style --header3="<actual escaped $name>" --newline \
+				"$(printf '%q' "$actual")" --newline \
+				--header3="</actual escaped $name>"
+		fi
+	}
+
 	# run the command
-	local args=() cmd_status stdout stderr cmd_string fail='no' title='' using_tty_stderr_fallback='no'
+	local args=() actual_exit_status actual_stdout actual_stderr cmd_string title='' can_test_stderr='yes'
 	cmd_string="$(echo-escape-command -- "${option_cmd[@]}")"
 	if [[ -n $option_name ]]; then
 		title="$option_name: $cmd_string"
 	else
 		title="$cmd_string"
 	fi
-	if ! get-terminal-tty-support --quiet; then
-		using_tty_stderr_fallback='yes'
+	if ! __has_tty_support; then
+		can_test_stderr='no'
 	fi
-	if [[ -n $option_status && $option_status != "$ignore_option" ]]; then
-		args+=('--statusvar=cmd_status')
-	fi
-	if [[ $option_stdout != "$ignore_option" ]]; then
-		args+=('--stdoutvar=stdout')
-	else
-		args+=('--no-stdout')
-	fi
-	if [[ $option_debug == 'yes' || $using_tty_stderr_fallback == 'yes' ]]; then
-		: # allow stderr to go directly to stderr
-	elif [[ $option_stderr != "$ignore_option" ]]; then
-		args+=('--stderrvar=stderr')
-	else
-		args+=('--no-stderr')
-	fi
+
+	# capture
+	args+=('--redirect-status={actual_exit_status}')
+	args+=('--redirect-stdout={actual_stdout}')
+	args+=('--redirect-stderr={actual_stderr}')
+
+	# run
 	echo-style --h3="$title"
-	eval_capture "${args[@]}" -- "${option_cmd[@]}"
+	__do "${args[@]}" -- "${option_cmd[@]}"
 
 	# check exit code
 	if [[ -n $option_status && $option_status != "$ignore_option" ]]; then
-		if [[ $option_status -ne $cmd_status ]]; then
-			fail='yes'
-			echo-style --red="Actual Exit Code [$cmd_status]  !=  Expected Exit Code [$option_status]"
+		if [[ $option_status -ne $actual_exit_status ]]; then
+			FAIL='yes'
+			echo-style --error="actual exit status [$actual_exit_status]  !=  expected exit status [$option_status]"
 		else
-			echo-style --green="Actual Exit Code [$cmd_status]  ==  Expected Exit Code [$option_status]"
+			echo-style --success="actual exit status [$actual_exit_status]  ==  expected exit status [$option_status]"
 		fi
 	fi
 
 	# check stdout
 	if [[ $option_stdout != "$ignore_option" ]]; then
-		if [[ $option_stdout != "$stdout" ]]; then
-			fail='yes'
-			echo-style --red="Actual Stdout  !=  Expected Stdout" $'\n' \
-				--header3='<actual stdout>' $'\n' \
-				"$stdout" $'\n' \
-				--header3='</actual stdout>' $'\n' \
-				--header3='<expected stdout>' $'\n' \
-				"$option_stdout" $'\n' \
-				--header3='</expected stdout>'
-			if [[ $option_stdout =~ [[:cntrl:]] || $stdout =~ [[:cntrl:]] ]]; then
-				echo-style --header3='<actual escaped stdout>' $'\n' \
-					"$(printf '%q' "$stdout")" $'\n' \
-					--header3='</actual escaped stdout>' $'\n' \
-					--header3='<expected escaped stdout>' $'\n' \
-					"$(printf '%q' "$option_stdout")" $'\n' \
-					--header3='</expected escaped stdout>'
-			fi
-		else
-			echo-style --green="Actual Stdout  ==  Expected Stdout"
-		fi
+		__compare 'stdout' "$actual_stdout" "$option_stdout"
+	elif [[ $FAIL == 'yes' ]]; then
+		__dump 'stdout' "$actual_stdout"
 	fi
 
-	# check stderr
+	# not ignored
 	if [[ $option_stderr != "$ignore_option" ]]; then
-		if [[ $option_debug == 'yes' ]]; then
-			echo-style --notice='Unable to test stderr, as debugging.'
-		elif [[ $using_tty_stderr_fallback == 'yes' ]]; then
-			echo-style --notice='Unable to test stderr, as it will be filled with TTY output.'
-		elif [[ $option_stderr != "$stderr" ]]; then
-			fail='yes'
-			echo-style --red="Actual Stderr  !=  Expected Stderr" $'\n' \
-				--header3='<actual stderr>' $'\n' \
-				"$stderr" $'\n' \
-				--header3='</actual stderr>' $'\n' \
-				--header3='<expected stderr>' $'\n' \
-				"$option_stderr" $'\n' \
-				--header3='</expected stderr>'
+		if [[ $can_test_stderr == 'yes' || $actual_stderr == "$option_stderr" ]]; then
+			__compare 'stderr' "$actual_stderr" "$option_stderr"
 		else
-			echo-style --green="Actual Stderr  ==  Expected Stderr"
+			echo-style --stderr --notice='Unable to validate stderr, as it will be filled with TTY output.'
 		fi
+	elif [[ $FAIL == 'yes' ]]; then
+		__dump 'stderr' "$actual_stderr"
 	fi
 
 	# pass or fail
-	if [[ $fail == 'yes' ]]; then
+	if [[ $FAIL == 'yes' ]]; then
 		echo-style --e3="$title" $'\n'
 		return 1
 	else
diff --git a/commands/fetch b/commands/fetch
--- a/commands/fetch
+++ b/commands/fetch
@@ -9,7 +9,7 @@ function fetch_() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Fetch the URL, using whichever tool is available on your system.
 
@@ -84,6 +84,7 @@ function fetch_() (
 	# =====================================
 	# Helpers
 
+	# consider converting this to a bash.bash helper called __convert_exit_status 141 -- ...
 	function __to_sigpipe {
 		local status="$?" item
 		for item in "$@"; do
@@ -96,7 +97,7 @@ function fetch_() (
 
 	function __log_failure {
 		local status="$?"
-		echo-style --error1='Failed to fetch the URL: ' --code-error1="$option_url" >/dev/stderr || return
+		echo-style --stderr --error1='Failed to fetch the URL: ' --code-error1="$option_url" || return
 		return "$status"
 	}
 
@@ -208,7 +209,7 @@ function fetch_() (
 		fetch_ok
 	elif [[ $option_ok == 'no' ]]; then
 		local ok_status
-		eval_capture --statusvar=ok_status -- fetch_ok
+		__try {ok_status} -- fetch_ok
 		[[ $ok_status -ne 0 ]]
 		return # explicit return with [[ required for bash v3
 	else
diff --git a/commands/git-helper b/commands/git-helper
--- a/commands/git-helper
+++ b/commands/git-helper
@@ -7,7 +7,7 @@ function git_helper() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Helpers for working with git repositories.
 
@@ -137,7 +137,7 @@ function git_helper() (
 	if [[ -z $option_path ]]; then
 		option_path="$(pwd)"
 	elif [[ ! -d $option_path ]]; then
-		echo-style --error1='Unable to use git-helper on a non-existent directory: ' --code-error1="$option_path" >/dev/stderr
+		echo-style --stderr --error1='Unable to use git-helper on a non-existent directory: ' --code-error1="$option_path"
 		return 2 # ENOENT 2 No such file or directory
 	fi
 
@@ -171,17 +171,17 @@ function git_helper() (
 	function verify_repository {
 		# verify repository
 		local git_status git_output
-		eval_capture --statusvar=git_status --outputvar=git_output -- git status
+		__do --redirect-status={git_status} --redirect-output={git_output} -- git status
 		if [[ $git_status -eq 128 ]]; then
-			echo-style --error1='The directory is not a git repository: ' --code-error1="$option_path" >/dev/stderr
+			echo-style --stderr --error1='The directory is not a git repository: ' --code-error1="$option_path"
 			if [[ -n $git_output ]]; then
-				__print_lines "$git_output" >/dev/stderr
+				__print_lines "$git_output" >&2
 			fi
 			return "$git_status" # makes more sense to continue inheriting the git exit status 128 than converting it to EFTYPE 79 Inappropriate file type or format
 		elif [[ $git_status -ne 0 ]]; then
-			echo-style --error1='Encountered an unknown git exit status ' --code-error1="$git_status" --error1=' when fetching the git status of the directory:' --code-error1="$option_path" >/dev/stderr
+			echo-style --stderr --error1='Encountered an unknown git exit status ' --code-error1="$git_status" --error1=' when fetching the git status of the directory:' --code-error1="$option_path"
 			if [[ -n $git_output ]]; then
-				__print_lines "$git_output" >/dev/stderr
+				__print_lines "$git_output" >&2
 			fi
 			return "$git_status"
 		fi
@@ -204,27 +204,27 @@ function git_helper() (
 		else
 			load_protocols
 			choose --required --no-confirm-solo \
-				--question'Which git protocol to use on the repository?' --question="$option_path" \
+				--question='Which git protocol to use on the repository?' --question="$option_path" \
 				--default="$protocol" -- "${protocols[@]}"
 		fi
 	}
 	function get_remotes {
 		# verify path, assumed verified for other actions
 		local remote_status remote_output
-		eval_capture --statusvar=remote_status --outputvar=remote_output -- git remote
+		__do --redirect-status={remote_status} --redirect-output={remote_output} -- git remote
 		if [[ $remote_status -eq 128 ]]; then
-			echo-style --error1='The directory is not a git repository: ' --code-error1="$option_path" >/dev/stderr
+			echo-style --stderr --error1='The directory is not a git repository: ' --code-error1="$option_path"
 			if [[ -n $remote_output ]]; then
-				__print_lines "$remote_output" >/dev/stderr
+				__print_lines "$remote_output" >&2
 			fi
 			return "$status" # makes more sense to continue inheriting the git exit status 128 than converting it to EFTYPE 79 Inappropriate file type or format
 		elif [[ -z $remote_output ]]; then
-			echo-style --error1='The directory is a git repository without any remotes: ' --code-error1="$option_path" >/dev/stderr
+			echo-style --stderr --error1='The directory is a git repository without any remotes: ' --code-error1="$option_path"
 			return 91 # ENOMSG 91 No message of desired type
 		elif [[ $remote_status -ne 0 ]]; then
-			echo-style --error1='Encountered an unknown git exit status ' --code-error1="$remote_status" --error1=' when fetching the remotes of the directory:' --code-error1="$option_path" >/dev/stderr
+			echo-style --stderr --error1='Encountered an unknown git exit status ' --code-error1="$remote_status" --error1=' when fetching the remotes of the directory:' --code-error1="$option_path"
 			if [[ -n $remote_output ]]; then
-				__print_lines "$remote_output" >/dev/stderr
+				__print_lines "$remote_output" >&2
 			fi
 			return "$remote_status"
 		else
@@ -517,7 +517,7 @@ function git_helper() (
 				__print_lines "$GIT_DEFAULT_BRANCH"
 				return 0
 			else
-				cat <<-EOF >/dev/stderr
+				cat <<-EOF >&2
 					No branches exist locally or remotely and [GIT_DEFAULT_BRANCH] is not specified, so no default branch was created.
 
 					Inside your [git.bash] configuration file, set [GIT_DEFAULT_BRANCH] to your desired default branch, then try again.
@@ -525,7 +525,7 @@ function git_helper() (
 				return 1
 			fi
 		else
-			cat <<-EOF >/dev/stderr
+			cat <<-EOF >&2
 				No default branch exists within the available branches:
 				$(git branch -a)
 
@@ -704,10 +704,10 @@ function git_helper() (
 		# write to stderr so that [git_update] returns only [failure|current|updated]
 		# @todo style this with eval-helper pending/success/failure
 		local update_status
-		eval_capture --statusvar=update_status --outputpipe=/dev/stderr -- do_update
+		__do --redirect-status={update_status} --redirect-stdout=stderr -- do_update
 		if [[ $update_status -ne 0 ]]; then
 			# update failed
-			echo-style --error1='git failed with exit status: ' --code-error1="$update_status" >/dev/stderr
+			echo-style --stderr --error1='git failed with exit status: ' --code-error1="$update_status"
 			__print_lines 'failure'
 			return 1
 		elif grep --quiet --fixed-strings --regexp='Already' -- "$PULL_OUTPUT_FILE"; then
@@ -721,13 +721,11 @@ function git_helper() (
 
 	function git_umt {
 		# https://serverfault.com/a/1031956
-		# git ls-tree -r --name-only HEAD -z | TZ=UTC xargs -0n1 -I_ git --no-pager log -1 --date=iso-local --format="%ad _" -- _
-		# git ls-tree -r --name-only HEAD -z | TZ=UTC xargs -0n1 git --no-pager log -1 --date=iso-local --name-only -z --format='format:%ad' | perl -npe "INIT {\$/ = \"\\0\"} s@^(.*? .*?) .*?\n(.*)\$@\$date=\$1; \$name=\$2; \$name =~ s/'/'\"'\"'/sg; \"TZ=UTC touch -m --date '\$date' '\$name';\n\"@se" | bash
-		# git ls-tree -r --name-only HEAD -z | TZ=UTC xargs -0n1 -I_ git --no-pager log -1 --date=iso-local --format='%ad _' -- _ | echo-wait | echo-regexp -gonm '^(.+?) \+0000 (.+)$' "TZ=UTC touch -md '\$1' '\$2'" | bash
-		# ^ these all produce: xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
+		# ^ all suggestions there have shortcomings, such as producing:
+		# xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
 		# this solves it:
 		# git ls-tree -r --name-only HEAD -z | TZ=UTC xargs -0 -I_ git --no-pager log -1 --date=iso-local --format='%ad _' -- _ | echo-wait | echo-regexp -gonm '^(.+?) \+0000 (.+)$' "TZ=UTC touch -md '\$1' '\$2'" | bash
-		# however this is far easier, more understandable, just as quick, and supports paths with % and quotes:
+		# however our below implementation is far easier, more understandable, just as quick, and supports paths with % and quotes:
 		local subfiles=() subfile timestamp
 		mapfile -t subfiles < <(git ls-tree -r --name-only HEAD)
 		for subfile in "${subfiles[@]}"; do
diff --git a/commands/is-not-symlink b/commands/is-not-symlink
--- a/commands/is-not-symlink
+++ b/commands/is-not-symlink
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
 
 function is_not_symlink_test() (
-	source "$DOROTHY/sources/tests.bash"
+	source "$DOROTHY/sources/is-fs-tests.bash"
 	echo-style --h1="TEST: $0"
 
 	local root command='is-not-symlink'
-	root="$(fs_tests__prep "$command")"
+	root="$(is_fs_tests__prep "$command")"
 
 	eval-tester --name='no args' --status=22 --ignore-stderr \
 		-- "$command" --
@@ -99,7 +99,7 @@ function is_not_symlink_test() (
 		79 "$root/symlinks/unwritable-filled-dir--filled-subfile"
 		79 "$root/symlinks/unwritable-filled-file"
 	)
-	fs_tests__tuples --group='test no escalation' "$command" --no-sudo -- "${tuples[@]}"
+	is_fs_tests__tuples --group='test no escalation' "$command" --no-sudo -- "${tuples[@]}"
 
 	# test default escalation
 	tuples=(
@@ -120,7 +120,7 @@ function is_not_symlink_test() (
 		79 "$root/symlinks/unexecutable-filled-dir--filled-subdir--empty-subdir"
 		79 "$root/symlinks/unexecutable-filled-dir--filled-subfile"
 	)
-	fs_tests__tuples --group='test default escalation' "$command" -- "${tuples[@]}"
+	is_fs_tests__tuples --group='test default escalation' "$command" -- "${tuples[@]}"
 
 	# test with escalation
 	tuples=(
@@ -141,7 +141,7 @@ function is_not_symlink_test() (
 		79 "$root/symlinks/unexecutable-filled-dir--filled-subdir--empty-subdir"
 		79 "$root/symlinks/unexecutable-filled-dir--filled-subfile"
 	)
-	fs_tests__tuples --group='test with escalation' "$command" --sudo -- "${tuples[@]}"
+	is_fs_tests__tuples --group='test with escalation' "$command" --sudo -- "${tuples[@]}"
 
 	# break the symlinks
 	sudo-helper -- rm -rf -- "$root/targets"
@@ -186,19 +186,19 @@ function is_not_symlink_test() (
 		79 "$root/symlinks/unwritable-filled-dir--filled-subfile"
 		79 "$root/symlinks/unwritable-filled-file"
 	)
-	fs_tests__tuples --group='test broken symlinks' "$command" -- "${tuples[@]}"
+	is_fs_tests__tuples --group='test broken symlinks' "$command" -- "${tuples[@]}"
 
 	echo-style --g1="TEST: $0"
 	return 0
 )
 function is_not_symlink() (
-	source "$DOROTHY/sources/bash.bash"
+	source "$DOROTHY/sources/is-fs.bash"
 
 	# =====================================
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Check if all <path>s are not a symlink, broken or otherwise.
 			Companion to [is-broken-symlink], [is-symlink].
@@ -207,17 +207,12 @@ function is_not_symlink() (
 			is-not-symlink [...options] [--] ...<path>
 
 			OPTIONS:
-			--sudo=<sudo>
-			    Defaults to [13], escalating to root if permission would otherwise be denied.
-			--user=<user>
-			--group=<group>
-			    Forwarded to [sudo-helper].
+			$(is_fs_options '13')
 
 			RETURNS:
-			[0] if all <path>s existed and were not a symlink (broken or otherwise)
-			[2] if a <path> was not found
-			[13] if a <path> was not accessible: unless [--no-sudo] was provided a sudo request will be made to prevent this failure.
-			[22] if empty arguments are provided
+			[0] if all <path>s were present and were not a symlink (broken or otherwise)
+			[2] if a <path> was missing
+			[13] if a <path> was not accessible
 			[79] if a <path> was a symlink (broken or otherwise)
 		EOF
 		if [[ $# -ne 0 ]]; then
@@ -227,37 +222,26 @@ function is_not_symlink() (
 	}
 
 	# process
-	local item option_inputs=() option_sudo='13' option_user='' option_group=''
-	while [[ $# -ne 0 ]]; do
-		item="$1"
-		shift
-		case "$item" in
-		'--help' | '-h') help ;;
-		'--no-sudo'* | '--sudo'*)
-			option_sudo="$(get-flag-value --affirmative --fallback-on-empty --fallback="$option_sudo" -- "$item")"
-			;;
-		'--user='*) option_user="${item#*=}" ;;
-		'--group='*) option_group="${item#*=}" ;;
-		'--')
-			option_inputs+=("$@")
-			shift $#
-			break
-			;;
-		'--'*) help "An unrecognised flag was provided: $item" ;;
-		*) option_inputs+=("$item") ;;
-		esac
-	done
+	local item option_inputs=() option_quiet='' option_elevated='' option_elevate='13' option_user='' option_group='' option_reason=''
+	is_fs_args "$@"
 
-	# verify
-	if [[ ${#option_inputs[@]} -eq 0 ]]; then
-		help 'No <input>s provided.'
+	# invoke
+	local fs_status fs_failed_path
+	is_fs_invoke 'is-not-symlink.bash'
+
+	# if verbose and failure, output contextual failure
+	if [[ $option_quiet == 'no' && $fs_status -ne 0 ]]; then
+		case "$fs_status" in
+		2) echo-style --stderr --error1='The path was missing: ' --code-error1="$fs_failed_path" ;;
+		13) echo-style --stderr --error1='The path was not accessible: ' --code-error1="$fs_failed_path" ;;
+		22) echo-style --stderr --error1='The path was not a valid argument: ' --code-error1="$fs_failed_path" ;;
+		79) echo-style --stderr --error1='The path was a symlink (broken or otherwise): ' --code-error1="$fs_failed_path" ;;
+		*) is_fs_unknown_error ;;
+		esac
 	fi
 
-	# =====================================
-	# Action
-
-	sudo-helper --inherit --sudo="$option_sudo" --user="$option_user" --group="$option_group" -- is-not-symlink.bash -- "${option_inputs[@]}"
-	return
+	# done
+	return "$fs_status"
 )
 
 # fire if invoked standalone
diff --git a/commands/open-app b/commands/open-app
--- a/commands/open-app
+++ b/commands/open-app
@@ -7,7 +7,7 @@ function open_app() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Open the specified GUI application.
 
@@ -62,7 +62,7 @@ function open_app() (
 	if [[ -n $app ]]; then
 		open -a "$app" "${option_args[@]}"
 	else
-		echo-style --error="Unable to find the application: $option_name" >/dev/stderr
+		echo-style --stderr --error="Unable to find the application: $option_name"
 		return 2 # ENOENT 2 No such file or directory
 	fi
 )
diff --git a/commands/setup-dns b/commands/setup-dns
--- a/commands/setup-dns
+++ b/commands/setup-dns
@@ -21,20 +21,20 @@ function setup_dns() (
 
 	# check for support
 	if is-wsl; then
-		echo-style --code-error1="$0" --error1=' is not applicable on WSL.' >/dev/stderr
+		echo-style --stderr --code-error1="$0" --error1=' is not applicable on WSL.'
 		return 19 # ENODEV 19 Operation not supported by device
 	elif is-mac; then
 		if __command_missing -- networksetup; then
-			echo-style --code-error1="$0" --error1=' is not applicable on this macOS environment, as ' --code-error1='networksetup' --error1=' was not available.' >/dev/stderr
+			echo-style --stderr --code-error1="$0" --error1=' is not applicable on this macOS environment, as ' --code-error1='networksetup' --error1=' was not available.'
 			return 19 # ENODEV 19 Operation not supported by device
 		fi
 	elif is-ubuntu; then
 		if __command_missing -- systemctl resolvectl; then
-			echo-style --code-error1="$0" --error1=' is not applicable on this Linux environment, as ' --code-error1='systemctl' ' and/or ' --code-error1='resolvectl' --error1=' were not available.' >/dev/stderr
+			echo-style --stderr --code-error1="$0" --error1=' is not applicable on this Linux environment, as ' --code-error1='systemctl' ' and/or ' --code-error1='resolvectl' --error1=' were not available.'
 			return 19 # ENODEV 19 Operation not supported by device
 		fi
 	else
-		echo-style --code-error1="$0" --error1=' is not applicable on this unknown system.' >/dev/stderr
+		echo-style --stderr --code-error1="$0" --error1=' is not applicable on this unknown system.'
 		return 19 # ENODEV 19 Operation not supported by device
 	fi
 
@@ -55,7 +55,7 @@ function setup_dns() (
 			fi
 		done
 		if [[ ${#missing_env_vars[@]} -ne 0 ]]; then
-			echo-style --error1='Missing these required environment variables: ' --code-error1="${missing_env_vars[*]}" >/dev/stderr
+			echo-style --stderr --error1='Missing these required environment variables: ' --code-error1="${missing_env_vars[*]}"
 			return 2 # ENOENT 2 No such file or directory
 		fi
 	}
@@ -167,8 +167,9 @@ function setup_dns() (
 		local id="$1" bin="$2" exists
 		exists="$(type -P "$id" || :)"
 		if [[ -n $exists && $exists != "$bin" ]]; then
-			echo-style --error1='The DNS service ' --code-error1="$id" ' has a non-standard installation at: ' --code-error1="$exists" $'\n' \
-				--error1='Remove it and try again...' >/dev/stderr
+			echo-style --stderr \
+				--error1='The DNS service ' --code-error1="$id" ' has a non-standard installation at: ' --code-error1="$exists" --newline \
+				--error1='Remove it and try again...'
 			return 75 # EPROGMISMATCH 75 Program version wrong
 		fi
 	}
@@ -176,7 +177,7 @@ function setup_dns() (
 	function __fail_if_dns_service_is_not_installed {
 		local id="$1" bin="$2"
 		if [[ ! -x $bin ]]; then
-			echo-style --error1='The DNS service ' --code-error1="$id" ' failed to install to: ' --code-error1="$bin" >/dev/stderr
+			echo-style --stderr --error1='The DNS service ' --code-error1="$id" ' failed to install to: ' --code-error1="$bin"
 			return 9 # EBADF 9 Bad file descriptor
 		fi
 	}
@@ -479,7 +480,7 @@ function setup_dns() (
 			# apply specific config
 			if [[ $action == 'enable' ]]; then
 				# using systemd, the initial lines are for ping/nslookup/etc, the [Resolve] lines are for systemd-resolve
-				sudo-helper -- tee -- /etc/resolv.conf <<-EOF
+				echo-wait -- /etc/resolv.conf <<-EOF
 					nameserver 127.0.0.53
 					options edns0 trust-ad
 					search .
@@ -492,7 +493,7 @@ function setup_dns() (
 				EOF
 			else
 				# use custom service
-				sudo-helper -- tee -- /etc/resolv.conf <<-EOF
+				echo-wait -- /etc/resolv.conf <<-EOF
 					nameserver ${servers[0]}
 					options edns0 trust-ad
 				EOF
@@ -509,8 +510,8 @@ function setup_dns() (
 
 			# apply the changes to their interfaces
 			mapfile -t interfaces < <(network-interface list | echo-values --stdin)
-			if test "${#interfaces[@]}" -eq 0; then
-				echo-style --error1='No interfaces were found.' >/dev/stderr
+			if [[ ${#interfaces[@]} -eq 0 ]]; then
+				echo-style --stderr --error1='No interfaces were found.'
 				return 1
 			fi
 			local default_route
@@ -651,7 +652,7 @@ function setup_dns() (
 
 	function die_incompatible_dns_service {
 		local service_title="${item#*=}"
-		echo-style --error1='This platform architecture ' --code-error1="$arch" --error1=' does not yet support: ' --code-error1="$service_title" >/dev/stderr
+		echo-style --stderr --error1='This platform architecture ' --code-error1="$arch" --error1=' does not yet support: ' --code-error1="$service_title"
 		return 19 # ENODEV 19 Operation not supported by device
 	}
 
@@ -944,7 +945,7 @@ function setup_dns() (
 				# create service with custom upstreams
 				# <string>--address</string>
 				# <string>0.0.0.0</string>
-				sudo-helper -- tee -- "$cloudflared__proxy_service_file" >/dev/null <<EOF
+				echo-wait -- "$cloudflared__proxy_service_file" <<EOF
 <?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
@@ -980,7 +981,7 @@ EOF
 				done
 
 				# create service with custom upstreams
-				sudo-helper -- tee -- "$cloudflared__proxy_service_file" >/dev/null <<-EOF
+				echo-wait -- "$cloudflared__proxy_service_file" <<-EOF
 					[Unit]
 					Description=${cloudflared__proxy_service_id}
 					Wants=network-online.target nss-lookup.target
@@ -1036,12 +1037,12 @@ EOF
 					fi
 				done
 				if [[ $found == 'no' ]]; then
-					echo-style --error1='Invalid dnscrypt-proxy configuration, the dnscrypt-name ' --code-error1="$a" --error1=' is invalid. Find a list of valid names at: ' --code-error1="$dnscrypt_names_file" >/dev/stderr
+					echo-style --stderr --error1='Invalid dnscrypt-proxy configuration, the dnscrypt-name ' --code-error1="$a" --error1=' is invalid. Find a list of valid names at: ' --code-error1="$dnscrypt_names_file"
 					return 3 # ESRCH 3 No such process
 				fi
 			done
 		elif [[ -n ${provider-} ]]; then
-			echo-style --error1='Invalid dnscrypt-proxy configuration, no dnscrypt-names were provided for the provider ' --code-error1="$provider" >/dev/stderr
+			echo-style --stderr --error1='Invalid dnscrypt-proxy configuration, no dnscrypt-names were provided for the provider ' --code-error1="$provider"
 			return 6 # ENXIO 6 Device not configured
 		fi
 
@@ -1174,9 +1175,10 @@ EOF
 		if [[ ! -s $dnscrypt_proxy__conf_file ]]; then
 			# then give up, as the internet is disabled in this mode
 			# as we deactivated the prior service
-			echo-style --error1='Missing configuration file: ' --code-error1="$dnscrypt_proxy__conf_file" >/dev/stderr
-			echo-style --notice1='You should attempt reinstallation then try again.' >/dev/stderr
-			echo-style --e2="$action_title $dnscrypt_proxy__title"
+			echo-style --stderr \
+				--error1='Missing configuration file: ' --code-error1="$dnscrypt_proxy__conf_file" --newline \
+				--notice1='You should attempt reinstallation then try again.' --newline \
+				--stdout --e2="$action_title $dnscrypt_proxy__title"
 		fi
 
 		# stop the service if it is installed, before config update
@@ -1229,7 +1231,7 @@ EOF
 		)
 		for fn in "${fns[@]}"; do
 			command -v "$fn" >/dev/null || {
-				echo-style --error1='The DNS service ' --code-error1="$fn_id" --error1=' is missing its helper: ' --code-error1="$fn" >/dev/stderr
+				echo-style --stderr --error1='The DNS service ' --code-error1="$fn_id" --error1=' is missing its helper: ' --code-error1="$fn"
 				return 1
 			}
 		done
@@ -1260,7 +1262,7 @@ EOF
 	# @todo move this later so that it also outputs providers
 	function help {
 		fetch_available_and_installed_services
-		cat <<-EOF >/dev/stderr
+		cat <<-EOF >&2
 			ABOUT:
 			Setup the DNS service for your system.
 
@@ -1734,15 +1736,15 @@ EOF
 	# verify that installed install and enable options are not used together
 	if [[ -n $option_installed ]]; then
 		if [[ -n $option_install || -n $option_enable ]]; then
-			help '--installed, --install, and --enable are mutually exclusive'
+			help --='--installed, --install, and --enable are mutually exclusive'
 		fi
 	elif [[ -n $option_install ]]; then
 		if [[ -n $option_installed || -n $option_enable ]]; then
-			help '--installed, --install, and --enable are mutually exclusive'
+			help --='--installed, --install, and --enable are mutually exclusive'
 		fi
 	elif [[ -n $option_enable ]]; then
 		if [[ -n $option_installed || -n $option_install ]]; then
-			help '--installed, --install, and --enable are mutually exclusive'
+			help --='--installed, --install, and --enable are mutually exclusive'
 		fi
 	fi
 
