*: use `TMPDIR` instead of `XDG_CACHE_HOME`
- fs-temp, *:
    - use `TMPDIR` instead of `XDG_CACHE_HOME` by default, to prevent SSD wear
- fs-temp:
    - support other types as well
    - return root if no `--file` nor `--directory`
    - no longer begin with `dorothy` as initial directory
- `bash.bash:__print_help`
    - support error as arguments

diff --git a/commands/eval-helper b/commands/eval-helper
--- a/commands/eval-helper
+++ b/commands/eval-helper
@@ -75,7 +75,7 @@ function eval_helper_test() (
 	# 	eval-helper --no-color --quiet --wrap --pending=my-pending --failure=my-failure --success=my-success --persist=STDOUT -- \
 	# 	waiter --timeout=0 --stdout=my-stdout --stderr=my-stderr
 
-	# for some reason, if `get-terminal-lines-and-columns` or `get-terminal-lines-and-columns.bash` are sent via `eval-helper` with `--clear` or `--alternative` then fetching the lines fails, which then causes `eval-helper` to always have auto always revert to direct mode as terminal_lines and terminal_columsn will be empty:
+	# for some reason, if `get-terminal-lines-and-columns` or `get-terminal-lines-and-columns.bash` are sent via `eval-helper` with `--clear` or `--alternative` then fetching the lines fails, which then causes `eval-helper` to always have auto always revert to direct mode as terminal_lines and terminal_columns will be empty:
 	# eval-helper --wrap --mode=alternative -- get-terminal-lines-and-columns.bash
 	# eval-helper --wrap --mode=clear -- get-terminal-lines-and-columns.bash
 	# eval-tester -- get-terminal-lines-and-columns.bash
@@ -90,11 +90,11 @@ function eval_helper() ( # to use this as a function, it needs to change from a 
 	# Arguments
 
 	function help {
-		__print_help <<-EOF || return
+		__print_help "$@" <<-EOF || return
 			ABOUT:
 			Execute a command with conveniences:
 			- Configure to wrap the command with pending, success, and failure messages; including expanded details on failures.
-			- Configure to hide and/or obsure the command output, ensuring it occurs within specified dimensions, including support for shapeshifting commands, alternative screen buffers, and cycling of output within a revolving door; with expansions on failures.
+			- Configure to hide and/or obscure the command output, ensuring it occurs within specified dimensions, including support for shapeshifting commands, alternative screen buffers, and cycling of output within a revolving door; with expansions on failures.
 			- Configure to elevate privileges of the command, with confirmation and reasoning of why and what is being elevated. Supporting \`sudo\`, \`doas\`, and \`cron\` environments.
 			- Configure to retry the command.
 
@@ -156,7 +156,7 @@ function eval_helper() ( # to use this as a function, it needs to change from a 
 			--[no-]alternative-screen-buffer | --mode=alternative
 			    If enabled, we will wrap the command output and alterations within an alternative screen buffer.
 			--[no-]clear | --mode=clear
-			    If enabled, we will send the terminal output to \`echo-revolving-door\` to ensure it operates within our desired dimensions and clears according to our desired messaging confuguration. Shapeshifting ANSI Escape Codes will be omitted visually. Visually STDOUT and STDERR are merged into STDERR, so alterations are not captured: use <persist> to capture/persist the original output upon completion.
+			    If enabled, we will send the terminal output to \`echo-revolving-door\` to ensure it operates within our desired dimensions and clears according to our desired messaging configuration. Shapeshifting ANSI Escape Codes will be omitted visually. Visually STDOUT and STDERR are merged into STDERR, so alterations are not captured: use <persist> to capture/persist the original output upon completion.
 			--mode=<mode:shapeshifter|alternative|clear|direct|auto>
 			    If <auto>, which is the default, it will be configured to <shapeshifter> for known shapeshifters (e.g. \`vim\`), to <alternative> for possible shapeshifters (e.g. \`ssh\`, \`sudo\`, \`doas\`), to <clear> if <quiet> or likewise, otherwise it will be <direct>. If <direct>, the command will execute directly.
 
@@ -196,9 +196,6 @@ function eval_helper() ( # to use this as a function, it needs to change from a 
 			--invalidate-elevation
 			    If specified, any active elevation will be invalidated. All other arguments are discarded.
 		EOF
-		if [[ $# -ne 0 ]]; then
-			__print_error "$@" || return
-		fi
 		return 22 # EINVAL 22 Invalid argument
 	}
 
