fix rate limit failure on empty auth token
/close #219

changes:

- down: fix bad bearer token check for wget
- fetch: fix empty tokens still being added, fix bad bearer token check for wget and curl
- service-helper: fix likewise but unrelated bad test

diff --git a/commands/fetch b/commands/fetch
--- a/commands/fetch
+++ b/commands/fetch
@@ -42,8 +42,18 @@ function fetch_() (
 		case "$item" in
 		'--help' | '-h') help ;;
 		'--auth-token='*) option_auth_token="${item#*=}" ;;
-		'--bot-token='*) option_auth_token="Bot ${item#*=}" ;;
-		'--bearer-token='*) option_auth_token="Bearer ${item#*=}" ;;
+		'--bot-token='*)
+			option_auth_token="${item#*=}"
+			if test -n "$option_auth_token"; then
+				option_auth_token="Bot $option_auth_token"
+			fi
+			;;
+		'--bearer-token='*)
+			option_auth_token="${item#*=}"
+			if test -n "$option_auth_token"; then
+				option_auth_token="Bearer $option_auth_token"
+			fi
+			;;
 		'--content-type='*) option_content_type="${item#*=}" ;;
 		'--json') option_content_type='application/json' ;;
 		'--body='*) option_body="${item#*=}" ;;
@@ -74,7 +84,7 @@ function fetch_() (
 
 	function __log_failure {
 		local status="$?"
-		echo-style --error="Failed to fetch the URL:" ' ' --code="$option_url" >/dev/stderr || return
+		echo-style --error='Failed to fetch the URL:' ' ' --code="$option_url" >/dev/stderr || return
 		return "$status"
 	}
 
@@ -89,7 +99,7 @@ function fetch_() (
 	# -S, --show-error                  When used with -s, --silent, it makes curl show an error message if it fails.
 	function do_curl {
 		local options=("$@")
-		if test "$option_auth_token"; then
+		if test -n "$option_auth_token"; then
 			options+=(
 				'--header'
 				"Authorization: $option_auth_token"
@@ -112,7 +122,7 @@ function fetch_() (
 	}
 	function do_wget {
 		local options=("$@")
-		if test "$option_auth_token"; then
+		if test -n "$option_auth_token"; then
 			options+=(
 				"--header=Authorization: $option_auth_token"
 			)
