WIP: reworked shell install, config, and select
dorothy:
- move shell configuration entirely to `setup-shell`, which is the correct place for it
    - this is the correct location for it, and allows shell installations and uninstallations to correct configure, deconfigure, select, and deselect themselves
- extract `fs-relocate` into its own command

echo-file, echo-wait:
- WIP

fetch:
- noramlise `wget` and `curl` variants of SIGPIPE failures into SIGPIPE failures, so the caller can act accordingly

setup-dns:
- fix help text

setup-environment-commands:
- consolidate prefix directory handling with new `add_prefix_dir` helper, which now handles all the complexities of such in a simpler and more robust way
- add `XDG_PREFIX` var
- the combination of changes here now enables building on macos without `setup-util-devel` needed

setup-git:
- add `--[no-]fallback`, `--no-extras`, and `--slim` support to support (de|re)configuration if uninstalling homebrew

setup-mac-brew:
- fix `setup-util-brew --uninstall` flow, as it may uninstall our current shell, so we should expect a crash and not do more stuff after the uninstall

setup-shell:
- handle installation, uninstallation, configuration, deconfiguration, selection and unselection, rather than just install/configure
- this prevents issues when uninstalling dorothy, uninstalling homebrew, and uninstalling a specific shell
- this guides the user through the installation process, for those who are YOLO no-RTFM users, or beginners who did RTFM but didn't understand any of it

setup-util:
- add `--configure` action to be a no-op on `--check` utilities
- rename `--check=<cmd>` to `--checker=<cmd>` such that `--[no-]check` is a boolean that makes it easier to handle, and prevents conflicts when toggling
- redid and simplied relevance algorithm
- improved verbosity when building download deps, such that debugging is easier

setup-util-bash:
- `setup-environment-commands` has been updated to support building on macos without `setup-util-devel`
- install to / uninstall from `XDG_PREFIX` when building
- simpler prompt for changing login shell if outdated bash
- update the build flags to include what bash reocmmends

setup-util-brew:
- fix uninstallation, fix `setup-dns` deconfiguration, fix `setup-git` deconfiguration

setup-util-(gawk|gsed):
- fix building, based on learnings from setup-util-bash

setup-util-nu:
- configure on other invokations than just install, but correctly document configuration can only occur if nu exists

setup-util-zsh:
- use the new `fs-relocate` command to ensure zsh configuration is in the correct location

bash.bash:
- add new helpers `__ignore_exit_status` and `__ignore_sigpipe`

stdinargs.bash:
- fix oudated comments explaining sigpipe and timeout handling

todo:
- [ ] echo-file, echo-wait reworking
- [ ] config-helper auto-escalation
- [ ] setup-util-$shell: call `setup-shell` when uninstalling, or on installation if non-quiet
- [ ] setup-util-brew: uninstall: the login shell handling in this is added, but is nonsensical, fix it to run `setup-shell --no-brew`
- [ ] ensure `setup-util "$@" --check` is updated for the new syntax

diff --git a/commands/fetch b/commands/fetch
--- a/commands/fetch
+++ b/commands/fetch
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+# @todo support --tool=<curl|wget|?>
+
 function fetch_() (
 	source "$DOROTHY/sources/bash.bash"
 
@@ -82,6 +84,16 @@ function fetch_() (
 	# =====================================
 	# Helpers
 
+	function __to_sigpipe {
+		local status="$?" item
+		for item in "$@"; do
+			if [[ $status -eq $item ]]; then
+				return 141
+			fi
+		done
+		return "$status"
+	}
+
 	function __log_failure {
 		local status="$?"
 		echo-style --error1='Failed to fetch the URL: ' --code-error1="$option_url" >/dev/stderr || return
@@ -117,10 +129,17 @@ function fetch_() (
 				"$option_body"
 			)
 		fi
-		# use echo-wait to fix [curl: (23) Failure writing output to destination] when piping to ripgrep
-		{
-			curl "${options[@]}" "$option_url" || __log_failure
-		} | echo-wait
+
+		# > set -o pipefail
+		# > curl --silent --show-error 'https://www.google.com' | :
+		# curl: Failed writing body
+		# [23]
+		#
+		# > set -o pipefail
+		# > curl --silent --show-error --write-out '%{http_code}' 'https://www.google.com' | :
+		# curl: (56) Failure writing output to destination, passed 1378 returned 0
+		# [56]
+		{ curl "${options[@]}" "$option_url" || __to_sigpipe 23 56; } || __log_failure
 	}
 	function do_wget {
 		local options=("$@")
@@ -129,7 +148,11 @@ function fetch_() (
 				"--header=Authorization: $option_auth_token"
 			)
 		fi
-		wget "${options[@]}" "$option_url" || __log_failure
+		# > set -o pipefail
+		# > wget -nv -O- 'https://www.google.com' | :te to ‘-’ (Success).
+		# Cannot write to ‘-’ (Success).
+		# [3]
+		{ wget "${options[@]}" "$option_url" || __to_sigpipe 3; } || __log_failure
 	}
 
 	function fetch_status {
diff --git a/commands/setup-git b/commands/setup-git
--- a/commands/setup-git
+++ b/commands/setup-git
@@ -30,6 +30,12 @@ function setup_git() (
 			OPTIONS:
 			--configure
 			    Whether to prompt, confirm, or save configuration changes.
+			--no-fallback
+			    Disables installation of fallbacks to install extras.
+			--no-extras
+			    Disables installation of extras, such as gpg etc.
+			--slim
+			    Disables configuration, fallbacks, and extras.
 		EOF
 		if [[ $# -ne 0 ]]; then
 			echo-error "$@"
@@ -38,7 +44,7 @@ function setup_git() (
 	}
 
 	# process
-	local item option_configure=''
+	local item option_configure='' option_fallback='' option_extras=''
 	while [[ $# -ne 0 ]]; do
 		item="$1"
 		shift
@@ -55,6 +61,17 @@ function setup_git() (
 		'--no-configure'* | '--configure'*)
 			option_configure="$(get-flag-value --affirmative --fallback="$option_configure" -- "$item")"
 			;;
+		'--no-fallback'* | '--fallback'*)
+			option_fallback="$(get-flag-value --affirmative --fallback="$option_fallback" -- "$item")"
+			;;
+		'--no-extras'* | '--extras'*)
+			option_extras="$(get-flag-value --affirmative --fallback="$option_extras" -- "$item")"
+			;;
+		'--slim')
+			option_configure='no'
+			option_fallback='no'
+			option_extras='no'
+			;;
 		'--'*) help "An unrecognised flag was provided: $item" ;;
 		*) help "An unrecognised argument was provided: $item" ;;
 		esac
@@ -66,9 +83,11 @@ function setup_git() (
 	echo-style --h1='Setup Git'
 
 	# dependencies
-	echo-style --h2='Install Git'
-	setup-util-git
-	echo-style --g2='Install Git'
+	if [[ $option_extras != 'no' ]] || __command_missing -- git; then
+		echo-style --h2='Install Git'
+		setup-util-git --fallback="$option_fallback"
+		echo-style --g2='Install Git'
+	fi
 
 	# vars
 	local protocol_options=(
@@ -146,14 +165,12 @@ function setup_git() (
 	# GITLAB_USERNAME
 
 	# required
-	if [[ -z $GIT_NAME || -z $GIT_EMAIL || -z $GIT_DEFAULT_BRANCH ]]; then
-		option_configure='yes'
-	fi
-	if ! is-needle --needle="$GIT_PROTOCOL" -- "${protocol_options[@]}"; then
-		option_configure='yes'
-	fi
-	if ! is-needle --needle="$MERGE_TOOL" -- "${merge_tools[@]}"; then
-		option_configure='yes'
+	if [[ -z $option_configure ]]; then
+		if [[ -z $GIT_NAME || -z $GIT_EMAIL || -z $GIT_DEFAULT_BRANCH ]] ||
+			! is-needle --needle="$GIT_PROTOCOL" -- "${protocol_options[@]}" ||
+			! is-needle --needle="$MERGE_TOOL" -- "${merge_tools[@]}"; then
+			option_configure='yes'
+		fi
 	fi
 
 	# configure
@@ -241,9 +258,15 @@ function setup_git() (
 
 	# Profile
 	echo-style --header2='Git Configuration: Profile'
-	git config --global user.name "$GIT_NAME"
-	git config --global user.email "$GIT_EMAIL"
-	git config --global git.protocol "$GIT_PROTOCOL"
+	if [[ -n $GIT_NAME ]]; then
+		git config --global user.name "$GIT_NAME"
+	fi
+	if [[ -n $GIT_EMAIL ]]; then
+		git config --global user.email "$GIT_EMAIL"
+	fi
+	if [[ -n $GIT_PROTOCOL ]]; then
+		git config --global git.protocol "$GIT_PROTOCOL"
+	fi
 
 	# Authorizations
 	echo-style --header2='Git Configuration: Auth'
@@ -260,8 +283,10 @@ function setup_git() (
 
 	# Merge Tool
 	echo-style --header2="Git Configuration: Merge/Diff Tool: $MERGE_TOOL"
-	git config --global diff.tool "$MERGE_TOOL"
-	git config --global merge.tool "$MERGE_TOOL"
+	if [[ -n $MERGE_TOOL ]]; then
+		git config --global diff.tool "$MERGE_TOOL"
+		git config --global merge.tool "$MERGE_TOOL"
+	fi
 
 	# Editor
 	local editor
@@ -446,38 +471,43 @@ function setup_git() (
 	# Security
 
 	echo-style --header2='Git Configuration: Permissions'
-	ssh-helper permissions
-	gpg-helper permissions
+	ssh-helper --install="$option_extras" permissions
+	gpg-helper --install="$option_extras" permissions
+	# @todo apply the above --install flag
+	# @todo github-download caching
+	# @todo read -i version added and bash.bash update
 
 	# =====================================
 	# SSH
 
-	ssh-helper setup --configure="$option_configure"
+	ssh-helper --install="$option_extras" --configure="$option_configure" setup
 
 	# =====================================
 	# Authenticate with CLIs
 
 	# Must be done here, as they depend on git and ssh being correctly configured
-	if [[ -n $GITHUB_USERNAME ]]; then
-		setup-util-gh --optional
+	if [[ -n $GITHUB_USERNAME && $option_extras != 'no' ]]; then
+		setup-util-gh --optional --fallback="$option_fallback"
 	fi
 
 	# =====================================
 	# Configure protocols now that ssh is setup
 
 	echo-style --header2="Git Configuration: Protocol: $GIT_PROTOCOL"
-	if [[ $GIT_PROTOCOL == 'ssh' ]] && ! ssh-helper test; then
-		echo-style --notice='SSH failed, temporarily configuring for HTTPS'
-		GIT_PROTOCOL='https'
-	fi
-	git config --global git.protocol "$GIT_PROTOCOL"
-	if __command_exists -- hub; then
-		git config --global hub.protocol "$GIT_PROTOCOL"
-	else
-		git config --global --unset hub.protocol || :
-	fi
-	if __command_exists -- gh; then
-		gh config set git_protocol "$GIT_PROTOCOL" || : # can fail
+	if [[ -n $GIT_PROTOCOL ]]; then
+		if [[ $GIT_PROTOCOL == 'ssh' ]] && ! ssh-helper test; then
+			echo-style --notice='SSH failed, temporarily configuring for HTTPS'
+			GIT_PROTOCOL='https'
+		fi
+		git config --global git.protocol "$GIT_PROTOCOL"
+		if __command_exists -- hub; then
+			git config --global hub.protocol "$GIT_PROTOCOL"
+		else
+			git config --global --unset hub.protocol || :
+		fi
+		if __command_exists -- gh; then
+			gh config set git_protocol "$GIT_PROTOCOL" || : # can fail
+		fi
 	fi
 
 	# if [[ -n "$GITLAB_USERNAME" ]]; then
