fetch: if failure, tell us what url failed
setup-rust, setup-util-1password: use fetch

diff --git a/commands/fetch b/commands/fetch
--- a/commands/fetch
+++ b/commands/fetch
@@ -63,6 +63,12 @@ function fetch() (
 	# =====================================
 	# Helpers
 
+	function log_failure {
+		local status="$?"
+		echo-style --error="Failed to fetch the URL:" ' ' --code="$option_url" >/dev/stderr
+		return "$status"
+	}
+
 	#  -I, --head                        Show document info only
 	#  -m, --max-time <seconds>          Maximum time allowed for the transfer
 	#  -o, --output <file>               Write to file instead of stdout
@@ -78,7 +84,7 @@ function fetch() (
 			--write-out '%{http_code}'
 		)
 		setup-util-curl --quiet
-		curl "${args[@]}" --location "$option_url"
+		curl "${args[@]}" --location "$option_url" || log_failure
 	}
 
 	function fetch_ok {
@@ -90,12 +96,12 @@ function fetch() (
 	function fetch_contents {
 		if command-exists curl; then
 			# use echo-wait to fix [curl: (23) Failure writing output to destination] when piping to ripgrep
-			curl -fsSL "$option_url" | echo-wait
+			curl -fsSL "$option_url" | echo-wait || log_failure
 		elif command-exists wget; then
-			wget "$option_url" -O -
+			wget "$option_url" -O - || log_failure
 		else
 			get-installer --first-success --invoke --quiet -- curl wget
-			fetch "$option_url"
+			fetch_contents
 		fi
 	}
 
