more ubuntu dns compat improvements

diff --git a/commands/flush-dns b/commands/flush-dns
--- a/commands/flush-dns
+++ b/commands/flush-dns
@@ -59,12 +59,12 @@ function flush-dns() (
 				--failure="$(echo-style --error='Failed to flush [discoveryutil].')" \
 				-- sudo discoveryutil mdnsflushcache
 		fi
-	elif command-exists systemd-resolve; then
+	elif command-exists resolvectl; then
 		eval-helper --quiet \
-			--pending="$(echo-style --bold='Flushing DNS cache via [systemd-resolve]...')" \
-			--success="$(echo-style --success='Flushed DNS cache via [systemd-resolve]')" \
-			--failure="$(echo-style --error='Failed to flush DNS cache via [systemd-resolve].') $(echo-style --notice='If using an alternative DNS service, then this is expected.')" \
-			-- systemd-resolve --flush-caches || :
+			--pending="$(echo-style --bold='Flushing DNS cache via [Systemd]...')" \
+			--success="$(echo-style --success='Flushed DNS cache via [Systemd]')" \
+			--failure="$(echo-style --error='Failed to flush DNS cache via [Systemd].') $(echo-style --notice='If using an alternative DNS service, then this is expected.')" \
+			-- sudo resolvectl flush-caches --no-pager || :
 	else
 		echo-error 'DNS flushing not yet implemented for this operating system.'
 		return 19 # Operation not supported by device
