replace `mapfile` with `__split`
`mapfile` doesn't exist on bash v3, and doesn't support `-d` until v4.4, furthermore it doesn't support multiple delimiters, multi-length delimiter(s), trimming zero-length, nor easy append

also deprecated `get-array` with new `__make_array`

fix some bad `--=` usage

`fs-diff`: fix deltea using incorrect width

add `--no-color` support to reduce need for `eval-no-color`

diff --git a/commands/fs-diff b/commands/fs-diff
--- a/commands/fs-diff
+++ b/commands/fs-diff
@@ -130,8 +130,16 @@ function fs_diff() (
 
 	# @todo support just plain diff
 	if [[ $option_tool == 'delta' ]]; then
+		# delta fails to detect terminal width correctly so do it ourselves
+		local terminal_columns
+		__split terminal_size --no-zero-length < <(get-terminal-lines-and-columns || :)
+		if [[ ${#terminal_size[@]} -eq 2 ]]; then
+			terminal_columns="${terminal_size[1]}"
+		else
+			terminal_columns='variable'
+		fi
 		eval-helper --inherit --elevated="$option_elevated" --elevate="$option_elevate" --user="$option_user" --group="$option_group" --reason="$option_reason" -- \
-			delta --paging never -s "$option_before" "$option_after" | echo-trim-zero-length --stdin
+			delta --width="$terminal_columns" --paging never -s "$option_before" "$option_after" | echo-trim-zero-length --stdin
 	elif [[ $option_tool == 'difft' ]]; then
 		# difftastic
 		eval-helper --inherit --elevated="$option_elevated" --elevate="$option_elevate" --user="$option_user" --group="$option_group" --reason="$option_reason" -- \
