fs-*: fix bad conclusion and exit codes
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/fs-mount b/commands/fs-mount
--- a/commands/fs-mount
+++ b/commands/fs-mount
@@ -65,101 +65,108 @@ function fs-mount() (
 	}
 
 	# =====================================
-	# Act
+	# Logging
 
-	local title conclusion='' mount_cmd=()
+	export title conclusion=''
 	title="fs-mount $(echo-quote "$mount_source")"
-	conclusion=''
-
-	function fs_mount {
-		local chown='no'
-
-		# verify and prep
-		if is_drive "$mount_source"; then
-			# mount drive
-			mount_cmd+=(
-				'sudo-helper'
-				'--'
-				'mount'
-				"$mount_source"
-				"$mount_target"
-			)
-			# instruct to chown
-			chown='yes'
-		elif gocryptfs-helper verify -- "$mount_source" &>/dev/null; then
-			# mount vault
-			mount_cmd+=(
-				'gocryptfs-helper'
-				'mount'
-				'--'
-				"$mount_source"
-				"$mount_target"
-				"--owner=$option_owner"
-				"--user=$option_user"
-				"--group=$option_group"
-			)
+	echo-segment --h2="$title"
+	conclusion="$(
+		echo-style --red="failed to mount."
+	)"
+	function on_return {
+		local ec="$?"
+		if test "$ec" -eq 0; then
+			echo-segment --g2="$title" " $conclusion"
 		else
-			conclusion="$(
-				echo-style --red="invalid mount source."
-			)"
-			echo-style --error="fs-mount doesn't know how to mount ${mount_source@Q}, it is neither a drive nor a gocryptfs vault"
-			return 22 # Invalid argument
+			echo-segment --e2="$title" " $conclusion"
 		fi
+		trap - RETURN EXIT
+		return "$ec"
+	}
+	trap on_return RETURN EXIT # RETURN is success, EXIT is exceptions
 
-		# if already mounted, then only do perms
-		if test -d "$mount_target"; then
-			if is-mounted --source="$mount_source" --target="$mount_target"; then
-				echo-style --bold="${mount_source@Q}" " already mounted to " --bold="${mount_target@Q}"
-				if ! confirm --bool --ppid=$$ -- 'Do you wish to remount?'; then
-					conclusion="$(
-						echo-style --green="was previously mounted."
-					)"
-					return "$?"
-				fi
+	# =====================================
+	# Action
+
+	local chown='no' mount_cmd=()
+
+	# verify and prep
+	if is_drive "$mount_source"; then
+		# mount drive
+		mount_cmd+=(
+			'sudo-helper'
+			'--'
+			'mount'
+			"$mount_source"
+			"$mount_target"
+		)
+		# instruct to chown
+		chown='yes'
+	elif gocryptfs-helper verify -- "$mount_source" "--user=$option_user" "--group=$option_group"; then
+		# mount vault
+		mount_cmd+=(
+			'gocryptfs-helper'
+			'mount'
+			'--'
+			"$mount_source"
+			"$mount_target"
+			"--owner=$option_owner"
+			"--user=$option_user"
+			"--group=$option_group"
+		)
+	else
+		conclusion="$(
+			echo-style --red="invalid mount source."
+		)"
+		echo-style --error="fs-mount doesn't know how to mount ${mount_source@Q}, it is neither a drive nor a gocryptfs vault"
+		return 22 # Invalid argument
+	fi
+
+	# if already mounted, then only do perms
+	if test -d "$mount_target"; then
+		if is-mounted --source="$mount_source" --target="$mount_target"; then
+			echo-style --bold="${mount_source@Q}" " already mounted to " --bold="${mount_target@Q}"
+			if ! confirm --bool --ppid=$$ -- 'Do you wish to remount?'; then
+				conclusion="$(
+					echo-style --green="was previously mounted."
+				)"
+				return 0
 			fi
-
-			# if mount is invalid, then unmount the directory
-			fs-unmount -- "$mount_target"
 		fi
 
-		# if not mounted, go through the process
-		sudo-helper \
-			-- mkdir -p "$mount_target"
+		# if mount is invalid, then unmount the directory
+		fs-unmount -- "$mount_target"
+	fi
+
+	# if not mounted, go through the process
+	sudo-helper \
+		-- mkdir -p "$mount_target"
+	eval-helper --no-quiet --wrap --shapeshifter \
+		-- fs-own --no-quiet --changes \
+		--owner="$option_owner" \
+		--user="$option_user" \
+		--group="$option_group" \
+		-- "$mount_target"
+
+	# mount
+	eval-helper --no-quiet --wrap \
+		-- "${mount_cmd[@]}"
+	echo-style --success="${mount_source@Q} was mounted."
+
+	# chown
+	if test "$chown" = 'yes'; then
 		eval-helper --no-quiet --wrap --shapeshifter \
 			-- fs-own --no-quiet --changes \
 			--owner="$option_owner" \
 			--user="$option_user" \
 			--group="$option_group" \
 			-- "$mount_target"
-
-		# mount
-		eval-helper --no-quiet --wrap \
-			-- "${mount_cmd[@]}"
-		echo-style --success="${mount_source@Q} was mounted."
-		if test "$chown" = 'yes'; then
-			eval-helper --no-quiet --wrap --shapeshifter \
-				-- fs-own --no-quiet --changes \
-				--owner="$option_owner" \
-				--user="$option_user" \
-				--group="$option_group" \
-				-- "$mount_target"
-		fi
-
-		# success
-		conclusion="$(
-			echo-style --green="mounted successfully."
-		)"
-	}
-
-	# act
-	echo-segment --h2="$title"
-	if fs_mount; then
-		echo-segment --g2="$title" " $conclusion"
-	else
-		local result="$?"
-		echo-segment --e2="$title" " $conclusion"
-		return "$result"
 	fi
+
+	# success
+	conclusion="$(
+		echo-style --green="mounted successfully."
+	)"
 )
 
 # fire if invoked standalone
diff --git a/commands/fs-rm b/commands/fs-rm
--- a/commands/fs-rm
+++ b/commands/fs-rm
@@ -91,10 +91,28 @@ function fs-rm() (
 		)"
 	}
 
-	local conclusion
 	function act {
 		local path="$1"
-		path="$(fs-absolute -- "$path")"
+		export title conclusion=''
+		path="$(fs-absolute -- "$path" || echo-quote "$path")"
+		title="fs-rm $path"
+		if test "$quiet" != 'yes'; then
+			echo-segment --h2="$title"
+			conclusion="$(
+				echo-style --red="failed to remove."
+			)"
+			function on_return {
+				local ec="$?"
+				if test "$ec" -eq 0; then
+					echo-segment --g2="$title" " $conclusion"
+				else
+					echo-segment --e2="$title" " $conclusion"
+				fi
+				trap - RETURN EXIT
+				return "$ec"
+			}
+			trap on_return RETURN EXIT # RETURN is success, EXIT is exceptions
+		fi
 
 		# is the path missing
 		if test ! -e "$path"; then
@@ -136,23 +154,10 @@ function fs-rm() (
 	}
 
 	# act with wrapping of success
-	local path title result=0
+	local path
 	for path in "${paths[@]}"; do
-		if test "$quiet" = 'yes'; then
-			act "$path"
-		else
-			title="fs-rm $(echo-quote "$path")"
-			echo-segment --h2="$title"
-			if act "$path"; then
-				echo-segment --g2="$title" " $conclusion"
-			else
-				result="$?"
-				echo-segment --e2="$title" " $conclusion"
-			fi
-		fi
+		act "$path"
 	done
-
-	return "$result"
 )
 
 # fire if invoked standalone
diff --git a/commands/fs-size b/commands/fs-size
--- a/commands/fs-size
+++ b/commands/fs-size
@@ -50,9 +50,27 @@ function fs-size() (
 	# =====================================
 	# Action
 
-	local conclusion
 	function act {
 		local path="$1"
+		export title conclusion=''
+		if test "$quiet" != 'yes'; then
+			title="fs-size $(echo-quote "$path")"
+			echo-segment --h2="$title"
+			conclusion="$(
+				echo-style --red="failed to determine size."
+			)"
+			function on_return {
+				local ec="$?"
+				if test "$ec" -eq 0; then
+					echo-segment --g2="$title" " $conclusion"
+				else
+					echo-segment --e2="$title" " $conclusion"
+				fi
+				trap - RETURN EXIT
+				return "$ec"
+			}
+			trap on_return RETURN EXIT # RETURN is success, EXIT is exceptions
+		fi
 
 		# is the path missing
 		if test ! -e "$path"; then
@@ -85,19 +103,11 @@ function fs-size() (
 		fi
 	}
 
-	local path title result=0
+	local path
 	for path in "${paths[@]}"; do
-		title="fs-size $(echo-quote "$path")"
-		echo-segment --h1="$title"
-		if act "$path"; then
-			echo-segment --g1="$title" " $conclusion"
-		else
-			result="$?"
-			echo-segment --e1="$title" " $conclusion"
-		fi
+		act "$path"
 	done
 
-	return "$result"
 )
 
 # fire if invoked standalone
