fix sharebox start, fix sudo-inherit calls

diff --git a/commands/fs-mount b/commands/fs-mount
--- a/commands/fs-mount
+++ b/commands/fs-mount
@@ -4,29 +4,70 @@ source "$DOROTHY/sources/strict.bash"
 # =====================================
 # Arguments
 
-# prepare
-if test "${1-}" = '--'; then
-	shift
-fi
-mount_source="${1-}"
-mount_point="${2-}"
-mount_owner="${3-}"
-
 # help
-if is-help "$@" || test -z "$mount_source" -o -z "$mount_point"; then
+function help() {
 	cat <<-EOF >/dev/stderr
 		ABOUT:
 		Mounts a source (be it a drive or gocryptfs vault) to a mount point.
 
 		USAGE:
-		fs-mount [--] <source> <mount-point> [owner]
+		fs-mount [--] <source> <mount-point> [<owner>]
+		fs-mount [--] [--source=<source>] [--target=<mount-point>] [--owner=<owner>] [--user=<user>] [--group=<group>]
 
 		QUIRKS:
-
-		If [owner] is provided, a [fs-own <mount-point>] will be performed after a successful mount.
-		As well as gocryptfs vaults being forced to that owner.
+		If [owner/user/group] is provided, then the mount point will be enforced to that owner/user/group.
 	EOF
-	exit 22 # Invalid argument
+	if test "$#" -ne 0; then
+		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
+	fi
+	return 22 # Invalid argument
+}
+
+# prepare
+while test "${1-}" = '--'; do
+	shift
+done
+
+# process
+paths=()
+mount_source=''
+mount_target=''
+option_owner=''
+option_user=''
+option_group=''
+while test "$#" -ne 0; do
+	item="$1"
+	shift
+	case "$item" in
+	'--help' | '-h') help ;;
+	'--source='*) mount_source="${item:9}" ;;
+	'--target='*) mount_target="${item:9}" ;;
+	'--owner='*) option_owner="${item:8}" ;;
+	'--user='*) option_user="${item:7}" ;;
+	'--group='*) option_group="${item:8}" ;;
+	'--')
+		paths+=("$@")
+		shift $#
+		break
+		;;
+	'--'*) help "An unrecognised flag was provided: $item" ;;
+	*)
+		if test -z "$mount_source"; then
+			mount_source="$item"
+		elif test -z "$mount_target"; then
+			mount_target="$item"
+		elif test -z "$option_owner"; then
+			option_owner="$item"
+		else
+			help "An unrecognised argument was provided: $item"
+		fi
+		;;
+	esac
+done
+
+# check
+if test -z "$mount_source" -o -z "$mount_target"; then
+	help "No paths were provided."
 fi
 
 # =====================================
@@ -34,14 +75,6 @@ fi
 
 function is_drive {
 	[[ "$1" = '/dev/'* ]]
-}
-
-function do_owner() {
-	# now that it is mounted, fix perms again
-	if test -n "$mount_owner"; then
-		fs-own --owner="$mount_owner" -- "$mount_point"
-		echo-style --success="${mount_point@Q} was permissions adjusted."
-	fi
 }
 
 # =====================================
@@ -52,6 +85,8 @@ conclusion=''
 mount_cmd=()
 
 function fs_mount() {
+	local chown='no'
+
 	# verify and prep
 	if is_drive "$mount_source"; then
 		# mount drive
@@ -59,8 +94,10 @@ function fs_mount() {
 			'sudo'
 			'mount'
 			"$mount_source"
-			"$mount_point"
+			"$mount_target"
 		)
+		# instruct to chown
+		chown='yes'
 	elif gocryptfs-helper verify -- "$mount_source" &>/dev/null; then
 		# mount vault
 		mount_cmd+=(
@@ -68,8 +105,10 @@ function fs_mount() {
 			'mount'
 			'--'
 			"$mount_source"
-			"$mount_point"
-			"$mount_owner"
+			"$mount_target"
+			"--owner=$option_owner"
+			"--user=$option_user"
+			"--group=$option_group"
 		)
 	else
 		conclusion="$(
@@ -80,30 +119,31 @@ function fs_mount() {
 	fi
 
 	# if already mounted, then only do perms
-	if test -d "$mount_point"; then
-		if is-mounted --source="$mount_source" --target="$mount_point"; then
-			conclusion="$(
-				echo-style --green="was previously mounted."
-			)"
-			echo-style --bold="${mount_source@Q}" " already mounted to " --bold="${mount_point@Q}"
-			do_owner
-			return "$?"
+	if test -d "$mount_target"; then
+		if is-mounted --source="$mount_source" --target="$mount_target"; then
+			echo-style --bold="${mount_source@Q}" " already mounted to " --bold="${mount_target@Q}"
+			if ! confirm-bool --ppid=$$ -- 'Do you wish to remount?'; then
+				conclusion="$(
+					echo-style --green="was previously mounted."
+				)"
+				return "$?"
+			fi
 		fi
 
 		# if mount is invalid, then unmount the directory
-		fs-unmount -- "$mount_point"
+		fs-unmount -- "$mount_target"
 	fi
 
 	# if not mounted, go through the process
-	sudo mkdir -p "$mount_point"
-	fs-own --owner="$mount_owner" -- "$mount_point"
+	sudo mkdir -p "$mount_target"
+	fs-own --owner="$option_owner" --user="$option_user" --group="$option_group" -- "$mount_target"
 
 	# mount
-	"${mount_cmd[@]}"
+	echo-eval -- "${mount_cmd[@]}"
 	echo-style --success="${mount_source@Q} was mounted."
-
-	# owner
-	do_owner
+	if test "$chown" = 'yes'; then
+		fs-own --owner="$option_owner" --user="$option_user" --group="$option_group" -- "$mount_target"
+	fi
 
 	# success
 	conclusion="$(
