setup-util-syncthing: fix app not being detected
also fix missing paths from complaining

and convention updates for error messages

diff --git a/commands/fs-own b/commands/fs-own
--- a/commands/fs-own
+++ b/commands/fs-own
@@ -45,6 +45,9 @@ function fs-own() (
 			--partial
 			    if provided, failures will be ignored.
 
+			--optional
+			    if provided, missing paths will be ignored.
+
 			--no-changes
 			    if provided, changes will not be reported if the operating system supports it.
 
@@ -71,8 +74,9 @@ function fs-own() (
 	local option_directory_permissions=''
 	local option_file_permissions=''
 	local option_sudo='no'
-	local option_changes=''
 	local option_partial='no'
+	local option_optional='no'
+	local option_changes=''
 	local option_recursive='yes'
 	while test "$#" -ne 0; do
 		item="$1"
@@ -88,11 +92,14 @@ function fs-own() (
 		'--no-sudo'* | '--sudo'*) option_sudo="$(
 			get-flag-value sudo --missing="$option_sudo" -- "$item" | echo-affirmative
 		)" ;;
-		'--no-changes'* | '--changes'*) option_changes="$(
-			get-flag-value changes --missing="$option_changes" -- "$item" | echo-affirmative
-		)" ;;
 		'--no-partial'* | '--partial'*) option_partial="$(
 			get-flag-value partial --missing="$option_partial" -- "$item" | echo-affirmative
+		)" ;;
+		'--no-optional'* | '--optional'*) option_optional="$(
+			get-flag-value optional --missing="$option_optional" -- "$item" | echo-affirmative
+		)" ;;
+		'--no-changes'* | '--changes'*) option_changes="$(
+			get-flag-value changes --missing="$option_changes" -- "$item" | echo-affirmative
 		)" ;;
 		'--no-recursive'* | '--recursive'*) option_recursive="$(
 			get-flag-value recursive --missing="$option_recursive" -- "$item" | echo-affirmative
@@ -114,16 +121,23 @@ function fs-own() (
 	done
 
 	# check
+	local index
 	if test "${#paths[@]}" -eq 0; then
 		help "No paths were provided."
 	fi
-	for path in "${paths[@]}"; do
+	for index in "${!paths[@]}"; do
+		path="${paths[index]}"
 		if test -z "$path"; then
-			echo-error "An empty path was provided." $'\n' "$(echo-verbose "${paths[@]}")"
+			echo-error "$0: An empty path was provided." $'\n' "$(echo-verbose "${paths[@]}")"
 		fi
 		if test ! -e "$path" -a ! -L "$path"; then
-			# symlinks fail -e
-			echo-error "A path was provided, that does not exist:" --code="$path"
+			# ^ symlinks fail -e
+			if test "$option_optional" = 'yes'; then
+				# echo-style --dim "Missing:" ' ' --code="$path"
+				paths[index]=''
+			else
+				echo-error "$0: A path was provided, that does not exist:" --code="$path"
+			fi
 		fi
 	done
 
@@ -252,11 +266,15 @@ function fs-own() (
 
 	if test "$option_partial" = 'yes'; then
 		for path in "${paths[@]}"; do
-			do_own "$path" || :
+			if test -n "$path"; then # handle --optional
+				do_own "$path" || :
+			fi
 		done
 	else
 		for path in "${paths[@]}"; do
-			do_own "$path"
+			if test -n "$path"; then # handle --optional
+				do_own "$path"
+			fi
 		done
 	fi
 )
