sharebox improvements
- vscode: use shellformat as trunk is not available on arm
- btrfs-helper, cpr, fs-mount, fs-size, get-drive-info, get-size, gocryptfs-helper: fix incorrect outputs
- debug-network: quicker debugging of most important information
- down: convention update, and remove botched `path=$(down ...)` implementation
- fs-mount: force flag usage, as args is too confusing
- fs-own, gpg-helper, ssh-helper: fix permission issue, turns out `X` is exactly what was needed
- fs-realpath: no longer fails on non-symlinks
- fs-unmount: no longer fails if already unmounted
- is-internet-working: fixed outdated failure message
- seedbox: move config into `sharebox.bash`, expose `ip` command, try various config options to try and get it to work (still unsuccessful)
- service-helper: add `--logs` and `--running`
- setup-dns: if internet isn't working, don't try and use remote services, also temporarily disable default-route change while we debug docker/vpn networking
- setup-docker: don't use failed `$USER` variable, and better debugging
- setup-go: convention updates
- setup-util: fix install detection, fix apt uninstall of keys and repo, fix dpkg deb downloads
- setup-util-gocryptfs: fix install if go not present
- setup-util-netscript: don't install if already installed
- setup-util-{nordvpn,openvpn,transmission}: add as `seedbox` is failing
- setup-util-{plex,resilio,samba,syncthing}: fix bad config and user/group handling
- sharebox: got it working, more or less, except for `seedbox`
- sudo-helper: fix edge case when running on a user which $HOME does not exist

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/fs-own b/commands/fs-own
--- a/commands/fs-own
+++ b/commands/fs-own
@@ -16,17 +16,17 @@ function fs-own() (
 			fs-own [...options] [--] <...paths>
 
 			OPTIONS:
+			--no-quiet
+			    if provided, will output the executed commands.
+
 			--verbose
-			    if provied, will output the executed commands.
+			    if provied, will use --verbose on executed chmod/chown commands.
+
+			--no-changes
+			    if provided, changes will not be reported if the operating system supports it.
 
 			--permissions=<permissions>
 			    sets file and directory permissions
-
-			--directory-permissions=<permissions>
-			    sets directory permisisons
-
-			--file-permissions=<permissions>
-			    set file permissions
 
 			--admin
 			    if provided, will use the platform specific admin values.
@@ -49,9 +49,6 @@ function fs-own() (
 			--optional
 			    if provided, missing paths will be ignored.
 
-			--no-changes
-			    if provided, changes will not be reported if the operating system supports it.
-
 			--no-recursive
 			    if provided, only the exact path will be used, not any child paths.
 
@@ -66,26 +63,32 @@ function fs-own() (
 
 	# process
 	local item paths=()
+	local option_quiet='yes'
 	local option_verbose='no'
+	local option_changes='' # os support
 	local option_owner=''
 	local option_user=''
 	local option_group=''
 	local option_admin='no'
 	local option_permissions=''
-	local option_directory_permissions=''
-	local option_file_permissions=''
+	local option_directory_permissions='' # deprecated
+	local option_file_permissions='' # deprecated
 	local option_sudo='no'
 	local option_partial='no'
 	local option_optional='no'
-	local option_changes=''
 	local option_recursive='yes'
+	option_quiet="$(echo-quiet "$option_quiet" -- "$@")"
 	while test "$#" -ne 0; do
 		item="$1"
 		shift
 		case "$item" in
 		'--help' | '-h') help ;;
+		'--no-quiet'* | '--quiet'* | '--no-verbose'* | '--verbose'*) ;; # handled by echo-quiet
 		'--no-verbose'* | '--verbose'*) option_verbose="$(
 			get-flag-value verbose --missing="$option_verbose" -- "$item" | echo-affirmative
+		)" ;;
+		'--no-changes'* | '--changes'*) option_changes="$(
+			get-flag-value changes --missing="$option_changes" -- "$item" | echo-affirmative
 		)" ;;
 		'--no-admin'* | '--admin'*) option_admin="$(
 			get-flag-value admin --missing="$option_admin" -- "$item" | echo-affirmative
@@ -98,9 +101,6 @@ function fs-own() (
 		)" ;;
 		'--no-optional'* | '--optional'*) option_optional="$(
 			get-flag-value optional --missing="$option_optional" -- "$item" | echo-affirmative
-		)" ;;
-		'--no-changes'* | '--changes'*) option_changes="$(
-			get-flag-value changes --missing="$option_changes" -- "$item" | echo-affirmative
 		)" ;;
 		'--no-recursive'* | '--recursive'*) option_recursive="$(
 			get-flag-value recursive --missing="$option_recursive" -- "$item" | echo-affirmative
@@ -144,10 +144,14 @@ function fs-own() (
 		fi
 	done
 
+	# check for deprecation
+	if test -n "$option_directory_permissions" -o -n "$option_file_permissions"; then
+		help "[file|directory]-permissions are deprecated, you probably just wanted to do --permissions=X..., see https://superuser.com/a/91966/32418"
+	fi
+
 	# adjustments: permissions
-	if test -z "$option_permissions" -a -z "$option_directory_permissions" -a -z "$option_file_permissions"; then
-		option_directory_permissions='755'
-		option_file_permissions='644'
+	if test -z "$option_permissions"; then
+		option_permissions='a-xrw,ug+Xrw'
 	fi
 
 	# adjustments: admin
@@ -192,6 +196,8 @@ function fs-own() (
 			option_changes='yes'
 		fi
 	fi
+
+	# apply args
 	if test "$option_changes" = 'yes'; then
 		if is-mac || is-alpine; then
 			echo-style --dim='Reporting permission changes is not provided by this Operating System.' >/dev/stderr
@@ -199,68 +205,62 @@ function fs-own() (
 			ch_args+=('--changes')
 		fi
 	fi
+	if test "$option_verbose" = 'yes'; then
+		ch_args+=('--verbose')
+	fi
+
+	# =====================================
+	# Prepare
+
+	local prefix_args=() sudo_as_user_args=() sudo_as_admin_args=()
+
+	# queit
+	if test "$option_quiet" = 'no'; then
+		prefix_args+=(
+			'eval-helper'
+			'--no-quiet'
+			'--wrap'
+			'--'
+		)
+	fi
+
+	# sudo as the user/group
+	if test -n "$owner" -o "$option_sudo" = 'yes'; then
+		sudo_as_user_args+=('sudo-helper')
+		if test -n "$option_user"; then
+			sudo_as_user_args+=("--user=$option_user")
+		fi
+		if test -n "$option_group"; then
+			sudo_as_user_args+=("--group=$option_group")
+		fi
+		sudo_as_user_args+=('--')
+	fi
+
+	# sudo as the admin
+	if test -n "$owner" -o "$option_sudo" = 'yes'; then
+		sudo_as_admin_args+=(
+			'sudo-helper'
+			'--'
+		)
+	fi
 
 	# =====================================
 	# Helpers
 
-	function do_sudo_as_user {
-		local cmd=()
-
-		# verbose if provided
-		if test "$option_verbose" = 'yes'; then
-			cmd+=('eval-helper' '--')
-		fi
-
-		# sudo as the user/group
-		if test -n "$owner" -o "$option_sudo" = 'yes'; then
-			cmd+=('sudo-helper')
-			if test -n "$option_user"; then
-				cmd+=("--user=$option_user")
-			fi
-			if test -n "$option_group"; then
-				cmd+=("--group=$option_group")
-			fi
-			cmd+=('--')
-		fi
-
-		# add args, then run the command, as this way supports bash v3
-		cmd+=("$@")
-		"${cmd[@]}"
-	}
-	function do_sudo_as_admin {
-		local cmd=()
-
-		# verbose if provided
-		if test "$option_verbose" = 'yes'; then
-			cmd+=('eval-helper' '--')
-		fi
-
-		# sudo as the admin
-		if test -n "$owner" -o "$option_sudo" = 'yes'; then
-			cmd+=('sudo-helper' '--')
-		fi
-
-		# add args, then run the command, as this way supports bash v3
-		cmd+=("$@")
-		"${cmd[@]}"
-	}
 	function do_own {
 		local path="$1"
 
 		# chown
 		if test -n "$owner"; then
-			do_sudo_as_admin chown "${ch_args[@]}" "$owner" "$path"
+			"${prefix_args[@]}" "${sudo_as_admin_args[@]}" \
+				chown "${ch_args[@]}" "$owner" "$path"
 		fi
 
 		# chmod
 		if test -n "$option_permissions"; then
-			do_sudo_as_user chmod "${ch_args[@]}" "$option_permissions" "$path"
-		fi
-		if test -n "$option_directory_permissions"; then
-			do_sudo_as_user find "$path" -type d -exec chmod "${ch_args[@]}" "$option_directory_permissions" {} \;
-		fi
-		if test -n "$option_file_permissions"; then
-			do_sudo_as_user find "$path" -type f -exec chmod "${ch_args[@]}" "$option_file_permissions" {} \;
+			# https://superuser.com/a/91966/32418
+			"${prefix_args[@]}" "${sudo_as_user_args[@]}" \
+				chmod "${ch_args[@]}" "$option_permissions" "$path"
 		fi
 	}
 
@@ -286,3 +286,27 @@ function fs-own() (
 if test "$0" = "${BASH_SOURCE[0]}"; then
 	fs-own "$@"
 fi
+
+
+# # find -exec fails when --user --group is provided as it fails to attach to correct home
+# # so instead xargs needs to be used, but that fails because too many files or so
+# # so instead we do a loop, but that is very slow
+# # and in the end, the only time people ever need this is when they actually inded to do
+# # an uppercase X permission https://superuser.com/a/91966/32418
+
+# if test -n "$option_directory_permissions"; then
+# 	test "$option_quiet" = 'no' && set -x || :
+# 	"${sudo_as_user_args[@]}" find "$path" -type d | while read -r dir; do
+# 		"${sudo_as_user_args[@]}" \
+# 			chmod "${ch_args[@]}" "$option_directory_permissions" "$dir"
+# 	done
+# 	test "$option_quiet" = 'no' && set +x || :
+# fi
+# if test -n "$option_file_permissions"; then
+# 	test "$option_quiet" = 'no' && set -x || :
+# 	"${sudo_as_user_args[@]}" find "$path" -type f | while read -r file; do
+# 		"${sudo_as_user_args[@]}" \
+# 			chmod "${ch_args[@]}" "$option_file_permissions" "$file"
+# 	done
+# 	test "$option_quiet" = 'no' && set +x || :
+# fi
diff --git a/commands/seedbox b/commands/seedbox
--- a/commands/seedbox
+++ b/commands/seedbox
@@ -69,6 +69,7 @@ function seedbox() (
 		debug
 		follow
 		id
+		ip
 		logs
 		remove
 		restart
@@ -101,9 +102,12 @@ function seedbox() (
 	fi
 
 	# check docker is working
-	eval-helper --quiet=yes \
-		-- service-helper --status -- docker || {
-		echo-error "$0: Docker not ready."
+	service-helper --running -- docker || {
+		if test "$action" = 'stop'; then
+			echo 'Docker is not running, so the seedbox is already stopped...'
+			return 0
+		fi
+		echo-error "$0: Docker not running."
 		return 1
 	}
 
@@ -113,9 +117,10 @@ function seedbox() (
 	source "$DOROTHY/sources/config.bash"
 
 	# seedbaox.bash provides:
+	# https://github.com/haugene/docker-transmission-openvpn
 	local image='haugene/transmission-openvpn' version='3.7.1' # latest
-	local SEEDBOX_PORT='' VPN_PROVIDER='' VPN_PROTOCOL='' VPN_COUNTRY='' VPN_DNS='' VPN_USER='' VPN_PASS='' DATA_PATH=''
-	if ! load_dorothy_config 'seedbox.bash'; then
+	local SHAREBOX_USER='' SHAREBOX_GROUP='' SEEDBOX_PORT='' VPN_PROVIDER='' VPN_PROTOCOL='' VPN_COUNTRY='' VPN_DNS='' VPN_USER='' VPN_PASS='' DATA_PATH=''
+	if ! load_dorothy_config 'sharebox.bash'; then
 		reconfigure='yes'
 	fi
 
@@ -136,16 +141,26 @@ function seedbox() (
 		VPN_COUNTRY="$(what-is-my-country)"
 	fi
 	if test -z "$VPN_DNS"; then
-		VPN_DNS="$(what-is-my-exposed-dns)"
+		VPN_DNS="$(what-is-my-dns exposed)"
 	fi
 
 	# required
-	if test -z "$DATA_PATH" -o -z "$VPN_USER" -o -z "$VPN_PASS"; then
+	if test -z "$SHAREBOX_USER" -o -z "$SHAREBOX_GROUP" -o -z "$DATA_PATH" -o -z "$VPN_USER" -o -z "$VPN_PASS"; then
 		reconfigure='yes'
 	fi
 
 	# update configuration
 	if test "$reconfigure" = 'yes'; then
+		SHAREBOX_USER="$(
+			ask --confirm \
+				--question='Enter the username to use for the share.' \
+				--default="$SHAREBOX_USER"
+		)"
+		SHAREBOX_GROUP="$(
+			ask --confirm \
+				--question='Enter the groupname to use for the share.' \
+				--default="$SHAREBOX_GROUP"
+		)"
 		DATA_PATH="$(
 			ask --required --confirm \
 				--question="Where do you want your seedbox data to exist?" \
@@ -164,6 +179,8 @@ function seedbox() (
 
 		# save
 		update_dorothy_user_config --prefer=local 'seedbox.bash' -- \
+			--field='SHAREBOX_USER' --value="$SHAREBOX_USER" \
+			--field='SHAREBOX_GROUP' --value="$SHAREBOX_GROUP" \
 			--field='DATA_PATH' --value="$DATA_PATH" \
 			--field='VPN_USER' --value="$VPN_USER" \
 			--field='VPN_PASS' --value="$VPN_PASS"
@@ -181,15 +198,6 @@ function seedbox() (
 	}
 
 	# actions
-	function seedbox_ip {
-		local id
-		id="$(seedbox_id || :)"
-		if test -z "$id"; then
-			echo-style --error='No seedbox exists to get IP address for.' >/dev/stderr
-			return 1
-		fi
-		docker exec -it "$id" curl -fsSL 'http://ipecho.net/plain'
-	}
 	function seedbox_id {
 		local ids
 		# the bellow could hang if there is an issue, hence the timeout
@@ -222,6 +230,15 @@ function seedbox() (
 	}
 	function seedbox_follow {
 		seedbox_logs --follow
+	}
+	function seedbox_ip {
+		local id
+		id="$(seedbox_id || :)"
+		if test -z "$id"; then
+			echo-style --error='No seedbox exists to get IP address for.' >/dev/stderr
+			return 1
+		fi
+		docker exec -it "$id" curl -fsSL 'http://ipecho.net/plain'
 	}
 	function seedbox_status {
 		local id localip hostip seedboxip details
@@ -261,14 +278,19 @@ function seedbox() (
 		# create
 		set -x # <debug>
 		# https://github.com/haugene/docker-transmission-openvpn/blob/master/docker-compose.yml
-		# --cap-add=NET_ADMIN \
+		# --cap-add=NET_ADMIN
+		# uid/gid are for inside the docker container, and are not related to the host machine
+		# -e PUID="$(uid "$SHAREBOX_USER")" \
+		# -e PGID="$(gid "$SHAREBOX_GROUP")" \
+		# bridge is legacy, I've spend days debugging this
+		# just use host, if you get a failed to create error, restarting or resetting the interfaces can fix it temporarily, however when it does work, it knocks out the host's networking and all dns resolutions will fail despite pings of ips still working, on host and vms
 		docker run \
 			--detach \
 			-v "$DATA_PATH":/data \
 			-e OPENVPN_PROVIDER="$VPN_PROVIDER" \
 			-e OPENVPN_USERNAME="$VPN_USER" \
 			-e OPENVPN_PASSWORD="$VPN_PASS" \
-			-e OPENVPN_OPTS='--mute-replay-warnings' \
+			-e OPENVPN_OPTS='--ping 10' \
 			-e NORDVPN_CATEGORY='P2P' \
 			-e NORDVPN_COUNTRY="$VPN_COUNTRY" \
 			-e NORDVPN_PROTOCOL="$VPN_PROTOCOL" \
@@ -278,7 +300,7 @@ function seedbox() (
 			-e TRANSMISSION_WEB_UI=flood-for-transmission \
 			-e WEBPROXY_ENABLED=false \
 			--log-driver json-file --log-opt max-size=256kb \
-			--net=host --dns="$VPN_DNS" \
+			--cap-add=NET_ADMIN --net=host --dns="$VPN_DNS" \
 			-p "$SEEDBOX_PORT":"$SEEDBOX_PORT" \
 			"$image:$version"
 
diff --git a/commands/service-helper b/commands/service-helper
--- a/commands/service-helper
+++ b/commands/service-helper
@@ -58,10 +58,16 @@ function fs-own() (
 			    Reenable the <service>.
 
 			--status
-			    Output the <service> status.
+			    Output the <service> status, ignores exit code for cross-platform consistency.
+
+			--logs
+			    Output the <service> logs, ignores exit code for cross-platform consistency.
+
+			--running
+			    Returns failure exit code if the <service> is not running. No output.
 
 			--exists
-			    Check if the <service> exists.
+			    REturns failure exit code if the <service> does not exist.
 		EOF
 		if test "$#" -ne 0; then
 			echo-error "$@"
@@ -71,7 +77,7 @@ function fs-own() (
 
 	# process
 	# don't use empty quiet, as that only outputs wraps
-	local item services=() quiet='no' ignore='no' supported='' start='' stop='' restart='' unmask='' load='' unload='' enable='' disable='' reenable='' status='' exists=''
+	local item services=() quiet='no' ignore='no' supported='' start='' stop='' restart='' unmask='' load='' unload='' enable='' disable='' reenable='' status='' logs='' running='' exists=''
 	quiet="$(echo-quiet "$quiet" -- "$@")"
 	while test "$#" -ne 0; do
 		item="$1"
@@ -112,6 +118,12 @@ function fs-own() (
 		'--no-status'* | '--status'*) status="$(
 			get-flag-value status --missing="$status" -- "$item" | echo-affirmative
 		)" ;;
+		'--no-logs'* | '--logs'*) logs="$(
+			get-flag-value logs --missing="$logs" -- "$item" | echo-affirmative
+		)" ;;
+		'--no-running'* | '--running'*) running="$(
+			get-flag-value running --missing="$running" -- "$item" | echo-affirmative
+		)" ;;
 		'--no-exists'* | '--exists'*) exists="$(
 			get-flag-value exists --missing="$exists" -- "$item" | echo-affirmative
 		)" ;;
@@ -134,7 +146,7 @@ function fs-own() (
 
 	if command-exists launchctl; then
 		# quirks about macos/launchctl
-		# - service identifiers can have a `system/` prefix, such as `system/com.apple.smbd`
+		# - service identifiers can have a `system/`, `user/`, `pid/`, and `session/` prefix, such as `system/com.apple.smbd`
 		# - service identifiers can also have extensions it seems, such as `system/com.apple.smb.preferences`
 		function do_unmask {
 			return 0 # not needed
@@ -146,7 +158,7 @@ function fs-own() (
 			# 		not loaded. Now, services are always loaded. If a service is
 			# 		disabled, launchd does not advertise its service endpoints
 			# 		(sockets, Mach ports, etc.).
-			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl load -w "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl load -w "$1"
 		}
 		function do_unload {
 			# Usage: launchctl unload <service-path, service-path2, ...>
@@ -154,97 +166,115 @@ function fs-own() (
 			# 		operations will result in a service which launchd tracks but
 			# 		cannot be launched or discovered in any way.
 			# ...
-			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl unload -w "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl unload -w "$1"
 		}
 		function do_start {
-			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl start "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl start "$1"
 		}
 		function do_stop {
-			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl stop "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl stop "$1"
 		}
 		function do_restart {
-			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl restart "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl restart "$1"
 		}
 		function do_enable {
-			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl enable "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl enable "$1"
 		}
 		function do_enable_now {
-			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl enable "$@"
-			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl start "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl enable "$1"
+			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl start "$1"
 		}
 		function do_disable {
-			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl disable "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl disable "$1"
 		}
 		function do_disable_now {
-			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl disable "$@"
-			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl stop "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl disable "$1"
+			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl stop "$1"
 		}
 		function do_reenable {
-			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl disable "$@"
-			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl enable "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl disable "$1"
+			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl enable "$1"
 		}
 		function do_status {
-			# print returns exit code based on service existence
-			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl print "$@"
+			# return code based on service existence, so ignore, save for running and exists
+			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl print "$1" || :
+		}
+		function do_logs {
+			# @todo
+			# https://stackoverflow.com/a/29926482/130638
+			# https://stackoverflow.com/a/6887421/130638
+			# https://stackoverflow.com/a/46004497/130638
+			# https://apple.stackexchange.com/a/435504/15131
+			return 78 # ENOSYS 78 Function not implemented
+		}
+		function do_running {
+			# return code based on service pid existing / running, hide outpu
+			eval-helper --quiet="$quiet" -- sudo-helper -- launchctl list | grep "$1" | grep -q '^[^-]'
 		}
 		function do_exists {
 			# /Library/LaunchAgents/*"$id"*   # user
 			# /Library/LaunchDaemons/*"$id"*  # everyone
 
-			# print returns exit code based on service existence
-			sudo-helper -- launchctl print "$@" &>/dev/null
+			# return code based on service existence
+			sudo-helper -- launchctl print "$1" &>/dev/null
 		}
 	elif command-exists systemctl; then
 		function do_unmask {
-			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl unmask "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl unmask "$1"
 		}
 		function do_load {
-			return 0 # not needed
+			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl daemon-reload
 		}
 		function do_unload {
-			return 0 # not needed
+			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl daemon-reload
 		}
 		function do_start {
-			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl start "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl start "$1"
 		}
 		function do_stop {
-			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl stop "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl stop "$1"
 		}
 		function do_restart {
-			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl restart "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl restart "$1"
 		}
 		function do_enable {
-			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl enable "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl enable "$1"
 		}
 		function do_enable_now {
-			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl enable --now "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl enable --now "$1"
 		}
 		function do_disable {
-			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl disable "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl disable "$1"
 		}
 		function do_disable_now {
-			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl disable --now "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl disable --now "$1"
 		}
 		function do_reenable {
-			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl reenable "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl reenable "$1"
 		}
 		function do_status {
-			# status returns exit exit code based on service running
-			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl status "$@" --no-pager
+			# return code based on service running, so ignore, save for running and exists
+			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl status "$1" --no-pager || :
+		}
+		function do_logs {
+			eval-helper --quiet="$quiet" -- sudo-helper -- sudo journalctl -u "$1" || :
+		}
+		function do_running {
+			# return code based on service running, hide output
+			eval-helper --quiet="$quiet" -- sudo-helper -- systemctl status "$1" --no-pager &>/dev/null
 		}
 		function do_exists {
-			# return status code based on service existence
-			# sudo-helper -- service "$@" | rg ' * Usage:'
+			# return code based on service existence
+			# sudo-helper -- service "$1" | rg ' * Usage:'
 			# sudo-helper -- service --status-all | rg "$1"
-			local id paths
-			for id in "$@"; do
-				paths=(
-					/etc/init.d/*"$id"*
-					/usr/lib/systemd/system/*"$id"*
-					/etc/systemd/system/*"$id"*
-				)
-				test "${#paths[@]}" -ne 0
-			done
+			# @todo this fails for virtual ids, e.g. `syncthing@ubuntu`
+			local id="$1" paths
+			paths=(
+				/etc/init.d/*"$id"*
+				/usr/lib/systemd/system/*"$id"*
+				/etc/systemd/system/*"$id"*
+			)
+			test "${#paths[@]}" -ne 0
 		}
 	elif command-exists rc-service; then
 		function do_unmask {
@@ -257,47 +287,53 @@ function fs-own() (
 			return 0 # not needed
 		}
 		function do_start {
-			eval-helper --quiet="$quiet" -- sudo-helper -- rc-service "$@" start
+			eval-helper --quiet="$quiet" -- sudo-helper -- rc-service "$1" start
 		}
 		function do_stop {
-			eval-helper --quiet="$quiet" -- sudo-helper -- rc-service "$@" stop
+			eval-helper --quiet="$quiet" -- sudo-helper -- rc-service "$1" stop
 		}
 		function do_restart {
-			eval-helper --quiet="$quiet" -- sudo-helper -- rc-service "$@" restart
+			eval-helper --quiet="$quiet" -- sudo-helper -- rc-service "$1" restart
 		}
 		function do_enable {
-			eval-helper --quiet="$quiet" -- sudo-helper -- rc-update add "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- rc-update add "$1"
 		}
 		function do_enable_now {
-			eval-helper --quiet="$quiet" -- sudo-helper -- rc-update add "$@"
-			eval-helper --quiet="$quiet" -- sudo-helper -- rc-service "$@" start
+			eval-helper --quiet="$quiet" -- sudo-helper -- rc-update add "$1"
+			eval-helper --quiet="$quiet" -- sudo-helper -- rc-service "$1" start
 		}
 		function do_disable {
-			eval-helper --quiet="$quiet" -- sudo-helper -- rc-update del "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- rc-update del "$1"
 		}
 		function do_disable_now {
-			eval-helper --quiet="$quiet" -- sudo-helper -- rc-service "$@" stop
-			eval-helper --quiet="$quiet" -- sudo-helper -- rc-update del "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- rc-service "$1" stop
+			eval-helper --quiet="$quiet" -- sudo-helper -- rc-update del "$1"
 		}
 		function do_reenable {
-			eval-helper --quiet="$quiet" -- sudo-helper -- rc-update add "$@"
+			eval-helper --quiet="$quiet" -- sudo-helper -- rc-update add "$1"
 		}
 		function do_status {
-			# status returns exit exit code based on service running
-			eval-helper --quiet="$quiet" -- sudo-helper -- rc-service "$@" status
+			# return code based on service running, so ignore, save for running and exists
+			eval-helper --quiet="$quiet" -- sudo-helper -- rc-service "$1" status || :
+		}
+		function do_logs {
+			# @todo
+			return 78 # ENOSYS 78 Function not implemented
+		}
+		function do_running {
+			# return code based on service running, hide output
+			eval-helper --quiet="$quiet" -- sudo-helper -- rc-service "$1" status &>/dev/null
 		}
 		function do_exists {
-			# return status code based on service existence
+			# return code based on service existence
 			# sudo-helper -- rc-service --list | grep -i "$1"
 			# https://wiki.alpinelinux.org/wiki/OpenRC
 			# despite docs, it is actually /etc/init.d/ and not /lib/rc/init.d
-			local id paths
-			for id in "$@"; do
-				paths=(
-					/etc/init.d/*"$id"*
-				)
-				test "${#paths[@]}" -ne 0
-			done
+			local id="$1" paths
+			paths=(
+				/etc/init.d/*"$id"*
+			)
+			test "${#paths[@]}" -ne 0
 		}
 	else
 		if test "$supported" = 'yes'; then
@@ -322,13 +358,13 @@ function fs-own() (
 	# brew services restart syncthing
 	# ^ for brew, not cask
 
-	# @todo can use this to check if it is already running
+	# @todo can use this to check if it is already working
 	# if ! systemctl status "$this_service" --no-pager >/dev/null; then
 
 	# https://man.archlinux.org/man/systemctl.1.en
 	# https://wiki.gentoo.org/wiki/OpenRC_to_systemd_Cheatsheet
 	function handle {
-		local this_service="$1" this_unmask="$unmask" this_load="$load" this_unload="$unload" this_start="$start" this_stop="$stop" this_restart="$restart" this_enable="$enable" this_disable="$disable" this_reenable="$reenable" this_status="$status" this_exists="$exists"
+		local this_service="$1" this_unmask="$unmask" this_load="$load" this_unload="$unload" this_start="$start" this_stop="$stop" this_restart="$restart" this_enable="$enable" this_disable="$disable" this_reenable="$reenable" this_status="$status" this_logs="$logs" this_running="$running" this_exists="$exists"
 
 		# ignore?
 		if test "$ignore" = 'yes' && ! do_exists "$this_service"; then
@@ -353,22 +389,26 @@ function fs-own() (
 			do_status "$this_service"
 		fi
 
-		# status
-		if test "$this_status" = 'yes'; then
-			this_status='maybe'
-			do_status "$this_service"
+		# unmask, do before load
+		if test "$this_unmask"; then
+			this_unmask=''
+			do_unmask "$this_service"
+
+			# renable status
+			if test "$this_status" = 'maybe'; then
+				this_status='yes'
+			fi
 		fi
 
 		# load
 		if test "$this_load"; then
 			this_load=''
 			do_load "$this_service"
-		fi
 
-		# unmask
-		if test "$this_unmask"; then
-			this_unmask=''
-			do_unmask "$this_service"
+			# renable status
+			if test "$this_status" = 'maybe'; then
+				this_status='yes'
+			fi
 		fi
 
 		# split restart if autostart is being modified
@@ -447,15 +487,27 @@ function fs-own() (
 		fi
 
 		# unload
-		if test "$this_unload"; then
+		if test "$this_unload" = 'yes'; then
 			this_unload=''
 			do_unload "$this_service"
 		fi
 
-		# startus
+		# status
 		if test "$this_status" = 'yes'; then
 			this_status=''
 			do_status "$this_service"
+		fi
+
+		# logs
+		if test "$this_logs" = 'yes'; then
+			this_logs=''
+			do_logs "$this_service"
+		fi
+
+		# running
+		if test "$this_running" = 'yes'; then
+			this_running=''
+			do_running "$this_service"
 		fi
 	}
 
diff --git a/commands/setup-docker b/commands/setup-docker
--- a/commands/setup-docker
+++ b/commands/setup-docker
@@ -94,7 +94,7 @@ function setup-docker() (
 		'docker.socket'
 		'docker'
 	)
-	local service_user="$USER"
+	local service_user="$(whoami)" # $USER fails inside newgrp
 	local service_group='docker'
 	local service_config_paths=(
 		"$HOME/.docker" # not uninstalled
@@ -133,16 +133,22 @@ function setup-docker() (
 		# remove the group from all users and the system, better than delgroup which is more focused only on the current user
 		sudo-helper -- groupdel "$service_group"
 	}
-	function add_service_group {
+	function install_user_group {
 		# official installer may already added the group for us
 		if ! check_group; then
 			# add a group to the system, better than addgroup which is more focused only on the current user
 			sudo-helper -- groupadd "$service_group"
 		fi
+
+		# official installer may already added the user to the group for us
+		if ! check_user_in_group; then
+			# add the user to the group, better than adduser which is more focused only on the current user
+			sudo-helper -- gpasswd -a "$service_user" "$service_group"
+		fi
 	}
 	function add_permissions_to_config {
 		mkdir -p "${service_config_paths[@]}"
-		fs-own --user="$service_user" --group="$service_group" --permissions='g+rwx' \
+		fs-own --user="$service_user" --group="$service_group" --permissions='g+Xrw' \
 			-- "${service_config_paths[@]}"
 	}
 	function check_docker_exists {
@@ -231,9 +237,6 @@ function setup-docker() (
 		eval "$(fetch https://get.docker.com)"
 		command-exists docker
 	)
-	function install_user_group {
-		add_service_group
-	}
 	function install_postinstall {
 		# this (newgrp) works, but fails on tty items
 		echo "$0 --postinstall" | newgrp "$service_group" || {
@@ -289,20 +292,17 @@ function setup-docker() (
 		sleep 2
 		service-helper --start -- containerd docker.socket docker || :
 		sleep 2
-		service-helper --status -- containerd docker.socket docker
+		service-helper --status --running -- containerd docker.socket docker
 	}
 	function run_debug {
 		# if failing to connect to your local dns serice
 		# ensure it is listening to 0.0.0.0 instead of 127.0.0.1 or 127.0.0.53
 
-		eval-helper --no-quiet --wrap --shapeshifter \
-			-- restart_docker
+		# eval-helper --no-quiet --wrap --shapeshifter \
+		# 	-- restart_docker
 
-		eval-helper --quiet --no-wrap --shapeshifter \
-			-- docker run --rm -it \
-			--net=host \
-			--dns="$(what-is-my-dns exposed)" \
-			-- alpine sh -c "$(cat "$DOROTHY/commands/debug-network")" || {
+		eval-helper --no-quiet --no-wrap \
+			-- docker run --rm -it --cap-add=NET_ADMIN --net=bridge --dns="$(what-is-my-dns exposed)" alpine sh -c "$(cat "$DOROTHY/commands/debug-network")" || {
 			local ec="$?"
 			echo-style --notice='If failing, try restart your computer, and run:' ' ' --code='setup-docker --postinstall'
 			return "$ec"
@@ -422,34 +422,6 @@ fi
 
 # =====================================
 # DOCKER NETWORKING
-
-# function reset_firewall {
-# 	# https://serverfault.com/a/200658/63348
-# 	sudo-helper -- iptables -P INPUT ACCEPT
-# 	sudo-helper -- iptables -P FORWARD ACCEPT
-# 	sudo-helper -- iptables -P OUTPUT ACCEPT
-# 	sudo-helper -- iptables -t nat -F
-# 	sudo-helper -- iptables -t mangle -F
-# 	sudo-helper -- iptables -F
-# 	sudo-helper -- iptables -X
-# 	sudo-helper -- ip6tables -P INPUT ACCEPT
-# 	sudo-helper -- ip6tables -P FORWARD ACCEPT
-# 	sudo-helper -- ip6tables -P OUTPUT ACCEPT
-# 	sudo-helper -- ip6tables -t nat -F
-# 	sudo-helper -- ip6tables -t mangle -F
-# 	sudo-helper -- ip6tables -F
-# 	sudo-helper -- ip6tables -X
-# 	sudo-helper -- iptables -nvL
-# 	sudo-helper -- ufw disable
-# 	sudo-helper -- ufw status verbose
-# }
-# function configure_firewall {
-# 	# https://docs.docker.com/network/bridge/#enable-forwarding-from-docker-containers-to-the-outside-world
-# 	sudo-helper -- sysctl net.ipv4.conf.all.forwarding=1
-# 	sudo-helper -- iptables -P FORWARD ACCEPT
-# 	# https://docs.docker.com/config/daemon/ipv6/
-# 	# /etc/docker/daemon.json doesn't seem to exist
-# }
 
 # https://docs.docker.com/network/bridge
 # https://docs.docker.com/network/bridge/#access-the-outside-world-from-a-container
