change all `chmod`/`chown` calls to `fs-own`
this solves cross-os compatibility differences, such as macos not supporting `--`, or `root:admin` being used when that is platform specific and `--root` or `--admin` is better
- /ref https://github.com/bevry/dorothy/actions/runs/13093354709

this commit also includes:
- fix `--code-notice` failures, replaced it with appropriate styles that do exit
- fix `setup-bin` crashing on permission failures, instead report them and continue

diff --git a/commands/fs-own b/commands/fs-own
--- a/commands/fs-own
+++ b/commands/fs-own
@@ -4,68 +4,54 @@ function fs_own_test() (
 	source "$DOROTHY/sources/bash.bash"
 	echo-style --h1="TEST: $0"
 
-	local root dir file
+	local root dir subfile file
 	root="$(fs-temp --directory)"
 	dir="$(fs-temp --root="$root" --directory='dir' --touch)"
-	file="$(fs-temp --root="$root" --file='file' --touch)"
 	subfile="$(fs-temp --root="$dir" --file='subfile' --touch)"
+	file="$(fs-temp --root="$root" --file='file' --touch)"
 
-	fs-structure -- "$root"
+	local flag flags=(
+		--X
+		--x
+		--r
+		--w
+		--u
+		--ug
+		--ugx
+		--permissions='a-xrw,ug+Xrw'
+		--reference="$DOROTHY"
+		--me
+		--admin
+		--root
+	)
+	fs-structure -- "$root" "$dir"
 
-	eval-tester --name='can own a file +quiet' \
-		-- fs-own --quiet -- "$file"
+	for flag in "${flags[@]}"; do
+		__print_line
+		eval-tester --ignore-stdout -- fs-own --changes "$flag" -- "$dir" "$file"
+		eval-tester --ignore-stdout -- fs-own --quiet "$flag" -- "$dir" "$file"
+		eval-tester --ignore-stdout -- fs-own --verbose "$flag" -- "$dir" "$file"
+		eval-tester --ignore-stdout -- fs-own --recursive --changes "$flag" -- "$dir"
+		eval-tester --ignore-stdout -- fs-own --recursive --quiet "$flag" -- "$dir"
+		eval-tester --ignore-stdout -- fs-own --recursive --verbose "$flag" -- "$dir"
+		fs-structure -- "$root" "$dir"
+	done
 
-	fs-structure -- "$root"
+	# @todo confirm dir and subfile, because of recursion, matched
 
-	eval-tester --name='can own a directory +quiet' \
-		-- fs-own --quiet -- "$dir"
-
-	fs-structure -- "$root"
-
-	eval-tester --name='can own a file -quiet' --ignore-stdout \
-		-- fs-own --no-quiet -- "$file"
-
-	fs-structure -- "$root"
-
-	eval-tester --name='can own a directory -quiet' --ignore-stdout \
-		-- fs-own --no-quiet -- "$dir"
-
-	fs-structure -- "$root"
-
-	eval-tester --name='can own a file +verbose' --ignore-stdout --ignore-stderr \
-		-- fs-own --verbose -- "$file"
-
-	fs-structure -- "$root"
-
-	eval-tester --name='can own a directory +verbose' --ignore-stdout --ignore-stderr \
-		-- fs-own --verbose -- "$dir"
-
-	fs-structure -- "$root"
-
-	eval-tester --name='can own a directory +quiet +admin' --ignore-stderr \
-		-- fs-own --quiet --admin -- "$dir"
-
-	fs-structure -- "$root"
-
-	eval-tester --name='can own a directory -quiet +admin' --ignore-stdout --ignore-stderr \
-		-- fs-own --no-quiet --admin -- "$dir"
-
-	fs-structure -- "$root"
-
-	eval-tester --name='can own a directory +quiet +root' --ignore-stdout --ignore-stderr \
-		-- fs-own --verbose --root -- "$dir"
-
+	__print_line
 	fs-structure -- "$root" || :
 	eval-helper --no-quiet --wrap -- is-accessible.bash -- "$dir" || :
 	eval-helper --no-quiet --wrap -- is-accessible -- "$dir" || :
-	eval-helper --no-quiet --wrap -- stat -L "$dir" || :
-	sudo-helper --wrap -- stat -L "$dir" || :
+	eval-helper --no-quiet --wrap -- stat -L -- "$dir" || :
+	sudo-helper --wrap -- stat -L -- "$dir" || :
 
+	__print_line
 	fs-structure -- "$dir" || :
 	eval-helper --no-quiet --wrap -- is-accessible.bash -- "$subfile" || :
 	eval-helper --no-quiet --wrap -- is-accessible -- "$subfile" || :
-	eval-helper --no-quiet --wrap -- stat -L "$subfile" || :
-	sudo-helper --wrap -- stat -L "$subfile" || :
+	eval-helper --no-quiet --wrap -- stat -L -- "$subfile" || :
+	sudo-helper --wrap -- stat -L -- "$subfile" || :
 
 	echo-style --g1="TEST: $0"
 	return 0
@@ -84,49 +70,59 @@ function fs_own() (
 			USAGE:
 			fs-own [...options] [--] ...<path>
 
+			EXAMPLE:
+			fs-own --recursive --ug -- .
+
 			OPTIONS:
-			--no-quiet
-			    if provided, will output the executed commands.
+			--quiet | --verbose | --changes
+			    if --verbose, apply --changes if supported and use --verbose on executed chmod/chown commands.
+			    if --quiet, apply --no-changes
+			    if neither --verbose or --quiet then apply --changes if supported
 
-			--verbose
-			    if provided, will use --no-quiet for this command, and use --verbose on executed chmod/chown commands.
-
-			--changes
-			    if provided, changes will be reported if the operating system supports it.
-				defaults to enabled if --quiet is not provided.
-
+			--X
+			    sets <permissions> to be executable directories for the user: +x
+			--x
+			    sets <permissions> to be executable for the user: +x
+			--r
+			    sets <permissions> to be executable for the user: +r
+			--w
+			    sets <permissions> to be executable for the user: +w
+			--u
+			    sets <permissions> to only be available to the user: a-xrw,u+Xrw
+			--ux
+			    sets <permissions> to only be available and executable to the user: a-xrw,u+xrw
+			--ug
+			    sets <permissions> to only be available to the user and group: a-xrw,ug+Xrw
+			--ugx
+			    sets <permissions> to only be available and executable to the user and group: a-xrw,ug+xrw
 			--permissions=<permissions>
-			    sets file and directory permissions
-
-			--me
-			    if provided, will set yourself as the owner.
-
-			--admin
-			    if provided, will use the platform specific admin values.
-
-			--root
-			    if provided, will use the platform specific root values.
+			    sets file and directory permissions.
+			--reference=<path>
+			    use the <permissions> from this <path>.
+			    is a cross-platform an alternative to:
+			    chmod --reference=<source> <target>
 
 			--owner=<owner>
-			    if provided, will set the path owner to this.
-
+			    if provided, will set the <path> to be owned by <owner>.
+			--me
+			    if provided, will set <user> to yourself.
+			--admin
+			    if provided, will set <owner> to the platform specific admin values.
+			--root
+			    if provided, will set <owner> to the platform specific root values.
 			--user=<user>
-			    if provided, will set the path owner to this user.
-
+			    if provided, will set <owner> to this user.
 			--group=<group>
-			    if provided, will set the path owner to this group.
+			    if provided, will set <owner> to this group.
 
 			--sudo
-			    if provided, sudo will be used, automatically enabled when admin/owner/user/group is provided.
+			    if provided, sudo will be used, automatically enabled when me/admin/root/owner/user/group is provided.
 
 			--optional
 			    if provided, ignore missing paths and failures.
 
-			--no-recursive
-			    if provided, only the exact path will be used, not any child paths.
-
-			QUIRKS:
-			If [--permissions=...], [--directory-permissions=...], [--file-permissions=...] are all omitted, then the permissions will be set to [a-xrw,ug+Xrw].
+			--recursive
+			    if provided, will recurse into child paths.
 		EOF
 		if [[ $# -ne 0 ]]; then
 			echo-error "$@"
@@ -137,7 +133,7 @@ function fs_own() (
 	# process
 	local item
 	local option_paths=()
-	local option_quiet='' option_verbose='no'
+	local option_quiet=''
 	local option_changes='' # os support
 	local option_owner=''
 	local option_user=''
@@ -149,19 +145,20 @@ function fs_own() (
 	local option_permissions=''
 	local option_directory_permissions='' # deprecated
 	local option_file_permissions=''      # deprecated
+	local option_reference=''
 	local option_sudo='no'
 	local option_optional='no'
-	local option_recursive='yes'
+	local option_recursive='no'
 	while [[ $# -ne 0 ]]; do
 		item="$1"
 		shift
 		case "$item" in
 		'--help' | '-h') help ;;
+		'--no-verbose'* | '--verbose'*)
+			option_quiet="$(get-flag-value --non-affirmative --fallback="$option_quiet" -- "$item")"
+			;;
 		'--no-quiet'* | '--quiet'*)
 			option_quiet="$(get-flag-value --affirmative --fallback="$option_quiet" -- "$item")"
-			;;
-		'--no-verbose'* | '--verbose'*)
-			option_verbose="$(get-flag-value --affirmative --fallback="$option_verbose" -- "$item")"
 			;;
 		'--no-changes'* | '--changes'*)
 			option_changes="$(get-flag-value --affirmative --fallback="$option_changes" -- "$item")"
@@ -187,13 +184,67 @@ function fs_own() (
 		'--no-recursive'* | '--recursive'* | '--no-recurse'* | '--recurse'* | '--no-recursion'* | '--recursion'*)
 			option_recursive="$(get-flag-value --affirmative --fallback="$option_recursive" -- "$item")"
 			;;
+		'--X')
+			if [[ -n $option_permissions ]]; then
+				help "$item cannot be specified with other <permissions>"
+			fi
+			option_permissions='+X'
+			;;
+		'--x')
+			if [[ -n $option_permissions ]]; then
+				help "$item cannot be specified with other <permissions>"
+			fi
+			option_permissions='+x'
+			;;
+		'--r')
+			if [[ -n $option_permissions ]]; then
+				help "$item cannot be specified with other <permissions>"
+			fi
+			option_permissions='+r'
+			;;
+		'--w')
+			if [[ -n $option_permissions ]]; then
+				help "$item cannot be specified with other <permissions>"
+			fi
+			option_permissions='+w'
+			;;
+		'--u')
+			if [[ -n $option_permissions ]]; then
+				help "$item cannot be specified with other <permissions>"
+			fi
+			option_permissions='a-xrw,u+Xrw'
+			;;
+		'--ux')
+			if [[ -n $option_permissions ]]; then
+				help "$item cannot be specified with other <permissions>"
+			fi
+			option_permissions='a-xrw,u+xrw'
+			;;
+		'--ug')
+			if [[ -n $option_permissions ]]; then
+				help "$item cannot be specified with other <permissions>"
+			fi
+			option_permissions='a-xrw,ug+Xrw'
+			;;
+		'--ugx')
+			if [[ -n $option_permissions ]]; then
+				help "$item cannot be specified with other <permissions>"
+			fi
+			option_permissions='a-xrw,ug+xrw'
+			;;
 		'--permissions='*) option_permissions="${item#*=}" ;;
 		'--directory-permissions='*) option_directory_permissions="${item#*=}" ;;
 		'--file-permissions='*) option_file_permissions="${item#*=}" ;;
+		'--reference='* | '--ref='*) option_reference="${item#*=}" ;;
 		'--owner='*) option_owner="${item#*=}" ;;
 		'--user='*) option_user="${item#*=}" ;;
 		'--group='*) option_group="${item#*=}" ;;
 		'--path='*) option_paths+=("${item#*=}") ;;
+		# these have to be last and in this order, as they could match earlier options:
+
+		'--no-u'* | '--u'*)
+			option_u="$(get-flag-value --affirmative --fallback="$option_u" -- "$item")"
+			;;
 		'--')
 			option_paths+=("$@")
 			shift $#
@@ -203,6 +254,11 @@ function fs_own() (
 		*) option_paths+=("$item") ;;
 		esac
 	done
+
+	# deprecations
+	if [[ -n $option_directory_permissions || -n $option_file_permissions ]]; then
+		help '[file|directory]-permissions are deprecated, you probably just wanted to do --permissions=X..., see https://superuser.com/a/91966/32418'
+	fi
 
 	# check
 	if [[ ${#option_paths[@]} -eq 0 ]]; then
@@ -220,14 +276,18 @@ function fs_own() (
 		fi
 	done
 
-	# check for deprecation
-	if [[ -n $option_directory_permissions || -n $option_file_permissions ]]; then
-		help '[file|directory]-permissions are deprecated, you probably just wanted to do --permissions=X..., see https://superuser.com/a/91966/32418'
-	fi
-
-	# adjustments: permissions
-	if [[ -z $option_permissions ]]; then
-		option_permissions='a-xrw,ug+Xrw'
+	# adjustments: reference
+	if [[ -n $option_reference ]]; then
+		if [[ -n $option_permissions ]]; then
+			help '<reference> and <permissions> cannot both be provided'
+		fi
+		if is-mac; then
+			option_permissions="$(stat -f '%p' -- "$option_reference")"
+		else
+			# %a = 644
+			# #A = -rw-r--r--
+			option_permissions="$(stat --format='%a' -- "$option_reference")"
+		fi
 	fi
 
 	# adjustments: admin
@@ -262,14 +322,28 @@ function fs_own() (
 
 	# adjustments: owner
 	local owner=''
-	if [[ -n $option_owner ]]; then
-		owner="$option_owner"
-	elif [[ -n $option_user && -n $option_group ]]; then
+	if [[ -n $option_user && -n $option_group ]]; then
 		owner="$option_user:$option_group"
 	elif [[ -n $option_user ]]; then
 		owner="$option_user"
 	elif [[ -n $option_group ]]; then
 		owner=":$option_group"
+	fi
+	if [[ -n $option_owner ]]; then
+		if [[ -n $owner ]]; then
+			if [[ $option_owner != $owner ]]; then
+				help 'multiple conflicting <owner> options cannot be provided'
+			fi
+			# $owner = $option_owner already
+		else
+			# $owner is empty, and $option_owner is defined
+			owner="$option_owner"
+		fi
+	fi
+
+	# validate there is an action to perform
+	if [[ -z $option_permissions && -z $owner ]]; then
+		help '<permissions> or <owner> required, to match the functionality of prior versions, provide --ug'
 	fi
 
 	# adjustments: recursive
@@ -286,32 +360,33 @@ function fs_own() (
 		fi
 	fi
 	if [[ $option_optional == 'yes' ]]; then
+		# chmod
+		# macos: -f: Do not display a diagnostic message if chmod could not modify the mode for file, nor modify the exit status to reflect such failures.
+		# ubuntu: -f, --silent, --quiet: suppress most error messages
 		ch_args+=('-f')
 	fi
 
-	# adjustments: changes
+	# adjustments: changes, quiet, verbose
 	if [[ -z $option_changes ]]; then
-		if [[ $option_quiet == 'yes' ]] || is-mac; then
+		if [[ $option_quiet == 'yes' ]]; then
 			option_changes='no'
 		else
-			option_changes='yes'
+			# neither --quiet/--verbose, or just --verbose
+			# in which case, enable changes if supported
+			if is-mac || is-alpine; then
+				option_changes='no'
+			else
+				option_changes='yes'
+			fi
 		fi
-	fi
-
-	# adjustments: quiet
-	if [[ -z $option_quiet ]]; then
-		option_quiet='yes'
-	fi
-
-	# apply args
-	if [[ $option_changes == 'yes' ]]; then
+	elif [[ $option_changes == 'yes' ]]; then
 		if is-mac || is-alpine; then
 			echo-style --dim='Reporting permission changes is not provided by this Operating System.' >/dev/stderr
 		else
 			ch_args+=('--changes')
 		fi
 	fi
-	if [[ $option_verbose == 'yes' ]]; then
+	if [[ $option_quiet == 'no' ]]; then
 		if is-mac; then
 			ch_args+=('-v')
 		else
@@ -331,16 +406,12 @@ function fs_own() (
 			all_parent_paths+=("${parent_paths[@]}")
 		done
 		fs-own --no-recursive --no-parents \
-			--quiet="$option_quiet" --changes="$option_changes" \
-			--me="$option_me" --admin="$option_admin" --root="$option_root" \
-			--sudo="$option_sudo" --user="$option_user" --group="$option_group" \
+			--quiet="$option_quiet" \
+			--changes="$option_changes" \
+			--sudo="$option_sudo" \
 			--optional="$option_optional" \
+			--owner="$owner" \
 			--permissions="$option_permissions" \
-			--directory-permissions="$option_directory_permissions" \
-			--file-permissions="$option_file_permissions" \
-			--owner="$option_owner" \
-			--user="$option_user" \
-			--group="$option_group" \
 			-- "${all_parent_paths[@]}"
 	fi
 
@@ -416,7 +487,13 @@ function fs_own() (
 			if [[ ${#sudo_as_admin_args[@]} -ne 0 ]]; then
 				cmd+=("${sudo_as_admin_args[@]}")
 			fi
-			cmd+=(chown "${ch_args[@]}" "$owner" -- "${paths[@]}")
+			# macos chown and chmod do not support --
+			cmd+=(chown "${ch_args[@]}" "$owner")
+			if ! is-mac; then
+				cmd+=('--')
+			fi
+			cmd+=("${paths[@]}")
+			# act
 			"${cmd[@]}" # eval
 		fi
 
@@ -428,7 +505,13 @@ function fs_own() (
 				cmd+=("${sudo_as_user_args[@]}")
 			fi
 			# removing readable perms on a directory, while recursing, will cause permission denied failure
-			cmd+=(chmod "${ch_args[@]}" "$option_permissions" -- "${paths[@]}")
+			# macos chown and chmod do not support --
+			cmd+=(chmod "${ch_args[@]}" "$option_permissions")
+			if ! is-mac; then
+				cmd+=('--')
+			fi
+			cmd+=("${paths[@]}")
+			# act
 			"${cmd[@]}" # eval
 		fi
 	}
@@ -467,26 +550,3 @@ if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
 		fs_own "$@"
 	fi
 fi
-
-# # find -exec fails when --user --group is provided as it fails to attach to correct home
-# # so instead xargs needs to be used, but that fails because too many files or so
-# # so instead we do a loop, but that is very slow
-# # and in the end, the only time people ever need this is when they actually intend to do
-# # an uppercase X permission https://superuser.com/a/91966/32418
-
-# if [[ -n "$option_directory_permissions" ]]; then
-# 	[[ "$option_quiet" = 'no' ]] && set -x || :
-# 	"${sudo_as_user_args[@]}" find "$path" -type d | while read -r dir; do
-# 		"${sudo_as_user_args[@]}" \
-# 			chmod "${ch_args[@]}" "$option_directory_permissions" -- "$dir"
-# 	done
-# 	[[ "$option_quiet" = 'no' ]] && set +x || :
-# fi
-# if [[ -n "$option_file_permissions" ]]; then
-# 	[[ "$option_quiet" = 'no' ]] && set -x || :
-# 	"${sudo_as_user_args[@]}" find "$path" -type f | while read -r file; do
-# 		"${sudo_as_user_args[@]}" \
-# 			chmod "${ch_args[@]}" "$option_file_permissions" -- "$file"
-# 	done
-# 	[[ "$option_quiet" = 'no' ]] && set +x || :
-# fi
