refact: dorothy trial/shell/run/init, mount-helper
- dorothy:
    - reintroduce `trial` command which is `shell --theme=trial`
    - quiet xcode, symlinks, and other setup, so `run` command is only vocal about the command
    - `shell` and `run` now use `init` script
    - `lint` now upgrades trunk
- mount-helper:
    - support macos gocryptfs automounting via cron, and test
    - support macos samba automounting via fstab and cron, and test
        - `/Volumes/*` can be mounted without sudo, all others require sudo for mounting and access
    - use new `config-edit` helper
    - adaptive mkdir, ownership, and sudo requirements
    - correct sources for standalone `check` usage
    - when automounting, use new `sudo-helper --local` to ensure cron is configured correctly for automounting
    - if sudo is required, it is also required for checking existance, updated relevant commands accordingly to support such checks
- `init.{sh,fish}`:
    - support inclusion in `shell` and `run` commands
    - fish init is now much cleaner, and handles fundle properly
- config-edit:
    - new command for manual review of configuration file changes
- edit:
    - if `--sudo` then use terminal editor, as gui editors don't support sudo
    - add `--wait` as alias for `--prompt`
- fs-own:
    - check paths with sudo when sudo is required, as otherwise sudo paths will be undetected (falsely reported as missing)
- fs-realpath:
    - bash v3 compatibility
- service-helper:
    - compatibility with the different macos id formats (system/service, service, service.plist)
- setup-util-cronitor:
    - use new `sudo-helper --local` for sudo and cron compatibility
- setup-util-trunk:
    - no longer call `trunk ugprade` here as it depends on a local trunk setup, instead it has moved to `dorothy lint`
- setup-util-xcode:
    - refactor to ensure correct setup
    - support quiet operation
- sudo-helper:
    - add `--local` to ensure sudo is correctly configured for local command access
- symlink-helper:
    - do not replace if already correct
    - add `--quiet` mode
- waiter:
    - support --exists=<path> to exit early if path becomes available

diff --git a/commands/fs-own b/commands/fs-own
--- a/commands/fs-own
+++ b/commands/fs-own
@@ -131,16 +131,6 @@ function fs-own() (
 			echo-error "$0: An empty path was provided." $'\n' "$(echo-verbose "${paths[@]}")"
 			return 1
 		fi
-		if test ! -e "$path" -a ! -L "$path"; then
-			# ^ symlinks fail -e
-			if test "$option_optional" = 'yes'; then
-				# echo-style --dim "Missing:" ' ' --code="$path"
-				paths[index]=''
-			else
-				echo-error "$0: A path was provided, that does not exist:" --code="$path"
-				return 1
-			fi
-		fi
 	done
 
 	# check for deprecation
@@ -246,6 +236,30 @@ function fs-own() (
 	# =====================================
 	# Helpers
 
+	# symlinks fail -e
+	function is_available {
+		local path="$1"
+
+		if test -n "$owner"; then
+			"${prefix_args[@]}" "${sudo_as_admin_args[@]}" \
+				test -e "$path" -o -L "$path"
+		else
+			"${prefix_args[@]}" "${sudo_as_user_args[@]}" \
+				test -e "$path" -o -L "$path"
+		fi
+	}
+
+	function check_exists {
+		local path="$1"
+		if ! is_available "$path"; then
+			if test "$option_optional" != 'yes'; then
+				echo-error "A path was provided that does not exist or was inaccessible:" --code="$path"
+				return 1
+			fi
+			# echo-style --dim "Missing:" ' ' --code="$path"
+		fi
+	}
+
 	function do_own {
 		local path="$1"
 
@@ -268,13 +282,13 @@ function fs-own() (
 
 	if test "$option_partial" = 'yes'; then
 		for path in "${paths[@]}"; do
-			if test -n "$path"; then # handle --optional
+			if check_exists "$path"; then
 				do_own "$path" || :
 			fi
 		done
 	else
 		for path in "${paths[@]}"; do
-			if test -n "$path"; then # handle --optional
+			if check_exists "$path"; then
 				do_own "$path"
 			fi
 		done
diff --git a/commands/setup-util-xcode b/commands/setup-util-xcode
--- a/commands/setup-util-xcode
+++ b/commands/setup-util-xcode
@@ -2,6 +2,7 @@
 
 function setup-util-xcode() (
 	source "$DOROTHY/sources/bash.bash"
+	source "$(command -v eval-helper)"
 
 	# =====================================
 	# Checks
@@ -15,64 +16,79 @@ function setup-util-xcode() (
 	# =====================================
 	# Action
 
+	# arguments
+	local quiet='no'
+	quiet="$(echo-quiet "$quiet" -- "$@")"
+
 	# log
-	echo-segment --h1="Install Xcode"
-
-	# rosetta
-	if is-apple-silicon && test ! -f /Library/Apple/usr/share/rosetta/rosetta; then
-		sudo-helper -- softwareupdate --install-rosetta --agree-to-license
+	if test "$quiet" = 'no'; then
+		echo-segment --h1="Install Xcode"
 	fi
-
-	# xcode cli tools
-	while true; do
-		if ! xcode-select --install &>/dev/null; then
-			break
-		else
-			confirm --ppid=$$ -- 'Press <enter> once the Apple Command Line Tools have been installed...'
-		fi
-	done
 
 	# check if xcode exists
 	local xcode xcodebuild xcodesdk
-	xcode="$(get-app 'Xcode' || get-app 'Xcode-beta' || :)"
-	xcodebuild="$xcode/Contents/Developer/usr/bin/xcodebuild"
-	xcodesdk="$xcode/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
-
-	# xcode cli tools license
-	function xcode_license_accepted {
-		# https://stackoverflow.com/a/60906147/130638
-		local xcode_version accepted_license_version
-		xcode_version="$("$xcodebuild" -version | grep '^Xcode\s' | sed -E 's/^Xcode[[:space:]]+([0-9\.]+)/\1/' || :)"
-		accepted_license_version="$(defaults read /Library/Preferences/com.apple.dt.Xcode 2>/dev/null | grep IDEXcodeVersionForAgreedToGMLicense | cut -d '"' -f 2 || :)"
-		test "$xcode_version" = "$accepted_license_version"
-	}
-	if test -x "$xcodebuild" && ! xcode_license_accepted; then
-		eval-helper --quiet --wrap \
-			--pending="$(echo-style --bold="Accepting Xcode license...")" \
-			--success="$(echo-style --success="Accepted Xcode license.")" \
-			--failure="$(echo-style --error="Failed to accept Xcode license.")" \
-			-- sudo-helper \
-			-- "$xcodebuild" -license accept
-	fi
-
-	# confirm xcode exists
-	if test -z "$xcode"; then
-		if command-missing mas || ! setup-util --name='Xcode' MAS='497799835'; then
-			echo-style --notice='Xcode requires manual installation...'
-			open 'https://apps.apple.com/us/app/xcode/id497799835'
-			confirm --ppid=$$ -- 'Press <enter> once Xcode has been installed...'
+	while true; do
+		# rosetta
+		if is-apple-silicon && test ! -f /Library/Apple/usr/share/rosetta/rosetta; then
+			sudo-helper -- softwareupdate --install-rosetta --agree-to-license
+			continue # try again
 		fi
-	fi
 
-	# confirm it all works
-	if ! "$xcodebuild" -sdk "$xcodesdk" -find clang &>/dev/null; then
-		echo-style --notice="Xcode SDKs require manual installation, opening Xcode..."
-		open "$xcode"
-		confirm --ppid=$$ -- 'Press <enter> once the Xcode Components have been installed...'
-	fi
+		# xcode cli tools
+		if xcode-select --install &>/dev/null; then
+			confirm --ppid=$$ -- 'Press <enter> once the Apple Command Line Tools have been installed...'
+			continue # try again
+		fi
+
+		# determine xcode location
+		xcode="$(get-app 'Xcode' || get-app 'Xcode-beta' || :)"
+		xcodebuild="$xcode/Contents/Developer/usr/bin/xcodebuild"
+		xcodesdk="$xcode/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
+
+		# confirm xcode exists
+		if test -z "$xcode"; then
+			if command-missing mas || ! setup-util --name='Xcode' MAS='497799835'; then
+				echo-style --notice='Xcode requires manual installation...'
+				open 'https://apps.apple.com/us/app/xcode/id497799835'
+				confirm --ppid=$$ -- 'Press <enter> once Xcode has been installed...'
+			fi
+			continue # try again
+		fi
+
+		# confirm it all works
+		if test ! -x "$xcodebuild" || ! "$xcodebuild" -sdk "$xcodesdk" -find clang &>/dev/null; then
+			echo-style --notice="Xcode SDKs require manual installation, opening Xcode..."
+			open "$xcode"
+			confirm --ppid=$$ -- 'Press <enter> once the Xcode Components have been installed...'
+			continue # try again
+		fi
+
+		# xcode cli tools license
+		function xcode_license_accepted {
+			# https://stackoverflow.com/a/60906147/130638
+			local xcode_version accepted_license_version
+			xcode_version="$("$xcodebuild" -version | grep '^Xcode\s' | sed -E 's/^Xcode[[:space:]]+([0-9\.]+)/\1/' | cut -d '.' -f 1 || :)"
+			accepted_license_version="$(defaults read /Library/Preferences/com.apple.dt.Xcode 2>/dev/null | grep IDEXcodeVersionForAgreedToGMLicense | cut -d '"' -f 2 | cut -d '.' -f 1 || :)"
+			test "$xcode_version" -eq "$accepted_license_version" || sudo-helper -- "$xcodebuild" -license accept
+		}
+		if test "$quiet" = 'yes'; then
+			xcode_license_accepted || continue # try again
+		else
+			eval-helper --quiet="$quiet" --wrap \
+				--pending="$(echo-style --bold="Accepting Xcode license...")" \
+				--success="$(echo-style --success="Accepted Xcode license.")" \
+				--failure="$(echo-style --error="Failed to accept Xcode license.")" \
+				-- xcode_license_accepted || continue # try again
+		fi
+
+		# success
+		break
+	done
 
 	# log
-	echo-segment --g1="Install Xcode"
+	if test "$quiet" = 'no'; then
+		echo-segment --g1="Install Xcode"
+	fi
 )
 
 # fire if invoked standalone
diff --git a/commands/sudo-helper b/commands/sudo-helper
--- a/commands/sudo-helper
+++ b/commands/sudo-helper
@@ -5,6 +5,7 @@
 
 function sudo-helper() (
 	source "$DOROTHY/sources/bash.bash"
+	source "$(command -v config-edit)"
 
 	# =====================================
 	# Arguments
@@ -16,6 +17,7 @@ function sudo-helper() (
 
 			USAGE:
 			sudo-helper [...options] -- <command...>
+			sudo-helper --local
 
 			OPTIONS:
 
@@ -27,6 +29,9 @@ function sudo-helper() (
 
 			--inherit
 			    if enabled, inherit environment variables include PATH.
+
+			--local
+			    update sudo configuration to enable access to /usr/local variables
 		EOF
 		if test "$#" -ne 0; then
 			echo-error "$@"
@@ -35,7 +40,7 @@ function sudo-helper() (
 	}
 
 	# process
-	local item cmd=() inherit='no' user='' group=''
+	local item cmd=() inherit='no' user='' group='' option_local=''
 	while test "$#" -ne 0; do
 		item="$1"
 		shift
@@ -43,6 +48,9 @@ function sudo-helper() (
 		'--help' | '-h') help ;;
 		'--no-inherit'* | '--inherit'*)
 			inherit="$(get-flag-value inherit --missing="$inherit" -- "$item" | echo-affirmative || :)"
+			;;
+		'--no-local'* | '--local'*)
+			option_local="$(get-flag-value local --missing="$option_local" -- "$item" | echo-affirmative || :)"
 			;;
 		'--user='*) user="${item#*--user=}" ;;
 		'--group='*) group="${item#*--group=}" ;;
@@ -55,6 +63,29 @@ function sudo-helper() (
 		*) help "An unrecognised argument was provided: $item" ;;
 		esac
 	done
+
+	# local
+	if test -n "$option_local"; then
+		# dependencies
+		setup-util-sd --quiet
+
+		# paths
+		local system_paths sudoers_line cron_system_line cron_user_line
+		system_paths="$(echo "$PATH" | sd "$HOME/.+?:" '')"
+		sudoers_line="Defaults	secure_path=\"$system_paths\"" # $HOME paths do not make sense for root operation
+		cron_system_line="PATH=\"$system_paths\""             # $HOME paths do not make sense for root operation
+		cron_user_line="PATH=\"$system_paths\""               # $HOME paths fails to apply
+
+		# sudoers
+		config-edit --sudoers --line="$sudoers_line" --needle='secure_path' --add="$option_local"
+
+		# cron
+		config-edit --cron-system --line="$cron_system_line" --needle='PATH=' --add="$option_local"
+		config-edit --cron-user --line="$cron_user_line" --needle='PATH=' --add="$option_local"
+
+		# done
+		return
+	fi
 
 	# check
 	if test "${#cmd[@]}" -eq 0; then
