more documentation
- renamed `truthy` to `echo-first-nonempty`, and now supports stdin in addition to arguments

- renamed `triim` to `echo-trim-lines`

- add docs to `down-zip`, `fetch`, `fs-absolute`, `fs-own`, `fs-realpath`, `geocode`, `get-app`, `gid`, `open-app`, `padd`, `pipp`, `rand`, `together`, `uid`, `unziptar`

- `fs-absolute` no longer resolves symlinks for the directory, that is what `fs-realpath` is for

- `geocode` has been updated for the latest api, and now prompts for the token

- `brew`,  now explains why it failed on non-brew systems or when brew is not installed

- `pipp` now outputs the right error if no python install exists on a non-brew system

- `files-to-list` is now simplified

/ref #7

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/fs-own b/commands/fs-own
--- a/commands/fs-own
+++ b/commands/fs-own
@@ -1,16 +1,33 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
+# help
+if is-help-separator "$@"; then
+	stderr echo-lines \
+		'ABOUT:' \
+		'Claim ownership of a path, by updating its permissions via chmod and chown.' \
+		'' \
+		'USAGE:' \
+		'fs-own [--user=...] [--group=...] -- <...paths>' \
+		'' \
+		'QUIRKS:' \
+		'The user and the group both get rwx permissions via [chmod g+rwx,u+rwx].'
+	exit 22 # Invalid argument
+fi
+
+# options
 mapfile -t options < <(echo-before-separator "$@")
 option_user="$(get-flag-value user -- "${options[@]}")"
 option_group="$(get-flag-value group -- "${options[@]}")"
 mapfile -t paths < <(echo-after-separator "$@")
 
+# check
 if is-array-empty-or-partial "${paths[@]}"; then
-	stderr echo 'USAGE: fs-own [--user=<user>] [--group=<group>] -- <...path>'
-	exit 1
+	stderr echo 'missing paths: refer to [fs-own --help]'
+	exit 22 # Invalid argument
 fi
 
+# helpers
 function do_sudo {
 	echo-eval sudo "$@"
 }
