bash.bash: introduce unsafe _try and _do
the prior approach from 5bb7b86cda6e2ba8c5935dcb5beaf50354d1a647 of skipping expensive try logic on safe functions and non-functions lead to issued with nested unsafe functions inside a safe `__do` or `__try` call, this commit removes unnecessary `__do` and `__try` calls and adds unsafe wrappers of `_do` and `_try` to prevent this nesting issue

improvements in the future could be having `__do` check the function it invokes for safety, in the same we do with `__try` for better autodetection

across all files this commit also removes unnecessary try and do calls by leveraging safety functions instead

/discards prior implementation of e32e887c41671b68892248dedc67d2698bd53219

diff --git a/commands/fs-remove b/commands/fs-remove
--- a/commands/fs-remove
+++ b/commands/fs-remove
@@ -203,26 +203,23 @@ function fs_remove() (
 		eval-helper "${elevation_args[@]}" --quiet="$option_quiet" --no-wrap="$option_quiet" --inherit -- "$@"
 	}
 
-	local CONCLUSION
-	function do_rm {
+	local CONCLUSION reset
+	reset="$(__print_style --no-trail --reset)" || return $?
+	function __remove {
 		local input="$1" path title='' body choices choice is defaults default_args preferences=("${option_preferences[@]}") temp had_failure='' is_readable is_empty can_readable can_trim can_trash can_delete default_for_noconfirm
 		__affirm_value_is_defined "$input" '<path>' || return $?
 
 		# is the input already removed?
 		if is-missing "${elevation_args[@]}" -- "$input"; then
-			CONCLUSION="$(
-				__print_style --success='previously removed.'
-			)"
+			CONCLUSION="$(__print_style --success='previously removed.')" || return $?
 			return 0
 		fi
 
 		# prevent deleting ourself which causes: shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
 		path="$(fs-path "${elevation_args[@]}" --absolute -- "$input")"
 		if [[ "$(pwd)" == "$path"* ]]; then
-			CONCLUSION="$(
-				__print_style --error='contains the CWD, denied.'
-			)"
-			__print_style --stderr --error1='Denied removing an ancestor of the current working directory, change the working directory to elsewhere and try again: ' --code-error1="$path"
+			CONCLUSION="$(__print_style --error='contains the CWD, denied.')" || return $?
+			__print_style --stderr --error1='Denied removing an ancestor of the current working directory, change the working directory to elsewhere and try again: ' --code-error1="$path" || return $?
 			return 1
 		fi
 
@@ -244,7 +241,7 @@ function fs_remove() (
 
 			# if not quiet, dump the progress
 			if [[ -n $CONCLUSION && $option_quiet == 'no' ]]; then
-				__print_style --stderr --code="$path" " $CONCLUSION"
+				__print_style --stderr --code="$path" " $CONCLUSION" || return $?
 			fi
 
 			# if readable, then we can detect emptiness
@@ -376,23 +373,17 @@ function fs_remove() (
 				choice="$default_for_noconfirm"
 			else
 				if [[ -n $is ]]; then
-					title="$(
-						__print_style --="$styled_reason" --notice1="How to remove $is " --code-notice1="$path"
-					)"
+					title="$(__print_style --="$styled_reason" --notice1="How to remove $is " --code-notice1="$path")" || return $?
 				else
-					title="$(
-						__print_style --="$styled_reason" --notice1='How to remove ' --code-notice1="$path"
-					)"
+					title="$(__print_style --="$styled_reason" --notice1='How to remove ' --code-notice1="$path")" || return $?
 				fi
 				if [[ $is_readable == 'no' && $is_directory == 'yes' ]]; then
 					# cannot ls/eza if directory is unreadable
 					body=''
 				else
-					body="$(__print_style --reset)$(fs-structure "${elevation_args[@]}" -- "$path")"
+					body="$reset$(fs-structure "${elevation_args[@]}" -- "$path")" || return $?
 				fi
-				choice="$(
-					choose --required "$title" "$body" --truncate-body "${default_args[@]}" --label -- "${choices[@]}"
-				)"
+				choice="$(choose --required "$title" "$body" --truncate-body "${default_args[@]}" --label -- "${choices[@]}")" || return $?
 			fi
 
 			# remove the predetermined choice from the preferences from next times defaults
@@ -428,16 +419,14 @@ function fs_remove() (
 				}
 				;;
 			'readable')
-				fs-own "${elevation_args[@]}" --quiet="$option_quiet" --r --recursive -- "$path"
+				fs-own "${elevation_args[@]}" --quiet="$option_quiet" --r --recursive -- "$path" || return $?
 				;;
 			'abort')
 				if [[ -n $is ]]; then
 					CONCLUSION="$is "
 				fi
-				CONCLUSION+="$(
-					__print_style --error='failed to remove'
-				)"
-				__print_style --stderr --code="$path" " $CONCLUSION"
+				CONCLUSION+="$(__print_style --error='failed to remove')" || return $?
+				__print_style --stderr --code="$path" " $CONCLUSION" || return $?
 				return 66 # ENOTEMPTY 66 Directory not empty
 				;;
 			'again' | '' | *)
@@ -450,9 +439,7 @@ function fs_remove() (
 				if [[ -n $is ]]; then
 					CONCLUSION="$is "
 				fi
-				CONCLUSION+="$(
-					__print_style --success='removed'
-				)"
+				CONCLUSION+="$(__print_style --success='removed')" || return $?
 				break
 			fi
 		done
@@ -460,10 +447,10 @@ function fs_remove() (
 	}
 
 	function act {
-		local input="$1" title rm_status
+		local input="$1" title
 		if [[ $option_quiet == 'yes' ]]; then
-			do_rm "$input"
-			return $?
+			__remove "$input" || return $?
+			return 0
 		else
 			title='fs-remove'
 			if [[ $option_confirm == 'yes' ]]; then
@@ -486,12 +473,13 @@ function fs_remove() (
 			fi
 			title+=" $(echo-escape-command -- "$input")"
 			__print_style --stderr --h2="$title"
-			__try {rm_status} -- do_rm "$input"
-			if [[ $rm_status -eq 0 ]]; then
+			local -i __remove_status=0
+			__remove "$input" || __remove_status=$?
+			if [[ $__remove_status -eq 0 ]]; then
 				__print_style --stderr --g2="$title" " $CONCLUSION"
 			else
 				__print_style --stderr --e2="$title" " $CONCLUSION"
-				return "$rm_status"
+				return "$__remove_status"
 			fi
 		fi
 	}
