fix and rewrite symlink support and handling
- fs-dirname: fix getting dirname on `dir-that-exists/file-that-does-not-exist`
- fs-realpath: complete rewrite for correct operating system and utility support
- symlink-helper: use our new universally compatible `fs-realpath`, instead of the builtin one

diff --git a/commands/fs-realpath b/commands/fs-realpath
--- a/commands/fs-realpath
+++ b/commands/fs-realpath
@@ -15,14 +15,24 @@ function fs-realpath() (
 			fs-realpath [...options] [--] ...<path>
 
 			OPTIONS:
-			--raw
-			    If the symlink target was a relative path, don't resolve it to an absolute path.
+			--resolve=YES
+			    If [--resolve=no] do not substitute symlinks with their targets.
+
+			--validate=NO | --broken=YES
+			    If [--validate=yes | --broken=no] require every part of the path to be resolvable, aka do not support broken symlinks.
+
+			--relative=NO | --absolute=YES
+			    If [--relative=yes | --absolute=no] don't resolve relative paths to an absolute path, aka support relative paths.
+
+			--relative-to=<relative_to>
+			    If provided, print the resolved path relative to DIR
+
+			--relative-base=<relative_base>
+			    If provided, print absolute paths unless paths below DIR
 
 			QUIRKS:
-			Use [fs-absolute] if you do not want symlinks resolved.
-			Will fail if the symlink does not exist.
-			If the symlink is broken (the target does not exist), the target is returned, just as it would if it was successful.
-			This behaviour is necessary for the usage of [fs-realpath] in repairing broken symlinks.
+			If you don't care about symlinks, you should prefer to use [fs-absolute] instead as it is simpler.
+			Use [--resolve --broken --relative] to help you repair broken relative symlinks.
 		EOF
 		if test "$#" -ne 0; then
 			echo-error "$@"
@@ -31,14 +41,32 @@ function fs-realpath() (
 	}
 
 	# options
-	local item paths=() raw='no'
+	local item paths=() option_resolve='yes' option_validate='no' option_relative='no' option_relative_to='' option_relative_base=''
 	while test "$#" -ne 0; do
 		item="$1"
 		shift
 		case "$item" in
 		'--help' | '-h') help ;;
-		'--no-raw'* | '--raw'*)
-			raw="$(get-flag-value raw --missing="$raw" -- "$item" | echo-affirmative)"
+		'--resolve'*)
+			option_resolve="$(get-flag-value resolve --missing="$option_resolve" -- "$item" | echo-affirmative)"
+			;;
+		'--validate'*)
+			option_validate="$(get-flag-value validate --missing="$option_validate" -- "$item" | echo-affirmative)"
+			;;
+		'--broken'*)
+			option_validate="$(get-flag-value broken --missing="$option_validate" -- "$item" | echo-non-affirmative)"
+			;;
+		'--absolute'*)
+			option_relative="$(get-flag-value absolute --missing="$option_relative" -- "$item" | echo-non-affirmative)"
+			;;
+		'--relative' | '--relative='*)
+			option_relative="$(get-flag-value relative --missing="$option_relative" -- "$item" | echo-affirmative)"
+			;;
+		'--relative-to='*)
+			option_relative_to="$(get-flag-value relative-to --missing="$option_relative_to" -- "$item")"
+			;;
+		'--relative-base='*)
+			option_relative_base="$(get-flag-value relative-base --missing="$option_relative_base" -- "$item")"
 			;;
 		'--')
 			paths+=("$@")
@@ -58,80 +86,239 @@ function fs-realpath() (
 	# =====================================
 	# Action
 
-	# greadlink and realpath are macos coreutils, neither are available on macos without coreutils
-	# readlink and realpath are linux coreutils, usually bundled
+	function do_gnu_realpath {
+		local gnu_realpath
+		if command-exists grealpath; then
+			gnu_realpath='grealpath'
+		elif command-exists realpath && is-linux; then
+			gnu_realpath='realpath'
+		else
+			return 45 # ENOTSUP 45 Operation not supported
+		fi
 
-	# macos readlink:
-	# -f fetches the absolutely resolved path
+		### grealpath (macos coreutils), realpath (ubuntu) ###
+		# realpath [OPTION]... FILE...
+		# -e, --canonicalize-existing:   all components of the path must exist
+		# -m, --canonicalize-missing:    no path components need exist or be a directory
+		# -L, --logical:                 resolve '..' components before symlinks
+		# -P, --physical:                resolve symlinks as encountered (default)
+		# -q, --quiet:                   suppress most error messages
+		# 	--relative-to=DIR:           print the resolved path relative to DIR
+		# 	--relative-base=DIR:         print absolute paths unless paths below DIR
+		# -s, --strip, --no-symlinks:    don't expand symlinks
+		# -z, --zero:                    end each output line with NUL, not newline
+		local path="$1"
+		local args=()
 
-	# greadlink, linux readlink, and realpath:
-	# -m, --canonicalize-missing   no path components need exist or be a directory
-	# -P, --physical               resolve symlinks as encountered (default)
-	# requires [-m] to support broken links
+		# grealpath always returns absolute paths, so do not support relative option
+		if test "$option_relative" = 'yes'; then
+			return 45 # ENOTSUP 45 Operation not supported
+		fi
 
-	# fish realpath builtin always returns absolute, and [-s] supports broken links
-	# https://gitter.im/fish-shell/fish-shell?at=60e4d29c9cf317173013b830
-	# file:///opt/homebrew/Cellar/fish/3.5.1/share/doc/fish/cmds/realpath.html?highlight=realpath
-	# not supported in fish v3.1.2
-	# supported in fish version v3.3.0
-	# exact compatibility unknown
-	# if you are using an old version, remove fish and reinstall using [setup-util-fish]
+		# grealpath supports validation, and non-validation
+		if test "$option_validate" = 'yes'; then
+			args+=('--canonicalize-existing')
+		else
+			args+=('--canonicalize-missing')
+		fi
 
-	# as such on macos, must use fish or install coreutils
+		# grealpath supports resolution, and non-resolution
+		if test "$option_resolve" = 'no'; then
+			args+=('--no-symlinks')
+		fi
 
+		# grealpath supports relative-to and relative-dir
+		if test -n "$option_relative_to"; then
+			args+=("--relative-to=$option_relative_to")
+		fi
+		if test -n "$option_relative_base"; then
+			args+=("--relative-to=$option_relative_base")
+		fi
+
+		# execute
+		"$gnu_realpath" "${args[@]}" "$path"
+	}
+	function do_gnu_readlink {
+		# don't support unsupported args
+		if test -n "$option_relative_to" -o -n "$option_relative_to"; then
+			return 45 # ENOTSUP 45 Operation not supported
+		fi
+
+		local gnu_readlink
+		if command-exists greadlink; then
+			gnu_readlink='greadlink'
+		elif command-exists readlink && is-linux; then
+			gnu_readlink='readlink'
+		else
+			return 45 # ENOTSUP 45 Operation not supported
+		fi
+
+		### greadlink macos coreutils), readlink (ubuntu) ###
+		# readlink [OPTION]... FILE...
+		# -f, --canonicalize:            canonicalize by following every symlink in every component of the given name recursively; all but the last component must exist
+		# -e, --canonicalize-existing:   canonicalize by following every symlink in every component of the given name recursively, all components must exist
+		# -m, --canonicalize-missing:    canonicalize by following every symlink in every component of the given name recursively, without requirements on components existence
+		# -n, --no-newline:              do not output the trailing delimiter
+		# -q, --quiet
+		# -s, --silent:                  suppress most error messages (on by default)
+		# -v, --verbose:                 report error messages
+		# -z, --zero:                    end each output line with NUL, not newline
+		local path="$1"
+
+		# greadlink always resolves symlinks
+		if test "$option_resolve" = 'no'; then
+			return 45 # ENOTSUP 45 Operation not supported
+		fi
+
+		# handle quirks
+		if test "$option_relative" = 'yes'; then
+			if test "$option_validate" = 'yes'; then
+				# relative paths are not supported when validating
+				return 45 # ENOTSUP 45 Operation not supported
+			elif test ! -L "$path"; then
+				# unless canoniclizing, then symlinks are required
+				return 45 # ENOTSUP 45 Operation not supported
+			else
+				"$gnu_readlink" "$path"
+			fi
+		else
+			if test "$option_validate" = 'yes'; then
+				"$gnu_readlink" --canonicalize-existing "$path"
+			else
+				"$gnu_readlink" --canonicalize-missing "$path"
+			fi
+		fi
+	}
+	function do_macos_readlink {
+		# don't support unsupported args
+		if test -n "$option_relative_to" -o -n "$option_relative_to"; then
+			return 45 # ENOTSUP 45 Operation not supported
+		fi
+
+		local macos_readlink
+		if command-exists readlink && is-mac; then
+			macos_readlink='readlink'
+		else
+			return 45 # ENOTSUP 45 Operation not supported
+		fi
+
+		### readlink (macos) ###
+		# readlink [-fn] [file ...]
+		# If the given argument is not a symbolic link and the -f option is not specified, readlink will print nothing and exit with an error.  If the -f option is specified, the output is canonicalized by following every symlink in every component of the given path recursively.
+		#
+		# NOTES
+		# -f fetches the absolutely resolved path
+
+		if test "$option_resolve" = 'yes' -a "$option_relative" = 'yes' -a "$option_validate" = 'no'; then
+			if test -L "$path"; then
+				"$macos_readlink" "$path"
+			else
+				return 45 # ENOTSUP 45 Operation not supported
+			fi
+		elif test "$option_resolve" = 'yes' -a "$option_relative" = 'no' -a "$option_validate" = 'yes'; then
+			# readlink will return correct output, but have a failure exit code if not valid
+			"$macos_readlink" -f "$path"
+		else
+			return 45 # ENOTSUP 45 Operation not supported
+		fi
+	}
+	function do_macos_realpath {
+		# don't support unsupported args
+		if test -n "$option_relative_to" -o -n "$option_relative_to"; then
+			return 45 # ENOTSUP 45 Operation not supported
+		fi
+
+		local macos_realpath
+		if command-exists realpath && is-mac; then
+			macos_realpath='realpath'
+		else
+			return 45 # ENOTSUP 45 Operation not supported
+		fi
+
+		### realpath (macos) ###
+		# realpath [-q] [path ...]
+		# If -q is specified, warnings will not be printed when realpath(3) fails.
+
+		if test "$option_resolve" = 'yes' -a "$option_relative" = 'no' -a "$option_validate" = 'yes'; then
+			"$macos_realpath" "$path"
+		else
+			return 45 # ENOTSUP 45 Operation not supported
+		fi
+	}
 	function fish_capable {
-		ommand-exists fish
+		command-exists fish
 		# trunk-ignore(shellcheck/SC2016)
 		test "$(version-compare "$(fish -c 'echo $FISH_VERSION')" 3.3.0)" -ge 0
 	}
+	function do_fish_realpath {
+		# don't support unsupported args
+		if test -n "$option_relative_to" -o -n "$option_relative_to"; then
+			return 45 # ENOTSUP 45 Operation not supported
+		fi
 
-	function resolve_symlink {
-		local path="$1"
-		if test ! -e "$path" -a ! -L "$path"; then
-			# just -e is not sufficient, as broken symlinks will fail -e
-			echo-error "$0: Missing: $path"
-			return 2 # ENOENT 2 No such file or directory
-		elif test ! -L "$path"; then
-			echo "$path" # is not a symlink
-		elif command-exists greadlink; then
-			# macos coreutils
-			if test "$raw" = 'yes'; then
-				greadlink "$path" # supports broken links, no resolve
+		if ! fish_capable; then
+			return 45 # ENOTSUP 45 Operation not supported
+		fi
+
+		### realpath (fish) ###
+		# realpath [OPTIONS] PATH
+		# realpath follows all symbolic links encountered for the provided PATH, printing the absolute path resolved. fish provides a realpath-alike builtin intended to enrich systems where no such command is installed by default.
+		#  If a realpath command exists, that will be preferred.  builtin realpath will explicitly use the fish implementation of realpath.
+		# -s or --no-symlinks:   Don't resolve symlinks, only make paths absolute, squash multiple slashes and remove trailing slashes.
+		#
+		# NOTES
+		# https://gitter.im/fish-shell/fish-shell?at=60e4d29c9cf317173013b830
+		# file:///opt/homebrew/Cellar/fish/3.5.1/share/doc/fish/cmds/realpath.html?highlight=realpath
+		# not supported in fish v3.1.2
+		# supported in fish version v3.3.0
+		# exact compatibility unknown
+		# if you are using an old version, remove fish and reinstall using [setup-util-fish]
+
+		if test "$option_relative" = 'no' -a "$option_validate" = 'no'; then
+			if test "$option_resolve" = 'no'; then
+				# trunk-ignore(shellcheck/SC2016)
+				fish -c 'builtin realpath --no-symlinks "$argv[1]"' -- "$path"
 			else
-				greadlink -m "$path" # supports broken links, resolve
-			fi
-		elif command-exists readlink; then
-			# linux coreutils
-			if test "$raw" = 'yes'; then
-				readlink "$path" # supports broken links, no resolve
-			else
-				readlink -m "$path" # supports broken links, resolve
-			fi
-		elif command-exists realpath; then
-			# macos coreutils, linux coreutils
-			if test "$raw" = 'yes'; then
-				realpath "$path" # supports broken links, no resolve
-			else
-				realpath -m "$path" # supports broken links, resolve
-			fi
-		elif fish_capable; then
-			# fish builtin
-			# trunk-ignore(shellcheck/SC2016)
-			fish -c 'realpath -s "$argv[1]"' -- "$path"
-		elif command-exists readlink; then
-			if test "$raw" = 'yes'; then
-				readlink "$path" # supports broken links, no resolve
-			else
-				readlink -f "$path" # DOES NOT SUPPORT broken links, resolve
-				# don't do the coreutils fallback here, as if we are here, we are too early in the dorothy setup
+				# trunk-ignore(shellcheck/SC2016)
+				fish -c 'builtin realpath "$argv[1]"' -- "$path"
 			fi
 		else
-			setup-util-coreutils --quiet
-			resolve_symlink "$path"
+			return 45 # ENOTSUP 45 Operation not supported
 		fi
 	}
 
-	local path
+	local fallback='yes'
+	local options=(
+		do_gnu_realpath
+		do_gnu_readlink
+		do_macos_readlink
+		do_macos_realpath
+		do_fish_realpath
+	)
+	function resolve_symlink {
+		local ec option path="${1%/}" # trim the trailing slash, as a trailing slash will fail symlink detection
+
+		# cycle through the options, and continue if the option is not supported
+		for option in "${options[@]}"; do
+			ec=0 && "$option" "$path" || ec="$?"
+			if test "$ec" -ne 45; then
+				return "$ec"
+			fi
+		done
+
+		# if no option was supported, then install utilities and try again
+		if test "$fallback" = 'no'; then
+			# greadlink + macos-readlink support [--relative=yes] but require [--resolve=yes --validate=no] and for the symlink to exist
+			echo-error "no realpath utility supports this combination of options: " $'\n' \
+				--code="fs-realpath --resolve=$option_resolve --validate=$option_validate relative=$option_relative -- ${path@Q}"
+			return 45 # ENOTSUP 45 Operation not supported
+		fi
+		fallback='no'
+		setup-util-coreutils --quiet
+		resolve_symlink "$path"
+	}
+
+	local path option ec
 	for path in "${paths[@]}"; do
 		resolve_symlink "$path"
 	done
