- is-same: add tests - eval-tester: cleanup output, fix fs-diff causing crash - is-ci: add `--verbose` support - fs-structure: fail if `--no-perms --no-eza` - fs-size: fail on unsupported paths - fs-diff: clarify in help aboout return statuses

diff --git a/commands/fs-size b/commands/fs-size
--- a/commands/fs-size
+++ b/commands/fs-size
@@ -105,8 +105,19 @@ function fs_size() (
 	# Action
 
 	# get apparent size in bytes
-	local path
+	local path readable_status
 	for path in "${option_paths[@]}"; do
+		# check path is valid
+		if [[ -p $path ]]; then
+			echo-error 'Cannot determine size of ' --path="$path" ' as it is a named pipe / file descriptor.'
+			return 79 # EFTYPE 79 Inappropriate file type or format
+		else
+			is-readable --verbose -- "$path" || {
+				readable_status="$?"
+				echo-error 'Cannot determine size of ' --path="$path" ' as it is not readable.'
+				return "$readable_status"
+			}
+		fi
 		__size "$path"
 	done
 )
