process/command substitutions discard exit status
---

workaround that process/command substitutions discard exit status

this also resolves the long-standing problem of `git-helper update` continuing to prompt for which remote, when there are none, because:

``` bash
__split {remotes} --no-zero-length < <(get_remotes)
```

would discard the exit status

added `__split ... --invoke -- <command> ...` to make respecting exit status easier

added `__get_semaphores` as well to make it easier

see `errors.md` for details

---

secondly, this enforces the `{var_name}` covnention for any `bash.bash` function that uses variable references, which improves clarity

in doing so, the WIP `__is_within` is now just `__has`

this also remvoves unnecessary quoting of the var references

---

other changes:

- `secret` has been rewritten to use safety functions, as there was too much unnecessary comoplexity otherwise, it's ugly, but whatever
- `debug-bash` and `dorothy` now share their `__get_bash_barinaries`
- `debug-bash` now supports separators on `--bash=` and `--version` arguments, not just `--versions=`
- use `... || __return $? -- __print_lines || return` and `... || __return $? -- echo-error ... || return` as a a suitable shorthand for outputting additional debug information on failures
- `dorothy theme` now defaults to your current theme selection, there was code there before for this, but it was never implemented corretly
- migrated `get-url-upgrade` to bash associative arrays, for easier maintainability and intention
- `setup-util-docker`: fix a typo regressionin the debug command
- `arrays.md` note that it is outdated
- `errors.md` and `subshells.md` rewrote for modern conventions and awareness of stituations that discard exit status

diff --git a/commands/fs-size b/commands/fs-size
--- a/commands/fs-size
+++ b/commands/fs-size
@@ -250,18 +250,14 @@ function fs_size() (
 	# Action
 
 	# get apparent size in bytes
-	local path readable_status
+	local path
 	for path in "${option_paths[@]}"; do
 		# check path is valid
 		if [[ -p $path ]]; then
 			echo-error 'Cannot determine size of ' --path="$path" ' as it is a named pipe / file descriptor.'
 			return 79 # EFTYPE 79 Inappropriate file type or format
 		else
-			is-readable --verbose -- "$path" || {
-				readable_status="$?"
-				echo-error 'Cannot determine size of ' --path="$path" ' as it is not readable.'
-				return "$readable_status"
-			}
+			is-readable --verbose -- "$path" || __return $? -- echo-error 'Cannot determine size of ' --path="$path" ' as it is not readable.' || return
 		fi
 		__size "$path"
 	done
diff --git a/commands/setup-util-node b/commands/setup-util-node
--- a/commands/setup-util-node
+++ b/commands/setup-util-node
@@ -24,7 +24,7 @@ function setup_util_node() (
 		# swap to system
 		nvm-env -- nvm use system || :
 		# fetch versions
-		__split versions --no-zero-length < <(__get_nvm_versions) || return
+		__split {versions} --no-zero-length --invoke -- __get_nvm_versions || return
 		if [[ ${#versions[@]} -eq 0 ]]; then
 			# already clean
 			return 0
@@ -34,7 +34,7 @@ function setup_util_node() (
 			nvm-env -- nvm uninstall "$version" | echo-regexp -n 'Uninstalled node ' 'Uninstalled: ' || return
 		done
 		# confirm clean was successful
-		__split versions --no-zero-length < <(__get_nvm_versions) || return
+		__split {versions} --no-zero-length --invoke -- __get_nvm_versions || return
 		[[ ${#versions[@]} -eq 0 ]] || return
 	}
 
@@ -95,9 +95,9 @@ function setup_util_node() (
 		if [[ -n $cache_dir && ! -d $cache_dir ]]; then
 			# try and make it
 			__mkdirp "$cache_dir" || {
-				echo-style --notice='Unconfiguring the invalid cache directory:' ' ' --code="$cache_dir"
-				nvm-env -- npm config delete cache
-			}
+				echo-style --notice='Unconfiguring the invalid cache directory:' ' ' --code="$cache_dir" || return
+				nvm-env -- npm config delete cache || return
+			} || return
 		fi
 
 		# continue with the upgrade
@@ -149,7 +149,8 @@ function setup_util_node() (
 			echo-style --dim='Installs active and LTS versions.'
 			eval_helper --quiet --no-wrap -- \
 				install_nvm_node
-			__split versions --no-zero-length < <(__get_nvm_versions)
+			__split {versions} --no-zero-length --invoke -- \
+				__get_nvm_versions
 			for version in "${versions[@]}"; do
 				__print_lines "Installed: v$version"
 			done
