fixes to bash.bash helpers, tests, conventions
- `bash.bash`:
    - add `__affirm_variable_is_defined`
    - ensure `__affirm_variable*` helpers are consistent with supporting a description argument and validation of arguments
    - add commented out `__is_stdin_special_file`, may be used later
    - improve naming and description and passed names/descriptions in error cascades
    - ensure consistent `local` convention for helper as-needed inputs
    - change various `__affirm_value_is_defined` to `__affirm_variable_is_defined` where appoprirate
    - `__reverse` now has consistent distinct types of its return variables
    - `__iterate`:
        - `__iterate` no longer makes confusing assumptions, anytime arguments cannot be implied without confusion their specification will now be explicitly required, this solves our own incorrect usage on several occassions, and promotes better saner and easier to maintain argument usage and conventions
        - `__iterate` arguments have changed accordingly
        - `__iterate` now fails on incompatible argument combinations
        - `__iterate` now works on multi-length string lookups on a string source when not-overlapping
        - `__iterate` now works on another situation where an array match was accidentally skipping all indices of the lookup length, which was intended as string-only behaviour
    - `__unique` now properly supports zero-length values
    - `__slice` now supports `--quiet`
    - `__split` now supports multiple sources, and no longer supports delimiters after `--`
- `*`:
    - update for `__iterate`'s new explicit argument requirements, which actually fixes incorrect assumptions in several locations
    - update for `__split` now requiring `--stdin` when processing stdin
- `setup-mac-brew`: fix bad brew fix from earlier
- `fs-size`: add `--lines` support
- add `echo-max` for getting the maximum value of an input
- `dorothy-internals`:
    - only show diffs if below 100 lines
    - do not do the ansi trim, it is too slow
    - have `__eval` output a clearing progress
    - add and fix tests for everything - ansi helpers still WIP
    - better more readable test/fixture conventions

diff --git a/commands/fs-size b/commands/fs-size
--- a/commands/fs-size
+++ b/commands/fs-size
@@ -22,6 +22,9 @@ function fs_size_test() (
 		fs-size --nearest "$0"
 
 	eval-tester --ignore-outputs -- \
+		fs-size --lines "$0"
+
+	eval-tester --ignore-outputs -- \
 		fs-size -- "$0"
 
 	return 0
@@ -56,6 +59,8 @@ function fs_size() (
 			    Get the size in megabytes.
 			--gigabytes
 			    Get the size in gigabytes.
+			--lines
+			    Get the size in lines instead of bytes.
 		EOF
 		if [[ $# -ne 0 ]]; then
 			echo-error "$@"
@@ -77,6 +82,7 @@ function fs_size() (
 		'--megabytes' | '--denomination=megabytes') option_denomination='megabytes' ;;
 		'--gigabytes' | '--denomination=gigabytes') option_denomination='gigabytes' ;;
 		'--nearest' | '--denomination=nearest') option_denomination='nearest' ;;
+		'--lines' | '--denomination=lines') option_denomination='lines' ;;
 		'--')
 			option_paths+=("$@")
 			shift $#
@@ -213,7 +219,14 @@ function fs_size() (
 
 	function __size {
 		local path="$1"
-		if [[ -n $option_tool ]]; then
+		if [[ $option_denomination == 'lines' ]]; then
+			if is-directory -- "$path"; then
+				echo-error 'Cannot calculate the size in lines of ' --path="$path" ' as it is a directory.' || :
+				return 22 # EINVAL 22 Invalid argument
+			else
+				wc -l "$path" | __cut ' ' || return
+			fi
+		elif [[ -n $option_tool ]]; then
 			if [[ "$(type -t "__${option_tool}_${option_denomination}" || :)" == 'function' ]]; then
 				"__${option_tool}_${option_denomination}" "$path" # eval
 			else
