`sudo-inherit` => `sudo-helper`
needed to support `doas` as well as alpine (root user, no sudo, no doas)

diff --git a/commands/get-size b/commands/get-size
--- a/commands/get-size
+++ b/commands/get-size
@@ -52,60 +52,60 @@ function get-size() (
 	if test "$#" -eq 0; then
 		if is-mac; then
 			# size of the drives
-			eval-helper -- sudo diskutil list
+			eval-helper --quiet=no -- sudo-helper -- diskutil list
 		else
 			# size of the drives
-			eval-helper -- sudo fdisk -l
+			eval-helper --quiet=no -- sudo-helper -- fdisk -l
 			# size of the mounts
-			eval-helper -- sudo lsblk -e7
+			eval-helper --quiet=no -- sudo-helper -- lsblk -e7
 		fi
 	else
 		for path in "${option_paths[@]}"; do
 			path="$(fs-absolute "$path")"
 			if is-btrfs "$path"; then
 				# Show the structure of a filesystem
-				eval-helper -- sudo btrfs filesystem show
+				eval-helper --quiet=no -- sudo-helper -- btrfs filesystem show
 
 				# Show detailed information about internal allocations in devices.
-				eval-helper -- sudo btrfs device usage "$path"
+				eval-helper --quiet=no -- sudo-helper -- btrfs device usage "$path"
 
 				# Show detailed information about internal filesystem usage .
-				eval-helper -- sudo btrfs filesystem usage "$path"
+				eval-helper --quiet=no -- sudo-helper -- btrfs filesystem usage "$path"
 
 				# Show space usage information for a mount point
-				eval-helper -- sudo btrfs filesystem df "$path"
+				eval-helper --quiet=no -- sudo-helper -- btrfs filesystem df "$path"
 
 				# Show space usage via system
 				# -a, --all             include pseudo, duplicate, inaccessible file systems
 				# -h, --human-readable  print sizes in powers of 1024 (e.g., 1023M)
-				eval-helper -- df -ha "$path"
+				eval-helper --quiet=no -- sudo-helper -- df -ah "$path"
 
 				# Show status
-				eval-helper -- sudo btrfs device stats "$path"
-				eval-helper -- sudo btrfs scrub status "$path" || :   # if still running, exit code 1
-				eval-helper -- sudo btrfs balance status "$path" || : # if still running, exit code 1
+				eval-helper --quiet=no -- sudo-helper -- btrfs device stats "$path"
+				eval-helper --quiet=no -- sudo-helper -- btrfs scrub status "$path" || :   # if still running, exit code 1
+				eval-helper --quiet=no -- sudo-helper -- btrfs balance status "$path" || : # if still running, exit code 1
 
 				# Summarize disk usage of every nested file inside the directory
-				# sudo btrfs filesystem du --summarize --human-readable "$path"
+				# eval-helper --quiet=no -- sudo-helper -- btrfs filesystem du --summarize --human-readable "$path"
 
 				# Rename
-				# sudo btrfs filesystem label "$path" "$name"
+				# eval-helper --quiet=no -- sudo-helper -- btrfs filesystem label "$path" "$name"
 
 				# Change unallocated to free
-				# sudo btrfs filesystem resize max "$path"
+				# eval-helper --quiet=no -- sudo-helper -- btrfs filesystem resize max "$path"
 
 				# Defragment (balance also defrags)
-				# sudo btrfs filesystem defragment "$path"
+				# eval-helper --quiet=no -- sudo-helper -- btrfs filesystem defragment "$path"
 
 				# Balance as raid1
-				# sudo btrfs balance start --background -dconvert=raid1 -mconvert=raid1 "$path"
+				# eval-helper --quiet=no -- sudo-helper -- btrfs balance start --background -dconvert=raid1 -mconvert=raid1 "$path"
 
 				# Scrub (check filesystem for errors and auto-heal)
-				# sudo btrfs scrub start "$path"
+				# eval-helper --quiet=no -- sudo-helper -- btrfs scrub start "$path"
 
 				# Check devices for errors
 				# WARNING: the repair mode is considered dangerous and should not be used without prior analysis of problems found on the filesystem.
-				# sudo btrfs check --repair --progress /dev/...
+				# eval-helper --quiet=no -- sudo-helper -- btrfs check --repair --progress /dev/...
 
 				# Logs
 				# tail -n 1000 -f /var/log/syslog | grep --fixed-strings --regexp='BTRFS'
@@ -118,7 +118,7 @@ function get-size() (
 			elif test -f "$path"; then
 				# path is a file
 				#   -h, --human-readable  print sizes in human readable format (e.g., 1K 234M 2G)
-				eval-helper -- du -h "$path"
+				eval-helper --quiet=no -- du -h "$path"
 
 			else
 				# path is a directory
@@ -146,7 +146,7 @@ function get-size() (
 					#   -h, --human-readable  print sizes in human readable format (e.g., 1K 234M 2G)
 					#   -d, --max-depth=N     print the total for a directory (or file, with --all)
 				fi
-				eval-helper -- du "${opts[@]}" "$path"
+				eval-helper --quiet=no -- du "${opts[@]}" "$path"
 			fi
 		done
 	fi
diff --git a/commands/set-hostname b/commands/set-hostname
--- a/commands/set-hostname
+++ b/commands/set-hostname
@@ -61,15 +61,15 @@ function set-hostname() (
 		# https://wiki.alpinelinux.org/wiki/Alpine_setup_scripts#setup-hostname
 		setup-hostname -n "$hostname"
 	elif command-exists 'hostname'; then
-		sudo hostname "$hostname"
+		sudo-helper -- hostname "$hostname"
 	elif command-exists 'hostnamectl'; then
-		sudo hostnamectl set-hostname "$hostname"
+		sudo-helper -- hostnamectl set-hostname "$hostname"
 	elif test -f '/etc/hostname'; then
-		echo "$hostname" | sudo tee -a /etc/hostname
+		echo "$hostname" | sudo-helper -- tee -a /etc/hostname
 	elif test -f '/proc/sys/kernel/hostname'; then
-		echo "$hostname" | sudo tee -a /proc/sys/kernel/hostname
+		echo "$hostname" | sudo-helper -- tee -a /proc/sys/kernel/hostname
 	elif command-exists 'sysctl'; then
-		sudo sysctl kernel.hostname="$hostname"
+		sudo-helper -- sysctl kernel.hostname="$hostname"
 	else
 		return 19 # ENODEV 19 Operation not supported by device
 	fi
@@ -77,7 +77,7 @@ function set-hostname() (
 	# write the hostname to the /etc/hosts file, this was necessary for a forgotten reason
 	# instead of two --expression, can also do -e 's//; s//'
 	# don't use sd, as this runs in initial setup
-	sudo-inherit -- gsed --null-data --in-place --regexp-extended \
+	sudo-helper --inherit -- gsed --null-data --in-place --regexp-extended \
 		--expression="s#127.0.0.1\s+($original|$hostname)\n##g" \
 		--expression="s#(\s+)localhost\n#\1localhost\n127.0.0.1\1$hostname\n#" \
 		/etc/hosts
@@ -85,11 +85,11 @@ function set-hostname() (
 
 	# restart the name server
 	if command-exists systemctl; then
-		sudo systemctl restart nmbd || : # fails on opensuse, but is applied right away
+		sudo-helper -- systemctl restart nmbd || : # fails on opensuse, but is applied right away
 	elif test -x /etc/init.d/hostname; then
 		/etc/init.d/hostname restart
 	elif test -f /etc/sysconfig/network; then
-		sudo-inherit -- config-helper --file='/etc/sysconfig/network' -- \
+		sudo-helper --inherit -- config-helper --file='/etc/sysconfig/network' -- \
 			--field='HOSTNAME' --no-quote --value="$hostname"
 	else
 		return 19 # ENODEV 19 Operation not supported by device
diff --git a/commands/setup-dns b/commands/setup-dns
--- a/commands/setup-dns
+++ b/commands/setup-dns
@@ -218,9 +218,9 @@ function setup-dns() (
 		if is-mac; then
 			# get its basename which is the service id
 			id="$(fs-filename --basename "$file")"
-			eval-helper -- sudo launchctl stop "$id" || :
+			eval-helper -- sudo-helper -- launchctl stop "$id" || :
 		else
-			sudo systemctl stop "$file" || :
+			sudo-helper -- systemctl stop "$file" || :
 		fi
 	}
 
@@ -242,13 +242,13 @@ function setup-dns() (
 			# -w      Additionally disables the service such that future load
 			#         operations will result in a service which launchd tracks but
 			#         cannot be launched or discovered in any way.
-			eval-helper -- sudo launchctl disable "system/$id" || :
-			eval-helper -- sudo launchctl stop "$id" || :
-			eval-helper -- sudo launchctl unload -w "$file" || :
+			eval-helper -- sudo-helper -- launchctl disable "system/$id" || :
+			eval-helper -- sudo-helper -- launchctl stop "$id" || :
+			eval-helper -- sudo-helper -- launchctl unload -w "$file" || :
 			do_rm -- /Library/Logs/*"$id"*.log || :
 		else
-			sudo systemctl disable --now "$file" || :
-			sudo systemctl status "$id" --no-pager || :
+			sudo-helper -- systemctl disable --now "$file" || :
+			sudo-helper -- systemctl status "$id" --no-pager || :
 		fi
 		do_rm -- "$file"
 	}
@@ -260,8 +260,8 @@ function setup-dns() (
 		if is-mac; then
 			# ensure correct permissions, not sure why
 			# but [homebrew services] does this, so doing it here
-			sudo chown root:admin "$file"
-			sudo chmod +t "$file"
+			sudo-helper -- chown root:admin "$file"
+			sudo-helper -- chmod +t "$file"
 
 			# Usage: launchctl load <service-path, service-path2, ...>
 			# -w      If the service is disabled, it will be enabled. In previous
@@ -276,14 +276,14 @@ function setup-dns() (
 			#         unlike the -w flag, this flag will not  modify the service's
 			#         disabled state; it will instead only ignore it for the load
 			#         operation.
-			eval-helper -- sudo launchctl load -w "$file" || :
-			# eval-helper -- sudo launchctl enable "system/$id" || :
-			eval-helper -- sudo launchctl start "$id" || :
+			eval-helper -- sudo-helper -- launchctl load -w "$file" || :
+			# eval-helper -- sudo-helper -- launchctl enable "system/$id" || :
+			eval-helper -- sudo-helper -- launchctl start "$id" || :
 			sleep 2
 			cat /Library/Logs/*"$id"*.log || :
 		else
-			sudo systemctl enable --now "$file" || :
-			sudo systemctl status "$id" --no-pager || :
+			sudo-helper -- systemctl enable --now "$file" || :
+			sudo-helper -- systemctl status "$id" --no-pager || :
 		fi
 	}
 
@@ -341,7 +341,7 @@ function setup-dns() (
 						ls -la "$rm_path"
 					)"
 				)"; then
-					sudo rm -rf "$rm_path"
+					sudo-helper -- rm -rf "$rm_path"
 				fi
 			fi
 		done
@@ -349,8 +349,8 @@ function setup-dns() (
 		# after service additions/removals
 		# systemctl needs to be reloaded apparently
 		if is-linux; then
-			sudo systemctl daemon-reload
-			sudo systemctl reset-failed
+			sudo-helper -- systemctl daemon-reload
+			sudo-helper -- systemctl reset-failed
 			# ^ use sudo, otherwise prompted via ubuntu user password
 		fi
 	}
@@ -751,7 +751,7 @@ function setup-dns() (
 			# apply
 			local interface
 			network-interface list | while read -r interface; do
-				sudo networksetup -setdnsservers "$interface" "${servers[@]}"
+				sudo-helper -- networksetup -setdnsservers "$interface" "${servers[@]}"
 			done
 
 			# log
@@ -792,12 +792,12 @@ function setup-dns() (
 			echo-segment --h1="Configure and $action_title $systemd_title"
 
 			# apply changes to services
-			sudo systemctl stop systemd-networkd || :
-			sudo systemctl stop systemd-resolved || :
+			sudo-helper -- systemctl stop systemd-networkd || :
+			sudo-helper -- systemctl stop systemd-resolved || :
 
 			# make life simple, using only /etc/resolv.conf
 			# https://www.freedesktop.org/software/systemd/man/resolved.conf.html
-			sudo rm -rf \
+			sudo-helper -- rm -rf \
 				/run/systemd/resolve/stub-resolv.conf \
 				/usr/lib/systemd/resolv.conf \
 				/run/systemd/resolve/resolv.conf \
@@ -819,7 +819,7 @@ function setup-dns() (
 			# apply specific config
 			if test "$action" = 'enable'; then
 				# using systemd, the initial lines are for ping/nslookup/etc, the [Resolve] lines are for systemd-resolve
-				sudo tee /etc/resolv.conf <<-EOF
+				sudo-helper -- tee /etc/resolv.conf <<-EOF
 					nameserver 127.0.0.53
 					options edns0 trust-ad
 					search .
@@ -832,20 +832,20 @@ function setup-dns() (
 				EOF
 			else
 				# use custom service
-				sudo tee /etc/resolv.conf <<-EOF
+				sudo-helper -- tee /etc/resolv.conf <<-EOF
 					nameserver ${servers[0]}
 					options edns0 trust-ad
 				EOF
 			fi
 
 			# temporarily start system services, so that changes can be applied to them
-			# sudo systemctl daemon-reload
-			# sudo systemctl start systemd-networkd
-			sudo systemctl start systemd-resolved
+			# sudo-helper -- systemctl daemon-reload
+			# sudo-helper -- systemctl start systemd-networkd
+			sudo-helper -- systemctl start systemd-resolved
 
 			# flush any caches
-			sudo resolvectl flush-caches --no-pager || :
-			sudo resolvectl reset-server-features --no-pager || :
+			sudo-helper -- resolvectl flush-caches --no-pager || :
+			sudo-helper -- resolvectl reset-server-features --no-pager || :
 
 			# apply changes to interfaces
 			mapfile -t interfaces < <(network-interface list)
@@ -855,14 +855,14 @@ function setup-dns() (
 			fi
 			for interface in "${interfaces[@]}"; do
 				# remove other changes
-				sudo resolvectl revert "$interface" || continue
+				sudo-helper -- resolvectl revert "$interface" || continue
 
 				# apply intended changes
-				sudo resolvectl default-route "$interface" false
-				sudo resolvectl domain "$interface" "$Domains"
-				sudo resolvectl dnssec "$interface" "$DNSSEC"
-				sudo resolvectl dnsovertls "$interface" "$DNSOverTLS"
-				sudo resolvectl dns "$interface" "${servers[@]}"
+				sudo-helper -- resolvectl default-route "$interface" false
+				sudo-helper -- resolvectl domain "$interface" "$Domains"
+				sudo-helper -- resolvectl dnssec "$interface" "$DNSSEC"
+				sudo-helper -- resolvectl dnsovertls "$interface" "$DNSOverTLS"
+				sudo-helper -- resolvectl dns "$interface" "${servers[@]}"
 
 				# reboot the interface
 				sleep 1
@@ -872,17 +872,17 @@ function setup-dns() (
 			# now that it is all done, enable or disable
 			if test "$action" = 'enable'; then
 				# enable
-				sudo systemctl enable --now systemd-resolved
+				sudo-helper -- systemctl enable --now systemd-resolved
 
 				# verify
 				verify_dns_resolvectl
 			else
-				sudo systemctl disable --now systemd-resolved
+				sudo-helper -- systemctl disable --now systemd-resolved
 			fi
 
 			# after significant systemd changes, it may need to be reloaded
-			# sudo systemctl daemon-reload
-			# sudo systemctl reset-failed
+			# sudo-helper -- systemctl daemon-reload
+			# sudo-helper -- systemctl reset-failed
 
 			# log
 			echo-segment --g1="Configure and $action_title $systemd_title"
@@ -938,7 +938,7 @@ function setup-dns() (
 		check_installation "$aghome_id" "$aghome_bin_file"
 
 		# ensure directories
-		sudo mkdir -p "$aghome_conf_dir" "$aghome_data_dir" "$aghome_state_dir"
+		sudo-helper -- mkdir -p "$aghome_conf_dir" "$aghome_data_dir" "$aghome_state_dir"
 
 		# download the installer, prior to disabling
 		temp_bin_file="$(fs-temp)"
@@ -951,10 +951,10 @@ function setup-dns() (
 		if test -f "$temp_bin_file"; then
 			if test -x "$aghome_bin_file"; then
 				# only tell prior cmd to stop if the prior cmd exists
-				sudo "${aghome_bin_cmd[@]}" --service stop || :
+				sudo-helper -- "${aghome_bin_cmd[@]}" --service stop || :
 			fi
-			sudo mv "$temp_bin_file" "$aghome_bin_file" || :
-			sudo chmod +x "$aghome_bin_file" || :
+			sudo-helper -- mv "$temp_bin_file" "$aghome_bin_file" || :
+			sudo-helper -- chmod +x "$aghome_bin_file" || :
 			# ^ allow failure,s as we will check this later
 		fi
 
@@ -977,8 +977,8 @@ function setup-dns() (
 		echo-segment --h1="Uninstall $aghome_title"
 
 		# stop and uninstall the service
-		sudo "${aghome_bin_cmd[@]}" --service stop || :
-		sudo "${aghome_bin_cmd[@]}" --service uninstall || :
+		sudo-helper -- "${aghome_bin_cmd[@]}" --service stop || :
+		sudo-helper -- "${aghome_bin_cmd[@]}" --service uninstall || :
 
 		# ensure adguard home has stopped
 		killall "$aghome_id" || :
@@ -1004,13 +1004,13 @@ function setup-dns() (
 
 		# this is here, because we need to seed the configuration file before we can do changes to it
 		if test ! -f "$aghome_conf_file" -a "$action" = 'enable'; then
-			sudo "${aghome_bin_cmd[@]}" --service install || :
-			sudo "${aghome_bin_cmd[@]}" --service start || :
+			sudo-helper -- "${aghome_bin_cmd[@]}" --service install || :
+			sudo-helper -- "${aghome_bin_cmd[@]}" --service start || :
 			confirm --ppid=$$ -- "Press any key once you have completed the initial $aghome_title setup..."
 		fi
 
 		# stop before config update
-		sudo "${aghome_bin_cmd[@]}" --service stop || :
+		sudo-helper -- "${aghome_bin_cmd[@]}" --service stop || :
 
 		# prepare desired providers
 		upstream_servers=(
@@ -1032,17 +1032,17 @@ function setup-dns() (
 		for server in "${upstream_servers[@]}"; do
 			replace+="  - $server"$'\n'
 		done
-		sudo-inherit -- sd "$pattern" "$replace" "$aghome_conf_file"
-		sudo "${aghome_bin_cmd[@]}" --check-config
+		sudo-helper --inherit -- sd "$pattern" "$replace" "$aghome_conf_file"
+		sudo-helper -- "${aghome_bin_cmd[@]}" --check-config
 
 		# enable or disable
 		# Service control action: status, install, uninstall, start, stop, restart, reload (configuration).
 		if test "$action" = 'enable'; then
-			sudo "${aghome_bin_cmd[@]}" --service install || :
-			sudo "${aghome_bin_cmd[@]}" --service reload || sudo "${aghome_bin_cmd[@]}" --service start || :
-			sudo "${aghome_bin_cmd[@]}" --service status || :
+			sudo-helper -- "${aghome_bin_cmd[@]}" --service install || :
+			sudo-helper -- "${aghome_bin_cmd[@]}" --service reload || sudo-helper -- "${aghome_bin_cmd[@]}" --service start || :
+			sudo-helper -- "${aghome_bin_cmd[@]}" --service status || :
 		else
-			sudo "${aghome_bin_cmd[@]}" --service uninstall || :
+			sudo-helper -- "${aghome_bin_cmd[@]}" --service uninstall || :
 		fi
 
 		# log
@@ -1110,16 +1110,16 @@ function setup-dns() (
 		check_installation "$dnscrypt_id" "$dnscrypt_bin_file"
 
 		# ensure directories
-		sudo mkdir -p "$dnscrypt_conf_dir"
+		sudo-helper -- mkdir -p "$dnscrypt_conf_dir"
 
 		# if downloaded, stop and install
 		if test -f "$temp_bin_file"; then
 			if test -x "$dnscrypt_bin_file"; then
 				# only tell prior cmd to stop if the prior cmd exists
-				sudo "${dnscrypt_bin_cmd[@]}" --service stop || :
+				sudo-helper -- "${dnscrypt_bin_cmd[@]}" --service stop || :
 			fi
-			sudo mv "$temp_bin_file" "$dnscrypt_bin_file" || :
-			sudo chmod +x "$dnscrypt_bin_file" || :
+			sudo-helper -- mv "$temp_bin_file" "$dnscrypt_bin_file" || :
+			sudo-helper -- chmod +x "$dnscrypt_bin_file" || :
 			# ^ allow failure,s as we will check this later
 		fi
 
@@ -1136,7 +1136,7 @@ function setup-dns() (
 				--ref='master' \
 				--pathname='dnscrypt-proxy/example-dnscrypt-proxy.toml' \
 				--path="$temp_conf_file"
-			sudo mv "$temp_conf_file" "$dnscrypt_conf_file"
+			sudo-helper -- mv "$temp_conf_file" "$dnscrypt_conf_file"
 		fi
 
 		# confirm success
@@ -1158,8 +1158,8 @@ function setup-dns() (
 		echo-segment --h1="Uninstall $dnscrypt_title"
 
 		# stop and uninstall the service
-		sudo "${dnscrypt_bin_cmd[@]}" --service stop || :
-		sudo "${dnscrypt_bin_cmd[@]}" --service uninstall || :
+		sudo-helper -- "${dnscrypt_bin_cmd[@]}" --service stop || :
+		sudo-helper -- "${dnscrypt_bin_cmd[@]}" --service uninstall || :
 
 		# ensure adguard home has stopped
 		killall "$dnscrypt_id" || :
@@ -1206,12 +1206,12 @@ function setup-dns() (
 		fi
 
 		# stop before config update
-		sudo "${dnscrypt_bin_cmd[@]}" --service stop || :
-		sudo "${dnscrypt_bin_cmd[@]}" --service disable || :
+		sudo-helper -- "${dnscrypt_bin_cmd[@]}" --service stop || :
+		sudo-helper -- "${dnscrypt_bin_cmd[@]}" --service disable || :
 
 		# update the configuration with the new [dnscrypt_names], if any
 		if test "${#dnscrypt_names[@]}" -ne 0; then
-			sudo-inherit -- config-helper --file="$dnscrypt_conf_file" -- \
+			sudo-helper --inherit -- config-helper --file="$dnscrypt_conf_file" -- \
 				--field='ipv4_servers' --no-quote --value='true' \
 				--field='ipv6_servers' --no-quote --value='true' \
 				--field='dnscrypt_servers' --no-quote --value='true' \
@@ -1219,18 +1219,18 @@ function setup-dns() (
 				--field='server_names' --no-quote --value="[$(
 					echo-join ', ' -- "${dnscrypt_names[@]@Q}"
 				)]"
-			sudo "${dnscrypt_bin_cmd[@]}" --check -config "$dnscrypt_conf_file"
+			sudo-helper -- "${dnscrypt_bin_cmd[@]}" --check -config "$dnscrypt_conf_file"
 		fi
 
 		# enable or disable
 		if test "$action" = 'enable'; then
-			sudo "${dnscrypt_bin_cmd[@]}" --service install || :
-			sudo "${dnscrypt_bin_cmd[@]}" --service enable || :
-			sudo "${dnscrypt_bin_cmd[@]}" --service start || :
+			sudo-helper -- "${dnscrypt_bin_cmd[@]}" --service install || :
+			sudo-helper -- "${dnscrypt_bin_cmd[@]}" --service enable || :
+			sudo-helper -- "${dnscrypt_bin_cmd[@]}" --service start || :
 		else
-			sudo "${dnscrypt_bin_cmd[@]}" --service stop || :
-			sudo "${dnscrypt_bin_cmd[@]}" --service disable || :
-			sudo "${dnscrypt_bin_cmd[@]}" --service uninstall || :
+			sudo-helper -- "${dnscrypt_bin_cmd[@]}" --service stop || :
+			sudo-helper -- "${dnscrypt_bin_cmd[@]}" --service disable || :
+			sudo-helper -- "${dnscrypt_bin_cmd[@]}" --service uninstall || :
 		fi
 
 		# log
@@ -1303,8 +1303,8 @@ function setup-dns() (
 		# if downloaded, stop and install
 		if test -f "$temp_bin_file"; then
 			service_stop "$cloudflared_proxy_service_file"
-			sudo mv "$temp_bin_file" "$cloudflared_bin_file"
-			sudo chmod +x "$cloudflared_bin_file"
+			sudo-helper -- mv "$temp_bin_file" "$cloudflared_bin_file"
+			sudo-helper -- chmod +x "$cloudflared_bin_file"
 		fi
 
 		# confirm success
@@ -1389,7 +1389,7 @@ function setup-dns() (
 				done
 
 				# create service with custom upstreams
-				sudo tee "$cloudflared_proxy_service_file" >/dev/null <<EOF
+				sudo-helper -- tee "$cloudflared_proxy_service_file" >/dev/null <<EOF
 <?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
@@ -1425,7 +1425,7 @@ EOF
 				done
 
 				# create service with custom upstreams
-				sudo tee "$cloudflared_proxy_service_file" >/dev/null <<-EOF
+				sudo-helper -- tee "$cloudflared_proxy_service_file" >/dev/null <<-EOF
 					[Unit]
 					Description=${cloudflared_proxy_service_id}
 					Wants=network-online.target nss-lookup.target
@@ -1469,7 +1469,7 @@ EOF
 
 		# make tunnel directories
 		mkdir -p "$tunnel_user_dir"
-		sudo mkdir -p "$tunnel_conf_dir"
+		sudo-helper -- mkdir -p "$tunnel_conf_dir"
 	}
 	function tunnel_uninstall {
 		local service_file
@@ -1581,10 +1581,10 @@ EOF
 			--credentials-file "$temp_cred_file" \
 			"$tunnel"
 		chmod 660 "$temp_cred_file"
-		sudo mv "$temp_cred_file" "$tunnel_cred_file"
+		sudo-helper -- mv "$temp_cred_file" "$tunnel_cred_file"
 
 		# route create
-		sudo tee "$tunnel_conf_file" >/dev/null <<-EOF
+		sudo-helper -- tee "$tunnel_conf_file" >/dev/null <<-EOF
 			tunnel: ${tunnel}
 			credentials-file: ${tunnel_cred_file}
 			${ingress}
@@ -1598,7 +1598,7 @@ EOF
 
 		# service create
 		if is-mac; then
-			sudo tee "$tunnel_service_file" >/dev/null <<EOF
+			sudo-helper -- tee "$tunnel_service_file" >/dev/null <<EOF
 <?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
@@ -1631,10 +1631,10 @@ EOF
 EOF
 
 			# update macos service permissions
-			sudo chown root:admin "$tunnel_service_file"
-			sudo chmod +t "$tunnel_service_file"
+			sudo-helper -- chown root:admin "$tunnel_service_file"
+			sudo-helper -- chmod +t "$tunnel_service_file"
 		else
-			sudo tee "$tunnel_service_file" >/dev/null <<-EOF
+			sudo-helper -- tee "$tunnel_service_file" >/dev/null <<-EOF
 				[Unit]
 				Description=${tunnel_service_id}
 				After=network.target
@@ -1800,13 +1800,13 @@ EOF
 	# https://eff-certbot.readthedocs.io/en/stable/using.html
 	# https://certbot-dns-cloudflare.readthedocs.io/en/stable/
 	# function letsencrypt {
-	# 	sudo snap install core
-	# 	sudo snap refresh core
-	# 	sudo apt-get remove certbot
+	# 	sudo-helper -- snap install core
+	# 	sudo-helper -- snap refresh core
+	# 	sudo-helper -- apt-get remove certbot
 
-	# 	sudo snap install --classic certbot
-	# 	sudo snap set certbot trust-plugin-with-root=ok
-	# 	sudo snap install certbot-dns-cloudflare
+	# 	sudo-helper -- snap install --classic certbot
+	# 	sudo-helper -- snap set certbot trust-plugin-with-root=ok
+	# 	sudo-helper -- snap install certbot-dns-cloudflare
 
 	# 	mkdir -p .secrets/certbot
 	# 	vim ~/.secrets/certbot/cloudflare.ini
@@ -1814,9 +1814,9 @@ EOF
 	# 	chmod -R 700 ~/.secrets
 	# 	chmod 600 ~/.secrets/certbot/cloudflare.ini
 
-	# 	sudo certbot certonly --dns-cloudflare --dns-cloudflare-credentials ~/.secrets/certbot/cloudflare.ini -d dns.lupton.cc
+	# 	sudo-helper -- certbot certonly --dns-cloudflare --dns-cloudflare-credentials ~/.secrets/certbot/cloudflare.ini -d dns.lupton.cc
 
-	# 	sudo certbot renew --dry-run
+	# 	sudo-helper -- certbot renew --dry-run
 	# }
 
 	# nofap
diff --git a/commands/setup-linux b/commands/setup-linux
--- a/commands/setup-linux
+++ b/commands/setup-linux
@@ -138,28 +138,28 @@ function setup-linux() (
 	}
 
 	function do_apt_update {
-		sudo apt-get update -y
+		sudo-helper -- apt-get update -y
 	}
 
 	function do_dnf_update {
-		sudo dnf check-update -y
+		sudo-helper -- dnf check-update -y
 	}
 
 	function do_pacman_update {
 		# init the local database
 		# this is needed on systems which pacman was installed
-		sudo pacman-key --init
+		sudo-helper -- pacman-key --init
 		# refresh the local database
-		sudo pacman --refresh --sync --noconfirm
+		sudo-helper -- pacman --refresh --sync --noconfirm
 	}
 
 	function do_yum_update {
-		sudo yum check-update -y || :
+		sudo-helper -- yum check-update -y || :
 		# ^ it always returns exit code 100
 	}
 
 	function do_zypper_update {
-		sudo zypper --non-interactive --gpg-auto-import-keys refresh
+		sudo-helper -- zypper --non-interactive --gpg-auto-import-keys refresh
 	}
 
 	# -------------------------------------
@@ -182,20 +182,20 @@ function setup-linux() (
 	}
 
 	function do_apt_upgrade {
-		sudo apt-get full-upgrade -y
+		sudo-helper -- apt-get full-upgrade -y
 	}
 
 	function do_dnf_upgrade {
-		sudo dnf upgrade -y --best
+		sudo-helper -- dnf upgrade -y --best
 	}
 
 	function do_flatpak_upgrade {
-		sudo flatpak update -y
+		sudo-helper -- flatpak update -y
 		# ^ sudo with flatpak avoids gui sudo prompt
 	}
 
 	function do_pamac_upgrade {
-		sudo pamac upgrade --no-confirm
+		sudo-helper -- pamac upgrade --no-confirm
 		# ^ sudo with pamac avoids gui sudo prompt
 		# ^ `pamac update` is an alias for `pamac upgrade`
 	}
@@ -204,15 +204,15 @@ function setup-linux() (
 		if ! is-snap; then
 			return 0
 		fi
-		sudo snap refresh || : # if snap was just installed on fedora, this can fail initially
+		sudo-helper -- snap refresh || : # if snap was just installed on fedora, this can fail initially
 	}
 
 	function do_yum_upgrade {
-		sudo yum upgrade -y --best
+		sudo-helper -- yum upgrade -y --best
 	}
 
 	function do_zypper_upgrade {
-		sudo zypper --non-interactive --gpg-auto-import-keys update --no-confirm --best-effort
+		sudo-helper -- zypper --non-interactive --gpg-auto-import-keys update --no-confirm --best-effort
 	}
 
 	# -------------------------------------
@@ -279,32 +279,32 @@ function setup-linux() (
 	)
 
 	function do_apt_clean {
-		sudo apt-get autoremove -y --purge
-		sudo apt-get autoclean -y
-		sudo apt-get clean -y
+		sudo-helper -- apt-get autoremove -y --purge
+		sudo-helper -- apt-get autoclean -y
+		sudo-helper -- apt-get clean -y
 	}
 
 	function do_dnf_clean {
-		sudo dnf clean all
+		sudo-helper -- dnf clean all
 	}
 
 	function do_pamac_clean {
-		sudo pamac clean --no-confirm
+		sudo-helper -- pamac clean --no-confirm
 		# ^ sudo with pamac avoids gui sudo prompt
 	}
 
 	function do_pacman_clean {
 		# -c, --clean
 		#   Remove packages that are no longer installed from the cache as well as currently unused sync databases to free up disk space.
-		sudo pacman --sync --noconfirm --clean
+		sudo-helper -- pacman --sync --noconfirm --clean
 	}
 
 	function do_yum_clean {
-		sudo yum clean all
+		sudo-helper -- yum clean all
 	}
 
 	function do_zypper_clean {
-		sudo zypper --non-interactive --gpg-auto-import-keys clean --all
+		sudo-helper -- zypper --non-interactive --gpg-auto-import-keys clean --all
 	}
 
 	# -------------------------------------
@@ -318,7 +318,7 @@ function setup-linux() (
 		if do-release-upgrade -c; then
 			# if there is one, then ask the user if they want to upgrade to it
 			if confirm-negative --ppid=$$ -- 'Upgrade the distribtion release?'; then
-				sudo do-release-upgrade
+				sudo-helper -- do-release-upgrade
 			fi
 		fi
 	}
