get-terminal-theme: don't check stdin+stderr as that is noisey

diff --git a/commands/get-terminal-theme b/commands/get-terminal-theme
--- a/commands/get-terminal-theme
+++ b/commands/get-terminal-theme
@@ -74,29 +74,27 @@ function get_terminal_theme() (
 	function get_theme_via_ansi_query {
 		# If the background color is `ba1a2b3c` the read will return `1a74/2b98/3cb6`
 		local _ color='' r g b l
-		# stdin+stderr must be readable+writable for the read to work
-		if (: </dev/stdin >/dev/stdin) && (: </dev/stderr >/dev//stderr); then
-			IFS=: read -s -t "$(get_read_decimal_timeout 0.01)" -d $'\a' -p $'\e]11;?\a' _ color || :
-			if test -n "$color"; then
-				# Fetch the first two characters of [1a]74/[2b]98/[3c]b6 which is our color, and convert from hexadecimal to decimal
-				# For what the latter two characters are, no one seems to know: https://unix.stackexchange.com/q/754952/50703
-				r=$((16#${color:0:2}))  # 1a => 26
-				g=$((16#${color:5:2}))  # 2b => 43
-				b=$((16#${color:10:2})) # 3c => 60
+		# stdin+stderr must be readable+writable for the read to work, but we can't check silently, as failures are noisey, and silencing the failures causes them to close: https://gist.github.com/balupton/6eee015345c663d7d7baf83d8e20ce1f so just note in this comment
+		IFS=: read -s -t "$(get_read_decimal_timeout 0.01)" -d $'\a' -p $'\e]11;?\a' _ color || :
+		if test -n "$color"; then
+			# Fetch the first two characters of [1a]74/[2b]98/[3c]b6 which is our color, and convert from hexadecimal to decimal
+			# For what the latter two characters are, no one seems to know: https://unix.stackexchange.com/q/754952/50703
+			r=$((16#${color:0:2}))  # 1a => 26
+			g=$((16#${color:5:2}))  # 2b => 43
+			b=$((16#${color:10:2})) # 3c => 60
 
-				# Figure out the lightness from HSL
-				max=$((r > g ? (r > b ? r : b) : (g > b ? g : b)))
-				min=$((r < g ? (r < b ? r : b) : (g < b ? g : b)))
-				l=$(((max + min) * 50 / 255))
+			# Figure out the lightness from HSL
+			max=$((r > g ? (r > b ? r : b) : (g > b ? g : b)))
+			min=$((r < g ? (r < b ? r : b) : (g < b ? g : b)))
+			l=$(((max + min) * 50 / 255))
 
-				# Is the lightness dark or light?
-				if ((l < 50)); then
-					print_line 'dark'
-				else
-					print_line 'light'
-				fi
-				return 0
+			# Is the lightness dark or light?
+			if ((l < 50)); then
+				print_line 'dark'
+			else
+				print_line 'light'
 			fi
+			return 0
 		fi
 		return 200 # ECUSTOM 200 Not applicable
 	}
