fix configuration modifiers
`config-*` scripts merged into `config-helper` script which works properly and has more power

`sudo-inherit` added for when you want dorothy scripts to run in sudo mode

`ripgrep.bash` added to workaround ripgrep sillyness (outputting colors and line numbers) which is not what we want to do

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/get-flag-value b/commands/get-flag-value
--- a/commands/get-flag-value
+++ b/commands/get-flag-value
@@ -4,31 +4,71 @@ source "$DOROTHY/sources/strict.bash"
 flag="${1-}"
 
 # shellcheck disable=2016
-if test -z "$flag"; then
-	stderr echo 'USAGE:'
-	stderr echo 'get-flag-value <flag> [--multi] -- <--flag=value> <--flag> <--no-flag> ...'
-	stderr echo
-	stderr echo '--flag becomes yes'
-	stderr echo '--no-flag becomes no'
-	stderr echo
-	stderr echo '--flag= is ignored'
-	stderr echo
-	stderr echo 'by default only returns first instance, if wanting duplicates:'
-	stderr echo 'mapfile -t a < <(env MULTI=yes get-flag-value a -- --a --a)'
-	stderr echo
-	stderr echo 'DOES NOT SUPPORT: --flag value'
-	stderr echo 'IT ONLY SUPPORTS: --flag=value'
-	stderr echo
-	exit 1
+if test -z "$flag" -o "$flag" = '--help' -o "$flag" = '-h'; then
+	stderr echo-lines \
+		'USAGE:' \
+		'get-flag-value <flag> [--multi] [--yes=...] [--no=...] [--missing=...] -- <--flag=value> <--flag> <--no-flag> ...' \
+		'' \
+		'FLAGS:' \
+		'Provide [--multi] to output the value for each occurence of the flag, instead of just the first.' \
+		'Provide [--yes=...] to customise the value for when the flag is provided without any value.' \
+		'Provide [--missing=...] to customise the value for when the flag is missing.' \
+		''
+		'QUIRKS:' \
+		'It does not support [--flag value], only [--[no-]flag=[value]].' \
+		'' \
+		'EXAMPLES:' \
+		'' \
+		'get-flag-value var -- ' \
+		'^ outputs nothing' \
+		'' \
+		'get-flag-value var -- --var' \
+		'^ outputs: yes' \
+		'' \
+		'get-flag-value var -- --no-var' \
+		'^ outputs: no' \
+		'' \
+		'get-flag-value var -- --var=value' \
+		'^ outputs: value' \
+		'' \
+		'get-flag-value var -- --var=' \
+		'^ outputs an empty line' \
+		'' \
+		'get-flag-value var --yes=yup --no=nada --missing=gone -- --var' \
+		'^ outputs: yup' \
+		'' \
+		'get-flag-value var --yes=yup --no=nada --missing=gone -- --var=yes' \
+		'^ outputs: yes' \
+		'' \
+		'get-flag-value var --yes=yup --no=nada --missing=gone -- --no-var' \
+		'^ outputs: nada' \
+		'' \
+		'get-flag-value var --yes=yup --no=nada --missing=gone -- --var=no' \
+		'^ outputs: no' \
+		'' \
+		'get-flag-value var --yes=yup --no=nada --missing=gone --' \
+		'^ outputs: gone' \
+		''
+	exit 22 # Invalid argument
 fi
 
 # cycle
+yes='yes'
+no='no'
+# don't set missing, as we don't want it to be defined to nothing and then use nothing
+found='no'
 multi='no'
 process='no'
 for arg in "${@:2}"; do
 	# handle our own options
 	if test "$process" = 'no'; then
-		if test "$arg" = '--multi'; then
+		if [[ "$arg" = '--yes='* ]]; then
+			yes="${arg:6}"
+		elif [[ "$arg" = '--no='* ]]; then
+			no="${arg:5}"
+		elif [[ "$arg" = '--missing='* ]]; then
+			missing="${arg:10}"
+		elif test "$arg" = '--multi'; then
 			multi='yes'
 		elif test "$arg" = '--'; then
 			process='yes'
@@ -59,11 +99,12 @@ for arg in "${@:2}"; do
 		# not our flag
 		continue
 	fi
+	found='yes'
 
 	# get the value
 	value="${arg:index+${#flag}}"
 	if test -z "$value"; then
-		value='yes'
+		value="$yes"
 	elif test "${value:0:1}" = '='; then
 		# is a proper value, trim =
 		value="${value:1}"
@@ -71,10 +112,10 @@ for arg in "${@:2}"; do
 
 	# perform inversion
 	if test "$inverted" = 'yes'; then
-		if test "$value" = 'yes'; then
-			value='no'
-		elif test "$value" = 'no'; then
-			value='yes'
+		if test "$value" = "$yes"; then
+			value="$no"
+		elif test "$value" = "$no"; then
+			value="$yes"
 		fi
 	fi
 
@@ -86,3 +127,7 @@ for arg in "${@:2}"; do
 		break
 	fi
 done
+
+if test "$found" = 'no' -a -v 'missing'; then
+	echo "$missing"
+fi
