eval-helper <= echo-eval, eval-collapse, eval-confirm

diff --git a/commands/get-size b/commands/get-size
--- a/commands/get-size
+++ b/commands/get-size
@@ -52,38 +52,38 @@ function get-size() (
 	if test "$#" -eq 0; then
 		if is-mac; then
 			# size of the drives
-			echo-eval -- sudo diskutil list
+			eval-helper -- sudo diskutil list
 		else
 			# size of the drives
-			echo-eval -- sudo fdisk -l
+			eval-helper -- sudo fdisk -l
 			# size of the mounts
-			echo-eval -- sudo lsblk -e7
+			eval-helper -- sudo lsblk -e7
 		fi
 	else
 		for path in "${option_paths[@]}"; do
 			path="$(fs-absolute "$path")"
 			if is-btrfs "$path"; then
 				# Show the structure of a filesystem
-				echo-eval -- sudo btrfs filesystem show
+				eval-helper -- sudo btrfs filesystem show
 
 				# Show detailed information about internal allocations in devices.
-				echo-eval -- sudo btrfs device usage "$path"
+				eval-helper -- sudo btrfs device usage "$path"
 
 				# Show detailed information about internal filesystem usage .
-				echo-eval -- sudo btrfs filesystem usage "$path"
+				eval-helper -- sudo btrfs filesystem usage "$path"
 
 				# Show space usage information for a mount point
-				echo-eval -- sudo btrfs filesystem df "$path"
+				eval-helper -- sudo btrfs filesystem df "$path"
 
 				# Show space usage via system
 				# -a, --all             include pseudo, duplicate, inaccessible file systems
 				# -h, --human-readable  print sizes in powers of 1024 (e.g., 1023M)
-				echo-eval -- df -ha "$path"
+				eval-helper -- df -ha "$path"
 
 				# Show status
-				echo-eval -- sudo btrfs device stats "$path"
-				echo-eval -- sudo btrfs scrub status "$path" || :   # if still running, exit code 1
-				echo-eval -- sudo btrfs balance status "$path" || : # if still running, exit code 1
+				eval-helper -- sudo btrfs device stats "$path"
+				eval-helper -- sudo btrfs scrub status "$path" || :   # if still running, exit code 1
+				eval-helper -- sudo btrfs balance status "$path" || : # if still running, exit code 1
 
 				# Summarize disk usage of every nested file inside the directory
 				# sudo btrfs filesystem du --summarize --human-readable "$path"
@@ -118,7 +118,7 @@ function get-size() (
 			elif test -f "$path"; then
 				# path is a file
 				#   -h, --human-readable  print sizes in human readable format (e.g., 1K 234M 2G)
-				echo-eval -- du -h "$path"
+				eval-helper -- du -h "$path"
 
 			else
 				# path is a directory
@@ -146,7 +146,7 @@ function get-size() (
 					#   -h, --human-readable  print sizes in human readable format (e.g., 1K 234M 2G)
 					#   -d, --max-depth=N     print the total for a directory (or file, with --all)
 				fi
-				echo-eval -- du "${opts[@]}" "$path"
+				eval-helper -- du "${opts[@]}" "$path"
 			fi
 		done
 	fi
