improved ability to install missing utilities
- command-exists:
    - update conventions
- debug-bash:
    - update for related changes
- renamed `get-command` to `echo-command`:
    - adopts benefits of echo-* conventions
- echo-html-decode:
    - support recode, textutil, and xmlstarlet
    - implement new get-installer fallback
- added `echo-html-encode`
- added `echo-if-command-exists`
- echo-url-{encode,decode}:
    - support python
    - implement new get-installer fallback
- fetch:
    - implement new get-installer fallback
- get-installer:
    - rewrote to use associative arrays to be more performant and easier
    - now only aliases need to be defined, as setup-util-<util> is checked
    - added new arguments to support new use cases
- renamed `setup-util-device-info` to `setup-util-devices`:
    - removed `smartmontools` as not useful enough to justify
- get-devices:
    - removed debug usage of `smartmontools` as not useful enough to justify
- added `setup-util-recode`

diff --git a/commands/get-installer b/commands/get-installer
--- a/commands/get-installer
+++ b/commands/get-installer
@@ -4,135 +4,76 @@
 
 function get-installer() (
 	source "$DOROTHY/sources/bash.bash"
+	require_array 'associative'
 
-	local command_to_installer_mapping=(
-		'amp' 'setup-util-amp'
-		'aria2' 'setup-util-aria2'
-		'bandwhich' 'setup-util-bandwhich'
-		'bandwich' 'setup-util-bandwhich' # common typo
-		'bash-completion' 'setup-util-bash'
-		'bash' 'setup-util-bash'
-		'bat' 'setup-util-bat'
-		'bottom' 'setup-util-bottom'
-		'brew' 'setup-mac-brew'
-		'build-essential' 'setup-util-devel'
-		'cargo' 'setup-rust'
-		'clang' 'setup-util-devel'
-		'cloudflare-warp' 'setup-util-warp'
-		'cmake' 'setup-util-devel'
-		'code' 'setup-util-vscode'
-		'coreutils' 'setup-util-devel'
-		'curl' 'setup-util-curl'
-		'deno' 'setup-util-deno'
-		'diff' 'setup-util-git'
-		'dig' 'setup-util-dig'
-		'docker' 'setup-docker'
-		'dust' 'setup-util-dust'
-		'emacs' 'setup-util-emacs'
-		'errno' 'setup-util-moreutils'
-		'exa' 'setup-util-exa'
-		'fd' 'setup-util-fd'
-		'fish' 'setup-util-fish'
-		'flatpak' 'setup-util-flatpak'
-		'gem' 'setup-ruby'
-		'gh' 'setup-util-gh'
-		'git-delta' 'setup-util-delta'
-		'git-lfs' 'setup-util-git'
-		'git' 'setup-util-git'
-		'glab' 'setup-util-glab'
-		'gnome-remote-desktop' 'setup-util-vnc'
-		'gnome-software' 'setup-util-gnome-software'
-		'gnu-sed' 'setup-util-gsed'
-		'gnupg' 'setup-util-git'
-		'gnupgp' 'setup-util-git'
-		'go' 'setup-go'
-		'gocryptfs' 'setup-util-gocryptfs'
-		'gpg' 'setup-util-git'
-		'greadlink' 'setup-util-coreutils'
-		'grex' 'setup-util-grex'
-		'gsed' 'setup-util-gsed'
-		'gxps' 'setup-util-ghostscript'
-		'hdparam' 'setup-util-drive-info'
-		'httpie' 'setup-util-httpie'
-		'hyperfine' 'setup-util-hyperfine'
-		'ifdown' 'setup-util-netscript'
-		'ifup' 'setup-util-netscript'
-		'jq' 'setup-util-jq'
-		'kr' 'setup-util-krypton'
-		'krgpg' 'setup-util-krypton'
-		'kypton' 'setup-util-kypton'
-		'libssl-dev' 'setup-util-devel'
-		'llvm' 'setup-util-devel'
-		'lshw' 'setup-util-drive-info'
-		'luajit' 'setup-util-neovim'
-		'make' 'setup-util-devel'
-		'mas' 'setup-util-mas'
-		'meld' 'setup-util-git'
-		'micro' 'setup-util-micro'
-		'moreutils' 'setup-util-devel'
-		'nano' 'setup-util-nano'
-		'ne' 'setup-util-ne'
-		'neovim' 'setup-util-neovim'
-		'net-tools' 'setup-util-netstat'
-		'netscript' 'setup-util-netscript'
-		'netstat' 'setup-util-netstat'
-		'node' 'setup-node'
-		'npm' 'setup-node'
-		'nvim' 'setup-util-neovim'
-		'ohmyzsh' 'setup-util-zsh'
-		'openssh' 'setup-util-git'
-		'openssl' 'setup-util-devel'
-		'pamac' 'setup-util-pamac'
-		'pinentry' 'setup-util-git'
-		'pip' 'setup-python'
-		'pipx' 'setup-python'
-		'pkg-config' 'setup-util-devel'
-		'plex' 'setup-util-plex'
-		'prettier' 'setup-util-prettier'
-		'procs' 'setup-util-procs'
-		'pv' 'setup-util-pv'
-		'python' 'setup-util-python'
-		'python2' 'setup-util-python'
-		'python3' 'setup-util-python'
-		'raspi-config' 'setup-linux-raspi'
-		'readlink' 'setup-util-coreutils'
-		'realpath' 'setup-util-coreutils'
-		'resilio-sync' 'setup-util-resilio'
-		'resilio' 'setup-util-resilio'
-		'ripgrep' 'setup-util-ripgrep'
-		'rmesg' 'setup-util-rmesg'
-		'rpi-eeprom' 'setup-linux-raspi'
-		'ruby' 'setup-ruby'
-		'rust' 'setup-rust'
-		'rustup' 'setup-rust'
-		'samba' 'setup-util-samba'
-		'screen' 'setup-util-screen'
-		'sdparm' 'setup-util-drive-info'
-		'shellcheck' 'setup-util-shellcheck'
-		'shfmt' 'setup-util-shfmt'
-		'signal' 'setup-util-signal'
-		'slap' 'setup-util-slap'
-		'smartmontools' 'setup-util-drive-info'
-		'snap' 'setup-util-snap'
-		'sponge' 'setup-util-devel'
-		'sshd' 'setup-util-git'
-		'sshfs' 'setup-util-git'
-		'starship' 'setup-util-starship'
-		'tealdeer' 'setup-util-tealdeer'
-		'teip' 'setup-util-teip'
-		'tokei' 'setup-util-tokei'
-		'tree-sitter' 'setup-util-neovim'
-		'vim' 'setup-util-vim'
-		'visual-studio-code' 'setup-util-vscode'
-		'vnc' 'setup-util-vnc'
-		'vscode' 'setup-util-vscode'
-		'warp-cli' 'setup-util-warp'
-		'warp' 'setup-util-warp'
-		'wget' 'setup-util-wget'
-		'xcode' 'setup-util-xcode'
-		'zoxide' 'setup-util-zoxide'
-		'zsh' 'setup-util-zsh'
-	)
+	# define aliases for everything that is not simply: setup-util-<name>
+	declare -A aliases
+	aliases['bandwich']='setup-util-bandwhich'
+	aliases['bash-completion']='setup-util-bash'
+	aliases['build-essential']='setup-util-devel'
+	aliases['cargo']='setup-rust'
+	aliases['clang']='setup-util-devel'
+	aliases['cloudflare-warp']='setup-util-warp'
+	aliases['cmake']='setup-util-devel'
+	aliases['code']='setup-util-vscode'
+	aliases['coreutils']='setup-util-devel'
+	aliases['diff']='setup-util-git'
+	aliases['docker']='setup-docker'
+	aliases['errno']='setup-util-moreutils'
+	aliases['gem']='setup-ruby'
+	aliases['git-delta']='setup-util-delta'
+	aliases['git-lfs']='setup-util-git'
+	aliases['github-cli']='setup-util-gh'
+	aliases['gitlab-cli']='setup-util-glab'
+	aliases['gnome-remote-desktop']='setup-util-vnc'
+	aliases['gnu-sed']='setup-util-gsed'
+	aliases['gnupg']='setup-util-git'
+	aliases['gnupgp']='setup-util-git'
+	aliases['go']='setup-go'
+	aliases['gpg']='setup-util-git'
+	aliases['greadlink']='setup-util-coreutils'
+	aliases['gxps']='setup-util-ghostscript'
+	aliases['hdparam']='setup-util-devices'
+	aliases['hdparm']='setup-util-devices'
+	aliases['ifdown']='setup-util-netscript'
+	aliases['ifup']='setup-util-netscript'
+	aliases['kr']='setup-util-krypton'
+	aliases['krgpg']='setup-util-krypton'
+	aliases['libssl-dev']='setup-util-devel'
+	aliases['llvm']='setup-util-devel'
+	aliases['lshw']='setup-util-devices'
+	aliases['luajit']='setup-util-neovim'
+	aliases['make']='setup-util-devel'
+	aliases['meld']='setup-util-git'
+	aliases['moreutils']='setup-util-devel'
+	aliases['net-tools']='setup-util-netstat'
+	aliases['node']='setup-node'
+	aliases['npm']='setup-node'
+	aliases['nvim']='setup-util-neovim'
+	aliases['ohmyzsh']='setup-util-zsh'
+	aliases['openssh']='setup-util-git'
+	aliases['openssl']='setup-util-devel'
+	aliases['pinentry']='setup-util-git'
+	aliases['pip']='setup-python'
+	aliases['pipx']='setup-python'
+	aliases['pkg-config']='setup-util-devel'
+	aliases['python2']='setup-util-python'
+	aliases['python3']='setup-util-python'
+	aliases['raspi-config']='setup-linux-raspi'
+	aliases['readlink']='setup-util-coreutils'
+	aliases['realpath']='setup-util-coreutils'
+	aliases['resilio-sync']='setup-util-resilio'
+	aliases['rpi-eeprom']='setup-linux-raspi'
+	aliases['ruby']='setup-ruby'
+	aliases['rust']='setup-rust'
+	aliases['rustup']='setup-rust'
+	aliases['sdparm']='setup-util-devices'
+	aliases['sponge']='setup-util-devel'
+	aliases['sshd']='setup-util-git'
+	aliases['sshfs']='setup-util-git'
+	aliases['tree-sitter']='setup-util-neovim'
+	aliases['visual-studio-code']='setup-util-vscode'
+	aliases['warp-cli']='setup-util-warp'
 
 	# =====================================
 	# Arguments
@@ -140,18 +81,24 @@ function get-installer() (
 	function help {
 		cat <<-EOF >/dev/stderr
 			ABOUT:
-			Output the command(s) necessary to install the <items>.
+			Output the command(s) necessary to install the <utility>.
 
 			USAGE:
-			get-installer [...options] -- ...<items>
+			get-installer [...options] -- ...<utility>
 
 			RETURNS:
-			Success if all <items> had an installer.
-			Failure if any <items> did not have an installer.
+			Success if all <utility> had an installer.
+			Failure if any <utility> did not have an installer.
 
 			OPTIONS:
 			--invoke
 			    Rather than output the installer, invoke it, such that installation occurs.
+
+			--first-success
+			    Exit on the first success, ignoring earlier failures.
+
+			--first-failure
+			    Exit on the first failure, skipping later utilities.
 
 			--quiet
 			    Do not output anything.
@@ -163,7 +110,7 @@ function get-installer() (
 	}
 
 	# process
-	local item items=() option_quiet option_invoke='no'
+	local item option_utils=() option_quiet option_invoke='no' option_first_success='no' option_first_failure='no'
 	option_quiet="$(echo-quiet -- "$@")"
 	while test "$#" -ne 0; do
 		item="$1"
@@ -175,19 +122,21 @@ function get-installer() (
 				get-flag-value invoke --missing="$option_invoke" -- "$item" | echo-affirmative
 			)"
 			;;
+		'--first-success'*) option_first_success='yes' ;;
+		'--first-failure'*) option_first_failure='yes' ;;
 		'--no-quiet'* | '--quiet'* | '--no-verbose'* | '--verbose'*) ;; # handled by echo-quiet
 		'--')
-			items+=("$@")
+			option_utils+=("$@")
 			shift "$#"
 			break
 			;;
 		'--'*) help "An unrecognised flag was provided: $item" ;;
-		*) items+=("$item") ;;
+		*) option_utils+=("$item") ;;
 		esac
 	done
 
 	# check
-	if test "${#items[@]}" -eq 0; then
+	if test "${#option_utils[@]}" -eq 0; then
 		help "No <items> were specified."
 	fi
 
@@ -199,44 +148,56 @@ function get-installer() (
 	# =====================================
 	# Action
 
-	# fetch installer
-	local found='no' missing='no' index command installer
-	for item in "${items[@]}"; do
+	# handle each utility
+	local util installer any_failure='no'
+	for util in "${option_utils[@]}"; do
 		# trim version suffix
 		# ruby@3 => ruby
-		item="${item%%@*}"
+		util="${util%%@*}"
 		# trim tap prefix
 		# clementtsang/bottom/bottom => bottom
-		item="${item##*/}"
+		util="${util##*/}"
 		# trim flags, and fix up superflous spaces at the start and end
 		# --classic code --classic => code
-		item="$(sd '(^| )[-][^ ]+' '' <<<"$item" | sd '^\s+|\s+$' '')"
+		util="$(sd '(^| )[-][^ ]+' '' <<<"$util" | sd '^\s+|\s+$' '')"
 
-		# installer
-		found='no'
-		for ((index = 0; index < ${#command_to_installer_mapping[@]}; index += 2)); do
-			command="${command_to_installer_mapping[index]}"
-			installer="${command_to_installer_mapping[$((index + 1))]}"
-			if test "$item" = "$command"; then
-				found='yes'
-				if test "$option_quiet" != 'no'; then
-					echo "$installer"
-				fi
-				if test "$option_invoke" = 'yes'; then
-					("$installer")
-				fi
-				break
+		# find it
+		installer="${aliases["$util"]-}"
+		if test -z "$installer"; then
+			installer="setup-util-$util"
+		fi
+		installer="$(echo-if-command-exists "$installer" || :)"
+
+		# handle it
+		if test -z "$installer"; then
+			any_failure='yes'
+			if test "$option_quiet" != 'yes'; then
+				echo-style --warning='No installer found for:' ' ' --code="$util" >/dev/stderr
 			fi
-		done
-		if test "$found" = 'no'; then
-			missing='yes'
+			if test "$option_first_failure" = 'yes'; then
+				return 1
+			fi
+		elif test "$option_invoke" = 'no'; then
+			if test "$option_quiet" != 'yes'; then
+				echo "$installer"
+			fi
+			if test "$option_first_success" = 'yes'; then
+				return 0
+			fi
+		elif "$installer" --quiet="$option_quiet"; then
+			if test "$option_first_success" = 'yes'; then
+				return 0
+			fi
+		else
+			any_failure='yes'
+			if test "$option_first_failure" = 'yes'; then
+				return 1
+			fi
 		fi
 	done
-	if test "$missing" = 'no' -a "$found" = 'yes'; then
-		return 0
-	else
-		return 1
-	fi
+
+	# check for failures
+	test "$any_failure" = 'no'
 )
 
 # fire if invoked standalone
