shellcheck improvements, among misc fixes
alias-details: don't error color the tab

ask, choose-menu: properly remove `--main` flag

cert: source `strict.bash`

chmod-helper: fix `--partial` argument default to `yes`

choose-option: `local` more variables

cpr: fix `different` tangent detection

echo-eval: no uses the new `echo-color` and makes status code red if failed

echo-exit-code: source `strict.bash`

secret: `envrg` => `envArg`

setup-docker: fix bad cleanup

ssh-ok: rewrote for new exit code convention

tmutil-evict: fix for modern conventions

diff --git a/commands/get-url-upgrade b/commands/get-url-upgrade
--- a/commands/get-url-upgrade
+++ b/commands/get-url-upgrade
@@ -16,7 +16,7 @@ if test -z "$protocol"; then
 	# try http, which tries https first, otherwise fail
 	stderr echo "[$url] missing protocol, will try variations"
 	get-url-upgrade "http://$url"
-	exit "$?"  # exit with the above on success and failure
+	exit "$?" # exit with the above on success and failure
 elif test "$protocol" = 'https'; then
 	# test original url works
 	if ! http-ok "$url"; then
@@ -91,7 +91,7 @@ result=''
 
 # check if it is a replaced domain
 if is-needle "$url" 'https://login.live.com' 'https://account.live.com' 'https://account.microsoft.com'; then
-	echo 'https://account.microsoft.com'  # curl fails for this, even though it exists, user agent change does nothing
+	echo 'https://account.microsoft.com' # curl fails for this, even though it exists, user agent change does nothing
 	exit
 elif is-needle "$url" 'https://signin.ebay.com.au'; then
 	echo 'https://www.ebay.com.au/signin/'
diff --git a/commands/secret b/commands/secret
--- a/commands/secret
+++ b/commands/secret
@@ -16,7 +16,7 @@ env QUIET=y setup-util-1password
 # database
 database="$DOROTHY/user/config.local/secrets.json"
 if ! sudo test -f "$database"; then
-	echo '{}' | sudo tee "$database"  &>/dev/null
+	echo '{}' | sudo tee "$database" &>/dev/null
 fi
 
 # move old state location to new state location
@@ -41,7 +41,8 @@ if is-affirmative "${QUIET-}"; then
 fi
 
 function cache_clear() {
-	local t="$(mktemp)"
+	local t
+	t="$(mktemp)"
 	mv "$database" "$t"
 	sudo rm -Rf "$state/"*
 	mv "$t" "$database"
@@ -50,7 +51,7 @@ function cache_clear() {
 function cache_exists() {
 	local key ec
 	for key in "$@"; do
-		ec=0; sudo test -f "$state/$key" || ec="$?"
+		ec=0 && sudo test -f "$state/$key" || ec="$?"
 		if test "$ec" -ne 0; then
 			return 1
 		fi
@@ -60,7 +61,7 @@ function cache_exists() {
 function cache_delete() {
 	local key ec
 	for key in "$@"; do
-		ec=0; sudo rm -f "$state/$key" || ec="$?"
+		ec=0 && sudo rm -f "$state/$key" || ec="$?"
 		if test "$ec" -ne 0; then
 			return 1
 		fi
@@ -105,7 +106,7 @@ function secret_get() {
 	# many
 	if test "${#@}" -gt '1'; then
 		for var in "$@"; do
-			ec=0; value="$(secret_get "$var")" || ec="$?"
+			ec=0 && value="$(secret_get "$var")" || ec="$?"
 			if test "$ec" -ne 0; then
 				stderr echo "ERROR: Unable to fetch the secret [$var] of many"
 				return 1
@@ -117,7 +118,7 @@ function secret_get() {
 
 	# singular
 	key="$1"
-	ec=0; result="$(cache_exists "$key" && cache_read "$key")" || ec="$?"
+	ec=0 && result="$(cache_exists "$key" && cache_read "$key")" || ec="$?"
 	if test "$ec" -ne 0; then
 		stderr echo "ERROR: Unable to fetch the secret [$var]"
 		return 1
@@ -145,7 +146,6 @@ function secret_get() {
 		echo -n "$value"
 	fi
 }
-
 
 function secret_signout() {
 	if test "${1-}" != '--quiet'; then
@@ -192,7 +192,7 @@ function secret_signin() {
 			# unfortunately, this still leaks email and subdomain
 			# https://1password.community/discussion/122030/flag-to-disable-op-signin-from-outputting-email-and-subdomain/p1?new=1
 			# don't pipe to anything else, as it breaks the OTP question
-			ec=0; OP_SESSION="$(op signin "$OP_SUBDOMAIN" "$email" "$key" --raw)" || ec="$?"
+			ec=0 && OP_SESSION="$(op signin "$OP_SUBDOMAIN" "$email" "$key" --raw)" || ec="$?"
 			if test "$ec" -ne 0; then
 				stderr echo "ERROR: Failed to sign into [$OP_SUBDOMAIN] via the email [$email] and account key [$key]."
 				stderr echo "$OP_SESSION"
@@ -206,9 +206,9 @@ function secret_signin() {
 	fi
 }
 
-function opwrap () {
+function opwrap() {
 	local ec result
-	ec=0; result="$(op "$@" 2>&1)" || ec="$?"
+	ec=0 && result="$(op "$@" 2>&1)" || ec="$?"
 	if test "$ec" -ne 0 || [[ "$result" = '[ERROR]'* ]]; then
 		if [[ "$result" = *'signed in'* ]] || [[ "$result" = *'session expired'* ]]; then
 			stderr echo "ERROR: Session expired, run [secret login] and try again."
@@ -226,19 +226,19 @@ function opgrab() {
 
 	if is-empty-value "$vault"; then
 		# fetch available values
-		ec=0; opwrap list vaults --session="$OP_SESSION" || ec="$?"
+		ec=0 && opwrap list vaults --session="$OP_SESSION" || ec="$?"
 	elif is-empty-value "$item"; then
 		# fetch available items
-		ec=0; opwrap list items --vault="$vault" --session="$OP_SESSION" || ec="$?"
+		ec=0 && opwrap list items --vault="$vault" --session="$OP_SESSION" || ec="$?"
 	else
 		# fetch item
-		ec=0; opwrap get item "$item" --vault="$vault" --session="$OP_SESSION" || ec="$?"
+		ec=0 && opwrap get item "$item" --vault="$vault" --session="$OP_SESSION" || ec="$?"
 	fi
 
 	return "$ec"
 }
 
-function fetch_vault () {
+function fetch_vault() {
 	local vault="${1-}" tuples
 
 	# fetch available vaults
@@ -251,10 +251,10 @@ function fetch_vault () {
 
 	# filter or ask
 	choose-option --question='Which vault do you want?' --filter="$vault" --label --visual="\$label [\$value]" -- "${tuples[@]}"
-	return "$?"  # return with the above on success and failure
+	return "$?" # return with the above on success and failure
 }
 
-function fetch_item () {
+function fetch_item() {
 	local vault="${1-}" item="${2-}" tuples
 
 	# fetch available items
@@ -267,10 +267,10 @@ function fetch_item () {
 
 	# filter or ask
 	choose-option --question='Which item do you want?' --filter="$item" --label --visual="\$label [\$value]" -- "${tuples[@]}"
-	return "$?"  # return with the above on success and failure
+	return "$?" # return with the above on success and failure
 }
 
-function fetch_field () {
+function fetch_field() {
 	local vault="${1-}" item="${2-}" field="${3-}" wants
 	local fields=() data fields_via_section fields_via_name fields_via_designation
 	if test "${4-}" = '--label'; then
@@ -302,17 +302,17 @@ function fetch_field () {
 
 	# filter or ask
 	choose-option --question='Which field do you want?' --filter="$field" --return="$wants" --label --visual="\$label [\$value]" -- "${fields[@]}"
-	return "$?"  # return with the above on success and failure
+	return "$?" # return with the above on success and failure
 }
 
-function get_job_count () {
+function get_job_count() {
 	jobs -p | get-line-count
 }
 
-function item_upgrade () {
+function item_upgrade() {
 	local vault="$1" item="$2" ec result
 	# fetch
-	ec=0; website="$(opwrap get item --session="$OP_SESSION" --vault "$vault" "$item" - --fields website)" || ec="$?"
+	ec=0 && website="$(opwrap get item --session="$OP_SESSION" --vault "$vault" "$item" - --fields website)" || ec="$?"
 	if test "$ec" -ne 0; then
 		echo "[$item] [$website] failed to fetch"
 		return 1
@@ -336,7 +336,7 @@ function item_upgrade () {
 	# echo to stdout, as is actionable for user if they are piping
 	echo "[$item] [$website] => [$result]"
 	# apply
-	ec=0; opwrap edit item --session="$OP_SESSION" --vault "$vault" "$item" website="$result" || ec="$?"
+	ec=0 && opwrap edit item --session="$OP_SESSION" --vault "$vault" "$item" website="$result" || ec="$?"
 	if test "$ec" -ne 0; then
 		stderr echo "[$item] [$website] failed to save"
 		return 1
@@ -345,13 +345,13 @@ function item_upgrade () {
 
 function secret_https() {
 	local last="${1-}" ec vault item
-	ec=0; vaults="$(opwrap list vaults --session="$OP_SESSION" | jq -r '.[].uuid' | sort)" || ec="$?"
+	ec=0 && vaults="$(opwrap list vaults --session="$OP_SESSION" | jq -r '.[].uuid' | sort)" || ec="$?"
 	if test "$ec" -ne 0 -o -z "$vaults"; then
 		stderr echo "failed to fetch vaults..."
 		return 1
 	fi
 	for vault in $vaults; do
-		ec=0; items="$(opwrap list items --session="$OP_SESSION" --categories Login --vault "$vault" | jq -r '.[].uuid' | sort)" || ec="$?"
+		ec=0 && items="$(opwrap list items --session="$OP_SESSION" --categories Login --vault "$vault" | jq -r '.[].uuid' | sort)" || ec="$?"
 		if test "$ec" -ne 0 -o -z "$vaults"; then
 			stderr echo "failed to fetch items from vault [$vault]"
 			return 1
@@ -379,16 +379,17 @@ function secret_https() {
 	while test "$(get_job_count)" -ne 0; do
 		echo "Waiting on [$(get_job_count)] jobs..."
 		sleep 5
-		jobs &> /dev/null # for some reason, this seems necessary to prevent hung jobs
+		jobs &>/dev/null # for some reason, this seems necessary to prevent hung jobs
 	done
 	echo 'All done.'
 }
 
 function secret_fetch() {
-	local vault="$(fetch_vault "${1-}")"
-	local item="$(fetch_item "$vault" "${2-}")"
+	local vault item
+	value="$(fetch_vault "${1-}")"
+	item="$(fetch_item "$vault" "${2-}")"
 	fetch_field "$vault" "$item" "${3-}"
-	return "$?"  # return with the above on success and failure
+	return "$?" # return with the above on success and failure
 }
 
 function secret_map() {
@@ -431,7 +432,7 @@ function secret_unmap() {
 function secret_env() {
 	local before=() after=() found='no' arg vars args
 	local envSecrets var value
-	local envArgs arg envrg
+	local envArgs arg envArg
 
 	for arg in "$@"; do
 		if test "$arg" = '--'; then
@@ -517,7 +518,7 @@ elif test "$action" = 'https'; then
 	secret_signin >&2 # redirect function to stderr
 	secret_https "${@:2}"
 elif test "$action" = 'help'; then
-	cat << EOF
+	stderr cat <<EOF
 USAGE:
 
 secret install
diff --git a/commands/setup-dns b/commands/setup-dns
--- a/commands/setup-dns
+++ b/commands/setup-dns
@@ -255,7 +255,7 @@ EOF
 			tunnel_url="$(ask --question='What is the URI that the tunnel exposes?' --default="${CLOUDFLARED_TUNNEL_URL:-"ssh://localhost:22"}" --required --confirm)"
 			tunnel_ingress="url: $tunnel_url"
 		fi
-		cat > "$hd/$tunnel_config" <<EOF
+		cat >"$hd/$tunnel_config" <<EOF
 tunnel: $tunnel_name
 credentials-file: $sd/$tunnel_cred
 $tunnel_ingress
@@ -386,7 +386,7 @@ function dnscrypt_install {
 		sudo dnscrypt-proxy -check -config '/usr/local/etc/dnscrypt-proxy.toml'
 		sudo dnscrypt-proxy -service install -config '/usr/local/etc/dnscrypt-proxy.toml'
 		sudo dnscrypt-proxy -service start -config '/usr/local/etc/dnscrypt-proxy.toml'
-		sleep 5  # needed otherwise sometimes resolve fails
+		sleep 5 # needed otherwise sometimes resolve fails
 		sudo systemctl status dnscrypt-proxy.service --no-pager
 		sudo dnscrypt-proxy -resolve cloudflare.com -config '/usr/local/etc/dnscrypt-proxy.toml'
 	fi
@@ -417,7 +417,7 @@ function dnscrypt_uninstall {
 	fi
 
 	# config
-	ok sudo rm -fvi '/usr/local/etc/dnscrypt-proxy.toml'  # ask if they want it removed
+	ok sudo rm -fvi '/usr/local/etc/dnscrypt-proxy.toml' # ask if they want it removed
 }
 
 # -------------------------------------
@@ -501,7 +501,7 @@ elif test "$service" = 'aghome' -o "$service" = 'adguard-home' -o "$service" = '
 		stderr echo "Supported DNS services for this platform are: ${services[*]}"
 		exit 1
 	fi
-elif test "$service" = 'cloudflared' -o  "$service" = 'cloudflare' -o  "$service" = 'cf'; then
+elif test "$service" = 'cloudflared' -o "$service" = 'cloudflare' -o "$service" = 'cf'; then
 	if is-needle 'cloudflared' "${services[@]}"; then
 		service='cloudflared'
 		echo 'Selected DNS service: Cloudflared'
@@ -510,7 +510,7 @@ elif test "$service" = 'cloudflared' -o  "$service" = 'cloudflare' -o  "$service
 		stderr echo "Supported DNS services for this platform are: ${services[*]}"
 		exit 1
 	fi
-elif test "$service" = 'dnscrypt' -o  "$service" = 'dnscrypt-proxy'; then
+elif test "$service" = 'dnscrypt' -o "$service" = 'dnscrypt-proxy'; then
 	if is-needle 'dnscrypt' "${services[@]}"; then
 		service='dnscrypt'
 		echo 'Selected DNS service: DNSCrypt Proxy'
@@ -541,7 +541,7 @@ else
 	# backup dns provider
 	echo "Configuring the system DNS service to use the backup DNS provider while we configure your new custom DNS service..."
 	select-dns backup --no-confirm
-	sleep 5  # needed otherwise sometimes install downloads fail
+	sleep 5 # needed otherwise sometimes install downloads fail
 
 	# reinstall the service we actually care about
 	if test "$service" = 'aghome'; then
@@ -564,7 +564,7 @@ else
 	# Test
 	echo
 	echo 'Testing that the system is now using the custom DNS service...'
-	if ! ( dig -x cloudflare.com | rg -q ';; SERVER: 127.0.0.1' ); then
+	if ! (dig -x cloudflare.com | rg -q ';; SERVER: 127.0.0.1'); then
 		stderr echo 'FAILURE'
 		stderr echo 'Custom DNS configuration has failed.'
 		stderr echo 'The domain failed to resolve or did not resolve with the local DNS service.'
diff --git a/commands/setup-mac-brew b/commands/setup-mac-brew
--- a/commands/setup-mac-brew
+++ b/commands/setup-mac-brew
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 # environment provides: HOMEBREW_PREFIX, HOMEBREW_CELLAR
 source "$DOROTHY/sources/strict.bash"
-source "$DOROTHY/sources/config.sh"; load_dorothy_config 'setup.bash'
+source "$DOROTHY/sources/config.sh"
+load_dorothy_config 'setup.bash'
 # ^ provides: HOMEBREW_ARCH, HOMEBREW_INSTALL_CASK, HOMEBREW_INSTALL_SLOW, HOMEBREW_INSTALL
 
 # Mode
@@ -28,7 +29,7 @@ source "$DOROTHY/sources/arrays.bash"
 if test "$ARRAYS" = 'no'; then
 	brew install bash
 	setup-mac-brew "$@"
-	exit "$?"  # exit with the above on success and failure
+	exit "$?" # exit with the above on success and failure
 fi
 
 # Helpers
@@ -61,7 +62,7 @@ function confirmbrewinstall() {
 		fi
 	else
 		fodder="$(choose-option --multi --question="What formulas would you like to brew install?" -- "$@")"
-		mapfile -t choices <<< "$fodder" # <( destroys stdin
+		mapfile -t choices <<<"$fodder" # <( destroys stdin
 	fi
 	if is-array-full-or-partial "${choices-}"; then
 		brewinstall "${choices[@]}"
@@ -76,7 +77,7 @@ function confirmcaskinstall() {
 		fi
 	else
 		fodder="$(choose-option --multi --question="Which casks would you like to brew install?" -- "$@")"
-		mapfile -t choices <<< "$fodder"  # <( destroys stdin
+		mapfile -t choices <<<"$fodder" # <( destroys stdin
 	fi
 	if is-array-full-or-partial "${choices-}"; then
 		# use $* as cask supports installing multiple together
@@ -114,8 +115,8 @@ ok rm -rf "/Users/$(whoami)/Library/Python/"*
 ok rm -rf "${HOMEBREW_CELLAR}/python"*
 ok rm -rf "${HOMEBREW_PREFIX}/opt/python"*
 # ok is used above as otherwise their non existance will cause failure
-brew cleanup  # used to fix the breaks from removing the above
-brew install python  # reinstall python now that it has been cleaned
+brew cleanup        # used to fix the breaks from removing the above
+brew install python # reinstall python now that it has been cleaned
 
 # ffmpeg
 if test "$mode" = "install" && confirm-bool $'\nDo you want to install encoding tools?'; then
