remove unnecessary bash v3 workarounds
Turns out Dorothy for 3 years has made it so that accessing empty arrays on bash <4.4 does not crash, as it disables their problematic implementation of `nounset`. I've now documented the various workarounds of `bash.bash` in `versions.md`.

I've also removed verbose comments about the `]] || retuurn` rule, as that can become a linter rule (added a todo note about it).

I've also fixed `dorothy-warnings` have incorrect function calls and documentation.

diff --git a/commands/get-terminal-reactivity-support b/commands/get-terminal-reactivity-support
--- a/commands/get-terminal-reactivity-support
+++ b/commands/get-terminal-reactivity-support
@@ -46,8 +46,8 @@ function get_terminal_reactivity_support() (
 	# Action
 
 	function __check {
-		[[ -t 0 ]] # this fails on GitHub Actions, if it passes on a CI, then we should add: && ! is-ci
-		return
+		# this fails on GitHub Actions, if it passes on a CI, then we should add: && ! is-ci
+		[[ -t 0 ]] || return
 	}
 
 	if [[ $option_quiet == 'yes' ]]; then
