convention updates

diff --git a/commands/get-size b/commands/get-size
--- a/commands/get-size
+++ b/commands/get-size
@@ -52,73 +52,111 @@ function get-size() (
 	if test "$#" -eq 0; then
 		if is-mac; then
 			# size of the drives
-			eval-helper --quiet=no -- sudo-helper -- diskutil list
+			eval-helper --quiet=no \
+				-- sudo-helper \
+				-- diskutil list
 		else
 			# size of the drives
-			eval-helper --quiet=no -- sudo-helper -- fdisk -l
+			eval-helper --quiet=no \
+				-- sudo-helper \
+				-- fdisk -l
 			# size of the mounts
-			eval-helper --quiet=no -- sudo-helper -- lsblk -e7
+			eval-helper --quiet=no \
+				-- sudo-helper \
+				-- lsblk -e7
 		fi
 	else
 		for path in "${option_paths[@]}"; do
 			path="$(fs-absolute "$path")"
 			if is-btrfs "$path"; then
 				# Show the structure of a filesystem
-				eval-helper --quiet=no -- sudo-helper -- btrfs filesystem show
+				eval-helper --quiet=no \
+					-- sudo-helper \
+					-- btrfs filesystem show
 
 				# Show detailed information about internal allocations in devices.
-				eval-helper --quiet=no -- sudo-helper -- btrfs device usage "$path"
+				eval-helper --quiet=no \
+					-- sudo-helper \
+					-- btrfs device usage "$path"
 
 				# Show detailed information about internal filesystem usage .
-				eval-helper --quiet=no -- sudo-helper -- btrfs filesystem usage "$path"
+				eval-helper --quiet=no \
+					-- sudo-helper \
+					-- btrfs filesystem usage "$path"
 
 				# Show space usage information for a mount point
-				eval-helper --quiet=no -- sudo-helper -- btrfs filesystem df "$path"
+				eval-helper --quiet=no \
+					-- sudo-helper \
+					-- btrfs filesystem df "$path"
 
 				# Show space usage via system
 				# -a, --all             include pseudo, duplicate, inaccessible file systems
 				# -h, --human-readable  print sizes in powers of 1024 (e.g., 1023M)
-				eval-helper --quiet=no -- sudo-helper -- df -ah "$path"
+				eval-helper --quiet=no \
+					-- sudo-helper \
+					-- df -ah "$path"
 
 				# Show status
-				eval-helper --quiet=no -- sudo-helper -- btrfs device stats "$path"
-				eval-helper --quiet=no -- sudo-helper -- btrfs scrub status "$path" || :   # if still running, exit code 1
-				eval-helper --quiet=no -- sudo-helper -- btrfs balance status "$path" || : # if still running, exit code 1
+				eval-helper --quiet=no \
+					-- sudo-helper \
+					-- btrfs device stats "$path"
+				eval-helper --quiet=no \
+					-- sudo-helper \
+					-- btrfs scrub status "$path" || : # if still running, exit code 1
+				eval-helper --quiet=no \
+					-- sudo-helper \
+					-- btrfs balance status "$path" || : # if still running, exit code 1
 
 				# Summarize disk usage of every nested file inside the directory
-				# eval-helper --quiet=no -- sudo-helper -- btrfs filesystem du --summarize --human-readable "$path"
+				# eval-helper --quiet=no \
+				#	-- sudo-helper \
+				#	-- btrfs filesystem du --summarize --human-readable "$path"
 
 				# Rename
-				# eval-helper --quiet=no -- sudo-helper -- btrfs filesystem label "$path" "$name"
+				# eval-helper --quiet=no \
+				#	-- sudo-helper \
+				#	-- btrfs filesystem label "$path" "$name"
 
 				# Change unallocated to free
-				# eval-helper --quiet=no -- sudo-helper -- btrfs filesystem resize max "$path"
+				# eval-helper --quiet=no \
+				#	-- sudo-helper \
+				#	-- btrfs filesystem resize max "$path"
 
 				# Defragment (balance also defrags)
-				# eval-helper --quiet=no -- sudo-helper -- btrfs filesystem defragment "$path"
+				# eval-helper --quiet=no \
+				#	-- sudo-helper \
+				#	-- btrfs filesystem defragment "$path"
 
 				# Balance as raid1
-				# eval-helper --quiet=no -- sudo-helper -- btrfs balance start --background -dconvert=raid1 -mconvert=raid1 "$path"
+				# eval-helper --quiet=no \
+				#	-- sudo-helper \
+				#	-- btrfs balance start --background -dconvert=raid1 -mconvert=raid1 "$path"
 
 				# Scrub (check filesystem for errors and auto-heal)
-				# eval-helper --quiet=no -- sudo-helper -- btrfs scrub start "$path"
+				# eval-helper --quiet=no \
+				#	-- sudo-helper \
+				#	-- btrfs scrub start "$path"
 
 				# Check devices for errors
 				# WARNING: the repair mode is considered dangerous and should not be used without prior analysis of problems found on the filesystem.
-				# eval-helper --quiet=no -- sudo-helper -- btrfs check --repair --progress /dev/...
+				# eval-helper --quiet=no \
+				#	-- sudo-helper \
+				#	-- btrfs check --repair --progress /dev/...
 
 				# Logs
 				# tail -n 1000 -f /var/log/syslog | grep --fixed-strings --regexp='BTRFS'
 
 			elif command-exists dust; then
-				eval-helper --quiet=no -- dust -d 1 "$path"
+				eval-helper --quiet=no \
+					-- dust -d 1 "$path"
 				#     -s, --apparent-size       Use file length instead of blocks
 				#     -d, --depth <depth>                             Depth to show
 
 			elif test -f "$path"; then
 				# path is a file
 				#   -h, --human-readable  print sizes in human readable format (e.g., 1K 234M 2G)
-				eval-helper --quiet=no -- du -h "$path"
+				eval-helper --quiet=no \
+					-- du -h "$path"
 
 			else
 				# path is a directory
@@ -146,7 +184,8 @@ function get-size() (
 					#   -h, --human-readable  print sizes in human readable format (e.g., 1K 234M 2G)
 					#   -d, --max-depth=N     print the total for a directory (or file, with --all)
 				fi
-				eval-helper --quiet=no -- du "${opts[@]}" "$path"
+				eval-helper --quiet=no \
+					-- du "${opts[@]}" "$path"
 			fi
 		done
 	fi
