improved theme detection
get-os-theme => get-desktop-theme

added get-terminal-theme which uses my own novel way of detecting it

update get-{desktop,terminal}-theme to be dumber, drop --refresh and --quiet args, as that is better handled by their callers

diff --git a/commands/get-desktop-theme b/commands/get-desktop-theme
--- a/commands/get-desktop-theme
+++ b/commands/get-desktop-theme
@@ -12,17 +12,10 @@ function get_os_theme() (
 	function help {
 		cat <<-EOF >/dev/stderr
 			ABOUT:
-			Output $(echo-style --code="light") or $(echo-style --code="dark") based on the theme of the Operating System.
+			Get whether the desktop environment is light or dark.
 
 			USAGE:
-			get-os-theme
-
-			OPTIONS:
-			--refresh
-			    If provided, do not trust the THEME environment variable.
-
-			--quiet
-			    If provided, errors are not output.
+			get-desktop-theme
 		EOF
 		if test "$#" -ne 0; then
 			echo-error "$@"
@@ -31,17 +24,12 @@ function get_os_theme() (
 	}
 
 	# process
-	local item option_quiet='no' option_refresh='no'
-	option_quiet="$(echo-quiet -- "$@")"
+	local item
 	while test "$#" -ne 0; do
 		item="$1"
 		shift
 		case "$item" in
 		'--help' | '-h') help ;;
-		'--no-quiet'* | '--quiet'* | '--no-verbose'* | '--verbose'*) ;; # handled by echo-quiet
-		'--no-refresh'* | '--refresh'*)
-			option_refresh="$(get-flag-value refresh --missing="$option_refresh" -- "$item" | echo-affirmative)"
-			;;
 		'--'*) help "An unrecognised flag was provided: $item" ;;
 		*) help "An unrecognised argument was provided: $item" ;;
 		esac
@@ -51,15 +39,9 @@ function get_os_theme() (
 	# Action
 
 	local result
-	if test "$option_refresh" = 'no' -a -n "${THEME-}"; then
-		if test "$THEME" = 'dark'; then
-			print_line 'dark'
-		else
-			print_line 'light'
-		fi
-	elif is-mac; then
+	if is-mac; then
 		# result="$(defaults read -globalDomain AppleInterfaceStyle || :)" <-- always reports Dark on macOS Ventura
-		result="$(osascript -e 'tell application "System Events" to tell appearance preferences to get dark mode' || :)"
+		result="$(osascript -e 'tell application "System Events" to tell appearance preferences to get dark mode' || :)" # note that this prompts the user if they wish to allow terminal to access system events, so is undesirable
 		if test "$result" = 'true'; then
 			print_line 'dark'
 		else
@@ -73,13 +55,9 @@ function get_os_theme() (
 			print_line 'light'
 		fi
 	else
-		# don't use echo-style here, as echo-style uses this
-		if test "$option_quiet" = 'no'; then
-			print_line "Unable to determine the Operating System theme." >/dev/stderr
-		fi
+		echo-style --error='Unable to determine if the desktop theme is light or dark.' >/dev/stderr
 		return 19 # ENODEV 19 Operation not supported by device
 	fi
-
 )
 
 # fire if invoked standalone
