get-size: update comment on purpose of scrub and check
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/get-size b/commands/get-size
--- a/commands/get-size
+++ b/commands/get-size
@@ -43,8 +43,8 @@ if test -n "$path"; then
 
 		# Show status
 		echo-eval sudo btrfs device stats "$path"
-		echo-eval sudo btrfs scrub status "$path" || :  # if still running, exit code 1
-		echo-eval sudo btrfs balance status "$path" || :  # if still running, exit code 1
+		echo-eval sudo btrfs scrub status "$path" || :   # if still running, exit code 1
+		echo-eval sudo btrfs balance status "$path" || : # if still running, exit code 1
 
 		# Summarize disk usage of every nested file inside the directory
 		# sudo btrfs filesystem du --summarize --human-readable "$path"
@@ -65,7 +65,8 @@ if test -n "$path"; then
 		# sudo btrfs scrub start "$path"
 
 		# Check devices for errors
-		# sudo btrfs check /dev/...
+		# WARNING: the repair mode is considered dangerous and should not be used without prior analysis of problems found on the filesystem.
+		# sudo btrfs check --repair --progress /dev/...
 
 		# Logs
 		# tail -n 1000 -f /var/log/syslog | grep "BTRFS"
