get-github-release: fix github api no longer accepting api.github.com as a hostname

diff --git a/commands/get-github-release b/commands/get-github-release
--- a/commands/get-github-release
+++ b/commands/get-github-release
@@ -272,11 +272,17 @@ function get_github_release() (
 	# 	GITHUB_API_URL='https://bevry.me/api/github' # caches results, to avoid rate limits
 	# fi
 
+	# GITHUB_HOSTNAME
+	if test -z "${GITHUB_HOSTNAME-}"; then
+		GITHUB_HOSTNAME='github.com'
+	fi
+
 	# GITHUB_TOKEN
 	if test -z "${GITHUB_TOKEN-}"; then
 		GITHUB_TOKEN=''
 		if command-exists gh; then
-			GITHUB_TOKEN="$(gh auth token --hostname "$GITHUB_API_URL" 2>/dev/null || :)"
+
+			GITHUB_TOKEN="$(gh auth token --hostname "$GITHUB_HOSTNAME" 2>/dev/null || :)"
 		fi
 	fi
 
@@ -285,7 +291,11 @@ function get_github_release() (
 		fetch --bearer-token="$GITHUB_TOKEN" "$1"
 	}
 	function fetch_json_of_rate_limit {
-		fetch_json "$GITHUB_API_URL/rate_limit"
+		fetch_json "$GITHUB_API_URL/rate_limit" || {
+			local exit_status="$?"
+			echo-error 'Failed to fetch the GitHub API Rate Limit.' ' ' --notice='Authorize with the GitHub CLI:' ' ' --code_notice='gh auth login'
+			return "$exit_status"
+		}
 	}
 	function extract_value_from_json_property_from_stdin {
 		local property="$1"
