fixes for debian, windows
- `dorothy`: require `nvm-env` for `prettier --version` invocation in case node is only installed via nvm
- `echo-json(.*)`:
    - use actions documentation
    - support `<property>` options for `decode` action
- `echo-wsl`, `get-codec`: lint
- `get-system`:
    - prefer `--codename` over `--code`
    - remove unused `lsb_release` and `config-helper` references
- `git-helper`: ensure remote is applied even if not updating, to fix nvm installation from `setup-util-nvm` that depends on it
- `gpg-helper`: if valid key is provided, don't prompt it
- `nvm-env`, `setup-util-nvm`: enable `--quiet` option to silent output, to prevent `setup-util --checker=...` usage from outpuutting nvm not found errors in `setup-util-nvm`
- `setup-util`:
    - move `scoop` and other windows sources way later to avoid `ripgrep` failing on WSL due to requiring Windows paths
    - `ppa:` support in `apt` is only for Ubuntu, so check for that
    - use `get-system --codename` instead of `lsb_release` to remove need for `lsb_release`
- `setup-util-apt`, `setup-util-lsb-release`, `installers.dat`: as nothing needs `lsb_release` anymore, move it to its own util installer
- `setup-util-node`:
    - fix apt installation, as nodesource changed its conventions
    - fix node failing once installed due to missing `libatomic1` dependency that is otherwise typically provided by devel
    - fix failure due to missing `eval_helper` source

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/git-helper b/commands/git-helper
--- a/commands/git-helper
+++ b/commands/git-helper
@@ -1367,8 +1367,14 @@ function git_helper() (
 			fi
 		fi
 
+		# this is outside update for `setup-util-nvm`, maybe restricting to no remotes and running in update otherwise would be better
+		# apply the remote
+		# the verify and test in update will handle update failures
+		remote="$(__remote --apply --remote="$remote" --url="$url" --protocol="$protocol" --verify --test)" || return $?
+
 		# exit early if no update
 		if [[ $update == 'no' ]]; then
+			# but still apply the remove
 			return 0
 		fi
 
@@ -1378,9 +1384,6 @@ function git_helper() (
 			# this prevents the need for doing a `git status &>/dev/null` check. to make sure the HEAD is fresh
 			# although, doing the status check is a better idea perhaps
 			git config --local pull.ff only || return $?
-
-			# the verify and test will handle the update failure
-			remote="$(__remote --apply --remote="$remote" --url="$url" --protocol="$protocol" --verify --test)" || return $?
 
 			# fetch all origins, branches, and prune remote deleted branches
 			local pending success failure
