dorothy no longer needs SSH configured to install/update, HTTPS will work fine
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/git-protocol-ensure b/commands/git-protocol-ensure
--- a/commands/git-protocol-ensure
+++ b/commands/git-protocol-ensure
@@ -3,17 +3,23 @@ source "$DOROTHY/sources/strict.bash"
 
 remote="$(ask --question='What remote to configure?' --default="${1:-"origin"}" --required)"
 protocol="$(git-protocol-ask "${2-}")"
+ourl="$(git-remote-url "$remote")"
+hurl="$(git-protocol-format "$ourl" https)"
+surl="$(git-protocol-format "$ourl" ssh)"
 
-# attempt default, ssh, https
+echo "git-protocol-ensure" > /dev/tty
+echo "Directory:    $(pwd)" > /dev/tty
+echo "Remote:       $remote" > /dev/tty
+echo "Remote URI:   $ourl" > /dev/tty
+echo "SSH URI:      $surl" > /dev/tty
+echo "HTTPS URI:    $hurl" > /dev/tty
+echo "Preference:   $protocol" > /dev/tty
+
 if test "$protocol" = 'ssh'; then
-	( \
-		silent is-ssh-working \
-		&& git-protocol-apply "$remote" ssh \
-		&& silent is-ssh-working \
-	) || git-protocol-apply "$remote" https
+	git-protocol-apply "$remote" ssh || {
+		echo 'SSH failed, attempting HTTPS...' > /dev/stderr
+		git-protocol-apply "$remote" https
+	}
 else
 	git-protocol-apply "$remote" https
 fi
-
-# report
-git remote -v
diff --git a/commands/git-remote-apply b/commands/git-remote-apply
--- a/commands/git-remote-apply
+++ b/commands/git-remote-apply
@@ -1,40 +1,60 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
+# options
 remote="$(ask --question='What remote to configure?' --default="${1:-"origin"}" --required)"
-url="$(ask --question='What is the URL to configure the remote to?' --default="${2-}" --required)"
+purl="$(ask --question='What is the URL to configure the remote to?' --default="${2-}" --required)"
 ourl="$(git-remote-url "$remote")"
 
-git remote remove "$remote"
-git remote add "$remote" "$url"
 
-nurl="$(git-remote-url "$remote")"
-if test "$nurl" != "$url"; then
-	stderr echo "Failed to change remote $remote"
-	stderr echo "from  $ourl"
-	stderr echo "to    $url"
-	stderr echo "is    $nurl"
+# check if there is a difference
+if test "$purl" = "$ourl"; then
+	echo "Original URL: $ourl" > /dev/tty
+	echo "Proposed URL: $purl" > /dev/tty
+	echo "They are the same, skipping application, but will still test." > /dev/tty
+else
+	# apply the change
+	git remote remove "$remote"
+	git remote add "$remote" "$purl"
 
-	glines="$(git config --global --list | grep '.insteadof=')"
-	if test -n "$glines"; then
-		stderr echo
-		stderr echo 'you have replacement rules in your global git config, remove them if you want this to work:'
-		stderr echo "$glines"
+	# check if it changed
+	nurl="$(git-remote-url "$remote")"
+	if test "$nurl" != "$purl"; then
+		stderr echo "Failed to change remote $remote"
+		stderr echo "from  $ourl"
+		stderr echo "to    $purl"
+		stderr echo "is    $nurl"
+
+		glines="$(git config --global --list | grep '.insteadof=')"
+		if test -n "$glines"; then
+			stderr echo
+			stderr echo 'you have replacement rules in your global git config, remove them if you want this to work:'
+			stderr echo "$glines"
+		fi
+
+		llines="$(git config --list | grep '.insteadof=')"
+		if test -n "$llines"; then
+			stderr echo
+			stderr echo 'you have replacement rules in your local git config, remove them if you want this to work:'
+			stderr echo "$llines"
+		fi
+
+		if test -n "$glines" -o -n "$llines"; then
+			stderr echo
+			stderr echo 'try run the following and try again'
+			echo "$glines" | sed -E 's#^#git config --global --unset #; s#=.+##'
+			echo "$llines" | sed -E 's#^#git config --unset #; s#=.+##'
+		fi
+
+		exit 1
 	fi
+fi
 
-	llines="$(git config --list | grep '.insteadof=')"
-	if test -n "$llines"; then
-		stderr echo
-		stderr echo 'you have replacement rules in your local git config, remove them if you want this to work:'
-		stderr echo "$llines"
-	fi
-
-	if test -n "$glines" -o -n "$llines"; then
-		stderr echo
-		stderr echo 'try run the following and try again'
-		echo "$glines" | sed -E 's#^#git config --global --unset #; s#=.+##'
-		echo "$llines" | sed -E 's#^#git config --unset #; s#=.+##'
-	fi
-
+# test the the change
+if git-remote-ok "$remote"; then
+	echo 'Test success.' > /dev/stderr
+	exit 0
+else
+	echo 'Test failed.' > /dev/stderr
 	exit 1
 fi
