choose: auto-select solo required item for git-helper use case
git-helper:
- add verify step
- improve the way remotes are gathered
- fix path not sent to review
- support update on repos that don't have origin, and restore remote prompt on repos with multiple remotes

/ref b60ef2429ff8d67c1f7eba62394c9440025d41cc
/ref https://github.com/bevry/dorothy/actions/runs/11267661909/job/31333162360#step:3:1812
/ref https://github.com/bevry/dorothy/actions/runs/11115550380/job/30884206594#step:3:1873
/ref https://github.com/bevry/dorothy/actions/runs/11277567607/job/31364020536#step:3:1873
/ref https://github.com/bevry/dorothy/actions/runs/11286493561/job/31390927875#step:3:2128
/ref https://github.com/bevry/dorothy/actions/runs/11286573839/job/31391154425#step:3:1896
/ref https://github.com/bevry/dorothy/actions/runs/11286652092/job/31391365190#step:3:2141
/ref https://github.com/bevry/dorothy/actions/runs/11287510416/job/31393567790#step:3:1797
/ref https://github.com/bevry/dorothy/actions/runs/11287614318/job/31393844817#step:3:1798
/ref https://github.com/bevry/dorothy/actions/runs/11287762099/job/31394250547#step:3:1861

diff --git a/commands/git-helper b/commands/git-helper
--- a/commands/git-helper
+++ b/commands/git-helper
@@ -19,6 +19,9 @@ function git_helper() (
 			--path=<path>
 			    Instead of the current working directory, use this path as the git repository.
 
+			--verify
+			    Verify the <path> contains an initialised git repository before proceeding with the <action>.
+
 			ACTIONS:
 			authors
 			    Output all authors (contributors) within this git repository.
@@ -70,6 +73,9 @@ function git_helper() (
 			        current    exit code 0
 			        updated    exit code 0
 
+			verify
+			    Verify the <path> contains an initialised git repository.
+
 			wipe
 			    Wipe the current working directory to the state of the last commit.
 		EOF
@@ -80,13 +86,16 @@ function git_helper() (
 	}
 
 	# process
-	local item action='' option_path='' option_args=()
+	local item action='' option_path='' option_verify='no' option_args=()
 	while test "$#" -ne 0; do
 		item="$1"
 		shift
 		case "$item" in
 		'--help' | '-h') help ;;
 		'--path='*) option_path="${item#*=}" ;;
+		'--no-verify'* | '--verify'*)
+			option_verify="$(get-flag-value --affirmative --fallback="$option_verify" -- "$item")"
+			;;
 		'--')
 			option_args+=("$@")
 			shift "$#"
@@ -109,8 +118,8 @@ function git_helper() (
 	if test -z "$option_path"; then
 		option_path="$(pwd)"
 	elif test ! -d "$option_path"; then
-		echo-error "$0: No directory at $option_path"
-		return 1
+		echo-style --error1='Unable to use git-helper on a non-existent directory: ' --code-error1="$option_path" >/dev/stderr
+		return 2 # ENOENT 2 No such file or directory
 	fi
 
 	# check
@@ -137,32 +146,70 @@ function git_helper() (
 	fi
 
 	# =====================================
-	# Adjustments
-
-	# enter path for the remainder of this command's subshell
-	# so that git commands work correctly
-	cd "$option_path"
-
-	# seed protocols, must be done here, as subshells prevent sharing later
-	local protocols=()
-	if test "${#protocols[@]}" -eq 0; then
-		if ssh-helper test &>/dev/null; then
-			protocols+=('ssh')
-		fi
-		protocols+=('https')
-	fi
-
-	# =====================================
 	# Helpers
 
+	local protocols=()
+	function verify_repository {
+		# verify repository
+		local git_status git_output
+		eval_capture --statusvar=git_status --outputvar=git_output -- git status
+		if test "$git_status" -eq 128; then
+			echo-style --error1='The directory is not a git repository: ' --code-error1="$option_path" >/dev/stderr
+			if test -n "$git_output"; then
+				__print_lines "$git_output" >/dev/stderr
+			fi
+			return "$git_status" # makes more sense to continue inheriting the git exit status 128 than converting it to EFTYPE 79 Inappropriate file type or format
+		elif test "$git_status" -ne 0; then
+			echo-style --error1='Encountered an unknown git exit status ' --code-error1="$git_status" --error1=' when fetching the git status of the directory:' --code-error1="$option_path" >/dev/stderr
+			if test -n "$git_output"; then
+				__print_lines "$git_output" >/dev/stderr
+			fi
+			return "$git_status"
+		fi
+
+		# done
+		return 0
+	}
+	function load_protocols {
+		if test "${#protocols[@]}" -eq 0; then
+			if ssh-helper test &>/dev/null; then
+				protocols+=('ssh')
+			fi
+			protocols+=('https')
+		fi
+	}
 	function get_protocol {
 		local protocol="${1:-"$GIT_PROTOCOL"}"
 		if test -n "$protocol"; then
 			__print_lines "$protocol"
 		else
-			choose \
+			load_protocols
+			choose --required \
 				--question='Which git protocol to use?' \
 				--default="$protocol" -- "${protocols[@]}"
+		fi
+	}
+	function get_remotes {
+		# verify path, assumed verified for other actions
+		local remote_status remote_output
+		eval_capture --statusvar=remote_status --outputvar=remote_output -- git remote
+		if test "$remote_status" -eq 128; then
+			echo-style --error1='The directory is not a git repository: ' --code-error1="$option_path" >/dev/stderr
+			if test -n "$remote_output"; then
+				__print_lines "$remote_output" >/dev/stderr
+			fi
+			return "$status" # makes more sense to continue inheriting the git exit status 128 than converting it to EFTYPE 79 Inappropriate file type or format
+		elif test -z "$remote_output"; then
+			echo-style --error1='The directory is a git repository without any remotes: ' --code-error1="$option_path" >/dev/stderr
+			return 91 # ENOMSG 91 No message of desired type
+		elif test "$remote_status" -ne 0; then
+			echo-style --error1='Encountered an unknown git exit status ' --code-error1="$remote_status" --error1=' when fetching the remotes of the directory:' --code-error1="$option_path" >/dev/stderr
+			if test -n "$remote_output"; then
+				__print_lines "$remote_output" >/dev/stderr
+			fi
+			return "$remote_status"
+		else
+			__print_lines "$remote_output"
 		fi
 	}
 	function get_remote_name {
@@ -170,7 +217,8 @@ function git_helper() (
 		if test -n "$remote"; then
 			__print_lines "$remote"
 		else
-			mapfile -t remotes < <(git remote)
+			# assume verified
+			mapfile -t remotes < <(get_remotes)
 			choose --required \
 				--question="$question" \
 				-- "${remotes[@]}"
@@ -405,7 +453,7 @@ function git_helper() (
 
 		# process
 		local original_url https_url ssh_url proposed_url=''
-		original_url="$(get_remote_url "$remote")"
+		original_url="$(get_remote_url "$remote" || :)"
 		https_url="$(format_protocol "$original_url" https)"
 		ssh_url="$(format_protocol "$original_url" ssh)"
 		proposed_url="$(format_protocol "$original_url" "$protocol")"
@@ -423,13 +471,14 @@ function git_helper() (
 
 		# apply difference if necessary
 		if test "$proposed_url" != "$original_url"; then
-			set_remote_url "$remote" "$proposed_url"
+			set_remote_url "$remote" "$proposed_url" # this will set a non-existent remote
 		fi
+		# @todo there is an [else] edge case here where the remote does not exist, in which the below will fail
 
 		# test application
 		function test_with_fallback {
 			local protocol="$1"
-			# 2todo style this with eval-helper pending/success/failure
+			# @todo style this with eval-helper pending/success/failure
 			__print_lines "Testing remote=[$remote] protocol=[$protocol] url=[$proposed_url] ..."
 			if __test_remote_name "$remote"; then
 				return 0
@@ -495,15 +544,15 @@ function git_helper() (
 	function git_review {
 		# @todo make this configurable
 		if __command_exists -- gf; then
-			gf "$@"
+			gf "$option_path" "$@"
 		elif get-app --quiet -- 'Gitfox'; then
-			open-app 'Gitfox' -- "$@"
+			open-app 'Gitfox' -- "$option_path" "$@"
 		elif __command_exists -- tower; then
-			tower "$@"
+			tower "$option_path" "$@"
 		elif get-app --quiet -- 'Tower'; then
-			open-app 'Tower' -- "$@"
+			open-app 'Tower' -- "$option_path" "$@"
 		else
-			help "No supported git reviewers installed."
+			help 'No supported git reviewers installed.'
 		fi
 	}
 
@@ -513,7 +562,7 @@ function git_helper() (
 	}
 
 	function git_update {
-		local item option_remote_name='origin' option_remote_url=''
+		local item option_remote_name='' option_remote_url=''
 		while test "$#" -ne 0; do
 			item="$1"
 			shift
@@ -533,21 +582,12 @@ function git_helper() (
 			esac
 		done
 
-		# verify path, assumed verified for other actions
-		local BODY=''
-		BODY="$(mktemp)"
-		if ! git remote &>"$BODY"; then
-			echo-error "$0: No git repository at $option_path"
-			return 1
-		elif test ! -s "$BODY"; then
-			echo-error "$0: No git remotes found at $option_path"
-			return 1
-		fi
-
 		# ensure remote in case it was empty
-		option_remote_name="$(get_remote_name "$option_remote_name")"
+		option_remote_name="$(get_remote_name "$option_remote_name" 'Which remote to pull?')"
 
 		# helper
+		local PULL_OUTPUT_FILE
+		PULL_OUTPUT_FILE="$(mktemp)"
 		function do_update {
 			# avoid merge conflicts
 			git config pull.ff only
@@ -560,19 +600,20 @@ function git_helper() (
 			# update all origins, branches, and prune remote deleted branches
 			git fetch --all --prune
 			# apply the remote changes to the local branch
-			git pull "$option_remote_name" "$(get_default_branch)" | tee "$BODY"
+			git pull "$option_remote_name" "$(get_default_branch)" | tee "$PULL_OUTPUT_FILE"
 		}
 
-		# write to BODY so that already updated can be detected
+		# write to PULL_OUTPUT_FILE so that already updated can be detected
 		# write to stderr so that [git_update] returns only [failure|current|updated]
 		# @todo style this with eval-helper pending/success/failure
 		local update_status
 		eval_capture --statusvar=update_status --outputpipe=/dev/stderr -- do_update
 		if test "$update_status" -ne 0; then
 			# update failed
+			echo-style --error1='git failed with exit status: ' --code-erro1="$update_status" >/dev/stderr
 			__print_lines 'failure'
 			return 1
-		elif grep --quiet --fixed-strings --regexp='Already' <"$BODY"; then
+		elif grep --quiet --fixed-strings --regexp='Already' <"$PULL_OUTPUT_FILE"; then
 			# already up to date
 			__print_lines 'current'
 		else
@@ -591,6 +632,15 @@ function git_helper() (
 	# =====================================
 	# Act
 
+	# enter the path so that git commands work correctly
+	cd "$option_path"
+
+	# verify?
+	if test "$option_verify" = 'yes'; then
+		verify_repository
+	fi
+
+	# perform the action
 	case "$action" in
 	'authors') get_authors "${option_args[@]}" ;;
 	'author-update') author_update "${option_args[@]}" ;;
@@ -607,6 +657,7 @@ function git_helper() (
 	'review') git_review "${option_args[@]}" ;;
 	'unstage') git_unstage "${option_args[@]}" ;;
 	'update') git_update "${option_args[@]}" ;;
+	'verify') verify_repository "${option_args[@]}" ;;
 	'wipe') git_wipe "${option_args[@]}" ;;
 	*) help "Unknown <action>." ;;
 	esac
