dramatic networking utility improvements
DNS utilities (`setup-dns`, `select-dns`) have been reworked:

- DNS selection now support Linux via `resolv`, `systemctl`, `ifdown`, and `ifup`
- DNS selection no longer fails if `NOFAP_DISCORD_WEBHOOK` optional env variable doesn't exist
- DNS selection can now select Cloudflare Teams via `cf-teams`
- DNS selection can now select `127.0.0.1:5553` via `local-5553`
- DNS setup resupports the latest Cloudflared utility, which configuration for DNS proxying has changed and simplified, and can now upgrade the service, and supports linux
- DNS setup resupports AdGuard Home, and can now upgrade the service, and supports linux
- DNS setup resupports DNSCrypt Proxy which configuration changed somewhat, and can now upgrade the service, and supports linux
- DNS setup UX has also been reworked, to make it a lot more intuitive, easier, and with smarter console outputs, and more intelligent testing

Downloaders have been reworked to support `dnscrypt-proxy` download in `setup-dns`:

- `down-zip-file` has been rewritten to properly implement its arguments, and its subfile now supports globs, in case say a directory name is amorphous

- `github-release-file` now does partial filename matches instead of absolute, this supports situations where say the file has a transient version number attached to it

- `github-release-file-download` now supports extracting files from archives, rather than just direct respository files

This has all been done to support Docker in circumstances where one's ISP, Government, or any other party is intercepting one's DNS, whcih can cause new security changes to determine this and cause Docker containers to fail. In processing this, the following utilities have also been added:

- `debug-docker` to debug your docker container connectivity
- `devbug-network` to debug your network connectivity

The following supportive utilities have also been added to facilitate all of this:

- `what-is-my-country`
- `what-is-my-dns`
- `what-is-my-exposed-dns`
- `what-is-my-ip`
- `what-is-my-local-ip`
- `what-is-my-resolver`

For background on these changes, please refer to:

- https://superuser.com/a/1660609/32418
- https://github.com/haugene/docker-transmission-openvpn/issues/1858#issuecomment-873124550

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/github-release-file-download b/commands/github-release-file-download
--- a/commands/github-release-file-download
+++ b/commands/github-release-file-download
@@ -1,4 +1,18 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-down "$(github-release-file "$1" "$2")" "${3-}"
+url="$(github-release-file "$1" "$2")"
+if test -z "$url"; then
+	stderr echo "failed to determine the release file for [$1] [$2]"
+	exit 1
+fi
+
+if echo "$url" | rg '.(tar|gz|zip)'; then
+	# may include arguments for subfile and destination
+	echo "extracting [$url] to [${@:3}]"
+	down-zip-file "$url" "${@:3}"
+else
+	# may include argument for destination
+	echo "downloading [$url] to [${3-}]"
+	down "$url" "${3-}"
+fi
