`confirm-*`: enforce `--ppid=$$` as too many issues without
also adapt code for `echo-lines --` to ensure things like `--help` don't bubble

diff --git a/commands/gocryptfs-helper b/commands/gocryptfs-helper
--- a/commands/gocryptfs-helper
+++ b/commands/gocryptfs-helper
@@ -71,7 +71,7 @@ function help() {
 			Verifies that the path is a gocryptfs vault.
 	EOF
 	if test "$#" -ne 0; then
-		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines "$@")" >/dev/stderr
+		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
 	fi
 	return 22 # Invalid argument
 }
@@ -256,7 +256,7 @@ function act_migrate {
 	do_mount "$new_vault" "$new_plain"
 
 	# speed
-	if confirm-positive "Run a speed comparison?"; then
+	if confirm-positive --ppid=$$ -- "Run a speed comparison?"; then
 		fs-speed "$old_plain"
 		fs-speed "$new_plain"
 	fi
@@ -280,7 +280,7 @@ function act_migrate {
 		Delete:  $old_vault
 		Move:    $new_vault  =>  $old_vault
 	EOF
-	if ! confirm-bool "Proceed with replacement?"; then
+	if ! confirm-bool --ppid=$$ -- "Proceed with replacement?"; then
 		return 1
 	fi
 	do_remove "$old_vault"
