gpg-helper: got it going with the rewrite from earlier
8da132804016fed498c5f779ae3bc0b090f117ba

diff --git a/commands/gpg-helper b/commands/gpg-helper
--- a/commands/gpg-helper
+++ b/commands/gpg-helper
@@ -1,10 +1,141 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-function gpg_edit {
-	source "$DOROTHY/sources/edit.sh"
-	edit "$HOME/.gnupg/" "$HOME/.gnupg/*.conf"
+# =====================================
+# Arguments
+
+# prepare
+actions=(
+	'configure'
+	'list'
+	'get'
+	'private'
+	'export'
+	'delete'
+	'new'
+	'edit'
+	'trust'
+	'extend'
+	'expire'
+	'encrypt'
+	'decrypt'
+	'symmetric'
+)
+
+# help
+function help() {
+	cat <<-EOF >/dev/stderr
+		ABOUT:
+		Helpers for interacting with GPG (GNU Pretty Good Privacy).
+
+		USAGE:
+
+		gpg-helper configure
+
+		    Open the gpg configuration files in your desired editor.
+
+		gpg-helper list
+		  <public|private>
+
+		    Output the details for all keys.
+
+		gpg-helper get
+		  <public|private>
+
+		    Output the identifier of a selected key.
+
+		gpg-helper export
+		  <public|private>
+		  <key id>
+
+		    Output the contents of a specific key.
+
+			 This [gpg-helper export public] is what you want to share your public key with another.
+
+		gpg-helper delete
+		  <public|private>
+		  <key id>
+
+		    Delete a specific key.
+
+		gpg-helper new
+
+		    Generate a new key.
+
+		gpg-helper edit
+		  <key id>
+
+		    Edit a specific private key.
+
+		gpg-helper trust
+		  <private key id>
+
+		    Mark that you trust a specific key.
+
+		gpg-helper extend
+		  <private key id>
+		  <date>
+
+		    Extend a specific key to a specific date, or if no date was supplied, then a year from now.
+
+		gpg-helper expire
+		  <private key id>
+
+		    Expire a specific key by marking its expiry date was this very moment.
+
+		gpg-helper encrypt
+		  <the file>
+		  <their user id, e.g. email>
+		  [your secret user id, e.g. email]
+
+		    Encrypt a file between yourself and someone else.
+
+			 You must have imported their public key into your keyring already.
+
+		gpg-helper decrypt
+		  <the file>
+
+		    Decrypt a file that has been encrypted to your public key.
+
+		gpg-helper symmetric
+		  <the file>
+
+		    Encrypt a file using a passphrase insteaad.
+
+	EOF
+	if test "$#" -ne 0; then
+		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
+	fi
+	return 22 # Invalid argument
 }
+
+# process
+action=''
+action_args=()
+while test "$#" -ne 0; do
+	item="$1"
+	shift
+	case "$item" in
+	'help' | '--help' | '-h') help ;;
+	'--'*) help "An unrecognised flag was provided: $item" ;;
+	*)
+		action="$item"
+		action_args+=("$@")
+		shift $#
+		break
+		;;
+	esac
+done
+
+# ensure valid action
+action="$(
+	choose-option --required \
+		--question='which action to perform?' \
+		--filter="$action" -- "${actions[@]}"
+)"
+
+# =====================================
+# Helpers
 
 # Guides
 # https://www.gnupg.org/gph/en/manual.html
@@ -19,24 +150,18 @@ function gpg_edit {
 # https://www.youtube.com/watch?v=ZSa-d_9O5DA
 
 # Codes
-# sec => 'Secret key'
-# ssb => 'Secret SuBkey'
-# pub => 'Public key'
-# sub => 'public SUBkey'
+# sec => 'secret key'
+# ssb => 'secret subkey'
+# pub => 'public key'
+# sub => 'public subkey'
 
-function getmode {
+# helpers
+function get_mode {
 	choose-option \
 		--question='What type of GPG key do you wish to fetch?' \
 		--filter="${1-}" -- 'public' 'private'
 }
-function getkey {
-	if test -n "${1-}"; then
-		echo "$1"
-	else
-		key get
-	fi
-}
-function getdate {
+function get_date {
 	if test -n "${1-}"; then
 		echo "$1"
 	else
@@ -44,28 +169,30 @@ function getdate {
 	fi
 }
 
-action="$(
-	choose-option \
-		--question='What action do you want to take?' \
-		--filter="${1-}" -- list get export delete new edit trust extend expire encrypt decrypt sencrypt
-)"
+# =====================================
+# Actions
+
+# configure
+function act_configure {
+	source "$DOROTHY/sources/edit.sh"
+	edit "$HOME/.gnupg/" "$HOME/.gnupg/*.conf"
+}
 
 # list [mode]
-if test "$action" = "list"; then
-	mode="$(getmode "${2-}")"
+function act_list {
+	local mode
+	mode="$(get_mode "${1-}")"
 	if test "$mode" = "private"; then
 		gpg --keyid-format LONG -K
 	else
 		gpg --keyid-format LONG -k
 	fi
+}
 
 # get [mode] [key]
-elif test "$action" = "get"; then
-	if test -n "${3-}"; then
-		echo "$3"
-		exit 0
-	fi
-	mode="$(getmode "${2-}")"
+function act_get {
+	local mode flag type keys
+	mode="$(get_mode "${1-}")"
 	if test "$mode" = "private"; then
 		flag="K"
 		type="sec"
@@ -78,21 +205,25 @@ elif test "$action" = "get"; then
 	choose-option --required \
 		--question='Which key to select?' \
 		-- "${keys[@]}"
+}
 
 # export [mode] [key]
-elif test "$action" = "export"; then
-	mode="$(getmode "${2-}")"
-	key="$(key get "$mode" "${3-}")"
+function act_export {
+	local mode key
+	mode="$(get_mode "${1-}")"
+	key="$(act_get "$mode" "${2-}")"
 	if test "$mode" = "private"; then
 		gpg --armor --export-secret-keys "$key"
 	else
 		gpg --armor --export "$key"
 	fi
+}
 
 # delete [mode] [key]
-elif test "$action" = "delete"; then
-	mode="$(getmode "${2-}")"
-	key="$(key get "$mode" "${3:?"USAGE: key delete <mode> <KEY>"}")"
+function act_delete {
+	local mode key
+	mode="$(get_mode "${1-}")"
+	key="$(act_get "$mode" "${2-}")"
 	if confirm-bool --ppid=$$ -- "Confirm you wish to delete [$mode] key [$key]?"; then
 		if test "$mode" = "private"; then
 			gpg --delete-secret-keys "$key"
@@ -100,61 +231,91 @@ elif test "$action" = "delete"; then
 			gpg --delete-keys "$key"
 		fi
 	fi
+}
 
 # new
-elif test "$action" = "new"; then
+function act_new {
 	gpg --gen-key
+}
 
 # edit [key]
-elif test "$action" = "edit"; then
-	key="$(getkey "${2-}")"
+function act_edit {
+	local key
+	key="$(act_get private "${1-}")"
 	gpg --edit-key "$key"
+}
 
 # trust [key]
-elif test "$action" = "trust"; then
-	key="$(key get private "${2-}")"
+function act_trust {
+	local key
+	key="$(act_get private "${1-}")"
 	if confirm-bool --ppid=$$ -- "Confirm you wish to trust key [$key]?"; then
 		echo "trust" | gpg --edit-key "$key"
 	fi
+}
 
 # extend [key] [date]
-elif test "$action" = "extend"; then
-	key="$(key get private "${2-}")"
-	date="$(getdate "${3-}")"
+function act_extend {
+	local key date
+	key="$(act_get private "${1-}")"
+	date="$(get_date "${2-}")"
 	if confirm-bool --ppid=$$ -- "Confirm you wish to extend key [$key] to [$date]?"; then
 		gpg --quick-set-expire "$key" "$date"
 	fi
+}
 
 # expire [key]
-elif test "$action" = "expire"; then
-	key="$(key get private "${2-}")"
+function act_expire {
+	key="$(act_get private "${1-}")"
 	date="$(date -v +0d "+%Y-%m-%d")"
 	if confirm-bool --ppid=$$ -- "Confirm you want to expire key [$key]?"; then
 		gpg --quick-set-expire "$key" "$date"
 	fi
+}
 
-# encrypt <file> <receipient's key> [your key]
-elif test "$action" = "encrypt"; then
-	file="${2:?"USAGE: key encrypt <FILE> <RECIPIENT's KEY> [your key]"}"
-	recipient="${3:?"USAGE: key encrypt <file> <RECIPIENT's KEY> [your key]"}"
-	you="${4-}"
-	if test -n "$you"; then
-		gpg -ase -r "$recipient" -u "$you" "$file"
-	else
-		gpg -ase -r "$recipient" "$file"
+# encrypt <file> <their user id> <your secret key id>
+function act_encrypt {
+	local file them you
+	file="${1-}"
+	them="${2-}"
+	you="${3-}" # "$(act_get private "${3-}")"
+	if test -z "$file" -o -z "$them"; then
+		help "encrypt requires file and their user id"
 	fi
+	if test -n "$you"; then
+		gpg -ase -r "$them" -u "$you" "$file"
+	else
+		gpg -ase -r "$them" "$file"
+	fi
+}
 
 # decrypt <file>
-elif test "$action" = "decrypt"; then
-	file="${2:?"USAGE: key descrypt <FILE>"}"
+function act_decrypt {
+	local file
+	file="${1-}"
+	if test -z "$file"; then
+		help "decrypt requires file"
+	fi
 	gpg -d "$file"
+}
 
-# sencrypt <file>
-elif test "$action" = "sencrypt"; then
-	file="${2:?"USAGE: key sencrypt <FILE>"}"
+# symmetric <file>
+function act_symmetric {
+	local file
+	file="${1-}"
+	if test -z "$file"; then
+		help "symmetric encryption requires file"
+	fi
 	gpg -c "$file"
+}
 
+# =====================================
+# Act
+
+if test "$(type -t "act_$action")" = 'function'; then
+	"act_$action" "${action_args[@]}"
+	exit "$?"
 else
-	stderr echo 'invalid action'
-	exit 1
+	echo-style --error="Action [$action] not yet implemented." >/dev/stderr
+	exit 78 # Function not implemented
 fi
