ci: debug https://github.com/bevry/dorothy/runs/6017919758

diff --git a/commands/is-empty-string b/commands/is-empty-string
--- a/commands/is-empty-string
+++ b/commands/is-empty-string
@@ -1,23 +1,29 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# prepare
-v="${1-}"
+function is-empty-string() (
+	local value="${1-}" i c
 
-# check if it is empty
-if test -z "$v"; then
-	exit 0
-fi
-
-# cycle through the characters
-for ((i = 0; i < ${#v}; i++)); do
-	c="${v:i:1}"
-	# check for non-empty characters
-	if ! test -z "$c" -o "$c" = $'\n' -o "$c" = $'\t' -o "$c" = ' '; then
-		# non-empty character found, fail
-		exit 1
+	# check if it is empty
+	if test -z "$value"; then
+		exit 0
 	fi
-done
 
-# all characters where empty, success
-exit 0
+	# cycle through the characters
+	for ((i = 0; i < ${#value}; i++)); do
+		c="${value:i:1}"
+		# check for non-empty characters
+		if ! test -z "$c" -o "$c" = $'\n' -o "$c" = $'\t' -o "$c" = ' '; then
+			# non-empty character found, fail
+			return 1
+		fi
+	done
+
+	# all characters where empty, success
+	return 0
+)
+
+# fire if invoked standalone
+if test "$0" = "${BASH_SOURCE[0]}"; then
+	is-empty-value "$@"
+fi
