breaking changes and quality of life improvements
Dorothy has come a long way in its near 10 years of development.
Initially it was licensed under the Unlicense, which was appropriate while it was simple functions.
However, as the years have gone by, Dorothy is now a complete ecosystem to enhance the dotfile development of yourself and your peers.
Some of its abilities have signficantly led the frontier, and as such, have been plagarised by non-reciprocal entities.
The license is now the RPL-1.5, to help its abilities continue to grow inside the commons, and don't just end behind yet another vc backed extend and extinguish strategy that leveraged the public R&D.
Eventually Dorothy will be dual-licensed using https://fareness.dev - which will also enable reciprocation via finances, rather than just source, which seems a better model than the zero-traction support tier model which is now removed from the readme.

Anyway, here is the changelog.

core improvements:

- `ACTIVE_LOGIN_SHELL` is no longer exported and is `ACTIVE_SHELL`
- `get_active_shell` now inlined into `sources/environment.sh`
- removed unused `sources/debug.bash`, use `debug-bash` instead
- `sources/home.sh` inlined into `setup-environment-commands` and `sudo-helper`
  - this enables non-dorothy invocations via:
    - crontab
    - `env -i "$(which bash)" -- "$(which dorothy-command)"`
- `{config,sources}/shell.*` now `interactive.*` to reflect what it does
- `{config,sources}/init.*` now `login.*` to reflect what it does
- `MAILCHECK` is no longer set as it doesn't work anymore, instead use the builtin `mail` command to attend to your terminal mail
- `sources/{shims,nullglob,globstar,extglob,arrays,strict}` merged into `sources/bash.bash`
  - `requires_array_support` now `require_array`
  - `nullglob.bash` now `require_nullglob`
  - `extglob.bash` now `require_extglob`
  - `nullglob.bash` now `require_nullglob`

command improvements:

- add `setup-util-cronitor`
- add `get-devices`
  - replaces `get-drive-info`, `get-drives`
- add `get-filesystem`
  - enhances `is-btrfs`
- add `mount-helper`
  - replaces `is-mounted`, `fs-mount`, `fs-unmount`
- enhanced `btrfs-helper`
- `edit` added some comments about absolute paths, which for now, doesn't seem necessary

diff --git a/commands/is-mounted b/commands/is-mounted
--- a/commands/is-mounted
+++ b/commands/is-mounted
@@ -1,22 +1,110 @@
 #!/usr/bin/env bash
 
 function is-mounted() (
-	source "$DOROTHY/sources/strict.bash"
+	source "$DOROTHY/sources/bash.bash"
 
-	local mount_source mount_target
-	mount_source="$(get-flag-value 'source' -- "$@")"
-	mount_target="$(get-flag-value 'target' -- "$@")"
+	# =====================================
+	# Arguments
 
-	if test -n "$mount_source" -a -n "$mount_target"; then
-		mount | grep --fixed-strings --regexp="${mount_source} on ${mount_target} type "
-	elif test -n "$mount_source"; then
-		mount | grep --fixed-strings --regexp="${mount_source} on"
-	elif test -n "$mount_target"; then
-		mount | grep --fixed-strings --regexp="on ${mount_target} type "
-	else
-		echo "need [--source=...] and/or [--target=...] arguments" >/dev/stderr
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Checks mounts for the presence of a source, target, type.
+
+			USAGE:
+			is-mounted [...options]
+
+			OPTIONS:
+			--source=<source>
+			--target=<mount-point>
+			--type=<type>
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # Invalid argument
+	}
+
+	# prepare
+	while test "${1-}" = '--'; do
+		shift
+	done
+
+	# process
+	local item __source='' target='' __type=''
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--source='*) __source="${item#*--source=}" ;;
+		'--target='*) target="${item#*--target=}" ;;
+		'--type='*) __type="${item#*--type=}" ;;
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) help "An unrecognised argument was provided: $item" ;;
+		esac
+	done
+
+	# =====================================
+	# dependencies
+
+	source "$DOROTHY/sources/ripgrep.bash"
+
+	# =====================================
+	# Helpers
+
+	local check_source='' check_target='' check_type='' filter=''
+
+	# create the check needle
+	if test -n "$source"; then
+		check_source="${__source} on "
+	fi
+	if test -n "$target"; then
+		check_target=" on ${target} "
+	fi
+	if test -n "$__type"; then
+		if is-mac; then
+			check_type+=" ($__type"
+		else
+			check_type+=" type $__type "
+		fi
+	fi
+
+	# check if invalid
+	if test -z "$check_source" -a -z "$check_target" -a -z "$check_type"; then
+		echo-error "Invalid arguments to; mount-helper --check"
 		return 22 # Invalid argument
 	fi
+
+	# start filtering
+	filter="$(mount)"
+	if test -n "$check_source"; then
+		filter="$(echo "$filter" | rg --fixed-strings --regexp="$check_source" || :)"
+		if test -z "$filter"; then
+			echo-style --error='missing mount source:' ' ' --code="$__source"
+			return 1
+		fi
+		echo-style --success='found mount source:' ' ' --code="$__source"
+	fi
+	if test -n "$check_target"; then
+		filter="$(echo "$filter" | rg --fixed-strings --regexp="$check_target" || :)"
+		if test -z "$filter"; then
+			echo-style --error='missing mount target:' ' ' --code="$target"
+			return 1
+		fi
+		echo-style --success='found mount target:' ' ' --code="$target"
+	fi
+	if test -n "$check_type"; then
+		filter="$(echo "$filter" | rg --fixed-strings --regexp="$check_type" || :)"
+		if test -z "$filter"; then
+			echo-style --error='missing mount type:' ' ' --code="$__type"
+			return 1
+		fi
+		echo-style --success='found mount type:' ' ' --code="$__type"
+	fi
+
+	# valid
+	return 0
 )
 
 # fire if invoked standalone
