better `--help` for several commands
/ref https://github.com/bevry/dorothy/issues/7

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/is-same b/commands/is-same
--- a/commands/is-same
+++ b/commands/is-same
@@ -3,14 +3,29 @@ source "$DOROTHY/sources/strict.bash"
 
 # options
 mapfile -t options < <(echo-before-separator "$@")
-option_algorithm=''  # confirmed later, as may not be necessary if paths match
+option_algorithm="$(get-flag-value algorithm -- "${options[@]}")"
 mapfile -t option_paths < <(echo-after-separator "$@")
 
 # verify
-if test "${#option_paths[@]}" -ne 2; then
-	echo 'USAGE:' > /dev/stderr
-	echo 'is-same [--algorithm=...] -- <first path> <second path>' > /dev/stderr
-	exit 2
+if test "${#option_paths[@]}" -ne 2 || is-help "$@"; then
+	stderr echo-lines \
+		'ABOUT:' \
+		'Compares two paths to determine if their contents are identical, compares:' \
+		'- paths' \
+		'- real paths, via [fs-realpath]' \
+		'- structure, via [fs-structure]' \
+		'- checksum, via [checksum]' \
+		'' \
+		'USAGE:' \
+		'is-same [--algorithm=...] -- <first path> <second path>' \
+		'' \
+		'FLAGS:' \
+		'Provide [--algorithm=...] to pre-specify a checksum algorithm. See [checksum --help] for details.' \
+		'' \
+		'RETURNS:' \
+		'Exit code [0] if the same.' \
+		'Exit code [1] if different.'
+	exit 22 # Invalid argument
 fi
 
 # path checks
@@ -47,17 +62,13 @@ if test "$first_structure" != "$second_structure"; then
 	exit 1
 fi
 
-# checksum algo fetch
-option_algorithm="$(get-flag-value algorithm -- "${options[@]}")"
-option_algorithm="$(choose-option --question='Which checksum algorithm do you wish to use?' --filter="$option_algorithm" -- 'md5sum' 'shasum' 'sha256sum')"
-
-# checksum, trim the filenames
-mapfile -t checksums < <(checksum --no-name --action=summary --algorithm="$option_algorithm" -- "$first_path" "$second_path")  # instead of --no-name, `| cut -d' ' -f1` would have sufficed
+# checksum
+mapfile -t checksums < <(checksum --untitled --summary --algorithm="$option_algorithm" -- "$first_path" "$second_path")
 echo-lines "${checksums[@]}"
 
 # sanity
 if test "${#checksums[@]}" -ne 2; then
-	echo 'invalid amount of checksums'
+	echo "invalid amount of checksums, there should only be two, a summary checksum for each directory, instead there were: ${#checksums[@]}"
 	exit 1
 fi
 
