is-tty: tests: fix the pipe failure

diff --git a/commands/is-tty b/commands/is-tty
--- a/commands/is-tty
+++ b/commands/is-tty
@@ -6,7 +6,7 @@ function is_tty_test() (
 	source "$(type -P eval-tester)"
 	echo-segment --h1="TEST: $0"
 
-	function do_test {
+	function do_test { # 👍 /docs/bash/errors: robust exit status, everything is ignored
 		print_line "\$- = $-"
 
 		# alpine doesn't support the [-p] argument
@@ -65,7 +65,7 @@ function is_tty_test() (
 	{
 		sleep 1
 		echo
-	} | do_test
+	} | do_test || : # this is necessary, as otherwise the pipe fails with 141
 
 	echo
 	print_line '### testing <<< ###'
