is-tty: more robust check

diff --git a/commands/is-tty b/commands/is-tty
--- a/commands/is-tty
+++ b/commands/is-tty
@@ -1,11 +1,23 @@
 #!/usr/bin/env bash
 
-# @todo detect NO_TTY and TTY=no
-
 function is-tty() (
 	source "$DOROTHY/sources/bash.bash"
 
-	test -t 0
+	# [-t 0] check stdin exists
+	# [-t 1] check stdout exists
+	# [-t 2] check stderr exists
+	# [-c '/dev/tty'] check tty exists
+	test -t 0 -a -t 1 -a -t 2 -a -c '/dev/tty' -a "${NO_TTY-}" != 'yes' -a "${TTY-}" != 'no'
+
+	# @todo handle NO_TTY=yes and TTY=no properly we need is-affirmative or echo-affirmative to not be as silly as they are
+	# is-affirmative fails if given only an empty string, and echo-affirmative outputs to stderr that must be silenced
+	#  -a "$(echo-affirmative "${NO_TTY-}" || :)" != 'yes' -a "$(echo-non-affirmative "${TTY-}" || :)" != 'yes'
+	# if test -n "${NO_TTY-}"; then
+	# 	! is-affirmative "$NO_TTY"
+	# fi
+	# if test -n "${TTY-}"; then
+	# 	! is-affirmative "$TTY"
+	# fi
 )
 
 # fire if invoked standalone
