is-tty: --test instead of --verbose, simple check
echo-lines: use stdinargs to support stdin and args

diff --git a/commands/is-tty b/commands/is-tty
--- a/commands/is-tty
+++ b/commands/is-tty
@@ -1,5 +1,162 @@
 #!/usr/bin/env bash
 
+function is_tty_test() (
+	source "$DOROTHY/sources/bash.bash"
+	source "$(type -P eval-tester)"
+	echo-segment --h1="TEST: $0"
+
+	function do_test {
+		print_line "\$- = $-"
+
+		print_line 'tty:'
+		ps -p "$$" -o tty= || :
+
+		( (tty -s && echo tty_s_pass) || echo tty_s_fail) || :
+
+		print_line '-----------'
+
+		( (test -t 0 && echo test_t_stdin_pass) || echo test_t_stdin_fail) || :
+		( (test -t 1 && echo test_t_stdout_pass) || echo test_t_stdout_fail) || :
+		( (test -t 2 && echo test_t_stderr_pass) || echo test_t_stderr_fail) || :
+
+		( (test -c /dev/stdin && echo test_c_stdin_pass) || echo test_c_stdin_fail) || :
+		( (test -c /dev/stdout && echo test_c_stdout_pass) || echo test_c_stdout_fail) || :
+		( (test -c /dev/stderr && echo test_c_stderr_pass) || echo test_c_stderr_fail) || :
+		( (test -c /dev/tty && echo test_c_tty_pass) || echo test_c_tty_fail) || :
+
+		( (exec </dev/stdin && echo exec_stdin_pass) || echo exec_stdin_fail) || :
+		( (exec </dev/stdout && echo exec_stdout_pass) || echo exec_stdout_fail) || :
+		( (exec </dev/stderr && echo exec_stderr_pass) || echo exec_stderr_fail) || :
+		( (exec </dev/tty && echo exec_tty_pass) || echo printf_tty_fail) || :
+
+		( (printf '' >/dev/stdout && echo printf_stdout_pass) || echo printf_stdout_fail) || :
+		( (printf '' >/dev/stderr && echo printf_stderr_pass) || echo printf_stderr_fail) || :
+		( (printf '' >/dev/tty && echo printf_tty_pass) || echo printf_tty_fail) || :
+
+		print_line '-----------'
+
+		echo | ( (test -t 0 && echo echo_test_t_stdin_pass) || echo echo_test_t_stdin_fail) || :
+		echo | ( (test -t 1 && echo echo_test_t_stdout_pass) || echo echo_test_t_stdout_fail) || :
+		echo | ( (test -t 2 && echo echo_test_t_stderr_pass) || echo echo_test_t_stderr_fail) || :
+
+		echo | ( (test -c /dev/stdin && echo echo_test_c_stdin_pass) || echo echo_test_c_stdin_fail) || :
+		echo | ( (test -c /dev/stdout && echo echo_test_c_stdout_pass) || echo echo_test_c_stdout_fail) || :
+		echo | ( (test -c /dev/stderr && echo echo_test_c_stderr_pass) || echo echo_test_c_stderr_fail) || :
+		echo | ( (test -c /dev/tty && echo echo_test_c_tty_pass) || echo echo_test_c_tty_fail) || :
+
+		( (test -t 0 0<&- && echo close_test_t_stdin_pass) || echo close_test_t_stdin_fail) || :
+		( (test -t 1 1<&- && echo close_test_t_stdout_pass) || echo close_test_t_stdout_fail) || :
+		( (test -t 2 2<&- && echo close_test_t_stderr_pass) || echo close_test_t_stderr_fail) || :
+
+		( (test -c /dev/stdin 0<&- && echo close_test_c_stdin_pass) || echo close_test_c_stdin_fail) || :
+		( (test -c /dev/stdout 1<&- && echo close_test_c_stdout_pass) || echo close_test_c_stdout_fail) || :
+		( (test -c /dev/stderr 2<&- && echo close_test_c_stderr_pass) || echo close_test_c_stderr_fail) || :
+
+	}
+
+	do_test
+
+	local stdout stderr
+
+	echo
+	print_line '### --stdoutvar ###'
+	stdout=''
+	stderr=''
+	eval_capture --stdoutvar=stdout -- do_test
+	print_line 'stdout ='
+	echo-lines --indent='    ' <<<"$stdout"
+	print_line 'stderr ='
+	echo-lines --indent='    ' <<<"$stderr"
+
+	echo
+	print_line '### --stderrvar ###'
+	stdout=''
+	stderr=''
+	eval_capture --stderrvar=stderr -- do_test
+	print_line 'stdout ='
+	echo-lines --indent='    ' <<<"$stdout"
+	print_line 'stderr ='
+	echo-lines --indent='    ' <<<"$stderr"
+
+	echo
+	print_line '### --stdoutvar --stderrvar ###'
+	stdout=''
+	stderr=''
+	eval_capture --stdoutvar=stdout --stderrvar=stderr -- do_test
+	print_line 'stdout ='
+	echo-lines --indent='    ' <<<"$stdout"
+	print_line 'stderr ='
+	echo-lines --indent='    ' <<<"$stderr"
+
+	# RUNNING ON MACOS
+	# + printf '%s\n' '$- = ehuxBE'
+	# $- = ehuxBE
+	# + tty -s
+	# + echo 'success status = 0'
+	# success status = 0
+	# + test -t 0
+	# + echo 'success status = 0'
+	# success status = 0
+	# + test -t 1
+	# + echo 'success status = 0'
+	# success status = 0
+	# + test -t 2
+	# + echo 'success status = 0'
+	# success status = 0
+	# + test -c /dev/stdin
+	# + echo 'success status = 0'
+	# success status = 0
+	# + test -c /dev/stdout
+	# + echo 'success status = 0'
+	# success status = 0
+	# + test -c /dev/stderr
+	# + echo 'success status = 0'
+	# success status = 0
+	# + test -c /dev/tty
+	# + echo 'success status = 0'
+	# success status = 0
+	# + echo 'NO_TTY = '
+	# NO_TTY =
+	# + echo 'TTY = '
+	# TTY =
+	# + ps -p 9850 -o tty=
+	# ttys011
+	# + echo 'success status = 0'
+	# success status = 0
+	# + exec
+	# + echo 'success status = 0'
+	# success status = 0
+	# + printf ''
+	# + echo 'success status = 0'
+	# success status = 0
+	# + set +x
+
+	# RUNNING ON MACOS VIA CRON
+	# < 'test' '-t' '0' >
+	# </ 'test' '-t' '0' >[1]
+	# < 'test' '-t' '1' >
+	# </ 'test' '-t' '1' >[1]
+	# < 'test' '-t' '2' >
+	# </ 'test' '-t' '2' >[1]
+	# < 'test' '-c' '/dev/tty' >
+	# </ 'test' '-c' '/dev/tty' >[0]
+	# < 'echo' '' >
+	# </ 'echo' '' >[0]
+	# < 'echo' '' >
+	# </ 'echo' '' >[0]
+	# < 'ps' '-p' '19201' '-o' 'tty=' >
+	# ??
+	# </ 'ps' '-p' '19201' '-o' 'tty=' >[0]
+	# + exec
+	# /Users/balupton/.local/share/dorothy/commands/is-tty: line 15: /dev/tty: Device not configured
+	# ++ EXIT_STATUS=1
+	# ++ test is_tty = eval_capture_wrapper
+	# ++ test -n is_tty
+	# ++ return 1
+
+	echo-segment --g1="TEST: $0"
+	return 0
+)
 function is_tty() (
 	source "$DOROTHY/sources/bash.bash"
 
@@ -13,11 +170,7 @@ function is_tty() (
 			This is important, as otherwise calls to [tty] will result in "not a tty" being output.
 
 			USAGE:
-			is-tty [...options]
-
-			OPTIONS:
-			--verbose
-			    If provided, output more information.
+			is-tty
 		EOF
 		if test "$#" -ne 0; then
 			echo-error "$@"
@@ -26,14 +179,12 @@ function is_tty() (
 	}
 
 	# process
-	local item option_quiet=''
-	option_quiet="$(echo-quiet --no-env "$option_quiet" -- "$@")"
+	local item
 	while test "$#" -ne 0; do
 		item="$1"
 		shift
 		case "$item" in
 		'--help' | '-h') help ;;
-		'--no-quiet'* | '--quiet'* | '--no-verbose'* | '--verbose'*) ;; # handled by echo-quiet
 		'--'*) help "An unrecognised flag was provided: $item" ;;
 		*) help "An unrecognised argument was provided: $item" ;;
 		esac
@@ -42,120 +193,16 @@ function is_tty() (
 	# =====================================
 	# Action
 
-	if test "$option_quiet" = 'no'; then
-		set -x
-		printf '%s\n' "\$- = $-"
-		(tty -s && echo "success status = $?") || echo "failure status = $?"
-		(test -t 0 && echo "success status = $?") || echo "failure status = $?"
-		(test -t 1 && echo "success status = $?") || echo "failure status = $?"
-		(test -t 2 && echo "success status = $?") || echo "failure status = $?"
-		(test -c '/dev/stdin' && echo "success status = $?") || echo "failure status = $?"
-		(test -c '/dev/stdout' && echo "success status = $?") || echo "failure status = $?"
-		(test -c '/dev/stderr' && echo "success status = $?") || echo "failure status = $?"
-		(test -c '/dev/tty' && echo "success status = $?") || echo "failure status = $?"
-		echo "NO_TTY = ${NO_TTY-}"
-		echo "TTY = ${TTY-}"
-		(ps -p "$$" -o tty= && echo "success status = $?") || echo "failure status = $?"
-		(exec </dev/tty && echo "success status = $?") || echo "failure status = $?"
-		(printf '' >/dev/tty && echo "success status = $?") || echo "failure status = $?"
-		( (exec </dev/tty) &> /dev/null && echo "success status = $?") || echo "failure status = $?"
-		( (printf '' >/dev/tty) &> /dev/null && echo "success status = $?") || echo "failure status = $?"
-		set +x
-
-		# RUNNING ON MACOS
-		# + printf '%s\n' '$- = ehuxBE'
-		# $- = ehuxBE
-		# + tty -s
-		# + echo 'success status = 0'
-		# success status = 0
-		# + test -t 0
-		# + echo 'success status = 0'
-		# success status = 0
-		# + test -t 1
-		# + echo 'success status = 0'
-		# success status = 0
-		# + test -t 2
-		# + echo 'success status = 0'
-		# success status = 0
-		# + test -c /dev/stdin
-		# + echo 'success status = 0'
-		# success status = 0
-		# + test -c /dev/stdout
-		# + echo 'success status = 0'
-		# success status = 0
-		# + test -c /dev/stderr
-		# + echo 'success status = 0'
-		# success status = 0
-		# + test -c /dev/tty
-		# + echo 'success status = 0'
-		# success status = 0
-		# + echo 'NO_TTY = '
-		# NO_TTY =
-		# + echo 'TTY = '
-		# TTY =
-		# + ps -p 9850 -o tty=
-		# ttys011
-		# + echo 'success status = 0'
-		# success status = 0
-		# + exec
-		# + echo 'success status = 0'
-		# success status = 0
-		# + printf ''
-		# + echo 'success status = 0'
-		# success status = 0
-		# + set +x
-
-		# RUNNING ON MACOS VIA CRON
-		# < 'test' '-t' '0' >
-		# </ 'test' '-t' '0' >[1]
-		# < 'test' '-t' '1' >
-		# </ 'test' '-t' '1' >[1]
-		# < 'test' '-t' '2' >
-		# </ 'test' '-t' '2' >[1]
-		# < 'test' '-c' '/dev/tty' >
-		# </ 'test' '-c' '/dev/tty' >[0]
-		# < 'echo' '' >
-		# </ 'echo' '' >[0]
-		# < 'echo' '' >
-		# </ 'echo' '' >[0]
-		# < 'ps' '-p' '19201' '-o' 'tty=' >
-		# ??
-		# </ 'ps' '-p' '19201' '-o' 'tty=' >[0]
-		# + exec
-		# /Users/balupton/.local/share/dorothy/commands/is-tty: line 15: /dev/tty: Device not configured
-		# ++ EXIT_STATUS=1
-		# ++ test is_tty = eval_capture_wrapper
-		# ++ test -n is_tty
-		# ++ return 1
-	fi
-
-	# So...
-	# [-t {0,1,2}] checks if {0,1,2} is attached to a terminal
-	# e.g. [echo | eval 'test -t 0 || echo no'] returns [no], as it fails [-t 0]
-	# e.g. [eval_capture --stdoutvar=...] fails [-t 1]
-	# e.g. [eval_capture --stderrvar=...] fails [-t 2]
-	# [-c /dev/{stdin,stdout,stderr,tty}] checks if it is available, regardless of termiinal attachment
-	# e.g. [(exec 0<&-; test -c /dev/stdin || echo no)] returns [no], as it fails [-c /dev/stdin]
-	# e.g. [(exec 2>&-; test -c /dev/stderr || echo no)] returns [no], as it fails [-c /dev/stderr]
-	# Cron jobs still pass [-c /dev/tty] even though /dev/tty is inaccessible [/dev/tty: Device not configured], as such [/dev/tty] would fail a [-t] check if TTY had a FD
-	# As such, we run a [ps -p] check to see if the process [/dev/tty] is actually attached to a terminal, as unlike {stdin,stdout,stderr} the /dev/tty must be attached to a terminal to be open/accessible.
-	test -c '/dev/tty' -a "${NO_TTY-}" != 'yes' -a "${TTY-}" != 'no'
-
-	# inside an [apk] check as alpine returns the following:
-	# ps: unrecognized option: p
-	# BusyBox v1.36.1 (2023-07-27 17:12:24 UTC) multi-call binary.
-	# Usage: ps [-o COL1,COL2=HEADER] [-T]
-	# Show list of processes
-	# -o COL1,COL2=HEADER	Select columns for display
-	if command-missing apk; then
-		[[ "$(ps -p "$$" -o tty= 2>/dev/null)" != '?'* ]]
-	fi
-
-	# if we got here, no exception, so success
-	return 0
+	# correctly test if TTY is writable
+	(exec </dev/tty) &>/dev/null
+	return $?
 )
 
 # fire if invoked standalone
 if test "$0" = "${BASH_SOURCE[0]}"; then
-	is_tty "$@"
+	if test "$*" = '--test'; then
+		is_tty_test
+	else
+		is_tty "$@"
+	fi
 fi
