is-tty: addd a printf test in verbose mode

diff --git a/commands/is-tty b/commands/is-tty
--- a/commands/is-tty
+++ b/commands/is-tty
@@ -55,12 +55,12 @@ function is_tty() (
 		(test -c '/dev/tty' && echo "success status = $?") || echo "failure status = $?"
 		echo "NO_TTY = ${NO_TTY-}"
 		echo "TTY = ${TTY-}"
-		(ps -p "$$" -o tty= 2>/dev/null && echo "success status = $?") || echo "failure status = $?"
-		(exec </dev/tty 2>/dev/null && echo "success status = $?") || echo "failure status = $?"
+		(ps -p "$$" -o tty= && echo "success status = $?") || echo "failure status = $?"
+		(exec </dev/tty && echo "success status = $?") || echo "failure status = $?"
+		(printf '' >/dev/tty && echo "success status = $?") || echo "failure status = $?"
 		set +x
 
 		# RUNNING ON MACOS
-		# > is-tty --verbose
 		# + printf '%s\n' '$- = ehuxBE'
 		# $- = ehuxBE
 		# + tty -s
@@ -91,11 +91,15 @@ function is_tty() (
 		# NO_TTY =
 		# + echo 'TTY = '
 		# TTY =
-		# + ps -p 25372 -o tty=
-		# ttys006
+		# + ps -p 9850 -o tty=
+		# ttys011
 		# + echo 'success status = 0'
 		# success status = 0
 		# + exec
+		# + echo 'success status = 0'
+		# success status = 0
+		# + printf ''
+		# + echo 'success status = 0'
 		# success status = 0
 		# + set +x
 
