setup-util-bash: improve interactive detection with new is-interactive
is-interactive uses is-ci and is-tty

is-tty, is-ci, is-interactive now use `--verbose` argument instead of `--debug`

is-affirmative updates to better support empty arguments when desired

diff --git a/commands/is-tty b/commands/is-tty
--- a/commands/is-tty
+++ b/commands/is-tty
@@ -3,18 +3,55 @@
 function is_tty() (
 	source "$DOROTHY/sources/bash.bash"
 
-	if test "$*" = '--debug'; then
-		eval-helper --wrap --no-quiet -- test -t 0 || :
-		eval-helper --wrap --no-quiet -- test -t 1 || :
-		eval-helper --wrap --no-quiet -- test -t 2 || :
-		eval-helper --wrap --no-quiet -- test -c '/dev/tty' || :
-		eval-helper --wrap --no-quiet -- echo "${NO_TTY-}" || :
-		eval-helper --wrap --no-quiet -- echo "${TTY-}" || :
-		eval-helper --wrap --no-quiet -- ps -p "$$" -o tty= || :
-		set +e -x
-		exec </dev/tty
-		echo $?
-		set -e +x
+	# =====================================
+	# Arguments
+
+	function help {
+		cat <<-EOF >/dev/stderr
+			ABOUT:
+			Checks if the environment actually has a TTY available.
+
+			USAGE:
+			is-tty [...options]
+
+			OPTIONS:
+			--verbose
+			    If provided, output more information.
+		EOF
+		if test "$#" -ne 0; then
+			echo-error "$@"
+		fi
+		return 22 # EINVAL 22 Invalid argument
+	}
+
+	# process
+	local item option_quiet=''
+	option_quiet="$(echo-quiet "$option_quiet" -- "$@")"
+	while test "$#" -ne 0; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--no-quiet'* | '--quiet'* | '--no-verbose'* | '--verbose'*) ;; # handled by echo-quiet
+		'--'*) help "An unrecognised flag was provided: $item" ;;
+		*) help "An unrecognised argument was provided: $item" ;;
+		esac
+	done
+
+	# =====================================
+	# Action
+
+	if test "$option_quiet" = 'no'; then
+		set -x
+		(test -t 0 && echo "success status = $?") || echo "failure status = $?"
+		(test -t 1 && echo "success status = $?") || echo "failure status = $?"
+		(test -t 2 && echo "success status = $?") || echo "failure status = $?"
+		(test -c '/dev/tty' && echo "success status = $?") || echo "failure status = $?"
+		echo "NO_TTY = ${NO_TTY-}"
+		echo "TTY = ${TTY-}"
+		(ps -p "$$" -o tty= && echo "success status = $?") || echo "failure status = $?"
+		(exec </dev/tty && echo "success status = $?") || echo "failure status = $?"
+		set +x
 
 		# RUNNING ON MACOS
 		# > is-tty --debug
