is-admin, is-user-in-group: fix for when `groups` is not available, such as running inside a platpack container (such as a vscode terminal)
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/is-user-in-group b/commands/is-user-in-group
--- a/commands/is-user-in-group
+++ b/commands/is-user-in-group
@@ -1,5 +1,16 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
+# confirm the groups is available
+# vscode flatpack doesn't have it, so vscode flatpack terminal will fail
+# roups: command not found
+if "$DOROTHY/commands/command-missing" groups; then
+	exit 2
+fi
+
+# prepare
+group="$1"
+user="${2-}"
+
 # -v inverts
-groups | grep -vq "$1"
+groups "$user" | grep -vq "$group"
