macos-drive: download installer if not present

diff --git a/commands/macos-drive b/commands/macos-drive
--- a/commands/macos-drive
+++ b/commands/macos-drive
@@ -2,13 +2,26 @@
 source "$DOROTHY/sources/strict.bash"
 source "$DOROTHY/sources/splitlines.bash"
 
-versions="$(expand-path '/Applications/Install macOS*')"
+# helper
+function find_installer {
+	versions="$(expand-path '/Applications/Install macOS*')"
+}
 
-if is-empty-string "$versions"; then
-	stderr echo 'download a macOS installer from the mac app store first'
-	exit 1
+# find it
+find_installer
+if test -z "$versions"; then
+	echo 'An existing macOS installer was not present on your system.'
+	echo 'Fetching the latest installer from Apple...'
+	softwareupdate --fetch-full-installer  # --download flag doesn't work, despite documentation
+	find_installer
+	if test -z "$versions"; then
+		stderr echo 'Even after fetching the installer, we could not find it. This is unexpected.'
+		stderr echo 'Report an issue at: https://github.com/bevry/dorothy/issues'
+		exit 1
+	fi
 fi
 
+# select it
 select version in $versions; do
 	volume="$(choose-path /Volumes)"
 	if confirm-bool "Install $(basename "$version") to $volume?"; then
