mail-sync: bugfixes around deletion and memory errors

diff --git a/commands/mail-sync b/commands/mail-sync
--- a/commands/mail-sync
+++ b/commands/mail-sync
@@ -94,19 +94,25 @@ args+=(
 )
 
 # delete?
-if confirm-positive --ppid=$$ -- "Delete messages from the origin IMAP server?"; then
-	args+=(--delete1 --expunge1 --noexpungeaftereach)
+if confirm-negative --ppid=$$ -- "Delete messages from the origin IMAP server?" "Do this only once you have already completed a successful synchronisation, otherwise only the first label/folder will be applied."; then
+	args+=(--delete1 --delete1emptyfolders --expunge1) # --noexpungeaftereach
 fi
 
 # act and continue until success
+# --usecache
+# --useuid
 while true; do
-	{
-		imapsync \
-			--automap \
-			--skipcrossduplicates \
-			--addheader --useheader "Message-Id" \
-			--syncinternaldates \
-			--nofoldersizes --nofoldersizesatend --no-modulesversion --nolog \
-			"${args[@]}" && break
-	} || :
+	ec=0 && imapsync \
+		--automap \
+		--skipcrossduplicates \
+		--addheader --useheader 'Message-Id' \
+		--syncinternaldates \
+		--nofoldersizes --nofoldersizesatend --no-modulesversion --nolog \
+		"${args[@]}" || ec="$?"
+	if test "$ec" -eq 0; then
+		echo-style --success='Success!'
+		break
+	else
+		echo-style --notice="Failure with exit code [$ec] restarting..."
+	fi
 done
