mount-helper: ensure utf8 samba support to prevent question marks in mounts

diff --git a/commands/mount-helper b/commands/mount-helper
--- a/commands/mount-helper
+++ b/commands/mount-helper
@@ -296,6 +296,9 @@
 # guest
 # don't prompt for a password.
 
+# iocharset
+# Charset used to convert local path names to and from Unicode. Unicode is used by default for network path names if the server supports it. If iocharset is not specified then the nls_default specified during the local client kernel build will be used. If server does not support Unicode, this parameter is unused.
+
 # setuids
 # If the CIFS Unix extensions are negotiated with the server the client will attempt to set the effective uid and gid of the local process on newly created files, directories, and devices (create, mkdir, mknod). If the CIFS Unix Extensions are not negotiated, for newly created files and directories instead of using the default uid and gid specified on the the mount, cache the new file's uid and gid locally which means that the uid for the file can change when the inode is reloaded (or the user remounts the share).
 
@@ -832,13 +835,16 @@ function mount-helper() (
 				uses_fstab='yes'
 				uses_mkdir='yes'
 
+				# we use [iocharset=utf8] during mounting to ensure utf8 is used rather than some peculiar default determined at kernel build time via the compiler's [NLS_DEFAULT]
+				# having the server specify [unix charset = UTF-8] in [/etc/samba/smb.conf]  had no effect, and would not cause the client to fail if the client did not support UTF8
 				fstab_options+=(
-					noexec    # ubuntu mount, macos mount
-					noatime   # ubuntu mount, macos mount
-					nodev     # ubuntu mount, macos mount
-					nosetuids # ubuntu mount (only samba), (not supported by gofscryptfs)
-					rw        # ubuntu mount, macos mount has [rdonly], gocryptfs mount
-					user      # ubuntu mount, (not supported by gofscryptfs)
+					iocharset=utf8 # ubuntu mount (only samba)
+					noexec         # ubuntu mount, macos mount
+					noatime        # ubuntu mount, macos mount
+					nodev          # ubuntu mount, macos mount
+					nosetuids      # ubuntu mount (only samba), (not supported by gofscryptfs)
+					rw             # ubuntu mount, macos mount has [rdonly], gocryptfs mount
+					user           # ubuntu mount, (not supported by gofscryptfs)
 					# X-mount.mkdir # ubuntu mount (doesn't work)
 				)
 				if test -n "$option_username"; then
@@ -1610,7 +1616,10 @@ function mount-helper() (
 				return "$unmount_ec"
 			fi
 
-			# validate here, as validating earlier can fail if the gocryptfs vault is inside a nested mount that is not moutned yet, and we just want to make sure that it is unmounted
+			# segment
+			echo-segment --h2='mount'
+
+			# validate gocryptfs here instead of during parsing, as if it is during parsing, it will crash if checking if an unmounted gocryptfs source is unmounted (e.g. /mnt/an-unmounted-hard-drive/a-gocryptfs-source)
 			if test -n "$gocryptfs_source"; then
 				if ! gocryptfs-helper verify -- "$gocryptfs_source" --user="$option_user" --group="$option_group"; then
 					echo-error "Failed to verify gocryptfs mount source: $gocryptfs_source"
@@ -1618,8 +1627,16 @@ function mount-helper() (
 				fi
 			fi
 
-			# segment
-			echo-segment --h2='mount'
+			# validate samba here instead of during parsing, for the same reason as gocryptfs
+			if test "$mount_type" = 'cifs' && is-apt; then
+				# [cifs-utils] is necessary for [mount.cifs] which offers advanced samba mounting support, such as [iocharset] option
+				setup-util --quiet --cli='mount.cifs' APT='cifs-utils'
+				# ensure UTF-8 encoding support
+				if ! test -e "/lib/modules/$(uname -r)/kernel/fs/nls/nls_utf8.ko"; then
+					# https://askubuntu.com/a/1098865/22776 — install the minimal necessary for encoding
+					setup-util --quiet --name='UTF-8 Encoding' APT="linux-modules-extra-$(uname -r)"
+				fi
+			fi
 
 			# verify fstab
 			if test "$uses_fstab" = 'yes'; then
