more documentation
- renamed `truthy` to `echo-first-nonempty`, and now supports stdin in addition to arguments

- renamed `triim` to `echo-trim-lines`

- add docs to `down-zip`, `fetch`, `fs-absolute`, `fs-own`, `fs-realpath`, `geocode`, `get-app`, `gid`, `open-app`, `padd`, `pipp`, `rand`, `together`, `uid`, `unziptar`

- `fs-absolute` no longer resolves symlinks for the directory, that is what `fs-realpath` is for

- `geocode` has been updated for the latest api, and now prompts for the token

- `brew`,  now explains why it failed on non-brew systems or when brew is not installed

- `pipp` now outputs the right error if no python install exists on a non-brew system

- `files-to-list` is now simplified

/ref #7

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/padd b/commands/padd
--- a/commands/padd
+++ b/commands/padd
@@ -1,8 +1,24 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-if test -f "yarn.lock"; then
+# help
+if is-help "$@"; then
+	stderr echo-lines \
+		'ABOUT:' \
+		'Forward to the correct package manager for your project.' \
+		'If [yarn.lock] is present, uses [yarn].' \
+		'If [package.json] is present, uses [package.json].' \
+		'' \
+		'USAGE:' \
+		'padd ...'
+	exit 22 # Invalid argument
+fi
+
+# act
+if test -f 'yarn.lock'; then
 	yarn add "$@"
-else
+elif test -f 'package.json'; then
 	npm install "$@"
+else
+	stderr echo 'could not determine the correct package manager this project'
 fi
