secret: better async and error handling

diff --git a/commands/secret b/commands/secret
--- a/commands/secret
+++ b/commands/secret
@@ -149,9 +149,6 @@ function secret_signin() {
 					secret_write "OP_SUBDOMAIN" "$OP_SUBDOMAIN"
 				fi
 			fi
-			if test "$quiet" = 'no'; then
-				stderr echo "Logging into [$OP_SUBDOMAIN], if that is incorrect use [secret clear]."
-			fi
 			# email
 			email="$(env PASS="$quiet" ask-mandatory 'What is your 1password email? This is not stored.')"
 			# secret
@@ -171,35 +168,35 @@ function secret_signin() {
 	stderr echo 'Signed in.'
 }
 
+function opwrap () {
+	result="$(op "$@" 2>&1 || :)"
+	if test "$?" -ne 0 || [[ "$result" = '[ERROR]'* ]]; then
+		if [[ "$result" = *'signed in'* ]] || [[ "$result" = *'session expired'* ]]; then
+			stderr echo "ERROR: Session expired, run [secret signin] and try again."
+			return 1
+		fi
+		stderr echo "$result"
+		return 1
+	else
+		echo -n "$result"
+	fi
+}
+
 function secret_grab() {
 	secret_signin
 	vault="${1-}"
 	item="${2-}"
 	if is-empty-value "$vault"; then
 		# fetch available values
-		result="$(op list vaults --session="$OP_SESSION" 2>&1 || :)"
+		opwrap list vaults --session="$OP_SESSION"
 	elif is-empty-value "$item"; then
 		# fetch available items
-		result="$(op list items --vault="$vault" --session="$OP_SESSION" 2>&1 || :)"
+		opwrap list items --vault="$vault" --session="$OP_SESSION"
 	else
 		# fetch item
-		result="$(op get item "$item" --vault="$vault" --session="$OP_SESSION" 2>&1 || :)"
+		opwrap get item "$item" --vault="$vault" --session="$OP_SESSION"
 	fi
-	# process result
-	if is-empty-value "$result"; then
-		stderr echo "ERROR: Nothing was returned: vault=[$vault], item=[$item], result=[$result]"
-		return 1
-	elif [[ "$result" = *'signed in'* ]]; then
-		stderr echo "ERROR: Unable to return: vault=[$vault], item=[$item]"
-		stderr echo "Session expired, run [secret signin] and try again."
-		return 1
-	elif [[ "$result" = *'ERROR'* ]]; then
-		stderr echo "ERROR: Failed to return: vault=[$vault], item=[$item]"
-		stderr echo "$result"
-		return 1
-	else
-		echo -n "$result"
-	fi
+	return "$?"
 }
 
 function secret_fetch() {
@@ -258,38 +255,59 @@ function secret_fetch() {
 	fi
 }
 
+function get_job_count () {
+	jobs -p | get-line-count
+}
+
 function item_upgrade () {
 	vault="$1"
 	item="$2"
 	# fetch
-	website="$(op get item --session="$OP_SESSION" --vault "$vault" "$item" - --fields website)"
+	website="$(opwrap get item --session="$OP_SESSION" --vault "$vault" "$item" - --fields website)"
+	if test "$?" -ne 0; then
+		echo "[$item] [$website] failed to fetch"
+		return 1
+	fi
 	if test -z "$website"; then
-		echo "[$item] [$website] empty"
+		stderr echo "[$item] [$website] empty"
 		return 1
 	fi
 	# upgrade
 	result="$(silent-stderr get-url-upgrade "$website" || :)"
 	if test -z "$result"; then
+		# echo to stdout, as is actionable for user if they are piping
 		echo "[$item] [$website] unresponsive, consider archiving"
 		return 1
 	fi
 	# check if changed
 	if test "$result" = "$website"; then
-		echo "[$item] [$website] already upgraded"
+		stderr echo "[$item] [$website] already upgraded"
 		return 1
 	fi
-	# apply
+	# echo to stdout, as is actionable for user if they are piping
 	echo "[$item] [$website] => [$result]"
-	op edit item --session="$OP_SESSION" --vault "$vault" "$item" website="$result"
-	return
+	# apply
+	opwrap edit item --session="$OP_SESSION" --vault "$vault" "$item" website="$result"
+	if test "$?" -ne 0; then
+		stderr echo "[$item] [$website] failed to save"
+		return 1
+	fi
 }
 
 function secret_https() {
 	last="${1-}"
 	secret_signin
-	vaults="$(op list vaults --session="$OP_SESSION" | jq -r '.[].uuid' | sort)"
+	vaults="$(opwrap list vaults --session="$OP_SESSION" | jq -r '.[].uuid' | sort || :)"
+	if test "$?" -ne 0 -o -z "$vaults"; then
+		stderr echo "failed to fetch vaults..."
+		return 1
+	fi
 	for vault in $vaults; do
-		items="$(op list items --session="$OP_SESSION" --categories Login --vault "$vault" | jq -r '.[].uuid' | sort || :)"
+		items="$(opwrap list items --session="$OP_SESSION" --categories Login --vault "$vault" | jq -r '.[].uuid' | sort || :)"
+		if test "$?" -ne 0 -o -z "$vaults"; then
+			stderr echo "failed to fetch items from vault [$vault]"
+			return 1
+		fi
 		# ignoring of status code is in case it returned a vault we don't have write access to
 		for item in $items; do
 			# resume
@@ -303,11 +321,17 @@ function secret_https() {
 					continue
 				fi
 			fi
-			while test "$(jobs -p | get-line-count)" -eq 15; do
+			while test "$(get_job_count)" -eq 15; do
 				sleep 1
 			done
 			(item_upgrade "$vault" "$item" || :) &
 		done
+	done
+	# wait for completed jobs, then note completion
+	while test "$(get_job_count)" -ne 0; do
+		echo "Waiting on [$(get_job_count)] jobs..."
+		sleep 5
+		jobs &> /dev/null # for some reason, this seems necessary to prevent hung jobs
 	done
 	echo 'All done.'
 }
