secret: greatly improved fetching and errors
- workflow has been rewritten

- fetching selection now works for vaults, items, and fields

Added `choose-tuple` as the brains of this.

diff --git a/commands/secret b/commands/secret
--- a/commands/secret
+++ b/commands/secret
@@ -26,54 +26,41 @@ export OP_SESSION
 export OP_SUBDOMAIN
 export database="$SECRETS/secrets.json"
 
-function secret_resolve() {
-	# Write the database if it does not exist
-	if ! sudo test -f "$database"; then
-		echo '{}' | sudo tee "$database"  &>/dev/null
-	fi
+# Write the database if it does not exist
+if ! sudo test -f "$database"; then
+	echo '{}' | sudo tee "$database"  &>/dev/null
+fi
 
-	# many
-	if test "${#@}" -gt '1'; then
-		for var in "$@"; do
-			value="$(secret_resolve "$var")"
-			echo "$var=$value"
-		done
-		exit
-	fi
-
-	# singular
-	key="$1"
-	result="$(secret_read "$key" || :)"
-	if is-string "$result"; then
-		echo -n "$result"
-	elif is-empty-string "$result"; then
-		vault="$(sudo jq -r ".${key}[0]" "$database")"
-		item="$(sudo jq -r ".${key}[1]" "$database")"
-		field="$(sudo jq -r ".${key}[2]" "$database")"
-		if is-value "$vault" && is-value "$item" && is-value "$field"; then
-			value="$(secret_fetch "$vault" "$item" "$field")"
-		else
-			stderr echo "ERROR: [$database] needs [$key] to have all three parts of its mapping: [$vault, $item, $field]"
-			stderr echo "Use the [secret map ...] command to set the mapping accordingly."
-			return 1
-		fi
-		if is-empty-value "$value"; then
-			stderr echo "ERROR: resolve returned nothing for: $key"
-			return 1
-		fi
-		secret_write "$key" "$value"
-		echo -n "$value"
-	else
-		echo "ERROR: could not fetch the secret: $key"
-		return 1
-	fi
+function cache_clear() {
+	t="$(mktemp)"
+	mv "$database" "$t"
+	sudo rm -Rf "$SECRETS/"*
+	mv "$t" "$database"
 }
 
-function secret_write() {
+function cache_exists() {
+	for key in "$@"; do
+		sudo test -f "$SECRETS/$key"
+		if test "$?" -ne 0; then
+			return 1
+		fi
+	done
+}
+
+function cache_delete() {
+	for key in "$@"; do
+		sudo rm -f "$SECRETS/$key"
+		if test "$?" -ne 0; then
+			return 1
+		fi
+	done
+}
+
+function cache_write() {
 	key="$1"
 	value="$2"
-	secret_delete "$key"
-	if is-string "$value"; then
+	cache_delete "$key"
+	if is-value "$value"; then
 		echo -n "$value" >"$SECRETS/$key"
 		sudo chown root: "$SECRETS/$key"
 		sudo chmod 600 "$SECRETS/$key"
@@ -83,54 +70,81 @@ function secret_write() {
 	fi
 }
 
-function secret_clear() {
-	t="$(mktemp)"
-	mv "$database" "$t"
-	sudo rm -Rf "$SECRETS/"*
-	mv "$t" "$database"
-}
-
-function secret_exists() {
-	for key in "$@"; do
-		sudo test -f "$SECRETS/$key"
-	done
-}
-
-function secret_delete() {
-	for key in "$@"; do
-		sudo rm -f "$SECRETS/$key"
-	done
-}
-
-function secret_read() {
+function cache_read() {
 	key="$1"
-	if secret_exists "$key"; then
+	if cache_exists "$key"; then
 		value="$(sudo cat "$SECRETS/$key" | tr -d '\n')"
-		if is-string "$value"; then
+		if is-value "$value"; then
 			echo -n "$value"
 		else
-			stderr echo "ERROR: cached secret was empty: $key"
-			secret_delete "$key"
+			stderr echo "ERROR: cached secret [$key] was empty [$value]"
+			cache_delete "$key"
 			return 1
 		fi
 	else
-		stderr echo "ERROR: cached secret was missing: $key"
+		stderr echo "ERROR: cached secret [$key] was missing"
 		return 1
 	fi
 }
 
+function fetch_secret() {
+	# many
+	if test "${#@}" -gt '1'; then
+		for var in "$@"; do
+			value="$(fetch_secret "$var")"
+			if test "$?" -ne 0; then
+				stderr echo "ERROR: Unable to fetch the secret [$var] of many"
+				return 1
+			fi
+			echo "$var=$value"
+		done
+		return
+	fi
+
+	# singular
+	key="$1"
+	result="$( (cache_exists "$key" && cache_read "$key") || :)"
+	if test "$?" -ne 0; then
+		stderr echo "ERROR: Unable to fetch the secret [$var]"
+		return 1
+	fi
+
+	# fetch
+	if test -n "$result"; then
+		echo -n "$result"
+	else
+		vault="$(sudo jq -r ".${key}[0]" "$database")"
+		item="$(sudo jq -r ".${key}[1]" "$database")"
+		field="$(sudo jq -r ".${key}[2]" "$database")"
+		if is-value "$vault" && is-value "$item" && is-value "$field"; then
+			value="$(fetch_field "$vault" "$item" "$field")"
+		else
+			stderr echo "ERROR: [$database] needs [$key] to have all three parts of its mapping: [$vault, $item, $field]"
+			stderr echo "Use the [secret map ...] command to set the mapping accordingly."
+			return 1
+		fi
+		if is-empty-value "$value"; then
+			stderr echo "ERROR: resolve returned nothing for: $key"
+			return 1
+		fi
+		cache_write "$key" "$value"
+		echo -n "$value"
+	fi
+}
+
+
 function secret_signout() {
 	echo 'Signing out...'
-	if is-empty-string "${OP_SESSION-}"; then
-		if secret_exists "OP_SESSION"; then
-			OP_SESSION="$(secret_read OP_SESSION)"
+	if test -z "${OP_SESSION-}"; then
+		if cache_exists "OP_SESSION"; then
+			OP_SESSION="$(cache_read OP_SESSION)"
 			op signout --session="$OP_SESSION" 2>&1 || :
 		fi
 	else
 		op signout --session="$OP_SESSION" 2>&1 || :
 	fi
-	secret_delete "OP_SESSION"
-	secret_delete "OP_SUBDOMAIN"
+	cache_delete "OP_SESSION"
+	cache_delete "OP_SUBDOMAIN"
 	OP_SESSION=''
 	echo 'Signed out.'
 }
@@ -138,15 +152,15 @@ function secret_signout() {
 function secret_signin() {
 	# session
 	echo 'Signing in...'
-	if is-empty-string "${OP_SESSION-}"; then
-		OP_SESSION="$(secret_read OP_SESSION || :)"
-		if is-empty-string "$OP_SESSION"; then
+	if test -z "${OP_SESSION-}"; then
+		OP_SESSION="$( (cache_exists OP_SESSION && cache_read OP_SESSION) || :)"
+		if test -z "$OP_SESSION"; then
 			# subdomain
-			if is-empty-string "${OP_SUBDOMAIN-}"; then
-				OP_SUBDOMAIN="$(secret_read OP_SUBDOMAIN || :)"
-				if is-empty-string "${OP_SUBDOMAIN-}"; then
+			if test -z "${OP_SUBDOMAIN-}"; then
+				OP_SUBDOMAIN="$( (cache_exists OP_SUBDOMAIN && cache_read OP_SUBDOMAIN) || :)"
+				if test -z "${OP_SUBDOMAIN-}"; then
 					OP_SUBDOMAIN="$(env PASS="$quiet" ask-mandatory 'What is your 1password subdomain?')"
-					secret_write "OP_SUBDOMAIN" "$OP_SUBDOMAIN"
+					cache_write "OP_SUBDOMAIN" "$OP_SUBDOMAIN"
 				fi
 			fi
 			# email
@@ -162,10 +176,10 @@ function secret_signin() {
 				stderr echo "$OP_SESSION"
 				return 1
 			fi
-			secret_write "OP_SESSION" "$OP_SESSION"
+			cache_write "OP_SESSION" "$OP_SESSION"
 		fi
 	fi
-	stderr echo 'Signed in.'
+	echo 'Signed in.'
 }
 
 function opwrap () {
@@ -175,17 +189,17 @@ function opwrap () {
 			stderr echo "ERROR: Session expired, run [secret signin] and try again."
 			return 1
 		fi
-		stderr echo "$result"
+		stderr echo "FAILURE: $result"
 		return 1
 	else
 		echo -n "$result"
 	fi
 }
 
-function secret_grab() {
-	secret_signin
+function opgrab() {
 	vault="${1-}"
 	item="${2-}"
+
 	if is-empty-value "$vault"; then
 		# fetch available values
 		opwrap list vaults --session="$OP_SESSION"
@@ -196,63 +210,68 @@ function secret_grab() {
 		# fetch item
 		opwrap get item "$item" --vault="$vault" --session="$OP_SESSION"
 	fi
+
 	return "$?"
 }
 
-function secret_fetch() {
+function fetch_vault () {
 	vault="${1-}"
-	if is-empty-value "$vault"; then
-		# fetch available vaults
-		data="$(secret_grab)"
-		if test "$?" -ne 0 || is-empty-value "$data"; then
-			return 1
-		fi
-		# output options
-		echo "$data" | jq -r '.[].name' # | (.uuid, .name)'
-		return
-	fi
-	item="${2-}"
-	if is-empty-value "$item"; then
-		stderr echo "ERROR: Vault was provided [$vault] but item was missing [$item]"
-		return 1
-		# # fetch available items
-		# data="$(secret_grab "$vault")"
-		# if test "$?" -ne 0 || is-empty-value "$data"; then
-		# 	return 1
-		# fi
-		# # output options
-		# echo "$data" | jq -r '.[] | (.uuid, .overview.title)'
-		# return
-	fi
-	field="${3-}"
-	data="$(secret_grab "$vault" "$item")"
-	if test "$?" -ne 0; then
+
+	# fetch available vaults
+	mapfile -t tuples <<<"$(opgrab | jq -r '.[] | (.name, .uuid)')"
+	if test "$?" -ne 0 -o "${#tuples[@]}" -le 1; then
 		return 1
 	fi
 
-	# fetch field value
-	if is-value "$field"; then
-		# fetch based on section
-		result="$(echo "$data" | jq -r --arg key "$field" ".details.sections[] | select(.fields).fields[] | select(.t==\$key).v")"
-		if is-empty-value "$result"; then
-			# fetch based on standalone
-			result="$(echo "$data" | jq -r --arg key "$field" ".details.fields[] | select(.name==\$key).value")"
-			# fetch based on designation
-			if is-empty-value "$result"; then
-				result="$(echo "$data" | jq -r --arg key "$field" ".details.fields[] | select(.designation==\$key).value")"
-			fi
-		fi
-		# output
-		echo -n "$result"
-	else
-		# fetch available field values
-		# fetch based on section
-		echo "$data" | jq -r ".details.sections[] | select(.fields).fields[] | .t"
-		# fetch based on standalone
-		echo "$data" | jq -r ".details.fields[] | .name"
-		# fetch based on designation
-		echo "$data" | jq -r ".details.fields[] | .designation"
+	# filter or ask
+	choose-tuple 'Which vault do you want?' "$vault" -- "${tuples[@]}"
+	return "$?"
+}
+
+function fetch_item () {
+	vault="${1-}"
+	item="${2-}"
+
+	# fetch available items
+	mapfile -t tuples <<<"$(opgrab "$vault" | jq -r '.[] | (.overview.title, .uuid)')"
+	if test "$?" -ne 0 -o "${#tuples[@]}" -le 1; then
+		return 1
 	fi
+
+	# filter or ask
+	choose-tuple 'Which item do you want?' "$item" -- "${tuples[@]}"
+	return "$?"
+}
+
+function fetch_field () {
+	vault="${1-}"
+	item="${2-}"
+	field="${3-}"
+	if test "${4-}" = '--label'; then
+		option='label'
+	else
+		option='value'
+	fi
+
+	# fetch available items
+	data="$(opgrab "$vault" "$item")"
+	fields=()
+	mapfile -t fields_via_section <<<"$(echo "$data" | jq -r '.details.sections[]? | select(.fields).fields[]? | select(.t != "" and .v != "") | (.t, .v)')"
+	if test "$?" -eq 0 -a "${#fields_via_section[@]}" -ge 2; then
+		fields+=("${fields_via_section[@]}")
+	fi
+	mapfile -t fields_via_name <<<"$(echo "$data" | jq -r '.details.fields[]? | select(.name != "" and .value != "") | (.name, .value)')"
+	if test "$?" -eq 0 -a "${#fields_via_name[@]}" -ge 2; then
+		fields+=("${fields_via_name[@]}")
+	fi
+	mapfile -t fields_via_designation <<<"$(echo "$data" | jq -r '.details.fields[]? | select(.designation != "" and .value != "") | (.designation, .value)')"
+	if test "$?" -eq 0 -a "${#fields_via_designation[@]}" -ge 2; then
+		fields+=("${fields_via_designation[@]}")
+	fi
+
+	# filter or ask
+	env VALUE_IN_LABEL=never RETURN="$option" choose-tuple 'Which field do you want?' "$field" -- "${fields[@]}"
+	return "$?"
 }
 
 function get_job_count () {
@@ -296,7 +315,6 @@ function item_upgrade () {
 
 function secret_https() {
 	last="${1-}"
-	secret_signin
 	vaults="$(opwrap list vaults --session="$OP_SESSION" | jq -r '.[].uuid' | sort || :)"
 	if test "$?" -ne 0 -o -z "$vaults"; then
 		stderr echo "failed to fetch vaults..."
@@ -338,9 +356,9 @@ function secret_https() {
 
 function secret_map() {
 	secret="$(ask-mandatory 'What shall the name of the environment variable (secret) be?' "${1-}")"
-	vault="$(ask-options 'What vault should it map to?' "${2-}" "$(secret_fetch)")"
-	item="$(ask-mandatory 'What item should it map to?' "${3-}")"
-	field="$(ask-options 'What field should it map to?' "${4-}" "$(secret_fetch "$vault" "$item")")"
+	vault="$(fetch_vault "${2-}")"
+	item="$(fetch_item "$vault" "${3-}")"
+	field="$(fetch_field "$vault" "$item" "${4-}" --label)"
 	result="$(sudo jq -r \
 		--arg secret "$secret" \
 		--arg vault "$vault" \
@@ -348,13 +366,13 @@ function secret_map() {
 		--arg field "$field" \
 		'.[$secret] = [$vault, $item, $field]' \
 		"$database")"
-	echo "$result" | sudo tee "$database"
+	echo "$result" | sudo tee "$database" &>/dev/null
 	sudo chown root "$database"
 	sudo chmod 600 "$database"
-	stderr echo "Sucessfully wrote [$secret] to fetch from [$vault].[$item].[$field]"
-	stderr echo "Attempting fetch of [$secret] now..."
-	secret_delete "$secret"
-	secret_resolve "$secret"
+	stderr echo "Sucessfully updated [$database] so that [$secret] fetches [$vault].[$item].[$field]"
+	stderr echo "Fetching [$secret]..."
+	cache_delete "$secret"
+	fetch_secret "$secret"
 }
 
 function secret_unmap() {
@@ -367,7 +385,7 @@ function secret_unmap() {
 	echo "$result" | sudo tee "$database"
 	sudo chown root "$database"
 	sudo chmod 600 "$database"
-	secret_delete "$secret"
+	cache_delete "$secret"
 	stderr echo "Sucessfully unmapped [$secret]"
 }
 
@@ -401,7 +419,7 @@ function secret_env() {
 	# load secrets
 	envSecrets=()
 	for var in "${vars[@]}"; do
-		value="$(secret_resolve "$var")"
+		value="$(fetch_secret "$var")"
 		envSecrets+=("$var=$value")
 	done
 
@@ -410,7 +428,7 @@ function secret_env() {
 	for arg in "${args[@]}"; do
 		envArg="$arg"
 		for var in "${vars[@]}"; do
-			value="$(secret_resolve "$var")"
+			value="$(fetch_secret "$var")"
 			envArg="${envArg//\$$var/$value}"
 		done
 		envArgs+=("$envArg")
@@ -425,12 +443,13 @@ function secret_env() {
 
 if test -n "${1-}"; then
 	if test "$1" = "env"; then
+		secret_signin >&2 # redirect function to stderr
 		secret_env "${@:2}"
 	elif test "$1" = "clear" -o "$1" = "delete"; then
 		if is-string "${2-}"; then
-			secret_delete "${@:2}"
+			cache_delete "${@:2}"
 		else
-			secret_clear
+			cache_clear
 		fi
 	elif test "$1" = "edit"; then
 		edit "$database"
@@ -440,16 +459,18 @@ if test -n "${1-}"; then
 	elif test "$1" = "signout" -o "$1" = "logout"; then
 		secret_signout
 	elif test "$1" = "refresh"; then
+		secret_signin >&2 # redirect function to stderr
 		if is-string "$2"; then
-			secret_delete "${@:2}"
-			secret_resolve "${@:2}"
+			cache_delete "${@:2}"
+			fetch_secret "${@:2}"
 		else
 			stderr echo 'ERROR: <name> was not found. Refer to usage.'
 			exit 1
 		fi
-	elif test "$1" = "get"; then
+	elif test "$1" = "get" -o "$1" = "fetch"; then
+		secret_signin >&2 # redirect function to stderr
 		if is-string "$2"; then
-			secret_resolve "${@:2}"
+			fetch_secret "${@:2}"
 		else
 			stderr echo 'ERROR: <name> was not found. Refer to usage.'
 			exit 1
@@ -461,12 +482,12 @@ if test -n "${1-}"; then
 		# 	brew install --cask 1password-cli --force
 		# fi
 	elif test "$1" = "map"; then
+		secret_signin >&2 # redirect function to stderr
 		secret_map "${@:2}"
 	elif test "$1" = "unmap"; then
 		secret_unmap "${@:2}"
-	elif test "$1" = "fetch"; then
-		secret_fetch "${@:2}"
 	elif test "$1" = "https"; then
+		secret_signin >&2 # redirect function to stderr
 		secret_https "${@:2}"
 	else
 		stderr echo 'invalid command'
