secret: don't crash if missing from cache
also:

- if filtering, mention the filter, in case exact match is possible
- ensure invalidate action is possible
- convention updates

diff --git a/commands/secret b/commands/secret
--- a/commands/secret
+++ b/commands/secret
@@ -30,7 +30,19 @@ OP_SESSION=''
 OP_SUBDOMAIN=''
 
 # options
-actions=('install' 'login' 'logout' 'map' 'get' 'env' 'unmap' 'fetch' 'https' 'help')
+actions=(
+	'install'
+	'login'
+	'logout'
+	'map'
+	'env'
+	'get'
+	'invalidate'
+	'unmap'
+	'fetch'
+	'https'
+	'help'
+)
 action="$(
 	choose-option \
 		--question='What action do you wish to take?' \
@@ -38,17 +50,14 @@ action="$(
 )"
 
 # quiet mode: whether or not we output account details
+quiet="$(is-quiet --missing='no' -- "$@")"
 askpassarg=''
-if is-affirmative "${QUIET-}"; then
+if test "$quiet" = 'yes'; then
 	askpassarg='--password'
 fi
 
 function cache_clear() {
-	local t
-	t="$(mktemp)"
-	mv "$database" "$t"
 	sudo rm -Rf "$state/"*
-	mv "$t" "$database"
 }
 
 function cache_exists() {
@@ -104,52 +113,51 @@ function cache_read() {
 }
 
 function secret_get() {
-	local var ec key result vault item field value
+	local ec key result vault item field value
 
 	# many
-	if test "${#@}" -gt '1'; then
-		for var in "$@"; do
-			ec=0 && value="$(secret_get "$var")" || ec="$?"
+	if test "$#" -gt '1'; then
+		for key in "$@"; do
+			ec=0 && value="$(secret_get "$key")" || ec="$?"
 			if test "$ec" -ne 0; then
-				stderr echo "ERROR: Unable to fetch the secret [$var] of many"
+				stderr echo "ERROR: Unable to fetch the secret [$key] of many"
 				return 1
 			fi
-			echo "$var=$value"
+			echo "$key=$value"
 		done
 		return
 	fi
 
 	# singular
 	key="$1"
-	ec=0 && result="$(cache_exists "$key" && cache_read "$key")" || ec="$?"
-	if test "$ec" -ne 0; then
-		stderr echo "ERROR: Unable to fetch the secret [$var]"
+
+	# fetch from cache
+	if cache_exists "$key"; then
+		cache_read "$key"
+		return "$?"
+	fi
+
+	# fetch from api
+	vault="$(sudo jq -r ".${key}[0]" "$database")"
+	item="$(sudo jq -r ".${key}[1]" "$database")"
+	field="$(sudo jq -r ".${key}[2]" "$database")"
+	if is-value "$vault" && is-value "$item" && is-value "$field"; then
+		value="$(fetch_field "$vault" "$item" "$field")"
+	else
+		stderr echo "ERROR: [$database] needs [$key] to have all three parts of its mapping: [$vault, $item, $field]"
+		stderr echo "Use the [secret map ...] command to set the mapping accordingly."
 		return 1
 	fi
-
-	# fetch
-	if test -n "$result"; then
-		echo -n "$result"
-	else
-		vault="$(sudo jq -r ".${key}[0]" "$database")"
-		item="$(sudo jq -r ".${key}[1]" "$database")"
-		field="$(sudo jq -r ".${key}[2]" "$database")"
-		if is-value "$vault" && is-value "$item" && is-value "$field"; then
-			value="$(fetch_field "$vault" "$item" "$field")"
-		else
-			stderr echo "ERROR: [$database] needs [$key] to have all three parts of its mapping: [$vault, $item, $field]"
-			stderr echo "Use the [secret map ...] command to set the mapping accordingly."
-			return 1
-		fi
-		if is-empty-value "$value"; then
-			stderr echo "ERROR: resolve returned nothing for: $key"
-			return 1
-		fi
-		cache_write "$key" "$value"
-		echo -n "$value"
+	if is-empty-value "$value"; then
+		stderr echo "ERROR: resolve returned nothing for: $key"
+		return 1
 	fi
+	cache_write "$key" "$value"
+	echo -n "$value"
 }
 
+# secret_signout [--quiet]
+# [--quiet] used when its operation is secondary to another
 function secret_signout() {
 	if test "${1-}" != '--quiet'; then
 		echo 'Unauthenticating...'
@@ -170,6 +178,8 @@ function secret_signout() {
 	fi
 }
 
+# secret_signin [--quiet]
+# [--quiet] used when its operation is secondary to another
 function secret_signin() {
 	local email key ec
 	# session
@@ -261,7 +271,7 @@ function fetch_vault() {
 
 	# filter or ask
 	choose-option \
-		--question='Which vault do you want?' \
+		--question="Which vault did you want with [$vault]?" \
 		--filter="$vault" --label --visual="\$label [\$value]" \
 		-- "${tuples[@]}"
 	return "$?" # return with the above on success and failure
@@ -280,7 +290,7 @@ function fetch_item() {
 
 	# filter or ask
 	choose-option \
-		--question='Which item do you want?' \
+		--question="Which item did you want with [$item]?" \
 		--filter="$item" --label --visual="\$label [\$value]" \
 		-- "${tuples[@]}"
 	return "$?" # return with the above on success and failure
@@ -318,7 +328,7 @@ function fetch_field() {
 
 	# filter or ask
 	choose-option \
-		--question='Which field do you want?' \
+		--question="Which field did you want with [$field]?" \
 		--filter="$field" --label --visual="\$label [\$value]" --return="$wants" \
 		-- "${fields[@]}"
 	return "$?" # return with the above on success and failure
@@ -457,9 +467,9 @@ function secret_unmap() {
 }
 
 function secret_env() {
-	local before=() after=() found='no' arg vars args
-	local envSecrets var value
-	local envArgs arg envArg
+	local before=() after=() found='no' args arg
+	local keys key value
+	local envSecrets envArgs envArg
 
 	for arg in "$@"; do
 		if test "$arg" = '--'; then
@@ -474,29 +484,27 @@ function secret_env() {
 	done
 
 	if test "$found" = 'yes' && is-array-full "${before[@]}" && is-array-full "${after[@]}"; then
-		vars=("${before[@]}")
+		keys=("${before[@]}")
 		args=("${after[@]}")
 	else
 		stderr echo 'ERROR: -- was not found. Refer to usage.'
 		return 1
-		# vars=()
-		# args=("${before[@]}")
 	fi
 
 	# load secrets
 	envSecrets=()
-	for var in "${vars[@]}"; do
-		value="$(secret_get "$var")"
-		envSecrets+=("$var=$value")
+	for key in "${keys[@]}"; do
+		value="$(secret_get "$key")"
+		envSecrets+=("$key=$value")
 	done
 
 	# replace secrets in args
 	envArgs=()
 	for arg in "${args[@]}"; do
 		envArg="$arg"
-		for var in "${vars[@]}"; do
-			value="$(secret_get "$var")"
-			envArg="${envArg//\$$var/$value}"
+		for key in "${keys[@]}"; do
+			value="$(secret_get "$key")"
+			envArg="${envArg//\$$key/$value}"
 		done
 		envArgs+=("$envArg")
 	done
