secret: rewrote help, and updated commands
- `signin` => `login`
- `signout` => `logout`
- `clear` => `invalidate`
- `fetch` is now documented and supported
- `help` is added
- if no action is provided, you are prompted
- supports fetching item

This is enabled by rewriting `ask-options` as the new `choose-option`, and updated `cpr` accordingly.

diff --git a/commands/secret b/commands/secret
--- a/commands/secret
+++ b/commands/secret
@@ -87,11 +87,11 @@ function cache_read() {
 	fi
 }
 
-function fetch_secret() {
+function secret_get() {
 	# many
 	if test "${#@}" -gt '1'; then
 		for var in "$@"; do
-			value="$(fetch_secret "$var")"
+			value="$(secret_get "$var")"
 			if test "$?" -ne 0; then
 				stderr echo "ERROR: Unable to fetch the secret [$var] of many"
 				return 1
@@ -134,7 +134,9 @@ function fetch_secret() {
 
 
 function secret_signout() {
-	echo 'Signing out...'
+	if test "${1-}" != '--quiet'; then
+		echo 'Unauthenticating...'
+	fi
 	if test -z "${OP_SESSION-}"; then
 		if cache_exists "OP_SESSION"; then
 			OP_SESSION="$(cache_read OP_SESSION)"
@@ -146,12 +148,16 @@ function secret_signout() {
 	cache_delete "OP_SESSION"
 	cache_delete "OP_SUBDOMAIN"
 	OP_SESSION=''
-	echo 'Signed out.'
+	if test "${1-}" != '--quiet'; then
+		echo 'Unauthenticated.'
+	fi
 }
 
 function secret_signin() {
 	# session
-	echo 'Signing in...'
+	if test "${1-}" != '--quiet'; then
+		echo 'Authenticating...'
+	fi
 	if test -z "${OP_SESSION-}"; then
 		OP_SESSION="$( (cache_exists OP_SESSION && cache_read OP_SESSION) || :)"
 		if test -z "$OP_SESSION"; then
@@ -179,14 +185,16 @@ function secret_signin() {
 			cache_write "OP_SESSION" "$OP_SESSION"
 		fi
 	fi
-	echo 'Signed in.'
+	if test "${1-}" != '--quiet'; then
+		echo 'Authenticated.'
+	fi
 }
 
 function opwrap () {
 	result="$(op "$@" 2>&1 || :)"
 	if test "$?" -ne 0 || [[ "$result" = '[ERROR]'* ]]; then
 		if [[ "$result" = *'signed in'* ]] || [[ "$result" = *'session expired'* ]]; then
-			stderr echo "ERROR: Session expired, run [secret signin] and try again."
+			stderr echo "ERROR: Session expired, run [secret login] and try again."
 			return 1
 		fi
 		stderr echo "FAILURE: $result"
@@ -354,6 +362,13 @@ function secret_https() {
 	echo 'All done.'
 }
 
+function secret_fetch() {
+	vault="$(fetch_vault "${1-}")"
+	item="$(fetch_item "$vault" "${2-}")"
+	fetch_field "$vault" "$item" "${3-}"
+	return "$?"
+}
+
 function secret_map() {
 	secret="$(ask-mandatory 'What shall the name of the environment variable (secret) be?' "${1-}")"
 	vault="$(fetch_vault "${2-}")"
@@ -372,7 +387,7 @@ function secret_map() {
 	stderr echo "Sucessfully updated [$database] so that [$secret] fetches [$vault].[$item].[$field]"
 	stderr echo "Fetching [$secret]..."
 	cache_delete "$secret"
-	fetch_secret "$secret"
+	secret_get "$secret"
 }
 
 function secret_unmap() {
@@ -419,7 +434,7 @@ function secret_env() {
 	# load secrets
 	envSecrets=()
 	for var in "${vars[@]}"; do
-		value="$(fetch_secret "$var")"
+		value="$(secret_get "$var")"
 		envSecrets+=("$var=$value")
 	done
 
@@ -428,7 +443,7 @@ function secret_env() {
 	for arg in "${args[@]}"; do
 		envArg="$arg"
 		for var in "${vars[@]}"; do
-			value="$(fetch_secret "$var")"
+			value="$(secret_get "$var")"
 			envArg="${envArg//\$$var/$value}"
 		done
 		envArgs+=("$envArg")
@@ -441,70 +456,144 @@ function secret_env() {
 	env "${envSecrets[@]}" "${envArgs[@]}"
 }
 
-if test -n "${1-}"; then
-	if test "$1" = "env"; then
-		secret_signin >&2 # redirect function to stderr
-		secret_env "${@:2}"
-	elif test "$1" = "clear" -o "$1" = "delete"; then
-		if is-string "${2-}"; then
-			cache_delete "${@:2}"
-		else
-			cache_clear
-		fi
-	elif test "$1" = "edit"; then
-		edit "$database"
-	elif test "$1" = "signin" -o "$1" = "login"; then
-		secret_signout
-		secret_signin
-	elif test "$1" = "signout" -o "$1" = "logout"; then
-		secret_signout
-	elif test "$1" = "refresh"; then
-		secret_signin >&2 # redirect function to stderr
-		if is-string "$2"; then
-			cache_delete "${@:2}"
-			fetch_secret "${@:2}"
-		else
-			stderr echo 'ERROR: <name> was not found. Refer to usage.'
-			exit 1
-		fi
-	elif test "$1" = "get" -o "$1" = "fetch"; then
-		secret_signin >&2 # redirect function to stderr
-		if is-string "$2"; then
-			fetch_secret "${@:2}"
-		else
-			stderr echo 'ERROR: <name> was not found. Refer to usage.'
-			exit 1
-		fi
-	elif test "$1" = "upgrade"; then
-		# https://app-updates.agilebits.com/product_history/CLI
-		brew install --cask 1password-cli --force
-		# if contains-string "$(op update)" "available"; then
-		# 	brew install --cask 1password-cli --force
-		# fi
-	elif test "$1" = "map"; then
-		secret_signin >&2 # redirect function to stderr
-		secret_map "${@:2}"
-	elif test "$1" = "unmap"; then
-		secret_unmap "${@:2}"
-	elif test "$1" = "https"; then
-		secret_signin >&2 # redirect function to stderr
-		secret_https "${@:2}"
+# action
+action="$(choose-option 'What action do you wish to take?' "${1-}" -- 'install' 'login' 'logout' 'map' 'get' 'env' 'unmap' 'fetch' 'https' 'help')"
+if test "$action" = 'install'; then
+	# @todo update setup-util-... to enable reinstalls
+	# https://app-updates.agilebits.com/product_history/CLI
+	brew install --cask 1password-cli --force
+	# if contains-string "$(op update)" "available"; then
+	# 	brew install --cask 1password-cli --force
+	# fi
+elif test "$action" = 'login'; then
+	secret_signout --quiet >&2 # redirect function to stderr
+	secret_signin
+elif test "$action" = 'logout'; then
+	secret_signout
+elif test "$action" = 'map'; then
+	secret_signin >&2 # redirect function to stderr
+	secret_map "${@:2}"
+elif test "$action" = 'env'; then
+	secret_signin --quiet >&2 # redirect function to stderr
+	secret_env "${@:2}"
+elif test "$action" = 'get'; then
+	secret_signin --quiet >&2 # redirect function to stderr
+	if is-string "$2"; then
+		secret_get "${@:2}"
 	else
-		stderr echo 'invalid command'
+		stderr echo 'ERROR: <name> was not found. Refer to usage.'
+		exit 1
 	fi
+elif test "$action" = 'invalidate'; then
+	if is-string "${2-}"; then
+		cache_delete "${@:2}"
+	else
+		cache_clear
+	fi
+elif test "$action" = 'unmap'; then
+	secret_unmap "${@:2}"
+elif test "$action" = 'fetch'; then
+	secret_signin >&2 # redirect function to stderr
+	secret_fetch "${@:2}"
+elif test "$action" = 'https'; then
+	secret_signin >&2 # redirect function to stderr
+	secret_https "${@:2}"
+elif test "$action" = 'help'; then
+	cat << EOF
+USAGE:
+
+secret install
+
+	The 1Password CLI tool will be installed upfront if it does not exist, however this command forces its upgrade.
+
+secret login|signin
+
+	Authenticate with the 1Password CLI tool.
+	You will need to do this often, as sessions expire quickly for security.
+
+secret logout|signout
+
+	Invalidates your current authentication with the 1Password CLI tool.
+
+secret map <secret> [vault] [item] [field]
+
+	Map a secret to a specific 1Password vault, item, and field.
+
+	For example:
+
+		secret map MY_SECRET
+
+		Will ask you which of your vaults you would like to use,
+		then ask you which of item inside that vault you would like to use,
+		then ask you which field inside that item you would like to use,
+		then it will map the MY_SECRET secret to that specification.
+
+		Once done, this enables:
+
+			secret get MY_SECRET
+			secret env MY_SECRET -- echo 'my secret is: \$MY_SECRET'
+
+secret get <secret>
+
+	Get the value of what the secret maps to,
+	from the cache if possible, otherwise from 1Password's API if signed in.
+
+secret env <secret...> -- <command> [args...]
+
+	Gets the value of the secret(s) and passes them as configured environment variables to solely the command.
+	This prevents exposing your secrets to your general shell, your shell history, and unauthorised commands,
+	as with this, only the command you intend to run is given the secrets.
+
+	For example:
+
+		secret env MY_SECRET -- echo 'my secret is: \$MY_SECRET'
+
+		Will get the value of MY_SECRET, and provide it to the echo command's environment
+		such that when it is interpolated into
+
+			echo my secret is: \$MY_SECRET
+
+		\$MY_SECRET will be exist in that environment, and be outputted accordingly.
+
+secret unmap <secret>
+
+	Removes the mapping for the secret, such that its shorthand can no longer be fetched.
+
+secret invalidate [secret]
+
+	If a the secret argument was provided, then that secret alone will be cleared from the cache.
+	If no argument is provided, then all cached secrets will be cleared.
+
+secret fetch [vault] [item] [field]
+
+	Fetches the value of a field, from an item, from a 1Password vault.
+	If an argument is missing, you will be prompted to select its value from the available options.
+	Arguments can be partial values (for filtering), and can be the label or value.
+	Labels for vaults and items are converted to the UUID, to avoid conflicts against ambiguous names.
+	Results will be cached until they are invalidated by \`secret invalidate <secret>\`
+		or unmapped by \`secret unmap <secret>\`.
+
+	For example:
+
+		secret fetch
+
+			Will ask you which of your vaults to use,
+			then ask you which item inside that vault to use,
+			then ask you which field inside that item to fetch the value for.
+
+secret https
+
+	Update all the login URLs in your 1Password vault to use HTTPS if they support it,
+	otherwise attempt several variations and use what does work,
+	and if nothing works, then advise that the service appears unresponsive and is likely ready for archiving.
+
+secret help
+
+	Output this help message.
+
+EOF
+
 else
-	stderr echo 'USAGE:'
-	stderr echo 'secret upgrade'
-	stderr echo 'secret edit'
-	stderr echo 'secret signin'
-	stderr echo 'secret signout'
-	stderr echo 'secret clear'
-	stderr echo 'secret clear <name>'
-	stderr echo 'secret refresh <name>'
-	stderr echo 'secret get <name>'
-	stderr echo 'secret env <secret...> -- <command> [args...]'
-	stderr echo 'secret map <environment variable / secret name> <vault name> <item name> <field name>'
-	stderr echo 'secret unmap <environment variable / secret name>'
-	stderr echo 'secret https'
-	# stderr echo 'secret fetch <vault name> <item name>'
+	stderr echo 'ERROR: invalid action, use [secret help] to discover what you can do'
+	exit 1
 fi
