secret: add `secret https` to swap URLs to HTTPS
- it checks to see if the upgrade is possible before applying it, if it encounters issues, it will try and work around those issues

- it will also remove information from the URL that was only applicable for a signup use case

- fixes a non-functional typo

Introduces `http-ok` and `is-inside`, and updates `http-status` and `setup-dorothy` accordingly.

diff --git a/commands/secret b/commands/secret
--- a/commands/secret
+++ b/commands/secret
@@ -137,7 +137,7 @@ function secret_signout() {
 
 function secret_signin() {
 	# session
-	echo 'Singing in...'
+	echo 'Signing in...'
 	if is-empty-string "${OP_SESSION-}"; then
 		OP_SESSION="$(secret_read OP_SESSION || :)"
 		if is-empty-string "$OP_SESSION"; then
@@ -166,9 +166,9 @@ function secret_signin() {
 				return 1
 			fi
 			secret_write "OP_SESSION" "$OP_SESSION"
-			stderr echo 'Signed in successfully.'
 		fi
 	fi
+	stderr echo 'Signed in.'
 }
 
 function secret_grab() {
@@ -256,6 +256,82 @@ function secret_fetch() {
 		# fetch based on designation
 		echo "$data" | jq -r ".details.fields[] | .designation"
 	fi
+}
+
+function secret_https() {
+	last="${1-}"
+	secret_signin
+	vaults="$(op list vaults --session="$OP_SESSION" | jq -r '.[].uuid' | sort)"
+	for vault in $vaults; do
+		items="$(op list items --session="$OP_SESSION" --categories Login --vault "$vault" | jq -r '.[].uuid' | sort || :)"
+		# ignoring of status code is in case it returned a vault we don't have write access to
+		for item in $items; do
+			# resume
+			if test -n "$last"; then
+				if test "$item" = "$last"; then
+					# stop skipping
+					last=''
+				else
+					# continue skipping
+					echo "[$item] skipping"
+					continue
+				fi
+			fi
+			website="$(op get item --session="$OP_SESSION" --vault "$vault" "$item" - --fields website)"
+			https="$website"
+			if test -z "$https"; then
+				echo "[$item] [$website] empty"
+				continue
+			elif is-prefix 'https://' "$https"; then
+				echo "[$item] [$website] already HTTPS"
+			else
+				# trim protocol
+				trim="${https#*//}"
+				https="https://${trim}"
+				if ! http-ok "$https"; then
+					# trim www
+					trim="${trim#*www.}"
+					https="https://${trim}"
+					if ! http-ok "$https"; then
+						 # trim path, only if ? is not present
+						if [[ "$trim" = *'?'* ]]; then
+							echo "[$item] [$website] => [$https] failed"
+							continue
+						else
+							trim="$(get-url-hostname "$https")"  # using bash var replacements, only replace the last occurrence
+							https="https://${trim}"
+							if ! http-ok "$https"; then
+								echo "[$item] [$website] => [$https] failed"
+								continue
+							fi
+						fi
+					fi
+				fi
+			fi
+			# if the pathname has registration details, trim them, as the account has already been created
+			if is-inside "$https" signup signing reset token join register logout password forgot invitation invite; then
+				trim="$(get-url-hostname "$https")"
+				if http-ok "https://${trim}"; then
+					https="https://${trim}"
+				fi
+			fi
+			# try trim www, in case the same, or in case only protocol was changed
+			trim="${https#*www.}"
+			if test "$trim" != "$https" && http-ok "https://${trim}"; then
+				https="https://${trim}"
+			fi
+			# apply the change
+			if test "$https" != "$website"; then
+				echo "[$item] [$website] => [$https]"
+				op edit item --session="$OP_SESSION" --vault "$vault" "$item" website="$https"
+			else
+				# check if the website is still active
+				if ! http-ok "$website"; then
+					echo "[$item] [$website] no longer active"
+				fi
+			fi
+		done
+	done
 }
 
 function secret_map() {
@@ -388,6 +464,8 @@ if test -n "${1-}"; then
 		secret_unmap "${@:2}"
 	elif test "$1" = "fetch"; then
 		secret_fetch "${@:2}"
+	elif test "$1" = "https"; then
+		secret_https "${@:2}"
 	else
 		stderr echo 'invalid command'
 	fi
@@ -404,5 +482,6 @@ else
 	stderr echo 'secret env <secret...> -- <command> [args...]'
 	stderr echo 'secret map <environment variable / secret name> <vault name> <item name> <field name>'
 	stderr echo 'secret unmap <environment variable / secret name>'
+	stderr echo 'secret https'
 	# stderr echo 'secret fetch <vault name> <item name>'
 fi
