- finish implementing `__slice` - prevent variable conflicts on eval'd statments - consistent reference behaviour - consistent return handling on print lines - consistent index syntax, `$` is only necessary on associative arrays - fix a syntax error on bash 4.3 and 4.4 - some mild improvements to `symlink-helper` - `errors.md` make the problems a little bit clear, even if it has some duplication

diff --git a/commands/secret b/commands/secret
--- a/commands/secret
+++ b/commands/secret
@@ -537,7 +537,7 @@ function secret_() (
 		# fetch available vaults
 		__split {tuples} --no-zero-length --invoke -- __op_grab || :
 		if [[ ${#tuples[@]} -eq 0 ]]; then
-			echo-error 'Failed to fetch vault:' --newline --="$(__dump_vars vault)" || return
+			echo-error 'Failed to fetch vault:' --newline --="$(__dump vault)" || return
 			return 1
 		fi
 
@@ -554,7 +554,7 @@ function secret_() (
 		# fetch available items
 		__split {tuples} --no-zero-length --invoke -- __op_grab "$vault" || :
 		if [[ ${#tuples[@]} -eq 0 ]]; then
-			echo-error 'Failed to fetch item:' --newline --="$(__dump_vars vault item)" || return
+			echo-error 'Failed to fetch item:' --newline --="$(__dump vault item)" || return
 			return 1
 		fi
 
@@ -577,7 +577,7 @@ function secret_() (
 		# fetch available items
 		__split {tuples} --no-zero-length --invoke -- __op_grab "$vault" "$item" || :
 		if [[ ${#tuples[@]} -eq 0 ]]; then
-			echo-error 'Failed to fetch field:' --newline --="$(__dump_vars vault item field)" || return
+			echo-error 'Failed to fetch field:' --newline --="$(__dump vault item field)" || return
 			return 1
 		fi
 
