secret: map will now ask which field
introduces a new `ask-options` command, which takes `ask-options <question> <default> <options...>`

updates `cpr` accordingly

fix lint issues in `setup-dns`

diff --git a/commands/secret b/commands/secret
--- a/commands/secret
+++ b/commands/secret
@@ -154,15 +154,18 @@ function secret_grab() {
 	vault="$1"
 	item="$2"
 	secret_signin
-	result="$(ok op get item "$item" --vault="$vault" --session="$OP_SESSION")"
-	if is-empty-string "$result"; then
-		stderr echo "ERROR: Failed to fetch item ${item} from vault ${vault}. Nothing was returned."
+	result="$(op get item "$item" --vault="$vault" --session="$OP_SESSION" 2>&1 || :)"
+	if is-empty-value "$result"; then
+		stderr echo "ERROR: Failed to fetch item ${item} from vault ${vault}."
+		stderr echo "Nothing was returned: [$item]=[$result]"
 		return 1
 	elif [[ "$result" = *'signed in'* ]]; then
-		stderr echo "ERROR: Failed to fetch item ${item} from vault ${vault}. Session expired. Run: secret signin"
+		stderr echo "ERROR: Failed to fetch item ${item} from vault ${vault}."
+		stderr echo "Session expired, run [secret signin] and try again."
 		return 1
 	elif [[ "$result" = *'ERROR'* ]]; then
-		stderr echo "ERROR: Failed to fetch item ${item} from vault ${vault}. ${result}"
+		stderr echo "ERROR: Failed to fetch item ${item} from vault ${vault}."
+		stderr echo "$result"
 		return 1
 	else
 		echo -n "$result"
@@ -172,13 +175,29 @@ function secret_grab() {
 function secret_fetch() {
 	vault="$1"
 	item="$2"
-	field="$3"
-	if test "$field" = "username"; then
-		secret_grab "$vault" "$item" | jq -r ".details.fields[] | select(.designation==\"username\").value"
-	elif test "$field" = "password"; then
-		secret_grab "$vault" "$item" | jq -r ".details.fields[] | select(.designation==\"password\").value"
-	elif is-string "$field"; then
-		secret_grab "$vault" "$item" | jq -r ".details.sections[] | select(.fields).fields[] | select(.t==\"$field\").v"
+	field="${3-}"
+	data="$(secret_grab "$vault" "$item")"
+	# fetch value, or fetch options
+	if is-value "$field"; then
+		# fetch based on section
+		result="$(echo "$data" | jq -r --arg key "$field" ".details.sections[] | select(.fields).fields[] | select(.t==\$key).v")"
+		if is-empty-value "$result"; then
+			# fetch based on standalone
+			result="$(echo "$data" | jq -r --arg key "$field" ".details.fields[] | select(.name==\$key).value")"
+			# fetch based on designation
+			if is-empty-value "$result"; then
+				result="$(echo "$data" | jq -r --arg key "$field" ".details.fields[] | select(.designation==\$key).value")"
+			fi
+		fi
+		# output
+		echo -n "$result"
+	else
+		# fetch based on section
+		echo "$data" | jq -r ".details.sections[] | select(.fields).fields[] | .t"
+		# fetch based on standalone
+		echo "$data" | jq -r ".details.fields[] | .name"
+		# fetch based on designation
+		echo "$data" | jq -r ".details.fields[] | .designation"
 	fi
 }
 
@@ -186,8 +205,7 @@ function secret_map() {
 	secret="$(ask-mandatory 'What shall the name of the environment variable (secret) be?' "${1-}")"
 	vault="$(ask-mandatory 'What vault should it map to?' "${2:-personal}")"
 	item="$(ask-mandatory 'What item should it map to?' "${3-}")"
-	field="$(ask-mandatory 'What field should it map to?' "${4-}")"
-	echo 'Enter your sudo password to update the database with the correct permissions...'
+	field="$(ask-options 'What field should it map to?' "${4-}" "$(secret_fetch "$vault" "$item")")"
 	result="$(sudo jq -r \
 		--arg secret "$secret" \
 		--arg vault "$vault" \
@@ -200,6 +218,7 @@ function secret_map() {
 	sudo chmod 600 "$database"
 	stderr echo "Sucessfully wrote [$secret] to fetch from [$vault].[$item].[$field]"
 	stderr echo "Attempting fetch of [$secret] now..."
+	secret_delete "$secret"
 	secret_resolve "$secret"
 }
 
@@ -213,6 +232,7 @@ function secret_unmap() {
 	echo "$result" | sudo tee "$database"
 	sudo chown root "$database"
 	sudo chmod 600 "$database"
+	secret_delete "$secret"
 	stderr echo "Sucessfully unmapped [$secret]"
 }
 
@@ -309,6 +329,8 @@ if test -n "${1-}"; then
 		secret_map "${@:2}"
 	elif test "$1" = "unmap"; then
 		secret_unmap "${@:2}"
+	elif test "$1" = "fetch"; then
+		secret_fetch "${@:2}"
 	else
 		stderr echo 'invalid command'
 	fi
@@ -325,4 +347,5 @@ else
 	stderr echo 'secret env <secret...> -- <command> [args...]'
 	stderr echo 'secret map <environment variable / secret name> <vault name> <item name> <field name>'
 	stderr echo 'secret unmap <environment variable / secret name>'
+	# stderr echo 'secret fetch <vault name> <item name>'
 fi
