secret: non-functional typo fixes

diff --git a/commands/secret b/commands/secret
--- a/commands/secret
+++ b/commands/secret
@@ -164,25 +164,23 @@ function secret_grab() {
 	if is-empty-value "$vault"; then
 		# fetch available values
 		result="$(op list vaults --session="$OP_SESSION" 2>&1 || :)"
+	elif is-empty-value "$item"; then
+		# fetch available items
+		result="$(op list items --vault="$vault" --session="$OP_SESSION" 2>&1 || :)"
 	else
-		if is-empty-value "$item"; then
-			# fetch available items
-			result="$(op list items --vault="$vault" --session="$OP_SESSION" 2>&1 || :)"
-		else
-			# fetch item
-			result="$(op get item "$item" --vault="$vault" --session="$OP_SESSION" 2>&1 || :)"
-		fi
+		# fetch item
+		result="$(op get item "$item" --vault="$vault" --session="$OP_SESSION" 2>&1 || :)"
 	fi
 	# process result
 	if is-empty-value "$result"; then
-		stderr echo "ERROR: Nothing was returned: value=[$vault], item=[$item], result=[$result]"
+		stderr echo "ERROR: Nothing was returned: vault=[$vault], item=[$item], result=[$result]"
 		return 1
 	elif [[ "$result" = *'signed in'* ]]; then
-		stderr echo "ERROR: Unable to return: value=[$vault], item=[$item]"
+		stderr echo "ERROR: Unable to return: vault=[$vault], item=[$item]"
 		stderr echo "Session expired, run [secret signin] and try again."
 		return 1
 	elif [[ "$result" = *'ERROR'* ]]; then
-		stderr echo "ERROR: Failed to return: value=[$vault], item=[$item]"
+		stderr echo "ERROR: Failed to return: vault=[$vault], item=[$item]"
 		stderr echo "$result"
 		return 1
 	else
