secret: add `secret map ...` command
now allows you to configure the json file yourself

also fixed some oddities with incorrect logic pathways being followed due to `jq` returning `null` when a fetch fails

introduces the new helper `is-value` accordingly

also fixes `is-empty-value` when no argument is passed

diff --git a/commands/secret b/commands/secret
--- a/commands/secret
+++ b/commands/secret
@@ -21,6 +21,11 @@ export OP_SUBDOMAIN
 export database="$SECRETS/secrets.json"
 
 function secret_resolve() {
+	# Write the database if it does not exist
+	if ! sudo test -f "$database"; then
+		echo '{}' | sudo tee "$database"  &>/dev/null
+	fi
+
 	# many
 	if test "${#@}" -gt '1'; then
 		for var in "$@"; do
@@ -36,20 +41,17 @@ function secret_resolve() {
 	if is-string "$result"; then
 		echo -n "$result"
 	elif is-empty-string "$result"; then
-		if ! sudo test -f "$database"; then
-			stderr echo -en "ERROR: secret requires [$database] to exist, in the format of:\\n{\\n  \"SECRET\": [\"vault\", \"item\", \"field\"]\\n}"
-			return 1
-		fi
 		vault="$(sudo jq -r ".${key}[0]" "$database")"
 		item="$(sudo jq -r ".${key}[1]" "$database")"
 		field="$(sudo jq -r ".${key}[2]" "$database")"
-		if is-string "$vault" && is-string "$item" && is-string "$field"; then
+		if is-value "$vault" && is-value "$item" && is-value "$field"; then
 			value="$(secret_fetch "$vault" "$item" "$field")"
 		else
-			stderr echo "ERROR: [$database] had an entry that did not have all three parts: [$vault] [$item] [$field]"
+			stderr echo "ERROR: [$database] needs [$key] to have all three parts of its mapping: [$vault, $item, $field]"
+			stderr echo "Use the [secret map ...] command to set the mapping accordingly."
 			return 1
 		fi
-		if is-empty-string "$value"; then
+		if is-empty-value "$value"; then
 			stderr echo "ERROR: resolve returned nothing for: $key"
 			return 1
 		fi
@@ -180,6 +182,40 @@ function secret_fetch() {
 	fi
 }
 
+function secret_map() {
+	secret="$(ask-mandatory 'What shall the name of the environment variable (secret) be?' "${1-}")"
+	vault="$(ask-mandatory 'What vault should it map to?' "${2:-personal}")"
+	item="$(ask-mandatory 'What item should it map to?' "${3-}")"
+	field="$(ask-mandatory 'What field should it map to?' "${4-}")"
+	echo 'Enter your sudo password to update the database with the correct permissions...'
+	result="$(sudo jq -r \
+		--arg secret "$secret" \
+		--arg vault "$vault" \
+		--arg item "$item" \
+		--arg field "$field" \
+		'.[$secret] = [$vault, $item, $field]' \
+		"$database")"
+	echo "$result" | sudo tee "$database"
+	sudo chown root "$database"
+	sudo chmod 600 "$database"
+	stderr echo "Sucessfully wrote [$secret] to fetch from [$vault].[$item].[$field]"
+	stderr echo "Attempting fetch of [$secret] now..."
+	secret_resolve "$secret"
+}
+
+function secret_unmap() {
+	secret="$(ask-mandatory 'What environment variable (secret) name do you wish to unmap?' "${1-}")"
+	echo 'Enter your sudo password to update the database with the correct permissions...'
+	result="$(sudo jq -r \
+		--arg secret "$secret" \
+		'del(.[$secret])' \
+		"$database")"
+	echo "$result" | sudo tee "$database"
+	sudo chown root "$database"
+	sudo chmod 600 "$database"
+	stderr echo "Sucessfully unmapped [$secret]"
+}
+
 function secret_env() {
 	before=()
 	after=()
@@ -269,6 +305,10 @@ if test -n "${1-}"; then
 		# if contains-string "$(op update)" "available"; then
 		# 	brew install --cask 1password-cli --force
 		# fi
+	elif test "$1" = "map"; then
+		secret_map "${@:2}"
+	elif test "$1" = "unmap"; then
+		secret_unmap "${@:2}"
 	else
 		stderr echo 'invalid command'
 	fi
@@ -283,4 +323,6 @@ else
 	stderr echo 'secret refresh <name>'
 	stderr echo 'secret get <name>'
 	stderr echo 'secret env <secret...> -- <command> [args...]'
+	stderr echo 'secret map <environment variable / secret name> <vault name> <item name> <field name>'
+	stderr echo 'secret unmap <environment variable / secret name>'
 fi
