secret now supports 1password cli v1 and v2
choose-option:

- fixes visual not able to access `$LABEL` or `$VALUE`

completions:

- add support for 1password cli

strict:

- simplified comments according to modern practices

diff --git a/commands/secret b/commands/secret
--- a/commands/secret
+++ b/commands/secret
@@ -23,7 +23,8 @@ function secret() (
 			login|signin
 
 			    Authenticate with the 1Password CLI tool.
-			    You will need to do this often, as sessions expire quickly for security.
+			    If using 1Password CLI v1, sessions expire quickly for security, so this is occassionally required.
+			    If using 1Password CLI v2 with Biometric security, this is rarely required.
 
 			logout|signout
 
@@ -139,18 +140,23 @@ function secret() (
 	# Dependencies
 
 	setup-util-jq --quiet
-	setup-util-1password-cli --quiet
-
-	# check compatibility
-	local cli_version
-	cli_version="$(op --version)"
-	if test "$(version-compare "$cli_version" 1)" -ne 0; then
-		help "Secret only supports 1Password CLI version 1. You have version $cli_version"
+	if command-missing op; then
+		setup-util-1password-cli --quiet
 	fi
 
-	# @todo add 1password cli v2 compat
-	# https://developer.1password.com/docs/cli/upgrade
-	# https://developer.1password.com/docs/cli/upgrade#step-2-update-your-scripts
+	# check compatibility
+	local op_version
+	op_version="$(op --version)"
+	if test "$(version-compare "$op_version" 1)" -eq 0; then
+		# https://developer.1password.com/docs/cli/v1/reference
+		op_version=1
+	elif test "$(version-compare "$op_version" 2)" -eq 0; then
+		# https://developer.1password.com/docs/cli/upgrade
+		# https://developer.1password.com/docs/cli/upgrade#step-2-update-your-scripts
+		op_version=2
+	else
+		help "Unsupported 1Password CLI version: $op_version"
+	fi
 
 	# =====================================
 	# Adjustments
@@ -320,10 +326,18 @@ function secret() (
 		if test -z "${OP_SESSION-}"; then
 			if cache_exists "OP_SESSION"; then
 				OP_SESSION="$(cache_read OP_SESSION)"
-				op signout --session="$OP_SESSION" 2>&1 || :
+				if test "$op_version" -eq 2; then
+					op signout --session "$OP_SESSION" 2>&1 || :
+				else
+					op signout --session="$OP_SESSION" 2>&1 || :
+				fi
 			fi
 		else
-			op signout --session="$OP_SESSION" 2>&1 || :
+			if test "$op_version" -eq 2; then
+				op signout --session "$OP_SESSION" 2>&1 || :
+			else
+				op signout --session="$OP_SESSION" 2>&1 || :
+			fi
 		fi
 		cache_delete "OP_SESSION"
 		cache_delete "OP_SUBDOMAIN"
@@ -335,6 +349,7 @@ function secret() (
 
 	# secret_signin [--quiet]
 	# [--quiet] used when its operation is secondary to another
+	# trunk-ignore(shellcheck/SC2120)
 	function secret_signin {
 		local quiet email key ec
 		quiet="$(echo-quiet "$option_quiet" -- "$@")"
@@ -360,22 +375,30 @@ function secret() (
 					ask --required "${ask_password_arguments[@]}" \
 						--question='What is your 1password email? This is not stored.'
 				)"
-				key="$(
-					ask --required "${ask_password_arguments[@]}" \
-						--question='What is your 1password account key? This is not stored.'
-				)"
-				# signin
-				# unfortunately, this still leaks email and subdomain
-				# https://1password.community/discussion/122030/flag-to-disable-op-signin-from-outputting-email-and-subdomain/p1?new=1
-				# don't pipe to anything else, as it breaks the OTP question
-				ec=0 && OP_SESSION="$(op signin "$OP_SUBDOMAIN" "$email" "$key" --raw)" || ec="$?"
+				if test "$op_version" -eq 2; then
+					ec=0 && OP_SESSION="$(op account add --address "$OP_SUBDOMAIN" --email "$email" --signin --raw)" || ec="$?"
+					# OP_SESSION will equal '' if biometric auth is used
+				else
+					key="$(
+						ask --required "${ask_password_arguments[@]}" \
+							--question='What is your 1password account key? This is not stored.'
+					)"
+					# unfortunately, this still leaks email and subdomain
+					# https://1password.community/discussion/122030/flag-to-disable-op-signin-from-outputting-email-and-subdomain/p1?new=1
+					# don't pipe to anything else, as it breaks the OTP question
+					ec=0 && OP_SESSION="$(op signin "$OP_SUBDOMAIN" "$email" "$key" --raw)" || ec="$?"
+				fi
 				if test "$ec" -ne 0; then
-					echo-errir \
+					echo-error \
 						"Failed to sign into [$OP_SUBDOMAIN] via the email [$email] and account key [$key]." \
 						"OP_SESSION = [$OP_SESSION]"
 					return 1
 				fi
-				cache_write "OP_SESSION" "$OP_SESSION"
+				if test -n "$OP_SESSION"; then
+					cache_write "OP_SESSION" "$OP_SESSION"
+				else
+					cache_delete "OP_SESSION" # biometric
+				fi
 			fi
 		fi
 		if test "$quiet" != 'yes'; then
@@ -388,7 +411,7 @@ function secret() (
 		ec=0 && result="$(op "$@" 2>&1)" || ec="$?"
 		if test "$ec" -ne 0 || [[ $result == '[ERROR]'* ]]; then
 			if [[ $result == *'signed in'* ]] || [[ $result == *'session expired'* ]]; then
-				echo-error "Session expired, run [secret login] and try again."
+				echo-error "Session expired, run [secret login] and try again." $'\n' "$result" # $'\n' "$OP_SESSION"
 				return 1
 			fi
 			echo-error "$result"
@@ -403,13 +426,53 @@ function secret() (
 
 		if is-empty-value "$vault"; then
 			# fetch available values
-			ec=0 && opwrap list vaults --session="$OP_SESSION" || ec="$?"
+			if test "$op_version" -eq 2; then
+				# https://developer.1password.com/docs/cli/reference/management-commands/vault#vault-list
+				ec=0 && opwrap vault list --format=json --session "$OP_SESSION" | jq -r '.[] | (.id, .name)' || ec="$?"
+			else
+				ec=0 && opwrap list vaults --session="$OP_SESSION" | jq -r '.[] | (.uuid, .name)' || ec="$?"
+			fi
 		elif is-empty-value "$item"; then
 			# fetch available items
-			ec=0 && opwrap list items --vault="$vault" --session="$OP_SESSION" || ec="$?"
+			if test "$op_version" -eq 2; then
+				# https://developer.1password.com/docs/cli/reference/management-commands/item#item-list
+				ec=0 && opwrap item list --vault "$vault" --format json --session "$OP_SESSION" | jq -r '.[] | (.id, .title)' || ec="$?"
+			else
+				ec=0 && opwrap list items --vault="$vault" --session="$OP_SESSION" | jq -r '.[] | (.uuid, .overview.title)' || ec="$?"
+			fi
 		else
 			# fetch item
-			ec=0 && opwrap get item "$item" --vault="$vault" --session="$OP_SESSION" || ec="$?"
+			if test "$op_version" -eq 2; then
+				# https://developer.1password.com/docs/cli/reference/management-commands/item#item-get
+				# https://stackoverflow.com/a/40321859
+				# newlines in notes will produces superflous tuples, so replace them four spaces
+				# cli v2 needs null checks too
+				ec=0 && opwrap item get "$item" --vault "$vault" --format json --session "$OP_SESSION" | jq -r '.fields[]? | select(.label != "" and .label != null and .value != "" and .value != null) | (.value, .label) | walk(if type == "string" then gsub("\\p{Cc}"; "    ") else . end)' || ec="$?"
+			else
+				ec=0 && data="$(opwrap get item "$item" --vault="$vault" --session="$OP_SESSION")" || ec="$?"
+				if test "$ec" -eq 0; then
+					# section fields
+					local fields_via_section
+					mapfile -t fields_via_section < <(echo "$data" | jq -r '.details.sections[]? | select(.fields).fields[]? | select(.t != "" and .v != "") | (.v, .t)')
+					if is-array-count-ge 2 "${fields_via_section[@]}"; then
+						echo-lines "${fields_via_section[@]}"
+					fi
+
+					# name fields
+					local fields_via_name
+					mapfile -t fields_via_name < <(echo "$data" | jq -r '.details.fields[]? | select(.name != "" and .value != "") | (.value, .name)')
+					if is-array-count-ge 2 "${fields_via_name[@]}"; then
+						echo-lines "${fields_via_name[@]}"
+					fi
+
+					# designation fields
+					local fields_via_designation
+					mapfile -t fields_via_designation < <(echo "$data" | jq -r '.details.fields[]? | select(.designation != "" and .value != "") | (.value, .designation)')
+					if is-array-count-ge 2 "${fields_via_designation[@]}"; then
+						echo-lines "${fields_via_designation[@]}"
+					fi
+				fi
+			fi
 		fi
 
 		return "$ec"
@@ -419,7 +482,7 @@ function secret() (
 		local vault="${1-}" tuples
 
 		# fetch available vaults
-		mapfile -t tuples < <(opgrab | jq -r '.[] | (.uuid, .name)')
+		mapfile -t tuples < <(opgrab)
 		if is-array-empty "${tuples[@]}"; then
 			echo-error "Failed to fetch a vault:" $'\n' \
 				"$(echo-verbose "${tuples[@]}")"
@@ -438,7 +501,7 @@ function secret() (
 		local vault="${1-}" item="${2-}" tuples
 
 		# fetch available items
-		mapfile -t tuples < <(opgrab "$vault" | jq -r '.[] | (.uuid, .overview.title)')
+		mapfile -t tuples < <(opgrab "$vault")
 		if is-array-empty "${tuples[@]}"; then
 			echo-error "Failed to fetch any items:" $'\n' \
 				"$(echo-verbose "${tuples[@]}")"
@@ -454,8 +517,8 @@ function secret() (
 	}
 
 	function fetch_field {
-		local vault="${1-}" item="${2-}" field="${3-}" wants
-		local fields=() data fields_via_section fields_via_name fields_via_designation
+		local vault="${1-}" item="${2-}" field="${3-}" tuples
+		local wants
 		if test "${4-}" = '--label'; then
 			# trunk-ignore(shellcheck/SC2016)
 			wants='$LABEL'
@@ -465,31 +528,18 @@ function secret() (
 		fi
 
 		# fetch available items
-		data="$(opgrab "$vault" "$item")"
-
-		# section fields
-		mapfile -t fields_via_section < <(echo "$data" | jq -r '.details.sections[]? | select(.fields).fields[]? | select(.t != "" and .v != "") | (.v, .t)')
-		if is-array-count-ge 2 "${fields_via_section[@]}"; then
-			fields+=("${fields_via_section[@]}")
-		fi
-
-		# name fields
-		mapfile -t fields_via_name < <(echo "$data" | jq -r '.details.fields[]? | select(.name != "" and .value != "") | (.value, .name)')
-		if is-array-count-ge 2 "${fields_via_name[@]}"; then
-			fields+=("${fields_via_name[@]}")
-		fi
-
-		# designation fields
-		mapfile -t fields_via_designation < <(echo "$data" | jq -r '.details.fields[]? | select(.designation != "" and .value != "") | (.value, .designation)')
-		if is-array-count-ge 2 "${fields_via_designation[@]}"; then
-			fields+=("${fields_via_designation[@]}")
+		mapfile -t tuples < <(opgrab "$vault" "$item")
+		if is-array-empty "${tuples[@]}"; then
+			echo-error "Failed to fetch any items:" $'\n' \
+				"$(echo-verbose "${tuples[@]}")"
+			return 1
 		fi
 
 		# filter or ask
 		choose-option \
 			--question="Which field did you want with [$field]?" \
 			--filter="$field" --label --visual="\$LABEL [\$VALUE]" --return="$wants" \
-			-- "${fields[@]}"
+			-- "${tuples[@]}"
 		return "$?" # return with the above on success and failure
 	}
 
@@ -499,50 +549,72 @@ function secret() (
 
 	function item_upgrade {
 		local vault="$1" item="$2" ec result
+
 		# fetch
-		ec=0 && website="$(opwrap get item --session="$OP_SESSION" --vault "$vault" "$item" --fields website)" || ec="$?"
+		if test "$op_version" -eq 2; then
+			# [select(.primary = true)] returns multiple urls
+			ec=0 && website="$(opwrap item get "$item" --vault "$vault" --format json --session "$OP_SESSION" | jq -r '.urls[]? | .href' | echo-first)" || ec="$?"
+		else
+			ec=0 && website="$(opwrap get item "$item" --vault "$vault" --fields website --session="$OP_SESSION")" || ec="$?"
+		fi
 		if test "$ec" -ne 0; then
-			echo-error "[$item] [$website] failed to fetch"
+			echo-style --error="[$item] [$website] failed to fetch"
 			return 1
 		fi
 		if test -z "$website"; then
-			echo-error "[$item] [$website] empty"
-			return 1
+			echo-style --dim="[$item] no urls"
+			return 0
 		fi
+
 		# upgrade
-		result="$(silent-stderr get-url-upgrade "$website" || :)"
+		result="$(get-url-upgrade "$website" 2>/dev/null || :)"
 		if test -z "$result"; then
 			# echo to stdout, as is actionable for user if they are piping
-			echo-error "[$item] [$website] unresponsive, consider archiving"
+			echo-style --notice="[$item] [$website] unresponsive, consider archiving"
 			return 1
 		fi
+
 		# check if changed
 		if test "$result" = "$website"; then
-			echo-error "[$item] [$website] already upgraded"
-			return 1
+			echo-style --dim="[$item] [$website] already upgraded"
+			return 0
 		fi
+
 		# echo to stdout, as is actionable for user if they are piping
-		echo "[$item] [$website] => [$result]"
+		echo-style --success="[$item] [$website] => [$result]"
+
 		# apply
-		ec=0 && opwrap edit item --session="$OP_SESSION" --vault "$vault" "$item" website="$result" || ec="$?"
+		if test "$op_version" -eq 2; then
+			ec=0 && opwrap item edit "$item" --vault "$vault" --url "$result" --format json --session "$OP_SESSION" >/dev/null || ec="$?"
+		else
+			ec=0 && opwrap edit item "$item" --vault "$vault" website="$result" --session="$OP_SESSION" || ec="$?"
+		fi
 		if test "$ec" -ne 0; then
-			echo-error "[$item] [$website] failed to save"
+			echo-style --error="[$item] [$website] failed to save"
 			return 1
 		fi
 	}
 
 	function secret_https {
 		local last="${1-}" ec vault item
-		ec=0 && vaults="$(opwrap list vaults --session="$OP_SESSION" | jq -r '.[].uuid' | sort)" || ec="$?"
+		if test "$op_version" -eq 2; then
+			ec=0 && vaults="$(opwrap vault list --format json --session "$OP_SESSION" | jq -r '.[].id' | sort)" || ec="$?"
+		else
+			ec=0 && vaults="$(opwrap list vaults --session="$OP_SESSION" | jq -r '.[].uuid' | sort)" || ec="$?"
+		fi
 		if test "$ec" -ne 0 -o -z "$vaults"; then
-			echo-error "failed to fetch vaults..."
+			echo-error "Failed to fetch vaults..."
 			return 1
 		fi
 		for vault in $vaults; do
-			ec=0 && items="$(opwrap list items --session="$OP_SESSION" --categories Login --vault "$vault" | jq -r '.[].uuid' | sort)" || ec="$?"
-			if test "$ec" -ne 0 -o -z "$vaults"; then
-				echo-error "failed to fetch items from vault [$vault]"
-				return 1
+			if test "$op_version" -eq 2; then
+				ec=0 && items="$(opwrap item list --categories Login --vault "$vault" --format json --session "$OP_SESSION" | jq -r '.[].id' | sort)" || ec="$?"
+			else
+				ec=0 && items="$(opwrap list items --categories Login --vault "$vault" --session="$OP_SESSION" | jq -r '.[].uuid' | sort)" || ec="$?"
+			fi
+			if test "$ec" -ne 0 -o -z "$items"; then
+				echo-style --notice="Failed to fetch items for vault [$vault]"
+				continue
 			fi
 			# ignoring of status code is in case it returned a vault we don't have write access to
 			for item in $items; do
@@ -553,7 +625,7 @@ function secret() (
 						last=''
 					else
 						# continue skipping
-						echo "[$item] skipping"
+						echo-style --dim="[$item] skipping"
 						continue
 					fi
 				fi
@@ -563,6 +635,7 @@ function secret() (
 				(item_upgrade "$vault" "$item" || :) &
 			done
 		done
+
 		# wait for completed jobs, then note completion
 		while test "$(get_job_count)" -ne 0; do
 			echo "Waiting on [$(get_job_count)] jobs..."
@@ -683,17 +756,15 @@ function secret() (
 		setup-util-1password-cli --upgrade
 	elif test "$action" = 'login'; then
 		secret_signout --quiet >/dev/stderr
+		# trunk-ignore(shellcheck/SC2119)
 		secret_signin
 	elif test "$action" = 'logout'; then
 		secret_signout
 	elif test "$action" = 'map'; then
-		secret_signin >/dev/stderr
 		secret_map "${args[@]}"
 	elif test "$action" = 'env'; then
-		secret_signin --quiet >/dev/stderr
 		secret_env "${args[@]}"
 	elif test "$action" = 'get'; then
-		secret_signin --quiet >/dev/stderr
 		if test -n "${args[*]}"; then
 			secret_get "${args[@]}"
 		else
@@ -708,10 +779,8 @@ function secret() (
 	elif test "$action" = 'unmap'; then
 		secret_unmap "${args[@]}"
 	elif test "$action" = 'fetch'; then
-		secret_signin >/dev/stderr
 		secret_fetch "${args[@]}"
 	elif test "$action" = 'https'; then
-		secret_signin >/dev/stderr
 		secret_https "${args[@]}"
 	elif test "$action" = 'help'; then
 		help
