setup-server, mount-helper: bugfixes
- config-edit:
    - cleaner output without useless padding
- edit:
    - vscode no longer supports sudo editing
    - cleaned up the code to make it clearer
- fs-own:
    - correct exit status on invalid paths and missing paths, such that chmod/chown failures are distinguishable from existence, access, and validity failures
    - fix --optional still failing on chmod fails
- fs-rm:
    - no longer noisy on empty directories
    - trimming empty directories no longer noisy with silly find errors
- get-devices:
    - support --quiet
- added is-abort:
    - abstacted out and added support for more abort exist statuses, such that complex abort handling such as inside mount-helper becomes streamlined
- mount-helper:
    - fix `--type=<type>` flag never having worked
    - can now unmount sources and types without targets
    - can now unmount the alternative targets of a source
    - cleanup parse/dump output
    - fix gocryptfs not getting fuse config when necessary
    - fix noisy and confusing get-devices output
    - improved unmount handling to support cases where the intended unmount was done by a user/group that wasn't intended
    - better clarity about what we are performign actions on
    - only output fstab/cron details when desired
    - correct usage of grep/ripgrep
    - correct and more details unmount handling under more variations of check statuses
    - correct handling of unmount aborts in more contexts
- secret:
    - correct modern detection of login and prevent login details being output with values
- setup-linux-fonts:
    - fix source-code-pro
- setup-util:
    - add --no-xdg support
- setup-util-gocryptfs:
    - use --no-xdg to ensure that mounting under specific users/groups works
- ssh-helper:
    - use `is-abort`
- sudo-helper:
    - clean output on --local
- setup-server:
    - ensure gocryptfs is configure correctly
- bash.bash:
    - add aliases for various flags for clearer usage

diff --git a/commands/secret b/commands/secret
--- a/commands/secret
+++ b/commands/secret
@@ -112,8 +112,7 @@ function secret_() (
 	}
 
 	# process
-	local item action='' option_args=() option_conceal='no' option_quiet
-	option_quiet="$(echo-quiet-enabled -- "$@")"
+	local item action='' option_args=() option_conceal='no'
 	while test "$#" -ne 0; do
 		item="$1"
 		shift
@@ -122,7 +121,6 @@ function secret_() (
 		'--no-conceal'* | '--conceal'*)
 			option_conceal="$(get-flag-value --affirmative --fallback="$option_conceal" -- "$item")"
 			;;
-		'--no-quiet'* | '--quiet'* | '--no-verbose'* | '--verbose'*) ;; # handled by echo-quiet-enabled
 		'signin') action='login' ;;
 		'signout') action='logout' ;;
 		'--')
@@ -163,6 +161,10 @@ function secret_() (
 	else
 		help "Unsupported 1Password CLI version: $op_version"
 	fi
+
+	# prepare
+	local tty_target
+	tty_target="$(is-tty --fallback)"
 
 	# =====================================
 	# Adjustments
@@ -341,49 +343,37 @@ function secret_() (
 		print_string "$value"
 	}
 
-	# secret_signout [--quiet]
-	# [--quiet] used when its operation is secondary to another
+	# secret_signout
 	function secret_signout {
-		local quiet status
-		quiet="$(echo-quiet-enabled --fallback="$option_quiet" -- "$@")"
-		if test "$quiet" != 'yes'; then
-			print_line 'Unauthenticating...'
-		fi
+		local status
 		if test -z "$OP_SESSION"; then
 			eval_capture --statusvar=status -- __cache_exists 'OP_SESSION'
 			if test "$status" -eq 0; then
 				OP_SESSION="$(cache_read OP_SESSION)"
 				if test "$op_version" -eq 2; then
-					op signout --session "$OP_SESSION" 2>&1 || :
+					op signout --session "$OP_SESSION" >"$tty_target" || :
 				else
-					op signout --session="$OP_SESSION" 2>&1 || :
+					op signout --session="$OP_SESSION" >"$tty_target" || :
 				fi
 			fi
 		else
 			if test "$op_version" -eq 2; then
-				op signout --session "$OP_SESSION" 2>&1 || :
+				op signout --session "$OP_SESSION" >"$tty_target" || :
 			else
-				op signout --session="$OP_SESSION" 2>&1 || :
+				op signout --session="$OP_SESSION" >"$tty_target" || :
 			fi
 		fi
 		cache_delete 'OP_SESSION'
 		cache_delete 'OP_SUBDOMAIN'
 		OP_SESSION=''
-		if test "$quiet" != 'yes'; then
-			print_line 'Unauthenticated.'
-		fi
 	}
 
-	# secret_signin [--quiet]
-	# [--quiet] used when its operation is secondary to another
-	# trunk-ignore(shellcheck/SC2120)
+	# secret_signin
 	function secret_signin {
-		local quiet email key status
-		quiet="$(echo-quiet-enabled --fallback="$option_quiet" -- "$@")"
+		local email key status
+		# signout
+		secret_signout
 		# session
-		if test "$quiet" != 'yes'; then
-			print_line 'Authenticating...'
-		fi
 		if test -z "$OP_SESSION"; then
 			OP_SESSION="$(cache_read_if_exists OP_SESSION)"
 			if test -z "$OP_SESSION"; then
@@ -402,7 +392,7 @@ function secret_() (
 						--question='What is your 1password email? This is not stored.'
 				)"
 				if test "$op_version" -eq 2; then
-					eval_capture --statusvar=status --stdoutvar=OP_SESSION -- \
+					eval_capture --statusvar=status --stdoutvar=OP_SESSION --stdoutpipe="$tty_target" -- \
 						op account add --address "$OP_SUBDOMAIN" --email "$email" --signin --raw
 					# OP_SESSION will equal '' if biometric auth is used
 				else
@@ -413,7 +403,7 @@ function secret_() (
 					# unfortunately, this still leaks email and subdomain
 					# https://1password.community/discussion/122030/flag-to-disable-op-signin-from-outputting-email-and-subdomain/p1?new=1
 					# don't pipe to anything else, as it breaks the OTP question
-					eval_capture --statusvar=status --stdoutvar=OP_SESSION -- \
+					eval_capture --statusvar=status --stdoutvar=OP_SESSION --stdoutpipe="$tty_target" -- \
 						op signin "$OP_SUBDOMAIN" "$email" "$key" --raw
 				fi
 				if test "$status" -ne 0; then
@@ -428,9 +418,6 @@ function secret_() (
 					cache_delete "OP_SESSION" # biometric
 				fi
 			fi
-		fi
-		if test "$quiet" != 'yes'; then
-			print_line 'Authenticated.'
 		fi
 	}
 
@@ -456,11 +443,18 @@ function secret_() (
 		eval_capture --statusvar=status --outputvar=result -- "${cmd[@]}"
 		if test "$status" -ne 0 || [[ $result == '[ERROR]'* ]]; then
 			if [[ $result == *'signed in'* ]] || [[ $result == *'session expired'* ]]; then
-				echo-error "Session expired, run [secret login] and try again." $'\n' "$result" # $'\n' "$OP_SESSION"
-				return 1
+				echo-style --notice='Session expired. Logging in...' >"$tty_target"
+				eval_capture --statusvar=status --stdoutpipe="$tty_target" -- secret_signin
+				if test "$status" -eq 0; then
+					op_wrap "$@"
+					return
+				else
+					return "$status"
+				fi
+			else
+				print_line "$result" >/dev/stderr
+				return "$status"
 			fi
-			echo-error "$result"
-			return 1
 		else
 			print_string "$result"
 		fi
@@ -656,7 +650,7 @@ function secret_() (
 				eval_capture --statusvar=status --stdoutvar=items -- op_wrap list items --categories Login --vault "$vault" > >(jq -r '.[].uuid' | sort)
 			fi
 			if test "$status" -ne 0 -o -z "$items"; then
-				echo-style --warning="Failed to fetch items for vault [$vault]"
+				echo-style --warning="Failed to fetch items for vault [$vault]" >/dev/stderr
 				continue
 			fi
 			# ignoring of status code is in case it returned a vault we don't have write access to
@@ -668,7 +662,7 @@ function secret_() (
 						last=''
 					else
 						# continue skipping
-						echo-style --dim="[$item] skipping"
+						echo-style --dim="[$item] skipping" >"$tty_target"
 						continue
 					fi
 				fi
@@ -681,11 +675,11 @@ function secret_() (
 
 		# wait for completed jobs, then note completion
 		while test "$(get_job_count)" -ne 0; do
-			print_line "Waiting on [$(get_job_count)] jobs..."
+			print_line "Waiting on [$(get_job_count)] jobs..." >"$tty_target"
 			sleep 3
 			jobs &>/dev/null # for some reason, this seems necessary to prevent hung jobs
 		done
-		print_line 'All done.'
+		print_line 'All done.' >"$tty_target"
 	}
 
 	function secret_fetch {
@@ -714,10 +708,9 @@ function secret_() (
 			"$database")"
 		print_line "$result" | sudo tee "$database" &>/dev/null
 		correct_database_permission
-		{
-			print_line "Sucessfully updated [$database] so that [$secret] fetches [$vault].[$item].[$field]"
-			print_line "Fetching [$secret]..."
-		} >/dev/stderr
+		print_lines \
+			"Sucessfully updated [$database] so that [$secret] fetches [$vault].[$item].[$field]" \
+			"Fetching [$secret]..." >"$tty_target"
 		cache_delete "$secret"
 		secret_get "$secret"
 	}
@@ -729,7 +722,7 @@ function secret_() (
 				--question='What environment variable (secret) name do you wish to unmap?' \
 				--default="${1-}"
 		)"
-		print_line 'Enter your sudo password to update the database with the correct permissions...'
+		print_line 'Enter your sudo password to update the database with the correct permissions...' >"$tty_target"
 		result="$(jq -r \
 			--arg secret "$secret" \
 			'del(.[$secret])' \
@@ -737,7 +730,7 @@ function secret_() (
 		print_line "$result" | sudo tee "$database"
 		correct_database_permission
 		cache_delete "$secret"
-		print_line "Sucessfully unmapped [$secret]" >/dev/stderr
+		print_line "Sucessfully unmapped [$secret]" >"$tty_target"
 	}
 
 	function secret_env {
@@ -801,19 +794,28 @@ function secret_() (
 	# =====================================
 	# Act
 
+	function ensure_authed {
+		local status
+		eval_capture --statusvar=status --no-output -- op_wrap account list
+		if test "$status" -ne 0; then
+			secret_signin
+		fi
+	}
+
 	if test "$action" = 'install'; then
 		setup-util-1password-cli --upgrade
 	elif test "$action" = 'login'; then
-		secret_signout --quiet >/dev/stderr
-		# trunk-ignore(shellcheck/SC2119)
 		secret_signin
 	elif test "$action" = 'logout'; then
 		secret_signout
 	elif test "$action" = 'map'; then
+		ensure_authed
 		secret_map "${option_args[@]}"
 	elif test "$action" = 'env'; then
+		ensure_authed
 		secret_env "${option_args[@]}"
 	elif test "$action" = 'get'; then
+		ensure_authed
 		if test -n "${option_args[*]}"; then
 			secret_get "${option_args[@]}"
 		else
@@ -826,10 +828,13 @@ function secret_() (
 			cache_clear
 		fi
 	elif test "$action" = 'unmap'; then
+		ensure_authed
 		secret_unmap "${option_args[@]}"
 	elif test "$action" = 'fetch'; then
+		ensure_authed
 		secret_fetch "${option_args[@]}"
 	elif test "$action" = 'https'; then
+		ensure_authed
 		secret_https "${option_args[@]}"
 	elif test "$action" = 'help'; then
 		help
