`__print_style` support vars, `git-helper` rewrote
- `git-helper`:
    - compeltely rewritten, with the same essence, but more robust
    - deprecated `get-git-active-branch` and `get-git-default-branch`
    - fixes some weird flows
    - better message and error formatting and handling throughout

- `bash.bash:__print_without_styles`, `styles.bash:__print_style`:
    - introduce `--value=`, `--variable-value=`, and `--variable=` smart styles

- `bash.bash:__flag`:
    - support `--no-coerce`

- `bash.bash`:
    - ensure no variable conflicts by namespacing the rest of the function local variables

- `dorothy`, `choose`, `secret`, `setup-util`: `stdinargs.bash`:
    - significantly better messages

- `echo-affirmative`, `echo-non-affirmative`, `config-helper`, `debug-bash`, `echo-file`, `eval-helper`, `eval-no-color`, `fs-link`, `get-app`, `get-terminal-theme`, `get-url-upgrade`, `github-download`, `gocryptfs-helper`, `is-same`, `openssl-helper`, `setup-hosts`, `setup-util-1password`, `setup-util-vim`, `ssh-helper`, `unziptar`:
    - notably better messages

- `dorothy`, `setup-util-nvm`:
    - update for the new `git-helper`

 - `echo-verbose`:
    - now uses `__print_style --variable-value=` for consistent styling

 - `*`:
     - better help errors

diff --git a/commands/secret b/commands/secret
--- a/commands/secret
+++ b/commands/secret
@@ -251,7 +251,7 @@ function secret_() (
 			__print_string "$value" >"$state/$key" || return
 			__correct_key_permission "$state/$key" || return
 		else
-			__print_error "Attempted to write an empty secret key [$key]" || return
+			__print_error 'Attempted to write an empty secret key ' --variable-value={key} || return
 			return 1
 		fi
 	}
@@ -262,12 +262,12 @@ function secret_() (
 			if is-value -- "$value"; then
 				__print_string "$value" || return
 			else
-				__print_error "Cached secret key [$key] was empty [$value]" || return
+				__print_error 'Cached secret key ' --variable-value={key} ' was empty ' --variable-value={value} || return
 				__cache_delete "$key" || return
 				return 1
 			fi
 		else
-			__print_error "Cached secret key [$key] was missing." || return
+			__print_error 'Cached secret key ' --variable-value={key} ' was missing.' || return
 			return 1
 		fi
 	}
@@ -289,7 +289,7 @@ function secret_() (
 			for key in "$@"; do
 				__do --redirect-status={status} --redirect-stdout={value} -- __secret_get "$key" || return
 				if [[ $status -ne 0 ]]; then
-					__print_error "Unable to fetch the secret key [$key] of many." || return
+					__print_error 'Unable to fetch the secret key ' --variable-value={key} ' of many.' || return
 					return 1
 				fi
 				__print_lines "$key=$value" || return
@@ -301,7 +301,7 @@ function secret_() (
 			__split --target={secrets} --no-zero-length --invoke=try -- \
 				jq -r 'keys_unsorted[]' "$database" || return
 			if [[ ${#secrets[@]} -eq 0 ]]; then
-				__print_error 'No secrets are mapped yet, run [secret map] to map a secret.' || return
+				__print_error 'No secrets are mapped yet, run ' --code='secret map' ' to map a secret.' || return
 				return 6 # ENXIO 6 Device not configured
 			fi
 			__split --target={choices} --no-zero-length --invoke -- \
@@ -327,19 +327,16 @@ function secret_() (
 		if is-value -- "$vault" "$item" "$field"; then
 			value="$(__fetch_field "$vault" "$item" "$field")"
 		else
-			__print_error "Key [$key] was missing all three parts of its mapping:" || return
-			cat <<-EOF >&2
-				vault = [$vault]
-				item  = [$item]
-				field = [$field]
-
-				Manually edit the database [$database]
-				or use the [secret map ...] command to set the mapping accordingly.
-			EOF
+			__print_error 'Key ' --variable-value={key} ' was missing all three parts of its mapping:' --newline \
+				--variable={vault} --newline \
+				--variable={item} --newline \
+				--variable={field} --newline \
+				--newline \
+				'Manually edit the database at ' --path="$database" ' or use the ' --code='secret map ...' ' command to set the mapping accordingly.' || return
 			return 1
 		fi
 		if is-empty-value -- "$value"; then
-			__print_error "Key [$key] failed to resolve." || return
+			__print_error 'Key ' --variable-value={key} ' failed to resolve.' || return
 			return 1
 		fi
 		__cache_write "$key" "$value" || return
@@ -412,9 +409,7 @@ function secret_() (
 						op signin "$OP_SUBDOMAIN" "$email" "$key" --raw || return
 				fi
 				if [[ $status -ne 0 ]]; then
-					__print_error "Failed to sign into [$OP_SUBDOMAIN] via the email [$email] and account key [$key]." --newline \
-						"STATUS = [$status]" --newline \
-						"OP_SESSION = [$OP_SESSION]" || return
+					__print_error 'Failed to sign into ' --variable={OP_SUBDOMAIN} ' ' --variable={email} ' ' --variable={key} ' ' --variable{OP_SESSION} ' ' --status="$status" || return
 					return "$status"
 				fi
 				if [[ -n $OP_SESSION ]]; then
@@ -597,45 +592,46 @@ function secret_() (
 	}
 
 	function __item_upgrade {
-		local vault="$1" item="$2" status result
+		local vault="$1" item="$2" website status new_website
 
 		# fetch
 		__do --redirect-status={status} --redirect-stdout={website} -- __get_website "$vault" "$item" || return
 		if [[ $status -ne 0 ]]; then
-			__print_style --stderr --error="[$item] [$website] failed to fetch" || return
+			__print_style --stderr --variable={vault} ' ' --variable={item} ' ' --variable={website} ' ' --error='failed to fetch website' ' ' --status="$status" || :
 			return 1
 		fi
 		if [[ -z $website ]]; then
-			__print_style --stderr --dim="[$item] no url to upgrade" || return
+			__print_style --tty --dim --variable={vault} ' ' --variable={item} ' ' --variable={website} ' ' --bold='skipping as no website.' || return
 			return 0
 		fi
 
 		# upgrade
-		result="$(get-url-upgrade "$website" 2>/dev/null || :)" || return
-		if [[ -z $result ]]; then
-			__print_style --stderr --warning="[$item] [$website] unresponsive, consider archiving" || return
+		new_website="$(get-url-upgrade "$website" 2>/dev/null || :)" || return
+		if [[ -z $new_website ]]; then
+			__print_style --stderr --variable={vault} ' ' --variable={item} ' ' --variable={website} ' ' -error='failed to upgrade, because the website is unresponsive, consider archiving instead.' || :
 			return 1
 		fi
 
 		# check if changed
-		if [[ $result == "$website" ]]; then
-			__print_style --stderr --dim="[$item] [$website] already upgraded" || return
+		if [[ $new_website == "$website" ]]; then
+			__print_style --tty --dim --variable={vault} ' ' --variable={item} ' ' --variable={website} ' ' --success='already upgraded.' || return
 			return 0
 		fi
 
 		# log
-		__print_style --stderr --success="[$item] [$website] => [$result]" || return
+		__print_style --tty --variable={vault} ' ' --variable={item} ' ' --variable={website} --variable={new_website} ' ' --bold='applying...' || return
 
 		# apply
 		if [[ $op_version -eq 2 ]]; then
-			__try {status} -- __op_wrap item edit "$item" --vault "$vault" --url "$result" --format json >/dev/null || return
+			__try {status} -- __op_wrap item edit "$item" --vault "$vault" --url "$new_website" --format json >/dev/null || return
 		else
-			__try {status} -- __op_wrap edit item "$item" --vault "$vault" website="$result" || return
+			__try {status} -- __op_wrap edit item "$item" --vault "$vault" website="$new_website" || return
 		fi
 		if [[ $status -ne 0 ]]; then
-			__print_style --stderr --error="[$item] [$website] failed to save" || return
+			__print_style --stderr --variable={vault} ' ' --variable={item} ' ' --variable={website} ' ' --variable={new_website} ' ' --error='failed to upgrade.' ' ' --status="$status" || :
 			return 1
 		fi
+		__print_style --tty --variable={vault} ' ' --variable={item} ' ' --variable={website} --variable={new_website} ' ' --success='successfully applied.' || return
 	}
 
 	function __get_vaults {
@@ -658,13 +654,14 @@ function secret_() (
 		local last="${1-}" status vault item
 		__do --redirect-status={status} --redirect-stdout={vaults} -- __get_vaults || return
 		if [[ $status -ne 0 || -z $vaults ]]; then
-			__print_error "Failed to fetch vaults..."
+			__print_error 'Failed to fetch vaults...' || :
 			return 1
 		fi
 		for vault in $vaults; do
 			__do --redirect-status={status} --redirect-stdout={items} -- __get_items "$vault" || return
 			if [[ $status -ne 0 || -z $items ]]; then
-				__print_style --stderr --warning="Failed to fetch items for vault [$vault]" || return
+				__print_style --stderr --variable={vault} ' ' --error='failed to fetch items.' || :
+				status=1
 				continue
 			fi
 			# ignoring of status code is in case it returned a vault we don't have write access to
@@ -676,7 +673,7 @@ function secret_() (
 						last=''
 					else
 						# continue skipping
-						__print_style --stderr --dim="[$item] skipping" || return
+						__print_style --stderr --dim --variable={vault} ' ' --variable={item} ' ' --bold='skipping.' || :
 						continue
 					fi
 				fi
@@ -687,13 +684,16 @@ function secret_() (
 			done
 		done
 
+		# @todo get failure status for the jobs
 		# wait for completed jobs, then note completion
-		while [[ "$(__get_job_count)" -ne 0 ]]; do
-			__print_style --tty --notice="Waiting on [$(__get_job_count)] jobs..." || return
+		local -i count="$(__get_job_count)"
+		while [[ $count -ne 0 ]]; do
+			__print_style --tty --notice="Waiting on $count jobs..." || return
 			sleep 3
 			jobs &>/dev/null # for some reason, this seems necessary to prevent hung jobs
+			count="$(__get_job_count)"
 		done
-		__print_style --stderr --success='All done.' || return
+		__print_style --tty --success='All done.' || return
 	}
 
 	function __secret_fetch {
@@ -720,9 +720,9 @@ function secret_() (
 			--arg field "$field" \
 			'.[$secret] = [$vault, $item, $field]' \
 			"$database" | echo-write --atomic -- "$database" || return
-		__print_lines \
-			"Successfully updated [$database] so that [$secret] fetches [$vault].[$item].[$field]" \
-			"Fetching [$secret]..." >&2 || return
+		__print_style --stderr \
+			'Successfully updated ' --path="$database" ' so that ' --variable-value={secret} ' fetches ' --variable={vault} ' ' --variable={item} ' ' --variable={field} --newline \
+			'Fetching ' --variable-value={secret] '...' || return
 		__cache_delete "$secret" || return
 		__secret_get "$secret" || return
 	}
@@ -739,7 +739,7 @@ function secret_() (
 			'del(.[$secret])' \
 			"$database" | echo-write --atomic -- "$database" || return
 		__cache_delete "$secret" || return
-		__print_lines "Successfully unmapped [$secret]" >&2 || return
+		__print_style --stderr 'Successfully unmapped ' --variable-value={secret} || return
 	}
 
 	function __secret_env {
@@ -768,12 +768,10 @@ function secret_() (
 			keys=("${before[@]}")
 			args=("${after[@]}")
 		else
-			help 'env action requires [--] separator' --newline \
-				"found = $found" --newline \
-				'before =' --newline \
-				--="$(echo-verbose -- "${before[@]}")" --newline \
-				'after =' --newline \
-				--="$(echo-verbose -- "${after[@]}")" || return
+			help --code='secret env' ' requires ' --code='--' ' separator' --newline \
+				--variable={found} --newline \
+				--variable={before} --newline \
+				--variable={after} || return
 		fi
 
 		# load secrets
