convention updates

diff --git a/commands/seedbox b/commands/seedbox
--- a/commands/seedbox
+++ b/commands/seedbox
@@ -85,21 +85,23 @@ function seedbox() (
 	# =====================================
 	# Checks
 
-	# check system
+	# check for support
 	if ! is-ubuntu; then
-		echo-style --error='only for ubuntu' >/dev/stderr
-		return 1
+		echo-style --error="[$0] is implemented for Ubuntu systems..." >/dev/stderr
+		if ! confirm-negative --ppid=$$ -- 'Proceed at your own risk?'; then
+			return 1
+		fi
 	fi
 
 	# dependencies
 	if ! command-exists docker; then
-		echo-style --error="docker was not found, install it first with [setup-docker]" >/dev/stderr
+		echo-style --error="Docker not found, install it first with [setup-docker]." >/dev/stderr
 		return 1
 	fi
 
 	# check docker is working
 	eval-helper --quiet=yes -- sudo-helper -- systemctl status docker --no-pager || {
-		echo-style --error='docker not ready' >/dev/stderr
+		echo-style --error='Docker not ready.' >/dev/stderr
 		return 1
 	}
 
@@ -181,7 +183,7 @@ function seedbox() (
 		local id
 		id="$(seedbox_id || :)"
 		if test -z "$id"; then
-			echo-style --error='no seedbox present to get ip for' >/dev/stderr
+			echo-style --error='No seedbox exists to get IP address for.' >/dev/stderr
 			return 1
 		fi
 		docker exec -it "$id" curl -fsSL 'http://ipecho.net/plain'
@@ -191,7 +193,7 @@ function seedbox() (
 		# the bellow could hang if there is an issue, hence the timeout
 		mapfile -t ids < <(timeout 60s docker ps -a --filter ancestor="$image:$version" --format '{{ .ID }}' || :)
 		if test "${#ids[@]}" -eq 0; then
-			echo-style --error='no seedbox present to get id for' >/dev/stderr
+			echo-style --error='No seedbox exists to get identifer for.' >/dev/stderr
 			return 1
 		fi
 		choose-option --required \
@@ -202,7 +204,7 @@ function seedbox() (
 		local id
 		id="$(seedbox_id || :)"
 		if test -z "$id"; then
-			echo-style --error='no seedbox present to get debug for' >/dev/stderr
+			echo-style --error='No seedbox exists to get debug information for.' >/dev/stderr
 			return 1
 		fi
 		docker exec -it "$id" sh -c "$(cat "$DOROTHY/commands/debug-network")"
@@ -211,7 +213,7 @@ function seedbox() (
 		local id
 		id="$(seedbox_id || :)"
 		if test -z "$id"; then
-			echo-style --error='no seedbox present to get logs for' >/dev/stderr
+			echo-style --error='No seedbox exists to get logs for.' >/dev/stderr
 			return 1
 		fi
 		docker logs "$id" "$@"
@@ -223,7 +225,7 @@ function seedbox() (
 		local id localip hostip seedboxip details
 		id="$(seedbox_id || :)"
 		if test -z "$id"; then
-			echo-style --error='no seedbox present to get status for' >/dev/stderr
+			echo-style --error='No seedbox exits to get status for.' >/dev/stderr
 			return 1
 		fi
 		localip="$(what-is-my-ip local)"
@@ -235,11 +237,11 @@ function seedbox() (
 			"seedbox url  =  http://$localip:$SEEDBOX_PORT"
 		)
 		if test "$hostip" != "$seedboxip"; then
-			echo-style --success='seedbox is running correctly'
+			echo-style --success='The seedbox is running correctly.'
 			echo-lines -- "${details[@]}"
 		else
 			{
-				echo-style --error='seedbox did not connect to the vpn it seems'
+				echo-style --error='The seedbox failed to connect to the VPN.'
 				echo-lines -- "${details[@]}"
 				echo
 				if confirm-positive --ppid=$$ -- 'Would you like to debug it?'; then
