setup-dns: note dependency requirements for new systems on linux
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/select-dns b/commands/select-dns
--- a/commands/select-dns
+++ b/commands/select-dns
@@ -216,6 +216,15 @@ if is-mac; then
 		exit 1
 	fi
 elif command-exists systemd-resolve; then
+	# check
+	if command-missing sd || command-missing rg; then
+		echo 'missing dependencies, run the following to enable DNS selection:'
+		echo 'setup-util-sd'
+		echo 'setup-util-rg'
+		exit 1
+	fi
+
+	# fetch
 	fetch_servers "$@"
 	echo "configuring dns to ${servers[*]}"
 
