select-dns: consistent stderr on dep installs, and readd support for environments that aren't running their own dns service
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/select-dns b/commands/select-dns
--- a/commands/select-dns
+++ b/commands/select-dns
@@ -225,14 +225,20 @@ elif command-exists systemd-resolve; then
 		stderr echo 'missing dependency [ripgrep], installing automatically...'
 		stderr setup-util-ripgrep
 	fi
-	if command-missing ifup || command-missing ifdown; then
+	if ! test -x /sbin/ifup -o -x /sbin/ifdown; then
 		stderr echo 'missing dependencies [ifup] [ifdown], installing automatically...'
-		sudo apt install netscript-2.4
+		stderr env APT=netscript-2.4 setup-util
 	fi
 
 	# fetch
 	fetch_servers "$@"
 	echo "configuring dns to ${servers[*]}"
+
+	# configure defaults
+	# once we have a way of accurately detecting our own `setup-dns` service is being used, we can change DNSOverTLS=true to enforce
+	# as if we are still using say the gateway's DNS, then that will fail and our system will get disconnected
+	DNSSEC='true'
+	DNSOverTLS='opportunistic'  # use `true` to enforce
 
 	# https://unix.stackexchange.com/a/334475/50703
 	# resolvectl is new way
@@ -280,7 +286,7 @@ elif command-exists systemd-resolve; then
 	# trim existing values
 	contents="$(cat /etc/systemd/resolved.conf | sd -p '^(DNS|DNSSEC|DNSOverTLS|Domains)=.+?\n' '')"
 	# add new values
-	printf "$contents\nDNS=${servers[*]}\nDNSSEC=true\nDNSOverTLS=true\nDomains=~.\n" | sudo tee /etc/systemd/resolved.conf  &>/dev/null
+	printf "$contents\nDNS=${servers[*]}\nDNSSEC=${DNSSEC}\nDNSOverTLS=${DNSOverTLS}\nDomains=~.\n" | sudo tee /etc/systemd/resolved.conf  &>/dev/null
 	# cat /etc/systemd/resolved.conf
 
 	# https://unix.stackexchange.com/a/442599/50703
@@ -316,8 +322,8 @@ elif command-exists systemd-resolve; then
 		# sudo resolvectl llmnr "$interface" false
 		# sudo resolvectl mdns "$interface" false
 		sudo resolvectl domain "$interface" '~.'
-		sudo resolvectl dnssec "$interface" true
-		sudo resolvectl dnsovertls "$interface" true
+		sudo resolvectl dnssec "$interface" "${DNSSEC}"
+		sudo resolvectl dnsovertls "$interface" "${DNSOverTLS}"
 		sudo resolvectl dns "$interface" "${servers[@]}"
 		sleep 1
 		sudo ifdown "$interface"
