set-hostname: opensuse support

diff --git a/commands/set-hostname b/commands/set-hostname
--- a/commands/set-hostname
+++ b/commands/set-hostname
@@ -85,7 +85,7 @@ function set-hostname() (
 
 	# restart the name server
 	if command-exists systemctl; then
-		sudo systemctl restart nmbd
+		sudo systemctl restart nmbd || : # fails on opensuse, but is applied right away
 	elif test -x /etc/init.d/hostname; then
 		/etc/init.d/hostname restart
 	elif test -f /etc/sysconfig/network; then
