setup-git: fallback to HTTPS is SSH is failing
- `ssh-helper test` only output failures

diff --git a/commands/setup-git b/commands/setup-git
--- a/commands/setup-git
+++ b/commands/setup-git
@@ -213,15 +213,6 @@ function setup-git() (
 		git config --global --unset gitlab.user || : # will fail if already unset
 	fi
 
-	# Protocol
-	echo-style --h2="Git Configuration: Protocol: $GIT_PROTOCOL"
-	git config --global git.protocol "$GIT_PROTOCOL"
-	if command-exists hub; then
-		git config --global hub.protocol "$GIT_PROTOCOL"
-	else
-		git config --global --unset hub.protocol || :
-	fi
-
 	# Merge Tool
 	echo-style --h2="Git Configuration: Merge/Diff Tool: $MERGE_TOOL"
 	git config --global diff.tool "$MERGE_TOOL"
@@ -353,18 +344,29 @@ function setup-git() (
 	# Authenticate with CLIs
 
 	# Must be done here, as they depend on git and ssh being correctly configured
-
 	if test -n "$GITHUB_USERNAME"; then
 		setup-util-gh --optional
-		if command-exists gh; then
-			# set the intended protocol
-			if gh config set git_protocol "$GIT_PROTOCOL"; then
-				# if this passed, then configuration writes work, if so, authenticate if not authenticated
-				if ! gh auth status &>/dev/null && confirm --negative --ppid=$$ -- "Authenticate with the GitHub CLI?"; then
-					gh auth login
-				fi
-			fi
+		if command-exists gh && ! gh auth status &>/dev/null && confirm --negative --ppid=$$ -- "Authenticate with the GitHub CLI?"; then
+			gh auth login
 		fi
+	fi
+
+	# =====================================
+	# Configure protocols now that ssh is setup
+
+	echo-style --h2="Git Configuration: Protocol: $GIT_PROTOCOL"
+	if test "$GIT_PROTOCOL" = 'ssh' && ! ssh-helper test; then
+		echo-style --notice="SSH failed, temporarily configuring for HTTPS"
+		GIT_PROTOCOL='https'
+	fi
+	git config --global git.protocol "$GIT_PROTOCOL"
+	if command-exists hub; then
+		git config --global hub.protocol "$GIT_PROTOCOL"
+	else
+		git config --global --unset hub.protocol || :
+	fi
+	if command-exists gh; then
+		gh config set git_protocol "$GIT_PROTOCOL" || : # can fail
 	fi
 
 	# if test -n "$GITLAB_USERNAME"; then
