setup-linux-fonts: don't download fonts if not needed
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/setup-linux-fonts b/commands/setup-linux-fonts
--- a/commands/setup-linux-fonts
+++ b/commands/setup-linux-fonts
@@ -36,6 +36,16 @@ function setup-linux-fonts() (
 	fi
 
 	# helpers
+	function has_font {
+		if test -f "$fonts/$2"; then
+			if confirm-negative --ppid=$$ -- "Upgrade $1?"; then
+				return 1
+			else
+				return 0
+			fi
+		fi
+		return 1
+	}
 	function get_monoid {
 		down https://cdn.rawgit.com/larsenwork/monoid/2db2d289f4e61010dd3f44e09918d9bb32fb96fd/Monoid.zip \
 			--unzip-filter='*.ttf' \
@@ -73,30 +83,38 @@ function setup-linux-fonts() (
 	function get_fonts {
 		echo-segment --h1='Install Fonts'
 
-		eval-helper --no-wrap --quiet \
-			--pending="$(echo-style --bold="Installing Monoid...")" \
-			--success="$(echo-style --success="Installed Monoid.")" \
-			--failure="$(echo-style --error="Failed to install Monoid.")" \
-			-- get_monoid
+		if ! has_font 'Monoid' 'Monoid-Regular.ttf'; then
+			eval-helper --no-wrap --quiet \
+				--pending="$(echo-style --bold="Installing Monoid...")" \
+				--success="$(echo-style --success="Installed Monoid.")" \
+				--failure="$(echo-style --error="Failed to install Monoid.")" \
+				-- get_monoid
+		fi
 
-		eval-helper --no-wrap --quiet \
-			--pending="$(echo-style --bold="Installing Source Code Pro...")" \
-			--success="$(echo-style --success="Installed Source Code Pro.")" \
-			--failure="$(echo-style --error="Failed to install Source Code Pro.")" \
-			-- get_scp
+		if ! has_font 'Source Code Pro' 'SourceCodePro-Regular.otf'; then
+			eval-helper --no-wrap --quiet \
+				--pending="$(echo-style --bold="Installing Source Code Pro...")" \
+				--success="$(echo-style --success="Installed Source Code Pro.")" \
+				--failure="$(echo-style --error="Failed to install Source Code Pro.")" \
+				-- get_scp
+		fi
 
-		eval-helper --no-wrap --quiet \
-			--pending="$(echo-style --bold="Installing Monaco...")" \
-			--success="$(echo-style --success="Installed Monaco.")" \
-			--failure="$(echo-style --error="Failed to install Monaco.")" \
-			-- get_monaco
+		if ! has_font 'Monaco' 'monaco.ttf'; then
+			eval-helper --no-wrap --quiet \
+				--pending="$(echo-style --bold="Installing Monaco...")" \
+				--success="$(echo-style --success="Installed Monaco.")" \
+				--failure="$(echo-style --error="Failed to install Monaco.")" \
+				-- get_monaco
+		fi
 
-		# this one has multiple, so we want to see details for each one
-		eval-helper --no-wrap --no-quiet \
-			--pending="$(echo-style --bold="Installing Nerd Fonts...")" \
-			--success="$(echo-style --success="Installed Nerd Fonts.")" \
-			--failure="$(echo-style --error="Failed to install Nerd Fonts.")" \
-			-- get_nerd
+		if ! has_font 'Nerd Fonts' 'Victor Mono SemiBold Nerd Font Complete.ttf'; then
+			# this one has multiple, so we want to see details for each one
+			eval-helper --no-wrap --no-quiet \
+				--pending="$(echo-style --bold="Installing Nerd Fonts...")" \
+				--success="$(echo-style --success="Installed Nerd Fonts.")" \
+				--failure="$(echo-style --error="Failed to install Nerd Fonts.")" \
+				-- get_nerd
+		fi
 
 		eval-helper --no-wrap --quiet \
 			--pending="$(echo-style --bold="Refreshing font cache...")" \
