setup-dorothy: more robust git interactions
- add `git-protocol-ensure` to try default, then ssh, then https
- move ssh testing into `ssh-test`
- update commands for trial mode

diff --git a/commands/setup-dorothy b/commands/setup-dorothy
--- a/commands/setup-dorothy
+++ b/commands/setup-dorothy
@@ -34,20 +34,25 @@ if test -d "$DOROTHY"; then
 		echo
 		echo "Updating the Dorothy installation at $DOROTHY"
 		log="$(mktemp)"
-		pushd "$DOROTHY"
-		"$DOROTHY/commands/ok" "$DOROTHY/commands/silent" git-protocol-apply origin
+		pushd "$DOROTHY" > /dev/null || exit 1
+		"$DOROTHY/commands/ok" "$DOROTHY/commands/silent" git-protocol-ensure origin
 		"$DOROTHY/commands/ok" "$DOROTHY/commands/silent" git config pull.ff only
-		git pull origin "$("$DOROTHY/commands/git-default-branch")" > "$log"
-		popd
-		cat "$log"
-		if grep "Already" < "$log"; then
+		if ! git pull origin "$("$DOROTHY/commands/git-default-branch")" > "$log" 2>&1; then
+			cat "$log"
+			echo "...Dorothy was unable to be updated, you will have to figure this out now."
+			rm "$log"
+			exit 1
+		elif grep -q "Already" < "$log"; then
 			echo "...Dorothy already updated, continuing!"
 			rm "$log"
 		else
+			cat "$log"
 			echo -e '\n\nDorothy was updated, open a new terminal and run the earlier command again...'
 			rm "$log"
 			exit 1
 		fi
+		"$DOROTHY/commands/ok" "$DOROTHY/commands/silent" git-protocol-apply origin
+		popd > /dev/null || exit 1
 	fi
 else
 	# install
@@ -82,24 +87,24 @@ if test -z "$skipUser"; then
 			echo
 			echo "Updating the Dorothy user configuration at $DOROTHY/user"
 			log="$(mktemp)"
-			pushd "$DOROTHY/user"
-			"$DOROTHY/commands/ok" "$DOROTHY/commands/silent" git-protocol-apply origin
+			pushd "$DOROTHY/user" > /dev/null || exit 1
+			"$DOROTHY/commands/ok" "$DOROTHY/commands/silent" git-protocol-ensure origin
 			"$DOROTHY/commands/ok" "$DOROTHY/commands/silent" git config pull.ff only
-			popd
-			if ! git pull origin "$("$DOROTHY/commands/git-default-branch")" > "$log"; then
+			if ! git pull origin "$("$DOROTHY/commands/git-default-branch")" > "$log" 2>&1; then
+				cat "$log"
 				echo "...Dorothy user configuration was unable to be updated, you will have to figure out why later (probably you are disconnected, or there is no remote pushes yet), continuing!"
+				rm "$log"
+			elif grep -q "Already" < "$log"; then
+				echo "...Dorothy user configuration already updated, continuing!"
 				rm "$log"
 			else
 				cat "$log"
-				if grep "Already" < "$log"; then
-					echo "...Dorothy user configuration already updated, continuing!"
-					rm "$log"
-				else
-					echo -e '\n\nDorothy user configuration was updated, open a new terminal and run the earlier command again...'
-					rm "$log"
-					exit 1
-				fi
+				echo -e '\n\nDorothy user configuration was updated, open a new terminal and run the earlier command again...'
+				rm "$log"
+				exit 1
 			fi
+			"$DOROTHY/commands/ok" "$DOROTHY/commands/silent" git-protocol-apply origin
+			popd > /dev/null || exit 1
 		fi # </skip updat?e>
 	else # </do update><install>
 		echo
@@ -161,9 +166,9 @@ if test -z "$skipUser"; then
 		if ! test -d "$DOROTHY/user"; then
 			echo "Scaffolding empty user configuration as instructured..."
 			mkdir -p "$DOROTHY/user"
-			pushd "$DOROTHY/user"
+			pushd "$DOROTHY/user" > /dev/null || exit 1
 			"$DOROTHY/commands/silent" git init
-			popd
+			popd > /dev/null || exit 1
 		fi
 
 		# create env.sh if it doesn't exist
