ci: lint

diff --git a/commands/setup-system b/commands/setup-system
--- a/commands/setup-system
+++ b/commands/setup-system
@@ -125,18 +125,18 @@ function setup_system() (
 		mkdir -p "${recreate[@]}"
 	}
 	eval_helper --shapeshifter --no-wrap \
-				--pending="$(echo-style --bold="Cleaning directory caches...")" \
-				--success="$(echo-style --success="Cleaned directory caches.")" \
-				--failure="$(echo-style --error="Failed to clean directory caches.")" \
-				-- clean_dirs
+		--pending="$(echo-style --bold="Cleaning directory caches...")" \
+		--success="$(echo-style --success="Cleaned directory caches.")" \
+		--failure="$(echo-style --error="Failed to clean directory caches.")" \
+		-- clean_dirs
 
 	# npm
 	if command-exists npm; then
 		eval_helper --shapeshifter --no-wrap \
-				--pending="$(echo-style --bold="Cleaning npm...")" \
-				--success="$(echo-style --success="Cleaned npm.")" \
-				--failure="$(echo-style --error="Failed to clean npm.")" \
-				-- nvm-env npm cache clean --force || :
+			--pending="$(echo-style --bold="Cleaning npm...")" \
+			--success="$(echo-style --success="Cleaned npm.")" \
+			--failure="$(echo-style --error="Failed to clean npm.")" \
+			-- nvm-env npm cache clean --force || :
 	fi
 
 	# operating system
