setup-* reworking to close #14
setup-*-{update|install} now either setup-mac or setup-linux, and will now ask if no action was provided what the intention was

setup-util now supports aur tooling, go, and better and more correct logging, with support for utility names in the logging, also fixed npm and pip fallbacks, and will output performance warning on slow machines

confirm-negative and confirm-positive now support newlines to be passed in their questions

fixed is-user-in-group failing in flatpak containers

setup-go now installs go

setup-python now fixes pip install, regression from last work

setup-util-* now support names, and the AUR ecosystem

log messages throughout now make use of some emojis for a nicer and clearer visual of progress

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/setup-go b/commands/setup-go
--- a/commands/setup-go
+++ b/commands/setup-go
@@ -2,16 +2,23 @@
 source "$DOROTHY/sources/essentials.sh"
 source "$DOROTHY/sources/strict.bash"
 
-# Check
-if ! command-exists go; then
-	stderr echo -e '\nsetup-go: go must be installed first, before it is able to be setup...'
-	exit
-fi
+# Install go if necessary
+echo -e "\nEnsuring go is installed..."
+env CLI=go \
+	SNAP='go' \
+	SNAP_CLASSIC='yes' \
+	BREW='go' \
+	setup-util
+
+# Reload paths
+echo -e '\nReload paths to ensure go is detected...'
+source "$DOROTHY/sources/paths.sh"
 
 # Helper
 function goinstall() {
 	for arg in "$@"; do
-		ok go get -u -v "$arg"
+		# don't fail if one of the packages fails to install
+		env NAME="go:$arg" GO="$arg" setup-util go || :
 	done
 }
 
@@ -23,21 +30,23 @@ fi
 # Check
 if is-present "${GO_INSTALL-}"; then
 	# Install extensions
-	if confirm-positive "Install go packages?"; then
+	if confirm-positive "\nInstall go packages?"; then
 		echo -e '\nInstalling go packages...'
 		goinstall "${GO_INSTALL[@]}"
-		echo '...success'
 	fi
 
 	# Update All
-	if confirm-negative "Update all go packages?"; then
-		ok go get -u -v all
+	if confirm-negative "\nUpdate all go packages?"; then
+		go get -u -v all || :
 	fi
 else
-	echo "no go packages to install, as GO_INSTALL was not found"
+	echo
+	echo "No go packages were installed as [GO_INSTALL] was empty."
 fi
 
 # Linter
-if command-exists gometalinter && confirm-negative "Complete gometalinter installation?"; then
-	ok gometalinter --install
+if command-exists gometalinter && confirm-negative "\ngometalinter was found, do you wish to install it completely?"; then
+	gometalinter --install || :
 fi
+
+echo -e "\nInstalled go successfully. ✅"
