setup-node: fix upon bad cache directory configuration

diff --git a/commands/setup-node b/commands/setup-node
--- a/commands/setup-node
+++ b/commands/setup-node
@@ -174,6 +174,19 @@ function setup-node() (
 	}
 
 	function upgrade_npm {
+		# ensure the cache is configured correctly
+		# to avoid when say a /Users/... cache config is copied to a Linux machine
+		local cache_dir
+		cache_dir="$(npm config get cache || :)"
+		if test -n "$cache_dir" -a ! -d "$cache_dir"; then
+			# try and make it
+			mkdir -p "$cache_dir" || {
+				echo-style --error="Unconfiguring the invalid cache directory:" --code="$cache_dir"
+				npm config delete cache
+			}
+		fi
+
+		# continue with the upgrade
 		echo-segment --h3='Upgrade npm'
 		echo-style --dim="Before: $(npm --version)"
 		setup-util --name='npm' --upgrade --force --quiet \
