setup-dns: fedora can take a while to verify dns

diff --git a/commands/setup-dns b/commands/setup-dns
--- a/commands/setup-dns
+++ b/commands/setup-dns
@@ -151,6 +151,44 @@ function setup-dns() (
 	# =====================================
 	# Helpers
 
+	function verify_dns_generic {
+		local attempt="${1:-1}" ec=0
+		nslookup cloudflare.com || ec="$?"
+		if test "$ec" -ne 0; then
+			echo-style --notice="DNS service failed to verify, trying again in 10 seconds."
+			sleep 10
+			attempt="$((attempt + 1))"
+			echo-style --notice="Attempt $attempt..."
+			verify_dns_generic "$attempt"
+			return "$?"
+		fi
+		return 0
+		# `dig -x cloudflare.com` times out for some reason, nslookup works though
+		# eval-helper -- what-is-listening dns
+		# open 'https://www.cloudflare.com/en-au/ssl/encrypted-sni/'
+		# open 'https://1.1.1.1/help'
+	}
+
+	function verify_dns_resolvectl {
+		local attempt="${1:-1}" ec=0
+		resolvectl query cloudflare.com --no-pager || ec="$?"
+		resolvectl status --no-pager || ec="$?"
+		resolvectl statistics --no-pager || ec="$?"
+		if test "$ec" -ne 0; then
+			echo-style --notice="DNS service failed to verify, trying again in 10 seconds."
+			sleep 10
+			attempt="$((attempt + 1))"
+			echo-style --notice="Attempt $attempt..."
+			verify_dns_resolvectl "$attempt"
+			return "$?"
+		fi
+		return 0
+		# `dig -x cloudflare.com` times out for some reason, nslookup works though
+		# eval-helper -- what-is-listening dns
+		# open 'https://www.cloudflare.com/en-au/ssl/encrypted-sni/'
+		# open 'https://1.1.1.1/help'
+	}
+
 	function check_installation {
 		local id="$1" bin="$2" exists
 		exists="$(which "$id" || :)"
@@ -831,13 +869,11 @@ function setup-dns() (
 
 			# now that it is all done, enable or disable
 			if test "$action" = 'enable'; then
-				# verify
-				resolvectl status --no-pager
-				resolvectl query cloudflare.com --no-pager
-				resolvectl statistics --no-pager
-
 				# enable
 				sudo systemctl enable --now systemd-resolved
+
+				# verify
+				verify_dns_resolvectl
 			else
 				sudo systemctl disable --now systemd-resolved
 			fi
@@ -1732,16 +1768,7 @@ EOF
 
 	# Verify DNS
 	echo-segment --h1='Verify DNS'
-	eval-helper -- nslookup cloudflare.com || {
-		echo 'trying again in 60 seconds...'
-		sleep 60
-		eval-helper -- nslookup cloudflare.com
-	}
-	# ^ `dig -x cloudflare.com` times out for some reason, nslookup works though
-
-	# eval-helper -- what-is-listening dns
-	# open 'https://www.cloudflare.com/en-au/ssl/encrypted-sni/'
-	# open 'https://1.1.1.1/help'
+	verify_dns_generic
 	echo-segment --g1='Verify DNS'
 
 	# Prompt the user which hosts they want to use
