removals of unneeded commands and sources
- `choose-basename` and `choose-expansion` were unused
- `choose-path` upgraded for `choose-option`
- `dark-mode` renamed to `macos-theme` and upgraded and fixed
- remove `splitlines.bash` and `IFS= ` as they were unnecessary: https://unix.stackexchange.com/a/676876/50703
- remove `files-to-list`, it was unused, as is simple enough
- remove `replace-inside`, it was unused, just use `sd`
- cleaned `nullglob.bash` and `globstar.bash` remaining usage
- improved `fs-absolute`,  `what-is-using`, `macos-drive`, `macos-state`, `echo-subpaths`
- added `echo-paths-and-basenames`
- rejigged `TIPS.md`
- fixed regression in `ask` from 5b6c078c1762ec9f92493ccb36ff04e597ba778a
- styled `setup-node` (progress #74)

diff --git a/commands/setup-node b/commands/setup-node
--- a/commands/setup-node
+++ b/commands/setup-node
@@ -1,87 +1,115 @@
 #!/usr/bin/env bash
+# shellcheck disable=SC2164
+source "$DOROTHY/sources/strict.bash"
 
 # setup-environment-commands provides: NVM_DIR
 if test -z "$NVM_DIR"; then
 	export NVM_DIR="$HOME/.nvm"
 fi
 
-# source "$DOROTHY/sources/strict.bash"
-# ^ nvm prevents strict from working: .nvm/nvm.sh: line 1966: TMPDIR: unbound variable
+# =====================================
+# Configuration
 
 source "$DOROTHY/sources/config.sh"
 load_dorothy_config 'setup.bash'
 # ^ provides: NODE_INSTALL
 
+# =====================================
+# Prepare
+
+echo-color $'\n' --h1="Setup Node.js ⏲"
+echo-color --dim "NVM_DIR=$NVM_DIR"
+
 # Wiping nvm, positive as we want to clear npm packages on outdated node versions
-if test -d "$NVM_DIR" && confirm-positive "\nClean NVM installation? [$NVM_DIR]"; then
-	ok rm -Rf "$NVM_DIR"
+if test -d "$NVM_DIR" && confirm-positive "Clean NVM installation? [$NVM_DIR]"; then
+	rm -Rf "$NVM_DIR"
 fi
+
+# =====================================
+# Install
 
 # Setup system node for global installs and vscode on mac
 if is-brew; then
-	echo -e '\nInstalling system node...'
-	brew reinstall node
+	echo-color --h2='Installing system node...'
+	brew install node || brew upgrade node || :
 	npm cache clean --force
 	brew cleanup
-	echo '...system node installed!'
+	echo-color --g2='...system node installed!'
 fi
 
 # Reinstalling nvm
-echo -e '\nInstalling nvm...'
-# install nvm
+echo-color --h2='Installing nvm...'
 if test -d "$NVM_DIR"; then
-	cd "$NVM_DIR" || exit 1
+	cd "$NVM_DIR"
 else
 	mkdir -p "$NVM_DIR"
-	cd "$NVM_DIR" || exit 1
+	cd "$NVM_DIR"
 	git init
-	git remote add origin https://github.com/nvm-sh/nvm.git
+	git remote add origin 'https://github.com/nvm-sh/nvm.git'
 fi
 # ensure git remote is usable
-git-protocol-ensure || exit 1
-# update
-git fetch --tags origin || exit 1
+git-protocol-ensure
+# fetch tags
+git fetch --tags origin
+# checkout latest stable tag
 # shellcheck disable=SC2006,SC2046
-git checkout "$(git describe --abbrev=0 --tags --match "v[0-9]*" "$(git rev-list --tags --max-count=1)")" || exit 1
-# load nvm
-source "$DOROTHY/sources/nvm.sh"
-echo '...nvm installed!'
+git checkout "$(git describe --abbrev=0 --tags --match "v[0-9]*" "$(git rev-list --tags --max-count=1)")"
+# log
+echo-color --g2='...nvm installed!'
 
-echo -e '\nInstalling nvm node versions...'
-nvm install node || exit 1       # latest active
-nvm-2596 install --lts || exit 1 # latest LTS
-echo '...nvm node versions installed!'
+# nvm node
+{
+	# install nvm
+	echo-color --h2='Installing nvm node versions...'
+	source "$DOROTHY/sources/nvm.sh"
+	nvm install node       # latest active
+	nvm-2596 install --lts # latest LTS
+	echo-color --g2='...nvm node versions installed!'
 
-echo -e '\nConfiguring default node version...'
-if is-brew; then
-	nvm alias default system
-else
-	# use latest lts
-	nvm alias default stable
-	# use current lts: "$(nvm version-remote --lts)"
-fi
-nvm use default
-echo '...success!'
+	# default node version
+	echo-color --h2='Configuring nvm default node version...'
+	if is-brew; then
+		nvm alias default system
+	else
+		# use latest lts
+		nvm alias default stable
+		# use current lts: "$(nvm version-remote --lts)"
+	fi
+	nvm use default
+	echo-color --g2='...configured nvm default node version!'
+} || {
+	echo-color --e2='...nvm failed!'
+	exit 1
+}
 
-echo -e '\nUpgrading npm...'
+# npm
+echo-color --h2='Upgrading npm...'
 npm install -g npm --force
-echo '...upgraded npm!'
+echo-color --g2='...upgraded npm!'
+
+# configure
+echo-color --h2='Configuring npm...'
+npm config set init.author.name "$(ask --question="What is your name that you want to configure npm with?" --default="$(npm config get init.author.name)" --required --confirm)"
+npm config set init.author.email "$(ask --question="What is your email that you want to configure npm with?" --default="$(npm config get init.author.email)" --required --confirm)"
+npm config set init.author.url "$(ask --question="What is your homepage that you want to configure npm with?" --default="$(npm config get init.author.url)" --required --confirm)"
+npm config set init.license "$(ask --question="What license do you want to configure npm to default to?" --default="$(npm config get init.license)" --required --confirm)"
+echo-color --g2='...configured npm!'
 
 # https://github.com/yarnpkg/yarn/issues/2993
-function act() {
-	echo -e "\nInstalling $# global npm packages..."
+function install_npm_packages() {
+	echo-color --h2="Installing $# npm packages..."
 	env NAME="npm:$*" NPM="$*" setup-util npm
+	echo-color --g2="Installed $# npm packages."
 }
+if test -v 'NPM_INSTALL'; then
+	install_npm_packages "${NPM_INSTALL[@]}"
+fi
 if test -v 'NODE_INSTALL'; then
-	act "${NODE_INSTALL[@]}"
+	install_npm_packages "${NODE_INSTALL[@]}"
 fi
 
-echo -e '\nConfiguring npm...'
-npm config set init.author.name "$(ask --question="What is the name you want to configure npm with?" --default="$(npm config get init.author.name)" --required --confirm)"
-npm config set init.author.email "$(ask --question="What is the email you want to configure npm with?" --default="$(npm config get init.author.email)" --required --confirm)"
-npm config set init.author.url "$(ask --question="What is the url you want to configure npm with?" --default="$(npm config get init.author.url)" --required --confirm)"
-npm config set init.license "$(ask --question="What license do you want to configure npm to default to?" --default="$(npm config get init.license)" --required --confirm)"
-echo '...configured npm!'
-
+# =====================================
 # Done
-echo -e '\nInstalled Node.js, its versions, and its packages successfully. ✅'
+
+echo-color --dim 'Installed Node.js, its versions, and its packages successfully.'
+echo-color --h1="Setup Node.js completed. ✅"
