WIP: reworked shell install, config, and select
dorothy:
- move shell configuration entirely to `setup-shell`, which is the correct place for it
    - this is the correct location for it, and allows shell installations and uninstallations to correct configure, deconfigure, select, and deselect themselves
- extract `fs-relocate` into its own command

echo-file, echo-wait:
- WIP

fetch:
- noramlise `wget` and `curl` variants of SIGPIPE failures into SIGPIPE failures, so the caller can act accordingly

setup-dns:
- fix help text

setup-environment-commands:
- consolidate prefix directory handling with new `add_prefix_dir` helper, which now handles all the complexities of such in a simpler and more robust way
- add `XDG_PREFIX` var
- the combination of changes here now enables building on macos without `setup-util-devel` needed

setup-git:
- add `--[no-]fallback`, `--no-extras`, and `--slim` support to support (de|re)configuration if uninstalling homebrew

setup-mac-brew:
- fix `setup-util-brew --uninstall` flow, as it may uninstall our current shell, so we should expect a crash and not do more stuff after the uninstall

setup-shell:
- handle installation, uninstallation, configuration, deconfiguration, selection and unselection, rather than just install/configure
- this prevents issues when uninstalling dorothy, uninstalling homebrew, and uninstalling a specific shell
- this guides the user through the installation process, for those who are YOLO no-RTFM users, or beginners who did RTFM but didn't understand any of it

setup-util:
- add `--configure` action to be a no-op on `--check` utilities
- rename `--check=<cmd>` to `--checker=<cmd>` such that `--[no-]check` is a boolean that makes it easier to handle, and prevents conflicts when toggling
- redid and simplied relevance algorithm
- improved verbosity when building download deps, such that debugging is easier

setup-util-bash:
- `setup-environment-commands` has been updated to support building on macos without `setup-util-devel`
- install to / uninstall from `XDG_PREFIX` when building
- simpler prompt for changing login shell if outdated bash
- update the build flags to include what bash reocmmends

setup-util-brew:
- fix uninstallation, fix `setup-dns` deconfiguration, fix `setup-git` deconfiguration

setup-util-(gawk|gsed):
- fix building, based on learnings from setup-util-bash

setup-util-nu:
- configure on other invokations than just install, but correctly document configuration can only occur if nu exists

setup-util-zsh:
- use the new `fs-relocate` command to ensure zsh configuration is in the correct location

bash.bash:
- add new helpers `__ignore_exit_status` and `__ignore_sigpipe`

stdinargs.bash:
- fix oudated comments explaining sigpipe and timeout handling

todo:
- [ ] echo-file, echo-wait reworking
- [ ] config-helper auto-escalation
- [ ] setup-util-$shell: call `setup-shell` when uninstalling, or on installation if non-quiet
- [ ] setup-util-brew: uninstall: the login shell handling in this is added, but is nonsensical, fix it to run `setup-shell --no-brew`
- [ ] ensure `setup-util "$@" --check` is updated for the new syntax

diff --git a/commands/setup-environment-commands b/commands/setup-environment-commands
--- a/commands/setup-environment-commands
+++ b/commands/setup-environment-commands
@@ -106,11 +106,12 @@ STATE_DIR='/var/local/state'
 # https://wiki.archlinux.org/title/XDG_Base_Directory
 # https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
 # XDG_RUNTIME_DIR is a special directory and variable created by the system
+export XDG_PREFIX="${XDG_PREFIX:-"$HOME/.local"}"
 export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"$HOME/.config"}"
 export XDG_CACHE_HOME="${XDG_CACHE_HOME:-"$HOME/.cache"}"
-export XDG_BIN_HOME="${XDG_BIN_HOME:-"$HOME/.local/bin"}"
-export XDG_DATA_HOME="${XDG_DATA_HOME:-"$HOME/.local/share"}"
-export XDG_STATE_HOME="${XDG_STATE_HOME:-"$HOME/.local/state"}"
+export XDG_BIN_HOME="${XDG_BIN_HOME:-"$XDG_PREFIX/bin"}"
+export XDG_DATA_HOME="${XDG_DATA_HOME:-"$XDG_PREFIX/share"}"
+export XDG_STATE_HOME="${XDG_STATE_HOME:-"$XDG_PREFIX/state"}"
 # ^ if these are already defined, not to worry, `env.bash` will tidy up duplicates
 __mkdirp "$XDG_CONFIG_HOME" "$XDG_CACHE_HOME" "$XDG_BIN_HOME" "$XDG_DATA_HOME" "$XDG_STATE_HOME"
 
@@ -125,6 +126,47 @@ export MANPATH="${MANPATH-}" INFOPATH="${INFOPATH-}" CLASSPATH="${CLASSPATH-}" P
 
 # local vars
 p=''
+
+# =====================================
+# Helpers
+
+# PATH, LDFLAGS, CPPFLAGS, PKG_CONFIG_PATH
+function add_prefix_dir {
+	local p="$1"
+	if [[ -n $p && -d $p ]]; then
+		# for invokers to discover it
+		if [[ -d "$p/bin" ]]; then
+			PATH="$p/bin:$PATH"
+		fi
+		# for invokers under root to discover it
+		if [[ $USER == 'root' && -d "$p/sbin" ]]; then
+			PATH="$p/sbin:$PATH"
+		fi
+		# for compilers to discover it
+		if [[ -d "$p/lib" ]]; then
+			LDFLAGS="-L$p/lib $LDFLAGS"
+			# for pkg-config to discover it
+			if [[ -d "$p/lib/pkgconfig" ]]; then
+				PKG_CONFIG_PATH="$p/lib/pkgconfig:$PKG_CONFIG_PATH"
+			fi
+		fi
+		if [[ -d "$p/include" ]]; then
+			CPPFLAGS="-I$p/include $CPPFLAGS"
+		fi
+		# man and share/man
+		if [[ -d "$p/man" ]]; then
+			MANPATH="$p/man:$MANPATH"
+		fi
+		if [[ -d "$p/share" ]]; then
+			if [[ -d "$p/share/man" ]]; then
+				MANPATH="$p/share/man:$MANPATH"
+			fi
+			if [[ -d "$p/share/info" ]]; then
+				INFOPATH="$p/share/info:$INFOPATH"
+			fi
+		fi
+	fi
+}
 
 # =====================================
 # Configuration
@@ -144,6 +186,14 @@ load_dorothy_config 'environment.bash'
 # =====================================
 # Environment
 
+# Should we prefer XDG?
+export PREFER_XDG
+if [[ $DOROTHY == "$HOME/.dorothy" ]]; then
+	PREFER_XDG='no'
+else
+	PREFER_XDG='yes'
+fi
+
 # XDG compiled properties
 export XDG_DATA_DIRS="${XDG_DATA_DIRS:-"$XDG_DATA_HOME:/usr/local/share:/usr/share"}"
 export XDG_CONFIG_DIRS="${XDG_CONFIG_DIRS:-"$XDG_CONFIG_HOME:/etc/xdg"}"
@@ -156,12 +206,19 @@ if [[ -d "$XDG_DATA_HOME/flatpak/exports/share" ]]; then
 	XDG_DATA_DIRS="$XDG_DATA_HOME/flatpak/exports/share:$XDG_DATA_DIRS"
 fi
 
-# Should we prefer XDG?
-export PREFER_XDG
-if [[ $DOROTHY == "$HOME/.dorothy" ]]; then
-	PREFER_XDG='no'
-else
-	PREFER_XDG='yes'
+# Homebrew, UNIX
+add_prefix_dir /usr
+add_prefix_dir /usr/local
+
+# Zsh
+# https://zsh.sourceforge.io/Intro/intro_3.html
+export ZDOTDIR
+if [[ -z ${ZDOTDIR-} ]]; then
+	if [[ $PREFER_XDG == 'yes' ]]; then
+			ZDOTDIR="$XDG_CONFIG_HOME/zsh"
+	elif [[ $PREFER_XDG == 'no' ]]; then
+			ZDOTDIR="$HOME"
+	fi
 fi
 
 # GnuPG
@@ -185,25 +242,20 @@ fi
 # Xcode
 # if [[ -x '/usr/bin/xcode-select' && -x '/usr/bin/xcrun' ]]; then
 if __command_exists -- 'xcode-select' 'xcrun'; then
-	#p='/Applications/Xcode.app/Contents/Developer'
-	p="$(xcode-select --print-path 2>/dev/null || :)"
-
 	# Apple Command Line Tools
-	if [[ -d '/Library/Developer/CommandLineTools/usr/bin' ]]; then
-		PATH="/Library/Developer/CommandLineTools/usr/bin:$PATH"
-	fi
+	add_prefix_dir '/Library/Developer/CommandLineTools/usr'
 
 	# Xcode Command Line Tools
-	if [[ -d "$p/usr/bin" ]]; then
-		PATH="$p/usr/bin:$PATH"
-	fi
+	#p='/Applications/Xcode.app/Contents/Developer'
+	p="$(xcode-select --print-path 2>/dev/null || :)"
+	add_prefix_dir "$p/usr"
 
 	# Xcode Toolchain
-	p="$p/Toolchains/XcodeDefault.xctoolchain/usr/bin"
-	if [[ -d $p ]]; then
-		PATH="$p:$PATH"
-		#CC="$p/clang"
-		#CXX="$p/clang++"
+	p="$p/Toolchains/XcodeDefault.xctoolchain"
+	add_prefix_dir "$p/usr"
+	if [[ -d "$p/usr/bin" ]]; then
+		#CC="$p/usr/bin/clang"
+		#CXX="$p/usr/bin/clang++"
 		CC="$(xcrun --find clang 2>/dev/null || :)"
 		CXX="$(xcrun --find clang++ 2>/dev/null || :)"
 	fi
@@ -212,12 +264,9 @@ if __command_exists -- 'xcode-select' 'xcrun'; then
 	# /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk => $p/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk => xcrun --sdk macosx --show-sdk-path
 	#p='/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
 	p="$(xcrun --sdk macosx --show-sdk-path 2>/dev/null || :)"
+	add_prefix_dir "$p/usr"
 	if [[ -d "$p/usr/lib" ]]; then
-		LDFLAGS="-L$p/usr/lib $LDFLAGS"
 		LIBRARY_PATH="$p/usr/lib:$LIBRARY_PATH"
-	fi
-	if [[ -d "$p/usr/include" ]]; then
-		CPPFLAGS="-I$p/usr/include $CPPFLAGS"
 	fi
 	if [[ -d "$p/System/Library/Frameworks" ]]; then
 		# https://stackoverflow.com/a/68766210
@@ -263,27 +312,7 @@ if is-wsl; then
 fi
 
 # Homebrew, UNIX
-if [[ -d '/usr/local/bin' ]]; then
-	PATH="/usr/local/bin:$PATH"
-fi
-if [[ -d '/usr/local/sbin' ]]; then
-	PATH="/usr/local/sbin:$PATH"
-fi
-if [[ -d '/usr/share/man' ]]; then
-	MANPATH="/usr/share/man:$MANPATH"
-fi
-if [[ -d '/usr/local/man' ]]; then
-	MANPATH="/usr/local/man:$MANPATH"
-fi
-if [[ -d '/usr/share/info' ]]; then
-	INFOPATH="/usr/share/info:$INFOPATH"
-fi
-if [[ -d '/usr/lib' ]]; then
-	LDFLAGS="-L/usr/lib $LDFLAGS"
-fi
-if [[ -d '/usr/lib/pkgconfig' ]]; then
-	PKG_CONFIG_PATH="/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
-fi
+add_prefix_dir /user/local
 
 # macOS
 if is-mac; then
@@ -352,45 +381,15 @@ if [[ -n ${HOMEBREW_PREFIX-} && -x "${HOMEBREW_PREFIX-}/bin/brew" ]]; then
 	fi
 
 	# for compilers to find llvm
-	if [[ -d "$HOMEBREW_PREFIX/lib" ]]; then
-		LDFLAGS="-L$HOMEBREW_PREFIX/lib $LDFLAGS"
-	fi
-	if [[ -d "$HOMEBREW_PREFIX/include" ]]; then
-		CPPFLAGS="-I$HOMEBREW_PREFIX/include $CPPFLAGS"
-	fi
-	if [[ -d "$HOMEBREW_PREFIX/lib/pkgconfig" ]]; then
-		PKG_CONFIG_PATH="$HOMEBREW_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
+	if [[ $HOMEBREW_PREFIX != '/user/local' ]]; then
+		add_prefix_dir "$HOMEBREW_PREFIX"
 	fi
 
 	# llvm
-	if [[ -d "$HOMEBREW_PREFIX/opt/llvm/bin" ]]; then
-		p="$HOMEBREW_PREFIX/opt/llvm"
-		PATH="$p/bin:$PATH"
-		# for compilers to find llvm
-		if [[ -d "$p/lib" ]]; then
-			LDFLAGS="-L$p/lib $LDFLAGS"
-		fi
-		if [[ -d "$p/include" ]]; then
-			CPPFLAGS="-I$p/include $CPPFLAGS"
-		fi
-	fi
+	add_prefix_dir "$HOMEBREW_PREFIX/opt/llvm"
 
 	# SQLite (dependency of python)
-	if [[ -d "$HOMEBREW_PREFIX/opt/sqlite/bin" ]]; then
-		p="$HOMEBREW_PREFIX/opt/sqlite"
-		PATH="$p/bin:$PATH"
-		# for compilers to find sqlite
-		if [[ -d "$p/lib" ]]; then
-			LDFLAGS="-L$p/lib $LDFLAGS"
-		fi
-		if [[ -d "$p/include" ]]; then
-			CPPFLAGS="-I$p/include $CPPFLAGS"
-		fi
-		# for pkg-config to find sqlite
-		if [[ -d "$p/lib/pkgconfig" ]]; then
-			PKG_CONFIG_PATH="$p/lib/pkgconfig $PKG_CONFIG_PATH"
-		fi
-	fi
+	add_prefix_dir "$HOMEBREW_PREFIX/opt/sqlite"
 
 	# guile (dependency of something)
 	if [[ -d "$HOMEBREW_PREFIX/share/guile" ]]; then
@@ -438,19 +437,7 @@ if [[ -n ${HOMEBREW_PREFIX-} && -x "${HOMEBREW_PREFIX-}/bin/brew" ]]; then
 			fi
 		fi
 		if [[ -n $p ]]; then
-			PATH="$p/bin:$PATH"
-			rubygems "$p/bin/gem"
-			# for compilers to find ruby
-			if [[ -d "$p/lib" ]]; then
-				LDFLAGS="-L$p/lib $LDFLAGS"
-			fi
-			if [[ -d "$p/include" ]]; then
-				CPPFLAGS="-I$p/include $CPPFLAGS"
-			fi
-			# for pkg-config to find ruby
-			if [[ -d "$p/lib/pkgconfig" ]]; then
-				PKG_CONFIG_PATH="$p/lib/pkgconfig:$PKG_CONFIG_PATH"
-			fi
+			add_prefix_dir "$p"
 		fi
 	else
 		# add them all, excluding special paths
@@ -481,32 +468,20 @@ if [[ -n ${HOMEBREW_PREFIX-} && -x "${HOMEBREW_PREFIX-}/bin/brew" ]]; then
 
 	# OpenSSL (dependency of python, gpg, and node)
 	# openssl is a symlink to whatever directory has the latest version
-	if [[ -d "$HOMEBREW_PREFIX/opt/openssl/bin" ]]; then
-		p="$HOMEBREW_PREFIX/opt/openssl"
-		PATH="$p/bin:$PATH"
-		if [[ -d "$p/lib" ]]; then
-			LDFLAGS="-L$p/lib $LDFLAGS"
-		fi
-		if [[ -d "$p/include" ]]; then
-			CPPFLAGS="-I$p/include $CPPFLAGS"
-		fi
-		if [[ -d "$p/lib/pkgconfig" ]]; then
-			PKG_CONFIG_PATH="$p/lib/pkgconfig:$PKG_CONFIG_PATH"
-		fi
-		# ^^ setup-util-gocryptfs needs this on macos big sur
-		# ```
-		# Package libcrypto was not found in the pkg-config search path.
-		# Perhaps you should add the directory containing `libcrypto.pc'
-		# to the PKG_CONFIG_PATH environment variable
-		# No package 'libcrypto' found
-		# pkg-config: exit status 1
-		# ```
-		# and
-		# ```
-		# ld: library not found for -lcrypto
-		# clang: error: linker command failed with exit code 1 (use -v to see invocation)
-		# ````
-	fi
+	add_prefix_dir "$HOMEBREW_PREFIX/opt/openssl"
+	# ^^ setup-util-gocryptfs needs this on macos big sur
+	# ```
+	# Package libcrypto was not found in the pkg-config search path.
+	# Perhaps you should add the directory containing `libcrypto.pc'
+	# to the PKG_CONFIG_PATH environment variable
+	# No package 'libcrypto' found
+	# pkg-config: exit status 1
+	# ```
+	# and
+	# ```
+	# ld: library not found for -lcrypto
+	# clang: error: linker command failed with exit code 1 (use -v to see invocation)
+	# ````
 
 	# NSS
 	if [[ -d "$HOMEBREW_PREFIX/opt/nss/bin" ]]; then
@@ -667,9 +642,9 @@ fi
 if [[ $XDG_BIN_HOME != "$HOME/.local/bin" ]]; then
 	PATH="$HOME/.local/bin:$PATH"
 fi
-
 # Generics: XDG, always add, even if not existent, in case it is created later
 PATH="$XDG_BIN_HOME:$PATH"
+add_prefix_dir "$XDG_PREFIX" # only adds directories that exist
 
 # GO LLVM
 # https://stackoverflow.com/a/58488820
diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -137,13 +137,16 @@ function setup_util() (
 			    Install all packages with this installer.
 
 			--cli=<cli>
-			    Used to check if the utility  is already installed, in this case, a CLI executable.
+			    Used to check if the utility is already installed, in this case, a CLI executable.
 
 			--app=<app>
-			    Used to check if the utility  is already installed, in this case, an application.
+			    Used to check if the utility is already installed, in this case, an application.
 
 			--font=<font>
-			    Used to check if the utility  is already installed, in this case, a font.
+			    Used to check if the utility is already installed, in this case, a font.
+
+			--checker=<command>
+			    The <command> is invoked to check if the utility is already installed. It should return [0] if installed, [1] if not installed.
 
 			--name=<name>
 			    The name to use for the utility in human readable output, such as log messages.
@@ -179,7 +182,7 @@ function setup_util() (
 			    If truthy, don't output anything that isn't an error message.
 			    If falsey, output everything.
 
-			--check | --check=<command>
+			--check | --check
 			    If used, then just check if an action is required to be performed.
 			    Returns [0] if quiet and no action is necessary.
 			    Returns [1] if an action is necessary.
@@ -188,6 +191,11 @@ function setup_util() (
 			    If used, just check if an installation or uninstallation is necessary.
 			    Returns [0] if quiet and no action is necessary.
 			    Returns [1] if an action is necessary.
+
+			--configure | --action=configure
+			    If used, then skip installation and uninstallation, and just do any [setup-util-*] configuration.
+			    Requires the [setup-util-*] command to have a [setup-util --check] call.
+			    Refer to [setup-shell], [setup-util-nu], [setup-util-zsh] for usage.
 
 			... uppercase arguments are options for our installers.
 
@@ -264,7 +272,7 @@ function setup_util() (
 	# </installer-options>
 
 	# process
-	local item option_quiet='' option_action='install' option_check='' option_installer='' option_app='' option_cli='' option_font='' option_name='' option_xdg='yes' option_sudo='no' option_confirm='no' option_optional='no' option_fallback='yes' option_upgrade='no' option_force='no' option_order=()
+	local item option_quiet='' option_action='install' option_check='' option_checker='' option_installer='' option_app='' option_cli='' option_font='' option_name='' option_xdg='yes' option_sudo='no' option_confirm='no' option_optional='no' option_fallback='yes' option_upgrade='no' option_force='no' option_order=()
 	while [[ $# -ne 0 ]]; do
 		item="$1"
 		shift
@@ -276,10 +284,12 @@ function setup_util() (
 		'--no-quiet'* | '--quiet'*)
 			option_quiet="$(get-flag-value --affirmative --fallback="$option_quiet" -- "$item")"
 			;;
+		'--no-check'* | '--check'*)
+			option_check="$(get-flag-value --affirmative --fallback="$option_check" -- "$item")"
+			;;
 		'--install') option_action='install' ;;
 		'--uninstall') option_action='uninstall' ;;
-		'--check='*) option_check="${item#*=}" ;;
-		'--check') option_check='yes' ;;
+		'--configure') option_action='configure' ;;
 		'--installed')
 			option_check='yes'
 			option_action='install'
@@ -292,6 +302,7 @@ function setup_util() (
 		'--action='*) option_action="${item#*=}" ;;
 		'--order='*) mapfile -t option_order < <(echo-split ' ' -- "${item#*=}") ;;
 		'--installer='*) option_installer="${item#*=}" ;;
+		'--checker='*) option_checker="${item#*=}" ;;
 		'--app='*) option_app="${item#*=}" ;;
 		'--cli='*) option_cli="${item#*=}" ;;
 		'--font='*) option_font="${item#*=}" ;;
@@ -430,8 +441,13 @@ function setup_util() (
 	if [[ -z $option_action ]]; then
 		option_action='install'
 	fi
-	if ! [[ $option_action =~ ^(install|uninstall|upgrade)$ ]]; then
-		help 'Invalid <action>, must be [install], [uninstall], or [upgrade].'
+	if ! [[ $option_action =~ ^(install|uninstall|upgrade|configure)$ ]]; then
+		help 'Invalid <action>, must be [install], [uninstall], [upgrade], [configure].'
+	fi
+
+	# if configure, then we don't actually need to do anything, as any action is handled by the [setup-util-*] caller
+	if [[ $option_action == 'configure' ]]; then
+		return 0
 	fi
 
 	# if uninstall, disable upgrade
@@ -440,63 +456,21 @@ function setup_util() (
 	fi
 
 	# ensure name fallback
-	if [[ -z $option_name && -n $option_app ]]; then
-		option_name="$option_app"
-	fi
-	if [[ -z $option_name && -n $option_cli ]]; then
-		option_name="$option_cli"
-	fi
-	if [[ -z $option_name && -n $option_font ]]; then
-		option_name="$option_font"
-	fi
-	if [[ -z $option_name && -n $option_installer ]]; then
-		option_name="$option_installer"
-	fi
-
-	# check if exists
-	local check_works='' app_exists='' cli_exists='' cli_working='' font_exists=''
-	if [[ -n $option_check && $option_check != 'yes' && $option_check != 'no' ]]; then
-		if command "$option_check"; then
-			if [[ -z $option_name ]]; then
-				option_name="$option_check"
-			fi
-			check_works='yes'
-		else
-			check_works='no'
-		fi
-	else
-		if [[ -n $option_app ]]; then
-			if get-app --quiet -- "$option_app"; then
-				app_exists='yes'
-			else
-				app_exists='no'
-			fi
-		fi
-		if [[ -n $option_cli ]]; then
-			if __command_exists -- "$option_cli"; then
-				cli_exists='yes'
-				if command-working --sudo="$option_sudo" -- "$option_cli"; then
-					cli_working='yes'
-				else
-					cli_working='no'
-				fi
-			else
-				cli_exists='no'
-				cli_working='no'
-			fi
-		fi
-		if [[ -n $option_font ]]; then
-			if get-font --quiet -- "$option_font"; then
-				font_exists='yes'
-			else
-				font_exists='no'
-			fi
-		fi
-	fi
-
-	# ensure name
 	if [[ -z $option_name ]]; then
-		help 'Either <name>, <cli>, <app>, <font>, <installer>, <check> must be provided.'
+		if [[ -n $option_app ]]; then
+			option_name="$option_app"
+		elif [[ -n $option_cli ]]; then
+			option_name="$option_cli"
+		elif [[ -n $option_font ]]; then
+			option_name="$option_font"
+		elif [[ -n $option_installer ]]; then
+			option_name="$option_installer"
+		elif [[ -n $option_checker ]]; then
+			option_name="$option_checker"
+		fi
+	fi
+	if [[ -z $option_name ]]; then
+		help 'Either <name>, <cli>, <app>, <font>, <installer>, <checker> must be provided.'
 	fi
 
 	# prep terminal vars
@@ -515,54 +489,106 @@ function setup_util() (
 		default_screen_buffer=''
 	fi
 
-	# check only
-	if [[ -n $option_check && $option_check != 'no' ]]; then
-		# @todo support --check for uninstall
-		if [[ $option_action == 'install' ]]; then
-			if [[ $check_works == 'yes' || $app_exists == 'yes' || $cli_working == 'yes' || $font_exists == 'yes' ]]; then
-				maybe_echo_style --good3="The [$option_name] utility is already installed. ✅" >"$terminal_device_file"
-				return 0
+	# check if exists
+	local can_validate='' is_working='' is_missing=''
+	if [[ -n $option_cli || -n $option_app || -n $option_checker || -n $option_font ]]; then
+		can_validate='yes'
+		is_working='yes'
+		is_missing='yes'
+		is_broken='no'
+		if [[ -n $option_checker ]]; then
+			if command "$option_checker"; then
+				is_missing='no'
+			else
+				is_working='no'
 			fi
 		fi
-		return 1
+		if [[ -n $option_app ]]; then
+			if get-app --quiet -- "$option_app"; then
+				is_missing='no'
+			else
+				is_working='no'
+			fi
+		fi
+		if [[ -n $option_cli ]]; then
+			if __command_exists -- "$option_cli"; then
+				is_missing='no'
+				if ! command-working --sudo="$option_sudo" -- "$option_cli"; then
+					is_working='no'
+				fi
+			else
+				is_working='no'
+			fi
+		fi
+		if [[ -n $option_font ]]; then
+			if get-font --quiet -- "$option_font"; then
+				is_missing='no'
+			else
+				is_working='no'
+			fi
+		fi
 	fi
 
-	# check for action (--check=yes/command would have already exited, as it would have above)
-	if [[ -n $option_app || -n $option_cli || -n $option_font ]]; then
-		if [[ $app_exists != 'yes' && $cli_exists != 'yes' && $font_exists != 'yes' ]]; then
-			# nothing installed
+	# check if already in desired state
+	if [[ $can_validate == 'yes' ]]; then
+		if [[ $is_missing == 'yes' ]]; then
+			# missing, nothing installed
 			if [[ $option_action == 'uninstall' ]]; then
-				# already uninstalled, so no need to uninstall
+				# nothing installed, so no need to uninstall
 				maybe_echo_style --good3="The [$option_name] utility was not found. Already uninstalled. ✅" >"$terminal_device_file"
 				# exit
 				return 0
 			fi
-			option_upgrade='no' # note that we aren't upgrading, which is used for logging
+			# nothing installed, want to install
+			if [[ $option_check == 'yes' ]]; then
+				# we are just checking if we need to act, no action is necessary
+				return 1
+			fi
+			# note that we aren't upgrading, which is used for logging
+			option_upgrade='no'
 			# perform install
 			maybe_echo_style --header3="The [$option_name] utility was not found. Installing automatically... ⏲" >"$terminal_device_file"
 		elif [[ $option_action == 'uninstall' ]]; then
-			# exists, uninstall enabled
-			option_upgrade='no' # note that we aren't upgrading, which is used for logging
+			# exists, uninstall enabled, want to uninstall
+			if [[ $option_check == 'yes' ]]; then
+				# we are just checking if we need to act, no action is necessary
+				return 1
+			fi
+			# note that we aren't upgrading, which is used for logging
+			option_upgrade='no'
 			# perform uninstall
 			maybe_echo_style --header3="The [$option_name] utility is marked for uninstall. Uninstalling... ⏲" >"$terminal_device_file"
 		elif [[ $option_upgrade == 'yes' ]]; then
-			# exists, upgrade enabled
+			# exists, upgrade enabled, want to upgrade
+			if [[ $option_check == 'yes' ]]; then
+				# we are just checking if we need to act, no action is necessary
+				return 1
+			fi
 			# perform upgrade
 			maybe_echo_style --header3="The [$option_name] utility is marked for upgrade. Upgrading... ⏲" >"$terminal_device_file"
-		elif [[ $cli_working == 'fail' ]]; then
-			# exists, not working
+		elif [[ $is_working == 'no' ]]; then
+			# exists, not working, want to fix
+			if [[ $option_check == 'yes' ]]; then
+				# we are just checking if we need to act, no action is necessary
+				return 1
+			fi
 			# perform reinstall
 			maybe_echo_style --header3="The [$option_name] utility via [$option_cli] is misbehaving. Reinstalling automatically... ⏲" >"$terminal_device_file"
-		elif [[ $option_check == 'no' ]]; then
-			# exists, don't care, proceed anyway
-			# used by setup-util-nerd-fonts to ensure we check for the correct font
-			: # do nothing
-		else
-			# exists, no upgrade, is working
-			# already installed, so no need to install again
+		elif [[ $is_working == 'yes' ]]; then
+			# exists, no upgrade, is working, no action necessary
 			maybe_echo_style --good3="The [$option_name] utility is already installed. ✅" >"$terminal_device_file"
 			return 0
+		else
+			# exists, don't care, proceed anyway
+			# used by setup-util-nerd-fonts to ensure we check for the correct font
+			if [[ $option_check == 'yes' ]]; then
+				# we are just checking if we need to act, no action is necessary
+				return 1
+			fi
 		fi
+	elif [[ $option_check == 'yes' ]]; then
+		# we are just checking if we need to act, no action is necessary
+		return 1
 	fi
 
 	# ensure order
@@ -3803,14 +3829,14 @@ function setup_util() (
 					do_the_download
 					# build uninstall
 					local build_status
-					echo-style --bold="Uninstalling built $option_name..."
+					echo-style --info1='Uninstalling the built ' --code-info1="$option_name" --info1=' in ' --code-info1="$download_directory" --info1=' ...'
 					pushd "$download_directory" &>/dev/null
 					eval_capture --statusvar=build_status -- "$build_uninstall"
 					popd &>/dev/null
 					if [[ $build_status -eq 0 ]]; then
-						echo-style --success="Uninstalled built $option_name."
+						echo-style --good1='Uninstalled the built ' --code-good1="$option_name" --good1=' in ' --code-good1="$download_directory"
 					else
-						echo-style --error="Failed to uninstall built $option_name." >/dev/stderr
+						echo-style --error1='Failed to uninstall the built ' --code-error1="$option_name" --error1=' in ' --code-error1="$download_directory" >/dev/stderr
 						return "$build_status"
 					fi
 				else
@@ -3833,13 +3859,13 @@ function setup_util() (
 		if [[ -n $build_install ]]; then
 			# build install
 			local build_status
-			echo-style --bold="Building $option_name..."
+			echo-style --info1='Building ' --code-info1="$option_name" --info1=' in ' --code-info1="$download_directory" --info1=' ...'
 			# can't do cd in a subshell as we want to capture the status
 			pushd "$download_directory" &>/dev/null
 			eval_capture --statusvar=build_status -- "$build_install"
 			popd &>/dev/null
 			if [[ $build_status -eq 0 ]]; then
-				echo-style --success="Built $option_name."
+				echo-style --good1='Built ' --code-good1="$option_name" --good1=' in ' --code-good1="$download_directory"
 			else
 				echo-style --error1='Failed to build ' --code-error1="$option_name" --error1=' in ' --code-error1="$download_directory" >/dev/stderr
 				return "$build_status"
@@ -3852,7 +3878,7 @@ function setup_util() (
 					expand-path -- "$download_directory/$build_glob"
 				)
 				if [[ ${#filtered_paths[@]} -eq 0 ]]; then
-					echo-error "No files matched the build filter [$build_glob] within [$download_directory]."
+					echo-style --error1='No files matched the build filter ' --code-error1="$build_glob" --error1=' within ' --code-error1="$download_directory" >/dev/stderr
 					fs-structure -- "$download_directory" >/dev/stderr
 					return 1
 				elif [[ ${#filtered_paths[@]} -eq 1 ]]; then
@@ -3863,7 +3889,7 @@ function setup_util() (
 						mv -fv -- "${filtered_paths[@]}" "$target_path"
 					fi
 				else
-					echo-error "Multiple files matched the build filter [$build_glob] within [$download_directory]."
+					echo-style --error1='Multiple files matched the build filter ' --code-error1="$build_glob" --error1=' within ' --code-error1="$download_directory" >/dev/stderr
 					fs-structure -- "$download_directory" >/dev/stderr
 					return 1
 				fi
