improvements to trial mode
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/setup-dorothy b/commands/setup-dorothy
--- a/commands/setup-dorothy
+++ b/commands/setup-dorothy
@@ -12,26 +12,34 @@ if test -z "${DOROTHY-}"; then
 	fi
 fi
 
+# determine intent
+if test "${1-}" = 'update'; then
+	DOROTHY_SKIP_SHELL='yes'
+fi
+
 # update or install dorothy
-echo
 if test -d "$DOROTHY"; then
-	# update
-	echo "Updating the Dorothy installation at $DOROTHY"
-	cd "$DOROTHY" || exit 1
-	log="$(mktemp)"
-	"$DOROTHY/commands/ok" "$DOROTHY/commands/silent" git-protocol-apply origin
-	git pull origin "$("$DOROTHY/commands/git-default-branch")" > "$log"
-	cat "$log"
-	if grep "Already" < "$log"; then
-		echo "...Dorothy already updated, continuing!"
-		rm "$log"
-	else
-		echo -e '\n\nDorothy was updated, open a new terminal and run the earlier command again...'
-		rm "$log"
-		exit 1
+	if test -z "${DOROTHY_SKIP_UPDATE-}"; then
+		# update
+		echo
+		echo "Updating the Dorothy installation at $DOROTHY"
+		cd "$DOROTHY" || exit 1
+		log="$(mktemp)"
+		"$DOROTHY/commands/ok" "$DOROTHY/commands/silent" git-protocol-apply origin
+		git pull origin "$("$DOROTHY/commands/git-default-branch")" > "$log"
+		cat "$log"
+		if grep "Already" < "$log"; then
+			echo "...Dorothy already updated, continuing!"
+			rm "$log"
+		else
+			echo -e '\n\nDorothy was updated, open a new terminal and run the earlier command again...'
+			rm "$log"
+			exit 1
+		fi
 	fi
 else
 	# install
+	echo
 	echo "Installing Dorothy into $DOROTHY"
 	git clone "https://github.com/bevry/dorothy.git" "$DOROTHY"
 fi
@@ -58,28 +66,31 @@ if test "$hostname" = 'ubuntu'; then
 fi
 
 # update or install user
-echo
 if test -d "$DOROTHY/user"; then
-	# update
-	echo "Updating the Dorothy user configuration at $DOROTHY/user"
-	cd "$DOROTHY/user" || exit 1
-	log="$(mktemp)"
-	"$DOROTHY/commands/ok" "$DOROTHY/commands/silent" git-protocol-apply origin
-	if ! git pull origin "$("$DOROTHY/commands/git-default-branch")" > "$log"; then
-		echo "...Dorothy user configuration was unable to be updated, you will have to figure out why later (probably you are disconnected, or there is no remote pushes yet), continuing!"
-		rm "$log"
-	else
-		cat "$log"
-		if grep "Already" < "$log"; then
-			echo "...Dorothy user configuration already updated, continuing!"
+	if test -z "${DOROTHY_SKIP_UPDATE-}"; then
+		# update
+		echo
+		echo "Updating the Dorothy user configuration at $DOROTHY/user"
+		cd "$DOROTHY/user" || exit 1
+		log="$(mktemp)"
+		"$DOROTHY/commands/ok" "$DOROTHY/commands/silent" git-protocol-apply origin
+		if ! git pull origin "$("$DOROTHY/commands/git-default-branch")" > "$log"; then
+			echo "...Dorothy user configuration was unable to be updated, you will have to figure out why later (probably you are disconnected, or there is no remote pushes yet), continuing!"
 			rm "$log"
 		else
-			echo -e '\n\nDorothy user configuration was updated, open a new terminal and run the earlier command again...'
-			rm "$log"
-			exit 1
+			cat "$log"
+			if grep "Already" < "$log"; then
+				echo "...Dorothy user configuration already updated, continuing!"
+				rm "$log"
+			else
+				echo -e '\n\nDorothy user configuration was updated, open a new terminal and run the earlier command again...'
+				rm "$log"
+				exit 1
+			fi
 		fi
 	fi
 else
+	echo
 	# check for skip
 	if test -z "${DOROTHY_SKIP_USER-}"; then
 		# install
@@ -137,7 +148,7 @@ else
 
 	# if skipped, or clone fail, then create the directory
 	if ! test -d "$DOROTHY/user"; then
-		echo "Skipping user configuration as instructured..."
+		echo "Scaffolding empty user configuration as instructured..."
 		mkdir -p "$DOROTHY/user"
 		cd "$DOROTHY/user" || exit 1
 		"$DOROTHY/commands/silent" git init
@@ -212,11 +223,7 @@ cd "$DOROTHY" || exit 1
 "$DOROTHY/commands/ok" "$DOROTHY/commands/silent" chmod -f +x ./user/commands/*  # would fail if no commands
 
 # proceed with shell cofniguration
-if test -n "${DOROTHY_SKIP_SHELL-}"; then
-	echo "Skipping shell configuration as instructured..."
-	exit
-fi
-if test "${1-}" != 'update'; then
+if test -z "${DOROTHY_SKIP_SHELL-}"; then
 	# now that dorothy is confirmed to exist, proceed with strict mode
 	source "$DOROTHY/sources/strict.bash"
 
