arm64 and x86_64 support for apple silicon
- accomodations for outdated bash
  - array, nullglob, extglob, and globstar now export a variable that can be checked for the sourcing script to fail on if necessary
  - expand-path is now split into bash and zsh implementations

- support for when all deps are installed
  - curl usage changed to `fetch` or `down` where appropriate
  - git is checked in setup-dorothy

- setup-paths-commands now ensures HOMEBREW_* env vars are set, and now operates without the need for paths to already be set
  - this will eventually mean a lot of sourcing `essentials.sh` may now be unnecessary

- as nvm now supports apple arm, we now also support falling back to x86_64 when node arm builds aren't available

- sources renamed
  - `functions.*` renamed to `history.*`
  - `getshell` renamed to `shell`

- `fs-absolute` now checks that fish exists before trying to call it

- `setup-util-gocryptfs` now `mkdir -p /usr/local/bin` in case brew isn't installed there

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/setup-dorothy b/commands/setup-dorothy
--- a/commands/setup-dorothy
+++ b/commands/setup-dorothy
@@ -4,6 +4,13 @@
 # for installation segments, be sure to use "blah" as paths have not yet been configured
 # use pushd/popd instead of cd, as this might be evaled in trial mode
 
+# dependencies
+if ! git --version > /dev/null; then
+	echo 'git is missing, please recheck the installation instructions:' > /dev/stderr
+	echo 'https://github.com/bevry/dorothy' > /dev/stderr
+	exit 1
+fi
+
 # determine directory
 if test -z "${DOROTHY-}"; then
 	# legacy compat
