`pipp` to `pip_helper` inside `setup-util`

diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -3,6 +3,7 @@
 source "$DOROTHY/sources/strict.bash"
 source "$DOROTHY/sources/arrays.bash"
 requires_array_support 'mapfile'
+source "$(which eval-collapse)"
 
 # prepare
 fallbacks=() # for package systems that could be installed
@@ -89,7 +90,7 @@ function do_brew() {
 		fi
 
 		# install, the `brew upgrade` in `setup-mac-brew` will handle upgrades
-		eval-collapse -- brew install "${args[@]}"
+		eval_collapse -- brew install "${args[@]}"
 	else
 		return 1
 	fi
@@ -129,7 +130,7 @@ function do_cask() {
 		fi
 
 		# install
-		eval-collapse -- brew install --cask "${args[@]}"
+		eval_collapse -- brew install --cask "${args[@]}"
 	else
 		# not applicable
 		return 1
@@ -154,7 +155,7 @@ function do_pacman() {
 			# -q, --quiet: show less information for query and search
 			args+=('--quiet')
 		fi
-		eval-collapse -- sudo pacman "${args[@]}" "${PACMAN}"
+		eval_collapse -- sudo pacman "${args[@]}" "${PACMAN}"
 	else
 		# not needed
 		return 1
@@ -171,7 +172,7 @@ function do_yay() {
 	# check applicabile and possible
 	if test -n "$pkg" && command-exists yay; then
 		# package case
-		eval-collapse -- yay -Sy "$pkg"
+		eval_collapse -- yay -Sy "$pkg"
 	else
 		# not needed
 		return 1
@@ -188,7 +189,7 @@ function do_paru() {
 	# check applicabile and possible
 	if test -n "$pkg" && command-exists paru; then
 		# package case
-		eval-collapse -- paru -Sy "$pkg"
+		eval_collapse -- paru -Sy "$pkg"
 	else
 		# not needed
 		return 1
@@ -205,7 +206,7 @@ function do_pakku() {
 	# check applicabile and possible
 	if test -n "$pkg" && command-exists pakku; then
 		# package case
-		eval-collapse -- pakku -Sy "$pkg"
+		eval_collapse -- pakku -Sy "$pkg"
 	else
 		# not needed
 		return 1
@@ -222,7 +223,7 @@ function do_aurutils() {
 	# check applicabile and possible
 	if test -n "$pkg" && command-exists aurutils; then
 		# package case
-		eval-collapse -- aurutils -Sy "$pkg"
+		eval_collapse -- aurutils -Sy "$pkg"
 	else
 		# not needed
 		return 1
@@ -245,7 +246,7 @@ function do_pamac() {
 		fi
 
 		# package case
-		eval-collapse -- pamac install --no-confirm "$pkg"
+		eval_collapse -- pamac install --no-confirm "$pkg"
 	else
 		# not applicable
 		return 1
@@ -272,7 +273,7 @@ function do_flatpak() {
 		fi
 
 		# package case
-		eval-collapse -- flatpak install "$repo" "$pkg"
+		eval_collapse -- flatpak install "$repo" "$pkg"
 	else
 		# not applicable
 		return 1
@@ -309,7 +310,7 @@ function do_snap() {
 		fi
 
 		# package case
-		eval-collapse -- sudo snap install "${args[@]}"
+		eval_collapse -- sudo snap install "${args[@]}"
 		# ^ needs sudo, otherwise: error: access denied (try with sudo)
 	else
 		# not applicable
@@ -352,7 +353,7 @@ function do_yum() {
 			fi
 
 			# install
-			eval-collapse -- sudo yum install -y "$pkg"
+			eval_collapse -- sudo yum install -y "$pkg"
 		fi
 	else
 		# not applicable
@@ -439,10 +440,10 @@ function do_apt() {
 
 			# ensure that the package can be found, and that it will be the latest
 			# initial installations may not have a package index yet, or it may be outdated
-			eval-collapse -- sudo apt-get update
+			eval_collapse -- sudo apt-get update
 
 			# install
-			eval-collapse -- sudo apt-get install -y --fix-broken "${args[@]}"
+			eval_collapse -- sudo apt-get install -y --fix-broken "${args[@]}"
 			# use `apt-get`, as using `apt` produces this warning on Ubuntu 20.04.3 LTS
 			# WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
 		fi
@@ -462,7 +463,7 @@ function do_apk() {
 		mapfile -t args < <(echo-split ' ' -- "$APK")
 
 		# install
-		eval-collapse -- apk add "${args[@]}"
+		eval_collapse -- apk add "${args[@]}"
 	else
 		# not needed
 		return 1
@@ -473,7 +474,7 @@ function do_apk() {
 function do_nix() {
 	# check applicable and possible
 	if test -n "${NIX-}" && command-exists nix-env; then
-		eval-collapse -- nix-env -iA "${NIX}"
+		eval_collapse -- nix-env -iA "${NIX}"
 	else
 		# not needed
 		return 1
@@ -484,7 +485,7 @@ function do_nix() {
 function do_xbps() {
 	# check applicable and possible
 	if test -n "${XBPS-}" && command-exists xbps-install; then
-		eval-collapse -- xbps-install -S "${XBPS}"
+		eval_collapse -- xbps-install -S "${XBPS}"
 	else
 		# not needed
 		return 1
@@ -495,7 +496,7 @@ function do_xbps() {
 function do_eopkg() {
 	# check applicable and possible
 	if test -n "${EOPKG-}" && command-exists eopkg; then
-		eval-collapse -- sudo eopkg it "${EOPKG}"
+		eval_collapse -- sudo eopkg it "${EOPKG}"
 	else
 		# not needed
 		return 1
@@ -520,7 +521,7 @@ function do_emerge() {
 
 		# package case
 		if test -n "${EMERGE-}"; then
-			eval-collapse -- sudo emerge -av "${EMERGE}"
+			eval_collapse -- sudo emerge -av "${EMERGE}"
 		fi
 	else
 		# not applicable
@@ -557,7 +558,7 @@ function do_dnf() {
 			fi
 
 			# install
-			eval-collapse -- sudo dnf install -y "${DNF}"
+			eval_collapse -- sudo dnf install -y "${DNF}"
 		fi
 	else
 		return 1
@@ -590,7 +591,7 @@ function do_zypper() {
 			fi
 
 			# install
-			eval-collapse -- sudo zypper install "${ZYPPER}"
+			eval_collapse -- sudo zypper install "${ZYPPER}"
 		fi
 	else
 		# not applicable
@@ -602,7 +603,7 @@ function do_zypper() {
 function do_port() {
 	# check applicable and possible
 	if test -n "${PORT-}" && command-exists port; then
-		eval-collapse -- sudo port install "${PORT}"
+		eval_collapse -- sudo port install "${PORT}"
 	else
 		# not needed
 		return 1
@@ -613,7 +614,7 @@ function do_port() {
 function do_choco() {
 	# check applicable and possible
 	if test -n "${CHOCO-}" && command-exists choco; then
-		eval-collapse -- choco install "${CHOCO}"
+		eval_collapse -- choco install "${CHOCO}"
 	else
 		# not needed
 		return 1
@@ -624,7 +625,7 @@ function do_choco() {
 function do_scoop() {
 	# check applicable and possible
 	if test -n "${SCOOP-}" && command-exists scoop; then
-		eval-collapse -- scoop install "${SCOOP}"
+		eval_collapse -- scoop install "${SCOOP}"
 	else
 		# not needed
 		return 1
@@ -635,7 +636,7 @@ function do_scoop() {
 function do_winget() {
 	# check applicable and possible
 	if test -n "${WINGET-}" && command-exists winget; then
-		eval-collapse -- winget install "${WINGET}"
+		eval_collapse -- winget install "${WINGET}"
 	else
 		# not needed
 		return 1
@@ -646,7 +647,7 @@ function do_winget() {
 function do_pkg() {
 	# check applicable and possible
 	if test -n "${PKG-}" && command-exists pkg; then
-		eval-collapse -- pkg install "${PKG}"
+		eval_collapse -- pkg install "${PKG}"
 	else
 		# not needed
 		return 1
@@ -657,7 +658,7 @@ function do_pkg() {
 function do_pkgutil() {
 	# check applicable and possible
 	if test -n "${PKGUTIL-}" && command-exists pkgutil; then
-		eval-collapse -- pkgutil -i "${PKG}"
+		eval_collapse -- pkgutil -i "${PKG}"
 	else
 		# not needed
 		return 1
@@ -668,7 +669,7 @@ function do_pkgutil() {
 function do_huber() {
 	# check applicable and possible
 	if test -n "${HUBER-}" && command-exists huber; then
-		eval-collapse -- huber install "${HUBER}"
+		eval_collapse -- huber install "${HUBER}"
 	else
 		# not needed
 		return 1
@@ -679,7 +680,7 @@ function do_huber() {
 function do_guix() {
 	# check applicable and possible
 	if test -n "${GUIX-}" && command-exists guix; then
-		eval-collapse -- guix package -i "${GUIX}"
+		eval_collapse -- guix package -i "${GUIX}"
 	else
 		# not needed
 		return 1
@@ -705,7 +706,7 @@ function do_dpkg() {
 
 		# package case
 		if test -n "${DPKG-}"; then
-			eval-collapse -- sudo dpkg --install "${DPKG}"
+			eval_collapse -- sudo dpkg --install "${DPKG}"
 		fi
 	else
 		# not applicable
@@ -717,7 +718,7 @@ function do_dpkg() {
 function do_doas() {
 	# check applicable and possible
 	if test -n "${DOAS-}" && command-exists doas; then
-		eval-collapse -- doas pkg_add "${DOAS}"
+		eval_collapse -- doas pkg_add "${DOAS}"
 	else
 		# not needed
 		return 1
@@ -728,7 +729,7 @@ function do_doas() {
 function do_pkg() {
 	# check applicable and possible
 	if test -n "${PKGADD-}" && command-exists pkg_add; then
-		eval-collapse -- pkg_add "${PKGADD}"
+		eval_collapse -- pkg_add "${PKGADD}"
 	else
 		# not needed
 		return 1
@@ -739,7 +740,7 @@ function do_pkg() {
 function do_pkgin() {
 	# check applicable and possible
 	if test -n "${PKGIN-}" && command-exists pkgin; then
-		eval-collapse -- pkgin install "${PKGIN}"
+		eval_collapse -- pkgin install "${PKGIN}"
 	else
 		# not needed
 		return 1
@@ -750,7 +751,7 @@ function do_pkgin() {
 function do_pkgman() {
 	# check applicable and possible
 	if test -n "${PKGMAN-}" && command-exists pkgman; then
-		eval-collapse -- pkgman install "${PKGMAN}"
+		eval_collapse -- pkgman install "${PKGMAN}"
 	else
 		# not needed
 		return 1
@@ -762,7 +763,7 @@ function do_stack() {
 	# check applicable and possible
 	if test -n "${STACK-}" && command-exists stack; then
 		stack update
-		eval-collapse -- stack install "${STACK}"
+		eval_collapse -- stack install "${STACK}"
 	else
 		# not needed
 		return 1
@@ -774,7 +775,7 @@ function do_cabal() {
 	# check applicable and possible
 	if test -n "${CABAL-}" && command-exists cabal; then
 		cabal update
-		eval-collapse -- cabal install "${CABAL}"
+		eval_collapse -- cabal install "${CABAL}"
 	else
 		# not needed
 		return 1
@@ -787,9 +788,9 @@ function do_conda() {
 	if test -n "${CONDA-}" && command-exists conda; then
 		# customise CONDA install based on presence of CONDA_CHANNEL
 		if test -n "${CONDA_CHANNEL-}"; then
-			eval-collapse -- conda install -c "${CONDA_CHANNEL}" "${CONDA}"
+			eval_collapse -- conda install -c "${CONDA_CHANNEL}" "${CONDA}"
 		else
-			eval-collapse -- conda install "${CONDA}"
+			eval_collapse -- conda install "${CONDA}"
 		fi
 	else
 		# not needed
@@ -824,7 +825,7 @@ function do_npm() {
 			fi
 
 			# install
-			eval-collapse -- npm install --global "${args[@]}"
+			eval_collapse -- npm install --global "${args[@]}"
 		fi
 	else
 		# not applicable
@@ -855,7 +856,7 @@ function do_go() {
 		fi
 
 		# package case
-		eval-collapse -- go install -v "$GO"
+		eval_collapse -- go install -v "$GO"
 	else
 		# not applicable
 		return 1
@@ -868,11 +869,34 @@ function do_go_fallback() {
 }
 
 # pip / Python
+function pip_helper {
+	# Use the correct [pip] executable for the user's environment, as there may be many or multiple installed, such as one for Python v2 and one for Python v3.
+	if command-exists pip; then
+		pip "$@"
+	elif python -m pip --version &>/dev/null; then
+		python -m pip "$@"
+	elif command-exists pip3; then
+		pip3 "$@"
+	elif python3 -m pip --version &>/dev/null; then
+		python -m pip "$@"
+	elif command-exists pip2; then
+		pip2 "$@"
+	elif python2 -m pip --version &>/dev/null; then
+		python -m pip "$@"
+	elif command-exists /usr/local/bin/pip; then
+		/usr/local/bin/pip "$@"
+	elif test -n "${HOMEBREW_PREFIX-}" -a -x "${HOMEBREW_PREFIX-}/bin/pip"; then
+		"${HOMEBREW_PREFIX}/bin/pip" "$@"
+	else
+		stderr echo "could not find any pip"
+		exit 1
+	fi
+}
 function do_pip() {
 	local args
 	if test -n "${PIP-}" -o -n "${PYTHON_EVAL-}"; then
 		# fallback case
-		if ! silent pipp --version; then
+		if ! pip_helper --version &>/dev/null; then
 			fallbacks+=('pip')
 			return 1
 		fi
@@ -889,7 +913,7 @@ function do_pip() {
 			mapfile -t args < <(echo-split ' ' -- "$PIP")
 
 			# install
-			eval-collapse -- pipp install --user --upgrade --force-reinstall --no-warn-script-location "${args[@]}"
+			eval_collapse -- pip_helper install --user --upgrade --force-reinstall --no-warn-script-location "${args[@]}"
 		fi
 	else
 		# not applicable
@@ -918,14 +942,14 @@ function do_pipx() {
 		mapfile -t args < <(echo-split ' ' -- "$PIPX")
 
 		# package case
-		eval-collapse -- pipx install "${args[@]}"
+		eval_collapse -- pipx install "${args[@]}"
 	else
 		# not applicable
 		return 1
 	fi
 }
 function do_pipx_fallback() {
-	if ! silent pipp --version; then
+	if ! pip_helper --version &>/dev/null; then
 		setup-python
 	fi
 	setup-util-pipx
@@ -953,11 +977,11 @@ function do_gem() {
 
 		# package case
 		if test -n "${GEM-}"; then
-			silent gem uninstall "$GEM" -axI
+			gem uninstall "$GEM" -axI &>/dev/null
 			if test -n "${GEM_VERSION-}"; then
-				eval-collapse -- gem install "$GEM" --version "$GEM_VERSION" --user-install --no-document
+				eval_collapse -- gem install "$GEM" --version "$GEM_VERSION" --user-install --no-document
 			else
-				eval-collapse -- gem install "$GEM" --user-install --no-document
+				eval_collapse -- gem install "$GEM" --user-install --no-document
 			fi
 		fi
 	else
@@ -985,7 +1009,7 @@ function do_cargo() {
 		if test "$QUIET" != 'yes'; then
 			log-performance
 		fi
-		eval-collapse -- cargo install "${CARGO}"
+		eval_collapse -- cargo install "${CARGO}"
 	else
 		# not applicable
 		return 1
@@ -1032,9 +1056,9 @@ function do_zip() {
 		# download the zip, and optionally filter it, extracting to $XDG_BIN_HOME
 		mkdir -p "$XDG_BIN_HOME"
 		if test -n "${ZIP_FILTER-}"; then
-			eval-collapse -- down-zip "$ZIP" --filter="$ZIP_FILTER" --destination="$XDG_BIN_HOME"
+			eval_collapse -- down-zip "$ZIP" --filter="$ZIP_FILTER" --destination="$XDG_BIN_HOME"
 		else
-			eval-collapse -- down-zip "$ZIP" --destination="$XDG_BIN_HOME"
+			eval_collapse -- down-zip "$ZIP" --destination="$XDG_BIN_HOME"
 		fi
 		# @todo is a chmod needed?
 	else
@@ -1049,7 +1073,7 @@ function do_cmd() {
 	if test -n "${CMD-}"; then
 		# SETUP_UTIL=yes so the cmd knows it is running inside SETUP_UTIL
 		# FORCE= so that its own dependencies aren't reinstalled
-		eval-collapse -- env SETUP_UTIL=yes FORCE= "$CMD"
+		eval_collapse -- env SETUP_UTIL=yes FORCE= "$CMD"
 	else
 		# not applicable
 		return 1
