shellformat: setup-util

diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -6,7 +6,7 @@ if test "$ARRAYS" = 'no'; then
 fi
 
 # prepare
-fallbacks=()  # for package systems that could be installed
+fallbacks=() # for package systems that could be installed
 
 # options
 CLI="${CLI:-"$(get-flag-value cli -- "$@")"}"
@@ -18,12 +18,12 @@ FORCE="${FORCE:-"$(get-flag-value force --missing=no -- "$@" | echo-affirmative)
 # check if necessary
 if test -n "$CLI"; then
 	if command-missing "$CLI"; then
-		echo "The [$NAME] utility does not appear to be installed because [$CLI] is missing. Installing automatically... ⏲" > /dev/tty
+		echo "The [$NAME] utility does not appear to be installed because [$CLI] is missing. Installing automatically... ⏲" >/dev/tty
 	elif test "$FORCE" = 'yes'; then
-		echo "The [$NAME] utility is already installed because [$CLI] is present. Forcing reinstall... ⏲" > /dev/tty
+		echo "The [$NAME] utility is already installed because [$CLI] is present. Forcing reinstall... ⏲" >/dev/tty
 	else
 		if test "$QUIET" = 'no'; then
-			echo "The [$NAME] utility is already installed because [$CLI] is present. All good. ✅" > /dev/tty
+			echo "The [$NAME] utility is already installed because [$CLI] is present. All good. ✅" >/dev/tty
 		fi
 		exit 0
 	fi
@@ -32,17 +32,17 @@ fi
 # confirm if necessary
 if test "$CONFIRM" = 'yes'; then
 	if ! confirm-positive "Do you want to install the [$NAME] utility?"; then
-		exit 2  # error exit code so that things that depend on this abort
+		exit 2 # error exit code so that things that depend on this abort
 	fi
 fi
 
 # log helpers
-function won () {
+function won() {
 	local method="$1"
-	echo "The [$NAME] utility is now installed via [$method]. ✅" > /dev/tty
+	echo "The [$NAME] utility is now installed via [$method]. ✅" >/dev/tty
 }
-function lost () {
-	echo "The [$NAME] utility was unable to be installed. ❌" > /dev/stderr
+function lost() {
+	echo "The [$NAME] utility was unable to be installed. ❌" >/dev/stderr
 	if test "$NAME" = 'unnamed'; then
 		if test "$QUIET" = 'no' && confirm-negative "Do you want to output the environment variables to determine what it was?"; then
 			env | sort
@@ -52,7 +52,7 @@ function lost () {
 }
 
 # brew / Homebrew / macOS
-function do_brew () {
+function do_brew() {
 	if test -n "${BREW-}"; then
 		if ! is-brew; then
 			if is-mac; then
@@ -61,7 +61,8 @@ function do_brew () {
 			return 1
 		fi
 		# support BREW holding multiple args
-		local args=(); mapfile -t args < <(echo-split ' ' -- "$BREW")
+		local args=()
+		mapfile -t args < <(echo-split ' ' -- "$BREW")
 		if test "$FORCE" = 'yes'; then
 			args+=('--force')
 		fi
@@ -72,14 +73,14 @@ function do_brew () {
 		return 1
 	fi
 }
-function do_brew_fallback () {
+function do_brew_fallback() {
 	setup-util-brew
 	source "$DOROTHY/sources/environment.sh"
 	do_brew "$@"
 }
 
 # brew / Homebrew Casks / macOS
-function do_cask () {
+function do_cask() {
 	if test -n "${CASK-}"; then
 		if ! is-brew; then
 			if is-mac; then
@@ -88,7 +89,8 @@ function do_cask () {
 			return 1
 		fi
 		# support CASK holding multiple args
-		local args=(); mapfile -t args < <(echo-split ' ' -- "$CASK")
+		local args=()
+		mapfile -t args < <(echo-split ' ' -- "$CASK")
 		args+=('--cask')
 		if test "$FORCE" = 'yes'; then
 			args+=('--force')
@@ -98,15 +100,14 @@ function do_cask () {
 		return 1
 	fi
 }
-function do_cask_fallback () {
+function do_cask_fallback() {
 	setup-util-brew
 	source "$DOROTHY/sources/environment.sh"
 	do_cask "$@"
 }
 
-
 # pacman / Arch Linux / Manjaro
-function do_pacman () {
+function do_pacman() {
 	if test -n "${PACMAN-}" && command-exists pacman; then
 		# -q, --quiet: show less information for query and search
 		# --needed: do not reinstall up to date packages
@@ -119,7 +120,7 @@ function do_pacman () {
 
 # yay / AUR / Arch Linux
 # https://github.com/Jguer/yay
-function do_yay () {
+function do_yay() {
 	pkg="${YAY:-"${AUR-}"}"
 	if test -n "$pkg" && command-exists yay; then
 		yay -Sy "$pkg"
@@ -130,7 +131,7 @@ function do_yay () {
 
 # paru / AUR / Arch Linux
 # https://itsfoss.com/paru-aur-helper/
-function do_paru () {
+function do_paru() {
 	pkg="${PARU:-"${AUR-}"}"
 	if test -n "$pkg" && command-exists paru; then
 		paru -Sy "$pkg"
@@ -141,7 +142,7 @@ function do_paru () {
 
 # pakku / AUR / Arch Linux
 # https://itsfoss.com/best-aur-helpers/
-function do_pakku () {
+function do_pakku() {
 	pkg="${PAKKU:-"${AUR-}"}"
 	if test -n "$pkg" && command-exists pakku; then
 		pakku -Sy "$pkg"
@@ -152,7 +153,7 @@ function do_pakku () {
 
 # aurutils / AUR / Arch Linux
 # https://itsfoss.com/best-aur-helpers/
-function do_aurutils () {
+function do_aurutils() {
 	pkg="${AURUTILS:-"${AUR-}"}"
 	if test -n "$pkg" && command-exists aurutils; then
 		aurutils -Sy "$pkg"
@@ -163,7 +164,7 @@ function do_aurutils () {
 
 # pamac / AUR / Arch Linux
 # https://itsfoss.com/best-aur-helpers/
-function do_pamac () {
+function do_pamac() {
 	pkg="${PAMAC:-"${AUR-}"}"
 	if test -n "$pkg"; then
 		if command-missing pamac; then
@@ -175,15 +176,15 @@ function do_pamac () {
 		return 1
 	fi
 }
-function do_pamac_fallback () {
+function do_pamac_fallback() {
 	setup-util-pamac
 	do_pamac "$@"
 }
 
 # flatpak / Arch Linux / Manjaro
-function do_flatpak () {
-	pkg="${FLATPAK:-"${FLATPACK-}"}"  # accomodate typo
-	repo="${FLATPAK_REPO:-"${FLATPACK_REPO:-flathub}"}"  # accomodate typo
+function do_flatpak() {
+	pkg="${FLATPAK:-"${FLATPACK-}"}"                    # accomodate typo
+	repo="${FLATPAK_REPO:-"${FLATPACK_REPO:-flathub}"}" # accomodate typo
 	if test -n "$pkg"; then
 		if command-missing flatpak; then
 			fallbacks+=('flatpak')
@@ -194,20 +195,21 @@ function do_flatpak () {
 		return 1
 	fi
 }
-function do_flatpak_fallback () {
+function do_flatpak_fallback() {
 	setup-util-flatpak
 	do_flatpak "$@"
 }
 
 # snap / Snap Craft / Ubuntu
-function do_snap () {
+function do_snap() {
 	if test -n "${SNAP-}"; then
 		if command-missing snap; then
 			fallbacks+=('snap')
 			return 1
 		fi
 		# support multiple args
-		local args=(); mapfile -t args < <(echo-split ' ' -- "$SNAP")
+		local args=()
+		mapfile -t args < <(echo-split ' ' -- "$SNAP")
 		# add `--classic` if `SNAP_CLASSIC` affirmative
 		if is-affirmative "${SNAP_CLASSIC-}"; then
 			args+=('--classic')
@@ -222,13 +224,13 @@ function do_snap () {
 		return 1
 	fi
 }
-function do_snap_fallback () {
+function do_snap_fallback() {
 	setup-util-snap
 	do_snap "$@"
 }
 
 # yum / RedHat / Fedora / CentOS / etc
-function do_yum () {
+function do_yum() {
 	if test -n "${YUM_EVAL-}" && command-exists yum; then
 		eval "${YUM_EVAL}"
 	elif test -n "${YUM-}" && command-exists yum; then
@@ -244,12 +246,13 @@ function do_yum () {
 
 # apt / Ubuntu / Debian / Linux Mint / elementary OS / etc
 # can also be used for install .deb files
-function do_apt () {
+function do_apt() {
 	if test -n "${APT_EVAL-}" && is-apt; then
 		eval "${APT_EVAL}"
 	elif test -n "${APT-}" && is-apt; then
 		# support multiple args
-		local args=(); mapfile -t args < <(echo-split ' ' -- "$APT")
+		local args=()
+		mapfile -t args < <(echo-split ' ' -- "$APT")
 		if test -n "${APT_KEY-}"; then
 			# @todo note that APT_KEY needs a rework
 			# https://blog.jak-linux.org/2021/06/20/migrating-away-apt-key/
@@ -270,10 +273,11 @@ function do_apt () {
 }
 
 # apk / Alpine Linux
-function do_apk () {
+function do_apk() {
 	if test -n "${APK-}" && command-exists apk; then
 		# support multiple args
-		local args=(); mapfile -t args < <(echo-split ' ' -- "$APK")
+		local args=()
+		mapfile -t args < <(echo-split ' ' -- "$APK")
 		apk add "${args[@]}"
 	else
 		return 1
@@ -281,7 +285,7 @@ function do_apk () {
 }
 
 # nix
-function do_nix () {
+function do_nix() {
 	if test -n "${NIX-}" && command-exists nix-env; then
 		nix-env -iA "${NIX}"
 	else
@@ -290,7 +294,7 @@ function do_nix () {
 }
 
 # xbps / Void Linux
-function do_xbps () {
+function do_xbps() {
 	if test -n "${XBPS-}" && command-exists xbps-install; then
 		xbps-install -S "${XBPS}"
 	else
@@ -299,7 +303,7 @@ function do_xbps () {
 }
 
 # eopkg / Solus
-function do_eopkg () {
+function do_eopkg() {
 	if test -n "${EOPKG-}" && command-exists eopkg; then
 		sudo eopkg it "${EOPKG}"
 	else
@@ -308,7 +312,7 @@ function do_eopkg () {
 }
 
 # emerge / GURU / Gentoo Linux
-function do_emerge () {
+function do_emerge() {
 	if test -n "${EMERGE_EVAL-}" && command-exists emerge; then
 		eval "${EMERGE_EVAL}"
 	elif test -n "${EMERGE-}" && command-exists emerge; then
@@ -319,7 +323,7 @@ function do_emerge () {
 }
 
 # dnf / COPR / Fedora / CentOS / RHEL
-function do_dnf () {
+function do_dnf() {
 	if test -n "${DNF_EVAL-}" && command-exists dnf; then
 		eval "${DNF_EVAL}"
 	elif test -n "${DNF-}" && command-exists dnf; then
@@ -336,7 +340,7 @@ function do_dnf () {
 }
 
 # zypper / openSUSE / SLES
-function do_zypper () {
+function do_zypper() {
 	# zypper needs sudo
 	if test -n "${ZYPPER_EVAL-}" && command-exists zypper; then
 		eval "${ZYPPER_EVAL}"
@@ -352,7 +356,7 @@ function do_zypper () {
 }
 
 # port / MacPorts
-function do_port () {
+function do_port() {
 	if test -n "${PORT-}" && command-exists port; then
 		sudo port install "${PORT}"
 	else
@@ -361,7 +365,7 @@ function do_port () {
 }
 
 # choco / Chocolatey / Windows
-function do_choco () {
+function do_choco() {
 	if test -n "${CHOCO-}" && command-exists choco; then
 		choco install "${CHOCO}"
 	else
@@ -370,7 +374,7 @@ function do_choco () {
 }
 
 # scoop / Windows
-function do_scoop () {
+function do_scoop() {
 	if test -n "${SCOOP-}" && command-exists scoop; then
 		scoop install "${SCOOP}"
 	else
@@ -379,7 +383,7 @@ function do_scoop () {
 }
 
 # winget / Windows Package Manager Client
-function do_winget () {
+function do_winget() {
 	if test -n "${WINGET-}" && command-exists winget; then
 		winget install "${WINGET}"
 	else
@@ -388,7 +392,7 @@ function do_winget () {
 }
 
 # pkg / FreeBSD / Termux
-function do_pkg () {
+function do_pkg() {
 	if test -n "${PKG-}" && command-exists pkg; then
 		pkg install "${PKG}"
 	else
@@ -397,7 +401,7 @@ function do_pkg () {
 }
 
 # pkgutil / Solaris 10+, Sparc and x86.
-function do_pkgutil () {
+function do_pkgutil() {
 	if test -n "${PKGUTIL-}" && command-exists pkgutil; then
 		pkgutil -i "${PKG}"
 	else
@@ -406,7 +410,7 @@ function do_pkgutil () {
 }
 
 # huber
-function do_huber () {
+function do_huber() {
 	if test -n "${HUBER-}" && command-exists huber; then
 		huber install "${HUBER}"
 	else
@@ -415,7 +419,7 @@ function do_huber () {
 }
 
 # guix
-function do_guix () {
+function do_guix() {
 	if test -n "${GUIX-}" && command-exists guix; then
 		guix package -i "${GUIX}"
 	else
@@ -425,7 +429,7 @@ function do_guix () {
 
 # dpkg / Debian / Ubuntu / Linux Mint / elementary OS / etc
 # used for installing .deb files
-function do_dpkg () {
+function do_dpkg() {
 	if command-exists dpkg; then
 		if test -n "${DPKG-}"; then
 			sudo dpkg --install "${DPKG}"
@@ -440,7 +444,7 @@ function do_dpkg () {
 }
 
 # doas / Solaris
-function do_doas () {
+function do_doas() {
 	if test -n "${DOAS-}" && command-exists doas; then
 		doas pkg_add "${DOAS}"
 	else
@@ -449,7 +453,7 @@ function do_doas () {
 }
 
 # pkg_add / OpenBSD
-function do_pkg () {
+function do_pkg() {
 	if test -n "${PKGADD-}" && command-exists pkg_add; then
 		pkg_add "${PKGADD}"
 	else
@@ -458,7 +462,7 @@ function do_pkg () {
 }
 
 # pkgin/ NetBSD
-function do_pkgin () {
+function do_pkgin() {
 	if test -n "${PKGIN-}" && command-exists pkgin; then
 		pkgin install "${PKGIN}"
 	else
@@ -467,7 +471,7 @@ function do_pkgin () {
 }
 
 # pkgman / Haiku
-function do_pkgman () {
+function do_pkgman() {
 	if test -n "${PKGMAN-}" && command-exists pkgman; then
 		pkgman install "${PKGMAN}"
 	else
@@ -476,7 +480,7 @@ function do_pkgman () {
 }
 
 # stack
-function do_stack () {
+function do_stack() {
 	if test -n "${STACK-}" && command-exists stack; then
 		stack update
 		stack install "${STACK}"
@@ -486,7 +490,7 @@ function do_stack () {
 }
 
 # cabal
-function do_cabal () {
+function do_cabal() {
 	if test -n "${CABAL-}" && command-exists cabal; then
 		cabal update
 		cabal install "${CABAL}"
@@ -496,7 +500,7 @@ function do_cabal () {
 }
 
 # conda
-function do_conda () {
+function do_conda() {
 	if test -n "${CONDA-}" && command-exists conda; then
 		if test -n "${CONDA_CHANNEL-}"; then
 			conda install -c "${CONDA_CHANNEL}" "${CONDA}"
@@ -509,14 +513,15 @@ function do_conda () {
 }
 
 # npm / Node.js
-function do_npm () {
+function do_npm() {
 	if test -n "${NPM-}"; then
 		if command-missing npm; then
 			fallbacks+=('npm')
 			return 1
 		fi
 		# support NPM holding multiple args
-		local args=(); mapfile -t args < <(echo-split ' ' -- "$NPM")
+		local args=()
+		mapfile -t args < <(echo-split ' ' -- "$NPM")
 		args+=('--global')
 		if is-affirmative "${NPM_FORCE-}"; then
 			args+=('--force')
@@ -526,16 +531,16 @@ function do_npm () {
 		return 1
 	fi
 }
-function do_npm_fallback () {
+function do_npm_fallback() {
 	setup-node
 	source "$DOROTHY/sources/environment.sh"
-	set +e  # nvm prevents strict from working: .nvm/nvm.sh: line 1966: TMPDIR: unbound variable
+	set +e # nvm prevents strict from working: .nvm/nvm.sh: line 1966: TMPDIR: unbound variable
 	source "$DOROTHY/sources/nvm.sh"
 	do_npm "$@"
 }
 
 # go
-function do_go () {
+function do_go() {
 	if test -n "${GO-}"; then
 		if command-missing go; then
 			fallbacks+=('go')
@@ -546,16 +551,17 @@ function do_go () {
 		return 1
 	fi
 }
-function do_go_fallback () {
+function do_go_fallback() {
 	setup-go
 	source "$DOROTHY/sources/environment.sh"
 	do_go "$@"
 }
 
 # pip / Python
-function do_pip () {
+function do_pip() {
 	if test -n "${PIP-}"; then
-		local args=(); mapfile -t args < <(echo-split ' ' -- "$PIP")
+		local args=()
+		mapfile -t args < <(echo-split ' ' -- "$PIP")
 		if ! silent pipp --version; then
 			fallbacks+=('pip')
 			return 1
@@ -565,16 +571,17 @@ function do_pip () {
 		return 1
 	fi
 }
-function do_pip_fallback () {
+function do_pip_fallback() {
 	setup-python
 	source "$DOROTHY/sources/environment.sh"
 	do_pip "$@"
 }
 
 # pipx / Python
-function do_pipx () {
+function do_pipx() {
 	if test -n "${PIPX-}"; then
-		local args=(); mapfile -t args < <(echo-split ' ' -- "$PIPX")
+		local args=()
+		mapfile -t args < <(echo-split ' ' -- "$PIPX")
 		if command-missing pipx; then
 			fallbacks+=('pipx')
 			return 1
@@ -584,7 +591,7 @@ function do_pipx () {
 		return 1
 	fi
 }
-function do_pipx_fallback () {
+function do_pipx_fallback() {
 	if ! silent pipp --version; then
 		setup-python
 	fi
@@ -594,7 +601,7 @@ function do_pipx_fallback () {
 }
 
 # gem / Ruby
-function do_gem () {
+function do_gem() {
 	# we use --user-install because of:
 	# https://github.com/ffi/ffi/issues/631
 	if test -n "${GEM-}"; then
@@ -612,14 +619,14 @@ function do_gem () {
 		return 1
 	fi
 }
-function do_gem_fallback () {
+function do_gem_fallback() {
 	setup-ruby
 	source "$DOROTHY/sources/environment.sh"
 	do_gem "$@"
 }
 
 # cargo / Crates.io / Rust
-function do_cargo () {
+function do_cargo() {
 	if test -n "${CARGO-}"; then
 		if command-missing cargo; then
 			fallbacks+=('cargo')
@@ -633,14 +640,14 @@ function do_cargo () {
 		return 1
 	fi
 }
-function do_cargo_fallback () {
+function do_cargo_fallback() {
 	setup-rust
 	source "$DOROTHY/sources/environment.sh"
 	do_cargo "$@"
 }
 
 # installer / Manual Installer
-function do_installer () {
+function do_installer() {
 	if test -n "${INSTALLER-}"; then
 		local f="$(mktemp)"
 		down "$INSTALLER" --destination="$f"
@@ -651,7 +658,7 @@ function do_installer () {
 }
 
 # curl / Manual Installer
-function do_curl () {
+function do_curl() {
 	if test -n "${CURL-}"; then
 		sh -c "$(fetch "$CURL")"
 	else
@@ -660,7 +667,7 @@ function do_curl () {
 }
 
 # zip / Manual Installer
-function do_zip () {
+function do_zip() {
 	if test -n "${ZIP-}"; then
 		mkdir -p "$HOME/bin"
 		if test -n "${ZIP_FILE-}"; then
@@ -753,7 +760,7 @@ fi
 # cycle through the order
 for item in "${order[@]}"; do
 	pass='y'
-	"do_${item}" > /dev/tty || pass='n'
+	"do_${item}" >/dev/tty || pass='n'
 	if test "${pass}" = 'y'; then
 		won "$item"
 		exit 0
@@ -764,7 +771,7 @@ done
 # fallback for failed packages which are missing their package system
 for item in "${fallbacks[@]}"; do
 	pass='y'
-	"do_${item}_fallback" > /dev/tty || pass='n'
+	"do_${item}_fallback" >/dev/tty || pass='n'
 	if test "${pass}" = 'y'; then
 		won "$item"
 		exit 0
