setup-utils: keep going on single util failure

diff --git a/commands/setup-utils b/commands/setup-utils
--- a/commands/setup-utils
+++ b/commands/setup-utils
@@ -87,7 +87,7 @@ function setup-utils() (
 		if test -n "$item"; then
 			cmd="setup-util-${item}"
 			if command-exists "$cmd"; then
-				"$cmd" "${args[@]}"
+				"$cmd" "${args[@]}" || : # don't fail everything if one fails
 			else
 				# can't use -EOF, as we want to print spacing
 				{
