setup-python now also installs python, better logs for setup-ruby, and setup-node

diff --git a/commands/setup-ruby b/commands/setup-ruby
--- a/commands/setup-ruby
+++ b/commands/setup-ruby
@@ -3,35 +3,45 @@ source "$DOROTHY/sources/essentials.sh"
 source "$DOROTHY/sources/strict.bash"
 
 # Install ruby if necessary
+echo -e "\nEnsuring ruby is installed..."
 brew_ruby='ruby'
 if test -n "${RUBY_VERSION-}" -a "${RUBY_VERSION-}" != 'system'; then
 	brew_ruby="ruby@${RUBY_VERSION}"
 fi
-setup-util CLI=ruby \
+env CLI=ruby \
 	APK=ruby \
 	APT='ruby-full' \
 	BREW="$brew_ruby" \
 	PACMAN=ruby \
 	setup-util
 
+# Clear caches that can conflict with paths and old installs
+# Using only the intended one, which is GEM_HOME
+echo -e "\nCleaning caches..."
+if test -d "$HOME/.gem"; then
+	echo "Cleaning: $HOME/.gem"
+	rm -Rf "$HOME/.gem"
+fi
+if test -d "$HOME/.ruby"; then
+	echo "Cleaning: $HOME/.ruby"
+	rm -Rf "$HOME/.ruby"
+fi
+if is-string "${GEM_HOME-}"; then
+	if test -d "$GEM_HOME"; then
+		echo "Cleaning: $GEM_HOME"
+		rm -Rf "$GEM_HOME"
+	fi
+	mkdir -p "$GEM_HOME"
+fi
+
 # Reload paths
+echo -e '\nReload paths to help changes be detected...'
 source "$DOROTHY/sources/paths.sh"
 
 # Check
 if ! command-exists gem; then
-	stderr echo -e '\nRuby (gem) does not seem to be installed...'
-	exit
-fi
-
-# Clean gem home
-rm -Rf "$HOME/.gem" "$HOME/.ruby"
-echo "CLEAR: $HOME/.gem $HOME/.ruby"
-
-# Clear GEM_HOME
-if is-string "${GEM_HOME-}"; then
-	echo "CLEAR: $GEM_HOME"
-	rm -Rf "$GEM_HOME"
-	mkdir -p "$GEM_HOME"
+	stderr echo -e '\nUnable to find [gem] executable, so cannot proceed... ❌'
+	exit 1
 fi
 
 # Helper
@@ -63,3 +73,5 @@ if is-present "${RUBY_INSTALL-}"; then
 	act "${RUBY_INSTALL[@]}"
 fi
 
+# Done
+echo -e '\nInstalled ruby and its gems successfully. ✅'
