setup-dorothy: better user configuration generation

diff --git a/commands/setup-dorothy b/commands/setup-dorothy
--- a/commands/setup-dorothy
+++ b/commands/setup-dorothy
@@ -69,18 +69,51 @@ else
 	fi
 	# clone
 	echo "Cloning the Dorothy user configuration into $DOROTHY/user"
-	git clone "$DOROTHY_USER_REPO" "$DOROTHY/user"
-	cd "$DOROTHY/user"
+	if ! git clone "$DOROTHY_USER_REPO" "$DOROTHY/user"; then
+		echo "The clone of the repository [$DOROTHY_USER_REPO] to [$DOROTHY/user] failed."
+		echo "Dorothy will initialise the directory as a git repository, and leave it up to you to sync it up with a remote."
+		echo
+		mkdir -p "$DOROTHY/user"
+		cd "$DOROTHY/user"
+		silent git init
+	else
+		cd "$DOROTHY/user"
+	fi
 	# seed
 	if is-missing "$DOROTHY/user/source.bash" && confirm-positive "Would you like to seed the configuration with the defaults?"; then
-		cp -v "$DOROTHY/sources/defaults.bash" "$DOROTHY/user/source.bash"
-		# shellcheck disable=SC2016
-		replace-inside "$DOROTHY/user/source.bash" \
-			'source "$DOROTHY/sources/defaults.sh"' \
-			'source "$DOROTHY/user/source.sh"'
-		cp -v "$DOROTHY/sources/defaults.sh" "$DOROTHY/user/source.sh"
-		mkdir -p "$DOROTHY/user/commands"
+		cat << EOF > "$DOROTHY/user/source.bash"
+#!/usr/bin/env bash
+
+# dorothy configuration options:
+# https://github.com/bevry/dorothy#configuration
+# https://github.com/bevry/dorothy/blob/master/sources/defaults.bash
+
+# inherit the cross-platform shell configuration
+source "\$DOROTHY/user/source.sh"
+
+EOF
+		cat << EOF > "$DOROTHY/user/source.sh"
+#!/usr/bin/env sh
+
+# dorothy configuration options:
+# https://github.com/bevry/dorothy#configuration
+# https://github.com/bevry/dorothy/blob/master/sources/defaults.sh
+
+# load my env file
+. "\$DOROTHY/user/env.sh"
+
+EOF
+		cat << EOF > "$DOROTHY/user/env.sh"
+#!/usr/bin/env sh
+
+# dorothy configuration options:
+# https://github.com/bevry/dorothy#configuration
+
+# use this file for placing things that you do not want committed to git
+
+EOF
 		printf "**/env/\n**/env.*\n**/secrets/\n" > "$DOROTHY/user/.gitignore"
+		mkdir -p "$DOROTHY/user/commands"
 	fi
 fi
 
