Better UX for `setup-mac-brew` and `setup-utils`
They now handle error conditions better.

Updates:

- `echo-color` with `{h,g,e}{2,3}` styles
- add `git-is-shallow` for determining if a repository is shallow or not
- `setup-mac-brew` now supports `HOMEBREW_TAPS`, `HOMEBREW_INSTALL_ENCODING`, and `HOMEBREW_UNINSTALL`
- `setup-mac-brew` no longer does premptive uninstalls, as this seems no longer necessary
- `setup-utils` now supports CLI arguments for what to install

Closes:

- https://github.com/bevry/dorothy/issues/67
- https://github.com/bevry/dorothy/issues/68

diff --git a/commands/setup-utils b/commands/setup-utils
--- a/commands/setup-utils
+++ b/commands/setup-utils
@@ -1,19 +1,42 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
+
+# =====================================
+# CONFIGURATION
+
 source "$DOROTHY/sources/config.sh"
 load_dorothy_config 'setup.bash'
-# ^ provides: SETUP_UTILS
-
-function act {
-	echo -e "\nSetting up $# utilities..."
-	for line in "$@"; do
-		if test -n "$line"; then
-			echo
-			setup-util-"$line"
-		fi
-	done
-}
-
-if test -v 'SETUP_UTILS'; then
-	act "${SETUP_UTILS[@]}"
+if test ! -v 'SETUP_UTILS'; then
+	SETUP_UTILS=()
 fi
+if test "$#" -ne 0; then
+	SETUP_UTILS=("$@")
+fi
+
+# =====================================
+# ACTION
+
+echo-color --h1 "Setup ${#SETUP_UTILS[@]} utilities..."
+for item in "${SETUP_UTILS[@]}"; do
+	if test -n "$item"; then
+		echo
+		cmd="setup-util-${item}"
+		if command-exists "$cmd"; then
+			"$cmd"
+		else
+			{
+				echo-color --e1="Unable to install [$item], as [$cmd] doesn't exist." $'\n' \
+					$'\n' \
+					--red="You can create the missing by running:" $'\n' \
+					$'\n' \
+					--dim="    touch $DOROTHY/user/$cmd" $'\n' \
+					--dim="    edit $DOROTHY/user/$cmd" $'\n' \
+					--dim="    open https://github.com/bevry/dorothy/discussions/73" $'\n' \
+					$'\n' \
+					--red="Once the command is created, re-run your prior command."
+				exit 1
+			} >/dev/stderr
+		fi
+	fi
+done
+echo-color --g1 "Setup ${#SETUP_UTILS[@]} utilities completed. ✅"
