*: improvements to macos update flow
- `config-helper`: use path style for paths
- `echo-subpaths`: use help styling, use coerce for boolean options
- `git-helper`: review: don't use clis for apps, the app is enough
- `setup-bin`: use help styling, remove broken symlinks
- `setup-git`: improve styles around signing
- `setup-mac-brew`, `setup.bash`: introduce `HOMEBREW_ENCODING_REINSTALL` and do not reinstall encoding unless it is `yes`

diff --git a/commands/setup-bin b/commands/setup-bin
--- a/commands/setup-bin
+++ b/commands/setup-bin
@@ -7,16 +7,13 @@ function setup_bin() (
 	# Arguments
 
 	function help {
-		cat <<-EOF >&2
+		__print_help "$@" <<-EOF || return $?
 			ABOUT:
-			For Applications you already have installed, expose their binaries to PATH by symlinks inside $(__print_style --code="$XDG_BIN_HOME").
+			For Applications you already have installed, expose their binaries to \`PATH\` by symlinks inside \`XDG_BIN_HOME\`.
 
 			USAGE:
 			setup-bin
 		EOF
-		if [[ $# -ne 0 ]]; then
-			__print_error "$@"
-		fi
 		return 22 # EINVAL 22 Invalid argument
 	}
 
@@ -100,6 +97,30 @@ function setup_bin() (
 	# Kaleidoscope
 	symlink_app 'Kaleidoscope.app' \
 		'Contents/Resources/bin/ksdiff' 'ksdiff'
+
+	# =====================================
+	# Remove broken symlinks
+
+	local bins=() bin missing=() remove=()
+	__split --target={bins} --no-zero-length --invoke -- \
+		echo-subpaths -- "$XDG_BIN_HOME"
+	for bin in "${bins[@]}"; do
+		if [[ ! -e $bin ]]; then
+			missing+=("$bin")
+		fi
+	done
+	for bin in "${missing[@]}"; do
+		if is-broken-symlink -- "$bin"; then
+			remove+=("$bin")
+		fi
+	done
+	if [[ ${#remove[@]} -ne 0 ]]; then
+		eval-helper \
+			--pending="$(__print_style --notice='Removing broken symlinks:')" \
+			--success="$(__print_style --success='Removed broken symlinks.')" \
+			--failure="$(__print_style --error='Failed to remove broken symlinks.')" \
+			-- rm -v -- "${remove[@]}" # fs-remove is too verbose
+	fi
 
 	# =====================================
 	# Permissions
