major rewrite bugfixes, remove DOROTHY_USER_HOME
- `$DOROTHY_USER_HOME` has been relegated to only being useful upon initial installation of Dorothy to customise where a potential `$DOROTHY/user` symlink will target. For all intents and purposes, `$DOROTHY/user` will exist and should be used, and `$DOROTHY_USER_HOME` should only ever be used to customise where that symlink goes in `setup-dorothy`.

- the special env handling of `setup-environment-commands` and `setup-editor-commands` now echos whatever changed, removing the need for the `env -i` workaround which did not work with a fish parent shell sending a space seperated PATH variable to a bash sub shell.

    - also did a more effecient way of deternming the var names and values

- if a configuration file is not able to be found, the failure exit code of `2` will be returned and an stderr error message

- `LC_CTYPE` now fallbacks to `$LANG`, and if no `$LANG`, then fallbacks to the usual `en_US.UTF-8`

- removed `getenv.sh` and replaced with a fish compatible option of an `ACTIVE_SHELL` environment variable setup in `init.fish` and `init.sh`

- fixed some cosmetic typos

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/setup-dorothy b/commands/setup-dorothy
--- a/commands/setup-dorothy
+++ b/commands/setup-dorothy
@@ -15,34 +15,21 @@ if ! git --version > /dev/null; then
 	exit 1
 fi
 
-# determine locations, and move old locations to new locations
+# check custom initiation (first time `setup-dorothy` run without anything configured)
 if test -z "${DOROTHY-}"; then
 	if test -n "${BDIR-}"; then
 		export DOROTHY="$BDIR"  # legacy
-	elif test -d "${XDG_DATA_HOME:-"$HOME/.local/share/dorothy"}"; then
-		export DOROTHY="${XDG_DATA_HOME:-"$HOME/.local/share/dorothy"}"
+	elif test -n "${XDG_DATA_HOME-}" -a -d "${XDG_DATA_HOME-}/dorothy"; then
+		export DOROTHY="$XDG_DATA_HOME/dorothy"
+	elif test -d "$HOME/.local/share/dorothy"; then
+		export DOROTHY="$HOME/.local/share/dorothy"
 	else
 		export DOROTHY="$HOME/.dorothy"
 	fi
 fi
-if test -z "${DOROTHY_USER_HOME-}"; then
-	if test -z "${XDG_CONFIG_HOME-}" -a -d "${XDG_CONFIG_HOME-}/dorothy"; then
-		export DOROTHY_USER_HOME="$XDG_CONFIG_HOME/dorothy"
-	elif test -d "$HOME/.config/dorothy"; then
-		export DOROTHY_USER_HOME="$HOME/.config/dorothy"
-	elif test -d "$DOROTHY/user"; then
-		export DOROTHY_USER_HOME="$DOROTHY/user"
-	else
-		export DOROTHY_USER_HOME="$HOME/.config/dorothy"
-	fi
-fi
-if test ! -d "$DOROTHY/user" -a -d "$DOROTHY_USER_HOME"; then
-	# always make the $DOROTHY/user symlink, so that our editors and terminals can easily navigate to it
-	ln -sfF "$DOROTHY_USER_HOME" "$DOROTHY/user"
-fi
 
-# ensure dorothy is accessible for this command
-export PATH="$DOROTHY_USER_HOME/commands.local:$DOROTHY_USER_HOME/commands:$DOROTHY/commands:$PATH"  # right to left is
+# ensure dorothy, and eventually user config, is accessible for this command
+export PATH="$DOROTHY/user/commands.local:$DOROTHY/user/commands:$DOROTHY/commands:$PATH"  # right to left is preference
 
 # helpers
 git_init () {
@@ -51,7 +38,7 @@ git_init () {
 	git init
 	popd > /dev/null
 }
-install_doroty () {
+install_dorothy () {
 	# check
 	if test -d "$DOROTHY"; then
 		update_dorothy
@@ -84,7 +71,7 @@ update_dorothy () {
 	fi
 }
 setup_dorothy () {
-	install_doroty  # goes to update_dorothy for us
+	install_dorothy  # goes to update_dorothy for us
 }
 setup_hostname () {
 	# check
@@ -106,16 +93,29 @@ setup_hostname () {
 	fi
 }
 install_user () {
-	# check
+	# check action
 	if test "$action" = 'trial'; then
 		return
 	fi
-	if test -d "$DOROTHY_USER_HOME"; then
+
+	# check custom initiation
+	if test ! -d "$DOROTHY/user"; then
+		if test -n "${DOROTHY_USER_HOME-}" -a -d "${DOROTHY_USER_HOME-}"; then
+			ln -sfF "$DOROTHY_USER_HOME" "$DOROTHY/user"
+		elif test -n "${XDG_CONFIG_HOME-}" -a -d "${XDG_CONFIG_HOME-}/dorothy"; then
+			ln -sfF "$XDG_CONFIG_HOME/dorothy" "$DOROTHY/user"
+		elif test -d "$HOME/.config/dorothy"; then
+			ln -sfF "$HOME/.config/dorothy" "$DOROTHY/user"
+		fi
+	fi
+
+	# check successful initiation
+	if test -d "$DOROTHY/user"; then
 		update_user
 		return "$?"
 	fi
 
-	# prepare
+	# prepare guided initiation
 	echo
 	local status='404' user repo temp init='no'
 
@@ -163,10 +163,10 @@ install_user () {
 
 	# clone if repo specified
 	if test -n "$repo"; then
-		echo "Cloning the Dorothy user configuration into $DOROTHY_USER_HOME"
-		if ! git clone "$repo" "$DOROTHY_USER_HOME"; then
+		echo "Cloning the Dorothy user configuration into $DOROTHY/user"
+		if ! git clone "$repo" "$DOROTHY/user"; then
 			init='yes'
-			echo "The clone of the repository [$repo] to [$DOROTHY_USER_HOME] failed."
+			echo "The clone of the repository [$repo] to [$DOROTHY/user] failed."
 			echo "Dorothy will initialise the directory as a git repository, and leave it up to you to sync it up with a remote."
 			echo
 		fi
@@ -176,12 +176,12 @@ install_user () {
 
 	# if skipped, or clone fail, then create the git directory
 	if test "$init" = 'yes'; then
-		git_init "$DOROTHY_USER_HOME" || exit 1
+		git_init "$DOROTHY/user" || exit 1
 	fi
 
 	# fix permissions
-	if test -d "$DOROTHY_USER_HOME/commands"; then
-		chmod -f +x "$DOROTHY_USER_HOME/commands/"*
+	if test -d "$DOROTHY/user/commands"; then
+		chmod -f +x "$DOROTHY/user/commands/"*
 	fi
 }
 update_user () {
@@ -192,10 +192,10 @@ update_user () {
 
 	# act
 	echo
-	echo "Updating the Dorothy user configuration at $DOROTHY_USER_HOME"
-	if git-update "$DOROTHY_USER_HOME" > /dev/null; then
-		if test -d "$DOROTHY_USER_HOME/commands"; then
-			chmod -f +x "$DOROTHY_USER_HOME/commands/"*
+	echo "Updating the Dorothy user configuration at $DOROTHY/user"
+	if git-update "$DOROTHY/user" > /dev/null; then
+		if test -d "$DOROTHY/user/commands"; then
+			chmod -f +x "$DOROTHY/user/commands/"*
 		fi
 	else
 		echo "...Dorothy user configuration was unable to be updated, you will have to figure this out now."
@@ -206,7 +206,7 @@ setup_user () {
 	if test "$action" = 'trial'; then
 		return
 	else
-		if test -d "$DOROTHY_USER_HOME"; then
+		if test -d "$DOROTHY/user"; then
 			update_user
 		else
 			install_user
@@ -223,14 +223,14 @@ setup_adjustments () {
 	# this is done awkardly, as we have no guarantees of being in a bash version that properly supports arrays
 	deprecated_configuration_files=''
 	for deprecated_configuration_file in \
-		"$DOROTHY_USER_HOME/source.sh" \
-		"$DOROTHY_USER_HOME/source.bash" \
-		"$DOROTHY_USER_HOME/source.zsh" \
-		"$DOROTHY_USER_HOME/source.fish" \
-		"$DOROTHY_USER_HOME/env.sh" \
-		"$DOROTHY_USER_HOME/env.bash" \
-		"$DOROTHY_USER_HOME/env.zsh" \
-		"$DOROTHY_USER_HOME/env.fish"; do
+		"$DOROTHY/user/source.sh" \
+		"$DOROTHY/user/source.bash" \
+		"$DOROTHY/user/source.zsh" \
+		"$DOROTHY/user/source.fish" \
+		"$DOROTHY/user/env.sh" \
+		"$DOROTHY/user/env.bash" \
+		"$DOROTHY/user/env.zsh" \
+		"$DOROTHY/user/env.fish"; do
 		if test -f "$deprecated_configuration_file"; then
 			deprecated_configuration_files="$deprecated_configuration_file"$'\n'"$deprecated_configuration_files"
 		fi
@@ -244,14 +244,14 @@ setup_adjustments () {
 
 	# create essential directories
 	mkdir -p \
-		"$DOROTHY_USER_HOME/commands.local" \
-		"$DOROTHY_USER_HOME/commands" \
-		"$DOROTHY_USER_HOME/config.local" \
-		"$DOROTHY_USER_HOME/config"
+		"$DOROTHY/user/commands.local" \
+		"$DOROTHY/user/commands" \
+		"$DOROTHY/user/config.local" \
+		"$DOROTHY/user/config"
 
 	# gitignore
 	config-helper \
-		--file="$DOROTHY_USER_HOME/.gitignore" \
+		--file="$DOROTHY/user/.gitignore" \
 		--find='commands.local/' --replace='commands.local/' \
 		--find='config.local/' --replace='config.local/'
 }
