better windows WSL compat

diff --git a/commands/setup-linux b/commands/setup-linux
--- a/commands/setup-linux
+++ b/commands/setup-linux
@@ -110,6 +110,9 @@ function setup-linux() (
 		sudo yum upgrade -y
 	}
 	function do_snap_upgrade {
+		if ! is-snap; then
+			return 0
+		fi
 		sudo snap refresh
 	}
 	function do_flatpak_upgrade {
@@ -161,6 +164,9 @@ function setup-linux() (
 		fi
 	}
 	function do_snap_packages {
+		if ! is-snap; then
+			return 0
+		fi
 		if test -n "${SNAP_INSTALL[*]}"; then
 			setup-util \
 				NAME="snap:${SNAP_INSTALL[*]}" \
@@ -264,7 +270,7 @@ function setup-linux() (
 	done
 
 	# setup fonts last, as it takes forever
-	setup-linux-fonts
+	setup-linux-fonts || :  # don't care for failures, as fonts are optional
 
 	# log
 	echo-segment --g1="$title"
