WIP: setup-util inlines `get-installer`
also fix help documentation

diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -147,7 +147,7 @@ function setup_util() (
 		else
 			source_options_rendered="$(__print_error --help='`deno` is required to display the source options; install it with: `setup-util-deno`' 2>&1)" || return $?
 		fi
-		__join --source={sources} --target={sources_rendered} --left='* ' --style=code --between=$'\n' || return $?
+		__join --source={sources} --target={sources_rendered} --between=', ' --style=code || return $?
 
 		# add invocation for debugging if error
 		if [[ $# -ne 0 ]]; then
@@ -184,7 +184,6 @@ function setup_util() (
 
 			OPTIONS:
 			These options determine the action to provide on the utility:
-
 			! When specifying these actions as a flag, i.e. with a preceding double dash, e.g. \`--instal\` instead of \`install\`, then it will be combined with prior enabled actions.
 			! When specifying actions as an argument, i.e. without their preceding double dash \`--\`, e.g. \`install\` instead of \`--install\`, then all other actions will be reset.
 			! Actions will be performed in their specified order.
@@ -213,8 +212,9 @@ function setup_util() (
 			    Returns [0] if quiet and no action is necessary.
 			    Returns [1] if an action is necessary.
 
-			[--][is-]installed|has [...<utility>]
-			[--][is-]uninstalled [...<utility>]
+			[--][is-]installed [--] [...<utility>]
+			[--]has [--] [...<utility>]
+			[--][is-]uninstalled [--] [...<utility>]
 			    If used, just check if an installation or uninstallation is necessary.
 			    Returns [0] if quiet and no action is necessary.
 			    Returns [1] if an action is necessary.
@@ -224,9 +224,9 @@ function setup_util() (
 			    Returns [0] if uninstall is the desired action.
 			    Returns [1] if any other action is desired.
 
-			[--]get-installations [...<utility>]
-			    Outputs a minified JSON array for existing installations. If no installations, return nothing with a failure. Discards all other actions.
-			    Theoretical non-minified output for \`setup-util-vscode get-installations\` if there are existing flatpak, cask, and desktop installations:
+			[--]get-installations [--] [...<utility>]
+			    Outputs a minified JSON array for existing installations. If no installations, return nothing with a failure exit status. Discards all other actions.
+			    Theoretical non-minified output for \`setup-util vscode get-installations\` with existing flatpak, cask, and desktop installations:
 			    \`\`\`
 			    [
 			        {"source":"flatpak","id":"com.visualstudio.code"},
@@ -235,22 +235,21 @@ function setup_util() (
 			    ]
 			    \`\`\`
 
-			[--]get-installer [<utility>]
+			[--]get-installer [--] [...<utility>]
 			    Outputs the command to install <util>.
 			    If no command, return failure status.
 
-			[--]invoke [<utility>] [-- <...arguments>]
+			[--]invoke [<utility>] [--] [<...arguments>]
 			    If enabled, invoke the <utility>.
 			    Returns the invocations exit status.
 
 			These options provide hooks:
-
 			--action-eval=<invocation>
 			    Runs the <invocation> if the action will be invoked.
 			--acted-eval=<invocation>
 			    Runs the <invocation> if the action was invoked.
 			--configure-eval=<invocation>
-			    Runs the <invocation> after the action, if <configure>> is true.
+			    Runs the <invocation> after the action, if <configure> is true.
 
 			These options specify and customise our interaction with the utility:
 
@@ -269,9 +268,21 @@ function setup_util() (
 			    Specify whether the utility requires elevation. Forwarded to \`command-working\`.
 
 			--[no-]dependency
-			    If enabled, treat this utility as a dependency, only outputting messages iff changes occur.
+			    If enabled, treat this utility as a dependency, only outputting messages iff changes occur. And not installing it if <dependencies> is false. <extra> will also be disabled iff <dependency>.
+			--[no-]deps | --[no-]dependencies
+			    If disabled, do not install any dependencies, even if required.
+			    ! If unset, defaults to the \`SETUP_UTIL__DEPENDENCIES\` environment variable.
+			--[no-]extra
+			    If disabled, do not install any recommended but supplementary dependencies.
+			    ! If unset, defaults to the \`SETUP_UTIL__EXTRA\` environment variable.
+			--[no-]fallback
+			    If disabled, do not install a package system in order to install the package.
+			    ! If unset, defaults to the \`SETUP_UTIL__FALLBACK\` environment variable.
+			--[no-]slim
+			    If enabled, disables <configure>, <fallback>, <dependencies>, <extras>.
+			    ! If unset, defaults to the \`SETUP_UTIL__SLIM\` environment variable.
 			--dependency=...<dependencies>
-			    Append <dependencies> to the list of dependencies that must be installed before this utility is installed.
+			    Append these <dependencies> to the list of dependencies that must be installed before this utility is installed.
 			--dependencies=<dependencies>
 			    Set these <dependencies> as the list of dependencies that must be installed before this utility is installed.
 			--[no-]quiet | --[no-]verbose
@@ -279,12 +290,12 @@ function setup_util() (
 			    If quiet, don't output anything that isn't an error message.
 			    If verbose, output everything.
 
-			UTILITIES:
-			You can specify utilities to install directly via:
+			These options specify the operation of the action on an predefined utility:
 			[--first-success] [--] ...<utility>
+			    E.g. \`setup-util install bat\` and \`setup-util install -- bat\` will trigger \`setup-util-bat\`.
+			    E.g. \`setup-util --first-success -- bat bottom\` will not install \`bottom\` if \`bat\` became installed.
 
-			These options help us detect existing and successful installations:
-
+			These options define a utility:
 			--cli=...<cli>
 			    Used to check if the utility is already installed, in this case, a CLI executable.
 			--app=...<app>
@@ -294,42 +305,24 @@ function setup_util() (
 			--checker=<command>
 			    The <command> is invoked to check if the utility is already installed. It should return [0] if installed, [1] if not installed.
 
-			These options are more intended to be used by the \`setup-util-*\` ecosystem, rather than the \`setup-util\` command itself. For adjust command behaviour respective the commands utilities.
-
-			--[no-]fallback
-			    If disabled, do not install a package system in order to install the package.
-			    ! If unset, defaults to the \`SETUP_UTIL__FALLBACK\` environment variable.
-			--[no-]deps | --[no-]dependencies
-			    If disabled, do not install any dependencies, even if required.
-			    ! If unset, defaults to the \`SETUP_UTIL__DEPENDENCIES\` environment variable.
-			--[no-]extra
-			    If disabled, do not install any recommended but supplementary dependencies.
-			    ! If unset, defaults to the \`SETUP_UTIL__EXTRA\` environment variable.
-			--[no-]slim
-			    If enabled, disables <configure>, <fallback>, <dependencies>, <extras>.
-			    ! If unset, defaults to the \`SETUP_UTIL__SLIM\` environment variable.
-
-			SOURCES:
-			Available sources and their default order of preference:
-			$sources_rendered
-
-			You can specify which sources are used by:
-
-			--source=<sources> | --sources=<sources> | --order=<sources>
-			    Used to override the preferred order of each source, space separated. Use \`...\` as placeholder for those not yet explicitly specified.
-
-			SOuRCE OPTIONS:
-			To use a source, you must customise its configuration. Available source configuration are:
+			These options define how to setup the utility, they are referred to as sources:
 			! \`=()\` indicates the option can be specified multiple times, e.g. [APT=one APT=two].
 			! \`=''\` indicates the option can be specified only once.
 			$source_options_rendered
 
-			You can simplify the specification of multiple packages from the same source with:
-
+			These options allow us to tranpose one source to many packages:
 			--transpose=<source> -- ...<package>
 			    Transposes <package>s onto a specific <source>.
 			    e.g. \`setup-util upstall --transpose=APT -- a b c\` becomes
 			         \`setup-util upstall APT=a APT=b APT=c\`
+
+			These options customise/override the order of the sources:
+			--source=<sources> | --sources=<sources> | --order=<sources>
+			    Used to override the preferred order of each source, space separated. Use \`...\` as placeholder for those not yet explicitly specified.
+
+			SOURCES:
+			Available sources are, in their default order of preference:
+			$sources_rendered
 		EOF
 		return 22 # EINVAL 22 Invalid argument
 	}
@@ -582,6 +575,193 @@ function setup_util() (
 
 	# =====================================
 	# Action
+
+	function help {
+		__print_help "$@" <<-EOF || return $?
+			ABOUT:
+			Output the command(s) necessary to install the <utility>.
+
+			USAGE:
+			\`get-installer [...options] -- ...<utility>\`
+
+			RETURNS:
+			Success if all <utility> had an installer.
+			Failure if any <utility> did not have an installer.
+
+			OPTIONS:
+			--invoke
+			    Rather than output the installer, invoke it, such that installation occurs.
+
+			--first-success
+			    Exit on the first success, ignoring earlier failures.
+
+			--first-failure
+			    Exit on the first failure, skipping later utilities.
+
+			--quiet
+			    If invoke, forwarded to installer.
+			    Otherwise, used to suppress missing installer error.
+
+			--verify
+			    Verify that the installers exist for the aliases. Useful only for testing.
+		EOF
+		return 22 # EINVAL 22 Invalid argument
+	}
+
+	# process
+	local item option_quiet='' option_verify='no' option_utils=() option_invoke='no' option_first_success='no' option_first_failure='no'
+	while [[ $# -ne 0 ]]; do
+		item="$1"
+		shift
+		case "$item" in
+		'--help' | '-h') help ;;
+		'--no-verbose'* | '--verbose'*) __flag --source={item} --target={option_quiet} --non-affirmative ;;
+		'--no-quiet'* | '--quiet'*) __flag --source={item} --target={option_quiet} --affirmative ;;
+		'--no-invoke'* | '--invoke'*) __flag --source={item} --target={option_invoke} --affirmative ;;
+		'--no-verify'* | '--verify'*) __flag --source={item} --target={option_verify} --affirmative ;;
+		'--first-success'*) option_first_success='yes' ;;
+		'--first-failure'*) option_first_failure='yes' ;;
+		'--')
+			option_utils+=("$@")
+			shift "$#"
+			break
+			;;
+		'--'*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
+		*) option_utils+=("$item") ;;
+		esac
+	done
+
+	# =====================================
+	# Configuration
+
+	# load aliases
+	local database="$DOROTHY/config/setup-util.dat" aliases=() installers=() alias installer
+	while IFS=' ' read -rd $'\n' alias installer; do
+		if [[ -z $alias && -z $installer ]]; then
+			# skip empty lines
+			continue
+		fi
+		if [[ -z $alias || -z $installer ]]; then
+			# if one of them is missing, then it's an invalid line
+			__print_style --stderr --code="$alias" ' => ' --code="$installer" ' ❌ ' --error='invalid database entry'
+			continue
+		fi
+		# both are present, it is a valid line
+		aliases+=("$alias")
+		installers+=("$installer")
+	done <"$database"
+
+	# =====================================
+	# Testing
+
+	# testing
+	if [[ $option_verify == 'yes' ]]; then
+		# test that the installers for the aliases actually exist
+		# queue the log entries to output all at once, as it turns it from like a minute into a second
+		local index result=0 logs=()
+		for index in "${!aliases[@]}"; do
+			alias="${aliases[index]}"
+			installer="${installers[index]}"
+			if [[ "setup-util-$alias" == "$installer" ]]; then
+				logs+=(--code="$alias" ' => ' --code="$installer" ' ❌ ' --error='no need for the alias' --newline)
+				result=1
+			elif __command_missing -- "$installer"; then
+				logs+=(--code="$alias" ' => ' --code="$installer" ' ❌ ' --error='missing' --newline)
+				result=1
+			elif [[ $option_quiet == 'no' ]]; then
+				logs+=(--code="$alias" ' => ' --code="$installer" ' ✅ ' --newline)
+			fi
+		done
+		if [[ ${#logs[@]} -ne 0 ]]; then
+			__print_style --no-trail --stderr "${logs[@]}"
+		fi
+
+		# return result
+		return "$result"
+	fi
+
+	# =====================================
+	# Action
+
+	# check
+	if [[ ${#option_utils[@]} -eq 0 ]]; then
+		help --help='No <utility>s specified.'
+	fi
+
+	# helpers
+	function __get_alias {
+		local util="$1"
+		# trim version suffix
+		# ruby@3 => ruby
+		util="${util%%@*}"
+		# trim tap prefix
+		# clementtsang/bottom/bottom => bottom
+		util="${util##*/}"
+		# if util has a space character, then it must have flags or superfluous spaces, trim them
+		if [[ $util == *' '* ]]; then
+			# --classic code --classic => code
+			# (^| ) matches either start of the line, or a space character
+			# -[^ ]+ matches a dash followed by one or more non-space characters
+			# so this is what converts the `--classic` flag into ``
+			# then we trim whitespace at the start and end
+			util="$(echo-regexp -g '(^| )-[^ ]+' '' -- "$util" | echo-trim-each-line --stdin)" || return $?
+		fi
+		# done
+		__print_lines "$util" || return $?
+	}
+
+	function __get_installer {
+		local alias="$1" index
+		for index in "${!aliases[@]}"; do
+			if [[ $alias == "${aliases[index]}" ]]; then
+				__print_lines "${installers[index]}" || return $?
+				return 0
+			fi
+		done
+		# alias not found, check if it exists normally
+		echo-if-command-exists -- "setup-util-$alias" || return $?
+	}
+
+	# handle each utility
+	local util alias installer any_failure='no'
+	for util in "${option_utils[@]}"; do
+		# get the alias
+		alias="$(__get_alias "$util")" || return $?
+		if [[ -z $alias ]]; then
+			continue
+		fi
+
+		# get the installer
+		installer="$(__get_installer "$alias" || :)"
+		if [[ -z $installer ]]; then
+			any_failure='yes'
+			if [[ $option_quiet != 'yes' ]]; then
+				__print_style --stderr --notice1='No installer found for: ' --code-notice1="$util" || return $?
+			fi
+			if [[ $option_first_failure == 'yes' ]]; then
+				return 1
+			fi
+		elif [[ $option_invoke == 'no' ]]; then
+			__print_lines "$installer" || return $?
+			if [[ $option_first_success == 'yes' ]]; then
+				return 0
+			fi
+		elif "$installer" --quiet="$option_quiet"; then
+			if [[ $option_first_success == 'yes' ]]; then
+				return 0
+			fi
+		else
+			any_failure='yes'
+			if [[ $option_first_failure == 'yes' ]]; then
+				return 1
+			fi
+		fi
+	done
+
+	# check for failures
+	[[ $any_failure == 'no' ]] || return $?
+
+	# -------------------------------------------------------------------------
 
 	local item cmd
 	__print_style --h1="Setup ${#option_utils[@]} utilities"
