setup-git: fix glab always needing auth

diff --git a/commands/setup-git b/commands/setup-git
--- a/commands/setup-git
+++ b/commands/setup-git
@@ -200,17 +200,24 @@ echo-style --h2='Git Configuration: Profile'
 git config --global user.name "$GIT_NAME"
 git config --global user.email "$GIT_EMAIL"
 git config --global git.protocol "$GIT_PROTOCOL"
-# optional
+
+# Authorizations
+echo-style --h2='Git Configuration: Auth'
 if test -n "$GITHUB_USERNAME"; then
 	git config --global github.user "$GITHUB_USERNAME"
-	gh auth status &>/dev/null || gh auth login
+	if ! gh auth status &>/dev/null; then
+		gh auth login
+	fi
 else
 	git config --global --unset github.user || : # will fail if already unset
 fi
 if test -n "$GITLAB_USERNAME"; then
 	git config --global gitlab.user "$GITLAB_USERNAME"
-	glab auth status |& grep -q 'Logged in to ' || glab auth login
-	# ^ we use the grep, as glab auth status still returns success exit code if not logged in
+	# glab writes to stderr, grep needed as return status is not indicative
+	# wrap in `! (` is to catch failures in the grep, and in the glab call
+	if ! (glab auth status |& grep --quiet 'Logged in to '); then
+		glab auth login
+	fi
 else
 	git config --global --unset gitlab.user || : # will fail if already unset
 fi
