more bash v3 compat

diff --git a/commands/setup-node b/commands/setup-node
--- a/commands/setup-node
+++ b/commands/setup-node
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 # shellcheck disable=SC2164,SC1091,SC2016
 source "$DOROTHY/sources/strict.bash"
+source "$DOROTHY/sources/arrays.bash"
+if test "$ARRAYS" = 'no'; then
+	echo "Array support required for: $0 $*" >/dev/stderr
+	exit 95 # Operation not supported
+fi
 source "$(which eval-collapse)"
 
 # =====================================
