setup-* reworking to close #14
setup-*-{update|install} now either setup-mac or setup-linux, and will now ask if no action was provided what the intention was

setup-util now supports aur tooling, go, and better and more correct logging, with support for utility names in the logging, also fixed npm and pip fallbacks, and will output performance warning on slow machines

confirm-negative and confirm-positive now support newlines to be passed in their questions

fixed is-user-in-group failing in flatpak containers

setup-go now installs go

setup-python now fixes pip install, regression from last work

setup-util-* now support names, and the AUR ecosystem

log messages throughout now make use of some emojis for a nicer and clearer visual of progress

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -1,24 +1,35 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
+# if quiet, log to stderr
+if is-affirmative "${QUIET-}"; then
+	env QUIET='' stderr setup-util
+	exit $?
+fi
+
 # prepare
 fallbacks=()  # for package systems that could be installed
+name="${NAME:-"${CLI:-unnamed}"}"
 
-# quiet
-if is-affirmative "${QUIET-}"; then
-	if test -n "${CLI-}"; then
-		if command-missing "${CLI}"; then
-			stderr echo "missing utility [$CLI], installing automatically..."
-			env QUIET='' stderr setup-util
-			exit $?
-		else
-			exit 0
-		fi
+# check if necessary
+if test -n "${CLI-}"; then
+	if command-missing "$CLI"; then
+		echo "The [$name] utility does not appear to be installed because [$CLI] is missing. Installing automatically... ⏲"
+	elif test -n "${FORCE-}"; then
+		echo "The [$name] utility is already installed beacuse [$CLI] is present. Forcing reinstall... ⏲"
 	else
-		env QUIET='' stderr setup-util
-		exit $?
+		echo "The [$name] utility is already installed beacuse [$CLI] is present. All good. ✅"
+		exit 0
 	fi
 fi
+
+# log helpers
+function won () {
+	echo "The [$name] utility is now installed. ✅"
+}
+function lost () {
+	echo "The [$name] utility was unable to be installed. ❌"
+}
 
 # brew / Homebrew / macOS
 function do_brew () {
@@ -416,7 +427,25 @@ function do_npm_fallback () {
 	setup-node
 	source "$DOROTHY/sources/paths.sh"
 	source "$DOROTHY/sources/nvm.sh"
-	do_gem "$@"
+	do_npm "$@"
+}
+
+# go
+function do_go () {
+	if test -n "${GO-}"; then
+		if command-missing go; then
+			fallbacks+=('go')
+			return 1
+		fi
+		go get -u -v "$GO"
+	else
+		return 1
+	fi
+}
+function do_go_fallback () {
+	setup-go
+	source "$DOROTHY/sources/paths.sh"
+	do_go "$@"
 }
 
 # pip / Python
@@ -434,7 +463,7 @@ function do_pip () {
 function do_pip_fallback () {
 	setup-python
 	source "$DOROTHY/sources/paths.sh"
-	do_cargo "$@"
+	do_pip "$@"
 }
 
 # gem / Ruby
@@ -468,6 +497,9 @@ function do_cargo () {
 		if command-missing cargo; then
 			fallbacks+=('cargo')
 			return 1
+		fi
+		if ! is-affirmative "${QUIET-}"; then
+			log-performance
 		fi
 		cargo install "${CARGO}"
 	else
@@ -537,6 +569,7 @@ if test "${#order[@]}"; then
 		# source
 		cargo
 		npm
+		go
 		pip
 		gem
 
@@ -569,45 +602,16 @@ if test "${#order[@]}"; then
 	)
 fi
 
-# log helpers
-function meh () {
-	if test -z "${CLI-}"; then
-		stderr echo 'The unamed utility is already installed on this platform. ✅'
-	else
-		stderr echo "The utility [${CLI-}] is already installed this platform. ✅"
-	fi
-}
-function won () {
-	if test -z "${CLI-}"; then
-		stderr echo 'Installed the unamed utility on this platform. ✅'
-	else
-		stderr echo "Installed the utility [${CLI-}] on this platform. ✅"
-	fi
-}
-function lost () {
-	if test -z "${CLI-}"; then
-		stderr echo 'Unable to install the unamed utility on this platform. ❌'
-		# env
-	else
-		stderr echo "Unable to install the utility [${CLI-}] on this platform. ❌"
-	fi
-}
-
 # cycle through the order
-if test -z "${FORCE-}" -a -n "${CLI-}" && command-exists "${CLI}"; then
-	meh
-	exit 0
-else
-	for item in "${order[@]}"; do
-		pass='y'
-		"do_${item}" || pass='n'
-		if test "${pass}" = 'y'; then
-			won
-			exit 0
-		fi
-		# stderr echo "failed via ${item}"
-	done
-fi
+for item in "${order[@]}"; do
+	pass='y'
+	"do_${item}" || pass='n'
+	if test "${pass}" = 'y'; then
+		won
+		exit 0
+	fi
+	# stderr echo "failed via ${item}"
+done
 
 # fallback for failed packages which are missing their package system
 for item in "${fallbacks[@]}"; do
@@ -622,4 +626,3 @@ done
 # failure
 lost
 exit 1
-
