get-github-release, github-download: rewrote
- get-github-release, github-download:
    - `--release=<...>` now deprecated in favour of `--lastest/alias/tag/id` (being specific is best)
- get-github-release:
    - solves API Rate Limit errors
        - fetches are now selected based on the least amount of API requests
        - the GitHub Token from the GitHub CLI is used if it is installed and authenticated
        - the GitHub CLI will be used if it is available
    - supports multiple techniques for inteacting with the GitHub API: gh, jq, and diy (before only jq xor diy could be used)
    - added more actions, and comprehensive support and testing for all actions
    - code is now straightforward and understandable
    - diy technique greatly improved, as my awk skills are now triumphant
- github-download:
    - `--reference=<...>` now deprecated in favour of `--head/branch/tag/commit` (beign specific is best)
    - code is now straightforward and understandable
    - now support downloading a release directly, rather than just an asset of the release
- github-download / down:
    - `--unzip-(filter|format)` renamed to `--archive-(filter|format)` (unzip terminology was inaccurate, considering tarballs were mostly used)
- setup-git, setup-util-gh:
    - authentication of the GitHub CLI now moved to its installer `setup-util-gh` directly, and note authentications role in reducing rate limit errors

/closes #202

diff --git a/commands/setup-util-gh b/commands/setup-util-gh
--- a/commands/setup-util-gh
+++ b/commands/setup-util-gh
@@ -27,8 +27,23 @@
 function setup_util_gh() (
 	source "$DOROTHY/sources/bash.bash"
 
+	# configure
+	function do_configure {
+		# check if we can auth
+		if command-exists gh && is-interactive; then
+			# check if we aren't authed
+			if ! gh auth status &>/dev/null; then
+				# check if we want to auth
+				if confirm --negative --ppid=$$ -- "Authenticate with the GitHub CLI?" 'Authenticating will prevent Rate Limit issues when fetching utilities.'; then
+					gh auth login || : # we don't care if auth fails, as is irrelevant to installation
+				fi
+			fi
+		fi
+	}
+
 	# improve performance
 	if is-needle --quiet "$@" && ! is-needle --upgrade "$@" && ! is-needle --uninstall "$@" && command-exists gh; then
+		do_configure
 		return 0
 	fi
 
@@ -57,7 +72,7 @@ function setup_util_gh() (
 		github-download \
 			--dry \
 			--slug='cli/cli' \
-			--release='latest' \
+			--latest \
 			--asset-filter="$(echo-escape-regex -- "$1")$" | echo-first-line || :
 	}
 	# function add_download_option {
@@ -122,6 +137,9 @@ function setup_util_gh() (
 	# 		add_download_option '_windows_386.zip'
 	# 		add_installer_option '_windows_386.msi'
 	# 	fi
+
+	# configure
+	do_configure
 )
 
 # fire if invoked standalone
