WIP: setup-util-* rewrite
Goal is merging `get-app`, `get-font`, `setup-bin`, `setup-utils`, into `setup-util`, `util.bash`

`setup-bin` gets moved into the individual installers

`setup-util --source=...` now `setup-util --transpose=...`

`setup-util-croc` had incorrect cli

`setup-util-neovim` now can detect its app

`setup-util-nerd-fonts` fix extraction

add `setup-util-super-productivity`

diff --git a/commands/setup-util-1password b/commands/setup-util-1password
--- a/commands/setup-util-1password
+++ b/commands/setup-util-1password
@@ -17,149 +17,128 @@
 
 function setup_util_1password() (
 	source "$DOROTHY/sources/bash.bash"
+	source "$(type -P setup-util)" # enable *_EVAL
 
-	# options
-	local option_reconfigure='yes' option_uninstall='no'
-	__flag --target={option_reconfigure} --name='reconfigure' --affirmative --coerce -- "$@"
-	__flag --target={option_uninstall} --name='uninstall' --affirmative --coerce -- "$@"
-
-	# helpers
-	# don't use `setup-util --check` as not all install methods provide something we can detect, just run this when installing
+	# prepare
+	local user_options=("$@") util_options=(
+		# `snap` and `flatpak` are last because `The 1Password SSH agent doesn't work with Flatpak  or Snap Store installations of 1Password. To use the SSH agent, choose a different method to install 1Password for Linux.`
+		--source='... snap flatpak'
+		--name='1Password Desktop'
+		--app='1Password' # macos
+		--app='1password' # .desktop
+		CASK='1password'
+		RECONFIGURE_INSTALLED_EVAL='__reconfigure'
+	)
 	function __reconfigure {
-		# if reconfigure is not desired, or if not installed, then don't reconfigure
-		if [[ $option_reconfigure == 'no' || $option_uninstall == 'yes' ]]; then
-			return 0
-		fi
-
 		# Browser Extension
 		__print_style 'Install the 1Password Browser extension by visiting the following URL:' --newline --url='https://1password.com/downloads/browser-extension' || return $?
 
 		# Vivaldi
-		setup-util-vivaldi --configure || :
+		setup-util-vivaldi reconfigure || return $?
 	}
-
-	# enable GITHUB_BUILD_EVAL
-	source "$(type -P setup-util)"
-
-	# =================================
-	# Desktop App
-
-	# setup
-	local arch reason='Your password is required to momentarily grant privileges to install 1Password.' options=(
-		--name='1Password App'
-		--app='1Password' # macos
-		--app='1password' # .desktop
-		# > The 1Password SSH agent doesn't work with Flatpak  or Snap Store installations of 1Password. To use the SSH agent, choose a different method to install 1Password for Linux.
-		# This is why snap and flatpak are last
-		--order='... snap flatpak'
-		"$@"
-	)
-	arch="$(__get_arch)"
-	function do_apt_keys {
-		setup-util-gpg --quiet # always call, as it ensures gpg is also setup correctly
-		fs-mkdir --reason="$reason" -- \
-			/etc/debsig/policies/AC2D62742012EA22 \
-			/usr/share/debsig/keyrings/AC2D62742012EA22
-		fetch 'https://downloads.1password.com/linux/debian/debsig/1password.pol' |
-			echo-write --binary --reason="$reason" -- \
-				/etc/debsig/policies/AC2D62742012EA22/1password.pol
-		fetch 'https://downloads.1password.com/linux/keys/1password.asc' |
+	# use platform exclusive configuration
+	if __is_linux; then
+		local arch reason='Your password is required to momentarily grant privileges to install 1Password.'
+		arch="$(__get_arch)"
+		function __apt_keys {
+			setup-util-gpg dependency || return $? # always call, as it ensures gpg is also setup correctly
+			fs-mkdir --reason="$reason" -- \
+				/etc/debsig/policies/AC2D62742012EA22 \
+				/usr/share/debsig/keyrings/AC2D62742012EA22 || return $?
+			fetch 'https://downloads.1password.com/linux/debian/debsig/1password.pol' |
+				echo-write --binary --reason="$reason" -- \
+					/etc/debsig/policies/AC2D62742012EA22/1password.pol || return $?
+			fetch 'https://downloads.1password.com/linux/keys/1password.asc' |
+				eval-helper --elevate --reason="$reason" -- \
+					gpg --dearmor --output \
+					/usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg || return $?
+		}
+		function __rpm_keys {
 			eval-helper --elevate --reason="$reason" -- \
-				gpg --dearmor --output \
-				/usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
-	}
-	function do_rpm_keys {
-		eval-helper --elevate --reason="$reason" -- \
-			rpm --import 'https://downloads.1password.com/linux/keys/1password.asc'
-		echo-write --reason="$reason" -- /etc/yum.repos.d/1password.repo <<-EOF
-			[1password]
-			name=1Password Channel
-			baseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch
-			enabled=1
-			gpgcheck=1
-			repo_gpgcheck=1
-			gpgkey="https://downloads.1password.com/linux/keys/1password.asc"
-		EOF
-	}
-	function do_gpg_keys {
-		setup-util-gpg --quiet # always call, as it ensures gpg is also setup correctly
-		fetch 'https://downloads.1password.com/linux/keys/1password.asc' | gpg --import
-	}
-	function __install {
-		# linux 1password expects it to be inside `/opt/1Password/`
+				rpm --import 'https://downloads.1password.com/linux/keys/1password.asc' || return $?
+			echo-write --reason="$reason" -- /etc/yum.repos.d/1password.repo <<-EOF || return $?
+				[1password]
+				name=1Password Channel
+				baseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch
+				enabled=1
+				gpgcheck=1
+				repo_gpgcheck=1
+				gpgkey="https://downloads.1password.com/linux/keys/1password.asc"
+			EOF
+		}
+		function __gpg_keys {
+			setup-util-gpg dependency || return $? # always call, as it ensures gpg is also setup correctly
+			fetch 'https://downloads.1password.com/linux/keys/1password.asc' | gpg --import || return $?
+		}
+		function __install {
+			# linux 1password expects it to be inside `/opt/1Password/`
 
-		# ensure moving doesn't get nested
-		fs-remove --quiet --no-confirm --elevate -- \
-			/opt/1Password || return $?
+			# ensure moving doesn't get nested
+			fs-remove --quiet --no-confirm --elevate -- \
+				/opt/1Password || return $?
 
-		# make the directory again
-		eval-helper --elevate --reason="$reason" -- \
-			mkdir -pv -- \
-			/opt/1Password || return $?
-
-		# move everything that was extracted to go inside the directory
-		eval-helper --elevate --reason="$reason" -- \
-			mv -v -- \
-			1password-*/* \
-			/opt/1Password || return $?
-
-		# run the official after-install script, and if it fails, just do the symlink part of it
-		eval-helper --elevate --reason="$reason" -- \
-			/opt/1Password/after-install.sh ||
+			# make the directory again
 			eval-helper --elevate --reason="$reason" -- \
-				ln -sf -- \
-				/opt/1Password/1password /usr/bin/1password || return $?
-	}
-	function __uninstall {
-		# https://support.1password.com/uninstall-1password/
-		if is-present -- /opt/1Password/after-remove.sh; then
+				mkdir -pv -- \
+				/opt/1Password || return $?
+
+			# move everything that was extracted to go inside the directory
 			eval-helper --elevate --reason="$reason" -- \
-				/opt/1Password/after-remove.sh || :
-		fi
-		fs-remove --quiet --no-confirm --elevate -- \
-			/opt/1Password /usr/bin/1password || return $?
-	}
-	if __is_macos; then
-		options+=(
-			CASK='1password'
-		)
-	elif __is_linux; then
-		if [[ $arch == 'a64' ]]; then
-			options+=(
-				DOWNLOAD='https://downloads.1password.com/linux/tar/stable/aarch64/1password-latest.tar.gz'
+				mv -v -- \
+				1password-*/* \
+				/opt/1Password || return $?
+
+			# run the official after-install script, and if it fails, just do the symlink part of it
+			eval-helper --elevate --reason="$reason" -- \
+				/opt/1Password/after-install.sh ||
+				eval-helper --elevate --reason="$reason" -- \
+					ln -sf -- \
+					/opt/1Password/1password /usr/bin/1password || return $?
+		}
+		function __uninstall {
+			# https://support.1password.com/uninstall-1password/
+			if is-present -- /opt/1Password/after-remove.sh; then
+				eval-helper --elevate --reason="$reason" -- \
+					/opt/1Password/after-remove.sh || :
+			fi
+			fs-remove --quiet --no-confirm --elevate -- \
+				/opt/1Password /usr/bin/1password || return $?
+		}
+		function __add_download_option {
+			local url="$1"
+			util_options+=(
+				DOWNLOAD="$url"
 				DOWNLOAD_ARCHIVE_EXTRACT='yes'
 				DOWNLOAD_TARGET_PATH='/opt/1Password/1password'
-				DOWNLOAD_BUILD_INSTALL='__install'
-				EVAL_UNINSTALL='__uninstall'
+				DOWNLOAD_BUILD_INSTALL_EVAL='__install'
 			)
+		fi
+		util_options+=(
+			EVAL_UNINSTALL='__uninstall'
+		)
+		if [[ $arch == 'a64' ]]; then
+			# only a64
+			__add_download_option 'https://downloads.1password.com/linux/tar/stable/aarch64/1password-latest.tar.gz'
 		else
-			# these are mutually exclusive and will not be on the same system
-			if is-system --apt; then
-				do_apt_keys
-			elif is-system --rpm; then
-				do_rpm_keys
-			elif is-system --arch; then
-				do_gpg_keys
-			fi
-			# add the x86 options
-			options+=(
+			# only x64
+			__add_download_option 'https://downloads.1password.com/linux/tar/stable/xx86_64/1password-latest.tar.gz'
+			util_options+=(
+				APT_INSTALL_EVAL='__apt_keys'
 				APT_KEY='https://downloads.1password.com/linux/keys/1password.asc'
 				APT_REPO='deb [arch={ARCH} signed-by={KEY}] https://downloads.1password.com/linux/debian/amd64 stable main'
 				APT='1password'
+				AUR_INSTALL_EVAL='__aur_keys'
 				AUR='1password'
-				DOWNLOAD_ARCHIVE_EXTRACT='yes'
-				DOWNLOAD_BUILD_INSTALL='__install'
-				DOWNLOAD_TARGET_PATH='/opt/1Password/1password'
-				DOWNLOAD='https://downloads.1password.com/linux/tar/stable/x86_64/1password-latest.tar.gz'
-				EVAL_UNINSTALL='__uninstall'
 				FLATPAK='https://downloads.1password.com/linux/flatpak/1Password.flatpakref'
+				RPM_INSTALL_EVAL='__rpm_keys'
 				RPM='1password'
 				SNAP='1password'
 			)
 		fi
 	fi
-	setup_util "${options[@]}"
-	__reconfigure
+
+	# setup
+	setup_util "${util_options[@]}" "${user_options[@]}"
 )
 
 # fire if invoked standalone
