setup-util: progress #74 (styling)
Added VERBOSE mode. Only display success if QUIET=no (which is VERBOSE=yes)

diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -11,7 +11,10 @@ fallbacks=() # for package systems that could be installed
 # options
 CLI="${CLI:-"$(get-flag-value cli -- "$@")"}"
 NAME="${NAME:-"$(get-flag-value name --missing="$CLI" -- "$@")"}"
-QUIET="${QUIET:-"$(get-flag-value quiet -- "$@" | echo-affirmative || :)"}" # empty by default, so not absolutely quiet
+QUIET="$(get-flag-value quiet --missing="${QUIET-}" -- "$@" | echo-affirmative || get-flag-value verbose --missing="${VERBOSE-}" -- "$@" | echo-non-affirmative || :)"
+# ^ quiet='' by default, which outputs useful things
+# ^ quiet=yes means don't output anything non-error
+# ^ quiet=no means output everything
 CONFIRM="${CONFIRM:-"$(get-flag-value confirm --missing=no -- "$@" | echo-affirmative)"}"
 OPTIONAL="${OPTIONAL:-"$(get-flag-value confirm --missing=yes -- "$@" | echo-affirmative)"}"
 FORCE="${FORCE:-"$(get-flag-value force --missing=no -- "$@" | echo-affirmative)"}"
@@ -61,7 +64,8 @@ function act() {
 	local ec output
 	ec=0 && output="$("$@" 2>&1)" || ec=$?
 	if test "$ec" -eq 0; then
-		if test "$QUIET" != 'yes'; then
+		# only show success when quiet=no, not quiet='', quiet=yes
+		if test "$QUIET" = 'no'; then
 			if test -n "$output"; then
 				echo-color \
 					--dim+h3='< ' --h3="$*" --dim+h3=' >' $'\n' \
@@ -75,6 +79,7 @@ function act() {
 			fi
 		fi
 	else
+		# always show failure
 		if test -n "$output"; then
 			echo-color \
 				--dim+h3='< ' --h3="$*" --dim+h3=' >' $'\n' \
