major and minor bugfixes
- ask, choose, confirm scripts now respect ctrl+c and other error codes once again

- setup-util now has a more sensible QUIET mode, no more success messages for quiet dependencies

- chmod-partial introduced to make setup-dorothy-permissions more readable

- is-mounted added to check if a source is mounted to a target

 - echo-(black|bold|green|red) added

 - is-empty-ls, is-empty-size added

 - get-size now shows drive size too in no arg mode

 - checksum, and is-same no longer fail due to parent directory being different (required update to fs-structure - `ls -a` to `ls -A`) and filenames causing differences in summary mode

 - cpr now supports CPR_REMOVE env var, todo will be move to flags instead of env vrs

 - ask now supports `--flag` value and accepting flags, to shortcut a common use case

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -5,12 +5,6 @@ if test "$ARRAYS" = 'no'; then
 	exit 95 # Operation not supported
 fi
 
-# if quiet, redo but log to stderr
-if is-affirmative "${QUIET-}"; then
-	env QUIET='' setup-util > /dev/stderr
-	exit "$?"  # exit with the above on success and failure
-fi
-
 # prepare
 fallbacks=()  # for package systems that could be installed
 name="${NAME:-"${CLI:-unnamed}"}"
@@ -18,11 +12,13 @@ name="${NAME:-"${CLI:-unnamed}"}"
 # check if necessary
 if test -n "${CLI-}"; then
 	if command-missing "$CLI"; then
-		echo "The [$name] utility does not appear to be installed because [$CLI] is missing. Installing automatically... ⏲"
+		echo "The [$name] utility does not appear to be installed because [$CLI] is missing. Installing automatically... ⏲" > /dev/tty
 	elif test -n "${FORCE-}"; then
-		echo "The [$name] utility is already installed because [$CLI] is present. Forcing reinstall... ⏲"
+		echo "The [$name] utility is already installed because [$CLI] is present. Forcing reinstall... ⏲" > /dev/tty
 	else
-		echo "The [$name] utility is already installed because [$CLI] is present. All good. ✅"
+		if ! is-affirmative "${QUIET-}"; then
+			echo "The [$name] utility is already installed because [$CLI] is present. All good. ✅" > /dev/tty
+		fi
 		exit 0
 	fi
 fi
@@ -37,10 +33,10 @@ fi
 # log helpers
 function won () {
 	method="$1"
-	echo "The [$name] utility is now installed via [$method]. ✅"
+	echo "The [$name] utility is now installed via [$method]. ✅" > /dev/tty
 }
 function lost () {
-	stderr echo "The [$name] utility was unable to be installed. ❌"
+	echo "The [$name] utility was unable to be installed. ❌" > /dev/stderr
 	if test "$name" = 'unnamed'; then
 		sleep 5
 		if confirm-positive "Do you want to output the environment variables to determine what it was?"; then
@@ -720,7 +716,7 @@ fi
 # cycle through the order
 for item in "${order[@]}"; do
 	pass='y'
-	"do_${item}" || pass='n'
+	"do_${item}" > /dev/tty || pass='n'
 	if test "${pass}" = 'y'; then
 		won "$item"
 		exit 0
@@ -731,7 +727,7 @@ done
 # fallback for failed packages which are missing their package system
 for item in "${fallbacks[@]}"; do
 	pass='y'
-	"do_${item}_fallback" || pass='n'
+	"do_${item}_fallback" > /dev/tty || pass='n'
 	if test "${pass}" = 'y'; then
 		won "$item"
 		exit 0
