setup-dns: better error flow on riscv failure

diff --git a/commands/setup-dns b/commands/setup-dns
--- a/commands/setup-dns
+++ b/commands/setup-dns
@@ -17,6 +17,7 @@ function setup-dns() (
 	# =====================================
 	# Detection
 
+	# helper
 	function die_unknown_os {
 		echo-style --error='Unknown Operating System'
 		return 19 # Operation not supported by device
@@ -85,6 +86,17 @@ function setup-dns() (
 	if test -n "$dnscrypt_installer"; then
 		services+=(dnscrypt)
 	fi
+
+	# helper
+	function die_incompatible_service {
+		local service_title
+		service_title="$1"
+		echo-style \
+			--error="This platform [$arch] does not yet support: $service_title" $'\n' \
+			--notice='Supported DNS services for this platform are:' $'\n' \
+			"${services[*]}"
+		return 19 # Operation not supported by device
+	}
 
 	# =====================================
 	# Arguments
@@ -353,26 +365,6 @@ function setup-dns() (
 			sudo-helper -- systemctl reset-failed
 			# ^ use sudo, otherwise prompted via ubuntu user password
 		fi
-	}
-
-	function die_service_unsupported {
-		local service_title
-		service_title="$1"
-		echo-style \
-			--error="This platform [$arch] does not yet support: $service_title" $'\n' \
-			--notice='Supported DNS services for this platform are:' $'\n' \
-			"${services[*]}"
-		return 19 # Operation not supported by device
-	}
-
-	function die_unknown {
-		local service_title
-		service_title="$1"
-		echo-style \
-			--error="Unknown DNS service: $service_title" $'\n' \
-			--notice='Supported DNS services for this platform are:' $'\n' \
-			"${services[*]}"
-		return 22 # Invalid argument
 	}
 
 	# =====================================
@@ -709,18 +701,20 @@ function setup-dns() (
 		if is-mac; then
 			command-exists networksetup
 		elif is-linux; then
-			command-exists systemd-resolve && command-exists resolvectl
+			command-exists systemctl resolvectl
 		else
 			die_unknown_os
 		fi
 	}
 	function system_install {
 		if ! system_exists; then
-			return 29 # Illegal seek
+			die_unknown_os || : # use this message, but keep the custom return code
+			return 29           # Illegal seek
 		fi
 	}
 	function system_uninstall {
-		return 29 # Illegal seek
+		die_unknown_os || : # use this message, but keep the custom return code
+		return 29           # Illegal seek
 	}
 	function system_configure {
 		# determine servers and action
@@ -928,7 +922,7 @@ function setup-dns() (
 
 		# check
 		if test -z "$aghome_installer"; then
-			die_service_unsupported "$aghome_title"
+			die_incompatible_service "$aghome_title"
 		fi
 
 		# log
@@ -1086,7 +1080,7 @@ function setup-dns() (
 
 		# check
 		if test -z "$dnscrypt_installer"; then
-			die_service_unsupported "$dnscrypt_title"
+			die_incompatible_service "$dnscrypt_title"
 		fi
 
 		# prepare and log
@@ -1274,7 +1268,7 @@ function setup-dns() (
 
 		# check
 		if test -z "$cloudflared_installer"; then
-			die_service_unsupported "$cloudflared_title"
+			die_incompatible_service "$cloudflared_title"
 		fi
 
 		# log
