setup-dorothy: use modern multiline conventions

diff --git a/commands/setup-dorothy b/commands/setup-dorothy
--- a/commands/setup-dorothy
+++ b/commands/setup-dorothy
@@ -4,11 +4,12 @@
 # this script may be eval'd or sourced
 # for install and trial modes
 # and dorothy may not exist yet
+# use stderr for errors, as otherwise trial mode will output failures to stdout
 
 # prepare
 export DOROTHY DOROTHY_USER_HOME DOROTHY_XDG
 action="${DOROTHY_SETUP_ACTION:-"${1:-"install"}"}" # install (runs everything), update, trial
-if test "${action:0:2}" = "--"; then
+if test "${action:0:2}" = '--'; then
 	action='install'
 fi
 
@@ -23,8 +24,10 @@ done
 
 # dependencies
 if ! git --version >/dev/null; then
-	echo 'git is missing, please recheck the installation instructions:' >/dev/stderr
-	echo 'https://github.com/bevry/dorothy' >/dev/stderr
+	cat <<-EOF >/dev/stderr
+		git is missing, please recheck the installation instructions:
+		https://github.com/bevry/dorothy
+	EOF
 	exit 1
 fi
 
@@ -53,13 +56,11 @@ if test "${DOROTHY_XDG-}" = 'yes'; then
 		if test -d "$DOROTHY"; then
 			DOROTHY="${XDG_DATA_HOME:-"$HOME/.local/share"}/dorothy"
 			if test -d "$DOROTHY"; then
-				{
-					echo "cannot move"
-					echo "	$HOME/.dorothy"
-					echo "to"
-					echo "	$DOROTHY"
-					echo "as both locations already exist"
-				} >/dev/stderr
+				cat <<-EOF >/dev/stderr
+					Unable to move:  $HOME/.dorothy
+					To the location: $DOROTHY
+					Because both locations already exist!
+				EOF
 				exit 1
 			fi
 			mv -v "$HOME/.dorothy" "$DOROTHY"
@@ -191,7 +192,7 @@ install_user() {
 	local status='404' user='' repo='' temp='' init='no'
 
 	# fetch username for git repo preparation
-	user="$(git config --global github.user || exit 0)"
+	user="$(git config --global github.user || true)"
 	if test -z "$user"; then
 		user="$(whoami)"
 		# clear generic
@@ -215,16 +216,27 @@ install_user() {
 
 	# if no implied user repo, then prompt for user repo
 	if test -z "$repo"; then
-		echo "If you don't have a repository for it yet, then create one at https://github.com/new using the following details:"
-		printf "\tRepository name: dotfiles\n"
-		printf "\tDescription: My user configuration for the Dorothy dotfile ecosystem: https://github.com/bevry/dorothy\n"
-		printf "\tVisibility: Public\n"
-		printf "\tInitialize with: keep everything unchecked\n"
-		echo ''
-		echo 'Once you have created a repository to house your Dorothy user configuration, then type its URL below'
+		cat <<-EOF
+			If you don't have a repository for it yet, then create one at https://github.com/new using the following details:
+
+			Repository name:
+			dotfiles
+
+			Description:
+			My user configuration for the Dorothy dotfile ecosystem: https://github.com/bevry/dorothy
+
+			Visibility:
+			Public
+
+			Initialize with:
+			keep everything unchecked
+
+			Once you have created the repository to house your Dorothy user configuration,
+			type its URL below
+		EOF
 		if test -n "$user"; then
 			repo="https://github.com/$user/dotfiles.git"
-			printf "or press ENTER to confirm its URL as [%s]\n" "$repo"
+			echo ", or press ENTER to confirm its URL as: $repo"
 		fi
 		read -rp "> " temp
 		if test -n "$temp"; then
@@ -307,12 +319,15 @@ setup_adjustments() {
 		fi
 	done
 	if test -n "$deprecated_configuration_files"; then
-		{
-			echo "Dorothy has moved away from one configuration file for everything, into specialised configuration files."
-			echo "Refer to: https://github.com/bevry/dorothy/discussions/24"
-			echo "For instructions on how to adjust the following files:"
-			echo "$deprecated_configuration_files"
-		} >/dev/stderr
+		cat <<-EOF >/dev/stderr
+			Dorothy has moved away from one configuration file for everything, into specialised configuration files.
+
+			Migration details can be found here:
+			https://github.com/bevry/dorothy/discussions/24
+
+			The following files will need to be migrated:
+			$deprecated_configuration_files
+		EOF
 	fi
 
 	# create essential directories
