setup-util: add `github`: ripgrep/sd now use it
ref #140

diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -64,6 +64,7 @@ function setup-util() (
 
 		# custom
 		installer # local or remote installer
+		github    # remote executable download from github, supports zip
 		download  # remote executable download, supports zip
 	)
 
@@ -163,6 +164,7 @@ function setup-util() (
 	local CARGO='' RUST=''
 	local INSTALLER='' INSTALLER_OPEN=''
 	local DOWNLOAD='' DOWNLOAD_FILENAME='' DOWNLOAD_UNZIP_FORMAT='' DOWNLOAD_UNZIP_FILTER=''
+	local GITHUB_SLUG=''GITHUB_FILENAME='' GITHUB_RELEASE='' GITHUB_ASSET_FILTER=''  GITHUB_UNZIP_FORMAT='' GITHUB_UNZIP_FILTER=''
 
 	# process
 	local item cli='' name='' quiet confirm='' optional='' upgrade='' force='' order=()
@@ -286,7 +288,12 @@ function setup-util() (
 		'DOWNLOAD_FILENAME='*) DOWNLOAD_FILENAME="${item#*DOWNLOAD_FILENAME=}" ;;
 		'DOWNLOAD_UNZIP_FORMAT='*) DOWNLOAD_UNZIP_FORMAT="${item#*DOWNLOAD_UNZIP_FORMAT=}" ;;
 		'DOWNLOAD_UNZIP_FILTER='*) DOWNLOAD_UNZIP_FILTER="${item#*DOWNLOAD_UNZIP_FILTER=}" ;;
-
+		'GITHUB_SLUG='*) GITHUB_SLUG="${item#*GITHUB_SLUG=}" ;;
+		'GITHUB_RELEASE='*) GITHUB_RELEASE="${item#*GITHUB_RELEASE=}" ;;
+		'GITHUB_ASSET_FILTER='*) GITHUB_ASSET_FILTER="${item#*GITHUB_ASSET_FILTER=}" ;;
+		'GITHUB_UNZIP_FORMAT='*) GITHUB_UNZIP_FORMAT="${item#*GITHUB_UNZIP_FORMAT=}" ;;
+		'GITHUB_UNZIP_FILTER='*) GITHUB_UNZIP_FILTER="${item#*GITHUB_UNZIP_FILTER=}" ;;
+		'GITHUB_FILENAME='*) GITHUB_FILENAME="${item#*GITHUB_FILENAME=}" ;;
 		*) ;; # passively ignore, could be custom arg, such as --paths for setup-util-plex
 		esac
 	done
@@ -1432,6 +1439,44 @@ function setup-util() (
 		fi
 	}
 
+	# github
+	function do_github {
+		local slug="${GITHUB_SLUG-}" filename="${GITHUB_FILENAME-}" release="${GITHUB_RELEASE-}" asset_filter="${GITHUB_ASSET_FILTER-}" unzip_format="${GITHUB_UNZIP_FORMAT-}" unzip_filter="${GITHUB_UNZIP_FILTER-}"
+
+		# check applicabile
+		if test -n "$slug"; then
+			# require filename
+			if test -z "$filename"; then
+				echo-style --error="GITHUB requires GITHUB_FILENAME"
+				return 1
+			fi
+
+			# prepare
+			mkdir -p "$XDG_BIN_HOME"
+
+			# download
+			github-download \
+				--slug="$slug" \
+				--release="$release" \
+				--asset-filter="$asset_filter" \
+				--unzip-format="$unzip_format" \
+				--unzip-filter="$unzip_filter" \
+				--path="$XDG_BIN_HOME/$filename"
+
+			# adjust
+			fs-own --permissions='+x' "$XDG_BIN_HOME/$filename"
+
+			# verify
+			if ! command-working "$XDG_BIN_HOME/$filename"; then
+				echo-style --error="GITHUB installed, however failed to verify."
+				return 1
+			fi
+		else
+			# not applicable
+			return 1
+		fi
+	}
+
 	# download
 	function do_download {
 		local download="${DOWNLOAD-}" filename="${DOWNLOAD_FILENAME-}" unzip_format="${DOWNLOAD_UNZIP_FORMAT-}" unzip_filter="${DOWNLOAD_UNZIP_FILTER-}"
@@ -1440,7 +1485,7 @@ function setup-util() (
 		if test -n "$download"; then
 			# require filename
 			if test -z "$filename"; then
-				echo-style --error="DOWNLOAD required DOWNLOAD_FILENAME"
+				echo-style --error="DOWNLOAD requires DOWNLOAD_FILENAME"
 				return 1
 			fi
 
@@ -1455,6 +1500,12 @@ function setup-util() (
 
 			# adjust
 			fs-own --permissions='+x' "$XDG_BIN_HOME/$filename"
+
+			# verify
+			if ! command-working "$XDG_BIN_HOME/$filename"; then
+				echo-style --error="DOWNLOAD installed, however failed to verify."
+				return 1
+			fi
 		else
 			# not applicable
 			return 1
