setup-util: initial work for #26
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -7,25 +7,31 @@ fi
 
 # prepare
 fallbacks=()  # for package systems that could be installed
-name="${NAME:-"${CLI:-unnamed}"}"
+
+# options
+NAME="${NAME:-"$(get-flag-value name -- "$@")"}"
+CLI="${CLI:-"$(get-flag-value cli -- "$@")"}"
+QUIET="${QUIET:-"$(get-flag-value quiet --missing=no -- "$@" | echo-affirmative)"}"
+CONFIRM="${CONFIRM:-"$(get-flag-value confirm --missing=no -- "$@" | echo-affirmative)"}"
+FORCE="${FORCE:-"$(get-flag-value force --missing=no -- "$@" | echo-affirmative)"}"
 
 # check if necessary
-if test -n "${CLI-}"; then
+if test -n "$CLI"; then
 	if command-missing "$CLI"; then
-		echo "The [$name] utility does not appear to be installed because [$CLI] is missing. Installing automatically... ⏲" > /dev/tty
-	elif test -n "${FORCE-}"; then
-		echo "The [$name] utility is already installed because [$CLI] is present. Forcing reinstall... ⏲" > /dev/tty
+		echo "The [$NAME] utility does not appear to be installed because [$CLI] is missing. Installing automatically... ⏲" > /dev/tty
+	elif test "$FORCE" = 'yes'; then
+		echo "The [$NAME] utility is already installed because [$CLI] is present. Forcing reinstall... ⏲" > /dev/tty
 	else
-		if ! is-affirmative "${QUIET-}"; then
-			echo "The [$name] utility is already installed because [$CLI] is present. All good. ✅" > /dev/tty
+		if test "$QUIET" = 'no'; then
+			echo "The [$NAME] utility is already installed because [$CLI] is present. All good. ✅" > /dev/tty
 		fi
 		exit 0
 	fi
 fi
 
 # confirm if necessary
-if is-affirmative "${CONFIRM-}"; then
-	if ! confirm-positive "Do you want to install the [$name] utility?"; then
+if test "$CONFIRM" = 'yes'; then
+	if ! confirm-positive "Do you want to install the [$NAME] utility?"; then
 		exit 2  # error exit code so that things that depend on this abort
 	fi
 fi
@@ -33,15 +39,15 @@ fi
 # log helpers
 function won () {
 	local method="$1"
-	echo "The [$name] utility is now installed via [$method]. ✅" > /dev/tty
+	echo "The [$NAME] utility is now installed via [$method]. ✅" > /dev/tty
 }
 function lost () {
-	echo "The [$name] utility was unable to be installed. ❌" > /dev/stderr
-	if test "$name" = 'unnamed'; then
-		sleep 5
-		if confirm-negative "Do you want to output the environment variables to determine what it was?"; then
+	echo "The [$NAME] utility was unable to be installed. ❌" > /dev/stderr
+	if test "$NAME" = 'unnamed'; then
+		if test "$QUIET" = 'no' && confirm-negative "Do you want to output the environment variables to determine what it was?"; then
 			env | sort
 		fi
+		sleep 5
 	fi
 }
 
@@ -56,7 +62,7 @@ function do_brew () {
 		fi
 		# support BREW holding multiple args
 		local args=(); mapfile -t args < <(echo-split ' ' -- "$BREW")
-		if test -n "${FORCE-}"; then
+		if test "$FORCE" = 'yes'; then
 			args+=('--force')
 		fi
 		if ! brew install "${args[@]}"; then
@@ -84,7 +90,7 @@ function do_cask () {
 		# support CASK holding multiple args
 		local args=(); mapfile -t args < <(echo-split ' ' -- "$CASK")
 		args+=('--cask')
-		if test -n "${FORCE-}"; then
+		if test "$FORCE" = 'yes'; then
 			args+=('--force')
 		fi
 		brew install "${args[@]}"
