is-apt, is-brew, setup-util: better cross-platform support
setup-util will now also fail when unable to install the utility

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -10,7 +10,8 @@ source "$DOROTHY/sources/strict.bash"
 
 if test -n "${CLI-}" && command-exists "${CLI}"; then
 	echo "${CLI} already installed"
-elif test -n "${BREW-}" && is-mac && command-exists brew; then # brew / Homebrew / macOS
+	exit 0
+elif test -n "${BREW-}" && is-brew; then # brew / Homebrew / macOS
 	brew install "${BREW}"
 elif test -n "${YAY-}" && command-exists yay; then # yay / AUR / Arch Linux
 	yay -Sy "${YAY}"
@@ -20,9 +21,9 @@ elif test -n "${YUM_EVAL-}" && command-exists yum; then # yum / RedHat / Fedora 
 	eval "${YUM_EVAL}"
 elif test -n "${YUM-}" && command-exists yum; then # yum / RedHat / Fedora / CentOS / etc
 	sudo yum install "${YUM}"
-elif test -n "${APT_EVAL-}" && command-exists apt; then # apt / Ubuntu / Debian / Linux Mint / elementary OS / etc
+elif test -n "${APT_EVAL-}" && is-apt; then # apt / Ubuntu / Debian / Linux Mint / elementary OS / etc
 	eval "${APT_EVAL}"
-elif test -n "${APT-}" && command-exists apt; then # apt / Ubuntu / Debian / Linux Mint / elementary OS / etc
+elif test -n "${APT-}" && is-apt; then # apt / Ubuntu / Debian / Linux Mint / elementary OS / etc
 	sudo apt install -y "${APT}"
 elif test -n "${APK-}" && command-exists apk; then # apk / Alpine Linux
 	apk add bat "${APK}"
@@ -89,4 +90,7 @@ elif test -n "${CARGO-}" && command-exists cargo; then # cargo / Crates.io / Rus
 	cargo install "${CARGO}"
 elif test -n "${CURL-}" && command-exists curl; then # curl / Manual Installer
 	sh -c "$(fetch "$CURL")"
+else
+	stderr echo 'unable to install utility on this platform'
+	exit 1
 fi
