spellcheck, fixes, improvements
- choose: add `--truncate-body` WIP
- config-edit: `--editer=` to `--editor=`
- add `echo-truncate-lines` WIP
- eval-helper: shapeshifter will be enabled on `sudo-helper` by default
- flush-dns, setup-util-docker, setup-util-xcode: fix formatting when sudo needed
- fs-rm: rewrote for new `fs-trim` command
- get-profile: `possesive-pronoun` to `possesive-pronoun`
- git-helper: fix bad formatting on failures
- is-present: speedier sudo checks, by first checking without sudo
- sudo-helper: support `--optional` for speedier checks without sudo
- mount-helper: fixed detection of forced unmount
- add `setup-util-tor-browser`
- styles: fix terminal title and resize not terminating

diff --git a/commands/setup-util-node b/commands/setup-util-node
--- a/commands/setup-util-node
+++ b/commands/setup-util-node
@@ -128,7 +128,7 @@ function setup_util_node() (
 		# continue with the upgrade
 		echo-style --dim="Before: v$(nvm-env -- npm --version)"
 		setup-util --name='npm' --upgrade --force --quiet \
-			NPM='npm' || echo-style --notice='You can ignore the npm ugprade failure, this will resolve after nvm is used.'
+			NPM='npm' || echo-style --notice='You can ignore the npm upgrade failure, this will resolve after nvm is used.'
 		nvm-env -- npm cache clean --force 2>/dev/null # silent --force warning
 		__print_lines "After:  v$(nvm-env -- npm --version)"
 	}
@@ -152,7 +152,7 @@ function setup_util_node() (
 
 		# clean NVM unless configured otherwise
 		# the intent of this is to purge unused global Node.js versions and packages
-		# we use a configuration variable to change this, as interuppting the flow and asking the user creates too much confusion
+		# we use a configuration variable to change this, as interrupting the flow and asking the user creates too much confusion
 		# as such a question is only necessary to experienced users
 		if [[ -d $NVM_DIR ]]; then
 			clean_otherwise_wipe_nvm
diff --git a/commands/sudo-helper b/commands/sudo-helper
--- a/commands/sudo-helper
+++ b/commands/sudo-helper
@@ -1,8 +1,5 @@
 #!/usr/bin/env bash
 
-# sudo a command helpering environment and path
-# https://stackoverflow.com/q/257616/130638
-
 function sudo_helper() (
 	source "$DOROTHY/sources/bash.bash"
 	source "$(type -P eval-helper)" # enable eval_helper
@@ -21,27 +18,29 @@ function sudo_helper() (
 
 			OPTIONS:
 			--reason=<reason>
-			    if a prompt is required for your sudo/root/login password, this reason will be used to explain why sudo was required.
+			    If a prompt is required for your sudo/root/login password, this reason will be used to explain why sudo was required.
 
 			--user=<user>
-			    specify a user to run the command as
+			    Specify a user to run the command as.
 			--group=<group>
-			    specify a group to run the command as
-			--no-sudo | --sudo=no
+			    Specify a group to run the command as.
+			--sudo=no | --required=no
 			    If specified, and no <user> nor <group> is provided, then sudo will not be used, and the command will be run normally.
+			--optional
+			    If specified, and no <user> nor <group> is provided, then try the command first without sudo, and if it fails, try again with sudo.
 
 			--inherit
-			    if enabled, inherit environment variables include PATH.
+			    If enabled, inherit environment variables include PATH.
 
 			--wrap
-			    if enabled, [eval-helper] will be used to wrap the output of the command
+			    If enabled, [eval-helper] will be used to wrap the output of the command
 			--quiet
-			    if enabled, [eval-helper] will be used to silence the output of the command
+			    If enabled, [eval-helper] will be used to silence the output of the command
 			--confirm
-			    if enabled, [eval-helper] will be used to confirm the execution of the command
+			    If enabled, [eval-helper] will be used to confirm the execution of the command
 
 			--local
-			    update sudo configuration to enable access to /usr/local paths
+			    Update sudo configuration to enable access to /usr/local paths
 
 		EOF
 		if [[ $# -ne 0 ]]; then
@@ -52,7 +51,7 @@ function sudo_helper() (
 
 	# process
 	# option_quiet='no' is an important default to ensure our call to eval-helper can still be interpolated
-	local item option_cmd=() option_quiet='no' option_reason='' option_user='' option_group='' option_sudo='yes' option_confirm='no' option_wrap='no' option_inherit='no' option_local=''
+	local item option_cmd=() option_quiet='no' option_reason='' option_user='' option_group='' option_required='yes' option_optional='no' option_confirm='no' option_wrap='no' option_inherit='no' option_local=''
 	while [[ $# -ne 0 ]]; do
 		item="$1"
 		shift
@@ -67,8 +66,11 @@ function sudo_helper() (
 		'--reason='*) option_reason="${item#*=}" ;;
 		'--user='*) option_user="${item#*=}" ;;
 		'--group='*) option_group="${item#*=}" ;;
-		'--no-sudo'* | '--sudo'*)
-			option_sudo="$(get-flag-value --affirmative --fallback="$option_sudo" -- "$item")"
+		'--no-sudo'* | '--sudo'* | '--no-required'* | '--required'*)
+			option_required="$(get-flag-value --affirmative --fallback="$option_required" -- "$item")"
+			;;
+		'--no-optional'* | '--optional'*)
+			option_optional="$(get-flag-value --affirmative --fallback="$option_optional" -- "$item")"
 			;;
 		'--no-inherit'* | '--inherit'*)
 			option_inherit="$(get-flag-value --affirmative --fallback="$option_inherit" -- "$item")"
@@ -131,6 +133,12 @@ function sudo_helper() (
 		help 'No <command> was provided.'
 	fi
 
+	# adjust
+	if [[ -n $option_user || -n $option_user ]]; then
+		option_required='yes'
+		option_optional='no'
+	fi
+
 	# =====================================
 	# Action
 
@@ -146,98 +154,111 @@ function sudo_helper() (
 	# -i, --login
 	#    Run the shell specified by the target user's password database entry as a login shell.
 
-	local run=() home='' command_style='sudo'
-	if [[ $option_sudo == 'no' ]]; then
-		command_style=''
-		run+=("${option_cmd[@]}")
-	elif __command_exists -- sudo; then
-		run+=('sudo')
+	local command_style='code'
+	function __wrap {
+		if [[ $option_wrap == 'yes' || $option_confirm == 'yes' || $option_quiet == 'yes' ]]; then
+			eval-helper --command="$(echo-style --"$command_style"="$(echo-escape-command -- "${option_cmd[@]}")")" --wrap="$option_wrap" --quiet="$option_quiet" --confirm="$option_confirm" -- "$@"
+			return
+		else
+			"$@" # eval
+			return
+		fi
+	}
 
-		if [[ -n $option_user ]]; then
-			run+=("--user=$option_user")
-			# should coincide with setup-environment-commands
-			if [[ -d /Users ]]; then
-				home="/Users/$option_user"
-			elif [[ -d '/home' ]]; then
-				home="/home/$option_user"
-			elif [[ -d "/$option_user" ]]; then
-				HOME="/$option_user"
-			fi
-		elif [[ -n $HOME ]]; then
-			home="$HOME"
+	# try without sudo
+	if [[ $option_required == 'no' ]]; then
+		__wrap "${option_cmd[@]}"
+		return
+	elif [[ $option_optional == 'yes' ]]; then
+		if __wrap "${option_cmd[@]}"; then
+			return 0
 		fi
-
-		if [[ -n $option_group ]]; then
-			run+=("--group=$option_group")
-		fi
-
-		if [[ -n $home ]]; then
-			if is-missing -- "$home"; then
-				sudo mkdir -p "$home" # don't use __sudo_mkdirp as that will forever recurse
-				fs-own --quiet --user="$option_user" --group="$option_group" -- "$home"
-			fi
-			run+=('--set-home')
-		fi
-
-		if [[ $option_inherit == 'yes' ]]; then
-			run+=(
-				'--preserve-env'
-				'env'
-				"PATH=$PATH"
-			)
-		fi
-
-		# check if password is required
-		# [sudo --validate] doesn't work on multipass, so just use [true] as a no-op
-		if ! sudo --non-interactive true &>/dev/null; then
-			# password is required, let the user know what they are being prompted for
-			# [--code=*] better than [echo-style --element/="$(echo-escape-command -- "${run[@]}" | echo-join ' ' --stdin)"] as that is too verbose
-			# use [--tty] to ensure the prompt is not hidden when otherwise hiding sudo output, such as in [command-working]
-			# while it would be nice to clear lines, we cannot know how many lines to clear as they could require multiple attempts to enter the password
-			if [[ -n $option_reason ]]; then
-				echo-style --tty --notice="$option_reason"
-			else
-				echo-style --tty --notice='Your sudo/root/login password is required to execute the command:'
-			fi
-			option_wrap='yes'
-		fi
-
-		run+=("${option_cmd[@]}")
-	elif __command_exists -- doas; then
-		# https://man.archlinux.org/man/doas.1.en
-		run+=('doas')
-		if [[ -n $option_user ]]; then
-			run+=(
-				'-u'
-				"$option_user"
-			)
-		fi
-		if [[ -n $option_group ]]; then
-			help 'doas does not support --group'
-		fi
-		if [[ $option_inherit == 'yes' ]]; then
-			run+=(
-				'env'
-				"DOROTHY=$DOROTHY"
-				"PATH=$PATH"
-			)
-		fi
-		run+=("${option_cmd[@]}")
-	else
-		# sudo/doas does not exist, probably not needed
-		command_style=''
-		run+=("${option_cmd[@]}")
 	fi
 
-	# execute
-	# @note that piping to cat, allows ctrl+c (SIGTERM) to be correctly reported, otherwise exit status 1 is returned
-	# the main thing here though, is that any failure should be detected and cancel in the caller
-	# perhaps requiring --ppid=$$ to be passed to sudo-helper is the way to go, as we do for [confirm]
-	if [[ $option_wrap == 'yes' || $option_confirm == 'yes' || $option_quiet == 'yes' ]]; then
-		eval-helper --command="$(echo-style --"$command_style"="$(echo-escape-command -- "${option_cmd[@]}")")" --wrap="$option_wrap" --quiet="$option_quiet" --confirm="$option_confirm" -- "${run[@]}"
-	else
-		"${run[@]}" # eval
+	local sudo_cmd=() home=''
+	if [[ $option_required == 'yes' ]]; then
+		# don't use is-directory, is-missing, __sudo_mkdirp, as they will cause infinite recursion
+		if __command_exists -- sudo; then
+			sudo_cmd+=('sudo')
+			if [[ -n $option_user ]]; then
+				sudo_cmd+=("--user=$option_user")
+				# should coincide with setup-environment-commands
+				if [[ -d /Users ]]; then
+					home="/Users/$option_user"
+				elif [[ -d '/home' ]]; then
+					home="/home/$option_user"
+				elif [[ -d "/$option_user" ]]; then
+					HOME="/$option_user"
+				fi
+			elif [[ -n $HOME ]]; then
+				home="$HOME"
+			fi
+
+			if [[ -n $option_group ]]; then
+				sudo_cmd+=("--group=$option_group")
+			fi
+
+			if [[ -n $home ]]; then
+				if [[ ! -e $home && ! -L $home ]]; then
+					sudo mkdir -p "$home"
+					fs-own --quiet --user="$option_user" --group="$option_group" -- "$home"
+				fi
+				sudo_cmd+=('--set-home')
+			fi
+
+			if [[ $option_inherit == 'yes' ]]; then
+				sudo_cmd+=(
+					'--preserve-env'
+					'env'
+					"PATH=$PATH"
+				)
+			fi
+
+			# check if password is required
+			# [sudo --validate] doesn't work on multipass, so just use [true] as a no-op
+			if ! sudo --non-interactive true &>/dev/null; then
+				# password is required, let the user know what they are being prompted for
+				# [--code=*] better than [echo-style --element/="$(echo-escape-command -- "${sudo_cmd[@]}" | echo-join ' ' --stdin)"] as that is too verbose
+				# use [--tty] to ensure the prompt is not hidden when otherwise hiding sudo output, such as in [command-working]
+				# while it would be nice to clear lines, we cannot know how many lines to clear as they could require multiple attempts to enter the password
+				if [[ -n $option_reason ]]; then
+					echo-style --tty --notice="$option_reason"
+				else
+					echo-style --tty --notice='Your sudo/root/login password is required to execute the command:'
+				fi
+				option_wrap='yes'
+			fi
+
+			sudo_cmd+=("${option_cmd[@]}")
+		elif __command_exists -- doas; then
+			# https://man.archlinux.org/man/doas.1.en
+			sudo_cmd+=('doas')
+			if [[ -n $option_user ]]; then
+				sudo_cmd+=(
+					'-u'
+					"$option_user"
+				)
+			fi
+			if [[ -n $option_group ]]; then
+				help 'doas does not support --group'
+			fi
+			if [[ $option_inherit == 'yes' ]]; then
+				sudo_cmd+=(
+					'env'
+					"DOROTHY=$DOROTHY"
+					"PATH=$PATH"
+				)
+			fi
+		else
+			# sudo/doas does not exist, probably not needed
+			option_required='no'
+		fi
 	fi
+
+	# try sudo
+	command_style='sudo'
+	__wrap "${sudo_cmd[@]}" "${option_cmd[@]}"
+	return
 )
 
 # fire if invoked standalone
