WIP: setup-util, *: more convention reworks
- `edit-dns`, `flush-dns`, `setup-dns`, `setup-hosts`: add todo comment re convergence
- `*: `dependency` to `--dependency`
- `nvm-env` to `node-env` to support `nvm`, `fnm`, etc
- `dorothy`: forward install/upstall
- `fs-own`: remove deprecated code and warnings
- `*`: use backticks not square brackets in comments
- `is-empty-value`: add todo comment re akk/any/none
- `is-system`: add `--nvm`
- `macos-drive`: use safety functions to avoid unnecessary try
- `macos-installer`: use modern tty convention
- `setup-git`: add todo merge comment
- `setup-linux`, `setup-mac`: hard deprecate for `setup-system`
- `setup-linux-raspi`: attempt at modern options
- `setup-mac-brew`: move encoding handling into `setup-util-ffmpeg`, remove cleaning as that is now handled by `setup-system` and `setup-util`, remove fast vs slow, this is all about transitioning to `setup-util`
- `setup-util`: merge the WIP list and search actions, add `system-*` actions, add nocase handling for source options, rename `--source` to `--sources`, add more exit status codes, add more convenience helpers, extra docs out, add ability to overwrite packages args for convenience helpers, rename `setup-upgrade` to `setup-update` so that `upgrade` is only used for `system-upgrade` (distro upgrade), prep more sources for new conventions, some prep to the cycling/invoking functionality
- add `setup-util-{ffmpeg,fnm,scoop}`
- remove long-standing deprecations from `setup-*`, and `setup-util-*` so the surface area of the new implementation is only what is needed
- `docs/setup-util/*`: add manual docs for different package managers, and move the docs from `setup-util` for htem to there
- `setup-node`: simplified dramtically as lot of the complexity is now first-partied into `setup-util`
- `setup-util-python`: only do `python3`, as doing both v2 and v3 and uv and hwatnot is just unnecessary burden
- `bash.bash`: remove `__invoke_and_workaround_carriage_returns` and just have `__workaround_carriage_returns` to reduce unused surface area

Major WIP stiff remaining:
- `setup.bash` variables, whether they will persist, what they will be called, and so on.
- instdallation of a package maanger / sources extras have moved into the actual `setup-util-${source}` script, however, I'm thinking this is unneeded, and having just a `setup-util.dat` file with things like `uv=....` is a better option than `UV_INSTALL=...` vars

diff --git a/commands/setup-system b/commands/setup-system
--- a/commands/setup-system
+++ b/commands/setup-system
@@ -57,6 +57,57 @@ function setup_system() (
 	# =====================================
 	# Action
 
+	if is-system --mac; then
+		# reassert minimal apple dependencies
+		setup-util install -- apple-rosetta apple-cli-tools
+		setup-util upstall -- brew
+	fi
+
+	# upgrade all existing packages
+	# ask, because manjaro and rolling releases can demand over 40GB for initial upgrades
+	if confirm --linger --positive --ppid=$$ -- 'Upgrade existing packages?'; then
+		setup-util upgrade-all --confirm --verbose --sources=apk,apt,dnf,pacman,zypper,... || return $?
+	fi
+
+	# setup essential system utilities
+	if [[ $action == 'install' ]]; then
+		setup-util-devel install
+	fi
+	if is-system --raspi; then
+		setup-linux-raspi "$action" # @todo move to `setup-util-*` ecosystem
+	fi
+	if [[ $action == 'install' ]] && confirm --linger --negative --ppid=$$ -- 'Enable recovery hotkeys?'; then
+		setup-linux-recovery # @todo move to `setup-util-*` ecosystem
+	fi
+
+	# install package managers
+	if [[ $action == 'install' ]]; then
+		if __is_linux; then
+			# in this order, based on dependency relationships
+			# relevacny is already handled by their scripts
+			setup-util install --optional --confirm -- pamac snap flatpak gnome-software
+		fi
+	fi
+
+	# upgrade the entire system
+	setup-util system-upgrade --optional --confirm
+
+	# setup user packages
+	# @todo redo this to do `SETUP_UTILS`, etc.
+	# for item in "${packages[@]}"; do
+	# 	if __command_exists -- "$item"; then
+	# 		eval_helper --no-wrap --shapeshifter \
+	# 			--pending="$(__print_style --bold="Installing packages of $item...")" \
+	# 			--success="$(__print_style --success="Installed packages of $item.")" \
+	# 			--failure="$(__print_style --error="Failed to install packages of $item.")" -- \
+	# 			"do_${item}_packages"
+	# 	fi
+	# done
+
+	# cleanup
+	setup-util clean-all --verbose || return $?
+
+
 	# log
 	__print_style --h1="$action_title"
 
@@ -74,7 +125,8 @@ function setup_system() (
 		if __is_macos; then
 			setup-mac "$action"
 		elif __is_linux; then
-			setup-linux "$action"
+			if is-system --raspi; then
+				setup-linux-raspi
 		fi
 
 		# windows
@@ -128,12 +180,12 @@ function setup_system() (
 		clean_dirs
 
 	# npm
-	if __command_exists -- npm; then
+	if setup-util-npm is-installed; then
 		eval_helper --quiet --wrap --shapeshifter \
 			--pending="$(__print_style --bold="Cleaning npm...")" \
 			--success="$(__print_style --success="Cleaned npm.")" \
 			--failure="$(__print_style --error="Failed to clean npm.")" -- \
-			nvm-env -- npm cache clean --force || :
+			node-env -- npm cache clean --force || :
 	fi
 
 	# operating system
