eval-collapse: fix recursion causing failure
abstract out `is-quiet` into its own script

in genral, we should only do stderr and stdout where it essential, otherwise it's extra complexity complicates matters - such as making things more difficult to clear, especially in the case of /dev/tty

diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -10,7 +10,7 @@ fallbacks=() # for package systems that could be installed
 # options
 CLI="${CLI:-"$(get-flag-value cli -- "$@")"}"
 NAME="${NAME:-"$(get-flag-value name --missing="$CLI" -- "$@")"}"
-QUIET="$(get-flag-value quiet --missing="${QUIET-}" -- "$@" | echo-affirmative || get-flag-value verbose --missing="${VERBOSE-}" -- "$@" | echo-non-affirmative || :)"
+QUIET="$(is-quiet -- "$@" || :)"
 # ^ quiet='' by default, which outputs useful things
 # ^ quiet=yes means don't output anything non-error
 # ^ quiet=no means output everything
@@ -21,12 +21,12 @@ FORCE="${FORCE:-"$(get-flag-value force --missing=no -- "$@" | echo-affirmative)
 # check if necessary
 if test -n "$CLI"; then
 	if command-missing "$CLI"; then
-		echo-color --h3="The [$NAME] utility does not appear to be installed because [$CLI] is missing. Installing automatically... ⏲" >/dev/tty
+		echo-color --h3="The [$NAME] utility does not appear to be installed because [$CLI] is missing. Installing automatically... ⏲"
 	elif test "$FORCE" = 'yes'; then
-		echo-color --h3="The [$NAME] utility is already installed because [$CLI] is present." $'\n' --h3="However, it has been marked for reinstall. Reinstalling... ⏲" >/dev/tty
+		echo-color --h3="The [$NAME] utility is already installed because [$CLI] is present." $'\n' --h3="However, it has been marked for reinstall. Reinstalling... ⏲"
 	else
 		if test "$QUIET" != 'yes'; then
-			echo-color --g3="The [$NAME] utility is already installed because [$CLI] is present. All good. ✅" >/dev/tty
+			echo-color --g3="The [$NAME] utility is already installed because [$CLI] is present. All good. ✅"
 		fi
 		exit 0
 	fi
@@ -42,11 +42,11 @@ fi
 # log helpers
 function won() {
 	local method="$1"
-	echo-color --g3="The [$NAME] utility is now installed via [$method]. ✅" >/dev/tty
+	echo-color --g3="The [$NAME] utility is now installed via [$method]. ✅"
 }
 function lost() {
 	local ec=1
-	echo-color --e3="The [$NAME] utility was unable to be installed. ❌" >/dev/stderr
+	echo-color --e3="The [$NAME] utility was unable to be installed. ❌"
 	if test "$OPTIONAL" != 'no'; then
 		echo-color --e3="However, [$NAME] has been marked as optional, so it is up to you to figure this out later."
 		ec=0
@@ -1101,11 +1101,11 @@ fi
 # cycle through the order
 for item in "${order[@]}"; do
 	if test -z "$item"; then
-		echo-color --error="an empty order argument was provided" >/dev/stderr
+		echo-color --error="an empty order argument was provided"
 		exit 22 # Invalid argument
 	fi
 	pass='y'
-	"do_${item}" >/dev/tty || pass='n'
+	"do_${item}" || pass='n'
 	if test "${pass}" = 'y'; then
 		won "$item"
 		exit 0
@@ -1116,7 +1116,7 @@ done
 # fallback for failed packages which are missing their package system
 test "${#fallbacks[@]}" -ne 0 && for item in "${fallbacks[@]}"; do
 	pass='y'
-	"do_${item}_fallback" >/dev/tty || pass='n'
+	"do_${item}_fallback" || pass='n'
 	if test "${pass}" = 'y'; then
 		won "$item"
 		exit 0
