autoinstall most common dependencies and remove them from `defaults.bash`
- `realpath` usage has been swapped for `fs-absolute` as fish shell also has a way of determining realpath, so the realpath/coreutils is a fallback if fish shell is not present
- `cd ... || exit 1` linting compliance
- `setup-util` now supports homebrew casks, pkgutil, and quiet mode

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/setup-dorothy b/commands/setup-dorothy
--- a/commands/setup-dorothy
+++ b/commands/setup-dorothy
@@ -17,7 +17,7 @@ echo
 if test -d "$DOROTHY"; then
 	# update
 	echo "Updating the Dorothy installation at $DOROTHY"
-	cd "$DOROTHY"
+	cd "$DOROTHY" || exit 1
 	log="$(mktemp)"
 	"$DOROTHY/commands/ok" "$DOROTHY/commands/silent" git-protocol-apply origin
 	git pull origin "$("$DOROTHY/commands/git-default-branch")" > "$log"
@@ -37,14 +37,14 @@ else
 fi
 
 # ensure any updated or installed commands have the correct permissions
-cd "$DOROTHY"
+cd "$DOROTHY" || exit 1
 chmod -f +x ./commands/*
 
 # stop git complaints for dorothy repo
 "$DOROTHY/commands/silent" git config pull.ff only
 
 # confirm hostname is intentional
-hostname="$(uname -n)"  # don't use $(get-hostname) as too inconvenient at this stage of dorothy's setup
+hostname="$("$DOROTHY/commands/get-hostname")"
 if test "$hostname" = 'ubuntu'; then
 	if "$DOROTHY/commands/confirm-bool" "This machine's hostname is currently generic [$hostname], would you like to change it?"; then
 		read -r -p "What should the new hostname be? " hostname
@@ -62,10 +62,10 @@ echo
 if test -d "$DOROTHY/user"; then
 	# update
 	echo "Updating the Dorothy user configuration at $DOROTHY/user"
-	cd "$DOROTHY/user"
+	cd "$DOROTHY/user" || exit 1
 	log="$(mktemp)"
-	ok silent git-protocol-apply origin
-	if ! git pull origin "$(git-default-branch)" > "$log"; then
+	"$DOROTHY/commands/ok" "$DOROTHY/commands/silent" git-protocol-apply origin
+	if ! git pull origin "$("$DOROTHY/commands/git-default-branch")" > "$log"; then
 		echo "...Dorothy user configuration was unable to be updated, you will have to figure out why later (probably you are disconnected, or there is no remote pushes yet), continuing!"
 		rm "$log"
 	else
@@ -80,58 +80,69 @@ if test -d "$DOROTHY/user"; then
 		fi
 	fi
 else
-	# install
-	if test -z "${DOROTHY_USER_REPO-}"; then
-		# can't use truthy, or ok command yet, as still installing
-		repo=''
-		status='404'
-		user="$(git config --global github.user || exit 0)"
-		if test -z "$user"; then
-			user="$(whoami)"
-			if test "$user" = 'ubuntu'; then
-				user=''
+	# check for skip
+	if test -z "${DOROTHY_SKIP_USER-}"; then
+		# install
+		if test -z "${DOROTHY_USER_REPO-}"; then
+			# can't use truthy, or ok command yet, as still installing
+			repo=''
+			status='404'
+			user="${DOROTHY_USER-}"  # allow setting via environment variable
+			if test -z "$user"; then
+				user="$(git config --global github.user || exit 0)"
+				if test -z "$user"; then
+					user="$(whoami)"
+					if test "$user" = 'ubuntu'; then
+						user=''
+					fi
+				fi
 			fi
-		fi
-		echo "Dorothy houses user configuration inside its own git repository."
-		if test -n "$user"; then
-			status="$(curl -I -s -w '%{http_code}\n' -o /dev/null "https://github.com/$user/dotfiles")"
-			repo="https://github.com/$user/dotfiles.git"
-			if test "$status" -eq 200; then
-				if ! "$DOROTHY/commands/confirm-bool" "Does this repository house your Dorothy user configuration? [$repo]"; then
-					repo=''
+			echo "Dorothy houses user configuration inside its own git repository."
+			if test -n "$user"; then
+				status="$(curl -I -s -w '%{http_code}\n' -o /dev/null "https://github.com/$user/dotfiles")"
+				repo="https://github.com/$user/dotfiles.git"
+				if test "$status" -eq 200; then
+					if ! "$DOROTHY/commands/confirm-bool" "Does this repository house your Dorothy user configuration? [$repo]"; then
+						repo=''
+					fi
+				fi
+			fi
+			if test -z "$repo"; then
+				echo "If you don't have a repository for it yet, then create one at https://github.com/new using the following details:"
+				printf "\tRepository name: dotfiles\n"
+				printf "\tDescription: My user configuration for the Dorothy dotfile ecosystem: https://github.com/bevry/dorothy\n"
+				printf "\tVisibility: Public\n"
+				printf "\tInitialize with: keep everything unchecked\n"
+				echo ''
+				echo 'Once you have created a repository to house your Dorothy user configuration, then type its URL below.'
+				if test -n "$user"; then
+					repo="https://github.com/$user/dotfiles.git"
+					printf "\tor press ENTER to confirm its URL as [%s]\n" "$repo"
+				fi
+				read -r -p "> " DOROTHY_USER_REPO
+				if test -z "$DOROTHY_USER_REPO"; then
+					export DOROTHY_USER_REPO="$repo"
 				fi
 			fi
 		fi
-		if test -z "$repo"; then
-			echo "If you don't have a repository for it yet, then create one at https://github.com/new using the following details:"
-			printf "\tRepository name: dotfiles\n"
-			printf "\tDescription: My user configuration for the Dorothy dotfile ecosystem: https://github.com/bevry/dorothy\n"
-			printf "\tVisibility: Public\n"
-			printf "\tInitialize with: keep everything unchecked\n"
-			echo ''
-			echo 'Once you have created a repository to house your Dorothy user configuration, then type its URL below.'
-			if test -n "$user"; then
-				repo="https://github.com/$user/dotfiles.git"
-				printf "\tor press ENTER to confirm its URL as [%s]\n" "$repo"
-			fi
-			read -r -p "> " DOROTHY_USER_REPO
-			if test -z "$DOROTHY_USER_REPO"; then
-				export DOROTHY_USER_REPO="$repo"
-			fi
+
+		# clone
+		echo "Cloning the Dorothy user configuration into $DOROTHY/user"
+		if ! git clone "$DOROTHY_USER_REPO" "$DOROTHY/user"; then
+			echo "The clone of the repository [$DOROTHY_USER_REPO] to [$DOROTHY/user] failed."
+			echo "Dorothy will initialise the directory as a git repository, and leave it up to you to sync it up with a remote."
+			echo
 		fi
 	fi
 
-	# clone
-	echo "Cloning the Dorothy user configuration into $DOROTHY/user"
-	if ! git clone "$DOROTHY_USER_REPO" "$DOROTHY/user"; then
-		echo "The clone of the repository [$DOROTHY_USER_REPO] to [$DOROTHY/user] failed."
-		echo "Dorothy will initialise the directory as a git repository, and leave it up to you to sync it up with a remote."
-		echo
+	# if skipped, or clone fail, then create the directory
+	if ! test -d "$DOROTHY/user"; then
+		echo "Skipping user configuration as instructured..."
 		mkdir -p "$DOROTHY/user"
-		cd "$DOROTHY/user"
+		cd "$DOROTHY/user" || exit 1
 		"$DOROTHY/commands/silent" git init
 	else
-		cd "$DOROTHY/user"
+		cd "$DOROTHY/user" || exit 1
 	fi
 
 	# stop git complaints for dorothy user repo
@@ -197,10 +208,14 @@ EOF
 fi
 
 # ensure any updated or installed commands have the correct permissions
-cd "$DOROTHY"
+cd "$DOROTHY" || exit 1
 "$DOROTHY/commands/ok" "$DOROTHY/commands/silent" chmod -f +x ./user/commands/*  # would fail if no commands
 
-# proceed with install
+# proceed with shell cofniguration
+if test -n "${DOROTHY_SKIP_SHELL-}"; then
+	echo "Skipping shell configuration as instructured..."
+	exit
+fi
 if test "${1-}" != 'update'; then
 	# now that dorothy is confirmed to exist, proceed with strict mode
 	source "$DOROTHY/sources/strict.bash"
diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -1,6 +1,21 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
+if is-needle '--quiet' "$@" || is-affirmative "${QUIET-}"; then
+	if test -n "${CLI-}"; then
+		if command-missing "${CLI}"; then
+			stderr echo "missing utility [$CLI], installing automatically..."
+			stderr setup-util
+			exit $?
+		else
+			exit 0
+		fi
+	else
+		stderr setup-util
+		exit $?
+	fi
+fi
+
 # these should be sorted in order of preference, which for now I am unsure
 # perhaps the order could even be a preference
 # like UTIL_INSTALLERS=("apt" "yum" "zypper")
@@ -13,6 +28,8 @@ if test -n "${CLI-}" && command-exists "${CLI}"; then
 	exit 0
 elif test -n "${BREW-}" && is-brew; then # brew / Homebrew / macOS
 	brew install "${BREW}"
+elif test -n "${CASK-}" && is-brew; then # brew / Homebrew / macOS
+	brew install --cask "${CASK}"
 elif test -n "${YAY-}" && command-exists yay; then # yay / AUR / Arch Linux
 	yay -Sy "${YAY}"
 elif test -n "${SNAP-}" && command-exists snap; then # snap/ Snap Craft / Ubuntu
@@ -60,6 +77,8 @@ elif test -n "${WINGET-}" && command-exists winget; then # winget / Windows Pack
 	winget install "${WINGET}"
 elif test -n "${PKG-}" && command-exists pkg; then # pkg / FreeBSD / Termux
 	pkg install "${PKG}"
+elif test -n "${PKGUTIL-}" && command-exists pkgutil; then # pkgutil / Solaris 10+, Sparc and x86.
+	pkgutil -i "${PKG}"
 elif test -n "${NPM-}" && command-exists npm; then # npm / Node.js
 	npm install -g "${NPM}"
 elif test -n "${HUBER-}" && command-exists huber; then # huber
