setup-dorothy: --xdg flag,  inline dorothy replacement
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/setup-dorothy b/commands/setup-dorothy
--- a/commands/setup-dorothy
+++ b/commands/setup-dorothy
@@ -6,39 +6,90 @@
 # and dorothy may not exist yet
 
 # prepare
-action="${DOROTHY_SETUP_ACTION:-"${1:-"install"}"}"  # install (runs everything), update, trial
+export DOROTHY DOROTHY_USER_HOME DOROTHY_XDG
+action="${DOROTHY_SETUP_ACTION:-"${1:-"install"}"}" # install (runs everything), update, trial
+if test "${action:0:2}" = "--"; then
+	action='install'
+fi
+
+# check for --xdg argument
+for arg in "$@"; do
+	if test "$arg" = '--xdg'; then
+		DOROTHY_XDG='yes'
+	fi
+done
 
 # dependencies
-if ! git --version > /dev/null; then
-	echo 'git is missing, please recheck the installation instructions:' > /dev/stderr
-	echo 'https://github.com/bevry/dorothy' > /dev/stderr
+if ! git --version >/dev/null; then
+	echo 'git is missing, please recheck the installation instructions:' >/dev/stderr
+	echo 'https://github.com/bevry/dorothy' >/dev/stderr
 	exit 1
 fi
 
-# check custom initiation (first time `setup-dorothy` run without anything configured)
+# check custom initiation
 if test -z "${DOROTHY-}"; then
-	if test -n "${BDIR-}"; then
-		export DOROTHY="$BDIR"  # legacy
-	elif test -n "${XDG_DATA_HOME-}" -a -d "${XDG_DATA_HOME-}/dorothy"; then
-		export DOROTHY="$XDG_DATA_HOME/dorothy"
+	# setup-dorothy is running via curl, so dorothy init has not happened
+	# check if dorothy has previously been cloned
+	# such that when we setup the shell init scripts, they go to the correct location
+	if test -n "${XDG_DATA_HOME-}" -a -d "${XDG_DATA_HOME-}/dorothy"; then
+		DOROTHY="$XDG_DATA_HOME/dorothy"
 	elif test -d "$HOME/.local/share/dorothy"; then
-		export DOROTHY="$HOME/.local/share/dorothy"
+		DOROTHY="$HOME/.local/share/dorothy"
 	else
-		export DOROTHY="$HOME/.dorothy"
+		DOROTHY="$HOME/.dorothy"
 	fi
 fi
 
-# ensure dorothy, and eventually user config, is accessible for this command
-export PATH="$DOROTHY/user/commands.local:$DOROTHY/user/commands:$DOROTHY/commands:$PATH"  # right to left is preference
+# ensure dorothy, and its xdg permutations are accessible
+export PATH="$DOROTHY/commands:$HOME/.dorothy/commands:$HOME/.local/share/dorothy/commands:$PATH"
+# ^ right to left is preference
+
+# check xdg env var
+if test "${DOROTHY_XDG-}" = 'yes'; then
+	# move .dorothy
+	if test "$DOROTHY" = "$HOME/.dorothy"; then
+		if test -d "$DOROTHY"; then
+			DOROTHY="${XDG_DATA_HOME:-"$HOME/.local/share"}/dorothy"
+			if test -d "$DOROTHY"; then
+				echo "cannot move" >/dev/stderr
+				echo "	$HOME/.dorothy" >/dev/stderr
+				echo "to" >/dev/stderr
+				echo "	$DOROTHY" >/dev/stderr
+				echo "as both locations already exist" >/dev/stderr
+				exit 1
+			fi
+			mv -v "$HOME/.dorothy" "$DOROTHY"
+		fi
+	else
+		echo "Dorothy already installed to $DOROTHY"
+	fi
+
+	# move .dorothy/user
+	# -h and -L are both tests for symlinks
+	if test -L "$DOROTHY/user"; then
+		DOROTHY_USER_HOME="$(fs-realpath "$DOROTHY/user")"
+		echo "Dorothy User Configuration already installed to $DOROTHY_USER_HOME"
+	else
+		DOROTHY_USER_HOME="${DOROTHY_USER_HOME:-"${XDG_CONFIG_HOME:-"$HOME/.config"}/dorothy"}"
+		if test -d "$DOROTHY/user"; then
+			# gotta move it
+			DOROTHY_USER_HOME="${DOROTHY_USER_HOME:-"${XDG_CONFIG_HOME:-"$HOME/.config"}/dorothy"}"
+			mv -v "$DOROTHY/user" "$DOROTHY_USER_HOME"
+			ln -vsfF "$DOROTHY_USER_HOME" "$DOROTHY/user"
+		else
+			echo "Dorothy User Configuration will be installed to $DOROTHY_USER_HOME"
+		fi
+	fi
+fi
 
 # helpers
-git_init () {
+git_init() {
 	mkdir -p "$1"
-	pushd "$1" > /dev/null || exit 1
+	pushd "$1" >/dev/null || exit 1
 	git init
-	popd > /dev/null
+	popd >/dev/null
 }
-install_dorothy () {
+install_dorothy() {
 	# check
 	if test -d "$DOROTHY"; then
 		update_dorothy
@@ -53,7 +104,7 @@ install_dorothy () {
 	# fix permissions
 	chmod -f +x "$DOROTHY/commands/"*
 }
-update_dorothy () {
+update_dorothy() {
 	# check
 	if test "$action" = 'trial'; then
 		return
@@ -62,7 +113,7 @@ update_dorothy () {
 	# act
 	echo
 	echo "Updating the Dorothy installation at $DOROTHY"
-	if git-update "$DOROTHY" > /dev/null; then
+	if git-update "$DOROTHY" >/dev/null; then
 		# fix permissions
 		chmod -f +x "$DOROTHY/commands/"*
 	else
@@ -70,10 +121,10 @@ update_dorothy () {
 		exit 1
 	fi
 }
-setup_dorothy () {
-	install_dorothy  # goes to update_dorothy for us
+setup_dorothy() {
+	install_dorothy # goes to update_dorothy for us
 }
-setup_hostname () {
+setup_hostname() {
 	# check
 	if test "$action" != 'install'; then
 		return
@@ -92,7 +143,7 @@ setup_hostname () {
 		fi
 	fi
 }
-install_user () {
+install_user() {
 	# check action
 	if test "$action" = 'trial'; then
 		return
@@ -101,11 +152,11 @@ install_user () {
 	# check custom initiation
 	if test ! -d "$DOROTHY/user"; then
 		if test -n "${DOROTHY_USER_HOME-}" -a -d "${DOROTHY_USER_HOME-}"; then
-			ln -sfF "$DOROTHY_USER_HOME" "$DOROTHY/user"
+			ln -vsfF "$DOROTHY_USER_HOME" "$DOROTHY/user"
 		elif test -n "${XDG_CONFIG_HOME-}" -a -d "${XDG_CONFIG_HOME-}/dorothy"; then
-			ln -sfF "$XDG_CONFIG_HOME/dorothy" "$DOROTHY/user"
+			ln -vsfF "$XDG_CONFIG_HOME/dorothy" "$DOROTHY/user"
 		elif test -d "$HOME/.config/dorothy"; then
-			ln -sfF "$HOME/.config/dorothy" "$DOROTHY/user"
+			ln -vsfF "$HOME/.config/dorothy" "$DOROTHY/user"
 		fi
 	fi
 
@@ -184,7 +235,7 @@ install_user () {
 		chmod -f +x "$DOROTHY/user/commands/"*
 	fi
 }
-update_user () {
+update_user() {
 	# check
 	if test "$action" = 'trial'; then
 		return
@@ -193,7 +244,7 @@ update_user () {
 	# act
 	echo
 	echo "Updating the Dorothy user configuration at $DOROTHY/user"
-	if git-update "$DOROTHY/user" > /dev/null; then
+	if git-update "$DOROTHY/user" >/dev/null; then
 		if test -d "$DOROTHY/user/commands"; then
 			chmod -f +x "$DOROTHY/user/commands/"*
 		fi
@@ -202,7 +253,7 @@ update_user () {
 		exit 1
 	fi
 }
-setup_user () {
+setup_user() {
 	if test "$action" = 'trial'; then
 		return
 	else
@@ -213,7 +264,7 @@ setup_user () {
 		fi
 	fi
 }
-setup_adjustments () {
+setup_adjustments() {
 	# check
 	if test "$action" = 'trial'; then
 		return
@@ -236,10 +287,10 @@ setup_adjustments () {
 		fi
 	done
 	if test -n "$deprecated_configuration_files"; then
-		stderr echo "Dorothy has moved away from one configuration file for everything, into specialised configuration files."
-		stderr echo "Refer to: https://github.com/bevry/dorothy/discussions/24"
-		stderr echo "For instructions on how to adjust the following files:"
-		stderr echo "$deprecated_configuration_files"
+		echo "Dorothy has moved away from one configuration file for everything, into specialised configuration files." >/dev/stderr
+		echo "Refer to: https://github.com/bevry/dorothy/discussions/24" >/dev/stderr
+		echo "For instructions on how to adjust the following files:" >/dev/stderr
+		echo "$deprecated_configuration_files" >/dev/stderr
 	fi
 
 	# create essential directories
@@ -255,11 +306,11 @@ setup_adjustments () {
 		--find='commands.local/' --replace='commands.local/' \
 		--find='config.local/' --replace='config.local/'
 }
-check () {
+check() {
 	if test -f "$1"; then
 		echo ''
 		echo "== <$1> =="
-		echo-trim-lines < "$1"
+		echo-trim-lines <"$1"
 		echo "== </$1> =="
 		echo
 		if confirm-positive "The above file is probably deprecated with Dorothy, would you like to replace it?"; then
@@ -267,7 +318,7 @@ check () {
 		fi
 	fi
 }
-function setup_shell () {
+setup_shell() {
 	# check
 	if test "$action" != 'install'; then
 		return
@@ -287,33 +338,37 @@ function setup_shell () {
 
 	if confirm-positive "Would you like bash to use Dorothy?"; then
 		# mac and raspi ubuntu
-		# shellcheck disable=SC2016
-		printf '\n\n# Source our custom dotfile configuration\nsource "%s/init.sh"\n' "$DOROTHY" >> "$HOME/.bash_profile"
+		config-helper \
+			--file="$HOME/.bash_profile" \
+			--find='source ".+?" # Dorothy' --replace="source \"$DOROTHY/init.sh\" # Dorothy"
 
 		# vm ubuntu
-		# shellcheck disable=SC2016
-		printf '\n\n# Source our custom dotfile configuration\nsource "%s/init.sh"\n' "$DOROTHY" >> "$HOME/.bashrc"
+		config-helper \
+			--file="$HOME/.bashrc" \
+			--find='source ".+?" # Dorothy' --replace="source \"$DOROTHY/init.sh\" # Dorothy"
 	fi
 
 	if confirm-positive "Would you like zsh to use Dorothy?"; then
-		# shellcheck disable=SC2016
-		printf '\n\n# Source our custom dotfile configuration\nsource "%s/init.sh"\n' "$DOROTHY" >> "$HOME/.zshrc"
+		config-helper \
+			--file="$HOME/.zshrc" \
+			--find='source ".+?" # Dorothy' --replace="source \"$DOROTHY/init.sh\" # Dorothy"
 
-		# shellcheck disable=SC2016
-		printf '\n\n# Source our custom dotfile configuration\nsource "%s/init.sh"\n' "$DOROTHY" >> "$HOME/.zprofile"
+		config-helper \
+			--file="$HOME/.zprofile" \
+			--find='source ".+?" # Dorothy' --replace="source \"$DOROTHY/init.sh\" # Dorothy"
 	fi
 
 	if confirm-positive "Would you like fish to use Dorothy?"; then
 		mkdir -p "$HOME/.config/fish"
-
-		# shellcheck disable=SC2016
-		printf '\n\n# Source our custom dotfile configuration\nsource "%s/init.fish"\n' "$DOROTHY" >>  "$HOME/.config/fish/config.fish"
+		config-helper \
+			--file="$HOME/.config/fish/config.fish" \
+			--find='source ".+?" # Dorothy' --replace="source \"$DOROTHY/init.fish\" # Dorothy"
 	fi
 }
 
 # perform the actions
 setup_dorothy
-source "$DOROTHY/sources/strict.bash"  # it is here, as now we know dorothy does exit
+source "$DOROTHY/sources/strict.bash" # it is here, as now we know dorothy does exit
 setup_hostname
 setup_user
 setup_adjustments
