setup-util-1password-cli: fix macos install

diff --git a/commands/setup-util-1password-cli b/commands/setup-util-1password-cli
--- a/commands/setup-util-1password-cli
+++ b/commands/setup-util-1password-cli
@@ -16,13 +16,14 @@ function setup-util-1password() (
 	setup-util-devel --quiet # sponge
 
 	# determine cli version
-	version="v$(fetch 'https://app-updates.agilebits.com/product_history/CLI2' | sponge | rg -o 'https://cache.agilebits.com/dist/1P/op2/pkg/v([^/]+)/' --replace '$1' --max-count 1 || :)"
+	# || : to avoid exit code 141
+	version="v$(fetch 'https://app-updates.agilebits.com/product_history/CLI2' | sponge | rg -o 'https://cache.agilebits.com/dist/1P/op2/pkg/v([^/-]+)/' --replace '$1' --max-count 1 || :)"
 
 	# fetch cli urls
 	if test "$platform" = 'Darwin'; then
 		pkg="https://cache.agilebits.com/dist/1P/op2/pkg/$version/op_apple_universal_$version.pkg"
 		# uninstall cask version as it lags behind
-		setup-util "@" --quiet --optional --uninstall --name='1Password CLI' \
+		setup-util "$@" --quiet --optional --uninstall --name='1Password CLI' \
 			CASK='homebrew/cask-versions/1password-cli-beta' \
 			CASK_TAP='homebrew/cask-versions'
 	elif test "$platform" = 'Linux'; then
@@ -65,7 +66,6 @@ function setup-util-1password() (
 	setup-util "$@" --name='1Password CLI' --cli=op \
 		DOWNLOAD="$zip" DOWNLOAD_FILENAME='op' DOWNLOAD_UNZIP_FILTER='op' \
 		INSTALLER="$pkg" INSTALLER_OPEN='yes'
-
 )
 
 # fire if invoked standalone
