setup-shell: rework
- `setup-shell`: rewritten to be clear and powerful
- `setup-server`: fix bug with `echo-file`
- `echo-file`: fix `--stdin` behaviour changing, old behaviour as used by `setup-shell` and `setup-server` is now `--stdin-paths`
- `config-helper`: document some issues and future improvements
- `echo-write`: support `--(path|file)=*` option alias
- `stdinargs`: fix `--stdin=`, use modern arg conventions to cleanup and clarify code
- `styles`: add `(icon|commentary)-nothing-available`

/workarounds #333
/fixes #325 #324 #317
/improves #308 #307
/discards cf4f6606f4f4f623515dae09ced973e16eeefa5e
/discards 34c4c3486d8343649f88b8dced6497a5a9272f07 8913b0b a1f870a270da7916e0e462e5c73f752806d96fee

diff --git a/commands/setup-mac-brew b/commands/setup-mac-brew
--- a/commands/setup-mac-brew
+++ b/commands/setup-mac-brew
@@ -415,8 +415,8 @@ function setup_mac_brew() (
 						eval_helper --quiet --wrap \
 							--pending="$(__print_style --bold='Uninstalling: ' --code="$pkg")" \
 							--success="$(__print_style --success='Uninstalled: ' --code="$pkg")" \
-							--failure="$(__print_style --error='Failed to uninstall: ' --code="$pkg")" \
-							-- brew uninstall --quiet --ignore-dependencies "$pkg" || :
+							--failure="$(__print_style --error='Failed to uninstall: ' --code="$pkg")" -- \
+							brew uninstall --quiet --ignore-dependencies "$pkg" || :
 					fi
 				done
 				# cleanup, used to fix any breaks after the removals, this is only here are is purges upgrade caches, which is undesirable on unreliable internet connections as it means re-runs always has to download everything again
@@ -438,8 +438,8 @@ function setup_mac_brew() (
 						eval_helper --quiet --wrap \
 							--pending="$(__print_style --bold='Untapping: ' --code="$tap")" \
 							--success="$(__print_style --success='Untapped: ' --code="$tap")" \
-							--failure="$(__print_style --error='Failed to untap: ' --code="$tap")" \
-							-- brew untap --quiet "$tap" || :
+							--failure="$(__print_style --error='Failed to untap: ' --code="$tap")" -- \
+							brew untap --quiet "$tap" || :
 					fi
 				done
 			fi
@@ -455,8 +455,8 @@ function setup_mac_brew() (
 			eval_helper --quiet --wrap \
 				--pending="$(__print_style --bold='Tap: ' --code="$tap")" \
 				--success="$(__print_style --success='Tapped: ' --code="$tap")" \
-				--failure="$(__print_style --error='Failed to tap: ' --code="$tap")" \
-				-- brew tap --quiet "$tap"
+				--failure="$(__print_style --error='Failed to tap: ' --code="$tap")" -- \
+				brew tap --quiet "$tap"
 		done
 		__print_style --g2="Tap $# repositories"
 	}
@@ -487,8 +487,8 @@ function setup_mac_brew() (
 			eval_helper --quiet --wrap \
 				--pending="$(__print_style --bold='Updating: ' --path="$repo")" \
 				--success="$(__print_style --success='Updated: ' --path="$repo")" \
-				--failure="$(__print_style --error='Failed to update: ' --path="$repo")" \
-				-- brew_update_repo "$repo"
+				--failure="$(__print_style --error='Failed to update: ' --path="$repo")" -- \
+				brew_update_repo "$repo"
 		done
 		__print_style --g2="Update $# repositories"
 	}
