setup-git: disable glab, as its busted

diff --git a/commands/setup-git b/commands/setup-git
--- a/commands/setup-git
+++ b/commands/setup-git
@@ -214,10 +214,15 @@ if test -n "$GITLAB_USERNAME"; then
 	git config --global gitlab.user "$GITLAB_USERNAME"
 	# glab writes to stderr, grep needed as return status is not indicative
 	# wrap in `! (` is to catch failures in the grep, and in the glab call
-	setup-util-glab # only install if gitlab is configured
-	if ! (glab auth status |& grep --quiet 'Logged in to '); then
-		glab auth login
-	fi
+
+	# setup-util-glab # only install if gitlab is configured
+	# if ! (glab auth status |& grep --quiet 'Logged in to '); then
+	# 	glab auth login
+	# fi
+
+	# ^ currently broken
+	# > glab auth login
+	# failed to read configuration:  open /home/ubuntu/.config/glab-cli/.config.yml2800055398: permission denied
 else
 	git config --global --unset gitlab.user || : # will fail if already unset
 fi
