arch compatability, setup-util improvements
added `setup-util-build` to house common dev deps, such as those needed by `setup-rust` and added arch support

`select-dns` now uses a new `network-interface` command that now includes arch support, and deprecates `setup-util-netscript`

`setup-util` no longer supports the unused `--quiet` argument, now arguments can be an optional order override, and if one method fails, it will try the next available method

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-if is-needle '--quiet' "$@" || is-affirmative "${QUIET-}"; then
+# quiet
+if is-affirmative "${QUIET-}"; then
 	if test -n "${CLI-}"; then
 		if command-missing "${CLI}"; then
 			stderr echo "missing utility [$CLI], installing automatically..."
@@ -16,142 +17,451 @@ if is-needle '--quiet' "$@" || is-affirmative "${QUIET-}"; then
 	fi
 fi
 
-# these should be sorted in order of preference, which for now I am unsure
-# perhaps the order could even be a preference
-# like UTIL_INSTALLERS=("apt" "yum" "zypper")
+# brew / Homebrew / macOS
+function do_brew () {
+	if test -n "${CASK-}" && is-brew; then
+		if test -n "${FORCE-}"; then
+			brew install --cask "${CASK}" --force
+		else
+			brew install --cask "${CASK}"
+		fi
+	else
+		return 1
+	fi
+}
 
-# perhaps instead of using ENV, we can use arguments instead, but that would require fancy parsing
-# as such, perhaps this can be rewritten as a rust util?
+# brew / Homebrew Casks / macOS
+function do_cask () {
+	if test -n "${CASK-}" && is-brew; then
+		if test -n "${FORCE-}"; then
+			brew install --cask "${CASK}" --force
+		else
+			brew install --cask "${CASK}"
+		fi
+	else
+		return 1
+	fi
+}
 
+# pacman / Arch Linux
+function do_pacman () {
+	if test -n "${PACMAN-}" && command-exists pacman; then
+	sudo pacman -S "${PACMAN}"
+	else
+		return 1
+	fi
+}
+
+# yay / AUR / Arch Linux
+function do_yay () {
+	if test -n "${YAY-}" && command-exists yay; then
+		yay -Sy "${YAY}"
+	else
+		return 1
+	fi
+}
+
+# snap/ Snap Craft / Ubuntu
+function do_snap () {
+	if test -n "${SNAP-}" && command-exists snap; then
+		if test -n "${SNAP_CHANNEL-}"; then
+			snap install --channel="${SNAP_CHANNEL}" "${SNAP}"
+		else
+			snap install "${SNAP}"
+		fi
+	else
+		return 1
+	fi
+}
+
+# yum / RedHat / Fedora / CentOS / etc
+function do_yum () {
+	if test -n "${YUM_EVAL-}" && command-exists yum; then
+		eval "${YUM_EVAL}"
+	elif test -n "${YUM-}" && command-exists yum; then
+		if test -n "${YUM_REPO-}"; then
+			cd /etc/yum.repos.d/ || exit 1
+			wget "$YUM_REPO"
+		fi
+		sudo yum install "${YUM}"
+	else
+		return 1
+	fi
+}
+
+# apt / Ubuntu / Debian / Linux Mint / elementary OS / etc
+function do_apt () {
+	if test -n "${APT_EVAL-}" && is-apt; then
+		eval "${APT_EVAL}"
+	elif test -n "${APT-}" && is-apt; then
+		if test -n "${APT_REPO-}"; then
+			sudo apt-add-repository -y "$APT_REPO"
+			sudo apt-get update
+		fi
+		sudo apt install -y "${APT}"
+	else
+		return 1
+	fi
+}
+
+# apk / Alpine Linux
+function do_apk () {
+	if test -n "${APK-}" && command-exists apk; then
+		apk add "${APK}"
+	else
+		return 1
+	fi
+}
+
+# nix
+function do_nix () {
+	if test -n "${NIX-}" && command-exists nix-env; then
+		nix-env -iA "${NIX}"
+	else
+		return 1
+	fi
+}
+
+# xbps / Void Linux
+function do_xbps () {
+	if test -n "${XBPS-}" && command-exists xbps-install; then
+		xbps-install -S "${XBPS}"
+	else
+		return 1
+	fi
+}
+
+# eopkg / Solus
+function do_eopkg () {
+	if test -n "${EOPKG-}" && command-exists eopkg; then
+		sudo eopkg it "${EOPKG}"
+	else
+		return 1
+	fi
+}
+
+# emerge / GURU / Gentoo Linux
+function do_emerge () {
+	if test -n "${EMERGE_EVAL-}" && command-exists emerge; then
+		eval "${EMERGE_EVAL}"
+	elif test -n "${EMERGE-}" && command-exists emerge; then
+		sudo emerge -av "${EMERGE}"
+	else
+		return 1
+	fi
+}
+
+# dnf / COPR / Fedora / CentOS / RHEL
+function do_dnf () {
+	if test -n "${DNF_EVAL-}" && command-exists dnf; then
+		eval "${DNF_EVAL}"
+	elif test -n "${DNF-}" && command-exists dnf; then
+		if test -n "${DNF_COPR-}"; then
+			sudo dnf copr enable -y "${DNF_COPR}"
+		fi
+		if test -n "${DNF_REPO-}"; then
+			sudo dnf config-manager --add-repo "$DNF_REPO"
+		fi
+		sudo dnf install "${DNF}"
+	else
+		return 1
+	fi
+}
+
+# zypper / openSUSE / SLES
+function do_zypper () {
+	if test -n "${ZYPPER_EVAL-}" && command-exists zypper; then
+		eval "${ZYPPER_EVAL}"
+	elif test -n "${ZYPPER-}" && command-exists zypper; then
+		if test -n "${ZYPPER_REPO-}"; then
+			zypper addrepo "$ZYPPER_REPO"
+			zypper refresh
+		fi
+		zypper install "${ZYPPER}"
+	else
+		return 1
+	fi
+}
+
+# port / MacPorts
+function do_port () {
+	if test -n "${PORT-}" && command-exists port; then
+		sudo port install "${PORT}"
+	else
+		return 1
+	fi
+}
+
+# choco / Chocolatey / Windows
+function do_choco () {
+	if test -n "${CHOCO-}" && command-exists choco; then
+		choco install "${CHOCO}"
+	else
+		return 1
+	fi
+}
+
+# scoop / Windows
+function do_scoop () {
+	if test -n "${SCOOP-}" && command-exists scoop; then
+		scoop install "${SCOOP}"
+	else
+		return 1
+	fi
+}
+
+# winget / Windows Package Manager Client
+function do_winget () {
+	if test -n "${WINGET-}" && command-exists winget; then
+		winget install "${WINGET}"
+	else
+		return 1
+	fi
+}
+
+# pkg / FreeBSD / Termux
+function do_pkg () {
+	if test -n "${PKG-}" && command-exists pkg; then
+		pkg install "${PKG}"
+	else
+		return 1
+	fi
+}
+
+# pkgutil / Solaris 10+, Sparc and x86.
+function do_pkgutil () {
+	if test -n "${PKGUTIL-}" && command-exists pkgutil; then
+		pkgutil -i "${PKG}"
+	else
+		return 1
+	fi
+}
+
+# npm / Node.js
+function do_npm () {
+	if test -n "${NPM-}" && command-exists npm; then
+		npm install -g "${NPM}"
+	else
+		return 1
+	fi
+}
+
+# huber
+function do_huber () {
+	if test -n "${HUBER-}" && command-exists huber; then
+		huber install "${HUBER}"
+	else
+		return 1
+	fi
+}
+
+# guix
+function do_guix () {
+	if test -n "${GUIX-}" && command-exists guix; then
+		guix package -i "${GUIX}"
+	else
+		return 1
+	fi
+}
+
+# dpkg / Debian / Ubuntu / Linux Mint / elementary OS / etc
+function do_dpkg () {
+	if test -n "${DPKG_EVAL-}" && command-exists dpkg; then
+		eval "${DPKG_EVAL}"
+	else
+		return 1
+	fi
+}
+
+# doas / Solaris
+function do_doas () {
+	if test -n "${DOAS-}" && command-exists doas; then
+		doas pkg_add "${DOAS}"
+	else
+		return 1
+	fi
+}
+
+# pkg_add / OpenBSD
+function do_pkg () {
+	if test -n "${PKGADD-}" && command-exists pkg_add; then
+		pkg_add "${PKGADD}"
+	else
+		return 1
+	fi
+}
+
+# pkgin/ NetBSD
+function do_pkgin () {
+	if test -n "${PKGIN-}" && command-exists pkgin; then
+		pkgin install "${PKGIN}"
+	else
+		return 1
+	fi
+}
+
+# pkgman / Haiku
+function do_pkgman () {
+	if test -n "${PKGMAN-}" && command-exists pkgman; then
+		pkgman install "${PKGMAN}"
+	else
+		return 1
+	fi
+}
+
+# stack
+function do_stack () {
+	if test -n "${STACK-}" && command-exists stack; then
+		stack update
+		stack install "${STACK}"
+	else
+		return 1
+	fi
+}
+
+# cabal
+function do_cabal () {
+	if test -n "${CABAL-}" && command-exists cabal; then
+		cabal update
+		cabal install "${CABAL}"
+	else
+		return 1
+	fi
+}
+
+# conda
+function do_conda () {
+	if test -n "${CONDA-}" && command-exists conda; then
+		if test -n "${CONDA_CHANNEL-}"; then
+			conda install -c "${CONDA_CHANNEL}" "${CONDA}"
+		else
+			conda install "${CONDA}"
+		fi
+	else
+		return 1
+	fi
+}
+
+# pip / Python
+function do_pip () {
+	if test -n "${PIP-}" && pipp --version; then
+		pip-install "${PIP}"
+	else
+		return 1
+	fi
+}
+
+# cargo / Crates.io / Rust
+function do_cargo () {
+	if test -n "${CARGO-}" && command-exists cargo; then
+		if command-missing cargo; then
+			stderr echo 'missing dependency [rust], installing automatically...'
+			stderr setup-rust
+		fi
+		cargo install "${CARGO}"
+	else
+		return 1
+	fi
+}
+
+# curl / Manual Installer
+function do_curl () {
+	if test -n "${CURL-}" && command-exists curl; then
+		sh -c "$(fetch "$CURL")"
+	else
+		return 1
+	fi
+}
+
+# zip / Manual Installer
+function do_zip () {
+	if test -n "${ZIP-}"; then
+		mkdir -p "$HOME/bin"
+		if test -n "${ZIP_FILE-}"; then
+			down-zip-file "$ZIP" "$ZIP_FILE" "$HOME/bin"
+		else
+			down-zip-file "$ZIP" "$HOME/bin"
+		fi
+	else
+		return 1
+	fi
+}
+
+# -------------------------------------
+
+# arguments specify the order
+order=("$@")
+if test "${#order[@]}"; then
+	order=(
+		# intelligent
+		brew
+		cask
+
+		# precompiled
+		pacman
+		apt
+		apk
+		yum
+
+		# precompiled containers
+		snap
+
+		# source containers
+		# flatpack
+
+		# source
+		cargo
+		npm
+		pip
+
+		# unknown
+		yay
+		nix
+		xbps
+		eopkg
+		emerge
+		dnf
+		zypper
+		port
+		choco
+		scoop
+		winget
+		pkg
+		pkgutil
+		huber
+		guix
+		dpkg
+		doas
+		pkg
+		pkgin
+		pkgman
+		stack
+		cabal
+		conda
+		yay
+
+		# custom
+		curl
+		zip
+	)
+fi
+
+# cycle through the order
 if test -z "${FORCE-}" -a -n "${CLI-}" && command-exists "${CLI}"; then
 	echo "${CLI} already installed"
 	exit 0
-elif test -n "${BREW-}" && is-brew; then # brew / Homebrew / macOS
-	if test -n "${FORCE-}"; then
-		brew install "${BREW}" --force
-	else
-		brew install "${BREW}"
-	fi
-elif test -n "${CASK-}" && is-brew; then # brew / Homebrew / macOS
-	if test -n "${FORCE-}"; then
-		brew install --cask "${CASK}" --force
-	else
-		brew install --cask "${CASK}"
-	fi
-elif test -n "${YAY-}" && command-exists yay; then # yay / AUR / Arch Linux
-	yay -Sy "${YAY}"
-elif test -n "${SNAP-}" && command-exists snap; then # snap/ Snap Craft / Ubuntu
-	if test -n "${SNAP_CHANNEL-}"; then
-		snap install --channel="${SNAP_CHANNEL}" "${SNAP}"
-	else
-		snap install "${SNAP}"
-	fi
-elif test -n "${YUM_EVAL-}" && command-exists yum; then # yum / RedHat / Fedora / CentOS / etc
-	eval "${YUM_EVAL}"
-elif test -n "${YUM-}" && command-exists yum; then # yum / RedHat / Fedora / CentOS / etc
-	if test -n "${YUM_REPO-}"; then
-		cd /etc/yum.repos.d/ || exit 1
-		wget "$YUM_REPO"
-	fi
-	sudo yum install "${YUM}"
-elif test -n "${APT_EVAL-}" && is-apt; then # apt / Ubuntu / Debian / Linux Mint / elementary OS / etc
-	eval "${APT_EVAL}"
-elif test -n "${APT-}" && is-apt; then # apt / Ubuntu / Debian / Linux Mint / elementary OS / etc
-	if test -n "${APT_REPO-}"; then
-		sudo apt-add-repository -y "$APT_REPO"
-		sudo apt-get update
-	fi
-	sudo apt install -y "${APT}"
-elif test -n "${APK-}" && command-exists apk; then # apk / Alpine Linux
-	apk add "${APK}"
-elif test -n "${PACMAN-}" && command-exists pacman; then # pacman / Arch Linux
-	sudo pacman -S "${PACMAN}"
-elif test -n "${NIX-}" && command-exists nix-env; then # nix
-	nix-env -iA "${NIX}"
-elif test -n "${XBPS-}" && command-exists xbps-install; then # xbps / Void Linux
-	xbps-install -S "${XBPS}"
-elif test -n "${EOPKG-}" && command-exists eopkg; then # eopkg / Solus
-	sudo eopkg it "${EOPKG}"
-elif test -n "${EMERGE_EVAL-}" && command-exists emerge; then # emerge / GURU / Gentoo Linux
-	eval "${EMERGE_EVAL}"
-elif test -n "${EMERGE-}" && command-exists emerge; then # emerge / GURU / Gentoo Linux
-	sudo emerge -av "${EMERGE}"
-elif test -n "${DNF_EVAL-}" && command-exists dnf; then # dnf / COPR / Fedora / CentOS / RHEL
-	eval "${DNF_EVAL}"
-elif test -n "${DNF-}" && command-exists dnf; then # dnf / COPR / Fedora / CentOS / RHEL
-	if test -n "${DNF_COPR-}"; then
-		sudo dnf copr enable -y "${DNF_COPR}"
-	fi
-	if test -n "${DNF_REPO-}"; then
-		sudo dnf config-manager --add-repo "$DNF_REPO"
-	fi
-	sudo dnf install "${DNF}"
-elif test -n "${ZYPPER_EVAL-}" && command-exists zypper; then # zypper / openSUSE / SLES
-	eval "${ZYPPER_EVAL}"
-elif test -n "${ZYPPER-}" && command-exists zypper; then # zypper / openSUSE / SLES
-	if test -n "${ZYPPER_REPO-}"; then
-		zypper addrepo "$ZYPPER_REPO"
-		zypper refresh
-	fi
-	zypper install "${ZYPPER}"
-elif test -n "${PORT-}" && command-exists port; then # port / MacPorts
-	sudo port install "${PORT}"
-elif test -n "${CHOCO-}" && command-exists choco; then # choco / Chocolatey / Windows
-	choco install "${CHOCO}"
-elif test -n "${SCOOP-}" && command-exists scoop; then # scoop / Windows
-	scoop install "${SCOOP}"
-elif test -n "${WINGET-}" && command-exists winget; then # winget / Windows Package Manager Client
-	winget install "${WINGET}"
-elif test -n "${PKG-}" && command-exists pkg; then # pkg / FreeBSD / Termux
-	pkg install "${PKG}"
-elif test -n "${PKGUTIL-}" && command-exists pkgutil; then # pkgutil / Solaris 10+, Sparc and x86.
-	pkgutil -i "${PKG}"
-elif test -n "${NPM-}" && command-exists npm; then # npm / Node.js
-	npm install -g "${NPM}"
-elif test -n "${HUBER-}" && command-exists huber; then # huber
-	huber install "${HUBER}"
-elif test -n "${GUIX-}" && command-exists guix; then # guix
-	guix package -i "${GUIX}"
-elif test -n "${DPKG_EVAL-}" && command-exists dpkg; then # dpkg / Debian / Ubuntu / Linux Mint / elementary OS / etc
-	eval "${DPKG_EVAL}"
-elif test -n "${DOAS-}" && command-exists doas; then # doas / Solaris
-	doas pkg_add "${DOAS}"
-elif test -n "${PKGADD-}" && command-exists pkg_add; then # pkg_add / OpenBSD
-	pkg_add "${PKGADD}"
-elif test -n "${PKGIN-}" && command-exists pkgin; then # pkgin/ NetBSD
-	pkgin install "${PKGIN}"
-elif test -n "${PKGMAN-}" && command-exists pkgman; then # pkgman / Haiku
-	pkgman install "${PKGMAN}"
-elif test -n "${STACK-}" && command-exists stack; then # stack
-	stack update && stack install "${STACK}"
-elif test -n "${CABAL-}" && command-exists cabal; then # cabal
-	cabal update && cabal install "${CABAL}"
-elif test -n "${CONDA-}" && command-exists conda; then # conda
-	if test -n "${CONDA_CHANNEL-}"; then
-		conda install -c "${CONDA_CHANNEL}" "${CONDA}"
-	else
-		conda install "${CONDA}"
-	fi
-elif test -n "${PIP-}" && pipp --version; then # pip / Python
-	pip-install "${PIP}"
-elif test -n "${CARGO-}" && command-exists cargo; then # cargo / Crates.io / Rust
-	if command-missing cargo; then
-		stderr echo 'missing dependency [rust], installing automatically...'
-		stderr setup-rust
-	fi
-	# this should be one of the last, as cargo has to fetch binaries for every dependency
-	# rather than just using a precompiled bundle
-	cargo install "${CARGO}"
-elif test -n "${CURL-}" && command-exists curl; then # curl / Manual Installer
-	sh -c "$(fetch "$CURL")"
-elif test -n "${ZIP-}"; then # zip / Manual Installer
-	mkdir -p "$HOME/bin"
-	if test -n "${ZIP_FILE-}"; then
-		down-zip-file "$ZIP" "$ZIP_FILE" "$HOME/bin"
-	else
-		down-zip-file "$ZIP" "$HOME/bin"
-	fi
 else
-	stderr echo 'unable to install utility on this platform'
-	exit 1
+	for item in "${order[@]}"; do
+		(eval "do_${item}") && exit 0
+	done
 fi
+
+# failure
+if test -z "${CLI-}"; then
+	stderr echo 'unable to install the utility on this platform'
+	# env
+else
+	stderr echo "unable to install utility [${CLI-}] on this platform"
+fi
+exit 1
+
