setup-dns: update for select-dns, allow selection of options

diff --git a/commands/setup-dns b/commands/setup-dns
--- a/commands/setup-dns
+++ b/commands/setup-dns
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+source "$BDIR/sources/essentials.sh"
 source "$BDIR/sources/strict.bash"
 
 # -------------------------------------
@@ -19,7 +20,7 @@ function aghome_uninstall {
 	echo 'Uninstalling AdGuard Home...'
 	if command-exists AdGuardHome; then
 		ok sudo AdGuardHome -s uninstall
-		ok rm -vi "$HOME/bin/AdGuardHome"*
+		ok rm -vi "$HOME/bin/AdGuardHome" #*
 		echo 'Uninstalled AdGuard Home'
 	else
 		echo 'AdGuard Home is already uninstalled'
@@ -161,7 +162,7 @@ function dns_uninstall {
 	aghome_uninstall
 	dnscrypt_uninstall
 	cloudflared_uninstall
-	flush-dns 1.1.1.1
+	select-dns
 }
 
 function dns_configured {
@@ -175,21 +176,38 @@ function dns_configured {
 }
 
 function dns_setup {
-	dns_uninstall
-	if test "${1:-}" = "cloudflared"; then
-		cloudflared_setup
-	elif test "${1:-}" = "dnscrypt"; then
-		dnscrypt_setup
+	services=(
+		adguard-home
+		cloudflared
+		dnscrypt
+	)
+	service=""
+	if is-string "${1:-}"; then
+		service="$1"
+	elif is-string "${DNS_SERVICE:-}"; then
+		service="$DNS_SERVICE"
 	else
+		service="${1:-"$(choose "${services[@]}")"}"
+	fi
+
+	dns_uninstall
+	if test "$service" = "cloudflared"; then
+		cloudflared_setup
+	elif test "$service" = "dnscrypt"; then
+		dnscrypt_setup
+	elif test "$service" = "adguard-home" -o "$service" = "adguard"; then
 		aghome_setup
+	else
+		stderr echo "ERROR: setup-dns requires the DNS_SERVICE environment variable to be set, or requires a service to be specified, available services are: ${services[*]}"
+		exit 1
 	fi
 }
 
 if test "${1:-}" = "uninstall"; then
 	dns_uninstall
-elif (test -z "${1:-}" && dns_configured) || (dns_setup "$1" && flush-dns 127.0.0.1 && dns_configured); then
+elif (test -z "${1:-}" && dns_configured) || (dns_setup "${1:-}" && select-dns local && dns_configured); then
 	echo 'DNS setup complete'
 else
-	flush-dns 1.1.1.1
+	select-dns
 	echo 'DNS setup FAILED'
 fi
