fs-dequarantine, setup-util-brew: fix peculiarities
- fs-dequarantine: no longer uses complex fallback method, and checks for approprite method first
- setup-util-brew: add debugging for unexpected environment configuration

```
xattr: /Users/runner/.local/bin/bash: No such xattr: com.apple.quarantine
The [bash] required utility was not upgraded via [download]
/Users/runner/.local/share/dorothy/commands/setup-util-brew: line 55: HOMEBREW_ARCH: unbound variable
```

> https://github.com/bevry/dorothy/actions/runs/7499530414/job/20416492860#step:3:32

diff --git a/commands/setup-util-brew b/commands/setup-util-brew
--- a/commands/setup-util-brew
+++ b/commands/setup-util-brew
@@ -8,17 +8,21 @@ function setup_util_brew() (
 		return 0
 	fi
 
+	# environment provides:
+	# HOMEBREW_ARCH, HOMEBREW_PREFIX
+	if test -z "${HOMEBREW_ARCH-}" -o -z "${HOMEBREW_PREFIX-}"; then
+		echo-error 'HOMEBREW_ARCH and HOMEBREW_PREFIX are missing, cannot setup brew, for some reason this was executed before the Dorothy environment was configured'
+		uname -a
+		uname -s
+		env >&2
+		return 6 # ENXIO 6 Device not configured
+	fi
+
 	# enable EVAL_INSTALL, etc
 	source "$(type -P setup-util)"
 
 	# uninstall brew, and adapt the system accordingly
 	function brew_uninstall {
-		# environment provides:
-		# HOMEBREW_ARCH, HOMEBREW_PREFIX
-		if test -z "${HOMEBREW_PREFIX-}"; then
-			echo-error 'HOMEBREW_PREFIX is not defined, cannot uninstall brew.'
-			return 6 # ENXIO 6 Device not configured
-		fi
 		local remove removals=(
 			"${HOMEBREW_PREFIX}/"*
 			/usr/local/*
@@ -37,7 +41,7 @@ function setup_util_brew() (
 
 		# uninstall brew
 		if is-brew; then
-			arch -"${HOMEBREW_ARCH}" /bin/bash -c "$(fetch https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)" -- --force
+			arch "-${HOMEBREW_ARCH}" /bin/bash -c "$(fetch https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)" -- --force
 		fi
 
 		# remove any leftover directories
@@ -53,7 +57,7 @@ function setup_util_brew() (
 	# https://github.com/balupton/dotfiles/commit/69dbbe81bf30f9e0d9a1dd1d00eca3f3c88b943b
 	function brew_install {
 		env HOMEBREW_NO_AUTO_UPDATE=1 \
-			arch -"${HOMEBREW_ARCH}" /bin/bash -c "$(fetch https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+			arch "-${HOMEBREW_ARCH}" /bin/bash -c "$(fetch https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 		source "$DOROTHY/sources/environment.sh" # child processes will also inherit these changes
 	}
 
