setup-util: fix sd failure if rust missing

diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -464,6 +464,17 @@ else
 	done
 fi
 
+# fallback to installable package systems
+# @todo eventually support multiple, and do it in the order
+if test -n "${CARGO-}" && is-needle cargo "${order[@]}" && command-missing cargo; then
+	echo "Possibly failed to install [${CLI-}] because rust was missing."
+	echo 'Will setup rust and try again...'
+	source "$DOROTHY/commands/setup-rust" # source for PATH
+	setup-util "$@"
+	exit $?
+fi
+	
+
 # failure
 if test -z "${CLI-}"; then
 	stderr echo 'unable to install the utility on this platform'
