setup-util: output progress as it happens (#76)
other changes:

- `echo-color` now supports a `-n` flag as first argument, to prevent trailing newline
- added `echo-clear-lines` to clear all lines from args or stdin

diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -61,36 +61,41 @@ function lost() {
 	return "$ec"
 }
 function act() {
-	local ec output
-	ec=0 && output="$("$@" 2>&1)" || ec=$?
+	# prepare
+	local ec log status
+	log="$(mktemp)"
+
+	# header
+	echo-color --dim+h3='< ' --h3="$*" --dim+h3=' >'
+
+	# command
+	ec=0 && ("$@" 2>&1 | tee "$log") || ec="$?"
 	if test "$ec" -eq 0; then
-		# only show success when quiet=no, not quiet='', quiet=yes
-		if test "$QUIET" = 'no'; then
-			if test -n "$output"; then
-				echo-color \
-					--dim+h3='< ' --h3="$*" --dim+h3=' >' $'\n' \
-					--dim="$output" $'\n' \
-					--dim+h3='</ ' --h3="$*" --dim+h3=' >' \
-					--g3="[$ec]" # ' ✅'
-			else
-				echo-color \
-					--dim+h3='< ' --h3="$*" --dim+h3=' />' \
-					--g3="[$ec]" # ' ✅'
-			fi
+		# unless QUIET=no (verbose mode) then hide all success
+		if test "$QUIET" != 'no'; then
+			# hide header
+			echo-clear-line
+			# hide output
+			echo-clear-lines <"$log"
+			# return
+			return "$ec"
 		fi
+		# success status
+		status="$(echo-color -n --g3="[$ec]")"
 	else
-		# always show failure
-		if test -n "$output"; then
-			echo-color \
-				--dim+h3='< ' --h3="$*" --dim+h3=' >' $'\n' \
-				--dim="$output" $'\n' \
-				--dim+h3='</ ' --h3="$*" --dim+h3=' >' \
-				--e3="[$ec]" # ' ❌'
-		else
-			echo-color \
-				--dim+h3='< ' --h3="$*" --dim+h3=' />' \
-				--e3="[$ec]" # ' ❌'
-		fi
+		# failure status
+		status="$(echo-color -n --e3="[$ec]")"
+	fi
+
+	# did the command output anything?
+	if test -z "$(cat "$log")"; then
+		# if not, hide header
+		echo-clear-line
+		# and output header footer combo
+		echo-color --dim+h3='< ' --h3="$*" --dim+h3=' />' "$status"
+	else
+		# if it did, then output a footer
+		echo-color --dim+h3='</ ' --h3="$*" --dim+h3=' >' "$status"
 	fi
 	return "$ec"
 }
