stylise `setup-mac-brew-uninstall` (progress #74)

diff --git a/commands/setup-mac-brew-uninstall b/commands/setup-mac-brew-uninstall
--- a/commands/setup-mac-brew-uninstall
+++ b/commands/setup-mac-brew-uninstall
@@ -1,20 +1,26 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 source "$DOROTHY/sources/nullglob.bash"
-# we can assume [HOMEBREW_ARCH, HOMEBREW_PREFIX] have already been provided
 
-# Remove nvm
-rm -Rf "$HOME/.nvm"
+# environment provides:
+# HOMEBREW_ARCH, HOMEBREW_PREFIX
 
-# Reconfigure shells for the lack of brew, by trimming the brew shells
-t="$(mktemp)"
-sudo bash <<EOF
-grep -v "${HOMEBREW_PREFIX}" /etc/shells > "$t"
-cat "$t" > /etc/shells
-rm "$t"
-EOF
+# prepare
+removals=(
+	"${NVM_DIR-}"
+	"$HOME/.nvm"
+	"${HOMEBREW_PREFIX}/"*
+	/usr/local/*
+	/opt/homebrew/*
+)
 
-# Set the default shell to a non-brew shell
+# log
+echo-segment --h1='Uninstall Homebrew'
+
+# reconfigure shells for the lack of brew, by trimming the brew shells
+grep -v "$HOMEBREW_PREFIX" /etc/shells | sudo sponge /etc/shells
+
+# set the default shell to a non-brew shell
 if command-exists /bin/zsh; then
 	select-shell /bin/zsh
 elif command-exists /bin/bash; then
@@ -23,17 +29,22 @@ elif command-exists /bin/sh; then
 	select-shell /bin/sh
 fi
 
-# Reset anything that depends on brew
+# reset anything that depends on brew
 setup-dns system || :
 env GIT_PROTOCOL=manual setup-git || :
 
-# Remove brew
+# uninstall brew
 if is-brew; then
 	arch -"${HOMEBREW_ARCH}" /bin/bash -c "$(fetch https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)" -- --force
 fi
-sudo rm -Rf "${HOMEBREW_PREFIX}/"* || :
-sudo rm -Rf /usr/local/* || :
-sudo rm -Rf /opt/homebrew/* || :
 
-# Done
-echo 'brew is now uninstalled, restart your terminal'
+# remove any leftover directories
+for remove in "${removals[@]}"; do
+	if test -n "$remove" -a -e "$remove"; then
+		sudo rm -Rf "$remove" || :
+	fi
+done
+
+# log
+echo-segment --g1='Uninstall Homebrew'
+echo-color --green+bold='Homebrew uninstalled, ' --red+bold+underline='restart your terminal to avoid errors.'
