setup-util-deno: disable cargo on WSL
dorothy: log platform and bash details on tests

need to find out why deno DOWNLOAD option is not filling on windows

diff --git a/commands/setup-util-deno b/commands/setup-util-deno
--- a/commands/setup-util-deno
+++ b/commands/setup-util-deno
@@ -55,12 +55,15 @@ function setup_util_deno() (
 		APK='deno'
 		AUR='deno' # ARCH
 		BREW='deno'
-		CARGO='deno'
 		CHOCO='deno'
 		PORT='deno'
 		SCOOP='deno'
 		WINGET='DenoLand.Deno'
 	)
+	# cargo fails on windows: https://github.com/bevry/dorothy/actions/runs/16106748853/job/45443438885
+	if ! is-wsl; then
+		options+=(CARGO='deno')
+	fi
 	arch="$(get-arch)"
 	function get_github_asset_url {
 		github-download \
