split xcode into apple-cli-tools and apple-rosetta
- xcode app is not minimal dep only apple-cli-tools and apple-rosetta are
- xcode app is what requires tos agreement

diff --git a/commands/setup-util-xcode b/commands/setup-util-xcode
--- a/commands/setup-util-xcode
+++ b/commands/setup-util-xcode
@@ -25,17 +25,9 @@ function setup_util_xcode() (
 	# check if xcode exists
 	local xcode xcodebuild xcodesdk
 	while true; do
-		# rosetta
-		if is-apple-silicon && test ! -f /Library/Apple/usr/share/rosetta/rosetta; then
-			sudo-helper -- softwareupdate --install-rosetta --agree-to-license
-			continue # try again
-		fi
-
-		# xcode cli tools
-		if xcode-select --install &>/dev/null; then
-			confirm --ppid=$$ -- 'Press <enter> once the Apple Command Line Tools have been installed...'
-			continue # try again
-		fi
+		# prerequisites
+		setup-util-apple-rosetta --quiet="$quiet"
+		setup-util-apple-cli-tools --quiet="$quiet"
 
 		# determine xcode location
 		xcode="$(get-app 'Xcode' || get-app 'Xcode-beta' || :)"
@@ -52,7 +44,7 @@ function setup_util_xcode() (
 			continue # try again
 		fi
 
-		# confirm it all works
+		# confirm xcode sdk exists
 		if test ! -x "$xcodebuild" || ! "$xcodebuild" -sdk "$xcodesdk" -find clang &>/dev/null; then
 			echo-style --notice="Xcode SDKs require manual installation, opening Xcode..."
 			open "$xcode"
@@ -60,13 +52,13 @@ function setup_util_xcode() (
 			continue # try again
 		fi
 
-		# xcode cli tools license
-		function xcode_license_accepted {
+		# xcode sdk license
+		function xcode_license_accepted { # 👍 /docs/bash/errors: robust exit status
 			# https://stackoverflow.com/a/60906147/130638
 			local xcode_version accepted_license_version
 			xcode_version="$("$xcodebuild" -version | grep '^Xcode\s' | sed -E 's/^Xcode[[:space:]]+([0-9\.]+)/\1/' | cut -d '.' -f 1 || :)"
 			accepted_license_version="$(defaults read /Library/Preferences/com.apple.dt.Xcode 2>/dev/null | grep IDEXcodeVersionForAgreedToGMLicense | cut -d '"' -f 2 | cut -d '.' -f 1 || :)"
-			test "$xcode_version" -eq "$accepted_license_version" || sudo-helper -- "$xcodebuild" -license accept
+			test "$xcode_version" -eq "$accepted_license_version" || sudo-helper -- "$xcodebuild" -license accept || return
 		}
 		if test "$quiet" = 'yes'; then
 			xcode_license_accepted || continue # try again
