better capability detection
- `arrays.bash` now offers functions for precise array capability detection and handling
- `{extglob,nullglob,globstar}.bash` now mandate requirement
- `config/shell.bash` created to auto-upgrade bash login shell capabilities, as fish will break with anything complex
- added `echo-element` to simplify element styling
- `echo-collapse` now uses `echo-element` for styling, even if in simple mode
- `find-files` rewritten and improved
- `select-shell` now loads `environment.bash` in case homebrew was just installed and the login shell hasn't adapted yet
- `setup-dorothy` now uses `echo-element` for styling code blocks, and improved bash upgrade flow
- `setup-mac-brew` moves bash upgrade flow to `setup-util-bash`
- `setup-util-bash` now handles forcing login shell upgrade
- `shell.sh` keep `export VAR=...` recommendation, as needed for compat with fish shell
- `themes/oz` fix fish shell support

diff --git a/commands/setup-mac-brew b/commands/setup-mac-brew
--- a/commands/setup-mac-brew
+++ b/commands/setup-mac-brew
@@ -155,41 +155,24 @@ else
 	# https://github.com/balupton/dotfiles/commit/69dbbe81bf30f9e0d9a1dd1d00eca3f3c88b943b
 	echo-color --h2='Installing Homebrew via its recomended method...'
 	arch -"${HOMEBREW_ARCH}" /bin/bash -c "$(fetch https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-	source "$DOROTHY/sources/environment.sh"
+	source "$DOROTHY/sources/environment.sh" # child processes will also inherit these changes
 	echo-color --g2='Homebrew is now installed.'
 fi
 
-# check arrays in case we need to install bash and reload
-source "$DOROTHY/sources/arrays.bash"
-if test "$ARRAYS" != 'yes'; then
-	echo-color --h2='Bash version too outdated for proper array support, upgrading bash...'
-	brew install bash
+# ensure latest bash version is being used
+if [[ "$BASH_VERSION" != "5."* ]]; then
+	echo-color --h2='Bash version is outdated, upgrading bash...'
+	setup-util-bash # upgrade bash from a legacy version
 	echo-color --g2='Bash has been upgraded.'
 	echo-color --h2='Reloading setup with the upgraded bash.'
-	setup-mac-brew "$@"
-	exit "$?" # exit with the above on success and failure
+	setup-mac-brew "$@" # this will inherit the environment changes of a new homebrew install
+	exit "$?"           # exit with the above on success and failure
+else
+	setup-util-bash # upgrade bash from the last version
 fi
-
-# check the login shell is not outdaetd
-# shellcheck disable=SC2016
-{
-	login_shell="${SHELL-}"
-	bash_shell="$(which bash)"
-	if test -n "$login_shell"; then
-		login_shell_name="$(basename "$login_shell")"
-		if test "$login_shell_name" = 'bash' -a "$login_shell" != "$bash_shell"; then
-			login_shell_version="$("$login_shell" -c -- 'echo $BASH_VERSION')"
-			bash_shell_version="$("$bash_shell" -c -- 'echo $BASH_VERSION')"
-			if test "$login_shell_version" != "$bash_shell_version"; then
-				echo-color --h2="Your login shell is an outdated version of bash."
-				echo-color --h2="You will now be prompted now to change it to a more modern shell."
-				select-shell
-				echo-color --h2="Close this terminal, open a new one, then run the command you ran again."
-				exit
-			fi
-		fi
-	fi
-}
+# sanity check array support
+source "$DOROTHY/sources/arrays.bash"
+requires_array_support 'mapfile' 'empty'
 
 # =====================================
 # Deprecations
