setup-util: improve github/installer messaging

diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -1710,7 +1710,7 @@ function setup-util() (
 
 	# github
 	function do_github {
-		local slug="$GITHUB_SLUG" filename="$GITHUB_FILENAME" ref="$GITHUB_REF" release="$GITHUB_RELEASE" pathname="$GITHUB_PATHNAME" asset_filter="$GITHUB_ASSET_FILTER" unzip_format="$GITHUB_UNZIP_FORMAT" unzip_filter="$GITHUB_UNZIP_FILTER"
+		local file slug="$GITHUB_SLUG" filename="$GITHUB_FILENAME" ref="$GITHUB_REF" release="$GITHUB_RELEASE" pathname="$GITHUB_PATHNAME" asset_filter="$GITHUB_ASSET_FILTER" unzip_format="$GITHUB_UNZIP_FORMAT" unzip_filter="$GITHUB_UNZIP_FILTER"
 
 		# check applicabile
 		if test -n "$slug"; then
@@ -1720,14 +1720,15 @@ function setup-util() (
 				return 1
 			fi
 
-			# uninstall?
-			if test "$uninstall" = 'yes'; then
-				rm -f "$XDG_BIN_HOME/$filename"
-				return 0
-			fi
-
 			# prepare
 			mkdir -p "$XDG_BIN_HOME"
+			file="$XDG_BIN_HOME/$filename"
+
+			# uninstall?
+			if test "$uninstall" = 'yes'; then
+				rm -f "$file"
+				return 0
+			fi
 
 			# download
 			github-download \
@@ -1739,14 +1740,14 @@ function setup-util() (
 				--asset-filter="$asset_filter" \
 				--unzip-format="$unzip_format" \
 				--unzip-filter="$unzip_filter" \
-				--path="$XDG_BIN_HOME/$filename"
+				--path="$file"
 
 			# adjust
-			fs-own --permissions='+x' "$XDG_BIN_HOME/$filename"
+			fs-own --permissions='+x' "$file"
 
 			# verify
-			if ! command-working "$XDG_BIN_HOME/$filename"; then
-				echo-style --error="GITHUB installed, however failed to verify."
+			if ! command-working "$file"; then
+				echo-style --error="$file installed, however failed to verify."
 				return 1
 			fi
 		else
@@ -1757,7 +1758,7 @@ function setup-util() (
 
 	# download
 	function do_download {
-		local download="$DOWNLOAD" filename="$DOWNLOAD_FILENAME" unzip_format="$DOWNLOAD_UNZIP_FORMAT" unzip_filter="$DOWNLOAD_UNZIP_FILTER"
+		local file download="$DOWNLOAD" filename="$DOWNLOAD_FILENAME" unzip_format="$DOWNLOAD_UNZIP_FORMAT" unzip_filter="$DOWNLOAD_UNZIP_FILTER"
 
 		# check applicabile
 		if test -n "$download"; then
@@ -1767,28 +1768,29 @@ function setup-util() (
 				return 1
 			fi
 
+			# prepare
+			file="$XDG_BIN_HOME/$filename"
+			mkdir -p "$XDG_BIN_HOME"
+
 			# uninstall?
 			if test "$uninstall" = 'yes'; then
-				rm -f "$XDG_BIN_HOME/$filename"
+				rm -f "$file"
 				return 0
 			fi
-
-			# prepare
-			mkdir -p "$XDG_BIN_HOME"
 
 			# download
 			down "$download" \
 				--quiet="$quiet" \
 				--unzip-format="$unzip_format" \
 				--unzip-filter="$unzip_filter" \
-				--path="$XDG_BIN_HOME/$filename"
+				--path="$file"
 
 			# adjust
-			fs-own --permissions='+x' "$XDG_BIN_HOME/$filename"
+			fs-own --permissions='+x' "$file"
 
 			# verify
-			if ! command-working "$XDG_BIN_HOME/$filename"; then
-				echo-style --error="DOWNLOAD installed, however failed to verify."
+			if ! command-working "$file"; then
+				echo-style --error="$file installed, however failed to verify."
 				return 1
 			fi
 		else
