pip-install, pipp, setup-python: attempt to install pip on systems where it does not exist

diff --git a/commands/setup-python b/commands/setup-python
--- a/commands/setup-python
+++ b/commands/setup-python
@@ -1,6 +1,13 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
+# Helper
+function pipinstall {
+	for ARG in "$@"; do
+		pip-install "$ARG"
+	done
+}
+
 # Uninstall Python
 if is-brew; then
 	echo -e '\nRemoving old brew python installations...'
@@ -13,27 +20,24 @@ if is-brew; then
 	brew install python
 fi
 
-# Helper
-function pipinstall {
-	for ARG in "$@"; do
-		pip-install "$ARG"
-	done
-}
+# Reload Paths
+echo -e '\nReload paths and install latest pip tooling...'
+source "$DOROTHY/sources/essentials.sh"
+
+# Ensure pip exists
+if ! pipp --version; then
+	echo "Could not find pip, installig it manually..."
+	curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
+fi
 
 # Reload Paths
 echo -e '\nReload paths and install latest pip tooling...'
 source "$DOROTHY/sources/essentials.sh"
-echo "python3=$(which python3)"
-echo "pip3=$(which pip3)"
-echo "pip=$(which pip)"
 pipinstall pip setuptools
 
 # Reload Paths
-	echo -e '\nReload paths for latest pip tooling...'
+echo -e '\nReload paths for latest pip tooling...'
 source "$DOROTHY/sources/essentials.sh"
-echo "python3=$(which python3)"
-echo "pip3=$(which pip3)"
-echo "pip=$(which pip)"
 
 # Install
 if is-present "${PYTHON_INSTALL-}"; then
