setup-mac-brew: ecosystem compatibility
don't support updating ffmpeg (for now)

remove zvbi flag, as no longer supported

diff --git a/commands/setup-mac-brew b/commands/setup-mac-brew
--- a/commands/setup-mac-brew
+++ b/commands/setup-mac-brew
@@ -536,58 +536,56 @@ function setup-mac-brew() (
 					--field='HOMEBREW_ENCODING_INSTALL' --value="$HOMEBREW_ENCODING_INSTALL"
 			fi
 		fi
+	fi
 
-		# if yes, then install the linting tools
-		if test "$HOMEBREW_ENCODING_INSTALL" = 'yes'; then
-			echo-segment --h1="Homebrew encoding tools"
-			echo-style --notice="This can take a while... ⏲"
+	# if yes, then install the linting tools
+	if test "$HOMEBREW_ENCODING_INSTALL" = 'yes'; then
+		echo-segment --h1="Homebrew encoding tools"
+		echo-style --notice="This can take a while... ⏲"
 
-			# install dependencies:
-			# https://github.com/varenc/homebrew-ffmpeg/issues/28
-			# https://trac.ffmpeg.org/wiki/CompilationGuide/MacOSX
-			# @todo perhaps this entire encoding section can become modifiers to the existing operations
-			brew_install_fast "${HOMEBREW_ENCODING_FORMULAS[@]}"
+		# install dependencies:
+		# https://github.com/varenc/homebrew-ffmpeg/issues/28
+		# https://trac.ffmpeg.org/wiki/CompilationGuide/macOS
+		# @todo perhaps this entire encoding section can become modifiers to the existing operations
+		brew_install_fast "${HOMEBREW_ENCODING_FORMULAS[@]}"
 
-			# Installing chromaprint will cause ffmpeg to be installed automatically, as such we need to remove that ffmpeg
-			# so that we can install the one with the build options
-			# Uninstall is necessary to prevent:
-			#     Error: ffmpeg is already installed
-			# --ignore-dependencies is necessary to prevent:
-			#     Error: Refusing to uninstall because it is required by chromaprint, which is currently installed.
-			#     Error: chromaprint not found
-			# More details:
-			# https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/13#issuecomment-647408007
-			brew_uninstall ffmpeg homebrew-ffmpeg/ffmpeg/ffmpeg || :
+		# Installing chromaprint will cause ffmpeg to be installed automatically, as such we need to remove that ffmpeg
+		# so that we can install the one with the build options
+		# Uninstall is necessary to prevent:
+		#     Error: ffmpeg is already installed
+		# --ignore-dependencies is necessary to prevent:
+		#     Error: Refusing to uninstall because it is required by chromaprint, which is currently installed.
+		#     Error: chromaprint not found
+		# More details:
+		# https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/13#issuecomment-647408007
+		brew_uninstall ffmpeg homebrew-ffmpeg/ffmpeg/ffmpeg || :
 
-			# log
-			echo-segment --h2="Install ffmpeg with options"
+		# log
+		echo-segment --h2="Install ffmpeg with options"
 
-			# fetch all the build options for ffmpeg
-			local ffmpeg_opts
-			ffmpeg_opts="$(brew options homebrew-ffmpeg/ffmpeg/ffmpeg --compact)"
-			# Remove options that break ffmpeg
-			# Resolved: https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/81#issuecomment-828722622
-			# Fails: https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/92
-			ffmpeg_opts="${ffmpeg_opts/--with-decklink /}"
-			# Fails: https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/37#issuecomment-958018136
-			ffmpeg_opts="${ffmpeg_opts/--with-game-music-emu /}"
-			# space seperated array
-			mapfile -t ffmpeg_opts < <(echo-split ' ' -- "$ffmpeg_opts")
+		# fetch all the build options for ffmpeg
+		local ffmpeg_opts
+		ffmpeg_opts="$(brew options homebrew-ffmpeg/ffmpeg/ffmpeg --compact)"
+		# Remove options that break ffmpeg
+		# Resolved: https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/81#issuecomment-828722622
+		# Fails: https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/92
+		ffmpeg_opts="${ffmpeg_opts/--with-decklink /}"
+		# Fails: https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/37#issuecomment-958018136
+		ffmpeg_opts="${ffmpeg_opts/--with-game-music-emu /}"
+		# Fails: Error: An exception occurred within a child process: FormulaUnavailableError: No available formula with the name "zvbi".
+		ffmpeg_opts="${ffmpeg_opts/--with-libzvbi /}"
+		# space seperated array
+		mapfile -t ffmpeg_opts < <(echo-split ' ' -- "$ffmpeg_opts")
 
-			# install with the build options
-			eval-helper --quiet \
-				-- brew install homebrew-ffmpeg/ffmpeg/ffmpeg "${ffmpeg_opts[@]}"
+		# install with the build options
+		eval-helper --quiet \
+			-- brew install homebrew-ffmpeg/ffmpeg/ffmpeg "${ffmpeg_opts[@]}"
 
-			# log
-			echo-segment --g2="Install ffmpeg with options"
-			echo-segment --g1="Homebrew encoding tools"
-		else
-			echo-style --notice="Skipped encoding tools installation, due to preference."
-		fi
-	elif test "$HOMEBREW_ENCODING_INSTALL" = 'yes'; then
-		echo-style --notice="Skipped encoding tools installation, due to update only."
+		# log
+		echo-segment --g2="Install ffmpeg with options"
+		echo-segment --g1="Homebrew encoding tools"
 	else
-		echo-style --notice="Skipped encoding tools installation, due to preference and update only"
+		echo-style --notice="Skipped encoding tools installation, due to preference."
 	fi
 
 	# -------------------------------------
