setup-git: authenticate with CLIs after everything else

diff --git a/commands/setup-git b/commands/setup-git
--- a/commands/setup-git
+++ b/commands/setup-git
@@ -203,30 +203,11 @@ function setup-git() (
 	echo-style --h2='Git Configuration: Auth'
 	if test -n "$GITHUB_USERNAME"; then
 		git config --global github.user "$GITHUB_USERNAME"
-		# only install if github is configured
-		if setup-util-gh --optional && command-exists gh; then
-			if ! gh auth status &>/dev/null; then
-				if confirm-negative --ppid=$$ -- "Authenticate with the GitHub CLI?"; then
-					gh auth login
-				fi
-			fi
-		fi
 	else
 		git config --global --unset github.user || : # will fail if already unset
 	fi
 	if test -n "$GITLAB_USERNAME"; then
 		git config --global gitlab.user "$GITLAB_USERNAME"
-		# glab writes to stderr, grep needed as return status is not indicative
-		# wrap in `! (` is to catch failures in the grep, and in the glab call
-
-		# setup-util-glab # only install if gitlab is configured
-		# if ! (glab auth status |& grep --quiet --fixed-strings --regexp='Logged in to '); then
-		# 	glab auth login
-		# fi
-
-		# ^ currently broken
-		# > glab auth login
-		# failed to read configuration:  open /home/ubuntu/.config/glab-cli/.config.yml2800055398: permission denied
 	else
 		git config --global --unset gitlab.user || : # will fail if already unset
 	fi
@@ -372,6 +353,33 @@ function setup-git() (
 	# SSH
 
 	ssh-helper configure
+
+	# =====================================
+	# Authenticate with CLIs
+
+	# Must be done here, as they depend on git and ssh being correctly configured
+
+	if test -n "$GITHUB_USERNAME"; then
+		setup-util-gh --optional
+		if command-exists gh && ! gh auth status &>/dev/null; then
+			# installed but not authenticated
+			if confirm-negative --ppid=$$ -- "Authenticate with the GitHub CLI?"; then
+				gh auth login
+			fi
+		fi
+	fi
+
+	# if test -n "$GITLAB_USERNAME"; then
+	# glab writes to stderr, grep needed as return status is not indicative
+	# wrap in `! (` is to catch failures in the grep, and in the glab call
+	# setup-util-glab--optional # only install if gitlab is configured
+	# if ! (glab auth status |& grep --quiet --fixed-strings --regexp='Logged in to '); then
+	# 	glab auth login
+	# fi
+	# ^ currently broken
+	# > glab auth login
+	# failed to read configuration:  open /home/ubuntu/.config/glab-cli/.config.yml2800055398: permission denied
+	# fi
 
 	# =====================================
 	# Done
