setup-linux: fix fresh snap on fedora

diff --git a/commands/setup-linux b/commands/setup-linux
--- a/commands/setup-linux
+++ b/commands/setup-linux
@@ -204,7 +204,7 @@ function setup-linux() (
 		if ! is-snap; then
 			return 0
 		fi
-		sudo snap refresh
+		sudo snap refresh || : # if snap was just installed on fedora, this can fail initially
 	}
 
 	function do_yum_upgrade {
