update syntax convention for ask/confirm/choose

diff --git a/commands/setup-mac b/commands/setup-mac
--- a/commands/setup-mac
+++ b/commands/setup-mac
@@ -33,7 +33,11 @@ if test "${1-}" = 'install'; then
 fi
 
 # action
-action="$(choose-option --question='Do you want to install or update this system?' --filter="${1-}" -- 'install' 'update' || echo "${1:-install}")" # or condition here is for bash v3, which choose-option will fail on, as bash v3 does not yet support arrays
+action="$(
+	choose-option \
+		--question='Do you want to install or update this system?' \
+		--filter="${1-}" -- 'install' 'update' || echo "${1:-install}"
+)" # or condition here is for bash v3, which choose-option will fail on, as bash v3 does not yet support arrays
 
 # =====================================
 # Start
