setup-dorothy: fix empty repo issue

diff --git a/commands/setup-dorothy b/commands/setup-dorothy
--- a/commands/setup-dorothy
+++ b/commands/setup-dorothy
@@ -12,14 +12,21 @@ if test -z "${DOROTHY-}"; then
 	fi
 fi
 
+# extract options
+action="${1-}"
+skipShell="${DOROTHY_SKIP_SHELL-}"
+skipUpdate="${DOROTHY_SKIP_UPDATE-}"
+skipUser="${DOROTHY_SKIP_USER-}"
+userRepo="${DOROTHY_USER_REPO-}"
+
 # determine intent
-if test "${1-}" = 'update'; then
-	DOROTHY_SKIP_SHELL='yes'
+if test "$action" = 'update'; then
+	skipShell='yes'
 fi
 
 # update or install dorothy
 if test -d "$DOROTHY"; then
-	if test -z "${DOROTHY_SKIP_UPDATE-}"; then
+	if test -z "$skipUpdate"; then
 		# update
 		echo
 		echo "Updating the Dorothy installation at $DOROTHY"
@@ -66,7 +73,7 @@ fi
 
 # update or install user
 if test -d "$DOROTHY/user"; then
-	if test -z "${DOROTHY_SKIP_UPDATE-}"; then
+	if test -z "$skipUpdate"; then
 		# update
 		echo
 		echo "Updating the Dorothy user configuration at $DOROTHY/user"
@@ -91,11 +98,10 @@ if test -d "$DOROTHY/user"; then
 else
 	echo
 	# check for skip
-	if test -z "${DOROTHY_SKIP_USER-}"; then
+	if test -z "$skipUser"; then
 		# install
-		if test -z "${DOROTHY_USER_REPO-}"; then
+		if test -z "$userRepo"; then
 			# can't use truthy, or ok command yet, as still installing
-			repo=''
 			status='404'
 			user="${DOROTHY_USER-}"  # allow setting via environment variable
 			if test -z "$user"; then
@@ -110,14 +116,12 @@ else
 			echo "Dorothy houses user configuration inside its own git repository."
 			if test -n "$user"; then
 				status="$("$DOROTHY/commands/http-status" "https://github.com/$user/dotfiles")"
-				repo="https://github.com/$user/dotfiles.git"
-				if test "$status" -eq 200; then
-					if ! "$DOROTHY/commands/confirm-bool" "Does this repository house your Dorothy user configuration? [$repo]"; then
-						repo=''
-					fi
+				userRepo="https://github.com/$user/dotfiles.git"
+				if ! ( test "$status" -eq 200 && "$DOROTHY/commands/confirm-bool" "Does this repository house your Dorothy user configuration? [$userRepo]" ); then
+					userRepo=''
 				fi
 			fi
-			if test -z "$repo"; then
+			if test -z "$userRepo"; then
 				echo "If you don't have a repository for it yet, then create one at https://github.com/new using the following details:"
 				printf "\tRepository name: dotfiles\n"
 				printf "\tDescription: My user configuration for the Dorothy dotfile ecosystem: https://github.com/bevry/dorothy\n"
@@ -126,20 +130,20 @@ else
 				echo ''
 				echo 'Once you have created a repository to house your Dorothy user configuration, then type its URL below.'
 				if test -n "$user"; then
-					repo="https://github.com/$user/dotfiles.git"
-					printf "\tor press ENTER to confirm its URL as [%s]\n" "$repo"
+					userRepo="https://github.com/$user/dotfiles.git"
+					printf "\tor press ENTER to confirm its URL as [%s]\n" "$userRepo"
 				fi
-				read -r -p "> " DOROTHY_USER_REPO
-				if test -z "$DOROTHY_USER_REPO"; then
-					export DOROTHY_USER_REPO="$repo"
+				read -r -p "> " manualRepo
+				if test -n "$manualRepo"; then
+					userRepo="$manualRepo"
 				fi
 			fi
 		fi
 
 		# clone
 		echo "Cloning the Dorothy user configuration into $DOROTHY/user"
-		if ! git clone "$DOROTHY_USER_REPO" "$DOROTHY/user"; then
-			echo "The clone of the repository [$DOROTHY_USER_REPO] to [$DOROTHY/user] failed."
+		if ! git clone "$userRepo" "$DOROTHY/user"; then
+			echo "The clone of the repository [$userRepo] to [$DOROTHY/user] failed."
 			echo "Dorothy will initialise the directory as a git repository, and leave it up to you to sync it up with a remote."
 			echo
 		fi
@@ -222,7 +226,7 @@ cd "$DOROTHY" || exit 1
 "$DOROTHY/commands/ok" "$DOROTHY/commands/silent" chmod -f +x ./user/commands/*  # would fail if no commands
 
 # proceed with shell cofniguration
-if test -z "${DOROTHY_SKIP_SHELL-}"; then
+if test -z "$skipShell"; then
 	# now that dorothy is confirmed to exist, proceed with strict mode
 	source "$DOROTHY/sources/strict.bash"
 
