fixed install on fresh macos
- remove `basic.vim` junk and gitignored it

- ensure array stuff is checked for bash compat, as macos big sur includes bash v3, which does not support arrays completely yet

- macos big sur does not include ping by default, so use whois if ping missing

- dorothy terminal now closed message is deprecated, removed it

- realpath instsall only attempted now when it is needed, as how to install it via brew if brew does not yet exist

- setup-mac restricts xcode license to only if xcode app is installed, as that is what the license is for

- brew install now works correctly given bash v3 array constraints, and fixes various issues such as broken symlinks from python reset

- uninstall brew now also resets dns to system

- fix sbin paths not being present

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/setup-mac b/commands/setup-mac
--- a/commands/setup-mac
+++ b/commands/setup-mac
@@ -4,15 +4,32 @@ source "$DOROTHY/sources/strict.bash"
 
 # check that an accident has not occured
 if ! is-mac; then
-	echo -e '[setup-mac] is only intended to be run on macOS systems...'
+	echo '[setup-mac] is only intended to be run on macOS systems...'
 	exit 2
 fi
 
-# install deps
-setup-util-devel
+# Make sure CLI tools are installed
+echo -e '\nEnsuring Apple Command Line Tool are installed..'
+while true; do
+	if ! xcode-select --install; then
+		echo "...Apple Command Line Tool are installed"
+		break
+	else
+		confirm "Press any key once the Apple Command Line Tool have been installed"
+	fi
+done
+
+# Make sure Xcode license is accepted
+if get-app 'Xcode' || get-app 'Xcode-beta'; then
+	echo -e '\nEnsuring the XCode license is accepted...'
+	sudo xcodebuild -license
+fi
+
+# Newline
+echo
 
 # action
-action="$(choose-option --question='Do you want to install or update this system?' --filter="${1-}" -- 'install' 'update')"
+action="$(choose-option --question='Do you want to install or update this system?' --filter="${1-}" -- 'install' 'update' || echo "${1:-install}")"  # or condition here is for bash v3, which choose-option will fail on, as bash v3 does not yet support arrays
 
 # log
 echo -e "\nThe $action of the macOS system has commenced... ⏲"
@@ -21,7 +38,7 @@ echo -e "\nThe $action of the macOS system has commenced... ⏲"
 setup-dorothy "$action"
 
 # mac
-setup-mac-brew "$action"
+setup-mac-brew "$action"  # setup-util-devel done as part of this
 if test "$action" = 'install'; then
 	setup-mac-apps
 	setup-mac-fonts
diff --git a/commands/setup-mac-brew b/commands/setup-mac-brew
--- a/commands/setup-mac-brew
+++ b/commands/setup-mac-brew
@@ -9,13 +9,30 @@ else
 	mode="install"
 fi
 
-# Setup install functions
+# Install brew
+if is-brew; then
+	echo -e '\nHomebrew is installed.'
+else
+	# recomended installation method, it is pretty much the only one that works properly
+	# https://github.com/balupton/dotfiles/commit/fff6fbc079aaa6ab9bb8438e02c307ebad46fd75
+	# https://github.com/balupton/dotfiles/commit/69dbbe81bf30f9e0d9a1dd1d00eca3f3c88b943b
+	echo -e '\nInstalling homebrew via its recomended method...'
+	arch -"${HOMEBREW_ARCH:-x86_64}" /bin/bash -c "$(fetch https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+
+	# as bash v3 doesn't support arrays, and as our config needs it, then install bash then reload
+	source "$DOROTHY/sources/paths.sh"
+	brew install bash
+	setup-mac-brew "$@"
+	exit "$?"
+fi
+
+# Helpers
 function brewforceuninstall() {
 	brew uninstall --ignore-dependencies "$@" || :
 }
 function brewinstall() {
 	echo -e "\nInstalling $# brew packages..."
-	setup NAME="brew:$*" BREW="$*" setup-util brew
+	env NAME="brew:$*" BREW="$*" setup-util brew
 }
 function slowbrewinstall() {
 	# if we are on /usr/local then we are using bottles, which are pre-compiled, and are fast
@@ -38,6 +55,7 @@ function confirmbrewinstall() {
 			choices=("$1")
 		fi
 	else
+		source "$DOROTHY/sources/arrays.bash"
 		fodder="$(choose-option --multi --question="What formulas would you like to brew install?" -- "$@")"
 		mapfile -t choices <<< "$fodder" # <( destroys stdin
 	fi
@@ -53,26 +71,17 @@ function confirmcaskinstall() {
 			choices=("$1")
 		fi
 	else
+		source "$DOROTHY/sources/arrays.bash"
 		fodder="$(choose-option --multi --question="Which casks would you like to brew install?" -- "$@")"
 		mapfile -t choices <<< "$fodder"  # <( destroys stdin
 	fi
 	if is-array-full-or-partial "${choices-}"; then
 		# use $* as cask supports installing multiple together
-		setup NAME="cask:$*" CASK="$*" setup-util cask
+		env NAME="cask:$*" CASK="$*" setup-util cask
 	fi
 }
 
-# Setup brew
-if is-brew; then
-	echo -e '\nHomebrew is already installed, great!'
-else
-	# recomended installation method, it is pretty much the only one that works properly
-	# https://github.com/balupton/dotfiles/commit/fff6fbc079aaa6ab9bb8438e02c307ebad46fd75
-	# https://github.com/balupton/dotfiles/commit/69dbbe81bf30f9e0d9a1dd1d00eca3f3c88b943b
-	echo -e '\nInstalling homebrew via its recomended method...'
-	arch -"${HOMEBREW_ARCH:-x86_64}" /bin/bash -c "$(fetch https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
-fi
-
+# Update brew
 echo -e '\nUpdating homebrew...'
 # trim deprecations
 ok silent brew untap caskroom/cask
@@ -91,17 +100,19 @@ brew tap homebrew/cask-fonts
 # done
 echo '...updated homebrew!'
 
-# Removing dependencies that routinelly fail due to their circular nature
+# Essentials
+echo -e '\nInstalling essentials...'
+setup-util-devel
+
+# Reinstall problematic dependencies that routinely fail due to their circular nature
 echo -e '\nRemoving circular brew dependencies for reinstallation later...'
 brewforceuninstall chromaprint homebrew-ffmpeg/ffmpeg/ffmpeg ffmpeg vim python ruby
-# finish wiping python
-rm -rf "/Users/$(whoami)/Library/Python/"*
-rm -rf "$(brew --cellar)/python"*
-rm -rf "$(brew --prefix)/opt/python"*
-
-# Reinstall dependencies
-# python
-brew install python
+ok rm -rf "/Users/$(whoami)/Library/Python/"*
+ok rm -rf "$(brew --cellar)/python"*
+ok rm -rf "$(brew --prefix)/opt/python"*
+# ok is used above as otherwise their non existance will cause failure
+brew cleanup  # used to fix the breaks from removing the above
+brew install python  # reinstall python now that it has been cleaned
 
 # ffmpeg
 if test "$mode" = "install" && confirm-bool $'\nDo you want to install encoding tools?'; then
@@ -153,8 +164,11 @@ if test "$mode" = "install" && confirm-bool $'\nDo you want to install encoding 
 	opts="$(brew options homebrew-ffmpeg/ffmpeg/ffmpeg --compact)"
 	# https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/81#issuecomment-828722622
 	opts="${opts/--with-decklink /}"
+	# space seperated array
+	source "$DOROTHY/sources/arrays.bash"
+	mapfile -t opts < <(echo-split ' ' -- "$opts")
 	# install
-	brew install homebrew-ffmpeg/ffmpeg/ffmpeg $opts
+	brew install homebrew-ffmpeg/ffmpeg/ffmpeg "${opts[@]}"
 fi
 
 # user cli deps
