setup-node: fix for alpine

diff --git a/commands/setup-node b/commands/setup-node
--- a/commands/setup-node
+++ b/commands/setup-node
@@ -87,19 +87,14 @@ function setup-node() (
 	# =====================================
 	# Install via System
 
-	# setup system node for global installs and vscode on mac
-	function install_homebrew_node() {
-		# `reinstall ... || :` as well as `install ... || upgrade ... || :` are no longer necessary,
-		# install does upgrade if it is already installed:
-		# https://github.com/Homebrew/brew/pull/11525
-		brew install node
+	if is-brew || is-alpine; then
+		echo-segment --h2='Install Node.js via System'
+		setup-util --name='Node.js via System' --quiet \
+			BREW='node' \
+			APK='nodejs'
 		npm cache clean --force
-	}
-	if is-brew; then
-		echo-segment --h2='Install Node.js via Homebrew'
-		eval-helper --quiet --no-wrap -- install_homebrew_node
 		echo "Installed: $(node --version)"
-		echo-segment --g2='Install Node.js via Homebrew'
+		echo-segment --g2='Install Node.js via System'
 	fi
 
 	# =====================================
@@ -176,10 +171,6 @@ function setup-node() (
 		# checkout latest stable tag
 		git checkout "$(git describe --abbrev=0 --tags --match "v[0-9]*" "$(git rev-list --tags --max-count=1)")"
 	}
-	echo-segment --h2='Install Node.js Version Manager (NVM)'
-	echo-style --dim "NVM_DIR=$NVM_DIR"
-	eval-helper --quiet --no-wrap -- install_nvm
-	echo-segment --g2='Install Node.js Version Manager (NVM)'
 
 	# install nvm node
 	function install_nvm_node() {
@@ -201,19 +192,29 @@ function setup-node() (
 		# default
 		nvm use default
 	}
-	echo-segment --h2='Install Node.js via NVM'
-	echo-style --dim='Installs active and LTS versions.'
-	eval-helper --quiet --no-wrap -- install_nvm_node
-	mapfile -t versions < <(get_nvm_versions)
-	for version in "${versions[@]}"; do
-		echo "Installed: v$version"
-	done
-	echo-segment --g2='Install Node.js via NVM'
 
-	# =====================================
-	# npm
+	# (arm) alpine does not support nvm, fails with:
+	# > mode no such file or directory
+	if ! is-alpine; then
+		# install nvm
+		echo-segment --h2='Install Node.js Version Manager (NVM)'
+		echo-style --dim "NVM_DIR=$NVM_DIR"
+		eval-helper --quiet --no-wrap -- install_nvm
+		echo-segment --g2='Install Node.js Version Manager (NVM)'
 
-	source "$DOROTHY/sources/nvm.sh"
+		# nvm node
+		echo-segment --h2='Install Node.js via NVM'
+		echo-style --dim='Installs active and LTS versions.'
+		eval-helper --quiet --no-wrap -- install_nvm_node
+		mapfile -t versions < <(get_nvm_versions)
+		for version in "${versions[@]}"; do
+			echo "Installed: v$version"
+		done
+		echo-segment --g2='Install Node.js via NVM'
+
+		# source nvm
+		source "$DOROTHY/sources/nvm.sh"
+	fi
 
 	# -------------------------------------
 	# Upgrade
