WIP: move `setup-utils` into `setup-util`

diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -159,12 +159,16 @@ function setup_util() (
 			Setup a utility on your system. Supports Linux, macOS, Windows. Supports direct sources (website, github) and indirect sources (package managers, app stores).
 
 			USAGE:
-			\`setup-util [...options] [<utility>]\`
+			Setup a utility from sources:
+			\`setup-util [...options] <...sources>\`
 
+			Setup a predefined utility from its \`setup-util-*\` command:
+			\`setup-util [...options] ...<utility>\`
+
+			Invoke a predefined utility from its \`setup-util-*\` command:
 			\`setup-util [...options] invoke <utility> [-- <...arguments>]\`
 
 			OPTIONS:
-
 			These options determine the action to provide on the utility:
 
 			! When specifying these actions as a flag, i.e. with a preceding double dash, e.g. \`--instal\` instead of \`install\`, then it will be combined with prior enabled actions.
@@ -308,7 +312,6 @@ function setup_util() (
 	}
 
 	# <options-for-sources>
-	local CONFIGURE_EVAL='' CONFIGURE_INSTALL_EVAL='' CONFIGURE_INSTALLED_EVAL='' DOWNLOAD_BUILD_UNINSTALL_EVAL=''
 	local APPIMAGE=() APPIMAGE_FILENAME=''
 	local APK=() APK_REPO=''
 	local APT=() APT_REPO='' APT_KEY='' APT_ID='' APT_INSTALL_EVAL=''
@@ -360,7 +363,7 @@ function setup_util() (
 	local item \
 		option_install='' option_upgrade='' option_uninstall='' option_dependency='' option_configure='' option_invoke='' \
 		option_action='' option_transpose='' \
-		option_source=() \
+		option_source=() option_dependencies=() \
 		option_apps=() option_clis=() option_fonts=() option_checker='' \
 		option_name='' option_quiet='' option_confirm='no' option_xdg='yes'option_optional='no' option_fallback='yes' option_force='no' option_elevate='no' \
 		option_deps='yes' # configure/deps/slim
@@ -515,6 +518,72 @@ function setup_util() (
 		*) help 'An unrecognised flag was provided: ' --variable-value={item} ;;
 		esac
 	done
+
+	# if args, don't use config
+	if [[ ${#option_utils[@]} -eq 0 ]]; then
+		# no args, so use configuration
+		source "$DOROTHY/sources/config.sh"
+
+		# setup.bash provides:
+		local SETUP_UTILS=()
+		load_dorothy_config 'setup.bash'
+
+		# if reconfiguring, prompt the user which ones
+		local options file basename name
+		if [[ $option_configure == 'yes' ]]; then
+			options=()
+			for file in "$DOROTHY/commands/setup-util-"*; do
+				basename="$(basename -- "$file")"
+				name="${basename#*setup-util-}"
+				options+=("$name")
+			done
+			__split --target={option_utils} --no-zero-length --invoke -- \
+				choose --linger --confirm --multi \
+				--question="Which utilities to install?" \
+				--defaults="$(__print_lines "${SETUP_UTILS[@]}")" -- \
+				"${options[@]}"
+
+			# save
+			dorothy-config 'setup.bash' -- \
+				--field='SETUP_UTILS' --array="$(__print_lines "${option_utils[@]}")"
+		else
+			option_utils=("${SETUP_UTILS[@]}")
+		fi
+	fi
+
+	# check
+	if [[ ${#option_utils[@]} -eq 0 ]]; then
+		__print_style --notice1='No utilities provided, to configure some use: ' --code-notice1='setup-utils --configure'
+		return 0
+	fi
+
+	# =====================================
+	# Action
+
+	local item cmd
+	__print_style --h1="Setup ${#option_utils[@]} utilities"
+	for item in "${option_utils[@]}"; do
+		if [[ -n $item ]]; then
+			cmd="setup-util-${item}"
+			if __command_exists -- "$cmd"; then
+				"$cmd" "${option_args[@]}" || : # don't fail everything if one fails
+			else
+				# can't use -EOF, as we want to print spacing
+				__print_error \
+					--help="Unable to install \`$item\`, as \`$cmd\` doesn't exist." --newline \
+					--newline \
+					--red="You can create the missing command by running:" --newline \
+					--newline \
+					--dim="    touch $DOROTHY/user/$cmd" --newline \
+					--dim="    edit $DOROTHY/user/$cmd" --newline \
+					--dim="    open https://github.com/bevry/dorothy/discussions/73" --newline \
+					--newline \
+					--red='Once the command is created, re-run your prior command.'
+				return 1
+			fi
+		fi
+	done
+	__print_style --g1="Setup ${#option_utils[@]} utilities"
 
 	# ensure action
 	if [[ -z $option_action ]]; then
