better nvm handling, setup-node now working again

diff --git a/commands/setup-node b/commands/setup-node
--- a/commands/setup-node
+++ b/commands/setup-node
@@ -86,26 +86,16 @@ function setup_node() (
 	# =====================================
 	# Helpers
 
-	function get_nvm_versions() ( # 👍 /docs/bash/errors: disabled errexit
-		set +Eeu # disable strict mode inside this subshell and load nvm only inside this subbshell as nvm does not conform to strict mode
-		source "$DOROTHY/sources/nvm.sh"
-		if ! command -v nvm &>/dev/null; then
-			return 1
-		fi
+	function get_nvm_versions { # 👍 /docs/bash/errors: disabled errexit
 		source "$DOROTHY/sources/ripgrep.bash"
-		nvm ls --no-colors --no-alias | rg -o 'v([^\s]+)' --replace '$1' || :
-	)
+		nvm-env nvm ls --no-colors --no-alias | rg -o 'v([^\s]+)' --replace '$1' || :
+	}
 
-	function clean_nvm() ( # 👍 /docs/bash/errors: disabled errexit
-		set +Eeu # disable strict mode inside this subshell and load nvm only inside this subbshell as nvm does not conform to strict mode
-		source "$DOROTHY/sources/nvm.sh"
-		if ! command -v nvm &>/dev/null; then
-			return 1
-		fi
+	function clean_nvm { # 👍 /docs/bash/errors: disabled errexit
 		# prepare
 		local versions version
 		# swap to system
-		nvm use system || :
+		nvm-env nvm use system || :
 		# fetch versions
 		mapfile -t versions < <(get_nvm_versions)
 		if test "${#versions[@]}" -eq 0; then
@@ -114,14 +104,14 @@ function setup_node() (
 		fi
 		# clean versions
 		for version in "${versions[@]}"; do
-			nvm uninstall "$version" | sd 'Uninstalled node ' 'Uninstalled: '
+			nvm-env nvm uninstall "$version" | sd 'Uninstalled node ' 'Uninstalled: '
 		done
 		# confirm clean was successful
 		mapfile -t versions < <(get_nvm_versions)
 		test "${#versions[@]}" -eq 0
-	)
+	}
 
-	function wipe_nvm { # 👍 /docs/bash/errors: disabled errexit
+	function wipe_nvm {
 		fs-rm --no-confirm --quiet -- "$NVM_DIR"
 	}
 
@@ -156,29 +146,23 @@ function setup_node() (
 		git checkout "$(git describe --abbrev=0 --tags --match "v[0-9]*" "$(git rev-list --tags --max-count=1)")"
 	}
 
-	function install_nvm_node() ( # 👍 /docs/bash/errors: disabled errexit
-		set +Eeu # disable strict mode inside this subshell and load nvm only inside this subbshell as nvm does not conform to strict mode
-		source "$DOROTHY/sources/nvm.sh"
-		if ! command -v nvm &>/dev/null; then
-			return 1
-		fi
-
+	function install_nvm_node {
 		# install
-		nvm install --no-progress node || return       # latest active
-		nvm-2596 install --no-progress --lts || return # latest LTS
+		nvm-env nvm install --no-progress node || return         # latest active
+		nvm-env --2596 nvm install --no-progress --lts || return # latest LTS
 
 		# set default node version
 		if is-brew; then
-			nvm alias default system || return
+			nvm-env nvm alias default system || return
 		else
 			# use latest lts
-			nvm alias default stable || return
+			nvm-env nvm alias default stable || return
 			# use current lts: "$(nvm version-remote --lts)"
 		fi
-	)
+	}
 
 	function install_system_node {
-		setup-util --name='Node.js via System' --quiet \
+		setup-util --name='Node.js via System' --cli=node --force --quiet \
 			APK='nodejs' APK='npm' \
 			APT_KEY='https://deb.nodesource.com/gpgkey/nodesource.gpg.key' \
 			APT_REPO='deb [arch={ARCH} signed-by={KEY}] https://deb.nodesource.com/node_18.x {RELEASE} main' \
@@ -195,49 +179,48 @@ function setup_node() (
 			WINGET='OpenJS.NodeJS' \
 			XBPS='nodejs' \
 			ZYPPER='nodejs'
+		print_line "Installed: $(node --version)"
 	}
 
-	function upgrade_system_npm {
+	function upgrade_system_or_nvm_npm {
 		# ensure the cache is configured correctly
 		# to avoid when say a /Users/... cache config is copied to a Linux machine
 		local cache_dir
-		cache_dir="$(npm config get cache || :)"
+		cache_dir="$(nvm-env npm config get cache || :)"
 		if test -n "$cache_dir" -a ! -d "$cache_dir"; then
 			# try and make it
 			mkdir -p "$cache_dir" || {
 				echo-style --error="Unconfiguring the invalid cache directory:" --code="$cache_dir"
-				npm config delete cache
+				nvm-env npm config delete cache
 			}
 		fi
 
 		# continue with the upgrade
-		echo-segment --h3='Upgrade npm'
-		echo-style --dim="Before: $(npm --version)"
+		echo-style --dim="Before: $(nvm-env npm --version)"
 		setup-util --name='npm' --upgrade --force --quiet \
-			NPM='npm' || echo-style --notice='Upgrading npm failed' ', likely due to a read-only global installation, this will resolve once nvm is used.'
-		npm cache clean --force
-		print_line "After:  $(npm --version)"
-		echo-segment --g3='Upgrade npm'
+			NPM='npm' || echo-style --notice='You can ignore the npm ugprade failure, this will resolve after nvm is used.'
+		nvm-env npm cache clean --force
+		print_line "After:  $(nvm-env npm --version)"
 	}
 
 	function configure_system_npm {
 		echo-segment --h2='Configure npm'
-		npm config set init-author-name "$(
+		nvm-env npm config set init-author-name "$(
 			ask --required --confirm \
 				--question="What is the profile name that you want to configure npm with?" \
 				--default="$(get-profile name -- npm ... || :)"
 		)"
-		npm config set init-author-email "$(
+		nvm-env npm config set init-author-email "$(
 			ask --required --confirm \
 				--question="What is the profile email that you want to configure npm with?" \
 				--default="$(get-profile email -- npm ... || :)"
 		)"
-		npm config set init-author-url "$(
+		nvm-env npm config set init-author-url "$(
 			ask --required --confirm \
 				--question="What is the profile homepage that you want to configure npm with?" \
 				--default="$(get-profile url -- npm ... || :)"
 		)"
-		npm config set init-license "$(
+		nvm-env npm config set init-license "$(
 			ask --required --confirm \
 				--question="What license do you want to configure npm to default to?" \
 				--default="$(npm config get init-license)"
@@ -251,14 +234,12 @@ function setup_node() (
 	echo-segment --h1='Setup Node.js'
 
 	# =====================================
-	# Install via System
+	# Install Node via System
 
 	# https://nodejs.org/en/download/package-manager/
 	# @todo https://github.com/nodejs/unofficial-builds for riscv, but provides tars that include multiple directories
 	echo-segment --h2='Install Node.js via System'
 	install_system_node
-	upgrade_system_npm
-	print_line "Installed: $(node --version)"
 	echo-segment --g2='Install Node.js via System'
 
 	# =====================================
@@ -273,7 +254,7 @@ function setup_node() (
 	fi
 
 	# =====================================
-	# Install via NVM
+	# Install NVM and Node via NVM
 
 	# (arm) alpine does not support nvm, fails with:
 	# > mode no such file or directory
@@ -288,7 +269,7 @@ function setup_node() (
 		# nvm node
 		echo-segment --h2='Install Node.js via NVM'
 		echo-style --dim='Installs active and LTS versions.'
-		eval_helper --quiet --no-wrap \
+		eval_helper --no-quiet --no-wrap \
 			-- install_nvm_node
 		mapfile -t versions < <(get_nvm_versions)
 		for version in "${versions[@]}"; do
@@ -297,8 +278,15 @@ function setup_node() (
 		echo-segment --g2='Install Node.js via NVM'
 	fi
 
-	# -------------------------------------
-	# Reconfiguration
+	# =====================================
+	# Upgrade npm
+
+	echo-segment --h3='Upgrade npm'
+	upgrade_system_or_nvm_npm
+	echo-segment --g3='Upgrade npm'
+
+	# =====================================
+	# Reconfigure npm
 
 	# check
 	if
@@ -315,8 +303,8 @@ function setup_node() (
 		configure_system_npm
 	fi
 
-	# -------------------------------------
-	# Packages
+	# =====================================
+	# Packages via npm
 
 	setup-util --installer="NODE" -- "${NPM_INSTALL[@]}"
 
