wsl-windows interaction
get-app: now OS specific, supports macos, and winget on wsl
setup-environment-commands: inherit PATH for wsl compat, and fallback to stable WSL paths if needed
setup-util: support winget
setup-util-obs: add winget

diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -75,8 +75,8 @@ function setup_util() (
 
 		# windows, unknown features
 		scoop
-		winget
-		choco # choco/chocolatey/cinst, interferes with WSL, so should be last preference on windows
+		winget # installs apps to windows, installs exes to windows, paths inherited but custom
+		choco  # choco/chocolatey/cinst, interferes with WSL, so should be last preference on windows
 
 		# solaris/bsd, unknown features
 		pkgin
@@ -3097,8 +3097,19 @@ function setup_util() (
 	# winget / Windows Package Manager Client
 	# https://docs.microsoft.com/en-us/windows/package-manager/winget/
 	# https://docs.microsoft.com/en-us/windows/package-manager/winget/install
+	function is_this_winget_package_installed {
+		winget.exe list --id="$package" &>/dev/null
+	}
+	function are_any_of_these_winget_packages_installed { # 👍 /docs/bash/errors: robust exit status
+		local package packages=("$@")
+		for package in "${packages[@]}"; do
+			# only supports one package at a time
+			is_this_winget_package_installed "$package"
+		done
+		return 1
+	}
 	function do_winget {
-		local args=() packages=()
+		local args=() opts=() package packages=()
 		if test "${#WINGET[@]}" -ne 0; then
 			packages+=("${WINGET[@]}")
 		fi
@@ -3107,30 +3118,52 @@ function setup_util() (
 		if test "${#packages[@]}" -eq 0; then
 			return 200 # ECUSTOM 200 Not applicable to this utility
 		fi
-		if command-missing winget; then
+		if command-missing 'winget.exe'; then
 			return 200 # ECUSTOM 200 Not applicable for this package system
+		fi
+		if test "$action" = 'uninstall' && ! are_any_of_these_winget_packages_installed "${packages[@]}"; then
+			return 200 # ECUSTOM 200 Not applicable to this uninstallation
 		fi
 
 		# args
-		if test "$action" = 'uninstall'; then
-			args+=(
-				'winget'
-				'uninstall'
-			)
-		elif test "$upgrade" = 'yes'; then
-			args+=(
-				'winget'
-				'upgrade'
-			)
-		else
-			args+=(
-				'winget'
-				'install'
-			)
-		fi
-
-		# packages
-		"${args[@]}" "${packages[@]}"
+		for package in "${packages[@]}"; do
+			args=()
+			if test "$action" = 'uninstall'; then
+				if ! is_this_winget_package_installed "${packages[@]}"; then
+					continue
+				fi
+				args+=(
+					'winget.exe'
+					'uninstall'
+				)
+			elif test "$upgrade" = 'yes'; then
+				args+=(
+					'winget.exe'
+					'upgrade'
+				)
+			else
+				if is_this_winget_package_installed "${packages[@]}"; then
+					continue
+				fi
+				args+=(
+					'winget.exe'
+					'install'
+					'--accept-package-agreements'
+					'--accept-source-agreements'
+				)
+				# aria2c gets installed as aria2c.exe
+				# which is available via an inherited and compliicated PATH modification
+				# as such isn't available to VSCode Terminal
+				# the .exe suffix also means it isn't easily discoverable either
+			fi
+			if test "$quiet" = 'yes'; then
+				args+=(
+					'--disable-interactivity'
+					'--silent'
+				)
+			fi
+			"${args[@]}" "$package"
+		done
 	}
 
 	# emerge / Portage / GURU / Gentoo Linux
