add [setup-system clean], is-exists => is-present

diff --git a/commands/setup-system b/commands/setup-system
--- a/commands/setup-system
+++ b/commands/setup-system
@@ -2,6 +2,7 @@
 
 function setup_system() (
 	source "$DOROTHY/sources/bash.bash"
+	source "$(type -P eval-helper)"
 
 	# =====================================
 	# Arguments
@@ -12,7 +13,7 @@ function setup_system() (
 			Configure the system to our expectations.
 
 			USAGE:
-			setup-system <install|update>
+			setup-system <install|update|clean>
 		EOF
 		if test "$#" -ne 0; then
 			echo-error "$@"
@@ -40,7 +41,10 @@ function setup_system() (
 
 	# assert action
 	if test -z "$action"; then
-		help "No action provided."
+		help "No <action> provided."
+	fi
+	if [[ ! $action =~ ^(install|update|clean)$ ]]; then
+		help "Invalid <action> provided: $action"
 	fi
 
 	# generate log title
@@ -102,16 +106,44 @@ function setup_system() (
 			# shell
 			select-shell
 		fi
+	fi
 
-		# clean
-		if is-mac; then
-			setup-mac clean
-		elif is-linux; then
-			setup-linux clean
-		fi
-	else
-		# unknown action
-		help "An unrecognised action was provided: $action"
+	# clean
+	function clean_dirs {
+		local caches recreate
+		caches=(
+			"$HOME/Library/Application Support/Plex Media Server/Updates"
+			"$HOME/Library/Application Support/Spotify/PersistentCache/Update"
+			"$XDG_CACHE_HOME"
+		)
+		recreate=(
+			"$XDG_CACHE_HOME"
+			# "$XDG_CACHE_HOME/gems"
+			# "$XDG_CACHE_HOME/pip/http"
+		)
+		fs-rm --no-confirm --quiet --sudo -- "${caches[@]}" || :
+		mkdir -p "${recreate[@]}"
+	}
+	eval_helper --shapeshifter --no-wrap \
+				--pending="$(echo-style --bold="Cleaning directory caches...")" \
+				--success="$(echo-style --success="Cleaned directory caches.")" \
+				--failure="$(echo-style --error="Failed to clean directory caches.")" \
+				-- clean_dirs
+
+	# npm
+	if command-exists npm; then
+		eval_helper --shapeshifter --no-wrap \
+				--pending="$(echo-style --bold="Cleaning npm...")" \
+				--success="$(echo-style --success="Cleaned npm.")" \
+				--failure="$(echo-style --error="Failed to clean npm.")" \
+				-- nvm-env npm cache clean --force || :
+	fi
+
+	# operating system
+	if is-mac; then
+		setup-mac clean
+	elif is-linux; then
+		setup-linux clean
 	fi
 
 	# log
