major is-same, checksum; minor many
- `checksum-directory` removed for new `checksum` which supports files and directories, more algorithms, better more robust outputs and progress bars

- `is-same` now does several simpler checks first, before comparing checksums

- `is-help*` commands added, to make checking for help state easier

- `fs-absolute` replaced with `fs-realpath`, and `fs-absolute` changed to do what its title suggests

- more exit codes throughout now changes to more conventional exit codes

- strict_pause now replaced with simpler method

- more commands getting help and ask/choose functionality

- secret had a few incorrect `|| :` usage removed

- `source/tty`: if `noact` is called, the exit code becomes its return code - before this was ignored

- added `echo-eval` for outputting the command that was run, along with its results

- `echo-paths` renamed to `echo-subpaths` to reflect its purpose

- `get-size` now is a lot more helpful, and works correctly now

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/setup-dorothy-permissions b/commands/setup-dorothy-permissions
--- a/commands/setup-dorothy-permissions
+++ b/commands/setup-dorothy-permissions
@@ -3,16 +3,23 @@ source "$DOROTHY/sources/strict.bash"
 source "$DOROTHY/sources/globstar.bash"
 source "$DOROTHY/sources/nullglob.bash"
 if test "$NULLGLOB" = 'no' -o "$GLOBSTAR" = 'no'; then
-	exit 1
+	exit 95 # Operation not supported
 fi
 
 # perform the act
-cd "$DOROTHY" || exit 1
+cd "$DOROTHY" || exit 2 # No such file or directory
 
+# user/secrets may need sudo
 echo 'correcting permissions...'
-chmod -f +rwx ./**
-chmod -f -x ./**/*.md ./sources/*.* ./user/**/*.*
-chmod -f +x ./**/commands/*
+echo-lines ./** | while read -r file; do
+	chmod -f +rwx "$file" || echo "unable to +rwx: $file"
+done
+echo-lines ./**/*.md ./sources/*.* ./user/**/*.* | while read -r file; do
+	chmod -f -x "$file" || echo "unable to -x: $file"
+done
+echo-lines ./**/commands/* | while read -r file; do
+	chmod -f +x "$file" || echo "unable to +x: $file"
+done
 
 echo 'stage new files...'
 ok silent git add --ignore-errors ./**
