setup-util-gsed: workaround for alpine

diff --git a/commands/setup-util-gsed b/commands/setup-util-gsed
--- a/commands/setup-util-gsed
+++ b/commands/setup-util-gsed
@@ -8,9 +8,22 @@ function setup-util-gsed() (
 			BREW='gnu-sed'
 	fi
 
-	# if [sed] is [gsed], then make sure [gsed] is available
-	if command-missing gsed; then
-		symlink-helper --existing="$(which sed)" --symlink="$XDG_BIN_HOME/gsed"
+	# if [sed] is [gsed], then make sure [gsed] is available and working
+	if ! command-working gsed; then
+		local existing symlink="$XDG_BIN_HOME/gsed"
+		existing="$(which sed)"
+		if test "$existing" != "$(fs-realpath "$existing")"; then
+			# alpine symlinks /bin/sed to /bin/busybox, as sych sed symlinks fail (applet not found)
+			# so do a workaround
+			cat <<-EOF >"$symlink"
+				#!/usr/bin/env bash
+				set -Eeuo pipefail
+				sed "\$@"
+			EOF
+			chmod +x "$symlink"
+		else
+			symlink-helper --existing="$existing" --symlink="$symlink"
+		fi
 	fi
 
 	# if gsed isn't being found, then you are probably using sudo
