better down*, setup-linux*, github*
- `array-evens`, `array-odds` now support jumbled arguments

- `down-zip-file` removed as functionality added into `down-zip`

- `down`, `down-zip`, `github-*`, `unziptar` now support options via questions and flags, no more guessing

- `setup-util-flatplak` now correctly named `setup-util-flatpak`

- add `is-arch`, is-gnome`, `is-manjaro`, `setup-linux-clean`, `setup-util-curl`, `setup-util-devel`, `setup-util-git`, `setup-util-gnome-software`, `setup-util-pamac`, `setup-util-snap`, and `setup-util-vnc`

- `setup-util`: more options have fallbacks enabled

- `setup-util`: now supports CONFIRM env var

- `setup-linux-apt` now renamed to `setup-util-apt`

- `setup-linux-apk` now renamed to setup-util-apk`

- `setup-linux-snap` now renamed to `setup-util-snap`

- `setup-linux` now runs `setup-linux-recovery`, and confirms for `setup-util-(gnome-software|snap|flatpak|pamac)`

- `snap`, `flatpak`, `pamac` can now install and configure themselves via their `setup-util-*` command

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/setup-linux b/commands/setup-linux
--- a/commands/setup-linux
+++ b/commands/setup-linux
@@ -9,7 +9,7 @@ if ! is-linux; then
 fi
 
 # action
-action="$(choose-option --question='Do you want to install or update this sytem?' --filter="${1-}" -- 'install' 'update')"
+action="$(choose-option --question='Do you want to install or update this system?' --filter="${1-}" -- 'install' 'update')"
 
 # log
 echo -e "\nThe $action of the Linux system has commenced... ⏲"
@@ -17,21 +17,30 @@ echo -e "\nThe $action of the Linux system has commenced... ⏲"
 # dorothy
 setup-dorothy "$action"
 
-# raspi
+# system
 setup-linux-raspi
+setup-linux-recovery
 
-# package systems
-setup-linux-apt
-setup-linux-apk
-setup-linux-snap
-
-# fonts
+# package managers and utilities
+setup-util-apt
+setup-util-apk
 if test "$action" = 'install'; then
+	env CONFIRM=yes setup-util-gnome-software || :
+	env CONFIRM=yes setup-util-snap || :
+	env CONFIRM=yes setup-util-flatpak || :
+	env CONFIRM=yes setup-util-pamac || :
 	setup-linux-fonts
+else
+	env ACTION=update setup-util-snap || :
+	env ACTION=update setup-util-flatpak || :
+	env ACTION=update setup-util-pamac || :
 fi
 
 # cross-platform
 setup-extras "$action"
+
+# cleanup
+setup-linux-clean
 
 # log
 echo -e "\nThe $action of the Linux system has completed successfully! ✅"
diff --git a/commands/setup-util b/commands/setup-util
--- a/commands/setup-util
+++ b/commands/setup-util
@@ -23,6 +23,13 @@ if test -n "${CLI-}"; then
 	fi
 fi
 
+# confirm if necessary
+if is-affirmative "${CONFIRM-}"; then
+	if ! confirm-positive "Do you want to install the [$name] utility?"; then
+		exit 2  # error exit code so that things that depend on this abort
+	fi
+fi
+
 # log helpers
 function won () {
 	echo "The [$name] utility is now installed. ✅"
@@ -33,7 +40,13 @@ function lost () {
 
 # brew / Homebrew / macOS
 function do_brew () {
-	if test -n "${BREW-}" && is-brew; then
+	if test -n "${BREW-}"; then
+		if ! is-brew; then
+			if is-mac; then
+				fallbacks+=('brew')
+			fi
+			return 1
+		fi
 		# support BREW holding multiple args
 		mapfile -t args < <(echo-split ' ' -- "$BREW")
 		if test -n "${FORCE-}"; then
@@ -46,10 +59,21 @@ function do_brew () {
 		return 1
 	fi
 }
+function do_brew_fallback () {
+	setup-util-brew
+	source "$DOROTHY/sources/paths.sh"
+	do_brew "$@"
+}
 
 # brew / Homebrew Casks / macOS
 function do_cask () {
-	if test -n "${CASK-}" && is-brew; then
+	if test -n "${CASK-}"; then
+		if ! is-brew; then
+			if is-mac; then
+				fallbacks+=('cask')
+			fi
+			return 1
+		fi
 		# support CASK holding multiple args
 		mapfile -t args < <(echo-split ' ' -- "$CASK")
 		args=('--cask')
@@ -61,6 +85,12 @@ function do_cask () {
 		return 1
 	fi
 }
+function do_cask_fallback () {
+	setup-util-brew
+	source "$DOROTHY/sources/paths.sh"
+	do_cask "$@"
+}
+
 
 # pacman / Arch Linux / Manjaro
 function do_pacman () {
@@ -122,27 +152,47 @@ function do_aurutils () {
 # https://itsfoss.com/best-aur-helpers/
 function do_pamac () {
 	pkg="${PAMAC:-"${AUR-}"}"
-	if test -n "$pkg" && command-exists pamac; then
-		pamac install "$pkg"
+	if test -n "$pkg"; then
+		if command-missing pamac; then
+			fallbacks+=('pamac')
+			return 1
+		fi
+		pamac install --no-confirm "$pkg"
 	else
 		return 1
 	fi
+}
+function do_pamac_fallback () {
+	setup-util-pamac
+	do_pamac "$@"
 }
 
 # flatpak / Arch Linux / Manjaro
 function do_flatpak () {
 	pkg="${FLATPAK:-"${FLATPACK-}"}"  # accomodate typo
 	repo="${FLATPAK_REPO:-"${FLATPACK_REPO:-flathub}"}"  # accomodate typo
-	if test -n "$pkg" && command-exists flatpak; then
+	if test -n "$pkg"; then
+		if command-missing flatpak; then
+			fallbacks+=('flatpak')
+			return 1
+		fi
 		flatpak install "$repo" "$pkg"
 	else
 		return 1
 	fi
 }
+function do_flatpak_fallback () {
+	setup-util-flatpak
+	do_flatpak "$@"
+}
 
 # snap / Snap Craft / Ubuntu
 function do_snap () {
-	if test -n "${SNAP-}" && command-exists snap; then
+	if test -n "${SNAP-}"; then
+		if command-missing snap; then
+			fallbacks+=('snap')
+			return 1
+		fi
 		args=()
 		# support multiple args
 		mapfile -t args < <(echo-split ' ' -- "$SNAP")
@@ -159,6 +209,10 @@ function do_snap () {
 	else
 		return 1
 	fi
+}
+function do_snap_fallback () {
+	setup-util-snap
+	do_snap "$@"
 }
 
 # yum / RedHat / Fedora / CentOS / etc
@@ -554,9 +608,9 @@ function do_zip () {
 	if test -n "${ZIP-}"; then
 		mkdir -p "$HOME/bin"
 		if test -n "${ZIP_FILE-}"; then
-			down-zip-file "$ZIP" "$ZIP_FILE" "$HOME/bin"
+			down-zip "$ZIP" --filter="$ZIP_FILE" --destination="$HOME/bin"
 		else
-			down-zip-file "$ZIP" "$HOME/bin"
+			down-zip "$ZIP" --destination="$HOME/bin"
 		fi
 	else
 		return 1
