`echo-<color>` removed for new `echo-color`

diff --git a/commands/sharebox b/commands/sharebox
--- a/commands/sharebox
+++ b/commands/sharebox
@@ -30,8 +30,8 @@ actions=(
 # =====================================
 # CONFIGURATION
 
-echo > /dev/tty
-echo "Processing configuration..." > /dev/tty
+echo >/dev/tty
+echo "Processing configuration..." >/dev/tty
 
 # load configuration
 config_file="$(get_dorothy_config 'sharebox.bash')"
@@ -99,7 +99,7 @@ fi
 
 # update configuration
 if test "$configure" = 'yes'; then
-	cat << EOF > "$config_file"
+	cat <<EOF >"$config_file"
 #!/usr/bin/env bash
 
 if test "\$(get-hostname)" = '$(get-hostname)'; then
@@ -133,9 +133,8 @@ function get_btrfs_drives_count {
 	sudo btrfs filesystem show "$label" | rg -o 'Total devices ([0-9]+)' --replace '$1'
 }
 function verify_btrfs_drives_count {
-	local label="$1"
-	local expected="$2"
-	local actual="$(get_btrfs_drives_count "$label")"
+	local label="$1" expected="$2" actual
+	actual="$(get_btrfs_drives_count "$label")"
 	if test "$actual" -ne "$expected"; then
 		echo "$actual out of $expected drives available, try again when all drives are available"
 		return 1
@@ -145,22 +144,21 @@ function get_vault_features {
 	gocryptfs --info "$1" | grep FeatureFlags
 }
 function compare_vault_features {
-	old_vault="$1"
-	new_vault="$2"
+	local old_vault="$1" new_vault="$2" old_vault_features new_vault_features
 	old_vault_features="$(get_vault_features "$old_vault")"
 	new_vault_features="$(get_vault_features "$new_vault")"
 	if test "$old_vault_features" = "$new_vault_features"; then
 		echo
-		echo-red "No need for vault upgrade!"
+		echo-color --red "No need for vault upgrade!"
 		echo "$old_vault and $new_vault"
 		echo "both have the same features"
 		return 1
 	else
 		echo
-		echo-green "Vault upgrade makes sense, changing features from:"
-		echo-black "$old_vault"
+		echo-color --green "Vault upgrade makes sense, changing features from:"
+		echo-color --bold "$old_vault"
 		echo "$old_vault_features"
-		echo-black "$new_vault"
+		echo-color --bold "$new_vault"
 		echo "$new_vault_features"
 	fi
 }
@@ -179,7 +177,7 @@ function is_drive_mounted {
 # VERIFY CONFIGURATION
 
 echo
-echo "Verifying configuration..."
+echo-color --header "Verifying configuration..."
 
 # verify drive
 # /dev/* locations can change, or be missing, so check for that
@@ -193,99 +191,98 @@ owner="$(uid "$option_user"):$(gid "$option_group")"
 gocryptfs_version="$(gocryptfs --version | rg -o '20\d+-\d+-\d+')"
 
 # upgrade configuration
-old_cipher="$option_cipher"  # this should never be different, they should always be the same
+old_cipher="$option_cipher" # this should never be different, they should always be the same
 old_plain="${option_plain}-old"
 new_cipher="${option_cipher}-${gocryptfs_version}"
 new_plain="${option_plain}-${gocryptfs_version}"
-
 
 # =====================================
 # ACTION
 
 echo
-echo "Verifying internet..."
+echo-color --header "Verifying internet..."
 
 is-internet-working
 
 echo
-echo "Proceeding with action..."
+echo-color --header "Proceeding with action..."
 
 # prepare helpers and actions
 function do_disable {
-	echo-bold 'disabling auto-start of services...'
-	set -x  # <debug>
+	echo-color --bold 'disabling auto-start of services...'
+	set -x # <debug>
 	sudo systemctl disable smbd || :
 	sudo systemctl disable plexmediaserver || :
 	sudo systemctl disable resilio-sync || :
 	sudo systemctl disable docker || :
 	sudo systemctl disable docker.socket || :
-	set +x  # </debug>
-	echo-green 'disabled auto-start of services.'
+	set +x # </debug>
+	echo-color --green 'disabled auto-start of services.'
 }
 function do_status {
-	echo-bold 'fetching status of services...'
-	set -x  # <debug>
+	echo-color --bold 'fetching status of services...'
+	set -x # <debug>
 	sudo systemctl status smbd --no-pager || :
 	sudo systemctl status plexmediaserver --no-pager || :
 	sudo systemctl status resilio-sync --no-pager || :
 	sudo systemctl status docker --no-pager || :
 	sudo systemctl status docker.socket --no-pager || :
 	seedbox status || :
-	set +x  # </debug>
-	echo-green 'fetched status of services.'
+	set +x # </debug>
+	echo-color --green 'fetched status of services.'
 }
 function act_stop {
-	echo-bold 'stopping services and unmonting...'
+	echo-color --bold 'stopping services and unmonting...'
 
 	do_disable
 
-	set -x  # <debug>
+	set -x # <debug>
 	sudo systemctl stop smbd || :
 	sudo systemctl stop plexmediaserver || :
 	sudo systemctl stop resilio-sync || :
 	timeout 60s seedbox stop || :
 	sudo timeout 60s systemctl stop docker || :
 	# sudo systemctl stop docker.socket || :
-	set +x  # </debug>
+	set +x # </debug>
 
 	act_unmount
-	echo-green 'stopped services and unmounted.'
+	echo-color --green 'stopped services and unmounted.'
 }
 function act_start {
-	echo-bold 'mounting and starting services...'
+	echo-color --bold 'mounting and starting services...'
 	act_mount
 
 	do_disable
 
-	set -x  # <debug>
+	set -x # <debug>
 	sudo systemctl restart docker || :
 	sudo systemctl restart smbd || :
 	sudo systemctl restart plexmediaserver || :
 	sudo systemctl restart resilio-sync || :
 	seedbox start || seedbox upgrade || :
-	set +x  # </debug>
+	set +x # </debug>
 
 	do_status
 
-	echo-green 'mounted and started services.'
+	echo-color --green 'mounted and started services.'
 }
 function act_reboot {
-	echo-bold 'stopping services and rebooting system...'
+	echo-color --bold 'stopping services and rebooting system...'
 	act_stop
 	sudo shutdown --reboot
-	echo-green 'stopped services and started reboot of system.'
+	echo-color --green 'stopped services and started reboot of system.'
 }
 function act_shutdown {
-	echo-bold 'stopping services and shutting down system...'
+	echo-color --bold 'stopping services and shutting down system...'
 	act_stop
 	sudo shutdown --poweroff
-	echo-green 'stopped services and started shutdown of system.'
+	echo-color --green 'stopped services and started shutdown of system.'
 }
 function act_size {
 	if is_drive_mounted; then
 		get-size "$option_drive_mount"
 	else
-		echo-red "Not yet mounted: $option_drive_mount"
+		echo-color --red "Not yet mounted: $option_drive_mount"
 		return 1
 	fi
 }
@@ -313,8 +310,9 @@ function act_info {
 	echo-eval gocryptfs --info "$old_cipher"
 }
 function do_setup_restore {
-	local _root="$(ask --question="Where is root file system to copy from?" --required)"
-	local paths=(
+	local _root _source paths
+	_root="$(ask --question="Where is root file system to copy from?" --required)"
+	paths=(
 		# fuse
 		/etc/fuse.conf
 
@@ -331,12 +329,13 @@ function do_setup_restore {
 		/lib/systemd/system/plexmediaserver.service
 		/var/lib/plexmediaserver/
 	)
-	local _source; for _path in "${paths[@]}"; do
+	for _path in "${paths[@]}"; do
 		_source="$(fs-join "$_root" "$_path")"
 		cpr --sudo --tool=rsync --action=copy --source="$_source" --destination="$_path"
 	done
 }
 function do_setup_plex {
+	local plex_config plex_user plex_group
 	# https://support.plex.tv/articles/235974187#enable-repository-updating-for-supported-linux-server-distributions/
 	# https://www.plex.tv/media-server-downloads##plex-media-server
 
@@ -346,18 +345,19 @@ function do_setup_plex {
 	sudo systemctl stop plexmediaserver || :
 
 	# configure
-	local plex_config='/lib/systemd/system/plexmediaserver.service'
+	plex_config='/lib/systemd/system/plexmediaserver.service'
 	if confirm-negative "Customise Plex Media Server configuration?"; then
 		sudo nano "$plex_config"
 	fi
 
 	# permissions
-	local plex_user="$(config-helper --file="$plex_config" --find='User=(.*)')"
-	local plex_group="$(config-helper --file="$plex_config" --find='Group=(.*)')"
+	plex_user="$(config-helper --file="$plex_config" --find='User=(.*)')"
+	plex_group="$(config-helper --file="$plex_config" --find='Group=(.*)')"
 	sudo gpasswd -a "$plex_user" "$option_group"
 	fs-own --user="$plex_user" --group="$plex_group" -- /var/lib/plexmediaserver/
 }
 function do_setup_resilio {
+	local resilio_config resilio_user resilio_group
 	# https://help.resilio.com/hc/en-us/articles/206178924
 	# https://help.resilio.com/hc/en-us/articles/204762449-Guide-to-Linux
 
@@ -367,15 +367,15 @@ function do_setup_resilio {
 	sudo systemctl stop resilio-sync || :
 
 	# configure
-	local resilio_config='/lib/systemd/system/resilio-sync.service'
+	resilio_config='/lib/systemd/system/resilio-sync.service'
 	if confirm-negative "Customise Resilio Sync configuration?"; then
 		sudo nano "$resilio_config"
 		sudo nano /etc/resilio-sync/config.json
 	fi
 
 	# permissions
-	local resilio_user="$(config-helper --file="$resilio_config" --find='User=(.*)')"
-	local resilio_group="$(config-helper --find="$resilio_config" --find='Group=(.*)')"
+	resilio_user="$(config-helper --file="$resilio_config" --find='User=(.*)')"
+	resilio_group="$(config-helper --find="$resilio_config" --find='Group=(.*)')"
 	sudo gpasswd -a "$resilio_user" "$option_group"
 	fs-own --user="$resilio_user" --group="$resilio_group" -- /etc/resilio-sync/ /var/lib/resilio-sync/
 }
@@ -463,13 +463,13 @@ function do_remove {
 	for path in "$@"; do
 		# trim
 		if do_trim "$path"; then
-			echo-green "[$path] trimmed and removed."
-		elif confirm-positive "$(echo-green "Confirm removal of non-empty directory: $path")"; then
-			sudo rm -RfvI "$path" || :  # may or may not remove
+			echo-color --green "[$path] trimmed and removed."
+		elif confirm-positive "$(echo-color --green "Confirm removal of non-empty directory: $path")"; then
+			sudo rm -RfvI "$path" || : # may or may not remove
 		fi
 		# confirm that it is removed
 		if ! is-missing "$path"; then
-			echo-red "[$path] failed to remove."
+			echo-color --red "[$path] failed to remove."
 			return 1
 		fi
 	done
@@ -493,15 +493,15 @@ function act_run {
 function do_unmount {
 	local path="$1"
 	echo
-	echo-bold "[$path] unmounting..."
+	echo-color --bold "[$path] unmounting..."
 	# exists
 	if is-missing "$path"; then
 		# unmounted
-		echo-green "[$path] already unmounted."
+		echo-color --green "[$path] already unmounted."
 	else
 		# unmount
 		fs-unmount "$path"
-		echo-green "[$path] unmounted."
+		echo-color --green "[$path] unmounted."
 		do_remove "$path"
 	fi
 }
@@ -531,19 +531,19 @@ function do_mount {
 
 	# recreate
 	echo
-	echo-bold "[$mount_target] making..."
+	echo-color --bold "[$mount_target] making..."
 	sudo mkdir -p "$mount_target"
 	act_chown "$mount_target"
 
 	# mount
 	echo
-	echo-bold "Mounting:"
+	echo-color --bold "Mounting:"
 	echo "$mount_source => $mount_target"
 	if is_drive "$mount_source"; then
 		# mount drive
 		sudo mount "$mount_source" "$mount_target"
 	elif is_vault "$mount_source"; then
-		echo-bold 'Enter the cipher password for mounting:'
+		echo-color --bold 'Enter the cipher password for mounting:'
 		echo "$mount_source => $mount_target"
 
 		# mount vault
@@ -554,7 +554,7 @@ function do_mount {
 		echo
 	else
 		echo
-		echo-red 'Failed to mount:'
+		echo-color --red 'Failed to mount:'
 		echo "$mount_source => $mount_target"
 		return 1
 	fi
@@ -589,27 +589,27 @@ function do_trim {
 
 	# missing
 	if is-missing "$path"; then
-		echo-green "[$path] already removed."
+		echo-color --green "[$path] already removed."
 		return
 	fi
 
 	# empty
 	if is-empty-ls "$path"; then
-		echo-green "[$path] is an empty directory."
+		echo-color --green "[$path] is an empty directory."
 	fi
 
 	# trim
 	do_size "$path"
-	echo-green "[$path] trimming empty directories."
+	echo-color --green "[$path] trimming empty directories."
 	sudo find "$path" -empty -type d -delete || :
 	do_run find "$path" -empty -type d -delete || :
 	if is-missing "$path"; then
-		echo-green "[$path] trimmed empty directories within, including itself."
+		echo-color --green "[$path] trimmed empty directories within, including itself."
 		return
 	fi
 
 	# leftovers
-	echo-bold "[$path] trimmed empty directories within, but not itself."
+	echo-color --bold "[$path] trimmed empty directories within, but not itself."
 	do_size "$path"
 	return 1
 }
@@ -617,14 +617,14 @@ function do_size {
 	local path="$1"
 
 	if is-missing "$path"; then
-		echo-green "[$path] already removed."
+		echo-color --green "[$path] already removed."
 		return
 	fi
 
 	echo-eval ls -la "$path"
 
 	if is-empty-ls "$path"; then
-		echo-green "[$path] is an empty directory."
+		echo-color --green "[$path] is an empty directory."
 		return
 	fi
 
@@ -632,11 +632,11 @@ function do_size {
 	echo-eval dust -f "$path"
 
 	if is-empty-size "$path"; then
-		echo-green "[$path] is only empty directories."
+		echo-color --green "[$path] is only empty directories."
 		return
 	fi
 
-	echo-red "[$path] is not empty, it has non-empty files..."
+	echo-color --red "[$path] is not empty, it has non-empty files..."
 	return
 }
 function do_migrate {
@@ -671,18 +671,20 @@ function act_upgrade {
 	# create
 	echo
 	if is_vault "$new_cipher"; then
-		echo-bold "The new vault [$new_cipher] already exists..."
-		echo-bold "This means a vault upgrade was started but not finished."
-		echo-bold "We will continue with this vault, if you wish setup a new one, remove the old one first."
+		echo-color --bold \
+			"The new vault [$new_cipher] already exists..." $'\n' \
+			"This means a vault upgrade was started but not finished." $'\n' \
+			"We will continue with this vault, if you wish setup a new one, remove the old one first."
 	elif is-missing "$new_cipher" || is-empty-ls "$new_cipher"; then
 		# act_run to ensure it creates with the right perms
-		echo-bold "Creating a new vault vault at [$new_cipher]..."
+		echo-color --bold "Creating a new vault vault at [$new_cipher]..."
 		option_algorithm="$(choose-option --question="Which algorithm to use?" --filter="$option_algorithm" -- aessiv xchacha)"
 		act_run gocryptfs --init --"$option_algorithm" "$new_cipher"
 		act_chown "$new_cipher"
 	else
-		echo-red "Something already existed at [$new_cipher] which was not a known vault structure..."
-		echo-red "Leaving for you to figure out."
+		echo-color --red \
+			"Something already existed at [$new_cipher] which was not a known vault structure..." $'\n' \
+			"Leaving for you to figure out."
 		echo-eval ls -la "$new_cipher"
 		return 1
 	fi
@@ -733,7 +735,7 @@ function act_upgrade {
 }
 
 # action
-if test "$(type -t "act_$option_action")" = 'function' ; then
+if test "$(type -t "act_$option_action")" = 'function'; then
 	"act_$option_action" "${args[@]}"
 else
 	stderr echo 'action not yet implemented'
