sparse-vault: interactive options/args
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/sparse-vault b/commands/sparse-vault
--- a/commands/sparse-vault
+++ b/commands/sparse-vault
@@ -1,36 +1,52 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-action="${1:?"USAGE: sparse-vault <new|open>"}"
+# options
+action="$(choose-option --question='What action would you like to do?' --filter="${1-}" -- create open)"
+if test "$action" = 'open'; then
+	option_path="$(ask --question='Enter its path.')"
 
-if is-either "$action" "new" "create"; then
-	name="${2:?"USAGE: sparse-vault new <NAME> <MAXSIZE|100g|1t> [SPARSE|SPARSEBUNDLE]"}"
-	size="${3:?"USAGE: sparse-vault new <name> <MAXSIZE|100g|1t> [SPARSE|SPARSEBUNDLE]"}"
-	type="${4:-SPARSE}"
+	echo
+	echo 'Compacting...'
+	(hdiutil compact "$option_path" && echo 'Compacted.') || echo 'Compact failed, not an issue, continuing.'
 
-	vol=$(basename "$name")
+	echo
+	echo 'Mounting...'
+	hdiutil mount "$option_path"
+	echo 'Mounted.'
+else
+	option_name="$(ask --question='Enter its name.')"
+	option_size="$(ask --question='Enter its maximum size. E.g. MAXSIZE|100g|1t')"
+	option_type="$(choose-option --question='Enter its type.' -- sparseimage sparsebundle)"
+
+	vol=$(basename "$option_name")
 	version=$(sw_vers -productVersion | awk -F '.' '{print $2}')
+	create_args=(
+		'-encryption' 'AES-256'
+		'-size' "$option_size"
+		'-volname' "$vol"
+	)
 
 	if test "$version" -ge "13"; then
-		fs="APFS"
+		create_args+=('-fs' 'APFS')
 	else
-		fs="Journaled HFS+"
+		create_args+=('-fs' 'Journaled HFS+')
 	fi
-	if test "$type" = "SPARSE"; then
-		filename="$2.sparseimage"
+	if test "$option_type" = 'sparseimage'; then
+		create_args+=('-type' 'SPARSE')
+		filename="${option_name}.sparseimage"
 	else
-		filename="$2.sparsebundle"
+		create_args+=('-type' 'SPARSEBUNDLE')
+		filename="${option_name}.sparsebundle"
 	fi
 
-	hdiutil create -type "$type" -encryption AES-256 -fs "$fs" -size "$size" -volname "$vol" "$name"
+	echo
+	echo 'Creating...'
+	hdiutil create "${create_args[@]}" "$option_name"
+	echo 'Created.'
+
+	echo
+	echo 'Mounting...'
 	hdiutil mount "$filename"
-
-elif is-either "$action" "open" "mount"; then
-	path="${2:?"SAGE: sparse-vault open <PATH>"}"
-	hdiutil compact "$path" || echo 'compact failed, continuing...'
-	hdiutil mount "$path"
-
-else
-	stderr echo "unknown state"
-	exit 1
+	echo 'Mounted.'
 fi
