add help fn up until `setup-util-*`

diff --git a/commands/sparse-vault b/commands/sparse-vault
--- a/commands/sparse-vault
+++ b/commands/sparse-vault
@@ -1,37 +1,81 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
-# options
-action="$(choose-option --question='What action would you like to do?' --filter="${1-}" -- create open)"
-if test "$action" = 'open'; then
+# =====================================
+# Arguments
+
+# help
+function help() {
+	cat <<-EOF >/dev/stderr
+		ABOUT:
+		    ???
+		USAGE:
+            ???
+	EOF
+	if test "$#" -ne 0; then
+		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
+	fi
+	return 22 # Invalid argument
+}
+
+# process
+local action option_name option_size option_type option_path
+while test "$#" -ne 0; do
+	item="$1"
+	shift
+	case "$item" in
+	'create' | 'open') action="$item" ;;
+	'--name='* ) name="${item:7}" ;;
+	'--size='* ) size="${item:7}" ;;
+	'--type='* ) type="${item:7}" ;;
+	'--path='* ) path="${item:7}" ;;
+	'help' | '--help' | '-h') help ;;
+	'--'*) help "An unrecognised flag was provided: $item" ;;
+	*) help "An unrecognised argument was provided: $item" ;;
+	esac
+done
+
+if test -z "$action"; then
+    action="$(choose-option --question='What action would you like to do?' --filter="${action-}" -- create open)"
+fi
+if test -z "$action" = 'open' -a -z "$option_path"; then
 	option_path="$(
 		ask \
 			--question='Enter its path.'
 	)"
-
-	echo
-	echo 'Compacting...'
-	(hdiutil compact "$option_path" && echo 'Compacted.') || echo 'Compact failed, not an issue, continuing.'
-
-	echo
-	echo 'Mounting...'
-	hdiutil mount "$option_path"
-	echo 'Mounted.'
-else
+fi
+if test -z "$action" = 'create' -a -z "$option_name"; then
 	option_name="$(
 		ask \
 			--question='Enter its name.'
 	)"
+fi
+if test -z "$action" = 'create' -a -z "$option_size"; then
 	option_size="$(
 		ask \
 			--question='Enter its maximum size. E.g. MAXSIZE|100g|1t'
 	)"
+fi
+if test -z "$action" = 'create' -a -z "$option_type"; then
 	option_type="$(
 		choose-option \
 			--question='Enter its type.' \
 			-- sparseimage sparsebundle
 	)"
+fi
 
+# =====================================
+# Act
+
+if test "$action" = 'open'; then
+	echo
+	echo 'Compacting...'
+	(hdiutil compact "$option_path" && echo 'Compacted.') || echo 'Compact failed, not an issue, continuing.'
+	echo
+	echo 'Mounting...'
+	hdiutil mount "$option_path"
+	echo 'Mounted.'
+else
 	vol=$(basename "$option_name")
 	version=$(sw_vers -productVersion | awk -F '.' '{print $2}')
 	create_args=(
@@ -39,7 +83,6 @@ else
 		'-size' "$option_size"
 		'-volname' "$vol"
 	)
-
 	if test "$version" -ge "13"; then
 		create_args+=('-fs' 'APFS')
 	else
@@ -52,7 +95,6 @@ else
 		create_args+=('-type' 'SPARSEBUNDLE')
 		filename="${option_name}.sparsebundle"
 	fi
-
 	echo
 	echo 'Creating...'
 	hdiutil create "${create_args[@]}" "$option_name"
