internal formatting changes
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/sparse-vault b/commands/sparse-vault
--- a/commands/sparse-vault
+++ b/commands/sparse-vault
@@ -27,7 +27,7 @@ if is-either "$action" "new" "create"; then
 
 elif is-either "$action" "open" "mount"; then
 	path="${2:?"SAGE: sparse-vault open <PATH>"}"
-	hdiutil compact "$path" || echo "compact failed, continuing..."
+	hdiutil compact "$path" || echo 'compact failed, continuing...'
 	hdiutil mount "$path"
 
 else
