until-success, until-ssh-success, retry
reworked them so they actually do what they are meant to do

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/commands/until-success b/commands/until-success
--- a/commands/until-success
+++ b/commands/until-success
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
-# no strict as we need exit codes
+source "$DOROTHY/sources/strict.bash"
 
-( "$@" ); while test "$?" -ne 0; do
-	sleep 1000; ( "$@" )
-done
+("$@") || {
+	stderr echo "failed with $? will try again in 10 seconds..."
+	sleep 10
+	until-success "$@"
+}
