add help to all files from z upuntil unziptar. unziptar is not finished

diff --git a/commands/what-is-my-gateway b/commands/what-is-my-gateway
--- a/commands/what-is-my-gateway
+++ b/commands/what-is-my-gateway
@@ -6,7 +6,38 @@ source "$DOROTHY/sources/ripgrep.bash"
 env QUIET=yes setup-util-sd
 env QUIET=yes setup-util-netstat
 
-# act
+# =====================================
+# Arguments
+
+# help
+function help() {
+	cat <<-EOF >/dev/stderr
+		ABOUT:
+		???
+
+		USAGE:
+		what-is-my-gateway
+	EOF
+	if test "$#" -ne 0; then
+		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
+	fi
+	return 22 # Invalid argument
+}
+
+# process
+while test "$#" -ne 0; do
+	item="$1"
+	shift
+	case "$item" in
+	'--help' | '-h') help ;;
+	'--'*) help "An unrecognised flag was provided: $item" ;;
+	*) help "An unrecognised argument was provided: $item" ;;
+	esac
+done
+
+# =====================================
+# Act
+
 if command-exists ip; then
 	# shellcheck disable=SC2016
 	ip route show dev eth0 | rg -o 'via (.+?) ' --replace '$1' | echo-first
@@ -14,6 +45,6 @@ elif command-exists netstat; then
 	# shellcheck disable=SC2016
 	netstat -nr | rg ' UG.+?(en0|eth0)' | sd '(0.0.0.0|default) +(.+?) .+' '$2' | echo-first
 else
-	stderr echo 'install [ip] or [netstat] and try again'
-	exit 1
+	echo-style --error='install [ip] or [netstat] and try again' > /dev/stderr
+	exit 19 # ENODEV 19 Operation not supported by device
 fi
diff --git a/commands/what-is-my-ip b/commands/what-is-my-ip
--- a/commands/what-is-my-ip
+++ b/commands/what-is-my-ip
@@ -1,21 +1,45 @@
 #!/usr/bin/env bash
 source "$DOROTHY/sources/strict.bash"
 
+# =====================================
+# Arguments
+
 # help
-if is-help "$@"; then
+function help() {
 	cat <<-EOF >/dev/stderr
 		ABOUT:
-		?????
-	EOF
-	return 22 # Invalid argument
-fi
+		Get your local or remote IP address.
 
-# options
+		USAGE:
+		what-is-my-ip [local|remote]
+	EOF
+	if test "$#" -ne 0; then
+		echo-style $'\n' --error="ERROR:" $'\n' --red="$(echo-lines -- "$@")" >/dev/stderr
+	fi
+	return 22 # Invalid argument
+}
+
+# process
+what=''
+while test "$#" -ne 0; do
+	item="$1"
+	shift
+	case "$item" in
+	'local' | 'remote') what="$item" ;;
+	'--'*) help "An unrecognised flag was provided: $item" ;;
+	*) help "An unrecognised argument was provided: $item" ;;
+	esac
+done
+
+# ensure
 what="$(
-	choose-option \
-		--question='Which IP do you want?' \
-		--filter="${1-}" -- local remote
+	choose-option --required \
+		--question='Which IP address do you want?' \
+		--filter="$what" -- local remote
 )"
+
+# =====================================
+# Act
 
 if test "$what" = 'remote'; then
 	# does not take into account cloudflare warp
@@ -38,6 +62,6 @@ elif command-exists ifconfig; then
 	# shellcheck disable=SC2016
 	ifconfig | rg -o 'inet ((192\.168\.|10\.0\.)\d+\.\d+)' --replace '$1'
 else
-	stderr echo 'unsupported environment'
-	exit 1
+	echo-style --error='unsupported environment' > /dev/stderr
+	exit 19 # ENODEV 19 Operation not supported by device
 fi
