balupton: boundation-upgrade: skip npm owner add
as it would often fail unncessarily, so better to just run manually

diff --git a/users/balupton/commands/boundation-upgrade b/users/balupton/commands/boundation-upgrade
--- a/users/balupton/commands/boundation-upgrade
+++ b/users/balupton/commands/boundation-upgrade
@@ -67,9 +67,9 @@ github-prepare
 ok git rm -rf docs
 git add .
 git commit -am "$v - boundation, changelog, version bump"
-if ! npm owner add bevryme; then
-	echo 'adding npm owner failed, trying again in two minutes'
-	sleep 2m
-	npm owner add bevryme
-fi
+# if ! npm owner add bevryme; then
+# 	echo 'adding npm owner failed, trying again in two minutes'
+# 	sleep 2m
+# 	npm owner add bevryme
+# fi
 github-release
