getapp: now supports with or without the .app suffix

diff --git a/.scripts/commands/getapp b/.scripts/commands/getapp
--- a/.scripts/commands/getapp
+++ b/.scripts/commands/getapp
@@ -1,13 +1,23 @@
 #!/usr/bin/env bash
 set -e
 
-# Setup binary files
-p="$HOME/Applications/$*"
-if is_dir "$p"; then
-	echo "$p"
+name="$*"
+basename="${name%.app}"
+path="$HOME/Applications/$name"
+if is_dir "$path"; then
+	app="$path"
 else
-	p="/Applications/$*"
-	if is_dir "$p"; then
-		echo "$p"
+	path="/Applications/$name"
+	if is_dir "$path"; then
+		app="$path"
 	fi
+fi
+
+if test -n "$app"; then
+	echo "$app"
+elif test "$basename" == "$name"; then
+	getapp "$basename.app"
+else
+	stderr echo "couldn't find app: $basename"
+	exit 1
 fi
