mac-state to macos-state

diff --git a/.scripts/commands/macos-state b/.scripts/commands/macos-state
--- a/.scripts/commands/macos-state
+++ b/.scripts/commands/macos-state
@@ -3,8 +3,8 @@ set -e
 
 if test "$1" != "backup" -a "$1" != "restore"; then
 	stderr echo "USAGE:"
-	stderr echo "BACKUP TO CLOUD: mac-state backup"
-	stderr echo "RESTORE FROM TIME MACHINE: mac-state restore"
+	stderr echo "BACKUP TO CLOUD: macos-state backup"
+	stderr echo "RESTORE FROM TIME MACHINE: macos-state restore"
 	exit 1
 fi
 
@@ -20,53 +20,52 @@ echo ''
 echo 'What is your local volume?'
 export localRoot; localRoot="$(choose-subdir /Volumes)"
 
-export backupRoot="$2";
-if is-empty-string "$backupRoot"; then
-	echo ''
-	echo 'Fetching Time Machine backup automatically...'
-	timeRoot="$(tmutil latestbackup || exit 0)"
-	if ! is-dir "$timeRoot"; then
-		echo ''
-		echo 'Fetching Time Machine backup manually...'
-		echo ''
-		echo 'Which volume contains the time machine backups?'
-		timeBackupVolume="$(choose-subdir /Volumes)"
-		echo ''
-		echo 'Which machine has the backups?'
-		timeBackupMachine="$(choose-subdir "$timeBackupVolume/Backups.backupdb")"
-		timeRoot="$timeBackupMachine/Latest"
-	fi
-
-	if ! is-dir "$timeRoot"; then
-		stderr echo 'Time Machine backup could not be determined'
-		exit 1
-	fi
-
-	echo ''
-	echo 'Selecting volume...'
-	if is-dir "$timeRoot/Macintosh HD"; then
-		timeRoot="$timeRoot/Macintosh HD"
-	elif is-dir "$timeRoot/System"; then
-		timeRoot="$timeRoot/System"
-	else
-		timeRoot="$timeRoot/$(choose-subdir "$timeRoot")"
-	fi
-
-	if ! is-dir "$timeRoot/$HOME"; then
-		stderr echo "Could not find user directory in time machine backup directory: $timeRoot"
-		exit 1
-	fi
-
-	backupRoot="$timeRoot"
-fi
-
-echo ''
 if is-equal "$action" "restore"; then
-	echo "Restoring from: $backupRoot"
-fi
+	export backupRoot="$2";
+	if is-empty-string "$backupRoot"; then
+		echo ''
+		echo 'Fetching Time Machine backup automatically...'
+		timeRoot="$(tmutil latestbackup || exit 0)"
+		if ! is-dir "$timeRoot"; then
+			echo ''
+			echo 'Fetching Time Machine backup manually...'
+			echo ''
+			echo 'Which volume contains the time machine backups?'
+			timeBackupVolume="$(choose-subdir /Volumes)"
+			echo ''
+			echo 'Which machine has the backups?'
+			timeBackupMachine="$(choose-subdir "$timeBackupVolume/Backups.backupdb")"
+			timeRoot="$timeBackupMachine/Latest"
+		fi
 
-echo ''
-echo 'What would you like to restore?'
+		if ! is-dir "$timeRoot"; then
+			stderr echo 'Time Machine backup could not be determined'
+			exit 1
+		fi
+
+		echo ''
+		echo 'Selecting volume...'
+		if is-dir "$timeRoot/Macintosh HD"; then
+			timeRoot="$timeRoot/Macintosh HD"
+		elif is-dir "$timeRoot/System"; then
+			timeRoot="$timeRoot/System"
+		else
+			timeRoot="$timeRoot/$(choose-subdir "$timeRoot")"
+		fi
+
+		if ! is-dir "$timeRoot/$HOME"; then
+			stderr echo "Could not find user directory in time machine backup directory: $timeRoot"
+			exit 1
+		fi
+
+		backupRoot="$timeRoot"
+	fi
+
+	echo ''
+	if is-equal "$action" "restore"; then
+		echo "Restoring from: $backupRoot"
+	fi
+fi
 
 function backup {
 	echo "backup: $1"
