macup: add DNScrypt and support non-home paths

diff --git a/.scripts/commands/macup b/.scripts/commands/macup
--- a/.scripts/commands/macup
+++ b/.scripts/commands/macup
@@ -14,84 +14,118 @@ echo -e '\n'
 
 export warnings="";
 export action="$1"
-export localRoot="$HOME"
 export cloudRoot="$HOME/Library/Mobile Documents/com~apple~CloudDocs/Apps/macup"
 
-export timeBackup="$2";
-if is_empty_string "$timeBackup"; then
-	echo "Fetching Time Machine backup automatically..."
-	timeBackup="$(tmutil latestbackup || exit 0)"
-	if ! is_dir "$timeBackup"; then
+echo ''
+echo 'What is your local volume?'
+export localRoot; localRoot="$(choose-subdir /Volumes)"
+
+export backupRoot="$2";
+if is_empty_string "$backupRoot"; then
+	echo ''
+	echo 'Fetching Time Machine backup automatically...'
+	timeRoot="$(tmutil latestbackup || exit 0)"
+	if ! is_dir "$timeRoot"; then
 		echo ''
 		echo 'Fetching Time Machine backup manually...'
 		echo ''
 		echo 'Which volume contains the time machine backups?'
-		backupVolume="$(choose-subdir /Volumes)"
+		timeBackupVolume="$(choose-subdir /Volumes)"
 		echo ''
 		echo 'Which machine has the backups?'
-		backupMachine="$(choose-subdir "$backupVolume/Backups.backupdb")"
-		timeBackup="$backupMachine/Latest"
+		timeBackupMachine="$(choose-subdir "$timeBackupVolume/Backups.backupdb")"
+		timeRoot="$timeBackupMachine/Latest"
 	fi
-	if ! is_dir "$timeBackup"; then
+
+	if ! is_dir "$timeRoot"; then
 		echo 'Time Machine backup could not be determined'
 		exit 1
 	fi
-fi
 
-export timeRoot;
-if is_dir "$timeBackup/Macintosh HD$HOME"; then
-	timeRoot="$timeBackup/Macintosh HD$HOME"
-elif is_dir "$timeBackup/System$HOME"; then
-	timeRoot="$timeBackup/System$HOME"
-elif is_dir "$timeBackup$HOME"; then
-	timeRoot="$timeBackup$HOME"
-elif is_dir "$(expandpath "$timeBackup/*$HOME")"; then
-	timeRoot="$(expandpath "$timeBackup/*$HOME")"
-else
-	echo "Could not find user directory in time machine backup: $timeBackup"
-	exit 1
+	echo ''
+	echo 'Selecting volume...'
+	if is_dir "$timeRoot/Macintosh HD"; then
+		timeRoot="$timeRoot/Macintosh HD"
+	elif is_dir "$timeRoot/System"; then
+		timeRoot="$timeRoot/System"
+	else
+		timeRoot="$timeRoot/$(choose-subdir "$timeRoot")"
+	fi
+
+	if ! is_dir "$timeRoot/$HOME"; then
+		echo "Could not find user directory in time machine backup directory: $timeRoot"
+		exit 1
+	fi
+
+	backupRoot="$timeRoot"
 fi
 
 echo ''
 if is_equal "$action" "restore"; then
-	echo "Restoring from: $timeRoot"
+	echo "Restoring from: $backupRoot"
 fi
+
 echo ''
 echo 'What would you like to restore?'
 
 function backup {
 	echo "backup: $1"
-	if is_exists "$localRoot/$1"; then
-		sudo rm -Rf "$cloudRoot/$1"
-		mkdir -p "$(dirname "$cloudRoot/$1")"
-		cp -fpLRv "$localRoot/$1" "$cloudRoot/$1"
+
+	local from
+	local to
+	if [[ "$1" = "/"* ]]; then
+		from="$localRoot$1"
+		to="$cloudRoot$1"
 	else
-		warning="MISSING: $localRoot/$1"
-		warnings="$warnings\n$warning"
-		echo "$warning"
+		from="$localRoot$HOME/$1"
+		to="$cloudRoot$HOME/$1"
+	fi
+
+	if is_exists "$from"; then
+		sudo rm -Rf "$to"
+		mkdir -p "$(dirname "$to")"
+		cp -fpLRv "$from" "$to"
+	else
+		warning="MISSING: $from"
+		warnings="$warnings\\n$warning"
+		echo -e "$warning"
 	fi
 }
+
 function restore {
 	echo "Restoring: $1"
-	if is_exists "$timeRoot/$1"; then
-		sudo rm -Rf "$localRoot/$1"
-		mkdir -p "$(dirname "$localRoot/$1")"
+
+	local from
+	local to
+	if [[ "$1" = "/"* ]]; then
+		from="$backupRoot$1"
+		to="$localRoot$1"
+	else
+		from="$backupRoot$HOME/$1"
+		to="$localRoot$HOME/$1"
+	fi
+
+	if is_exists "$from"; then
+		sudo rm -Rf "$to"
+		mkdir -p "$(dirname "$to")"
 		if contains_word "$timeRoot" "Time Machine Backups"; then
-			tmutil restore -v "$timeRoot/$1" "$localRoot/$1"
+			tmutil restore -v "$from" "$to"
 		else
-			cp -fav "$timeRoot/$1" "$localRoot/$1"
-			own "$localRoot/$1"
+			cp -fav "$from" "$to"
+			own "$to"
 		fi
 	else
-		warning="MISSING: $timeRoot/$1"
-		warnings="$warnings\n$warning"
-		echo "$warning"
+		warning="MISSING: $from"
+		warnings="$warnings\\n$warning"
+		echo -e "$warning"
 	fi
 }
+
 function remove {
 	echo "Removing: $1"
 	sudo rm -Rf "$localRoot/$1"
 }
+
 function act {
 	if is_equal "$action" "backup"; then
 		backup "$1"
@@ -99,6 +133,7 @@ function act {
 		restore "$1"
 	fi
 }
+
 function process {
 	if confirm "$1"; then
 		for p in "${@:2}"; do
@@ -222,6 +257,7 @@ process "Cyberduck" \
 
 process "DevDocs" "Library/Application Support/DevDocs"
 process "DiskMap" "Library/Preferences/com.fiplab.diskmap.plist"
+process "DNSCrypt" '/usr/local/etc/dnscrypt-proxy.toml'
 
 process "Donut" \
 	"Library/Application Support/Donut" \
