Update macup

diff --git a/.scripts/commands/macup b/.scripts/commands/macup
--- a/.scripts/commands/macup
+++ b/.scripts/commands/macup
@@ -35,12 +35,13 @@ if is_dir "$timeBackup/Macintosh HD$HOME"; then
 	timeRoot="$timeBackup/Macintosh HD$HOME"
 elif is_dir "$timeBackup/System$HOME"; then
 	timeRoot="$timeBackup/System$HOME"
-else
+else if_dir "$timeBackup$HOME"; then
+	timeRoot="$timeBackup$HOME"
+else if_dir "$(expandpath "$timeBackup/*$HOME")"; then
 	timeRoot="$(expandpath "$timeBackup/*$HOME")"
-	if ! is_dir "$timeRoot"; then
-		echo "Could not find user directory in time machine backup"
-		exit 1
-	fi
+else
+	echo "Could not find user directory in time machine backup: $timeBackup"
+	exit 1
 fi
 
 function backup {
