b/c break for shellcheck compliance, see desc
this commit fixes nearly all of the shellcheck compliance issues, in order to acccomplish that, the following b/c breaks were performed:

1. the user env INSTALL variables are now arrays, as such, they must now be defined as such - to accomplish that, you probably want to rename your user `source.sh` to `source.bash` and adopt the bash array format (changing quotes into parenthesis)

2. the `contains` command has been renamed to the `conains_word` command - it has been updated to using posix compliant fuzzy matching

3. pdfdecrypt: failure condition has been fixed, as bash handles and/ors different than javascript

4. fixed npm package installs, was not using the correct user env var

diff --git a/.scripts/commands/pdfdecrypt b/.scripts/commands/pdfdecrypt
--- a/.scripts/commands/pdfdecrypt
+++ b/.scripts/commands/pdfdecrypt
@@ -11,16 +11,15 @@ outdir="$(fullpath "$outdir")"
 mkdir -p "$outdir"
 
 function decrypt {
-	local input="$(fullpath "$1")"
-	local inputdir="$(dirname "$input")"
-	local inputfile="$(basename "$input")"
-	local output="$outdir/$(basename "$1")"
+	local input; input="$(fullpath "$1")"
+	local inputdir; inputdir="$(dirname "$input")"
+	local output; output="$outdir/$(basename "$1")"
 	cd "$inputdir"
 	echo "$1 to $output"
 	while is_file "$output"; do
 		output="${output%.*}!.pdf"
 	done
-	qpdf -password="$password" -decrypt "$input" "$output" && echo "SUCCESS" || echo "FAILURE"
+	(qpdf -password="$password" -decrypt "$input" "$output" && echo "SUCCESS") || echo "FAILURE"
 	cd "$p"
 }
 
