podcast: different handling for mono and stereo

diff --git a/.scripts/commands/podcast b/.scripts/commands/podcast
--- a/.scripts/commands/podcast
+++ b/.scripts/commands/podcast
@@ -1,11 +1,88 @@
 #!/usr/bin/env bash
 set -e
 
-if is_empty_string "$1"; then
-	echo "podcast <in>"
-	exit 1
-else
-	out="${1%.*}-aac_he.m4a"
+# https://en.wikipedia.org/wiki/High-Efficiency_Advanced_Audio_Coding
+# https://en.wikipedia.org/wiki/Parametric_Stereo
+# https://developer.apple.com/library/content/technotes/tn2236/_index.html
+# https://developer.apple.com/library/content/technotes/tn2224/_index.html#//apple_ref/doc/uid/DTS40009745-CH1-SETTINGSFILES
+# https://trac.ffmpeg.org/wiki/Encode/AAC#fdk_he
+# https://trac.ffmpeg.org/wiki/AudioChannelManipulation
+
+# HE-AAC v2 for lower bitrates between 16 - 40 kb/s.
+# HE-AAC v1 for bitrates between 32 - 80 kb/s
+# AAC-LC for bitrates higher than 80 kb/s
+
+# HE-AAC v1 at 64 kb/s is comparable to AAC-LC at 96 kb/s.
+# HE-AAC version 2 (HE-AAC v2) adds Parametric Stereo (PS) to further enhance the compression efficiency of stereo signals at very low bit rates only. This technique is only useful at the lowest bitrates (approx. 16 - 48 kbit/s).
+
+# HE-AAC version 1 is suited for bit rates below 64kb/s (for stereo audio) down to about 48 kb/s
+# HE-AAC version 2 is suited for bit rates as low as 32 kb/s (again, for stereo)
+
+# HE-AAC version 2 only handles stereo
+# If you have mono, or want to down-mix to mono, use HE-AAC version 1
+
+# -profile:a aac_he -b:a 64k
+# -profile:a aac_he_v2 -b:a 32k
+
+function downmix {
+	out="${1%.*}-downmixed.m4a"
+	if codec "$1" | grep "alac"; then
+		ffmpeg -i "$1" -ac 1 -acodec alac "$out"
+	else
+		echo 'downmixing only supported on alac'
+		exit 1
+	fi
+	if is_mono "$out"; then
+		echo 'downmixing successful'
+	else
+		echo 'downmixing failed'
+		exit 1
+	fi
+	mono "$out"
+}
+function stereo {
+	out="${1%.*}-aac_he_v2-48k-stereo.m4a"
+	ffmpeg -i "$1" -c:a libfdk_aac -profile:a aac_he_v2 -b:a 48k "$out"
+	if is_stereo "$out"; then
+		echo 'stereo successful'
+	else
+		echo 'stereo failed'
+		exit 1
+	fi
+}
+function mono {
+	out="${1%.*}-aac_he_v1-48k-mono.m4a"
 	ffmpeg -i "$1" -c:a libfdk_aac -profile:a aac_he -b:a 48k "$out"
+	if is_mono "$out"; then
+		echo 'mono successful'
+	else
+		echo 'mono failed'
+		exit 1
+	fi
+}
+
+if is_empty_string "$1"; then
+	find ./*.mp4 | while read -r file; do
+		convert "$file"
+	done
+else
+
+	if is_stereo "$1"; then
+		if confirm "Would you like to downmix to mono?"; then
+			downmix "$1"
+		else
+			stereo "$1"
+		fi
+	else
+		mono "$1"
+	fi
+
+	# ffmpeg
+	# -i INPUT
+	# -b:a AUDIO_BITRATE
+	# -c:a AUDIO_CODEC
+	# -profile:a AUDIO_PROFILE
+	# -ac AUDIO_CHANNELS
+
 	#avconv -i "$1" -vn -c:a libfdk_aac -profile:a aac_he -b:a 48k "$out"
 fi
