secret: UX improvements - support multiple args to exist and delete - output error on invalid command - output usage on no command
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/.scripts/commands/secret b/.scripts/commands/secret
--- a/.scripts/commands/secret
+++ b/.scripts/commands/secret
@@ -78,13 +78,15 @@ function secret_clear() {
 }
 
 function secret_exists() {
-	key="$1"
-	sudo test -f "$HOME/.scripts/env/secrets/$key"
+	for key in "$@"; do
+		sudo test -f "$HOME/.scripts/env/secrets/$key"
+	done
 }
 
 function secret_delete() {
-	key="$1"
-	sudo rm -f "$HOME/.scripts/env/secrets/$key"
+	for key in "$@"; do
+		sudo rm -f "$HOME/.scripts/env/secrets/$key"
+	done
 }
 
 function secret_read() {
@@ -229,32 +231,36 @@ function secret_env() {
 	env "${envSecrets[@]}" "${envArgs[@]}"
 }
 
-if test "$1" = "setup"; then
-	secret_setup
-elif test "$1" = "env"; then
-	secret_env "${@:2}"
-elif test "$1" = "clear"; then
-	secret_clear
-elif test "$1" = "edit"; then
-	edit "$database"
-elif test "$1" = "signin"; then
-	secret_signout
-	secret_signin
-elif test "$1" = "signout"; then
-	secret_signout
-elif test "$1" = "delete"; then
-	if is-string "$2"; then
-		secret_delete "$2"
+if test -n "${1:-}"; then
+	if test "$1" = "setup"; then
+		secret_setup
+	elif test "$1" = "env"; then
+		secret_env "${@:2}"
+	elif test "$1" = "clear"; then
+		secret_clear
+	elif test "$1" = "edit"; then
+		edit "$database"
+	elif test "$1" = "signin"; then
+		secret_signout
+		secret_signin
+	elif test "$1" = "signout"; then
+		secret_signout
+	elif test "$1" = "delete"; then
+		if is-string "$2"; then
+			secret_delete "${@:2}"
+		else
+			stderr echo 'ERROR: <name> was not found. Refer to usage.'
+			exit 1
+		fi
+	elif test "$1" = "get"; then
+		if is-string "$2"; then
+			secret_resolve "${@:2}"
+		else
+			stderr echo 'ERROR: <name> was not found. Refer to usage.'
+			exit 1
+		fi
 	else
-		stderr echo 'ERROR: <name> was not found. Refer to usage.'
-		exit 1
-	fi
-elif test "$1" = "get"; then
-	if is-string "$2"; then
-		secret_resolve "${@:2}"
-	else
-		stderr echo 'ERROR: <name> was not found. Refer to usage.'
-		exit 1
+		stderr echo 'invalid command'
 	fi
 else
 	stderr echo 'USAGE:'
