secret: now handles failures more appropriately

diff --git a/.scripts/commands/secret b/.scripts/commands/secret
--- a/.scripts/commands/secret
+++ b/.scripts/commands/secret
@@ -19,13 +19,13 @@ function secret_resolve {
 
 	# singular
 	key="$1"
-	result="$(secret_read "$key" || echo -n '')"
+	result="$(secret_read "$key" || :)"
 	if test -n "$result"; then
 		echo -n "$result"
 	elif test -z "$result"; then
 		if ! sudo test -f "$database"; then
 			stderr echo -en "ERROR: secret requires [$database] to exist, in the format of:\\n{\\n  \"SECRET\": [\"vault\", \"item\", \"field\"]\\n}"
-			exit 1
+			return 1
 		fi
 		vault="$(sudo jq -r ".${key}[0]" "$database")"
 		item="$(sudo jq -r ".${key}[1]" "$database")"
@@ -34,13 +34,17 @@ function secret_resolve {
 			value="$(secret_fetch "$vault" "$item" "$field")"
 		else
 			stderr echo "ERROR: [$database] had an entry that did not have all three parts: [$vault] [$item] [$field]"
-			exit 1
+			return 1
+		fi
+		if test -z "$value"; then
+			stderr echo "ERROR: resolve returned nothing for: $key"
+			return 1
 		fi
 		secret_write "$key" "$value"
 		echo -n "$value"
 	else
 		echo "ERROR: could not fetch the secret: $key"
-		exit 1
+		return 1
 	fi
 }
 
@@ -54,7 +58,8 @@ function secret_write {
 		sudo chown root: "$HOME/.scripts/env/secrets/$key"
 		sudo chmod 600 "$HOME/.scripts/env/secrets/$key"
 	else
-		exit 1
+		stderr echo "ERROR: wanted to write empty secret: $key"
+		return 1
 	fi
 }
 
@@ -79,11 +84,13 @@ function secret_read {
 		if test -n "$value"; then
 			echo -n "$value"
 		else
+			stderr echo "ERROR: empty secret: $1"
 			secret_delete "$key"
-			exit 1
+			return 1
 		fi
 	else
-		exit 1
+		stderr echo "ERROR: missing secret: $1"
+		return 1
 	fi
 }
 
@@ -102,11 +109,11 @@ function secret_signout {
 
 function secret_signin {
 	if test -z "${OP_SESSION-}"; then
-		OP_SESSION="$(secret_read OP_SESSION || echo -n '')"
+		OP_SESSION="$(secret_read OP_SESSION || :)"
 		if test -z "$OP_SESSION"; then
-			if test -z "$OP_SUBDOMAIN"; then
-				OP_SUBDOMAIN="$(secret_read OP_SUBDOMAIN || echo -n '')"
-				if test -z "$OP_SUBDOMAIN"; then
+			if test -z "${OP_SUBDOMAIN-}"; then
+				OP_SUBDOMAIN="$(secret_read OP_SUBDOMAIN || :)"
+				if test -z "${OP_SUBDOMAIN-}"; then
 					OP_SUBDOMAIN="$(ask 'What is your 1password subdomain?')"
 					secret_write "OP_SUBDOMAIN" "$OP_SUBDOMAIN"
 				fi
@@ -120,14 +127,18 @@ function secret_signin {
 
 function secret_grab {
 	secret_signin
-	if result="$(op get item "$2" --vault="$1" --session="$OP_SESSION" 2>&1)"; then
-		echo -n "$result"
+	result="$(op get item "$2" --vault="$1" --session="$OP_SESSION" || :)"
+	if test -z "$result"; then
+		stderr echo "ERROR: Failed to fetch item $2 from vault $1. Nothing was returned."
+		return 1
 	elif [[ "$result" = *'You are not currently signed in'* ]]; then
-		stderr echo 'ERROR: Session expired. Run: secret signin'
-		exit 1
+		stderr echo "ERROR: Failed to fetch item $2 from vault $1. Session expired. Run: secret signin"
+		return 1
+	elif [[ "$result" = *'ERROR'* ]]; then
+		stderr echo "ERROR: Failed to fetch item $2 from vault $1. $result"
+		return 1
 	else
-		stderr echo "$result"
-		exit 1
+		echo -n "$result"
 	fi
 }
 
@@ -162,9 +173,8 @@ function secret_env {
 		vars=("${before[@]}")
 		args=("${after[@]}")
 	else
-		stderr echo 'ERROR: -- was not found'
-		stderr echo 'USAGE: secret env <secret...> -- <command> [args...]'
-		exit 1
+		stderr echo 'ERROR: -- was not found. Refer to usage.'
+		return 1
 		# vars=()
 		# args=("${before[@]}")
 	fi
@@ -209,14 +219,14 @@ elif test "$1" = "delete"; then
 	if test -n "$2"; then
 		secret_delete "$2"
 	else
-		stderr echo 'USAGE: secret delete <name>'
+		stderr echo 'ERROR: <name> was not found. Refer to usage.'
 		exit 1
 	fi
 elif test "$1" = "get"; then
 	if test -n "$2"; then
 		secret_resolve "${@:2}"
 	else
-		stderr echo 'USAGE: secret get <name...>'
+		stderr echo 'ERROR: <name> was not found. Refer to usage.'
 		exit 1
 	fi
 else
@@ -228,5 +238,4 @@ else
 	stderr echo 'secret get <name>'
 	stderr echo 'secret delete <name>'
 	stderr echo 'secret env <secret...> -- <command> [args...]'
-	exit 1
 fi
