secret: various fixes

diff --git a/.scripts/commands/secret b/.scripts/commands/secret
--- a/.scripts/commands/secret
+++ b/.scripts/commands/secret
@@ -80,17 +80,17 @@ function secret_delete {
 
 function secret_read {
 	key="$1"
-	if secret_exists "$1"; then
+	if secret_exists "$key"; then
 		value="$(sudo cat "$HOME/.scripts/env/secrets/$key" | tr -d '\n')"
 		if is-string "$value"; then
 			echo -n "$value"
 		else
-			stderr echo "ERROR: empty secret: $1"
+			stderr echo "ERROR: cached secret was empty: $key"
 			secret_delete "$key"
 			return 1
 		fi
 	else
-		stderr echo "ERROR: missing secret: $1"
+		stderr echo "ERROR: cached secret was missing: $key"
 		return 1
 	fi
 }
@@ -126,16 +126,18 @@ function secret_signin {
 }
 
 function secret_grab {
+	vault="$1"
+	item="$2"
 	secret_signin
-	result="$(op get item "$2" --vault="$1" --session="$OP_SESSION" || :)"
+	result="$(op get item "$item" --vault="$vault" --session="$OP_SESSION" || :)"
 	if is-empty-string "$result"; then
-		stderr echo "ERROR: Failed to fetch item $2 from vault $1. Nothing was returned."
+		stderr echo "ERROR: Failed to fetch item ${item} from vault ${vault}. Nothing was returned."
 		return 1
 	elif [[ "$result" = *'signed in'* ]]; then
-		stderr echo "ERROR: Failed to fetch item $2 from vault $1. Session expired. Run: secret signin"
+		stderr echo "ERROR: Failed to fetch item ${item} from vault ${vault}. Session expired. Run: secret signin"
 		return 1
 	elif [[ "$result" = *'ERROR'* ]]; then
-		stderr echo "ERROR: Failed to fetch item $2 from vault $1. $result"
+		stderr echo "ERROR: Failed to fetch item ${item} from vault ${vault}. ${result}"
 		return 1
 	else
 		echo -n "$result"
