terminal and gui editors are now configurable
you can now set TERMINAL_EDITORS and GUI_EDITORS in your user configuration to set the preference of your editors

diff --git a/.scripts/commands/setup-editor-commands b/.scripts/commands/setup-editor-commands
--- a/.scripts/commands/setup-editor-commands
+++ b/.scripts/commands/setup-editor-commands
@@ -1,8 +1,13 @@
 #!/usr/bin/env bash
 set -e
+IFS=$'\n' # https://unix.stackexchange.com/q/9496/50703
 
+# User
+source "$HOME/.scripts/sources/user.sh"
+
+# Helpers
 function vset {
-	export $1="$2"  # here so EDITOR $TERMINAL_EDITOR_PROMPT works
+	export "$1"="$2"  # here so EDITOR $TERMINAL_EDITOR_PROMPT works
 	echo "var_set $1 \"$2\";"  # ; needed for fish
 }
 
@@ -11,31 +16,37 @@ if is_empty_string "$LC_CTYPE"; then
 	vset LC_CTYPE 'en_US.UTF-8'
 fi
 
-if command_exists micro; then
-	vset TERMINAL_EDITOR 'micro'
-	vset TERMINAL_EDITOR_PROMPT 'micro'
-elif command_exists nano; then
-	vset TERMINAL_EDITOR 'nano'
-	vset TERMINAL_EDITOR_PROMPT 'nano'
-elif command_exists vim; then
-	vset TERMINAL_EDITOR 'vim'
-	vset TERMINAL_EDITOR_PROMPT 'vim' # --noplugin -c "set nowrap"'
+# Terminal Editor
+if test -z "$TERMINAL_EDITORS"; then
+	(>&2 echo "# cannot set terminal editor, as \$TERMINAL_EDITORS was undefined")
+else
+	for prompt in "${TERMINAL_EDITORS[@]}"; do
+		name="${prompt%% *}"
+		if command_exists "$name"; then
+			vset "TERMINAL_EDITOR" "$name"
+			vset "TERMINAL_EDITOR_PROMPT" "$prompt"
+			break
+		fi
+	done
 fi
 
-if command_exists code; then
-	vset GUI_EDITOR 'code'
-	vset GUI_EDITOR_PROMPT 'code -w'
-elif command_exists atom; then
-	vset GUI_EDITOR 'atom'
-	vset GUI_EDITOR_PROMPT 'atom -w'
-elif command_exists subl; then
-	vset GUI_EDITOR 'subl'
-	vset GUI_EDITOR_PROMPT 'subl -w'
-elif command_exists gedit; then
-	vset GUI_EDITOR 'gedit'
-	vset GUI_EDITOR_PROMPT 'gedit'
+# GUI Editor
+if test -z "$GUI_EDITORS"; then
+	(>&2 echo "# cannot set gui editor, as \$GUI_EDITORS was undefined")
+else
+	for prompt in "${GUI_EDITORS[@]}"; do
+		name="${prompt%% *}"
+		if command_exists "$name"; then
+			vset "GUI_EDITOR" "$name"
+			vset "GUI_EDITOR_PROMPT" "$prompt"
+			break
+		fi
+	done
 fi
 
-# Always use terminal editor for prompts
-# as GUI editors are too slow
-vset EDITOR "$TERMINAL_EDITOR_PROMPT"
+# Always use terminal editor for prompts as GUI editors are too slow
+if test -z "$GUI_EDITORS"; then
+	(>&2 echo "# cannot set editor, as \$TERMINAL_EDITORS was undefined")
+else
+	vset EDITOR "$TERMINAL_EDITOR_PROMPT"
+fi
