rename confirm to confirm-bool, add new confirm command, add new down-zip-file command, update setup-dns for uninstallation as well as for AdGuard Home as primary
Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/.scripts/commands/setup-dns b/.scripts/commands/setup-dns
--- a/.scripts/commands/setup-dns
+++ b/.scripts/commands/setup-dns
@@ -4,6 +4,30 @@ source "$HOME/.scripts/sources/strict.bash"
 # https://developers.cloudflare.com/1.1.1.1/dns-over-https/cloudflared-proxy/
 # https://developers.cloudflare.com/argo-tunnel/downloads/
 
+function aghome_install {
+	if command-exists AdGuardHome; then
+		echo 'adguard home already installed'
+	else
+		down-zip-file "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.101.0/AdGuardHome_MacOS.zip" "AdGuardHome" "$HOME/bin/AdGuardHome"
+		chmod +x "$HOME/bin/AdGuardHome"
+	fi
+}
+
+function aghome_uninstall {
+	ok sudo AdGuardHome -s uninstall
+	ok rm -vi "$HOME/bin/AdGuardHome"*
+}
+
+function aghome_service {
+	ok sudo AdGuardHome -s uninstall
+	sudo AdGuardHome -s install
+	confirm "Press any key once you have completed the AdGuard Home setup..."
+}
+
+function aghome_setup {
+	aghome_install && aghome_service
+}
+
 function cloudflare_install {
 	if command-exists cloudflared; then
 		echo 'cloudflared already installed'
@@ -15,6 +39,22 @@ function cloudflare_install {
 			stderr echo 'installation of cloudflared not yet added for non-macos platforms'
 			return 1
 		fi
+	fi
+}
+
+function cloudflare_uninstall {
+	if command-exists cloudflared; then
+		if is-mac; then
+			ok sudo launchctl stop com.cloudflare.cloudflared
+			ok sudo launchctl remove com.cloudflare.cloudflared
+			ok sudo cloudflared service uninstall
+			ok brew uninstall cloudflare/cloudflare/cloudflared
+		else
+			stderr echo 'uninstallation of cloudflared not yet added for non-macos platforms'
+			return 1
+		fi
+	else
+		echo 'cloudflared already uninstalled'
 	fi
 }
 
@@ -36,19 +76,27 @@ EOF
 	fi
 }
 
-function cloudflare_configured {
+function cloudflare_setup {
+	cloudflare_install && cloudflare_service
+}
+
+function dns_configured {
 	out="$(dig -x google.com)"
 	if echo "$out" | grep ";; SERVER: 127.0.0.1#53(127.0.0.1)"; then
-		echo 'cloudflared is configured and running correctly'
+		echo 'dns is configured and running correctly'
 	else
-		echo 'cloudflared did not appear to be setup correctly'
+		echo 'dns did not appear to be setup correctly'
 		return 1
 	fi
 }
 
-if cloudflare_configured || (cloudflare_install && cloudflare_service && flush-dns 127.0.0.1 && cloudflare_configured); then
-	echo 'dns setup now complete'
+if test "${1:-}" = "uninstall"; then
+	aghome_uninstall
+	cloudflare_uninstall
+	flush-dns 1.1.1.1
+elif dns_configured || (aghome_setup && flush-dns 127.0.0.1 && dns_configured); then
+	echo 'SUCCESS dns setup complete'
 else
 	flush-dns 1.1.1.1
-	echo 'failed to setup dns'
+	echo 'FAILURE dns setup failed'
 fi
