another round of unbound fixes
/ref d38fa39bb463ea200a6ff44a25339a62891596f5

also:

- renames secure_history to secure-history
- adds is-either, is-present, is-neither, is-missing
- removes new-ssh-key as it was a duplicate of ssh-new

diff --git a/.scripts/commands/sparse-vault b/.scripts/commands/sparse-vault
--- a/.scripts/commands/sparse-vault
+++ b/.scripts/commands/sparse-vault
@@ -1,34 +1,36 @@
 #!/usr/bin/env bash
 source "$HOME/.scripts/sources/strict.bash"
 
-if test "$1" = "new" -o "$1" = "create"; then
-	name="$2"
-	size="$3"
-	if test -z "$size"; then
-		stderr echo "sparse-vault new <NAME> <MAXSIZE|100g|1t>"
-		exit 1
-	fi
+action="${1:?"USAGE: sparse-vault <new|open>"}"
+
+if is-either "$action" "new" "create"; then
+	name="${2:?"USAGE: sparse-vault new <NAME> <MAXSIZE|100g|1t> [SPARSE|SPARSEBUNDLE]"}"
+	size="${3:?"USAGE: sparse-vault new <name> <MAXSIZE|100g|1t> [SPARSE|SPARSEBUNDLE]"}"
+	type="${4:-SPARSE}"
+
 	vol=$(basename "$name")
 	version=$(sw_vers -productVersion | awk -F '.' '{print $2}')
+
 	if test "$version" -ge "13"; then
 		fs="APFS"
 	else
 		fs="Journaled HFS+"
 	fi
-	type="SPARSE" # SPARSEBUNDLE
 	if test "$type" = "SPARSE"; then
 		filename="$2.sparseimage"
 	else
 		filename="$2.sparsebundle"
 	fi
+
 	hdiutil create -type "$type" -encryption AES-256 -fs "$fs" -size "$size" -volname "$vol" "$name"
 	hdiutil mount "$filename"
 
-elif test "$1" = "open" -o "$1" = "mount"; then
-	hdiutil compact "$2" || echo "compact failed, continuing..."
-	hdiutil mount "$2"
+elif is-either "$action" "open" "mount"; then
+	path="${2:?"SAGE: sparse-vault open <PATH>"}"
+	hdiutil compact "$path" || echo "compact failed, continuing..."
+	hdiutil mount "$path"
 
 else
-	echo "vault <new|open> <PATH>"
-
+	stderr echo "unknown state"
+	exit 1
 fi
