install/update procedure is now more descriptive of what is happening

diff --git a/.scripts/commands/travis_token b/.scripts/commands/travis_token
--- a/.scripts/commands/travis_token
+++ b/.scripts/commands/travis_token
@@ -1,3 +1,8 @@
 #!/usr/bin/env bash
 
-grep access_token < "$HOME/.travis/config.yml" | sed -E 's/.+: //'
+if is_file "$HOME/.travis/config.yml"; then
+	grep access_token < "$HOME/.travis/config.yml" | sed -E 's/.+: //'
+else
+	echo "$HOME/.travis/config.yml was not found"
+	exit 1
+fi
