fix: trim-audio, setup-git, setup-dns, key
add: ssh-add-all, mac-addr-refresh, mac-addr-new, is-integer, is-float, fail

correct formatting of README

update balupton customisations

Signed-off-by: Benjamin Lupton <b@lupton.cc>

diff --git a/.scripts/commands/trim-audio b/.scripts/commands/trim-audio
--- a/.scripts/commands/trim-audio
+++ b/.scripts/commands/trim-audio
@@ -1,18 +1,36 @@
 #!/usr/bin/env bash
 source "$HOME/.scripts/sources/strict.bash"
 
+usage="USAGE: trim-audio [<audio-stream-to-keep>] ...<input-video-file>"
+
 function convert() {
-	local input="$1"
-	local output="${1%.*}-noaudio.mp4"
+	local stream="$1"
+	local input="${2:?"$usage"}"
+	local extension="${input#*.}"
+	local filename="${input%.*}"
+
+	if test "${stream}" -eq -1; then
+		local output="${filename} [no audio].${extension}"
+	else
+		local output="${filename} [only audio stream ${stream}].${extension}"
+	fi
+
 	rm -f "$output"
 	echo "converting $input to $output"
-	ffmpeg -i "$input" -c copy -an "$output" &>/dev/null && echo "converted  $input to $output" || echo "conversion of $input to $output FAILED"
+
+	if test "${stream}" -eq -1; then
+		(ffmpeg -i "$input" -c copy -an "$output" && echo "trimmed audio from $input to $output") || fail "failed on $input to $output"
+	else
+		(ffmpeg -i "$input" -c copy -map 0:v -map 0:a:"${stream}" "$output" && echo "keep audio stream ${stream} from $input to $output") || fail "failed on $input to $output"
+	fi
 }
 
-if is-empty-string "${1:-}"; then
-	find ./*.264 | while read -r file; do
-		convert "$file"
+if is-integer "${1:?"$usage"}"; then
+	for arg in "${@:2}"; do
+		convert "$1" "$arg"
 	done
 else
-	convert "$1"
+	for arg in "${@:2}"; do
+		convert -1 "$arg"
+	done
 fi
