usesh more useful error

diff --git a/.scripts/commands/usesh b/.scripts/commands/usesh
--- a/.scripts/commands/usesh
+++ b/.scripts/commands/usesh
@@ -5,8 +5,14 @@ if is_empty_string "$1"; then
 	exit 1
 fi
 
+export shell; shell=$(which "$1")
+
+if ! command_exists "$shell"; then
+	echo "ERROR: which for the shell [$1] returned [$shell]"
+	exit 1
+fi
+
 set -e
-export shell; shell=$(which $1)
 
 echo "adding $shell to the standard shells"
 # needed to prevent
