vault now continues with warning if compact fails

diff --git a/.scripts/commands/vault b/.scripts/commands/vault
--- a/.scripts/commands/vault
+++ b/.scripts/commands/vault
@@ -19,7 +19,7 @@ if test "$1" = "new" -o "$1" = "create"; then
 	hdiutil mount "$2.sparsebundle"
 
 elif test "$1" = "open" -o "$1" = "mount"; then
-	hdiutil compact "$2"
+	hdiutil compact "$2" || echo "compact failed, continuing..."
 	hdiutil mount "$2"
 
 else
