boundation-upgrade: make sure all commans are authed, and add fallback for when npm owner add fails

diff --git a/.scripts/users/balupton/commands/boundation-upgrade b/.scripts/users/balupton/commands/boundation-upgrade
--- a/.scripts/users/balupton/commands/boundation-upgrade
+++ b/.scripts/users/balupton/commands/boundation-upgrade
@@ -61,11 +61,15 @@ fi
 
 # prepare
 npm i
-secret env GITHUB_CLIENT_ID GITHUB_CLIENT_SECRET -- npm run our:release:prepare
+github-prepare
 
 # release
 ok git rm -rf docs
 git add .
 git commit -am "$v - boundation, changelog, version bump"
-npm owner add bevryme
-secret env GITHUB_CLIENT_ID GITHUB_CLIENT_SECRET -- npm run our:release
+if ! npm owner add bevryme; then
+	echo 'adding npm owner failed, trying again in two minutes'
+	sleep 2m
+	npm owner add bevryme
+fi
+github-release
