ci: use WSL over MSYS for Windows CI
Squashes:
8a898fe
d0edacf
c495ab9
45cfc76
b904a90
56c9d10
6a8ad9a
e88811c
0339935
2abfe3f
5ae4a12
4ffb782
b7a115c
a510716
1961e05
e2333c2
9cf3eb3
a571971
0946a88
3275903
c771517
50135dd
72c8966
e9db5c9
009a4f5
ea78bc9
691ff35
2b55771
97ab5ba
791c362
d5075aa
c608db5
59b7f02
cd6422c
3125959
321544c
7dc18cf
19c70f5
05c4fca
e23aa4c
790cc5f
cef23d4
8391645

diff --git a/.github/workflows/dorothy-workflow.yml b/.github/workflows/dorothy-workflow.yml
--- a/.github/workflows/dorothy-workflow.yml
+++ b/.github/workflows/dorothy-workflow.yml
@@ -117,6 +117,7 @@ jobs:
           EGITHUB
   login-shells:
     needs: setup
+    # if: false
     runs-on: ubuntu-latest
     steps:
       - name: "Dorothy Install"
@@ -181,6 +182,7 @@ jobs:
           echo-style --success='ok'
   check:
     needs: setup
+    # if: false
     runs-on: ubuntu-latest
     steps:
       - name: "Dorothy Check"
@@ -192,6 +194,7 @@ jobs:
           bash -c "$(curl -fsSL 'https://dorothy.bevry.me/check?slug=${{ needs.setup.outputs.SLUG }}&commit=${{ needs.setup.outputs.COMMIT }}')"
   format:
     needs: setup
+    # if: false
     if: github.event_name == 'push'
     runs-on: ubuntu-latest
     steps:
@@ -217,6 +220,7 @@ jobs:
           fi
   macos-test:
     needs: setup
+    # if: false
     strategy:
       fail-fast: false
       matrix:
@@ -252,25 +256,47 @@ jobs:
           SLUG: ${{ needs.setup.outputs.SLUG }}
           COMMIT: ${{ needs.setup.outputs.COMMIT }}
           COMMAND: "dorothy test --bash=${{ matrix.bash }}"
-  windows-test:
+  windows-wsl-test:
     needs: setup
-    strategy:
-      fail-fast: false
-      matrix:
-        runner:
-          - windows-2025
-          - windows-2022
-          # - windows-11-arm <-- deno doesn't yet support windows arm
-    runs-on: ${{ matrix.runner }}
+    # if: false
+    runs-on: windows-2025
     steps:
+      - name: "WSL Install"
+        shell: powershell
+        env:
+          WSL_DISTRO: Debian # __evict on msys is 2255 secnds, on WSL Debian is 365 seconds, on WSL kali-linux is 367 seconds
+        run: |
+          $ErrorActionPreference = "Stop"
+          wsl.exe --set-default-version 2
+          wsl.exe --install --no-launch --web-download $Env:WSL_DISTRO
+          wsl.exe --set-default $Env:WSL_DISTRO
+          wsl.exe --list --verbose
+          wsl.exe -- sudo apt-get update
+          wsl.exe -- sudo apt-get -y install git curl
       - name: "Dorothy Test"
-        uses: bevry/dorothy/.github/actions/dorothy-test@master
-        with:
-          GITHUB_TOKEN: ${{ secrets.READONLY_GITHUB_TOKEN }}
-          SLUG: ${{ needs.setup.outputs.SLUG }}
-          COMMIT: ${{ needs.setup.outputs.COMMIT }}
+        env:
+          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
+          WSL_SCRIPT: bash -c "$(curl -fsSL "https://dorothy.bevry.me/test?slug=${{ needs.setup.outputs.SLUG }}&commit=${{ needs.setup.outputs.COMMIT }}")"
+        shell: powershell
+        run: |
+          # `GITHUB_STEP_SUMMARY` is on a different partition, that WSL cannot access, so proxy it
+          $summaryHost = $Env:GITHUB_STEP_SUMMARY
+          $summaryFile = "summary.txt"
+          $summaryWSL = wsl.exe -- wslpath -au $summaryFile
+          # Write the script
+          Set-Content -Path script.sh -NoNewline -Value $Env:WSL_SCRIPT
+          # Execute the script, with appropriate ENV varrs, and with some `setsid` magic so that WSL isn't interactive and TTY attached
+          wsl.exe -- env GITHUB_TOKEN=$Env:GITHUB_TOKEN CI=true GITHUB_ACTIONS=$Env:GITHUB_ACTIONS GITHUB_STEP_SUMMARY=$summaryWSL bash -eo pipefail -c '(setsid ./script.sh) </dev/null |& cat'
+          $scriptExitStatus = $LastExitCode
+          # Append `GITHUB_STEP_SUMMARY` with the WSL generated summary
+          Add-Content -Path $summaryHost -Value (Get-Content -Path $summaryFile)
+          # Report and fail with the script's exit status
+          # Note a GitHub Actions bug converges PowerShell non-zero exit statuses to 1: https://github.com/actions/runner/issues/351
+          Write-Host "Script Exit Status: $scriptExitStatus"
+          Exit($scriptExitStatus)
   bash-versions-test:
     needs: setup
+    # if: false
     strategy:
       fail-fast: false
       matrix:
@@ -298,6 +324,7 @@ jobs:
           COMMAND: "dorothy test --bash=${{ matrix.bash }}"
   containers-x86-test:
     needs: setup
+    # if: false
     strategy:
       fail-fast: false
       matrix:
@@ -332,6 +359,7 @@ jobs:
           COMMIT: ${{ needs.setup.outputs.COMMIT }}
   containers-arm-test:
     needs: setup
+    # if: false
     strategy:
       fail-fast: false
       matrix:
