ci/readkey: make input/output checks consistent

diff --git a/.github/workflows/dorothy-workflow.yml b/.github/workflows/dorothy-workflow.yml
--- a/.github/workflows/dorothy-workflow.yml
+++ b/.github/workflows/dorothy-workflow.yml
@@ -53,14 +53,14 @@ jobs:
         shell: bash
         run: |
           # test input/output availability
-          (: </dev/stdin || print_line 'cannot read stdin')
-          (: >/dev/stdin || print_line 'cannot write stdin')
-          (: </dev/stdout || print_line 'cannot read stdout')
-          (: >/dev/stdout || print_line 'cannot write stdout')
-          (: </dev/stderr || print_line 'cannot read stderr')
-          (: >/dev/stderr || print_line 'cannot write stderr')
-          (: </dev/tty || print_line 'cannot read tty')
-          (: >/dev/tty || print_line 'cannot write tty')
+          (: </dev/stdin || printf '%s\n' 'cannot read stdin') || :
+          (: >/dev/stdin || printf '%s\n' 'cannot write stdin') || :
+          (: </dev/stdout || printf '%s\n' 'cannot read stdout') || :
+          (: >/dev/stdout || printf '%s\n' 'cannot write stdout') || :
+          (: </dev/stderr || printf '%s\n' 'cannot read stderr') || :
+          (: >/dev/stderr || printf '%s\n' 'cannot write stderr') || :
+          (: </dev/tty || printf '%s\n' 'cannot read tty') || :
+          (: >/dev/tty || printf '%s\n' 'cannot write tty') || :
           # test read-key failure without any possible interference
           book='' status=0
           status=0 && read -sN1 -t 1 book || status=$?
@@ -150,14 +150,14 @@ jobs:
         # shell: 'script -q -e -c "bash {0}"'
         run: |
           # test input/output availability
-          (: </dev/stdin || print_line 'cannot read stdin')
-          (: >/dev/stdin || print_line 'cannot write stdin')
-          (: </dev/stdout || print_line 'cannot read stdout')
-          (: >/dev/stdout || print_line 'cannot write stdout')
-          (: </dev/stderr || print_line 'cannot read stderr')
-          (: >/dev/stderr || print_line 'cannot write stderr')
-          (: </dev/tty || print_line 'cannot read tty')
-          (: >/dev/tty || print_line 'cannot write tty')
+          (: </dev/stdin || printf '%s\n' 'cannot read stdin') || :
+          (: >/dev/stdin || printf '%s\n' 'cannot write stdin') || :
+          (: </dev/stdout || printf '%s\n' 'cannot read stdout') || :
+          (: >/dev/stdout || printf '%s\n' 'cannot write stdout') || :
+          (: </dev/stderr || printf '%s\n' 'cannot read stderr') || :
+          (: >/dev/stderr || printf '%s\n' 'cannot write stderr') || :
+          (: </dev/tty || printf '%s\n' 'cannot read tty') || :
+          (: >/dev/tty || printf '%s\n' 'cannot write tty') || :
           # test read-key failure without any possible interference
           book='' status=0
           status=0 && read -sN1 -t 1 book || status=$?
