ci: refinements to WSL flow
use a script path and use hashbang to ensure correct execution

add comment noting that `$Host.SetShouldExit($scriptExitStatus)` works around https://github.com/actions/runner/issues/351

diff --git a/.github/workflows/dorothy-workflow.yml b/.github/workflows/dorothy-workflow.yml
--- a/.github/workflows/dorothy-workflow.yml
+++ b/.github/workflows/dorothy-workflow.yml
@@ -279,7 +279,9 @@ jobs:
       - name: "Dorothy Test"
         env:
           GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
-          WSL_SCRIPT: bash -c "$(curl -fsSL "https://dorothy.bevry.me/test?slug=${{ needs.setup.outputs.SLUG }}&commit=${{ needs.setup.outputs.COMMIT }}")"
+          WSL_SCRIPT: |
+            #!/usr/bin/env bash
+            bash -c "$(curl -fsSL "https://dorothy.bevry.me/test?slug=${{ needs.setup.outputs.SLUG }}&commit=${{ needs.setup.outputs.COMMIT }}")"
         shell: powershell
         run: |
           # `GITHUB_STEP_SUMMARY` is on a different partition, that WSL cannot access, so proxy it
@@ -287,16 +289,15 @@ jobs:
           $summaryFile = "summary.txt"
           $summaryWSL = wsl.exe -- wslpath -au $summaryFile
           # Write the script
-          Set-Content -Path script.sh -NoNewline -Value $Env:WSL_SCRIPT
+          $scriptPath = './script'
+          Set-Content -Path $scriptPath -NoNewline -Value $Env:WSL_SCRIPT
           # Execute the script, with appropriate ENV varrs, and with some `setsid` magic so that WSL isn't interactive and TTY attached
-          wsl.exe -- env GITHUB_TOKEN=$Env:GITHUB_TOKEN CI=true GITHUB_ACTIONS=$Env:GITHUB_ACTIONS GITHUB_STEP_SUMMARY=$summaryWSL bash -eo pipefail -c '(setsid ./script.sh) </dev/null |& cat'
+          wsl.exe -- env GITHUB_TOKEN=$Env:GITHUB_TOKEN CI=true GITHUB_ACTIONS=$Env:GITHUB_ACTIONS GITHUB_STEP_SUMMARY=$summaryWSL bash -eo pipefail -c '(setsid $scriptPath) </dev/null |& cat'
           $scriptExitStatus = $LastExitCode
           # Append `GITHUB_STEP_SUMMARY` with the WSL generated summary
           Add-Content -Path $summaryHost -Value (Get-Content -Path $summaryFile)
           # Report and fail with the script's exit status
-          # Note a GitHub Actions bug converges PowerShell non-zero exit statuses to 1: https://github.com/actions/runner/issues/351
-          Write-Host "Script Exit Status: $scriptExitStatus"
-          $Host.SetShouldExit($scriptExitStatus)
+          $Host.SetShouldExit($scriptExitStatus) # This works around https://github.com/actions/runner/issues/351 and has GitHub Actions report the correct exit status
           Exit($scriptExitStatus)
   bash-versions-test:
     needs: setup
