ci: check the read failure in the workflow file
as that won't have any intereference

the read failure is that it should timeout with 142 or 60, but it is timing out on CI with 1

diff --git a/.github/workflows/dorothy-workflow.yml b/.github/workflows/dorothy-workflow.yml
--- a/.github/workflows/dorothy-workflow.yml
+++ b/.github/workflows/dorothy-workflow.yml
@@ -52,6 +52,12 @@ jobs:
         if: github.event_name == 'push'
         shell: bash
         run: |
+          # test read-key failure without any possible interference
+          book='' status=0
+          status=0 && read -sN1 -t 1 book || status=$?
+          printf '%s\n' "read-key v4 status [$status] and read [$book]"
+          status=0 && IFS= read -sn1 -t 1 book || status=$?
+          printf '%s\n' "read-key v3 status [$status] and read [$book]"
           # source dorothy
           DOROTHY_LOAD=yes
           DOROTHY_LOADED=no
@@ -134,4 +140,10 @@ jobs:
       - name: 'Dorothy Remote Tests'
         # shell: 'script -q -e -c "bash {0}"'
         run: |
+          # test read-key failure without any possible interference
+          book='' status=0
+          status=0 && read -sN1 -t 1 book || status=$?
+          printf '%s\n' "read-key v4 status [$status] and read [$book]"
+          status=0 && IFS= read -sn1 -t 1 book || status=$?
+          printf '%s\n' "read-key v3 status [$status] and read [$book]"
           bash -ic "$(curl -fsSL 'https://dorothy.bevry.me/run?branch=${{ github.ref_name }}&commit=${{ github.sha }}')" -- dorothy test
